### ISSUE TITLE
Anchore-cli import feature

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1001]
### Issue Type 
- [ ] Bug
- [x] Enhancement

### Description
It would be great to be able to import `anchore-cli`'s json output into DefectDojo.

**Comment by devGregA** [comment]
@madchap would you please supply a sample scan? This is something I can give to the interns in a couple weeks.

**Comment by madchap** [comment]
Hi @devEricA 

Here it is. However, looking at the parser.py for Anchore-engine (which I had not seen 0_o), this seems to be it. Bombing with a 500 error though right now, haven't had time to investigate or check anything.

I see there is one also uploaded here by @jaguasch: https://github.com/DefectDojo/sample-scan-files/tree/master/anchore-engine . My file is also a 0.3.3 version.

[anchore_v0.3.3_openjdk-11.0.3-jdk-stretch.json.txt](https://github.com/DefectDojo/django-DefectDojo/files/3093257/anchore_v0.3.3_openjdk-11.0.3-jdk-stretch.json.txt)

So, I think I can close this anyways. I will test some more why I am getting a 500 error when ingesting my file, and open up a bug if I can reproduce.

That being said, I will see if I can provide you with something else (i.e. Twistlock?) so that we can beef up the ingestion capabilities!
