### ISSUE TITLE
docker-compose restart loses all system settings

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1003]
Please use the following template when submitting issues: (If this is a security issue, then review the [disclosure policy](https://github.com/DefectDojo/django-DefectDojo/blob/master/SECURITY.md) and submit via our security reporting program.

### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description
If you modify system settings, then `docker-compose restart`, all changes are gone.

### Operating System 
Please include the version number (ex: Ubuntu 16.04)
Ubuntu 18.04

### Install

- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

### DefectDojo Version
1.5.4

### Steps to Reproduce
* Run a `docker-compose up`
* Do changes in system settings as admin, i.e. tick boxes
* Run a `docker-compose restart`
* Log back in, go to system settings, and notice customized settings are gone.

**Comment by aaronweaver** [comment]
Hi @madchap - Looks like we need to add a datavolume for mysql - would you mind trying that out?

```
volumes:
      - dojomysql-datavolume:/var/lib/mysql
volumes:
  dojomysql-datavolume:
```

**Comment by madchap** [comment]
One interesting thing possibly. I configured the slack stuff, then restarted. As expected, upon restart, all blank.

However, looking in the logs I saw this happening upon engagement added (which is ticked to send a slack notif):

```
uwsgi_1         | Starting new HTTPS connection (1): slack.com:443
uwsgi_1         | https://slack.com:443 "POST /api/chat.postMessage HTTP/1.1" 200 53
```

Even though that showed up in the log, I got nothing in Slack (which I had tested previously with the legacy token and worked).

**Comment by madchap** [comment]
This fixes it. Do you want me to submit a PR, or you want to care of it yourself?

**Comment by madchap** [comment]
So apparently not fixing it. Here are the steps I took.

- Modified the docker-compose.yml as mentioned.
- Created named volume for mysql
- Copied the unnamed volume mysql data out to the named volume (just in case, don't know what's in there yet)
- `docker-compose stop` and `rm` and then `up`.
- The mysql container uses the bind mount as instructed:
```
$ sudo docker inspect --format "{{.Mounts}}" django-defectdojo_mysql_1

[{volume django-defectdojo_dojomysql-datavolume /var/lib/docker/volumes/django-defectdojo_dojomysql-datavolume/_data /var/lib/mysql local rw true }]
```

- Using chrome incognito, logged in, made some changes to system config
- `docker-compose restart`
- refreshed, no settings saved.

**Comment by madchap** [comment]
So, it is a bug rather than an enhancement I am afraid.

Upon docker-compose restart, the initializer container resets the table -- l.45 of file `entrypoint-initializer.sh`, pointing to system_settings.json. Commenting that line out, the values remain.

The volume to the mysql is a nice to have, but has nothing to do with it.

**Comment by madchap** [comment]
A quick workaround is to add this variable to the `docker-compose.xml` for the `initializer` stanza's environment:

```
DD_INITIALIZE: "false"
```

and benefit from @hendrikhalkow's change from a month ago for his k8s work. Initialization is then skipped, and the database tables left alone.

**Comment by aaronweaver** [comment]
I added that earlier this afternoon to [Docker.md](https://github.com/DefectDojo/django-DefectDojo/blob/dev/DOCKER.md) and made a couple small changes to the docker compose file. I have one small change to make to settings to enable better development.

Also will make a change in the intializer to detect if init has been run.

`export DD_INITIALIZE=false`

**Comment by hendrikhalkow** [comment]
That's exactly the reason why `DD_INITIALIZE` is there. I should have documented it ;) However, I think we should make the initialize container smarter so that it can run on every startup.
