### ISSUE TITLE
Progpilot SAST integration 

### ISSUE THREAD

**Issue by nAgga3** [DefectDojo/django-DefectDojo#10044]
Hello community, I would like to be able to request the following tool to be added to DefectDojo

**Progpilot**
Progpilot is a static analysis tool for PHP that detects security vulnerabilities such as XSS and SQL injection. Not only these types of findings, but the tool is very customizable.

https://github.com/designsecurity/progpilot

**Sample File**
[progpilot.json](https://github.com/DefectDojo/django-DefectDojo/files/15133915/progpilot.json)

Thanks

**Comment by manuel-sommer** [comment]
Hi @nAgga3,

did you upload the sample file to the semgrep parser of DefectDojo?

**Comment by nAgga3** [comment]
Oh @manuel-sommer thanks for your notice.

I updated it

**Comment by manuel-sommer** [comment]
@mtesauro, I don't know if it makes sense to implement this parser if semgrep is supported as the output. Did you try to parse the semgrep output with the Semgrep parser @nAgga3 ?

**Comment by mtesauro** [comment]
@manuel-sommer I poked around the Github repo and .md docs for this took and didn't find the output as matching semgrep. Where did you find that info?

**Comment by manuel-sommer** [comment]
He had a semgrep outputfile and then removed it and uploaded a parser specific one

**Comment by mtesauro** [comment]
@manuel-sommer Ahh, that explains it.  If there's a tool-specific JSON format, it's probably worth doing a parser for it.

**Comment by nAgga3** [comment]
Hello! yes, I was wrong but I reuploaded the file with the json output belonging to Progpilot.  

Sorry @mtesauro and @manuel-sommer if I create confusion with my mistake, I apologize.

Would it be possible in this case to create a parser for Progpilot?

**Comment by manuel-sommer** [comment]
I started a PR @nAgga3.

**Comment by manuel-sommer** [comment]
@nAgga3 could you provide more sample scans?

**Comment by manuel-sommer** [comment]
I finished the PR @nAgga3 and I would like to have a little more scandata to sufficiently test it.

**Comment by nAgga3** [comment]
Hello, @manuel-sommer sorry for the delay. 

[progpilot2.json](https://github.com/DefectDojo/django-DefectDojo/files/15150141/progpilot2.json)
[progpilot3.json](https://github.com/DefectDojo/django-DefectDojo/files/15150142/progpilot3.json)
[progpilot.json](https://github.com/DefectDojo/django-DefectDojo/files/15150149/progpilot.json)

If you need more let me know, thank you very much.

**Comment by nAgga3** [comment]
@manuel-sommer hello, Was the scan data enough to be able to test the parser?

**Comment by manuel-sommer** [comment]
Yeah thank you! Take a look at the PR

**Comment by nAgga3** [comment]
Thanks a lot @manuel-sommer  !!!

**Comment by mtesauro** [comment]
Closing this since the PR is merged

**Comment by nAgga3** [comment]
Sorry for coming back to this topic.
 
We were testing the Progpilot import but there is a little bug between two types of vulnerabilities. Should I open an issue? @manuel-sommer

**Comment by manuel-sommer** [comment]
Yes, please, or share here, I will submit a PR to fix it today

**Comment by nAgga3** [comment]
Okey, the parser fails when trying to match the vulnerabilities of "vuln_name": "security misconfiguration",

Apparently it doesn't take the start of the keys correctly. This produces two things: only one vulnerability is taken or part of the previous vulnerability is reflected in the next vulnerability.
For example, taking progpilot.json, the parser obtains this data incorrectly.

Using this JSON output : [progpilot.json](https://github.com/DefectDojo/django-DefectDojo/files/15276518/progpilot.json)

![Security miscronfiguration](https://github.com/DefectDojo/django-DefectDojo/assets/105750469/3063f465-e6b8-4ecf-9454-827760fb9b59)
![SQLI](https://github.com/DefectDojo/django-DefectDojo/assets/105750469/ae3a089c-a6cc-4be3-ad9e-bd8148f40a12)

I think that the structure of the "security misconfiguration" type vulnerabilities is what is causing the problem because the structure is different from XSS and SQLI @manuel-sommer

**Comment by nAgga3** [comment]
@manuel-sommer . You could see it? Thank you

**Comment by manuel-sommer** [comment]
See my fix @nAgga3

**Comment by nAgga3** [comment]
Awesome @manuel-sommer , thanks for all!!
