### ISSUE TITLE
error in python with linux rocky v9

### ISSUE THREAD

**Issue by johnfelipe** [DefectDojo/django-DefectDojo#10063]
[furrego@trilliant.local@nc-sw-keycloaktest01 ~]$ cat /etc/*release
	NAME="Rocky Linux"
	VERSION="9.3 (Blue Onyx)"
	ID="rocky"
	ID_LIKE="rhel centos fedora"
	VERSION_ID="9.3"
	PLATFORM_ID="platform:el9"
	PRETTY_NAME="Rocky Linux 9.3 (Blue Onyx)"
	ANSI_COLOR="0;32"
	LOGO="fedora-logo-icon"
	CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
	HOME_URL="https://rockylinux.org/"
	BUG_REPORT_URL="https://bugs.rockylinux.org/"
	SUPPORT_END="2032-05-31"
	ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
	ROCKY_SUPPORT_PRODUCT_VERSION="9.3"
	REDHAT_SUPPORT_PRODUCT="Rocky Linux"
	REDHAT_SUPPORT_PRODUCT_VERSION="9.3"
	Rocky Linux release 9.3 (Blue Onyx)
	Rocky Linux release 9.3 (Blue Onyx)
	Rocky Linux release 9.3 (Blue Onyx)

next

    docker --version
    
    Docker version 26.0.2, build 3c863ff

next

    docker compose version
    
    Docker Compose version v2.26.1

im in not sudo user

    [root@nc-sw-keycloaktest01 furrego]# pwd
    /home/trilliant.local/furrego

and this is error today 29/04/2024

    [furrego@trilliant.local@nc-sw-keycloaktest01 django-DefectDojo]$ sudo ./dc-build.sh
    [sudo] password for furrego@trilliant.local:
    Checking docker compose version
    Supported docker compose version
    Building docker compose
    [+] Building 4.3s (2/2) FINISHED                                 docker:default
     => [uwsgi internal] load build definition from Dockerfile.django-debian   1.7s
     => => transferring dockerfile: 4.83kB                                     0.0s
     => ERROR [uwsgi internal] load metadata for docker.io/library/python:3.1  1.0s
    ------
     > [uwsgi internal] load metadata for docker.io/library/python:3.11.4-slim-bullseye@sha256:40319d0a897896e746edf877783ef39685d44e90e1e6de8d964d0382df0d4952:
    ------
    failed to solve: python:3.11.4-slim-bullseye@sha256:40319d0a897896e746edf877783ef39685d44e90e1e6de8d964d0382df0d4952: failed to resolve source metadata for docker.io/library/python:3.11.4-slim-bullseye@sha256:40319d0a897896e746edf877783ef39685d44e90e1e6de8d964d0382df0d4952: failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/python/manifests/sha256:40319d0a897896e746edf877783ef39685d44e90e1e6de8d964d0382df0d4952: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

how can solve this?

**Comment by mtesauro** [comment]
Look at the error message:
> 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit.

Nothing to solve but to wait until that resource is no longer rate limited.
