### ISSUE TITLE
HCL appscan issue / An exception error occurred during the report import:argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by johnfelipe** [DefectDojo/django-DefectDojo#10074]
![SNAG-0225](https://github.com/DefectDojo/django-DefectDojo/assets/428820/d0fdc226-89e6-4d9e-b03d-b23c98de715f)

HCL version

![SNAG-0226](https://github.com/DefectDojo/django-DefectDojo/assets/428820/bc4a4863-f2f8-4f55-b873-2f3623c98906)

export like this:

![SNAG-0227](https://github.com/DefectDojo/django-DefectDojo/assets/428820/be8edfc2-3bf8-44b4-8852-7c7694bf7187)

issue show like this:

*An exception error occurred during the report import:argument of type 'NoneType' is not iterable*

view video:

https://github.com/DefectDojo/django-DefectDojo/assets/428820/b9197936-00c5-42f6-9c56-89dd0908a006

**Comment by manuel-sommer** [comment]
Could you please add an outputfile, then I will make a PR

**Comment by johnfelipe** [comment]
where can review or download that outputfile?

**Comment by manuel-sommer** [comment]
Can you please Download the XML from your HCL appscan, anonymize critical values and upload that file to this issue here. Then, I can easily reproduce and fix it.

**Comment by johnfelipe** [comment]
how can anonymize critical values, because that xml have critical and privacy data, tell me witch nodes in xml file need to be replace or delete?

**Comment by johnfelipe** [comment]
xml file have 123325 lines, is a big xml file

**Comment by manuel-sommer** [comment]
Please take a look yourself which data you need to anonymize to not expose critical data.

**Comment by manuel-sommer** [comment]
You can shorten it. I have done it in the past also for other unittest files

**Comment by johnfelipe** [comment]
can u give me your gmail account or something more private, i will send all
file only for test and PR aproach

**Comment by manuel-sommer** [comment]
I am sorry, I will not share my private email address here. Can you either post a file to reproduce it or the exact error (see container logs)

**Comment by johnfelipe** [comment]
Send me a post email to  ***@***.***

And I will send XML file for HCL and snn for Invictus

Tnks

**Comment by johnfelipe** [comment]
Pls Review my GitHub profile and send me an email to Gmail share there

**Comment by manuel-sommer** [comment]
Hi @johnfelipe. 
Let me get more clear here. You have these options:

- You can upload the file directly to this issue or share here a link to access this file. I will then make a PR and fix the issue. However, I will NOT anonymize any data within the file and use the file as it is within a unittest.
- You can ask the official DefectDojo support https://defectdojo.com/pricing for help.
- You can do a PR yourself.
- You can ask somebody else to fix it. 

I will not:
- ... write you an email to get the sample scan file.
- ... reproduce the issue myself as I don't have access to HCL.
- ... anonymize any data within a provided sample file.
 
I hope this helps to clarify responsibilities.

Best,

Manuel

**Comment by johnfelipe** [comment]
[PrimeRead30042024 - copia.zip](https://github.com/DefectDojo/django-DefectDojo/files/15190671/PrimeRead30042024.-.copia.zip)

ok all nodes is CENSURED, can you use and create a PR with fixes

**Comment by johnfelipe** [comment]
When can update, and retry?

**Comment by johnfelipe** [comment]
is already updated but is not good with tittle and other things, i will open new issue

![SNAG-0253](https://github.com/DefectDojo/django-DefectDojo/assets/428820/a8c8a8b2-4d0e-40d6-b939-7ed62feed847)

i think is not parse all xml file
![SNAG-0254](https://github.com/DefectDojo/django-DefectDojo/assets/428820/055c98dc-6e46-427f-ba93-156861f4e3f9)
