### ISSUE TITLE
Project vulnerabilities count is not deduplicated

### ISSUE THREAD

**Issue by acherifi** [DefectDojo/django-DefectDojo#10081]
**Problem description**

Hello, we want to use defectdojo to manage our vulneratibilities. We want a clear understanding of which vulnerabilities affect our code in our various branches. The case is the following. We have multiple products in DefectDojo that reflect the code we are producing internally (AppA, AppB, etc.). Next we use the Engagement feature to create an engagement for every dev branch that has a merge request active and also an other branch for our Production environment (All of that is done through CI/CD). Tests are then run and sent to the corresponding engagements through CI. 

Now we have the following in defectDofo:
```
|-Product AppA
|--- Engagement feature/my-feature
|------ Test from CI
|--- Engagement Production 
|------ Test from CI
|--- Engagement feature/other-feature
|------ Test from CI
```
We know that AppA has 64 vulnerabilities which are correctly identified for each engagement. However the Product overview states that we have 192 vulnerabilities which is mathematically correct by technically not correct. We still have 64 vulnerabilities just duplicated across multiples branches. 

We enabled deduplication at the engagement level. We tried to enable deduplication on a product level but doing so makes a vulnerability disappear from all the engagement if it is fixed in one of them which is not true. The vulnerability might be patched in _feature/other-feature_ but not in _production_.

Is there any way to "deduplicate" the vulnerabilities count in order to only have the unique ones ? This way we can have correct and usable metrics for a given product.

*I am not saying that this is a bug but maybe a misconfiguration on our side. I am searching a way to reach our desired goal.*

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Kubernetes
 - DefectDojo version (see footer) or commit message: 2.33.7

![image](https://github.com/DefectDojo/django-DefectDojo/assets/19311305/c20e9762-94e3-4d8a-a691-79fd04381d5f)

**Comment by mtesauro** [comment]
If you're going to use the engagements as place where each branch lives, then you'd also need to do reporting at the engagement level.

You can pull engagement level reports or do finding filtering by engagements in multiple places in DefectDojo and for how you've described, that would be were you should look at the metrics you want.

FWIW, I've seen several others do exactly what you're doing with branches so that's not a 'wrong' choice.

**Comment by acherifi** [comment]
Thank you for your answer. We will then proceed by generating reports at  the engagement level.
