### ISSUE TITLE
HTTP 404 for static file fullcalendar.min.js, yarn dependency range not correct

### ISSUE THREAD

**Issue by Ravenons** [DefectDojo/django-DefectDojo#1011]
**Bug description**
Frontend is getting HTTP 404 when trying to load _/static/fullcalendar/dist/fullcalendar.min.js_, basically because version in _package.json_ is "*", which installs recently released version 4 of the dependency, and that file is not there anymore. I solved it by specifying version "3" and installing the package again, which installs version "3.10.0" and solves the issue. I'm not submitting a PR for this, because I'm no expert on it and somebody may like to review dependencies for additional wildcards (I would say that's a bad practise)".

**Steps to reproduce**
1. Install DefectDojo
2. Open Network tab in Developer Tools in your favourite web browser
3. Open DefectDojo and observe HTTP 404 for the specified file

**Expected behavior**
HTTP 200 for the specified file

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [X] setup.bash / **legacy-setup.bash**

**Environment information**
 - Operating System: Debian 9.8 (stretch)
 - DefectDojo version: cce0532: Merge pull request #856 from devGregA/master [2019-01-28 10:29:22 -0600]

**Comment by dragos-sh** [comment]
:+1: 

Got the same: 

```
nginx_1         | 2019/06/28 07:15:01 [error] 6#6: *39 open() "/usr/share/nginx/html/static/fullcalendar/dist/fullcalendar.min.js" failed (2: No such file or directory), client: <client_ip>, server: , request: "GET /static/fullcalendar/dist/fullcalendar.min.js HTTP/1.1", host: "defect-dojo-[]", referrer: "https://defect-dojo-[]com/login?next=/"
```

**Comment by Maffooch** [comment]
@dragos-sh Are you still having this issue on the current dev branch?

**Comment by dragos-sh** [comment]
@Maffooch Hi, I am seeing this message while I am using the version from the **master** branch. Thank you.

**Comment by Maffooch** [comment]
@dragos-sh Good deal. Not sure when that fix will make it to master branch, but it is currently in the dev branch. Thank you for confirming!
