### ISSUE TITLE
Improve App loading to reduce Kubernetes liveness/readiness error

### ISSUE THREAD

**Issue by sebglon** [DefectDojo/django-DefectDojo#10137]
**Is your feature request related to a problem? Please describe**
We need to improve the Django app loading to make deployments less disruptive

[here](https://simon-ninon.medium.com/making-django-deployments-less-disruptive-5ace190f6d8e) is a blog post that we already have implemented on another Django app

**Describe the solution you'd like**
On the `wsgi.py` add a call to the Django URL resolver to force the django loading before than wsgi start listening http requests.

Example of code: 
```
get_resolver(ROOT_URLCONF).url_patterns
```

**Comment by kiblik** [comment]
@mtesauro, this issue can be closed. Thank you
