### ISSUE TITLE
Deduplication of issues happens if all endpoints match ignoring everything else

### ISSUE THREAD

**Issue by adracea** [DefectDojo/django-DefectDojo#1013]
**Bug description**
deduplication_on_engagement deduplicates issues if all endpoints match ignoring everything else including hash , severity , etc.
**Steps to reproduce**
1. Create an engagement with deduplication_on_engagement enabled
2. Add one issue with high severity and a name set endpoint to `http://test.com/test.php` , another one with low severity and a different name but the same endpoint .
3.Trigger deduplication
High Issue gets deduplicated down into the low one . 

**Expected behavior**
Issues are both unique as only the locations where they happen is the same .
**Deployment method** *(select with an `X`)*
- [X] Docker
- [ ] Kubernetes
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 18.04
 - DefectDojo version: 5908433: Merge pull request #1006 from valentijnscholten/pr/1002-make-deduplication-work-with-skip-duplicates [2019-04-03 20:32:32 -0500]

**Screenshots** (optional)
![image](https://user-images.githubusercontent.com/6214663/55574046-184a5d80-5714-11e9-85f9-6fbd1d1a0cdb.png)

**Comment by adracea** [comment]
The behavior of this seems to be rather inconsistent as importing a Burp Report doesn't seem to cause this issue to trigger , but manual findings seems to be triggering this all the time .

**Comment by adracea** [comment]
The root cause seems to be the fact that manually creating findings doesn't compute the hash codes

**Comment by adracea** [comment]
https://github.com/DefectDojo/django-DefectDojo/blob/6e18f3a92ff0a28b57f61e63ae04a441f3130a81/dojo/models.py#L1229

Seems to be the culprit , in my test I've moved it to line 1236 , under the `if/else` snippet and the deduplication seems fixed .
@aaronweaver any suggestions if this would be the right approach ?

**Comment by aaronweaver** [comment]
@devGregA Can you take a look?

**Comment by valentijnscholten** [comment]
Hi @adracea wasn't this fixed by #1043  ?

**Comment by adracea** [comment]
@valentijnscholten should have been but I wanted more than just my confirmation

**Comment by Maffooch** [comment]
Confirmed that this has been fixed at some point. Not sure when though.
