### ISSUE TITLE
How to add products and findings via api?

### ISSUE THREAD

**Issue by Lax-Asuna** [DefectDojo/django-DefectDojo#10135]
It seems that I can't add products or findings via the api interface in the api documentation provided.
So can I add them through the API? Or do I  need to implement it by my own? Thanks!

![image](https://github.com/DefectDojo/django-DefectDojo/assets/55973393/323e4460-d25a-421b-9501-343226f7f544)

**Comment by kiblik** [comment]
It is definitely possible and you are also looking for the right API endpoint. Can you go into more detail about how exactly you try to add a product? Have you received any errors? What does the error look like?

**Comment by Lax-Asuna** [comment]
I've tried the following APIs and succeeded. Thanks a lot.
POST /api/v2/products/
POST /api/v2/findings/
