### ISSUE TITLE
failed to solve: process "/bin/sh -c cd components &&   yarn" did not complete successfully: exit code: 1 / update failed 06/05/2024

### ISSUE THREAD

**Issue by johnfelipe** [DefectDojo/django-DefectDojo#10131]
i do this commands:

git fetch
    
    remote: Enumerating objects: 3589, done.
    remote: Counting objects: 100% (3584/3584), done.
    remote: Compressing objects: 100% (332/332), done.
    remote: Total 3589 (delta 1796), reused 3446 (delta 1714), pack-reused 5
    Receiving objects: 100% (3589/3589), 1.69 MiB | 4.42 MiB/s, done.
    Resolving deltas: 100% (1796/1796), completed with 287 local objects.
    From https://github.com/DefectDojo/django-DefectDojo
       f66e6dbb0..9693fa096  master                 -> origin/master
       8931ed4c6..2cc78128f  bugfix                 -> origin/bugfix
     * [new branch]          dependabot/npm_and_yarn/components/dev/datatables.net-2.0.6 -> origin/dependabot/npm_and_yarn/components/dev/datatables.net-2.0.6
     * [new branch]          dependabot/npm_and_yarn/components/dev/datatables.net-dt-2.0.6 -> origin/dependabot/npm_and_yarn/components/dev/datatables.net-dt-2.0.6
     + 3f66f61a9...c6d40a6c0 dependabot/pip/dev/django-crispy-forms-2.1 -> origin/dependabot/pip/dev/django-crispy-forms-2.1  (forced update)
     + 566dc2dde...f7afac7a9 dependabot/pip/dev/urllib3-2.2.1 -> origin/dependabot/pip/dev/urllib3-2.2.1  (forced update)
       e5c83b9ad..668b03e27  dev                    -> origin/dev
       23800d19c..47164ca39  gh-pages               -> origin/gh-pages
     * [new branch]          hblankenship-doc-patch -> origin/hblankenship-doc-patch
     * [new branch]          hblankenship-patch-1   -> origin/hblankenship-patch-1
       4eb0a4cce..6e6d787f2  helm-charts            -> origin/helm-charts
     * [new branch]          release/2.34.0         -> origin/release/2.34.0
     + 6415338c6...b411d69d1 renovate/mysql-10.x    -> origin/renovate/mysql-10.x  (forced update)
     + ac3ccd247...5421bbd98 renovate/mysql-9.x     -> origin/renovate/mysql-9.x  (forced update)
     + c73482753...54f3592fc renovate/postgresql-ha-14.x -> origin/renovate/postgresql-ha-14.x  (forced update)
     * [new tag]             2.34.0                 -> 2.34.0

then pulled

    git pull

here log:

https://gist.github.com/johnfelipe/9a2c520daf0002ba242917596e8f7c9d

git merge origin/master

    Already up to date.

*BUILD AGAIN*

cd django-DefectDojo

./dc-build.sh

    Checking docker compose version
    Supported docker compose version
    Building docker compose
    [+] Building 341.5s (32/39)                                      docker:default
     => [uwsgi internal] load build definition from Dockerfile.django-debian   0.0s
     => => transferring dockerfile: 4.83kB                                     0.0s
     => [nginx internal] load metadata for docker.io/library/python:3.11.4-s  22.0s
     => [uwsgi internal] load .dockerignore                                    0.0s
     => => transferring context: 120B                                          0.0s
     => [uwsgi internal] load build context                                    0.2s
     => => transferring context: 6.19MB                                        0.2s
     => [nginx base 1/1] FROM docker.io/library/python:3.11.4-slim-bullseye@s  0.0s
     => CACHED [nginx build 1/4] WORKDIR /app                                  0.0s
     => CACHED [nginx build 2/4] RUN   apt-get -y update &&   apt-get -y inst  0.0s
     => [uwsgi build 3/4] COPY requirements.txt ./                            18.0s
     => [uwsgi build 4/4] RUN CPUCOUNT=1 pip3 wheel --wheel-dir=/tmp/wheels  118.0s
     => CACHED [uwsgi django  2/12] RUN   apt-get -y update &&   mkdir -p /us  0.0s
     => [uwsgi django  3/12] COPY --from=build /tmp/wheels /tmp/wheels         0.0s
     => [uwsgi django  4/12] COPY requirements.txt ./                          0.0s
     => [uwsgi django  5/12] RUN export PYCURL_SSL_LIBRARY=openssl &&     pi  46.7s
     => [uwsgi django  6/12] COPY   docker/entrypoint-celery-beat.sh   docker  0.0s
     => [uwsgi django  7/12] COPY wsgi.py manage.py docker/unit-tests.sh ./    0.0s
     => [uwsgi django  8/12] COPY dojo/ ./dojo/                                0.6s
     => [uwsgi django  9/12] COPY docker/extra_fixtures/* /app/dojo/fixtures/  0.0s
     => [uwsgi django 10/12] COPY tests/ ./tests/                              0.0s
     => [uwsgi django 11/12] RUN   rm -f /readme.txt &&   rm -f dojo/fixtures  0.2s
     => [uwsgi django 12/12] RUN     addgroup --gid 1337 defectdojo &&     ad  1.6s
     => [uwsgi] exporting to image                                             4.2s
     => => exporting layers                                                    4.2s
     => => writing image sha256:b2c87213cdbc522429daf5a96b8c40de705ed6e24d1d8  0.0s
     => => naming to docker.io/defectdojo/defectdojo-django:latest             0.0s
     => [nginx internal] load build definition from Dockerfile.nginx-debian    0.0s
     => => transferring dockerfile: 3.48kB                                     0.0s
     => [nginx internal] load metadata for docker.io/library/nginx:1.26.0-alp  2.4s
     => [nginx internal] load .dockerignore                                    0.0s
     => => transferring context: 120B                                          0.0s
     => [nginx internal] load build context                                    0.1s
     => => transferring context: 231.07kB                                      0.1s
     => [nginx stage-3 1/5] FROM docker.io/library/nginx:1.26.0-alpine@sha256  2.6s
     => => resolve docker.io/library/nginx:1.26.0-alpine@sha256:ca16009a8c25f  0.0s
     => => sha256:572be995fb17299a231739208707efa025543f32b 10.98kB / 10.98kB  0.0s
     => => sha256:091275ae680776b2922329c9b3f581863a6de95856c 3.99MB / 3.99MB  0.8s
     => => sha256:680080a33f4ff2b0d8aedac2d12fda4dec7b4522728f1bc 629B / 629B  0.9s
     => => sha256:ca16009a8c25f52193506d4c90c98efbad4b6cbe733 9.06kB / 9.06kB  0.0s
     => => sha256:6a0a9d8f730f67d04eac41a3411155f519fdce3bd9c 2.50kB / 2.50kB  0.0s
     => => sha256:b04f45f24a9c66d04eee91e92f732179b6f37f834b8751f 957B / 957B  1.1s
     => => extracting sha256:091275ae680776b2922329c9b3f581863a6de95856c04671  0.4s
     => => sha256:26087820d60a54635a5c91a255fc080b80bb15c40b880e2 394B / 394B  1.2s
     => => sha256:bd75bb60cdbb992a9f78232b550adf88b3199f1c885 1.21kB / 1.21kB  1.2s
     => => sha256:125d178ee43c0b386693c2635ecce90f8aad572f9a7 1.40kB / 1.40kB  1.4s
     => => sha256:0e4a02da9f62b5bc6ac6a424775ec683d55e630f1 13.04MB / 13.04MB  1.8s
     => => extracting sha256:680080a33f4ff2b0d8aedac2d12fda4dec7b4522728f1bc5  0.0s
     => => extracting sha256:b04f45f24a9c66d04eee91e92f732179b6f37f834b8751f1  0.0s
     => => extracting sha256:26087820d60a54635a5c91a255fc080b80bb15c40b880e24  0.0s
     => => extracting sha256:bd75bb60cdbb992a9f78232b550adf88b3199f1c8853d369  0.0s
     => => extracting sha256:125d178ee43c0b386693c2635ecce90f8aad572f9a7a05f1  0.0s
     => => extracting sha256:0e4a02da9f62b5bc6ac6a424775ec683d55e630f1b407752  0.6s
     => CACHED [nginx build 3/4] COPY requirements.txt ./                      0.0s
     => CACHED [nginx build 4/4] RUN CPUCOUNT=1 pip3 wheel --wheel-dir=/tmp/w  0.0s
     => [nginx collectstatic 1/7] RUN   apt-get -y update &&   apt-get -y in  67.2s
     => [nginx collectstatic 2/7] RUN pip3 install  --no-cache-dir  --no-ind  36.0s
     => [nginx collectstatic 3/7] COPY components/ ./components/               0.0s
     => ERROR [nginx collectstatic 4/7] RUN   cd components &&   yarn         23.5s
    ------
     > [nginx collectstatic 4/7] RUN   cd components &&   yarn:
    0.573 yarn install v1.22.10
    0.638 [1/5] Validating package.json...
    0.642 [2/5] Resolving packages...
    0.761 [3/5] Fetching packages...
    17.12 error An unexpected error occurred: "https://registry.yarnpkg.com/bootstrap-social/-/bootstrap-social-4.11.0.tgz: getaddrinfo EAI_AGAIN registry.yarnpkg.com".
    17.12 info If you think this is a bug, please open a bug report with the information provided in "/app/components/yarn-error.log".
    17.12 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
    ------
    failed to solve: process "/bin/sh -c cd components &&   yarn" did not complete successfully: exit code: 1

**Comment by johnfelipe** [comment]
something happend with network i think, is already updated

**Comment by mtesauro** [comment]
A quick Google for `getaddrinfo EAI_AGAIN` shows that that's a network error. Nothing to do with the DefectDojo source code or build process.

Looking at the replies, it boils down to:
* Try it again 
* Use a different network
