### ISSUE TITLE
Install and run DefectDojo from docker hub images

### ISSUE THREAD

**Issue by halfliffe** [DefectDojo/django-DefectDojo#10140]
Please tell me how, or provide a link to instructions - how to install and run DefectDojo from ready-made images from docker hub?

I have a host with docker installed.
I do the following:
1. docker pull defectdojo/defectdojo-django
2. docker pull defectdojo/defectdojo-nginx
3. docker run -d defectdojo/defectdojo-nginx
4. docker run -d -p 8100:8080 defectdojo/defectdojo-django --name=defectdojo --restart=always

```
docker ps | grep defectdojo
7dfc30498afd defectdojo/defectdojo-django "/entrypoint-uwsgi.s…" 13 seconds ago Up 12 seconds 0.0.0.0:8100->8080/tcp, :::8100->8080/tcp quirky_williams
```

And, the http://dockerhost:8100 page is not responding.
Please tell me what and how to do to launch defectdojo from ready-made docker hub images?

**Comment by kiblik** [comment]
Please follow the instructions in the documentation:
- https://documentation.defectdojo.com/getting_started/installation/

which will forward you to
- https://github.com/DefectDojo/django-DefectDojo/blob/dev/readme-docs/DOCKER.md

**Comment by halfliffe** [comment]
Yes, this helped for me, thanks!
