### ISSUE TITLE
Import Type "SonarQube Scan detailed" Ignores Severity Level

### ISSUE THREAD

**Issue by enidevops** [DefectDojo/django-DefectDojo#10150]
**Bug description**
When importing results from sonar-report using the "SonarQube Scan detailed" importer the severity level get's ignored

Below is the output from sonar-report directly inside the pipeline:

![image](https://github.com/DefectDojo/django-DefectDojo/assets/44378292/674b25e5-306f-4705-8510-1d2d23c6caa5)

When importing the results into Defectdojo I get the following result:

![image](https://github.com/DefectDojo/django-DefectDojo/assets/44378292/c5079a4e-2595-44ec-afd5-6e9e6b57cb44)

As you can see, all 3 findings are marked as "Info"

In the report you can see that those 3 findings should be 2x High and 1x Low:

![image](https://github.com/DefectDojo/django-DefectDojo/assets/44378292/2d1cc57e-0dee-49e1-820d-dec3d3e1644d)

**Sample File
[sonar-report_sonar-report.txt](https://github.com/DefectDojo/django-DefectDojo/files/15238321/sonar-report_sonar-report.txt)

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**

- DefectDojo version 2.34.0

**Comment by manuel-sommer** [comment]
@enidevops take a look at the PR

**Comment by enidevops** [comment]
@manuel-sommer this is now working, thx

**Comment by manuel-sommer** [comment]
This can be closed @enidevops
