### ISSUE TITLE
Add social login feature - google, github

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1015]
**Is your feature request related to a problem? Please describe**
From both a functional and security point of view, authenticating with OAuth against an IdP is often the way to go, rather that using a built-in database.

There is also a lack of bulk importing users out-of-the-box.

**Describe the solution you'd like**
Integrate social oauth, pretty much as described in this post: https://fosstack.com/how-to-add-google-authentication-in-django/

**Comment by aaronweaver** [comment]
Looks fairly straightforward. @devGregA has also been working on SAML integration and in particular with Okta.

**Comment by propersam** [comment]
Hi, @devGregA  @aaronweaver , I can quickly get this done following the blog referenced above.

After going through the blog. I think integrate  github auth first. Because I don't have access to google cloud console credentials. but I can easily generate one from github

**Comment by propersam** [comment]
My worry now is how do we handle the github credentials *(GITHUB_KEY AND GITHUB_SECRET)* that are meant to be unique.

**Comment by propersam** [comment]
I know that I can make them environment variable. I mean how do other developers using docker-compose to run the project get access to the functionality in their own environment.

**Comment by devGregA** [comment]
Added via https://github.com/DefectDojo/django-DefectDojo/pull/1209
