### ISSUE TITLE
nginx '413 Request Entity Too Large' error when uploading Burp scan result

### ISSUE THREAD

**Issue by ebdecastro** [DefectDojo/django-DefectDojo#1016]
**Bug description**
When trying to upload a Burp scan results xml, I get a '413 Request Entity Too Large' error from nginx.

**Steps to reproduce**
1. Export Burp scan results with 200 items.
2. Trying to upload it.

**Expected behavior**
Correct import of the document

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 18.04.2 LTS
 - DefectDojo version: 2af278b: Merge pull request #972 from DefectDojo/dev [2019-03-22 20:32:29 -0400]

**Comment by adracea** [comment]
Ahh the burp report has over the limits allowed by nginx config in the nginx Docker

**Comment by ebdecastro** [comment]
I guess it is necessary to modify nginx.conf file changing "client_max_body_size 8m;" line.

**Comment by adracea** [comment]
exactly that , after which you have to rebuild the nginx container and it should work just fine :)
