### ISSUE TITLE
unable to upload large qualys scan result

### ISSUE THREAD

**Issue by sameeragp** [DefectDojo/django-DefectDojo#10199]
Kubernetes Cluster : Azure K8's
K8's Version: v1.28.5

Defect Dojo is running in AKS cluster installed via helm charts

Database used : postgressql

**Kubernetes service expose by nginx controller** 

File size: 20 mb , extenstion type: .xml scan type : qualys infra scan.

![image](https://github.com/DefectDojo/django-DefectDojo/assets/71246248/9910235a-4c65-4b7c-b4fa-6a7cc07d74d6)

**Comment by manuel-sommer** [comment]
Did you maybe change DD_SCAN_FILE_MAX_SIZE in dojo/settings/settings.dist.py ?

**Comment by sameeragp** [comment]
Hi Team,

We checked on this internally. issue is resolved after adding client-max-body-size: 150m above variable and value in nginx ingress controller config map
