### ISSUE TITLE
Severity "lost" when importing a Qualys Scan

### ISSUE THREAD

**Issue by nv-pipo** [DefectDojo/django-DefectDojo#10206]
**Bug description**
When trying to import import a "Qualys Scan" (Qualys VMDR) the severity is lost because the mapping (dict) is expecting an int. Xml's parser returns a string (`findtext`), so it needs to be converted to int.

Please approve PR: https://github.com/DefectDojo/django-DefectDojo/pull/10205

Basically, it's just a cast from string to int.

**Steps to reproduce**

**Expected behavior**

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo version (see footer) or commit message: [use `git show -s --format="[%ci] %h: %s [%d]"`]

**Logs** 
Use `docker-compose logs` (or similar, depending on your deployment method) to get the logs and add the relevant sections here showing the error occurring (if applicable).

**Sample scan files**
If applicable, add sample scan files to help reproduce your problem.

**Screenshots**

**Additional context** (optional)

**Comment by manuel-sommer** [comment]
Can you close this @nv-pipo ?

**Comment by nv-pipo** [comment]
@manuel-sommer 
PR https://github.com/DefectDojo/django-DefectDojo/pull/10205 merged. Closing
