### ISSUE TITLE
works hard

### ISSUE THREAD

**Issue by e1ght81t** [DefectDojo/django-DefectDojo#10238]
Hello

I use DefectDojo in production. My version is 2.31.2
This works for a very long time. The main page opens in 7-10 seconds. I tried scaling as stated in the documentation and using docker-compose scale. How can I try to speed up the work?
Resources: 12 processor cores, 8Gb RAM, SSD.

**Comment by manuel-sommer** [comment]
Hi @e1ght81t , I guess this is rather a community question but not a real issue. Please ask consulting question either through the official support or the OWASP Slack channel. @mtesauro I guess this can be closed.

**Comment by mtesauro** [comment]
Agreed manuel-sommer
