### ISSUE TITLE
ZAP Scan deduplication is not working

### ISSUE THREAD

**Issue by zakrush** [DefectDojo/django-DefectDojo#10252]
**Be informative**
ZAP Scan reports is not deduplicated in new engagement  of same product,

**Bug description**
A clear and concise description of what the bug is. For errors include at least the exact error message you are seeing (including traceback).

**Steps to reproduce**
1. Create Engagment. Dedup on Engagment is disable. 
2. Import ZAP_Scan report.(attached)
3. Create Second engagment. Dedup on Engagment is disable. 
4. Import the same ZAP_scan report
[some_report.txt](https://github.com/DefectDojo/django-DefectDojo/files/15403215/some_report.txt)

**Expected behavior**
After importing ZAP report to new engagement all findings have been deduplicated

**Deployment method** *(select with an `X`)*
- [x] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - DefectDojo version v. 2.34.4

**Logs** 
Use `docker-compose logs` (or similar, depending on your deployment method) to get the logs and add the relevant sections here showing the error occurring (if applicable).

**Sample scan files**
If applicable, add sample scan files to help reproduce your problem.

**Screenshots**
First import

![image](https://github.com/DefectDojo/django-DefectDojo/assets/33844164/221305b6-c111-4188-8e7d-b7144ae38ed0)

second import
![image](https://github.com/DefectDojo/django-DefectDojo/assets/33844164/7eb44230-ae6c-4700-bb34-f77d2ade7312)

**Comment by mtesauro** [comment]
Do you have dedupication turned on globally in System Settings?

![image](https://github.com/DefectDojo/django-DefectDojo/assets/3422419/3bc9e8e2-fbb2-4f9a-bba6-c643e709a4d4)
