### ISSUE TITLE
Metrics dashboard crash on nginx with 502 bad gateway

### ISSUE THREAD

**Issue by sebglon** [DefectDojo/django-DefectDojo#10259]
**Bug description**
We have a big defectdojo.
When we need to show the metris dashobard `/metrics?date=5&view=dashboard`, the query require 10G on the uwsgi and the nginx return an error 

**Steps to reproduce**
1. Go to UI  
2. Click on metrics dashboard

**Expected behavior**
The dashboard is well open

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [x] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo version (see footer) or commit message: 2.34.4

**Logs** 
```
2024/05/23 09:06:48 [error] 12#12: *265 upstream prematurely closed connection while reading response header from upstream, client: 10.233.114.23, server: , request: "GET /metrics?date=5&view=dashboard HTTP/1.1", upstream: "uwsgi://unix:///run/defectdojo/uwsgi.sock:", host: "defectdojo.xxxxxx"
10.233.114.23 - - [23/May/2024:09:06:48 +0000] "GET /metrics?date=5&view=dashboard HTTP/1.1" 502 497 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" "10.0.1.74"
Thu May 23 09:02:18 2024 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) !!!
Thu May 23 09:02:18 2024 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during GET /alerts/count (10.233.78.161)
```

**Comment by Gurban77** [comment]
@sebglon Hi!
I fixed the same issue just adding more resource for uwsgi and a little bit for nginx container of django-defectdojo pod. My DefectDojo also deploy via k8s

**Comment by manuel-sommer** [comment]
I guess this can be closed @mtesauro .
