### ISSUE TITLE
Remediation progress tracking

### ISSUE THREAD

**Issue by mossytrees** [DefectDojo/django-DefectDojo#1027]
**Is your feature request related to a problem? Please describe**
Currently there is no way to track progress remediating a particular finding.  If a finding affects 10 endpoints and 9 are remediated, the finding remains open, and there is no way to report on the progress remediating the finding.  Similarly, if a finding affects two different areas of a single endpoint (e.g. CSS in two different fields), the finding remains open until all instances of the finding are fixed.

This presents challenges for communicating with developers when they think they've resolved the issue but have really only partially resolved it.  It also presents challenges for use in broader vulnerability management (scanning whole networks or network segments, as opposed to scanning just the servers supporting a particular product).

**Describe the solution you'd like**
As a vulnerability scanning program manager, I want a way to track the status of individual instances of a particular finding, so that progress can be tracked, and communication on outstanding items can be clear and concise.

**Describe alternatives you've considered**
The first option I considered was to break out vulnerability scanning into separate products and engagements, running separate scans for each, and importing the results from each area into DD.  However this quickly becomes unmanageable without additional automation (e.g. kicking off the scans from within DD and importing the results directly), and even then poses challenges for network discovery scans, where you don't know what product or environment a discovered endpoint will belong to.)

Another option is to change the key used to determine uniqueness of findings when importing from a scan tool.  For example, the Nessus importer looks at "severity + title" for deduplication, combining all affected endpoints into one DefectDojo finding.  If we change to "severity + title + endpoint", we'll have individual instances of each finding, but the findings list will also be flooded with what look like duplicates.

Ultimately I think the right solution is to add the concept of an "instance", and link findings to instances, and instances to endpoints.  Each instance should be able to have its own evidence, remediation status, notes, tags, user list (to indicate who is responsible for remediation) etc.

**Additional context**
The use case of vulnerability management may be a bit of a stretch for what DD was designed for.  Vulnerability management programs typically encompass multiple products and multiple product owners.

**Comment by devGregA** [comment]
Hi @mossytrees, thank you for your detailed writeup. I've been thinking about this, and one way we may be able to address this is adding the notion of remediated endpoints. Do you think that would do enough to cover your use case?

**Comment by mossytrees** [comment]
@devGregA, sounds likely.  The main need I'm looking to fill is being able to track status of endpoints in relationship to findings.  So if a single finding has 10 endpoints associated, and we can mark each endpoint as remediated or not individually, and then be able to do some reporting/charting around that, I'd be happy :) . (Better yet if subsequent scan imports can be used to automatically mark endpoints as remediated if they don't show up on the latest scan results...)

**Comment by devGregA** [comment]
I've added this as an issue for the interns I hired for summer. They start in about a month. Approximate ETA to completion 6 weeks. https://github.com/DefectDojo/django-DefectDojo/projects/7

**Comment by mossytrees** [comment]
Awesome!! 👍
