### ISSUE TITLE
Can not copy and paste images to issues

### ISSUE THREAD

**Issue by kaanatmacaa** [DefectDojo/django-DefectDojo#10276]
When creating/editing an issue i am not able to copy and paste images.

**Comment by mtesauro** [comment]
That's never been possible so expected behavior. If you want to add images to findings, you'll need to use the "Manage file" mechanism:

![image](https://github.com/DefectDojo/django-DefectDojo/assets/3422419/b3975a37-2a2c-4c2c-8e12-b5d75153f53c)
