### ISSUE TITLE
End of life Alpine Linux 3.16

### ISSUE THREAD

**Issue by sknabe-DBS** [DefectDojo/django-DefectDojo#10277]
According to the official website https://alpinelinux.org/releases/ alpine 3.16 has reached it's end of life on  2024-05-23.
Loos like 3.16 is still used in 2.34.4.

To receive security fixes etc. the alpine containers referenced in the Dockerfiles should upgraded to a newer version, i. e. 3.20.

Best regards,
Stephan Knabe

**Comment by kiblik** [comment]
@mtesauro, this issue can be closed. Alpine has been updated to 3.20
