### ISSUE TITLE
K8 PVC Issue

### ISSUE THREAD

**Issue by marquezc1** [DefectDojo/django-DefectDojo#1030]
**Bug description**
It appears that when I try to deploy this platform in a 2 node K8 cluster through helm, I see the following warning event on the MySQL pod:
Warning  FailedScheduling  pod has unbound immediate PersistentVolumeClaims

I think I need to create a PV type role in the desired namespace but I am just not sure how to go about this and keep the claimname consistent with what the pod is expecting. Once the PV is present in the cluster then I expect mysql to get deployed and the pod deployment of defectdojo-django.

**Steps to reproduce**
1. Follow https://github.com/DefectDojo/django-DefectDojo/blob/master/KUBERNETES.md quickstart section
2. Deploy Tiller in a namespace, restricted to deploying resources only in that namespace
3. Create a Role and RoleBinding to limit Tiller’s scope to a particular namespace.
4. Install helm chart
5. Check pod event details

**Expected behavior**
All pods in the defect-dojo namespace to be in a ready status. 

**Deployment method** *(select with an `X`)*
- [X ] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 18.04 server
 - DefectDojo version: 1.5.4rc1

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

**Comment by marquezc1** [comment]
I was able to figure out what was needed to make this work.

- Create a storage class resource in your K8 cluster
- Create a local persistent volume on a node within your cluster
- Update the mysql helm chart values.yaml file and point to your storage class

**Comment by michaelsync-mt** [comment]
@marquezc1 Do you have the example of values.yaml?  It seems like Helm chart doesn't support storage class and etc.

**Comment by dsever** [comment]
Hi, what is your usecase? If you talking about pvc for mysql or pgsql, it is supported by parent class. So take a look at bitnami helm for postgresql.

**Comment by michaelsync-mt** [comment]
@dsever Thanks. I am new to DefectDojo. I am just trying to install DefectDojo to AWS EKS. I am currently following this guide https://github.com/DefectDojo/django-DefectDojo/blob/dev/readme-docs/KUBERNETES.md.  

The chart that I am using is helm repo add helm-charts 'https://raw.githubusercontent.com/DefectDojo/django-DefectDojo/helm-charts' 

Is this the right chart? Or is it the older Helm 2 version?  Should I use https://charts.bitnami.com/bitnami? 

According to the doc, I need to use S3 for PVC. I am not sure whether it's for mysql or pgsql. I don't mind using either one. 

`To enable persistence of the media storage that supports R/W many, should be in use as backend storage like S3, NFS, glusterfs, etc`

I have opened up the issue https://github.com/DefectDojo/django-DefectDojo/discussions/5966 but no reply. So I found this post. I want to know how to use S3 when deploying defectdojo to EKS.

**Comment by dsever** [comment]
Hi,

In DD  PVC is mandatory only for DB data, and in some cases for RabbitMQ.  This instructions you are following are for media files (like images if you want to store it) in case you want to preserve some additional items together with findings.

Related to the path, I'm not sure, because I'm always using helm from the repo directly. This bitnami is origin for postgresql dependencies.
