### ISSUE TITLE
I want to integrate the defect dojo with the azure devops where the defect dojo should fetch the scan results of the sonarqube,trivy,dependency check identified in the azure devops pipeline to the defect dojo as soon as the results where created in the artifacts folder 

### ISSUE THREAD

**Issue by Nsai1997** [DefectDojo/django-DefectDojo#10305]
I want to integrate the defect dojo with the azure devops where the defect dojo should fetch the scan results of the sonarqube,trivy,dependency check identified in the azure devops pipeline to the defect dojo as soon as the results where created in the artifacts folder

**Comment by manuel-sommer** [comment]
I guess this is rather a consulting request for the official Support or owasp slack channel and can be closed @mtesauro

**Comment by mtesauro** [comment]
@Nsai1997 
Feel free to ask your your question in the OWASP Slack for DefectDojo - info on doing that is at https://github.com/DefectDojo/django-DefectDojo/issues/10305  You're more likely to get good feedback and answers there than a Github issue.

Also, we're currently not accepting API integrations to DefectDojo while we work on getting to version 3 - see Github Discussions:
https://github.com/DefectDojo/django-DefectDojo/discussions/8002
https://github.com/DefectDojo/django-DefectDojo/discussions/8974
https://github.com/DefectDojo/django-DefectDojo/discussions/9690
