### ISSUE TITLE
Netsparker scan import issue  'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by MotiejusK** [DefectDojo/django-DefectDojo#10311]
**Bug description**

Current implementation is expecting that if finding defines unsaved_req_resp, it comes as tuple <req, resp> every time (with both items filled with non empty data). However, it looks that since some time, some tools (followed by parsers) are putting here only requests.
In case of Netsparker, Vulnerabilities[].HttpResponse.Content might be empty.

**Steps to reproduce**
1. Go to  product
2. Click on Fidings
4. Click on Add scan resulst
5. Fill form
6. Click submit
7. See error

**Expected behavior**
Scan would be imported 

**Deployment method** *(select with an `X`)*
- [x] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Logs** 
212 bytes (1 switches on core 0)
uwsgi-1 | [30/May/2024 11:54:11] ERROR [dojo.engagement.views:955] 'NoneType' object has no attribute 'encode'
uwsgi-1 | Traceback (most recent call last):
uwsgi-1 |  File "/app/dojo/engagement/views.py", line 943, in import_findings
uwsgi-1 |   context["test"], _, finding_count, closed_finding_count, _, _, _ = importer_client.process_scan(
uwsgi-1 |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1 |  File "/app/dojo/importers/default_importer.py", line 134, in process_scan
uwsgi-1 |   new_findings = self.determine_process_method(test, parsed_findings, user, **kwargs)
uwsgi-1 |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1 |  File "/app/dojo/importers/base_importer.py", line 306, in determine_process_method
uwsgi-1 |   return self.sync_process_findings(
uwsgi-1 |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1 |  File "/app/dojo/importers/default_importer.py", line 449, in sync_process_findings
uwsgi-1 |   return self.process_findings(
uwsgi-1 |       ^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1 |  File "/app/dojo/importers/default_importer.py", line 224, in process_findings
uwsgi-1 |   self.process_request_response_pairs(finding)
uwsgi-1 |  File "/app/dojo/importers/base_importer.py", line 826, in process_request_response_pairs
uwsgi-1 |   burpResponseBase64=base64.b64encode(req_resp["resp"].encode("utf-8")))
uwsgi-1 |                     ^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1 | AttributeError: 'NoneType' object has no attribute 'encode'

**Sample scan files**
Could be shared only private

**Additional context** (optional)
Issue already discussed in slack channel.

**Comment by manuel-sommer** [comment]
This can be closed @cneill and @MotiejusK
