### ISSUE TITLE
docker-compose version number configuration file bug

### ISSUE THREAD

**Issue by ismailtasdelen** [DefectDojo/django-DefectDojo#1032]
Hello DefectDojo Team,

My name is Ismail Tasdelen. I found a docker-compose via bug. I encountered an error in the yml configuration file on the docker-compose used in the web application.

Step by Step :

```
git clone https://github.com/DefectDojo/django-DefectDojo
cd django-DefectDojo
docker-compose up
```
First Error Message :

![Screenshot at 2019-04-10 10-49-22](https://user-images.githubusercontent.com/15425071/55861200-8c568c80-5b7e-11e9-8f84-136770c15222.png)

Solution : 

Change the version number from the first line in the `docker-compose.yml` to the "3.3" version from 3.7.

Second Error Message : 

![Screenshot at 2019-04-10 10-49-57](https://user-images.githubusercontent.com/15425071/55861470-1f8fc200-5b7f-11e9-8017-58ddd87c5c7b.png)

Solution : 

Change the version number from the first line in the `docker-compose.override.yml` to the "3.3" version from 3.7.

Thanks

**Comment by ptrovatelli** [comment]
Hi @ismailtasdelen . Can you post your docker-compose and docker version?
docker-compose --version
docker --version
 3.7 file format requires 18.06.0+ docker engine. See https://docs.docker.com/compose/compose-file/
With "Docker version 18.06.1-ce, build e68fc7a" i'm not seing this problem.
You might just need to upgrade docker
We should add this in as a pre-requisites in the documentation though

**Comment by ptrovatelli** [comment]
If you're trying to install the dev branch with docker and are still having issues, you may want to check this issue https://github.com/DefectDojo/django-DefectDojo/issues/1026 :)

**Comment by aaronweaver** [comment]
Fixed
