### ISSUE TITLE
Accessing the defect dojo in the Vms

### ISSUE THREAD

**Issue by Nsai1997** [DefectDojo/django-DefectDojo#10321]
hi team

I have installed the defect dojo using the virtual machine in the gcp using the docker.But now I want to access the defect dojo dashboard to integrate some of the tool reports in order to track them efficiently

could you please help me with that

**Comment by manuel-sommer** [comment]
Hi @Nsai1997, could you please ask in the OWASP Slack channel this question or use the official support. This is not an issue. 
@mtesauro I guess this can be closed.
