### ISSUE TITLE
SMTP configuration issue - [Errno 111] Connection refused

### ISSUE THREAD

**Issue by J1nchur1k1** [DefectDojo/django-DefectDojo#10339]
I have configured defect dojo, but unable to work on the notification part. with many threads I did configuration on many file but unable to resolve the issue, but I saw these messages from the docker logs.
Please help.

Traceback (most recent call last):
  File "/app/dojo/notifications/helper.py", line 299, in send_mail_notification
    email.send(fail_silently=False)
  File "/usr/local/lib/python3.11/site-packages/django/core/mail/message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/mail/backends/smtp.py", line 124, in send_messages
    new_conn_created = self.open()
                       ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/mail/backends/smtp.py", line 80, in open
    self.connection = self.connection_class(
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by J1nchur1k1** [comment]
Yes we did
Can you again confirm the file and the format again ?

**Comment by J1nchur1k1** [comment]
> Have you configured `DD_EMAIL_URL`? Have you added it to `uwsgi` and `celery-worker` as well? Do you have the ability to test connectivity between your host and your SMTP server?

Yes we did
Can you again confirm the file and the format again ?

**Comment by kiblik** [comment]
**Format**: DD is using `environ` for parsing `DD_EMAIL_URL`

https://github.com/DefectDojo/django-DefectDojo/blob/67a75710d6991a3ee3d4ed8dca7d0ef5c9cef46a/dojo/settings/settings.dist.py#L886-L887

It might look like `smtp://user@:password@localhost:25`. SSL/TLS is also supported, check [docs](https://django-environ.readthedocs.io/en/latest/types.html#environ-env-email-url).

**File (location)**:
- For docker-compose: `environment` sections under `uwsgi` and `celeryworker` in [docker-compose.yml](https://github.com/DefectDojo/django-DefectDojo/blob/master/docker-compose.yml) (if you add it to all containers nothing bad will happen, it will be just ignored)
- For helm: `extraConfigs`, `extraSecrets` or `extraEnv`: https://github.com/DefectDojo/django-DefectDojo/blob/67a75710d6991a3ee3d4ed8dca7d0ef5c9cef46a/helm/defectdojo/values.yaml#L531-L551

**Comment by kiblik** [comment]
> Thanks mate Issue got resolved. Moreover is there any setting in application in which I can define the notification should only go to the specific person defined in the product details. like application owner.

In short: no.
Notifications are not sent based on fields like `product_manager`, `technical_contact` or `team_manager` but based on role (or group role) assignment. The person needs to be at least `Reader` in the product to be able to receive email notifications.
