### ISSUE TITLE
Unify page headings

### ISSUE THREAD

**Issue by efficiosoft** [DefectDojo/django-DefectDojo#1033]
**Is your feature request related to a problem? Please describe**
The headings of the various web UI pages do differ in heading level used. Some pages don't even have a heading. This makes navigating the UI with assistive technologies inefficient as it's not possible to jump to the beginning of content straight away.

**Describe the solution you'd like**
I could unify this and make all pages use h1 headings, which follows the convention that every page should have one single h1 at the top. Styling of the h1 tag could then be adjusted via CSS globally.

What do you think, is this acceptable?

Best regards
Robert

**Comment by aaronweaver** [comment]
That approach sounds fine.

**Comment by efficiosoft** [comment]
Ok, I'm already half way through this and will file a PR with changed headings and a bunch of other accessibility fixes all over the UI soon.

Thanks @aaronweaver for adding the access linting bot. I'm not sure what exactly it checks for but this is a great addition!
