### ISSUE TITLE
 An exception error occurred during the report import ,during the sonar cloud integration with the defect dojo

### ISSUE THREAD

**Issue by Nsai1997** [DefectDojo/django-DefectDojo#10343]
Hi team, when click on import vulnerabilities while i am importing the vulnerabilites from the sonarqube to defect dojo I am getting the below error.  An exception error occurred during the report import: api_scan_configuration of type <class 'dojo.models.Product_API_Scan_Configuration'> is not one of [<class 'dojo.models.Tool_Configuration'>] Here are all the options submitted: None

Even I checked the API key in the tool configuration,Project key while importing the findings all are correct

**Comment by Nsai1997** [comment]
Hi team,
Even I tried with the latest release 2.3.5 but facing same error.
![Uploading IMG_0920.png…](

Can you please help me in guide me the steps to resolve this issue

**Comment by 37b** [comment]
We're having the same issue with on-prem SonarQube. We're stuck until this is resolved.

**Comment by Nsai1997** [comment]
![IMG_0920](https://github.com/DefectDojo/django-DefectDojo/assets/46392529/26200c39-2d3c-4e81-a16c-78e6ec614d4e)

**Comment by mtesauro** [comment]
Please try [2.35.1](https://github.com/DefectDojo/django-DefectDojo/releases/tag/2.35.1) release that happened today. A fix (#10345) was in that release that made an attempt at fixing it though the fix wasn't able to be tested.

Since it appears none of the core contributors have access to an on-prem or cloud version of SonarQube, we're kinda stuck without more details to help figure out what's going on if 2.35.1 doesn't fix the issue.

**Comment by Nsai1997** [comment]
Hi team,did we implement the fix for the above issue in the 2.35.1.As we need to follow a large process to setup so want to confirm before going ahead?

**Comment by mtesauro** [comment]
The PR I mentioned (#10345 ) was in 2.35.1 so yes a fix for the issue was added to that version.

As I said above:
**made an attempt at fixing it though the fix wasn't able to be tested**
because
**it appears none of the core contributors have access to an on-prem or cloud version of SonarQube**

so we _believe_ the fix is valid but don't have a way to confirm that. This is one the unfortunate aspects of API integrations with DefectDojo - they are difficult to test and confirm they work as expected unless someone happens to have that API running in a place where it can be tested.

Unfortunately, we cannot provide any more assurance than the info above.

**Comment by Nsai1997** [comment]
Hi Team,

After reviewing the new release, I've identified a couple of issues that need attention:

Incomplete Vulnerability Import: It seems that only a fraction of the vulnerabilities are being imported correctly. For instance, out of the 20 expected vulnerabilities, we're only receiving 3. This partial import could potentially leave us vulnerable to undetected threats.

Missing Vulnerabilities from SonarQube: Additionally, we're noticing discrepancies in the vulnerabilities imported from SonarQube. It appears that not all vulnerabilities detected by SonarQube are being included in our import process. This oversight could lead to gaps in our security coverage.

It's crucial that we address these issues promptly to ensure the integrity and security of our releases

**Comment by Nsai1997** [comment]
![Uploading IMG_0921.jpeg…]()

**Comment by kiblik** [comment]
@Nsai1997, thank you for the test and feedback.

Based on [history of SQ parser](https://github.com/DefectDojo/django-DefectDojo/commits/master/dojo/tools/api_sonarqube), the method of how the findings are processed has not been changed since _Jul 21, 2023_. So there is a quite low chance that the mentioned behavior (fetch only selected vulnerabilities) is connected to recent changes.
For me, it looks like the difference between _the default behavior_ and _the available options of the parser_.
Can you please check, that you set `BUG,VULNERABILITY,CODE_SMELL` to `extras` of your tool config as it is described in [documentation](https://documentation.defectdojo.com/integrations/parsers/api/sonarqube/)?

**Comment by Nsai1997** [comment]
Hi Team,

Following a thorough review of the new release, I've identified several issues that require attention regarding the integration of Security tools with Defect Dojo.


1.Login Issues: Some users encounter an internal server error when attempting to log in, while others can access the product without any trouble. Notably, the number of concurrent users accessing the instance does not exceed three.

https://github.com/DefectDojo/django-DefectDojo/assets/46392529/50c9904a-42b7-4efe-8289-a3698ff3883a


2.We have integrated the Defect dojo with the below tools 


2.1.SonarQube :When we integrated the Defect dojo with the sonarQube tool (its tool to tool integration via API import).When we tried importing the vulnerabilites/Security hotspots/Code smells/Bugs out of more than
100 issues only 3 got imported.

So after integration not all vulnerabilities are getting imported after integration in this release.

![image](https://github.com/DefectDojo/django-DefectDojo/assets/46392529/6c810dfb-668d-42a6-967e-7c8cc415a4b1)

Integrated Tools: Vulnerabilities imported from ADO pipelines, including Dependency Check, Trivy Scan, and Trivy Image Scan, are not consistently imported after integration. Only few of the vulnerabilities are getting imported. But for the same configuration we are able to import all vulnerabilities for the below tools in the earlier release


2.2.Dependency check 
2.3.Trivy scan
2.4.Trivy Image scan

3.SonarQube Integration: The option to import security hotspots not locatable within SonarQube.

![image](https://github.com/DefectDojo/django-DefectDojo/assets/46392529/79994bdb-434b-465a-81af-7b19a746a028)

4.Report Feature: The report feature is non-functional. Upon attempting to generate a report by providing a report name, 
selecting inclusion of notes, finding images, and choosing a report type, the page becomes blank after clicking 'run'.

![image](https://github.com/DefectDojo/django-DefectDojo/assets/46392529/65d54080-7a8a-407f-9e42-a05860c11221)


5.Metrics ->Product type metrics :  Even after having lot of vulnerabilites.Everything being displayed here is zero

![image](https://github.com/DefectDojo/django-DefectDojo/assets/46392529/88cb3f8a-ecae-417e-ad3f-5b313a9db70a)

6. Product type count : Its is showing the zero count of the vulnerabilities even having the lot of vulnerabilities

![image](https://github.com/DefectDojo/django-DefectDojo/assets/46392529/f3741fd4-f9fb-4699-b783-ed72894d3da9)

7.Product tag counts : Even Its is showing the zero count of the vulnerabilities even having the lot of vulnerabilities
![image](https://github.com/DefectDojo/django-DefectDojo/assets/46392529/8a74604d-c841-44ff-8c78-9c13e54317bd)

8.Simple metrics :Even Its is showing the zero count of the vulnerabilities even having the lot of vulnerabilities

![image](https://github.com/DefectDojo/django-DefectDojo/assets/46392529/b9a56bb1-4c4f-405f-8fa0-317f07864cdb)


9.Engineer Metrics: The first and last names of users fail to display despite being added

![image](https://github.com/DefectDojo/django-DefectDojo/assets/46392529/15d97000-125a-4ba8-98f9-077c1fc6c7b6)


These issues hinder the effectiveness and functionality of our integration and require immediate attention to ensure seamless operation. Thank you for your prompt action in addressing these concerns.

Best regards

**Comment by Nsai1997** [comment]
> @Nsai1997, thank you for the test and feedback.
> 
> Based on [history of SQ parser](https://github.com/DefectDojo/django-DefectDojo/commits/master/dojo/tools/api_sonarqube), the method of how the findings are processed has not been changed since _Jul 21, 2023_. So there is a quite low chance that the mentioned behavior (fetch only selected vulnerabilities) is connected to recent changes. For me, it looks like the difference between _the default behavior_ and _the available options of the parser_. Can you please check, that you set `BUG,VULNERABILITY,CODE_SMELL` to `extras` of your tool config as it is described in [documentation](https://documentation.defectdojo.com/integrations/parsers/api/sonarqube/)?

Yes I have set the same configuration.Please find the screenshot mentioned above

**Comment by 37b** [comment]
> The PR I mentioned (#10345 ) was in 2.35.1 so yes a fix for the issue was added to that version.
> 
> 
> 
> As I said above:
> 
> **made an attempt at fixing it though the fix wasn't able to be tested**
> 
> because
> 
> **it appears none of the core contributors have access to an on-prem or cloud version of SonarQube**
> 
> 
> 
> so we _believe_ the fix is valid but don't have a way to confirm that. This is one the unfortunate aspects of API integrations with DefectDojo - they are difficult to test and confirm they work as expected unless someone happens to have that API running in a place where it can be tested.
> 
> 
> 
> Unfortunately, we cannot provide any more assurance than the info above.
> 
> 

Fixed for us. Thanks.

**Comment by Nsai1997** [comment]
@37b 
1. Are you able to import all the security hotspots ,Vulnerabilities ,Bugs, code smells for the sonarqube?

For the Other tools as well Are you able to import the all the issues from the other tools.

If so can you please let me know what configuration you have set here 

![image](https://github.com/DefectDojo/django-DefectDojo/assets/46392529/03156e3e-93c9-4e68-82ef-640378f595fc)

**Comment by Nsai1997** [comment]
Hi team,

Can we at least fix for  that importing all vulnerabilities issue so that customers can integrate with their tools to  import all the findings from their security tools such Sonarqube, Dependency check, Trivy scan  ,Trivy Image scan etc.. so that customers can understand how can they use the defect dojo effectively for their organization effectively to track the vulnerabilites , as in the earlier release sonarqube import was not working and for the rest tools import is working fine.But in the latest release we are able to import vulnerabilities all tools but not all vulnerabilities are getting imported.

**Comment by 37b** [comment]
> @37b
> 
> 1. Are you able to import all the security hotspots ,Vulnerabilities ,Bugs, code smells for the sonarqube?
> 
> For the Other tools as well Are you able to import the all the issues from the other tools.
> 
> If so can you please let me know what configuration you have set here
> 
> ![image](https://private-user-images.githubusercontent.com/46392529/337836874-03156e3e-93c9-4e68-82ef-640378f595fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NTM5ODgsIm5iZiI6MTcxNzg1MzY4OCwicGF0aCI6Ii80NjM5MjUyOS8zMzc4MzY4NzQtMDMxNTZlM2UtOTNjOS00ZTY4LTgyZWYtNjQwMzc4ZjU5NWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDEzMzQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5MzhmM2Y1NWQzZDZiMGQ5NDVmZDBjNDA3ZDdlZWY5NDNlYjkxMTQwOGM3ZGZmM2U5ZGRkZTgyN2I3ZjQ2MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.itkEaZijXxZRbx-Mz5W_XaCdl7RpOrrlqXSYogIQphY)

We only import vulns and security hotspots. I have nothing in Extras, but `DD_SONARQUBE_API_PARSER_HOTSPOTS=True` in settings.

I haven't seen any issues in other importers at this point.

**Comment by Nsai1997** [comment]
@37b can you please let me now the exact path under the section where to mention 

DD_SONARQUBE_API_PARSER_HOTSPOTS=True 

as we have multiple sections under the settings.It would be great if you can share the navigation path where to mention it

**Comment by mtesauro** [comment]
@37b 
> 
> Fixed for us. Thanks.

Thanks for confirming the fix.

I'm going to close this issue but feel free to keep the conversation going either here or at [OWASP Slack](https://github.com/DefectDojo/django-DefectDojo/issues/10343#issuecomment-2155710303).
