### ISSUE TITLE
Grading can never return to A

### ISSUE THREAD

**Issue by barbich** [DefectDojo/django-DefectDojo#1034]
**Bug description**
The grading for a product does(can) never return to "A" once all findings are closed.

**Steps to reproduce**
1. Take a product with grading different from 'A'
2. Close all Findings
3. Grade stays stuck to latest calculate value

**Expected behavior**
If all findings are closed the grade for a product should be 'A'

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
not relevant

**Additional context** (optional)
I believe the issue is located in utils.py calculate_grade() . The query for "severity_values" will return nothing if (for example) all findings are in a closed(inactive) state which will therefore not trigger a recalculation of the grade (line 1606 in utils.py).

**Comment by aaronweaver** [comment]
@barbich can you retest?
