### ISSUE TITLE
MySQL to Postgres migration manual

### ISSUE THREAD

**Issue by kiblik** [DefectDojo/django-DefectDojo#10359]
Because the support of MySQL in DD will be [stopped soon](https://github.com/DefectDojo/django-DefectDojo/discussions/9690), many users will look for manual/documentation, on how to migrate their setup (like [here](https://owasp.slack.com/archives/C2P5BA8MN/p1717609900301399?thread_ts=1717587117.831149&cid=C2P5BA8MN)).
It is possible to find steps that include extending `DATABASES` [definition](https://pythonfusion.com/switch-database-django/). I do not think it is easy to edit for everybody.
It is the reason why it might be a good idea to prepare some migration manual.

**Comment by manuel-sommer** [comment]
Maybe this helps https://github.com/DefectDojo/django-DefectDojo/discussions/9480

**Comment by mtesauro** [comment]
Added a summary of what @kiblik posted in OWASP Slack to the GH Discussion manual-sommer linked and answered on that Slack thread as well pointing people to the GH discussion which now has 3+ methods to try.

**Comment by StephanPillhofer** [comment]
I think this issue can be closed, I posted an up-to-date step-by-step guide on how to do the migration [here.](https://github.com/DefectDojo/django-DefectDojo/discussions/9480#discussioncomment-10202618)
