### ISSUE TITLE
Remove Localhost in email notification send.

### ISSUE THREAD

**Issue by J1nchur1k1** [DefectDojo/django-DefectDojo#10364]
I have enabled the Email notification feature, but the notification sent is having the hyperlink of http://localhost:8080. which needs to be replaced by the IP of the server.

![Screenshot 2024-06-10 101120](https://github.com/DefectDojo/django-DefectDojo/assets/53573052/d1f72434-531e-4e23-af89-e0b11897d81a)

**Comment by kiblik** [comment]
URL in the notification is set based on the environmental variable `DD_SITE_URL` (needed in `uwsgi` and `celeryworker`). For helm [site_url](https://github.com/DefectDojo/django-DefectDojo/blob/cfdc7cdcd33032b8c142f8a9edff16e1e627d3be/helm/defectdojo/values.yaml#L50).

**Comment by kiblik** [comment]
> > URL in the notification is set based on the environmental variable `DD_SITE_URL` (needed in `uwsgi` and `celeryworker`). For helm [site_url](https://github.com/DefectDojo/django-DefectDojo/blob/cfdc7cdcd33032b8c142f8a9edff16e1e627d3be/helm/defectdojo/values.yaml#L50).
> 
> We already did the changes but still we are getting the same notification

Can you confirm, that you set it in both containers, please?

**Comment by J1nchur1k1** [comment]
> > > URL in the notification is set based on the environmental variable `DD_SITE_URL` (needed in `uwsgi` and `celeryworker`). For helm [site_url](https://github.com/DefectDojo/django-DefectDojo/blob/cfdc7cdcd33032b8c142f8a9edff16e1e627d3be/helm/defectdojo/values.yaml#L50).
> > 
> > 
> > We already did the changes but still we are getting the same notification
> 
> Can you confirm, that you set it in both containers, please?

Ok let me check and get back to you

**Comment by J1nchur1k1** [comment]
> ll we are getting the same notifica

Thanks, it is working now.
Really appricate your help.
