### ISSUE TITLE
Acunetix report raised error 500

### ISSUE THREAD

**Issue by ptitkosmos** [DefectDojo/django-DefectDojo#10370]
**Bug description**
I automated reports from Acunetix 360 to be imported into defect dojo. One vulnerability make the import crash due to no classification provided by Acunetix

**Steps to reproduce**
Get an Acunetix 360 json report with no "classification" property in a vulnerability
Import the scan into Defect Dojo
Got "argument of type 'NoneType' is not iterable"

**Expected behavior**
Field should be tested and related code bypassed

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - DefectDojo version : v. 2.33.2

**Screenshots**
Partial report:
![image](https://github.com/DefectDojo/django-DefectDojo/assets/20866643/3951cb39-0250-4fc6-ad42-89e85ba83e2a)
Line to fix (20): 
![image](https://github.com/DefectDojo/django-DefectDojo/assets/20866643/a62bddd9-5a98-404c-93f2-94a1bb3bd759)

**Comment by manuel-sommer** [comment]
Can we please close this ticket?
