### ISSUE TITLE
dockers initialize but ip:8080 returns "Internal Server Error" 

### ISSUE THREAD

**Issue by mitraed** [DefectDojo/django-DefectDojo#1039]
**Bug description**
when running docker compose up all dockers initialize but ip:8080 returns "Internal Server Error" on web .

logs :
nginx_1         | 172.16.200.4 - - [11/Apr/2019:20:03:53 +0000] "GET / HTTP/1.1" 500 32 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "-"
uwsgi_1         | --- **no python application found**, check your startup logs for errors ---
uwsgi_1         | [pid: 1|app: -1|req: -1/42] 172.16.200.4 () {42 vars in 749 bytes} [Thu Apr 11 20:03:53 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
nginx_1         | 172.16.200.4 - - [11/Apr/2019:20:03:54 +0000] "GET /favicon.ico HTTP/1.1" 500 32 "http://10.3.22.87:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "-"
uwsgi_1         | --- no python application found, check your startup logs for errors ---
uwsgi_1         | [pid: 1|app: -1|req: -1/43] 172.16.200.4 () {44 vars in 720 bytes} [Thu Apr 11 20:03:54 2019] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)

**Environment information**
[root@localhost ~]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by aaronweaver** [comment]
Related to #1036 closing. PR coming shortly or use the docker branch.
