### ISSUE TITLE
add feature to connect existing jira ticket to a finding

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#1040]
Sometimes when uploading a scan report into DD results in some findings that are already in JIRA.

Currently this could be handled in different ways:
- Push them to JIRA anyway and close them in JIRA as duplicates.
- Just leave them hanging around in DefectDojo and update manually when resolved in JIRA
- Mark them as out-of-scope or inactive or ... in DefectDojo

I was thinking maybe it would be nice to be able to connect an existing JIRA ticket to a DD Finding?

I haven't looked at implementation details yet, but it could be as simple as "making the jira issue id field" editable on the finding edit screen?

Any thoughts?

**Comment by aaronweaver** [comment]
I've thought this as well though the one issue will be that potentially the JIra ticket won't have the same information. An update to DD might change important details on the Jira side. Since it's a manual option that might be ok, as long as the user understands it might over write existing data.

**Comment by madchap** [comment]
If the JIRA id was manually put in Dojo (via API for example, or via the UI when it will exist), then further attempt to automatically sync jira and dojo for this issue should not take place.

Maybe an immediate workaround to allow people inputting manually through the API would be to make sure the "Push to JIRA" checkbox does not get re-ticked automatically. This way, the current logic `if push_to_jira` would be skipped?

**Comment by madchap** [comment]
So I have been using the API to `patch` the finding with the jira information. This is painful :(

Also, and maybe this is specific to how we use dojo, once the jira is created (either manually or through push), I never had a case where pushing over an exising jira from DefectDojo's finding screen made sense (so I am glad 1324 was merged :))

A field would be super welcome to enter the JIRA key (that would of course fetch the `issue_id` automatically).

**Comment by madchap** [comment]
bump before the bot comes before me.
