### ISSUE TITLE
sync with tenable nessus latest version

### ISSUE THREAD

**Issue by johnfelipe** [DefectDojo/django-DefectDojo#10453]
https://192.168.20.30:10443/#/settings/my-account/api-keys

![SNAG-0224](https://github.com/DefectDojo/django-DefectDojo/assets/428820/87c9639f-7590-437e-83b0-deebf096925b)

![SNAG-0225](https://github.com/DefectDojo/django-DefectDojo/assets/428820/76e20025-c041-4534-87fe-4ca72256ba08)
already revoked

---

http://192.168.20.22:8080/tool_type/7/edit

![SNAG-0226](https://github.com/DefectDojo/django-DefectDojo/assets/428820/d9454b6b-4d03-4a2e-a158-be0b3efd50aa)

http://192.168.20.22:8080/tool_config/2/edit

![SNAG-0227](https://github.com/DefectDojo/django-DefectDojo/assets/428820/5dcdcdb8-9143-4830-b361-16668beea4e1)

http://192.168.20.22:8080/product/38/edit_api_scan_configuration/3

![SNAG-0228](https://github.com/DefectDojo/django-DefectDojo/assets/428820/98cf10df-c688-4340-9679-89eee5340394)

https://192.168.20.30:10443/#/scans/reports/13/hosts

![SNAG-0229](https://github.com/DefectDojo/django-DefectDojo/assets/428820/82df671a-39c0-401c-aefa-d4cb5ed6c1aa)

![SNAG-0230](https://github.com/DefectDojo/django-DefectDojo/assets/428820/a84a4fd7-17cc-48f7-a693-1607918a7e93)

but when im trying to sync
![SNAG-0231](https://github.com/DefectDojo/django-DefectDojo/assets/428820/62e69f6e-4de7-4ed2-a822-5ee7837e7172)

show this:

![SNAG-0232](https://github.com/DefectDojo/django-DefectDojo/assets/428820/82c047e3-976b-49a4-b5c9-175be3bb9186)

    the Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead. See https://www.w3.org/TR/powerful-features/#potentially-trustworthy-origin and https://html.spec.whatwg.org/#the-cross-origin-opener-policy-header.

**Comment by kiblik** [comment]
Hi @johnfelipe,
DD supports only "file version" of reports from Tenable: https://documentation.defectdojo.com/integrations/parsers/file/tenable/
Only the following tools are supported via API: https://documentation.defectdojo.com/integrations/parsers/api/

**Comment by johnfelipe** [comment]
is in roadmap put tenable nessus via API?

**Comment by mtesauro** [comment]
@johnfelipe TBH, No.

API integrations with 3rd party vendors, especially commercial vendors, are particularly tricky/difficult to have since we cannot adequately test them when taking PRs and an open source project maintaining a license to a commercial product isn't feasible.

You can look at my posts in GH discussions to see where the DefectDojo maintainers are headed and what we're thinking about the future if you're curious:
https://github.com/DefectDojo/django-DefectDojo/discussions?discussions_q=author%3Amtesauro

**Comment by manuel-sommer** [comment]
I guess this can be closed, right?
