### ISSUE TITLE
docker-compose.yml not found

### ISSUE THREAD

**Issue by fabiopires** [DefectDojo/django-DefectDojo#1046]
**Bug description**
The last merge removed the `docker-compose.yml` file from the repository, thus preventing users to simply run `docker-compose up`, as mentioned on the instructions.

The solution is either updating the instructions, or running:
`docker-compose -f docker-compose_base.yml -f docker-compose_uwsgi-release.yml up`

**Steps to reproduce**
1. Run : docker-compose up
```
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
```
**Expected behavior**
Docker should initialize as normal.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 18.04
 - DefectDojo version: b36f03b: Entrypoint fix for docker (#1041) [2019-04-11 21:03:41 -0400]

**Comment by aaronweaver** [comment]
Thanks updated the [docs](https://defectdojo.readthedocs.io/en/latest/getting-started.html#docker-compose-install).
