### ISSUE TITLE
SLA Notification

### ISSUE THREAD

**Issue by J1nchur1k1** [DefectDojo/django-DefectDojo#10463]
### Discussed in https://github.com/DefectDojo/django-DefectDojo/discussions/10412

<div type='discussions-op-text'>

<sup>Originally posted by **J1nchur1k1** June 17, 2024</sup>
I have created notification, and while testing I created one Critical vulnerabilities, but I am not getting notification on it.
can anyone tell me after how much time these mails are being sent.
![image](https://github.com/DefectDojo/django-DefectDojo/assets/53573052/8840420e-ab12-4b80-959c-cd9783554c79)
</div>

**Comment by manuel-sommer** [comment]
I guess you should rather ask on the slack channel.
