### ISSUE TITLE
Segmentation fault with Version 2.35.3 and Fargate

### ISSUE THREAD

**Issue by MarianG** [DefectDojo/django-DefectDojo#10477]
We deployed the version 2.35.3 of DefectDojo on AWS ECS with Fargate (1.4) and the worker and beat container were running fine.
However, we had issues with the django container that run into segmentation faults.
This resulted in the ECS Task restarting over and over again. In the logs we received the message `!!! uWSGI process 14479 got Segmentation Fault !!!`
**Steps to reproduce**
1. Go to AWS ECS create a cluster 
2. Build the containers with version 2.35.3
3. deploy the containers on Fargate

**Expected behavior**
Task are executed with containers and Dojo application is starting

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo
- [x] Container build + AWS Fargate

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo version (see footer) or commit message: 2.35.3

**Logs** 
Use `docker-compose logs` (or similar, depending on your deployment method) to get the logs and add the relevant sections here showing the error occurring (if applicable).

**Additional context** (optional)
It seems that on some environments the wsgi process has trouble with memory management, e.g. https://github.com/pytorch/pytorch/issues/42125

**Comment by mtesauro** [comment]
@MarianG 

Unfortunately, AWS Fargate isn't a supported install option so there's not much the project can say about the issue you reported as we don't have tests that cover that situation nor any real familiarity with AWS Fargate.

From the README.md:
![image](https://github.com/DefectDojo/django-DefectDojo/assets/3422419/5faad1a2-b355-4d7f-8e2a-0dd4ea79efad)

You _may_ be able to get assistance by asking this on the OWASP Slack in the #defectdojo channel - details on joining Slack are at https://github.com/DefectDojo/django-DefectDojo?tab=readme-ov-file#community-getting-involved-and-updates

**Comment by NilsKlawitter** [comment]
We are facing the same issue with 2.36.6. Do do happen to have found a solution @MarianG ?

**Comment by MarianG** [comment]
No, not really.
We tested several combinations of alpine image and python but it seems that the change from openssl1.1 to openssl3 was kind of the problem. We also tested the openssl1.1.1-compat package of alpine but it didnt help either.

Finally, we switched to the debian image that is still working for us

**Comment by sanjeevh** [comment]
@MarianG  @NilsKlawitter  by image you mean container image not AMI right ? I am just starting to explore feasibility of using DD on aws fargate, can you please advise if your solution is working and stable. any pointers will be highly appreciated. thanks.

**Comment by MarianG** [comment]
We are currently running a test environment on AWS Fargate with DefectDojo 3.0.1 and it is working with the alpine container images.
So, I am not sure when it was fixed back in the days, but there were some versions which were incompatible with alpine and fargate.
