### ISSUE TITLE
to start the project it's  a take a long time

### ISSUE THREAD

**Issue by abdoqaidhaidar** [DefectDojo/django-DefectDojo#10515]
Hi
i run the project before but when i close my device and come back the next day to runn the project via 
./dc-build.sh 
it's take a long time , may be 4 hours to run 

it's just show things like this
django-defectdojo-master-celerybeat-1    | [04/Jul/2024 06:07:22] INFO [celery.beat:278] Scheduler: Sending due task dedupe-delete (dojo.tasks.async_dupe_delete)
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:07:22] INFO [celery.worker.strategy:161] Task dojo.tasks.async_dupe_delete[95519682-75d1-4a61-8287-e93ca4774d1f] received
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:07:22] INFO [celery.app.trace:128] Task dojo.tasks.async_dupe_delete[95519682-75d1-4a61-8287-e93ca4774d1f] succeeded in 0.05016916399472393s: None
django-defectdojo-master-celerybeat-1    | [04/Jul/2024 06:08:22] INFO [celery.beat:278] Scheduler: Sending due task dedupe-delete (dojo.tasks.async_dupe_delete)
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:08:22] INFO [celery.worker.strategy:161] Task dojo.tasks.async_dupe_delete[82140fc7-49cc-4773-aa93-c27de224d6bc] received
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:08:22] INFO [celery.app.trace:128] Task dojo.tasks.async_dupe_delete[82140fc7-49cc-4773-aa93-c27de224d6bc] succeeded in 0.02522215999488253s: None
django-defectdojo-master-celerybeat-1    | [04/Jul/2024 06:09:22] INFO [celery.beat:278] Scheduler: Sending due task dedupe-delete (dojo.tasks.async_dupe_delete)
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:09:22] INFO [celery.worker.strategy:161] Task dojo.tasks.async_dupe_delete[269e3851-e222-47ba-a189-102d30a752d1] received
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:09:22] INFO [celery.app.trace:128] Task dojo.tasks.async_dupe_delete[269e3851-e222-47ba-a189-102d30a752d1] succeeded in 0.05195289800030878s: None
django-defectdojo-master-postgres-1      | 2024-07-04 06:09:52.604 UTC [26] LOG:  checkpoint starting: time
django-defectdojo-master-postgres-1      | 2024-07-04 06:09:53.483 UTC [26] LOG:  checkpoint complete: wrote 11 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.828 s, sync=0.005 s, total=0.880 s; sync files=10, longest=0.005 s, average=0.001 s; distance=4 kB, estimate=4 kB; lsn=0/26AFBF8, redo lsn=0/26AFBC0
django-defectdojo-master-celerybeat-1    | [04/Jul/2024 06:10:22] INFO [celery.beat:278] Scheduler: Sending due task dedupe-delete (dojo.tasks.async_dupe_delete)
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:10:22] INFO [celery.worker.strategy:161] Task dojo.tasks.async_dupe_delete[4336a539-023a-4ad2-90e1-9df7b8ee7e01] received
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:10:22] INFO [celery.app.trace:128] Task dojo.tasks.async_dupe_delete[4336a539-023a-4ad2-90e1-9df7b8ee7e01] succeeded in 0.04733875899546547s: None
django-defectdojo-master-celerybeat-1    | [04/Jul/2024 06:11:22] INFO [celery.beat:278] Scheduler: Sending due task dedupe-delete (dojo.tasks.async_dupe_delete)
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:11:22] INFO [celery.worker.strategy:161] Task dojo.tasks.async_dupe_delete[a7b43712-fabe-4645-9e68-f208f646c2aa] received
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:11:22] INFO [celery.app.trace:128] Task dojo.tasks.async_dupe_delete[a7b43712-fabe-4645-9e68-f208f646c2aa] succeeded in 0.04769722700439161s: None
django-defectdojo-master-celerybeat-1    | [04/Jul/2024 06:12:22] INFO [celery.beat:278] Scheduler: Sending due task dedupe-delete (dojo.tasks.async_dupe_delete)
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:12:22] INFO [celery.worker.strategy:161] Task dojo.tasks.async_dupe_delete[01fd6574-7787-4475-ae9a-86e5c5392453] received
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:12:22] INFO [celery.app.trace:128] Task dojo.tasks.async_dupe_delete[01fd6574-7787-4475-ae9a-86e5c5392453] succeeded in 0.05397990100027528s: None
django-defectdojo-master-celerybeat-1    | [04/Jul/2024 06:13:22] INFO [celery.beat:278] Scheduler: Sending due task dedupe-delete (dojo.tasks.async_dupe_delete)
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:13:22] INFO [celery.worker.strategy:161] Task dojo.tasks.async_dupe_delete[c1d3f5e4-8d81-4d9d-8daf-334658f82d3b] received
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:13:22] INFO [celery.app.trace:128] Task dojo.tasks.async_dupe_delete[c1d3f5e4-8d81-4d9d-8daf-334658f82d3b] succeeded in 0.024056804002611898s: None
django-defectdojo-master-celerybeat-1    | [04/Jul/2024 06:14:22] INFO [celery.beat:278] Scheduler: Sending due task dedupe-delete (dojo.tasks.async_dupe_delete)
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:14:22] INFO [celery.worker.strategy:161] Task dojo.tasks.async_dupe_delete[6f4af533-7d69-42ad-b503-a0d388819caa] received
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:14:22] INFO [celery.app.trace:128] Task dojo.tasks.async_dupe_delete[6f4af533-7d69-42ad-b503-a0d388819caa] succeeded in 0.05401885900209891s: None
django-defectdojo-master-celerybeat-1    | [04/Jul/2024 06:15:22] INFO [celery.beat:278] Scheduler: Sending due task dedupe-delete (dojo.tasks.async_dupe_delete)
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:15:22] INFO [celery.worker.strategy:161] Task dojo.tasks.async_dupe_delete[09416ced-b4d4-4a9d-875d-04c385640162] received
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:15:22] INFO [celery.app.trace:128] Task dojo.tasks.async_dupe_delete[09416ced-b4d4-4a9d-875d-04c385640162] succeeded in 0.025804536999203265s: None
django-defectdojo-master-celerybeat-1    | [04/Jul/2024 06:16:22] INFO [celery.beat:278] Scheduler: Sending due task dedupe-delete (dojo.tasks.async_dupe_delete)
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:16:22] INFO [celery.worker.strategy:161] Task dojo.tasks.async_dupe_delete[d5619c13-d852-4f59-8281-7d3b65e41b8e] received
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:16:22] INFO [celery.app.trace:128] Task dojo.tasks.async_dupe_delete[d5619c13-d852-4f59-8281-7d3b65e41b8e] succeeded in 0.051120261996402405s: None
django-defectdojo-master-celerybeat-1    | [04/Jul/2024 06:17:22] INFO [celery.beat:278] Scheduler: Sending due task dedupe-delete (dojo.tasks.async_dupe_delete)
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:17:22] INFO [celery.worker.strategy:161] Task dojo.tasks.async_dupe_delete[7c51d5c0-c879-44e8-baf1-a5edc4532c57] received
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:17:22] INFO [celery.app.trace:128] Task dojo.tasks.async_dupe_delete[7c51d5c0-c879-44e8-baf1-a5edc4532c57] succeeded in 0.048265119999996386s: None
django-defectdojo-master-celerybeat-1    | [04/Jul/2024 06:18:22] INFO [celery.beat:278] Scheduler: Sending due task dedupe-delete (dojo.tasks.async_dupe_delete)
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:18:22] INFO [celery.worker.strategy:161] Task dojo.tasks.async_dupe_delete[d0bf82d6-d906-4b0a-8421-abb98a4abab2] received
django-defectdojo-master-redis-1         | 1:M 04 Jul 2024 06:18:22.437 * 100 changes in 300 seconds. Saving...
django-defectdojo-master-redis-1         | 1:M 04 Jul 2024 06:18:22.438 * Background saving started by pid 21
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:18:22] INFO [celery.app.trace:128] Task dojo.tasks.async_dupe_delete[d0bf82d6-d906-4b0a-8421-abb98a4abab2] succeeded in 0.047370763997605536s: None
django-defectdojo-master-redis-1         | 21:C 04 Jul 2024 06:18:22.459 * DB saved on disk
django-defectdojo-master-redis-1         | 21:C 04 Jul 2024 06:18:22.461 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
django-defectdojo-master-redis-1         | 1:M 04 Jul 2024 06:18:22.543 * Background saving terminated with success
django-defectdojo-master-celerybeat-1    | [04/Jul/2024 06:19:22] INFO [celery.beat:278] Scheduler: Sending due task dedupe-delete (dojo.tasks.async_dupe_delete)
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:19:22] INFO [celery.worker.strategy:161] Task dojo.tasks.async_dupe_delete[9cfb289c-932e-45bd-b069-5995c0184345] received
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:19:22] INFO [celery.app.trace:128] Task dojo.tasks.async_dupe_delete[9cfb289c-932e-45bd-b069-5995c0184345] succeeded in 0.04852304000087315s: None
django-defectdojo-master-celerybeat-1    | [04/Jul/2024 06:20:22] INFO [celery.beat:278] Scheduler: Sending due task dedupe-delete (dojo.tasks.async_dupe_delete)
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:20:22] INFO [celery.worker.strategy:161] Task dojo.tasks.async_dupe_delete[159ce6a7-b4f7-49a5-9957-81089bae9724] received
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:20:22] INFO [celery.app.trace:128] Task dojo.tasks.async_dupe_delete[159ce6a7-b4f7-49a5-9957-81089bae9724] succeeded in 0.05086795300303493s: None
django-defectdojo-master-celerybeat-1    | [04/Jul/2024 06:21:22] INFO [celery.beat:278] Scheduler: Sending due task dedupe-delete (dojo.tasks.async_dupe_delete)
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:21:22] INFO [celery.worker.strategy:161] Task dojo.tasks.async_dupe_delete[7454aa97-62fe-4053-ab2c-81c11e5e05ee] received
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:21:22] INFO [celery.app.trace:128] Task dojo.tasks.async_dupe_delete[7454aa97-62fe-4053-ab2c-81c11e5e05ee] succeeded in 0.07640753799933009s: None
django-defectdojo-master-celerybeat-1    | [04/Jul/2024 06:22:22] INFO [celery.beat:278] Scheduler: Sending due task dedupe-delete (dojo.tasks.async_dupe_delete)
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:22:22] INFO [celery.worker.strategy:161] Task dojo.tasks.async_dupe_delete[629bac14-23fb-4c3e-87a0-0730cfc2b7b0] received
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:22:22] INFO [celery.app.trace:128] Task dojo.tasks.async_dupe_delete[629bac14-23fb-4c3e-87a0-0730cfc2b7b0] succeeded in 0.046505268997862004s: None
django-defectdojo-master-celerybeat-1    | [04/Jul/2024 06:23:22] INFO [celery.beat:278] Scheduler: Sending due task dedupe-delete (dojo.tasks.async_dupe_delete)
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:23:22] INFO [celery.worker.strategy:161] Task dojo.tasks.async_dupe_delete[718a10b5-50b3-4133-b470-af026c07fd28] received
django-defectdojo-master-celeryworker-1  | [04/Jul/2024 06:23:22] INFO [celery.app.trace:128] Task dojo.tasks.async_dupe_delete[718a10b5-50b3-4133-b470-af026c07fd28] succeeded in 0.050510880995716434s: None

**Comment by mtesauro** [comment]
@abdoqaidhaidar 
Given the information you provided, it's not possible to provide much help or advice.

You don't mention how you've deployed DefectDojo nor with what resources. I could guess you're running this on a raspberry pi and decide that's why it's running so slow. I have no real information beyond some log output.

I'd also suggest that you as these kind of questions on OWASP Slack on the #defectdojo channel as it appears to be something around how you deployed/configured DefectDojo versus a true issue with the software running the app.

You can get info on joining OWASP's Slack at https://github.com/DefectDojo/django-DefectDojo?tab=readme-ov-file#community-getting-involved-and-updates
