### ISSUE TITLE
xray add tool

### ISSUE THREAD

**Issue by abdoqaidhaidar** [DefectDojo/django-DefectDojo#10523]
**xray**
xray scan for cves
https://github.com/chaitin/xray/

**Sample File**
[sdsdc.json](https://github.com/user-attachments/files/16119707/sdsdc.json)

**Comment by manuel-sommer** [comment]
@abdoqaidhaidar ,

this is not a vaild json file as it is malformed. Please upload a valid json file here.

**Comment by abdoqaidhaidar** [comment]
[xray.json](https://github.com/user-attachments/files/16147926/xray.json)

**Comment by xingyunliuyue** [comment]
can add tools like nuclei
https://github.com/projectdiscovery/nuclei

**Comment by manuel-sommer** [comment]
I just checked the json output of xray. Before it makes sense to write a parser here, I need things to get clarified first:

- How can I determine the severity here?
- Do you have an example file where "param": {} is not empty?
- Which parameter can I choose as the name of the finding? 

To me, it is quite hard to write a parser here as details are missing. Is it possible to make the output more verbose?

**Comment by manuel-sommer** [comment]
Reminder @xingyunliuyue .

**Comment by manuel-sommer** [comment]
I guess this can be closed @mtesauro.  No Response
