### ISSUE TITLE
"Unsupported extension" issue due to typo on supported file formats

### ISSUE THREAD

**Issue by MarMoriMem** [DefectDojo/django-DefectDojo#10529]
**Bug description**

When trying to attach a file to a Finding (within a Finding, clicking on "Manage Files"), I get an error saying the following:
Unsupported extension. Supported extensions are as follows: .txt, .pdf, .json, .xml, .csv, .yml, .png, .jpeg, .sarif, .xslx, .doc, .html, .js, .nessus, .zip

The issue being file type ".xslx" - this is a typo of the Excel format, ".xlsx"

This means you are unable to attach files which are of .xlsx format.

I believe that the issue is located within the file:
dojo/settings/settings.dist.py
On line 277-279:
`    # List of acceptable file types that can be uploaded to a given object via arbitrary file upload
    DD_FILE_UPLOAD_TYPES=(list, ['.txt', '.pdf', '.json', '.xml', '.csv', '.yml', '.png', '.jpeg',
                                 '.sarif', '.xslx', '.doc', '.html', '.js', '.nessus', '.zip']),`

**Steps to reproduce**
1. Go to any Finding
2. Click on Manage Files from the hamburger icon in the top right
3. Try to upload a .xlsx file

**Expected behavior**
I expect to be able to upload Excel sheets.

**Screenshots**
Please see attached.
![Screenshot 2024-07-05 140937](https://github.com/DefectDojo/django-DefectDojo/assets/175004539/7a350619-04e0-43f7-9e0c-b6cef391c1f4)

**Comment by mtesauro** [comment]
@MarMoriMem 
Looks like @manuel-sommer has already created a PR for to fix this typo.

In the mean time, you can override the default set of allowed files by either setting an env variable for DD_FILE_UPLOAD_TYPES or override the value in local_settings.py

**Comment by manuel-sommer** [comment]
This was already released @mtesauro.
It would be great if you can always close the issues after merge / release
