### ISSUE TITLE
check for new scanner output files

### ISSUE THREAD

**Issue by abdoqaidhaidar** [DefectDojo/django-DefectDojo#10554]
hi 
please when developed new scanner tools test all others tool with latest version becuse some versions of it checnge the structer of json files and then the output don't show in defectdojo

**Comment by mtesauro** [comment]
@abdoqaidhaidar 
Thanks for opening this issue.

As a community run open source project, every user of DefectDojo is empowered to help make it better.

In your example, a change to the output of a particular tool may only been seen by a small portion of the overall DefectDojo Community so the best way to get scanners updated is to provide sanitized versions of the files as Github issues and note which fields are missing. Ideally, we'd love to have a PR but if you're not a Python code, just providing an example file makes updates possible.

At 179+ security tools, it's not possible for the core contributors to run all 179+ tools - instead we rely on the community to let us know and help us enhance tool coverage over time as scanner output changes.

HTH

**Comment by manuel-sommer** [comment]
Hi @abdoqaidhaidar,
please provide exact details, than I also might help if changes don't require too much affort. Otherwise, please let's close this issue @mtesauro

**Comment by abdoqaidhaidar** [comment]
please addd integRATIOON FOR XRAY SCANNER

https://github.com/chaitin/xray/

Sample File
https://github.com/user-attachments/files/16119707/sdsdc.json
https://github.com/user-attachments/files/16147926/xray.json

**Comment by manuel-sommer** [comment]
Hi @abdoqaidhaidar ,
is this issue https://github.com/DefectDojo/django-DefectDojo/issues/10523 a duplicate?
If yes, please close one of both issues. Openening several issues with the same topic does not speed things up. In fact, it does slow the process down due to the complexity and the management of issues.

**Comment by mtesauro** [comment]
@manuel-sommer I agree this is a duplicate. I'll close this and we can work off #10523 going forward. Since you reference it here, you can always come back to this issue if the attached files are of use.
