### ISSUE TITLE
Directory '.[mysql]' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

### ISSUE THREAD

**Issue by kibnelbachyr** [DefectDojo/django-DefectDojo#1056]
**Bug description**

Hi DefectDojo's community,

I am attempting to deploy/install DefectDojo's solution on a Linux environment following this documentation : https://github.com/DefectDojo/django-DefectDojo/wiki/DefectDojo-Installation-Guide-Ubuntu-Desktop-16.04.2, but I have some errors in the "Installing DefectDojo Django application" step just after running the ./setup.bash 
* Can you advice please?

Thank you ! 

==========
Installing DefectDojo Django application
===========================================
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
The directory '/home/adminuser/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/adminuser/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages (19.0.3)
sudo: unable to resolve host LinuxUbuntuVM
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Directory '.[mysql]' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
/home/adminuser/django-DefectDojo/entrypoint_scripts/os/linux.sh: line 257: entrypoint_scripts/common/setup-superuser.expect: No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
/home/adminuser/django-DefectDojo/entrypoint_scripts/os/linux.sh: line 279: cd: components: No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory

**Steps to reproduce**
https://github.com/DefectDojo/django-DefectDojo/wiki/DefectDojo-Installation-Guide-Ubuntu-Desktop-16.04.2

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [x] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 16.04.6 LTS

**Console logs** 
[DefectDojoInstall-bug.txt](https://github.com/DefectDojo/django-DefectDojo/files/3086940/DefectDojoInstall-bug.txt)

**Comment by kibnelbachyr** [comment]
After changing user to root and running the ./setup.bash : 


=======
Installing DefectDojo Django application
==============================================================================
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages (19.0.3)
sudo: unable to resolve host zafaforgsvcs03
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Directory '.[mysql]' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
/root/django-DefectDojo/entrypoint_scripts/os/linux.sh: line 257: entrypoint_scripts/common/setup-superuser.expect: No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
/root/django-DefectDojo/entrypoint_scripts/os/linux.sh: line 279: cd: components: No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory

DEBUG JUNK:
PROMPT is true
====>
INSTALL_OS is linux-gnu

**Comment by dr3dd589** [comment]
hello, @kibnelbachyr, I think this issue is relevant to this #851 and this issue is fixed in the new updated version 1.5.4.
Can you recheck now?

**Comment by aaronott** [comment]
I was receiving this same error then realized it looks like the config-vars.sh assumes that you are installing in /opt/dojo/django-DefectDojo. When I moved the project to the /opt/dojo directory, I was able to get further.

I'm now working on other errors during the install.

**Comment by ppiotr3k** [comment]
Hi @aaronott, Docker and Kubernetes installations are preferred deployment ways for the time being.
Official DefectDojo is available on [Read The Docs](https://defectdojo.readthedocs.io/en/latest/getting-started.html#docker-compose-install).
Do you have specific needs requiring a manual installation, and not using Docker for example?
