### ISSUE TITLE
new sonatype scanner

### ISSUE THREAD

**Issue by johnfelipe** [DefectDojo/django-DefectDojo#10576]
Release 174
Powered by Sonatype IQ Server

![SNAG-0466](https://github.com/user-attachments/assets/35b955bb-aae6-4e77-b159-bf0374ef0c98)

[TNC_PrimeRead-build-f2c3b683f67343329c446f2c3847e447.spdx.json](https://github.com/user-attachments/files/16253388/TNC_PrimeRead-build-f2c3b683f67343329c446f2c3847e447.spdx.json)

**Comment by mtesauro** [comment]
@johnfelipe FWIW, DefectDojo supports CycloneDX which I see as a supported output.

https://documentation.defectdojo.com/integrations/parsers/file/cyclonedx/

So, while we could add support for SPDX, it seems somewhat unnecessary.

**Comment by manuel-sommer** [comment]
Can we close this issue then, @mtesauro ?
