### ISSUE TITLE
how can export sonatype with latest version

### ISSUE THREAD

**Issue by johnfelipe** [DefectDojo/django-DefectDojo#10575]
https://github.com/DefectDojo/django-DefectDojo/blob/master/unittests/scans/sonatype/many_vulns.json

![SNAG-0466](https://github.com/user-attachments/assets/34c0c68d-e9c4-4818-9a5f-20f565c010d6)

Sonatype IQ Server, as of version 174, does not have a built-in feature to directly export JSON files of its data, such as component details, policies, or scan results.

how can export in sonatype correct json?

**Comment by manuel-sommer** [comment]
@mtesauro I guess this is a duplicate to this: https://github.com/DefectDojo/django-DefectDojo/issues/10576
It looks like you figured it out. But otherwise you should rather ask the support of Sonatype. This is the wrong space.

**Comment by johnfelipe** [comment]
I think JSON file with new builds of sonatype is totally different to default and example JSON.
I think, really need to be new JSON file using latest builds of scanner

**Comment by mtesauro** [comment]
@johnfelipe @manuel-sommer 

As I said in #10576:

FWIW, DefectDojo supports CycloneDX which I see as a supported output.

https://documentation.defectdojo.com/integrations/parsers/file/cyclonedx/

So, while we could add support for SPDX, it seems somewhat unnecessary.

**Comment by manuel-sommer** [comment]
Can we close this issue then @mtesauro ?
