### ISSUE TITLE
Import Aqua Scan with sensitive datas

### ISSUE THREAD

**Issue by kzzz1** [DefectDojo/django-DefectDojo#10585]
**Bug description**
We are integrating Aqua Scan to DefectDojo. The AquaScanner scans for vulnerabilities, but also for sensitive datas, and those appear on the scan report. When I Import the scan manually in the Defect-dojo UI, I have an error 'NoneType'. Also, when this happens, the scan results is still added to the engagement, but with 0 findings in it (which is not the case).

**Steps to reproduce**
1. Scan an image with the aquascanner with sensitive datas in it (I scanned Juice-shop for example). Take the json file.
2. Import the Aqua scan results to defect-dojo
3. I have this error in the UI
![image](https://github.com/user-attachments/assets/c73d950d-1bc8-46a4-a9e7-21ea5d8a134f)
 
I looked in the logs, and it looks like the Aqua parser is iterating over each vulnerabilities of each resources, but the sensitive datas don't have that key, they have sensitive_data-items instead. 
![image](https://github.com/user-attachments/assets/2bde4d89-96d8-4f7f-98fe-32b5e3a61a34)

![image](https://github.com/user-attachments/assets/4c18aa9e-dee8-4648-bb6a-5a2bc6b6688c)

**Expected behavior**
The Aqua parser can handle an Aqua Scan having sensitive datas in it.

I also think that when that kind of error occurs, it should be better to not add a test with 0 findings in defect dojo as this is misleading.

**Comment by manuel-sommer** [comment]
this can be closed @mtesauro

**Comment by manuel-sommer** [comment]
Can you close this and the other issues which are already merged @kzzz1 ?

**Comment by kzzz1** [comment]
@manuel-sommer Is there any chance those sensitive_datas from an Aqua Scan report will be in the DefectDojo findings list when a report is uploaded?

**Comment by manuel-sommer** [comment]
I don't understand this question. The PR reflects this.

**Comment by mtesauro** [comment]
@manuel-sommer Do you want this closed or should it wait for #10611 to be merged? 

Trying to catch up on things...

**Comment by manuel-sommer** [comment]
I guess this can be closed now @mtesauro

**Comment by kzzz1** [comment]
@manuel-sommer , I just tried the new version thank you it works well now I don't have the NoneType error leading to 0 findings anymore. But I still don't see the sensitive datas displayed on the findings list when I import an Aqua Scan with  sensitive datas in it. Do I'm supposed to see them or it's normal that I just see the vulnarabilities only?

**Comment by manuel-sommer** [comment]
@kzzz1 
Could you specific with these example reports exactly what is missing?
https://github.com/DefectDojo/django-DefectDojo/tree/master/unittests/scans/aqua

**Comment by kzzz1** [comment]
@manuel-sommer  
[aqua_devops_issue_10611.json](https://github.com/DefectDojo/django-DefectDojo/blob/master/unittests/scans/aqua/aqua_devops_issue_10611.json)
That report contains sensitive_data_items, but when I import that report in DefectDojo, the sensitive datas are not displayed in the findings list...
![image](https://github.com/user-attachments/assets/fa3c5250-8faf-426b-a800-a422d7dab9f0)

**Comment by manuel-sommer** [comment]
Can you get more specific and mention the lines in the json which are missing?

**Comment by kzzz1** [comment]
Of course, there is 3 sensitive items in that file. None of them are displayed in the DefectDojo UI when I import that report. (same for all the files I tested with sensitive datas). 
Line 3020-3038, 3040-3061, 3290-3308.

Here is a screenshot from Aqua UI on the sensitive datas
![image](https://github.com/user-attachments/assets/65e86a87-2ef5-4ecb-bf74-38193af2b910)

**Comment by manuel-sommer** [comment]
see PR @kzzz1
