### ISSUE TITLE
add docs for developers

### ISSUE THREAD

**Issue by abdoqaidhaidar** [DefectDojo/django-DefectDojo#10597]
Hi i want to ask about the developers who want to add new feauters to defectdojo

1- read me file to install project  without docker with every info
2- docs to how to add new api 

because now i want to edit in the project but it'sa in docker when i edit in project i have to rebuild the docker to show the code

what is the good way to edit in project and easy ?

**Comment by manuel-sommer** [comment]
Hi @abdoqaidhaidar, 

please close this issue as this is rather a community question and not a bug. 
Use the OWASP slack channel. 

Also take a look here: https://defectdojo.github.io/django-DefectDojo/contributing/
