### ISSUE TITLE
Add an other Aqua Scan Format

### ISSUE THREAD

**Issue by kzzz1** [DefectDojo/django-DefectDojo#10611]
I have an Aqua Scan Report coming from Azure Devops job. The file has slightly different json structure, having outter square brackets and 2 more lines at the beginning (image_name and results). The rest is the same, I think the part we want is in the 'results' json key. That file gives me 0 findings when I import it like this. Is it possible to add that new format? 

![image](https://github.com/user-attachments/assets/4eb75dcd-9b60-41a0-aa8a-e799b103a9db)

**Comment by manuel-sommer** [comment]
Could you add an example file?

**Comment by kzzz1** [comment]
sure
[AquaSecurity-test-local-202407191.json](https://github.com/user-attachments/files/16349480/AquaSecurity-test-local-202407191.json)

**Comment by manuel-sommer** [comment]
See PR @kzzz1
