### ISSUE TITLE
@mtesauro

### ISSUE THREAD

**Issue by afagund** [DefectDojo/django-DefectDojo#10629]
@mtesauro 

We are talking about pure API requests being sent to DefectDojo at api/v2/reimport-scan/. If we have a problem, it must be with the DefectDojo API not handling the requests correctly.

_Originally posted by @afagund in https://github.com/DefectDojo/django-DefectDojo/issues/10607#issuecomment-2249215389_

**Comment by mtesauro** [comment]
Not sure why a new issue was opened for this. Conversation is happening on #10607 so closing this as a duplicate.
