### ISSUE TITLE
Assess Unit Test Coverage

### ISSUE THREAD

**Issue by devGregA** [DefectDojo/django-DefectDojo#1064]
1. Review tests at https://github.com/DefectDojo/django-DefectDojo/tree/master/tests.
2. Create a checklist of ideal unit tests and check-off coverage we currently have.

**Comment by propersam** [comment]
I'm interested in this. Please can you give a clearer explanation on what's needed/expected

**Comment by propersam** [comment]
contributing to be this project in the aspect of unit tests is my submission for GSOC. 

You can point me to any resource(s) you think I should go through that might be helpful.

of course, learning never stops. :smiley:

**Comment by ptrovatelli** [comment]
Hi,
What I would say is missing (or I haven't found yet) : 
- deduplication: 
  import twice the same report and make sure the duplicates are found
  to test at engagement level and product level both with and without "deduplication on engagement" ticked. 
  do this for various reports as it will not give the same results (checkmarx, zap, dependency check...)
Not sure this can be easily done with unit test, maybe add smoke tests? 
Also test duplicates present in the same report

- database insertion (regarding recent encoding issues). Again with smoke test, import reports with non-ascii characters and make sure everything works (number of findings found).
I have just added unit tests for checkmarx parser but it's not testing database insertion. see sample files here https://github.com/DefectDojo/django-DefectDojo/pull/1076/files

**Comment by ptrovatelli** [comment]
for deduplication, i've found some good stuff in the apiv2 unit tests (test_apiv2_scan_import_options.py for example). However they're only covering ZAP reports. They may also be more detailed, testing when findings are or are not duplicate, depending on their fields
I'm currently looking at adding checkmarx report tests in those api tests.
