### ISSUE TITLE
The `/tests` endpoint from the REST API is not returning all tests

### ISSUE THREAD

**Issue by rgcouto** [DefectDojo/django-DefectDojo#10655]
**What I'm working on**
I'm working on an CI integration with Defect Dojo. We're collecting a series of reports through out the CI pipeline and then upload it to DD. The problem is that if you're on a Merge Request and commit changes many times, you'll end up with lots of the same tests on a given engagement. Thus, I was thinking on looking only at the most recent test for any given test type, in order to decide if the MR gate should be lifted or not. 

**Bug description**
When I request the `/tests` endpoint for a given engagement like: `.../tests/?engagement=875` the results list contains lots of tests and test types but never the most recent one.

**Steps to reproduce**
1. Create an engagement;
2. Upload various reports of the same type to it (which simulates the various runs of the pipeline during the lifecycle of a Merge Request);
3. Check on the UI the list of tests, you should see various tests having the same name on the engagement;
4. Check the ID of the most recent one, i.e., the highest ID;
5. Make a simple curl request or use postman to call the `tests` endpoint speciying the engangement and you'll see the highest ID you find in the browser is no the one you see in the REST API.

**Expected behavior**
It would be expected that the highest IDs should match.

**Deployment method** *(select with an `X`)*
- [ X ] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - DefectDojo version 2.34.3 

**Screenshots**
The UI highlighting the most recent scan ID
![image](https://github.com/user-attachments/assets/a8743d46-65ae-4711-b212-449b4cd187ed)

When calling the `/test` endpoint, this is the highest ID I get for the test type of the previous image.
![image](https://github.com/user-attachments/assets/ffaefc00-ef99-41cc-8b51-69306dad9cbe)

**Comment by hblankenship** [comment]
@rgcouto I have not been able to reproduce this. My own tests DO return the most recent test (in this case 2332, as below):
![image](https://github.com/user-attachments/assets/bf28bf28-3318-4746-a7f1-6354b47e5c7e)

I do note that the default limit once the count goes over 25 comes into play. You have 29 results which suggests that perhaps there is a 'next' for paging in your call? Like so:
![image](https://github.com/user-attachments/assets/5ab467d0-4192-4dea-8f2b-89ff7c858b22)

You can also try calling the curl command with the limit parameter set to 100 or something over your expected count. Are you still seeing this issue?

**Comment by rgcouto** [comment]
Oh boy....What a dumb ass of mine..

You're right, I didn't thought about pagination. My bad..

Thanks anyway! Great job!
