### ISSUE TITLE
Missing Scan type for Bearer CLI in DefectDojo:

### ISSUE THREAD

**Issue by harshilkyada** [DefectDojo/django-DefectDojo#10652]
I am trying to upload a scan report generated by Bearer CLI to DefectDojo, but I am encountering an issue where neither "Bearer CLI" nor "Bearer" is recognized as a valid scan_type. 

Steps to Reproduce:
1. Generate a scan report using Bearer CLI.
2. Attempt to upload the report to DefectDojo using the /import-scan/ API endpoint.
3. Set the scan_type to "Bearer CLI" or "Bearer".

Expected Behavior:
The scan report should be uploaded successfully with the appropriate scan_type.

Actual Behavior:
The upload fails with the following error message:

Upload failed
Status Code: 400
Response: {'scan_type': ['"Bearer CLI" is not a valid choice.'], 'message': '{\'scan_type\': [ErrorDetail(string=\'"Bearer CLI" is not a valid choice.\', code=\'invalid_choice\')]}'}

Environment:

DefectDojo version: [v. 2.36.5 ]
Deployment method: [Virtual Machine (VM)]
Bearer CLI version: [1.45.2]

Thank you for considering this request. Please let me know if any additional information is required.

**Comment by manuel-sommer** [comment]
Do you have an example File?

**Comment by harshilkyada** [comment]
[bearer_report.json](https://github.com/user-attachments/files/16428068/bearer_report.json)
yes, i have a example file. that's Report.json File.
Also, i tried to upload a file manually in DefectDOjo but there are also Bearer CLI scan type option is not available.

**Comment by manuel-sommer** [comment]
I have pushed a fix @harshilkyada

**Comment by manuel-sommer** [comment]
btw: the json file you provided is not really a json file, but I was able to fix it anyway

**Comment by manuel-sommer** [comment]
This can be closed @mtesauro  @harshilkyada
