### ISSUE TITLE
IBM App Scan Integration

### ISSUE THREAD

**Issue by vivek1123** [DefectDojo/django-DefectDojo#1075]
I am currently performing DAST activities for my security team and using IBM App Scan Standard for the same. Recently I came across Defect Dojo which I think can be very effective for Defect Tracking as well as client integration. 

Bu the tool doesn't support the IBM App Scan output.

Can you help me with this new solution.

**Comment by aaronweaver** [comment]
@vivek1123  There is app scan support. Is the importer not working? Please provide an error if there is one.

**Comment by valentijnscholten** [comment]
Which tool should be selected as I can't see any IBM either in https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/factory.py

**Comment by aaronweaver** [comment]
My bad I was thinking of AppSpider, instead of AppScan. @vivek1123 can you provide a sample export file and upload [here](https://github.com/DefectDojo/sample-scan-files)?

**Comment by vivek1123** [comment]
@aaronweaver not able to upload files at ur link, requires additional push rights.

**Comment by aaronweaver** [comment]
@vivek1123  you need to submit a PR.

**Comment by aaronweaver** [comment]
@vivek1123 We can work on this, just attach the sample file directly to this issue.

**Comment by dougmcdorman** [comment]
You might find the parsers from OWASP Benchmark useful to refer to
https://github.com/OWASP/Benchmark/tree/master/src/main/java/org/owasp/benchmark/score/parsers
AppScanDynamicReader.java
AppScanDynamicReader2.java

**Comment by propersam** [comment]
I am waiting for a valid sample XML, CSV or JSON file for this issue before I can dig in.

**Comment by aaronweaver** [comment]
@propersam See attached xml file.

[testfire.xml.zip](https://github.com/DefectDojo/django-DefectDojo/files/3249135/testfire.xml.zip)

**Comment by propersam** [comment]
seen. You can assign this to me. and set to In Progress

**Comment by propersam** [comment]
The threat class in this template are not categorized into mediun, info, low, high, etc..
..I think I need a list of all the threat class used by IBM APP Scan categorized according to severity.

**Comment by propersam** [comment]
The threat I have seen sofar in this template are:

catPredicatableResourceLocation
catInformationLeakage
catcontentSpoofing
catUrlRedirectoryAbuse
catCrossSiteRequestForgery
etc..

They are not categorized according to severity level

**Comment by propersam** [comment]
What does `count` and `maxIssueSeverity` item tag attributes under `issue-type-group` tag stand for?

**Comment by aaronweaver** [comment]
I wouldn't do anything with the categories. Use the severity: issue-group/item/severity. Count and maxIssueSeverity aren't needed either for the import. For reference view this [importer](https://github.com/infobyte/faraday/blob/master/plugins/repo/appscan/plugin.py).

**Comment by propersam** [comment]
This is one huge xml file.

Thanks for the reference I can work with that.

**Comment by propersam** [comment]
@aaronweaver  I am done with implementing this scanner.

But i'm having issues choosing the type of unit test to write for it.

the sample XML file is too large (over 22,000 lines) I can't just go in and modify the file into *Single finding, no finding and multiple findings*.

Is it okay if I just write the test as a functional selenium test ?

**Comment by propersam** [comment]
or can you provide the different instance of the xml file.

one with no findings at all
and another with only 1 finding

**Comment by propersam** [comment]
finally made a PR..
waiting review...
