### ISSUE TITLE
An exception error occurred during the report import: 'Generated' - semgrep scan

### ISSUE THREAD

**Issue by demos2022** [DefectDojo/django-DefectDojo#10755]
This is my very first time using DefectDojo. I had spun up a local instance of DefectDojo with docker.
The report I am attempting to import in DefectDojo is Semgrep json scan report. 
<img width="820" alt="image" src="https://github.com/user-attachments/assets/8d2d4860-cd5b-42a7-8f2a-a7445e59d25a">

**Comment by mtesauro** [comment]
From the screenshot, it appears you didn't set the "Scan Type" which should be Semgrep.

If you're running locally, you can also look at the docker logs to see more error details.

See
https://documentation.defectdojo.com/integrations/importing/
and
https://documentation.defectdojo.com/integrations/parsers/file/semgrep/
for more details

**Comment by demos2022** [comment]
@mtesauro That worked. Thanks
