### ISSUE TITLE
Error when run the project in docker 

### ISSUE THREAD

**Issue by mhsinj0** [DefectDojo/django-DefectDojo#10777]
Hi iam sorry for noising but some time when i run the project in docker it's don't start , amy be because the initializer stopped
 
 
 django-defectdojo-master-initializer-1   | [17/Aug/2024 06:07:00] INFO [dojo.models:4567] enabling audit logging
django-defectdojo-master-initializer-1   | Creation of non-standard permissions
django-defectdojo-master-initializer-1   | [17/Aug/2024 06:07:06] INFO [dojo.models:4567] enabling audit logging
django-defectdojo-master-initializer-1   | [17/Aug/2024 06:07:09] INFO [dojo.management.commands.initialize_permissions:28] Non-standard permissions have been created
django-defectdojo-master-initializer-1 exited with code 0

i try to start with docker start but it's same problem it' just show after django-defectdojo-master-initializer-1  

django-defectdojo-master-celeryworker-1  | [17/Aug/2024 06:08:00] INFO [celery.worker.strategy:161] Task dojo.tasks.async_dupe_delete[203d8716-1a9c-4e35-b18e-e32064f29a1d] received
django-defectdojo-master-celeryworker-1  | [17/Aug/2024 06:08:00] INFO [celery.app.trace:128] Task dojo.tasks.async_dupe_delete[203d8716-1a9c-4e35-b18e-e32064f29a1d] succeeded in 0.030708130998391425s: None
django-defectdojo-master-celerybeat-1    | [17/Aug/2024 06:09:00] INFO [celery.beat:278] Scheduler: Sending due task dedupe-delete (dojo.tasks.async_dupe_delete)
django-defectdojo-master-celeryworker-1  | [17/Aug/2024 06:09:00] INFO [celery.worker.strategy:161] Task dojo.tasks.async_dupe_delete[ba55e49b-e74e-4dc0-9234-825a6cff4ef1] received
django-defectdojo-master-celeryworker-1  | [17/Aug/2024 06:09:00] INFO [celery.app.trace:128] Task dojo.tasks.async_dupe_delete[ba55e49b-e74e-4dc0-9234-825a6cff4ef1] succeeded in 0.03419619499982218s: None
django-defectdojo-master-celerybeat-1    | [17/Aug/2024 06:10:00] INFO [celery.beat:278] Scheduler: Sending due task dedupe-delete (dojo.tasks.async_dupe_delete)
django-defectdojo-master-celeryworker-1  | [17/Aug/2024 06:10:00] INFO [celery.worker.strategy:161] Task dojo.tasks.async_dupe_delete[799c9f16-03eb-493c-908b-687c09a72446] received
django-defectdojo-master-celeryworker-1  | [17/Aug/2024 06:10:00] INFO [celery.app.trace:128] Task dojo.tasks.async_dupe_delete[799c9f16-03eb-493c-908b-687c09a72446] succeeded in 0.03322019999905024s: None
django-defectdojo-master-celerybeat-1    | [17/Aug/2024 06:11:00] INFO [celery.beat:278] Scheduler: Sending due task dedupe-delete (dojo.tasks.async_dupe_delete)
django-defectdojo-master-celeryworker-1  | [17/Aug/2024 06:11:00] INFO [celery.worker.strategy:161] Task dojo.tasks.async_dupe_delete[5063cc2d-f128-45ed-a4a1-8627cbacdef2] received
django-defectdojo-master-celeryworker-1  | [17/Aug/2024 06:11:00] INFO [celery.app.trace:128] Task dojo.tasks.async_dupe_delete[5063cc2d-f128-45ed-a4a1-8627cbacdef2] succeeded in 0.02916085399920121s: None

**Comment by kiblik** [comment]
It is not a bug 🐛, it is a feature 😄.
`initializer` is a job responsible for the preparation and migration of a database. When a database is ready, the job successfully finishes (with return code 0).
If your application does not work, there will be probably some other reason.

**Comment by mhsinj0** [comment]
but when i try to access to 
127.0.0.1:8080
it's don't work 

yesterday it's working well !! and the logs of docker is good.

**Comment by kiblik** [comment]
I would recommend explicitly checking logs from `nginx` and `uwsgi` from the time when you are trying to access the page.

Sometimes, I accidentally forget that I'm running a different app on the same port (8080). Try to check this kind of interference as well.

**Comment by mhsinj0** [comment]
thank you , it's solved
