### ISSUE TITLE
after development

### ISSUE THREAD

**Issue by mhsinj0** [DefectDojo/django-DefectDojo#10785]
now if iadd some feauters to defectdojo and development for it , and after one moth there is  new relese for new version of defectdojo with some feauters and fix bugs , how i can add this updates to my project that iam development it

**Comment by manuel-sommer** [comment]
https://defectdojo.github.io/django-DefectDojo/getting_started/upgrading/

Please ask such questions rather in the OWASP slack channel.
I guess this can be closed @mtesauro

**Comment by mhsinj0** [comment]
thank you for your support , you are amazing team .
