### ISSUE TITLE
DefectDojo and external DB

### ISSUE THREAD

**Issue by Halogenmake** [DefectDojo/django-DefectDojo#10792]
**Problem description**
Hi, I have a task to install DefectDojo on Kubernetes, with its database set up on a separate server. I’m using a Helm chart for the installation. Could you please advise what changes need to be made in the values.yaml config to ensure that DefectDojo installed on Kubernetes uses an external database?

At the very least, I'm not quite sure where to specify the database username and password.

Thanks for your help!

**Deployment method** 
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: minikube
 - DefectDojo version 2.37.2
 - DefectDojo chart version: 1.6.146

**Comment by mtesauro** [comment]
@Halogenmake 
The better place to ask this question is in OWASP Slack in the #defectdojo channel

Details on joining that channel are at: https://github.com/DefectDojo/django-DefectDojo?tab=readme-ov-file#community-getting-involved-and-updates
