### ISSUE TITLE
Cannot Update Finding As Soon as Jira is Configured

### ISSUE THREAD

**Issue by sbani** [DefectDojo/django-DefectDojo#1081]
## Bug description
When trying to close a finding an exception is thrown because the system is trying to update the (non-existing) Jira ticket.

Looking at the code gives me the impression that a Jira Issue is mandatory as soon as one enables a Jira config.

Looks like `j_issue = JIRA_Issue.objects.get(finding=finding)` is throwing an exception which is not handled properly.

## Steps to reproduce
1. Setup Jira for a product
2. Create a finding
3. Create a review, settings do not matter
4. Send POST requests => Exception

## Expected behavior
There shouldn't be an error only because you don't have a Jira ticket connected to a finding.

## Deployment method
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

## Environment information
 - Operating System: Ubuntu / Docker
 - DefectDojo version: master / 2b5d417: Update README.md [2019-04-12 14:49:15 -0500]

## Console logs
```
uwsgi_1         | Starting new HTTPS connection (1): jira.XXX.de:443
uwsgi_1         | https://jira.XXX.de:443 "GET /rest/api/2/serverInfo HTTP/1.1" 200 None
uwsgi_1         | https://jira.XXX.de:443 "GET /rest/api/2/field HTTP/1.1" 200 None
uwsgi_1         | Internal Server Error: /finding/1/defect_review
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
uwsgi_1         |     response = self._get_response(request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
uwsgi_1         |     return view_func(request, *args, **kwargs)
uwsgi_1         |   File "./dojo/finding/views.py", line 365, in defect_finding_review
uwsgi_1         |     j_issue = JIRA_Issue.objects.get(finding=finding)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
uwsgi_1         |     return getattr(self.get_queryset(), name)(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 380, in get
uwsgi_1         |     self.model._meta.object_name
uwsgi_1         | DoesNotExist: JIRA_Issue matching query does not exist.
```

## Possible solution for that:
Put everything in try except blocks. It helps in this case, but I'm sure there are more cases, at least in `views.py`. I'm not deep enough into the code that I find a more generic solution like a `load_jira_issue()` function that catches the exceptions and returns `None` instead. It would be easier to handle, but I'm not sure where to put that. I'm willing to create a PR, but I think a major contributor should have a look first to find a more generic solution.

Here is a possible fix for  `finding/views.py` line 350+
```python
            # Jira ticket update
            try:
                if defect_choice == "Close Finding":
                    jira = get_jira_connection(finding)
                    if jira:
                        j_issue = JIRA_Issue.objects.get(finding=finding)
                        issue = jira.issue(j_issue.jira_id)
                        # If the issue id is closed jira will return Reopen Issue
                        resolution_id = jira_get_resolution_id(jira, issue,
                                                            "Reopen Issue")
                        if resolution_id is None:
                            resolution_id = jira_get_resolution_id(
                                jira, issue, "Resolve Issue")
                            jira_change_resolution_id(jira, issue, resolution_id)
                            new_note.entry = new_note.entry + "\nJira issue set to resolved."
                else:
                    # Re-open finding with notes stating why re-open
                    jira = get_jira_connection(finding)
                    j_issue = JIRA_Issue.objects.get(finding=finding)
                    issue = jira.issue(j_issue.jira_id)
                    resolution_id = jira_get_resolution_id(jira, issue,
                                                        "Resolve Issue")
                    if resolution_id is not None:
                        jira_change_resolution_id(jira, issue, resolution_id)
                        new_note.entry = new_note.entry + "\nJira issue re-opened."
            except:
                pass
```

**Thanks for your effort!**

**Comment by valentijnscholten** [comment]
Might not be the best idea to swall just all exceptions, may be better to add a check before trying to close the JIRA ticket:

`if jira and JIRA_Issue.objects.filter(finding=finding).exists():`

**Comment by sbani** [comment]
Hi @valentijnscholten,
your suggestions sounds reasonable, but `JIRA_Issue.objects.filter(finding=finding)` itself is throwing the exception. Adding the `exists()` method is not solving the issue here.

I changed the code slightly:
```python
            # Push info to jira
            jira = get_jira_connection(finding)
            try:
                j_issue = JIRA_Issue.objects.get(finding=finding)
            except JIRA_Issue.DoesNotExist:
                j_issue = None

            if jira and j_issue is not None:
                issue = jira.issue(j_issue.jira_id)

                if defect_choice == "Close Finding":
                    # If the issue id is closed jira will return Reopen Issue
                    resolution_id = jira_get_resolution_id(jira, issue, "Reopen Issue")
                    if resolution_id is None:
                        resolution_id = jira_get_resolution_id(jira, issue, "Resolve Issue")
                        jira_change_resolution_id(jira, issue, resolution_id)
                        new_note.entry = new_note.entry + "\nJira issue set to resolved."
                else:
                    # Re-open finding with notes stating why re-open
                    resolution_id = jira_get_resolution_id(jira, issue, "Resolve Issue")
                    if resolution_id is not None:
                        jira_change_resolution_id(jira, issue, resolution_id)
                        new_note.entry = new_note.entry + "\nJira issue re-opened."
```

**Comment by valentijnscholten** [comment]
I'm using filter not get. It's used in other places in DD and working just fine as far as I know.

if jira and JIRA_Issue.objects.**filter**(finding=finding).exists():

**Comment by sbani** [comment]
Ah ok, I see. But aren't we doing two queries then?

Do you think my code is less readable or not django/python style? I'm asking because I'm curious how to do it "right" in this case

**Comment by valentijnscholten** [comment]
I am not a fan of using exceptions for flow control: https://softwareengineering.stackexchange.com/questions/189222/are-exceptions-as-control-flow-considered-a-serious-antipattern-if-so-why

So prefer a nicely readable check.

**Comment by sbani** [comment]
Thank you @valentijnscholten for the link.
I tried to follow your suggestion and created a PR - as you can see.

I'm sorry for the commits. I configured the wrong email in git and fixed it for the branch. You see only one commit in the linked PR.

**Comment by ppiotr3k** [comment]
> I am not a fan of using exceptions for flow control: https://softwareengineering.stackexchange.com/questions/189222/are-exceptions-as-control-flow-considered-a-serious-antipattern-if-so-why
> 
> So prefer a nicely readable check.

I have to disagree on this one, sorry. Although the provided link may make sense for Java/C++, and I do understand @valentijnscholten's  personal preference, the [official Python documentation](https://docs.python.org/3/glossary.html?highlight=eafp#term-eafp) states otherwise:
```
EAFP
Easier to ask for forgiveness than permission. This common Python coding style assumes
the existence of valid keys or attributes and catches exceptions if the assumption proves
false. This clean and fast style is characterized by the presence of many try and except
statements. The technique contrasts with the LBYL style common to many other languages
such as C.
```

As well summarized in the book [Dive into Python](http://diveintopython3.problemsolving.io//your-first-python-program.html#exceptions): `Python encourages the use of exceptions, which you handle.` 

Moreover, besides being the _Pythonic-way_, EAFP often result in cleaner code, with less lines (no extra `if check and extracheck... elif... else...`), and better speed (because you actually don't do those extra checks/lookups that can have/add a **high Big-O complexity**.

But @sbani, in all cases, **never** silence exceptions, like in this code snippet from your 1st solution proposition:
```python
try:
  [...]
except:
  pass
```
You will have no clue if something isn't working as expected, e.g. in a case you haven't though about.

**Comment by sbani** [comment]
thank you @ppiotr3k for commenting.

I found other try-catch-examples in the project.

You can see a better try-catch approach in one of the above comments:
https://github.com/DefectDojo/django-DefectDojo/issues/1081#issuecomment-486568431

It's not suppressing too much and it's concentrated on one command. I think that would have been a good solution, but the one from the pull requests looks good too.

**Comment by sbani** [comment]
I will close here because #1084 fixed the issue.
