### ISSUE TITLE
Number of Endpoints is not consistent in UI

### ISSUE THREAD

**Issue by Leo90124** [DefectDojo/django-DefectDojo#1093]
**Bug description**
The number of endpoints is not consistent thruout the UI for Nessus Pro 8.2 Scan.

**Steps to reproduce**
1. Use Nessus Pro 8.2 and do a Basic Network Scan on multiple endpoints; Export CSV and import into DD.
2. Click on Products > All Products says 26 Findings and 41 Endpoints for one of my engagements
3. Click on Engagements > All Engagements > Click on my engagement and the tabs say 26 Findings and 76 Endpoints
4. See error - number of endpoints is not consistent

**Expected behavior**
Number of endpoints would be the same in both places

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash
X not sure as person who set it up is on vacation

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo version: [use `git show -s --format="%h: %s [%ci]"`]  1.5.4 running celery

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

**Comment by ppiotr3k** [comment]
Hi @Leo90124, could you provide a sample CSV file to reproduce this bug? Not everybody has access to Nessus Pro. Feel free to edit the URLs / IPs should it be a problem to include the originals.

**Comment by Leo90124** [comment]
By taking a closer look at the CSV, I have some answers and a question.
Click on Products > All Products says 26 Findings and 41 Endpoints for one of my engagements.  Here the  number of endpoints is equal to the number of unique IPs in the CSV.
Click on Engagements > All Engagements > Click on my engagement and the tabs say 26 Findings and 76 Endpoints.  Here the number of endpoints is equal to the number of unique IP and Port combinations in the CSV.  So the definition of Endpoint is not consistent thruout the UI.
Now a question.  The UI says 26 Findings, but my CSV has 65 unique CVEs including some blanks.  Shouldn't the UI say 65 Findings?

**Comment by devGregA** [comment]
Hi all, without a sample scan, we can't investigate. Please feel free to reopen if you can provide a sample scan.
