### ISSUE TITLE
DB migrations should never be changed after committing them

### ISSUE THREAD

**Issue by efficiosoft** [DefectDojo/django-DefectDojo#1097]
Hi,

I saw commit 4dc17ddd, which was merged into dev recently, changed the initial db migration. I don't know why that happened in detail, but shouldn't DB migrations be unmodifiable after they were committed to a branch like dev? Otherwise, they would be pretty useless.

Django can account for a huge number of migrations without being slowed down, we shouldn't worry about having lots of them as long as they're consistent and never change.

AFAIK, it was once decided last year to use migrations to make updating to never versions a seamless process. Since they now also support migrating data, this feels even better since it will obsolete all the custom management commands for data migration and enable a consistent and self-explaining upgrade path.

We could take this issue as a general discussion about the usage of migrations for tracking of schema and data format changes within the project, if so desired.

Best regards
Robert

**Comment by valentijnscholten** [comment]
I was wondering the same.

**Comment by aaronweaver** [comment]
The migration wasn't done properly. I'll revert and then reapply. I also will be adding a unit test for testing migrations. It's one of the reasons we never wanted to manage migrations in source but containers pushed us into that corner.

**Comment by efficiosoft** [comment]
@aaronweaver May I ask why you wanted to avoid shipping migrations with the source? IMHO that's the only way to use them properly as they're related to the models they migrate, which live in source code, too.

What we should avoid in any case is people pulling from dev or master having to run `makemigrations` and `migrate` themselves, as that brings them out of sync with the official project's migration chain.

I could add a test ensuring there are no unmigrated changes tomorrow, if you want.
