### ISSUE TITLE
Unknown column 'dojo_finding.cve' in 'field list'

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1098]
**Bug description**
Checked out fresh copy, `dev` branch.

```
uwsgi_1         | [28/Apr/2019 12:19:30] "GET / HTTP/1.1" 302 0
uwsgi_1         | Internal Server Error: /dashboard
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
uwsgi_1         |     response = self._get_response(request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
uwsgi_1         |     return view_func(request, *args, **kwargs)
uwsgi_1         |   File "/app/dojo/home/views.py", line 71, in dashboard
uwsgi_1         |     for finding in findings:
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
uwsgi_1         |     self._fetch_all()
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1121, in _fetch_all
uwsgi_1         |     self._result_cache = list(self._iterable_class(self))
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
uwsgi_1         |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
uwsgi_1         |     raise original_exception
uwsgi_1         | OperationalError: (1054, "Unknown column 'dojo_finding.cve' in 'field list'")
uwsgi_1         | Internal Server Error: /dashboard
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
uwsgi_1         |     response = self._get_response(request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
uwsgi_1         |     return view_func(request, *args, **kwargs)
uwsgi_1         |   File "/app/dojo/home/views.py", line 71, in dashboard
uwsgi_1         |     for finding in findings:
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
uwsgi_1         |     self._fetch_all()
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1121, in _fetch_all
uwsgi_1         |     self._result_cache = list(self._iterable_class(self))
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
uwsgi_1         |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
uwsgi_1         |     raise original_exception
uwsgi_1         | OperationalError: (1054, "Unknown column 'dojo_finding.cve' in 'field list'")
```
Probably related to https://github.com/DefectDojo/django-DefectDojo/commit/0c2d17f3710c50e0c0e9d53541c4706b65b0b8a8 so cc'ing @devGregA. Did not dig, however.

**Steps to reproduce**
1. Clone fresh, switch to dev branch.
2. `docker-compose -f docker-compose_base.yml -f docker-compose_uwsgi-dev.yml up`
3. Login with admin
4. Witness /dashboard 500 error with error in title.

**Expected behavior**
Login proceeds successfully and shows dashboard.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Comment by dr3dd589** [comment]
hello, @madchap I'm not able to reproduce this according to your suggested steps. I think there is maybe a problem in your database volume. to a fresh install, you should remove your old DD database volume and after that do these steps.

**Comment by madchap** [comment]
I did prune all volumes when cloning the repo anew, but will try again. Maybe I oversaw something or got mixed up. Thanks.

**Comment by madchap** [comment]
Just tried again, definitely cleared all volumes, recloned repo new. I still have that.

Uploaded an asciicast showing there is no volume (beginning of cast), bringing up the docker-compose and erroring out (end of cast): https://asciinema.org/a/QPfEZdHyQniPAMTroFkDtXS2o

**Comment by dr3dd589** [comment]
this should work but don't know why you are getting this maybe remove all containers of DD and then try again.

**Comment by propersam** [comment]
I encountered this error...untill i ran 
```python manage.py makemigrations``` then ```python manage.py migrate```

**Comment by propersam** [comment]
Someone made changes to a model but didn't add the makemigrations that is why dockercompose also is not running the migrate to update the model

**Comment by propersam** [comment]
@valentijnscholten 
My current pull request on *PASSWORD TOGGLE VISIBILTY* as d migration file update in it.
@madchap is there a way u can try out my branch to build nd run ur docker to see if it works for you.

**Comment by efficiosoft** [comment]
This could also be related to https://github.com/DefectDojo/django-DefectDojo/issues/1097

**Comment by efficiosoft** [comment]
I encountered the same issue this morning after pulling from upstream dev and running with my existing db. Probably, the commit that changed the initial migration (4dc17dd,) should be reverted and a proper new migration be created that expresses the changes.

**Comment by madchap** [comment]
@aaronweaver @devGregA @valentijnscholten  can we please up the priority of this? This is real.

**Comment by madchap** [comment]
> @valentijnscholten
> My current pull request on _PASSWORD TOGGLE VISIBILTY_ as d migration file update in it.
> @madchap is there a way u can try out my branch to build nd run ur docker to see if it works for you.

Same problem.

**Comment by madchap** [comment]
> I encountered this error When i updated my code by pulling recent updates...untill i ran
> `python manage.py makemigrations` then `python manage.py migrate`

Within uwsgi container.
```
$ DD_DEBUG=off python manage.py makemigrations
No changes detected

I have no name!@ecabecb277af:/app$ DD_DEBUG=off python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auditlog, auth, authtoken, contenttypes, custom_field, django_celery_results, dojo, sessions, sites, tagging, tastypie, watson
Running migrations:
  No migrations to apply.
```

**Comment by propersam** [comment]
Well dat worked for...although i am not using docker... I am using manual setup. Admin needs to look into it.

**Comment by madchap** [comment]
Without much further looking into which commit caused what, from the description, I reverted to commit  https://github.com/DefectDojo/django-DefectDojo/commit/f3cb830b533cd4711616f1ed78d8861d32041e22 to continue on my own little stuff, assuming https://github.com/DefectDojo/django-DefectDojo/pull/973 is causing the issue.

**Comment by aaronweaver** [comment]
I reverted it. We need a unit test for migrations.

**Comment by valentijnscholten** [comment]
For me it worked fine in standalone after running migrations. Now that it's reverted I wonder what will happen next time I do an upgrade/run migrations....

**Comment by efficiosoft** [comment]
@valentijnscholten You also ran `makemigrations`, which created a new migration for you after pulling from dev, didn't you?

Then you can try this:

1. Pull from latest dev
2. ``./manage.py makemigrations``
3. ``./manage.py migrate``
4. ``./manage.py migrate --fake 0001_initial``
5. Delete all migration files except for ``0001_initial.py``.
6. Never run `makemigrations` again unless you made model changes you want to commit. Just do `migrate` after pulling new commits in.

And take a `dbbackup` before just to be sure.

**Comment by efficiosoft** [comment]
@valentijnscholten Not 100% sure it'll work though, because the initial migration was changed without django knowing about it, but apart from that your only chance is bringing the db scheme to the state `0001_initial` manually with the `dbshell` and then running from step 4 onwards.

**Comment by valentijnscholten** [comment]
I'll find a way, we just have to make sure to reduce the chances we ever have to roll back db model changes from the dev branch. I think managing migration files in source code is more robust.

**Comment by valentijnscholten** [comment]
I'll find a way, we just have to make sure to reduce the chances we ever have to roll back db model changes from the dev branch. I think managing migration files in source code is more robust and might make data migrations easier.

**Comment by efficiosoft** [comment]
Ok, will look into adding a simple unittest for that tomorrow if @aaronweaver wants me to.

**Comment by aaronweaver** [comment]
@efficiosoft I was thinking of create a sqlite database in our sample repo with the current migration and the unit test would check to see if migrations need to be applied and then use that database and attempt to apply the migration. Does that approach make sense? I'm trying to catch the use case where an existing database need to apply the new column.

**Comment by propersam** [comment]
> @valentijnscholten You also ran `makemigrations`, which created a new migration for you after pulling from dev, didn't you?
> 
> Then you can try this:
> 
> 1. Pull from latest dev
> 2. `./manage.py makemigrations`
> 3. `./manage.py migrate`
> 4. `./manage.py migrate --fake dojo 0001_initial`
> 5. Delete all migration files except for `0001_initial.py`.
> 6. Never run `makemigrations` again unless you made model changes you want to commit. Just do `migrate` after pulling new commits in.
> 
> And take a `dbbackup` before just to be sure.
> 
> **EDIT:** Fixed command in step 4 to include the app name.

@efficiosoft 
Your instructions worked very well for me, thanks..

**Comment by efficiosoft** [comment]
@aaronweaver Just to be sure I got you right:

You want to maintain a database inside the repository with the latest migration state applied and then let the test run `migrate` in order to verify new migrations apply cleanly?

I don't think this is really needed, because even when migrating a fresh database up to the latest migration, django applies them one after the other and would complain if something fails while migrating from step X to Y. I'd rather do the following:

1. Check if there are unmigrated changes. If yes, **FAIL** and tell the user to let django generate correct migrations on top of the existing ones.
2. Apply all migrations in series on a fresh database. If that fails, **FAIL**.

We then wouldn't need to keep an sqlite db under version control... What do you think?

**Comment by aaronweaver** [comment]
@efficiosoft works for me, much better than maintaining any db. Thanks!

**Comment by efficiosoft** [comment]
Ok, then I'm going to dig into this tomorrow. Shouldn't be to involved.
