### ISSUE TITLE
Start new engagement and add 'symbolic links' to vulnerabilties from other engagements or tests. 

### ISSUE THREAD

**Issue by moatn** [DefectDojo/django-DefectDojo#11003]
**Describe the solution you'd like**
As a penetration tester, i want to start a new engagement and not copy, but link older vulnerabilities (from previous engagements) to the new engagement. That way, we merge findings from different engagements to a new one but the SLA en original finding stays in the original engagement.

**Describe alternatives you've considered**
We have tried copying and moving engagements and vulnerabilities. But it did't gave us the right results.

**Comment by mtesauro** [comment]
Unfortunately, the way many of the features around findings work (reimport, dedup, ...) the ability to add a 'simple symlink' really isn't available without a significant programming effort so while this is an interesting idea (I likely would use this if I was still doing pen testing), we won't be adding this to DefectDojo.

Thanks for the suggesting never the less.
