### ISSUE TITLE
Netsparker Scan - Date Parser Issue

### ISSUE THREAD

**Issue by ekondur** [DefectDojo/django-DefectDojo#11020]
Hello team, 
I am Emrah from the Invicti team. There is an issue when importing scans with "yyyy-MM-dd" date format. We have encountered this issue both with UI and API. 

**Response Message:**
```
{ statusCode = BadRequest, content = {"message":"[\"time data '2024-01-26 05:18 PM' does not match format '%d/%m/%Y %H:%M %p'\"]"}, headers = System.Collections.Generic.List`1[RestSharp.Parameter], responseUri = https://demo.defectdojo.org//api/v2/import-scan/, errorMessage =  }
```
![image](https://github.com/user-attachments/assets/59228863-cce8-4702-a65f-2198f549efee)

I can import the same report with Acunetix successfully. The problem seems to be related to the parser. When I compare `AcunetixJSONParser` and `NetsparkerParser`, the  ` data["Generated"]` field is parsed differently. 

[attached example report: example-scan-report.json](https://github.com/user-attachments/files/17293318/example-scan-report.json)

Regards.

**Comment by manuel-sommer** [comment]
Could you close this @ekondur ?

**Comment by ekondur** [comment]
we will test it on https://demo.defectdojo.org/ env. and close it.

**Comment by ekondur** [comment]
Hi @manuel-sommer , the same issue still exists on Demo, when will it be released?

**Comment by manuel-sommer** [comment]
I don't know, please ask the maintainers.

**Comment by mtesauro** [comment]
@ekondur The demo was updated to 2.39.1 last night (US Central Time) Monday was a US holiday so the release happened on Tuesday instead of the usual Monday.

![image](https://github.com/user-attachments/assets/fb15564d-bfed-4317-a725-b48573d789b6)

**Comment by ekondur** [comment]
Thank you @mtesauro we will test it and close the issue then. FYI @manuel-sommer
