### ISSUE TITLE
Endpoints with hostnames over 50 characters generate 500 Errors

### ISSUE THREAD

**Issue by adracea** [DefectDojo/django-DefectDojo#1104]
**Bug description**
If an endpoint hostname has over 50 characters Defect Dojo generates a 500 error message 
**Steps to reproduce**
1. Go to Endpoints
2. Add an endpoint with a hostname of over 50 characters
3. Open the endpoint 
4. Observe 500 error
https://defectdojo.herokuapp.com/endpoint/83
(not sure if it will work for long)
**Expected behavior**

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Irrelevant
 - DefectDojo version: [5377f1f864cf71956fe38380b263dee122557da3]

**Screenshots** (optional)
![image](https://user-images.githubusercontent.com/6214663/57078010-131e0580-6cf6-11e9-8fde-4b916df4a4d9.png)

Note: In my environment I fixed it by simply removing the actual shortening .
I haven't had time to further inspect the issue and find the actual root cause but I believe it's trying to shorten the path when the path isn't the actual issue , but the `url.netloc` as seen in the screenshot above .

**Comment by propersam** [comment]
It's either this issue have been fixed already or the error only occurs in your instance.

I can't seem to get any error as described above.

https://defectdojo.herokuapp.com/endpoint/20

**Comment by adracea** [comment]
`https://test123123.test123123-test.testtesttest.teeeeeessssssssttttt.com:443`
Can you try with this string @propersam ? Still seems to be replicating on the current heroku version :)
![image](https://user-images.githubusercontent.com/6214663/58975279-43613400-87cd-11e9-95f0-0b5cdeeb8837.png)

**Comment by propersam** [comment]
oh... i see the error now

**Comment by propersam** [comment]
This issue can't be retriggered in my local environment. it seems it has been fixed but the heroku version is yet to be updated

**Comment by propersam** [comment]
With all current changes being put in place .. i doubt this issue still exists....

**Comment by devGregA** [comment]
@aaronweaver we're automatically updating the heroku instance?

**Comment by devGregA** [comment]
Changes should be propagated at this point.
