### ISSUE TITLE
Import Trivy Scan Results (Image, FileSystem IaC)

### ISSUE THREAD

**Issue by leoo-hub** [DefectDojo/django-DefectDojo#11057]
**Problem description**
Hello, I need to import three scan types from Trivy: Image, FileSystem, and IaC. How can I do this in just one engagement? I was thinking of merging the three JSON report files into one by combining the results sections and then importing that into Dojo. Is this the best approach?

**Steps to reproduce**
Generate three Trivy scans (Image, FileSystem, and IaC) in JSON format and import them into a Dojo engagement using the 'Trivy Scan' option.

**Expected behavior**
A way to import the three report files generated by Trivy into just one engagement.

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Comment by mtesauro** [comment]
The reason we have engagements in the [DefectDojo data model](https://documentation.defectdojo.com/usage/models/) is to allow the outputs of 1+ scan or manual effort to be combined and reported on as a single unit.

![image](https://github.com/user-attachments/assets/bb7342e5-87a3-4198-b4bb-733d04e1add7)


There no reason to combine the JSON unless you just want to.

Instead, create an engagement and then add 3 tests to that engagement, one for each Trivy scan type.

You can then choose to report/view the findings from one of those tests or combined at the engagement level.

HTH

**Comment by leoo-hub** [comment]
> The reason we have engagements in the [DefectDojo data model](https://documentation.defectdojo.com/usage/models/) is to allow the outputs of 1+ scan or manual effort to be combined and reported on as a single unit.
> 
> ![image](https://private-user-images.githubusercontent.com/3422419/376334529-bb7342e5-87a3-4198-b4bb-733d04e1add7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MzU3NDAsIm5iZiI6MTcyODkzNTQ0MCwicGF0aCI6Ii8zNDIyNDE5LzM3NjMzNDUyOS1iYjczNDJlNS04N2EzLTQxOTgtYjRiYi03MzNkMDRlMWFkZDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTRUMTk1MDQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzkyNzkyN2JjOWFkMWM1ODgwMDJmMTllZjk1YTc5ZDE3ODg5OGQ2OTMwMDUyMmViMTVkMjAzYmE0OWU3YjEzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.fjsKP4NHdzv7mgNoNiPczL_z3onP53iX1Skei2WtQLA)
> 
> There no reason to combine the JSON unless you just want to.
> 
> Instead, create an engagement and then add 3 tests to that engagement, one for each Trivy scan type.
> 
> You can then choose to report/view the findings from one of those tests or combined at the engagement level.
> 
> HTH



> The reason we have engagements in the [DefectDojo data model](https://documentation.defectdojo.com/usage/models/) is to allow the outputs of 1+ scan or manual effort to be combined and reported on as a single unit.
> 
> ![image](https://private-user-images.githubusercontent.com/3422419/376334529-bb7342e5-87a3-4198-b4bb-733d04e1add7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MzU3NDAsIm5iZiI6MTcyODkzNTQ0MCwicGF0aCI6Ii8zNDIyNDE5LzM3NjMzNDUyOS1iYjczNDJlNS04N2EzLTQxOTgtYjRiYi03MzNkMDRlMWFkZDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTRUMTk1MDQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzkyNzkyN2JjOWFkMWM1ODgwMDJmMTllZjk1YTc5ZDE3ODg5OGQ2OTMwMDUyMmViMTVkMjAzYmE0OWU3YjEzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.fjsKP4NHdzv7mgNoNiPczL_z3onP53iX1Skei2WtQLA)
> 
> There no reason to combine the JSON unless you just want to.
> 
> Instead, create an engagement and then add 3 tests to that engagement, one for each Trivy scan type.
> 
> You can then choose to report/view the findings from one of those tests or combined at the engagement level.
> 
> HTH

I tric

> The reason we have engagements in the [DefectDojo data model](https://documentation.defectdojo.com/usage/models/) is to allow the outputs of 1+ scan or manual effort to be combined and reported on as a single unit.
> 
> ![image](https://private-user-images.githubusercontent.com/3422419/376334529-bb7342e5-87a3-4198-b4bb-733d04e1add7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MzU4OTYsIm5iZiI6MTcyODkzNTU5NiwicGF0aCI6Ii8zNDIyNDE5LzM3NjMzNDUyOS1iYjczNDJlNS04N2EzLTQxOTgtYjRiYi03MzNkMDRlMWFkZDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTRUMTk1MzE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTM4Y2QwZTZkNjRiOTY1YWJkYTAyNmFkNmIwYmYxYzVmNzA1NTgwZjJmNTBjNzI5OTM4MGYyMmFiZjRhZGM4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.TMT2YZNtviLxRf3VKDF379BiIxp9AqcZCXFp6ZyV8pU)
> 
> There no reason to combine the JSON unless you just want to.
> 
> Instead, create an engagement and then add 3 tests to that engagement, one for each Trivy scan type.
> 
> You can then choose to report/view the findings from one of those tests or combined at the engagement level.
> 
> HTH

O tried 

> The reason we have engagements in the [DefectDojo data model](https://documentation.defectdojo.com/usage/models/) is to allow the outputs of 1+ scan or manual effort to be combined and reported on as a single unit.
> 
> ![image](https://private-user-images.githubusercontent.com/3422419/376334529-bb7342e5-87a3-4198-b4bb-733d04e1add7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MzU4OTYsIm5iZiI6MTcyODkzNTU5NiwicGF0aCI6Ii8zNDIyNDE5LzM3NjMzNDUyOS1iYjczNDJlNS04N2EzLTQxOTgtYjRiYi03MzNkMDRlMWFkZDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTRUMTk1MzE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTM4Y2QwZTZkNjRiOTY1YWJkYTAyNmFkNmIwYmYxYzVmNzA1NTgwZjJmNTBjNzI5OTM4MGYyMmFiZjRhZGM4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.TMT2YZNtviLxRf3VKDF379BiIxp9AqcZCXFp6ZyV8pU)
> 
> There no reason to combine the JSON unless you just want to.
> 
> Instead, create an engagement and then add 3 tests to that engagement, one for each Trivy scan type.
> 
> You can then choose to report/view the findings from one of those tests or combined at the engagement level.
> 
> HTH

MTH, I’ve tried, but the option ‘close old findings with this same engagement’ results in the elimination of findings from different analyses from Trivy.

tks;

**Comment by leoo-hub** [comment]
> The reason we have engagements in the [DefectDojo data model](https://documentation.defectdojo.com/usage/models/) is to allow the outputs of 1+ scan or manual effort to be combined and reported on as a single unit.
> 
> ![image](https://private-user-images.githubusercontent.com/3422419/376334529-bb7342e5-87a3-4198-b4bb-733d04e1add7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMTIwNzIsIm5iZiI6MTcyOTExMTc3MiwicGF0aCI6Ii8zNDIyNDE5LzM3NjMzNDUyOS1iYjczNDJlNS04N2EzLTQxOTgtYjRiYi03MzNkMDRlMWFkZDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTZUMjA0OTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODNjOGQ5ZDhmZTUyYTMxYTFiNGQ3Yjk3YmU4OThhMTNlYzRlZTExZDgzODBiNGIxODQzZWZjN2IxNzkyY2VjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.fbbqwsoTPu71hvT8JE6lPniLQZ5Mp6vSPPwUOSpsajc)
> 
> There no reason to combine the JSON unless you just want to.
> 
> Instead, create an engagement and then add 3 tests to that engagement, one for each Trivy scan type.
> 
> You can then choose to report/view the findings from one of those tests or combined at the engagement level.
> 
> HTH

MTH, I’ve tried, but the option ‘close old findings with this same engagement’ results in the elimination of findings from different analyses from Trivy.

tks;
