### ISSUE TITLE
Harbor Vulnerability Scan closing "old findings" while they are still present on the report.

### ISSUE THREAD

**Issue by TeixeiraRafael** [DefectDojo/django-DefectDojo#11072]
**Problem description**
I'm working on a setup where I have a container which is being scanned by the Harbor Vulnerability Scanner, there's an integration script I've wrote that simply pulls the report from Harbor and uploads it to DefectDojo. The script runs weekly, so it is expected that some reports will be unchanged if there was no new scan performed on harbor between two runs. The problem I'm facing is that when DefectDojo reimports a Harbor Vulnerability report, some findings are closed as mitigated. I assume this is because I'm using the `close_old_findings` flag, but since the reports are identical, DefectDojo shouldn't perceive the reimported findings as not present anymore, closing them.

**Steps to reproduce**
1. Create a product
2. Create and engagement
3. Upload a Harbor Vulnerability Scan report
4. Reimport the same report through the /reimport-scan endpoint, with `close_old_findings` set to `true`.

**Expected behavior**
When reimporting an unchanged vulnerability report, I expect the findings to remain untouched. Even if the `close_old_findings` flag is enabled, the reimport of an identical scan shouldn't make DefectDojo see some the same previous findings as no longer present on the report.

**Deployment method** *(select with an `X`)*
- [x] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Ubuntu 22.04.5
 - DefectDojo version: v. 2.33.7

**Sample scan files**
[report.json](https://github.com/user-attachments/files/17379733/report.json)

**Screenshots**
First import:
![image](https://github.com/user-attachments/assets/b0d94468-e1b0-426f-9b76-a7c2bcc5eb0f)

First Reimport:
![image](https://github.com/user-attachments/assets/34c2620d-261d-4352-b572-ee57ce4f837c)

Further reimports (no more findings are closed):
![image](https://github.com/user-attachments/assets/0788ad8e-7b78-4e26-8bad-2c8f5d0d28ba)

**Comment by manuel-sommer** [comment]
Hi @TeixeiraRafael ,
to be honest, I can't reproduce this issue. I just used https://demo.defectdojo.org with version v. 2.39.0 ( release mode ) and everything was fine. Also, I tested it locally with the latest dev branch v. 2.39.1 and also everything was fine:
![grafik](https://github.com/user-attachments/assets/4b06c059-d8fb-4ef5-b3dc-7d17dd69b714)

I guess you are doing something wrong.
