### ISSUE TITLE
Netsparker Scan XML importing Issue

### ISSUE THREAD

**Issue by ekondur** [DefectDojo/django-DefectDojo#11089]
Hi, I am Emrah from the Invicti team. 

There is an issue when importing a Netspaker Scan in XML format.  I can import the same report in JSON format without any problem. 

Exception Message:
`An exception error occurred during the report import: ['Expecting value: line 1 column 1 (char 0)']`

![image](https://github.com/user-attachments/assets/a30f5ccb-e60f-4b41-b83f-b4b76b0675a6)

Attached scan files. [scan-files.zip](https://github.com/user-attachments/files/17429399/scan-files.zip)

**Comment by mtesauro** [comment]
@ekondur Looking at the Netsparker parser, there's two things to note:
1. The parser is only written for the JSON output - here's [the unit test files](https://github.com/DefectDojo/django-DefectDojo/tree/master/unittests/scans/netsparker) the project uses to test Netsparker
2. Netsparker has been renamed to Invicti - see [here](https://documentation.defectdojo.com/integrations/parsers/file/invicti/).

If you or another community member would like to extend the existing parser to support XML, we'll be happy to take the PR. However, I'm unsure if the "new" Invicti scanner outputs XML so it may have limited use. The Invicti  parser only handles JSON scan files in it's current version.
