### ISSUE TITLE
Tenable report field name change

### ISSUE THREAD

**Issue by WojTecH94** [DefectDojo/django-DefectDojo#11102]
Few weeks ago Tenable changed one of the fields in its csv reports. 
Was: "Solution"
Now it is: "Steps to Remediate"

**Bug description**
When importing new scans from tenable (csv format) mitigation field in DefectDojo is not filled.

**Steps to reproduce**
1. Import scan (csv format) from tenable (current version)

**Expected behavior**
"Steps to Remediate" field is imported into DD's Mitigation

**Deployment method** *(select with an `X`)*
- [x] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Sample scan files**
[tenable_sample_scan.csv](https://github.com/user-attachments/files/17459001/tenable_sample_scan.csv)

**Additional context** (optional)
Not sure what about older version of reports (for example if someone does not update tenable)... with old field name: should we care about them? If not, then fix is simple and I can do it.

**Comment by manuel-sommer** [comment]
See PR @WojTecH94

**Comment by WojTecH94** [comment]
@manuel-sommer so thats how you do it :D Tested it locally, seems fine, thanks 👍

**Comment by mtesauro** [comment]
Closing as PR is merged and will be in the next release. Feel free to reopen if there's an issue post the release.
