### ISSUE TITLE
Custom Excel Template

### ISSUE THREAD

**Issue by Prosfinity** [DefectDojo/django-DefectDojo#11117]
Hi All,

Is it possible to submit custom excel of PIA information?

Thanks!

**Comment by mtesauro** [comment]
@Prosfinity  TBH, that's not enough info to provide a reasonable answer - what does PIA stand for in this case? Perfectly Imperfect Answer? Partial Ice Access? Purple Igloo Archive?

**Comment by Prosfinity** [comment]
@mtesauro 

There are 2 samples.
1. Third-party revised a reports and the format not from list of scanner, how to import the scan?
2. PIA, such as text or content, Personal Information Audit, for import to somewhere else.

**Comment by mtesauro** [comment]
@Prosfinity You could take the Excel you have, change the columns to match what's expected for the Generic CSV finding importer and then export the Excel as CSV. That should work that to get the Excel data into DefectDojo.

Details are at:
https://documentation.defectdojo.com/integrations/parsers/file/generic/

HTH
