### ISSUE TITLE
Add Tenable Plugin Info to References

### ISSUE THREAD

**Issue by Marterich** [DefectDojo/django-DefectDojo#11127]
**Is your feature request related to a problem? Please describe**
Tenable Vulnerability Scanner use so called Plugins to check a given host for the existence of Vulnerabilities.
Plugins can be thought of as a Script telling the scanner "Connect to port X, check for the Version string Y and if found do Z" These Plugins do have a unique Id and the plugin content can change over time. In every scan export, the Plugin Id, Published Date and Modified Date are contained. 

After importing the Scan information, the Information which Plugin Id and the date values of the Plugin are discarded so there is no possibility to check from Defect Dojo which Plugin Version was used to find the Vulnerability. This information could be valuable when investigating to find out exactly why and how the scanner detected a given vulnerability

**Describe the solution you'd like**
The Scan Plugin Information should be added to the References section of a given Vulnerability when a Tenable scan is imported. Format wise this could be appended as a new line like:
<Tenable Plugin Information: ID: 12345, Published: 01/01/24, Modified: 01/01/24>

**Comment by Marterich** [comment]
Thank you very much :)
Had an implementation pretty much at the ready, but hesitated because i did not manage to get the unittests to run in my environment

**Comment by manuel-sommer** [comment]
> Thank you very much :) Had an implementation pretty much at the ready, but hesitated because i did not manage to get the unittests to run in my environment

https://github.com/DefectDojo/django-DefectDojo/pull/11143
