### ISSUE TITLE
Unit tests won't run

### ISSUE THREAD

**Issue by xpert98** [DefectDojo/django-DefectDojo#11128]
**Problem description**
Attempting to run a unit test for _any_ parser results in the following error:

======================================================================
ERROR: unittests (unittest.loader._FailedTest.unittests)
----------------------------------------------------------------------
ImportError: Failed to import test module: unittests
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/unittest/loader.py", line 162, in loadTestsFromName
    module = __import__(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'unittests'

----------------------------------------------------------------------

**Steps to reproduce**
The same error occurs when using both of these commands
./dc-unittest.sh --test-case unittests.tools.test_<name>_parser.Test<name>Parser
docker compose exec uwsgi bash -c 'python manage.py test unittests.tools.<name>_parser.Test<name>Parser'

This goes for the parser I've written as well as existing unmodified parsers.

**Expected behavior**
Expected behavior is for the unit test to run.

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Ubuntu 22.04
 - DefectDojo version (see footer) or commit message: 2.39.1

**Comment by manuel-sommer** [comment]
I have the same problem. It was introduced in 2.38.0

**Comment by kiblik** [comment]
_It works on my computer_ 😄 
Can you check where `docker-compose.override.yml` is pointing? This file (symlink) is set by `docker/setEnv.sh` script.
It might be connected to the fact that `debug` env is not available anymore. You need to use `dev` env for development/debugging/troubleshooting.

**Comment by kiblik** [comment]
For context: https://github.com/DefectDojo/django-DefectDojo/pull/10692

Can you confirm and can we close this issue?

**Comment by manuel-sommer** [comment]
Yes, I can confirm this, but opened a PR to fix the docs.

**Comment by mtesauro** [comment]
Closing this one as the PR has started getting approvals.
