### ISSUE TITLE
Adding PDF support for docker containers

### ISSUE THREAD

**Issue by mayantec** [DefectDojo/django-DefectDojo#1116]
**Bug description**
When trying to add the wkhtmltopdf to docker containers, it just does not work, Web UI still showing only HTML and ASCII.

**Steps to reproduce**
1. setup your docker-compose*yml to include `DD_WKHTMLTOPDF: /usr/bin/wkhtmltopdf` in environment sections.
2. rebuild images with this simple Dockerfile
```
FROM defectdojo/defectdojo-django
USER root
RUN apt update && apt install -y wkhtmltopdf
```
3. start docker-compose
4. try to make a report from any product you only see:

- HTML
- AsciiDoc

**Expected behavior**
Option to export in PDF.

**Deployment method**
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. CentOS 7, latest docker/compose]
 - DefectDojo version: 2b5d417: Update README.md [2019-04-12 14:49:15 -0500]

**Comment by mayantec** [comment]
Also, forgot to mention that pdfkit was installed by default in the container, I've checked it with `pip install pdfkit`, and the legend "already installed" appears.
If you can contribute with any tip, will be appreciated.

Regards in advance.

**Comment by wiref4lcon** [comment]
Exactly the same issue here!

**Comment by mayantec** [comment]
Hello there:
Creating a symlink to the default path from setup.py (/usr/local/bin/wkhtmltopdf), and get rid of the DD_WKHTMLTOPDF, does not work also:

```
FROM defectdojo/defectdojo-django
USER root
RUN apt update && apt install -y wkhtmltopdf
RUN mkdir -p /usr/local/bin/ ; ln -s /usr/bin/wkhtmltopdf /usr/local/bin/
```
Same result, PDF is not an option while exporting.

**Comment by aaronweaver** [comment]
We are deprecating PDF, I'd recommend using html and printing to PDF.

**Comment by mayantec** [comment]
Thanks for the clarification.
I was pushing a stone.
Have a nice day.
