### ISSUE TITLE
WebInspect / Mirco Focus WebInspect v22.2.0.253 issues XML import to DD

### ISSUE THREAD

**Issue by johnfelipe** [DefectDojo/django-DefectDojo#11163]
Sample file:
https://drive.google.com/file/d/1OlLnu5GcgYh9R1Ez6PUOqHysaetJmG9E/view?usp=sharing

**Comment by mtesauro** [comment]
@johnfelipe Can you provide a bit more detail here?

I'm guessing there's an issue with the existing parser but having the error from the logs or something more then a link to a Google drive will greatly increase your chances on someone picking this up and fixing the issue.

**Comment by manuel-sommer** [comment]
worked on my computer:
![grafik](https://github.com/user-attachments/assets/4aa1eb00-44d1-4340-b3f4-06ee8bb3cb62)

**Comment by johnfelipe** [comment]
Which version?

**Comment by manuel-sommer** [comment]
v. 2.39.4 ( release mode )

**Comment by manuel-sommer** [comment]
Can we close this @johnfelipe?

**Comment by johnfelipe** [comment]
Yes pls, update code and works, tnks

**Comment by manuel-sommer** [comment]
Can you close it @johnfelipe ?
