### ISSUE TITLE
issue with connect with SONARQUBE Developer EditionVersion 10.3 (build 82913)

### ISSUE THREAD

**Issue by johnfelipe** [DefectDojo/django-DefectDojo#11196]
HTTPConnectionPool(host='grs-sw-sonarqubedev.trilliant.linux', port=9000): Max retries exceeded with url: /api/components/search?qualifiers=TRK (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff16c865cd0>, 'Connection to grs-sw-sonarqubedev.trilliant.linux timed out. (connect timeout=None)')) 

![SNAG-0147](https://github.com/user-attachments/assets/860b43f0-ed6f-44c5-b044-3577e1f7f128)

**Comment by johnfelipe** [comment]
GAMEMAX@DESKTOP-HUP76T1 MINGW64 ~
    $ ping grs-sw-sonarqubedev.trilliant.linux
    
    Haciendo ping a grs-sw-sonarqubedev.trilliant.linux [10.123.25.137] con 32 bytes de datos:
    Respuesta desde 10.123.25.137: bytes=32 tiempo=137ms TTL=62
    Respuesta desde 10.123.25.137: bytes=32 tiempo=130ms TTL=62
    Respuesta desde 10.123.25.137: bytes=32 tiempo=128ms TTL=62
    Respuesta desde 10.123.25.137: bytes=32 tiempo=129ms TTL=62
    
    Estad▒sticas de ping para 10.123.25.137:
        Paquetes: enviados = 4, recibidos = 4, perdidos = 0
        (0% perdidos),
    Tiempos aproximados de ida y vuelta en milisegundos:
        M▒nimo = 128ms, M▒ximo = 137ms, Media = 131ms
    
    GAMEMAX@DESKTOP-HUP76T1 MINGW64 ~
    $ ping grs-sw-sonarqubedev.trilliant.linux
    
    Haciendo ping a grs-sw-sonarqubedev.trilliant.linux [10.123.25.137] con 32 bytes de datos:
    Respuesta desde 10.123.25.137: bytes=32 tiempo=130ms TTL=62
    Respuesta desde 10.123.25.137: bytes=32 tiempo=125ms TTL=62
    Respuesta desde 10.123.25.137: bytes=32 tiempo=122ms TTL=62
    Respuesta desde 10.123.25.137: bytes=32 tiempo=135ms TTL=62
    
    Estad▒sticas de ping para 10.123.25.137:
        Paquetes: enviados = 4, recibidos = 4, perdidos = 0
        (0% perdidos),
    Tiempos aproximados de ida y vuelta en milisegundos:
        M▒nimo = 122ms, M▒ximo = 135ms, Media = 128ms
    
    GAMEMAX@DESKTOP-HUP76T1 MINGW64 ~
    $ curl -X GET "http://grs-sw-sonarqubedev.trilliant.linux:9000/api/components/search?qualifiers=TRK" \
         -H "Authorization: Bearer squ_BLABLABLA"
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0{"paging":{"pageIndex":1,"pageSize":100,"total":82},"components":[{"key":"com.trilliantnetworks:GenerateTLReport","name":"SW-GenerateTLReport","qualifier":"TRK","project":"com.trilliantnetworks:GenerateTLReport"},{"key":"com.trilliant:SLCSummaryProcessor","name":"slcsummaryprocessor","qualifier":"TRK","project":"com.trilliant:SLCSummaryProcessor"},{"key":"fw:smv6:libshell","name":"FW - SMv6 - LIBSHELL","qualifier":"TRK","project":"fw:smv6:libshell"},{"key":"fw:smv6:libdlms","name":"FW - SMv6 - LIBDLMS","qualifier":"TRK","project":"fw:smv6:libdlms"},{"key":"com.trilliantnetworks.acp.services:acp-emcm-parent","name":"SW - ACP EMCM Parent","qualifier":"TRK","project":"com.trilliantnetworks.acp.services:acp-emcm-parent"},{"key":"CFWT-TRP","name":"CFWT-TRP","qualifier":"TRK","project":"CFWT-TRP"},{"key":"com.trilliantnetworks.devicedrivers:edmi-parent","name":"SW - DRIVERS: EDMI\u0027s parent","qualifier":"TRK","project":"com.trilliantnetworks.devicedrivers:edmi-parent"},{"key":"com.trilliantnetworks.enrollment:enrollment-parent","name":"SW - SERVICE: EST Server","qualifier":"TRK","project":"com.trilliantnetworks.enrollment:enrollment-parent"},{"key":"fw:smv6:6lr:apps:DLMS","name":"FW - SMv6 - Apps (DLMS)","qualifier":"TRK","project":"fw:smv6:6lr:apps:DLMS"},{"key":"com.trilliantnetworks.protocols.ansi:protocols-ansi-parent","name":"SW - Communi.....

**Comment by johnfelipe** [comment]
all with webui forms not working show same error again and again
i create all with python scripts, but i have error in POST request:

    Verificando proyecto en SonarQube:
    Status: 200
    Proyecto encontrado:
    {
      "component": {
        "key": "com.trilliant:requestService",
        "name": "SW - Unity Suite RequestService",
        "description": "Request and trigger service for Unitysuite",
        "qualifier": "TRK",
        "analysisDate": "2024-09-17T19:46:20+0000",
        "tags": [],
        "visibility": "private",
        "leakPeriodDate": "2024-09-06T13:54:41+0000",
        "version": "1.1.2",
        "needIssueSync": false
      },
      "ancestors": []
    }
    
    Verificando configuración en DefectDojo...
    Conexión base a DefectDojo: 200
    
    Configuración de API Scan:
    {
      "id": 3,
      "service_key_1": "com.trilliant:requestService",
      "service_key_2": null,
      "service_key_3": null,
      "product": 1,
      "tool_configuration": 1,
      "prefetch": {}
    }
    
    Configuración de la herramienta:
    {
      "id": 1,
      "name": "SonarQube Integration",
      "description": "SonarQube production connection",
      "url": "http://grs-sw-sonarqubedev.trilliant.linux:9000/api",
      "authentication_type": "API",
      "extras": "BUG,VULNERABILITY,CODE_SMELL",
      "username": null,
      "auth_title": null,
      "tool_type": 5,
      "prefetch": {}
    }
    
    [OK] Todas las verificaciones completadas
    
    ¿Desea continuar con la importación? (s/n): s
    
    Iniciando importación...
    Enviando solicitud de importación...
    
    Datos de importación:
    {
      "scan_date": "2024-11-06",
      "minimum_severity": "Low",
      "active": "true",
      "verified": "true",
      "scan_type": "SonarQube API Import",
      "engagement": "3",
      "lead": "1",
      "tags": "SonarQube",
      "close_old_findings": "false",
      "service": "com.trilliant:requestService",
      "api_scan_configuration": "3"
    }
    
    Intentando conectar a DefectDojo...
    Conexión base a DefectDojo: 200
    Enviando solicitud POST...
    Error: La solicitud excedió el tiempo de espera (30 segundos)

my scanning in sonarqube need to be in webui not in python and console, can u help me?

**Comment by johnfelipe** [comment]
all this i created using python script using API of DD:

![SNAG-0168](https://github.com/user-attachments/assets/6304c422-626a-4a8f-b869-a4b4c056ea45)

and

![SNAG-0169](https://github.com/user-attachments/assets/9ff6da1e-0b5e-4efc-9ff1-c2ec8a17d71e)

and this to

![SNAG-0170](https://github.com/user-attachments/assets/666867a2-6907-4a00-9fe3-22ef5e2feb64)

but is not working correctly sync with sonarqube Developer EditionVersion 10.3 (build 82913)

**Comment by johnfelipe** [comment]
i update to latest version

and submit already sonarqube integration in tool config, and same error:

    HTTPConnectionPool(host='grs-sw-sonarqubedev.trilliant.linux', port=9000): Max retries exceeded with url: /api/components/search?qualifiers=TRK (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f368e671650>, 'Connection to grs-sw-sonarqubedev.trilliant.linux timed out. (connect timeout=None)')) 


![SNAG-0171](https://github.com/user-attachments/assets/95d76e9c-f9bd-4fd4-9c32-bc7bdec2e26f)

any suggestion for solve this?

**Comment by kiblik** [comment]
Hi @johnfelipe. For me, it looks like connectivity issues. I see you tested the connection to SQ but probably from your local machine. Can you run a connection test from the DD instance?

**Comment by johnfelipe** [comment]
Run all python test in DD server?

**Comment by kiblik** [comment]
> Run all python test in DD server?

It would be also possible. But simple `curl` should be enough.

**Comment by johnfelipe** [comment]
yes, i put curl inside of VM and incomplete, and same thing in my local and its fine, then is something in network from VM, tnks
