### ISSUE TITLE
Issue - 'engagement_end_date' field in API 're-import scan' request is ignored

### ISSUE THREAD

**Issue by NumenDivinum** [DefectDojo/django-DefectDojo#11202]
**Bug description**
I am working on importing of the Trivy vulnerability scan reports to DefectDojo via CI/CD pipeline (Jenkins).
For that to work I need the long-lasting Engagements, where the consequent reports will be re-imported after every scan.

Here's the request that I use:
curl -X POST ${DEFECTDOJO_API_URL}/reimport-scan/ \
                                -H 'Authorization: Token ${DEFECTDOJO_API_TOKEN}' \
                                -F 'scan_type=Trivy Scan' \
                                -F 'file=@${jsonFileName}' \
                                -F 'tags=helm-chart' \
                                -F 'product_type_name=Helm Chart' \
                                -F 'product_name=HelmChart-${chartName}' \
                                -F 'engagement_name=Trivy Automated Scan Engagement by Jenkins' \
                                -F 'minimum_severity=Info' \
                                -F 'active=True' \
                                -F 'verified=True' \
                                -F 'test_title=Jenkins initiated Trivy scan' \
                                -F 'auto_create_context=True' \
                                -F 'do_not_reactivate=False' \
                                -F 'deduplication_on_engagement=True' \
                                **-F 'engagement_end_date=2100-01-01' \**
                                -F 'commit_hash=None' \
                                -F 'version=${chartVersion}' \
                                -F 'branch_tag=master' \
                                -F 'build_id=None' \
                                -F 'close_old_findings=True' \
                                -F 'close_old_findings_product_scope=False' \
                                -o curl_output.txt

As you may see, the 'engagement_end_date' parameter is set to the distant date '2100-01-01'

The definition of Defect Dojo API v2 OpenAPI  gives the following:
"Request body: engagement_end_date - string($date) - End Date for Engagement. Default is current time + 365 days. Required format year-month-day"
So the format seems to be correct.
However, when the request is executed, the Engagement is created with the default term of one year (request execution current time + 365 days).
Could you please help - am I missing something here?
Is there some limitation on the maximum Engagement term?
Is this parameter conflicts with some other parameter in the request?
Is it a bug?..

**Steps to reproduce**
1. Send API request of type '/reimport-scan' with 'engagement_end_date' property set to the distant date (>365 days), creating a new Engagement 
2. Check the Engagement created
3. Note the created Engagement's end date - it is defaulted to 'current date + 365 days' 

**Expected behavior**
The created Engagement's end date should match the property 'engagement_end_date' specified in the API request 

**Deployment method**
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System:   image: 'docker.io/defectdojo/defectdojo-django:latest'
 - DefectDojo version (see footer) or commit message: v. 2.39.1 ( release mode )

**Logs** 
Logs are not helpful since the request in general is successful 

**Sample scan files**
N/A

**Screenshots**
N/A

**Additional context** (optional)
The DefectDojo source code that controls this behaviour:
https://github.com/DefectDojo/django-DefectDojo/blob/fafe5c3cc5f1287963e4681979095b8b8064575f/dojo/api_v2/serializers.py#L2263-L2265
https://github.com/DefectDojo/django-DefectDojo/blob/fafe5c3cc5f1287963e4681979095b8b8064575f/dojo/importers/auto_create_context.py#L278-LL331

**Comment by mtesauro** [comment]
@NumenDivinum Please upgrade to 2.40.0 which includes #11174 that addresses this issue.
