### ISSUE TITLE
Display Progress of Benchmark Levels in Product Overview

### ISSUE THREAD

**Issue by denniskniep** [DefectDojo/django-DefectDojo#1120]
**Is your feature request related to a problem? Please describe**
Would be nice to view the current progress of the Benchmarks (OWASP ASVS) on the Overview 

**Describe the solution you'd like**
Another box on the Overview of a product. It should display a progressbar for each Level of a Benchmark.

**Comment by devGregA** [comment]
@aaronweaver thoughts? I like this one.

**Comment by devGregA** [comment]
I'm going to go ahead and give this one to @devEricA

**Comment by devEricA** [comment]
Enhancement has been pushed and is ready for review @devGregA. Let me know what you think.
