### ISSUE TITLE
error on import bearer cli report

### ISSUE THREAD

**Issue by saldam72** [DefectDojo/django-DefectDojo#11245]
Hello,
I have tried to import json report that I have got scanning webgoat with bearer version 1.46.4, build 380afa10188c8a5e5a4f3c6ebe7009373b44137f  but I got the error "An exception error occurred during the report import: 'snippet'" (see details below)

uwsgi-1         | [12/Nov/2024 14:26:46] ERROR [dojo.engagement.views:933] 'snippet'
uwsgi-1         | Traceback (most recent call last):
uwsgi-1         |   File "/app/dojo/engagement/views.py", line 924, in import_findings
uwsgi-1         |     context["test"], _, finding_count, closed_finding_count, _, _, _ = importer_client.process_scan(
uwsgi-1         |                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/app/dojo/importers/default_importer.py", line 107, in process_scan
uwsgi-1         |     self.parsed_findings = self.parse_findings(scan, parser)
uwsgi-1         |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/app/dojo/importers/default_importer.py", line 313, in parse_findings
uwsgi-1         |     self.parsed_findings = self.parse_findings_static_test_type(scan, parser)
uwsgi-1         |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/app/dojo/importers/default_importer.py", line 330, in parse_findings_static_test_type
uwsgi-1         |     return super().parse_findings_static_test_type(scan, parser)
uwsgi-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/app/dojo/importers/base_importer.py", line 161, in parse_findings_static_test_type
uwsgi-1         |     return parser.get_findings(scan, self.test)
uwsgi-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/app/dojo/tools/bearer_cli/parser.py", line 36, in get_findings
uwsgi-1         |     description=bearerfinding["description"] + "\n Detected code snippet: \n" + bearerfinding["snippet"],
uwsgi-1         |                                                                                 ~~~~~~~~~~~~~^^^^^^^^^^^
uwsgi-1         | KeyError: 'snippet'

Then I have renamed "code_extract" property with "snippet and I have successufully imported the report.

Regards,
Sal

**Comment by manuel-sommer** [comment]
Could you test this PR @saldam72 ?

**Comment by saldam72** [comment]
Hi Manuel,
I cannot test this PR because at the moment I cannot build image.

Regards,
Sal

**Comment by manuel-sommer** [comment]
@saldam72 , could you please close this issue? The PR is merged already.
