### ISSUE TITLE
Migration issues - docker-compose not working on dev

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1125]
**Bug description**
Cannot run docker-compose on fresh rebase of dev branch, due to migrations issues.

**Steps to reproduce**
1. prune all containers and volumes
2. git fetch upstream and rebase local branch
3. `docker-compose -f docker-compose_base.yml -f docker-compose_uwsgi-dev.yml up`
4. Try to login and see the `Unknown column 'dojo_finding.cve' in 'field list'` error
5. Try to run migrations manually `docker exec -ti madchap-ddojo_uwsgi_1 python manage.py makemigrations` and see the error
```
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0002_auto_20190502_1119, 0004_cve_field in dojo).
To fix them run 'python manage.py makemigrations --merge'
```
6. Consequently attempt to run `python manage.py makemigrations --merge`. Since rights in docker are not high enough, this fails with a permission denied.
```
Merging dojo
  Branch 0002_auto_20190502_1119
    - Add field cve to finding
    - Add field cve to finding_template
    - Alter field match_field on child_rule
    - Alter field hash_code on finding
    - Alter field applied_field on rule
    - Alter field match_field on rule
  Branch 0004_cve_field
    - Alter field hash_code on finding
    - Add field title to test
    - Add field cve to finding
    - Add field cve to finding_template
    - Alter field match_field on child_rule
    - Alter field applied_field on rule
    - Alter field match_field on rule

Merging will only work if the operations printed above do not conflict
with each other (working on different fields or models)
Do you want to merge these migration branches? [y/N] y
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 142, in handle
    return self.handle_merge(loader, conflicts)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 311, in handle_merge
    with io.open(writer.path, "w", encoding='utf-8') as fh:
IOError: [Errno 13] Permission denied: '/app/dojo/db_migrations/0005_merge_20190511_1429.py'
```
7. Experience frustration ;-)

**Expected behavior**
1. Ideally migration just work automatically
2. Still ok, migration by hand works.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - dev branch

**Comment by ppiotr3k** [comment]
Weird, I don't see the `0005_merge_20190511_1429.py` file in current [db_migration folder](https://github.com/DefectDojo/django-DefectDojo/tree/055c20512dda36b35d56d1b4db882966e64272b6/dojo/db_migrations) on `dev` branch.
Isn't it a permission issue added by a new file in your local repository?

**Comment by madchap** [comment]
That merge file is generated by the `makemigrations --merge`. It does not exist in my `db_migration` folder either. At that stage, it is just a reference and cannot be persisted to disk due to the permission error.

**Comment by madchap** [comment]
Thanks for your comment @ppiotr3k, looking at it, I had another `0002_auto_` file in my directory from.. somewhere :-/ Removing that extra file, I am back in business.
