### ISSUE TITLE
Deduplication considers None a valid value for CWE and matches findings together

### ISSUE THREAD

**Issue by Ravenons** [DefectDojo/django-DefectDojo#1128]
**Bug description**
According to dojo/models.py, Finding model has default=0 and null=True for cwe field, so both 0 and None are valid values there.

In dojo/utils.py, sync_dedupe function looks for duplicate findings with the same cwe than the current finding, excluding cwe when it's equal to 0, but not when it's equal to None.

Nessus parser sometimes sets cwe to None, and therefore importing Nessus scans results in false duplicates in the same test, because it's grouping together findings with cwe equal to None.

There might be something similar in sync_false_history in the same file, because there it's filtering with cwe equal to None, but not filtering with cwe equal to 0.

You should decide if you want to change cwe field in Finding to be null=False or you want to check for both values (None and 0) every time you need to filter for an empty field. I can provide a PR for the way you choose.

**Steps to reproduce**
1. Enable deduplication
2. Create a finding with field cwe equal to None
3. Create a second finding with field cwe equal to None
4. Check that the second finding was marked as a duplicate of the first

**Expected behavior**
The second finding is not marked as a duplicate of the first

**Deployment method**
setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Debian 9.8 (stretch)
 - DefectDojo version: 01bf1ec9: Merge pull request #1084 from sbani/fix-jira-finding-issue [2019-05-10 18:05:11 +0200]

**Comment by adracea** [comment]
The problem also comes from the fact that numerous scanners don't give a certain cwe value to each issue so we would have to somehow either standardise this on our end or come up with a more complex deduplication system.

**Comment by valentijnscholten** [comment]
I think the deduplication logic should not consider these issues as "equal", 0 or None is clearly a surrogate value in these cases.

**Comment by Ravenons** [comment]
> The problem also comes from the fact that numerous scanners don't give a certain cwe value to each issue so we would have to somehow either standardise this on our end or come up with a more complex deduplication system.

That's true, but I would say that importers should not have that responsibility. DefectDojo core should be the one that's robust, because importers are written mostly by different people with different skill levels.

So in my opinion we have two options:

- cwe field with null=False (and keeping default=0)
- Every time you have to filter for an empty cwe, you have to filter both None and 0 values.

I would not recommend the latter, as people probably won't notice this and it could happen again (not checking for both values).

**Comment by madchap** [comment]
> The problem also comes from the fact that numerous scanners don't give a certain cwe value to each issue so we would have to somehow either standardise this on our end or come up with a more complex deduplication system.

We could attempt to automatically fill in the CWE, given the info at hand: https://github.com/DefectDojo/django-DefectDojo/issues/1119

**Comment by Ravenons** [comment]
Maybe @aaronweaver can decide how this should be handled.
