### ISSUE TITLE
Uploaded images can not be displayed

### ISSUE THREAD

**Issue by denniskniep** [DefectDojo/django-DefectDojo#1129]
**Bug description**
When starting defect dojo with docker-compose all uploaded images can not be displayed. I get a 404. 

The reason is probably the conditional url mapping on `settings.DEBUG` here https://github.com/DefectDojo/django-DefectDojo/blob/2a8e2ef508791f979e91a554165ae276d86a05be/dojo/urls.py#L177

Why is the media url only exposed in debug mode? (If I set `settings.DEBUG` to `on` everything works fine) 

**Steps to reproduce**
1. Start defect-dojo with docker-compose (the env variable `DD_DEBUG`  is set to `off` (https://github.com/DefectDojo/django-DefectDojo/blob/2a8e2ef508791f979e91a554165ae276d86a05be/docker-compose_uwsgi-release.yml#L10)
2. Upload an image to a finding
3. View the uploaded image
4. 404

**Expected behavior**
The image should be viewable

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - defectdojo/defectdojo-django:1.5.3.1 

**Additional context** (optional)

**Comment by devGregA** [comment]
I believe @propersam fixed this?

**Comment by propersam** [comment]
Yes, i created and issue #1204 fixed this in a PR that was just recently merged .

**Comment by propersam** [comment]
wait a minute.. i didn't fixx all of this... working on this now

**Comment by propersam** [comment]
PR made..

**Comment by propersam** [comment]
please have this assigned to me on the gsoc project board
