### ISSUE TITLE
Add Engagement Unit Tests

### ISSUE THREAD

**Issue by Maffooch** [DefectDojo/django-DefectDojo#1133]
Please use the following example at as a template:
https://github.com/DefectDojo/django-DefectDojo/blob/dev/tests/Product_unit_test_example.py

Implement the following tests:
- Add
- Edit
- Close
- Delete
- Import scan results
- Add new CI/CD Engagement

Master List and Overview: https://docs.google.com/document/d/1dSS7tWuQukAX3VWtzPAlOfFNoqLQh-mBHBfmsu2WlU0/edit?usp=sharing

**Comment by ppiotr3k** [comment]
@Maffooch, please, really have a look at https://github.com/DefectDojo/django-DefectDojo/issues/1131#issuecomment-493279138 before using https://github.com/DefectDojo/django-DefectDojo/blob/dev/tests/Product_unit_test_example.py for all the functional tests. :pray:

**Comment by dr3dd589** [comment]
@Maffooch working on this too.
