### ISSUE TITLE
BUG - Windows Invalid Path - remove : and <> from doc names please

### ISSUE THREAD

**Issue by testaccount90009** [DefectDojo/django-DefectDojo#11366]
Steps to Reproduce:

Clone DefectDojo on a Windows system and attempt to checkout branch.  Will run into errors like below, because of the ":"  and "<>" characters being invalid on Windows. 

git checkout dev
error: invalid path 'docs/content/en/dashboard/How-To: Add, Edit or Delete Dashboard Tiles.md'
error: invalid path 'docs/content/en/dashboard/How-To: Edit Dashboard Configuration.md'
error: invalid path 'docs/content/en/jira_integration/Configuring the Jira <> DefectDojo Webhook.md'
error: invalid path 'docs/content/en/working_with_findings/finding_deduplication/Avoiding Duplicates: Reimport Recurring Tests.md'
error: invalid path 'docs/content/en/working_with_findings/findings_workflows/How-To: Manage Duplicate Findings.md'
error: invalid path 'docs/content/en/working_with_findings/organizing_engagements_tests/Product Hierarchy: Overview.md'

**Comment by mtesauro** [comment]
@testaccount90009 We've got PR #11368 which address this situation (sorry, I'm on Linux only so didn't have this issue)

It's in the bugfix branch so will go out in the release Monday, Dec 9th.

**Comment by testaccount90009** [comment]
@mtesauro no worries, appreciate the quick response!

I have a new Mend parser to try and submit with a PR once this hotfix goes out.  I'll test it on my dev stack tomorrow and the rest of this week, in prep for Mondays release.  It should remedy https://github.com/DefectDojo/django-DefectDojo/issues/11340 as well.

**Comment by testaccount90009** [comment]
Closing this issue due to pending fix.
