### ISSUE TITLE
Add Finding Unit Tests

### ISSUE THREAD

**Issue by Maffooch** [DefectDojo/django-DefectDojo#1137]
Please use the following example at as a template:
https://github.com/DefectDojo/django-DefectDojo/blob/dev/tests/Product_unit_test_example.py

Implement the following tests:
- Add
- Edit
- Delete
- Import scan results
- Add Images
- Delete Images
- Mark for review
- Make a template and use template for another finding
- Close Finding

Master List and Overview: https://docs.google.com/document/d/1dSS7tWuQukAX3VWtzPAlOfFNoqLQh-mBHBfmsu2WlU0/edit?usp=sharing

**Comment by ppiotr3k** [comment]
@Maffooch, please, really have a look at https://github.com/DefectDojo/django-DefectDojo/issues/1131#issuecomment-493279138 before using https://github.com/DefectDojo/django-DefectDojo/blob/dev/tests/Product_unit_test_example.py for all the functional tests. :pray:

**Comment by propersam** [comment]
@Maffooch  assign this to me.
i'm done with product
