### ISSUE TITLE
Question about "Close old findings within this engagement."

### ISSUE THREAD

**Issue by R00G3R** [DefectDojo/django-DefectDojo#11379]
Hello everyone,

I have been using DefectDojo for a while to consolidate my results from Tenable Nessus.
Currently, I have been creating "engagements" and adding the results of the scans as shown in the screenshot below. However, I notice that if a vulnerability is no longer found in a future scan, it is not being closed automatically, even when importing the results using "Close old findings within this engagement."
Is there something I might be doing wrong?

![image](https://github.com/user-attachments/assets/6bfed167-5f78-46ab-a0d7-c3e75d104456)

This is an example of a finding that was added in the first upload of results. In the following results, it still existed and was added as duplicates. However, in tests after August 1st, it no longer appears in the results because it was fixed, but the finding still active.

![image](https://github.com/user-attachments/assets/c52404e8-efb5-4be6-88bb-997b5f25aede)

**Comment by mtesauro** [comment]
@R00G3R If you're scanning the same thing aka the scope of what you're scanning doesn't change, you want to use reimport rather then import to have DefectDojo auto-close findings which are only in previous scans and not in the current scan.

We just updated our docs site, so here's the info on reimport that's new:
https://docs.defectdojo.com/en/connecting_your_tools/import_scan_files/using_reimport/

And here's the original content on import & reimport:
https://docs.defectdojo.com/en/open_source/archived_docs/importing/

HTH

**Comment by R00G3R** [comment]
Thank you, @mtesauro
Just rebuild my engagements using re-uploading and everything works nicely.
