### ISSUE TITLE
Add the ability to import reports from wapiti

### ISSUE THREAD

**Issue by NRGLine4Sec** [DefectDojo/django-DefectDojo#1139]
Can you add the ability to import reports from [wapiti](http://wapiti.sourceforge.net/) ?
Maybe with the help of the [Faraday's parser](https://github.com/infobyte/faraday/blob/master/plugins/repo/wapiti/plugin.py)

**Comment by aaronweaver** [comment]
@NRGLine4Sec do you have a sample file you can attach?

**Comment by devGregA** [comment]
No sample scan, no support! 😂 Feel free to reopen if a sample scan is provided.

**Comment by NRGLine4Sec** [comment]
This is a repport scan by wapiti with the argument `-f openvas -o repport_scan_wapiti_https.xml` :
[repport_scan_wapiti_https.xml.zip](https://github.com/DefectDojo/django-DefectDojo/files/3231470/repport_scan_wapiti_https.xml.zip)

**Comment by dr3dd589** [comment]
hello @Maffooch working on this!

**Comment by devGregA** [comment]
Added via #1206
