### ISSUE TITLE
add the ability to import reports from sslyze

### ISSUE THREAD

**Issue by NRGLine4Sec** [DefectDojo/django-DefectDojo#1140]
Can you add the ability to import reports from [sslyze](https://github.com/nabla-c0d3/sslyze) ?
Maybe with the help of the [Faraday's parser](https://github.com/infobyte/faraday/blob/master/plugins/repo/sslyze/plugin.py)

**Comment by aaronweaver** [comment]
@NRGLine4Sec do you have a sample file you can attach?

**Comment by NRGLine4Sec** [comment]
This is a repport scan by sslyze :
[rapport_scan_sslyze_https.zip](https://github.com/DefectDojo/django-DefectDojo/files/3196911/rapport_scan_sslyze_https.zip)

**Comment by dr3dd589** [comment]
hello, @NRGLine4Sec Can you provide some information about which type of information you want to extract from this XML report and there is also no vulnerability describe in your report, how we decide which we have to parse or not?

**Comment by NRGLine4Sec** [comment]
The important information are :
* The use of Weak Cipher suite
* the validation of certificate
* the vulnerability in Heartblead, OpenSSL CCS Injection, ...
* when `isSecure=""` is not equal to true
* when `<sslv2 isProtocolSupported=""` is equal to true  (vulnerable)
* when `<sslv3 isProtocolSupported=""` is equal to true  (vulnerable)

For reference view this [importer](https://github.com/infobyte/faraday/blob/master/faraday/client/plugins/repo/sslyze/plugin.py)

**Comment by dr3dd589** [comment]
hello, @Maffooch working on it now, assign this to me.

**Comment by NRGLine4Sec** [comment]
#issuecomment-504677197
