### ISSUE TITLE
Link to upgrade notes is broken

### ISSUE THREAD

**Issue by d-mankowski-synerise** [DefectDojo/django-DefectDojo#11422]
For example: https://github.com/DefectDojo/django-DefectDojo/releases/tag/2.41.1

```
Please consult the [Upgrade notes in the documentation ](https://documentation.defectdojo.com/getting_started/upgrading/)
```

it should point to `https://docs.defectdojo.com/en/open_source/upgrading/upgrading_guide/`

**Comment by mtesauro** [comment]
@d-mankowski-synerise Thanks for the heads up. We recently completely redid our documentation site and this got missed. It's part of our release automation.

We should have it sorted out by the next release (Dec 23). :+1:
