### ISSUE TITLE
After 30 min -  [error] 14#14: *122 upstream timed out (110: Operation timed out) while reading response hea upstream: "uwsgi://unix:///run/defectdojo/uwsgi.sock", host: " 

### ISSUE THREAD

**Issue by roshvin** [DefectDojo/django-DefectDojo#11424]
**Slack us first!**
The easiest and fastest way to help you is via Slack. There's a free and easy signup to join our #defectdojo channel in the OWASP Slack workspace: [Get Access.](https://owasp.org/slack/invite)
If you're confident you've found a bug, or are allergic to Slack, you can submit an issue anyway.

**Be informative**

While uploading Gitleaks json file with 50K findings , we are getting below error after 30 min , each time its getting terminated after 30 min, is there any 30 min timeout setting.

```

2024/12/13 09:37:11 [error] 14#14: *122 upstream timed out (110: Operation timed out) while reading response hea upstream: "uwsgi://unix:///run/defectdojo/uwsgi.sock", host: "

```

**Problem description**
A clear and concise description of what the problem is. For errors include at least the exact error message you are seeing (including traceback).

**Deployment method** *(select with an `X`)*

- [ ] Kubernetes

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo version v. 2.40.2 

**Logs** 

```

2024/12/13 09:37:11 [error] 14#14: *122 upstream timed out (110: Operation timed out) while reading response hea upstream: "uwsgi://unix:///run/defectdojo/uwsgi.sock", host: "
```

**Sample scan files**
If applicable, add sample scan files to help reproduce your problem.

**Screenshots**

**Additional context** (optional)

**Comment by mtesauro** [comment]
There's many places where timeouts can impact a DefectDojo installation:
* Any proxy between you and the installation
* Any security device between you and the installation (e.g. WAF, VPN, ...)
* k8s ingress
* k8s networking/istio/whatever
* nginx (assuming you're fronting DD with the project's nginx container
* uwsgi

Generally these are _usually_ the nginx configuration but YMMV.

It is interesting that the `host: ` is empty in the log line you shared. That may also be an issue unless smaller uploads work as expected.

You could try using one of the projects small unit-test files to validate the ability of uploads in general assuming you've not already done that or have other imports that are working for you.

**Comment by roshvin** [comment]
Hi @mtesauro Thanks a lot for you support. Please find the details below.
- we dont have proxy setup , security device , k8 ingress etc between client and DD
- we are using default nginx container with DD 
- we are able to upload small json , also big ones with 10 K finding , 
- what we see is always it terminate with after 30 min and was wondering is there any 30 min disconnect settings in uwsgi , or nginx .

**Comment by valentijnscholten** [comment]
Sounds like it could be `uwsgi_read_timeout 1800;` in `nginx.conf` or `nginx_TLS.conf`.

**Comment by roshvin** [comment]
hi , @valentijnscholten  thanks a lot it worked.
