### ISSUE TITLE
Deduplication not working with apiv2 when close_old_findings=false and skip_duplicates=false

### ISSUE THREAD

**Issue by ptrovatelli** [DefectDojo/django-DefectDojo#1145]
**Bug description**
The deduplication doesn't seem to be working with the API v2 endpoint, or at least not the same way as an import in the GUI or with APIv1:
When close_old_findings=false and skip_duplicates=false the deduplication is not happening, even if it's activated in the system configuration (celery is running)

**What is working with APIV2**
When using the APIv2, we can handle the deduplication using the parameter close_old_findings : when true, findings that were in the previous scan type for the same product (or engagement) and that are not present in the new scan of the same type are closed (Inactive, Verified, Mitigated). 
Another option is to set skip_duplicates=true and in that case duplicates in the same product (or engagement) are not imported at all.
This is working fine as seen in test set test_apiv2_scan_import_options.py
However the deduplication as it works with imports through the GUI doesn't seem to work. Maybe that's the normal behavior but it's really counter intuitive.

**Steps to reproduce**
See test test_apiv2_deduplication.py in https://github.com/DefectDojo/django-DefectDojo/pull/1144
Or else, with Postman:

- Body / form-data / bulk edit: 
```
engagement:1
verified:true
active:true
lead:1
tags:test
scan_date:2019-04-30
scan_type:ZAP Scan
minimum_severity:Info
active:true
skip_duplicates:false
close_old_findings:false
```
- Add a file parameter and select "file" instead of "text" (activates multipart-form-data) with file tests/zap_sample_1vuln.xml (see https://github.com/DefectDojo/django-DefectDojo/pull/1144)
- Add the authorization header
- Post twice
- Wait 5 minutes

**Expected behavior**
The second finding imported should be detected as duplicate as the dedup is activated at system level. This is what happens when we do the same scenario using the GUI import or using apiV1

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - DefectDojo version: 
`7ce115fd: Merge pull request #1130 from Maffooch/dev [2019-05-16 18:43:08 -0500]`

**Sample scan files** (optional)
tests/zap_sample_1vuln.xml (see https://github.com/DefectDojo/django-DefectDojo/pull/1144)

**Screenshots** (optional)
See defect.docx, first screenshot

[defect.docx](https://github.com/DefectDojo/django-DefectDojo/files/3194583/defect.docx)

**Console logs** (optional)
See defect.log
[defect.log](https://github.com/DefectDojo/django-DefectDojo/files/3194585/defect.log)

**Additional context** (optional)
The strangest is that if I force the dedup with 
docker exec -it django-defectdojo_uwsgi_1 bash
./manage.py dedupe

Then both findings are detected as duplicate: finding 1 in duplicate of finding 2, finding 2 is duplicate of finding 1 (see  defect.docx, last screenshots)

**Comment by ptrovatelli** [comment]
Looking at the code, it seems that we have two separate dedup algorithm: 
- When using the APIv2 `import-scan`, dedup is done  in dojo/api_v2/serializers.py based on 
  - skip_duplicates and close_old_findings options
  - finding's hash_code
- When using the GUI, dedup is done with dojo/utils.py
  - There is no skip_duplicates nor close_old_findings option available in the GUI.
  - dedup is done based on cwe, title, line, file_path, date, dynamic/static finding, hash_code

Shouldn't we merge those algorithm in order to have a consistent behavior whether we're  using the API or a manual import? 

I have tried to test apiv1 `importscan` but could only obtain HTTP 501 Not implemented. Is that supposed to work?

**Comment by ptrovatelli** [comment]
I have to say I got used to the GUI algorithm and I fail to see how the API one could answer my requirements. 
Say you want to follow the evolution of vulnerabilities across releases:
1) You want to know what vulnerability is present in what release
2) You want to enrich vulnerabilities (add note for example) and keep this enrichment after re-importing the same vulnerability again and again (because you won't fix all the vulnerabilities right away)

Say you have vunl1 present in release 1.0.0 (engagement "1.0.0")
You have added a note in the finding attached to engagement 1.0.0
you have not fixed the vuln in the next release so it's imported again from the report into engagement 1.0.1.

With the API algorithm:
- skip_duplicates = true: will not import the vuln in engagement 1.0.1. Looking at findings attached to engagement 1.0.1 you may think this vuln was fixed, but it's not
- close_old_findings = true: importing the vuln into engagement 1.0.1 will create a new finding without any link to the finding that's attached to engagement 1.0.0 so you've actually lost all the work done on engagement 1.0.0 (note or any other addition in the finding)

With the GUI algorithm, if you don't select "deduplicate on engagement" this works: all vulnerabilities are present in all engagements. The duplicates ones have a specific status and there is a link to the original finding that can centralize all the work done on this specific finding, be it done during 1.0.0 release or any time later. 

What do you think? I can work on this but we need to agree on what exactly we want to do. Is anybody actually using the apiv2 webservice in a ci-cd? How did you overcome the limitations I have found? 

Ideally, i'd say : 
- In the gui : add skip_duplicates and close_old_findings checkboxes, in case anyone is using those
- In the gui algorithm add skip_duplicates and close_old_findings handling
- From the API: call the new gui algorithm

It may be the occasion to revisit the GUI deduplication algorithm. I don't really understand why it's done like this and why we don't just use the hash_code. If the hash_code was not good enough, instead of adding conditions in the algorithm why don't we just change the hash_code computation until it's good enough for the deduplication? It's there only for deduplication as far as I know.

To be complete there is a last element about deduplication: this `dojo/management/commands/dedupe.py` can be called to trigger an immediate deduplication: 
```
docker exec -it django-defectdojo_uwsgi_1 bash
./manage.py dedupe
```

From what i've seen, it can be impredictible so should be used with care, although in a production environment it won't be called

**Comment by ptrovatelli** [comment]
See also this other issue that should be addressed at the same time: https://github.com/DefectDojo/django-DefectDojo/issues/1176

**Comment by ptrovatelli** [comment]
@aaronweaver @adracea @valentijnscholten any thoughts?

**Comment by aaronweaver** [comment]
@ptrovatelli I remember when API v2 was fist submitted and this was a concern as to why there was "duplication" of code. In any case let's consolidate API V1, V2 and GUI to all use the same logic, what you've outline above seems reasonable and we should have a readthedocs page just on dedeuplication as that question comes up on how exactly it works.

**Comment by ptrovatelli** [comment]
@aaronweaver do you know why is there an apiv1 and an apiv2 by the way? is "importscan" from apiv1 supposed to work? I couldn't get it to work. I've used (postman / form data / bulk edit): 
```
verified:true
active:true
lead:1
tags:test
scan_date:2019-04-30
scan_type:ZAP Scan
minimum_severity:Info
```
+"file" parameter of type "file" (triggering multi-part request) which is tests/zap_sample.xml
with: POST http://localhost:8080/api/v1/engagements/1/importscan/
This gives http 501 not implemented

Same result with no parameter given except file (they are all optional)

The notable difference between `import-scan` from apiv2 and `importscan` from apiv1 is that skip_duplicates and close_old_findings options are not present in apiv1 (also apiv1 seems to want an URI with the engagement in it or else says: `A valid engagement must be supplied. Ex. /api/v1/engagements/1/` )

**Comment by aaronweaver** [comment]
The file has to be posted  in the body, you can look at the API wrapper in the repo for how it works. V1 was done with TastyPie and was difficult for some to use as the documentation it generates isn't that great and a little weird. Another person worked on V2 using django rest framework but didn't consolidate functions and ended up duplicating code. I solely use V1 as it works just fine for what I need while others preferred V2.

Ideally both would use the same function and then going forward we'd probably improve V2 but leave V1 for those that use it.

**Comment by ptrovatelli** [comment]
the file was fine, it's the engagement and lead format that weren't correct. the message made me think I had to put the engagement in the URL but it's not the case, it just meant that the engagement parameter needs to be an URI. This is working with APIv1:
http://localhost:8080/api/v1/importscan/
```
verified:true
active:true
lead:/api/v1/users/1/
tags:test
scan_date:2019-04-30
scan_type:ZAP Scan
minimum_severity:Info
engagement:/api/v1/engagements/3/
```
plus file parameter of the type "file" in postman (activates multi-part request)
The good news is that this is using the same deduplication as the GUI so my usecase works. I'll update my initial post with that information

**Comment by ptrovatelli** [comment]
i've added documentation about this in https://github.com/DefectDojo/Documentation/pull/42 . For the time being it may be enough as apiv1 is able to do what apiv2 fails to do. I'll look at https://github.com/DefectDojo/django-DefectDojo/issues/1176 first, it seems more urgent.

**Comment by ptrovatelli** [comment]
see also https://github.com/DefectDojo/django-DefectDojo/projects/7#card-20402679

**Comment by ptrovatelli** [comment]
> * close_old_findings = true: importing the vuln into engagement 1.0.1 will create a new finding without any link to the finding that's attached to engagement 1.0.0 so you've actually lost all the work done on engagement 1.0.0 (note or any other addition in the finding)

I was wrong on this: we can use "close_old_findings=true" which will set the findings that are not present anymore to "inactive/mitigated" in previous tests/engagements . Still the enrichment will remain for recurrent findings : the new finding will point to the old finding in case of duplicate

So in the end, both algorithms can work in a similar way. The main difference is that 
- with apiv2 and close_old_findings, if you want a vision of a previous test/engagement, you need to look at active and inactive/mitigated findings
- with apiv1/gui old findings remain unchanged
