### ISSUE TITLE
Introduction of a Sponsorship Logo Policy

### ISSUE THREAD

**Issue by wurstbrot** [DefectDojo/django-DefectDojo#1150]
A designer gave me the hint the sponsor-logos are looking ugly because they have different sizes and no margin.

# Easy solution
Add a line between each logo and add a space between 2 logos in the same row.

# Advanced solution
Define a logo size. In case a logo does match, the image will be scaled.
To scale an image, markdown might be used or the image is manually resized.

Maybe tables might be a good idea also. It needs to be discovered via trail and error.

I will do the work after I get approval for one solution.

**Comment by wurstbrot** [comment]
@devGregA

**Comment by devGregA** [comment]
@wurstbrot I agree that a policy is needed. Will work on this after the big upgrade this month.
