### ISSUE TITLE
JIRA configurations should have a unique display string

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1154]
**Is your feature request related to a problem? Please describe**
If having several JIRA configurations having the same JIRA URL and username, you can not distinguish them as the UI shows the URL and the username in the edit project view and JIRA config view. 

Configuration can vary, as the "Open status key" or "Close status key"  transitions can be different per project.

**Describe the solution you'd like**
Simply add a description field that will be used to uniquely identify the configuration for users at a glance (UI view) should be enough.

**Comment by valentijnscholten** [comment]
This would benefit us as well as we have different workflows and issuetypes in the same JIRA.

**Comment by devGregA** [comment]
@devEricA Please add a name that displays instead of the URL / username

**Comment by valentijnscholten** [comment]
Or maybe a name AND URL/username (between brackets)
