### ISSUE TITLE
Simple search should display engagement info

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1155]
**Is your feature request related to a problem? Please describe**
When simple searching, the finding results table should include the engagement and associated test in which findings reside. It would make it easier to know where it is located without having to click on the title.

**Describe the solution you'd like**
Add an extra column(s) that display and link to finding's engagement and associated test.

**Comment by devGregA** [comment]
@aaronweaver do you have any thoughts on this?

**Comment by aaronweaver** [comment]
@devGregA yes, makes sense.
