### ISSUE TITLE
Findings cannot return to any other status but duplicate once set

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1157]
**Bug description**
Edit a finding and mark it as duplicate (hence non active nor verified). If you try to make it active and verified again, it won't work despite the successful message.

**Steps to reproduce**
1. Go to a finding and mark it duplicate
2. Save
3. Go back to that finding, and mark it active, verified.
4. Save
5. Notice the status didn't change
6. Re-edit finding and notice the checkboxes were not saved properly.

**Expected behavior**
The finding goes back to whatever is checked.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - dev branch.

**Comment by devGregA** [comment]
@devEricA please investigate once you finish reviewing that PR.

**Comment by devEricA** [comment]
No dice in getting the bug reproduced @devGregA. I followed all of the steps to produce this bug. Checking active and verified simply sets the finding status back to active and verified, even after un-marking the duplicate checkbox. Attempting to mark active and verified while the duplicate checkbox is marked results in a message 'duplicate findings cannot active and verified' without throwing an exception.

**Comment by devGregA** [comment]
@devEricA did you try master dev or both?

**Comment by devEricA** [comment]
I did dev because that's the branch noted in the environment information.

**Comment by devGregA** [comment]
Oh okay, missed that, thanks. @madchap I think this is coming from dedupe overriding statuses rather than an issue with the actual progression of active / verified / duplicate.

**Comment by madchap** [comment]
OK, thanks.

Could there be at least a logging message when this happens? I encountered that this week again, and this is troubling.
