### ISSUE TITLE
404 for static files retrieved as dependencies when running dev docker

### ISSUE THREAD

**Issue by nbuzydeb** [DefectDojo/django-DefectDojo#1160]
**Bug description**
When running DefectDojo in debug (using the aliases_dev.sh script and then docker-compose up, as described in DOCKER.md; I hope I didn't miss any step ?), static files that are dependencies (so DefectDojo own static files are successfully retrieved it seems) can't be retrieved and result in 404.

**Steps to reproduce**
1. Run DefectDojo in Debug with Docker using aliases_dev.sh & docker-compose up
2. Try browsing to http://localhost:8000
3. UI is broken as many files can't be retrieved. Those can be seen on the console output. 

**Expected behavior**
Dependencies should be successfully retrieved, leading to a working UI.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: MacOS 10.14.5
 - DefectDojo version: 2a8e2ef5: Merge pull request #1109 from wurstbrot/patch-1 [2019-05-06 12:13:47 -0400]

**Screenshots** (optional)
![Screenshot 2019-05-22 at 12 19 22 PM](https://user-images.githubusercontent.com/10597937/58147216-099c1380-7c8c-11e9-899f-6cd9eabd188e.png)

**Console logs** (optional)
<img width="872" alt="Screenshot 2019-05-22 at 12 04 00 PM" src="https://user-images.githubusercontent.com/10597937/58147141-bb871000-7c8b-11e9-998e-220d20f3f667.png">

**Comment by madchap** [comment]
I have experienced the same. 

As a possible workaround, launch the `docker-compose_uwsgi-release.yml` first, `docker cp` the static content locally from the uwsgi container, and then launch the `docker-compose_uwsgi-dev.yml`.

**Comment by aaronweaver** [comment]
@ptrovatelli has been working on updates to the dev compose, you may want to try out what he's been working on.

**Comment by ayomawdb** [comment]
In Dev environment DefectDojo (uwsgi) is exposed over port 8000. 

https://github.com/DefectDojo/django-DefectDojo/blob/2a8e2ef508791f979e91a554165ae276d86a05be/docker-compose_uwsgi-dev.yml#L14

However, the Nginx instance pointing to static resources in question is exposed over port 8080 

https://github.com/DefectDojo/django-DefectDojo/blob/2a8e2ef508791f979e91a554165ae276d86a05be/docker-compose_base.yml#L9

When in Dev environment DefectDojo tries to load static resources from port 8000 which fails, since they are exposed from 8080. I am trying to find a simpler fix, but it might take some time since I am new to the project.

**Comment by nbuzydeb** [comment]
> I have experienced the same.
> 
> As a possible workaround, launch the `docker-compose_uwsgi-release.yml` first, `docker cp` the static content locally from the uwsgi container, and then launch the `docker-compose_uwsgi-dev.yml`.

These files were present in the nginx container (no difference with the release version on that side), so the initial retrieval of these files actually worked. But somehow, the live web application was unable to fetch the files from the container it seems.

> @ptrovatelli has been working on updates to the dev compose, you may want to try out what he's been working on.

I have just checked out @ptrovatelli 's PR and tried, it seems it fixes the issue :)

**Comment by nbuzydeb** [comment]
8c558b8acc5b0827edaaa96a5936960a6e3b3d6d fixes the issue for me, so I'm closing this ticket.
