### ISSUE TITLE
Non-Staff (non-admin) users can't add or edit any product or engagement.

### ISSUE THREAD

**Issue by cymxiao** [DefectDojo/django-DefectDojo#1161]
**Bug description** 
Even with all permissions added to a group, and a non-staff user in that group, that user cannot add or edit the product even this user has been authorized to the product. each time I try to add an engagement or edit the product with a  non-staff user , it would redirect to login page.

even with all the permissions added, there are no menu options for Engagements, Tests, Findings, etc.... only Products, Reports, Metrics and Configuration. The user is also added to the authorized users field of a product. Anything we are doing wrong on our end?

It's similar with issue Non-Staff (non-admin) users can't see findings #385 https://github.com/DefectDojo/django-DefectDojo/issues/385#event-1529214983

**Steps to reproduce**
1.  using usr/pwd:    product_manager / defectdojo@demo#product  to login to official test environment: https://defectdojo.herokuapp.com/
2. Click on  product:  BodgeIt 
3. edit the active engagement : AdHoc Import - Fri, 17 Aug 2018
4. it would redirect to login page.
 

**Expected behavior** 
since the  non-staff user has been assigned with full permission, it should has permission to add or edit product or engagement.

**Comment by devGregA** [comment]
Hi @cymxiao this is intended behavior. When Dojo was first written, the Django admin interface wasn't near as good as it is today. At some point in the future we'll look at adjusting permissions, but our focus currently is on unit tests and python3.
