### ISSUE TITLE
Server Error (500) importing Fortify scan XML file

### ISSUE THREAD

**Issue by dougmcdorman** [DefectDojo/django-DefectDojo#1171]
When attempting to import a Fortify XML scan report the server gives Server Error (500) from the underlying "TypeError: cannot concatenate 'str' and 'int' objects" fault.

**Steps to reproduce**
1. Download  docker-compose_base.yml docker-compose_uwsgi-release.yml
2. docker-compose -f docker-compose_base.yml -f docker-compose_uwsgi-release.yml up
3. Attempt to upload a Fortify Scan XML file created from results.fpr using ReportGenerator 
4. 500 error (from webserver)

**Expected behavior**
Fortify scan would be imported.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Windows 10 with Docker Toolbox and Virtualbox
 - Lastest on git release website, just downloaded the 2  docker-compose_base.yml docker-compose_uwsgi-release.yml files directly

**Sample scan files** (optional)
Will try to create redacted version.

**Console logs** (optional)
uwsgi_1         | Internal Server Error: /product/1/import_scan_results
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
uwsgi_1         |     response = self._get_response(request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
uwsgi_1         |     return view_func(request, *args, **kwargs)
uwsgi_1         |   File "./dojo/product/views.py", line 382, in import_scan_results_prod
uwsgi_1         |     return import_scan_results(request, pid=pid)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
uwsgi_1         |     return view_func(request, *args, **kwargs)
uwsgi_1         |   File "./dojo/engagement/views.py", line 519, in import_scan_results
uwsgi_1         |     parser = import_parser_factory(file, t)
uwsgi_1         |   File "./dojo/tools/factory.py", line 123, in import_parser_factory
uwsgi_1         |     parser = FortifyXMLParser(file, test)
uwsgi_1         |   File "./dojo/tools/fortify/parser.py", line 91, in __init__
uwsgi_1         |     dupe_key = (title + sev + cwe_id)
uwsgi_1         | TypeError: cannot concatenate 'str' and 'int' objects

**Additional context** (optional)
in 
 django-DefectDojo/dojo/tools/fortify/parser.py  line 60
 cwe_id = 0
This should probably be:
 cwe_id = "0"
So that it is a string not an integer. In my Fortify XML scan result there are no CWEs in the < groupTitle > so it is probably always dropping to the cwe_id = 0.
This is later used in line 91, where it tries to concatenate this now int with strings and faults.
 dupe_key = (title + sev + cwe_id)
TypeError: cannot concatenate 'str' and 'int' objects

**Comment by dr3dd589** [comment]
hello @dougmcdorman Can you provide scan sample which produces this error so that we can easily reproduce it?

**Comment by aaronweaver** [comment]
@dougmcdorman Did you try your suggest change of making it = "0"?

**Comment by dougmcdorman** [comment]
I haven't been able to run a dev environment yet so I can't try the fix. When I try the dev environment I see this in the logs and the webserver doesn't respond:
nginx_1         | nginx: [emerg] host not found in upstream "uwsgi:3031" in /run/uwsgi_server:1
django-defectdojo_nginx_1 exited with code 1

If someone can provide more guidance on getting a dev environment going I will try, asked in slack.

I plan to try redacting the scan result so I can share.

**Comment by devGregA** [comment]
I believe th correct fix is to extend cast the int to string for the
purposes of the dupe key.

**Comment by devGregA** [comment]
** instead

**Comment by dougmcdorman** [comment]
@devGregA I thought about that but if it does find a CWE value then that is going to be a string not an int so then you would be trying to cast a string from an int to an string. I'm hoping I can find some older or other Forify scan results around that have the CWE value to test that as well. But I don't know if I will find any or if they really ever have that.

**Comment by dougmcdorman** [comment]
Added redacted scan file. I ripped out most of the results so I can't guarantee it is still completely valid but it does cause the same error. If I can get a dev environment running I will compare results with the unredacted file.
The unredacted xml file was generated from the Fortify .fpr file using the ReportGenerator utility since the original fpr file is actually a zip file containing a whole bunch of files:
C:\Program Files\HPE_Security\Fortify_SCA_and_Apps_17.20\bin\ReportGenerator.bat -format XML -f fortify_v18.20.1046.xml -source fortify_v18.20.1046.fpr

[fortify_v18.20.1046.xml.zip](https://github.com/DefectDojo/django-DefectDojo/files/3215223/fortify_v18.20.1046.xml.zip)

**Comment by dougmcdorman** [comment]
@dr3dd589 redacted scan file in the above comment.

**Comment by dr3dd589** [comment]
main problem is here in grouptitles:
`<groupTitle>Privilege Management: Unnecessary Permission</groupTitle>`
`<groupTitle>Null Dereference</groupTitle>`
`<groupTitle>&lt;none&gt;</groupTitle>`
`<groupTitle>Issue New: May 7, 2019</groupTitle>`

which is not fixed and in the parser, it checks cwe no in <groupTitle> also the sample you provided does not contain any cwe no in <groupTitle> and in fortify parser it uses this method to extract cwe no which raise problem:
```
     cwe_id = grouptitle.split(' ')
     if len(cwe_id) > 2:
              cwe_id = cwe_id[2]
               if "," in cwe_id:
                       cwe_id = cwe_id[:1]
      else:
              cwe_id = 0
```
I cannot find old fortify sample based on this parser is created.
to fix this I need the latest fortify scan sample which contains also cwe number in xml file so that I can figure it out how to extract.

**Comment by devGregA** [comment]
@devEricA please investigate this for you next issue. @dougmcdorman has attached a sample scan.

**Comment by dougmcdorman** [comment]
@devEricA I should have a PR ready in a couple days.

**Comment by devEricA** [comment]
@devGregA and @aaronweaver I think I have a fix ready. Before I push, I would like to obtain older fortify scans in order to ensure that my updates work with the older files. Where could I find those files?

**Comment by aaronweaver** [comment]
@devEricA I can't seem to find any. @devGregA I thought we had some but I can't find it.

**Comment by dougmcdorman** [comment]
Note the OWASP Benchmark program also has a Fortify parser, but I'm not use if they are using the .fpr file or a generated report. 
https://github.com/OWASP/Benchmark/blob/master/src/main/java/org/owasp/benchmark/score/parsers/FortifyReader.java

I have managed to get the report generator and a modified defectdojo parser to give all results instead of just a sample from each category. @devEricA perhaps you want to share what you did for a fix and I can merge my changes in.

**Comment by dougmcdorman** [comment]
@devEricA Were you given any scans that include a CWE in the groupTitle? If so what did it look like? Can you provide some of the values for the groupTitle?

I took a look at your changes and I wanted to suggest a few modifications. The original code before your updated doesn't seem very robust and I was hoping we could try to improve it.
Note .isdigit will give false if it finds whitespace even though converting to int would work.
I would propose that where the cwe_id is read it always gives the same type of value (a string or an int).

The logic in the original file doesn't seem to make sense, it always looks to see if the second word is a number, I suppose if the first word is "cwe" then that would make sense but then it seems it should test for that. I could see the CWE number being tacked onto the end, but then it wouldn't always be the second word. But I have no example with a cwe to go by. 

If we want to assume it is always the second word, which could contain a comma, then I would suggest this:
                    # The cwe number always seems to appear in the second word but might contain a comma
                    cwe_id_list = grouptitle.split(' ')
                    if len(cwe_id_list) > 2:
                        cwe_id = cwe_id_list[2].replace(',', '')  # replace any ","
                    else 
                        cwe_id = "0"

                    try:
                        cwe_int=int(cwe_id)
                    except ValueError:  # if the exception ValueError comes up then it couldn't be converted to a int
                        cwe_id = "0"
                        cwe_int = 0

and lower down
                        dupe_key = (title + sev + cwe_id)

                            find = Finding(title=title,
                                            cwe=cwe_int,
