### ISSUE TITLE
DefectDojo Docker fails to launch 

### ISSUE THREAD

**Issue by Hax0rG1rl** [DefectDojo/django-DefectDojo#1172]
**Bug description**

The latest DofectDojo framework fails to launch when following the provided starting steps. 

**Steps to reproduce**
1. Clone the defectdojo locally
2. Follow the run instructions

```
git clone https://github.com/DefectDojo/django-DefectDojo
cd django-DefectDojo
docker-compose up
```

```
docker-compose up
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
```

**Expected behavior**

The image to build and properly launched. 

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Ubuntu 18.04
 - 2a8e2ef5: Merge pull request #1109 from wurstbrot/patch-1 [2019-05-06 12:13:47 -0400]

**Comment by mtesauro** [comment]
Update docker and docker compose to the latest.

docker compose is a separate update from docker and usually manual (depends
on platform)

See:
https://defectdojo.readthedocs.io/en/latest/getting-started.html#docker-compose-install

--
-- Matt Tesauro
OWASP AppSec Pipeline Lead
https://www.owasp.org/index.php/OWASP_AppSec_Pipeline
OWASP WTE Project Lead
https://www.owasp.org/index.php/OWASP_Web_Testing_Environment_Project
http://AppSecLive.org - Community and Download site

**Comment by Hax0rG1rl** [comment]
Heya, 

Thanks for your quick answer. I got the compose updated and, as you can see, I do use the latest version. 

```
monkey@ubuntu:~/Desktop/django-DefectDojo$ sudo docker-compose --version 
docker-compose version 1.24.0, build 0aa59064
```

However, I still get this: 

```
monkey@ubuntu:~/Desktop/django-DefectDojo$ git reset --hard
HEAD is now at 2a8e2ef5 Merge pull request #1109 from wurstbrot/patch-1
monkey@ubuntu:~/Desktop/django-DefectDojo$ git pull origin 
Already up to date.
monkey@ubuntu:~/Desktop/django-DefectDojo$ docker-compose up 
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
``

Thanks!

**Comment by dougmcdorman** [comment]
Perhaps try it with this command. 
docker-compose -f docker-compose_base.yml -f docker-compose_uwsgi-release.yml up

I don't see your steps to reproduce ding the command . docker/aliases_release.sh) as per ths info here:

https://github.com/DefectDojo/django-DefectDojo/blob/master/DOCKER.md

**Comment by mtesauro** [comment]
Interesting.  Last time I ran the docker-compose I got the same error and
updating docker (docker ce to be precise) and docker-compose worked for
me.  I'm also on Ubuntu 18.04:
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

Let me pull down a the latest from master and give it a go again.  I tested
the docker-compose in master ~ 1 month ago and it worked for me (after
updating the docker bits).

The usual culprit is docker-compose being out of date - at least the last N
times we've had issues with docker-compose.  It will probably will be
tomorrow before I get a chance to test out the latest version from master.

Cheers!

--
-- Matt Tesauro
OWASP Defect Dojo
https://www.defectdojo.org/
OWASP AppSec Pipeline Lead
https://github.com/appsecpipeline
OWASP WTE Project Lead
https://github.com/mtesauro/owasp-wte

**Comment by Hax0rG1rl** [comment]
Hi, 

@dougmcdorman , @mtesauro, the issue got resolved running that cli:

```
docker-compose -f docker-compose_base.yml -f docker-compose_uwsgi-release.yml up
```

However, a standard user like me would expect to have this started by simply running the docker-compose up.

And, yes, I am using the latest version of docker got it from the official docker web site and not the package delivered by the official Ubuntu repositories available through an apt-get command. 

I'll close this one now. 

Thanks!

**Comment by Hax0rG1rl** [comment]
@mtesauro @aaronweaver Side question, is there any commercial support for this product? How can I get more info about such an option? Thanks!

**Comment by dougmcdorman** [comment]
@Hax0rG1rl all I know is that the FAQ says this:
https://www.defectdojo.org/#faq5
Is hosting, custom integration and commercial support available for DefectDojo?
Yes, commercial support and integration is available for DefectDojo through
10Security https://10security.com/

**Comment by devGregA** [comment]
Hi @Hax0rG1rl please send an email to info@10security.com
