### ISSUE TITLE
defectdojo master:dev will not run /usr/bin/env: ‘bash\r’: No such file or directory

### ISSUE THREAD

**Issue by dougmcdorman** [DefectDojo/django-DefectDojo#1173]
**Bug description**
Attempting to run a dev instance of defectdojo via docker compose but the web site does not come up.
Log shows: 
uwsgi_1         | /usr/bin/env: ‘bash\r’: No such file or directory
django-defectdojo_uwsgi_1 exited with code 127

**Steps to reproduce**
1. . docker/aliases_dev.sh
2. docker-compose up
3. http://localhost:8080
4. Unable to connect

**Expected behavior**
The web interface loads.
Note: the web interface does load when using release via:
. docker/aliases_release.sh
docker-compose up

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
- Windows 10 with Docker Toolbox and Virtualbox
- git show -s --format="%h: %s [%ci]"
2a8e2ef5: Merge pull request #1109 from wurstbrot/patch-1 [2019-05-06 12:13:47 -0400]
Note, there are no code changes in my local copy.

**Console logs** (optional)
$ . docker/aliases_dev.sh
$ docker-compose up
Starting django-defectdojo_mysql_1    ... done
Starting django-defectdojo_rabbitmq_1    ... done
Starting django-defectdojo_uwsgi_1        ... done
Starting django-defectdojo_initializer_1  ... done
Starting django-defectdojo_celeryworker_1 ... done
Starting django-defectdojo_celerybeat_1   ... done
Starting django-defectdojo_nginx_1        ... done
Attaching to django-defectdojo_mysql_1, django-defectdojo_rabbitmq_1, django-defectdojo_initializer_1, django-defectdojo_celeryworker_1, django-defectdojo_celerybeat_1, django-defectdojo_uwsgi_1, django-defectdojo_nginx_1
mysql_1         | 2019-05-24T04:58:10.920337Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql_1         | 2019-05-24T04:58:10.931557Z 0 [Note] mysqld (mysqld 5.7.26) starting as process 1 ...
mysql_1         | 2019-05-24T04:58:10.957366Z 0 [Note] InnoDB: PUNCH HOLE support available
mysql_1         | 2019-05-24T04:58:10.957954Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql_1         | 2019-05-24T04:58:10.958334Z 0 [Note] InnoDB: Uses event mutexes
mysql_1         | 2019-05-24T04:58:10.958511Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mysql_1         | 2019-05-24T04:58:10.958760Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mysql_1         | 2019-05-24T04:58:10.960161Z 0 [Note] InnoDB: Using Linux native AIO
mysql_1         | 2019-05-24T04:58:10.961327Z 0 [Note] InnoDB: Number of pools: 1
mysql_1         | 2019-05-24T04:58:10.961803Z 0 [Note] InnoDB: Using CPU crc32 instructions
mysql_1         | 2019-05-24T04:58:10.968211Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
uwsgi_1         | /usr/bin/env: ‘bash\r’: No such file or directory
mysql_1         | 2019-05-24T04:58:11.028010Z 0 [Note] InnoDB: Completed initialization of buffer pool
mysql_1         | 2019-05-24T04:58:11.037003Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql_1         | 2019-05-24T04:58:11.061154Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
mysql_1         | 2019-05-24T04:58:11.077656Z 0 [Note] InnoDB: Log scan progressed past the checkpoint lsn 20920752
mysql_1         | 2019-05-24T04:58:11.078488Z 0 [Note] InnoDB: Doing recovery: scanned up to log sequence number 20920761
mysql_1         | 2019-05-24T04:58:11.078921Z 0 [Note] InnoDB: Database was not shutdown normally!
django-defectdojo_uwsgi_1 exited with code 127
nginx_1         | 2019/05/24 04:58:11 [emerg] 1#1: host not found in upstream "uwsgi:3031" in /run/uwsgi_server:1
nginx_1         | nginx: [emerg] host not found in upstream "uwsgi:3031" in /run/uwsgi_server:1
mysql_1         | 2019-05-24T04:58:11.079623Z 0 [Note] InnoDB: Starting crash recovery.
mysql_1         | 2019-05-24T04:58:11.354153Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
mysql_1         | 2019-05-24T04:58:11.355776Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
django-defectdojo_nginx_1 exited with code 1
mysql_1         | 2019-05-24T04:58:11.356198Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql_1         | 2019-05-24T04:58:11.422861Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql_1         | 2019-05-24T04:58:11.424861Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
mysql_1         | 2019-05-24T04:58:11.425240Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
mysql_1         | 2019-05-24T04:58:11.427857Z 0 [Note] InnoDB: Waiting for purge to start
mysql_1         | 2019-05-24T04:58:11.478575Z 0 [Note] InnoDB: 5.7.26 started; log sequence number 20920761
mysql_1         | 2019-05-24T04:58:11.480550Z 0 [Note] Plugin 'FEDERATED' is disabled.
mysql_1         | 2019-05-24T04:58:11.486116Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql_1         | 2019-05-24T04:58:11.503137Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
mysql_1         | 2019-05-24T04:58:11.506459Z 0 [Warning] CA certificate ca.pem is self signed.
mysql_1         | 2019-05-24T04:58:11.514706Z 0 [Note] InnoDB: Buffer pool(s) load completed at 190524  4:58:11
mysql_1         | 2019-05-24T04:58:11.517900Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
mysql_1         | 2019-05-24T04:58:11.518319Z 0 [Note] IPv6 is available.
mysql_1         | 2019-05-24T04:58:11.518985Z 0 [Note]   - '::' resolves to '::';
mysql_1         | 2019-05-24T04:58:11.519296Z 0 [Note] Server socket created on IP: '::'.
mysql_1         | 2019-05-24T04:58:11.522575Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
mysql_1         | 2019-05-24T04:58:11.553271Z 0 [Note] Event Scheduler: Loaded 0 events
mysql_1         | 2019-05-24T04:58:11.554640Z 0 [Note] mysqld: ready for connections.
mysql_1         | Version: '5.7.26'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
initializer_1   | wait-for-it.sh: waiting 60 seconds for mysql:3306
initializer_1   | wait-for-it.sh: mysql:3306 is available after 2 seconds
initializer_1   | Initializing.
initializer_1   | Admin user: admin
initializer_1   | Admin password: redacted
mysql_1         | 2019-05-24T04:58:12.065306Z 2 [Note] Got an error reading communication packets
celeryworker_1  | wait-for-it.sh: waiting 30 seconds for mysql:3306
celeryworker_1  | wait-for-it.sh: mysql:3306 is available after 2 seconds
celerybeat_1    | wait-for-it.sh: waiting 30 seconds for mysql:3306
celerybeat_1    | wait-for-it.sh: mysql:3306 is available after 2 seconds
mysql_1         | 2019-05-24T04:58:12.459745Z 3 [Note] Got an error reading communication packets

**Comment by dougmcdorman** [comment]
I also tried in the dev branch, same result.
$ git show -s --format="%h: %s [%ci]"
ce53e8ff: Merge pull request #1153 from dr3dd589/ProductTypeTest [2019-05-22 15:11:37 -0500]

**Comment by dougmcdorman** [comment]
I am suspecting this is due to git converting files to windows CR/LF.
It looks like a .gitattributes file in the root of the project could fix this for everyone using windows.
https://help.github.com/en/articles/dealing-with-line-endings#platform-windows

**Comment by dougmcdorman** [comment]
I changed the line endings with this:
find . -type f -print0 | xargs -0 dos2unix

Then docker-compose build
. docker/aliases_dev.sh
docker-compose up

It gets farther but now I get this error in the browser:
"An error occurred.
Sorry, the page you are looking for is currently unavailable.
Please try again later.
If you are the system administrator of this resource then you should check the error log for details.
Faithfully yours, nginx."

Log shows:
A few of these, then the failed request below
uwsgi_1         | Waiting for initializer to complete

nginx_1         | 2019/05/24 20:55:08 [error] 6#6: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.99.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://172.19.0.7:3031", host: "192.168.99.102:8080", referrer: "http://192.168.99.102:8080/"

**Comment by jsalado** [comment]
I'm having the same issue afer building locally the images from the dev branch, then
docker-compose up
http://myserver:8080
Get the error page as above

Log shows:
nginx_1         | 2019/05/28 14:45:30 [error] 7#7: *18 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.1.82, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://172.22.0.4:3031", host: "dockerserver.kiuwan.com:8080"
nginx_1         | 192.168.1.82 - - [28/May/2019:14:45:30 +0000] "GET / HTTP/1.1" 502 494 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "-"

**Comment by jsalado** [comment]
I got the dev instance working:

I checked out the dev branch  and built the images manually with:
docker build -t defectdojo/defectdojo-django -f Dockerfile.django .
docker build -t defectdojo/defectdojo-nginx -f Dockerfile.nginx .

Then I run:
. docker/aliases_release.sh
docker-compose up

This brings up a working instance of the dev branch. Notice that I use aliases_release.sh not aliases_dev.sh that one does not work!!!

**Comment by dougmcdorman** [comment]
@jsalado great! that worked for me as well! I will have to do some more testing with a .gitattributes and submit a PR to add one so that docker for windows will work at least for the dev branch in release (mode?).

**Comment by Teazane** [comment]
Hello there!
I got the same problem when I tried to run DefectDojo through Docker method.
I tried to change the line endings as suggested above, but nothing changed, the problem was still here, so I decided to reopen this issue (also it seems that no pull request has been made or accepted as no .gitattributes has been added to the project so far). 

Here's what I use:
- Windows 10
- Docker Desktop v. 2.1.0.5 (including Docker v. 19.03.5 and Docker-compose V. 1.24.1)

With a simple "doker-compose up" here's the problems I got:
```
initializer_1   | /usr/bin/env: ‘bash\r’: No such file or directory
celeryworker_1  | /usr/bin/env: ‘bash\r’: No such file or directory
uwsgi_1         | /usr/bin/env: ‘bash\r’: No such file or directory
celerybeat_1    | /usr/bin/env: ‘bash\r’: No such file or directory
nginx_1         | standard_init_linux.go:211: exec user process caused "no such file or directory"
django-defectdojo_celeryworker_1 exited with code 127
django-defectdojo_celerybeat_1 exited with code 127
django-defectdojo_uwsgi_1 exited with code 127
django-defectdojo_initializer_1 exited with code 127
django-defectdojo_nginx_1 exited with code 1
```

For more information, here are the complete logs:
```
Starting django-defectdojo_mysql_1    ... done
Starting django-defectdojo_rabbitmq_1    ... done
Starting django-defectdojo_initializer_1  ... done
Starting django-defectdojo_uwsgi_1        ... done
Starting django-defectdojo_celerybeat_1   ... done
Starting django-defectdojo_celeryworker_1 ... done
Starting django-defectdojo_nginx_1        ... done
Attaching to django-defectdojo_mysql_1, django-defectdojo_rabbitmq_1, django-defectdojo_initializer_1, django-defectdojo_celeryworker_1, django-defectdojo_uwsgi_1, django-defectdojo_celerybeat_1, django-defectdojo_nginx_1
mysql_1         | 2020-01-31T14:48:14.618320Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql_1         | 2020-01-31T14:48:14.619898Z 0 [Note] mysqld (mysqld 5.7.27) starting as process 1 ...
mysql_1         | 2020-01-31T14:48:14.625528Z 0 [Note] InnoDB: PUNCH HOLE support available
mysql_1         | 2020-01-31T14:48:14.625785Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql_1         | 2020-01-31T14:48:14.625907Z 0 [Note] InnoDB: Uses event mutexes
mysql_1         | 2020-01-31T14:48:14.626003Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mysql_1         | 2020-01-31T14:48:14.626108Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mysql_1         | 2020-01-31T14:48:14.626117Z 0 [Note] InnoDB: Using Linux native AIO
mysql_1         | 2020-01-31T14:48:14.626544Z 0 [Note] InnoDB: Number of pools: 1
mysql_1         | 2020-01-31T14:48:14.626648Z 0 [Note] InnoDB: Using CPU crc32 instructions
mysql_1         | 2020-01-31T14:48:14.628325Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
mysql_1         | 2020-01-31T14:48:14.640150Z 0 [Note] InnoDB: Completed initialization of buffer pool
mysql_1         | 2020-01-31T14:48:14.643441Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql_1         | 2020-01-31T14:48:14.655766Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
mysql_1         | 2020-01-31T14:48:14.661457Z 0 [Note] InnoDB: Log scan progressed past the checkpoint lsn 12464725
mysql_1         | 2020-01-31T14:48:14.661486Z 0 [Note] InnoDB: Doing recovery: scanned up to log sequence number 12464734
mysql_1         | 2020-01-31T14:48:14.661493Z 0 [Note] InnoDB: Database was not shutdown normally!
mysql_1         | 2020-01-31T14:48:14.661497Z 0 [Note] InnoDB: Starting crash recovery.
mysql_1         | 2020-01-31T14:48:14.859105Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
mysql_1         | 2020-01-31T14:48:14.859174Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql_1         | 2020-01-31T14:48:14.859399Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
initializer_1   | /usr/bin/env: ‘bash\r’: No such file or directory
mysql_1         | 2020-01-31T14:48:15.334882Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
celeryworker_1  | /usr/bin/env: ‘bash\r’: No such file or directory
mysql_1         | 2020-01-31T14:48:15.336370Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
mysql_1         | 2020-01-31T14:48:15.337100Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
mysql_1         | 2020-01-31T14:48:15.337991Z 0 [Note] InnoDB: Waiting for purge to start
mysql_1         | 2020-01-31T14:48:15.388818Z 0 [Note] InnoDB: 5.7.27 started; log sequence number 12464734
mysql_1         | 2020-01-31T14:48:15.390150Z 0 [Note] Plugin 'FEDERATED' is disabled.
mysql_1         | 2020-01-31T14:48:15.401889Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
mysql_1         | 2020-01-31T14:48:15.402116Z 0 [Warning] CA certificate ca.pem is self signed.
mysql_1         | 2020-01-31T14:48:15.413494Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql_1         | 2020-01-31T14:48:15.415393Z 0 [Note] InnoDB: Buffer pool(s) load completed at 200131 14:48:15
mysql_1         | 2020-01-31T14:48:15.418827Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
mysql_1         | 2020-01-31T14:48:15.418877Z 0 [Note] IPv6 is available.
mysql_1         | 2020-01-31T14:48:15.418891Z 0 [Note]   - '::' resolves to '::';
mysql_1         | 2020-01-31T14:48:15.418905Z 0 [Note] Server socket created on IP: '::'.
mysql_1         | 2020-01-31T14:48:15.438650Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
mysql_1         | 2020-01-31T14:48:15.489024Z 0 [Note] Event Scheduler: Loaded 0 events
mysql_1         | 2020-01-31T14:48:15.496515Z 0 [Note] mysqld: ready for connections.
mysql_1         | Version: '5.7.27'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
uwsgi_1         | /usr/bin/env: ‘bash\r’: No such file or directory
celerybeat_1    | /usr/bin/env: ‘bash\r’: No such file or directory
nginx_1         | standard_init_linux.go:211: exec user process caused "no such file or directory"
django-defectdojo_celeryworker_1 exited with code 127
django-defectdojo_celerybeat_1 exited with code 127
django-defectdojo_uwsgi_1 exited with code 127
django-defectdojo_initializer_1 exited with code 127
django-defectdojo_nginx_1 exited with code 1
rabbitmq_1      | 2020-01-31 14:48:24.410 [info] <0.8.0> Feature flags: list of feature flags found:
rabbitmq_1      | 2020-01-31 14:48:24.411 [info] <0.8.0> Feature flags: feature flag states written to disk: yes
rabbitmq_1      | 2020-01-31 14:48:24.620 [info] <0.264.0>
rabbitmq_1      |  Starting RabbitMQ 3.7.17 on Erlang 22.0.7
rabbitmq_1      |  Copyright (C) 2007-2019 Pivotal Software, Inc.
rabbitmq_1      |  Licensed under the MPL.  See https://www.rabbitmq.com/
rabbitmq_1      |
rabbitmq_1      |   ##  ##
rabbitmq_1      |   ##  ##      RabbitMQ 3.7.17. Copyright (C) 2007-2019 Pivotal Software, Inc.
rabbitmq_1      |   ##########  Licensed under the MPL.  See https://www.rabbitmq.com/
rabbitmq_1      |   ######  ##
rabbitmq_1      |   ##########  Logs: <stdout>
rabbitmq_1      |
rabbitmq_1      |               Starting broker...
rabbitmq_1      | 2020-01-31 14:48:24.622 [info] <0.264.0>
rabbitmq_1      |  node           : rabbit@464cea08f827
rabbitmq_1      |  home dir       : /var/lib/rabbitmq
rabbitmq_1      |  config file(s) : /etc/rabbitmq/rabbitmq.conf
rabbitmq_1      |  cookie hash    : c8G1QDB/5I6aW7tIdIzwmw==
rabbitmq_1      |  log(s)         : <stdout>
rabbitmq_1      |  database dir   : /var/lib/rabbitmq/mnesia/rabbit@464cea08f827
rabbitmq_1      | 2020-01-31 14:48:24.642 [info] <0.264.0> Running boot step pre_boot defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.642 [info] <0.264.0> Running boot step rabbit_core_metrics defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.647 [info] <0.264.0> Running boot step rabbit_alarm defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.665 [info] <0.274.0> Memory high watermark set to 792 MiB (830652416 bytes) of 1980 MiB (2076631040 bytes) total
rabbitmq_1      | 2020-01-31 14:48:24.687 [info] <0.303.0> Enabling free disk space monitoring
rabbitmq_1      | 2020-01-31 14:48:24.687 [info] <0.303.0> Disk free limit set to 50MB
rabbitmq_1      | 2020-01-31 14:48:24.698 [info] <0.264.0> Running boot step code_server_cache defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.698 [info] <0.264.0> Running boot step file_handle_cache defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.700 [info] <0.317.0> Limiting to approx 1048476 file handles (943626 sockets)
rabbitmq_1      | 2020-01-31 14:48:24.700 [info] <0.318.0> FHC read buffering:  OFF
rabbitmq_1      | 2020-01-31 14:48:24.701 [info] <0.318.0> FHC write buffering: ON
rabbitmq_1      | 2020-01-31 14:48:24.702 [info] <0.264.0> Running boot step worker_pool defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.703 [info] <0.267.0> Will use 2 processes for default worker pool
rabbitmq_1      | 2020-01-31 14:48:24.703 [info] <0.267.0> Starting worker pool 'worker_pool' with 2 processes in it
rabbitmq_1      | 2020-01-31 14:48:24.704 [info] <0.264.0> Running boot step database defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.712 [info] <0.264.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
rabbitmq_1      | 2020-01-31 14:48:24.783 [info] <0.264.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
rabbitmq_1      | 2020-01-31 14:48:24.784 [info] <0.264.0> Peer discovery backend rabbit_peer_discovery_classic_config does not support registration, skipping registration.
rabbitmq_1      | 2020-01-31 14:48:24.784 [info] <0.264.0> Running boot step database_sync defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.786 [info] <0.264.0> Running boot step feature_flags defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.786 [info] <0.264.0> Running boot step codec_correctness_check defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.787 [info] <0.264.0> Running boot step external_infrastructure defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.787 [info] <0.264.0> Running boot step rabbit_registry defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.787 [info] <0.264.0> Running boot step rabbit_auth_mechanism_cr_demo defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.790 [info] <0.264.0> Running boot step rabbit_queue_location_random defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.791 [info] <0.264.0> Running boot step rabbit_event defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.792 [info] <0.264.0> Running boot step rabbit_auth_mechanism_amqplain defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.793 [info] <0.264.0> Running boot step rabbit_auth_mechanism_plain defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.794 [info] <0.264.0> Running boot step rabbit_exchange_type_direct defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.795 [info] <0.264.0> Running boot step rabbit_exchange_type_fanout defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.795 [info] <0.264.0> Running boot step rabbit_exchange_type_headers defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.796 [info] <0.264.0> Running boot step rabbit_exchange_type_topic defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.797 [info] <0.264.0> Running boot step rabbit_mirror_queue_mode_all defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.798 [info] <0.264.0> Running boot step rabbit_mirror_queue_mode_exactly defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.798 [info] <0.264.0> Running boot step rabbit_mirror_queue_mode_nodes defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.799 [info] <0.264.0> Running boot step rabbit_priority_queue defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.799 [info] <0.264.0> Priority queues enabled, real BQ is rabbit_variable_queue
rabbitmq_1      | 2020-01-31 14:48:24.799 [info] <0.264.0> Running boot step rabbit_queue_location_client_local defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.799 [info] <0.264.0> Running boot step rabbit_queue_location_min_masters defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.799 [info] <0.264.0> Running boot step kernel_ready defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.799 [info] <0.264.0> Running boot step rabbit_sysmon_minder defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.800 [info] <0.264.0> Running boot step rabbit_epmd_monitor defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.807 [info] <0.264.0> Running boot step guid_generator defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.823 [info] <0.264.0> Running boot step rabbit_node_monitor defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.824 [info] <0.343.0> Starting rabbit_node_monitor
rabbitmq_1      | 2020-01-31 14:48:24.824 [info] <0.264.0> Running boot step delegate_sup defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.827 [info] <0.264.0> Running boot step rabbit_memory_monitor defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.830 [info] <0.264.0> Running boot step core_initialized defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.830 [info] <0.264.0> Running boot step upgrade_queues defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.867 [info] <0.264.0> Running boot step rabbit_connection_tracking defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.868 [info] <0.264.0> Running boot step rabbit_connection_tracking_handler defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.868 [info] <0.264.0> Running boot step rabbit_exchange_parameters defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.868 [info] <0.264.0> Running boot step rabbit_mirror_queue_misc defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.872 [info] <0.264.0> Running boot step rabbit_policies defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.874 [info] <0.264.0> Running boot step rabbit_policy defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.875 [info] <0.264.0> Running boot step rabbit_queue_location_validator defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.875 [info] <0.264.0> Running boot step rabbit_vhost_limit defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.875 [info] <0.264.0> Running boot step recovery defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.882 [info] <0.372.0> Making sure data directory '/var/lib/rabbitmq/mnesia/rabbit@464cea08f827/msg_stores/vhosts/628WB79CIFDYO9LJI6DKMI09L' for vhost '/' exists
rabbitmq_1      | 2020-01-31 14:48:24.904 [info] <0.372.0> Starting message stores for vhost '/'
rabbitmq_1      | 2020-01-31 14:48:24.905 [info] <0.376.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_transient": using rabbit_msg_store_ets_index to provide index
rabbitmq_1      | 2020-01-31 14:48:24.916 [info] <0.372.0> Started message store of type transient for vhost '/'
rabbitmq_1      | 2020-01-31 14:48:24.919 [info] <0.379.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_persistent": using rabbit_msg_store_ets_index to provide index
rabbitmq_1      | 2020-01-31 14:48:24.923 [warning] <0.379.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_persistent": rebuilding indices from scratch
rabbitmq_1      | 2020-01-31 14:48:24.927 [info] <0.372.0> Started message store of type persistent for vhost '/'
rabbitmq_1      | 2020-01-31 14:48:24.937 [info] <0.264.0> Running boot step empty_db_check defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.937 [info] <0.264.0> Running boot step rabbit_looking_glass defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.937 [info] <0.264.0> Running boot step rabbit_core_metrics_gc defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.938 [info] <0.264.0> Running boot step background_gc defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.941 [info] <0.264.0> Running boot step connection_tracking defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.942 [info] <0.264.0> Setting up a table for connection tracking on this node: tracked_connection_on_node_rabbit@464cea08f827
rabbitmq_1      | 2020-01-31 14:48:24.943 [info] <0.264.0> Setting up a table for per-vhost connection counting on this node: tracked_connection_per_vhost_on_node_rabbit@464cea08f827
rabbitmq_1      | 2020-01-31 14:48:24.945 [info] <0.264.0> Running boot step routing_ready defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.945 [info] <0.264.0> Running boot step pre_flight defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.945 [info] <0.264.0> Running boot step notify_cluster defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.945 [info] <0.264.0> Running boot step networking defined by app rabbit
rabbitmq_1      | 2020-01-31 14:48:24.954 [warning] <0.402.0> Setting Ranch options together with socket options is deprecated. Please use the new map syntax that allows specifying socket options separately from other options.
rabbitmq_1      | 2020-01-31 14:48:24.956 [info] <0.416.0> started TCP listener on [::]:5672
rabbitmq_1      | 2020-01-31 14:48:24.957 [info] <0.264.0> Running boot step direct_client defined by app rabbit
rabbitmq_1      |  completed with 0 plugins.
rabbitmq_1      | 2020-01-31 14:48:25.208 [info] <0.8.0> Server startup complete; 0 plugins started.
```

Any help?
