### ISSUE TITLE
Kiuwan scan import issues

### ISSUE THREAD

**Issue by jsalado** [DefectDojo/django-DefectDojo#1174]
**Bug description**
1. Findings are imported with Type = Dynamic. Kiuwan is a static analyzer, so I guess they shuld be Static.
2. If there is a defect in the imported CSV file with empty CWE, the import results in an Internal Server Error (500). 

**Steps to reproduce**
1. Open the details of an imported finding and see that the Type is Dynamic
2. Try to import the attached sample CSV export from Kiuwan. It will fail. Edit the file and complete the CWE missing (4th column). Try to import again. It will succeed.
 - DefectDojo version: 045ad95: Merge pull request #1163 from devEricA/dev [2019-05-23 14:16:50 -0500]

** Expected behavior **
Not all Kiuwan vulnerabilities have a mapped CWE. If a CWE is mandatory for DefectsDojo, I suggest the instead of failing, skip the records without CWE.

**Sample scan files** (optional)
2019-05-22_Kiuwan_VulnerabilitiesTable_rfc_4180.zip
[2019-05-22_Kiuwan_VulnerabilitiesTable_rfc_4180.zip](https://github.com/DefectDojo/django-DefectDojo/files/3216733/2019-05-22_Kiuwan_VulnerabilitiesTable_rfc_4180.zip)

**Comment by dr3dd589** [comment]
@jsalado I am able to reproduce this. going to fix it now.

**Comment by jsalado** [comment]
@dr3dd589 That's great, thank you!

**Comment by dr3dd589** [comment]
@jsalado Can you make changes which I have made in this PR #1175 and check if it fixes it or not?
