### ISSUE TITLE
Jquery missing on some page

### ISSUE THREAD

**Issue by 1Jesper1** [DefectDojo/django-DefectDojo#1180]
**Bug description**
Jquery is missing on some pages, like "/add_findings". Notifications dropdown gives error: "Cannot read property 'trim' of undefined"

**Steps to reproduce**
1. Go to '"/add_findings/{number}
2. Click on notifications dropdown.
3. Notification dropdown won't load.

**Environment information**
 - Operating System: [Ubuntu 18.04]
 - DefectDojo version: Dev

**Comment by propersam** [comment]
I wanted to fix this issue. but I can't seem to repeat it from my end.

I can't find any endpoint called /add_findings/{number} on my instance.

can you point out any other page you have this issue.

**Comment by 1Jesper1** [comment]
@propersam  https://github.com/DefectDojo/django-DefectDojo/blob/e5a884296b3fefa48a48602b58f9884b762b2f6f/dojo/templates/dojo/add_findings.html
Page doesn't have <script type="application/javascript" src="{% static "chosen/chosen.jquery.min.js" %}"></script> like https://github.com/DefectDojo/django-DefectDojo/blob/e5a884296b3fefa48a48602b58f9884b762b2f6f/dojo/templates/dojo/add_related.html

**Comment by propersam** [comment]
Oh.

I will like to understand clearly. Are you asking that all jquery include files be added equally to every page.

**Comment by 1Jesper1** [comment]
Yes, some pages are missing the Jquery script and throw errors because of that.

**Comment by propersam** [comment]
alright, will do just that..

**Comment by propersam** [comment]
@aaronweaver what do u say about this.

Are some of the jquery files ignored for special reasons ?

**Comment by propersam** [comment]
with the upgrade to python3 and other upgraded packages.. I think this should now be stable...

any jquery not added on a page now ..should be because it's not needed on that page.

@Maffooch what do you say?

**Comment by Maffooch** [comment]
@propersam I don't know very much about jQuery. I can guess that upgrading to python3 and other packages has no relation to jQuery. I would say do whatever it takes to resolve the bug. In this case, make sure 'Notifications dropdown gives error: "Cannot read property 'trim' of undefined"' does not happen.

**Comment by aaronweaver** [comment]
It was probably not on every template, no reason it's can't be on every page.

**Comment by propersam** [comment]
my problem now is  I cant seem to repeat the error y'all talking about but on my local instance and heroku instance.

I should have fixed this a long time ago...

Is there any clear nd direct steps to trigger this error on screen while clicking through the app??
