### ISSUE TITLE
Import Scan for Immuniweb

### ISSUE THREAD

**Issue by aaronweaver** [DefectDojo/django-DefectDojo#1185]
Create an importer for Immuniweb. XML will be provided shortly.

**Comment by aaronweaver** [comment]
[ImmuniWeb-XML-6507875.xml.zip](https://github.com/DefectDojo/django-DefectDojo/files/3232423/ImmuniWeb-XML-6507875.xml.zip)

**Comment by propersam** [comment]
You can assign this to me.

**Comment by propersam** [comment]
This can now be added to In progress

**Comment by propersam** [comment]
wow, finally done with this. awaiting review.
