### ISSUE TITLE
Import Scan for wpscan

### ISSUE THREAD

**Issue by aaronweaver** [DefectDojo/django-DefectDojo#1186]
Create an importer for wpscan.

**Comment by dr3dd589** [comment]
hello, @aaronweaver  assign this to me. Can you please provide sample scan for this scanner?

**Comment by aaronweaver** [comment]
@dr3dd589 See attached, also please submit this file as a sample to the sample repo. Thx! Change the name to wordpress.json.

Output for wordpress -f json
[wordpress.json.txt](https://github.com/DefectDojo/django-DefectDojo/files/3351957/wordpress.json.txt)

**Comment by dr3dd589** [comment]
@Maffooch it's done you can close this one.
