### ISSUE TITLE
Import Scan for sslscan 

### ISSUE THREAD

**Issue by NRGLine4Sec** [DefectDojo/django-DefectDojo#1187]
Create an importer for [sslscan](https://github.com/rbsec/sslscan) with the XML output.

**Comment by NRGLine4Sec** [comment]
This is a repport scan by sslscan :
[repport_scan_sslscan_https.xml.zip](https://github.com/DefectDojo/django-DefectDojo/files/3251200/repport_scan_sslscan_https.xml.zip)

**Comment by propersam** [comment]
what does sslscan contain...

I don't seem to find any information about *Vulnerability Finding*

**Comment by propersam** [comment]
@NRGLine4Sec  
can I say sslscan result only contains endpoints found on a host and not vulnerabilities?

**Comment by NRGLine4Sec** [comment]
I understand what you say, with sslscan report, a vulnerability finding correpond to `vulnerable="1"/>` or if `<cipher status=""` is not equal to strong or acceptable. Other data should be noted as information about endpoints.

**Comment by dr3dd589** [comment]
@propersam are you working on this?

**Comment by propersam** [comment]
nope not now...
I am currently working on the scanner unittest task

**Comment by aaronweaver** [comment]
@dr3dd589 Did you take this one yet?

**Comment by dr3dd589** [comment]
no, currently working on wpscan parser now.

**Comment by himani-dangwal** [comment]
Hi i tried to import the sslscan report which is similar to the one attached previous comments "repport_scan_sslscan_https.xml.zip" but i am unable to get data on defectdojo for that

**Comment by steeve85** [comment]
This is because only weak ciphers are imported.
If you look at your XML file, most of the cipher suite probably have a `strength` of `acceptable` or `strong` and these are not imported. Lower strength and Heartbleed vulnerabilities will be imported.

**Comment by himani-dangwal** [comment]
> This is because only weak ciphers are imported.
> If you look at your XML file, most of the cipher suite probably have a `strength` of `acceptable` or `strong` and these are not imported. Lower strength and Heartbleed vulnerabilities will be imported.

Thanks for the info.. But now it seems there is issue in my sslscan report import.. I validated my report that is being generated which is correct. But when i do the import i get the following error
<img width="591" alt="sslscan issue" src="https://user-images.githubusercontent.com/53521513/81532156-8fbfd700-9381-11ea-805f-7091314b35cf.PNG">

**Comment by steeve85** [comment]
@himani-dangwal Please open a new issue with as much details as possible: screenshot, logs, sanitized sslscan report

**Comment by himani-dangwal** [comment]
> @himani-dangwal Please open a new issue with as much details as possible: screenshot, logs, sanitized sslscan report

Hi @steeve85  as suggested I have raised a new ticket  for sslscan with all possible data https://github.com/DefectDojo/django-DefectDojo/issues/2428
