### ISSUE TITLE
Import Scan for Golismero

### ISSUE THREAD

**Issue by NRGLine4Sec** [DefectDojo/django-DefectDojo#1188]
Create an importer for [Golismero](https://github.com/golismero/golismero) with the XML output.

**Comment by dr3dd589** [comment]
hello, @NRGLine4Sec Can you provide a sample report for this?

**Comment by aaronweaver** [comment]
@NRGLine4Sec Can you provide a sample file, we have the bandwidth to do it now. Thx!

**Comment by NRGLine4Sec** [comment]
Sorry, I can't because of sensitive information inside the report. But I have check the XML output and I don’t think that we could use the result of the XML output into DefecDojo, so maybe we could close this issue or someone else could install Golsimero and check the XML output too.
