### ISSUE TITLE
Acunetix parser

### ISSUE THREAD

**Issue by 40R40L** [DefectDojo/django-DefectDojo#1190]
Hi,

i noticed that an Acunetix parser was integrated in this version but it does not work ( for me ) 
i get a Server Error (500) when i try to upload an acunetix scan report . 

i used to use this parser in the previous version of DefecDojo and its working very fine for me
https://github.com/code4innerpeace/DefectDojoAcunetixParsers

**Comment by devGregA** [comment]
@40R40L we are unable to investigate without a sample scan.

**Comment by zfirered** [comment]
hello i got the sample for this one
please re open it
