### ISSUE TITLE
K8 Deployment with Helm 2.14.0 results to a error

### ISSUE THREAD

**Issue by marquezc1** [DefectDojo/django-DefectDojo#1192]
**Bug description**
Error: validation failed: error validating "": error validating data: unknown object type "nil" in ConfigMap.data.DD_CELERY_LOG_LEVEL

It appears that prior to 2.14, Helm silently accepted schema validation errors, but as of 2.14, all manifests are validated, including ones that were previously accepted. 
https://github.com/helm/helm/issues/5750

**Steps to reproduce**
1. Follow KUBERNETES.md instructions for production deployment
2. Perform helm install
3. See error

**Expected behavior**
Deployment does not respond with an error and helm successfully deploys defectdojo in defined namespace.

**Deployment method** *(select with an `X`)*
- [X] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 18.04 server
 - DefectDojo version: 2a8e2ef5: Merge pull request #1109 from wurstbrot/patch-1 [2019-05-06 12:13:47 -0400]
- K8 version: kubeadm version: &version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:20:34Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by marquezc1** [comment]
For the time being, I downgraded helm to version 2.13.1 and the deployment worked.

**Comment by aaronweaver** [comment]
I wonder if there is a helm linter we could add to our travis tests?

**Comment by marquezc1** [comment]
Hi Aaron, I tired performing helm lint ./helm/defectdojo/ to try this helm function out and got a Lint OK with no failures but if helm lint ./helm/defectdojo/ --strict is used then a different template issue gets reported:

[ERROR] templates/: render error in "defectdojo/charts/mysql/templates/tests/test.yaml": template: defectdojo/charts/mysql/templates/_helpers.tpl:15:14: executing "mysql.fullname" at <.Values.fullnameOver...>: map has no entry for key "fullnameOverride"

I do agree that this should warrant some travis test cases like performing a --dry-run with helm against the template in order to review the format and expected output values.

When injecting strings from the .Values object into the template, we ought to quote these strings. We can do that by calling the quote function in the template directive as so: 

{{ quote .Values.celery.logLevel }}
{{ .Values.celery.logLevel | quote }}

I believe by including this quote function within the templates that this issue can potentially be resolved and met Helm/Go best practices. I currently don't have the cycles to validate or apply these changes but do hope to contribute my first PR to this great project in the future when time permits or unless someone else can work on these template updates.
