### ISSUE TITLE
Is there any plan that defectdojo would support MSSQL server in future.

### ISSUE THREAD

**Issue by cymxiao** [DefectDojo/django-DefectDojo#1196]
Dear Sir,

Is there any plan that defectdojo would support  Microsoft SQL server in  future?
If not, is it possible to connect to MSSQL server container or a real MSSQL server if I make a second development. I am not sure If defectdojo can connect to mssql with regard to technique.

btw,  is there a guide document from your team to make defectdojo to support another db?

it would be great appreciate if i get your feedback. 

Thanks in advance.

**Comment by aaronweaver** [comment]
@cymxiao We only support mysql / postgres. DefectDojo uses Django and you can check out more info on that [here](https://docs.djangoproject.com/en/2.2/ref/databases/).
