### ISSUE TITLE
Integration with Agilecraft

### ISSUE THREAD

**Issue by dougmcdorman** [DefectDojo/django-DefectDojo#1197]
**Is your feature request related to a problem? Please describe**
Ability to synchronize issues to agilecraft.com

**Describe the solution you'd like**
Two way communication with Agilecraft similar to the Jira integration.

**Describe alternatives you've considered**
Manual creation of issues in Agilecraft.

**Additional context**
Agilecraft is able to synchronize with Jira and is now owned by Altasian (also owns Jira), so the integration might be fairly straightforward.
So the ability to push issues into Agilecraft and have them created there. Then if updated in agilecraft the updated would be reflected in Defectdojo.

**Comment by aaronweaver** [comment]
@dougmcdorman would it work then to push DefectDojo --> Jira --> AgileCraft?

**Comment by devGregA** [comment]
Hi All, I'm going to archive this for now. AgileCraft has since been acquired by Atlassian, there maybe an easy way to integrate JIRA issues with what they're now calling JIRA Align, but I don't think we can make this happen in the near future.
