### ISSUE TITLE
Arachni results parsed but no metrics overview

### ISSUE THREAD

**Issue by wheelq** [DefectDojo/django-DefectDojo#1200]
**Bug description**
After importing arachni scan results, DD displays table with findings and severity for each finding. But no data appears in Metrics or Overview.

**Screenshots** 
Import results:
![image](https://user-images.githubusercontent.com/1497172/58710968-69459d80-83b5-11e9-8cdc-acb73cd3c43e.png)

Findings count:
![image](https://user-images.githubusercontent.com/1497172/58710934-59c65480-83b5-11e9-8322-2745685e15f5.png)

Overview
![image](https://user-images.githubusercontent.com/1497172/58710898-4adfa200-83b5-11e9-822b-79cfe0482fee.png)

**Comment by dougmcdorman** [comment]
I don't think findings show up on the metrics unless they are marked as verified. I presume this is so that false positives don't show up on metrics. 
When importing you can choose the default to import them as not verified, or have them come in as verified.

**Comment by aaronweaver** [comment]
Yes, that's correct, active + verified.
