### ISSUE TITLE
Alerts notifications functional improvements

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1211]
**Is your feature request related to a problem? Please describe**
As the email is currently impaired (see #835), the alerts notification icon on the top right hand corner is along with Slack (which needs improvements too #1158) a critical indicator of what's happening or need to happen.

Today, there is no way to:
* clear all alerts directly from the notification pop-up
* clear a single alert from the notification pop-up
* clear all alerts even when navigating into the "See all alerts" page. If you have 100s of alerts, you need to go page by page and delete.

**Describe the solution you'd like**
* The alert notification pop-up should handle clearing alerts directly, one or all (and eventually many)
* For specific alerts when "requesting a review", I would think an extra visual clue would be a nice addition.

**Comment by devGregA** [comment]
@devEricA please add a clear all alerts options under view all with a confirmation javascript popup. Please also add an 'x' to each entry to remove an alert

**Comment by devGregA** [comment]
![Screen Shot 2019-06-12 at 4 18 44 PM](https://user-images.githubusercontent.com/4741312/59387088-e6fe9700-8d2d-11e9-8886-8920a245a170.png)
