### ISSUE TITLE
Importer Whitesource

### ISSUE THREAD

**Issue by aaronweaver** [DefectDojo/django-DefectDojo#1212]
Create an importer for [Whitesource](https://www.whitesourcesoftware.com/). Sample file coming shortly.

**Comment by madchap** [comment]
There you go. This is a json export from the "vulnerability report" from whitesource on a arbitrary project.


[okhttp-vulnerability-report.json.zip](https://github.com/DefectDojo/django-DefectDojo/files/3266101/okhttp-vulnerability-report.json.zip)

**Comment by dr3dd589** [comment]
hello, @Maffooch assign this to me.
