### ISSUE TITLE
is it possible to connect to an external MYSQL server for defectdojo?

### ISSUE THREAD

**Issue by cymxiao** [DefectDojo/django-DefectDojo#1217]
I am struggling with the config on the docker-compose yml file to connect it to a remotely hosted mysql database. The reason being, if I want to install Dojo in Prod, I would like the data to persist even when the docker container isn't available.
Is defectdojo possible to connect to an external MySQL server?  your feedback would be great appreciate. 

Thanks.

**Comment by aaronweaver** [comment]
Hi @cymxiao - It's all the configuration for DefectDojo is through environment variables and those can be seen [here](https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/settings/settings.dist.py), to set an external database export the variable: DD_DATABASE_HOST=yourexternalmysqlhost.
