### ISSUE TITLE
Making Accepting Risks easier to access for Findings

### ISSUE THREAD

**Issue by nwse-strm-suer** [DefectDojo/django-DefectDojo#1219]
**Is your feature request related to a problem? Please describe**
Vulnerability manager normally don't patch software by themself. If a finding is reported to the responsible person/team, a product owner may accept this risk of running vulnerable software. At the moment DefectDojo does not offer any solution for "risk acceptance". For a documentation and as a kind of audit trail, this feature would be helpful. The "false positive" status does not cover this correctly and other stati would generate new findings of the same vulnerability.

**Describe the solution you'd like**
An additional findings status like "accepted risk" or similar to display the correct status. This would express a not "active" status and offer a filter in the findings list. Also a state chart for the different stati and possible transitions would be helpful.

**Describe alternatives you've considered**
The current alternative is to add a note and maybe set the status to false positive to remove it from active findings. This is not really practical and does not reflect the reality.

**Comment by aaronweaver** [comment]
Hi @nwse-strm-suer, did you take a look at test, then scroll down to 'Risk Acceptance'? 

![image](https://user-images.githubusercontent.com/220838/59036390-2fedb180-883d-11e9-850e-8d0481bdd0f8.png)

**Comment by devGregA** [comment]
We should probably add risk acceptance off the finding menu bar, rather than just be available via the engagement interface.

**Comment by devGregA** [comment]
@devEricA Please add accepting findings to the dropdown finding menu. Adding a screenshot momentarily.

**Comment by devGregA** [comment]
![Screen Shot 2019-06-06 at 3 02 43 PM](https://user-images.githubusercontent.com/4741312/59062790-4bbc7c00-886c-11e9-9474-b588dc2dd477.png)
![Screen Shot 2019-06-06 at 3 03 01 PM](https://user-images.githubusercontent.com/4741312/59062791-4bbc7c00-886c-11e9-8fa5-a4515d3ea270.png)

**Comment by devGregA** [comment]
Below "Close Finding" please.

**Comment by valentijnscholten** [comment]
Where is the functionality currently located? I remember seeing it and testing it but cannot find it anymore anywhere currently on the dev branch.

**Comment by madchap** [comment]
> Where is the functionality currently located? I remember seeing it and testing it but cannot find it anymore anywhere currently on the dev branch.

You need to go back to the engagement screen. Then you will see a section dedicated to it called "Risk Acceptance", where you can click the "+" sign. Then, only "Active" and "Verified" findings will show in the select box (which also bears an inconsistency, as if you then want to add further acceptance, they all show -- probably warrants an issue.)

**Comment by valentijnscholten** [comment]
Ah thank you, it was below the long list of tests :)
Is there a reason why the risk acceptance is handled as a bolt on proces? I would rather see that it's just a status of a finding and the notes and acceptor etc are visible when viewing the finding. And make it available in as a bulk edit (that would work across engagements/products).

**Comment by nwse-strm-suer** [comment]
> Hi @nwse-strm-suer, did you take a look at test, then scroll down to 'Risk Acceptance'?

thank you all for discussing this! I did not find it (not in our preview instance yet). But it seems that the visibility could be improved.

From my workflow I would have expected it in the Status section as a state or as a drop down menu item like @devEricA suggested. In the latter with additional information, a timespan the risk was accepted were possible, making the finding active again after that period. I don't want to make this bigger as it is ;), consider the scenario that a product owner accepts a risk until the next planned sprint or any migration is finished.

An overview of accepted risks per Engagement or a metric for reporting would be cool., too.
