### ISSUE TITLE
Bulk edit of findings do not work if findings mandatory fields are not satisfied 

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1239]
**Bug description**
And this definitely does not sound like a bad thing, and working by design.

However, that "impact" field being mandatory *after* the initial data ingestion, whereas many importers do not put anything in it on ingestion is making it just a bad experience and the UI does not even reflect what the problem might be.

Would we eventually want to make "impact" a non-mandatory field? Or put the burden on each parser to put at least some string in it? Should consistency with that field (and surely others) be imposed straight from the import function?

**Steps to reproduce**
1. Select findings for bulk editing, which have an empty "impact" field
2. Try to change their status, say "false positive"
3. Witness nothing changes, and no error message either.

**Expected behavior**
- At least some error message, and not a "successful" message...
- or fix the root

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Comment by devEricA** [comment]
Hey @madchap what scanner did you use to produce this? The reason I ask is because I tried to replicate this bug using the cobalt parser, but bulk edit worked as intended, even though the cobalt's findings have nothing in their impact field.
