### ISSUE TITLE
Imported findings from Kiuwan don't show in metrics dashboards

### ISSUE THREAD

**Issue by jsalado** [DefectDojo/django-DefectDojo#1242]
**Bug description**
After importing findings for a product from a Kiuwan scan CSV file, the list of findings appear in the findings list for the product and in the correspondent engagement (the Kiuwan scan the gets created automatically with the import).
However, in the dashboard those new findings are not counted and if you go to the product metrics screen they don't appear there either.
I have activated them after the import but still they don't show in any counter/dashboard mentioned above

**Steps to reproduce**
1. Select a product
2. Import findings from a Kiuwan CSV vulnerabilities file. You can  use any sample available in the project django-DefectDojo/dojo/unittests/scans/kiuwan_sample/ or use the one below
3. List all findings, see the findings
4. Activate all or some findings in bulk
5. Go to the metrics screen for the product. See that the number of findings are not updated, but if you click on the link for Open findings it'll take you to the list of findings including the ones not shown in the counter.
6. The same happens if you go to the global dashboard, the newly imported findings are not there
See screenshots

**Expected behavior**
All counters in all dashboards refreshed taking into account

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo version: [use `git show -s --format="%h: %s [%ci]"`]
1.5.4

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.
[2019-05-22_Kiuwan_VulnerabilitiesTable_rfc_4180.zip](https://github.com/DefectDojo/django-DefectDojo/files/3276869/2019-05-22_Kiuwan_VulnerabilitiesTable_rfc_4180.zip)

**Screenshots** (optional)
![findings-list](https://user-images.githubusercontent.com/12932925/59280025-3a58e280-8c65-11e9-9235-32ca6a220519.png)
![product-overview](https://user-images.githubusercontent.com/12932925/59279828-eb12b200-8c64-11e9-830a-7cbf2a4d88a3.png)
![product-metrics](https://user-images.githubusercontent.com/12932925/59279842-efd76600-8c64-11e9-8f73-b509a02447b8.png)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

**Comment by aaronweaver** [comment]
@jsalado are the findings also set to verified?

**Comment by jsalado** [comment]
@aaronweaver I see I've set the status as Active AND Verified and now the dashboards show the information.
I see now that the import screen allows you to check both statuses, so they can automatically be created with both set. This obvious ly will depend on the process every user wants to implement and the level of confidence in Kiuwan results ;-)

Thanks. All clear now, I'm closing the issue.

**Comment by aaronweaver** [comment]
@jsalado I think I'll add some text on the screen to indicate that it's only showing active and verified.
