### ISSUE TITLE
Execute an action when finding status changes

### ISSUE THREAD

**Issue by clazba** [DefectDojo/django-DefectDojo#1244]
**Is your feature request related to a problem? Please describe**
I'd like the ability to automatically update configuration/suppression files for security scanning tools based on the status of a finding. For example, if a finding is closed as "false positive" in DD I'd like the ability to update the configuration file for the tool accordingly 

**Describe the solution you'd like**
As a developer I'd like to build a way for DD to trigger and action (e.g. script execution) following a change in a finding's status.

**Describe alternatives you've considered**
I've considered a running a cron job to monitor database changes but feels messy - also the action trigger should be 'pushed' rather than 'pulled'

**Additional context**
@aaronweaver @devGregA This feature requires some work. Before considering a PR, do you see it as a valid use case for DD's community? Would be good to have this merged into master eventually.

**Comment by aaronweaver** [comment]
@clazba I think that's a really interesting use case and would be useful for some users. I wonder though if we added webhooks for events with a webhook endpoint that an external service / endpoint could decide how to supress the findings in the various scanners. That feature would be very useful (webhooks) to the community at large and address your specific use case. We could also consider add a microservice repo in the DD org for useful integrations such as this.

**Comment by clazba** [comment]
@aaronweaver I think it's a super idea and a more robust way to provide 3rd party integration. Is this something the DD core dev team has already started looking into? Else happy to discuss it with some colleagues to see how much work this would be for us to implement.

**Comment by aaronweaver** [comment]
@clazba Feel free to work on it, I can convert this to an issue and assign you as the owner. At the moment we are wrapping up the Python3 and Django 2.2 migration.
