### ISSUE TITLE
How to back up the DefectDojo database to upgrade to the new release ?

### ISSUE THREAD

**Issue by NRGLine4Sec** [DefectDojo/django-DefectDojo#1250]
How to back up the DefectDojo database to upgrade to the new release ?
In the [doc](https://defectdojo.readthedocs.io/en/latest/upgrading.html), You tell us to 

> Back up your database first, ideally take the backup from production and test the upgrade on a staging server.

but you don't explain how to back up the database and how to re-import the database to the new version of DefectDojo.

In the step 2 :

> Edit the settings.py file which can be found in django-DefectDojo/dojo/settings/settings.py

But the file `django-DefectDojo/dojo/settings/settings.py` don't exist, there is only the file named `settings.dist.py`. It is this file we have to edit ?

**Comment by devGregA** [comment]
`python manage.py dumpdata > backup.json` which may not be ideal if you're re-running the initializer on a fresh install. You'll also need to pull down the images from the server if you're using finding images. Some variation of dumpdata + pulling the images is what I'd recommend.

**Comment by NRGLine4Sec** [comment]
Ok thanks !

**Comment by madchap** [comment]
That's what I do to export/import data also when upgrading.

Currently broken though, see #1336 .

**Comment by NRGLine4Sec** [comment]
So, how do you upgrading and keep your database ?

**Comment by madchap** [comment]
> So, how do you upgrading and keep your database ?

Kinda stuck today until it is fixed :-) 

You can still `mysqldump` the DB too, so you could reload it on an instance of the same version I guess.

**Comment by NRGLine4Sec** [comment]
Ok, so I will be patient..
Maybe one day there will be a button to make an upgrate much easier like i suggest in #1286 :)

**Comment by hujarl** [comment]
I am very interested in the upgrade process as well

**Comment by adon90** [comment]
> > So, how do you upgrading and keep your database ?
> 
> Kinda stuck today until it is fixed :-)
> 
> You can still `mysqldump` the DB too, so you could reload it on an instance of the same version I guess.

I am trying:

![image](https://user-images.githubusercontent.com/7115563/104730041-a3ee7c00-5739-11eb-9782-4e34d992152b.png)

Do know how can I do that?

**Comment by joebasirico** [comment]
I'm not sure if you are setup the same as me, but mysql user is defectdojo, not root.
