### ISSUE TITLE
Complete ImportScanner Unit Test Requirements

### ISSUE THREAD

**Issue by Maffooch** [DefectDojo/django-DefectDojo#1254]
**Scanner Name**
[Located in python3_dev](https://github.com/DefectDojo/django-DefectDojo/blob/python3_dev/tests/Import_scanner_unit_test.py)

**Sample File**
[To-Do](https://docs.google.com/document/d/14ncrWjAPYQvsYOPg5nMkVW1CO9IJwFhaMRd2w9WpxJI/edit#)

**Comment by propersam** [comment]
Unit test is my focus....

i'm working on this now

**Comment by propersam** [comment]
it's probably gonna last all through next week... but i should be done before GSOC evaluation week...

**Comment by propersam** [comment]
I have made a PR to update sample_test_file repo..

**Comment by devGregA** [comment]
@Maffooch am I good to close this?

**Comment by Maffooch** [comment]
Don't think he is done with it yet. @propersam What is your status on this one?

**Comment by propersam** [comment]
No.. Don't close this yet...  We are still on it...
