### ISSUE TITLE
Unable to upload Images to reported vulnerability - Server Error 500

### ISSUE THREAD

**Issue by parag85** [DefectDojo/django-DefectDojo#1267]
**Bug description**
Unable to upload Images to reported vulnerability - Server Error 500 page received

**Steps to reproduce**
1. Go to Engagement
2. Click on three dots of any logged vulnerability
3. Scroll down to "Manage Images" and click on it
4. Upload any image from See error

**Expected behavior**

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 18.04
 - DefectDojo version: Latest docker file

**Screenshots** (optional)
![image](https://user-images.githubusercontent.com/8840359/59556025-b2af0300-8fd9-11e9-81e5-dc49aef486c2.png)

**Console logs** (optional)
uwsgi_1         | [pid: 1|app: 0|req: 2992/2992] 115.99.1.112 () {44 vars in 837                                                                                         bytes} [Sat Jun 15 20:21:10 2019] GET /alerts/count => generated 13 bytes in 13                                                                                         msecs (HTTP/1.1 200) 4 headers in 114 bytes (1 switches on core 0)
nginx_1         | 2019/06/15 20:21:11 [warn] 6#6: *3514 a client request body is                                                                                         buffered to a temporary file /var/cache/nginx/client_temp/0000000018, client: 1                                                                                        15.99.1.112, server: , request: "POST /finding/13/manage_images HTTP/1.1", host:                                                                                         "68.183.86.6:8080", referrer: "http://68.183.86.6:8080/finding/13/manage_images                                                                                        "
uwsgi_1         | STREAM 'IHDR' 16 13
uwsgi_1         | STREAM 'sRGB' 41 1
uwsgi_1         | STREAM 'gAMA' 54 4
uwsgi_1         | STREAM 'pHYs' 70 9
uwsgi_1         | STREAM 'IDAT' 91 65445
uwsgi_1         | Internal Server Error: /finding/13/manage_images
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/han                                                                                        dlers/exception.py", line 41, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/han                                                                                        dlers/base.py", line 249, in _legacy_get_response
uwsgi_1         |     response = self._get_response(request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/han                                                                                        dlers/base.py", line 187, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request                                                                                        )
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/han                                                                                        dlers/base.py", line 185, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **cal                                                                                        lback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/contrib/                                                                                        auth/decorators.py", line 23, in _wrapped_view
uwsgi_1         |     return view_func(request, *args, **kwargs)
uwsgi_1         |   File "./dojo/finding/views.py", line 1189, in manage_images
uwsgi_1         |     images_formset.save()
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/forms/mo                                                                                        dels.py", line 666, in save
uwsgi_1         |     return self.save_existing_objects(commit) + self.save_new_                                                                                        objects(commit)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/forms/mo                                                                                        dels.py", line 800, in save_new_objects
uwsgi_1         |     self.new_objects.append(self.save_new(form, commit=commit)                                                                                        )
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/forms/mo                                                                                        dels.py", line 644, in save_new
uwsgi_1         |     return form.save(commit=commit)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/forms/mo                                                                                        dels.py", line 468, in save
uwsgi_1         |     self.instance.save()
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/db/model                                                                                        s/base.py", line 808, in save
uwsgi_1         |     force_update=force_update, update_fields=update_fields)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/db/model                                                                                        s/base.py", line 838, in save_base
uwsgi_1         |     updated = self._save_table(raw, cls, force_insert, force_u                                                                                        pdate, using, update_fields)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/db/model                                                                                        s/base.py", line 924, in _save_table
uwsgi_1         |     result = self._do_insert(cls._base_manager, using, fields,                                                                                         update_pk, raw)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/db/model                                                                                        s/base.py", line 963, in _do_insert
uwsgi_1         |     using=using, raw=raw)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/db/model                                                                                        s/manager.py", line 85, in manager_method
uwsgi_1         |     return getattr(self.get_queryset(), name)(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/db/model                                                                                        s/query.py", line 1079, in _insert
uwsgi_1         |     return query.get_compiler(using=using).execute_sql(return_                                                                                        id)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/db/model                                                                                        s/sql/compiler.py", line 1111, in execute_sql
uwsgi_1         |     for sql, params in self.as_sql():
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/db/model                                                                                        s/sql/compiler.py", line 1064, in as_sql
uwsgi_1         |     for obj in self.query.objs
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/db/model                                                                                        s/sql/compiler.py", line 1013, in pre_save_val
uwsgi_1         |     return field.pre_save(obj, add=True)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/db/model                                                                                        s/fields/files.py", line 296, in pre_save
uwsgi_1         |     file.save(file.name, file.file, save=False)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/db/model                                                                                        s/fields/files.py", line 94, in save
uwsgi_1         |     self.name = self.storage.save(name, content, max_length=se                                                                                        lf.field.max_length)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/fil                                                                                        es/storage.py", line 54, in save
uwsgi_1         |     return self._save(name, content)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/fil                                                                                        es/storage.py", line 321, in _save
uwsgi_1         |     os.makedirs(directory)
uwsgi_1         |   File "/usr/local/lib/python2.7/os.py", line 150, in makedirs
uwsgi_1         |     makedirs(head, mode)
uwsgi_1         |   File "/usr/local/lib/python2.7/os.py", line 157, in makedirs
uwsgi_1         |     mkdir(name, mode)
uwsgi_1         | OSError: [Errno 13] Permission denied: '/app/media'
nginx_1         | 115.99.1.112 - - [15/Jun/2019:20:21:11 +0000] "POST /finding/1                                                                                        3/manage_images HTTP/1.1" 500 27 "http://68.183.86.6:8080/finding/13/manage_imag                                                                                        es" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like G                                                                                        ecko) Chrome/75.0.3770.90 Safari/537.36" "-"
uwsgi_1         | [pid: 1|app: 0|req: 2993/2993] 115.99.1.112 () {52 vars in 123                                                                                        2 bytes} [Sat Jun 15 20:21:11 2019] POST /finding/13/manage_images => generated                                                                                         27 bytes in 114 msecs (HTTP/1.1 500) 4 headers in 126 bytes (1 switches on core                                                                                         0)
celeryworker_1  | [2019-06-15 20:21:12,891: INFO/MainProcess] Received task: doj                                                                                        o.tasks.async_dupe_delete[0c51e3d0-c9ce-44c8-94e3-3cd75d487c0d]
celeryworker_1  | [2019-06-15 20:21:12,893: INFO/MainProcess] dojo.tasks.async_d                                                                                        upe_delete[0c51e3d0-c9ce-44c8-94e3-3cd75d487c0d]: delete excess duplicates
celeryworker_1  | [2019-06-15 20:21:12,897: INFO/MainProcess] Task dojo.tasks.as                                                                                        ync_dupe_delete[0c51e3d0-c9ce-44c8-94e3-3cd75d487c0d] succeeded in 0.00419680302                                                                                        73s: None
celeryworker_1  | [2019-06-15 20:22:12,904: INFO/MainProcess] Received task: dojo.tasks.async_dupe_delete[c9c2a8cf-4809-4f1c-8302-f5c49b80901b]
celeryworker_1  | [2019-06-15 20:22:12,906: INFO/MainProcess] dojo.tasks.async_dupe_delete[c9c2a8cf-4809-4f1c-8302-f5c49b80901b]: delete excess duplicates
celeryworker_1  | [2019-06-15 20:22:12,910: INFO/MainProcess] Task dojo.tasks.async_dupe_delete[c9c2a8cf-4809-4f1c-8302-f5c49b80901b] succeeded in 0.00417271000333s: None

**Additional context** (optional)

**Comment by Maffooch** [comment]
Hello @parag85 this bug will be fixed in the dev branch in PR #1255. The corrections in that PR have already been made on the python3_dev branch if switching over is an option for you.
