### ISSUE TITLE
add a simple button to upgrade DefectDojo

### ISSUE THREAD

**Issue by NRGLine4Sec** [DefectDojo/django-DefectDojo#1286]
It could be great if you add a simple button to upgrade DefectDojo in `Configuration`, `System Settings` page.

**Comment by madchap** [comment]
If we could get `dumpdata` and `loaddata` work flawlessly it would help. 

Currently not the case as I tried and raised an issue here: #1289

**Comment by NRGLine4Sec** [comment]
Yes, I can't upgrade to the new version of DefectDojo because, I already try to upgrade with the help of the documentation but it's not working. I had open an issue : https://github.com/DefectDojo/django-DefectDojo/issues/1250, but no one has answered me yet. This is why I open this issue, because it's would be great if we just have to click on the "upgrade" button and DefectDojo uprade itself automatically, like other software wokrs.

**Comment by devGregA** [comment]
@NRGLine4Sec I'm going to go ahead and archive this issue for now. I agree that upgrades are not as easy as they should be. At some point it is something we'll revisit, but our current focus is making functionality as resilient as possible through code changes.

**Comment by NRGLine4Sec** [comment]
OK but maybe you could add this to you [intern](https://github.com/DefectDojo/django-DefectDojo/projects/7) to do list ?
