### ISSUE TITLE
loaddata Test_Type duplicate entry

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1289]
**Bug description**
Context: Trying to export/import data from an instance running off of `dev` (python 2, May 28) to the newest `dev` (python 3, June 22), the latter being empty. My opinion is not to even try updating in place as it stands.

The instance running has data I cannot lose and need to re-import. I am guessing this is also a good exercise and some documentation could come out of it.  

The `loaddata` fails (after loading a bunch of stuff it seems) with:
```
$ docker exec -i django-defectdojo_uwsgi_1 bash -c 'python manage.py loaddata datadump_natural.json'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 312, in _query
    db.query(q)
  File "/usr/local/lib/python3.7/site-packages/MySQLdb/connections.py", line 224, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry 'Nessus Scan' for key 'name'")
```

I cannot provide the dump, unfortunately, due to private IP data being in it.

**Steps to reproduce**
1. `dumpdata` from the original instance with the following command: `docker exec -ti dojo_upstream_uwsgi_1 bash -c 'python manage.py dumpdata --indent=4 -e sessions -e admin --natural-foreign --natural-primary -e contenttypes -e auth.permission' > datadump_natural.json`
2. Get that file over to the new instance.
3. `loaddata` with `docker exec -i django-defectdojo_uwsgi_1 bash -c 'python manage.py loaddata datadump_natural.json'`
4. Error pops up.

Edit: the same happens when not using the `natural` flags.

**Expected behavior**
The entire data dump restores on the new instance with no problem!

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Comment by pratik0101** [comment]
Can i plz tell us impact?

**Comment by madchap** [comment]
Inability to have a proper backup/restore solution, or eventual upgrade path.

**Comment by madchap** [comment]
@aaronweaver This thing is definitely blocking me to move forward with DefectDojo. The ability to export/import is crucial, even for development purposes to test upgrade path for example.

Who do you think would be best at helping me out with this? I will dig some more, but would definitely appreciate a Django expert pointers.

Thank you!

**Comment by valentijnscholten** [comment]
Why is an in place upgrade not an option? I think I was told it should be ok to do an in place upgrade.

**Comment by madchap** [comment]
My current workaround, only locally test (partially, i.e clicking around)

On your new defectdojo instance, where you currently have no data other than what the initializer did:
```delete from dojo_test_type;
commit;
```
Load the fixture.

It (seems to) have worked for me.

**Comment by devGregA** [comment]
@madchap you're running into overlap in regards to what the initializer is doing and what is in your dump. Dumpdata also has an exclude option, so if disabling the initializer isn't an option, you can pass over a specific structure such as test type: `python manage.py  dumpdata dojo --exclude dojo.test_type >> backup.json`. You can also disable the env variable `DD_INITIALIZE`, which tells Dojo not to run the initializer script. If you disable the initializer script, you would also need to copy over your settings.py file, but  dump / load is functioning as intended.

**Comment by madchap** [comment]
> `python manage.py dumpdata dojo --exclude dojo.test_type >> backup.json`. 

Does not work, getting `Test_Type matching query does not exist.` when importing.
