### ISSUE TITLE
Python2.7 Legacy Branch Thorough Test

### ISSUE THREAD

**Issue by Maffooch** [DefectDojo/django-DefectDojo#1295]
The legacy dev branch needs to be thoroughly tested. 
Every single button needs to be clicked! 
This includes testing all scanners, API stuff, and various reports.
Record any issues you come across.

**Comment by devEricA** [comment]
Test Completed. Here's my report: https://docs.google.com/document/d/1ipoB6oRT3DOE9smgSsFzgOmlcouinKGhr2URaqwXkBU/edit?usp=sharing
