### ISSUE TITLE
Add the ability to export report as PDF

### ISSUE THREAD

**Issue by NRGLine4Sec** [DefectDojo/django-DefectDojo#1299]
Actuallly, it's only possible to export report in HTML or in AsciiDoc, it's would be great if you had the ability to export these as PDF.

**Comment by devGregA** [comment]
Hi @NRGLine4Sec we used to support a pdf option for reports, but it created some incompatibility issues and inconsistencies in regards to libraries. What most folks do now is use the HTML export and then save to PDF.
