### ISSUE TITLE
installation documentation

### ISSUE THREAD

**Issue by Oxima69** [DefectDojo/django-DefectDojo#1300]
Sorry. I am a beginner Linux/defectdojo
I am confused. python2, python3, pip pip3 Ubuntu 16.04, 18.04 virtualenv, venv, dev branch, requirenments.txt ...... .setup.bash etc.

I just can't get it to work.
Is there a current installation guide somewhere ?

Thank you guys

**Comment by ptrovatelli** [comment]
Hi @Oxima69 . Are you on linux or windows? 
for starting I recommend using the docker method described in 
- https://github.com/DefectDojo/django-DefectDojo/tree/dev §"quick start" 
- and a bit more detailed in 
https://github.com/DefectDojo/django-DefectDojo/blob/dev/DOCKER.md (some of the commands here require linux but you should check the pre-requisites there is the quick start is not working)

**Comment by Oxima69** [comment]
Hi @ptrovatelli Thanks for your answer.
I'am on Linux.
And prefer the installation for production. 
https://defectdojo.readthedocs.io/en/latest/running-in-production.html

- fresh Ubuntu 18 has python3 installed
- defectdojo´s dev branch is supposed to be on python3 (requirements.txt)

setup.bash install python2 etc....

Somewhat difficult for me to describe the exact problem as I previously had no touch points with django and python etc. :-)

Does defectdojo run completely on Python3 ?
And is there possibly a step by step guide for the installation? (Ubuntu 18.04 or Centos 7)

thanks for your help

**Comment by ptrovatelli** [comment]
OK. I can't help you though i'm only using docker for now. I'm not sure what's the status with the linux install right now. For general help request, maybe it's better you start with the stack channel though, and open an issue when you have found something specific that's definitely not working. 
Slack link can be found under "getting involved" at https://github.com/DefectDojo/django-DefectDojo
At this point I'd recommend to go with python3 dev branch for a linux install. If not already, it should work very soon.

**Comment by Oxima69** [comment]
Okay, thanks. I've got it going now.
I had to use this setup.bash file.

https://github.com/DefectDojo/django-DefectDojo/blob/dev/setup/setup.bash

This one looks better. --> python3

**Comment by ptrovatelli** [comment]
@Oxima69 so there is an issue: the documentation points to the wrong file when using python3 :) Other than that, every was working just by following the documentation? 
thanks
