### ISSUE TITLE
Twistlock parser should base itself on severity and not CVSS score

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1302]
**Bug description**
Depending on what we want to achieve here I guess.

If all parsers base themselves on CVSS score, we may want to keep this way to be homogeneous in DD.

However, going through a twistlock report now, the severity can be "low" (and shown as low in twistlock itself), the cvss score above 9, and we have a discrepancy.

Thoughts?

**Comment by madchap** [comment]
@aaronweaver @devGregA @valentijnscholten ^

**Comment by aaronweaver** [comment]
@madchap Do they explain why there is a discrepancy in severity vs. CVSS score? Are they doing some modification based on other mitigating factors? Most of the scanners utilize the severity field as CVSS support from the scanners varies.

**Comment by madchap** [comment]
I don't know.

However, looking at other scanners, I think I will change the behavior to take in `severity` and not `cvss`. There are a few that use cvss apparently, because there may be no obvious severity field.

If you agree with this, I will patch it.

**Comment by valentijnscholten** [comment]
I would think using severity would be best to stay in line with the other scanners. CVSS could (should?) be its own field in DefectDojo...

**Comment by madchap** [comment]
> I would think using severity would be best to stay in line with the other scanners. CVSS could (should?) be its own field in DefectDojo...

I would agree with CVSS being its own field as well.

**Comment by valentijnscholten** [comment]
might be best to have a separate issue/pr for that though

**Comment by madchap** [comment]
> might be best to have a separate issue/pr for that though

Of course.
