### ISSUE TITLE
Support Azure AD as authentication method

### ISSUE THREAD

**Issue by dougmorato** [DefectDojo/django-DefectDojo#1307]
**Feature request**
As more and more enterprises are leveraging Office 365 and Azure, implementing Azure AD authentication using OAuth would be extremely helpful as an alternative from relying on AD/LDAP connectivity, enabling admins to deploy Defect Dojo in the cloud without having to send authentication requests back to on-premises AD/LDAP

**Describe the solution you'd like**

- As a user, I would like to use my Azure AD / Office 365 credentials to log in to Defect Dojo and not have to remember yet another credential for a system.

- As a super-user, I would like to have any of the users of my Azure AD tenant be able to log in to Defect Dojo, but I want to manually enable the role and application they have access to.

**Describe alternatives you've considered**
Currently, there is no Active Directory integration or SAML integration out of the box. SInce cloud-enabled identities are becoming enterprise standard, Azure AD can piggyback on the excellent work done on the OKTA and Google OAuth integration

**Comment by aaronweaver** [comment]
@dougmorato I believe you can use oauth2 or saml with social auth. There is a guide [here](https://python-social-auth.readthedocs.io/en/latest/backends/azuread.html). Might just be a matter of adding those to the settings.py config.
