### ISSUE TITLE
Review emails get sent to unaddressed users

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1311]
**Bug description**
If I request a review to a specific user, all users that have the "Personal" notification for "Review requested" enabled receive the email. They should not, since they were not targeted in the review request.

This is on dev.

**Comment by adracea** [comment]
Hey , the email system works like this : 
If the user is subscribed to receive email notifications of the reviews, he'll get an email of that no matter if he is or not involved in the process . I think this should be up for a rework as it doesn't really make much sense and we should most likely only email the involved person (from which the review was requested) .

**Comment by madchap** [comment]
Yes indeed, the point of me opening the issue ;-) Thanks for confirming.

**Comment by madchap** [comment]
bot, don't do that.
