### ISSUE TITLE
Have specific fields for CVSS string and base score

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1313]
**Is your feature request related to a problem? Please describe**
Have optional fields to hold the information in a structured way.

The v2 API should also be updated accordingly if this is a separate process (?)

**Comment by madchap** [comment]
@valentijnscholten fyi

**Comment by aaronweaver** [comment]
We've talked about doing this in the past and were considering using an API such as [this](https://github.com/toolswatch/pycvss3) for parsing the string.
