### ISSUE TITLE
Changing DefectDojo URL breaks alerts links

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1314]
**Bug description**
The table `dojo_alerts` contains the full URL in the `url` field.

If you import data onto another instance, or change the port of the instance, the links of the alerts break.

**Steps to reproduce**
1. Do some stuff to have alerts
2. Modify your instance port and restart
3. Note the Alerts links still point to the original link and will fail to load when you click on it.

**Expected behavior**
The URL of the alerts adapt, and are not hardcoded in the database. They should contain a relative path.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Comment by madchap** [comment]
Example, I changed the defectdojo instance port as `dev` progressed with Dockerfile changes, so had to go to mysql and do:

`update defectdojo.dojo_alerts set url = replace(url, ':8000', ':8080') where instr(url, ':8000');`

in order for the links to keep working.

**Comment by aaronweaver** [comment]
@Maffooch We should probably add a DD_DOJO_URL to settings.dist.py and update alerts to utilize that.
