### ISSUE TITLE
Travis should use python3 for flake8 tests

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1320]
**Is your feature request related to a problem? Please describe**
See example of #1318 for flake8 failure.

```
Found violations: dojo/tools/blackduck/importer.py
	E999 @ 41:64 - SyntaxError: invalid syntax
Found violations: dojo/tools/blackduck/model.py
	E999 @ 7:12 - SyntaxError: invalid syntax
```

They pass when on python3. The code there is python 3.7+ only.

**Comment by Maffooch** [comment]
Turns out when Travis pulls a copy of python3 for flake8 testing, it pulls the default of Debian. At this time, the default is Python 3.5. Should just be as simple as pulling a newer reference of python to set this straight.

**Comment by madchap** [comment]
I think we should not restrict code that could be written just because the current travis pulls an older version of python. It would be shooting ourselves in the foot down the road.
