### ISSUE TITLE
Server Error 500 importing Arachni json Report 

### ISSUE THREAD

**Issue by Oxima69** [DefectDojo/django-DefectDojo#1322]
**Bug description**
Error 500 importing Arachni json Report.

**Deployment method**
- [ ] Kubernetes
- [ ] Docker
- [x] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 18.04
 - DefectDojo version: Dev branch
2d099e39: Merge pull request #1312 from madchap/fix-twistlock-sev-1302 [2019-06-27 13:17:19 -0500]

**Console logs** (optional)
Jun 28 12:18:24 dojo dojo[1621]: Successfully loaded extension "markdown.extensions.toc.TocExtension".
Jun 28 12:18:24 dojo dojo[1621]: Successfuly imported extension module "markdown.extensions.tables".
Jun 28 12:18:24 dojo dojo[1621]: Successfully loaded extension "markdown.extensions.tables.TableExtension".
Jun 28 12:18:25 dojo dojo[1621]: [pid: 1855|app: 0|req: 57/418] 172.17.166.1 () {46 vars in 1103 bytes} [Fri Jun 28 06:18:24 2019] GET /engagement/1 => generated 47558 bytes in 135 msecs (HTTP/1.1 200) 7 headers in 387 bytes (1 switches on core 0)
Jun 28 12:18:28 dojo dojo[1621]: [pid: 1750|app: 0|req: 76/419] 172.17.166.1 () {44 vars in 828 bytes} [Fri Jun 28 06:18:28 2019] GET /alerts/json?limit=12 => generated 804 bytes in 10 msecs (HTTP/1.1 200) 5 headers in 148 bytes (1 switches on core 0)
Jun 28 12:18:30 dojo dojo[1621]: [pid: 1851|app: 0|req: 84/420] 172.17.166.1 () {44 vars in 964 bytes} [Fri Jun 28 06:18:30 2019] GET /engagement/1/import_scan_results => generated 45086 bytes in 56 msecs (HTTP/1.1 200) 6 headers in 336 bytes (1 switches on core 0)
Jun 28 12:18:40 dojo dojo[1621]: [pid: 1750|app: 0|req: 77/421] 172.17.166.1 () {44 vars in 833 bytes} [Fri Jun 28 06:18:40 2019] GET /alerts/count => generated 12 bytes in 9 msecs (HTTP/1.1 200) 5 headers in 147 bytes (1 switches on core 0)
Jun 28 12:18:49 dojo dojo[1621]: item blowup
Jun 28 12:18:49 dojo dojo[1621]: Cross-Site Request Forgery (2608930084)
Jun 28 12:18:50 dojo dojo[1621]: applying rules
Jun 28 12:18:50 dojo dojo[1621]: [pid: 1750|app: 0|req: 78/422] 172.17.166.1 () {44 vars in 833 bytes} [Fri Jun 28 06:18:50 2019] GET /alerts/count => generated 12 bytes in 10 msecs (HTTP/1.1 200) 5 headers in 147 bytes (1 switches on core 0)
Jun 28 12:18:50 dojo dojo[1621]: Internal Server Error: /engagement/1/import_scan_results
Jun 28 12:18:50 dojo dojo[1621]: Traceback (most recent call last):
Jun 28 12:18:50 dojo dojo[1621]:   File "/opt/dojo/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
Jun 28 12:18:50 dojo dojo[1621]:     response = get_response(request)
Jun 28 12:18:50 dojo dojo[1621]:   File "/opt/dojo/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
Jun 28 12:18:50 dojo dojo[1621]:     response = self.process_exception_by_middleware(e, request)
Jun 28 12:18:50 dojo dojo[1621]:   File "/opt/dojo/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
Jun 28 12:18:50 dojo dojo[1621]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Jun 28 12:18:50 dojo dojo[1621]:   File "/opt/dojo/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
Jun 28 12:18:50 dojo dojo[1621]:     return view_func(request, *args, **kwargs)
Jun 28 12:18:50 dojo dojo[1621]:   File "./dojo/engagement/views.py", line 550, in import_scan_results
Jun 28 12:18:50 dojo dojo[1621]:     burpRequestBase64=req_resp["req"].encode("utf-8"),
Jun 28 12:18:50 dojo dojo[1621]: AttributeError: 'bytes' object has no attribute 'encode'
Jun 28 12:18:50 dojo dojo[1621]: [pid: 1851|app: 0|req: 85/423] 172.17.166.1 () {52 vars in 1244 bytes} [Fri Jun 28 06:18:49 2019] POST /engagement/1/import_scan_results => generated 27 bytes in 903 msecs (HTTP/1.1 500) 5 headers in 159 bytes (16 switches on core 0)
Jun 28 12:18:56 dojo systemd[1]: Starting Message of the Day...

**Additional context** (optional)
the first finding (entry) is imported and displayed

**Comment by devGregA** [comment]
@devEricA

**Comment by Oxima69** [comment]
Nice ....it works, thank you for your effort.
Little question from a beginner.
I just did a git pull to get the changes. That's enough ?
