### ISSUE TITLE
Dojo Intake Survey

### ISSUE THREAD

**Issue by devGregA** [DefectDojo/django-DefectDojo#1333]
**Is your feature request related to a problem? Please describe**
A clear and concise description of what the problem is.

Project Goal: Add intake functions to Dojo that allow users to request assessments and provide information through a questionnaire.

We had done this previously at Rackspace. Here is the code: https://github.com/grendel513/defectDojo-engagement-survey

- [x] Step 1: [Convert the code to python3](https://docs.python.org/2/library/2to3.html), add it to a repo in the Dojo GitHub, test the plugin
- [x] Step 2: Create a view on the dojo dashboard that displays unassigned engagements from the survey
- [x] Step 3: In the dashboard, create a way to assign / self-assign unassigned engagements created for surveys
- [x] Step 4. Make sure the plugin is added by default in setup.bash / docker

**Additional context**
Add any other context, screenshots, sketch, code snippet, etc. about the feature request here.

**Comment by ycrumeyrolle** [comment]
Is this feature developed or is the issue just closed?

**Comment by Maffooch** [comment]
This feature is developed. Im slowly working on documentation now and will push both once everything is ready.
