### ISSUE TITLE
API v2: Add ability to deal with findings through tags

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1340]
**Is your feature request related to a problem? Please describe**
In the same vein in making tags a first-class citizen, we should be able to deal with findings using tags, through the API.

Today, no parameter allows this.

`/api/v2/findings/` API path should be augmented with a `tags` parameter or similiar.

**Comment by propersam** [comment]
I would be taking this up...

can i get more explanation and direction of where else tag is used somewhere in the project

**Comment by Maffooch** [comment]
@propersam Tags can be added to a finding by editing them. They can add some extra info, or just as a label. Issue is, the tags are not models. They are stored in a finding as a simple list of Tag objects. That is the reason it is not possible to add tags when creating a new finding. Im not sure how this will be done. Best of luck!

**Comment by propersam** [comment]
Tags not being a model is not a problem for me....

lemme check it out..nd come back if i've got any questions...

**Comment by propersam** [comment]
meanwhile i made some PR to Documentation repo..expecting merge in order to proceed with unittest issue...

**Comment by propersam** [comment]
@madchap @Maffooch 
I added a tag endpoint to conrol tags in findings.
you can perform any of the following request:
GET
POST
DELETE

http://127.0.0.1:8080/api/v2/findings/2/tags/

data format is an array of tags:
{
	"tags": ["desperate", "metarmorphosis"]
}

**Comment by propersam** [comment]
For the sake of understandable documentation there have been an update...
a new end point as been added..

http://127.0.0.1:8080/api/v2/findings/:id/remove_tags/

this endpoint cn take *PUT* or *PATCH* method..
and receive data format:

{
"tags": ["tag1", "tag2"]
}

*DELETE* method is no more supported on http://127.0.0.1:8080/api/v2/findings/:id/tags/ endpoint
only *GET* and *POST*
