### ISSUE TITLE
API: Ability to retrieve findings notes

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1343]
**Is your feature request related to a problem? Please describe**
The API does not have any endpoint to retrieve notes made on findings.

**Describe the solution you'd like**
An endpoint to retrieve notes with their id.

Ideally, the whole suite of methods as appropriate.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you have considered.

**Additional context**
Add any other context, screenshots, sketch, code snippet, etc. about the feature request here.

**Comment by propersam** [comment]
working on this..

**Comment by propersam** [comment]
@madchap can you test...before I move on to add tests nd documentation

http://localhost:8000/api/v2/notes/ - fetches all notes
http://localhost:8000/api/v2/notes/2 - fetch note by id

**Comment by propersam** [comment]
I think You can also perform POST request and other basic API request..
.. help test them all out...

**Comment by madchap** [comment]
Will do, hopefully some time today (CEST TZ). Thanks for taking this on quickly!
