### ISSUE TITLE
Add "remove all" for Alerts

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#1346]
**Is your feature request related to a problem? Please describe**
As a staff user I'm currently seeing 75 pages of alerts and I would like to be able to remove them all at once

**Describe the solution you'd like**
Remove all button

**Comment by madchap** [comment]
This was done already in #1211 ?

**Comment by valentijnscholten** [comment]
Hmm I searched for 'alert' and 'alerts' and 'remove all' etc. Not for 'clear all' I guess, but good that it is already there, guess I need to upgrade to python3.
