### ISSUE TITLE
Getting ERROR: Service 'uwsgi' failed to build while executing docker-compose build

### ISSUE THREAD

**Issue by bilalk88** [DefectDojo/django-DefectDojo#1349]
# docker-compose build
mysql uses an image, skipping
initializer uses an image, skipping
rabbitmq uses an image, skipping
celeryworker uses an image, skipping
celerybeat uses an image, skipping
Building uwsgi
Step 1/21 : FROM python:2 as build
**ERROR: Service 'uwsgi' failed to build: Error parsing reference: "python:2 as build" is not a valid repository/tag: invalid reference format**

I'm using CentOS 7.

**Comment by bilalk88** [comment]
Figured out the concern. Now it's working fine.

**Comment by chethanabhaskara** [comment]
Could you tell me what was the problem here? I'm facing the same problem in CentOS
