### ISSUE TITLE
Download AsciiDoc report as plaintext

### ISSUE THREAD

**Issue by denniskniep** [DefectDojo/django-DefectDojo#1352]
**Is your feature request related to a problem? Please describe**
Everytime copy/paste the ascii-doc report from the html page into a textfile. That is a pain point in case of automation.

**Describe the solution you'd like**
Provide a button to download the ascii-doc report as text file. Would be nice that this functionality could be also easily executed via API.

**Comment by propersam** [comment]
@mafooch have this assigned to me....
already looking into it..

**Comment by propersam** [comment]
After trying different methods this past few days.. I finally went with the method that uses javascript without interacting with server....

@denniskniep does this meet your requirement...?

**Comment by propersam** [comment]
i'm not sure of the possiblity of trigerring the download through API... 

@Maffooch  are asciidoc reports also generated through API ?... i can't seem to find where that is going on..?

**Comment by Maffooch** [comment]
@propersam Are you asking where to view asciidoc reports? When generating a report, instead of generating the HTML version, use the drop down where it says HTML and select Asciidoc.

**Comment by propersam** [comment]
That is d GUI... Which I have implemented now... I am asking if report are generated through any of the Api endpoints..

**Comment by propersam** [comment]
That one can request through curl or postman

**Comment by Maffooch** [comment]
> Edit: Never mind, I see what's going on. At first glance, it doesn't look like reports can be generated from the API. Looks like you have to implement it. API v1 stuff is in /dojo/api.py and you're already familiar with v2 stuff.

**Comment by propersam** [comment]
Oh... 

That means I can implement it in Apiv2 right?

**Comment by Maffooch** [comment]
I guess implement in both. No idea what @denniskniep preference is on API version.

**Comment by denniskniep** [comment]
Thank you very much for your efforts! ApiV2 would be sufficient for me :)

**Comment by propersam** [comment]
Hey @Maffooch nd @denniskniep 

I added a huge enhancement to DefectDojo.

You can now generate reports through Api v2 with the above PR

You need to make a POST request.. to any of the following valid endpoints:

http://127.0.0.1:8000/api/v2/product_types/<id>/generate_report/
http://127.0.0.1:8000/api/v2/products/<id>/generate_report/
http://127.0.0.1:8000/api/v2/engagements/<id>/generate_report/
http://127.0.0.1:8000/api/v2/endpoints/<id>/generate_report/
http://127.0.0.1:8000/api/v2/tests/<id>/generate_report/
http://127.0.0.1:8000/api/v2/findings/generate_report/

the Post data can receive any of the following fields: 
(Post data is optional default values of 'false' are already initialised)

{
	"include_finding_notes":true,
	"include_executive_summary": true,
	"include_table_of_contents": false,
	"include_finding_images": true
}

**Comment by propersam** [comment]
Please do try it out..and let me know if it's okay to process with Documenation and unittest.
