### ISSUE TITLE
Add new image and select from existing images inside the finding editor

### ISSUE THREAD

**Issue by denniskniep** [DefectDojo/django-DefectDojo#1354]
**Is your feature request related to a problem? Please describe**
Jump between the views "Edit a Finding"  and  "Add images to ..." to add images

**Describe the solution you'd like**
It would be really nice if I could add an image to a finding inside the edit mode. There is already an image button in the toolbar of the text fields. Maybe there can be a drop down list with already uploaded images and a button for uploading a new image. 
Furthermore the link to the existing or new image could be automatically inserted.

**Comment by dr3dd589** [comment]
hello, @Maffooch assign this to me and set it in progress.

**Comment by denniskniep** [comment]
...still relevant for me, thx.

**Comment by denniskniep** [comment]
...still relevant for me, thx.
