### ISSUE TITLE
not able to access defectdojo

### ISSUE THREAD

**Issue by bilalk88** [DefectDojo/django-DefectDojo#1357]
Hello, 
I ran docker-compose up, for few minutes it's working and after keeping it idle for few minutes like 30 minutes or 1 hours then in console getting below logs while I try to access DefectDojo [http://localhost:8080]
celeryworker_1  | [2019-07-09 08:47:40,663: INFO/MainProcess] Received task: dojo.tasks.async_dupe_delete[a038f0cb-bc68-4adb-9f7e-65d142204f7a]
celeryworker_1  | [2019-07-09 08:47:40,664: INFO/MainProcess] dojo.tasks.async_dupe_delete[a038f0cb-bc68-4adb-9f7e-65d142204f7a]: delete excess duplicates
celeryworker_1  | [2019-07-09 08:47:40,668: INFO/MainProcess] Task dojo.tasks.async_dupe_delete[a038f0cb-bc68-4adb-9f7e-65d142204f7a] succeeded in 0.00395535200005s: None

**Comment by Maffooch** [comment]
Hey @bilalk88 just to clarify, you were able to connect and use DefectDojo and then after some time you could no longer connect? The logs seen above are more like status codes rather than error codes. They are totally normal.

**Comment by bilalk88** [comment]
Hi @Maffooch . Thanks for the response.
Yeah. When I execute docker-compose up, for few minutes I'm able to access it and use it. But after sometime I'm not able to access it. Getting something like this "This site can’t be reached".

For reference, you can refer below screenshot.

![image](https://user-images.githubusercontent.com/10231632/60893486-a0de1a00-a27e-11e9-8cc0-b0682f8e4493.png)

**Comment by Maffooch** [comment]
Seems like there is a timeout due to inactivity somewhere in your configuration. Could be associated with your network, database or elsewhere. Does everything return to normal by stopping the process and relaunching with docker-compose up?

**Comment by bilalk88** [comment]
Once I got the time out. I've to restart the machine and again have to execute the docker-compose up.
If I stop the process and again run the docker-compose up, it's not working. 
But when I check the docker ps or docker-compose ps, found that all required containers are running.

**Comment by Maffooch** [comment]
Try docker-compose down. It kills and removes containers without trashing your data. It should get around the issue of restarting your machine.

**Comment by bilalk88** [comment]
Just observed that when I check locally on the main machine its working. e.g. http://localhost:8080/
But when I try the same on remote machine by using the http://<ip where DefectDojo>:8080 . It works for sometime. And then again facing that time out concern.

**Comment by Maffooch** [comment]
Sounds like the connection between remote and host machine is the suspect. Is it okay to close this issue?

**Comment by bilalk88** [comment]
Yes. I think something is getting blocked after sometime. will check the iptables. 
Thanks for the help.
Yeah will close the issue..
