### ISSUE TITLE
Importing existing Jira tickets into Dojo

### ISSUE THREAD

**Issue by nebi-frame** [DefectDojo/django-DefectDojo#1359]
**Is your feature request related to a problem? Please describe**
Instead of creating webhooks for newly created jira issues, I want to export every issues in my jira to dojo.

**Describe the solution you'd like**
Importer for jira based on csv or xml 

**Describe alternatives you've considered**
No alternatives that I can think of.

**Comment by xthk** [comment]
I'd recommend to use Jira's API for that.

1. GET an issue via `/rest/api/latest/issue/FOOBAR-3141`,
1. create a finding in DefectDojo,
1. and link back to Jira

Jira API docs: https://developer.atlassian.com/server/jira/platform/rest-apis/

**Comment by Maffooch** [comment]
@nebi-frame Is using Jira's API a sufficient solution for you?
