### ISSUE TITLE
Checkmarx scan import failed because of bad char

### ISSUE THREAD

**Issue by Tibo-le-canard** [DefectDojo/django-DefectDojo#1369]
**Bug description**
Hello,

Some import of checkmarx scan fail because of bad char encoding.
I manage to fix the issue, here are the modifications I made :
https://github.com/Tibo-le-canard/django-DefectDojo/commit/be7ece8442fb38e3fadc238abb16f8700c6ac6dc

Should I make a pull request ?

**Steps to reproduce**
Hard to reproduce.
I can't provide the file, there is to much data in it.

**Expected behavior**
The import should be successful.

**Deployment method**
- [x ] Docker

**Environment information**
 - Operating  Ubuntu 18.04
 - DefectDojo version: 5a350025: Merge pull request #1330 from Maffooch/update_PR_template [2019-07-01 11:13:16 -0500]

**Console logs** (optional)

> uwsgi_1         | Internal Server Error: /product/1/import_scan_results
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
uwsgi_1         |     response = self._get_response(request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
uwsgi_1         |     return view_func(request, *args, **kwargs)
uwsgi_1         |   File "./dojo/product/views.py", line 389, in import_scan_results_prod
uwsgi_1         |     return import_scan_results(request, pid=pid)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
uwsgi_1         |     return view_func(request, *args, **kwargs)
uwsgi_1         |   File "./dojo/engagement/views.py", line 517, in import_scan_results
uwsgi_1         |     parser = import_parser_factory(file, t, active, verified)
uwsgi_1         |   File "./dojo/tools/factory.py", line 80, in import_parser_factory
uwsgi_1         |     parser = CheckmarxXMLParser(file, test)
uwsgi_1         |   File "./dojo/tools/checkmarx/parser.py", line 74, in __init__
uwsgi_1         |     title, description, pathnode = self.get_finding_detail(query, result)
uwsgi_1         |   File "./dojo/tools/checkmarx/parser.py", line 111, in get_finding_detail
uwsgi_1         |     findingdetail = "{}**Source Object:** {}\n".format(findingdetail, pathnode.find('Name').text)
uwsgi_1         | UnicodeEncodeError: 'ascii' codec can't encode character u'\xf9' in position 104: ordinal not in range(128)
uwsgi_1         | Internal Server Error: /product/1/import_scan_results
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
uwsgi_1         |     response = self._get_response(request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
uwsgi_1         |     return view_func(request, *args, **kwargs)
uwsgi_1         |   File "./dojo/product/views.py", line 389, in import_scan_results_prod
uwsgi_1         |     return import_scan_results(request, pid=pid)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
uwsgi_1         |     return view_func(request, *args, **kwargs)
uwsgi_1         |   File "./dojo/engagement/views.py", line 517, in import_scan_results
uwsgi_1         |     parser = import_parser_factory(file, t, active, verified)
uwsgi_1         |   File "./dojo/tools/factory.py", line 80, in import_parser_factory
uwsgi_1         |     parser = CheckmarxXMLParser(file, test)
uwsgi_1         |   File "./dojo/tools/checkmarx/parser.py", line 74, in __init__
uwsgi_1         |     title, description, pathnode = self.get_finding_detail(query, result)
uwsgi_1         |   File "./dojo/tools/checkmarx/parser.py", line 111, in get_finding_detail
uwsgi_1         |     findingdetail = "{}**Source Object:** {}\n".format(findingdetail, pathnode.find('Name').text)
uwsgi_1         | UnicodeEncodeError: 'ascii' codec can't encode character u'\xf9' in position 104: ordinal not in range(128)

**Comment by dr3dd589** [comment]
yes, we have to encode these to utf-8. your fix looking good to me. Can you open a PR to fix this or I do?
