### ISSUE TITLE
System settings are not accessible.

### ISSUE THREAD

**Issue by ycrumeyrolle** [DefectDojo/django-DefectDojo#1370]
**Bug description**
System settings are not accessible and generates an error. Trying to access to it cause the server to freeze during about 30 seconds.

**Steps to reproduce**
1. Go to 'https://defectdojo.herokuapp.com'
2. Connect as 'admin'
3. Clic on 'Configuration' -> 'System settings'
4. Wait....
5. See error

**Expected behavior**
Display the System settings

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
https://defectdojo.herokuapp.com

**Screenshots**
![image](https://user-images.githubusercontent.com/1958836/61127745-72e01c00-a4b0-11e9-8a20-ce7ed206d430.png)

**Additional context** (optional)
We have the same issue with our local docker instance.

**Comment by devGregA** [comment]
@Maffooch  please verify.

**Comment by Maffooch** [comment]
Hey @ycrumeyrolle I was able to replicate your error in the heroku app, but not on the master, nor dev branch. I remember experiencing this error at one point a while back though. How recent is your local build?

**Comment by ycrumeyrolle** [comment]
Hi @Maffooch, we have deployed the docker file 1.5.4rc5 available on https://hub.docker.com/r/defectdojo/defectdojo-django (latest version)

The issue was fixed by adding the components Celery & RabbitMQ.

**Comment by Maffooch** [comment]
@ycrumeyrolle Good deal. Glad you got it working.
