### ISSUE TITLE
Include tags in reports

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1378]
**Is your feature request related to a problem? Please describe**
When executing a report for an engagement, findings' tags do not show up in the reports.

**Describe the solution you'd like**
An extra column could be added to list the tags of the findings.

**Comment by dr3dd589** [comment]
hello, @madchap you want to add tags information in HTML and AsciiDoc reports or just show a column of tags of findings before generating reports?

**Comment by madchap** [comment]
Hey @dr3dd589 

I was thinking in the reports. It does not have to be a column maybe -- for the HTML -- a cue in the finding's header or something?
