### ISSUE TITLE
mysql-client APT package installation  attempt causes Docker Compose Build to Fail

### ISSUE THREAD

**Issue by theappsecguy** [DefectDojo/django-DefectDojo#1381]
When running "docker-compose build" command, it fails when attempting to install mysql-client because the APT package manager does not recognize "mysql-client" as an actual package name. 

To fix this, I had to go into the Dockerfile and change "mysql-client" to "default-mysql-client". From there I was able to successfully build the Docker image. 

Would recommend changing this in the Docker files.

**Comment by Maffooch** [comment]
@theappsecguy This has now been fixed on both the master and dev branches. Thank you for the concern.
