### ISSUE TITLE
Nikto importing fails

### ISSUE THREAD

**Issue by dougmorato** [DefectDojo/django-DefectDojo#1382]
**Bug description**
When attempting to import XML reports from the NIKTO nxmlversion="1.2", the import fails as the importer is not able to find the scan details

I do not have an old file to compare, but the current NIKTO export has 2 <niktoscan> tags in the XML.

**Comment by Maffooch** [comment]
@dougmorato Importing the NIKTO file in the [sample-scan repo](https://github.com/DefectDojo/sample-scan-files/blob/master/nikto/nikto.xml) did not produce any errors. It is xml version 1.0. Are you able to provide the error traceback since the file is not available?
