### ISSUE TITLE
Result Upload Api

### ISSUE THREAD

**Issue by outdoorguy007** [DefectDojo/django-DefectDojo#1392]
Has anyone been able to upload results via the API?  I must be doing something wrong. I always get {"file":["The submitted data was not a file. Check the encoding type on the form."]}

Here is the code.
#! /usr/bin/python
import requests
import json

url = 'https://defectdojo.herokuapp.com/api/v2/import-scan/'

headers = {#'content-type': 'application/json',
           'Authorization': 'Token 548afd6fab3bea9794a41b31da0e9404f733e222'}
          

body = {'scan_date': '2019-07-04',
        'scan_type': 'Dependency Check Scan',
        'file': '/Users/tchase/Downloads/dependency-check/bin/dependency-check-report.json',
        'engagement': '14',
        'lead': '1'
        }

r = requests.post(url, headers=headers, verify=True, data=body) # set verify to False if ssl

**Comment by Maffooch** [comment]
Hey @outdoorguy007 I assume you're using APIv2. Based on this [unit test](https://github.com/DefectDojo/django-DefectDojo/blob/5a3500257f34193dc206e3e2607683e105a9b9fb/dojo/unittests/test_apiv2_scan_import_options.py#L28), it looks like you have to input an actual file instead of the path to it.

**Comment by outdoorguy007** [comment]
Yeah, so I tried that and now it gives me a 503...

import requests
import json

url = 'https://defectdojo.herokuapp.com/api/v2/import-scan/'

headers = {
        'Content-type': 'multipart/form-data',
           'Authorization': 'Token 548afd6fab3bea9794a41b31da0e9404f733e222'}
          
files = {'file': open('/Users/tchase/Downloads/dependency-check/bin/dependency-check-report.json','rb')}


body = {'scan_date': '2019-07-04',
        'scan_type': 'Dependency Check Scan',
        'engagement': '18',
        'lead': '1'
        }

r = requests.post(url, headers=headers, files=files, verify=True, data=body) # set verify to
