### ISSUE TITLE
Getting 500 Server Error when trying to upload nessus scan files

### ISSUE THREAD

**Issue by bilalk88** [DefectDojo/django-DefectDojo#1399]
Getting 500 Server Error when trying to upload nessus scan file.
Below is the console log.

uwsgi_1         | [pid: 1|app: 0|req: 31/31] xx.xx.xx.xx () {44 vars in 836 bytes} [Mon Jul 22 09:20:55 2019] GET /alerts/count => generated 13 bytes in 8 msecs (HTTP/1.1 200) 4 headers in 114 bytes (1 switches on core 0)
nginx_1         | xx.xx.xx.xx - - [22/Jul/2019:09:20:55 +0000] "GET /alerts/count HTTP/1.1" 200 13 "http://xx.xx.xx.xx:8080/engagement/3/import_scan_results" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36" "-"

nginx_1         | 2019/07/22 09:21:01 [warn] 6#6: *1 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000001, client: xx.xx.xx.xx, server: , request: "POST /engagement/3/import_scan_results HTTP/1.1", host: "xx.xx.xx.xx:8080", referrer: "http://xx.xx.xx.xx:8080/engagement/3/import_scan_results"
uwsgi_1         | Internal Server Error: /engagement/3/import_scan_results
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
uwsgi_1         |     response = self._get_response(request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
uwsgi_1         |     return view_func(request, *args, **kwargs)
uwsgi_1         |   File "./dojo/engagement/views.py", line 517, in import_scan_results
uwsgi_1         |     parser = import_parser_factory(file, t, active, verified)
uwsgi_1         |   File "./dojo/tools/factory.py", line 68, in import_parser_factory
uwsgi_1         |     parser = NessusXMLParser(file, test)
uwsgi_1         |   File "./dojo/tools/nessus/parser.py", line 184, in __init__
uwsgi_1         |     impact = item.find("description").text + "\n\n"
uwsgi_1         | AttributeError: 'NoneType' object has no attribute 'text'
uwsgi_1         | [pid: 1|app: 0|req: 32/32] xx.xx.xx.xx () {52 vars in 1252 bytes} [Mon Jul 22 09:21:01 2019] POST /engagement/3/import_scan_results => generated 27 bytes in 184 msecs (HTTP/1.1 500) 4 headers in 126 bytes (1 switches on core 0)
nginx_1         | xx.xx.xx.xx - - [22/Jul/2019:09:21:01 +0000] "POST /engagement/3/import_scan_results HTTP/1.1" 500 27 "http://xx.xx.xx.xx:8080/engagement/3/import_scan_results" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36" "-"

**Comment by adracea** [comment]
Hello , could you also show us a redacted version of the nessus scan file used ?

**Comment by bilalk88** [comment]
I'm using Nessus version : 8.5.1

**Comment by bilalk88** [comment]
[nessus-scan.zip](https://github.com/DefectDojo/django-DefectDojo/files/3417681/nessus-scan.zip)
Attached is the nessus file, that I'm using.
