### ISSUE TITLE
Minikube is blowing up

### ISSUE THREAD

**Issue by Maffooch** [DefectDojo/django-DefectDojo#1403]
**Bug description**
When broker ares being run by Travis CI, the Minikube server cannot be accessed. The test continues to run until timeout. Maybe updating will resolve this issue?

**Steps to reproduce**
1. Submit a PR for travis to test
2. See many error messages

**Expected behavior**
Travis is happy

**Screenshots**
<img width="994" alt="Screen Shot 2019-07-22 at 2 56 00 PM" src="https://user-images.githubusercontent.com/46459665/61661199-2905eb80-ac91-11e9-9d2c-e7d0a777a693.png">

**Comment by dr3dd589** [comment]
the error looks something like this [issue](https://github.com/kubernetes/minikube/issues/2493)
