### ISSUE TITLE
Helm deployment doesn't allow specifying SSL connection to MySQL

### ISSUE THREAD

**Issue by jmezach** [DefectDojo/django-DefectDojo#1410]
**Bug description**
We are trying to deploy DefectDojo into an Azure Kubernetes (AKS) cluster with the database stored on Azure MySQL Hosted Service. However, as we were trying to make that work we ran into an issue that it doesn't seem possible to specify through the Helm chart that the connection to the database should be encyrpted. By default Azure MySQL database enforces SSL. We can of course disable this, but we prefer not to.

**Steps to reproduce**
1. Deploy DefectDojo through the [Helm chart](https://github.com/DefectDojo/django-DefectDojo/tree/master/helm/defectdojo)
2. See that there is no way to specify SSL connection to the database.

**Expected behavior**
From a security related tool I would expect there is some way to configure using an SSL connection to the database.

**Deployment method** *(select with an `X`)*
- [X] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 16.04 (hosted agent)
 - DefectDojo version: 1.5.4

**Comment by alles-klar** [comment]
Hi @jmezach, if you want to connect to the database over ssl you can add this option in the django settings file. For this you have to build your own django container. It does not work out of the box at the moment, but if you want to run it in production you will have to customize the file either way.

**Comment by onecallalex** [comment]
I ran into this as well, and would love to see it resolved.

**Comment by 676031** [comment]
I have found the steps to add “root-ca.pem” to establish ssl connection to AWS RDS. 
In my case Im working with GCP and there are (server-ca, client-ca and client-key) needed to configure ssl connection for postgresql. 
it will be very helpful to have some explanation of how to make it work.
