### ISSUE TITLE
Add CIS Benchmark

### ISSUE THREAD

**Issue by tkr6743** [DefectDojo/django-DefectDojo#1414]
Dear Team,

Can you please suggest me how to add new benchmarks to the defectdojo tool

**Comment by Maffooch** [comment]
Hey @tkr6743 adding benchmarks to DefectDojo requires modifications of the fixtures in the source code. These fixtures can be found in /dojo/fixtures. Files related to benchmarks generally have "benchmark" in the file name. Fixtures can then be loaded into the database via the loaddata command. It is used as follows: "python3 manage.py loaddata <fixture_filename.json>".
