### ISSUE TITLE
Looking for a DefectDojo sensei to consult on implementation

### ISSUE THREAD

**Issue by coivase** [DefectDojo/django-DefectDojo#1421]
I'm looking to consult someone knowledgable on the DefectDojo implementation. Specifically interested in mistakes to avoid and lessons learned with Jira hookup, metadata to collect, reporting, engaging vulnerability owners, etc.

**Comment by ptrovatelli** [comment]
Hi @coivase . 
If you haven't found yet, you can ask your questions on the slack channel. See under "Gettings involved" at https://github.com/DefectDojo/django-DefectDojo
