### ISSUE TITLE
Uploading Synk Scan fails wiht 500 status code

### ISSUE THREAD

**Issue by praveendvd** [DefectDojo/django-DefectDojo#1432]
**Bug description**

Uploading snyk.json throws 500 status code

**Steps to reproduce**

1. Go to Engagement>Import_scan
2. Import 'Snyk Scan' json result
3. see the error

**Expected behavior**

status 201 

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [CentOS Linux release 7.6.1810 (Core)  ]
 - DefectDojo version: [Docker Hub Latest]

**Sample scan files** (optional)

[snyk.zip](https://github.com/DefectDojo/django-DefectDojo/files/3443112/snyk.zip)

**Screenshots** (optional)
![image](https://user-images.githubusercontent.com/45095911/62062969-f07e8880-b221-11e9-9fbd-af7c08f12eb7.png)

**Additional context** (optional)

Retire.js results also throws 500 error

**Comment by devGregA** [comment]
@devEricA @praveendvd has included a sample scan file, please verify.

**Comment by devEricA** [comment]
Worked fine on mine @devGregA under the dev branch. @praveendvd Which branch are you using?

**Comment by praveendvd** [comment]
> Worked fine on mine @devGregA under the dev branch. @praveendvd Which branch are you using?

Hi i am using docker image,

Below are the steps i did

stop all containers (sudo docker stop $(sudo docker ps -aq)
remove all images using (sudo docker system prune -a)
run the dojo container  (sudo docker run -it -p 8000:8000 appsecpipeline/django-defectdojo)

created a new product under research adn development
created a new engagement
upload synk report

i tried in another centos OS system and was able to reproduce the issue

i am logged in as non root , and i have only admin account in dojo

**Comment by dr3dd589** [comment]
works fine for me too on the dev branch. @praveendvd  checkout to the dev branch.
````
git checkout dev
docker-compose build
cp dojo/settings/settings.dist.py dojo/settings/settings.py
docker/setEnv.sh dev
docker-compose up ```

before running these commands remove all images.

**Comment by praveendvd** [comment]
> works fine for me too on the dev branch. @praveendvd checkout to the dev branch.
> 
> ```
> git checkout dev
> docker-compose build
> cp dojo/settings/settings.dist.py dojo/settings/settings.py
> docker/setEnv.sh dev
> docker-compose up ```
> 
> before running these commands remove all old images.
> ```
@dr3dd589 @devEricA @devGregA 

Hi , I cloned the latest code from git and ran the docker. Now the upload is working from UI but not through API.

Below is the python python code i used
**Note:** The defect dojo api package is the latest one available in the git. i pulled the code and installed through ' python setup.py develop'.


```
#!/usr/bin/python

#import the package
from defectdojo_api import defectdojo
import os

#setup DefectDojo connection information
host = 'http://localhost:8000'
api_key = '<Provide_API>''
user = 'admin'


#instantiate the DefectDojo api wrapper
dd = defectdojo.DefectDojoAPI(host, api_key, user, debug=False)


print dd.upload_scan(1,"Snyk Scan", "<file_path>/snyk.json", "True", "2019-08-08")

```


Could you please guide me here, is it issue with pytho api

how to try this manually , what would be the payload. How to try the same using rest-client or postman.

**Comment by praveendvd** [comment]
> > works fine for me too on the dev branch. @praveendvd checkout to the dev branch.
> > ```
> > git checkout dev
> > docker-compose build
> > cp dojo/settings/settings.dist.py dojo/settings/settings.py
> > docker/setEnv.sh dev
> > docker-compose up ```
> > 
> > before running these commands remove all old images.
> > ```
> 
> @dr3dd589 @devEricA @devGregA
> 
> Hi , I cloned the latest code from git and ran the docker. Now the upload is working from UI but not through API.
> 
> Below is the python code i used for uploading the scan results
> 
> **Note:** The defect dojo api package is the latest one available in the git. i pulled the code and installed through ' python setup.py develop'.
> 
> ```
> #!/usr/bin/python
> 
> #import the package
> from defectdojo_api import defectdojo
> import os
> 
> #setup DefectDojo connection information
> host = 'http://localhost:8000'
> api_key = '<Provide_API>''
> user = 'admin'
> 
> 
> #instantiate the DefectDojo api wrapper
> dd = defectdojo.DefectDojoAPI(host, api_key, user, debug=False)
> 
> 
> print dd.upload_scan(1,"Snyk Scan", "<file_path>/snyk.json", "True", "2019-08-08")
> ```
> 
> Could you please guide me here, is it issue with pytho api
> 
> how to try this manually , what would be the payload. How to try the same using rest-client or postman.

Hi i was able to check the same using postman, and it throws the same error, @devGregA  @devEricA @dr3dd589 

![image](https://user-images.githubusercontent.com/45095911/62149670-2ee47800-b2f4-11e9-8bab-cec98c118681.png)

**Comment by praveendvd** [comment]
> > > works fine for me too on the dev branch. @praveendvd checkout to the dev branch.
> > > ```
> > > git checkout dev
> > > docker-compose build
> > > cp dojo/settings/settings.dist.py dojo/settings/settings.py
> > > docker/setEnv.sh dev
> > > docker-compose up ```
> > > 
> > > before running these commands remove all old images.
> > > ```
> > 
> > 
> > @dr3dd589 @devEricA @devGregA
> > Hi , I cloned the latest code from git and ran the docker. Now the upload is working from UI but not through API.
> > Below is the python code i used for uploading the scan results
> > **Note:** The defect dojo api package is the latest one available in the git. i pulled the code and installed through ' python setup.py develop'.
> > ```
> > #!/usr/bin/python
> > 
> > #import the package
> > from defectdojo_api import defectdojo
> > import os
> > 
> > #setup DefectDojo connection information
> > host = 'http://localhost:8000'
> > api_key = '<Provide_API>''
> > user = 'admin'
> > 
> > 
> > #instantiate the DefectDojo api wrapper
> > dd = defectdojo.DefectDojoAPI(host, api_key, user, debug=False)
> > 
> > 
> > print dd.upload_scan(1,"Snyk Scan", "<file_path>/snyk.json", "True", "2019-08-08")
> > ```
> > 
> > 
> > Could you please guide me here, is it issue with pytho api
> > how to try this manually , what would be the payload. How to try the same using rest-client or postman.
> 
> Hi i was able to check the same using postman, and it throws the same error, @devGregA @devEricA @dr3dd589
> 
> ![image](https://user-images.githubusercontent.com/45095911/62149670-2ee47800-b2f4-11e9-8bab-cec98c118681.png)

Hi team dev branch is working , master branch had the issue. Thank you for the help @devGregA @devEricA @dr3dd589
