### ISSUE TITLE
Unsupported OS error on Defectdojo installation in CentOS 7 through setup.bash

### ISSUE THREAD

**Issue by praveendvd** [DefectDojo/django-DefectDojo#1433]
**Bug description**

On trying to install defectDojo using setup.bash in CentOS 7, the user is getting unsupported OS error

**Steps to reproduce**

1. Download latest RC candidate
2. Extract the zip
3. Navigate to extracted folder
4. Run ./setup.py
5. Give all the required input
6. Gets unsupported OS error

**Expected behavior**

Should install successfully

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [X] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [CentOS Linux release 7.6.1810 (Core)  ]
 - DefectDojo version: [1.5.4rc5]

**Screenshots** (optional)

![image](https://user-images.githubusercontent.com/45095911/62063586-08a2d780-b223-11e9-8967-02e975bbe61b.png)

**Comment by Maffooch** [comment]
Hey @praveendvd Have you tried the setup.bash script [here](https://github.com/DefectDojo/django-DefectDojo/tree/master/setup)? It is the current one. Not exactly sure why we have two. Very confusing. If that does not work, I recommend using the [docker-compose](https://github.com/DefectDojo/django-DefectDojo/blob/master/DOCKER.md) install option. 

Good luck!

**Comment by praveendvd** [comment]
> Hey @praveendvd Have you tried the setup.bash script [here](https://github.com/DefectDojo/django-DefectDojo/tree/master/setup)? It is the current one. Not exactly sure why we have two. Very confusing. If that does not work, I recommend using the [docker-compose](https://github.com/DefectDojo/django-DefectDojo/blob/master/DOCKER.md) install option.
> 
> Good luck!

![image](https://user-images.githubusercontent.com/45095911/62080544-cb514080-b248-11e9-8322-da2078a512a9.png)


I am getting the same error in a much more visually appealing way 💃 

@Maffooch I tried docker-compose, but I am getting no Package 'MySQL-client'.

**Comment by Maffooch** [comment]
@praveendvd I don't know anything about CentOS besides its a distro of Linux. I know @ptrovatelli has gotten it working though. Maybe he has some pointers for you.

**Comment by ptrovatelli** [comment]
nope sorry i'v always used docker only :) . On centos host but docker-based 
I thought only ubuntu was supported but i couldn't find this limitation in the doc anymore. 
I'm not sure what's the status on this setup.bash install actually; i have seen messages on slack like a month back saying it worked for python3 (from @mtesauro I think?) but the readthedoc still states that it's deprecated and shouln't be used and the README.MD on dev branch doesn't even mention it.

**Comment by praveendvd** [comment]
> @praveendvd I don't know anything about CentOS besides its a distro of Linux. I know @ptrovatelli has gotten it working though. Maybe he has some pointers for you.



> nope sorry i'v always used docker only :) . On centos host but docker-based
> I thought only ubuntu was supported but i couldn't find this limitation in the doc anymore.
> I'm not sure what's the status on this setup.bash install actually; i have seen messages on slack like a month back saying it worked for python3 (from @mtesauro I think?) but the readthedoc still states that it's deprecated and shouln't be used and the README.MD on dev branch doesn't even mention it.

@ptrovatelli  @Maffooch Thank you so much for looking into this, could you guys guide me how to use docker-compose , i was able to start the docker using docker-compose up . But have no clue whats the username and password.

**Comment by Maffooch** [comment]
@praveendvd That I can help with! Username and password are set by the initializer container. The username defaults to admin, and the password is randomly generated. You've got two options here. 

1. Find the generated password with the following command:
``container_id=(`docker ps -a \
--filter "name=django-defectdojo_initializer_1" \
| awk 'FNR == 2 {print $1}'`) && \
docker logs $container_id 2>&1 | grep "Admin password:"``
2. Change the password to something you can remember:
There is a good procedure [here](https://github.com/DefectDojo/django-DefectDojo/issues/1409).

Let us know if you run into any difficulties.

**Comment by praveendvd** [comment]
> @praveendvd That I can help with! Username and password are set by the initializer container. The username defaults to admin, and the password is randomly generated. You've got two options here.
> 
> 1. Find the generated password with the following command:
>    `` container_id=(`docker ps -a \ --filter "name=django-defectdojo_initializer_1" \ | awk 'FNR == 2 {print $1}'`) && \ docker logs $container_id 2>&1 | grep "Admin password:" ``
> 2. Change the password to something you can remember:
>    There is a good procedure [here](https://github.com/DefectDojo/django-DefectDojo/issues/1409).
> 
> Let us know if you run into any difficulties.

Perfect!!! it worked like a charm.   

Just to mention, I was not able to build the docker image using "**sudo docker-compose build**", it was having many issues like no mysqlclient module, no djange etc. 

So I stopped all containers using ( **sudo docker stop $(sudo docker ps -aq** )

deleted all images using ( **sudo docker system prune -a** )

Then used ( **sudo docker-compose up** ) directly without using docker-compose build.

After that, I followed the link you mentioned to change the password. Everything is working fine now,

Good day ahead @Maffooch @ptrovatelli  you saved my life 👍

**Comment by Maffooch** [comment]
@praveendvd Glad you've got it straightened out. Since you're basing this from dockerhub, I'm not sure this will matter to you or not, but not building the current code base forces docker-compose up to pull the latest release from docker-hub. In short, any changes you make to the code base will not be reflected in the running instance. More info on this can be found in the DOCKER.md.
