### ISSUE TITLE
Retirejs scans not getting uploaded 

### ISSUE THREAD

**Issue by praveendvd** [DefectDojo/django-DefectDojo#1438]
**Bug description**

Uploading retirejs scan results throws Unicode-objects must be encoded before hashing 

**Steps to reproduce**

1. Goto Egagements
2. Upload the Retirejs scan result
3. Throws unicode erro

**Expected behavior**

File should parse successfully

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**

 - Operating System:  [CentOS Linux release 7.6.1810 (Core) ]
 - DefectDojo version: [908118a: Merge pull request #1412 from Maffooch/dev [2019-07-30 08:47:59 -0500]]

**Sample scan files** (optional)

[result.zip](https://github.com/DefectDojo/django-DefectDojo/files/3451352/result.zip)

**Screenshots** (optional)

![image](https://user-images.githubusercontent.com/45095911/62206469-cb0c8e80-b389-11e9-8215-fe9264cc3c5a.png)

**Comment by Maffooch** [comment]
@devEricA Could you verify and correct? Thanks.

**Comment by devEricA** [comment]
Fix is done, just awaiting it to be pushed. While I am at it, @praveendvd do you mind if we add your scan to our Sample Scan repository? The reason I ask is because our sample scan for Retire.js hasn't been working for a long time, so I tailored the fix around yours.

**Comment by praveendvd** [comment]
> Fix is done, just awaiting it to be pushed. While I am at it, @praveendvd do you mind if we add your scan to our Sample Scan repository? The reason I ask is because our sample scan for Retire.js hasn't been working for a long time, so I tailored the fix around yours.

Perfect , you can use that report . It doesn't contain any sensitive information as I used OWASP juice shop as the target. Thank you so much for working on this

**Comment by praveendvd** [comment]
@Maffooch  In which commit does this fix available ? or is it yet to be pushed ?

**Comment by praveendvd** [comment]
I am getting invalid format error in the latest dev commit: 68339f6: Merge pull request #1449 from Maffooch/dev [2019-08-05 11:02:03 -0500]



![image](https://user-images.githubusercontent.com/45095911/62538577-0e17a780-b84b-11e9-8fa2-01c9682fa222.png)

**Comment by praveendvd** [comment]
@devEricA Thank you guys for looking into this, please let me know if i am on wrong commit

**Comment by Maffooch** [comment]
@praveendvd So there was a couple issues. At some point, all JSON based parser were broken in the way that raised the exception that you're getting. Not sure when it happened or what broke them though. That was fixed [here](https://github.com/DefectDojo/django-DefectDojo/pull/1449). The fix motivated from your issue was resolved somewhere in [here](https://github.com/DefectDojo/django-DefectDojo/pull/1437). I apologize for the confusion!
