### ISSUE TITLE
JIRA Closed issue status is not updated in DefectDojo

### ISSUE THREAD

**Issue by tkr6743** [DefectDojo/django-DefectDojo#1441]
Dear Team,

We have successfully push finding into jira but when we close the issue in jira, the status is not updated in DefectDojo

Thanks,
Kondal

**Comment by praveendvd** [comment]
@tkr6743  Could you help me with pushing defect dojo issues to Jira.  How did you do that

**Comment by Maffooch** [comment]
Hey @tkr6743 Check out #1419 It sounds like it might work for you.
