### ISSUE TITLE
Issues deploying DefectDojo using Docker compose strategy

### ISSUE THREAD

**Issue by MatteoMori** [DefectDojo/django-DefectDojo#1442]
**Bug description**
Hello guys, 
Apologies for disturbing you but I am having some troubles deploying DefectDojo using docker-compose.

I have basically fetched the repository and followed what described in the main README file. However I keep having the following issue:
```
# docker-compose build

Traceback (most recent call last):
  File "/bin/docker-compose", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 71, in main
    command()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 124, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 42, in project_from_options
    compatibility=options.get('--compatibility'),
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 123, in get_project
    host=host, environment=environment
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 94, in get_client
    environment=environment, tls_version=get_tls_version(environment)
  File "/usr/lib/python2.7/site-packages/compose/cli/docker_client.py", line 127, in docker_client
    client = APIClient(**kwargs)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 128, in __init__
    config_dict=self._general_configs, credstore_env=credstore_env,
TypeError: load_config() got an unexpected keyword argument 'config_dict'
```

Am I doing something stupid here?

**Steps to reproduce**
```
git clone https://github.com/DefectDojo/django-DefectDojo.git
cd django-DefectDojo/
docker-compose build
```

**Expected behavior**
As per documentation, I expect the containers to start building

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ X ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: 
    RHEL 7.6
 ```
docker version

Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-102.git7f2769b.el7.x86_64
 Go version:      go1.10.8
 Git commit:      7f2769b/1.13.1
 Built:           Thu Jul 11 09:14:01 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-102.git7f2769b.el7.x86_64
 Go version:      go1.10.8
 Git commit:      7f2769b/1.13.1
 Built:           Thu Jul 11 09:14:01 2019
 OS/Arch:         linux/amd64
 Experimental:    false
 ```

```
docker-compose version

docker-compose version 1.24.1, build 4667896
docker-py version: 3.7.3
CPython version: 2.7.5
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017
```

 - DefectDojo version: [use `git show -s --format="%h: %s [%ci]"`]
```
git show -s --format="%h: %s [%ci]"

9e850dc: Merge pull request #1413 from piyarathnalakmali/bug-ReImportscan [2019-07-31 15:06:45 -0500]

git branch

* master
```

Thank you guys,

Matteo

**Comment by MatteoMori** [comment]
I am sure it does not make any difference but I have also tried to install `docker ce` just in case:

```
 docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:07 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

However it keeps failing with the same output

**Comment by praveendvd** [comment]
even 97261ad: Merge pull request #1420 from dr3dd589/fix_permission [2019-07-31 13:08:52 -0500] dev branch is  failing but with importError: for Celery

![image](https://user-images.githubusercontent.com/45095911/62287357-9d8b1800-b451-11e9-8093-de6bde5af6a8.png)

**Comment by praveendvd** [comment]
> **Bug description**
> Hello guys,
> Apologies for disturbing you but I am having some troubles deploying DefectDojo using docker-compose.
> 
> I have basically fetched the repository and followed what described in the main README file. However I keep having the following issue:
> 
> ```
> # docker-compose build
> 
> Traceback (most recent call last):
>   File "/bin/docker-compose", line 10, in <module>
>     sys.exit(main())
>   File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 71, in main
>     command()
>   File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 124, in perform_command
>     project = project_from_options('.', options)
>   File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 42, in project_from_options
>     compatibility=options.get('--compatibility'),
>   File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 123, in get_project
>     host=host, environment=environment
>   File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 94, in get_client
>     environment=environment, tls_version=get_tls_version(environment)
>   File "/usr/lib/python2.7/site-packages/compose/cli/docker_client.py", line 127, in docker_client
>     client = APIClient(**kwargs)
>   File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 128, in __init__
>     config_dict=self._general_configs, credstore_env=credstore_env,
> TypeError: load_config() got an unexpected keyword argument 'config_dict'
> ```
> 
> Am I doing something stupid here?
> 
> **Steps to reproduce**
> 
> ```
> git clone https://github.com/DefectDojo/django-DefectDojo.git
> cd django-DefectDojo/
> docker-compose build
> ```
> 
> **Expected behavior**
> As per documentation, I expect the containers to start building
> 
> **Deployment method** _(select with an `X`)_
> 
> * [ ]  Kubernetes
> * [ X ] Docker
> * [ ]  setup.bash / legacy-setup.bash
> 
> **Environment information**
> 
> * Operating System:
>   RHEL 7.6
> 
> ```
> docker version
> 
> Client:
> Version:         1.13.1
> API version:     1.26
> Package version: docker-1.13.1-102.git7f2769b.el7.x86_64
> Go version:      go1.10.8
> Git commit:      7f2769b/1.13.1
> Built:           Thu Jul 11 09:14:01 2019
> OS/Arch:         linux/amd64
> 
> Server:
> Version:         1.13.1
> API version:     1.26 (minimum version 1.12)
> Package version: docker-1.13.1-102.git7f2769b.el7.x86_64
> Go version:      go1.10.8
> Git commit:      7f2769b/1.13.1
> Built:           Thu Jul 11 09:14:01 2019
> OS/Arch:         linux/amd64
> Experimental:    false
> ```
> 
> ```
> docker-compose version
> 
> docker-compose version 1.24.1, build 4667896
> docker-py version: 3.7.3
> CPython version: 2.7.5
> OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017
> ```
> 
> * DefectDojo version: [use `git show -s --format="%h: %s [%ci]"`]
> 
> ```
> git show -s --format="%h: %s [%ci]"
> 
> 9e850dc: Merge pull request #1413 from piyarathnalakmali/bug-ReImportscan [2019-07-31 15:06:45 -0500]
> 
> git branch
> 
> * master
> ```
> 
> Thank you guys,
> 
> Matteo



> **Bug description**
> Hello guys,
> Apologies for disturbing you but I am having some troubles deploying DefectDojo using docker-compose.
> 
> I have basically fetched the repository and followed what described in the main README file. However I keep having the following issue:
> 
> ```
> # docker-compose build
> 
> Traceback (most recent call last):
>   File "/bin/docker-compose", line 10, in <module>
>     sys.exit(main())
>   File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 71, in main
>     command()
>   File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 124, in perform_command
>     project = project_from_options('.', options)
>   File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 42, in project_from_options
>     compatibility=options.get('--compatibility'),
>   File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 123, in get_project
>     host=host, environment=environment
>   File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 94, in get_client
>     environment=environment, tls_version=get_tls_version(environment)
>   File "/usr/lib/python2.7/site-packages/compose/cli/docker_client.py", line 127, in docker_client
>     client = APIClient(**kwargs)
>   File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 128, in __init__
>     config_dict=self._general_configs, credstore_env=credstore_env,
> TypeError: load_config() got an unexpected keyword argument 'config_dict'
> ```
> 
> Am I doing something stupid here?
> 
> **Steps to reproduce**
> 
> ```
> git clone https://github.com/DefectDojo/django-DefectDojo.git
> cd django-DefectDojo/
> docker-compose build
> ```
> 
> **Expected behavior**
> As per documentation, I expect the containers to start building
> 
> **Deployment method** _(select with an `X`)_
> 
> * [ ]  Kubernetes
> * [ X ] Docker
> * [ ]  setup.bash / legacy-setup.bash
> 
> **Environment information**
> 
> * Operating System:
>   RHEL 7.6
> 
> ```
> docker version
> 
> Client:
> Version:         1.13.1
> API version:     1.26
> Package version: docker-1.13.1-102.git7f2769b.el7.x86_64
> Go version:      go1.10.8
> Git commit:      7f2769b/1.13.1
> Built:           Thu Jul 11 09:14:01 2019
> OS/Arch:         linux/amd64
> 
> Server:
> Version:         1.13.1
> API version:     1.26 (minimum version 1.12)
> Package version: docker-1.13.1-102.git7f2769b.el7.x86_64
> Go version:      go1.10.8
> Git commit:      7f2769b/1.13.1
> Built:           Thu Jul 11 09:14:01 2019
> OS/Arch:         linux/amd64
> Experimental:    false
> ```
> 
> ```
> docker-compose version
> 
> docker-compose version 1.24.1, build 4667896
> docker-py version: 3.7.3
> CPython version: 2.7.5
> OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017
> ```
> 
> * DefectDojo version: [use `git show -s --format="%h: %s [%ci]"`]
> 
> ```
> git show -s --format="%h: %s [%ci]"
> 
> 9e850dc: Merge pull request #1413 from piyarathnalakmali/bug-ReImportscan [2019-07-31 15:06:45 -0500]
> 
> git branch
> 
> * master
> ```
> 
> Thank you guys,
> 
> Matteo

Hi @MatteoMori it is working fine in my system. Could you remove unused images and volumes and try again. ( use below steps only in non-production environment)

You can use below commands:

**sudo docker stop $(sudo docker ps -aq)** - stops all containers , **use only if you are not using any other containers than defect dojo**

else individually stop containers using

**sudo docker stop <conatiner_ID>** 

stop all the bellow containers ( use **'sudo docker ps -a**' to see all running containers)

![image](https://user-images.githubusercontent.com/45095911/62288762-fe681f80-b454-11e9-9be7-c5452cdb461c.png)

now use **docker system prune -a** to remove all unused and dangling images

now remove the volumes:

use '**sudo docker system prune --volumes**' to remove all volumes  ( use only in non production enviroment)

else remove individually using "**sudo docker volume ls**" and "**sudo docker volume rm <volume_name**"

and then try

**sudo docker-compose up**

**Comment by MatteoMori** [comment]
Hi!

Thank you very much for your help on this. I did follow your suggestions and try to run `docker-compose up` after having cleaned.

However I keep having issues:
```
docker-compose up

Creating network "django-defectdojo_default" with the default driver
Creating volume "django-defectdojo_defectdojo_data" with default driver
Pulling mysql (mysql:5.7)...
Trying to pull repository registry.access.redhat.com/mysql ...
Pulling repository registry.access.redhat.com/mysql
Trying to pull repository docker.io/library/mysql ...
5.7: Pulling from docker.io/library/mysql
0a4690c5d889: Pull complete
98aa2fc6cbeb: Pull complete
0777e6eb0e6f: Pull complete
2464189c041c: Pull complete
b45df9dc827d: Pull complete
b42b00086160: Pull complete
bb93567627c7: Pull complete
419b68a254a1: Pull complete
8c4bc5b87c07: Pull complete
59234e88c262: Pull complete
2406ac6e266f: Pull complete
Digest: sha256:540488d8f0e04c1077d17934d1c1511fe417e2221dff508ce4621f5efe6131db
Status: Downloaded newer image for docker.io/mysql:5.7
Pulling initializer (defectdojo/defectdojo-django:latest)...
Trying to pull repository registry.access.redhat.com/defectdojo/defectdojo-django ...
Pulling repository registry.access.redhat.com/defectdojo/defectdojo-django
Trying to pull repository docker.io/defectdojo/defectdojo-django ...
latest: Pulling from docker.io/defectdojo/defectdojo-django
743f2d6c1f65: Pull complete
9bfbedfce8de: Pull complete
7f4da2474cef: Pull complete
ffc893575679: Pull complete
82833fe30934: Pull complete
66ea24266a5c: Pull complete
1f89aff36df5: Pull complete
abb09910e713: Pull complete
d9a1c9fd1902: Pull complete
6467a7719476: Pull complete
6c6877d31d74: Pull complete
05a5f3414e3d: Pull complete
d952212d7572: Pull complete
e12c795fd789: Pull complete
abd9592b5085: Pull complete
8da37c534219: Pull complete
Digest: sha256:c539b89e5022d2b8a79bfe6bf16e342012197edec367f64ddd4460c039c9decd
Status: Downloaded newer image for docker.io/defectdojo/defectdojo-django:latest
Building nginx
Step 1/22 : FROM python:2 as build
ERROR: Service 'nginx' failed to build: Error parsing reference: "python:2 as build" is not a valid repository/tag: invalid reference format
``` 

and If I try to build:
```
docker-compose build

mysql uses an image, skipping
initializer uses an image, skipping
rabbitmq uses an image, skipping
celeryworker uses an image, skipping
celerybeat uses an image, skipping
Building uwsgi
Step 1/21 : FROM python:2 as build
ERROR: Service 'uwsgi' failed to build: Error parsing reference: "python:2 as build" is not a valid repository/tag: invalid reference format
```

**Comment by praveendvd** [comment]
@MatteoMori  try reinstalling your docker and docker compose ,

use the official document for installing and uninstalling, remove both docker-compose and docker engine, and then reInstall.

Your docker version was showing 1.13.1 which was released in 2017. the current version is 19 ( which you had in the docker-ce). the syntax ' FROM PYTHON:2 ' is supported only from versions > 17.06.

**Comment by praveendvd** [comment]
@MatteoMori

**Comment by praveendvd** [comment]
https://docs.docker.com/install/linux/docker-ce/centos/ 

Use this step , and install using yum

**Comment by MatteoMori** [comment]
Ahhh ok!

I tried and the application came up just fine. Thank you very much for your help on this!
