### ISSUE TITLE
Issues regarding dependency "pandas"

### ISSUE THREAD

**Issue by torgebauer** [DefectDojo/django-DefectDojo#1443]
Since the release of the new version of pandas (0.25.0) my docker image build runs into following issue:

```
Collecting pandas>=0.22.0 (from -r requirements.txt (line 76))
  Downloading https://files.pythonhosted.org/packages/0b/1f/8fca0e1b66a632b62cc1ae38e197befe48c5cee78f895edf4bf8d340454d/pandas-0.25.0.tar.gz (12.6MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-dB70lw/pandas/setup.py", line 21, in <module>
        import versioneer
      File "/tmp/pip-build-dB70lw/pandas/versioneer.py", line 1629
        print("Adding sample versioneer config to setup.cfg", file=sys.stderr)
                                                                  ^
    SyntaxError: invalid syntax
```
    

Please adjust the requirements.txt to a fixed version e.g. pandas==0.24.2.

Greetings

**Comment by Maffooch** [comment]
Hey @torgebauer that seems to new addition introduced in python3. The dev branch is currently running on python3, so it is not an issue over there.

**Comment by Maffooch** [comment]
I forgot the mention that fixes and changes in the dev branch will eventually make it to the master branch. In the meantime, feel free to modify your requirements.txt to resolve the syntax errors.
