### ISSUE TITLE
Broken importscan API v1

### ISSUE THREAD

**Issue by praveendvd** [DefectDojo/django-DefectDojo#1448]
**Bug description**

Cannot upload files using API v1

**Steps to reproduce**

1. Try uploading files using api
2. provide fields like engagement,scan_date,scan_type and file
3. Send post request
4. Import_parser_factory() error is thrown

**Expected behavior**

The file should get uploaded else server should return other required fields

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**

 - Operating System: [ CentOS 7]
 - DefectDojo version: [9e850dc: Merge pull request #1413 from piyarathnalakmali/bug-ReImportscan [2019-07-31 15:06:45 -0500]]

**Screenshots** (optional)

![image](https://user-images.githubusercontent.com/45095911/62379868-bb36ab00-b53f-11e9-9616-c1a3d2a045f7.png)

**Comment by Maffooch** [comment]
Hey @praveendvd I just realized the bug you found was on the master branch. This has since been fixed on the dev branch and will eventually make it to the master branch.
