### ISSUE TITLE
Server Error (500) - Issue review status change from "Close Finding" to "Not Fixed"

### ISSUE THREAD

**Issue by parag85** [DefectDojo/django-DefectDojo#1456]
**Bug description**
Post changing Issue review status from Closed Finding to Not Fixed, server error (500) error page comes.

**Steps to reproduce**
1. Go to Edit Issue page
2. Select "Under defect review" checkbox
3. Click on Finished button
4. Click on  [Review Finding for Closure] button
5. Add note
6. Select "Not Fixed" value from "Defect Choice" dropdown
7. Click on Finished button
8. "Server Error (500)" error page received

**Expected behaviour**
Issue status should change to "Not Fixed" status

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 18.04.2 LTS
 - DefectDojo version: Latest from Docker

**Screenshots** (optional)
![image](https://user-images.githubusercontent.com/8840359/62514592-529c4680-b83d-11e9-866f-58a302502ac5.png)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.
![image](https://user-images.githubusercontent.com/8840359/62514831-056ca480-b83e-11e9-9998-9dfedbb66fe9.png)

nginx_1         | 49.206.8.226 - - [06/Aug/2019:06:02:08 +0000] "GET /alerts/count HTTP/1.1" 200 13 "http://IP_ADD/finding/56/defect_review" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36" "-"
uwsgi_1         | [pid: 1|app: 0|req: 22592/22592] 49.206.8.226 () {44 vars in 837 bytes} [Tue Aug  6 06:02:08 2019] GET /alerts/count => generated 13 bytes in 10 msecs (HTTP/1.1 200) 4 headers in 114 bytes (1 switches on core 0)
uwsgi_1         | Internal Server Error: /finding/56/defect_review
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
uwsgi_1         |     response = self._get_response(request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
uwsgi_1         |     return view_func(request, *args, **kwargs)
uwsgi_1         |   File "./dojo/finding/views.py", line 365, in defect_finding_review
uwsgi_1         |     j_issue = JIRA_Issue.objects.get(finding=finding)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
uwsgi_1         |     return getattr(self.get_queryset(), name)(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 380, in get
uwsgi_1         |     self.model._meta.object_name
uwsgi_1         | DoesNotExist: JIRA_Issue matching query does not exist.
nginx_1         | 49.206.8.226 - - [06/Aug/2019:06:02:15 +0000] "POST /finding/56/defect_review HTTP/1.1" 500 27 "http://IP_ADD/finding/56/defect_review" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36" "-"
uwsgi_1         | [pid: 1|app: 0|req: 22593/22593] 49.206.8.226 () {52 vars in 1158 bytes} [Tue Aug  6 06:02:15 2019] POST /finding/56/defect_review => generated 27 bytes in 76 msecs (HTTP/1.1 500) 4 headers in 126 bytes (1 switches on core 0)

**Comment by dr3dd589** [comment]
hello, @parag85 I think you are using the master branch. It is working fine in the dev branch. it will be fixed in the next release. or you can use dev branch.

**Comment by parag85** [comment]
Can you help me how to upgrade my docker to latest one, so will get the latest update for my defectdojo env.

**Comment by dr3dd589** [comment]
there is doc how to install the development version of Defectdojo [here](https://github.com/DefectDojo/django-DefectDojo/blob/master/DOCKER.md)

note: on installing new one first remove old Defectdojo containers and volume.

**Comment by parag85** [comment]
What about Data which are already there?
