### ISSUE TITLE
Snyk report not getting uploaded

### ISSUE THREAD

**Issue by praveendvd** [DefectDojo/django-DefectDojo#1457]
**Bug description**

gets invalid format error on uploading snyk json report

**Steps to reproduce**

1. Go to Engagement
2. Import Snyk report
3. Invalid format error is thrown

**Expected behavior**

It should upload successfully 

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [CentOS 7]
 - DefectDojo version: 68339f6: Merge pull request #1449 from Maffooch/dev [2019-08-05 11:02:03 -0500]

**Sample scan files** 

[text.json.zip](https://github.com/DefectDojo/django-DefectDojo/files/3472063/text.json.zip)

**Screenshots** 

![image](https://user-images.githubusercontent.com/45095911/62538273-4c609700-b84a-11e9-9f0b-35815286c9a9.png)

**Comment by dr3dd589** [comment]
hey, @praveendvd  your sample works fine on my system. ( docker + dev branch)

![synk](https://user-images.githubusercontent.com/31597172/62549062-75524d80-b885-11e9-8881-273219a35ce0.png)

**Comment by praveendvd** [comment]
> hey, @praveendvd your sample works fine on my system. ( docker + dev branch)
> 
> ![synk](https://user-images.githubusercontent.com/31597172/62549062-75524d80-b885-11e9-8881-273219a35ce0.png)

Hi , I am still getting the same error. Could you try removing all the images and volumes , and try again

**Comment by Maffooch** [comment]
Hey @praveendvd something broke all JSON based parsers at some point. The fix was made [here](https://github.com/DefectDojo/django-DefectDojo/pull/1449).

**Comment by dr3dd589** [comment]
yes, @praveendvd  you are right it's not fixed yet. I can reproduce this now. @Maffooch it raises exception error now.

**Comment by Maffooch** [comment]
@dr3dd589 Shoot me. Would you mind looking into it? Maybe it is other parsers as well?

**Comment by dr3dd589** [comment]
yes, I'm getting this error in all JSON support parsers.

**Comment by Maffooch** [comment]
Hmm. Something is not right here...

**Comment by Maffooch** [comment]
Hey @praveendvd Im pretty sure this time around was the fix. Would you mind testing it out? PR #1467

**Comment by praveendvd** [comment]
> Hey @praveendvd Im pretty sure this time around was the fix. Would you mind testing it out? PR #1467

I am at 342b90c: Merge pull request #1460 from devEricA/Bulk_Edit_filters [2019-08-08 15:03:24 -0500]

and still faces the same issue.

![image](https://user-images.githubusercontent.com/45095911/62790252-9a7fcf80-bac2-11e9-8387-8063fc032f41.png)

**Comment by Maffooch** [comment]
@praveendvd PR #1467 has not been merged yet. Checkout the branch and try it. This may be of help https://help.github.com/en/articles/checking-out-pull-requests-locally

**Comment by praveendvd** [comment]
> @praveendvd PR #1467 has not been merged yet. Checkout the branch and try it. This may be of help https://help.github.com/en/articles/checking-out-pull-requests-locally

Thank you so much its working fine , but the retire Js upload fails again. Should I raise a bug or comment on the closed #1438 

![image](https://user-images.githubusercontent.com/45095911/62809301-6f14d900-baf2-11e9-84b8-4f674e423fa9.png)

**Comment by Maffooch** [comment]
@praveendvd I'll look into it right now and create a new PR. Are you still using the report that was in your initial issue about retire.js?

**Comment by praveendvd** [comment]
> @praveendvd I'll look into it right now and create a new PR. Are you still using the report that was in your initial issue about retire.js?
@Maffooch Thanks for pointing out that, the old json is working fine. I will just triage my new report and see if its issue from my side or not. Thank you for that

**Comment by Maffooch** [comment]
@praveendvd Hmm. If it doesn't work, would you mind sending me the broken file so that the parser could be improved?

**Comment by praveendvd** [comment]
> @praveendvd Hmm. If it doesn't work, would you mind sending me the broken file so that the parser could be improved?


[RetireResults.json.tar.gz](https://github.com/DefectDojo/django-DefectDojo/files/3488083/RetireResults.json.tar.gz)

Sure @Maffooch ,

**Comment by Maffooch** [comment]
@praveendvd Thank you so much! They appear to be different versions. Ill have something for you by the end of the day Monday.

**Comment by praveendvd** [comment]
> @praveendvd Thank you so much! They appear to be different versions. Ill have something for you by the end of the day Monday.

Thank you so much @Maffooch for your effort and help, please do let me know if you would be needing anything else.  Happy friday, :)

**Comment by Maffooch** [comment]
Hey @praveendvd I forgot I will be out for some of Monday, so I fixed the issue today. Checkout #1481 to see the fixes. Would you allow me to include the new scan file in the sample-scan repo for future testing?

**Comment by praveendvd** [comment]
> Hey @praveendvd I forgot I will be out for some of Monday, so I fixed the issue today. Checkout #1481 to see the fixes. Would you allow me to include the new scan file in the sample-scan repo for future testing?

Hi @Maffooch  i verified the fix and its working perfectly thank you so much for looking into this , that too on a weekend. Enjoy your vacation and feel free to use the scan report as sample.
