### ISSUE TITLE
Github Issue Support

### ISSUE THREAD

**Issue by devGregA** [DefectDojo/django-DefectDojo#146]
### Make sure you assign this issue to yourself so folks do not duplicate effort.

To complete this issue, Dojo users should be able to auto-push to github issues similar to how the current JIRA integration works.

Implementation Requirements:

- [ ] Create a model that holds a Github URL and has a foreign key as a Product.
- [ ] Add a checkbox to the create finding view that will allow a Dojo user to push an issue to github.
- [ ] Update the issue in github as it is updated in dojo, description, status, etc.
- [ ] Have a toggle-able option to accept changes from github
- _this is for folks who either want Dojo to update automatically or want Dojo to always be the source of truth_
- [ ] Add documentation to the /docs folder.

Resources:
Github's developer guide:  https://developer.github.com/v3/issues/

**Comment by aaronweaver** [comment]
@devGregA What's this one about? Integrating Dojo with Github like Jira?

**Comment by devGregA** [comment]
Yes, that's correct. More info for anyone interested https://developer.github.com/v3/issues/

**Comment by rohithasrk** [comment]
Would like to work on it @devGregA

**Comment by devGregA** [comment]
Awesome @rohithasrk all yours! If you need any help, doesn't hesitate to ping me.
