### ISSUE TITLE
Issue importing a scan with more than one finding

### ISSUE THREAD

**Issue by bmiller2807** [DefectDojo/django-DefectDojo#1470]
**Bug description**
When i try to import a scan of a csv file containing more than 1 finding, it only imports 1 finding. I am not sure this is the expected behavior. 

**Steps to reproduce**
1. Go a products engagements screen 
2. Click on findings then import scan
3. Enter all the required information including the .csv file that contains the multiple findings, then click Upload File
4. Then i see the error:

Request Method: | POST
-- | --
http://10.32.36.18:8000/product/111/import_scan_results
1.11.11
ProgrammingError
(sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 140530616362752 and this is thread id 140530642048768 [SQL: u'SELECT kombu_queue.id AS kombu_queue_id, kombu_queue.name AS kombu_queue_name \nFROM kombu_queue \nWHERE kombu_queue.name = ?\n LIMIT ? OFFSET ?'] [parameters: [{}]] (Background on this error at: http://sqlalche.me/e/f405)
/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py in cursor, line 1027
/usr/bin/python
2.7.12
['/opt/django-DefectDojo',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages',  '/opt/django-DefectDojo']
Fri, 9 Aug 2019 14:43:13 -0400

**Expected behavior**
I expected to see that all findings in the .csv file to be listed as findings under a test , but only see 1 

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: RHEL
 - DefectDojo version: v2

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)
Date,Title,CweId,Url,Severity,Description,Mitigation,Impact,References,Active,Verified,FalsePositive,Duplicate
1/1/19,"CSVImportTest1",129,none,Critical,"This is the first finding","Remove first suspected SecureData from code","keep Nono stuff out of code",None,TRUE,TRUE,FALSE,FALSE
1/2/19,"CSVImportTest2",130,none,Critical,"This is the second finding","Remove second suspected SecureData from code","more Nono stuff found",None,TRUE,TRUE,FALSE,FALSE
1/3/19,"CSVImportTest3",131,none,Critical,"This is the third finding","Remove third suspected SecureData from code","even MORE Nono stuff found",None,TRUE,TRUE,FALSE,FALSE
1/3/19,"CSVImportTest4",131,none,Critical,"This is the fourth finding","Remove fourth suspected SecureData from code","even MORE Nono stuff found",None,TRUE,TRUE,FALSE,FALSE

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

**Comment by Maffooch** [comment]
Hey @bmiller2807 What scan type are you using? Also, is it safe to assume you're on the master branch? There is a new release coming in the near future to fix a lot of issues.

**Comment by bmiller2807** [comment]
> Hey @bmiller2807 What scan type are you using? Also, is it safe to assume you're on the master branch? There is a new release coming in the near future to fix a lot of issues.

I am using Generic Findings Report , the version we are using is v1.5.2

**Comment by Maffooch** [comment]
@bmiller2807 Oh goodness. This bug has been fixed quite some time ago. I recommend upgrading either to the current master branch or the dev branch. A new release is coming soon to update the python3 and Django 2.2 so updating to dev may be in your best interest.

**Comment by bmiller2807** [comment]
> @bmiller2807 Oh goodness. This bug has been fixed quite some time ago. I recommend upgrading either to the current master branch or the dev branch. A new release is coming soon to update the python3 and Django 2.2 so updating to dev may be in your best interest.

@Maffooch Thank you ... and Agreed .. we will check out the dev branch... Can you advise if accessing Custom Fields via the API is in the latest as well ?

**Comment by Maffooch** [comment]
@bmiller2807 Im not sure. I don't really use the API unless I have to. May just have to test it and find out :)
