### ISSUE TITLE
apt get update failes in Docker Image

### ISSUE THREAD

**Issue by wurstbrot** [DefectDojo/django-DefectDojo#1527]
Hi,

besides that the release label "python3" is not nice, the docker images are not getting build. Maybe because of  errors in travis https://travis-ci.org/DefectDojo/django-DefectDojo/builds/576885586 .
-> Docker Images are not getting build
Cheers,
Timo

**Comment by Miradorn** [comment]
update: `apt-get update` causes the problem,see https://travis-ci.org/DefectDojo/django-DefectDojo/jobs/576880722

**Comment by ptrovatelli** [comment]
I do not replicate
if you're still seeing it, does this fix it? 
`apt -o Acquire::https::No-Cache=True -o Acquire::http::No-Cache=True update`

ref: https://github.com/nodesource/distributions/issues/500, https://askubuntu.com/questions/751801/apt-update-fails-writing-more-data-than-expected

**Comment by wurstbrot** [comment]
works for locally, also. But on travis it might still be an issue.
