### ISSUE TITLE
Sort  "Product List" by amount of Vulnerabilities

### ISSUE THREAD

**Issue by xthk** [DefectDojo/django-DefectDojo#1535]
**Is your feature request related to a problem? Please describe**

There might be "products" with many open vulnerabilities, I'd like to address those on a different level.

**Describe the solution you'd like**

As a user I'd like to sort the "Product List" by the amount of open vulnerabilities. The data is already shown in the table, but the table could not be sorted.

**Describe alternatives you've considered**

None.

**Additional context**

- https://defectdojo.herokuapp.com/product

**Comment by dougmorato** [comment]
This might be solved by my Pull Request #1586 

If it doesn't do what you expect when it's merged, let me know and I can tackle this

**Comment by Maffooch** [comment]
This is totally solved by #1586. Thanks for killing the fourth bird with a single stone!
