### ISSUE TITLE
Docker-compose up results in Server Error (500)

### ISSUE THREAD

**Issue by liketop** [DefectDojo/django-DefectDojo#1537]
**Bug description**
I try to get DefectDojo running. I did docker-compose build and then docker-compose up. 
After initialisation I tried to login on localhost:8080 but i got following error:

**Expected behavior**
No Server Error (500)

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 18.04
 - DefectDojo version: 33f60a42: Merge pull request #1508 from Maffooch/dedupe [2019-08-20 08:54:31 -0500]

**Console logs** (optional)

`uwsgi_1         | Popen(['git', 'version'], cwd=/app, universal_newlines=False, shell=None, istream=None)
uwsgi_1         | Popen(['git', 'version'], cwd=/app, universal_newlines=False, shell=None, istream=None)
uwsgi_1         | [pid: 1|app: 0|req: 1/1] 172.19.0.1 () {50 vars in 894 bytes} [Tue Sep  3 05:36:01 2019] GET / => generated 0 bytes in 1132 msecs (HTTP/1.1 302) 5 headers in 149 bytes (1 switches on core 0)
nginx_1         | 172.19.0.1 - - [03/Sep/2019:05:36:03 +0000] "GET / HTTP/1.1" 302 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
uwsgi_1         | Internal Server Error: /login
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
uwsgi_1         |     return self.cursor.execute(sql, params)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
uwsgi_1         |     return self.cursor.execute(query, args)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 206, in execute
uwsgi_1         |     res = self._query(query)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 312, in _query
uwsgi_1         |     db.query(q)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/connections.py", line 224, in query
uwsgi_1         |     _mysql.connection.query(self, query)
uwsgi_1         | MySQLdb._exceptions.ProgrammingError: (1146, "Table 'defectdojo.django_site' doesn't exist")
uwsgi_1         | 
uwsgi_1         | The above exception was the direct cause of the following exception:
uwsgi_1         | 
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
uwsgi_1         |     return self.dispatch(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py", line 45, in _wrapper
uwsgi_1         |     return bound_method(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
uwsgi_1         |     return view(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py", line 45, in _wrapper
uwsgi_1         |     return bound_method(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
uwsgi_1         |     response = view_func(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py", line 45, in _wrapper
uwsgi_1         |     return bound_method(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
uwsgi_1         |     response = view_func(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/views.py", line 61, in dispatch
uwsgi_1         |     return super().dispatch(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 97, in dispatch
uwsgi_1         |     return handler(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/views/generic/edit.py", line 133, in get
uwsgi_1         |     return self.render_to_response(self.get_context_data())
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/views.py", line 95, in get_context_data
uwsgi_1         |     current_site = get_current_site(self.request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/contrib/sites/shortcuts.py", line 13, in get_current_site
uwsgi_1         |     return Site.objects.get_current(request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/contrib/sites/models.py", line 58, in get_current
uwsgi_1         |     return self._get_site_by_id(site_id)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/contrib/sites/models.py", line 30, in _get_site_by_id
uwsgi_1         |     site = self.get(pk=site_id)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
uwsgi_1         |     return getattr(self.get_queryset(), name)(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 402, in get
uwsgi_1         |     num = len(clone)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 256, in __len__
uwsgi_1         |     self._fetch_all()
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1242, in _fetch_all
uwsgi_1         |     self._result_cache = list(self._iterable_class(self))
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 55, in __iter__
uwsgi_1         |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
uwsgi_1         |     cursor.execute(sql, params)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 67, in execute
uwsgi_1         |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
uwsgi_1         |     return executor(sql, params, many, context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
uwsgi_1         |     return self.cursor.execute(sql, params)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
uwsgi_1         |     raise dj_exc_value.with_traceback(traceback) from exc_value
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
uwsgi_1         |     return self.cursor.execute(sql, params)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
uwsgi_1         |     return self.cursor.execute(query, args)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 206, in execute
uwsgi_1         |     res = self._query(query)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 312, in _query
uwsgi_1         |     db.query(q)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/connections.py", line 224, in query
uwsgi_1         |     _mysql.connection.query(self, query)
uwsgi_1         | django.db.utils.ProgrammingError: (1146, "Table 'defectdojo.django_site' doesn't exist")
uwsgi_1         | [pid: 1|app: 0|req: 2/2] 172.19.0.1 () {50 vars in 917 bytes} [Tue Sep  3 05:36:03 2019] GET /login?next=/ => generated 27 bytes in 94 msecs (HTTP/1.1 500) 4 headers in 126 bytes (1 switches on core 0)
nginx_1         | 172.19.0.1 - - [03/Sep/2019:05:36:03 +0000] "GET /login?next=/ HTTP/1.1" 500 27 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
uwsgi_1         | [pid: 1|app: 0|req: 3/3] 172.19.0.1 () {48 vars in 833 bytes} [Tue Sep  3 05:36:03 2019] GET /favicon.ico => generated 0 bytes in 35 msecs (HTTP/1.1 302) 5 headers in 160 bytes (1 switches on core 0)
nginx_1         | 172.19.0.1 - - [03/Sep/2019:05:36:03 +0000] "GET /favicon.ico HTTP/1.1" 302 0 "http://localhost:8080/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
uwsgi_1         | Internal Server Error: /login
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
uwsgi_1         |     return self.cursor.execute(sql, params)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
uwsgi_1         |     return self.cursor.execute(query, args)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 206, in execute
uwsgi_1         |     res = self._query(query)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 312, in _query
uwsgi_1         |     db.query(q)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/connections.py", line 224, in query
uwsgi_1         |     _mysql.connection.query(self, query)
uwsgi_1         | MySQLdb._exceptions.ProgrammingError: (1146, "Table 'defectdojo.django_site' doesn't exist")
uwsgi_1         | 
uwsgi_1         | The above exception was the direct cause of the following exception:
uwsgi_1         | 
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
uwsgi_1         |     return self.dispatch(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py", line 45, in _wrapper
uwsgi_1         |     return bound_method(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
uwsgi_1         |     return view(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py", line 45, in _wrapper
uwsgi_1         |     return bound_method(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
uwsgi_1         |     response = view_func(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py", line 45, in _wrapper
uwsgi_1         |     return bound_method(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
uwsgi_1         |     response = view_func(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/views.py", line 61, in dispatch
uwsgi_1         |     return super().dispatch(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 97, in dispatch
uwsgi_1         |     return handler(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/views/generic/edit.py", line 133, in get
uwsgi_1         |     return self.render_to_response(self.get_context_data())
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/views.py", line 95, in get_context_data
uwsgi_1         |     current_site = get_current_site(self.request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/contrib/sites/shortcuts.py", line 13, in get_current_site
uwsgi_1         |     return Site.objects.get_current(request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/contrib/sites/models.py", line 58, in get_current
uwsgi_1         |     return self._get_site_by_id(site_id)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/contrib/sites/models.py", line 30, in _get_site_by_id
uwsgi_1         |     site = self.get(pk=site_id)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
uwsgi_1         |     return getattr(self.get_queryset(), name)(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 402, in get
uwsgi_1         |     num = len(clone)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 256, in __len__
uwsgi_1         |     self._fetch_all()
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1242, in _fetch_all
uwsgi_1         |     self._result_cache = list(self._iterable_class(self))
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 55, in __iter__
uwsgi_1         |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
uwsgi_1         |     cursor.execute(sql, params)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 67, in execute
uwsgi_1         |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
uwsgi_1         |     return executor(sql, params, many, context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
uwsgi_1         |     return self.cursor.execute(sql, params)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
uwsgi_1         |     raise dj_exc_value.with_traceback(traceback) from exc_value
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
uwsgi_1         |     return self.cursor.execute(sql, params)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
uwsgi_1         |     return self.cursor.execute(query, args)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 206, in execute
uwsgi_1         |     res = self._query(query)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 312, in _query
uwsgi_1         |     db.query(q)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/connections.py", line 224, in query
uwsgi_1         |     _mysql.connection.query(self, query)
uwsgi_1         | django.db.utils.ProgrammingError: (1146, "Table 'defectdojo.django_site' doesn't exist")
nginx_1         | 172.19.0.1 - - [03/Sep/2019:05:36:03 +0000] "GET /login?next=/favicon.ico HTTP/1.1" 500 27 "http://localhost:8080/login?next=/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
uwsgi_1         | [pid: 1|app: 0|req: 4/4] 172.19.0.1 () {48 vars in 856 bytes} [Tue Sep  3 05:36:03 2019] GET /login?next=/favicon.ico => generated 27 bytes in 138 msecs (HTTP/1.1 500) 4 headers in 126 bytes (1 switches on core 0)
`

**Comment by wurstbrot** [comment]
full_calender version might be wrong and is fixed in develop, already.

**Comment by Maffooch** [comment]
Additionally, it looks some of your migrations did not run properly. Run `python3 manage.py migrate` to make everything run manually.
