### ISSUE TITLE
New line not respected in the note form

### ISSUE THREAD

**Issue by Wadeck** [DefectDojo/django-DefectDojo#1546]
**Bug description**
When creating/editing a note (private or public), the newlines entered in the textarea are not kept in the display view. If you edit the note again, you will see them. Seems like a simple "nl2br" filter missing in the page.

**Steps to reproduce**
1. Go to any finding
2. Enter a multiline text in the note, save
3. The note is displayed in a one-line

**Expected behavior**
Even if markdown is not supported, I expect to have at least the new line being respected.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo version: commit cc958f2 + PR #1544 merged

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)
<details>

<summary>Value entered in the textarea</summary>

![Screenshot_2019-09-11_151547_001](https://user-images.githubusercontent.com/2662497/64700587-750e2900-d4a7-11e9-8ab8-812ef4dff9f2.png)

</details>
<details>

<summary>Value displayed after save</summary>

![Screenshot_2019-09-11_151600_001](https://user-images.githubusercontent.com/2662497/64700591-763f5600-d4a7-11e9-8f2b-7b73d83ec6a6.png)

</details>

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

FYI @madchap

**Comment by Maffooch** [comment]
Hey @Wadeck, I appended the fix for this issue to PR #1556. Check it out and let me know if you approve!

**Comment by Wadeck** [comment]
@Maffooch our version is not yet updated I imagine :) we got the first corrections but not the third one :)  cc @madchap
