### ISSUE TITLE
CVE regex too constraining

### ISSUE THREAD

**Issue by Wadeck** [DefectDojo/django-DefectDojo#1553]
**Bug description**
The CVE validation rules on the finding form is too constraining. When we receive CVEs from Sonatype or WhiteSource, they are not all in the expected public format CVE-XXXX-XXXxxxxx. Due to their internal nature, there is no way to provide a CVE regex that will cover everything.

It seems quite frequent to receive internal reference for reported stuff and thus the regex cannot be applied in every situation. Perhaps the regex could trigger a warning instead of an error or perhaps a javascript only warning could be sufficiant. It's especially annoying when we receive that error on an existing finding and thus we cannot modify it through the web UI.

**Steps to reproduce**
1. Go to a finding edit page
2. Change the CVE to something like WS-XXXX-YYYY
3. Click on save

**Expected behavior**

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo version: commit cc958f2 + PR #1544 merged

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)
![Screenshot_2019-09-12_153143_001](https://user-images.githubusercontent.com/2662497/64788451-c505f200-d572-11e9-826d-d8afa4cc49c9.png)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

FYI @madchap

**Comment by madchap** [comment]
Should be addressed by #1659
