### ISSUE TITLE
Tags not supported with "Table of Contents: yes"

### ISSUE THREAD

**Issue by Wadeck** [DefectDojo/django-DefectDojo#1555]
**Bug description**
When generating a report for a product or an engagement, the table of contents is "broken / glitched" when the findings have tags. In the screenshot, the findings contain only one "info", 2 critical and 6 high, but the list show all the "tagged" findings as info which is wrong but also dangerous in terms of "information display" / "wrong assumption".

**Steps to reproduce**
1. Go to report generation page for product / engagement
2. Put yes in the "Table of contents"
3. Generate

**Expected behavior**
The categorisation by severity should be respected for all findings.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo version: commit cc958f2 + PR #1544 merged

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)
<img width="710" alt="table_content - redacted" src="https://user-images.githubusercontent.com/2662497/64800032-208dab00-d586-11e9-96c6-9901c8eeabb8.png">

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

**Comment by madchap** [comment]
I will also let @Wadeck double-check, but after doing that extra due diligence on my side, your PR https://github.com/DefectDojo/django-DefectDojo/pull/1556 seems to fix that as well.

**Comment by Wadeck** [comment]
@Maffooch the table of content is corrected displayed now, thank you!

**Comment by madchap** [comment]
@Maffooch feel free to mark this resolved :) Thanks!

**Comment by madchap** [comment]
Or @Wadeck I guess you're satisfied ;-)
