### ISSUE TITLE
Show the engagement 'version' field and tags in search results

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1559]
**Is your feature request related to a problem? Please describe**
In order to better pinpoint what the search is returning, it would be nice to have the engagement show the version (as in the version field that can be put in the engagement metadata), and eventually the tags.

![image](https://user-images.githubusercontent.com/5468769/65160690-7c4cae00-da36-11e9-88f0-214847692e8c.png)

fyi @Wadeck

**Comment by dougmorato** [comment]
@madchap  Are you working on this or is it up from grabs? 

I think I can tackle it as I have a similar need (i would like finding ID to be displayed), so if you are not working on it, I can possibly tackle it, does not seem to be super difficult:
https://github.com/DefectDojo/django-DefectDojo/blob/dev/dojo/templates/dojo/simple_search.html#L150

**Comment by madchap** [comment]
Hey @dougmorato 

I am not. I'd be grateful if you could :-)

**Comment by dougmorato** [comment]
@madchap Just created a new Pull Request #1596 that implements what you asked and also adds a finding ID column.

Here is a picture of the end result:

![image](https://user-images.githubusercontent.com/9654/66688984-09aaa900-ec57-11e9-8907-959b3d64fe41.png)

**Comment by madchap** [comment]
Thank you @dougmorato, this looks good to me :+1:
