### ISSUE TITLE
Celery Job cannot handle empty CVE when sending finding to Jira

### ISSUE THREAD

**Issue by FrankSh0rty** [DefectDojo/django-DefectDojo#1573]
**Bug description**
The DefectDojo Docker Celery worker cannot handle an empty CVE when bulk sending issues to JIRA.

**Steps to reproduce**
1. Setup a DefectDojo docker with a Jira connection
2. Create some issues with an Emptu CVE (Nessus import by default does not fill the CVE field)
3. Select some issues and press Bulk Edit
4. Click on Send To Jira
5. See the Error in the console log for the docker. 
6. Edit a single issue in DefectDojo with an Empty CVE
7. Select the Push To Jira at the bottom of the page
8. See that it gets send to Jira.

**Expected behavior**
Would expect the bulk edit to not care about an empty CVE or other field and just send an empty string over the API. Would also expect DefectDojo to give a clear error when fields are required. 

**Temporary workaround**
Either, send all issues to Jira one by one 
Or, fill out all the fields of all issues and then bulk send.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: DefectDojo Docker on MacOS
 - DefectDojo version: v. 1.5.4 

**Screenshots** (optional)
![DD_issue](https://user-images.githubusercontent.com/51950529/65857092-6fe42180-e363-11e9-8a81-ad24d3195194.png)

**Comment by dr3dd589** [comment]
hello, @FrankSh0rty it is fixed in the dev branch. Wait until next release or use dev version.

**Comment by FrankSh0rty** [comment]
Hi @dr3dd589, thanks for the reply. That is good news. Do you know if this branch also includes other bug fixes concerning the JIRA integration, like that findings are not synced when importing test results or that those findings do not attach to the epic that DefectDojo creates? 

Thank you!
