### ISSUE TITLE
Need custom field for Default issue type for JIRA integration

### ISSUE THREAD

**Issue by bilalk88** [DefectDojo/django-DefectDojo#1579]
**Is your feature request related to a problem? Please describe**
I'm using jira software, where we have issue type as VULN and Defect. We are not using default issue type that jira bydefault provide like Task/Bug/Story etc.
So If we can get some option where we can configure default issue type in DefectDojo for jira integration.

**Describe the solution you'd like**
We can give text box where we can ask user to enter his own issue type. As most of the users uses defferent types of issue types in jira.

**Comment by madchap** [comment]
Or at least something in the `settings.py` I guess.

**Comment by madchap** [comment]
This was addressed in the above PR, which was merged in `dev`. You can now specify which issue type in the `settings.py` file.
