### ISSUE TITLE
Add new notes for findings using API V2

### ISSUE THREAD

**Issue by piyarathnalakmali** [DefectDojo/django-DefectDojo#1592]
**Is your feature request related to a problem? Please describe**
There is no way to add new notes to an existing finding using the API version 2. Finding endpoint does not support any request related to notes and notes endpoint only support retrieving and updating notes.  

Creating an issue as per [request](https://github.com/DefectDojo/django-DefectDojo/pull/1360#issuecomment-541021572) @propersam

**Comment by propersam** [comment]
I'm on this... Will make a PR as soon as I can... 

Have it assigned to me

**Comment by propersam** [comment]
@piyarathnalakmali Help Test My PR if it meets your requirements

You can Add a New Note to Finding by making *POST* Request to /findings/<fid>/notes

and pass in data parameters 
{
  "entry": "note entry goies here",
 "private": false
}

```
curl -X POST  -H 'content-type: application/json' -H 'Authorization: Token < auth-token >' http://127.0.0.1:8000/api/v2/findings/1/notes/ -d '{
"entry": "This is another brand new note i'm just adding to this finding",
"private": true
}'
```

**Comment by propersam** [comment]
If you send a *GET* request to http://127.0.0.1:8080/api/v2/findings/1/notes/ 
The api will retrieve all Notes that are assigned to the current Finding

To Delete a Note from a finding you will have to make a *PUT* or *PATCH* request to 
http://127.0.0.1:8080/api/v2/findings/1/remove_note/
with *"note_id"* parameter. 
e.g .
```
curl -X PATCH  -H 'content-type: application/json' -H 'Authorization: Token < auth-token >' http://127.0.0.1:8080/api/v2/findings/1/remove_note/ -d '{
"note_id": 20}'
```

**Comment by madchap** [comment]
Would the PATCH method address changing the note's visibility as well? (on mobile, not looking at code)

**Comment by propersam** [comment]
PUT/PATCH on this endpoint is only for removing notes from a particular Finding and deleting them so we don't leave a dangling note. 

There is already a note End Point for modifying Notes... 
https://github.com/DefectDojo/django-DefectDojo/pull/1360

Did I get your question right...?  Or what do u mean by visibility

**Comment by madchap** [comment]
Thanks, I remember you doing that then. By visibility I meant toggling the private flag.

**Comment by propersam** [comment]
U can toggle the private flag of a note by making patch request to the note endpoint.. 
https://github.com/DefectDojo/django-DefectDojo/pull/1360

**Comment by propersam** [comment]
```
curl -X PATCH  -H 'content-type: application/json' -H 'Authorization: Token < auth-token >' http://127.0.0.1:8000/api/v2/notes/1/ -d '{ "private": true }'
```

**Comment by piyarathnalakmali** [comment]
Sorry for the delay @propersam.
I tested both POST and PATCH requests. They work exactly as expected. 
GET also worked when the selected finding had at least one note. But when the selected finding doesn't have any notes it gives the following error.
```
AttributeError at /api/v2/findings/5/notes/
'list' object has no attribute 'data'

Traceback:

File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python3.5/site-packages/django/views/decorators/csrf.py" in wrapped_view
  54.         return view_func(*args, **kwargs)

File "/usr/local/lib/python3.5/site-packages/rest_framework/viewsets.py" in view
  116.             return self.dispatch(request, *args, **kwargs)

File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py" in dispatch
  495.             response = self.handle_exception(exc)

File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py" in handle_exception
  455.             self.raise_uncaught_exception(exc)

File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py" in dispatch
  492.             response = handler(request, *args, **kwargs)

File "./dojo/api_v2/views.py" in notes
  223.         return Response(serialized_notes.data,
```

**Comment by propersam** [comment]
Wow... Thanks for d catch... 
I will fix that Asap...

**Comment by piyarathnalakmali** [comment]
I am working on a new feature related to notes. In that I have a requirement to add new notes to findings using the API. 
As per the current implementation only the users with admin privileges are allowed to send POST, PUT, and PATCH requests to the finding API. The user, who is sending the API request is set as the author of the added note. So, each note added via the API will have admin as the author.

Passing the "author" as one data parameter in the request can solve this issue. But then, admin can add new notes setting the author as any user he prefers. That will also be a problem.

The best solution for this issue will be moving all the product permission validations inside the API and allow any user to invoke the API. 
What do you think @propersam?
Do you think this should be moved to a separate issue?

**Comment by propersam** [comment]
> Wow... Thanks for d catch...
> I will fix that Asap...

Update made..check if u still get the error...and please write your review in the Repo link
https://github.com/DefectDojo/django-DefectDojo/pull/1595

**Comment by propersam** [comment]
> I am working on a new feature related to notes. In that I have a requirement to add new notes to findings using the API.
> As per the current implementation only the users with admin privileges are allowed to send POST, PUT, and PATCH requests to the finding API. The user, who is sending the API request is set as the author of the added note. So, each note added via the API will have admin as the author.
> 
> Passing the "author" as one data parameter in the request can solve this issue. But then, admin can add new notes setting the author as any user he prefers. That will also be a problem.
> 
> The best solution for this issue will be moving all the product permission validations inside the API and allow any user to invoke the API.
> What do you think @propersam?
> Do you think this should be moved to a separate issue?

In the current implementation of Notes. Any authenticated user can add notes not only the Admin. Defect Dojo allows for different types of users. So whenever a user is adding a note...The current user is fetched and attached to the note as the author. And Also notes keeps history records of any updated made on it. 
So making author a parameter does not seem like a good move for the sake of data integrity.

Also in the implementation..only the author of a specific note is allowed to delete the note. So anyone trying to delete a note not authored by them will flag an error.

author parameter is like a logging detail (more like date created and date updated parameters in database)... For keeping proper report and records. Allowing it to be modified externally will make data integrity questionable

**Comment by propersam** [comment]
Any authenticated user can edit a note not only the author who created it. The user who edits the note will be stored as an editor, along side the edit date and stored in the note history.

So with this I think there should be enough flexbility already...

If permission checks are removed from the Api that would be a move against Security.

**Comment by piyarathnalakmali** [comment]
@propersam Thank you for the information.
The issue was with users django.contrib.auth model permissions. After adding add, change and delete permissions on Finding model user can add, update and delete notes.
