### ISSUE TITLE
Add a model for CVEs and generic vulnerability databases

### ISSUE THREAD

**Issue by jvz** [DefectDojo/django-DefectDojo#1594]
**Is your feature request related to a problem? Please describe**

While working on a solution for https://github.com/DefectDojo/django-DefectDojo/issues/1119, I figured it would make sense to cache the CVE metadata in the database.

**Describe the solution you'd like**

As a user, I want my security scan uploads to be matched against an internal CVE database to ensure that findings contain the CWE as well as allowing for findings that reference the same CVE to be logically related. This internal CVE database should be configurable with a git repository which is imported and updated periodically. While I only need to support CVEs, this should be extensible to support other vulnerability databases that may be specific to individual security products.

**Describe alternatives you've considered**

Making calls to an API that serves CVEs could potentially be easier to use, but the ability to run DefectDojo offline prevents that.

**Additional context**

As of the date of filing, the git repository for https://github.com/CVEProject/cvelist is about 962 MB (including both the working directory and the .git/ directory). As such, I'd imagine the disk usage from importing to various databases to be comparable (i.e., less than a gigabyte). Due to this, this feature should likely be opt-in rather than enabled by default.

**Comment by madchap** [comment]
For the offline issue, maybe another feature would be required to import a zip file or something. Then, for this feature, the defacto would be to just be online and perform queries?

Do we have any idea on how many installations of DD are online vs offline?

**Comment by jvz** [comment]
Using an input source other than a git repository certainly helps inform how to structure the code, though that's not too big a deal to change in this project.

**Comment by jvz** [comment]
So I noticed that there's a `CWE` model that isn't used much yet. I can likely link into that table for vulnerabilities with a CWE which provides a richer data model.

**Comment by jvz** [comment]
Reopen?
