### ISSUE TITLE
Help with configuring DefectDojo over HTTPS for docker-compose

### ISSUE THREAD

**Issue by bilalk88** [DefectDojo/django-DefectDojo#1597]
Hi,
I need some help w.r.t configuring docker based DefectDojo over https, right now I'm using it at default 8080 port.

Can someone please help me it, that how to do that in docker-compose for DefectDojo.

**Comment by ptrovatelli** [comment]
Hi @bilalk88 ; this PR does it https://github.com/DefectDojo/django-DefectDojo/pull/1581
Is it helping?

**Comment by bilalk88** [comment]
@ptrovatelli : thanks for the response. I'm working on it. Once done will update you.

**Comment by bilalk88** [comment]
@ptrovatelli Hi, i did changes as per the documentation. I want to run it on port 443 but I'm getting an error .

nginx_1         | 2019/10/17 09:30:38 [emerg] 1#1: bind() to 0.0.0.0:443 failed (13: Permission denied)
nginx_1         | nginx: [emerg] bind() to 0.0.0.0:443 failed (13: Permission denied)

**Comment by madchap** [comment]
This type of "issue" (request for help) is certainly better suited for Slack, and not a github issue.

**Comment by adracea** [comment]
This seems like a firewall issue more than anything , the idea is to have nginx's whatever port bound to the host's 443 port , which requires some level of administrative rights on the host machine .

**Comment by ptrovatelli** [comment]
@bilalk88 you need to be root to run a service that listens on port 443 (which is in range 1-1023). by default nginx runs as non-root user. I you really want to use port 443, it may be enough to remove that from Dockerfile.nginx and rebuild, although i haven't tried: 
`USER 1001`
Else you can use a port >1023 and run as non-root.

**Comment by ptrovatelli** [comment]
and you'd need also to be root in the host

**Comment by bilalk88** [comment]
Thank you guyz for the tips.
