### ISSUE TITLE
Change the restrictions in editing a note

### ISSUE THREAD

**Issue by piyarathnalakmali** [DefectDojo/django-DefectDojo#1604]
DefectDojo supports adding notes for findings and tests. Those added notes can be edited only by the author of the note and by admins. **Is there any specific use case which requires limiting the edit access only to those users?** If not isn't it more suitable to allow any user who is permitted to the product (which the particular finding or test belongs to) to edit any note added to a finding/test?

For each note, it's edit history is stored separately with the editor, time of editing and the new entry. So there will not be a problem of tracking who made the changes to an existing note. That way notes can be maintained more collaboratively. Otherwise there won't be a considerable advantage of maintaining the note history as editors will always be either admin or the author. 

@devGregA @aaronweaver @mtesauro could you please give your ideas about this. If it's okay to allow other users to edit notes I can do the required changes.

**Comment by Maffooch** [comment]
I don't see any issue with that change. It's more intuitive as well. Plus one from me.
