### ISSUE TITLE
DefectDojo known security vulnerability in docker images w.r.t jquery

### ISSUE THREAD

**Issue by bilalk88** [DefectDojo/django-DefectDojo#1605]
Hello Team,

We are trying to on board defectdeojo in our corporate, but as per our policy we have to perform container security scanning. While scanning we came up accross with jquery version used by defectdojo is vulnerable.
DefectDojo uses jquery version 2.1.* and from our scanning it shows that it should be upgraded to latest version 3.0.

So could you please provide some suggestion on upgrading jquery or can we get latest update on via docker image itself.

**Comment by ptrovatelli** [comment]
hi  @bilalk88 . on what branch are you? do you know where this dependency come from? from what I see in package.json on dev or master branch we're supposed to be using jquery 3: 
` "@yarn_components/jquery": "jquery/jquery-dist#~3.3.1",`

**Comment by bilalk88** [comment]
Hi @ptrovatelli . Thanks for the response.
I'm in the master branch. I'm not sure from where this old version of jquery came from. But when I checked in the nginx container under  " /usr/share/nginx/html/static/ " there all are older version of jquery there.

**Comment by ptrovatelli** [comment]
Those files are generated by (Dockerfile.nginx)
`python3 manage.py collectstatic --noinput`
they contain with other things, libraries pulled by yarn based on package.json.
this basically gets all static resources from django so that nginx can serve them. 

I'm actually even seeing what seems to be jquery 1.7 and jquery 1.8. Can you point us to the files you're seing that are jquery 2.1? 
```
docker exec -it django-defectdojo_nginx_1 bash
cd /usr/share/nginx/html/static
 find . -type f -name '*jquery*'
(...)
./font-awesome/src/3.2.1/assets/js/jquery-1.7.1.min.js
./fontawesome/src/3.2.1/assets/js/jquery-1.7.1.min.js
(...)
./jquery-ui/ui/jquery-1-7.js
(...)
./jquery.hotkeys/jquery-1.4.2.js
(...)
./rest_framework_swagger/lib/jquery-1.8.0.min.js
(...)
./tastypie_swagger/js/lib/jquery-1.8.0.min.js
./tastypie_swagger/js/lib/jquery.ba-bbq.min.js
./tastypie_swagger/js/lib/jquery.slideto.min.js
./tastypie_swagger/js/lib/jquery.wiggle.min.js
```

it's probably possible to improve the situation by tuning that package.json file.

**Comment by bilalk88** [comment]
@ptrovatelli. Thanks for the response.

Actually, jquery 2.* versions are inside the /usr/share/nginx/html/static/startbootstrap-sb-admin-2/bower_components/jquery/dist/jquery.js

**Comment by devGregA** [comment]
Believe this is fixed: https://github.com/DefectDojo/django-DefectDojo/blob/414e10fd8b7aa51a27edfdce8a02ad3a512fe45c/components/package.json
