### ISSUE TITLE
Ability to filter test findings by status

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1609]
**Is your feature request related to a problem? Please describe**
When viewing a test's finding (test view), having a way to filter findings per status would be very useful, especially when dealing with many pages.

**Describe the solution you'd like**
Add the filter bar to the test view? Or maybe something fancy could be done if data tables were introduced in the test view?

**Comment by valentijnscholten** [comment]
Fixed by #1884
