### ISSUE TITLE
Email notification configuration using docker 

### ISSUE THREAD

**Issue by elyeschemengui** [DefectDojo/django-DefectDojo#1617]
**Bug description**
I have defectdojo running under docker, in system settings i have enabled email notification and in notifications i have enabled all type of notifications via email.

The problem is that i can't find where exactly i have to configure my gmail information in the app to then defectdojo could use it for email notifications.
I know it's not a security bug, but in documentation i didn't find a clue. Could you please help me with that ?

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Comment by madchap** [comment]
You would probably either use your host's MTA or a service like SendGrid.

You would configure the information in the `setting.py` file, around line 488, look for `DD_EMAIL_URL`. Another way to do it would be to pass that environment variable through your docker-compose to override `DD_EMAIL_URL` and not touch that file eventually, but both would work.

**Comment by madchap** [comment]
Stale, closing. Some docs probably needed.

**Comment by sayanTlregtech** [comment]
Hey but how to pass the smtp url? In the settings.py there is an url for smtp.     smtp://user@:password@localhost:25
But I have another smtp service like brevo. How to configure this one? If anyone have any idea please let me know. This so urgent.
