### ISSUE TITLE
Using API V1, get all findings of an engagement using the engagement's ID.

### ISSUE THREAD

**Issue by marc-199** [DefectDojo/django-DefectDojo#1618]
**Bug description**
Trying to get all findings of an engagement using the engagement's ID but I end up having all findings.

1. Use this GET request <  {URL}/api/v1/findings/?test__engagement=1  > to access to all the findings that are under engagement 1
2. The API returns all findings (must have more than one engagement to notice that).

The expected behavior is retreiving the findings that are only under the engagement that has an id=1

**Comment by blacklotos** [comment]
Greetings marc-199.

What version of DefectDojo do you use?

**Comment by marc-199** [comment]
Hi, I'm using the following branch : https://github.com/DefectDojo/django-DefectDojo/pull/1540 
I'm trying to export the data via the API requesting all findings for an engagement but I end up getting all the findings. To avoid getting all the findings, I'm using a filter on the engagement string value to verify that it ends with the desired ID but the operation will become very heavy when the number of finding becomes really high. Thank you !

**Comment by blacklotos** [comment]
I was checked on DefectDojo v1.5.4 and work fine. It is possible what you make mistake on request (you can miss "_" then it will return all list of findings)

**Comment by marc-199** [comment]
I'm pretty sure about the bug, please find in attachement the response of the application in .json format for the following GET request using Postman : {url}/api/v1/findings/?limit=1000&?offeset=0&?test__engagement=1&?active=1&?false_p=0&?verified=1
I changed the extension to .txt so the file can be uploaded.
Thank you.

[getEngagementById.json.txt](https://github.com/DefectDojo/django-DefectDojo/files/3778560/getEngagementById.json.txt)

**Comment by blacklotos** [comment]
May I ask you try API v2, <Server>/api/v2/doc/
API v1 will be no supported in the future.
Best regards.

**Comment by madchap** [comment]
Quickly trying to reproduce, I can't.

I am simply using my instance's https://defectdojo.xxx.com/api/v1/doc/#!/findings/findings_list swagger, passing an engagement ID. That engagement has 56 findings in it as show in the UI.

Call:
`https://defectdojo.cloudbees.com/api/v1/findings/?test__engagement=2`

The API call returns (truncated, but glanced at entire json)
```
{"meta": {"limit": 20, "next": "/api/v1/findings/?test__engagement=2&offset=20&_=1572294219136&limit=20", "offset": 0, "previous": null, "total_count": 56}, "objects": [{ ..... ]}
```

Looking at the json produced:
```
$ cat test.json |jq '.objects[].engagement' |sort |uniq
"/api/v1/engagements/2/"
```
