### ISSUE TITLE
Admin credentials printed on the console after running 'docker compose up' do not work.

### ISSUE THREAD

**Issue by jovyn** [DefectDojo/django-DefectDojo#1623]
**Bug description**
I tried the setup via Docker Compose. I built and ran the application and the credentials were printed on the console. While navigating to the site i.e http://localhost:8080 the application does not accept the credentials. I receive the invalid credentials message.
This is a fresh installation, I have tried this multiple times by deleting the previous docker images but the result is the same. 
DefectDojo version = 1.5.4 (Release Mode)

**Steps to reproduce**
1. Clone the repo  - git clone https://github.com/DefectDojo/django-DefectDojo
2. Goto the directory - `cd django-DefectDojo`
3. Building -    `docker-compose build`
4.  Running -     `docker-compose up`

![1](https://user-images.githubusercontent.com/3529476/67624589-1d0d6500-f850-11e9-8049-aaf7ba7040dd.PNG)

![2](https://user-images.githubusercontent.com/3529476/67624593-34e4e900-f850-11e9-86b7-937b88e66ab6.PNG)

5. Goto http://localhost:8080 and enter the credentials printed on the console from the previous command.
![3](https://user-images.githubusercontent.com/3529476/67624600-44643200-f850-11e9-82e4-fb4c84859381.PNG)

6. An Error message is thrown out, instead of logging in to the dashboard. 
![4](https://user-images.githubusercontent.com/3529476/67624603-4c23d680-f850-11e9-9850-621d558545c8.PNG)

**Expected behavior**
The credentials printed on the console after running 'docker-compose up' must work on the site (lhttp://localhost:8080) 

**Deployment method** *(select with an `X`)*

- [X] Docker

**Environment information**
 - Operating System: `Ubuntu 16.04`
 - DefectDojo Commit Message: `42f1d4e7: Update issue templates[2019-10-02 16:01:25 -0500]`

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)
Screenshots are added along with the steps in "Steps to Reproduce"

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)
I have tried this only on Ubuntu 16.04. The 'docker-compose build' runs successfully and after running 'docker-compose up' the console output is also as expected.

**Comment by blacklotos** [comment]
Greeting jovyn.

Valid password generate at first run ("Make sure you write down the first password generated as you'll need it when re-starting the application.") if you didn`t write it down you will need to Clean up Docker Compose (but it will drop your DB)
To do this run (https://github.com/DefectDojo/django-DefectDojo/blob/master/DOCKER.md):
Removes all containers
    docker-compose down
Removes all containers, networks and the database volume
    docker-compose down --volumes

**Comment by ptrovatelli** [comment]
I think there's a way to update the admin password without removing the db if you already have data (seen on some slack discussion) but i haven't tried yet. we should probably add it in the docker.md as it's a common issue.

**Comment by ptrovatelli** [comment]
got it; again i've never tried it though :)
```docker ps```
grab container id of  `django-defectdojo_uwsgi_1`
```docker exec -it <container_id>  /bin/bash```
now just change password
```python manage.py changepassword admin```

**Comment by madchap** [comment]
Good point @ptrovatelli :+1: 
I always forget about these "django-esqueries" ;-)

We could probably patch up `entrypoint-initializer.sh` to actually spit out a line of help in the logs if `ADMIN_EXISTS` is true and move that up actually in the script. IMO, that should be coming before.

**Comment by jovyn** [comment]
Thank You Every one for your time in helping me out.  
Fortunately I did not have much data in the db so went on to clean up docker compose.
Then did a re-build and the newly generated passcode worked. 
After this I went on to change the password (Using the steps mentioned by @ptrovatelli ) and the password change worked for me :) 

I am closing this bug :)

Just a thought, guys do you think a user should be forced to change the password the first time he logs in. I feel instead of noting down the password it would be easier to set a new password instead. 
Though this can be done by the user even without being forced.
