### ISSUE TITLE
Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "apps/v1"

### ISSUE THREAD

**Issue by gibranduatiga** [DefectDojo/django-DefectDojo#1631]
Hi.. please help me to solve this problem.
I have tried to follow the installation tutorial on the page below
- https://github.com/DefectDojo/django-DefectDojo/blob/master/KUBERNETES.md

but I encountered a problem during the helm chart installation step into the minikube:
![alt text](https://i.ibb.co/hVfwxFP/Screen-Shot-2019-11-01-at-16-43-37.png "Error-1")

**Comment by gnarly-cl0s** [comment]
What version of helm are you using? I encountered this issue in https://github.com/DefectDojo/django-DefectDojo/issues/1192 due to lint format issue on some charts. 

See https://github.com/helm/helm/issues/5750 for more details since I am guessing you are encountering same error.

**Comment by gibranduatiga** [comment]
before this.. i using helm version 2.15.2, now i am downgrade to v2.15.0, and then error explain

> Error: validation failed: [unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"]

any advise?

**Comment by Apipia** [comment]
I had a similar issue and my solution was to downgrade the version of Kubernetes that is used by minikube.
When launching minikube: `minikube start --kubernetes-version=v1.15.4 --memory=4g`

I do not believe that the current DefectDojo release has the helm/kubernetes properly configured for kubernetes latest update.

**Comment by gibranduatiga** [comment]
> I had a similar issue and my solution was to downgrade the version of Kubernetes that is used by minikube.
> When launching minikube: `minikube start --kubernetes-version=v1.15.4 --memory=4g`
> 
> I do not believe that the current DefectDojo release has the helm/kubernetes properly configured for kubernetes latest update.

can you explain clearly which version you use for helmet, minikube and Kubectl @Apipia ?
I think it caused by when k8s v1.16 come out, some of the older APIs will be full deprecated, just as a temporary workaround (until this is fixed) I adding :

```yaml
spec:
    ...
    - --runtime-config=apps/v1beta1=true,apps/v1beta2=true,extensions/v1beta1/daemonsets=true,extensions/v1beta1/deployments=true,extensions/v1beta1/replicasets=true,extensions/v1beta1/networkpolicies=true,extensions/v1beta1/podsecuritypolicies=true
```

In my case, deployment with helm works fine afterwards.

**Comment by Apipia** [comment]
> > I had a similar issue and my solution was to downgrade the version of Kubernetes that is used by minikube.
> > When launching minikube: `minikube start --kubernetes-version=v1.15.4 --memory=4g`
> > I do not believe that the current DefectDojo release has the helm/kubernetes properly configured for kubernetes latest update.
> 
> can you explain clearly which version you use for helm, minikube and Kubectl @Apipia ?
> I think it caused by when k8s v1.16 come out, some of the older APIs will be full deprecated, just as a temporary workaround (until this is fixed) I adding line below on `/etc/kubernetes/manifests/kube-apiserver.yaml` :
> 
> ```yaml
> spec:
>     ...
>     - --runtime-config=apps/v1beta1=true,apps/v1beta2=true,extensions/v1beta1/daemonsets=true,extensions/v1beta1/deployments=true,extensions/v1beta1/replicasets=true,extensions/v1beta1/networkpolicies=true,extensions/v1beta1/podsecuritypolicies=true
> ```
> 
> and run `kubectl -n kube-system delete pod kube-apiserver-* kube-controller-manager-*`
> In my case, deployment with helm works fine afterwards.

I pretty much installed whatever version was most current for each tool. And this was pretty recently, I'll provide those versions for you though:
```
$ helm version                                                                                                                                                                                              
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

$ minikube version
minikube version: v1.4.0
```

with kubectl, as I said, minikube will set up whatever version you provide it in the start command, as I stated in my previous post, I use v1.15.4, as v1.16 seems to break.

**Comment by namloc2001** [comment]
Right, I think I may have it sussed...

So this is the description of helm dependencies:
```
dependencies: # A list of the chart requirements (optional)
  - name: The name of the chart (nginx)
    version: The version of the chart ("1.2.3")
    repository: The repository URL ("https://example.com/charts") or alias ("@repo-name")
    condition: (optional) A YAML path that resolves to a boolean, used for enabling/disabling charts (e.g. subchart1.enabled)
    tags: # (optional)
      - Tags can be used to group charts for enabling/disabling together
    enabled: (optional) Enabled bool determines if chart should be loaded
    import-values: # (optional)
      - ImportValues holds the mapping of source values to parent key to be imported. Each item can be a string or pair of child/parent sublist items.
    alias: (optional) Alias usable alias to be used for the chart. Useful when you have to add the same chart multiple times
```
You can see version is referring to the chart version.

Versions list in: https://github.com/DefectDojo/django-DefectDojo/blob/master/helm/defectdojo/requirements.yaml are:
- mysql = 0.15.0
- postgresql = 3.11.7
- rabbitmq = 4.3.1
- redis = 6.1.4

If you run helm `search repo stable` you can see all charts and their versions. You can also do `helm search repo -l stable/<chart_name>` and this'll show you for a specific chart.
The latest version for the dependencies is as follows:
- mysql = 1.6.2
- postgresql = 8.1.4
- rabbitmq = 6.16.3
- redis = 10.3.4

So choosing mysql as it's top of the list, I had a look at https://github.com/helm/charts/commits/master/stable/mysql/templates/deployment.yaml and then history. I can see on 04.10.19 a commit with title "Update api versions to support k8s 1.16" listed. So I click on this and see this page: https://github.com/helm/charts/commit/9e2902f1a563dc7710321050534a74c899056fcf#diff-1b628c10a6fb23ebc38e18fdfaab3490 where on it you can see:
```
- apiVersion: extensions/v1beta1
+ apiVersion: apps/v1
```
This means mysql would have been using wrong apiversion/extension in 0.15.0 but not now.

So versions in the dependency file (requirements.yaml) needs to be updated to later versions (as per second list).
