### ISSUE TITLE
Slack invite link is no longer active

### ISSUE THREAD

**Issue by ThibaudLopez** [DefectDojo/django-DefectDojo#1636]
**Bug description**
The Slack invite link of the readme page is no longer active. It says "This invite link is no longer active. Please check with the person who shared it with you to see if there's a new link available."

**Steps to reproduce**
1. Go to https://github.com/DefectDojo/django-DefectDojo/blob/master/README.md
2. Click on Get Access, the current link is: https://owasp.slack.com/join/shared_invite/enQtNjExMTc3MTg0MzU4LTViMDg1MmJiMzMwZGUxZjgxZWQ1MTE0NTBlOTBhNjhhZDIzZTZiNmEwOTJlYjdkMzAxMGVhNDkwNDNiNjZiOWQ
3. It will open Slack

![image](https://user-images.githubusercontent.com/6137886/68363252-45228100-00f8-11ea-93be-7a039ccb47a7.png)

**Expected behavior**
The invite should work.

**Comment by Aniket21mathur** [comment]
Fixed in #1688
