### ISSUE TITLE
Engagement view: action shortcuts not working and test menu hardly visible

### ISSUE THREAD

**Issue by ptrovatelli** [DefectDojo/django-DefectDojo#1643]
**Bug description**
Two UI issues in engagement view, introduced at 1720c95bf831236b81c5713d6006b29e55dec33c I believe
- action buttons aren't working anymore: when pushing "i" or "a" or "e" it's not doing anything: 
` ProTip! Type e to edit this engagement. Type i to import scan results or a to add tests.`
- the test drop-down menu is hardly visible and we need to scroll to be able to see it (see screenshot)

**Steps to reproduce**
setup env:
```
git checkout 1720c95bf831236b81c5713d6006b29e55dec33c
# this will remove any data
docker-compose down --volumes
docker-compose build
docker-compose up
```

- create a product
- create an engagement
- import any scan (for exemple tests/zap_sample.xml)
- click on the engagement name to display the engagement window or navigate to http://localhost:8080/engagement/1
- push "i" key: nothing happens
- click "..." in the tests section

**Expected behavior**
- "i" should open the import scan window
- "..." should display a visible menu

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
1720c95bf831236b81c5713d6006b29e55dec33c

**Screenshots** (optional)
![menu](https://user-images.githubusercontent.com/34663482/68552565-ac9e4080-0418-11ea-829e-71e4c333c65f.jpg)

**Additional context** (optional)
I have tried with the previous commit e49bbb5e4fb8cab0d8e2214f153744ed86a8d39a and everything works fine. 
It's hard to tell where the issue comes from. My guess is that it comes from the application imported in requirements that somehow changes the engagement view.
`git+https://github.com/DefectDojo/defectDojo-engagement-survey@master#egg=defectDojo-engagement-survey
`

I have saved the html page from e49bbb5e4fb8cab0d8e2214f153744ed86a8d39a and from 1720c95bf831236b81c5713d6006b29e55dec33c and there are some diff that I have a hard time understanding (don't seem to come from anything commited at 1720c95bf831236b81c5713d6006b29e55dec33c). the issue probably comes from one of theese diffs. 
See diff in attachment: 
[view_engagement_html_code.zip](https://github.com/DefectDojo/django-DefectDojo/files/3829165/view_engagement_html_code.zip)

@Maffooch any idea where this could be coming from?

**Comment by Maffooch** [comment]
No idea where it’s coming from. Likely the repo that handles all that if I had to guess. I’ll look into it.

**Comment by ptrovatelli** [comment]
fixed by https://github.com/DefectDojo/django-DefectDojo/pull/1713 and https://github.com/DefectDojo/django-DefectDojo/pull/1718
