### ISSUE TITLE
VSTS/AzureDevOps integration, similar to existing Jira integration

### ISSUE THREAD

**Issue by GeneNinestein** [DefectDojo/django-DefectDojo#1650]
**Is your feature request related to a problem? Please describe**
Problem - we don't use Jira, we use Azure DevOps 

**Describe the solution you'd like**
Similar integration to what has been done with Jira for creating tickets for findings.  Grouping findings into one ticket would be great!

**Describe alternatives you've considered**
Looked at tools that would use Jira as stepping stone to Azure DevOps, but seems clunky and adds complexity

**Additional context**
Other tools have Azure DevOps integration through API's, expect this request can't be overly difficult.

**Comment by immewnity** [comment]
Adding support here for Azure DevOps (formerly known as TFS) integration - we're looking at the API and will commit back if we get it working, but I'm not too familiar yet with either DefectDojo or ADO/TFS, so someone with better knowledge might get the job done faster/better.

**Comment by batteryxsnare** [comment]
@immewnity @GeneNinestein  if you got anything working i'd love to know as my company just moved onto Azure DevOps

**Comment by bcncarlesc** [comment]
> Adding support here for Azure DevOps (formerly known as TFS) integration - we're looking at the API and will commit back if we get it working, but I'm not too familiar yet with either DefectDojo or ADO/TFS, so someone with better knowledge might get the job done faster/better.

I would like try to add this feature on djando-DefectDoj. Where is within the code the part of jira? Where is the restapi calling to jira. My idea its clone this part and change to devops restapi.

**Comment by devhops** [comment]
+1 for this feature from me

**Comment by ixnet** [comment]
that would be awesome to have

**Comment by damiencarol** [comment]
Just to be clear, what's is discussed here is sync with AzDO board? like creating a "Bug" ticket when there is vulnerability in DD.

**Comment by bcncarlesc** [comment]
Hi [damiencarol](https://github.com/damiencarol)
Yes this is the idea create a Bug or WorkItem on Azure Devops. It could be bidirectional. Using the webhooks on Azure Devops we could set fixed on DefectDojo when it was fixed from Azure Devops.

![imagen](https://user-images.githubusercontent.com/51196641/217670352-3319f19d-4e55-446c-9544-6ea52fb0c284.png)
You could add Azure devops repository and  Azure devops area on DD for each project to know where you need create the item on Azure Devops.

**Comment by FuzzyUn1c0rn** [comment]
+1 for this feature

**Comment by Nsai1997** [comment]
Is this feature available where we can integrate the defect dodo with the azure devops

**Comment by kzzz1** [comment]
+1 for this feature! is it already available?
