### ISSUE TITLE
Cannot install on Debian 10.1

### ISSUE THREAD

**Issue by Pl0414141** [DefectDojo/django-DefectDojo#1652]
SO: Debian 10.1 clean install and full updated

root@debian:/home/peto/django-DefectDojo# docker-compose up
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

root@debian:/home/peto/django-DefectDojo# docker-compose --version
docker-compose version 1.21.0, build unknown

root@debian:/home/peto/django-DefectDojo# docker --version
Docker version 18.09.1, build 4c52b90

Should be supported, any ideas?

**Comment by ptrovatelli** [comment]
Hi @Pl0414141 
Kindly check the DOCKER.MD: 
```
Prerequisites
Docker version
Installing with docker-compose requires at least docker 18.09.4 and docker-compose 1.24.0. See "Checking Docker versions" below for version errors during running docker-compose.

```
