### ISSUE TITLE
Heroku test app linked in docs not working

### ISSUE THREAD

**Issue by JacobBrackett** [DefectDojo/django-DefectDojo#1656]
**Bug description**
Not sure if this is the right place for this report, but considering this test app is linked in the documentation here I'll report it as at least an issue in the README.md file. The test app is no longer working (https://defectdojo.herokuapp.com/)

**Steps to reproduce**
1. Go to https://defectdojo.herokuapp.com/
2. See error

![image](https://user-images.githubusercontent.com/42220852/68968560-bbc61b00-0797-11ea-8abb-7aea377f71f3.png)

**Expected behavior**
The application should load

**Deployment method** *(select with an `X`)*
- [x] Heroku

**Comment by ptrovatelli** [comment]
Hello @JacobBrackett . thanks for reporting on this but there is already an issue for this problem: https://github.com/DefectDojo/django-DefectDojo/issues/1648
can we close this one? 
thanks!

**Comment by JacobBrackett** [comment]
Missed that, sorry!
