### ISSUE TITLE
Integrate SAML2 into DefectDojo.

### ISSUE THREAD

**Issue by piyarathnalakmali** [DefectDojo/django-DefectDojo#1661]
**Is your feature request related to a problem? Please describe**

WSO2 uses DefectDojo as the Vulnerability Management System and we need to do the authentication using a custom Identity provider. Our IDP supports both SAML and JWT s. Between those two options SAML is the easiest to implement in DefectDojo. I found [this PR](https://github.com/DefectDojo/django-DefectDojo/pull/1363) which includes **SAML integration for DefectDojo**. By applying the proposed changes manually, I was able to successfully integrate SAML into DefectDojo. But, when we want to migrate the VMS to new DefectDojo versions we will have to repeat this configuration again and again. The same problem will be applicable to other co-operate DefectDojo users as well.

**Describe the solution you'd like**
It would be grate if SAML is integrated into DefectDojo by default.

**Comment by dougmcdorman** [comment]
At first glance it looks like the social auth https://python-social-auth.readthedocs.io/en/latest/backends/saml.html?highlight=saml is a general SAML implementation and so could probably be used by your corporate SAML implementation with DefectDojo. Social auth is mentioned in the referenced PR.
I'm not clear yet if DD just needs configuration to do social auth or actual code changes.

**Comment by alles-klar** [comment]
@piyarathnalakmali I am using the implementation from https://github.com/DefectDojo/django-DefectDojo/pull/1363 and it works very well for me. I had some problems to configure saml with social auth, so I decided to stick to the version from the PR because it was already running.
