### ISSUE TITLE
BlackDuck zip-file importer - always 0 findings

### ISSUE THREAD

**Issue by Apipia** [DefectDojo/django-DefectDojo#1680]
**Bug description**
BlackDuck import accepts a zip file with various csv's in them for upload. The code for this expects to find 2 files: files.csv and security.csv. However, these files are not named exactly that. As you can see below, the files contain a date. Also, in the particular version of blackduck that we use, the files.csv has been renamed to source.
![image](https://user-images.githubusercontent.com/17787069/70001653-b7795c00-1512-11ea-9ef5-734f26f2dd7e.png)

Code to be changed:
https://github.com/DefectDojo/django-DefectDojo/blob/4c5bf565ccce0df5c6e4fb3f23fd68f18864f2e4/dojo/tools/blackduck/importer.py#L58

**Steps to reproduce**
1. Create a blackduck report zip file
2. Upload the zipfile to a test in Defect Dojo
3. Note that no findings are found (since it doesn't find the files it's looking for)
4. (No error message)

**Expected behavior**
It should find the proper files and upload their results.

**Deployment method** *(select with an `X`)*
- [X] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 16.04]

This issue is quite similar to #1658, however that issue is more related to the CVE and database scheme, not the importer logic. I also noticed that amrityam's zip file is formatted similar to mine, meaning that we should be sharing this issue as well.

**Comment by madchap** [comment]
Thanks for reporting this @Apipia !

As discussed on Slack, if you'd like to submit a small PR to fix this, I can assign this issue to you. Let me know :-)

**Comment by Apipia** [comment]
Yeah that works! I'm testing my changes right now.

**Comment by madchap** [comment]
Closing this, since your patch was merged. Cheers!
