### ISSUE TITLE
The testing environment heroku app is giving application error

### ISSUE THREAD

**Issue by Aniket21mathur** [DefectDojo/django-DefectDojo#1686]
**Bug description**
The testing environment heroku app is giving application error.
**Steps to reproduce**
1. Go to 'https://github.com/DefectDojo/django-DefectDojo#demo'
2. Click on 'testing environment'

**Expected behavior**
The demo app should run.

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]

**Comment by adracea** [comment]
Hello @Aniket21mathur please take a look at the slack channel , this is a known issue that is currently being worked on . Duplicate of #1648 .

**Comment by Aniket21mathur** [comment]
> Hello @Aniket21mathur please take a look at the slack channel , this is a known issue that is currently being worked on .

Thanks. Noted :-)
