### ISSUE TITLE
PHP Security Audit Scan Report import logic flaw

### ISSUE THREAD

**Issue by Kumaran2** [DefectDojo/django-DefectDojo#1701]
**Bug description**
PHP Security Audit Scan Report import logic seems flawed. JSON report generated by php security audit has two issue types "error" and "warning" for each file scanned.  Warnings are not imported if the file is not having any errors, where as if a file is having error and warning, then warnings are imported as well. 

So for eg.
1.  if file has 1 error and 3 warning, the parser checks if file has error count > 0, condition passes and imports all issues. ie 4 issues imported .
2. if file has 0 error and 3 warning, the parser checks if file has error count > 0, condition fails and no issues are imported for that file.

Above logic seems to be flawed. I am not a python developer but high level scan through of code I suspect code below contains the flawed logic to import based on error alone.

/dojo/tools/php_security_audit_v2/parser.py

**Steps to reproduce**
1. Go to findings
2. Click Import Scan results
3. Browse and Import sample PHP Security Scan report attached.
4. See all findings, you will notice files having only warning issues are not imported. Where as warning in files having error are imported.

**Expected behavior**
Expect all warning and errors to be imported.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: OSX
 - DefectDojo Commit Message: 1.5.4 Release

**Sample scan files** (optional)
Sample scan report, expected findings on import into DefectDojo is 19 issues but actual is 18.

[phpcs_security_audit.txt](https://github.com/DefectDojo/django-DefectDojo/files/3965604/phpcs_security_audit.txt)

**Comment by Apipia** [comment]
Made a PR for this: 
https://github.com/DefectDojo/django-DefectDojo/pull/1705

**Comment by sergray** [comment]
PR #1705 is merged, so this issue can be closed
