### ISSUE TITLE
API Parity with DefectDojo

### ISSUE THREAD

**Issue by aaronweaver** [DefectDojo/django-DefectDojo#171]
The following API calls should be added to Dojo:

**Users:**
- POST /api/v1/users - Create a new user
- PUT /api/v1/users -  Update an existing user
- DELETE /api/v1/users - Delete a user

**Tagging**
In general: Support for searching by tags in all API's

**Product Type**
- /api/v1/product_types
- All API actions PUT, POST, DELETE, GET for Product Type

**Test Type**
- /api/v1/test_types
- All API actions PUT, POST, DELETE, GET for Test Types

**Development Environments**
- /api/v1/dev_environments
- All API actions PUT, POST, DELETE, GET for Development Environments

**Metrics**
- /api/v1/metrics/bug_count_month - Bug count by month
- /api/v1/metrics/product_open_bug - Open bug summary
- /api/v1/metrics/total_findings_severity - Total open by severity

Additional metrics that would be useful via the API

**Comment by aaronweaver** [comment]
@mtesauro, @YSaxon  Any other API calls that are missing?

**Comment by grendel513** [comment]
@aaronweaver - I like these, they were not included in the original implementation of the API due to business restrictions...these are easy to implement.  I'll take it!

**Comment by grendel513** [comment]
@aaronweaver - I started work on this today.  DELETE will be some work as there are business rules that have to be enforced before we can delete any record.  For example, deleting a Product Type would also delete all Products associated with it.  This means that we will not allow any Product Type deletions if products are assigned.  More to come.
