### ISSUE TITLE
Issue in finding description rendering

### ISSUE THREAD

**Issue by jmpabreu** [DefectDojo/django-DefectDojo#1717]
**Bug description**
When adding a markdown code block in the description field of a finding, the app renders everything in a single line.

**Steps to reproduce**
Send this payload to the findings (`/api/v2/findings/`) endpoint:
```
{
	"description": "```line1\nline2```",
	"found_by": [
		1
	],
	"impact": "```line1\nline2```",
	"mitigation": "```line1\nline2```",
	"numerical_severity": "S1",
	"severity": "Low",
	"test": 1,
	"title": "title",
	"active": true,
	"duplicate": false,
	"verified": false,
	"false_p": false
}
```
Go to findings detail page.

**Expected behavior**
Similar behavior to other fields (mitigation/impact) in terms of respecting new lines in the code block.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: macOS w/ Docker for mac
 - DefectDojo Commit Message: 'Correct link to setup.bash README.md'

**Screenshots** (optional)
![image](https://user-images.githubusercontent.com/11588493/71265701-addb5b00-233e-11ea-9d2d-c0d774f2ee22.png)

**Additional context** (optional)
The resulting HTML looks the same, so it's probably a CSS issue.

**Comment by Maffooch** [comment]
Corrected on the `dev` branch. Will reach `master` at a later date.
