### ISSUE TITLE
Choose which fields to push to JIRA

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1724]
**Is your feature request related to a problem? Please describe**
Depending on your process, you may not want to see all the information in your JIRA, but possibly only a few such as Title and References. Description, Mitigation and such may contain too many details and harm information confidentiality. Or you may want to add "Steps to reproduce".

**Describe the solution you'd like**
Have a way to [un]select which DefectDojo fields to push to JIRA.

**Comment by madchap** [comment]
Just got this again, where "Steps to reproduce" are not pushed to JIRA.

**Comment by Maffooch** [comment]
Is this still an issue since the mass JIRA bugfix PR's?

**Comment by madchap** [comment]
No, now we can tweak the template so effectively workaround this issue.
