### ISSUE TITLE
Setup.bash script failing on mysqlclient=1.4.2 install

### ISSUE THREAD

**Issue by kslosek** [DefectDojo/django-DefectDojo#1753]
**Bug description**
I am trying to install defectDojo in production.  run the setup.bash in interactive mode and it get to the part where it installs the dependencies from the requirements.txt file.  It looks like it's failing to install mysqlclient.

I ran sudo apt-get install libmysqlclient-dev and then re-ran the script and it seemed to install fine.  I've pasted my errors from the "Installing Defect Dojo Django application" phase below.

**Steps to reproduce**
1. Clone Defectdojo to /opt/dojo/
2. sudo ./django-DefectDojo/setup/setup.bash

**Expected behavior**
The script should install Defect Dojo.  

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [X] setup.bash 

**Environment information**
 - Operating System: Ubuntu 18.04
 - DefectDojo Commit Message: d8cd7607: Merge pull request #1729 from DefectDojo/Maffooch-patch-1 [2020-01-03 18:41:53 -0600]

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

==============================================================================
  Installing DefectDojo Django application 
==============================================================================

Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /opt/dojo/bin/python3
Not overwriting existing python script /opt/dojo/bin/python (you must use /opt/dojo/bin/python3)
Installing setuptools, pkg_resources, pip, wheel...done.
WARNING: The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting asteval==0.9.14
  Downloading https://files.pythonhosted.org/packages/ee/a1/c6273e6cbebe0b9e2e620ae78d535cdf0e4b972656f3271590cd0fa8b6de/asteval-0.9.14.tar.gz (52kB)
     |████████████████████████████████| 61kB 3.0MB/s 
Collecting bleach>=3.1.0
  Downloading https://files.pythonhosted.org/packages/ab/05/27e1466475e816d3001efb6e0a85a819be17411420494a1e602c36f8299d/bleach-3.1.0-py2.py3-none-any.whl (157kB)
     |████████████████████████████████| 163kB 7.5MB/s 
Collecting bleach-whitelist>=0.0.10
  Downloading https://files.pythonhosted.org/packages/cf/6b/0c10f2341f5f257b4b47514cd54eaf5bf91b0b52725b71331b2d1cfd3ce7/bleach-whitelist-0.0.10.tar.gz
Collecting celery==4.3.0
  Downloading https://files.pythonhosted.org/packages/5c/a1/a3dd9d8bfa09156ec2cba37f90accf35c0f4ecc3980d96cb4fb99e56504b/celery-4.3.0-py2.py3-none-any.whl (413kB)
     |████████████████████████████████| 419kB 40.8MB/s 
Collecting coverage==4.5.3
  Downloading https://files.pythonhosted.org/packages/f8/4e/f28fc04019bac97d301512d904992791569234a06826cd420f78fba9a361/coverage-4.5.3-cp36-cp36m-manylinux1_x86_64.whl (205kB)
     |████████████████████████████████| 215kB 42.6MB/s 
Collecting defusedxml==0.6.0
  Downloading https://files.pythonhosted.org/packages/06/74/9b387472866358ebc08732de3da6dc48e44b0aacd2ddaa5cb85ab7e986a2/defusedxml-0.6.0-py2.py3-none-any.whl
Collecting django_celery_results==1.1.1
  Downloading https://files.pythonhosted.org/packages/1d/3f/a82aa9fb1f2e35a72a710134a7bf9d9b1dc45dea9f6c2c16d06bb6363554/django_celery_results-1.1.1-py2.py3-none-any.whl
Collecting django-auditlog==0.4.5
  Downloading https://files.pythonhosted.org/packages/8a/0f/58bc78cb9b7513924accbaf1e6886e31d9b9baff20fcafdd4354198d484f/django-auditlog-0.4.5.tar.gz
Collecting django-custom-field
  Cloning https://github.com/DefectDojo/django-custom-field.git (to revision 4e095dd9119858e90fd21560e5618c6347e4ef1b) to /tmp/pip-install-0a6d3jni/django-custom-field
  Running command git clone -q https://github.com/DefectDojo/django-custom-field.git /tmp/pip-install-0a6d3jni/django-custom-field
Collecting django-dbbackup>=3.2.0
  Downloading https://files.pythonhosted.org/packages/97/52/4ed76751134651ce0d51f623952537ecc7e17ec781739f0a858447d35b75/django-dbbackup-3.2.0.tar.gz
Collecting django-environ==0.4.5
  Downloading https://files.pythonhosted.org/packages/9f/32/76295a1a5d00bf556c495216581c6997e7fa5f533b2229e0a9d6cbaa95ae/django_environ-0.4.5-py2.py3-none-any.whl
Collecting django-filter==2.0.0
  Downloading https://files.pythonhosted.org/packages/6a/8b/8517167a0adc45ce94d0873efb9487dd4cdeff7e10f96e837ad3d58f5837/django_filter-2.0.0-py3-none-any.whl (69kB)
     |████████████████████████████████| 71kB 46.1MB/s 
Collecting django-imagekit==4.0.2
  Downloading https://files.pythonhosted.org/packages/e5/2a/a5c62376e897c23d1ce21be86c18e68096cb8c83df7d010d24ca81139e9e/django_imagekit-4.0.2-py2.py3-none-any.whl (47kB)
     |████████████████████████████████| 51kB 43.5MB/s 
Collecting django-multiselectfield==0.1.8
  Downloading https://files.pythonhosted.org/packages/c4/39/792bb001beb9cfd7f8dc5d88edb80963de0ae281b77be79038c0fe50582b/django-multiselectfield-0.1.8.tar.gz
Collecting django-overextends==0.4.3
  Downloading https://files.pythonhosted.org/packages/00/ea/843fc542fae2af50f5c3d543245e8175307328c82b6bd1ef4d2b0edf4943/django_overextends-0.4.3-py2.py3-none-any.whl
Collecting django-polymorphic==2.0.1
  Downloading https://files.pythonhosted.org/packages/14/54/540103056d15bf06682f97d09f2aed8103916acbd326e4ca54b926d4e021/django_polymorphic-2.0.1-py2.py3-none-any.whl (77kB)
     |████████████████████████████████| 81kB 51.5MB/s 
Collecting django-rest-swagger==2.1.2
  Downloading https://files.pythonhosted.org/packages/2c/12/28d0677756283d913f8371ad7590e16f5e6c8444044f5b1b1586f956e610/django_rest_swagger-2.1.2-py2.py3-none-any.whl (747kB)
     |████████████████████████████████| 757kB 42.8MB/s 
Collecting django-slack==5.13.0
  Downloading https://files.pythonhosted.org/packages/87/7f/e2b9cadff538b4dd95b50f714efc4405987cd83cb0e6b68987c4fd9bc724/django-slack-5.13.0.tar.gz
Collecting django-tagging==0.4.6
  Downloading https://files.pythonhosted.org/packages/5e/fc/9d095602bf5d2edcbc2c5721e3d243028544575a145d84ca1ec50f7e2fc1/django_tagging-0.4.6-py2.py3-none-any.whl
Collecting django-taggit-serializer==0.1.7
  Downloading https://files.pythonhosted.org/packages/68/c4/9737e1df18ca8af0f40f46a54af08a15d75eb7afd7805ba94c87fc042ae3/django-taggit-serializer-0.1.7.tar.gz
Collecting django-tastypie-swagger
  Cloning https://github.com/DefectDojo/django-tastypie-swagger.git (to revision c7c5629480dc20cadd3015490a01bd8e70393c36) to /tmp/pip-install-0a6d3jni/django-tastypie-swagger
  Running command git clone -q https://github.com/DefectDojo/django-tastypie-swagger.git /tmp/pip-install-0a6d3jni/django-tastypie-swagger
Collecting django-tastypie==0.14.2
  Downloading https://files.pythonhosted.org/packages/92/46/3a166f9d4fab4baf0d919755cc7223d02a48b0d4e159c89050aa1f61cd1f/django-tastypie-0.14.2.tar.gz (146kB)
     |████████████████████████████████| 153kB 40.9MB/s 
Collecting django-watson==1.5.2
  Downloading https://files.pythonhosted.org/packages/eb/9f/dd7b624de57eae649d4768b91aa27d617805ec0fbabbf3bc374c5c8cfd91/django-watson-1.5.2.tar.gz
Collecting Django==2.2.4
  Downloading https://files.pythonhosted.org/packages/d6/57/66997ca6ef17d2d0f0ebcd860bc6778095ffee04077ca8985928175da358/Django-2.2.4-py3-none-any.whl (7.5MB)
     |████████████████████████████████| 7.5MB 44.0MB/s 
Collecting djangorestframework==3.9.4
  Downloading https://files.pythonhosted.org/packages/1b/fe/fcebec2a98fbd1548da1c12ce8d7f634a02a9cce350833fa227a625ec624/djangorestframework-3.9.4-py2.py3-none-any.whl (911kB)
     |████████████████████████████████| 921kB 40.0MB/s 
Collecting gunicorn==19.9.0
  Downloading https://files.pythonhosted.org/packages/8c/da/b8dd8deb741bff556db53902d4706774c8e1e67265f69528c14c003644e6/gunicorn-19.9.0-py2.py3-none-any.whl (112kB)
     |████████████████████████████████| 122kB 44.1MB/s 
Collecting html2text==2018.1.9
  Downloading https://files.pythonhosted.org/packages/16/20/de2b458ef434713053dd83209a03a5431ebe0527c8e14d9ae7838ff67d8a/html2text-2018.1.9-py3-none-any.whl
Collecting humanize==0.5.1
  Downloading https://files.pythonhosted.org/packages/8c/e0/e512e4ac6d091fc990bbe13f9e0378f34cf6eecd1c6c268c9e598dcf5bb9/humanize-0.5.1.tar.gz
Collecting jira==2.0.0
  Downloading https://files.pythonhosted.org/packages/cb/c2/4203b6cad72d115b0ad62ae7028567b538c8933745f665d0eee5082baf67/jira-2.0.0-py2.py3-none-any.whl (57kB)
     |████████████████████████████████| 61kB 45.8MB/s 
Collecting lxml==4.3.3
  Downloading https://files.pythonhosted.org/packages/35/8a/5e066949f2b40caac32c7b2a77da63ad304b5fbe869036cc3fe4a198f724/lxml-4.3.3-cp36-cp36m-manylinux1_x86_64.whl (5.7MB)
     |████████████████████████████████| 5.7MB 42.3MB/s 
Collecting Markdown==3.1.1
  Downloading https://files.pythonhosted.org/packages/c0/4e/fd492e91abdc2d2fcb70ef453064d980688762079397f779758e055f6575/Markdown-3.1.1-py2.py3-none-any.whl (87kB)
     |████████████████████████████████| 92kB 52.4MB/s 
Collecting mysqlclient==1.4.2
  Downloading https://files.pythonhosted.org/packages/73/79/67ddf24ac31b05d741f0ac87fa612c7a11bab1b39b8270ed7344d149f8af/mysqlclient-1.4.2.tar.gz (85kB)
     |████████████████████████████████| 92kB 49.6MB/s 
    ERROR: Command errored out with exit status 1:
     command: /opt/dojo/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0a6d3jni/mysqlclient/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0a6d3jni/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-0a6d3jni/mysqlclient/pip-egg-info
         cwd: /tmp/pip-install-0a6d3jni/mysqlclient/
    Complete output (10 lines):
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-0a6d3jni/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-0a6d3jni/mysqlclient/setup_posix.py", line 51, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-0a6d3jni/mysqlclient/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
spawn python3 manage.py changepassword admin
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
yarn install v1.21.1
warning package.json: No license field
info No lockfile found.
warning No license field
[1/5] Validating package.json...
warning No license field
[2/5] Resolving packages...
warning @yarn_components/mocha > jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
warning @yarn_components/mocha > glob > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning @yarn_components/mocha > glob > graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
[3/5] Fetching packages...
error marked@0.8.0: The engine "node" is incompatible with this module. Expected version ">= 8.16.2". Got "8.10.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
python3: can't open file 'manage.py': [Errno 2] No such file or directory

**Comment by AlexanderTyutin** [comment]
Sent pull request https://github.com/DefectDojo/django-DefectDojo/pull/1880 to fix it

**Comment by valentijnscholten** [comment]
better try the dev branch to install from.
