### ISSUE TITLE
Localhost username not working -all documented credentials are STILL NOT WORKING

### ISSUE THREAD

**Issue by AjCaroline** [DefectDojo/django-DefectDojo#1755]
it is a new year and it seems this issue still exists...??? Can someone help? Finally after 2 weeks I got the localhost page up and now something as silly as credentials is not documented (or easily found) ANYWHERE. Help. Please. Trying to review the application but it has been EXTREMELY painful just even starting....>! Thank you.

**Comment by urand0m** [comment]
I reviewed it and there is a script that basically generates random password for the app. unfortunately that password is not stored anywhere (as far as I could see) if you use docker you can simply access uwsgi with :

``` 
docker exec -it django-defectdojo_uwsgi_1 bash 
```

and then :

```
echo "from django.contrib.auth.models import User; User.objects.create_superuser('youruser', 'admin@example.com', 'yourpasswords')" | python manage.py  shell
```

after you will be able to login in defectdojo with the credentials provided above.
Hope it helps.

**Comment by AjCaroline** [comment]
Thank you so much Cristiano, but I'm using docker-compose then I go to local host. I tried running that command and I get "No such container: django-defectdojo_uwsgi_1".... Can you help? For background reference I cloned the repo from the main DefectDojo page then I ran docker build - docker compose up...as they have the instructions there...I had SO MANY OTHER issues after that and could NOT get localhost to come up - Now it's finally up.   I'm running this on Ubuntu 18.04.3 LTS (bionic). I installed Docker itself as well.....thank you for helping with this!

**Comment by Cylix** [comment]
I can also confirm this issue.

I started defectdojo using `docker-compose up` and was able to see the credentials in the initializer logs (for example `initializer_1   | Admin password: SOME_PWD`). However, the credentials were rejected whenever I tried to use them. I even completely deleted all the images and re-installed from scratch to make sure I am using the very first password, but it just didn't work.

I checked in the DB and the admin user exists though, the password is just unknown.

The solution of @uran0m works: I just created by admin user and forgot about that.

**Comment by valentijnscholten** [comment]
Which branch/commit are you on?

**Comment by Cylix** [comment]
I was using the latest master branch

**Comment by valentijnscholten** [comment]
I'm not using docker so not sure if the master branch is still supposed to work with that, you will be much better of by using the dev branch. Both regarding docker maturity and also features of defect dojo in general.

**Comment by Cylix** [comment]
got it, I'll look into it! Thanks for the tip :)

**Comment by gautammayekar** [comment]
HI Anything on this?  Even I am facing the same problem.

**Comment by madchap** [comment]
Hi,

This was likely fixed in the dev branch. Please try it there. Please read the DOCKER.md in the dev branch too.

We're working towards an rc6 release as well.

**Comment by gautammayekar** [comment]
Hi, An update. 

//docker exec -it django-defectdojo_uwsgi_1 bash 
and then :

echo "from django.contrib.auth.models import User; User.objects.create_superuser('youruser', 'admin@example.com', 'yourpasswords')" | python manage.py  shell//

This command seemed to work for me, I can now login and access the portal using the users I passed in the second command.  

Thanks much.  :)

**Comment by madchap** [comment]
Regarding the change of only the `admin` user or to create another superuser, you'd have a similar but easier option with manage.py. Just type `python3 manage.py` once you exec'ed in the uwsgi container's shell to get a list of all commands.

In this case, take a look at specifically at

```
[auth]
    changepassword
    createsuperuser
```

**Comment by A30003153** [comment]
First thanks and awesome @urand0m for your trick. I was using the dev and master branch both but admin password from initializer was not working at all, finally I did what you suggested and it worked. Thanks again.
