### ISSUE TITLE
Uploaded images aren't loaded

### ISSUE THREAD

**Issue by guillermo85** [DefectDojo/django-DefectDojo#1798]
**Bug description**
Images uploaded on a finding aren't loaded, they are supposed to be uploaded to /media/finding_images/image_name.jpg  but there aren't and not loaded to view.

**Steps to reproduce**
1. Go to 'Edit a Finding'
2. On Images click on 'Add images to Finding'
3. Upload some image
4. See error, that the image you upload doesn't upload or can be viewed on finding.

**Expected behavior**
The uploaded images on findings must be uploaded and then viewed.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ x ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 18.04
 - DefectDojo Commit Message: 42f1d4e: Update issue templates [2019-10-02 16:01:25 -0500]

**Comment by adracea** [comment]
Hello @guillermo85  I've found the solution to be somewhere along the lines of : https://defectdojo.readthedocs.io/en/latest/running-in-production.html (NGINX part) .
when running in docker-compose though , I've also added something along those lines:
```
uwsgi:
   -volumes:
        - defectdojomedia:/app/media
nginx:
   -volumes:
        - defectdojomedia:/usr/share/nginx/media
```
To the compose .
As well as the following to the `nginx/nginx.conf` file : 
```
location /media/ {
      alias /usr/share/nginx/media;
  }
```

Also make sure the volumes have the proper user ownership and r/w access for user 1001 .
