### ISSUE TITLE
Kubernetes installation doesn't work

### ISSUE THREAD

**Issue by httpnotonly** [DefectDojo/django-DefectDojo#1803]
**Bug description**
Kubernetes installation doesn't work
Not with the latest helm 3.0.2, not even with 2.16.1

**Steps to reproduce**
1. Go to KUBERNETES.md
2. Try to follow instructions with the latest minikube and helm
3. See error

helm 2.16
```
appsec@appsec-2 django-DefectDojo % helm install \
  ./helm/defectdojo \
  --name=defectdojo \
  --set django.ingress.enabled=false
Error: validation failed: [unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"]
```

helm 3.0.2

```
appsec@appsec-2 django-DefectDojo % helm install \
   defectdojo \
  ./helm/defectdojo \
  --set django.ingress.enabled=false
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2", error validating "": error validating data: ValidationError(Job.spec.template.spec.containers[0]): unknown field "requests" in io.k8s.api.core.v1.Container]
```

**Expected behavior**
Working installation
**Deployment method** *(select with an `X`)*
- [X] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: MacOS Catalina

**Comment by ptrovatelli** [comment]
hello,
Can you try out https://github.com/DefectDojo/django-DefectDojo/pull/1752? should be better

```
git fetch origin pull/1752/head:pr-1752
git checkout pr-1752
```

**Comment by dsever** [comment]
@ptrovatelli, it works with few minor fixes. But looks like docker images have been created from dev repo (and some functionalities are broken)

**Comment by ptrovatelli** [comment]
yes master tend to be a bit behind. most of us are working on dev. 
there are more fixes on dev branch since PR 1752
if you have fixes that are not on dev, you're welcome to share :)

**Comment by ptrovatelli** [comment]
this also is not on dev yet: 
https://github.com/DefectDojo/django-DefectDojo/pull/1881
