### ISSUE TITLE
Product list sorting / filtering issues

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#1811]
**Bug description**
The Product list page has some issues with:
- (Default) sorting
- Filter panel

**Sorting**
1. Go to /product
2. Observe that initial page load shows product list sorted by product name in ascending order (OK)
3. Observe that after page load the javascript takes over and sort the list by product name in descending order (NOK)
4. Observe that hoovering over the arrow at the product name table header has tooltip "sort descending" (NOK)
5. Click on that anyway
6. Observe that the javascript sorts the list by product name in ascending order (OK/NOK)
7. Parallel to that the page is reloaded with server-side sorting in descending order replacing the product list completely (OK/NOK)

So all in all a conflict between client-side and server-side sorting I think. I think this was added at some point last 6 months but I am only seeing it now because I never updated the static files :-D
Somebody added it so hopefully also somebody know how this front-end stuff works :-)

**Filter panel**
1. Go to /product
2. Observe that initial page load does not show the filter panel (OK)
3. Click on the arrow at product name table header to sort 
4. Observe that the page reloads and now shows the filter panel (NOK)
5. Same happens if you click on page 2 or next page for example.

**Expected behavior**
I am not a fan of client-side sorting, especially in a paged situation. So my vote would be to remove the client-side sorting.
I think the filter panel should only be shown when explicitly chosen by the user as on other pages in DD.

**Deployment method** *(select with an `X`)*
- [X] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Debian Stretch, Ubuntu 19.04
 - Latest dev branch (89aa6f9eeedb09889d8ef9d12372397b09335d41)

![image](https://user-images.githubusercontent.com/4426050/73125947-12787e00-3fad-11ea-851e-fc6399655685.png)

**Comment by valentijnscholten** [comment]
Hmm it seems to be working when using `runserver`. But behind nginx the above happens, tried on two different machines. Debian and Ubuntu. Some kind of settings I'm missing?

**Comment by valentijnscholten** [comment]
Hold on, might be caused by some side effects of merging somebody elses branches. Let me double check.

**Comment by dougmorato** [comment]
I think you are be right..... I added the datatables and I have been noticing some weird sorting issues recently. I also believe the conflict is between server vs client sorting.

I have been wanting to improve the datatables to get the native (or JSON) data objects and IT then generating the table, instead of monkey-patching  the table after the fact which causes some issues (paging, column visibility, sorting...)

I can't fix this week, but happy to take a look next week at this.

**Comment by ycrumeyrolle** [comment]
@dougmorato same issue with the severity and date filters of the finding list.

**Comment by valentijnscholten** [comment]
this is mostly resolved now by all the javascript related fixes that went in. the only thing left is that we have 2 ways of sorting, client-side and server-side, but that would be a bigger separate change  if needed.
