### ISSUE TITLE
Replace django-tagging with somethings else, i.e. django-tagulous

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#1812]
**Current situation**
Currently DD is using `django-tagging` for tagging products and findings: https://github.com/Fantomas42/django-tagging

I would like to replace this, because:
- it's a performance bottleneck. it's using raw queries underneath, so we can't use `select_related` and `prefetch_related` to have decent performance when rendering lists of products/findings (N+1 queries problem)
- it's old and maybe no longer maintained (latest release Oct '17)
- it's missing features that at some point might be interesting, such as autocomplete.
- tags are not deleted for tests/engagements/products that are deleted, so stuff remains behind in the database 

I'm working on optimizing the queries for the product list page, finding list page, product type list page and active engement page. Most of the queries can be optimized, except the ones related to tags/django-tagging.

**Describe the solution you'd like**
At first I was looking at `django-tagging` but it looks like 'django-tagulous' is the best combination of features and ease of use: https://github.com/radiac/django-tagulous

It's using django models and foreign keys, so everything related to that works as usual, including select_related, prefetch_related and Prefetch.

There is example pseudo code to use django migrations to migrate away from django-tagging.

Some more info: http://radiac.net/projects/django-tagulous/documentation/introduction/#comparison-with-other-tagging-libraries

**Next steps**
Before implementing this I would like some feedback on whether this sounds like a good idea, possible alternatives and of course the chances you would approve to merge this into dev after review/testing.

**Comment by valentijnscholten** [comment]
would be good @devGregA  @aaronweaver @mtesauro to get your feedback here as well.

**Comment by valentijnscholten** [comment]
Also there is currently no way to remove a tag from an object. Maybe by hassling with strings and comma seperated lists.

**Comment by jvz** [comment]
I've been wanting to query things using tags recently, and the current tag library seems fairly limited there. Tagulous looks like a fairly nice improvement to me in multiple ways reading through their docs. I'd love to see this.

**Comment by madchap** [comment]
Tags should become prime citizens. I would also welcome the change.

**Comment by jvz** [comment]
Update: I've figured out how to query tags properly using the existing library, though I'd still welcome this change as it would make tag integration much easier to take advantage of.

**Comment by adracea** [comment]
I was testing with our current django-tagging in order to make a PR for the API by tags , I've managed to get it working fairly easy with the APIv1 in tastypie , I made a tags endpoint where you can get all tags and all items tagged with them based on model (i.e. : list of findings,tests,engagements with tag banana ) . Made all tags appear in the APIs when querying an item , like engagement 1 will also contains the list of tags it has attached to it .
The way this works , I'd need to only make a few changes to APIv1 , I'd have to look into APIv2 to know how to make that one work but should be fairly easy .

**Comment by adracea** [comment]
@valentijnscholten I see that the article was written by the creator of the library , I've looked at a few things and noticed that taggit is still maintained while tagulous is not ? I'm going to do a deep dive next week and see what I can come up with tho .

**Comment by valentijnscholten** [comment]
Taggit is in jazzband which usually means the original author has left and it is maintained by them. But it could be also a viable option. I am reaching 200 products soon, so scalability is important for me. Would like the new library / integration to have:
- prefetch_related support
- orm caching support
Basically means it has to use django relationships like ForeignKey / ManyToMany.

**Comment by valentijnscholten** [comment]
If we merge #2012 the performance penalty from current `django.taggit` will be largely removed so the need to migrate to a different tagging library is lower, especially since such a migration needs a somewhat complex database migration.
