### ISSUE TITLE
Implement NodeJsScan parser

### ISSUE THREAD

**Issue by karthik137** [DefectDojo/django-DefectDojo#1824]
**Bug description**
I am unable to import NodeJsScan report. The API doesn't have a key-type called 'NodeJsScan'. I am using docker setup with hot reloading.

**Environment information**
 - Operating System: [Ubuntu16.04]

**Screenshots** (optional)
![defectdojo](https://user-images.githubusercontent.com/19289544/73236157-6060d200-41b7-11ea-9ede-8bd8755f0f84.png)

**Comment by valentijnscholten** [comment]
Could you explain what steps you are doing? Are you uploading via the api (if yes, v1 or v2?).
The screenshot is from the UI, so are you uploading through the UI?
And what type of scan are you uploading? There is Node Security Platform or NPM Audit available in Defect Dojo.

**Comment by valentijnscholten** [comment]
Looks like this is not a bug but a request to support the SAST reports from https://github.com/ajinabraham/nodejsscan

**Comment by karthik137** [comment]
Hi @valentijnscholten  check this issue https://github.com/ajinabraham/nodejsscan/issues/149

Yes i was using UI. I don't remember the exact version. Let me check that.

**Comment by dmaselbas** [comment]
Hi, I just ran into this as well. 

Just a heads up that the docs do say that this tool is supported.  @devGregA I have a report to share but I need to get it to you via some other channel. GitHub is just a little too public.

![image](https://user-images.githubusercontent.com/4480337/89065364-bfe79800-d328-11ea-939b-3045c8c24447.png)
https://defectdojo.readthedocs.io/en/latest/integrations.html

**Comment by blue4209211** [comment]
Hey,
I am also facing similar issue, can you please let me know steps to resolve this.

**Comment by spmishra121** [comment]
@dmaselbas Which version you are using. I am using defectdojo version 2.6.1 and I am not seeing any option to upload nodejsscan report.
![image](https://user-images.githubusercontent.com/6615148/153826053-7e188241-c5fa-4220-9c53-ebbf3ef64513.png)

**Comment by valentijnscholten** [comment]
Node JS Scans are currently not supported. If a proper sample is provided we can look at implementing it.

**Comment by jonny64** [comment]
@valentijnscholten could you please look at it?
```
git clone git@github.com:do-/dia.js.git
docker run -v $PWD:/src --rm -it opensecurity/nodejsscan:v4.7 nodejsscan --json /src
```
available formats are `--sarif, --sonarcube, --json`, are any of they supported?

what I need is somehow pass to defectdojo code snippet (`physicalLocation.region.snippet` for --sarif)

**Comment by damiencarol** [comment]
@jonny64 the format SARIF is supported and maintained.
@karthik137 could you try to use SARIF format?

**Comment by manuel-sommer** [comment]
What is the status here? Is someone interested to try out SARIF outpput and share a sample report if SARIF won't work?

**Comment by manuel-sommer** [comment]
I guess this is stale @mtesauro
