### ISSUE TITLE
PDf option not available in report builder

### ISSUE THREAD

**Issue by cpandya2909** [DefectDojo/django-DefectDojo#1830]
**Bug description**
I have used docker-compose to bring up defectdojo but I am not seeing PDf option for reporting.

**Steps to reproduce**
1. git clone https://github.com/DefectDojo/django-DefectDojo.git
2. cd django-DefectDojo
3. docker/setEnv.sh release
4. docker-compose build
5. docker-compose up
6. login to defectdojo
7. Go to Report Builder. There is only 1 option on report type which is ascii

**Expected behavior**
Report builder should show PDF option also.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 16.04

**Comment by Maffooch** [comment]
At this time, the report builder only supports asciidoc reports. There are pdf reports for products, engagements, and tests available in the main dropdown menu of each of those items. They are still pretty customizable as well.

**Comment by NRGLine4Sec** [comment]
Hi @cpandya2909 I have already request this possibility in #1299.
