### ISSUE TITLE
Upgrade some componets to the latest. 

### ISSUE THREAD

**Issue by Hax0rG1rl** [DefectDojo/django-DefectDojo#1840]
**Is your feature request related to a problem? Please describe**

Deploying the package through docker-compose I have seen a couple of component out-of-date. 

**Describe the solution you'd like**

Would you consider upgrading them? This one is quite interesting: _Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue_

**Additional context**

```
warning @yarn_components/mocha > jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
warning @yarn_components/mocha > glob > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning @yarn_components/mocha > glob > graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > @yarn_components/metisMenu@3.0.5" has unmet peer dependency "jquery@^3.3.1".
[5/5] Building fresh packages...

```

**Comment by valentijnscholten** [comment]
We have dependabot alerting us to bump versions, especially for security related updates. Not sure if it covers the yarn/nodejs items, but feel free to post a PR (against the dev branch)

**Comment by madchap** [comment]
It was set to only security updates. Turned that off to get a broader scope, let's see what it comes up with. I am afraid that we'll be drown in dependabot storms, however, so we may have to give boundaries to dependabot at some point.

**Comment by valentijnscholten** [comment]
resolved by revamping npm/yarn, updating as much as possible and following dependabot PRs.
