### ISSUE TITLE
Testing environment is down

### ISSUE THREAD

**Issue by ycrumeyrolle** [DefectDojo/django-DefectDojo#1843]
**Bug description**
Hi, the testing environment is down and produce an HTTP 503 error.

**Steps to reproduce**
1. Go to https://defectdojo.herokuapp.com/
2. Enjoy the error

![image](https://user-images.githubusercontent.com/1958836/73744801-dc2bc300-4751-11ea-87af-e1cb2a53f152.png)

**Comment by dr3dd589** [comment]
Hi @ycrumeyrolle, We are working on this  #1648 
Thanks.
