### ISSUE TITLE
API V2 documentation is API key  protected

### ISSUE THREAD

**Issue by ycrumeyrolle** [DefectDojo/django-DefectDojo#1844]
**Bug description**
The API V2 documentation should be accessible by an authenticated user. With the version 1.5.4 RC6 the page /api/v2/doc/ is token protected, being not accessible through a browser.

**Steps to reproduce**
1. Go to '/api/v2/doc/'
2. See error '401 Unauthorized'

**Expected behavior**
Expect to have the same behavior than the API V1 documentation

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - DefectDojo version 1.5.4 RC6 docker image

**Console logs** (optional)
Got the WWW-Authenticate: Token response header, meaning that the server is expecting the API key in the Authorization header.

**Comment by valentijnscholten** [comment]
Did you also try `dev` branch? For me it's working both the same v1 and v2 in dev branch. I can view both swagger docs when logged in. Token only needed to perform actions from the swagger UI.

**Comment by ycrumeyrolle** [comment]
Was an issue with the reverse proxy fronting the DD instance. 
Removing some rewrite rules on it fixed the issue. 
Closed  !
