### ISSUE TITLE
Production install steps are not working  

### ISSUE THREAD

**Issue by MagicScorpion** [DefectDojo/django-DefectDojo#1845]
**Bug description**

**Steps to reproduce**
1. Go to 'https://defectdojo.readthedocs.io/en/latest/running-in-production.html'
2. Follow  'Running in Production' steps
3. See error

Prompts for DefectDojo's admin login HERE

==============================================================================
  End of interactive portion of the installer
==============================================================================

==============================================================================
  Determining installation OS
==============================================================================

==============================================================================
  OS type for install is Linux
==============================================================================

==============================================================================
  Linux install on Red Hat Enterprise Linux Server version 7.7
==============================================================================

==============================================================================
  Bootstrapping required installer dependencies
==============================================================================

==============================================================================
  Install user is root, sudo access not required, continuing installation
==============================================================================

##############################################################################
#  ERROR: Unknown or NIY OS - exiting                                        #
#############################################################################

**Expected behavior**
If you follow the "Running in Production" step then you should be able to install defectdojo in production.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [X] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Red Hat Enterprise Linux Server version 7.7
 - DefectDojo Commit Message: [use `git show -s --format="%h: %s [%ci]"`]
d8cd760: Merge pull request #1729 from DefectDojo/Maffooch-patch-1 [2020-01-03 18:41:53 -0600]

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

./setup.bash

        ____       ____          __     ____          _
       / __ \___  / __/__  _____/ /_   / __ \____    (_)___
      / / / / _ \/ /_/ _ \/ ___/ __/  / / / / __ \  / / __ \
     / /_/ /  __/ __/  __/ /__/ /_   / /_/ / /_/ / / / /_/ /
    /_____/\___/_/  \___/\___/\__/  /_____/\____/_/ /\____/
                                               /___/

 Welcome to DefectDojo! This is a quick script to get you up and running.
 For more info on how setup.bash does an install, see:
   https://github.com/DefectDojo/django-DefectDojo/tree/master/setup

==============================================================================
  Starting interactive DefectDojo installation
==============================================================================

  Choose install type: setup.bash supports the following install types:

    (1) Single Server - Everything on one OS/server/container

    (2) Dev Install - Single Server install with all default install options
        & passwords

    (3) Stand-alone Server - DefectDojo installed on a separate OS/server/
        container then the database

Select install type: (1) Single-Server, (2) Dev Install or (3) Stand-alone: 3

==============================================================================
  Select database type
==============================================================================

Select database type: (1) SQLite, (2) MySQL or (3) PostgreSQL: 2

==============================================================================
  Select if database is remote or local to this install
==============================================================================

  Will the MySQL database be local (on the same OS) or remote for this install?

Select (1) Remote, (2) Local: 2

==============================================================================
  Select if database should be installed during setup
==============================================================================

  Will the MySQL database be installed during setup or does it already exist?

Select (1) Install of MySQL required, (2) MySQL server already exists/is running: 2

==============================================================================
  Keep existing Defect Dojo database if found?
==============================================================================

  If the installer finds an existing DefectDojo database, should it be dropped?

Select (1) Drop existing database, (2) Keep existing database & exit: 1

==============================================================================
  Install settings for local database that already is installed
==============================================================================

  Please update database config to reflect the existing local database

==============================================================================
  Prompting for DB options
==============================================================================

  Change DB name from dojodb? (1) Yes, (2) No, keep the default: 1

    Enter a new DB name: defectdojo

  Change DB user from dojodbusr (1) Yes, (2) No, keep the default: defectdojo
    Error: Please enter 1, or 2
  Change DB user from dojodbusr (1) Yes, (2) No, keep the default: 1

    Enter a new DB user: defectdojo

  Change DB password from osX8y6vi)3GIpfl4Z0GM(yu7 (1) Yes, (2) No, keep this password: 1

    Enter a new DB password: defectdojo

  Change DB port from 3306 (1) Yes, (2) No, keep this port number: 2

  Keeping DB port of 3306

==============================================================================
  Install settings for OS configuration
==============================================================================

  Current OS install config includes:
    OS user to run Dojo as:             dojo-srv
    Password for OS user:               Wi+&lCyqdFDAN!+(yHX8!k(E
    Group for the OS user:              dojo-srv
    Install root directory:             /opt/dojo
    DefectDojo source directory:        /opt/dojo/django-DefectDojo
    Directory of files created by Dojo: /opt/dojo/local
    Directory of uploads/media of Dojo: /opt/dojo/local/media
    Directory of static files for Dojo: /opt/dojo/local/static

  Do you want to change any of these values?

Select (1) Yes, (2) No: 2

  OK. Keeping default OS configuration values for this install

==============================================================================
  Install settings for Defect Dojo application configuration
==============================================================================

  Current admin user config for DefectDojo:
    Admin user to log into Dojo:  admin
    Password for the admin user:  BYLiOcG9iN4Xm2jJd@Wo3##j
    Email for the admin user:     ed@example.com

  Do you want to change any of these values?

Select (1) Yes, (2) No: 1

Prompts for DefectDojo's admin login HERE

==============================================================================
  End of interactive portion of the installer
==============================================================================

==============================================================================
  Determining installation OS
==============================================================================

==============================================================================
  OS type for install is Linux
==============================================================================

==============================================================================
  Linux install on Red Hat Enterprise Linux Server version 7.7
==============================================================================

==============================================================================
  Bootstrapping required installer dependencies
==============================================================================

==============================================================================
  Install user is root, sudo access not required, continuing installation
==============================================================================

##############################################################################
#  ERROR: Unknown or NIY OS - exiting                                        #
##############################################################################

[root@lx-vm28 django-DefectDojo]# git show -s --format="%h: %s [%ci]
> "
d8cd760: Merge pull request #1729 from DefectDojo/Maffooch-patch-1 [2020-01-03 18:41:53 -0600]

**Additional context** (optional)

**Comment by MagicScorpion** [comment]
We would like to use defectdojo in our production environment. We want to install it on  "Red Hat Enterprise Linux Server release 7.7".
Please provide us the installation steps. We do not want to use docker version in our production environment.

**Comment by syntillations** [comment]
Facing the same issue with RHEL 7.6. Any guidance on this issue will be helpful

**Comment by valentijnscholten** [comment]
Did you try dev or master? dev is the one to be used.
Currently the script only supports certain ubuntu versions and centos versions. The scripts are not too hard to understand and RHEL should be similar to CentOS. I looked at the docker containers to install locally, as the Dockerfile(s) more are less are telling us what steps are needed to install it.

**Comment by spaluchowski** [comment]
When this is expected to be fixed?

**Comment by devGregA** [comment]
The script is working as intended. We limited OS support for production a while back to mitigate certain OS specific drifts in packages. I recommend Ubuntu 18.04 LTS. We realize documentation is a sore spot right now. Updating docs is high priority.
