### ISSUE TITLE
Various filters are overloaded by duplicate findings listings

### ISSUE THREAD

**Issue by jvz** [DefectDojo/django-DefectDojo#1846]
**Bug description**
Some of the advanced filters for findings will not exclude the `duplicate_list` and `duplicate_finding` fields which leads to long page load times and slow UIs with large amounts of data.

**Steps to reproduce**
1. Go to 'Closed Findings'
2. Click on the filter button on the top right.
3. See "Duplicate finding" and "Duplicate list" filters.

**Expected behavior**
Don't have those filters.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Commit Message: [use `git show -s --format="%h: %s [%ci]"`]

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

**Comment by jvz** [comment]
Some sort of common set of filtered fields for `Finding` could be maintained which avoids the duplication of effort whenever new fields are added that may or may not be useful for searching/filtering.

**Comment by valentijnscholten** [comment]
To add to this: the filters are slow in general because every query is executed twice by django-filter.

**Comment by valentijnscholten** [comment]
Would be interesting to see of this is still an issue after the recent changes regarding the duplicate_list vs duplicate_finding field.
