### ISSUE TITLE
Add not exclusion on calendar 

### ISSUE THREAD

**Issue by amnesik** [DefectDojo/django-DefectDojo#1850]
Hello :)

I wanted to ask you one question, it is about calendar.

- we use a script to automatically import nessus scan in an engagement, to automatically see what has been corrected for critical assets we know the IP adress won't change. The engagement duration is many years  and we re-upload the new nesses scans on the same Test. Is it the best way to do it ? It is cool because when we correct something it will be updated on defectdojo when the new scan is uploaded.
- But we have a little problem on calendar. each engagement is displayed on calendar and it is annoying, forinstance :

![image](https://user-images.githubusercontent.com/6387451/73944166-69a61900-48f2-11ea-8dc4-ca7593b9cea7.png)

Can we add a feature to display only some users by default, or to filter without an account (automatic_scan in our case). Or am i wrong by doing automatic scans this way ?

Thanks in advance for your answer !

Goodbye

**Comment by valentijnscholten** [comment]
Are you using CI/CD engagements? It would make sense maybe if we do not show these on the calendar as they are typically long runing / continuous.

**Comment by devGregA** [comment]
I believe that continuous engagements are not shown on the calendar.
