### ISSUE TITLE
Sonatype parser fails to deduplicate when the `pathnames` is too big

### ISSUE THREAD

**Issue by ycrumeyrolle** [DefectDojo/django-DefectDojo#1851]
**Bug description**
The deduplication is failing on findings imported from the Sonatype parser when the `pathnames` property is huge (thanks to NPM...). 
The `file` field of the created finding is truncated to 4001 characters.
@madchap 

**Steps to reproduce**
1. Import a scan result of type Sonatype
2. Import the same scan result within a second test
3. The "too long pathnames" findings are not tagged as duplicated

**Expected behavior**
The second test should contains only duplicated findings

**Sample scan files** 
Here is a scan result file with two findings. The first one has a big `pathnames` property, the second one has a "small" `pathnames` property:
[sonatype_test.json.txt](https://github.com/DefectDojo/django-DefectDojo/files/4166651/sonatype_test.json.txt)

**Comment by ycrumeyrolle** [comment]
https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/sonatype/parser.py#L109

Maybe replacing 
```
            file_path = ' '.join(vulnerability['pathnames'])
```
by 
```
            file_path = ' '.join(vulnerability['pathnames'])[:4000]
```

**Comment by urand0m** [comment]
>  file_path = ' '.join(vulnerability['pathnames'])[:4000]

I don't think the fix is there the error does not happen at the serializer level but it comes from restrictions of the model.

from models.py 

```
file_path = models.CharField(null=True, blank=True, max_length=1000)
```
Maybe a blob? not so sure about how this can be fixed.

I have a report from Sonatype in which one of the file_path length is even 356134 chars, so the solution would be not to include all the file_paths or modifying the model.

**Comment by ptrovatelli** [comment]
I'd say we can truncate the field upon import if it's too big.

**Comment by ycrumeyrolle** [comment]
Any update on this bug?

**Comment by devGregA** [comment]
@ycrumeyrolle I'm sorry we're so backlogged. Thank you for including the a sample scan! I'm working to get some more resources to validate and prioritize bugs.

**Comment by valentijnscholten** [comment]
The way sonatype reports this makes no sense. Why flagging every single javascript file in the lodash package? Just one filepath pointing to the lodash package would suffic. 
Still I don't know why deduplication is not working as an import of the exact same file will result in the exact same filepath (truncated at 1000)?
Anyway, I suggest we change the sonatype parser to use some other field for filepath. Nobody needs 1000+ filepaths crunched together in one charfield :-)

**Comment by ycrumeyrolle** [comment]
> Anyway, I suggest we change the sonatype parser to use some other field for filepath. Nobody needs 1000+ filepaths crunched together in one charfield :-)

I do agree, we do not use this for tracking the vulnerabilities.

**Comment by valentijnscholten** [comment]
truncating it to 1000 seems to work. I think the saontype parser needs more work, but at least this bug is fixed now.

**Comment by devGregA** [comment]
Believed to be fixed. Please reopen if this is not correct.
