### ISSUE TITLE
Multiple Docker Build ERROR

### ISSUE THREAD

**Issue by frankyyyyyyy** [DefectDojo/django-DefectDojo#1861]
Having a few issues with my current build of DefectDojo and am looking to take the master branch to do some testing on the newer version to see if its my build or bugs and having a few issues with the docker build.

**Bug description**
Seeing a range of ERRORS in the Docker build process.

`ERROR: django-auditlog 0.4.5 has requirement python-dateutil==2.6.0, but you'll have python-dateutil 2.8.0 which is incompatible.                                                                                                     
ERROR: django-overextends 0.4.3 has requirement django<2.0,>=1.8, but you'll have django 2.2.4 which is incompatible.qq`

`ERROR: django-auditlog 0.4.5 has requirement python-dateutil==2.6.0, but you'll have python-dateutil 2.8.0 which is incompatible.
ERROR: django-overextends 0.4.3 has requirement django<2.0,>=1.8, but you'll have django 2.2.4 which is incompatible.`

A bunch of warnings are also returned but not sure if these are going to cause an issue at this stage.

`warning @yarn_components/mocha > jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
warning @yarn_components/mocha > glob > graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
warning @yarn_components/mocha > glob > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`

**Steps to reproduce**

- git clone <repo> (master)
- docker-compose build

**Expected Behaviour**

Build without errors.

**Environment**

- Docker version 19.03.5-ce on Arch

**Console Logs**

A subset of console logs in case it might be useful:

`
Processing /tmp/wheels/pyasn1-0.4.8-py2.py3-none-any.whl                                                                                                                                                                              
Processing /tmp/wheels/smmap2-2.0.5-py2.py3-none-any.whl                                                                                                                                                                              
Processing /tmp/wheels/zipp-1.1.0-py2.py3-none-any.whl                                                                                                                                                                                
Processing /tmp/wheels/Jinja2-2.11.1-py2.py3-none-any.whl                                                                                                                                                                             
Processing /tmp/wheels/MarkupSafe-1.1.1-cp35-cp35m-manylinux1_x86_64.whl                                                                                                                                                              
Building wheels for collected packages: django-custom-field, django-tastypie-swagger                                                                                                                                                  
  Building wheel for django-custom-field (setup.py): started                                                                                                                                                                          
  Building wheel for django-custom-field (setup.py): finished with status 'done'                                                                                                                                                      
  Created wheel for django-custom-field: filename=django_custom_field-2.9-py3-none-any.whl size=9826 sha256=0097bb6b799b2f6b6835c19dc3bf714f6c3293875da5e12031a493ffadc7fefe                                                          
  Stored in directory: /tmp/pip-ephem-wheel-cache-c_rqdfwj/wheels/6f/59/9e/9b3c0e3b0c4f98b9a324754773e75c4185bcd9cb2b11cc125d                                                                                                         
  Building wheel for django-tastypie-swagger (setup.py): started                                                                                                                                                                      
  Building wheel for django-tastypie-swagger (setup.py): finished with status 'done'                                                                                                                                                  
  Created wheel for django-tastypie-swagger: filename=django_tastypie_swagger-0.1.4-py3-none-any.whl size=170084 sha256=2baeb808e6cc45788adfbf4db61f8cd3fd76ac6802d3a5d8d34e812626bbc606                                              
  Stored in directory: /tmp/pip-ephem-wheel-cache-c_rqdfwj/wheels/e7/aa/b1/0c68c8e17e28e977dde43efe040c92038d55f7b7e669b340e1                                                                                                         
Successfully built django-custom-field django-tastypie-swagger                                                                                                                                                                        
ERROR: django-auditlog 0.4.5 has requirement python-dateutil==2.6.0, but you'll have python-dateutil 2.8.0 which is incompatible.                                                                                                     
ERROR: django-overextends 0.4.3 has requirement django<2.0,>=1.8, but you'll have django 2.2.4 which is incompatible.                                                                                                                 
Installing collected packages: numpy, six, asteval, webencodings, bleach, bleach-whitelist, billiard, vine, pytz, zipp, importlib-metadata, amqp, kombu, celery, coverage, defusedxml, django-celery-results, python-dateutil, sqlpars
e, Django, django-jsonfield, django-auditlog, django-custom-field, django-dbbackup, django-environ, django-filter, django-appconf, pilkit, django-imagekit, django-multiselectfield, django-overextends, django-polymorphic, djangores
tframework, simplejson, MarkupSafe, jinja2, coreschema, uritemplate, urllib3, certifi, chardet, idna, requests, itypes, coreapi, openapi-codec, django-rest-swagger, django-slack, django-tagging, django-taggit, django-taggit-serial
izer, django-tastypie-swagger, python-mimeparse, django-tastypie, django-watson, gunicorn, html2text, humanize, pyjwt, pycparser, cffi, asn1crypto, cryptography, oauthlib, requests-oauthlib, pbr, requests-toolbelt, jira, lxml, Mar
kdown, mysqlclient, pandas, pdfkit, Pillow, psycopg2-binary, pygments, python-nmap, redis, sqlalchemy, meld3, supervisor, uWSGI, vobject, whitenoise, titlecase, python3-openid, social-auth-core, social-auth-app-django, ecdsa, futu
re, pyasn1, rsa, Python-jose, smmap2, gitdb2, gitpython                                                                                                                                                                               
Successfully installed Django-2.2.4 Markdown-3.1.1 MarkupSafe-1.1.1 Pillow-6.0.0 Python-jose-3.0.1 amqp-2.5.2 asn1crypto-1.3.0 asteval-0.9.14 billiard-3.6.2.0 bleach-3.1.0 bleach-whitelist-0.0.10 celery-4.3.0 certifi-2019.11.28 cf
fi-1.14.0 chardet-3.0.4 coreapi-2.3.3 coreschema-0.0.4 coverage-4.5.3 cryptography-2.7 defusedxml-0.6.0 django-appconf-1.0.3 django-auditlog-0.4.5 django-celery-results-1.1.1 django-custom
`

`
Collecting python3-openid>=3.0.10; python_version >= "3.0" (from social-auth-core>=1.2.0->social-auth-app-django==3.1.0->-r ./requirements.txt (line 52))                                                                             
Collecting pyasn1>=0.1.3 (from rsa->Python-jose==3.0.1->-r ./requirements.txt (line 53))                                                                                                                                              
Collecting smmap2>=2.0.0 (from gitdb2>=2.0.0->gitpython>=2.1.13->-r ./requirements.txt (line 54))                                                                                                                                     
Collecting zipp>=0.5 (from importlib-metadata>=0.18; python_version < "3.8"->kombu<5.0,>=4.4.0->celery==4.3.0->-r ./requirements.txt (line 5))                                                                                        
Collecting jinja2 (from coreschema->coreapi>=2.3.0->django-rest-swagger==2.1.2->-r ./requirements.txt (line 18))                                                                                                                      
Collecting MarkupSafe>=0.23 (from jinja2->coreschema->coreapi>=2.3.0->django-rest-swagger==2.1.2->-r ./requirements.txt (line 18))                                                                                                    
Building wheels for collected packages: django-custom-field, django-tastypie-swagger                                                                                                                                                  
  Building wheel for django-custom-field (setup.py): started                                                                                                                                                                          
  Building wheel for django-custom-field (setup.py): finished with status 'done'                                                                                                                                                      
  Created wheel for django-custom-field: filename=django_custom_field-2.9-cp35-none-any.whl size=9825 sha256=c508aec034b47ba2b7387d05f686452e5eff12385f9074086106da627d41f713
  Stored in directory: /tmp/pip-ephem-wheel-cache-dea559s0/wheels/1f/80/54/96282fa201cd4a45b500d621356ee348d43cebf1133dc7b797
  Building wheel for django-tastypie-swagger (setup.py): started
  Building wheel for django-tastypie-swagger (setup.py): finished with status 'done'
  Created wheel for django-tastypie-swagger: filename=django_tastypie_swagger-0.1.4-cp35-none-any.whl size=170085 sha256=bbdcac28f48b0188ebfb42a6250d302db9158b5dca1720196a6502ef448c0789
  Stored in directory: /tmp/pip-ephem-wheel-cache-dea559s0/wheels/db/47/ff/9112c9c8a2c16fdb7d836153822ba59216b6cd6dab80bee002
Successfully built django-custom-field django-tastypie-swagger
ERROR: django-auditlog 0.4.5 has requirement python-dateutil==2.6.0, but you'll have python-dateutil 2.8.0 which is incompatible.
ERROR: django-overextends 0.4.3 has requirement django<2.0,>=1.8, but you'll have django 2.2.4 which is incompatible.
Installing collected packages: six, numpy, asteval, webencodings, bleach, bleach-whitelist, zipp, importlib-metadata, vine, amqp, kombu, pytz, billiard, celery, coverage, defusedxml, django-celery-results, python-dateutil, sqlpars
e, Django, django-jsonfield, django-auditlog, django-custom-field, django-dbbackup, django-environ, django-filter, django-appconf, pilkit, django-imagekit, django-multiselectfield, django-overextends, django-polymorphic, uritempla
te, itypes, MarkupSafe, jinja2, coreschema, certifi, idna, urllib3, chardet, requests, coreapi, openapi-codec, simplejson, djangorestframework, django-rest-swagger, django-slack, django-tagging, django-taggit, django-taggit-serial
izer, django-tastypie-swagger, python-mimeparse, django-tastypie, django-watson, gunicorn, html2text, humanize, pbr, asn1crypto, pycparser, cffi, cryptography, pyjwt, oauthlib, requests-toolbelt, requests-oauthlib, jira, lxml, Mar
kdown, mysqlclient, pandas, pdfkit, Pillow, psycopg2-binary, pygments, python-nmap, redis, sqlalchemy, meld3, supervisor, uWSGI, vobject, whitenoise, titlecase, python3-openid, social-auth-core, social-auth-app-django, ecdsa, futu
re, pyasn1, rsa, Python-jose, smmap2, gitdb2, gitpython
Successfully installed Django-2.2.4 Markdown-3.1.1 MarkupSafe-1.1.1 Pillow-6.0.0 Python-jose-3.0.1 amqp-2.5.2 asn1crypto-1.3.0 asteval-0.9.14 billiard-3.6.2.0 bleach-3.1.0 bleach-whitelist-0.0.10 celery-4.3.0 certifi-2019.11.28 cf
fi-1.14.0 chardet-3.0.4 coreapi-2.3.3 coreschema-0.0.4 coverage-4.5.3 cryptography-2.7 defusedxml-0.6.0 django-appconf-1.0.3 django-auditlog-0.4.5 django-celery-results-1.1.1 django-custom-field-2.9 django-dbbackup-3.2.0 django-en
viron-0.4.5 django-filter-2.0.0 django-imagekit-4.0.2 django-jsonfield-1.4.0 django-multiselectfield-0.1.8 django-overextends-0.4.3 django-polymorphic-2.0.1 django-rest-swagger-2.1.2 django-slack-5.13.0 django-tagging-0.4.6 django
-taggit-1.2.0 django-taggit-serializer-0.1.7 django-tastypie-0.14.2 django-tastypie-swagger-0.1.4 django-watson-1.5.2 djangorestframework-3.9.4 ecdsa-0.15 future-0.18.2 gitdb2-2.0.6 gitpython-3.0.7 gunicorn-19.9.0 html2text-2018.1
.9 humanize-0.5.1 idna-2.8 importlib-metadata-1.5.0 itypes-1.1.0 jinja2-2.11.1 jira-2.0.0 kombu-4.6.7 lxml-4.3.3 meld3-2.0.0 mysqlclient-1.4.2 numpy-1.18.1 oauthlib-3.1.0 openapi-codec-1.3.2 pandas-0.25.3 pbr-5.4.4 pdfkit-0.6.1 pi
lkit-2.0 psycopg2-binary-2.8.2 pyasn1-0.4.8 pycparser-2.19 pygments-2.4.2 pyjwt-1.7.1 python-dateutil-2.8.0 python-mimeparse-1.6.0 python-nmap-0.6.1 python3-openid-3.1.0 pytz-2019.1 redis-3.2.1 requests-2.22.0 requests-oauthlib-1.
3.0 requests-toolbelt-0.9.1 rsa-4.0 simplejson-3.17.0 six-1.14.0 smmap2-2.0.5 social-auth-app-django-3.1.0 social-auth-core-3.2.0 sqlalchemy-1.3.13 sqlparse-0.3.0 supervisor-4.0.3 titlecase-0.12.0 uWSGI-2.0.18 uritemplate-3.0.1 ur
llib3-1.25.3 vine-1.3.0 vobject-0.9.6.1 webencodings-0.5.1 whitenoise-5.0.1 zipp-1.1.0
Removing intermediate container fab4716f29bd
`

**Comment by AlexanderTyutin** [comment]
During my build I see such kind of warnings too, but the build is successful.

```
ERROR: django-auditlog 0.4.5 has requirement python-dateutil==2.6.0, but you'll have python-dateutil 2.8.0 which is incompatible.
ERROR: django-overextends 0.4.3 has requirement django<2.0,>=1.8, but you'll have django 2.2.4 which is incompatible.
```

**Comment by AlexanderTyutin** [comment]
As I can see the first error is from other project: https://github.com/jjkester/django-auditlog/issues/162

**Comment by AlexanderTyutin** [comment]
There is a good explanation about second error: https://stackoverflow.com/questions/50507194/mezzanine-4-2-3-has-requirement-django1-11-1-8-but-youll-have-django-2-0-2

**Comment by ptrovatelli** [comment]
there are often this kind of errors but they don't seem to cause issue in the application. Ideally though , dependencies version should be finely tuned to avoid those as it could cause issues.
