### ISSUE TITLE
Introduce use of feature flags

### ISSUE THREAD

**Issue by jvz** [DefectDojo/django-DefectDojo#1871]
**Is your feature request related to a problem? Please describe**
There are a few optional features and in-development features that could be hidden behind proper feature flags using some sort of feature flag framework. The current application will make frequent database queries to check if runtime-toggleable features are enabled.

**Describe the solution you'd like**
A proper feature flag framework for enabling and disabling optional, beta, and experimental features rather than ad hoc system settings or global Django settings booleans. One example I found while searching was https://github.com/django-waffle/django-waffle.

**Describe alternatives you've considered**
There are other feature flag frameworks available for Python, though I'm not very familiar with the competition.

**Comment by jvz** [comment]
I'll note that adopting use of feature flags would allow for trunk-based development which significantly reduces the burden for making new releases. New features can be developed and only enabled by those who want to use and test them first.

**Comment by madchap** [comment]
Could be really useful for https://github.com/DefectDojo/django-DefectDojo/pull/1362
