### ISSUE TITLE
API: Possibility to generate and remove users through the API. 

### ISSUE THREAD

**Issue by Dorfus1988** [DefectDojo/django-DefectDojo#1873]
**Is your feature request related to a problem? Please describe**
There is no way to generate and remove users through the API to automate e.g. the switch of service owners. 

**Describe the solution you'd like**
I would like to have a way to generate and remove users through the API to automate e.g. the switch of service owners.

**Comment by cpandya2909** [comment]
@valentijnscholten , please help us to provide a programmatical way create or delete users or provide any other solution by which we can onboard users in bulk.

**Comment by valentijnscholten** [comment]
If you use SAML integration, user accounts will be autocreated.
