### ISSUE TITLE
Bulk "Set finding to Verified" set the findings to "Inactive"

### ISSUE THREAD

**Issue by ycrumeyrolle** [DefectDojo/django-DefectDojo#1876]
**Bug description**
When bulk updating the findings to the "Verified" status, the "Active" findings are set to "Inactive", which seems to be a non-sense.

**Steps to reproduce**
1. Go to Findings view
2. Select 2 or more "Active" findings 
3. Click on the Bulk Edit and submit a "Verified" status

**Expected behavior**
A "Verified" finding should remain "Active" as long as is is remediated of accepted.

**Environment information**
DefectDojo 1.5.4 RC6

**Comment by valentijnscholten** [comment]
Could you try with dev branch? master is very old.

**Comment by valentijnscholten** [comment]
The way this works is that you need to check all of the status fields that you want to become or stay checked. So if you are marking active findings as verified, you need to both check the active box and the verified box.

**Comment by ycrumeyrolle** [comment]
Ok I understand the behavior. Not the expected at first glance, but it's ok.
Related to #1875, causing some trouble to understand :)

**Comment by valentijnscholten** [comment]
no problem.
