### ISSUE TITLE
Unsupported OS on Ubuntu 19.10 through setup.bash

### ISSUE THREAD

**Issue by viral-sangani** [DefectDojo/django-DefectDojo#1883]
**Bug description**
While installing Defect-dojo on Ubuntu 19.10, getting an Error of Unsupported OS version - 19.10

**Steps to reproduce**
1. Cloned latest master branch from django-DefectDojo repository on Ubuntu - 19.10
2. Navigate to setup dir.
3. run `sudo setup.bash`
4. Provided all the required input
5. Got Unsupported OS version for wkthml - 19.10

**Expected behavior**
Should have installed successfully.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [x] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System:  Ubuntu 19.10
 - DefectDojo Commit Message: `Merge pull request #1729 from DefectDojo/Maffooch-patch-1 [2020-01-03 18:41:53 -0600]`

**Console logs**
```
===========================================================================
  Installing wkhtml for PDF report generation 
===========================================================================

===========================================================================
  Error: Unsupported OS version for wkthml - 19.10
===========================================================================

    Error: Unsupported OS version - 19.10
```

**Comment by viral-sangani** [comment]
I found this bug while installing DefectDojo on latest Ubuntu 19.10 Version.
If it's okay I would like to solved this bug.

**Comment by ptrovatelli** [comment]
Hello @viral-sangani ,
currently 19.10 is not supported; see https://github.com/DefectDojo/django-DefectDojo/blob/master/setup/README.MD :
`Ubuntu Linux - officially supported versions: 16.04 LTS, 18.04 LTS`

If you have time to handle this upgrade, we'll be glad for you to do so. @mtesauro anything special to know? Is there any ongoing work on this? 
thanks
