### ISSUE TITLE
[k8s] initializer

### ISSUE THREAD

**Issue by dsever** [DefectDojo/django-DefectDojo#1890]
**Bug description**

I'm using helm (from DEV),  when launching initializer there I'm getting:

psycopg2.errors.UndefinedTable: relation "defectdojo_engagement_survey_question" does not exist
LINE 1: select polymorphic_ctype_id from defectDojo_engagement_surve...
 
From logs I can conclude that, problem is with case sensitivity?

helm in master repo is not supporting helm 3

Thanks

**Steps to reproduce**

**Expected behavior**

**Deployment method** *(select with an `X`)*
- [X] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Commit Message: [use `git show -s --format="%h: %s [%ci]"`]

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

**Comment by dsever** [comment]
Ok, it now works for me.

There is misconiguration in ingress:

servicePort http->80

Also for config map, we should allow probes:
DD_ALLOWED_HOSTS: "*"
If we allow host only, that liveness problem will trigger problem.

**Comment by dsever** [comment]
But if calling system_settings it crashes the application, looks like latest docker images were not build by master repo (using docker- compose it looks ok)?

**Comment by dsever** [comment]
Looks like problem ```psycopg2.errors.UndefinedTable: relation "defectdojo_engagement_survey_question" does not exist``` only exists in postgresql config, while solution for psql gives an error for mysql.

**Comment by ptrovatelli** [comment]
I think i have this error too, still the application is working; i'm not using surveys though

**Comment by athurm** [comment]
We have this error in postgresql configuration too, but system settings working.

**Comment by ptrovatelli** [comment]
i never use the images from dockerhub; always build my own. 

dockerhub is from master i think but before yesterday master was monthes old and missing many fixes. 

we updated master yesterday, the images should be more recent now

**Comment by dsever** [comment]
@athurm this error reflects only to Survay, with system_settings was something else (I'm not sure 100% what  is it)

**Comment by athurm** [comment]
system_settings not working if rabbitMQ not working ... 

> we updated master yesterday, the images should be more recent now

https://hub.docker.com/r/defectdojo/defectdojo-django/tags
latest still seams a month old :/

**Comment by ptrovatelli** [comment]
my bad, I thought this was automatic :)
still, building local images is the best way to use whatever version you need and be sure that the images you work with contain the code you're looking at. you don't even need a private registry with the `imagePullPolicy=Never` parameter

**Comment by athurm** [comment]
seams not that easy here:
 Found existing installation: pip 19.3.1
    Uninstalling pip-19.3.1:
ERROR: Could not install packages due to an EnvironmentError: [Errno 39] Directory not empty: '/usr/local/lib/python3.5/site-packages/pip-19.3.1.dist-info/'

can you upload it on dockerhub pleassssee :-)

**Comment by dinvlad** [comment]
So is there any workaround for this for now?

**Comment by dsever** [comment]
@dinvlad, for what, to retrieve new image of for postgres problem? In anycase I'm using option to build new image for myself and I'm pushing it to my private dockerhub

**Comment by dinvlad** [comment]
@dsever yep, we've just patched and rebuilt it thanks to your https://github.com/DefectDojo/django-DefectDojo/issues/1890#issuecomment-589996536 (I was confused before). It'd be nice to have this patched upstream though. Do I understand correctly that quoting the table in this case makes it incompatible with MySQL (so this patch is blocked atm)?

**Comment by dsever** [comment]
So there are 2 options, one is to detect mysql vs postgres and than execute query (I see it as antipattern).

The other permanent solution is rename table to proper naming, but I don't know how it will reflect to the logic behind and upgrade procedure.

**Comment by ptrovatelli** [comment]
@dsever what would be the proper naming?

**Comment by dsever** [comment]
I would say that issues come from non standard naming of the table (defectdojo_engagement_survey_question), so some reason pqsql doesn't understand it or sees some unsupported chars or keywords.

Or this could be the case:
```Postgresql treats identifiers case insensitively when not quoted (it actually folds them to lowercase internally), and case sensitively when quoted; many people are not aware of this idiosyncrasy. Using always lowercase you are safe. Anyway, it's acceptable to use camelCase or PascalCase (or UPPER_CASE), as long as you are consistent: either quote identifiers always or never (and this includes the schema creation!).```

And we have: in query: 

```
cursor.execute("select polymorphic_ctype_id from defectDojo_engagement_survey_question;")
```

Or even during the table creation...

This is something that has to be tested

**Comment by ptrovatelli** [comment]
quoting will be problematic. for mysql it's backquotes, for other engines it's double quotes. 
If the case is really the issue, I don't see any clean solution except for putting everything in lower case but that's a lot of impacts 

Note that the default database when using docker-compose is mysql while with kubernetes it's postgresql. Alghough it's easy to switch to mysql in kubernetes if you really need the surveys (but i find the postgres helm chart is better thanks to the statefulset). 
the contrary is not true (using postgres with docker-compose is not trivial)

@Maffooch what's your take on this? have you ever tried using surveys with a postgresql database?

**Comment by dsever** [comment]
As kind of workaround we can build separate images, for init job, but the problem is if we want to use generic helm from the repo.
