### ISSUE TITLE
default docker-compose setup is broken after 1.5.4rc3

### ISSUE THREAD

**Issue by xens** [DefectDojo/django-DefectDojo#1907]
**Bug description**
The default docker-compose installation is not working

**Steps to reproduce**

Follow the setup instructions on the README.md file:

```
git clone https://github.com/DefectDojo/django-DefectDojo
cd django-DefectDojo
# building
docker-compose build
# running
docker-compose up
```
The containers are correctly built and started:

```shell
Starting django-defectdojo_rabbitmq_1 ... done
Starting django-defectdojo_mysql_1    ... done
Recreating django-defectdojo_uwsgi_1        ... done
Recreating django-defectdojo_celerybeat_1   ... done
Recreating django-defectdojo_initializer_1  ... done
Recreating django-defectdojo_celeryworker_1 ... done
Recreating django-defectdojo_nginx_1        ... done
```
but the ```manage.py migrate``` always stack-traces:

```shell
initializer_1   | Operations to perform:
initializer_1   |   Apply all migrations: admin, auditlog, auth, authtoken, contenttypes, custom_field, defectDojo_engagement_survey, django_celery_results, dojo, sessions, sites, social_django, tagging, tastypie, watson
initializer_1   | Running migrations:
initializer_1   |   Applying django_celery_results.0005_taskresult_worker... OK
initializer_1   |   Applying django_celery_results.0006_taskresult_date_created... OK
initializer_1   |   Applying django_celery_results.0007_remove_taskresult_hidden... OK
initializer_1   |   Applying dojo.0028_finding_indices... OK
initializer_1   | Traceback (most recent call last):
initializer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
initializer_1   |     return self.cursor.execute(sql, params)
initializer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
initializer_1   |     return self.cursor.execute(query, args)
initializer_1   |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 209, in execute
initializer_1   |     res = self._query(query)
initializer_1   |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 315, in _query
initializer_1   |     db.query(q)
initializer_1   |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/connections.py", line 239, in query
initializer_1   |     _mysql.connection.query(self, query)
initializer_1   | MySQLdb._exceptions.ProgrammingError: (1146, "Table 'defectdojo.django_site' doesn't exist")
```
and thus the program is not able to serve requests:

```shell
$ curl -L 127.0.0.1:8080              
<h1>Server Error (500)</h1>%                                
```
**Expected behavior**

The DB migration should succeed and the program start

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 19.10
 - DefectDojo Commit Message: 6a635336: Merge pull request #1892 from DefectDojo/owasp-link-invite-update-master [2020-02-18 11:29:03 -0500]

**Comment by madchap** [comment]
Hi @xens 

Please try tag `1.5.4rc6` for now (that one should work, if not, please let us know at it is the candidate to be merged to `master` soon...ish...), something may have broke in `dev`, will need to get a new instance to check it out, hopefully this week-end.

Thanks.

**Comment by xens** [comment]
thanks @madchap for your suggestion.

I tried with the ```1.5.4rc6``` version as suggested and it's not better, I've got the same stack-trace from ```initializer_1```.

I also tried to docker prune all my older images and rebuild everything from scratch without luck.

**Comment by xens** [comment]
Ok I gave a try to ```1.5.4rc2``` and this one is working, the only major difference that I can see is that all the images are pre-built so there's nothing to build or compile, on ````1.5.4rc6``` docker-compose was building the ```uwsgi``` container.

```shell
$docker-compose build
mysql uses an image, skipping
initializer uses an image, skipping
uwsgi uses an image, skipping
nginx uses an image, skipping
rabbitmq uses an image, skipping
celeryworker uses an image, skipping
celerybeat uses an image, skipping
```

**Comment by xens** [comment]
Did a couple of more tests the last working version is ```1.5.4rc3```

**Comment by madchap** [comment]
Ok that's really weird, because these tags are really old and it was clearly working after that, so there is something else I guess.

When you tried again, did you also delete the mysql docker volume? If not, this would certainly be why it didn't work when you tried rc6.

**Comment by madchap** [comment]
I cleaned up my stuff, then pulled latest `dev` as of just now (`471ae8d7f7c154ddf4106aae03f0b3dce3c5cbf7`)

- `docker-compose rm -vf`
- `docker volume rm madchap_ddojo_defectdojo_data` (whatever is yours...)
- `docker-compose build`

 then `docker-compose up -d` and everything went as expected :thinking:

I am not sure what went wrong there.

**Comment by xens** [comment]
Awesome, thanks @madchap ! That was the mysql volume messing things up. With all my tests going back and forth between version I ended up with a broken / non-migrable database. Removing the mysql volume and rebuilding everything from scratch now works for both the ```dev``` and ```1.5.4rc6```.

Closing this one.
