### ISSUE TITLE
Development environment documentation

### ISSUE THREAD

**Issue by dsever** [DefectDojo/django-DefectDojo#1908]
Hi,

Can someone explain procedure to run development environment, I would like to test SAML integration but I'm not able to run DEV environment.

I'm getting ``` Migration defectDojo_engagement_survey.0001_initial dependencies reference nonexistent parent node ('dojo', '0001_initial')
```

But probable I missed something.

Thanks

**Comment by AlexanderTyutin** [comment]
@dsever In this PR https://github.com/DefectDojo/django-DefectDojo/pull/1905 I put quick and easy way to get dev env (as I was need to run it too).
May be it will help you. Also there is a transparent README placed.
You can find clear repo with those scripts [here](https://github.com/AlexanderTyutin/django-DefectDojo/tree/dev/setup/single-container) while PR https://github.com/DefectDojo/django-DefectDojo/pull/1905 is not merged yet.

**Comment by dsever** [comment]
Thanks I will take a look.

**Comment by ptrovatelli** [comment]
hello; what did you run exactly? dev environment using docker-compose should work : https://github.com/DefectDojo/django-DefectDojo/blob/dev/DOCKER.md
you need to use dev branch though, master is ancient.

**Comment by dsever** [comment]
@ptrovatelli,

This looks nice, I was't aware of docker documentation. I was simply trying to, run docker-compose with overwriting with dev settings, and than launch server locally (I test it it works)  

At the end looks like i don't need SAML to integrate dojo with keycloak, I can use SOC_AUTH (https://github.com/python-social-auth/social-core/blob/master/social_core/backends/keycloak.py). 

I will close this, tnx
