### ISSUE TITLE
Default values for Dependency Checker

### ISSUE THREAD

**Issue by eaguade-bodas** [DefectDojo/django-DefectDojo#1915]
**Bug description**
When the DependencyCheck report is imported from the XML, if Description / Mitigation or/and Impact value is not properly loaded (with None value), the import process fails and the then the last finding is stored with empty values which it causes a lot of 500 errors.

**Steps to reproduce**
1. Go to Engagement-> Select Scan Type to Dependency Check
2. Load the XML file exported from the tool.
3. Click on Upload.

**Expected behavior**
Should import all findings.

**Console logs** (optional)
`
celeryworker_1  | [2020-02-21 14:00:46,956: INFO/MainProcess] Task tool_issue_updater[51adb98c-0c8c-4aca-a131-af39d7284565] succeeded in 0.00042003399994428037s: None
uwsgi_1         | applying rules
uwsgi_1         | item blowup
uwsgi_1         | jquery.mobile-1.0.js | 94317
uwsgi_1         | Internal Server Error: /engagement/1/import_scan_results
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
uwsgi_1         |     return self.cursor.execute(query, args)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 209, in execute
uwsgi_1         |     res = self._query(query)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 315, in _query
uwsgi_1         |     db.query(q)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/MySQLdb/connections.py", line 239, in query
uwsgi_1         |     _mysql.connection.query(self, query)
uwsgi_1         | MySQLdb._exceptions.OperationalError: (1048, "Column 'description' cannot be null")
`

**Comment by valentijnscholten** [comment]
Thank you for your report. Could you check it against `dev`? `master` is very old and missing lots of changes.

**Comment by eaguade-bodas** [comment]
Hi, I've modified to set only default values only for description, which was the problem; and leaving Impact and Mitigation empty.
Check against DEV and working perfectly.
