### ISSUE TITLE
Mitigated finding upon re-import keeps on commenting

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1926]
**Bug description**
When a finding is found to be mitigated through a scan re-import (e.g. fixed upstream), DD adds a comment and changes the finding's status to Inactive, Mitigated.

However, on further re-import iterations, it keeps on adding comments. So we can end up having multiple useless comments as re-imports occur.

![image](https://user-images.githubusercontent.com/5468769/75250466-b6d22800-57d8-11ea-9dee-0a3ea58d800d.png)

**Steps to reproduce**
1. Import a scan
2. Re-import over it, having removed findings from the report. This should tell DD the finding is mitigated, as not found anymore in the uploaded report.
3. Notice the finding status change and comment
4. Re-import the same report as in step 2.
5. Notice a comment is again being added.

**Expected behavior**

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
Latest `dev` as of today.

**Comment by valentijnscholten** [comment]
yes I have seen this also and fixed in my branch: https://github.com/valentijnscholten/django-DefectDojo/tree/reupload_mitigate_only_once will make a PR soon.

**Comment by madchap** [comment]
This was fixed by the related PR.
