### ISSUE TITLE
Migrations Error in Dev Branch

### ISSUE THREAD

**Issue by devGregA** [DefectDojo/django-DefectDojo#1944]
**Bug description**
Migrations error when running: cd /opt/dojo/django-DefectDojo && source ../bin/activate && python3 manage.py makemigrations --merge --noinput

 raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration defectDojo_engagement_survey.0001_initial dependencies reference nonexistent parent node ('dojo', '0001_initial')

**Steps to reproduce**
1. Run godojo installer: https://github.com/mtesauro/godojo

**Expected behavior**

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Commit Message: [use `git show -s --format="%h: %s [%ci]"`]

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

**Comment by madchap** [comment]
How old are your images?

**Comment by devGregA** [comment]
I'm not using any docker images. I'm using the godojo installer, which follows setup.bash

**Comment by madchap** [comment]
> I'm not using any docker images. I'm using the godojo installer, which follows setup.bash

Right, just saw the `godojo` ref.

**Comment by mahirrudin** [comment]
Hi, why this issue closed? any solution about this?
