### ISSUE TITLE
Docker-compose building error

### ISSUE THREAD

**Issue by AlexanderTyutin** [DefectDojo/django-DefectDojo#1950]
**Bug description**
Unable to run current `dev` code under docker-compose:
```
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

**Steps to reproduce**
1. Install Ubuntu 18.04 and Upgrade to latest LTS release 18.04.4
2. Install latest versions of docker (https://docs.docker.com/install/linux/docker-ce/ubuntu/) and docker-compose (`apt-get install docker-compose`)
3. Clone django-DefectDojo repository
4. Switch to `dev` branch
5. Go to django-DefectDojo directory
6. Run command `docker-compose build` according to manual

**Expected behavior**
Building containers those are required to run application

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 18.04.4

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
```
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

**Additional context** (optional)

**Comment by valentijnscholten** [comment]
What version of docker-compose do you have? Latest can be installed with something like
`sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose`

**Comment by ptrovatelli** [comment]
hello,
can we close this? probably a wrong version of docker-compose installed

**Comment by ptrovatelli** [comment]
closing for now; don't hesitate to re-open if really needed :)
