### ISSUE TITLE
Push to JIRA option when Importing findings (UI and API)

### ISSUE THREAD

**Issue by Apipia** [DefectDojo/django-DefectDojo#1973]
**Is your feature request related to a problem? Please describe**
Would be nice to be able to import findings and check "Push these new findings to Jira" so one doesn't have to take an extra step to bulk edit findings and push them to Jira.

**Describe the solution you'd like**
A Push To Jira checkbox on the import/re-import findings UI, one that, when checked, will push all resulting Findings to whatever JIRA configuration (if one exists) for the product. Adding this functionality to the import/re-import API endpoints as well.

**Describe alternatives you've considered**
There is also the option of creating API endpoints for JIRA related actions as well. Possibly updating the PUT for Findings to include a PushToJira boolean value that will allow an API user to send a request to push the issue to JIRA. 
Or a separate endpoint all together that takes a list of Finding ID's and performs similar logic to the bulk edit that will push all findings to JIRA.
OR a various /jira/ endpoints that can exist on Products, engagements, tests, that will push all of those findings within each to JIRA. 
PUT jira/engagement/{engagement_id}
PUT jira/product/{product_id}
With empty bodies? 
Looking for feedback here.

**Additional context**
I wouldn't mind implementing these (or attempting to implement them) but I'm looking for some community feedback on the best approach.

**Comment by valentijnscholten** [comment]
There is a checkbox on Product settings called 'Push all issues' which is supposed to do this, but it doesn't work. As far as I can see it's only partially implemented and some parts are commented out. Probably because somebody stopped halfway implementing it.
I can definately see a usecase for this, especially for companies which are based completely of JIRA for developer workloads (such as mine).

**Comment by Apipia** [comment]
> There is a checkbox on Product settings called 'Push all issues' which is supposed to do this, but it doesn't work. As far as I can see it's only partially implemented and some parts are commented out. Probably because somebody stopped halfway implementing it.
> I can definately see a usecase for this, especially for companies which are based completely of JIRA for developer workloads (such as mine).

Yeah I've noticed this as well. Do you think it's supposed to enlist it in some celery-based task that constantly keeps the issues synced..? Or possibly any time a finding is edited in a product where that's been checked, it calls the push-to-jira action? That might not be a bad method, I could just try to see if that's an implementation I could finish.

**Comment by valentijnscholten** [comment]
I think from what I saw it was only the initial push to JIRA that was (partly) implemented.
Pushing on every edit might go a bit to far as it might overwrite stuff in JIRA. So maybe start with the initial creation in JIRA to be automated and then take it from there? Maybe we want to add automatic syncing as well, but as a separate feature with separate flag?

**Comment by madchap** [comment]
I'd see other JIRA enhancements before this one actually. I'd be afraid that creating JIRA like crazy would create so much noise that you'd make the engineering teams tired and hate you :-)

But why not! :-)

**Comment by Apipia** [comment]
> I'd see other JIRA enhancements before this one actually. I'd be afraid that creating JIRA like crazy would create so much noise that you'd make the engineering teams tired and hate you :-)
> 
> But why not! :-)

Currently our team is implementing an automated pipeline that will take findings that are imported via API/automation into defect dojo and create JIRA tickets as a result. I don't quite have a preference _where_ the "push to JIRA" functionality lives, as long as I can get to it via automation (the API). Even if I have to loop through every Finding and hit an endpoint to "Push to JIRA", that's fine, I just need the endpoint.
What might be the most effective way to introduce this? And also, what are the other JIRA enhancements you'd like to see before this one?

**Comment by madchap** [comment]
Actually, I just got a use-case now to have that API endpoint ;-) so go go go :100: 

For others, we have #1724 still opened. Other ideas could be:
* Be able to add/edit/delete the JIRA info of a finding straight from the UI 
* Be able to have labels added to the JIRA issue (not only a component)
* Be able to template what fields/info goes from DD to JIRA. Today is hard-coded AFAIK.

**Comment by Apipia** [comment]
> Actually, I just got a use-case now to have that API endpoint ;-) so go go go 💯

Just want to clarify, you're in favor of updating existing endpoints to allow push to jira? (such as PUT/POST on /finding/ and POST import and POST re-import?
Or separate endpoint altogether for a myriad of JIRA functionality?

**Comment by Apipia** [comment]
I've got something coded right now I'm testing. Involves moving the "Should I update JIRA" logic into the .save() method for a Finding. Seems like a more logical place for it.
Let me know if that goes against some paradigm I'm not aware of.

**Comment by madchap** [comment]
I don't have an opinion on the actual implementation today.

The `jira_finding_mappings` is there and I guess useful, I used it a few times to manually update relationships between DD and Jira. 

If you want to submit a Draft PR (little arrow to change the PR "submit" button "submit Draft" (or something like that), then we can take a look at what you have.

**Comment by Apipia** [comment]
I'll probably have a PR up today sometime in the next few hours. Just have to make a feeew more changes.
