### ISSUE TITLE
How to work with multiple URL's in Same Issue (scanner import)

### ISSUE THREAD

**Issue by gautammayekar** [DefectDojo/django-DefectDojo#1975]
So, I have a question here with regards to multiple URL's reported in scanners for a same issue. 

For Eg. An IBM Appscan report says XSS vulnerabilities found and it has around 10 URL's out of which 4 are false positives. How to tackle this problem. 

I only get an option to tick the whole XSS issue as False positive. I would like to have few URL's / Parameters flagged as false positives and few as not.

**Comment by gautammayekar** [comment]
Hi, 

Any update on this?

**Comment by madchap** [comment]
This is currently not supported, and would probably require more than just a parser update.

**Comment by gautammayekar** [comment]
Hi,

Thanks for the response. Any plans to support this feature in future?

**Comment by gautammayekar** [comment]
Hello, any progress and discussions on this? 
Kindly let me know,

Thanks.

**Comment by cody-m-tibco** [comment]
Hello @gautammayekar, there is a notion of remediated endpoints that allow a user to mark a specific endpoint as remediated or still vulnerable. After remediation, it will be moved to another dropdown box in the finding view. Though it does not mark the endpoint as any of the status' a finding could have, it may be of good use to you. Currently, the remediation only applies to the host, but it should apply to the path instead. I can fix that for you. What do you think?

**Comment by devGregA** [comment]
@cody-m-tibco please reference this issue in your PR when ready.

**Comment by Maffooch** [comment]
Fixed
