### ISSUE TITLE
Permission weirdness when creating engagement and test

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1977]
**Bug description**
A couple months ago, a user could create a new engagement and import a new test with the following rights

- "Active", and granted explicit access to the product.
- Under `/admin`, be granted the following rights

![image](https://user-images.githubusercontent.com/5468769/75870741-b7d40c80-5e0b-11ea-8daf-1e8ab1c40a34.png)

Today, at commit `14eb162463d89039e3911ba0f4b851bc170843f3` on `dev`, I am getting a 403 error when wanting to create a new test. However, a new engagement can still be created without the need for the user to belong to `staff`.

Both actions apparently require `@user_passes_test(lambda u: u.is_staff)` though. So why would the engagement creation succeed and not the test creation? I would add "anymore" since it used to work for test a couple months ago on my instance. 

That setup was used in pipelines, which all started failing to create new tests after an update.

**Steps to reproduce**

**Expected behavior**

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**

`14eb1624: Merge remote-tracking branch 'refs/remotes/origin/dev' into dev [2020-03-03 08:38:25 +0000]`

**Comment by madchap** [comment]
Moreover, re-importing findings in an already existing test works without `staff` too, whereas it seems that it also checks for the `u.is_staff` permission.

**Comment by madchap** [comment]
OK found the culprit...

https://github.com/DefectDojo/django-DefectDojo/blob/dev/dojo/api_v2/views.py#L617

So now, while I just hit a "regression" via the API, the UI checks permissions differently.

fyi @jvz

**Comment by jvz** [comment]
Oh, I think I remember why I added that line. The django security model was preventing my staff user from accessing this API. I think it was checking the authorized users and ignoring for the `is_staff` bit. Might be a bug either way?

**Comment by madchap** [comment]
> Oh, I think I remember why I added that line. The django security model was preventing my staff user from accessing this API. I think it was checking the authorized users and ignoring for the `is_staff` bit. Might be a bug either way?

That's weird, because it's been this way for a long time and used by all imports that go through the API?

Just tested without it, works actually :thinking:

**Comment by jvz** [comment]
May have been user error :)

**Comment by valentijnscholten** [comment]
What I am interested in is if this:
_- Under /admin, be granted the following rights_
_- Can add engagement_
_- Can add test_
Is actually needed/working/effective? I think someone told me these permission flags under /admin don't do anything. But I may be wrong. Another thing maybe that needs some documentation.

**Comment by madchap** [comment]
Using that exactly in my production environment. Works for the API, probably not for a regular "UI" user.

**Comment by valentijnscholten** [comment]
And if you remove those permissions it doesn't work anymore?

**Comment by madchap** [comment]
Correct.
