### ISSUE TITLE
Ability to filter by status in test view

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1988]
**Is your feature request related to a problem? Please describe**
At the moment, you can't filter test findings by status.

Having an easy way to filter findings by status would help in navigating the many findings scan imports can have.

**Describe the solution you'd like**
1. on the column itself (if the datatable permits) ?
2. To the left of the number of pages of the report?

![image](https://user-images.githubusercontent.com/5468769/76086903-5f407300-5fb5-11ea-80ae-f0a674490ff7.png)

**Comment by Maffooch** [comment]
This was somewhat implemented in #1884 in the filter dropdown

**Comment by madchap** [comment]
Yes, it seems this is there for the `/finding`, but not when viewing under `/test/{id}`.

**Comment by valentijnscholten** [comment]
I think it is there as the changes from #1884 are actually causing the problem seen in #1995.

**Comment by madchap** [comment]
Addressed by https://github.com/DefectDojo/django-DefectDojo/pull/2365
