### ISSUE TITLE
Can no longer bulk edit findings

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#1995]
**Bug description**

The checkboxes remain greyed out, unable to select new status.

![image](https://user-images.githubusercontent.com/5468769/76110125-354f7680-5fde-11ea-9425-937a084fbefc.png)

Latest `dev`

**Comment by valentijnscholten** [comment]
Which version/commit are you running and on which page are you trying this? For me it works running very close to `dev`

**Comment by madchap** [comment]
http://localhost:8080/test/{test_number}

**Comment by valentijnscholten** [comment]
confirmed, I see the problem as well. May or may not be related to javascript errors:
![image](https://user-images.githubusercontent.com/4426050/76321107-d93c6900-62e1-11ea-8d50-85e3a9946091.png)

**Comment by valentijnscholten** [comment]
Confirmed it is cause by #2000

**Comment by valentijnscholten** [comment]
It was caused by an impartial fix in e35dcc46e9d712f11e0ea85c5619ee7ed68f584c. Everywhere we use `findings_list.html` template to render lists of findings, except here (in `view_test.html`).
