### ISSUE TITLE
fix datatables dependency

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#1999]
**Bug description**
It seems like the javascript `datatables` library is included in two ways in the project.
Via `dojo/static/dojo/js/datatables.min.js` and via a dependency in `package-json`.
The former is included in the html so looks like that is the one being used. However that file is generated by the downloader at https://datatables.net/download/ and should include `pdfmake`. However, in the defect dojo logs there are `404` errors for `dojo/static/dojo/js/pdfmake.min.js.map` which is weird, or maybe a bug in the generated datatables.min.js. 

**Expected behavior**
I would say that we should choose one way of including datatables and it makes the most sense to use the `npm/yarn` to do this: https://datatables.net/download/npm

**Environment information**
- dev branch 28822ced96024a4b5d84a62c84b47870a8d1ad66 and master branch 1.5.4.1.

**Comment by madchap** [comment]
Closing here per the merged PR, please re-open if I am wrong @valentijnscholten.

**Comment by valentijnscholten** [comment]
It's not resolved. My understanding is:
- DD includes a staticly linked datatables.js in the static/dojo/static folder, downloaded from datatables.net. I think this should be removed in favor of a proper npm/yarn dependency
- DD also includes a dependency declaration in package-json, which is also bundled, but in static/datatables. I don't think these are used, but I do think this is the proper way to include dependencies.
- Same for 2 datatables plugins declard in package-json. Are they used or should they be removed?

**Comment by 00rex00** [comment]
package-json is used by Yarn to prepare /components .. the manage.py collectstatic prepares the /static folder

**Comment by valentijnscholten** [comment]
So?

**Comment by JoseRoman** [comment]
1+ to keeping only one import, also agree with using npm/yarn as this is more maintainable and the best overall option.

**Comment by valentijnscholten** [comment]
Fixed by #2861
