### ISSUE TITLE
Open Findings views are not consistent

### ISSUE THREAD

**Issue by ycrumeyrolle** [DefectDojo/django-DefectDojo#2013]
Findings views from `Products` and Finding views form `Findings` are not consistent with the notion of `Open`.
Findings -> Open Findings: include all findings with the Active status
Product -> Open FIndings: include all findings with the Active status, except False positive

Identified on version 1.5.4 RC6.

**Comment by madchap** [comment]
Relates to https://github.com/DefectDojo/django-DefectDojo/pull/1896 and there should have been a PR fixing this, but can't find it...

**Comment by madchap** [comment]
> Product -> Open FIndings: include all findings with the Active status, except False positive

Actually, a finding is not allowed to be both Active and False-positive at the same time -- at least through the UI. I know that crazy things can happen through the API, however, including states whereby a finding should not be in...

**Comment by ycrumeyrolle** [comment]
This is also occurring with the checkmarx parser, and probably with other parsers.

**Comment by madchap** [comment]
It is not a per-parser behavior, but global.
