### ISSUE TITLE
/finding/accepted title is incorrect

### ISSUE THREAD

**Issue by ycrumeyrolle** [DefectDojo/django-DefectDojo#2014]
The accepted findings is displayed as ` Tool Configuration List`. This might be `Findings`.

![image](https://user-images.githubusercontent.com/1958836/76239830-848de500-6232-11ea-98a4-470a1585f4c0.png)

Found in 1.5.4RC6

**Comment by valentijnscholten** [comment]
I can see it see when you first go to http://defectdojo/tool_config and then to http://defectdojo-dev/finding/accepted

**Comment by FlyingLos** [comment]
Looks like the accepted_findings() and closed_findings() in /dojo/finding/views.py don't have anything for updating/adding a breadcrumb.

Would the correct display be to show the breadcrumb ? Or no breadcrumb at all ?
Example: <img width="320" alt="Screen Shot 2020-03-10 at 6 18 36 PM" src="https://user-images.githubusercontent.com/33731795/76364471-a0a98900-62fb-11ea-8080-817d1c1cd5c2.png">

https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/finding/views.py#L560-L585

**Comment by valentijnscholten** [comment]
Home findings I think.
