### ISSUE TITLE
"Other" type

### ISSUE THREAD

**Issue by httpnotonly** [DefectDojo/django-DefectDojo#2036]
**Scanner Name**
Just other plaintext report

**Sample File**
whatever

**Comment by valentijnscholten** [comment]
Could you elaborate on what your request is? Feature request? What is the expected result of a plain text file input?

**Comment by httpnotonly** [comment]
I just want to add my custom scanner output there

**Comment by valentijnscholten** [comment]
It's not clear what you're requesting, if you have a generic report you could try the csv importer: https://defectdojo.readthedocs.io/en/latest/integrations.html#generic-findings-import
