### ISSUE TITLE
Demo site down (Heroku)

### ISSUE THREAD

**Issue by codethatrocks** [DefectDojo/django-DefectDojo#2037]
**Bug description**
demo of defect dojo at https://defectdojo.herokuapp.com  not working

**Steps to reproduce**
1. call https://defectdojo.herokuapp.com/
2. See error 

**Deployment method** *(select with an `X`)*
- [x] Heroku Demo
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Comment by valentijnscholten** [comment]
known issue, new demo is in the works.

**Comment by jsimoni** [comment]
this issue / error with the demo site is still valid

**Comment by Ivanello** [comment]
demo still down

**Comment by jmj-uy** [comment]
demo still down

**Comment by mtesauro** [comment]
The old demo site is not going to come back.  However, the new demo site is available at:

https://demo.defectdojo.org/
Login with admin / defectdojo@demo#appsec

Its still being tweaked this week so it may by up and down more than usual.  Also, it gets fully deleted and re-installed every hour.

**Comment by mtesauro** [comment]
I'm going to go ahead and close this as the project has a new location for the demo site.
