### ISSUE TITLE
[Question] Active/Inactive findings behavior

### ISSUE THREAD

**Issue by ycrumeyrolle** [DefectDojo/django-DefectDojo#2038]
When importing a scan result, the Findings are always set to `Inactive`. 
When the user check the `Active` box, the Findings are set to `Active`, even if the Finding is marked as `False Positive`. 
![image](https://user-images.githubusercontent.com/1958836/76409463-aef4b500-638e-11ea-9f7b-a6dd6cc75c7a.png)

I do not understand the behavior. When I import findings from other tools, I assume them to be set as by default `Active` when not status is provided by the scanning tool (false positive, ...).  
For the moment, I force the `Active` checkbox, but this is causing issue by setting both flags `Active` & `False positive`, which should not be possible.

Identified on 1.5.4 RC6.

**Comment by valentijnscholten** [comment]
yeah nobody really knows how it is supposed to work and it works inconsequently across DD. It's on our list to fix. usually the import itself shouldn't set false positive, or is it a duplicate of an existing false positive? or which scanner are we talking about?

**Comment by ycrumeyrolle** [comment]
This is the Checkmarx scanner. I am also using the Sonatype scanner and I expect the same behavior(will take a look). These tools allow to qualify the defects, and I expect to not lose it when importing into DD.
