### ISSUE TITLE
finding images don't work in docker deployment

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#2045]
When running integration tests uploading of findings works fine, but when returning to the view finding page findings cannot be retrieved:

```
GET http://localhost:8080/static/dojo/img/zoom-in.cur 404 (Not Found)
5d242da1aa6aa4fd589e851648b9edf1.jpg:1 GET http://localhost:8080/media/CACHE/images/finding_images/e88bcf2b-5076-4078-b646-b0f2b4de4bbe/5d242da1aa6aa4fd589e851648b9edf1.jp
```
(errors from browser console)

`dev` at 3d3804589049ff538734b47d6147077caaea8998

**Comment by ClintCrawford** [comment]
I solved it this way
https://github.com/DefectDojo/django-DefectDojo/issues/1930

**Comment by valentijnscholten** [comment]
Thanks, I was hoping it was something easy to fix. Will take a look.

**Comment by valentijnscholten** [comment]
The main reason it was not working is because the images cannot be retrieved via nginx. Persistent volumes are indeed needed if you want to keep them working across restarts, but I already ran into the problem right after uploading the image. Will probably have a PR soon, might try to fix risk acceptance in one go.

**Comment by dayal18** [comment]
Any idea on how to fix this in setup.bash?
I have the same issue.

**Comment by dayal18** [comment]
the interesting thing is that the image exists at that location when I click the magnifying symbol, I see my URL changes to:

**http://localhost:8000/media/finding_images/2d53a220-da1a-40c3-8178-f9632a8f9207.png**

I looked at the server for the image, and I find the image at this location:
Command run on the server:

root@ip-10-31-23-147:/home/ubuntu# updatedb
root@ip-10-31-23-147:/home/ubuntu# locate 2d53a220-da1a-40c3-8178-f9632a8f9207.png
**/opt/dojo/django-DefectDojo/media/finding_images/2d53a220-da1a-40c3-8178-f9632a8f9207.png**
root@ip-10-31-23-147:/home/ubuntu#

----

and still I see 404..

**Comment by dayal18** [comment]
And in logs I see:
[09/Apr/2020 23:25:38] "**GET /media/CACHE/images/finding_images/2d53a220-da1a-40c3-8178-f9632a8f9207/eed88358fb41221c1db604dc4422efe4.jpg HTTP/1.1**" 404 22622

Any help please

**Comment by valentijnscholten** [comment]
Do you have the `/media` static file location setup in `nginx`?

**Comment by dayal18** [comment]
Yup.. I did add that location mentioned in #1930 in my ngnix.conf file under (/opt/dojo/django-DefectDojo/ngnix/ngnix.conf)

location /media {
      alias /usr/share/nginx/html/media;
    }

But I don't know if I'm using ngnix.. as I run the **python manage.py runserver 0.0.0.0:8000** to start the server..

![ngnix](https://user-images.githubusercontent.com/43857391/78998323-fe550f00-7b0d-11ea-9895-9da9cd4383c8.png)

**Comment by dayal18** [comment]
> I solved it this way
> #1930

@ClintCrawford 
How can I fix this in setup.bash?
Any help pls.
I'm running the Dojo with python3 manage.py runserver command...
