### ISSUE TITLE
all audit logs have empty actor_id (user)

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#2064]
Defect Dojo users `django-auditlog` to track changes to model fields. The log can be viewed via the View History menu option.

Currently all entries have `None` for the Actor column (`actor_id`). 

Database:

```
mysql> select actor_id from auditlog_logentry where actor_id is not null;
+----------+
| actor_id |
+----------+
0 rows in set
```` 

latest `dev` at 451ed448b74e92aaa48f63ac841462cc65664097

**Comment by ptrovatelli** [comment]
it seems this can be closed (fixed by https://github.com/DefectDojo/django-DefectDojo/pull/2067)
@valentijnscholten you confirm?

**Comment by valentijnscholten** [comment]
It seems to to work for changes made through the UI, but not for imports made through api_v2.
