### ISSUE TITLE
Import performance (slowness) considerations

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#2065]
The Import can be very slow if you have somewhat larger scans to be imported. I've heard some people complaining about this on Slack and other places.

From a high level there are 2 steps that we can take. They are not mutually exclusive, but I would like to start with step 2.

1) Make (re-)imports asynchronous.
This seems like a tempting approach because it would make the initial response very fast. But it also has a lot of downsides:
- How do we report back to the user the import was finished? What was the result?
- What do we do when an import doesn't finish or crash?
- What if an import is still running and (another) user tries to import the same file concurrently?
- What if the current (cicd) script using the API expects some stats in the response? (nr of issue imported, nr of duplicates, ...)
- What about the performance impact of running large imports in the background?
Because there are some relatively easy and big gains to be made in step 2, I think we should go for that first.

2) Simplify and Optimize (re-)import
We don't want to overoptimize, but looking at the import code there are some big performance gained to be made from simplifying things.
a) `finding.save()` is called 4 for times for each new finding.
`serializer.py` calls `finding.save()` twice. And `Finding.save()` itself calls `super().save()` twice.
This causes `django-auditlog` to have to calculate differences 4 times. And this causes 4-8 extra db queries. `django-watson` will update its search index 4 times, also 4 extra queries.
Simplifying this to be exactly *one* `save()` call will instantly make the import 4 times faster.

b) `watson` search index is updated syncrhonously during import.
This could be made asynchronously to speed up more. Might need some help from `django-watson` authors as they are using `post_save` signals which are synchronous by design
edit: turns out there is a middleware that deduplicates watson updates, which already helps. PR #2066 . Might be an interesting approach for auditlog as well.

c) notifications are created synchronously
By design defect dojo creates a notification for each user in the system. I have over 50 users in my system, resulting in 50 database queries. This could be made asynchronously and should be limited to `authorized` users for each product.

d) calculate *product* grade is performed after updating of * each finding*.
This should be done only at the end of the import once for each product. And preferably asynchronously.

I realize that starting this journey (simplifying) will impact some core pieces of code. So I would like to hear some feedback on this before starting. We could consider starting a 2.0 branch where we do stuff like this, including removing api v1, unify UI and api_V2 logic, ...

**Comment by devGregA** [comment]
1. Is something Matt T & I have been discussing recently. And the UI changes that would be necessary and what additional warnings we'd have to put next to metrics while uploads are being processed.

**Comment by ansidorov** [comment]
Too bad no further work/discussion has been done on this issue
