### ISSUE TITLE
Cannot create "generic" note if a custom note type was added

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#2069]
**Bug description**
If you create a custom note type, then you can no longer create a "regular" note (for lack of better word).

**Steps to reproduce**
1. Create a custom note type
2. Go to a finding
3. Try to create a note that is _not_ of that custom note type
4. You must select one.

**Expected behavior**
If not specifying a note type, it should still default to some "regular" note.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
`dev`

![image](https://user-images.githubusercontent.com/5468769/76755287-e2b34e80-6783-11ea-96f4-665cb516f507.png)

**Comment by madchap** [comment]
fyi @propersam if you'd be interested to hack a fix or something there?

**Comment by propersam** [comment]
🤔🤔
...hmm
Looks interesting..I can give it a go later today...
