### ISSUE TITLE
Cannot edit a note type to "is_single" if not created as such

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#2070]
**Bug description**
I am guessing a model issue if one were to then create mutliple note instance with that note type, and then think of reverting to is_single?

Culprit code would be at https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/forms.py#L227

**Steps to reproduce**
1. Create a note type, not single and possibly not mandatory
2. Try to edit that note type again
3. Notice you cannot make it "is_single" again

![image](https://user-images.githubusercontent.com/5468769/76756678-76861a00-6786-11ea-8fbb-9e5813376d28.png)

**Expected behavior**
Unsure.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Comment by madchap** [comment]
Maybe just a comment to indicate that it may be normal due to underlying database model constraints (if that's the case) would be a good step forward.

**Comment by madchap** [comment]
fyi @propersam I am sure you already have the answer to that one :)

**Comment by propersam** [comment]
> Culprit code would be at https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/forms.py#L227

From what I see in the referenced code in line 222

it's like 'is_single' was implemented for both create and update..it just wasn't added to the edit note type view...

Well, I think I need to investigate this further before arriving at any conclusions yet...will get back to u on this later. Likely, with a fix (nt active ATM)..

**Comment by madchap** [comment]
No problem man! I appreciate your fast response here :+1: No rush either :)

**Comment by valentijnscholten** [comment]
Could be that it is considered confusing / misleasing if a notetype was not is_single and some findings have multiple notes of that type. If the notetype then is switched to is_single=True, some code might expect to have at most 1 of that type of note for a finding and not multiple instances.
