### ISSUE TITLE
Crashtest & Fortify FPR Scan Import Server Error (500)

### ISSUE THREAD

**Issue by TheUnriashol** [DefectDojo/django-DefectDojo#2072]
**Bug description**
I get a Server Error 500 when trying to upload a Crastest(XML) or Fortify (FPR) Scan.

**Steps to reproduce**
1. Go to 'Findings'
2. Click on 'Import Scan Results'
3. Select Scan Type 'Crashtest' or 'Fortify'
4. Upload a file
5. Press on 'Import'

**Expected behavior**
I would expect the scan results to be imported into the project as findings.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Windows 10 Pro using Docker
 - Branch: Stable & Dev

**Sample scan files** (optional)
https://raw.githubusercontent.com/DefectDojo/sample-scan-files/master/crashtest_security/crashtest_security_v20190103.xml

https://raw.githubusercontent.com/DefectDojo/sample-scan-files/master/fortify/fortify_v18.20.1046.xml

**Console logs** (optional)

```
FINGERPRINTING (1)
Internal Server Error: /product/1/import_scan_results
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./dojo/product/views.py", line 438, in import_scan_results_prod
    return import_scan_results(request, pid=pid)
  File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./dojo/engagement/views.py", line 570, in import_scan_results
    if Finding.SEVERITIES[sev] > Finding.SEVERITIES[min_sev]:
KeyError: 'medium'
[pid: 18|app: 0|req: 19/21] 192.168.99.1 () {52 vars in 1271 bytes} [Thu Mar 19 11:18:11 2020] POST /product/1/import_scan_results => generated 27 bytes in 132 msecs (HTTP/1.1 500) 6 headers in 192 bytes (1 switches on core 0)
```

**Comment by Apipia** [comment]
Used your provided Fortify XML and ran it through an import and didn't receive any errors. 
According to the error message, your severity was 'a'?
Is the error log you submitted for Fortify or Crashtest?

**Comment by TheUnriashol** [comment]
@Apipia Thanks for checking over what I found. I just updated my issue. Seems like DefectDojo does not support Fortify FPR uploads?

But I am still having the issue with the Crashtest file upload. I ran it again with the same file I linked in my initial comment and this time I am getting a `KeyError: 'medium'` error.

Any idea why this could be happening?

**Comment by Apipia** [comment]
So I wrote most of the latest Fortify parser logic. It should work with an XML file that you generate from the FPR, but not an FPR itself. To generate the XML you need to use the Fortify_SCA_and_APPS ReportGenerator tool. There should be some instructions in a readme file.
https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/fortify/README.md

The default XML that is generated will only import one issue per issue-type (AKA: Kingdom) but that readme has instructions on how to get all of them.

As for the Crashtest parser, I could take a look at what's going on. It looks like the severity is being saved as 'medium' but maybe it needs to be 'Medium'? I can't recall what it's expecting but I'll check it out.

**Comment by TheUnriashol** [comment]
@Apipia Thank you for the info, I will try out the Fortify Tool 👍 

I think you might be right with the CrashTest parser. I took a look at it and on line 72 it tries to get a numerical severity of the string.

https://github.com/DefectDojo/django-DefectDojo/blob/64d5f3485adc9d725a0ee650122371afdbbf4d3a/dojo/tools/crashtest_security/parser.py#L58-L74


When I look in the models file I can see that it seems to expect "Medium" rather then "medium"


https://github.com/DefectDojo/django-DefectDojo/blob/64d5f3485adc9d725a0ee650122371afdbbf4d3a/dojo/models.py#L1456-L1471


I will have to try it out and check if it works. Will update this issue with the result.

**Comment by Apipia** [comment]
It seems that we have to options to fix this, either in the CrashTest parser we change all severities to their proper casing ("low" to "Low, "high" to "High") or we update the comparison of severities with a `.lower()` to ensure it will always work. The former is the quickest and easiest solution, while the latter will prevent errors like this in the future.

**Comment by Apipia** [comment]
Hey I was just noting that in the parser for CrashTest (on dev, are you running dev?) it grabs the severity and capitalize it.

https://github.com/DefectDojo/django-DefectDojo/blob/eb2971886f64af20750a37ce36db1ed717af9ae6/dojo/tools/crashtest_security_xml/parser.py#L61

So you shouldn't get any issues with "medium" rather than "Medium". Maybe you can check that your current version has this line?
