### ISSUE TITLE
Default value for deduplicated finding

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#2074]
**Is your feature request related to a problem? Please describe**

When you have a finding (A) that is marked as duplicate of another one (B), but there are other similar findings (C, D). 

When you save A as a duplicate of B, and then come back into edit mode for A, the selected item for the original selection will not have B as default value but the first item of the list, potentially C or D if they have a lower ID. This is misleading and confusing at best.

**Describe the solution you'd like**
Have the default value set.

fyi @Wadeck

**Comment by ptrovatelli** [comment]
Hello @madchap . 
I don't really understand the use case. 

could you elaborate on "When you save A => B" please? save A then save B? deduplicate B from A? 
and "the select for the original selection" ? 
thanks!

**Comment by madchap** [comment]
Amended the original post.

**Comment by valentijnscholten** [comment]
fixed by #2843
