### ISSUE TITLE
Nginx crash loop in Kubernetes deployment

### ISSUE THREAD

**Issue by sbarbeau-od** [DefectDojo/django-DefectDojo#2083]
**Bug description**

My (slightly custom) kubernetes deployment works well, except when I try to access `System settings`.

**Steps to reproduce**
1. Go to https://defectdojo.XXX.TLD/dashboard
2. Click on 'Configuration > System settings'
3. After a long time, the nginx responds with a 503 error

Clicking on `System settings` totally break nginx container which make DefectDojo unusable. The only workaround is to replace the pod and not use `System settings`.

I built the Docker containers from the `master` branch

The modifications I did on my Kubernetes deployment are related to:
- Adding a new parser
- Activating SSO authentication
- Using AWS RDS for database

I did not change nginx configuration or anything related to the core of DefectDojo.

**Expected behavior**
DefectDojo works well in my Kubernetes environment except the 'System settings' page

**Deployment method**
- [X] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Debian GNU/Linux 10

**Console logs** (optional)

These are logs from the `nginx` containers on `defectdojo-django-*` pods:

```

2020-03-18T19:05:56.952110811Z XX.XX.XX.XX - - [18/Mar/2020:19:05:56 +0000] "GET / HTTP/1.1" 499 0 "-" "kube-probe/1.14" "-"
2020-03-18T19:05:57.646882395Z XX.XX.XX.XX - - [18/Mar/2020:19:05:57 +0000] "GET / HTTP/1.1" 499 0 "-" "kube-probe/1.14" "-"
2020-03-18T19:05:06.952222877Z XX.XX.XX.XX - - [18/Mar/2020:19:05:06 +0000] "GET / HTTP/1.1" 499 0 "-" "kube-probe/1.14" "-"
[...]
XX.XX.XX.XX - - [18/Mar/2020:19:06:35 +0000] "GET / HTTP/1.1" 502 494 "-" "kube-probe/1.14" "-"
2020/03/18 19:06:43 [error] 16#16: *21 connect() to unix:///run/uwsgi.sock failed (11: Resource temporarily unavailable) while connecting to upstream, client: XX.XX.XX.XX, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///run/uwsgi.sock:", host: "defectdojo.XXX.TLD"
XX.XX.XX.XX - - [18/Mar/2020:19:06:43 +0000] "GET / HTTP/1.1" 502 494 "-" "kube-probe/1.14" "-"
XX.XX.XX.XX - - [18/Mar/2020:19:06:45 +0000] "GET / HTTP/1.1" 502 494 "-" "kube-probe/1.14" "-"
2020/03/18 19:06:45 [error] 16#16: *23 connect() to unix:///run/uwsgi.sock failed (11: Resource temporarily unavailable) while connecting to upstream, client: XX.XX.XX.XX, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///run/uwsgi.sock:", host: "defectdojo.XXX.TLD"
2020/03/18 19:06:53 [error] 16#16: *25 connect() to unix:///run/uwsgi.sock failed (11: Resource temporarily unavailable) while connecting to upstream, client: XX.XX.XX.XX, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///run/uwsgi.sock:", host: "defectdojo.XXX.TLD"
```

**Additional context** (optional)

There are additional errors at Kubernetes level:

```
Events:
  Type     Reason     Age                     From                                    Message
  ----     ------     ----                    ----                                    -------
  Warning  Unhealthy  7m27s (x161 over 153m)  kubelet, ip-XX-XX-XX-XX.ec2.internal  Liveness probe failed: HTTP probe failed with statuscode: 502
  Warning  BackOff    2m48s (x360 over 161m)  kubelet, ip-XX-XX-XX-XX.ec2.internal  Back-off restarting failed container
```

As the error seems related to the uwsgi socket, here is the content of related files:
```
I have no name!@defectdojo-django-xxxxxxxxxx-xxxxx:/$ cat /run/uwsgi_pass 
uwsgi_pass unix:///run/uwsgi.sock;
I have no name!@defectdojo-django-xxxxxxxxxx-xxxxx:/$ cat /run/uwsgi_server
server localhost:3031;
```

and ENV variables:
```
I have no name!@defectdojo-django-xxxxxxxxxx-xxxxx:/$ env | grep -i uwsgi
DD_UWSGI_PORT=3031
DD_UWSGI_HOST=localhost
DD_UWSGI_ENDPOINT=/run/uwsgi.sock
DD_UWSGI_PASS=unix:///run/uwsgi.sock
```

Please let me know if you need more details

**Comment by sbarbeau-od** [comment]
I'm closing this issue. I don't know where the problem was coming from, but a redeployment of the Helm chart fixed it...

**Comment by antisec135** [comment]
@sbarbeau-od Did you figure out the reason? I tried redeployment with Helm but  it didn't work for me
