### ISSUE TITLE
Qualys Web Application Scanner Import

### ISSUE THREAD

**Issue by scottgoettepnc** [DefectDojo/django-DefectDojo#2089]
**Bug description**
Defect Dojo Qualys Web Application Scanner import currently does not work

**Steps to reproduce**
1. Download report from Qualys (three paths: API, Download from Scan View, Download XML from report View)
2. Attempt to do an import Findings in DefectDojo
3. See Zero Findings imported

In currently working scans, I see

`<?xml version='1.0' encoding='UTF-8'?><WAS_WEBAPP_REPORT><HEADER><NAME>Web Application Report</NAME><DESCRIPTION>Each targeted web application is listed with the total number of detected vulnerabilities and sensitive content.</DESCRIPTION>GENERATION_DATETIME>02 Dec 2019 12:49PM GMT-0500</GENERATION_DATETIME><COMPANY_INFO>....`

++some other changes in XML entities and such to detailed for this issue++

in current XML reports that come from UI, I see the following:
(Legacy Format)
`<?xml version="1.0" encoding="UTF-8"?>**<!DOCTYPE WEB_APPLICATION_SCAN SYSTEM "https://qualysapi.qualys.com/webapp_scan.dtd"><WEB_APPLICATION_SCAN>**<HEADER><NAME>Web Application Vulnerability Scan Results</NAME><GENERATION_DATETIME>2020-03-19T20:35:01Z</GENERATION_DATETIME><COMPANY_INFO....`

In XML from report download
`<?xml version='1.0' encoding='UTF-8'?>**<WAS_SCAN_REPORT>**<HEADER><NAME>Scan Report</NAME><DESCRIPTION>Vulnerabilities of all selected scans are consolidated into one report so that you can view their evolution.</DESCRIPTION><GENERATION_DATETIME>19 Mar 2020 04:35PM GMT-0400</GENERATION_DATETIME><COMPANY_INFO>`
   
so should just be getting the new XML format, pick where it comes from and updating code (XSLT?). Not sure who originally worked on it - would love to get in contact with that person.

**Comment by dr3dd589** [comment]
hello @scottgoettepnc,
Can you upload a new updated sample report file, So that we can reproduce the actual error?
Thanks

**Comment by scottgoettepnc** [comment]
Apologies - was able to determine what caused this. The import from Qualys is based on the Asset export (Aggregate scan) vs. the Individual Scan. There are a couple .XML exports from Qualys and they do not result in the same file structure.

There are some other issues with the Asset export in terms of deduplication, CWE findings, etc.. Will post those as requests

**Comment by ducquang92** [comment]
Hi @scottgoettepnc ,
I also encounter this issue now, could you please update with me the status of this issue?

**Comment by Teazane** [comment]
Hi, this error also happens for me. 

Here is what my Qualys Webapp Scan report looks like:
`<?xml version='1.0' encoding='UTF-8'?>
<WAS_SCAN_REPORT>
    <HEADER>
        <NAME>Scan Report</NAME>
        <DESCRIPTION>Vulnerabilities of all selected scans are consolidated into one report so that you can view their evolution.</DESCRIPTION>
        <GENERATION_DATETIME>06 Oct 2020 03:11PM GMT</GENERATION_DATETIME>
        ...
    </HEADER>
    <FILTERS> ... </FILTERS>
    <TARGET>
        <SCAN>Webapp campaign 2020</SCAN>
    </TARGET>
    <SUMMARY> ... </SUMMARY>
    <RESULTS>
        <VULNERABILITY_LIST>
            <VULNERABILITY>
                <UNIQUE_ID>blahblahblah</UNIQUE_ID>
                ...
            </VULNERABILITY> ...`
But when imported in an engagement, no finding is found is the report. I don't understand: the test type is OK, the minimum severity too, there is no reason for the vulnerability found by the Qualys scan to be ignored as findings when imported in DefectDojo. What's going on? Any information or help to solve this problem?
