### ISSUE TITLE
Demo at defectdojo.herokuapp.com is broken

### ISSUE THREAD

**Issue by andifalk** [DefectDojo/django-DefectDojo#2103]
**Bug description**
The demo app at https://defectdojo.herokuapp.com does not work. Instead, it reports an _Application error_

**Steps to reproduce**
1. Go to 'https://defectdojo.herokuapp.com'
2. See error

**Expected behavior**
The demo app should work and be useable to see it in action

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Linux Mint 19.3

**Comment by valentijnscholten** [comment]
duplicates #2037
