### ISSUE TITLE
Panel with Bulk Actions doesn't appear on select finding

### ISSUE THREAD

**Issue by faklad** [DefectDojo/django-DefectDojo#2108]
**Panel with Bulk Actions doesn't appear on select finding**
Panel with Bulk Actions doesn't appear on select finding. It appears only if choose "select_all". 

**Steps to reproduce**
1. Go to Findings page
2. Click on the checkbox of any finding in the table. It is first column.
3. See panel "Bulk Actions" doesn't appear on the top of the table.

**Expected behavior**
Panel with Bulk Actions should appear if at least one finding was chosen in the table.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Comment by faklad** [comment]
Actually the problem is in the initialization of event handle for checkboxes "onchange" in the table.
It was done before DataTable initialization. During DataTable initialization stage all "old" event handles for checkboxes were removed and only DataTable event handles.

**Comment by faklad** [comment]
Hm, Looks like this issue was solved in dev branch

**Comment by valentijnscholten** [comment]
yeah we did quite some javascript related fixes in `dev` since the last release on `master`.  please reopen when needed.
