### ISSUE TITLE
Staff role for engagement lead: mandatory or not ?

### ISSUE THREAD

**Issue by christophe226** [DefectDojo/django-DefectDojo#2113]
**Is your feature request related to a problem? Please describe**
Why a Testing lead user must have the staff role ? As a standard user (ie. not staff) who interact with DefectDojo through the API, I am frustrated when I have to specify a staff-user for lead engagement. I may work in a context where there is no staff-user, and it does not make sense to specify the 'admin' user as engagement lead.

**Describe the solution you'd like**
As a standard user using DefectDojo API, I want to create engagements for which I have the Testing lead, so that :
- I do not need to be staff myself. Otherwise I would have too many permissions on other products
- I do not need to designate another staff-user as lead, because it does not make sense for my product

**Describe alternatives you've considered**
The solution would be to remove the exclusion filter isStaff=False in dojo/forms.py:669

**Comment by madchap** [comment]
Agreed the model is not what it should be. We welcome work on refactoring that ;-)

For my API users which import or re-import tests from pipelines, I do the following:
- Only `Active` (no staff)
- Through the `/admin` django interface, I assign specific wider permissions like

![image](https://user-images.githubusercontent.com/5468769/77656902-d5147a80-6f74-11ea-9761-8da0274a465c.png)

This only works for the API, however.

Hope this helps.
