### ISSUE TITLE
Latest commit in dev (#1863) breaks social-authentication

### ISSUE THREAD

**Issue by xens** [DefectDojo/django-DefectDojo#2122]
**Bug description**
Social authentication (Auth0, Gitlab, ...) is broken

**Steps to reproduce**

1. Go to the login page when a social-provider is configured (here Auth0)
2. Click on the social-provider login button
3. You'll be redirected to the IdP to enter your credentials
4. You'll be redirected to the DDJ authentication page without being authenticated

**Expected behavior**

At point 4 I should be redirected in to the DDJ dashboard (/dashboard)

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**

* Work as expected before https://github.com/DefectDojo/django-DefectDojo/pull/1863

**Additional information**

It's working as expected for static user/password credentials, only the social-auth is broken.

**Comment by madchap** [comment]
FYI @Nilix007 @valentijnscholten

**Comment by Nilix007** [comment]
Educated guess:  The entries for socal auth URLs in `LOGIN_EXEMPT_URLS` do not match the actual URLs.

We set `SOCIAL_AUTH_TRAILING_SLASH=False` by default, but the URLs specified in `LOGIN_EXEMPT_URLS` end with a trailing slash.

https://github.com/DefectDojo/django-DefectDojo/blob/3a8392db9f69a08745cca865529d875188734ef1/dojo/settings/settings.dist.py#L72

https://github.com/DefectDojo/django-DefectDojo/blob/3a8392db9f69a08745cca865529d875188734ef1/dojo/settings/settings.dist.py#L329-L342

**Comment by valentijnscholten** [comment]
I don't have any social integrations so can't test educated guess. 1863 in itself should be OK.

**Comment by xens** [comment]
Thanks for the tips @Nilix007 I'll give a try to these EXEMPT_URLs these evening.

**Comment by xens** [comment]
Ok I was able to fix the issue which is a combination of multiple things:

1. It was working before #1863 because the authentication mechanism was a bit broken and LOGIN_EXEMPT_URLS was not properly evaluated (as far as I understand).
2. #1863 was merged and broke the social authentication, it's due to the following option that strips the trailing / at the end of the call-back URLs thus making it incompatible with the list LOGIN_EXEMPT_URLS as suggested bz @Nilix007 

https://github.com/DefectDojo/django-DefectDojo/blob/3a8392db9f69a08745cca865529d875188734ef1/dojo/settings/settings.dist.py#L72

https://github.com/DefectDojo/django-DefectDojo/blob/3a8392db9f69a08745cca865529d875188734ef1/dojo/settings/settings.dist.py#L329-L342

3. the call-back URL of the python-social Auth0 backend is wrong:

https://github.com/DefectDojo/django-DefectDojo/blob/3a8392db9f69a08745cca865529d875188734ef1/dojo/settings/settings.dist.py#L336

According to https://github.com/python-social-auth/social-core/blob/6606794df5a51b7c9b46e3ff76e6e5d2efc30053/social_core/backends/auth0.py#L12

it should be ```auth0``` and not ```auth0-oauth2``` (unlike the other social integrations.)

It was working before the PR again because of this list not being properly evaluated.

So if that make sense for you I'll submit a PR that:

1. sets the following to true:

https://github.com/DefectDojo/django-DefectDojo/blob/3a8392db9f69a08745cca865529d875188734ef1/dojo/settings/settings.dist.py#L72

2. rename the auth0 provider call-back URL

Make sense for you ?

**Comment by valentijnscholten** [comment]
Sounds good, thanks. Hopefully there's also somebody who can test some of the other socials. @Maffooch

**Comment by Nilix007** [comment]
Another idea:  Add `r'complete/'` for whitelisting all social auth backends. (And remove the obsolete ones)

**Comment by xens** [comment]
Closing this one as it has been fixed by the referenced merge request
