### ISSUE TITLE
engagement on /jira_finding_mappings endpoint is always null

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#2128]
**Bug description**
When querying GET'ing the `/jira_finding_mappings`, the `engagement` value is always null.

```
{
      "id": 69,
      "jira_id": "244117",
      "jira_key": "DOJOSBX-17",
      "finding": 36940,
      "engagement": null
}
```
This makes it hard to build a list of findings that have a jira issue associated.

fyi @Apipia ;-)

**Comment by Apipia** [comment]
😆Yeah the "engagement" logic with JIRA has a bunch of holes in it. Saw a lot of commented out code and things in that regard. Definitely something I can look into.

**Comment by valentijnscholten** [comment]
The engagement field is only populated if the jira issue is the epic mapped to an engagement. In that case the finding field is null/none. So a jira_issue record either belongs to a finding XOR to an engagement.
If you need the engagement value you can go `finding.test.engagment' or do another API call :-)
