### ISSUE TITLE
Dashboard Historical Finding Severity piechart doesn't show numbers

### ISSUE THREAD

**Issue by undelete** [DefectDojo/django-DefectDojo#2129]
Version: Docker - 1.5.4

The historical finding severity don't show details in numbers.
<img width="570" alt="Captura de Pantalla 2020-03-31 a la(s) 04 36 44" src="https://user-images.githubusercontent.com/25057634/77999795-a518fe80-7309-11ea-8512-64987270aece.png">

**Comment by dayal18** [comment]
@undelete Yeah, it doesn't. This should be enhancement request I guess.

**Comment by valentijnscholten** [comment]
In the next release (1.6.0) there will be tooltips when you hover over the pie chart. Would that suffice for now?

**Comment by dayal18** [comment]
Thanks @valentijnscholten , I would say something is better than having nothing.
If adding statics is concern for a donut chart, a full pie chart doesn't hurt.

And probably the heading Historical "verified" findings as this doesn't include any active, mitigated.. the status of the finding should have "verified" check to make itself on this pie chart, which causes conflict from home dashboard vs each product dashboard.. if you mark finding as verified you wouldn't see in product else you wouldn't see on home dashboard. (An eye for an eye) I know this could be feature.

**Comment by valentijnscholten** [comment]
We need to do a re-definition of all statuses and update/check our codebase, this will happen in #2215.

**Comment by undelete** [comment]
> In the next release (1.6.0) there will be tooltips when you hover over the pie chart. Would that suffice for now?

Yes, thanks.

**Comment by dayal18** [comment]
@valentijnscholten cool.. thanks much..
