### ISSUE TITLE
The metrics in the product are incorrect/confusing

### ISSUE THREAD

**Issue by undelete** [DefectDojo/django-DefectDojo#2130]
** The metrics in the product are not displayed and the findings are already activated and verified **
When you add a manual find and check active and verified metrics are not shown.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Commit Message: [use `git show -s --format="%h: %s [%ci]"`]
<img width="213" alt="Captura de Pantalla 2020-03-31 a la(s) 04 43 18" src="https://user-images.githubusercontent.com/25057634/78000704-11483200-730b-11ea-9d6b-94c6fbadbfb5.png">
<img width="500" alt="Captura de Pantalla 2020-03-31 a la(s) 04 42 56" src="https://user-images.githubusercontent.com/25057634/78000709-12795f00-730b-11ea-9b91-15e971ef9c9b.png">
<img width="773" alt="Captura de Pantalla 2020-03-31 a la(s) 04 42 46" src="https://user-images.githubusercontent.com/25057634/78000710-1311f580-730b-11ea-91c6-45801d4d5897.png">

**Comment by dayal18** [comment]
@undelete remove the "Verified" and you'll see the finding count at the product level, but here is the trick - if you remove "Verified" -You'll not see the status in the main dashboard.

**Comment by undelete** [comment]
> @undelete remove the "Verified" and you'll see the finding count at the product level, but here is the trick - if you remove "Verified" -You'll not see the status in the main dashboard.

Thanks, so it is not possible to have metrics and the and the status of the findings in the main dashboard?

This is it a feature or a bug?

**Comment by dayal18** [comment]
@undelete I would say it as a feature, rather than a Bug. You can go to "views.py" to customize the query as you want.

**Comment by valentijnscholten** [comment]
We need to do a re-definition of all statuses and update/check our codebase, this will happen in #2215.
