### ISSUE TITLE
Non-staff user cannot create engagements through API

### ISSUE THREAD

**Issue by christophe226** [DefectDojo/django-DefectDojo#2132]
**Bug description**
As a standard user (ie. non-staff), when I use API v1 to create an engagement, I get an error:

> argument of type 'ManyRelatedManager' is not iterable

**Steps to reproduce**
1. As admin logged in DefectDojo front-end, I create a new product Product1
2. Still as admin logged in DefectDojo front-end, I create a new user John Doe: I check "Active" checkbox, but do not check "Staff status" nor "Superuser status", and I enter Product1 in Authorized products.
3. In Django administration interface, I give John Doe the following minimal user permissions: only "auth | user | Can change user" and "dojo | engagement | Can add engagement". And I set him a password.
4. I log in as John Doe, to get my API v1 Key
5. In a command-line interface, I try to create a new engagement through API v1, using the following curl request: 
`curl -X POST -d @api_input.json http://localhost:8080/api/v1/engagements/ --header "Content-Type: application/json" --header "Authorization: ApiKey JohnDoe:56e455e1165fb30a133fb723c75da4131ca71421" --verbose`
with the following data in api_input.json:
`{"lead": "/api/v1/users/1/", "engagement_type": "CI/CD", "product": "/api/v1/products/1/", "name": "Engagement1", "status": "In Progress", "target_start": "2020-03-31", "target_end": "2020-04-07"}`
I get an error: 

> argument of type 'ManyRelatedManager' is not iterable

(see console details above)

**Expected behavior**
I expect the API request to succeed.
When I set John Doe as a staff user, the API request succeeds.
Like for other similar bugs such as https://stackoverflow.com/questions/14920735/manyrelatedmanager-object-is-not-iterable, the solution is to replace dojo/api.py:159` bundle.obj.authorized_users` with `bundle.obj.authorized_users.all()`. There are 3 other similar replacements to do in api.py, at lines 167, 175 and 182.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System:  Ubuntu 18.04
 - DefectDojo Commit Message: d3d64c95: Implement Gitlab OAuth2 authentication. Fix #1966 (#1967) [2020-03-03 10:21:16 +0100]

**Console logs**
Here are the console logs after I launch command line in step 5:
{"error_message": "argument of type 'ManyRelatedManager' is not iterable", "traceback": "
Traceback (most recent call last):
  File \"/usr/local/lib/python3.5/site-packages/tastypie/resources.py\", line 228, in wrapper
  response = callback(request, *args, **kwargs)
  File \"/usr/local/lib/python3.5/site-packages/tastypie/resources.py\", line 468, in dispatch_list
  return self.dispatch('list', request, **kwargs)
  File \"/usr/local/lib/python3.5/site-packages/tastypie/resources.py\", line 500, in dispatch
  response = method(request, **kwargs)
  File \"/usr/local/lib/python3.5/site-packages/tastypie/resources.py\", line 1409, in post_list
  updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))
  File \"/usr/local/lib/python3.5/site-packages/tastypie/resources.py\", line 2251, in obj_create
  bundle = self.full_hydrate(bundle)
  File \"/usr/local/lib/python3.5/site-packages/tastypie/resources.py\", line 957, in full_hydrate
  value = field_object.hydrate(bundle)
  File \"/usr/local/lib/python3.5/site-packages/tastypie/fields.py\", line 788, in hydrate
  return self.build_related_resource(value, request=bundle.request)
  File \"/usr/local/lib/python3.5/site-packages/tastypie/fields.py\", line 691, in build_related_resource
  return self.resource_from_uri(fk_resource, value, **kwargs)
  File \"/usr/local/lib/python3.5/site-packages/tastypie/fields.py\", line 595, in resource_from_uri
  obj = fk_resource.get_via_uri(uri, request=request)
  File \"/usr/local/lib/python3.5/site-packages/tastypie/resources.py\", line 883, in get_via_uri
  return self.obj_get(bundle=bundle, **self.remove_api_resource_names(kwargs))
  File \"/usr/local/lib/python3.5/site-packages/tastypie/resources.py\", line 2237, in obj_get
  self.authorized_read_detail(object_list, bundle)
  File \"/usr/local/lib/python3.5/site-packages/tastypie/resources.py\", line 641, in authorized_read_detail
  auth_result = self._meta.authorization.read_detail(object_list, bundle)
  File \"./dojo/api.py\", line 160, in read_detail
  bundle.request.user in bundle.obj.authorized_users)
  TypeError: argument of type 'ManyRelatedManager' is not iterable
"}

**Comment by mahirrudin** [comment]
AFAIK, only staff user or above can create engagement.

**Comment by madchap** [comment]
Currently expected, and therefore not an issue.

**Comment by AYUSH-KUMAR123** [comment]
why are you doing email frequently you mother fuck i will make you to suck
if you don't stop it right you bitch crazy mother fucker.
