### ISSUE TITLE
alert notifications shown as enabled by default when they're not

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#2151]
When a user has not setup nofitications yet, the django view code defaults to creating a new Notifications model instance. This has all notifications types set to be enabled for 'alert'.
So on screen it looks to the user that these notifications are enabled, when in reality they are not.

solution is either to disable them by default in the Notifications model or to somehow create a default Notifications model instance in the database whenever a new user is created.

**Comment by valentijnscholten** [comment]
fixed for users created after https://github.com/DefectDojo/django-DefectDojo/blob/4be8d4c6e4f6e72f3574098e985d067b068bceb1/dojo/utils.py#L1971 
existing users may still suffer.

**Comment by valentijnscholten** [comment]
if someone can write a short piece of code to fix this for existing users, we can add that as a migration

**Comment by devGregA** [comment]
@valentijnscholten  are we okay to close this one?
