### ISSUE TITLE
code to evaluate rules asynchronously is synchronous

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#2152]
There is code in `finding.save()` to evaluate rules asynchronously:

```
       if rules_option:
            from dojo.tasks import async_rules
            from dojo.utils import sync_rules
            try:
                if self.reporter.usercontactinfo.block_execution:
                    sync_rules(self, *args, **kwargs)
                else:
                    async_rules(self, *args, **kwargs)
            except UserContactInfo.DoesNotExist:
                async_rules(self, *args, **kwargs)
                pass
```
However, in all cases the rules are evaluated syncrhonously.
The call to `async_rules` should really be `async_rules.delay`.
And probably the call for when usercontactinfo doesn't exist should default to synchronous.

I don't want to change it rightaway as I don't know what people are using rules for and if it will affect dedupe etc.

**Comment by devGregA** [comment]
@valentijnscholten I'm not sure if some delay causes these to function correctly or if it is a side effect. But generally speaking, the functions have worked for me as intended.

**Comment by valentijnscholten** [comment]
Fixed in pr
