### ISSUE TITLE
Add delete functionality to DefectDojo Product type, Jira 

### ISSUE THREAD

**Issue by aaronweaver** [DefectDojo/django-DefectDojo#216]
Add delete functionality and review to make sure all types can be removed.

**Comment by grendel513** [comment]
@aaronweaver @devGregA this is dangerous since all other models are essentially a child of product type.  Any product that is under that product type, any engagement under that product, any test under that engagement, any finding, etc will all also be deleted.  Is this what you intend?

**Comment by devGregA** [comment]
@grendel513 I **think** @aaronweaver is referring to when issues are pushed to JIRA via Dojo. If a mistake is made, there is no way to delete the JIRA issue

**Comment by mccabe615** [comment]
This would be a useful feature as otherwise, you have to manually delete records from the database. I think a simple check to see if there are relationships before allowing deletion would prevent what @grendel513 is referring to.
