### ISSUE TITLE
PDF Report Type not available

### ISSUE THREAD

**Issue by dayal18** [DefectDojo/django-DefectDojo#2162]
**Bug description**
I might be missing something, but I looked at every possible option and think its a bug.
I don't see Report Type - PDF (I see HTML, Asciidoc), but no PDF.
I'm not looking at the _Report Builder_ as I know we don't have that feature, but I'm looking for a PDF Report type for **Product or Engagements or Tests.**

**Steps to reproduce**
1. Go to 'any product or engagement or test'
2. Click on '3 dots and say Product report or engagement report or test report'
3. Scroll down to 'middle and select all the options you need like findings? Table of contents?, etc.,'
4. Next will be drop down where I'll see only HTML and Asciidoc options.

**Expected behavior**
I should probably see PDF report option in the dropdown menu.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [ X] setup.bash / legacy-setup.bash

**Environment information**
 - Ubuntu 18.04
 - I have celeryd and celerybeat running
 - I have pip pdfkit installed
 - I have wkhtmltopdf installed (path is same in settings.py)

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

**Comment by Apipia** [comment]
Yeah I noticed this as well. I have been "printing" the HTML report and saving it as a PDF. On a MAC you can select the printer "Save as PDF", and I believe there is a similar functionality in Windows.

**Comment by dayal18** [comment]
That does no good, as the report doesn't look authentic. For the work we do in pentesting the applications the report should present its value. This DefectDojo is really good at showing it, but a really good report will be very great.

The other option I can think is to allow all users to see the HTML report, by sharing the link directly. As people will also get familiar with the application.

I have the latest version running 1.5.4.1 and there are issues in this version.

**Comment by madchap** [comment]
I've never seen a PDF report in Dojo, not sure why it's marked as `Bug`. I see a ref here, but I believe the docs would need to be refreshed (that predates me here for sure)

Two options I see or now:
* We accept PRs :-)
* Try your luck with whatever asciidoc to PDF converters.
* Use the APIv2 to create your own report the way you want (that's what I do for now)

**Comment by dayal18** [comment]
Thanks @madchap , yeah I saw that in the document and also I looked at version 1.2 I guess, where the application have "PDF screenshots" in report builder. Thanks for the options I will try my luck to see if there is anything that can help, then I can publish the APIs for others as well.

**Comment by NRGLine4Sec** [comment]
Hi @dayal18, I request this feature too in #1299. It would be great if you can make it happen.

**Comment by dayal18** [comment]
I'll see if I can come up with something interesting, with API's.

**Comment by PreenaPrakash** [comment]
[https://github.com/DefectDojo/django-DefectDojo/issues/224#issuecomment-703239097](url)
