### ISSUE TITLE
Caching of system_settings breaks integration tests

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#2164]
See #2160 for details.

The cache that is used for system setting is local to a worker. So if you have multiple workers, the cache can be out of sync. But only for 30seconds, because that's the livetime of the cache. We (I) thought this would be OK, but in the particular case of having an integration test enabling dedupe and then relying on it, it will sometimes fail. So I guess it's my own fault then :-0. Now thinking about how to fix it. I really don't want to go back to having 50 database queries per request just to retrieve system settings.

The alternative that I considered earlier was to have a middleware that caches the settings per request.

**Comment by madchap** [comment]
Possible that it is not thread safe, but could work on multiple non-threaded processes? (that's what I've been reading anyways).

Otherwise, what are you thinking about? Memcache backend or something? Should not be too hard of a change I guess?

**Comment by valentijnscholten** [comment]
I am trying to avoid extra software and keep it simple. There are lots of example with middleware that caches a value in a thread local variable. So that's what is the easiest I think. So no longer use the Django cache.

**Comment by madchap** [comment]
Can we close @valentijnscholten?

**Comment by valentijnscholten** [comment]
After 2174 is merged yes
