### ISSUE TITLE
AWS Security Hub Finding Importer

### ISSUE THREAD

**Issue by xee5ch** [DefectDojo/django-DefectDojo#2167]
**Is your feature request related to a problem? Please describe**
A clear and concise description of what the problem is.

[SecurityHub](https://docs.aws.amazon.com/securityhub/latest/userguide/what-is-securityhub.html) is a promising new service to integrate security findings from a variety of inputs and "begins consuming, aggregating, organizing, and prioritizing findings from AWS services, such as Amazon GuardDuty, Amazon Inspector, and Amazon Macie, and from AWS partner security products." These third-party integrations also include [cloud-custodian](https://cloudcustodian.io/docs/aws/topics/securityhub.html) and [tenable.io](https://docs.tenable.com/integrations/AWS/Content/TenableioAWS/SecurityHub.htm). Therefore, this poses a unique standardized format, [AWS Security Hub Finding Format (ASFF)](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-findings-format.html) to ingest cloud security, native, and third-party, from cloud accounts to specific cloud infrastructure and servers, with native reporting and popular third-party tools.

**Describe the solution you'd like**

As a security engineer utilizing Defect Dojo, in order to better understand the context of application, server, and cloud infra findings, I would like to utilize a standardize AWS format, ASFF, to unify findings of various categories for my AWS accounts.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you have considered.

We can continue to implement custom formats for AWS Guard Duty and AWS Inspector and additional 3rd party tools for every new AWS-related security tool worth importing.

**Comment by valentijnscholten** [comment]
Could be useful, even though AWS Security Hub is sort of the same type of application as Defect Dojo. We could start by looking at some examples and make a parser for those? It does look like ASFF has a LOT of info/data in it, so will be cherry-picking for what to include in defect dojo as fields.

**Comment by xee5ch** [comment]
>Could be useful, even though AWS Security Hub is sort of the same type of application as Defect Dojo.

This is true. Our group would like to use the data, but AWS Security Hub is really targeted at AWS inputs and outputs, and I am sure you know even a run-of-the-mill app is more complicated than just its EC2 and RDS. Additionally, we work with a large customer starting with cloud-native teams, but other groups long-term have legacy applications not even in cloud, so I see Security Hub as a very useful bridge format and data-store and we use DD like it should be used, surface the data full of its context along app code findings and other stuff organized by project. :-)

> We could start by looking at some examples and make a parser for those? It does look like ASFF has a LOT of info/data in it, so will be cherry-picking for what to include in defect dojo as fields.

That is exactly my plan, but wanted to know we are on the same page first. I volunteer! Haha
