### ISSUE TITLE
Finding Images 404

### ISSUE THREAD

**Issue by dayal18** [DefectDojo/django-DefectDojo#2168]
**Bug description**
Go to any finding and upload an image, the image doesn't display and give a 404

**Steps to reproduce**
1. Go to 'Product --> Engagement --> finding --> manage image --> upload image'
2. Return back to the finding page
3. The image doesn't load, click on that magnifying icon, and the image open in new tab with 404

**Expected behavior**
The image should load.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [ x] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 18.04

**Sample log files** (optional)
[10/Apr/2020 00:40:34] "GET **/media/CACHE/images/finding_images/909f1078-7589-4657-add3-f7a561c870b4/052d44fc4b558f4facc26077f7f43128.jpg HTTP/1.1" 404** 22622
[10/Apr/2020 00:40:35] "GET /alerts/count HTTP/1.1" 200 13
[10/Apr/2020 00:40:35] "GET /alerts/count HTTP/1.1" 200 13
Popen(['git', 'cat-file', '--batch-check'], cwd=/opt/dojo/django-DefectDojo, universal_newlines=False, shell=None, istream=<valid stream>)
[10/Apr/2020 00:40:35] "GET **/media/finding_images/909f1078-7589-4657-add3-f7a561c870b4.png HTTP/1.1" 404** 22622
[10/Apr/2020 00:40:35] "GET /static/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 304 0

**Screenshots** (optional)
![404](https://user-images.githubusercontent.com/43857391/78963035-bc02e200-7abb-11ea-87a7-7ee8de023f68.png)

On the Dojo platform:
![thumbnail](https://user-images.githubusercontent.com/43857391/78963066-da68dd80-7abb-11ea-821d-e28c8de1d7c5.png)

**Console logs** (optional)
![logs](https://user-images.githubusercontent.com/43857391/78963091-fb313300-7abb-11ea-9e3a-741017df0d5d.png)

**File on Server**
I see the file is also successfully uploaded to the server.
![locate](https://user-images.githubusercontent.com/43857391/78963291-a5a95600-7abc-11ea-9e32-692eebc3c10f.png)

I saw a few references error for docker and fix for it, not sure how can I fix this in .setup.bash setup.
#1930 #2045

**Comment by dayal18** [comment]
I did a fresh installation today again and have the same issue.

**Comment by dayal18** [comment]
I have to install nginx, running the application via "python manage.py runserver" will not work.
So we have to install nginx, and then configure the nginx.conf file accordingly.
The .setup.bash will not install nginx, so this is additional step we have to do.

**Comment by dayal18** [comment]
Check if your nginx config is configured with the port 8000 as you are using the same port in Python..

**Comment by dayal18** [comment]
This should be your nginx config.. modify as required..



upstream django {
  server 127.0.0.1:8001;
}

server {
  listen 80;
  return 301 https://$host$request_uri;
}

server {
  listen 8000;
  server_name <YOUR_SERVER_NAME>;

  client_max_body_size 500m; # To accommodate large scan files

  ssl_certificate           <PATH_TO_CRT>;
  ssl_certificate_key       <PATH_TO_KEY>;

  ssl on;

  <YOUR_SSL_SETTINGS> # ciphers, options, logging, etc

  location /static/ {
      alias   <PATH_TO_DOJO>/django-DefectDojo/static/;
  }

  location /media/ {
      alias   <PATH_TO_DOJO>/django-DefectDojo/media/;
  }

  location / {
      uwsgi_pass django;
      include     <PATH_TO_DOJO>/django-DefectDojo/wsgi_params;
  }
}

**Comment by iLeandro** [comment]
Made that change ( i had 8080 and still not working)
