### ISSUE TITLE
docker-compose dev environment reload extremely slow

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#2176]
Whenever you run Defect Dojo using docker-compose with the `dev` environment (overrides), uwsgi will reload if it detects changes in `.py` files. nginx will reload static files.
However the reloading consistently is extremely slow taking 30-60s before defect dojo works again.

It looks like this is because `nginx` doesn't seem to know `uwsgi`  has restarted. When I restart the nginx container, it works instantly.

**Comment by madchap** [comment]
I think this is due to multi-procs and/or threads actually. I am using `ptvsd` for my local dev all the time, we took it out and reload is fast.

**Comment by valentijnscholten** [comment]
I tried earlier setting workers/threads to 2, but got the same result. With `ptvsd` it looks faster indeed, still makes `dev` a poor choice.

**Comment by madchap** [comment]
Yea, we some discussions at some point about merging the options together.

**Comment by madchap** [comment]
This was addressed by one of @Maffooch with the `no-mercy` parameter in https://github.com/DefectDojo/django-DefectDojo/pull/2639
