### ISSUE TITLE
Product metrics now showing closed (mitigated) findings

### ISSUE THREAD

**Issue by AlexanderTyutin** [DefectDojo/django-DefectDojo#2187]
During implementing continuous vulnerability scan I was using APIv2 option "close_old_findings". And here in the main dashboard I see 4 closed findings. If I click on "Closed in Last 7 Days" I can see products related to these closed findings.

![image](https://user-images.githubusercontent.com/49285004/79100921-33609c00-7d70-11ea-899c-b470c01a364e.png)

But if I go to products metrics then no one of 4 products has any closed findings there.

![image](https://user-images.githubusercontent.com/49285004/79101200-b4b82e80-7d70-11ea-8d47-3c16c2671ecf.png)

![image](https://user-images.githubusercontent.com/49285004/79101206-ba157900-7d70-11ea-8c0a-4f6d4b22c561.png)

![image](https://user-images.githubusercontent.com/49285004/79101221-c13c8700-7d70-11ea-95be-1a7bce5a04bf.png)

![image](https://user-images.githubusercontent.com/49285004/79101239-c6013b00-7d70-11ea-82cc-3c1ab1210641.png)

When I click to closed findings I see a list of them. And when I click on any finding I see the finding record and the product which is related to the finding:

![image](https://user-images.githubusercontent.com/49285004/79101281-e0d3af80-7d70-11ea-8d30-6ec96ee92012.png)

**Comment by valentijnscholten** [comment]
Changed the title to make it better aligned with what the problem is, it's not only for auto closed findings.

**Comment by valentijnscholten** [comment]
We need to do a re-definition of all statuses and update/check our codebase, this will happen in #2215.
