### ISSUE TITLE
Adding Github integration to project automatically configures JIRA

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#2191]
If both JIRA and Github integration are enabled in the instance, configuring the GH integration will also show that the JIRA is configured.

![image](https://user-images.githubusercontent.com/5468769/79163065-9e48bc00-7dde-11ea-9ab7-22099a0ed827.png)

fyi @mestrade

**Comment by madchap** [comment]
![image](https://user-images.githubusercontent.com/5468769/79212053-53af5a00-7e47-11ea-9e51-20f419e82990.png)

**Comment by valentijnscholten** [comment]
@madchap is this still an issue with the latest version of #2140 ?

**Comment by madchap** [comment]
No, fixed indeed. Thanks for the eagle eye.
