### ISSUE TITLE
How can a finding be reopen from the API?

### ISSUE THREAD

**Issue by kareem-DA** [DefectDojo/django-DefectDojo#2201]
**Bug description**
I don't see a way to re-open a finding with the API after its been closed.  I have tried sending the commands with the v2 version of the API to set it back to active.  

data = {"active": True,
        "mitigated": "NULL",
        "mitigated_by": None,
        "verified": True}
response = dd._request("PATCH", "findings/{}/".format(finding_id), data=data)

But I can't reset the "MITIGATED" state to null.  Everything else works fine, but the finding continues to be reported as mitigated.

Any thoughts on how I can make this work?

**Steps to reproduce**

**Expected behavior**
Re-open a closed ticket

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ X] Docker
- [ ] setup.bash / legacy-setup.bash

**Comment by Nilesh0101** [comment]
@kareem-DA ,
To re-open the finding you use is_Mitigated=False, active=True
to close the finding you use is_Mitigated=True, active=False
