### ISSUE TITLE
Apply template to finding doesn't fill in all fields 

### ISSUE THREAD

**Issue by Lisa-Fiander** [DefectDojo/django-DefectDojo#2205]
**Bug description**
Creating a  _NewTemplate_  and filling in all sections including:
* Description 
* Mitigation 
* Impact 

Creates a full template that should be able to be used in other findings. However when trying to apply this template to another finding and selecting _ReplaceAll_, the sections _Mitigation_ and _Impact_ are no longer filled in and you need to input these yourself. Which takes away from having a fully filled in template. 

**Steps to reproduce**
1. Go to the DefectDojo UI and create a new template 
2. Go to Open Findings 
* Click on the three dots next to a finding
* Click 'Apply Template to Finding'
* Click on the newly created template
* Click 'Replace All'
3. Try to save and you will see that you still need to fill in the other sections even though this had been done in the original template

**Comment by Lisa-Fiander** [comment]
This is still an issue

**Comment by valentijnscholten** [comment]
Just tried this with latest dev and works for me
