### ISSUE TITLE
display_tags.py throws exception when urls larger than 50 chars are specified as Endpoints

### ISSUE THREAD

**Issue by bhepp-sec** [DefectDojo/django-DefectDojo#2226]
I found an issue in /dojo/templatetags/**display_tags.py** and was hoping you could make the update without a pull-request. It's an fairly obvious line-liner. 

![image](https://user-images.githubusercontent.com/64037862/79789323-fe2bef00-8317-11ea-976c-54d3f376757a.png)

When the input **value** is a class, like Endpoint, and the path length is one, and the input **value** length is greater than 50, it throws with _django-DefectDojo/dojo/templatetags/display_tags.py", line 81, in url_shortner
    return_value = "..." + return_value[50:]
TypeError: 'Endpoint' object is not subscriptable_

Line 79 needs a 'str' added to **value**, like this:

![image](https://user-images.githubusercontent.com/64037862/79789769-b5286a80-8318-11ea-957a-78f97eafc78c.png)

**Comment by namloc2001** [comment]
Hi, did anything progress with this?

**Comment by madchap** [comment]
I'd say it would be good for you to open a PR for the one liner :-)

**Comment by namloc2001** [comment]
> 
> 
> I'd say it would be good for you to open a PR for the one liner :-)

Done.
