### ISSUE TITLE
Documentation missing for Tool Configuration/Tool Type

### ISSUE THREAD

**Issue by immewnity** [DefectDojo/django-DefectDojo#2233]
I'm just starting out in using DefectDojo, and am a bit confused on what the Tool Type and Tool Configuration sections inside Configuration. I know that documentation is something DefectDojo prides itself on, and I greatly appreciate the breadth of it... but I can't seem to find this documented anywhere.

**Comment by jgirelli** [comment]
+1 this issue. I can't find any documentation on how to configure Tool Types or Configurations. It is referenced in the SonarQube API section under "Integrations", but the term "Tool Configuration" never appears again in the docs.

**Comment by damiencarol** [comment]
@jgirelli as notified in our "Support" section of the README.md https://github.com/DefectDojo/django-DefectDojo#support-bug-reports-and-getting-involved , this kind of question are better to manage directly in Slack => https://owasp-slack.herokuapp.com/ 

Closing this one as it's not really an issue.

**Comment by anandmahurakar** [comment]
Hi, How can we integrate sonarqube 9.5 with defetctdojo ? If you have any resource please share to anand.mahurakar@cloudzenix.com Thank you in advance
