### ISSUE TITLE
500 Error on Custom General Engagement Survey Submission

### ISSUE THREAD

**Issue by bitwisebytefoolish** [DefectDojo/django-DefectDojo#2245]
**Bug description**

- When saving a custom survey with questions of a mix of "Text" type "Choice" type, I get a 500 Internal Server Error.
- When saving a custom survey with questions of one "Choice" type, I get a 500 Internal Server Error.  
- Filling out a custom survey with questions of only "Text" type are working fine

**Steps to reproduce**
1. Go to http://<hostname>/survey
2. Click on 'Create Survey'
3. Give it a name and a description
4. Click on 'Create Survey and Add Questions'
5. Add a new question by clicking on the "+"
6. Select "Choice" from the "Type" dropdown
7. Select either Multichoice or not, Optional or not, either way the results are the same
8. Finish up with "Update Survey Questions"
9. Create a "General Engagement" survey
10. Select the survey you created and give it an expiration
11. Click "Add Survey"
12. Under the "General Engagement" survey section, select the "Share Survey" button
13. Take note of the URL, copy and paste it into a new tab (e.g. http://localhost:8080/empty_survey/2/answer)
14. Fill out the form as requested
15. Click the "Save Survey" button
16. Take note of the resulting 500 Internal Server Error 

**Expected behavior**
Redirect to /dashboard with the message "Successfully answered, all answers valid."

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Docker for Windows (Windows 10 Pro)
 - DefectDojo Commit Message: ffb1f375: Update values.yaml (#2194) [2020-04-14 17:36:50 +0200]

**Sample scan files** 
This isn't a scan file, but here's the form data from my POST request:
`csrfmiddlewaretoken=agr20ez14eGIN9XPZwdKhT8kXYTOFL0je0dtkjg7LJBotRTGxkHEJIN7sjgm2ICw&44-answer=mynewsite&45-answer=mike+r&47-answer=2&47-answer=3&47-answer=4&save_survey=Save+Survey`

**Screenshots** (optional)
![image](https://user-images.githubusercontent.com/55219898/80030086-bb078280-84b5-11ea-90ac-1b0422064438.png)

**Console logs** (optional)
```
uwsgi_1         | [pid: 1|app: 0|req: 213/490] 172.18.0.1 () {50 vars in 910 bytes} [Wed Apr 22 20:27:52 2020] GET /alerts/count => generated 13 bytes in 10 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
uwsgi_1         | [pid: 19|app: 0|req: 278/491] 172.18.0.1 () {50 vars in 910 bytes} [Wed Apr 22 20:28:02 2020] GET /alerts/count => generated 13 bytes in 11 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
nginx_1         | 172.18.0.1 - - [22/Apr/2020:20:28:02 +0000] "GET /alerts/count HTTP/1.1" 200 13 "http://localhost:8080/empty_survey/2/answer" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36" "-"
celeryworker_1  | [2020-04-22 20:28:06,207: INFO/MainProcess] Received task: dojo.tasks.async_dupe_delete[2a5ad001-45e5-4afb-a6ec-0e6bd898d66e]
celeryworker_1  | [2020-04-22 20:28:06,207: INFO/MainProcess] dojo.tasks.async_dupe_delete[2a5ad001-45e5-4afb-a6ec-0e6bd898d66e]: delete excess duplicates
celeryworker_1  | [2020-04-22 20:28:06,211: INFO/MainProcess] Task dojo.tasks.async_dupe_delete[2a5ad001-45e5-4afb-a6ec-0e6bd898d66e] succeeded in 0.003970844998548273s: None
uwsgi_1         | Internal Server Error: /empty_survey/2/answer
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/defectDojo_engagement_survey/views.py", line 735, in answer_empty_survey
uwsgi_1         |     question.save()
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/defectDojo_engagement_survey/forms.py", line 189, in save
uwsgi_1         |     choice_answer.answer = choices
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 538, in __set__
uwsgi_1         |     % self._get_set_deprecation_msg_params(),
uwsgi_1         | TypeError: Direct assignment to the forward side of a many-to-many set is prohibited. Use answer.set() instead.
nginx_1         | 172.18.0.1 - - [22/Apr/2020:20:28:07 +0000] "POST /empty_survey/2/answer HTTP/1.1" 500 27 "http://localhost:8080/empty_survey/2/answer" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36" "-"
uwsgi_1         | [pid: 1|app: 0|req: 214/492] 172.18.0.1 () {60 vars in 1261 bytes} [Wed Apr 22 20:28:07 2020] POST /empty_survey/2/answer => generated 27 bytes in 131 msecs (HTTP/1.1 500) 6 headers in 192 bytes (1 switches on core 1)
```

**Additional context** (optional)

**Comment by dayal18** [comment]
Thanks, this fix works.
