### ISSUE TITLE
Char 0x0 out of allowed range Error Parsing Acunetix XML File

### ISSUE THREAD

**Issue by zfirered** [DefectDojo/django-DefectDojo#2247]
**Expected behavior**
I want to import another XML but ther is an another Error, i describe bellow

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 18.04

**Screenshots**
![image](https://user-images.githubusercontent.com/17750324/80076761-d5edfb80-8576-11ea-9e46-12decad56c0b.png)

![image](https://user-images.githubusercontent.com/17750324/80076812-e30aea80-8576-11ea-85f7-7e0e0f5f90b5.png)

**Additional context**
Line 9476 is:
<Details><![CDATA[  URL encoded POST input <strong><span class="bb-dark">emails</span></strong> was set to <strong><span class="bb-dark">1 À§À¢%2527%2522</span></strong><br/><br/>  Error message found: <pre><span class="bb-blue">A Database Error Occurred</span></pre>  ]]></Details>

**Comment by zfirered** [comment]
After some infestigation this is was the problem

1 À§À¢%2527%2522

because XML parser wont input that character

**Comment by steeve85** [comment]
According to the [XML specification](https://www.w3.org/TR/xml/#charsets), NULL byte is not valid character. I believe Acunetix should remove invalid XML characters before creating the file. In the meantime, you can manually fix your XML file before importing it into DefectDojo.

**Comment by zfirered** [comment]
> According to the [XML specification](https://www.w3.org/TR/xml/#charsets), NULL byte is not valid character. I believe Acunetix should remove invalid XML characters before creating the file. In the meantime, you can manually fix your XML file before importing it into DefectDojo.

Already done by that, so i have manualy edit the file before upload it
