### ISSUE TITLE
Sorting products alphabetically on /product doesn't work

### ISSUE THREAD

**Issue by Apipia** [DefectDojo/django-DefectDojo#2252]
**Bug description**

**Steps to reproduce**
1. go to All Products
2. Click the Product header to sort the name ascending/descending alphabetically
3. Watch as it work initially, then reloads the table and loses the sort

**Expected behavior**
It would be sorted.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [X] setup.bash / legacy-setup.bash

**Comment by valentijnscholten** [comment]
I think this is by design in order to be able to sort _all_ products and not only the ones on screen. It's just that the datatables javascript component sorts it clients side while the server side request is being displayed. Haven't looked at possible fixes.

**Comment by valentijnscholten** [comment]
Solved by those prs
