### ISSUE TITLE
Cannot create JIRA issues on fresh instance?

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#2258]
**Bug description**
FYI @Apipia 

Upon a new `dev`, the UI makes you think the JIRA gets created successfully, but is not.

```
celeryworker_1  | 2020-04-24T11:12:08.618223025Z [2020-04-24 11:12:08,617: ERROR/MainProcess] Task add_issue_task[5c1d0188-87ca-4dba-bc06-4febfd5140ea] raised unexpected: TypeError("Can't convert 'NoneType' object to str implicitly",)
celeryworker_1  | 2020-04-24T11:12:08.618287910Z Traceback (most recent call last):
celeryworker_1  | 2020-04-24T11:12:08.618303520Z   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 385, in trace_task
celeryworker_1  | 2020-04-24T11:12:08.618317178Z     R = retval = fun(*args, **kwargs)
celeryworker_1  | 2020-04-24T11:12:08.618328610Z   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 650, in __protected_call__
celeryworker_1  | 2020-04-24T11:12:08.618356305Z     return self.run(*args, **kwargs)
celeryworker_1  | 2020-04-24T11:12:08.618380433Z   File "/app/dojo/tasks.py", line 269, in add_issue_task
celeryworker_1  | 2020-04-24T11:12:08.618399602Z     add_issue(find, push_to_jira)
celeryworker_1  | 2020-04-24T11:12:08.618420977Z   File "/app/dojo/utils.py", line 1372, in add_issue
celeryworker_1  | 2020-04-24T11:12:08.618438368Z     jira_conf.finding_text),
celeryworker_1  | 2020-04-24T11:12:08.618454959Z   File "/app/dojo/utils.py", line 1288, in jira_long_description
celeryworker_1  | 2020-04-24T11:12:08.618471991Z     find_id) + "\n\n" + jira_conf_finding_text
celeryworker_1  | 2020-04-24T11:12:08.618490320Z TypeError: Can't convert 'NoneType' object to str implicitly
```

Discovered when trying to find out about https://github.com/DefectDojo/django-DefectDojo/issues/2257. That strack trace also appears twice per aforementioned issue.

**Steps to reproduce**

**Expected behavior**

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
commit 29887635ef26865bcbb9ea49ffe31452d7d761ca

**Comment by madchap** [comment]
Seems that creating the JIRA config through the API now does not work as it used to -- e.g. creating it in a working state.

If I go back into the JIRA configuration and re-enter the password (the same used when creating the API), it's ok.

**Comment by madchap** [comment]
@Apipia any idea why that might be? I could still reproduce this issue right now, while doing some last tests for 1.6.0.

**Comment by valentijnscholten** [comment]
@Apipia I think this can still happen and may need a fix for 1.6.1

**Comment by Apipia** [comment]
Quick analysis makes it seem like there should be some text in the jira_conf.finding_text. According to the model it can be Null/Blank.
`finding_text = models.TextField(null=True, blank=True, help_text="Additional text that will be added to the finding in Jira. For example including how the finding was created or who to contact for more information.")`

So we should probably have a check that it's not None before we try to add it to the description:
`description=jira_long_description(
                                find.long_desc(), find.id,
                                jira_conf.finding_text), ... `
Might be able to get away with something like `jira_conf.finding_text or ""`

**Comment by madchap** [comment]
Consider this: https://github.com/madchap/dojo-helpers/blob/master/jira.py

When invoking this, the JIRA configuration gets created, but is not usable to create issue unless I go back through the UI and re-enter the same password.

So the model change would prevent the stacktrace and could give an informative message, but will not fix the underlying issue I was reporting.
