### ISSUE TITLE
Jira Pull feature

### ISSUE THREAD

**Issue by zorianix** [DefectDojo/django-DefectDojo#2266]
Currently there is no feature which allows to import bugs from jira directly. Considering if a company has already a team internally, they are filling tickets via jira, now they implement DefectDojo, there is no way that they can import that finding from jira directly to DefectDojo. May be a feature something like a jira configuration page where you can choose to put in details like project name , reporter name and jira status and it will just pull all the tickets for that matching criteria and will update metrics based on the ticket severity present in jira

**Comment by valentijnscholten** [comment]
Do you have more ideas on how this could work? Lots of setups have CI/CD engagements with branch names, versions, commit_hashes which I'm not sure we could get from JIRA tickets reliably. Maybe we should put them in a separate engagement? I think it could be useful as also in my company we have security tickets created in JIRA by devs or others and  it might be useful to have those in DD to have one central overview of the status of projects/products.

**Comment by zorianix** [comment]
@valentijnscholten  I implemented this in a different way , since DD doesnt have that

**Comment by devGregA** [comment]
Tagged as archived for now. May revisit in the future, resources allowing.
