### ISSUE TITLE
'Survey' -- Modified as 'Questionnaire'

### ISSUE THREAD

**Issue by dayal18** [DefectDojo/django-DefectDojo#2271]
**Is your feature request related to a problem? Please describe**
The current Dojo application has "Surveys", which might be ok for many, but it would be more professional if we call it a "Questionnaire".

Various questionnaires for various needs.
I'm still trying to modify the length of the TextBoxes, which doesn't look good, any help would be great. (#2265 )

**Describe the solution you'd like**
I have a modified version published here, where I made some changes on the appearance to look as "Security Questionnaire" than just calling it Survey.
The repository is here:
https://github.com/dayal18/defectDojo-engagement-survey.git

**How to install**
Once you get the Dojo Project, modify the requirement.txt to include this repository.

**How to update the current Survey?**
Follow these steps:
Modify your requirements.txt to add this repository (it will be in the last 4th line..)
pip3 uninstall defectDojo-engagement-survey
git clone https://github.com/dayal18/defectDojo-engagement-survey.git
cd defectDojo-engagement-survey && pip3 install .
pip3 install -r requirements.txt --upgrade
python3 manage.py makemigrations defectDojo_engagement_survey
python3 manage.py migrate

**Screenshots**
![image](https://user-images.githubusercontent.com/43857391/80313652-d6260b00-87b1-11ea-9d7c-a846819fbdd3.png)

![image](https://user-images.githubusercontent.com/43857391/80313659-e0480980-87b1-11ea-8ada-23dfc327bbb4.png)

![image](https://user-images.githubusercontent.com/43857391/80313681-1c7b6a00-87b2-11ea-9f1f-edc3f505969b.png)

![image](https://user-images.githubusercontent.com/43857391/80313688-3157fd80-87b2-11ea-81a2-9620ca4e85a5.png)

![image](https://user-images.githubusercontent.com/43857391/80313710-5cdae800-87b2-11ea-8d89-f22c4605a976.png)

**Comment by valentijnscholten** [comment]
I think the survey stuff should be best merged into defect dojo codebase @mtesauro ? Or do we want to keep a separate repo?

**Comment by dayal18** [comment]
#2334
