### ISSUE TITLE
Detail on Acunetix Import

### ISSUE THREAD

**Issue by zfirered** [DefectDojo/django-DefectDojo#2276]
Hey team thanx for Fixing Acunetix Import! :D

can you make mode detail  for Acunetix?
Example when Acunetix found HTML CSRF has 3 finding, but now acunetix import count as 1 HTML CSRF

What i want is Dojo Import the detail too, like
1. HTML CSRF at www.example.com/bla/bla
2. HTML CSRF at www.example.com/asd/
3. HTML CSRF at www.example.com/jkl/

**Comment by steeve85** [comment]
@zfirered can you share an example of Acunetix file? I do not have access to Acunetix to export scan results.

**Comment by zfirered** [comment]
here the example files
[XML_http_example_co_id_.zip](https://github.com/DefectDojo/django-DefectDojo/files/4544179/XML_http_example_co_id_.zip)
