### ISSUE TITLE
Internal Server Error: NoReverseMatch at /engagements_all

### ISSUE THREAD

**Issue by steeve85** [DefectDojo/django-DefectDojo#2278]
**Bug description**

There is an URL resolver issue which break the "All engagements" page.

**Steps to reproduce**
1. Go to 'Engagement'
2. Click on 'All engagements'
3. See error

**Expected behavior**

The page should show all engagements but instead there is an 500 error.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Commit Message: [f8b94207: Bump google-api-python-client from 1.8.0 to 1.8.2 (#2236) [2020-04-25 15:41:58 +0200]]

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

uwsgi_1         | Internal Server Error: /engagements_all
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
uwsgi_1         |     return view_func(request, *args, **kwargs)
uwsgi_1         |   File "./dojo/engagement/views.py", line 130, in engagements_all
uwsgi_1         |     'eng_words': sorted(set(eng_words)),
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/shortcuts.py", line 36, in render
uwsgi_1         |     content = loader.render_to_string(template_name, context, request, using=using)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/loader.py", line 62, in render_to_string
uwsgi_1         |     return template.render(context, request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/backends/django.py", line 61, in render
uwsgi_1         |     return self.template.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 171, in render
uwsgi_1         |     return self._render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 163, in _render
uwsgi_1         |     return self.nodelist.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 937, in render
uwsgi_1         |     bit = node.render_annotated(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
uwsgi_1         |     return self.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/loader_tags.py", line 150, in render
uwsgi_1         |     return compiled_parent._render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 163, in _render
uwsgi_1         |     return self.nodelist.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 937, in render
uwsgi_1         |     bit = node.render_annotated(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
uwsgi_1         |     return self.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/loader_tags.py", line 150, in render
uwsgi_1         |     return compiled_parent._render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 163, in _render
uwsgi_1         |     return self.nodelist.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 937, in render
uwsgi_1         |     bit = node.render_annotated(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
uwsgi_1         |     return self.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/loader_tags.py", line 62, in render
uwsgi_1         |     result = block.nodelist.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 937, in render
uwsgi_1         |     bit = node.render_annotated(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
uwsgi_1         |     return self.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/defaulttags.py", line 309, in render
uwsgi_1         |     return nodelist.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 937, in render
uwsgi_1         |     bit = node.render_annotated(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
uwsgi_1         |     return self.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/defaulttags.py", line 209, in render
uwsgi_1         |     nodelist.append(node.render_annotated(context))
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
uwsgi_1         |     return self.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/defaulttags.py", line 209, in render
uwsgi_1         |     nodelist.append(node.render_annotated(context))
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
uwsgi_1         |     return self.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/template/defaulttags.py", line 443, in render
uwsgi_1         |     url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/urls/base.py", line 90, in reverse
uwsgi_1         |     return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
uwsgi_1         |     raise NoReverseMatch(msg)
uwsgi_1         | django.urls.exceptions.NoReverseMatch: Reverse for 'product_type_metrics' with arguments '('',)' not found. 1 pattern(s) tried: ['metrics/product/type/(?P<mtype>\\d+)$']

**Additional context** (optional)
This issue is present in `dev` branch but also in `master`

**Comment by valentijnscholten** [comment]
Do you have products without a product_type?

**Comment by steeve85** [comment]
Yes. And if I add a product_type the errors is gone.

Currently the WebUI requires to set a product_type when we create a product but not the API (v2). 
To avoid running into this issue, should we modify the /engagements_all page or make the product_type required in API (v2)?

**Comment by JoseRoman** [comment]
@valentijnscholten I can try to tackle this bug, if you don't mind. I think it could be a good way for me to get used to the code base. I'm assuming we want to make product type also required through the API (V2) since it is required on the UI.

**Comment by valentijnscholten** [comment]
I think it should be required everywhere. I think if you make it mandatory on the model, it will be made mandatory everywhere (at least apiv2) automagically.
