### ISSUE TITLE
Products > Contacts Modal

### ISSUE THREAD

**Issue by iLeandro** [DefectDojo/django-DefectDojo#2281]
![enhacement](https://user-images.githubusercontent.com/32276456/80480426-89c10380-8948-11ea-9506-9c18dcd22853.PNG)

The ideia is; in the Product page, in the Contacts area all names (Team Manager, Product Manager) are clickable in a way that pops up a modal with usefull information like the e-mail or the phone of the Team Manager.
This way, I don't have to save it on other places.

**Comment by valentijnscholten** [comment]
Making them clickable should be fairly easy. Are you ready to learn some python + django? :-)

**Comment by iLeandro** [comment]
> Making them clickable should be fairly easy. Are you ready to learn some python + django? :-)

Let's do it together :D
