### ISSUE TITLE
Postgres Install Fails

### ISSUE THREAD

**Issue by kareem-DA** [DefectDojo/django-DefectDojo#2282]
**Bug description**
I am trying to do a stand alone install with an external Postgres database.  I am doing the install on GCP with an Ubuntu 18.04 server and a GCP Postgres DB.    When I run the setup.bash, I get a time out when setting up the database

1. Setup Ubuntu server
2. Setup Postgres DB
3. Run setup.bash. I selected the following options 
- Installation Type:  3 - stand alone server
- Database Type:  3 - PostgreSQL
- Location: 1 - Remote
- Install DB during setup: 2 - Postgres already running
- Keep Existing DB: 1 - Drop existing
- DB Name: “dojodb”
- DB User: “dojodbusr”
- DB Password: <removed>
- DB Host: <IP Removed>
- DB Port: 5432
- Accept the Install OS Config
- Accept the Defect Dojo App.

**Expected behavior**
I see the message "Biginning Ubuntu Installation" and then the install appears to time out.  Looking at the code, It looks like its executing the script "scripts/os/linux.sh".  It runs the function "ubuntu_db_config()".  $DB_LOCAL=false, so the code then executes line 60, ‘if mysql -fs -h “$DB_HOST” -P “$DB_PORT” -u”$DB_USER” -p”$DB_PASS” -e “quit” > /dev/null 2>&1; then’….
It tries to connect to a postgres database with a mysql client… 

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [ X] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 18.04 and PostgreSQL 10

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
==============================================================================
  Python 3.6.9 found, continuing install
==============================================================================

==============================================================================
  Starting the install of Defect Dojo
==============================================================================

==============================================================================
  Linux install target
==============================================================================

==============================================================================
  Beginning Ubuntu installation
==============================================================================

##############################################################################
#  ERROR: Remote PostgreSQL server connectivey failed - exiting                #
##############################################################################

**Additional context** (optional)

**Comment by valentijnscholten** [comment]
Can you connect succesfully to postgress from the same box manually?

**Comment by kareem-DA** [comment]
Yes, before I submitted the bug, I did make sure that I could connect from the server to the database directly.

**Comment by valentijnscholten** [comment]
Postures DB needs to be created before running the install. This is now documented and checked by the script.
