### ISSUE TITLE
Selenium test report generated via testng import

### ISSUE THREAD

**Issue by himani-dangwal** [DefectDojo/django-DefectDojo#2292]
Selenium test report which is generated via test-ng .it provides an xml file in output

Here is  a sample file for the same
[testng-results.zip](https://github.com/DefectDojo/django-DefectDojo/files/4551775/testng-results.zip)

**Comment by valentijnscholten** [comment]
Could you describe how you see the info from testng reports mapped to defect dojo findings? i.e. what should be the title, severity, description, cwe, etc?
