### ISSUE TITLE
HTML Report - Charts doesn't work

### ISSUE THREAD

**Issue by dayal18** [DefectDojo/django-DefectDojo#2294]
**Bug description**
The charts on the HTML Report doesn't work in a combination of "Table of Contents".
If you just select "Executive Summary" or any combination except "Tabel of Contents" the charts work. With "Table of Contents" the chart doesn't work (I guess something on the CSS files because of same name? probably?)

**Steps to reproduce**
1. Go to 'Product or Engagement or Test'
2. Click on 'Product Report / Engagement Report'
3. Apply the 'findings filers for the report'
4. Select the 'Table of Contents and Executive Summary'
5. Select 'HTML' and click on Generate Report
6. Scroll down to 'Executive chart section and the charts don't work'
7. Do the same thing again without "Table of Contents" and the chart works.

**Expected behavior**
The charts should show even when the Table of Contents is selected.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [x] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [Ubuntu 18.04]

Update to issue #2238

**Comment by iLeandro** [comment]
Working on Firefox.
NOT working on Chrome

**Comment by JoseRoman** [comment]
I'll try to fix this @dayal18 can you assign this issue to me please

**Comment by dayal18** [comment]
I don't know if I have permission to do that.. I'll have to request @valentijnscholten or @Maffooch to do that.

**Comment by JoseRoman** [comment]
No worries

**Comment by dayal18** [comment]
The chars work now with a combination of "Executive Summary" + "Table of Contents" on Chrome..
But it doesn't work with a combination of "Finding Images"

**Comment by dayal18** [comment]
So, further testing reveals 'Table of contents' and 'Finding Images' cannot be used together.
The images retrieved from 'Finding Images' in the HTML report, when I open it in new-tab.. it gives me a 403 error as well.. Looks like the images are created and destroyed immediately from the sever.
