### ISSUE TITLE
SSLyze: Client renegotiation vulnerability is not added via scan import

### ISSUE THREAD

**Issue by AlexanderTyutin** [DefectDojo/django-DefectDojo#2295]
SSLyze output:
```
Client-initiated Renegotiation:    VULNERABLE - Server honors client-initiated renegotiations"
```

XML report entity:
```
      <reneg title="Session Renegotiation">
        <sessionRenegotiation canBeClientInitiated="True" isSecure="True"/>
      </reneg>
```

Expected DefectDojo result:
* high or critical finding created

Real result:
* No finding about client-renegotiation created

**Comment by steeve85** [comment]
Can you share the command you ran and/or the XML file?

**Comment by AlexanderTyutin** [comment]
Actually I found a lot of obsoleted stuff in the SSlyze parser and made a full refactoring. Will write also integration tests and make the PR.
