### ISSUE TITLE
Closed Finding not Counting on Metrics

### ISSUE THREAD

**Issue by zfirered** [DefectDojo/django-DefectDojo#2296]
**Bug description**

**Steps to reproduce**
1. Go to 'Finding'
2. Click on 'Close Finding'
4. Go to Metrics
5. Closed Finding always count as 0

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 18.04

**Screenshots**
![image](https://user-images.githubusercontent.com/17750324/80645116-e03b5880-8a94-11ea-9254-f55ebd9c6b43.png)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Thank You Team! Your'e the best!

**Comment by iLeandro** [comment]
Here it's working.
What is your DefectDojo version?

If you edit the vulnerability and uncheck "Active" option it should go to Closed Findings too.

**Comment by valentijnscholten** [comment]
known issue, will be picked up as part of #2215 I think the idea is that mitigated is different from closed.
