### ISSUE TITLE
Default sorting by severity is not performed by severity value

### ISSUE THREAD

**Issue by AlexanderTyutin** [DefectDojo/django-DefectDojo#2298]
Sorting by severity is not performed by severity value

![image](https://user-images.githubusercontent.com/49285004/80652718-3900f600-8a81-11ea-84d1-470978887cc1.png)

**Comment by valentijnscholten** [comment]
which page/url is this? For me it's working on open/closed/all findings list.

**Comment by iLeandro** [comment]
> which page/url is this? For me it's working on open/closed/all findings list.

I did not test in all, but in Open Findings it starts loading by severity but then it "breaks".

In my case it starts with Critical High Medium on load. When it loads becomes Medium High Critical.

**Comment by iLeandro** [comment]
![11111](https://user-images.githubusercontent.com/32276456/80754394-db26e980-8b26-11ea-80a9-245516f464bf.PNG)

Ok. I've found the issue. if you click that little icon instead of clicking on severity text, it correctly sorts

**Comment by bbirkinbine** [comment]
Not exactly sure what is in control of the column sort here.  Clicking on the arrow with the stairstep icon appears to do a sort via the UI (didn't see any calls to the server), verses clicking on the 'Severity' column name makes a call to the server to retrieve new data.

In both cases, the severity appears to be ascending (or descending) with regard to the Severity strings of 'Critical', 'High', 'Low', etc versus a numeric/ordinal version of Critical High Medium Low, etc.  Not sure if the data retrieved is sorted correctly or if the UI elements are automatically sorting the elements incorrectly (aria-sort = ascending or descending).

I've uploaded some screenshots showing the improper ordering of the Severity (which appear to be sorted based on literal String of Critical/High/Medium/Low/Info.
![Screen Shot 2020-04-30 at 19 54 47-highlight](https://user-images.githubusercontent.com/585281/80772208-f17f7600-8b23-11ea-9456-53ec28b271ea.png)
![Screen Shot 2020-04-30 at 19 55 22-highlight](https://user-images.githubusercontent.com/585281/80772210-f5ab9380-8b23-11ea-81b7-1360e48e7f9a.png)

**Comment by valentijnscholten** [comment]
Ok, this occurs because we recently fixed the datatables sorter that was broken. And it now sorts by severity but the javascript only knows the text labels, so it sorts them by label even though the server initially sent them ordered by numerical severity. We'll have to check if the datatables library supports sorting by something other than the text label. Or we should remove client side sorting for severity. Or remove client side sorting alltogether when we're in paged mode :-)

**Comment by valentijnscholten** [comment]
I fixed the default sorting on initial page load on #2311. I opened #2312 as a new bug report to fix the remaining part as the issue here is already mixing 2 things :-)
