### ISSUE TITLE
Installing DefectDojo without (full) EPEL

### ISSUE THREAD

**Issue by immewnity** [DefectDojo/django-DefectDojo#2307]
Supposedly, we're not allowed to use EPEL at my org due to contract issues (ridiculous, I know). Without going through the hundreds of EPEL packages, does anyone know which packages are actually used by DefectDojo? I might be able to clear individual packages through our server ops team.

(I know this isn't technically a *feature* request, but not sure what it might better fit as)

**Comment by valentijnscholten** [comment]
Looking throught the setup bash script and/or docker files may be helpful. Or do a quick install and see what packages it needs, shouldn't be too exotic.

**Comment by immewnity** [comment]
I've been trying, but EPEL is a package of packages, so the install scripts just mention epel-release (same for an install of course, just pulls the epel package). In order to see the packages used within epel, one would have to look through the entire project.

**Comment by valentijnscholten** [comment]
My idea was to comment that out and you'll run into errors which indicate what is missing.

**Comment by immewnity** [comment]
Clever idea... thanks.
________________________________

**Comment by devGregA** [comment]
I'm going to go ahead and archive this because I don't believe there is any bandwith for something like this. As an archived issue, this maybe something we address in the future.
