### ISSUE TITLE
Unused edit github views/file

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#2327]
When looking at files that are not referenced anywhere in the codebase, I found that:

- `edit_github.html` is not used anywhere
- `edit_github` function in `github_issue_link/views.py` does nothing
- url pattern for `edit_github` is not used anywhere.

@mestrade can these be removed or do they need implementation?

**Comment by mestrade** [comment]
I’m planning a second effort soon by implementing bi directional update and
a more mature code. Hope to be able to do that before this summer. I don’t
mind if you delete it, Up to you :)

Le lun. 4 mai 2020 à 23:25, valentijnscholten <notifications@github.com> a
écrit :

**Comment by valentijnscholten** [comment]
Covered by #2336
