### ISSUE TITLE
API v2 updating a finding on a product with no JIRA configuration leads to 500

### ISSUE THREAD

**Issue by Apipia** [DefectDojo/django-DefectDojo#2332]
**Bug description**
API call to PATCH request on /finding/{ID} leads to a 500 if the product doesn't have a JIRA configuration 

**Additional context** (optional)

Change:
if get_system_setting('enable_jira') and JIRA_PKey.objects.filter(
                product=serializer.instance.test.engagement.product) != 0:
To:
if get_system_setting('enable_jira') and \
                serializer.instance.test.engagement.product.jira_pkey_set.first() is not None:

**Comment by madchap** [comment]
@Apipia I am closing this, assuming the PR effectively fixes it. It will be backported for 1.6.0.
