### ISSUE TITLE
CI/CD Imported Scans doesn't deduplicate findings with APIv2

### ISSUE THREAD

**Issue by al3ks1s** [DefectDojo/django-DefectDojo#2338]
**Bug description**
When importing Trivy scans through the APIv2, the findings aren't deduplicated, even with "deduplication on engagement" and system deduplication on.

**Steps to reproduce**
Import scans using the APIv2

**Expected behavior**
Duplicates findings gets marked as such.

**Deployment method** *(select with an `X`)*
- [ X ] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - DefectDojo version :  v. 1.5.4

**Comment by valentijnscholten** [comment]
If you enable dedupe on engagement it will only deduplicate findings within that engagement. Can you provide deduplicationlogger (DEBUG) logs?
