### ISSUE TITLE
Limit on report size that can be imported

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#2346]
**Is your feature request related to a problem? Please describe**
Right now, anyone can import any size a report, which can lead to a DoS -- as I can experiment now. For example, git repositories scans can generate a ton of findings (esp. if you don't pay the right attention to false-positives). 
In my case, well over 100K across all branch caused a DoS on my instance.

We should have an upper limit to mitigate DoS.

**Describe the solution you'd like**
The idea is to limit -- both at UI and API levels -- the size of the report that can be uploaded. It could be number of rows or file size.

**Comment by valentijnscholten** [comment]
isn't there a limit by default? we get questions about how to raise the limit on a weekly basis in the clack channel. Or is that only for the standalone / setup.bash installs?

**Comment by madchap** [comment]
Maybe through the UI, but not the API somehow.

**Comment by madchap** [comment]
https://github.com/DefectDojo/django-DefectDojo/blob/dev/nginx/nginx.conf#L14

800m.. we're asking to be DoS'ed it seems.

**Comment by Maffooch** [comment]
Seems to be fixed
