### ISSUE TITLE
Node.js 6.x LTS Boron Deprecation Warning

### ISSUE THREAD

**Issue by Chan9390** [DefectDojo/django-DefectDojo#2374]
**Bug description**

With a clean install of the DefectDojo setup, I get a deprecation notice from NodeJS. This is because of the following nodesource url in config-vars

https://github.com/DefectDojo/django-DefectDojo/blob/d411791a84ad5b84ee4d5706d855d83c07afaa32/setup/scripts/common/config-vars.sh#L115

**Steps to reproduce**

```
$ sudo mkdir /opt/dojo
$ cd /opt/dojo
$ sudo git clone https://github.com/DefectDojo/django-DefectDojo --depth 1
$ cd django-DefectDojo
$ sudo ./setup/setup.bash

...
Select install type: (1) Single-Server, (2) Dev Install or (3) Stand-alone: 1
...
Select database type: (1) SQLite, (2) MySQL or (3) PostgreSQL: 2
...
Select (1) Remote, (2) Local: 2
...
Select (1) Install of MySQL required, (2) MySQL server already exists/is running: 1
...
Select (1) Drop existing database, (2) Keep existing database & exit: 1
...
Current MySQL database install config includes:
Do you want to change any of these values? Select (1) Yes, (2) No: 2
...
Current OS install config includes:
Do you want to change any of these values? Select (1) Yes, (2) No: 2
...
Current admin user config for DefectDojo:
Do you want to change any of these values? Select (1) Yes, (2) No: 2
...
...
Deprecation Warning
```

![image](https://user-images.githubusercontent.com/12944530/82135254-3db60000-981e-11ea-924f-82a2bb4c0019.png)

**Expected behavior**
Non-deprecated version of NodeJS should be used by default.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [x] setup.bash

**Environment information**
 - Operating System: Ubuntu 18.04
 - DefectDojo Commit Message: `027d879: Fixes to plantuml action [2020-05-09 06:50:52 +0200]`

**Comment by Chan9390** [comment]
The fix is merged to `dev` branch in #1902 

However in master and other branches like `1.5.4.1` its still 6.x

https://github.com/DefectDojo/django-DefectDojo/blob/e73f033ca7d582acb69ac30c337c13ffe21848ab/setup/scripts/common/config-vars.sh#L115

Is `dev` branch stable and production ready ?

**Comment by valentijnscholten** [comment]
No, but release 1.6.0 is around the corner.

**Comment by Chan9390** [comment]
Yes. `release/1.6.0` branch worked perfectly.

Is it intentional to not update the master branch and then create a release branch from it ?

The `release/1.6.0` branch says 348 commits ahead & 61 commits behind master. Thats a lot of difference IMO.

**Comment by valentijnscholten** [comment]
Should be all good now, dev will become in sync with master after we merge back 1.6.5 into dev.
