### ISSUE TITLE
Python dependencies incompatibility 

### ISSUE THREAD

**Issue by Chan9390** [DefectDojo/django-DefectDojo#2375]
**Bug description**
Python dependencies like `django-auditlog 0.4.7` and `django-overextends 0.4.3` have other dependencies. However, the incompatible versions of other dependencies are already installed which leads to a error message during installation.

**Steps to reproduce**

```
$ sudo mkdir /opt/dojo
$ cd /opt/dojo
$ sudo git clone https://github.com/DefectDojo/django-DefectDojo --depth 1
$ cd django-DefectDojo
$ sudo ./setup/setup.bash

...
Select install type: (1) Single-Server, (2) Dev Install or (3) Stand-alone: 1
...
Select database type: (1) SQLite, (2) MySQL or (3) PostgreSQL: 2
...
Select (1) Remote, (2) Local: 2
...
Select (1) Install of MySQL required, (2) MySQL server already exists/is running: 1
...
Select (1) Drop existing database, (2) Keep existing database & exit: 1
...
Current MySQL database install config includes:
Do you want to change any of these values? Select (1) Yes, (2) No: 2
...
Current OS install config includes:
Do you want to change any of these values? Select (1) Yes, (2) No: 2
...
Current admin user config for DefectDojo:
Do you want to change any of these values? Select (1) Yes, (2) No: 2
...
...
Python dependencies error
```

![image](https://user-images.githubusercontent.com/12944530/82135415-2bd55c80-9820-11ea-9935-09bced26a7d8.png)

**Expected behavior**
The dependencies should be compatible. 

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [x] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 18.04
 - DefectDojo Commit Message: `027d879: Fixes to plantuml action [2020-05-09 06:50:52 +0200]`

**Comment by Chan9390** [comment]
`django-auditlog 0.4.7` was introduced by #1763

**Comment by Chan9390** [comment]
If the dependency errors doesnt break anything then please close the issue. If possible add it to the documentation.

**Comment by valentijnscholten** [comment]
There no newer versions of those libraries available, so I guess we'll have to stop using them or just hope they don't brake anything. I think we are not using django-overtends ourselves, so we could maybe remove it from requirements.txt?

**Comment by Chan9390** [comment]
That would work.

**Comment by valentijnscholten** [comment]
https://github.com/jjkester/django-auditlog/issues/250

**Comment by valentijnscholten** [comment]
overextends is needed by the survey part of DD, to be merged into here.
https://github.com/DefectDojo/django-DefectDojo/pull/2334

**Comment by valentijnscholten** [comment]
For now going to close this one as either it's been raised in other tickets or we can't do anything about it currently. Dependabot will warn is if newer versions are available.
