### ISSUE TITLE
Set SonarQube project ID via API

### ISSUE THREAD

**Issue by cpandya2909** [DefectDojo/django-DefectDojo#2376]
I am trying to create a new project via API and I want to set SonarQube project ID so that I can run sonarqube API import. But I do not see any API option to set project id value. 

Please help in what API needs to call to set the SonarQube project ID.

**Comment by valentijnscholten** [comment]
This is currently not possible it seems, you may want to try and persuade @twsagarcia to add this to the api(v2).

**Comment by cpandya2909** [comment]
Hi @twsagarcia, can we make an API parameter at project creation to add SonarQube project ID?

**Comment by Maffooch** [comment]
Fixed by #2683
