### ISSUE TITLE
Assign permissions to engagement

### ISSUE THREAD

**Issue by anakin1** [DefectDojo/django-DefectDojo#238]
We have a common use case where project managers or development team may be responsible for remediating issues found during a particular engagement, so the PMs/devs need permission to view findings found during the engagement so that they can remediate them, but should not be able to view other findings for the product.

**Comment by devGregA** [comment]
Hi @anakin1 this one seems strange to me. Do you break down products further into 'apps'? Why would it be okay for devs to see some issues in their product but not others?

**Comment by anakin1** [comment]
Hi @devGregA, we do break some products down into apps (microservices), but we also have a lot of legacy code for some very large products (e.g. banking apps) where project teams are spun up to add new features over a couple of sprints, and then they might move on to another feature. The project team needs to see issues that they've introduced, but ideally should not be able to see other existing open issues. Perhaps we are a "special" case :)

**Comment by devGregA** [comment]
Hi @anakin1 I recently re-did authorized user permissions, which might work in your case (PR is coming tomorrow), however, it now let's users view all issues for a given product which sounds too permissive. Unfortunately, I don't think there is any bandwith for the maintainers to get this on the roadmap. If you have an in house python developer, I don't think this would take them a lot of time (or if you could briefly get a contractor).I'm archiving this issue for now, but may get to it in the future.
