### ISSUE TITLE
Dojo Survey (Multiple Choice - UI rendering issues)

### ISSUE THREAD

**Issue by dayal18** [DefectDojo/django-DefectDojo#2382]
**Bug description**
The multiple-choice selection in the Defectdojo Survey doesn't display the UI in the intended way.
The UI needs to be fixed to allow Multile-choice to be better visible

**Steps to reproduce**
1. Go to 'Create survey with Multiple-choices'
2. Send Survey 'via link, with the new survey just created'
3. Scroll down to 'Multiple choice question in the survey and you'll see the UI doesn't handle it properly.'

**Expected behavior**
The UI should handle Multiple Choices and render them properly.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [x] setup.bash / legacy-setup.bash

**Environment information**
 - Ubuntu 18.04
 - DefectDojo 1.6.0

**Screenshots** (optional)
![image](https://user-images.githubusercontent.com/43857391/82170476-257bca80-988a-11ea-9ed3-86616d7a11e8.png)

**Comment by JoseRoman** [comment]
I think we will have to wait until #2334 is merged to fix this.

**Comment by dayal18** [comment]
Thanks @JoseRoman
