### ISSUE TITLE
bulk edit findings bypasses audit log

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#2388]
The bulk editing of findings bypasses the audit log. The audit log works by using django signals. These are only triggered on regular inserts and saves, but not on the  bulk `queryset.update()` used by the bulk edit code.

**Comment by valentijnscholten** [comment]
This more or less the same with every audit log library due to how these bulk queries work. We may first want to decide which audit log library we want to use before we try and fix this. The `django-auditlog` we now have seems quite limited and not very active (django 2 not supported yet). Looking at https://djangopackages.org/grids/g/model-audit/ and some of those on there it seems `django-simple-history` is the best fit: https://django-simple-history.readthedocs.io/en/latest/index.html

**Comment by mtesauro** [comment]
I don't have a strong opinion on a replacement but I'm all for removing a somewhat stale library (django-auditlog) especially if it's not working for DD.
From a very quick look, django-simple-history looks good.
