### ISSUE TITLE
Aqua scanner format no longer working

### ISSUE THREAD

**Issue by jvz** [DefectDojo/django-DefectDojo#2389]
**Scanner Name**
Aqua.

**Sample File**
@madchap I have a sample file internally from a real report. The gist here is that the old aqua file format uses a top level JSON key called "resources" where each scanned item has a list of vulnerabilities. In the new format (or at least the alternative format?), the top level JSON key is called "cves" and has flattened the structure to be more similar to how the Anchore file format works.

**Comment by Maffooch** [comment]
Couple different associated PRs merged
