### ISSUE TITLE
delete finding template test failing since chrome 83 upgrade

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#2400]
Happens during integration tests. Doesn't seem to be a bug in DD itself.
Test is disabled for now.
```
test_delete_finding_template (__main__.FindingTest) ... ERROR
======================================================================
ERROR: test_delete_finding_template (__main__.FindingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/Finding_unit_test.py", line 254, in test_delete_finding_template
    productTxt = driver.find_element_by_tag_name("BODY").text
  File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=83.0.4103.61)
````

**Comment by JoseRoman** [comment]
@Maffooch @valentijnscholten should we consider using/setting up Browserstack? It can help find cross-browser compatibility issue early on. It is also free for open-source projects.

**Comment by JoseRoman** [comment]
@Maffooch @valentijnscholten Would you guys be open to switching to [Cypress](https://www.cypress.io/features) for the tests? I would be more than happy to volunteer to migrate what we have so far. We could also run them both at the same time until one of them is retired.

**Comment by valentijnscholten** [comment]
I'm not a really a front-end dev, but from their homepage it sounds like Cypress is easier than Selenium which I've always found to be very clunky. As longs as we don't get any NodeJS callback hell, I'm good with switching as long as we don't go downwards in coverage.

**Comment by valentijnscholten** [comment]
Do they provide CI/CD on their side, or do we still run in travis? What would be a big benefit is if we could see what is/was going on in a failed test. Screenshots, logs, whatever. With selenium you can't even choose the let it log what it doing.

**Comment by JoseRoman** [comment]
Awesome! I started working last night on migrating some of the current
tests over to Cypress. I’ll make a PR once I feel like I have enough tests
done. And like I said, we can always keep them both until we feel
comfortable.

**Comment by JoseRoman** [comment]
> Do they provide CI/CD on their side, or do we still run in travis? What would be a big benefit is if we could see what is/was going on in a failed test. Screenshots, logs, whatever. With selenium you can't even choose the let it log what it doing.

@valentijnscholten  We can still run them through Travis. Debugging failed tests is 100x easier with Cypress, in my opinion. 

https://docs.cypress.io/guides/guides/debugging.html

We can record videos of the tests, take screenshots, and also look step by step in a browser how the test is running.

**Comment by valentijnscholten** [comment]
I think we would have to find out how we can get Travis to store those artifacts somewhere. Also, if you're a front-end developer, you might be thinking the DD UI is a bit old school and needs more ajaxy stuff?

**Comment by JoseRoman** [comment]
I was a “Full Stack” developer for a while, but my strength is definitely
on the front-end side. And yes, the front-end does need some work and
organization. Are you guys open to some PRs for improvement of the
front-end? I would be interested in helping with that too.

**Comment by valentijnscholten** [comment]
Maybe start a thread on Slack cause I am not the only one to decide :-)

**Comment by valentijnscholten** [comment]
fixed by PRs.
