### ISSUE TITLE
codermirror / simplemde loading 3rd party javascript

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#2410]
In https://travis-ci.org/github/DefectDojo/django-DefectDojo/jobs/690298613 the job failed because 3rd party javascript could not be loaded. It is being loaded by codemirror which I believe is part of the simplemde markdown editor we use (Client-side).
Not sure if we feel fine with 3rd party javascript being loaded. Strange thing is nobody every complained about it when there must be corporate who haven't whitelisted this domain.

```
test_create_product (__main__.ProductTest) ... ×
Product added successfully.
{'level': 'SEVERE', 'timestamp': 1590226648051, 'source': 'network', 'message': 'https://cdn.jsdelivr.net/codemirror.spell-checker/latest/en_US.aff - Failed to load resource: net::ERR_CONNECTION_RESET'}
``` 

![image](https://user-images.githubusercontent.com/4426050/82727358-490b9e80-9cea-11ea-8140-3a90b72841c7.png)

I think the simplemde is deprecated anyway, so we need to find a replacement.

**Comment by JoseRoman** [comment]
Looks like https://github.com/Ionaru/easy-markdown-editor is the most popular and active fork of simplemde.

**Comment by valentijnscholten** [comment]
Yeah, I thought I already documented that somewhere in an issue, but not sure. Should be more or less a drop in replacement...

**Comment by JoseRoman** [comment]
Going to give this a try @valentijnscholten

**Comment by JoseRoman** [comment]
@valentijnscholten I believe #2413 fixes this problem since we also turned `spellChecker` off.
