### ISSUE TITLE
Internal error when closing SonarQube finding

### ISSUE THREAD

**Issue by cpandya2909** [DefectDojo/django-DefectDojo#2411]
**Bug description**
Have imported findings from SonarQube API, but when I close finding Dojo, It is giving 500 error

> uwsgi_1         | applying rules
uwsgi_1         | Internal Server Error: /finding/6432/close
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
uwsgi_1         |     return self.cursor.execute(sql, params)
uwsgi_1         | psycopg2.errors.StringDataRightTruncation: value too long for type character varying(100)
uwsgi_1         | 
uwsgi_1         | 
uwsgi_1         | The above exception was the direct cause of the following exception:
uwsgi_1         | 
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
uwsgi_1         |     return view_func(request, *args, **kwargs)
uwsgi_1         |   File "./dojo/finding/views.py", line 785, in close_finding
uwsgi_1         |     url=request.build_absolute_uri(reverse('view_test', args=(finding.test.id, ))),
uwsgi_1         |   File "./dojo/utils.py", line 1714, in create_notification
uwsgi_1         |     send_alert_notification()
uwsgi_1         |   File "./dojo/utils.py", line 1680, in send_alert_notification
uwsgi_1         |     alert.save()
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 741, in save
uwsgi_1         |     force_update=force_update, update_fields=update_fields)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 779, in save_base
uwsgi_1         |     force_update, using, update_fields,
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 870, in _save_table
uwsgi_1         |     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 908, in _do_insert
uwsgi_1         |     using=using, raw=raw)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
uwsgi_1         |     return getattr(self.get_queryset(), name)(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1186, in _insert
uwsgi_1         |     return query.get_compiler(using=using).execute_sql(return_id)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1368, in execute_sql
uwsgi_1         |     cursor.execute(sql, params)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 67, in execute
uwsgi_1         |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
uwsgi_1         |     return executor(sql, params, many, context)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
uwsgi_1         |     return self.cursor.execute(sql, params)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
uwsgi_1         |     raise dj_exc_value.with_traceback(traceback) from exc_value
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
uwsgi_1         |     return self.cursor.execute(sql, params)
uwsgi_1         | django.db.utils.DataError: value too long for type character varying(100)

**Expected behavior**
Finding not closed on SonarQube

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System:  Ubuntu 16.04

**Comment by valentijnscholten** [comment]
Which version are you on? I think it's master because it's using the old notification code. Looks likes either the source or title field is too long, we can truncate those in alerts I guess.

**Comment by valentijnscholten** [comment]
Fixed by #2412, probably going to be in 1.6.1 bugfix release.

**Comment by cpandya2909** [comment]
Did git clone of the master branch and done docker build

**Comment by valentijnscholten** [comment]
The next release is 1.6.5 and will contain PR2412
