### ISSUE TITLE
Questionnaire / Survey - Multiple Check box, answers doesn't populate in the response

### ISSUE THREAD

**Issue by dayal18** [DefectDojo/django-DefectDojo#2419]
**Bug description**
One the questionnaire/survey with multiple choice is filled in, the response don't show the options selected.

**Steps to reproduce**
1. Go to 'Create a survey with multiple-choice'
2. Click on 'submit the multiple-choice questionnaire/survey'
3. Scroll down to 'Once the submission is received on Dashboard, click and view the Questionnaire / Survey -- The Multiple-choice will not get selected' (radio buttons get selected and populated)

**Expected behavior**
The multiple-choice should also show the options that responded to the response view.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [x] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [Ubuntu 18.04]
 - DefectDojo Commit Message: 1.6.0 (with fixes from @Maffooch  on Survey / Questionnaire Module)

**Screenshots** (optional)
![image](https://user-images.githubusercontent.com/43857391/82744793-e98dad00-9d42-11ea-8bb7-210436087e33.png)

**Comment by cody-m-tibco** [comment]
There is a big disconnect on the survey/questionnaire front between 1.6 and dev.
The dev branch has surveys integrated into DD completely with fixes being in DD.
1.6 still has surveys/questionnaires hosted on another repository and then installed at install time. The bugs you're finding are likely due to this disconnect. In fact, a lot of the bugs came from that merger.

**Comment by JoseRoman** [comment]
@cody-m-tibco @dayal18 I have a draft PR #2420 with a bunch of changes to improve the adoption of survey/questionnaire into DD. Not sure if it will fix this issue, but planning on finishing it tonight, I can verify if this issue is still happening.

**Comment by dayal18** [comment]
Thanks Jose, I think the issue still exists. I tired to make the changes in
my local and still was still facing the issue with no results.
Once the questionnaire is submitted I also tried to edit it, but the
answers for multiple choice never gets saved or retrieved.
