### ISSUE TITLE
Only add new SonarQube issues when using re-import

### ISSUE THREAD

**Issue by cpandya2909** [DefectDojo/django-DefectDojo#2422]
I have coded a webhook that as soon as a sonarqube scan is finished, I call Dojo API to re-import the SonarQube API import test. This creates tones of duplicate findings and the dashboard also loses count of Open findings and Dashboard shows 0 open findings. 

Or please suggest any more workflow.

**Comment by valentijnscholten** [comment]
Do you have deduplication enabled? It should deduplicate after the import in the background celery process. Not ideal, but should work.

**Comment by cpandya2909** [comment]
yes, deduplication is selected,

**Comment by cpandya2909** [comment]
Hi @valentijnscholten , had you a chance to look into it?
