### ISSUE TITLE
Exposing Finding.sla to API

### ISSUE THREAD

**Issue by edersonbrilhante** [DefectDojo/django-DefectDojo#2423]
Hey team :)

**Is your feature request related to a problem? Please describe**
I would like to use Defectdojo API in my CI/CD, in the way I can config jobs to failed or not based on SLAs and severity.

**Describe the solution you'd like**
Premisses: I am sending reports to defectdojo:
Eg: I have 1 repo that is been scanned by static analysis code. If the SAST tool finds 1 vuln with a medium severity, I will have 30 days to fix it. In case the next job finds the same vuln, the job should fail if SLA is overdue.
This logic could be possible using "finding" property "sla" in api.

What do you think? Does make sense to expose this property?

**Comment by valentijnscholten** [comment]
It makes sense and I'm pretty sure I'll need it at some point, so I created a PR.
It returns age and sla_days_remaining. Returning the colour is not a quickfix as we only use that in the html templating layer. Does this help?

**Comment by edersonbrilhante** [comment]
@valentijnscholten I tested here, it is a good solution for me.

**Comment by madchap** [comment]
I am guessing this can be closed @edersonbrilhante ?

**Comment by edersonbrilhante** [comment]
@madchap Yes. Thanks for your contribution @valentijnscholten 
Closing :)
