### ISSUE TITLE
Azure SSO is not working

### ISSUE THREAD

**Issue by cpandya2909** [DefectDojo/django-DefectDojo#2424]
**Bug description**
I have provided Azure SSO details but still do not see login with the Azure button.

**Steps to reproduce**
1. Git clone the defectdojo and cd to dir
2. Create SSL certificates
3. Configure Azure details in dojo/settings/settings.dist.py.

> DD_SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_ENABLED=(bool, 'True'),
    DD_SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_KEY=(str, '6c1cb3a0-XXXX-XXXX-9d9e-7fa49ddd4cea'),
    DD_SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_SECRET=(str, 'XXXX'),
    DD_SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_TENANT_ID=(str, '89359cf4-XXXX-XXXX-80c4-775a0cfe27a7'),
    DD_SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_RESOURCE=(str, 'https://graph.microsoft.com/'),
4. Do docker-compose build and docker-compose up.
5. Go to Dojo URL but do not see the Azure login button.

**Expected behavior**
After configuring Azure details, I should see login with the Azure button.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System:  Ubuntu 16.04

**Comment by xens** [comment]
'True' is not a bool it's a string
```
DD_SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_ENABLED=(bool, 'True'),
```

Can you try to remove the single quotes around it ?

**Comment by cpandya2909** [comment]
It worked, thanks
