### ISSUE TITLE
Install DefectDojo on OCI Virtual Machine (Oralcle Cloud)

### ISSUE THREAD

**Issue by frocchi14** [DefectDojo/django-DefectDojo#2430]
I'm not able to install DefectDojo on OCI using user linux "opc"

II'm trying to install DefectDojo on Oracle Cloud. The Virtual Machiene created (VM) there is the following sw:

- Oracle Linux 7.8
- Tomcat 9.0.35
- Java 8
OCI don't provide "root" credential for security reasons and you must use the user "opc" with "sudo". I executed the following steps:
1. downolad DefectDojo 
2. I run "./setup.bash" and I chose the simple installation with defoult parameters.
3. After the request "ocp" password the install finished with the following error:

[sudo] password for opc:
================================================================
  Sufficient priveleges found, continuing installation
================================================================
##########################################################################
#  ERROR: Unknown or NIY OS - exiting                                        #
##########################################################################

I repeted the istallation using "sudo":

1. sudo ./setup.bash
2. I run "./setup.bash" and I chose the simple installation with defoult parameters.

I receved the following error:
================================================================
  Install user is root, sudo access not required, continuing installation
================================================================

##########################################################################
#  ERROR: Unknown or NIY OS - exiting                                        #
##########################################################################

I attach the log file for both installation.
Can you help me

Thanks

[defectdojo.txt](https://github.com/DefectDojo/django-DefectDojo/files/4689176/defectdojo.txt)
[defectdojo_sudo.txt](https://github.com/DefectDojo/django-DefectDojo/files/4689177/defectdojo_sudo.txt)

**Comment by JoseRoman** [comment]
I don't think the OS you are trying to use is supported.

**Comment by valentijnscholten** [comment]
Oracle is not supported/tested, but the script can help you to install it by looking through its source and executing the steps and adapt them to oracle linux.
The easiest way to get started though is the docker-compose way.
