### ISSUE TITLE
Use DefectDojo to manage vulnerability from NVD Data Feeds

### ISSUE THREAD

**Issue by NRGLine4Sec** [DefectDojo/django-DefectDojo#2433]
**Describe the solution you'd like**
It would be great if DefectDojo could be used to automatically download, filter for one product and  open in DefectDojo a vulnerability by itself.

For exemple, if I want to monitor OpenSSL , I create a product named "OpenSSL" and I put the cpe for the filter in a field of this product (`cpe:2.3:a:openssl:openssl:-:*:*:*:*:*:*:*`). I active the option "Monitor Vulnerability for this product" and DefectDojo can automatically check availability of new vulnerability of this product with the NVD Data Feeds (https://nvd.nist.gov/vuln/data-feeds). When a vulnerability is discovered, DefectDojo create by itself a new Finding associated with the product "OpenSSL" with information like the CVSS score, resume and links to the vulnerability.

And after this Finding is create, it can be assigned automatically for one operator in charge of the security of this product.

**Comment by valentijnscholten** [comment]
realted to / blocked by #1602

**Comment by NRGLine4Sec** [comment]
@valentijnscholten Yes It Seems to be related to #1602. But, correct me if i am wrong, the PR don't tell about automatically add Finding in DefectDojo by itself when a vulnerability is discovered in the NVD Data Feeds ?

**Comment by valentijnscholten** [comment]
No, but I think we would need that PR to be able to have all the data synced into Defect Dojo. Or are you thinking more lightweight by downloading the CVE feeds from NVD on a daily basis?

**Comment by NRGLine4Sec** [comment]
I don't know how to do it exactly, but I want to be able to manage vulnerability automatically by a synchronisation of new discovered vulnerability for one product (like OpenSSl, or whatever) in DefectDojo. Actually, we could import scan report into DD and it works well but It could be great to use DD without importing report, with the sync of NVD Feeds and automatic adding in DD for new vulns. I think we could use the @jvz's PR, but I'm not developper so I don't really know :)

**Comment by NRGLine4Sec** [comment]
unstale

**Comment by valentijnscholten** [comment]
Not sure if this would be helpful / needed. You can get lots of false positives for CVEs that are already fixed because the openssl instance was already updated/patched. Also monitoring NVD/CVE is not the most reliable way, it's better to subscribe to bulletins from the vendor / authors. Defect Dojo is designed to import reports with findings so this request is a bit outside it's core tasks and focus.
