### ISSUE TITLE
Issues that have a JIRA link update, even if "push to jira" not ticked

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#2438]
**Bug description**
When updating the status of a finding that already has a JIRA link to it, it will go update the JIRA ticket status, even though the "push to JIRA" checkbox is not checked, and even though the product is not configured to "push all to JIRA".

FYI @Apipia  

**Steps to reproduce**

**Expected behavior**
I have control over what gets pushed to JIRA and don't want surprises.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
`5bca73ba: Merge remote-tracking branch 'refs/remotes/origin/dev' into dev [2020-05-27 07:48:25 +0000]`

**Comment by dayal18** [comment]
Here is my config:

I have enabled JIRA push in Product level..
On findings, it is enabled by default.. I created finding but didn't select 'Verified' (as this trigerred the JIRA). I added all the findings and then use bulk option - changed the status to active + verified and selected push to jira.. it worked fine with creating JIRA tickets... but the JIRA Change time always remains 0.

Secondly,
I created a new finding in the same product with Active + Verified.. this created 2 duplicate JIRA tickets.

Also, I'm no longer able to use the Webhook -- this used to work in 1.5.4. In 1.6 when I update the comments in JIRA they are not populating in DD. The vice-versa however works form DD (notes) --> JIRA. (I checked my celeryd and celerybeat services are running).

Testing other use cases.

**Comment by dayal18** [comment]
And other thing.. the alerts keep on increase like anything..

![image](https://user-images.githubusercontent.com/43857391/83472337-a02d1400-a44c-11ea-9f51-1b15695d8c83.png)

**Comment by dayal18** [comment]
The other thing is the Alerts keep on increase like anything..
![image](https://user-images.githubusercontent.com/43857391/83472407-cb176800-a44c-11ea-8f98-6aca726a72c3.png)

**Comment by dayal18** [comment]
Its hardly 1 minute.. and as about 100 alerts.. everything is JIRA..

![image](https://user-images.githubusercontent.com/43857391/83472542-1fbae300-a44d-11ea-9d25-4b98f8ca305f.png)

**Comment by dayal18** [comment]
Only deleting all the findings helped me to keep the alerts quite..
not sure what's wrong.. :(

![image](https://user-images.githubusercontent.com/43857391/83473221-a7edb800-a44e-11ea-9a33-c91bbec7336f.png)

**Comment by dayal18** [comment]
I guess the alerts will increase if you enable "push Notes" in the product profile.. as soon as I enable it.. the count started increasing..

**Comment by madchap** [comment]
fyi @Apipia

**Comment by dayal18** [comment]
I'm unable to reproduce this now, I guess this was part of your working PR.. I modified something earlier and messed up, I have to checkout master again and do the configs again.. I don't see this issue.. 

Webhooks is still an issue
and that JIRA Bulk which you are already working on.

**Comment by madchap** [comment]
Webhook to be part of something else.
