### ISSUE TITLE
OKTA Username and Email ID, both populating the same value

### ISSUE THREAD

**Issue by dayal18** [DefectDojo/django-DefectDojo#2452]
**Bug description**
After you integrate with OKTA and mapping the username, email fields value in the dojo/okta.py.
The profile in DD takes the username and email value as the same. 

**Steps to reproduce**
1. Go to 'settings.py and okta.py - confgiure for OKTA'
2. Click on 'Login using OKTA button'
3. Scroll down to 'After login using Okta, go to profile and check'
4. See the username and the email fields values are the same.

**Expected behavior**
Both the values should be different, I guess the mapping isn't working for username. Or the user name is getting replaced with the value of email.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [x] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Commit Message: [1.6 Master]

**Sample scan files** (optional)
Okta response:

https://xxxxx.okta.com:443 "GET /oauth2/default/v1/userinfo HTTP/1.1" 200 None
{'token_type': 'Bearer', 'expires_in': 3600, 'access_token': 'xxxxx', 'scope': 'profile openid', 'id_token': 'xxxxx', 'sub': '00ewrtgERThwdLdXe1t7', 'name': '**EFGH**', 'locale': 'US', 'nickname': 'xxxx', 'preferred_username': '**xxxx@abcd.com**', 'given_name': 'xxxx', 'family_name': 'xxxx', 'zoneinfo': 'America/Los_Angeles', 'updated_at': xxx}

name =  ID
preferred_username = email
given_name = firstname
family_name = lastname

This mapping is performed below in the dojo/okta.py file.

**Screenshots** (optional)

**Okta.py mapping as per the okta response:**

![image](https://user-images.githubusercontent.com/43857391/83455927-53cdde00-a424-11ea-843b-7c07452b06d8.png)

**After we see the logged-in user account which got created:**

![image](https://user-images.githubusercontent.com/43857391/83455791-1a956e00-a424-11ea-9a94-edb1ccab3854.png)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

**Comment by Rezkmike** [comment]
Im having problem integrating OKTA with DD. After done login with okta, it stucks there forever
