### ISSUE TITLE
JIRA WebHook and  other test use cases including bulk + product level push all (Master 1.6 - 654801f9)

### ISSUE THREAD

**Issue by dayal18** [DefectDojo/django-DefectDojo#2458]
**Bug description**
Tested few uses cases with JIRA 'Push all findings + Notes + Individual push of findings'
Here are my results.

**use case 1: (Worked)
In this use case, I have disabled push to JIRA at the Product level, as well as disabled Notes**

**Product level - JIRA disabled, Notes disabled**

Create new finding in a new engagement --
1) In new finding - status = Active + verified and select 'push to JIRA' - Works
2) In a finding - status = Active, then edit the finding - status = Active + Verified and select 'push to JIRA' - Works

**use case 2: (Half worked, error handling should be enabled)
In this use case, I have enabled push to JIRA at the Product level, and disabled Notes**

**Product level - JIRA enabled, Notes disabled**

Create new finding in a new engagement --
1) In new finding - status = Active + verified and auto-select 'push to JIRA' - Works
2) In a finding - status = Active then save (though auto-select JIRA is enabled it will save), then edit the finding - status = Active + Verified and auto-select 'push to JIRA' - Doesn't work, the JIRA Age and JIRA change appear - but with no JIRA ticket info or actual JIRA ticket creation. (I repeat this step of editing again, no luck) -- see step 4 when I used 'bulk edit'
3) In a finding - status = Under Review (anything other than Active or Active + verified), then I cannot save finding, as JIRA requires Active + Verified to be enabled by default.
4) I tried bulk edit option and select only 1 or all the findings and 'Push to JIRA' -- This step worked and fixed the issue of Step 2.

**use case 3: (Half worked, error handling should be enabled)
In this use case I have enabled push to JIRA at the Product level, and also enabled Notes (because I need bi-directional JIRA conversation)**

Results the same as to use case 2...

**use case 4: (Worked, but some cosmetic changes as the info about JIRA age and JIRA change doesn't populate)
In this use case, I have disabled JIRA and enabled NOTES at product level..**

**Product level - JIRA disabled, Notes enabled**

Create a new finding in a new engagement ---
1) In new finding - status = Active + verified and select 'push to JIRA' - Works
2) In a finding - status = Active, then edit the finding - status = Active + Verified and select 'push to JIRA' - Works
3) Create all findings status = Active + Verified, then finally use the Bulk Edit options and select 'Push to JIRA' - Works but no JIRA Age or JIRA Change info update on DD.

Have to test WebHooks as well..

**Comment by dayal18** [comment]
The webHook isn't working, is there something I need to check on DD or should I check with my JIRA team?
This works on 1.5.4 but not on 654801f9, I'll check with my JIRA team as well meanwhile.

**Comment by dayal18** [comment]
Celeryd and Celerybeat services are running..

**Comment by madchap** [comment]
> The webHook isn't working, is there something I need to check on DD or should I check with my JIRA team?
> This works on 1.5.4 but not on [654801f](https://github.com/DefectDojo/django-DefectDojo/commit/654801f9d864544e5a25a16d7d5567c614a0e2fd), I'll check with my JIRA team as well meanwhile.

You mean the webhook that allows jira to basically update the finding in DefectDojo, correct?

**Comment by dayal18** [comment]
Yes, that right.. it allows JIRA to push changes to DD.
This worked perfectly fine when developer closes or update the ticket in JIRA.. the same thing will reflect in DD.

**Comment by dayal18** [comment]
@madchap - will the WebHook be fixed as well via PR 2441.. is this issue in DefectDojo? or Is this issue with my JIRA team?

**Comment by madchap** [comment]
I don't know. I have not touched that part of the code yet (not am I using it yet), and I have not seen anything obvious in PRs I've looked at that modify that behavior. @Apipia maybe you know?

I would still check on your side if coincidentally, something didn't change in your infrastructure unrelated to DefectDojo.

**Comment by dayal18** [comment]
Sure.. I'll check internally with JIRA team, I have set up a meeting tomorrow to talk with them. Thank you

**Comment by madchap** [comment]
Check out https://github.com/DefectDojo/django-DefectDojo/pull/2462/commits/f844036295a070151dd1157fbe42dd8dff0df1c0 ... it could be that the recent github integration stepped onto the jira webhook toes. Wild guess and untested. If you have the chance to test it out, let me know.

**Comment by madchap** [comment]
> In a finding - status = Active then save (though auto-select JIRA is enabled it will save), then edit the finding - status = Active + Verified and auto-select 'push to JIRA' - Doesn't work, the JIRA Age and JIRA change appear - but with no JIRA ticket info or actual JIRA ticket creation. (I repeat this step of editing again, no luck) -- see step 4 when I used 'bulk edit'

Use-case 2 point 2 should be fixed I think via the linked PR.

Also logging has been fixed, so you would actually see things now..

**Comment by dayal18** [comment]
> Check out [45da66b](https://github.com/DefectDojo/django-DefectDojo/commit/45da66b62c59b13f431fea94d78a797c3b997715) ... it could be that the recent github integration stepped onto the jira webhook toes. Wild guess and untested. If you have the chance to test it out, let me know.

Unfortunately it didn't work.

**Comment by dayal18** [comment]
@madchap @valentijnscholten The JIRA webhook worked.. in 1.6 I think the webhook URL has a "/" (slash at the end) in setting.py. 

I had meeting with JIRA team today.. and told them to add "/" which worked.. However the alerts when the webhook changes the JIRA ticket (adding notes / changing status) didn't trigerred an alert... the alert would be very helpful in this case though.

**Comment by dayal18** [comment]
> Check out [45da66b](https://github.com/DefectDojo/django-DefectDojo/commit/45da66b62c59b13f431fea94d78a797c3b997715) ... it could be that the recent github integration stepped onto the jira webhook toes. Wild guess and untested. If you have the chance to test it out, let me know.

@madchap - Really thanks for this, I tried to remove this fix as well and give it a try.. it works without this fix as well..

**Comment by madchap** [comment]
Thanks for the follow-up @dayal18. So issue solved on your side, besides a possible improvement for alerts?

**Comment by dayal18** [comment]
> Thanks for the follow-up @dayal18. So issue solved on your side, besides a possible improvement for alerts?

Yup.. the issues are fixed.. Thank you so much.. I don't know if you noticed, but I did a retest of all the JIRA test cases mentioned in this.. everything works.. just small fix when using - 'bulk edit' for JIRA push.. the JIRA Age and JIRA Change (which shows the time, that doesn't get added)

**Comment by madchap** [comment]
Thanks for your diligence in testing over and over. The JIRA integration is lacking proper automated testing unfortunately, so until we get there, we're bound to see unwanted things slip by...

Please continue to report bugs or other oddities if you come across them!

I will close this issue as https://github.com/DefectDojo/django-DefectDojo/pull/2462 was merged for 1.6.5.

Cheers.
