### ISSUE TITLE
Hiding "Bug" Icon for the Products without JIRA config

### ISSUE THREAD

**Issue by dayal18** [DefectDojo/django-DefectDojo#2460]
**Is your feature request related to a problem? Please describe**
Hiding the "Bug" / JIRA icon, when the product is not configured for JIRA would help to have a quick view on what applications are enabled with JIRA and what is not. Currently, you can only get this information when you hover over your mouse on that icon.

**Describe the solution you'd like**
If the Bug icon is hidden it would help to quickly analyze or sort the products without JIRA configurations.

![image](https://user-images.githubusercontent.com/43857391/83567720-a3c1a900-a4e7-11ea-924d-7004dd6256e8.png)

**Comment by madchap** [comment]
I don't see the bug icon when a product has no JIRA configuration. Can you please detail? Thanks.

Could you check if what happens in the following scenario:
- Configure JIRA for a product and save --> the icon is there
- Remove the JIRA configuration --> the icon is there
- Create a new product, but never touch its JIRA configuration --> confirm no icon is present.

I think the DB may have an empty record, which then gets shown.

**Comment by dayal18** [comment]
Yes, its Bug...

Use case 1: Create a new Product --> No JIRA --> Save... there is NO ICON
Use case 2: Create a new product --> No JIRA --> Save --> Edit again --> no changes --> Save --> See icon

**Comment by madchap** [comment]
Yes, got it. Fixed in a local PR of mine, will push later.

**Comment by dayal18** [comment]
Thank you..

**Comment by dayal18** [comment]
@madchap Thanks that fix works :)
