### ISSUE TITLE
Expose open metrics (Prometheus) endpoint

### ISSUE THREAD

**Issue by omerlh** [DefectDojo/django-DefectDojo#2464]
**Is your feature request related to a problem? Please describe**
Defect dojo has a lot of interesting metrics, but no easy way to export them and integrate into existing dev tools like Grafana.

**Describe the solution you'd like**
As a sec engineer, I would like to expose all the metrics in defect dojo in open metrics/prometheus format so I could collect them with Prometheus and create various dashboards in Grafana.

**Describe alternatives you've considered**
Write an exporter using the API.

**Comment by madchap** [comment]
I could not find any docs but you have a `DD_DJANGO_METRICS_ENABLED` that will expose some metrics that I believe can be consumed. These are typically Django metrics. @alles-klar is there documentation I am missing?

@omerlh otherwise, what other metrics were you thinking about?

**Comment by omerlh** [comment]
Ideally? All the metrics that are stored by defect dojo - so I could easily create similar dashboards on Grafana, for example

**Comment by alles-klar** [comment]
For django and nginx metrics we have this option @madchap described. But it sounds for me that @omerlh wants to expose the "security" metrics, for example the number of vulnerabilities?

Generally this would be possible with the current solution but Prometheus and Grafana are not build for sensitive data. It is really hard to create a secure setup.

**Comment by omerlh** [comment]
I really not sure I agree with that, but anyway - this is up to the user to decide :)

**Comment by valentijnscholten** [comment]
I would be perfectly fine and interested to get statistics about the number of findings into a dashboard like grafana. However I'm not sure if that is something should go through an application monitoring system / setup like prometheus. Would be easier to just run some queries on the db and send those to grafana or a timeseries db for grafana.

**Comment by omerlh** [comment]
Yep, but this will put coupling on the internal design of DefectDojo and make upgrades very hard...

**Comment by valentijnscholten** [comment]
We could add some stuff to the API get statistics, I think there already is some. Either way if we add/remove/rename fields or statistics it will be breaking changes as well.

**Comment by iamhalje** [comment]
I also has a task, if anyone else is interested, please you can you it

https://github.com/iamhalje/defectdojo-exporter
