### ISSUE TITLE
User creation and management API

### ISSUE THREAD

**Issue by cpandya2909** [DefectDojo/django-DefectDojo#2466]
Currently there no API to create a new user or to edit it.

**Comment by JoseRoman** [comment]
Duplicate of #1873

**Comment by valentijnscholten** [comment]
closing as duplicate, but we understand it might be helpful. not sure if django provides something out of the box.

**Comment by cpandya2909** [comment]
So this means there will be no API support for user creation and management?

**Comment by cpandya2909** [comment]
@valentijnscholten , can you suggest me some temp solution to create users as my production setup is pending due to not able to onboard users.
