### ISSUE TITLE
Duplicate JIRA issues created when an ad-hoc finding is created.

### ISSUE THREAD

**Issue by kareem-DA** [DefectDojo/django-DefectDojo#2485]
**Bug description**
DDJ creates duplicate issue in JIRA when an ad-hoc finding is created.

**Steps to reproduce**
1. Setup DDJ to report issues to JIRA
2. Create a new finding significant enough to create a ticket in JIRA
4. Multiple tickets will get created in JIRA.  

**Expected behavior**
Only one ticket gets created

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: ubuntu 18.04
 - DefectDojo Commit Message: [use `git show -s --format="%h: %s [%ci]"`]

Sample log output has been added 

https://gist.github.com/kareem-DA/808799245be125df3948cfc7b4ecf4e0

I modified the code right before the add_issue_task.delay command to output a traceback. 

The add_issue_task call gets called 2 from product/views.py. Once from line 938 and again from line 964

**Comment by valentijnscholten** [comment]
Which branch/commit is this on? There are some fixes in `release/1.6.1` and some PRs pending to go in there as well. There was talk about duplicates and it might have been resolved in one of those PRs.

**Comment by kareem-DA** [comment]
This was on 1.6.0.   I haven't looked at the 1.6.1 release yet.

**Comment by valentijnscholten** [comment]
I just checked and I think this one is not yet fixed by 1.6.1 nor any PRs. @madchap @Apipia

**Comment by Maffooch** [comment]
Associated PR has been merged
