### ISSUE TITLE
pwgen: command not found error

### ISSUE THREAD

**Issue by Pl0414141** [DefectDojo/django-DefectDojo#2500]
**Bug description**
Using legacy install with mySQL option fails to install.

**Steps to reproduce**
Try to install through setup.sh and choose mySQL option.

**Expected behavior**
Install success

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [ X ] setup.bash / legacy-setup.bash

**Environment information**
Ubuntu 20 TLS
DefectDojo 1.6.2

**Console logs** (optional)

Setting password...
entrypoint_scripts/common/dojo-shared-resources.sh: line 544: pwgen: command not found
ERROR 1045 (28000): Access denied for user 'hola'@'localhost' (using password: NO)
mysqladmin: [ERROR] mysqladmin: Empty value for 'port' specified.
Error! Failed to create database . Check your credentials.

Setting password...
entrypoint_scripts/common/dojo-shared-resources.sh: line 544: pwgen: command not found
ERROR 1045 (28000): Access denied for user 'hola'@'localhost' (using password: NO)
mysqladmin: [ERROR] mysqladmin: Empty value for 'port' specified.
Error! Failed to create database . Check your credentials.

**Comment by valentijnscholten** [comment]
What database url / post did you use? Can you provide logs of all input / output during setup.sh?

**Comment by notbryan** [comment]
Looks like it was only installed using Docker installations. 

Just submitted a PR which should fix this using the legacy-setup on all supported platforms.

Please see #2500
