### ISSUE TITLE
JIRA webhook not working for comments

### ISSUE THREAD

**Issue by kareem-DA** [DefectDojo/django-DefectDojo#2501]
**Bug description**
When I post a comment into JIRA that should get posted back to DDJ as a note to a find, I get an error in the logs.

uwsgi_1         |     resolution = parsed[‘issue’][‘fields’][‘resolution’]
uwsgi_1         | KeyError: ‘resolution’

and the find doesn't get updated.

**Steps to reproduce**
1. New install of DDJ integrated with JIRA and the JIRA webhook
2. Create a finding in DDJ that will result in an issue getting created in JIRA.
3. Add a note to the JIRA issue that should be posted back to DDJ

**Expected behavior**
Adding a comment in JIRA should result in a note getting created for that finding in DDJ

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X ] Docker
- [ ] setup.bash / legacy-setup.bash\\

**Environment information**
DDJ 1.6.0
Atlassian JIRA Cloud 

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Additional context** (optional)
When a comment gets posted to JIRA, JIRA posts a webhook to DDJ.  The content of the JSON message from JIRA contains the comment as well as issue details.  See example (https://gist.github.com/kareem-DA/cf578564cf05fae917f18bcf7b6b3ef2). 

Looking at the code that handles the JIRA webhooks (jira_link/view.py) determine if the content of the web hook is an update to the finding or a new comment by the existence of an "issue" key in the body of the message (line 37: if 'issue' in list(parsed.keys())  The webhook messages sent by the cloud contain the field for both types of messages, so the comments fail with an error.  

https://developer.atlassian.com/server/jira/platform/webhooks/

From the JIRA webhook documentation this check should be done by comparing the key value for the "webhookEvent" key.  If payload is for a comment the value should be "comment_created" and for a update to the issue the value should be jira:issue_updated

**Comment by madchap** [comment]
This should be fixed with the PR from @kareem-DA . Thanks!
