### ISSUE TITLE
Nexpose scan file severity level mismatch when uploaded to DefectDojo

### ISSUE THREAD

**Issue by jajahhmt** [DefectDojo/django-DefectDojo#2511]
I have upload scan file (Nexpose) using an example file below: (Actually I used my Nexpose scan file and found the same problem, so I tried using a sample in the project too)

https://raw.githubusercontent.com/DefectDojo/sample-scan-files/master/nexpose/nexpose_v_unknown.xml

and found that a severity level was wrong match when uploaded to DefectDojo

Here's one of the examples what I found

1. vulnerability named "_FTP access with ftp account_" has severity level 1 in raw file
![image](https://user-images.githubusercontent.com/10954429/84100246-a9fadc80-aa35-11ea-94e6-f66293289f18.png)

2. Severity level when uploaded to Defectdojo was labeled as "Critical"
![image](https://user-images.githubusercontent.com/10954429/84100475-28577e80-aa36-11ea-9984-15e5c67f7306.png)

note: I just wonder why we have to minus the severity with 1 before divided by 2. (There're 10 levels of severity in Nexpose scan file. From my understanding, we divide 2 to adjust it to 5 levels (Info, low, medium,high, critical). But I don't understand why we minus with 1. (Correct me if I'm wrong :) )
https://github.com/DefectDojo/django-DefectDojo/blob/5c561d70286d09bc6a84448e71cc8ebf7547d9e2/dojo/tools/nexpose/parser.py#L164

**Comment by valentijnscholten** [comment]
If you can find out what the mapping from nexpose severity to defect dojo is / should be we can implement that. Maybe we could just use the pciSeverity field as that seems 1-5 based?

**Comment by jajahhmt** [comment]
In my opinion, pciSeverity field is focusing on PCI-DSS standard which is a specific vulnerability score based on the Payment Card Industry Data Security Standard (PCI DSS) Version 2.0, while severity field using CVSSv2 which is standard.

Here's what I found.. https://nvd.nist.gov/vuln-metrics/cvss
![image](https://user-images.githubusercontent.com/10954429/84220397-e47b7c80-aafc-11ea-9699-f5629273b82a.png)

Nexpose severity is a roundup of the cvssScore field. (ref: https://nexpose.help.rapid7.com/docs/working-with-risk-strategies-to-analyze-threats)

Thus, I think if we can use this criterion to labeled a 1-5 based on severity, it would be great.
