### ISSUE TITLE
field `impact` from finding should be mandatory?

### ISSUE THREAD

**Issue by edersonbrilhante** [DefectDojo/django-DefectDojo#2513]
**Description**
The field `impact` from finding is mandatory, but some tools are not filling it, like as `anchore engine`. Should we rethink whether impact should be mandatory or the tools should be changed to fill impact with some value?

**Comment by madchap** [comment]
Right, it's been bothering me too. No strong opinion, I think we could make it optional.

**Comment by edersonbrilhante** [comment]
I agree, but maybe there is some reason why impact is mandatory that I don't know. But I think we should fix in plugins or in the finding. Change to optional in finding is easier :p
