### ISSUE TITLE
Error when creating a new finding - JIRA

### ISSUE THREAD

**Issue by dayal18** [DefectDojo/django-DefectDojo#2521]
**Bug description**
When creating a new finding without ANY status checked (no active, no verified, no xx, no xx), the error would pop-up showing JIRA should need Active + Verified.

**Steps to reproduce**
New Product (JIRA config and **NO Push all issues**) --> new engagement --> new finding (NO status check and NO push to Jira) --> try to save --> Error.

**Expected behavior**
The finding should get save irrespective of whatever the status value is or even if there is no status value.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [x] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Commit Message: 1.6 + PR for JIRA fixes

**Screenshots** (optional)
![image](https://user-images.githubusercontent.com/43857391/84315210-f544e600-ab2e-11ea-938c-34ccc669e001.png)

**Comment by Apipia** [comment]
I have a fix for this in a PR I'll be submitting later. 
If anyone is curious:
```
if form['active'].value() is False or form['verified'].value() is False \
                and 'jiraform-push_to_jira' in request.POST:
```
Was changed to:
```
if (form['active'].value() is False or form['verified'].value() is False) \
                and 'jiraform-push_to_jira' in request.POST:
```
(Notice the parentheses)

**Comment by madchap** [comment]
@dayal18 are you able to confirm that this issue is fixed with the merged PR above? Thanks.

**Comment by dayal18** [comment]
@madchap Will test it today and update you..

**Comment by dayal18** [comment]
> I have a fix for this in a PR I'll be submitting later.
> If anyone is curious:
> 
> ```
> if form['active'].value() is False or form['verified'].value() is False \
>                 and 'jiraform-push_to_jira' in request.POST:
> ```
> 
> Was changed to:
> 
> ```
> if (form['active'].value() is False or form['verified'].value() is False) \
>                 and 'jiraform-push_to_jira' in request.POST:
> ```
> 
> (Notice the parentheses)

first I thought there is no change at all ;P

**Comment by dayal18** [comment]
@madchap @Apipia it works as expected.. thank you
