### ISSUE TITLE
Import Scan API returning 401 

### ISSUE THREAD

**Issue by bikeboardsurf1** [DefectDojo/django-DefectDojo#2529]
I am currently running Defectdojo using docker-compose on Ubuntu 18.04, I am using an up to date version of the code Defectdojo code obtained from here. Using the api (both via v1 and v2 of the api) via curl commands I am able to authenticate and retrieve products, engagements etc. However when I try to import a scan I'm constantly getting a 401 Unauthorized response. I can upload reports into the UI however clearly this is manual so not suitable.

The below is an example:

`curl -i -F "file=@zaproxy-wavsep_v1.4.1.xml" -H "Authorization: ApiKey <name>:<token>" -F "scan_type=ZAP Scan" -F "verified=true" -F scan_date=${mydate} -F "engagement=/api/v1/engagements/2/" http://127.0.0.1:8080/api/v1/importscan/`

The output is:
HTTP/1.1 100 Continue

HTTP/1.1 401 Unauthorized
Server: nginx/1.17.9
Date: Wed 10 Jun 2020 11:12:05 GMT
Content-Type: text/html; charset=utf-8
Content-Length=0
X-Frame-Options: SAMEORIGIN
Vary: Cookie
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block

I have tried the following:
api v1 and v2
the python api
Changing the content-type in the header to be multipart/form-data
Updating the header to be more permissive in terms of CORS 

Despite the above I get the same result. I'm not sure if there is some additional nginx security setting that is blocking this from happening but I have looked inside the nginx.conf files but I dont think there are any particular surprises in there, I'm not sure if there XSS-Protection is causing a problem, anyway grateful for some thoughts.

**Comment by nour1509** [comment]
> I am currently running Defectdojo using docker-compose on Ubuntu 18.04, I am using an up to date version of the code Defectdojo code obtained from here. Using the api (both via v1 and v2 of the api) via curl commands I am able to authenticate and retrieve products, engagements etc. However when I try to import a scan I'm constantly getting a 401 Unauthorized response. I can upload reports into the UI however clearly this is manual so not suitable.
> 
> The below is an example:
> 
> `curl -i -F "file=@zaproxy-wavsep_v1.4.1.xml" -H "Authorization: ApiKey <name>:<token>" -F "scan_type=ZAP Scan" -F "verified=true" -F scan_date=${mydate} -F "engagement=/api/v1/engagements/2/" http://127.0.0.1:8080/api/v1/importscan/`
> 
> The output is: HTTP/1.1 100 Continue
> 
> HTTP/1.1 401 Unauthorized Server: nginx/1.17.9 Date: Wed 10 Jun 2020 11:12:05 GMT Content-Type: text/html; charset=utf-8 Content-Length=0 X-Frame-Options: SAMEORIGIN Vary: Cookie X-Content-Type-Options: nosniff X-XSS-Protection: 1; mode=block
> 
> I have tried the following: api v1 and v2 the python api Changing the content-type in the header to be multipart/form-data Updating the header to be more permissive in terms of CORS
> 
> Despite the above I get the same result. I'm not sure if there is some additional nginx security setting that is blocking this from happening but I have looked inside the nginx.conf files but I dont think there are any particular surprises in there, I'm not sure if there XSS-Protection is causing a problem, anyway grateful for some thoughts.

I

**Comment by nour1509** [comment]
I HAVE THE SAME PROBLEM
