### ISSUE TITLE
Developing for DefectDojo in Visual Studio 2019

### ISSUE THREAD

**Issue by dbrewerton** [DefectDojo/django-DefectDojo#2530]
Greetings and well met. I am a developer attempting to build out defect dojo and was wondering how I might make it so I can work with it in Visual Studio? I like the way VS allows me to create virtual environments with a right click. How can I get the app to run inside VS with a Virtual Environment?

**Comment by devGregA** [comment]
@dbrewerton This is not currently supported. Unfortunately I don't see the team getting bandwith to support this. If this is something you are interested in working on, we would gladly accept a pull request to the documentation.
