### ISSUE TITLE
Re-Import Scan Result Feature for SonarQube API Scan fails due to missing file

### ISSUE THREAD

**Issue by zorianix** [DefectDojo/django-DefectDojo#2531]
Re-Import Scan feature request for a file upload for Sonarqube API Scan types this cause the request to fail with a 500 error as there is no file uploaded . A validation is required to check whether the type of Scan Import was Sonarqube API Scan , in that case it should allow for re-generation of api call to sonarqube server

1. Go to Import Scan Results
2. Select Scan Type to: Sonarqube Api Import and add complete Import Process
3. Select the Test again and choose Re-Import Scan Result, now if the user blindly clicks on the import this result in a Server 500 error as no file is uploaded in the Re-Import process

Expected behavior
An API request should be re-generated for the re-import request

**Deployment method** *(select with an `X`)*
- [X] Kubernetes
- [X] Docker
- [X] setup.bash / legacy-setup.bash

**Comment by Maffooch** [comment]
Fixed in #2606
