### ISSUE TITLE
Mark multiple issue resolve at once

### ISSUE THREAD

**Issue by himani-dangwal** [DefectDojo/django-DefectDojo#2535]
**I have integrated multiple tools report in defect dojo. Issue is after I resolve the issue I want to close them all at once rather than closing them one by one**

Ex: On daily basis I have 2 to 3 builds and thus having 2 to 4 engagements having plenty of issues in them.

**Describe the solution you'd like**
Here in the bulk edit if I get the option to mark all the selected item as closed.
![image](https://user-images.githubusercontent.com/53521513/84471122-53460a80-aca2-11ea-9978-d3b128fbb092.png)

**Comment by valentijnscholten** [comment]
You can use bulk edit to uncheck 'Active'.
