### ISSUE TITLE
Group based access

### ISSUE THREAD

**Issue by himani-dangwal** [DefectDojo/django-DefectDojo#2536]
I wanted to have different groups which have different rights.
1) Can view only the projects assigned to them
2) Can only view the products and engagements (delete and add should not be possible)
3) Can view the findings and do the updates like close, mark as active but cannot delete

 I did created a group using the admin interface but when the user tries to close the issue he is asked to enter the credentials and nothing happens

I have given all the possible access to the group
![image](https://user-images.githubusercontent.com/53521513/84483836-88108c80-acb7-11ea-92ba-f91c7bd73364.png)
![image](https://user-images.githubusercontent.com/53521513/84483903-9f4f7a00-acb7-11ea-92d5-b8f0ae0ed04d.png)
![image](https://user-images.githubusercontent.com/53521513/84483941-ad9d9600-acb7-11ea-9a3e-d2650bf1aedf.png)

**Comment by valentijnscholten** [comment]
currently most of these don't work, #1048

**Comment by himani-dangwal** [comment]
> currently most of these don't work, #1048

Do I have any other alternative through which I can handle this..user who is just "Active" cannot mark the issue as close. While I don't want him to see any further detail.

**Comment by valentijnscholten** [comment]
#2615 will allow active and authorized users to close findings.
