### ISSUE TITLE
Help on setting up this on ECS

### ISSUE THREAD

**Issue by bharathgajendran** [DefectDojo/django-DefectDojo#2541]
Hey Everyone,
I was trying to set this up on ECS, seems like we have an image appsecpipeline/django-defectdojo to run everything in a single container, but it doesn't looks like an updated one do we have any new image which has everything (except MySQL) in a single image which I can use to run defect dojo in ECS.

If you could point me to some documentation on running this in ECS, it will be really helpful.

Thanks..

**Comment by valentijnscholten** [comment]
There are some others working with ECS discussing it in the slack chanel.
