### ISSUE TITLE
How to manage correctly 2 tests of the same type in the same product?

### ISSUE THREAD

**Issue by ycrumeyrolle** [DefectDojo/django-DefectDojo#2588]
I have 1 product. 
In this product, I have 1 engagement of type CI/CD. 
In this engagement, I have 2 tests of type Sonatype (or whatever), one for the JavaScript client application located in a specific repository, another for the C# server application located in another repository. 

When I import a scan result via the API, with the parameter `close_old_findings` set to `true`, it will close ALL the findings from the other test, which is not what I need. 
If I enable the parameter `Deduplication on engagement` on my current engagement, I lose the capability to deduplicate accross other engagements, which is a requirement in order to follow the finding accross the environment. I have 1 engagement per environment, I cannot have findings duplicated X-times.

It would be great to be able to close old finding only for the current test, and not for all the tests of the same type... Even if I need to set a new flag like `close_old_findings_same_test` !

**Comment by ycrumeyrolle** [comment]
OK we have found a workaround .
When importing a scan test for the first time, set the parameter `close_old_findings`  to `false`, or it will close the other tests of the same type.
When re-importing a scan test, you can set the parameter `close_old_findings` to `true`, it will close only the current test, as expected.

**Comment by Maffooch** [comment]
Thanks for following up with your workaround!
