### ISSUE TITLE
Unable to view all engagement

### ISSUE THREAD

**Issue by omerlh** [DefectDojo/django-DefectDojo#2600]
**Bug description**
When trying to view all engagement, an error page is show, this is the exception from the logs:

defectdojo-django-6bf8cc4f7f-bkt7l uwsgi Internal Server Error: /engagements_all
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi Traceback (most recent call last):
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     response = get_response(request)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     response = self.process_exception_by_middleware(e, request)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     response = wrapped_callback(request, *callback_args, **callback_kwargs)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     return view_func(request, *args, **kwargs)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "./dojo/engagement/views.py", line 129, in engagements_all
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     'eng_words': sorted(set(eng_words)),
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/shortcuts.py", line 36, in render
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     content = loader.render_to_string(template_name, context, request, using=using)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/template/loader.py", line 62, in render_to_string
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     return template.render(context, request)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/template/backends/django.py", line 61, in render
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     return self.template.render(context)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 171, in render
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     return self._render(context)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 163, in _render
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     return self.nodelist.render(context)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 937, in render
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     bit = node.render_annotated(context)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     return self.render(context)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/template/loader_tags.py", line 150, in render
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     return compiled_parent._render(context)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 163, in _render
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     return self.nodelist.render(context)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 937, in render
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     bit = node.render_annotated(context)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     return self.render(context)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/template/loader_tags.py", line 150, in render
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     return compiled_parent._render(context)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 163, in _render
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     return self.nodelist.render(context)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 937, in render
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     bit = node.render_annotated(context)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     return self.render(context)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/template/loader_tags.py", line 62, in render
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     result = block.nodelist.render(context)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 937, in render
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     bit = node.render_annotated(context)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     return self.render(context)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/template/defaulttags.py", line 309, in render
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     return nodelist.render(context)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 937, in render
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     bit = node.render_annotated(context)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     return self.render(context)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/template/defaulttags.py", line 209, in render
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     nodelist.append(node.render_annotated(context))
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     return self.render(context)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/template/defaulttags.py", line 209, in render
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     nodelist.append(node.render_annotated(context))
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     return self.render(context)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/template/defaulttags.py", line 443, in render
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/urls/base.py", line 90, in reverse
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi   File "/usr/local/lib/python3.5/site-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi     raise NoReverseMatch(msg)
defectdojo-django-6bf8cc4f7f-bkt7l uwsgi django.urls.exceptions.NoReverseMatch: Reverse for 'product_type_metrics' with arguments '('',)' not found. 1 pattern(s) tried: ['metrics/product/type/(?P<mtype>\\d+)$']

**Deployment method** *(select with an `X`)*
- [X] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Docker
 - DefectDojo Commit Message: 70e626c1102f645631c3b936f663ad5510b4b90b

**Comment by valentijnscholten** [comment]
This is because you have a product without a product type
