### ISSUE TITLE
Server error 500 when trying to import Spotbugs(v4.0.6) report

### ISSUE THREAD

**Issue by roman933** [DefectDojo/django-DefectDojo#2609]
**Bug description**
Server error 500
Unable to download Spotbugs (v4.0.6) report to the DD via dashboard or curl to the API

**Steps to reproduce**
1. Create Spotbugs textui XML report from Jar file (size 20mb-40mb)
2.Import it via DD's dashboard or API post

**Expected behavior**
Scan file is uploaded and scan results are accessible on the DD's dashboard

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 20.04]
 - DefectDojo Commit Message: 5c561d70: fix version numbers missed in 1.6.1 (#2498) [2020-06-07 09:51:01 +0200]

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)
![Annotation 2020-06-24 204246](https://user-images.githubusercontent.com/66245796/85617270-abe4b280-b667-11ea-9cbc-683ea87c2279.png)

**Comment by roman933** [comment]
I guess this will help someone.
Resloved
The Spotbugs scan is needed to be run with the following parameter:
 -xml:withMessages

Example:
/home/user/spotbugs-4.0.6/bin/spotbugs -textui -progress -xml:withMessages -output name_of_the_scan.xml /home/user/jar_folder/*.jar

**Comment by valentijnscholten** [comment]
Could you maybe create a PR with some info/instructions for Spotbugs here https://github.com/DefectDojo/Documentation/blob/master/docs/integrations.rst ?
