### ISSUE TITLE
jira: prefetching no longer (or just not) working

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#2623]
With the recent JIRA push all changes in 1.6.0 and 1.6.5 the way to retrieve the JIRA configuration for a finding / engagement / product has changed to use `first()`:

`test.engagement.product.jira_pkey_set.first()`

when viewing a test, the prefetching no longer works (or maybe it never worked) resulting in 3 extra queries per finding in the test:

![image](https://user-images.githubusercontent.com/4426050/86118270-ca680500-bad0-11ea-8c2d-a14aae8fa5c9.png)
![image](https://user-images.githubusercontent.com/4426050/86118286-d358d680-bad0-11ea-8e91-bdb4502388dd.png)

**Comment by Maffooch** [comment]
All attached PRs are merged, so closing
