### ISSUE TITLE
Trufflehog json import error

### ISSUE THREAD

**Issue by eshanaswar** [DefectDojo/django-DefectDojo#2651]
**Bug description**
Whenever I try to import truffle hog json file it throws server 500 error.
Logs are provided below

**Steps to reproduce**
1. Go to 'Engagement'
2. Click on 'Findings -> Import Scan Result -> Upload json file -> Select Scan type as truffle hog scan'
3. See error

**Expected behavior**
Json import should be successful

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04] debian 10
 - DefectDojo Commit Message: [use `git show -s --format="%h: %s [%ci]"`] f93e24ef: removing dev branch and add security section [2020-06-16 23:28:05 +0200]

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
uwsgi_1         | the JSON object must be str, not 'bytes'                                                                                                                
uwsgi_1         | Traceback (most recent call last):                                                                                                                      
uwsgi_1         |   File "./dojo/tools/trufflehog/parser.py", line 73, in parse_json                                                                                      
uwsgi_1         |     json_data = json.loads(str(json_output, 'utf-8'))                                                                                                   
uwsgi_1         |   File "/usr/local/lib/python3.5/json/__init__.py", line 319, in loads                                                                                  
uwsgi_1         |     return _default_decoder.decode(s)                                                                                                                   
uwsgi_1         |   File "/usr/local/lib/python3.5/json/decoder.py", line 339, in decode                                                                                  
uwsgi_1         |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                                                                   
uwsgi_1         |   File "/usr/local/lib/python3.5/json/decoder.py", line 357, in raw_decode                                                                              
uwsgi_1         |     raise JSONDecodeError("Expecting value", s, err.value) from None                                                                                    
uwsgi_1         | json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)                                                                                 
uwsgi_1         |                                                                                                                                                         
uwsgi_1         | During handling of the above exception, another exception occurred:                                                                                     
uwsgi_1         |                                                                                                                                                         
uwsgi_1         | Traceback (most recent call last):                                                                                                                      
uwsgi_1         |   File "./dojo/engagement/views.py", line 583, in import_scan_results                                                                                   
uwsgi_1         |     parser = import_parser_factory(file, t, active, verified)                                                                                           
uwsgi_1         |   File "./dojo/tools/factory.py", line 156, in import_parser_factory                                                                                    
uwsgi_1         |     parser = TruffleHogJSONParser(file, test)                                                                                                           
uwsgi_1         |   File "./dojo/tools/trufflehog/parser.py", line 14, in __init__                                                                                        
uwsgi_1         |     json_data = self.parse_json(line)                                                                                                                   
uwsgi_1         |   File "./dojo/tools/trufflehog/parser.py", line 75, in parse_json                                                                                      
uwsgi_1         |     json_data = json.loads(json_output)                                                                                                                 
uwsgi_1         |   File "/usr/local/lib/python3.5/json/__init__.py", line 312, in loads                                                                                  
uwsgi_1         |     s.__class__.__name__))                                                                                                                              
uwsgi_1         | TypeError: the JSON object must be str, not 'bytes'                                                                                                     
uwsgi_1         | Error in parser: the JSON object must be str, not 'bytes'                                                                                               
uwsgi_1         | Internal Server Error: /product/1/import_scan_results                                                                                                   
uwsgi_1         | Traceback (most recent call last):                                                                                                                      
uwsgi_1         |   File "./dojo/tools/trufflehog/parser.py", line 73, in parse_json                                                                                      
uwsgi_1         |     json_data = json.loads(str(json_output, 'utf-8'))                                                                                                   
uwsgi_1         |   File "/usr/local/lib/python3.5/json/__init__.py", line 319, in loads                                                                                 
uwsgi_1         |     return _default_decoder.decode(s)
uwsgi_1         |   File "/usr/local/lib/python3.5/json/decoder.py", line 339, in decode                                                                                 
uwsgi_1         |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
uwsgi_1         |   File "/usr/local/lib/python3.5/json/decoder.py", line 357, in raw_decode                                                                             
uwsgi_1         |     raise JSONDecodeError("Expecting value", s, err.value) from None                                                                                   
uwsgi_1         | json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)                                                                                
uwsgi_1         |
uwsgi_1         | During handling of the above exception, another exception occurred:
uwsgi_1         |
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "./dojo/engagement/views.py", line 583, in import_scan_results
uwsgi_1         |     parser = import_parser_factory(file, t, active, verified)
uwsgi_1         |   File "./dojo/tools/factory.py", line 156, in import_parser_factory
uwsgi_1         |     parser = TruffleHogJSONParser(file, test)
uwsgi_1         |   File "./dojo/tools/trufflehog/parser.py", line 14, in __init__
uwsgi_1         |     json_data = self.parse_json(line)
uwsgi_1         |   File "./dojo/tools/trufflehog/parser.py", line 75, in parse_json
uwsgi_1         |     json_data = json.loads(json_output)
uwsgi_1         |   File "/usr/local/lib/python3.5/json/__init__.py", line 312, in loads
uwsgi_1         |     s.__class__.__name__))
uwsgi_1         | TypeError: the JSON object must be str, not 'bytes'
uwsgi_1         |
uwsgi_1         | During handling of the above exception, another exception occurred:
uwsgi_1         |
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
uwsgi_1         |     return view_func(request, *args, **kwargs)
uwsgi_1         |   File "./dojo/product/views.py", line 475, in import_scan_results_prod
uwsgi_1         |     return import_scan_results(request, pid=pid)
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
uwsgi_1         |     return view_func(request, *args, **kwargs)
uwsgi_1         |   File "./dojo/engagement/views.py", line 592, in import_scan_results
uwsgi_1         |     return HttpResponseRedirect(reverse('import_scan_results', args=(eid,)))
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/urls/base.py", line 90, in reverse
uwsgi_1         |     return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
uwsgi_1         |     raise NoReverseMatch(msg)
uwsgi_1         | django.urls.exceptions.NoReverseMatch: Reverse for 'import_scan_results' with arguments '(None,)' not found. 1 pattern(s) tried: ['engagement/(?P<eid>\\
d+)/import_scan_results$']

**Additional context** (optional)

**Comment by devGregA** [comment]
Hi @eshanaswar, without a sample scan, we aren't able to investigate.
