### ISSUE TITLE
Swagger vs Application

### ISSUE THREAD

**Issue by secf00tprint** [DefectDojo/django-DefectDojo#2658]
**Bug description**

Possible mismatch between database and REST API v2 concerning products.

**Steps to reproduce**

Under "Edit Products" I can enter
- Prod manager
- Tech contact 
- managers and other things. DefectDojo stores it correctly and I can reopen the data.

However, this data does
 not appear when I use the REST APIv2:

```
curl -X GET --header 'Accept: application/json' --header 'X-CSRFToken: abc' --header 'Authorization: Token xyz' 'https://defect-dojo.onmyprem.tld/api/v2/products/8/?id=8'
```

Response is:

```
  "created": null,
  "prod_numeric_grade": null,
  "business_criticality": null,
  "platform": null,
  "lifecycle": null,
  "origin": null,
  "user_records": null,
  "revenue": null,
  "external_audience": false,
  "internet_accessible": false,
  "product_manager": null,
  "technical_contact": null,
  "team_manager": null,
```
![Bildschirmfoto von 2020-07-08 14-37-04](https://user-images.githubusercontent.com/1818452/86920226-c15ae180-c129-11ea-8599-c03ac77102d6.png)

Could this be because of an too old version. I couldn't find a fix in the [releases page](https://github.com/DefectDojo/django-DefectDojo/releases)

**Environment information**
 - DefectDojo Version v. 1.5.4

**Comment by valentijnscholten** [comment]
could you retry with 1.6.5 or `dev`?
