### ISSUE TITLE
unable to import reports from wapiti 

### ISSUE THREAD

**Issue by himani-dangwal** [DefectDojo/django-DefectDojo#2671]
**Bug description**
Wapiti scan report when imported does not show any issue in defect dojo while when i check it in the html format it has issues in it.

**Steps to reproduce**
1. Perform a  wapiti scan on a url - wapiti version 3.0.2
2. Have the output in xml format
3. import the result
4. it will show 0 findings

**Expected behavior**
it should show the issues
**Deployment method** *(select with an `X`)*
- [X ] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Centos 7]

**Comment by devGregA** [comment]
What format is the wapiti output? Do you have a sample scan you can provide?

**Comment by himani-dangwal** [comment]
> What format is the wapiti output? Do you have a sample scan you can provide?

Hi , PFA the sample report.. 
[vulxml.zip](https://github.com/DefectDojo/django-DefectDojo/files/4951381/vulxml.zip)

**Comment by himani-dangwal** [comment]
> > What format is the wapiti output? Do you have a sample scan you can provide?
> 
> Hi @devGregA , PFA the sample report..
> [vulxml.zip](https://github.com/DefectDojo/django-DefectDojo/files/4951381/vulxml.zip)

Hi @devGregA  any update on this

**Comment by valentijnscholten** [comment]
Can you provide the (debug) log output after importing? Are you import via APIv2, APIv2 or UI?

**Comment by himani-dangwal** [comment]
> Can you provide the (debug) log output after importing? Are you import via APIv2, APIv2 or UI?

I have tried with UI as well as with APIv2 but with both no vulnerability is imported. It does not give any issues. As in the above xml you can see some vulnerabilities. when imported they should be reflected

**Comment by himani-dangwal** [comment]
any updates on this

**Comment by valentijnscholten** [comment]
Up to you to provide the logs
