### ISSUE TITLE
The DB password is printed out in the logs 

### ISSUE THREAD

**Issue by ccojocar** [DefectDojo/django-DefectDojo#2677]
**Bug description**
The DB password is printed out in the logs by several components such as initialize:

```
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/dbshell.py", line 22, in handle
    connection.client.runshell()
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/client.py", line 48, in runshell
    subprocess.check_call(args)
  File "/usr/local/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mysql', '--user=defectdojo', '--password=edited', '--host=127.0.0.1', '--port=3306', 'defectdojo']' returned non-zero exit status 1
```

**Steps to reproduce**
1.  Checks the logs during the startup when the component tries to connect to the DB
2. You can find the password in the exception generated by calling the mysql CLI (See above)

**Expected behavior**

The password should be marked or removed.

**Deployment method** *(select with an `X`)*
- [x] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Commit Message: [use `git show -s --format="%h: %s [%ci]"`]

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

**Comment by valentijnscholten** [comment]
Can you post the full stacktrace to see where this originates from?

**Comment by valentijnscholten** [comment]
If this is from migrations chances are it needs to be reported upstream to django migrations, django or mysqlclient
