### ISSUE TITLE
Duplicated findings in reimport

### ISSUE THREAD

**Issue by edersonbrilhante** [DefectDojo/django-DefectDojo#2687]
**Bug description**
I was using reimport function and I saw some active finding been duplicated in each reimport.

**Steps to reproduce**
Flow
1 - Create a product, engagement, and test.
2 - Use reimport with 1 finding
3 - The first import will be fine. We will have 1 active finding.
4 - Use reimport with the previous file

**Expected behavior**
The active finding is deactivated and DD creates a new active finding. When I reimport again, the issue appears again. So I will the "same" finding duplicated(1 activated, rest them deactivated)
<img width="1176" alt="Screenshot 2020-07-15 at 18 54 48" src="https://user-images.githubusercontent.com/1094995/87686882-5773b500-c785-11ea-94d9-93c5c0c59587.png">

**Debugging**
I saw that the issue happen just in postgres. Perhaps it is a case-sensitive filter. 
The finding title is changed inside models.py:1924
```  
# Title Casing
from titlecase import titlecase
self.title = titlecase(self.title)
````

Woking fine in using mysql:5.7.29
<img width="1440" alt="Screenshot 2020-07-16 at 16 40 35" src="https://user-images.githubusercontent.com/1094995/87691656-226a6100-c78b-11ea-8cc1-c651c6b62efe.png">
<img width="1201" alt="Screenshot 2020-07-16 at 16 36 30" src="https://user-images.githubusercontent.com/1094995/87691657-2302f780-c78b-11ea-8ef4-42d18091a4a1.png">

Reproducing using  postgres:9.6-alpine
<img width="1440" alt="Screenshot 2020-07-16 at 17 36 37" src="https://user-images.githubusercontent.com/1094995/87691650-20080700-c78b-11ea-90b2-4a03d1c3ba43.png">

**Propose**
Change files 
dojo/api_v2/serializers.py, 
dojo/api.py
dojo/test/views.py

Changes:
```
from titlecase import titlecase
item.title = titlecase(self.title)
findings = Finding.objects.filter(
  title=item.title,
  test=test,
  severity=sev,
  numerical_severity=Finding.get_numerical_severity(sev)).all()
```
or
```
findings = Finding.objects.filter(
  title__iexact=item.title,
  test=test,
  severity=sev,
  numerical_severity=Finding.get_numerical_severity(sev)).all()
```

**Comment by valentijnscholten** [comment]
fixed by pr
