### ISSUE TITLE
"engagement":["This field is required."],"scan_type":["This field is required."] while importing XML file

### ISSUE THREAD

**Issue by Nilesh0101** [DefectDojo/django-DefectDojo#2689]
**Bug description**
I'm trying to import "Qualys WebApp Scan" XML report file using **import-scan API** and getting errors related to missing fields.

**Steps to reproduce**
Below is my POST request code in Java:

`URL url = new URL("http://<ip-address>/api/v2/import-scan/");
httpClient = this.getHttpClient();
File file = new File(xmlFilepath);

JsonObject dataObj = new JsonObject();
dataObj.addProperty("engagement", "96");
dataObj.addProperty("scan_type", "Qualys Webapp Scan");
Gson gson = new Gson();
StringEntity jsonEntity = new StringEntity(gson.toJson(dataObj));

HttpPost postRequest = new HttpPost(url.toString());
postRequest.addHeader("Accept", "application/json");
postRequest.addHeader("Authorization", "Token <token>");
postRequest.addHeader("Content-Type", "multipart/form-data");
postRequest.setEntity(new FileEntity(file));
postRequest.setEntity(jsonEntity);

CloseableHttpResponse response = httpClient.execute(postRequest);`

Above code gives me below error:

`"engagement":["This field is required."],"scan_type":["This field is required."]`

**Expected behavior**

Below is my POST request code in Python, which works fine. Also import-scan API works fine from Swagger and CURL.

`url = "http://" + server + ':' + port + import_scan_result_api
    filepath = "<xml-file-name>.xml"
    files = {'file': open(filepath, 'rb')}
    data = {'engagement': '96', 'scan_type': 'Qualys Webapp Scan'}
    r = requests.post(url, files=files, headers={'Authorization': 'Token <token>'}, data=data)`

**Comment by valentijnscholten** [comment]
Looks like something wrong with content-type etc. I think the api expects www url form encoded request with key/values in the body. My fork of the defect dojo api is working for sure: https://github.com/valentijnscholten/defectdojo_api?organization=valentijnscholten&organization=valentijnscholten apiv2 is what I am using.
