### ISSUE TITLE
Abnormal Date Sorting in Metrics Dashboard for Individual Products

### ISSUE THREAD

**Issue by tohch4** [DefectDojo/django-DefectDojo#2692]
**Bug description**
Dates in time series metrics graphs behave weirdly for `/product/1234/metrics` for any given data uploaded with significant time ranges going back 1-3 months. This has been reproduced on 1.6.2 and potentially 1.6.4 (pending tests in our non-production environments).

**Steps to reproduce**
1. Upload data spanning several months.
2. Open metrics dashboard for an individual product.
3. Observe abnormal sorting of dates were indicates of every 1-2 weeks are interleaved in a non-linear order.

**Expected behavior**

Date sort from latest to oldest or oldest to latest, currently they do neither.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] ECS Fargate
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: N/A (ECS Fargate, so presumed Amazon Linux 2)
 - DefectDojo Commit Message: [fix version numbers missed in 1.6.1 (#2498)](https://github.com/DefectDojo/django-DefectDojo/commit/5c561d70286d09bc6a84448e71cc8ebf7547d9e2)

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

![image](https://user-images.githubusercontent.com/39844334/87845127-9b081500-c892-11ea-99cc-78b0becc4832.png)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

Potentially related to DefectDojo/django-DefectDojo#2661

**Comment by valentijnscholten** [comment]
which database, encoding, collation, timezones, etc are you using?

**Comment by tohch4** [comment]
Sorry, I was away from laptop. I will check and get back to you this afternoon or tomorrow morning with this, @valentijnscholten!
