### ISSUE TITLE
notifications get sent to users that are no longer authorized for a product

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#2700]
**Bug description**
if a user once was an authorized user for a product and has configured notifications, the user will still receive those even after the user would have been removed as authorized user from the product. 

I haven't tested this, but as I wrote the code I think this can happen :-)

**Comment by kbonato** [comment]
I am having a similar bug, a user who is not in other products he receives notifications normally, but cannot access.

**Comment by valentijnscholten** [comment]
is he a staff user? staff users have another set of notifications in global settings.

**Comment by kbonato** [comment]
No, active user normal

**Comment by dayal18** [comment]
I have fixed this in #2877
