### ISSUE TITLE
Authentication with SAML2

### ISSUE THREAD

**Issue by UilianM** [DefectDojo/django-DefectDojo#2706]
Hello.

Using deploy in CentOS can I use authentication via SAML2?
How do I enable this?

**Comment by valentijnscholten** [comment]
what happens if you follow the docs? https://defectdojo.readthedocs.io/en/latest/ SAML2 was added today in 1.7.0

**Comment by UilianM** [comment]
I deployed my application using this procedure.

https://github.com/DefectDojo/Community-Contribs/tree/master/CentOS-7-deploy

How do I configure my containers and keep the settings when I restart the containers?
