### ISSUE TITLE
Improve database connection (environment) variables / documentation

### ISSUE THREAD

**Issue by zakrush** [DefectDojo/django-DefectDojo#2709]
**Bug description**
Hi, all.
I try to deploy the defectDojo into production and  I changed all password. 
Into docker logs I get:
`initializer_1   |   File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
initializer_1   |     raise CalledProcessError(retcode, cmd)
initializer_1   | subprocess.CalledProcessError: Command '['mysql', '--user=defectdojo', '--password=defectdojo', '--host=mysql', '--port=3306', 'defectdojo']' returned non-zero exit status 1.
`

**Steps to reproduce**
1. Go to docker-compose.yml
2. Change `MYSQL_PASSWORD: ${DD_DATABASE_PASSWORD:-defectdojo}` variable. Setup any password, for exmpl:
MYSQL_PASSWORD: ${DD_DATABASE_PASSWORD:-12345}
Also I tried to change ENV in settings.dist.py and Dockerfile.django
3. docker-compose up --build. 
4. See error described into bug description. 

**Expected behavior**

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes

- [x]  Docker

- [ ] setup.bash / legacy-setup.bash

**Environment information**
  - DefectDojo Commit Message: 
```
git show origin/master -s --format="[%ci] %h: %s [%d]"
[2020-06-16 23:28:05 +0200] f93e24ef: removing dev branch and add security section [ (origin/master, origin/HEAD)]
```

**Screenshots** (optional)
![image](https://user-images.githubusercontent.com/33844164/88156317-f1b67b80-cc11-11ea-903f-d68e15d40636.png)

**Comment by valentijnscholten** [comment]
Is this with a clean database or did you change the password after some earlier build/run which created the database? Can you run `docker system prune --volumes` and try again? (This will remove ALL docker volumes, containers, etc)

**Comment by zakrush** [comment]
@valentijnscholten Yes. I did `docker system prune --volumes` and have the same error.

Also. I went to mysql container and login to mysql as defectdojo user and password 1234, that was setup into docker-compose.yaml

**Comment by zakrush** [comment]
I found trouble.
It's `DD_DATABASE_URL: ${DD_DATABASE_URL:-mysql://defectdojo:defectdojo@mysql:3306/defectdojo}` ENV variable.
I setuped it as `DD_DATABASE_URL: ${DD_DATABASE_URL:-mysql://defectdojo:12345@mysql:3306/defectdojo}` (for my example) and it working fine.

I think you'll should setup this variables in dependences from 
MYSQL_USER, MYSQL_PASSWORD and MYSQL_DATABASE env variables.
