### ISSUE TITLE
Problems repeated notifications in slack

### ISSUE THREAD

**Issue by undelete** [DefectDojo/django-DefectDojo#2713]
**Bug description**
At the moment when an engagement is created or a finding is deleted, notifications are repeated. I have observed this bug since I updated to version 1.7.0, I do not know if it also affects email notifications

**Steps to reproduce**
1. Create engagement or finding delete

**Expected behavior**
A one notification.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Commit Message: [use `git show -s --format="[%ci] %h: %s [%d]"`]

**Screenshots** (optional)

<img width="797" alt="Captura de Pantalla 2020-07-22 a la(s) 22 16 15" src="https://user-images.githubusercontent.com/25057634/88247313-505c1380-cc6b-11ea-81f2-46cea7ec3d14.png">

<img width="787" alt="Captura de Pantalla 2020-07-22 a la(s) 22 18 34" src="https://user-images.githubusercontent.com/25057634/88247333-5fdb5c80-cc6b-11ea-8225-3e295ce2a09d.png">

**Comment by dayal18** [comment]
I have seen this issue only when I have notification enabled for both Global and Personal.
Later I have put everything in Global leaving personal as blank and then I get only 1 notification. I enabled email notification.
