### ISSUE TITLE
Problems in config email notifications

### ISSUE THREAD

**Issue by undelete** [DefectDojo/django-DefectDojo#2714]
**Bug description**
Overwriting the setting.py file adding DD_EMAIL_URL, when I do tests it only indicates the log that the task was sent but it was not completed.

**Expected behavior**
Send Email.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Commit Message: [use `git show -s --format="[%ci] %h: %s [%d]"`]

**Screenshots** (optional)

<img width="971" alt="Captura de Pantalla 2020-07-22 a la(s) 22 35 21" src="https://user-images.githubusercontent.com/25057634/88251045-93bc7f00-cc77-11ea-95f9-5e5fd88510cc.png">

**Comment by valentijnscholten** [comment]
Can you run with debug logging

**Comment by undelete** [comment]
> Can you run with debug logging

Yes, let me check. Thanks

**Comment by dayal18** [comment]
I have tested this and it works for me. 1.7.1 (docker)

**Comment by undelete** [comment]
> I have tested this and it works for me. 1.7.1 (docker)

What configuration did you apply in the docker-compose? Could you show me the syntax and where did you leave the command in the uswgi? Thanks

**Comment by dayal18** [comment]
> > I have tested this and it works for me. 1.7.1 (docker)
> 
> What configuration did you apply in the docker-compose? Could you show me the syntax and where did you leave the command in the uswgi? Thanks

I just added in settings.dist.py the remote smtp server details. (make sure your smtp server is working, try with a script first)
Then on the DDJ setting - I have enabled email Notification with from address and to address.

**Comment by sayanTlregtech** [comment]
Hey how do you edited the remote smtp server options? I am unable to set up that please help me.
