### ISSUE TITLE
Add "Recently visited" menu

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#2716]
**Is your feature request related to a problem? Please describe**
Navigating to a specific test after having navigated away is usually cumbersome.

**Describe the solution you'd like**
It would be nice to have a menu on the left (or somewhere easy to click) with the 5 most recent tests visited, or something along these lines.

**Comment by valentijnscholten** [comment]
I was thinking about this recently. Mostly for findings. But then I thought maybe we can tweak page titles so the browser history makes sense?

**Comment by madchap** [comment]
Still something I'd eventually want to see.
