### ISSUE TITLE
Allow authorized users to add findings, allow users to be staff of only certain products

### ISSUE THREAD

**Issue by undelete** [DefectDojo/django-DefectDojo#2718]
**Is your feature request related to a problem? Please describe**
A clear and concise description of what the problem is.
In the new permissions for users to be able to edit and delete findings, is it possible to allow them to enter findings, for example if we give access to a user and that the user is technical and needs to enter findings, is it possible to be able to indicate that within django in the permissions?
Because staff have access to all products when we want to give specific access to a product.

**Describe the solution you'd like**
An effective solution could be:
1) Allow users to (add) edit and delete already own it in version 1.7.0. And if you need to be able to change them, example: I want you to just edit but not delete or just add. I don't know if django allows to have unbundled permissions or they should do it in a permission table with permission id. This applies to a user who is pentest but with minimal permissions.
2) Allow the staff what product they can see and likewise change the permissions. Because they can see staff users that you only require to see x product and edit those products.

**Additional context**
I hope with this to give you a good feedback and you can take into consideration the points that you indicate.
Thank you very much

**Comment by dayal18** [comment]
This exist in the version 1.7.1 you have to change the setting in the settings.py file.

**Comment by valentijnscholten** [comment]
Not sure if I understand all the requirements:
- Request to allow users with change permission to add findings: Currently not possible, but could be added
- Request to allow users to be staff users only for certain products: This is more or less implemented in #2765

**Comment by madchap** [comment]
I think this can be closed, per https://github.com/DefectDojo/django-DefectDojo/pull/2765?

@undelete, can you confirm?

**Comment by valentijnscholten** [comment]
new permission system in the works, which will support this.

**Comment by valentijnscholten** [comment]
The foundations were laid with #4503 and #4530, @Hijerboa is currently working on the UI.

**Comment by valentijnscholten** [comment]
fixed in dev / 2.0.0
