### ISSUE TITLE
semgrep json output integration

### ISSUE THREAD

**Issue by cristiano-corrado** [DefectDojo/django-DefectDojo#2720]
**Scanner Name**
semgrep, repository below.

https://github.com/returntocorp/semgrep

Semgrep is a command-line tool for offline static analysis. Use pre-built or custom rules to enforce code and security standards in your codebase. You can try it now with our interactive live editor.

Semgrep combines the convenient and iterative style of grep with the powerful features of an Abstract Syntax Tree (AST) matcher and limited dataflow. Easily find function calls, class or method definitions, and more without having to understand ASTs or wrestle with regexes.

**Sample File**
Please attach a sample file and the format of the file (xml, json, csv).

[semgrep-example.json.zip](https://github.com/DefectDojo/django-DefectDojo/files/4970305/semgrep-example.json.zip)

**Comment by ievans** [comment]
Hi @cristiano-corrado, thanks for making this ticket. I'm a semgrep maintainer and defect dojo integration is on our todo-list eventually, but you all may beat us to it! I just wanted to chime in and note that semgrep has a `--sarif` output format option which may be easier to integrate than the `--json` output.

**Comment by SPoint42** [comment]
Hi @ievans . I need to parse semgrep for some project and could work on it. But I do not do double dev if this is on your todo. Did you have any ETA for it ?

**Comment by ievans** [comment]
Hi @SPoint42: I would love to support you doing the work, I am still a few months out from being able to do it myself. Feel free to join our community slack (https://r2c.dev/slack) or I am also on the defectdojo slack if I can be helpful!

**Comment by SPoint42** [comment]
@ievans @valentijnscholten : So OK, I need it, will try to do some plugins import.

**Comment by xee5ch** [comment]
@SPoint42, have you begun work on this?

**Comment by SPoint42** [comment]
Not yet. I planned to begin next week. But if you have time . Let me know. 
I think this is an background task for me next week

**Comment by xee5ch** [comment]
@ievans, it seems that SARIF output schema is not as complex as the JSON output, but I am not 100% sure because the standard is long but [the code seems to be pretty straightforward](https://github.com/returntocorp/semgrep/blob/0aebdd3871b3adb98a1fcf62f50c626ccf12575c/semgrep/semgrep/output.py#L148-L171). Am I far off? I guess I will start off with JSON first, then move on to SARIF later, unless someone beats me to it!

`semgrep` seems wonderful by the way. I had heard of it, but not experimented with it yet. You all are going to convert me into a believer fast!

**Comment by SPoint42** [comment]
Integrate in PR #2781 
REady to review

**Comment by valentijnscholten** [comment]
merged into dev, will be in 1.10.0

**Comment by damiencarol** [comment]
@memelet there is 2 ways to import reports from semgrep:
1. JSON output (--json) with "semgrep" parser
2. SARIF output (--sarif) with SARIF parser
