### ISSUE TITLE
integration tests fails because chrome vs chromedriver version mismatch

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#2721]
Currently the latest chromedriver v85, but the chrome for ubuntu that we download is still at v84.

```
Preparing to unpack google-chrome-stable_current_amd64.deb ...
Unpacking google-chrome-stable (84.0.4147.89-1) ...
Setting up google-chrome-stable (84.0.4147.89-1) ...
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/google-chrome (google-chrome) in auto mode
--2020-07-23 20:48:08--  https://chromedriver.storage.googleapis.com/85.0.4183.38/chromedriver_linux64.zip
Resolving chromedriver.storage.googleapis.com (chromedriver.storage.googleapis.com)... 172.217.214.128, 2607:f8b0:4001:c05::80
Connecting to chromedriver.storage.googleapis.com (chromedriver.storage.googleapis.com)|172.217.214.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 92523702 (88M) [application/zip]
Saving to: ‘/tmp/chromedriver.zip’
```

Resulting in 

```
This version of ChromeDriver only supports Chrome version 85
```

The solution is:

- Wait for the versions to be aligned again, or:
- Implement the version matching procedure as described by chromium at: https://chromedriver.chromium.org/downloads/version-selection

> - First, find out which version of Chrome you are using. Let's say you have Chrome 72.0.3626.81.
> - Take the Chrome version number, remove the last part, and append the result to URL "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_". For example, with Chrome version 72.0.3626.81, you'd get a URL "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_72.0.3626".
> - Use the URL created in the last step to retrieve a small file containing the version of ChromeDriver to use. For example, the above URL will get your a file containing "72.0.3626.69". (The actual number may change in the future, of course.)
> - Use the version number retrieved from the previous step to construct the URL to download ChromeDriver. With version 72.0.3626.69, the URL would be "https://chromedriver.storage.googleapis.com/index.html?path=72.0.3626.69/".
> - After the initial download, it is recommended that you occasionally go through the above process again to see if there are any bug fix releases.

**Comment by Maffooch** [comment]
Fixed itself after time
