### ISSUE TITLE
Cannot upload bundle audit test through UI or APIV2

### ISSUE THREAD

**Issue by carlanderson86** [DefectDojo/django-DefectDojo#2733]
**Bug description**

When you attempt to upload a bundle-audit generated through `bundler-audit check` or `bundler-audit check --update` a 500 response code is given.

This used to work but appears to have broken a few months ago.

**Steps to reproduce**
1. Go to an engagement `engagement/<id>`
2. Click on `Import Scan Results` on the Tests section dropdown
3. Select `Bunder Audit Scan`
4. Upload output of `bundler-audit check` (see attached)

**Expected behavior**
A test should be created with the findings from the bundler audit

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Debian Stretch
 - Image: `defectdojo/defectdojo-django:1.5.4.1`

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.
[bundler_audit.txt](https://github.com/DefectDojo/django-DefectDojo/files/4988910/bundler_audit.txt)
[bundle_audit_no_update.txt](https://github.com/DefectDojo/django-DefectDojo/files/4988985/bundle_audit_no_update.txt)

**Screenshots** (optional)
![Screenshot 2020-07-28 at 15 32 21](https://user-images.githubusercontent.com/33194028/88679904-d94dd180-d0e7-11ea-978c-43bc9a92707a.png)

**Console logs** (optional)
```
Environment:


Request Method: POST
Request URL: https://defectdojo.sandbox.zappi.it/engagement/44/import_scan_results

Django Version: 2.2.9
Python Version: 3.5.9
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'polymorphic',
 'overextends',
 'django.contrib.admin',
 'django.contrib.humanize',
 'gunicorn',
 'tastypie',
 'auditlog',
 'defectDojo_engagement_survey',
 'dojo',
 'tastypie_swagger',
 'watson',
 'tagging',
 'custom_field',
 'imagekit',
 'multiselectfield',
 'rest_framework',
 'rest_framework.authtoken',
 'rest_framework_swagger',
 'dbbackup',
 'taggit_serializer',
 'django_celery_results',
 'social_django',
 'drf_yasg')
Installed Middleware:
['django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'dojo.middleware.LoginRequiredMiddleware',
 'dojo.middleware.TimezoneMiddleware',
 'social_django.middleware.SocialAuthExceptionMiddleware']



Traceback:

File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)

File "./dojo/engagement/views.py" in import_scan_results
  558.             parser = import_parser_factory(file, t, active, verified)

File "./dojo/tools/factory.py" in import_parser_factory
  183.         parser = BundlerAuditParser(file, test)

File "./dojo/tools/bundler_audit/parser.py" in __init__
  13.         warnings = lines.split('\n\n')

Exception Type: TypeError at /engagement/44/import_scan_results
Exception Value: a bytes-like object is required, not 'str'
```

**Additional context** (optional)
This also fails using an apiv2 call

**Comment by valentijnscholten** [comment]
Format seems to be similar to the one in sample files so that's not the issue it seems: https://github.com/DefectDojo/sample-scan-files/blob/master/bundler_audit/bundler-audit_v0.6.1.txt We need to make a unit test and take it from there.

**Comment by carlanderson86** [comment]
We upgraded our defect dojo deployment to the latest version and this issue was resolved.
