### ISSUE TITLE
Containers should not run with root group

### ISSUE THREAD

**Issue by zacblazic** [DefectDojo/django-DefectDojo#2742]
**Is your feature request related to a problem? Please describe**

Currently containers are run with the group `root` and are unable to run when the group is set to anything else  i.e. `nobody`.

From within a container:
```
$ id
uid=1001 gid=0(root) groups=0(root),1(daemon)
```

**Describe the solution you'd like**

I would like to be able to run the containers without them requiring the `root` group.

Edit: Clarified that this does not run the container as `root`.

**Comment by devGregA** [comment]
Confirmed running under a specific user that isn't root and isn't in root group.
