### ISSUE TITLE
Problems generating reports in AsciiDOC in version 1.7.0

### ISSUE THREAD

**Issue by undelete** [DefectDojo/django-DefectDojo#2744]
**Bug description**
When you try to generate an AsciiDOC type product report, it keeps loading, it never responds and then nginx falls.

**Expected behavior**
In version 1.6.0 this problem did not happen, they generated without problems.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Commit Message: [use `git show -s --format="[%ci] %h: %s [%d]"`]

**Screenshots** (optional)
<img width="1329" alt="Captura de Pantalla 2020-07-30 a la(s) 18 07 58" src="https://user-images.githubusercontent.com/25057634/88979526-e1487580-d28f-11ea-9f9b-b3cdcd219445.png">

**Comment by valentijnscholten** [comment]
what version are you running? can you provide debug logs?

**Comment by undelete** [comment]
> what version are you running? can you provide debug logs?

The version is 1.7.0 docker. Let me check in debug lugs

**Comment by undelete** [comment]
We upgrade version to V 1.7.1 and the same error in the debug console i see this
<img width="1417" alt="Captura de Pantalla 2020-08-03 a la(s) 19 00 13" src="https://user-images.githubusercontent.com/25057634/89245069-0877ad80-d5d6-11ea-982c-393834896eb2.png">

**Comment by valentijnscholten** [comment]
Although that trace looks like a possible bug, I don't think it's related to generating ascii docs. We need the logs from the uwsgi container or an easy way to reproduce it. Does it happen with an "empty" docker-compose install?

**Comment by undelete** [comment]
Yes, with an empty installation it happens.
 
In order to replicate the error they must do the following:

First, in the product go to "Product Report"
<img width="944" alt="product" src="https://user-images.githubusercontent.com/25057634/89374853-7c8b8180-d6ba-11ea-9946-a1714bcb3136.png">

Then generate the report in AsciiDOC
<img width="1324" alt="generate" src="https://user-images.githubusercontent.com/25057634/89374931-9af17d00-d6ba-11ea-874b-edc4b7ec8e6f.png">

That way they can observe the error in the logs
