### ISSUE TITLE
404 error generating reports for endpoints Version 1.7.0

### ISSUE THREAD

**Issue by undelete** [DefectDojo/django-DefectDojo#2745]
**Bug description**
Trying to generate a report for endpoint gives error 404 when it should be generated.

**Expected behavior**
You should generate the report without problems

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Commit Message: [use `git show -s --format="[%ci] %h: %s [%d]"`]

**Screenshots** (optional)
<img width="1337" alt="Captura de Pantalla 2020-07-30 a la(s) 12 14 33" src="https://user-images.githubusercontent.com/25057634/88979936-a266ef80-d290-11ea-8012-6aeb9c1a6403.png">

<img width="1337" alt="Captura de Pantalla 2020-07-30 a la(s) 12 14 39" src="https://user-images.githubusercontent.com/25057634/88979989-bca0cd80-d290-11ea-826f-0e521717dd9c.png">

**Comment by valentijnscholten** [comment]
Can you try with 1.7.1, there was a bug in 1.7.0 around endpoints.

**Comment by undelete** [comment]
> Can you try with 1.7.1, there was a bug in 1.7.0 around endpoints. 

Great, let me check. Thanks

**Comment by undelete** [comment]
The same error 404 in version 1.7.1.

**Comment by valentijnscholten** [comment]
@Maffooch any thoughts?

**Comment by Maffooch** [comment]
Looks like the referenced PR fixed this.
