### ISSUE TITLE
Error pushing findings to Jira Cloud

### ISSUE THREAD

**Issue by celagus** [DefectDojo/django-DefectDojo#2747]
**Bug description**

There is an "out of range" error when I trying to push findings from DDojo to Jira (cloud). Please see console log below.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [CentOS 8]
 - DefectDojo Commit Message: [[2020-07-27 13:20:04 -0500] d8fb1cd3: Update master version (#2731) [ (HEAD -> master, tag: 1.7.1, origin/master, origin/HEAD)]]

**Console logs**

celeryworker_1  | Traceback (most recent call last):
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task
celeryworker_1  |     R = retval = fun(*args, **kwargs)
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__
celeryworker_1  |     return self.run(*args, **kwargs)
celeryworker_1  |   File "/app/dojo/tasks.py", line 268, in add_issue_task
celeryworker_1  |     add_issue(find, push_to_jira)
**celeryworker_1  |   File "/app/dojo/utils.py", line 1398, in add_issue
celeryworker_1  |     if 'duedate' in meta['projects'][0]['issuetypes'][0]['fields']:
celeryworker_1  | IndexError: list index out of range**

**Comment by valentijnscholten** [comment]
Are you using a nextgen project? those are not supported yet as Atlassian changed a whole bunch of things on those projects.

**Comment by celagus** [comment]
Hi. I found a config error when I mapped severity from DDojo to Jira. Jira doesn't expect "Critical" severity lavel but "Highest". Anyway It doesn't fix the issue, but I've tryed same setup on Ubuntu Server and it works! I couldn't figured out why it doesn't work on CentOS. It doesn't matter now, I'll go ahead with Ubuntu by this time :)

**Comment by valentijnscholten** [comment]
Pretty sure it's related to the type of JIRA project chosen. The new style "next gen" projects are a bit different and missing some fields and apparently some metadata too.

**Comment by valentijnscholten** [comment]
sounds resolved, please reopen when needed.

**Comment by Ivanello** [comment]
I have the same issue while integrating with Classical (non-nextgen project)
`celeryworker_1_c93dde253bf4 | [2020-10-02 11:39:06,277: ERROR/MainProcess] Task add_issue_task[26927c8b-7b04-4c82-9641-d926fb00cbe8] raised unexpected: IndexError('list index out of range',)
celeryworker_1_c93dde253bf4 | Traceback (most recent call last):
celeryworker_1_c93dde253bf4 |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task
celeryworker_1_c93dde253bf4 |     R = retval = fun(*args, **kwargs)
celeryworker_1_c93dde253bf4 |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__
celeryworker_1_c93dde253bf4 |     return self.run(*args, **kwargs)
celeryworker_1_c93dde253bf4 |   File "/app/dojo/tasks.py", line 268, in add_issue_task
celeryworker_1_c93dde253bf4 |     add_issue(find, push_to_jira)
celeryworker_1_c93dde253bf4 |   File "/app/dojo/utils.py", line 1398, in add_issue
celeryworker_1_c93dde253bf4 |     if 'duedate' in meta['projects'][0]['issuetypes'][0]['fields']:
celeryworker_1_c93dde253bf4 | IndexError: list index out of range`

**Comment by valentijnscholten** [comment]
which version are you running, this isse was fixed in dev & 1.8.0
