### ISSUE TITLE
Incorrect parsing and displaying IPv6

### ISSUE THREAD

**Issue by Hawk1812** [DefectDojo/django-DefectDojo#2750]
**Bug description**
DefectDojo cannot appropriate process IPv6 addresses during importing openvas scans that includes IPv6 hosts. Incorrect parsing, writing to the db and displaying in web console.

**Steps to reproduce**
Import an openvas report with ipv6 hosts. Or add manually IPv6 host finding.

**Expected behavior**
Same behaviour as for IPv4 hosts.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker Compose
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: any

**Sample scan files** (optional)
Any report with IPv6.

**Additional context** (optional)
Seems the root cause is not only in the openvas parser. Also affected model and view.
[Attempt](https://github.com/Hawk1812/django-DefectDojo/commit/634fed2126c74f560a1c626188ec7f2fd3870ca3) to fix the described behaviour. Worked fine. Checked manually. 
Need your approval for making PR with these changes and further assistance for making this fix better.

**Comment by valentijnscholten** [comment]
PR is welcome
