### ISSUE TITLE
403: Forbidden - CSRF Verification failed

### ISSUE THREAD

**Issue by stefan6534** [DefectDojo/django-DefectDojo#2760]
**Bug description**

_Using Kali Linux:_
After successfully installing defectDojo's latest version and running it using docker-compose, I am unable to import scan result. Each upload attempt results in a 403 Forbidden page. The weird thing is that I was able to import scan results on last Thursday, using the same version. Any help?

**Steps to reproduce**
1. Go to 'Products'
2. Create a Product
3. Go to 'Findings' tab and select 'Import Scan Results'
4. Try importing any sort of scan - I am using Burp Scan
5. Click on Import and see this:

![image](https://user-images.githubusercontent.com/69247008/89412103-286eb480-d72f-11ea-94fe-1b4f9a519711.png)

**Expected behavior**
I should be able to successfully upload my xml Burp Scan file

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Kali 2020.3

**Network Logs**
![image](https://user-images.githubusercontent.com/69247008/89412321-87ccc480-d72f-11ea-85e9-534b43d61deb.png)

![image](https://user-images.githubusercontent.com/69247008/89412353-9a46fe00-d72f-11ea-8802-a12fd8635eda.png)

**CSRF Middleware Token**
![image](https://user-images.githubusercontent.com/69247008/89412428-be0a4400-d72f-11ea-8d20-37e6e2f29d4c.png)

I've checked and tried all google solutions, nothing works - any ideas?

**Comment by valentijnscholten** [comment]
May sound stupid, but did you try to logout and login again? clear cookies/cache/etc?

**Comment by stefan6534** [comment]
> May sound stupid, but did you try to logout and login again? clear cookies/cache/etc?

Yep, I've tried everything really, did not work

**Comment by valentijnscholten** [comment]
Have no idea, must be something local stripping the CSRF header, or some corruption of the settings.py file where CSRF exemptions are configured.

**Comment by devGregA** [comment]
I've seen this with SSO when SSO bypasses dojo's login method. I want to add a fix to the middleware, but it can be a hard issue to reproduce. Planning to add a middleware check that will reset CSRF in the future.

**Comment by JamesCullum** [comment]
I was able to reconstruct this issue. It is caused if you have cookies set from a UI session. You can find the details about the background described [here](https://stackoverflow.com/a/26639895/1424378) - basically if it sees a login cookie, it now runs the full CSRF checks and you need to set the CSRF header and a correct referrer.

In previous versions, this was not the case - there it only verified API tokens for the API.

**Comment by valentijnscholten** [comment]
@JamesCullum I use the API from the browser all the time while logged in to the UI. Are you sure this is a generic an reproducible issue?

**Comment by JamesCullum** [comment]
It was a different thing than the OP mentioned, but was definitely reconstructable enough. I would get those CSRF errors only when the script first logged in via UI. I can imagine that you are sending different headers than the script, which might bypass this.

**Comment by devGregA** [comment]
I know of one other spot where this occurs. When getting an SSO token
without first going to Dojo, CSRF will not be set properly. We could catch
all CSRF issues by reissuing in the middleware, when appropriate.

Greg Anderson
DefectDojo Project Leader
***@***.***

**Comment by ganesh2183** [comment]
Trying to upload MobSF scan results using json file.

Getting 403 Forbidden - CSRF verification failed. Request aborted.

Why? What to do now
![IMG_20210820_232115](https://user-images.githubusercontent.com/41476297/130278379-a45701cd-1dd8-443e-b3cb-32ab19455ad2.jpg)

**Comment by devGregA** [comment]
I would recommend turning on debug to gain additional information about the error.

**Comment by wattlehound** [comment]
The issue is still persistant, API calls are failing due to CSRF token requirment
