### ISSUE TITLE
Problems to get a report filtering the vulnerability

### ISSUE THREAD

**Issue by undelete** [DefectDojo/django-DefectDojo#2761]
**Bug description**
When it is necessary to export the report of a finding, it shows the blank report in html

**Steps to reproduce**
1. Go to Product Report and click on filtered options
<img width="1399" alt="Captura de Pantalla 2020-08-05 a la(s) 18 30 23" src="https://user-images.githubusercontent.com/25057634/89470684-5e6d6200-d74a-11ea-98d2-5d47ecb8395e.png">

2. Select report options
<img width="1386" alt="Captura de Pantalla 2020-08-05 a la(s) 18 30 36" src="https://user-images.githubusercontent.com/25057634/89470773-8ceb3d00-d74a-11ea-81ab-281f4870aca4.png">

3. Click on Generate Report and see error
<img width="1322" alt="Captura de Pantalla 2020-08-05 a la(s) 18 29 19" src="https://user-images.githubusercontent.com/25057634/89470820-aee4bf80-d74a-11ea-8d06-da9f28f564df.png">

**Expected behavior**
Show the report

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Commit Message: [use `git show -s --format="[%ci] %h: %s [%d]"`]
 - DefectDojo Version 1.7.1

**Comment by sc-tibco** [comment]
Hello, I am able to filter options such as "Name" and the product report shows up correctly. I have attached screenshots of filtering working. Perhaps you filtered incorrectly and so no findings showed up? 
![Screenshot from 2020-09-10 15-59-07](https://user-images.githubusercontent.com/67396122/92820939-6474e500-f37f-11ea-877d-b7bd5a95d672.png)
![Screenshot from 2020-09-10 15-59-50](https://user-images.githubusercontent.com/67396122/92820951-68086c00-f37f-11ea-825f-c169e95931ca.png)

**Comment by undelete** [comment]
> Hello, I am able to filter options such as "Name" and the product report shows up correctly. I have attached screenshots of filtering working. Perhaps you filtered incorrectly and so no findings showed up?
> ![Screenshot from 2020-09-10 15-59-07](https://user-images.githubusercontent.com/67396122/92820939-6474e500-f37f-11ea-877d-b7bd5a95d672.png)
> ![Screenshot from 2020-09-10 15-59-50](https://user-images.githubusercontent.com/67396122/92820951-68086c00-f37f-11ea-825f-c169e95931ca.png)

The information don't showed up! I filter by "Name"
