### ISSUE TITLE
Reports imported with nessus do not show the CVE

### ISSUE THREAD

**Issue by undelete** [DefectDojo/django-DefectDojo#2762]
**Bug description**
When importing nessus reports, either nessus or .csv type, the cve field is not imported and it always remains "none"

**Expected behavior**
I should import the CVE.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Commit Message: [use `git show -s --format="[%ci] %h: %s [%d]"`]
 - DefectDojo Version: 1.7.1

**Screenshots** (optional)
<img width="1357" alt="Captura de Pantalla 2020-08-05 a la(s) 18 54 36" src="https://user-images.githubusercontent.com/25057634/89472679-f705e100-d74e-11ea-9909-f26976bda4c1.png">

**Comment by valentijnscholten** [comment]
do you have a sample file to reproduce this?
