### ISSUE TITLE
Database export

### ISSUE THREAD

**Issue by LeonardoNve** [DefectDojo/django-DefectDojo#2763]
The problem I have is to export DATA from a DefectDojo to another DD, where one is in a 1.6 version and other is the recently publish 1.7.1. The idea is the possibility of export from one mysql database to the new schema.

A possible solution is a way to a modify a .sql from a mysqldump to the new format.

**Comment by valentijnscholten** [comment]
We don't have the resources to support this. Can you upgrade both to the same version? That would allow an easy data migration. You could also look into using the django dump/load feature, but I don't like that one.
