### ISSUE TITLE
Error while importing HTML report Burp Enterprise Scan

### ISSUE THREAD

**Issue by stevieg27** [DefectDojo/django-DefectDojo#2764]
While importing HTML report of Burp Enterprise scan to defect dojo version 1.7.1 latest version it throws below error.

uwsgi_1         | list index out of range
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "./dojo/engagement/views.py", line 586, in import_scan_results
uwsgi_1         |     parser = import_parser_factory(file, t, active, verified)
uwsgi_1         |   File "./dojo/tools/factory.py", line 100, in import_parser_factory
uwsgi_1         |     parser = BurpEnterpriseHtmlParser(file, test)
uwsgi_1         |   File "./dojo/tools/burp_enterprise/parser.py", line 30, in __init__
uwsgi_1         |     self.items = self.get_items(tree)
uwsgi_1         |   File "./dojo/tools/burp_enterprise/parser.py", line 68, in get_items
uwsgi_1         |     url = endpoint_text[index].text[16:]
uwsgi_1         | IndexError: list index out of range
uwsgi_1         | Error in parser: list index out of range

**Comment by Maffooch** [comment]
Hi @stevieg27 can you provide some sort of sample file that you encountered this issue with? Note that this parser only supports detailed reports, not the summarized versions.

**Comment by Maffooch** [comment]
Also please see if the error is still present with #2725

**Comment by Maffooch** [comment]
Going to assume this is fixed due to lack of response.
