### ISSUE TITLE
Support Importing Scans from vuls.io

### ISSUE THREAD

**Issue by ohsh6o** [DefectDojo/django-DefectDojo#2771]
**Is your feature request related to a problem? Please describe**
A clear and concise description of what the problem is.

I want to be able to ingest [vuls.io](https://vuls.io/) findings into DefectDojo.

**Describe the solution you'd like**
Ex: As a < role >, I want < some goal > so that < some reason >.

**Describe alternatives you've considered**
I can ingest data from alternative sources, but this tool support analysis of application dependencies, container dependencies, and operating systems for vulnerable packages which we are currently assessing in our environment.

**Additional context**
Add any other context, screenshots, sketch, code snippet, etc. about the feature request here.

**Comment by kembox** [comment]
Up, this should be very nice.
