### ISSUE TITLE
Deduplication does not work when importing scans

### ISSUE THREAD

**Issue by atruemper** [DefectDojo/django-DefectDojo#2772]
**Bug description**
We try to import different scans via api/v2, but even when importing manually deduplication does not seem to work.

**Steps to reproduce**
/system_settings: Deduplicate findings is enabled
in the file settings.py:
Hashcodeconfiguration 
- HASHCODE_FIELDS_PER_SCANNER defined as "'Dependency Track Finding Packaging Format (FPF) Export': ['cwe', 'severity']," for DependencyTrack
-  DEDUPLICATION_ALGORITHM_PER_PARSER is defined as DEDUPE_ALGO_HASH_CODE for DepTrackFinding:
    'Dependency Track Finding Packaging Format (FPF) Export': DEDUPE_ALGO_HASH_CODE,

Create new engagement and import given sample file twice.
The duplicate findings are not detected
![Test_DepTrackImport_Engagements](https://user-images.githubusercontent.com/18392452/90009140-d0d7c800-dc9d-11ea-9599-1102f680e028.jpg)
That log says that hashcodes are being calculate for cwe and severity, though:
[log_importscan.log](https://github.com/DefectDojo/django-DefectDojo/files/5062293/log_importscan.log)

Creating CI/CD-engagements and importing scans via Jenkins and api/v2 doesn't work either

**Expected behavior**
Findings in the second import scan are detected as being duplicate

**Deployment method** *(select with an `X`)*
- [X] Kubernetes (openshift)
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: CentOS
- Version: DefectDojo 1.6.5

**Sample scan files**
[deptrack.zip](https://github.com/DefectDojo/django-DefectDojo/files/5062256/deptrack.zip)

**Screenshots**
![Test_DepTrackImport_Engagements](https://user-images.githubusercontent.com/18392452/90009303-198f8100-dc9e-11ea-865e-5197c0da2424.jpg)

**Console logs**
[log_importscan.log](https://github.com/DefectDojo/django-DefectDojo/files/5062301/log_importscan.log)

**Comment by Maffooch** [comment]
HI @atruemper do you happen to have deduplication on engagements enabled by chance? This option is found on when creating/editing an engagement. If enabled, then deduplication will be restricted to the engagement itself, and not across other engagements. This scenario fits what you have described here.

**Comment by atruemper** [comment]
Hi @Maffooch thanks for the hint, but I don't have deduplication enabled on engagement level for the engagements.
I noticed that DefectDojo complains about Celery on the system_settings page. There are a pods defectdojo-celery-beat and -worker running on the openshift project however, but maybe we're missing some configuration (Routes etc.) because celery-beat has errors in the log like
"kombu.exceptions.OperationalError: [Errno 113] No route to host". Unfortunately it doesn't report which host can't be contacted.

**Comment by valentijnscholten** [comment]
deduplication is asynchronous so executed by the celery worker. If the worker is not running dedupe will not happen.

**Comment by atruemper** [comment]
The Celery worker was up and running, but due to our setup of projects and engagements it seemed to be overloaded. We have different modules that upload scans automatically during CI/CD whenever a master-branch is build and each creates a new engagement. System-wide deduplication is enabled but deduplication on engagement level was disabled. Thus we had about 200k open issues and the process started to compare each issue from a new scan with each of the 200k open issues which effectively blocked celery.

We try a different approach now to upload the scans to a dedicated engagement with enabled deduplication and this seems to work now.

So I agree this is not a bug but we were using DefectDojos projects and engagements in a way it was not intended to be used, but the algorithm doing the deduplication check does not seem to be implemented very efficiently as well.

**Comment by valentijnscholten** [comment]
The import needs some performance tuning indeed.
