### ISSUE TITLE
Upgrade defectdojo using docker-compose

### ISSUE THREAD

**Issue by ducquang92** [DefectDojo/django-DefectDojo#2775]
Hi,
Is there any way we can upgrade DefectDojo to a new version using docker-compose without losing the database?
I found the main documentation at https://defectdojo.readthedocs.io/en/latest/upgrading.html but I think it is for local installation, not for the container.

**Comment by dayal18** [comment]
Change the docker-compose.yml file add your existing DB details (url, db name, creds, etc..), also change in settings.dist.py.
And also mount your local database volume path (mysql) to the mysql docker image docker-compose.yml.

If you don't want to use mysql as a docker image, then modify docker-compose remove the mysql docker image.. and then just make the other changes..

**Comment by madchap** [comment]
docker-compose has a volume for mysql. If you update and do not remove the volume, your database will remain intact. Of course, after updating, you should make sure to run `python manage.py migrate`.
