### ISSUE TITLE
Support for Apache

### ISSUE THREAD

**Issue by navzen2000** [DefectDojo/django-DefectDojo#2776]
**Is your feature request related to a problem? Please describe**
Nginx is facing a lawsuite and it will help if defect dojo can be setup with apache

**Describe the solution you'd like**
Replace nginx with apache
Please provide verified steps in docker build

**Describe alternatives you've considered**
Use Apache image
Install modwsgi
Create vhost.conf that can replace nginx.conf and include in httpd.conf

**Additional context**
https://www.crn.com/news/cloud/firm-sues-f5-networks-claims-rights-to-nginx-tech-developed-by-its-employees
https://django-project-skeleton.readthedocs.io/en/latest/apache2_vhost.html
https://docs.djangoproject.com/en/3.1/howto/deployment/wsgi/modwsgi/
https://www.metaltoad.com/blog/hosting-django-sites-apache

**Comment by Maffooch** [comment]
Hi @navzen2000 this can easily be accomplished after installing via [setup.bash](https://github.com/DefectDojo/django-DefectDojo/blob/master/setup/README.md) instead of using docker. If you would like to implement this feature, please submit to the [Community Contribs Repo](https://github.com/DefectDojo/Community-Contribs). Thanks!

**Comment by navzen2000** [comment]
@Maffooch setup.bash installation  method will be EOL on 2020-12-31
Am looking on steps to wire apache with defect dojo django container, but there are no documented steps as such.

**Comment by navzen2000** [comment]
Quick Update: Tried a workaround like follows and its working.
Hope I have not missed anything.
Got rid of nginx by removing the service container
uwsgi is now enabled with http
configured uwsgi to render static files (collecstatic output copied to uwsgi container image)
stood up apache as reverse proxy to uwsgi http service inside uwsgi container

**Comment by valentijnscholten** [comment]
I don't think we can support all possible configurations. nginx is easy and lightweight so we're probably going to stick to that.
