### ISSUE TITLE
Error in changing the status of an issue from Jira to defectdojo

### ISSUE THREAD

**Issue by pabloalexsandroalmeida83** [DefectDojo/django-DefectDojo#2784]
**Bug description**
I integrated DefectDojo with Jira, everything is working fine, only when I try to change the status of an issue in Jira, it gives error 500 when trying to reflect on DefectDojo

**Steps to reproduce**

**Expected behavior**

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Commit Message: [use `git show -s --format="[%ci] %h: %s [%d]"`]

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

![Captura de Tela 2020-08-16 às 18 55 00](https://user-images.githubusercontent.com/57901549/90344711-926e4000-dff2-11ea-9e55-c48eb2c50ad7.png)

**Console logs** (optional)

n core 0)

nginx_1         | 10.10.78.38 - - [16/Aug/2020:21:44:29 +0000] "GET /alerts/count HTTP/1.1" 200 15 "http://10.10.91.114:8080/system_settings" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" "-"

uwsgi_1         | [pid: 17|app: 0|req: 489/1004] 10.10.78.38 () {46 vars in 832 bytes} [Sun Aug 16 21:44:29 2020] GET /alerts/count => generated 15 bytes in 6 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 1)

uwsgi_1         | Internal Server Error: /webhook/

uwsgi_1         | Traceback (most recent call last):

uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner

uwsgi_1         |     response = get_response(request)

uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response

uwsgi_1         |     response = self.process_exception_by_middleware(e, request)

uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response

uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)

uwsgi_1         |   File "/usr/local/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view

uwsgi_1         |     return view_func(*args, **kwargs)

uwsgi_1         |   File "./dojo/jira_link/views.py", line 36, in webhook

uwsgi_1         |     parsed = json.loads(request.body.decode('utf-8'))

uwsgi_1         |   File "/usr/local/lib/python3.5/json/__init__.py", line 319, in loads

uwsgi_1         |     return _default_decoder.decode(s)

uwsgi_1         |   File "/usr/local/lib/python3.5/json/decoder.py", line 339, in decode

uwsgi_1         |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())

uwsgi_1         |   File "/usr/local/lib/python3.5/json/decoder.py", line 357, in raw_decode

uwsgi_1         |     raise JSONDecodeError("Expecting value", s, err.value) from None

uwsgi_1         | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

uwsgi_1         | [pid: 1|app: 0|req: 516/1005] 10.10.10.207 () {52 vars in 877 bytes} [Sun Aug 16 21:44:29 2020] POST /webhook/?user_id=5ede4d30b5854a0abfbd704d&user_key=5ede4d30b5854a0abfbd704d => generated 27 bytes in 23 msecs (HTTP/1.1 500) 6 headers in 192 bytes (1 switches on core 0)

nginx_1         | 10.10.10.207 - - [16/Aug/2020:21:44:29 +0000] "POST /webhook/?user_id=5ede4d30b5854a0abfbd704d&user_key=5ede4d30b5854a0abfbd704d HTTP/1.1" 500 27 "-" "Atlassian Webhook HTTP Client" "18.234.32.227"

uwsgi_1         | [pid: 17|app: 0|req: 490/1006] 10.10.10.207 () {50 vars in 989 bytes} [Sun Aug 16 21:44:32 2020] GET /alerts/count => generated 15 bytes in 8 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)

nginx_1         | 10.10.10.207 - - [16/Aug/2020:21:44:32 +0000] "GET /alerts/count HTTP/1.1" 200 15 "https://meudojo.com.br/product/39/finding/open?test__engagement__product=39" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0" "177.33.138.198"

uwsgi_1         | [pid: 1|app: 0|req: 517/1007] 10.10.78.38 () {46 vars in 832 bytes} [Sun Aug 16 21:44:39 2020] GET /alerts/count => generated 15 bytes in 6 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 1)

nginx_1         | 10.10.78.38 - - [16/Aug/2020:21:44:39 +0000] "GET /alerts/count HTTP/1.1" 200 15 "http://10.10.91.114:8080/system_settings" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" "-"

nginx_1         | 10.10.66.240 - - [16/Aug/2020:21:44:39 +0000] "GET / HTTP/1.1" 302 0 "-" "ELB-HealthChecker/2.0" "-"

uwsgi_1         | [pid: 1|app: 0|req: 518/1008] 10.10.66.240 () {34 vars in 396 bytes} [Sun Aug 16 21:44:39 2020] GET / => generated 0 bytes in 0 msecs (HTTP/1.1 302) 7 headers in 215 bytes (1 switches on core 0)

nginx_1         | 10.10.10.207 - - [16/Aug/2020:21:44:43 +0000] "GET /alerts/count HTTP/1.1" 200 15 "https://meudojo.com.br/product/39/finding/open?test__engagement__product=39" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0" "177.33.138.198"

**Additional context** (optional)

**Comment by valentijnscholten** [comment]
Can you add some logging to the webhook and post the json body  here that is causing the exception?

**Comment by valentijnscholten** [comment]
Please come to slack if you're still experiencing errors.
