### ISSUE TITLE
Import feature for Finding Templates

### ISSUE THREAD

**Issue by dayal18** [DefectDojo/django-DefectDojo#2787]
**Is your feature request related to a problem? Please describe**
Today we don't have an import feature for findings to be updated to Finding Template.

**Describe the solution you'd like**
Having import findings to DefectDojo in Finding Templates helps a lot while migrating or using the same template across various instances.

**Describe alternatives you've considered**
Copy the Database table from one instance to another.

**Comment by Maffooch** [comment]
HI @dayal18 a potential solution for you would be to leverage Django's dumpdata/loaddata. It allows for exporting and importing json documents to automatically create objects similar to how API calls would work. [dumpdata](https://docs.djangoproject.com/en/3.1/ref/django-admin/#dumpdata) and [loaddata](https://docs.djangoproject.com/en/3.1/ref/django-admin/#loaddata)

**Comment by valentijnscholten** [comment]
I don't understand the feature request. Is it that you want to be able to export finding templates from one instance and import them in another instance?

**Comment by dayal18** [comment]
Yup, that's what I want. Suppose if I have a JSON file or XML file for many findings (template findings with Description, remediation, Impact, etc..,), all I was looking is to import this file into DDJ.. Because the templates are going to be the same for many and this template can also be shared with others.

Example:
OWASP Finding Template
SANS Finding Template
etc..,

**Comment by Maffooch** [comment]
@dayal This what you're looking for exactly:

Export all finding templates to JSON
docker-compose exec uwsgi ./manage.py dumpdata --indent 2 dojo.finding_template > some_file.json

Import back into dojo
docker-compose exec uwsgi ./manage.py loaddata some_file.json

**Comment by dayal18** [comment]
> @dayal This what you're looking for exactly:
> 
> Export all finding templates to JSON
> docker-compose exec uwsgi ./manage.py dumpdata --indent 2 dojo.finding_template > some_file.json
> 
> Import back into dojo
> docker-compose exec uwsgi ./manage.py loaddata some_file.json

Thank you @Maffooch
