### ISSUE TITLE
Import SonarQube Security-hotspot via the SonarQube API Importer

### ISSUE THREAD

**Issue by SPoint42** [DefectDojo/django-DefectDojo#2790]
SonarQube 

In the news version of sonarqube we have the security hotspot. 
This is another kind of source of vulns we can add to defect via sonar

There is the possibility to get via the API at : 

http://mysonar/api/hotspots/search?projectKey=myprojectkey

[sechotspotsonar-json.txt](https://github.com/DefectDojo/django-DefectDojo/files/5096711/sechotspotsonar-json.txt)

**Comment by SPoint42** [comment]
work on it this week

**Comment by damiencarol** [comment]
@SPoint42 it seems this issue is resolved no? I tested version 1.9.2 and I'm able to import Security Hotspot SonarQube scans.

**Comment by SPoint42** [comment]
@damiencarol via Sonar API Import ?

**Comment by damiencarol** [comment]
@SPoint42 I think you are right. For now, we only manage vulnerabilities. Are you still working on this one?

**Comment by damiencarol** [comment]
Adding more resources to the discussion: https://jira.sonarsource.com/browse/MMF-1672

**Comment by SPoint42** [comment]
@damiencarol I go to things, but I still have problem to import via API the hotspots

**Comment by damiencarol** [comment]
If I can help you don't hesitate.
