### ISSUE TITLE
External Dependency in Safety Parser Requires Internet Connection

### ISSUE THREAD

**Issue by alles-klar** [DefectDojo/django-DefectDojo#2795]
**Bug description**
Until release 1.7. it was possible to run defectdojo in environments without internet connection. The new safety parser requires a connection to https://raw.githubusercontent.com/pyupio/safety-db/master/data/insecure_full.json. In setups without a internet connections the unit tests and also using the parser will fail.

dojo/tools/safety/parser.py", line 11

**Steps to reproduce**
1. Run the unit tests of defectdojo in a environment without internet connection.

**Expected behavior**
Handling the Error when the url is not reachable.

**Deployment method** *(select with an `X`)*
- [x] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Console logs** (optional)

 ERROR: test_no_cve (dojo.unittests.test_safety_parser.TestSafetyParser)

 Traceback (most recent call last):
   File "/usr/local/lib/python3.6/urllib/request.py", line 1349, in do_open
     encode_chunked=req.has_header('Transfer-encoding'))
   File "/usr/local/lib/python3.6/http/client.py", line 1272, in request
     self._send_request(method, url, body, headers, encode_chunked)
   File "/usr/local/lib/python3.6/http/client.py", line 1318, in _send_request
     self.endheaders(body, encode_chunked=encode_chunked)
   File "/usr/local/lib/python3.6/http/client.py", line 1267, in endheaders
     self._send_output(message_body, encode_chunked=encode_chunked)
   File "/usr/local/lib/python3.6/http/client.py", line 1038, in _send_output
     self.send(msg)
   File "/usr/local/lib/python3.6/http/client.py", line 976, in send
     self.connect()
   File "/usr/local/lib/python3.6/http/client.py", line 1425, in connect
     super().connect()
   File "/usr/local/lib/python3.6/http/client.py", line 948, in connect
     (self.host,self.port), self.timeout, self.source_address)
   File "/usr/local/lib/python3.6/socket.py", line 724, in create_connection
     raise err
   File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
     sock.connect(sa)
 TimeoutError: [Errno 110] Connection timed out
 During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
   File "/app/dojo/unittests/test_safety_parser.py", line 19, in test_no_cve
     parser = SafetyParser(f, Test())
   File "/app/dojo/tools/safety/parser.py", line 11, in __init__
     response = urllib.request.urlopen(url)
   File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
     return opener.open(url, data, timeout)
   File "/usr/local/lib/python3.6/urllib/request.py", line 526, in open
     response = self._open(req, data)
   File "/usr/local/lib/python3.6/urllib/request.py", line 544, in _open
     '_open', req)
   File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
     result = func(*args)
   File "/usr/local/lib/python3.6/urllib/request.py", line 1392, in https_open
     context=self._context, check_hostname=self._check_hostname)
   File "/usr/local/lib/python3.6/urllib/request.py", line 1351, in do_open
     raise URLError(err)
 urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

 Ran 419 tests in 561.413s
 FAILED (errors=4, skipped=14)

**Comment by valentijnscholten** [comment]
What's your suggested solution?

**Comment by alles-klar** [comment]
Not sure what is optimal:
* Catch the error and throw a warning -> Good for production but hard to test
* add a database copy to defectdojo -> external dependency, how do we update the files?

**Comment by valentijnscholten** [comment]
I don't think we have the resources to support this scenario. If someone wants to use this in production without internet, they'll have to find out how to supply the data to the parser. For unit tests they'll have to disable this parser (skip the test).

**Comment by alles-klar** [comment]
Maybe we download the files during installation (where we need internet anyway) and only try to update the database in the parser. If the connection fails we can throw a warning.

**Comment by jay3-3** [comment]
Hi,

Is this still working on last release version 1.11.1?
If I try "docker-compose build" without internet I get the next message:

> Step 21/26 : RUN curl -sS -o dojo/tools/safety/insecure_full.json https://raw.githubusercontent.com/pyupio/safety-db/master/data/insecure_full.json
>  Running in 590894e93d9d
> 
> curl: (6) Could not resolve host: raw.githubusercontent.com
> ERROR: Service 'uwsgi' failed to build : The command '/bin/sh -c curl -sS -o dojo/tools/safety/insecure_full.json https://raw.githubusercontent.com/pyupio/safety-db/master/data/insecure_full.json' returned a non-zero code: 6


Before I built and run the project with internet. Now I am trying to build without internet.

Thank you.

**Comment by valentijnscholten** [comment]
You can't build without internet. I think that would be impossible anyway because you're using docker that pulls image, pip that installs packages, etc?

**Comment by jay3-3** [comment]
Thank you @valentijnscholten I misunderstood the problem here. It is only related to test and to execute DD, but not to build it.

Technically, it will be possible to build the project, won't it? If I use pip, docker... locally saving all dependencies in advance. Sorry, this is another topic.

**Comment by valentijnscholten** [comment]
hmm maybe. never had to work in an environment without internet :-) But this ticket indeed was about making the unit tests run without internet. if you don't use that scanner/parser, you can comment out that part from the build.

**Comment by alles-klar** [comment]
The fix was merged, so defectdojo can run without internet connection if you pull the image for example from a private repository. If you also have no connection on the client side you may get some javascript errors.
