### ISSUE TITLE
Contrast Scan import error

### ISSUE THREAD

**Issue by RuiSN** [DefectDojo/django-DefectDojo#2803]
**Bug description**
The import of a contrast scan in CSV format fails in version 1.7.1. The same file gets imported on version 1.5.4 without error.

**Steps to reproduce**
Steps to reproduce the behaviour:
1. Upload a CSV Contrast scan to an engagement on defect dojo 1.7.1
2. See that it fails with the error: "An error has occurred in the parser, please see error log for details."
3. run "docker logs [django-defectdojo_uwsgi_1 contained ID]"
4. See error:
`'DataFrame' object has no attribute 'ix'
Traceback (most recent call last):
  File "./dojo/engagement/views.py", line 586, in import_scan_results
    parser = import_parser_factory(file, t, active, verified)
  File "./dojo/tools/factory.py", line 122, in import_parser_factory
    parser = ContrastCSVParser(file, test)
  File "./dojo/tools/contrast/parser.py", line 22, in __init__
    cwe = self.format_cwe(df.ix[i, 'CWE ID'])
  File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 5130, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'ix'
Error in parser: 'DataFrame' object has no attribute 'ix'`

**Expected behavior**
I expected the CSV to be imported.

**Deployment method** *(select with an `X`)*
- [X] Docker

**Environment information**
 - Operating System: Ubuntu 18.04.4 LTS
 - DefectDojo Commit Message: https://github.com/DefectDojo/django-DefectDojo/commit/d8fb1cd38e981a2e24465dcc579409607274e137

**Comment by valentijnscholten** [comment]
Can you provide an example file to reproduce?

**Comment by RuiSN** [comment]
[vulnerabilities2020-09-21.csv.zip](https://github.com/DefectDojo/django-DefectDojo/files/5254910/vulnerabilities2020-09-21.csv.zip)

Sure, here you go. You have to unzip it first before use.

**Comment by RuiSN** [comment]
Hi @valentijnscholten , any news about this? Have you tried the example file?

**Comment by damiencarol** [comment]
@RuiSN refreshig this one. Saw that we don't have much tests on this format. I'm investigating.

**Comment by RuiSN** [comment]
Thank you @damiencarol.

**Comment by damiencarol** [comment]
@RuiSN fixed by  #3737 . wil be part of `1.13.0`
