### ISSUE TITLE
Add finding from Template - Internal Server Error

### ISSUE THREAD

**Issue by dayal18** [DefectDojo/django-DefectDojo#2818]
**Bug description**
When trying to add a finding to a test from "template" (Add finding from template) this generates an Internal Server Error 500.

**Steps to reproduce**
1. Create 'a finding template by going to "Finding Templates" --> Add a Finding Template'
2. Go To 'Product --> engagement --> Test and "add finding from Template" '
3. The Application 'Provides with a list of all the finding templates, --> select Use this Template'

**Expected behavior**
The template should apply to the Test.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [ Ubuntu 18.04]
 - DefectDojo Commit Message: [use `git show -s --format="[%ci] %h: %s [%d]"`]

uwsgi_1         | Internal Server Error: /test/3/add_findings/6
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
uwsgi_1         |     return view_func(request, *args, **kwargs)
uwsgi_1         |   File "./dojo/test/views.py", line 542, in add_temp_finding
uwsgi_1         |     'tags': [tag.name for tag in finding.tags]})
uwsgi_1         |   File "./dojo/forms.py", line 1008, in __init__
uwsgi_1         |     self.fields['simple_risk_accept'].initial = True if self.instance.is_simple_risk_accepted else False
uwsgi_1         |   File "./dojo/models.py", line 1538, in is_simple_risk_accepted
uwsgi_1         |     if self.get_simple_risk_acceptance(create=False) is not None:
uwsgi_1         |   File "./dojo/models.py", line 1501, in get_simple_risk_acceptance
uwsgi_1         |     if hasattr(self.test.engagement, 'simple_risk_acceptance') and len(self.test.engagement.simple_risk_acceptance) > 0:
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 189, in __get__
uwsgi_1         |     "%s has no %s." % (self.field.model.__name__, self.field.name)
uwsgi_1         | dojo.models.Finding.test.RelatedObjectDoesNotExist: Finding has no test.
uwsgi_1         | [pid: 17|app: 0|req: 4224/7773] 10.44.2.86 () {54 vars in 2607 bytes} [Mon Aug 31 19:14:46 2020] GET /test/3/add_findings/6 => generated 27 bytes in 3766 msecs (HTTP/1.1 500) 6 headers in 192 bytes (1 switches on core 0)

URLs accessed:
https://localhost/test/3/add_findings/6
https://localhost/test/3/search

**Comment by dayal18** [comment]
Have to disable the line 1002 in dojo/forms.py
line 1002: self.fields['simple_risk_accept'].initial = True if self.instance.is_simple_risk_accepted else False

Is there an alternative fix to this?

**Comment by valentijnscholten** [comment]
fixed in that PR. Going to close this now so we can focus on the remaining issues.
