### ISSUE TITLE
Incorrect API documentation

### ISSUE THREAD

**Issue by bertonjulian** [DefectDojo/django-DefectDojo#282]
Hey guys,

The documentation when navigating to /api/v1/doc/ seems to be incorrect in quite a few places making it difficult to interact with. One example (image below) is when looking at the importscan endpoint description, it mentions that the engagement parameter is optional (which it isn't) and gives the example value of "hello world". However it expects a uri to an engagement. The file parameter is not as bad but still lacks information like that it can also support local file paths. Here is an example of the data that is meant to be sent for this request:

 `
{
 "minimum_severity": "Info",
 "scan_date": "2017-05-13",
 "verified": false,
 "file": "/home/ubuntu/zap_report.xml",
 "tags": "",
 "active": false,
 "engagement": "/api/v1/engagements/1/",
 "scan_type": "ZAP Scan"
}
`

![image](https://cloud.githubusercontent.com/assets/2941730/26180992/09155ec2-3bb0-11e7-8381-814245d9e568.png)

**Comment by devGregA** [comment]
@grendel513 do we know where this is generated from?

**Comment by grendel513** [comment]
django-tastypie generates all the documentation.

**Comment by devGregA** [comment]
@bertonjulian investigating on Monday as part of our summit

**Comment by devGregA** [comment]
Hi @bertonjulian, came back to this, but the tastypie page has significantly changed. I don't think much can be changed here with the new layout. It no longer says required or not. It shows all the options (I'm not sure if that is better). We've discussed moving away from tastypie, but the resources aren't really there to do that at this time.
