### ISSUE TITLE
Easily identify instances

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#2833]
**Is your feature request related to a problem? Please describe**
When having several running instances of DefectDojo, it'd be nice to have a clear visual indication as to what instance that is. E.g. production, QA, test (other than the url bar).

This to avoid eventual tests/deletion being done on the wrong instance.

**Describe the solution you'd like**
I was thinking of a very visible button/text/whatnot on the top-level bar at the same level as the logo?

It could be displayed when a settings.py flag is there, or better yet, be just another setting in the global settings page.

**Comment by valentijnscholten** [comment]
RTF urlbar ;-) 

On the top of the screen between logo and search field we have lots of space, so we could add an "instance name" kind of value there. Possibly from settings.py so it can be easily overriden per environment without doing db queries.

**Comment by madchap** [comment]
Bah, RTF urlbar is very valid :+1: 

Between this and being able to have the browser's back button with meaningful info to get back to things you want, I'd rather spend time on the latter.
