### ISSUE TITLE
500 error on importing trufflehog scan result

### ISSUE THREAD

**Issue by alishasinghania** [DefectDojo/django-DefectDojo#2848]
**Bug description**
On importing the scan results of Trufflehog, it gives server 500 error and the findings dont get upoloaded.

**Steps to reproduce**
1. Go to findings tab
2. Click on "Import Scan Results"
3. Select the scan type as Trufflehog scan and upload the json file 
4. After clicking on Import it gives 500 server error

**Comment by valentijnscholten** [comment]
Please follow instructions in the template and provide version, sample, logs, stacktrace, etc.
