### ISSUE TITLE
api_v2: support filtering on metadata for products, endpoints and findings

### ISSUE THREAD

**Issue by xens** [DefectDojo/django-DefectDojo#2854]
**Description**
DefectDojo offers the possibility to create custom key/value entries called metadata in the `products` and `endpoints` models.

```     
"product_meta": [
        {
          "name": "customfield1",
          "value": "value"
        },
        {
          "name": "customfield2",
          "value": "value"
        },
]
``` 
it's a great way to extend the existing models for user-specific use cases, but as-of-today DDJ lacks the ability do filtering on those fields which is quite limiting when dealing with its API.

**Describe the solution you'd like**

As a user I should be able to query the different API endpoints that support these metadata and do filtering based on their key or on their key **and** value, so a query like this

`api/v2/products/?metadata=customfield1` should return only the products containing this key.

Filtering on the key + the value should also be supported

`api/v2/products/?metadata=customfield1:value`

**Limitations**

custom metadata are a great way to add flexibility to an existing model but there's limitations like the lack of a proper type (all fields are strings) so it's not possible to easily do sorting on queries as we can't predict the kind of data the user will store on them.

**Proposal**

If the above description works for you I should be able to start to work on its implementation soon. I'll also open a separate PR to implement the metadata fields on the `/findings/` endpoint.

**Comment by valentijnscholten** [comment]
I think this is useful. Is that ':' construct a common thing, or just something you thought would work well?

**Comment by xens** [comment]
I've spent some time this afternoon reading things on that subject and that's what I've ended up with basically.

There's also this alternative that is quite popular `?metadata[customfield1]=value` and part of the OpenAPIv3 spec (the more I read on the subject the more I'd tend to use that syntax).

refs:
* https://swagger.io/docs/specification/serialization/
* https://github.com/OAI/OpenAPI-Specification/issues/1706
* https://www.moesif.com/blog/technical/api-design/REST-API-Design-Filtering-Sorting-and-Pagination/

**Comment by ptrovatelli** [comment]
seems nice to me. the array quotation seems more standard and intuitive indeed `?metadata[customfield1]=value`

**Comment by mtesauro** [comment]
Seems like a very useful API addition as I've used custom metadata for many different DefectDojo installs.

I also like the `?metadata[customfield1]=value` syntax

**Comment by valentijnscholten** [comment]
Thanks for looking into some syntax that is common / standard / spec-compliant, I think that's the preferred option.

**Comment by xens** [comment]
Awesome, thanks for all your answers, I'll go ahead with the implementation and reference this issue in the future PR.

**Comment by xens** [comment]
@valentijnscholten this one is not implemented yet, the PR you referenced was the metadata support on findings, now I'll start to work on filtering on all the metadata endpoint's
