### ISSUE TITLE
`Authentication credentials were not provided` during API import scan

### ISSUE THREAD

**Issue by TMFRook** [DefectDojo/django-DefectDojo#2872]
**Bug description**
I am trying to perform an import scan through the API. Per the documentation, I provided the header `Authorization: ApiKey admin:XXXmykeyXXX`.

![image](https://user-images.githubusercontent.com/68116003/93226425-4cb3ad00-f741-11ea-96ad-135b3327ece4.png)

However, I am still getting the error message `Authentication credentials were not provided`.

**Steps to reproduce**
1. Get your API key through https://yourdomain.com/api/key
2. Add it to your request headers
3. Set other parameters for the `api/v2/import-scan` request.
4. See error `Authentication credentials were not provided`.

**Expected behavior**
Should have imported the scan.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 20.04]
 - d8fb1cd38e981a2e24465dcc579409607274e137

**Comment by Maffooch** [comment]
Hi @TMFRook, the key you used belongs to the APIv1 instead of APIv2. Please use the APIv2 key at  https://yourdomain.com/api/key-v2 if you want to use APIv2.
