### ISSUE TITLE
Report Builder AsciiDoc endpoint_status error

### ISSUE THREAD

**Issue by irmachez** [DefectDojo/django-DefectDojo#2897]
**Report Builder Server Error (500)**
I would like to test some Version of DefectDojo. I am DefectDojo v.1.8.0-dev right now.
I want to generate a Report of Engagements of some Products and i get Server Error (500) 

**Steps to reproduce**
1. Go to 'Reports '
2. Click on 'Report Builder'
3. Report type 'AsciiDoc', Drag Finding and filter the Findings I want to be appeared in Report
4. See error 'Server Error (500)'

**Expected behavior**
I got the same problem by DefectDojo v.1.7.1
I dont get this such error with DefectDojo v.1.5.4 but of course I would like to use the latest version of DefectDojo, because they have more Feature.
Will and when this Issue by DefectDojo v.1.8.0-dev and v.1.7.1 be fixed please? Or How to fix it if i should do it myself? I will be very gratefull for some helps.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Ubuntu 18.04

**Comment by valentijnscholten** [comment]
Do you have any stacktrace from the log file? Or from the browser 500 page if you enable DEBUG in settings.py?

**Comment by irmachez** [comment]
Hallo, thanks for ask. I got this Message from Log file: 

<img width="570" alt="Report Error 500" src="https://user-images.githubusercontent.com/50573839/94532876-b7cfaa00-023e-11eb-8089-7c2816d4a366.PNG">

**Comment by valentijnscholten** [comment]
@Maffooch can you take look, looks like a bug?
