### ISSUE TITLE
Transitions in JIRA will result in an endless loop of updates

### ISSUE THREAD

**Issue by kareem-DA** [DefectDojo/django-DefectDojo#2948]
Bug description
An update to a finding that will result in a transition to a JIRA issue also ends up in an endless loop

**Steps to reproduce**
1. Create a finding in a product with push_to_JIRA set.
2. From the API send 
{"push_to_jira": "true",
  "active": "false",
  "verified": "true",
  "is_Mitigated": "true"}
To patch that finding. 
3. DDJ will loop in updates to JIRA to try to update a ticket that has already been done

**Expected behavior**
DDJ will update the JIRA ticket once only

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
DDJ version 1.8.0. Installed with docker compose.

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)
O.K.  I started this thread on https://owasp.slack.com/archives/C2P5BA8MN/p1601478823038900, but the discussion really belongs here.  So, I am continuing here.  When I started this, I really didn’t expect to be digging into code.  After a lot of debugging, here is where I am and a couple of questions that I have.
First, the setup:
I have a finding that I am trying to close with the API.  So I am pushing to the API.
{ “push_to_jira”: “true”,
  “active”: “false”,
  “verified”: “true”,
  “is_Mitigated”: “true”}
When it saves it gets processed by finding.save() and then gets sent to function update_jira_issue.  the update_jira_issue function calls find.save several times.  At least twice when it there is a state transition for JIRA. Once around line 1610 and another time after the transition is complete.  When find.save() is called, it doesn’t specifically state that push_to_jira is true, but the object still has push_to_jira set, so .save() will overwrite the default value of push_to_jira (~ 6 lines into the function).  This happens 2 per call to update_jira_issue.  Now the code is running in a loop.
Questions:
If push_to_jira is specifically called out when the .save() functions is called, should the value in the object be overwriting it?
Should the value of find.push_to_jira be set to false by update_jira_issue before calling save again? (edited) 

See Slack Chats.
https://owasp.slack.com/archives/C014H3ZV9U6/p1601570100039600?thread_ts=1601563511.038000&cid=C014H3ZV9U6
https://owasp.slack.com/archives/C2P5BA8MN/p1601478823038900

**Comment by valentijnscholten** [comment]
fixed in dev, will be in 1.9.0
