### ISSUE TITLE
Update demo details on defectdojo.org (was: Test environment is down)

### ISSUE THREAD

**Issue by achaussier** [DefectDojo/django-DefectDojo#2958]
Hello,

For information, the test environment at https://defectdojo.herokuapp.com/ is down:

```
 Application error

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail 
```

Have a nice day,

**Comment by madchap** [comment]
Heroku app is no longer supported. Where did you see it referenced? Thanks.

**Comment by valentijnscholten** [comment]
#2479

**Comment by achaussier** [comment]
It's the link of the demo environment in the README file: https://github.com/DefectDojo/django-DefectDojo/blob/master/README.md#demo

**Comment by StefanFl** [comment]
The link is on https://www.defectdojo.org/ as well. Under "Get Started" it says: "Take DefectDojo for a spin and review the demo of DefectDojo and login with sample credentials." with a link to Heroku.

**Comment by madchap** [comment]
Thanks, we'll get that corrected.

https://github.com/DefectDojo/django-DefectDojo/pull/2963

and defectdojo.org will come soonish...

**Comment by madchap** [comment]
This slipped under the radar. @mtesauro could you amend the page with the latest details to reach the demo site? Cheers.

**Comment by devGregA** [comment]
fixed
