### ISSUE TITLE
Error while creating new finding integration with JIra

### ISSUE THREAD

**Issue by stevieg27** [DefectDojo/django-DefectDojo#2976]
**Bug description**
Integrated Jira with defectdojo but while testing the working it is throwing the below error in logs.

********************************************

celeryworker_1  | [ ERROR/MainProcess] Task add_issue_task[0bb87eb7-c4ac-4a9b-80a0-24bc357a61a8] raised unexpected: IndexError('list index out of range',)
celeryworker_1  | Traceback (most recent call last):
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task
celeryworker_1  |     R = retval = fun(*args, **kwargs)
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__
celeryworker_1  |     return self.run(*args, **kwargs)
celeryworker_1  |   File "/app/dojo/tasks.py", line 268, in add_issue_task
celeryworker_1  |     add_issue(find, push_to_jira)
celeryworker_1  |   File "/app/dojo/utils.py", line 1398, in add_issue
celeryworker_1  |     if 'duedate' in meta['projects'][0]['issuetypes'][0]['fields']:
celeryworker_1  | IndexError: list index out of range

*****************************************************

**Steps to reproduce**
1. Go to defetcdojo add manually a new finding after integrating with jira as per defctdojo documentation
2. Issue not created in Jira
3. Check the logs and can find the one mentioned above.

**Expected behavior**
Create the finding in Jira along with defectdojo.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [* ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [Kali Linux]
 

**Console logs** (optional)

celeryworker_1  | [ ERROR/MainProcess] Task add_issue_task[0bb87eb7-c4ac-4a9b-80a0-24bc357a61a8] raised unexpected: IndexError('list index out of range',)
celeryworker_1  | Traceback (most recent call last):
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task
celeryworker_1  |     R = retval = fun(*args, **kwargs)
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__
celeryworker_1  |     return self.run(*args, **kwargs)
celeryworker_1  |   File "/app/dojo/tasks.py", line 268, in add_issue_task
celeryworker_1  |     add_issue(find, push_to_jira)
celeryworker_1  |   File "/app/dojo/utils.py", line 1398, in add_issue
celeryworker_1  |     if 'duedate' in meta['projects'][0]['issuetypes'][0]['fields']:
celeryworker_1  | IndexError: list index out of range

**Comment by valentijnscholten** [comment]
we see this sometimes but we don't know why, can you add some logging to print the actual response from the jira api? 
is the jira server or cloud? normal project or next gen?
which version of DD are you using

**Comment by whitespots** [comment]
+1
```
celeryworker_1_c93dde253bf4 | Traceback (most recent call last): celeryworker_1_c93dde253bf4 | File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task celeryworker_1_c93dde253bf4 | R = retval = fun(*args, **kwargs) celeryworker_1_c93dde253bf4 | File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__ celeryworker_1_c93dde253bf4 | return self.run(*args, **kwargs) celeryworker_1_c93dde253bf4 | File "/app/dojo/tasks.py", line 268, in add_issue_task celeryworker_1_c93dde253bf4 | add_issue(find, push_to_jira) celeryworker_1_c93dde253bf4 | File "/app/dojo/utils.py", line 1398, in add_issue celeryworker_1_c93dde253bf4 | if 'duedate' in meta['projects'][0]['issuetypes'][0]['fields']: celeryworker_1_c93dde253bf4 | IndexError: list index out of range celeryworker_1_c93dde253bf4 | [2020-10-02 08:48:47,637: INFO/MainProcess] Received task: add_issue_task[e3f2e81e-c69a-448c-a820-ee1eb0813f80] celeryworker_1_c93dde253bf4 | [2020-10-02 08:48:47,639: INFO/MainProcess] add_issue_task[e3f2e81e-c69a-448c-a820-ee1eb0813f80]: add issue task celeryworker_1_c93dde253bf4 | [2020-10-02 08:48:47,966: ERROR/MainProcess] Task add_issue_task[e3f2e81e-c69a-448c-a820-ee1eb0813f80] raised unexpected: IndexError('list index out of range',)
```

**Comment by valentijnscholten** [comment]
next gen projects are not supported yet

**Comment by valentijnscholten** [comment]
we added some DEBUG logging in 1.9.2. Can you try again with 1.9.2 and setting loglevel to DEBUG in settings.dist.py for all loggers or at least the 'dojo' logger.
