### ISSUE TITLE
Add cloudsploit importer

### ISSUE THREAD

**Issue by SPoint42** [DefectDojo/django-DefectDojo#2979]
**Scanner Name**
https://github.com/aquasecurity/cloudsploit

CloudSploit by Aqua is an open-source project designed to allow detection of security risks in cloud infrastructure accounts, including: Amazon Web Services (AWS), Microsoft Azure, Google Cloud Platform (GCP), Oracle Cloud Infrastructure (OCI), and GitHub. These scripts are designed to return a series of potential misconfigurations and security risks.

**Sample File**
Please attach a sample file and the format of the file (xml, json, csv).

**Comment by SPoint42** [comment]
@valentijnscholten : assign to me please

**Comment by berez23** [comment]
Is there any plan to add this integration? @SPoint42 
Thanks

**Comment by SPoint42** [comment]
I've start working last month on it

**Comment by berez23** [comment]
Do you have some code to share .. @peppelinux  and me would love to have this code ready soon?

**Comment by berez23** [comment]
Thanks @SPoint42

**Comment by damiencarol** [comment]
I will be glad to help you in this task @SPoint42 . The way we add parsers has changed a little bit. (less work)
don't hesitate to ping me in your pull request.

**Comment by luliz** [comment]
Is there any update on the status of this integration? @SPoint42

**Comment by valentijnscholten** [comment]
merged into dev / 2.2.0
