### ISSUE TITLE
Search product by tags

### ISSUE THREAD

**Issue by saldam72** [DefectDojo/django-DefectDojo#2993]
Hello Team,
We are evaluating DefectDojo in our organization and have found tags to be a very useful feature. We would need to be able to search for a product or an engagement with their tags. It's possible ?

Thanks
Sal

**Comment by wurstbrot** [comment]
I agree, but please search for existing issues, e.g. https://github.com/DefectDojo/django-DefectDojo/issues/2569

**Comment by valentijnscholten** [comment]
and #1812. It is something we are considering, but would (ideally) require the django-tagging library to be replaced by django-tagulous and we may need some sponsoring to get it implemented.
