### ISSUE TITLE
Authorized User with permission to add Engagements is able to add Engagements to all Products

### ISSUE THREAD

**Issue by Yuuichi89** [DefectDojo/django-DefectDojo#2999]
**Bug description**
Authorized User who has the right to add Engagements can add Engagements to all Products (and therefor see the names of all Products) even those he is not authorized.

**Steps to reproduce**
1. On the settings.py file set DD_AUTHORIZED_USERS_ALLOW_STAFF,
DD_AUTHORIZED_USERS_ALLOW_CHANGE and
DD_AUTHORIZED_USERS_ALLOW_DELETE, to true
2. Log on as a User who only has the Active Permission
3. Click on a product he is an Authorized User of
4. Click on `Engagement `-> `Add new Engagement`
5. Fill out the required boxes
6. On the Product select Box choose a Product on which he is not an authorized User.
7. Click on `Done`
8. A 403 Error message is shown but the Engagement is added to the selected Product

**Expected behavior**
The active User only gets to select Products he is authorized. All other Products should not be displayed.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 20.04
 - DefectDojo Commit Message: [2020-10-02 18:19:00 +0200] a89d7df: renovate: only rebase when conflicted [ (HEAD -> master, origin/master, origin/HEAD)]

**Comment by valentijnscholten** [comment]
hmm this is weird because apart from the dropdown that should only contain authorized products, the engagement also should not be created for non-authorized products.

**Comment by valentijnscholten** [comment]
Can you try the PR mentioned above?

**Comment by Yuuichi89** [comment]
Nice! This seems to fix the issue thank you 👍

**Comment by valentijnscholten** [comment]
reopening as it is not merged yet

**Comment by valentijnscholten** [comment]
will be in the next release.
