### ISSUE TITLE
Add mitigated column in engagement view

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#3001]
To add clarity at a glance, add a mitigated column which shows the number of mitigated findings (whichever sort).
Currently, open and duplicate are shown. But maybe out of these 100 findings, all are mitigated and you need to actually open the engagement to find out.

**Comment by valentijnscholten** [comment]
I think this again boils down to definition of `open`. I think open should mean something like  "`active` and not `mitigated`"

**Comment by valentijnscholten** [comment]
fixed by #3029 @madchap ?

**Comment by madchap** [comment]
Yes
