### ISSUE TITLE
Un-marking findings active shows them as "Mitigated", but do not set "is_Mitigated"

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#3026]
**Bug description**
When one unmarks an Active finding, it goes to "Inactive, Mitigated". 
However, the `is_Mitigated` is not set to `True`.

However, in bulk edit for example, marking findings as "Mitigated" is possible and sets that field.

This results in discrepancies.

**Comment by valentijnscholten** [comment]
I've seen this descrepency also. Thought there was an issue for it, but couldn't find it.
