### ISSUE TITLE
Bulk edit menu does not show on multiple single checkbox selection 

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#3027]
**Bug description**
1st part of the video: If you select multiple findings via the severity of a finding, resulting in multiple checkbox to be set, the bulk edit menu shows up.
2nd part of the video: If you select multiple findings manually, the bulk edit box never shows up.

**Steps to reproduce**

![simplescreenrecorder](https://user-images.githubusercontent.com/5468769/96332644-9572c480-1065-11eb-9880-698094611e5a.gif)

**Expected behavior**
Selecting multiple checkboxs manually should show the bulk edit box.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
Latest `dev`

**Comment by valentijnscholten** [comment]
What page are you on and what does the javascript console say? For me this works. What commit are you on?

**Comment by madchap** [comment]
`1c431de0feaa95e79e7afb512b4313160184d829`

http://localhost:8080/test/3

nothing much?

![image](https://user-images.githubusercontent.com/5468769/96352450-7f93ec80-10c3-11eb-9f1d-8f25fa6ab8ff.png)

**Comment by valentijnscholten** [comment]
ah, the view_test page is the only view that does not use the findings_list.html. let me check
