### ISSUE TITLE
Add ceiling limit at which to automatically delete CI/CD engagements

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#3033]
**Is your feature request related to a problem? Please describe**
With aggressive CI/CD imports, one can start to have 1000s of engagements per product. Most findings within them may have status "Inactive, Duplicate". These engagements have no value in themselves, if no one looks at them for some time and only make the database grow for nothing, impairing performance and eventually, availability.

It would be useful to add a ceiling at which the oldest engagements get delete, provided they meet certain critieria, maybe:

Target is to only have `x` number of engagement at any time. To achieve, engagements subject to deletion would have to meet the following criteria:
- engagement is older than `n` months
- engagement does not contain notes -- or notes of certain types
- engagement contains only duplicates findings, no original.

An opt-in notification could be made to administrator or product leads when things get deleted.

**Comment by valentijnscholten** [comment]
Why not use reimport so you have just 1 engagement per branch?
