### ISSUE TITLE
Several errors importing dumped data

### ISSUE THREAD

**Issue by LeonardoNve** [DefectDojo/django-DefectDojo#3060]
**Bug description**
After a dumpdata on a DD v5.4 I tried to loaddata the result JSON file. First I getted this:
`json.decoder.JSONDecodeError: Invalid control character at: line 1230684 column 6153 (char 74261006)`
This was because inside the file there were \r\d charancters in some JSON descriptions fields (is this because a bug in dumpdata function?). 

I solved that with:
```
sed -i 's/\r//g' dumpdata.json
sed -i ':a;N;$!ba;s/\n//g' dumpdata.json

```
But now I get the following error:
`json.decoder.JSONDecodeError: Invalid \uXXXX escape: line 128749 column 40 (char 6667587)`
Analizing that line:
```
# sed '128749!d' dumpdata.json
        "object_repr": "Ausencia e pol\u00etica e contrase\u00f1as robustas",
```
I see the error is at \u00e unicode character which is í in Spanish

To continue I modified the dumpdata file changing all \u00e strings to i (bad written in Spanish but...), I did it witd sed:
`sed -i 's/\\u00e/i/g' dumpdata.json`

No I tried to loaddata again with the following error now:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 155, in get_app_config
    return self.app_configs[app_label]
KeyError: 'defectDojo_engagement_survey'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/serializers/python.py", line 154, in _get_model
    return apps.get_model(model_identifier)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 205, in get_model
    app_config = self.get_app_config(app_label)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 162, in get_app_config
    raise LookupError(message)
LookupError: No installed app with label 'defectDojo_engagement_survey'.

```

Difficult to follow with the task from here.

**Expected behavior**
Load backup data on an actualized DD 8.0 deployment.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Linux dojo 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 20.04)
 - DefectDojo Commit Message: [2020-10-02 18:19:00 +0200] a89d7df4: renovate: only rebase when conflicted [ (HEAD -> master, origin/master, origin/HEAD)]

**Screenshots**
![image](https://user-images.githubusercontent.com/6109592/96712783-ed7c3480-139f-11eb-9099-752e08439adc.png)

![image](https://user-images.githubusercontent.com/6109592/96712856-0be23000-13a0-11eb-96b9-95e90dab6244.png)

![image](https://user-images.githubusercontent.com/6109592/96716966-13a4d300-13a6-11eb-9b55-d76e8abf07e5.png)

**Comment by valentijnscholten** [comment]
loading and dumping data is a built in function of the django framework. we have no control over it.
dumping from 1.5.4 and loading in 1.8.0 is not supported. you need to upgrade to 1.8.0 first and then dump -> load.
the message about engagementsurvey is because of changes in settings.dist.py that you may need to apply to your local copy of that file or settings.py

**Comment by valentijnscholten** [comment]
BTW it's much easier to use `mysqldump` to dump the data and load it in a new database. In that scenario you can dump from 1.5.4 and load into 1.8.0 and the migrations will upgrade the database format.

**Comment by LeonardoNve** [comment]
> BTW it's much easier to use `mysqldump` to dump the data and load it in a new database. In that scenario you can dump from 1.5.4 and load into 1.8.0 and the migrations will upgrade the database format.

How can the migrations upgrade the database format in an 1.8.0 version?

**Comment by devGregA** [comment]
Hi @LeonardoNve like @valentijnscholten mentioned dumpdata is a django function and not a dojo function, so there isn't anything we can do here. You shouldn't have to mess with migrations, as we provide the files, but how it works is a migration is created that diffs the DB and figures out what is missing / added. We then add code to handle data transfers or manipulations (when needed).
