### ISSUE TITLE
Findings count not showing up in tests list

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#3061]
**Bug description**
![image](https://user-images.githubusercontent.com/5468769/96740735-663fb880-13c1-11eb-8ac3-b83ff561592f.png)

Same for the list of tests that hold the original findings:
![image](https://user-images.githubusercontent.com/5468769/96740901-925b3980-13c1-11eb-8f9c-b3ccef1e38b9.png)

Latest dev or almost.

**Comment by madchap** [comment]
But sometimes it does? 

![image](https://user-images.githubusercontent.com/5468769/96853118-43adae00-145a-11eb-9edc-958685d1ef02.png)

**Comment by valentijnscholten** [comment]
I think it only counts active findings or active and verified.
