### ISSUE TITLE
endpoint status filter values 

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#3090]
When you go to open findings or all findings and you open the filter section to do some filtering, the endpoint_status field looks like this:

![image](https://user-images.githubusercontent.com/4426050/97106826-0fd5c100-16c4-11eb-88c1-79cea4a4c9dc.png)

I'm not 100% sure about the intention of this filter field, but I think it would be more useful if you could filter on the endpoint status? so active/mitigated/false_p/out_of_scope, similar to filtering on finding status?

**Comment by valentijnscholten** [comment]
wdyt @Maffooch

**Comment by Maffooch** [comment]
Think it's in the form because it was not added to the `exclude` field. It wouldn't be difficult to be able to filter on endpoint statuses though.
