### ISSUE TITLE
OCI runtime create failed while initiating docker-compose command

### ISSUE THREAD

**Issue by ParthibanSG** [DefectDojo/django-DefectDojo#3101]
**Bug description**
DefectDojo application is not running

**Steps to reproduce**
I downloaded the latest defectdojo code and modified below files since there is another application utilizing 8080 and 8443 port

Changed image names for pulling from our corporate docker artifactory network
Changed image names in Dockerfiles (nginx and django) 
Included Proxy step in Dockerfiles to allow communication for downloading metadata
Change NGINX port from 8080 to 8081 and 8443 to 9443 in docker-compose.yml, nginx/nginx.conf, nginx/nginx_TLS.conf and docker-compose.override.https.yml

Post above steps, I did a docker-compose build and it was successfull however when I try to bring up the application using docker-compose up command, I could see below errors for four containers

INFO[2020-10-27T09:25:52.720067978+01:00] shim reaped                                   id=853e72d26b634e728f39e9a685742bf17521951afe17274b679c5e94bff77c3e
ERRO[2020-10-27T09:25:52.740308107+01:00] stream copy error: reading from a closed fifo
ERRO[2020-10-27T09:25:52.740378224+01:00] stream copy error: reading from a closed fifo
ERRO[2020-10-27T09:25:52.792970170+01:00] 853e72d26b634e728f39e9a685742bf17521951afe17274b679c5e94bff77c3e cleanup: failed to delete container from containerd: no such container
Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/wait-for-it.sh\": permission denied": unknown

**Expected behavior**
DefectDojo should have been up and running under a different port. Port have been reconfigured from our end in nginx location as well as in the Dockerfile

**Deployment method** *(select with an `X`)*

Docker-Compose method is being used and I had introduce ENV Proxy step for downloading the metadata for the images

**Environment information**

I am working on a Linux environment (RHEL 7)

**Console logs** (optional)

INFO[2020-10-27T09:25:52.720067978+01:00] shim reaped                                   id=853e72d26b634e728f39e9a685742bf17521951afe17274b679c5e94bff77c3e
ERRO[2020-10-27T09:25:52.740308107+01:00] stream copy error: reading from a closed fifo
ERRO[2020-10-27T09:25:52.740378224+01:00] stream copy error: reading from a closed fifo
ERRO[2020-10-27T09:25:52.792970170+01:00] 853e72d26b634e728f39e9a685742bf17521951afe17274b679c5e94bff77c3e cleanup: failed to delete container from containerd: no such container
Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/wait-for-it.sh\": permission denied": unknown

It would be good if we can find a solution to run DefectDojo apart from default ports

**Comment by valentijnscholten** [comment]
Please provide the information requeted in the template such as which version/brach you are running.

**Comment by ParthibanSG** [comment]
@valentijnscholten 

I cloned the master branch and started performing the updates I mentioned above to bring up DefectDojo on a different port

**Comment by valentijnscholten** [comment]
without the exact version as requested per the template we can't help you.
using custom ports was fixed in https://github.com/DefectDojo/django-DefectDojo/pull/3059 which was released to master yesterday in 1.9.0.

**Comment by jay3-3** [comment]
It happens the same to me. But I only copy the same folder with the full dd with another name. I explain myself:

I have folder django-DefectDojo and I do docker-compose build and up. It is working perfectly.
I close everything, then I copy the folder and I change the name to "anotherDD" but the docker-compose up I get the same error as you. 

I think this is docker related because I change nothing on DD.
