### ISSUE TITLE
POST /findings redirect you to a GET request /findings/

### ISSUE THREAD

**Issue by vira-vira** [DefectDojo/django-DefectDojo#3120]
**Bug description**
If you create a POST request with the method /findings (without the character "/" at the end) It redirects you to a GET request /findings/
**Steps to reproduce**
1. If you have defect dojo in your localhost environment, run a POST request with Postman to the following url http://127.0.0.1:8080/api/v2/findings (without the "/" at the end) and send the request
2. The response is a GET request
![Screen Shot 2020-10-28 at 15 35 06](https://user-images.githubusercontent.com/32620981/97482992-a5c45280-1935-11eb-8b4e-946cfe61ca4b.png)

**Comment by valentijnscholten** [comment]
This is a feature of Django Rest Framework. We could change the default settings for that, but unsure about the impact and what it would mean to existing scripts. Why is this an issue for you?

**Comment by vira-vira** [comment]
That is not the expected behavior I would expect if I missed a "/" in the request. If you are not going to fix, at least is going to be good to have this well documented.
Regards,

**Comment by valentijnscholten** [comment]
and what _is_ the expected behaviour.

**Comment by vini-ppro** [comment]
I have just spent ~1 hour of my day due to this issue :/
