### ISSUE TITLE
There are more mandatory fields required than showed in Swagger

### ISSUE THREAD

**Issue by vira-vira** [DefectDojo/django-DefectDojo#3121]
**Attempted to**
Create a new issue in Defect Dojo through API v2 using the minimal parameters marked as mandatory in the documentation. We use a POST Request with the endpoint /findings/
Documentation:
 http://127.0.0.1:8080/api/v2/doc/
Screenshots of Swagger:

<img width="1266" alt="Screen Shot 2020-10-29 at 09 16 27" src="https://user-images.githubusercontent.com/32620981/97572902-bcb38500-19c7-11eb-9161-8788fdd8e9a2.png">
<img width="1166" alt="Screen Shot 2020-10-29 at 09 16 49" src="https://user-images.githubusercontent.com/32620981/97572910-c0470c00-19c7-11eb-86b7-0ac0151bd3bb.png">
<img width="1171" alt="Screen Shot 2020-10-29 at 09 17 08" src="https://user-images.githubusercontent.com/32620981/97572913-c1783900-19c7-11eb-8e54-73ca8b72e198.png">
<img width="1185" alt="Screen Shot 2020-10-29 at 09 17 25" src="https://user-images.githubusercontent.com/32620981/97572919-c210cf80-19c7-11eb-98f8-a4390a168d30.png">

In Swagger, it shows that the minimum mandatory fields required for a POST Request in /findings are:
- test
- found_by
- title
- severity
- description
- mitigation
- impact

**The expected behavior was**
A 201 Created with a JSON response as stated in the docs.
**We Got**
<h1> 500 Error </h1>.
In the server logs there is this traceback:
![image](https://user-images.githubusercontent.com/32620981/97574556-2b91dd80-19ca-11eb-9b0a-33c3c27bac49.png)

**Workaround**
We created POST request with the following parameters:

- test
- found_by
- title
- severity
- description
- mitigation
- impact
- numerical_severity
- duplicate
- verified
- false_p

**Comment by valentijnscholten** [comment]
@vidhan13j07 could you check again in `dev`? We have fixed lots of schema inconsistencies and added an OpenAPI v3 schema as well.

**Comment by devGregA** [comment]
@valentijnscholten  I can have this validated.

**Comment by XiChen-Tibco** [comment]
@vira-vira Hi, could you give us more details about how to reproduce this error?

**Comment by valentijnscholten** [comment]
merged into dev / 2.2.0

**Comment by valentijnscholten** [comment]
The fix turned out to be incomplete, see for example https://github.com/DefectDojo/django-DefectDojo/issues/5019

**Comment by sokayvich-git** [comment]
In /import-scan/, environment variable is not marked as required in swagger, but results in 500 errors when using the netsparker import test_type without it.
