### ISSUE TITLE
Endpoint_Status matching query does not exist.

### ISSUE THREAD

**Issue by owaspdpn** [DefectDojo/django-DefectDojo#3123]
**Bug description**
Error while creating finding with Endpoints "Endpoint_Status matching query does not exist."

**Steps to reproduce**
1) Go to a product
2) add engagement  with all the require basic data
3) add a test with  "pen test" as  test type, all the require basic data
4) add a finding
5) In finding go to the endpoint and click on the + icon and a popup would open.
6) In the popup give the URL and click on submit. The popup window closes and now click on Finished.
The finding return in 500 error message also the test seems to be broken after adding the finding

**Expected behavior**
Finding should be saved without any error and the test should be accessible after adding the finding.

**Deployment method** *(select with an `X`)*
- [ X] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - DefectDojo V 1.9.0

**Console logs** (optional)
Request Method:	GET
Request URL:	https://defectdojo/test/1
Django Version:	2.2.16
Exception Type:	DoesNotExist
Exception Value:	
Endpoint_Status matching query does not exist.
Exception Location:	/usr/local/lib/python3.6/site-packages/django/db/models/query.py in get, line 408
Python Executable:	/usr/local/bin/uwsgi
Python Version:	3.6.12
Python Path:	
['/app',
 '/usr/local/lib/python3.6/site-packages/git/ext/gitdb',
 '.',
 '',
 '/usr/local/lib/python36.zip',
 '/usr/local/lib/python3.6',
 '/usr/local/lib/python3.6/lib-dynload',
 '/usr/local/lib/python3.6/site-packages',
 '/usr/local/lib/python3.6/site-packages/gitdb/ext/smmap']
Server time:	Wed, 28 Oct 2020 11:07:32 +0000

**Additional context** (optional)

**Comment by madchap** [comment]
I still have the issue, albeit when viewing a test, like `https://defectdojo.mydomain.com/test/6117`
