### ISSUE TITLE
Defect Dojo can't connect to JIRA - HTTP 500/ Issue not created in JIRA

### ISSUE THREAD

**Issue by nbublikov** [DefectDojo/django-DefectDojo#3130]
**Bug description**
I can't integrate Defect Dojo with JIRA. After filling in the configuration, the error "unable to authenticate, wrong password or ext .." but always right. Done with instruction https://defectdojo.readthedocs.io/en/latest/features.html#jira-integration

**Steps to reproduce**
![image](https://user-images.githubusercontent.com/68223804/97690911-b4824500-1aae-11eb-9868-2d9c93a60a0b.png)

when i click 'submit' in the UI i get this error in the logs
<img width="768" alt="Screenshot_1" src="https://user-images.githubusercontent.com/68223804/97693240-ecd75280-1ab1-11eb-9c98-463cdc3f40cd.png">

**Expected behavior**
I expect that the configuration with findinds will be added, marked active and verified will be launched in JIRA

**Deployment method** *(select with an `X`)*
- [X] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 18.04

If additional information is required, please write

**Comment by madchap** [comment]
It seems you're integrating with JIRA servicedesk and not JIRA software. It's possible that the API is not the same, hence why it'd be failing.

The JIRA integration is only tested on JIRA software.

**Comment by nbublikov** [comment]
now a Jira Software + Jira SD instance, i.e. on one instance and then and then.

Could this be a problem?

**Comment by madchap** [comment]
It's not because they run on the same instance that the products share the same APIs.

**Comment by nbublikov** [comment]
We sorted it out!!! On the JIRA side there were problems with the JIRA account rights

But there another question. I have project with finding and i want to push this finding in JIRA
![image](https://user-images.githubusercontent.com/68223804/97698758-13998700-1aba-11eb-8810-d932823482bd.png)


I tap this
![image](https://user-images.githubusercontent.com/68223804/97698788-214f0c80-1aba-11eb-8b67-b4e86f678cb1.png)


Then
![image](https://user-images.githubusercontent.com/68223804/97698812-2ad87480-1aba-11eb-9e07-1e2285b5c77a.png)

Then i tap
![image](https://user-images.githubusercontent.com/68223804/97698854-43e12580-1aba-11eb-8ceb-d48dc773a1b3.png)

Then 
![image](https://user-images.githubusercontent.com/68223804/97698893-55c2c880-1aba-11eb-87ae-33f838e9464d.png)

But issue in JIRA was not created, whats wrong in this way?
![image](https://user-images.githubusercontent.com/68223804/97698957-70953d00-1aba-11eb-95c6-24d7ef951d6c.png)

**Comment by nbublikov** [comment]
Nothing in logs, after successfull add JIRA configuration
![image](https://user-images.githubusercontent.com/68223804/97699054-9884a080-1aba-11eb-9c58-e1c624814a72.png)

**Comment by nbublikov** [comment]
or example with active, verified finding, but no issue in JIRA was created 
![image](https://user-images.githubusercontent.com/68223804/97699406-1e085080-1abb-11eb-8026-e154a7ec8cd2.png)

**Comment by valentijnscholten** [comment]
1: What version / branch / commit are you running
2: defect review has nothing to do with JIRA. To push to jira go to edit finding and on the bottom check push to jira checkbox and press save/submit/done

**Comment by nbublikov** [comment]
1. Tell me please, do you mean which version of defect dojo I'm using? Defect Dojo 1.7.1 
2. Reproduce step
![image](https://user-images.githubusercontent.com/68223804/97700904-9ec84c00-1abd-11eb-9b60-c69466cb1f18.png)

![image](https://user-images.githubusercontent.com/68223804/97700961-b7386680-1abd-11eb-98b4-1def33384064.png)
![image](https://user-images.githubusercontent.com/68223804/97701025-d3d49e80-1abd-11eb-9473-dea550916ada.png)
![image](https://user-images.githubusercontent.com/68223804/97701043-ddf69d00-1abd-11eb-8b60-35c5ba863cdb.png)

After finished
![image](https://user-images.githubusercontent.com/68223804/97701320-4776ab80-1abe-11eb-8689-fc511453a336.png)
![image](https://user-images.githubusercontent.com/68223804/97701423-712fd280-1abe-11eb-9766-ebb797881533.png)

Nothing in logs
![image](https://user-images.githubusercontent.com/68223804/97701456-8278df00-1abe-11eb-8779-4b4c9c7d10a3.png)

**Comment by nbublikov** [comment]
In settings it connect to JIRA
![image](https://user-images.githubusercontent.com/68223804/97701529-a0deda80-1abe-11eb-9c41-9cdbe9e44e54.png)
![image](https://user-images.githubusercontent.com/68223804/97701561-ac320600-1abe-11eb-8f88-84c9f7b7267f.png)

**Comment by valentijnscholten** [comment]
Please update to 1.9.0 or latest dev

**Comment by nbublikov** [comment]
Thank you! Either today or on Monday we will update and write how it goes

**Comment by nbublikov** [comment]
ipdate to 1.9.0, something goes on

![image](https://user-images.githubusercontent.com/68223804/97708387-c9b89d00-1ac9-11eb-870e-d8f56b586dbf.png)
![image](https://user-images.githubusercontent.com/68223804/97708424-d6d58c00-1ac9-11eb-9a47-e81d3ca02389.png)

**Comment by valentijnscholten** [comment]
If you click see all alerts you can see the error. I doubt the error in the logs is from jira integration as it doesn't use oauth but basic authentication to connect to JIRA.

**Comment by nbublikov** [comment]
I will try to make finding Active and Verified
![image](https://user-images.githubusercontent.com/68223804/97709298-26688780-1acb-11eb-8e7a-d553ec1d886c.png)

**Comment by valentijnscholten** [comment]
yeah, jira integration runs in the background so it's not always clear.

**Comment by nbublikov** [comment]
Ok!
1. I select finding 
![image](https://user-images.githubusercontent.com/68223804/97710253-91668e00-1acc-11eb-98e4-07a6ea95fa99.png)

2. checkbox at verified, active
![image](https://user-images.githubusercontent.com/68223804/97710364-bc50e200-1acc-11eb-877e-fa3fa84ac266.png)

3. 
![image](https://user-images.githubusercontent.com/68223804/97710455-d38fcf80-1acc-11eb-95e7-2688b161475b.png)

4. This finding 
![image](https://user-images.githubusercontent.com/68223804/97710548-ef937100-1acc-11eb-8e2d-06f8c709320a.png)

5. Select this finding and click there 
![image](https://user-images.githubusercontent.com/68223804/97710629-0c2fa900-1acd-11eb-9db5-858d04f18bb9.png)

6. This error in logs
![image](https://user-images.githubusercontent.com/68223804/97710677-1ea9e280-1acd-11eb-82f0-097cba65a6a9.png)

7. In UI error log nothing about last finding 1098
![image](https://user-images.githubusercontent.com/68223804/97711414-23bb6180-1ace-11eb-9f14-147c931b0ca0.png)


In JIRA in project SECURE, no new issues


Maybe somethins wrong, maybe need restart dojo?

**Comment by valentijnscholten** [comment]
check the uwsgi and celery logs. just this one logline about oauth2 doens't really provide any insight.

**Comment by nbublikov** [comment]
![image](https://user-images.githubusercontent.com/68223804/97713201-92012380-1ad0-11eb-9a89-26aece895da8.png)


not very informative, right? (

**Comment by nbublikov** [comment]
Perhaps only Oauth2.0 is configured in JIRA and basic is disabled, I will clarify

**Comment by nbublikov** [comment]
Good day! Clarified.

1.OAuth2.0 is used in JIRA
2. Basic auth is also used in JIRA and it is not disabled

Any ideas?

**Comment by nbublikov** [comment]
I found similar issue, but it non-informative(
https://github.com/micahhausler/k8s-oidc-helper/issues/23

**Comment by nbublikov** [comment]
it's maybe similar issue?
https://github.com/DefectDojo/django-DefectDojo/issues/1487

**Comment by nbublikov** [comment]
I also looked at this script, I don't see any mention of OAuth.2.0, hmmm
https://github.com/DefectDojo/django-DefectDojo/blob/9e850dc26fcbed7b33669d8dcb9c5ef843e6271d/dojo/jira_link/views.py#L79

I do not understand the reason for the error

**Comment by nbublikov** [comment]
Here's what I found. 

1. When the defectdojo uchetka knocks on the jiru - all the rules (Authorization passed).
2. When sending a webhook from jira - 403 error

httpclient-callbacks: thread-1627 WARN anonymous [cawebhooks.plugin.PublishTaskFactoryImpl $ PublishTaskImpl]

Client error - 403 when posting to webhook at https: //defectdojo.trarara.co/webhook/ '

**Comment by nbublikov** [comment]
I tried curl from the server jira address above - <h1> 403 </h1>
    <hr />
    <h2>
        You don't have permission to do that. Contact your administrator for additional accesss.
    </h2>

**Comment by nbublikov** [comment]
@valentijnscholten

**Comment by nbublikov** [comment]
I think it's on jira side https://confluence.atlassian.com/jirakb/webhook-fails-with-http-403-forbidden-989759150.html

**Comment by nbublikov** [comment]
Hi! I think we found error, but what is the best thing to do with it? Can this be the case in 1.9.1 too?
[log.txt](https://github.com/DefectDojo/django-DefectDojo/files/5500224/log.txt)

**Comment by valentijnscholten** [comment]
What kind of project is it? next gen projects can give this error.
Or are you saying it starts working if the jira account has admin rights?

**Comment by nbublikov** [comment]
Hi! 
1. attach 2 screenshots, with errors, when JIRA service account with and witount global admin rights, according https://github.com/DefectDojo/django-DefectDojo/issues/3180#issu
<img width="727" alt="with global admin rights" src="https://user-images.githubusercontent.com/68223804/98540132-81099c80-229e-11eb-82d1-997a922e04d0.png">
![without global admib rights](https://user-images.githubusercontent.com/68223804/98540135-823ac980-229e-11eb-98ac-fbeb006c51ce.jpg)

ecomment-723302578

**Comment by nbublikov** [comment]
![image](https://user-images.githubusercontent.com/68223804/98545508-a69aa400-22a6-11eb-98df-e48ac4954fd6.png)

The logs showed that he was trying to create a security task in the secure project. There is such a project, but there is no task type.

I am trying to transfer from Security to Task, I get an error,

I already saw that you are preparing a fix, we will update and I will try to do everything and write

**Comment by nbublikov** [comment]
Latest status:
1. I see this error
[log JIRA-DD 1.9.2.txt](https://github.com/DefectDojo/django-DefectDojo/files/5510847/log.JIRA-DD.1.9.2.txt)

2. Question: Should JIRA have previously created the necessary issue types, for example: low, medium, high, etc ...?

**Comment by valentijnscholten** [comment]
No. You need to configure the correct values in DD that are existing in your JIRA instance.

**Comment by nbublikov** [comment]
Should I somehow modify these types in JIRA?
![image](https://user-images.githubusercontent.com/68223804/98554124-6bea3900-22b1-11eb-9278-cc42087fec52.png)

**Comment by nbublikov** [comment]
Question: We have status id and category id
What id i should paste here? 

![image](https://user-images.githubusercontent.com/68223804/98555595-2dee1480-22b3-11eb-95f3-055d27037f6c.png)

**Comment by valentijnscholten** [comment]
Better come to slack for support: https://github.com/DefectDojo/django-DefectDojo#getting-involved

**Comment by nbublikov** [comment]
It was about the license. It was for Jira SD but not for Jira Software)
