### ISSUE TITLE
DefectDojo cannot parse imported MobSF Scan

### ISSUE THREAD

**Issue by jayala-29** [DefectDojo/django-DefectDojo#3134]
**Bug description**
DefectDojo is having issues parsing a MobSF scan when trying to import its JSON file into an Engagement. This is occurring after the latest MobSF update (version 3.1.7)

**Steps to reproduce**
1. Grab MobSF scan as a JSON file
2. Go to an Engagement and click Import Scan Results
3. Scroll down to Choose report file and upload MobSF scan

**Expected behavior**
A successful scan import, DefectDojo parses the scan and properly displays findings.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: macOS Catalina 10.15.4

**Sample scan file** 
[mobsf-scan.zip](https://github.com/DefectDojo/django-DefectDojo/files/5466408/mobsf-scan.zip)

**Screenshots**
<img width="1574" alt="Screen Shot 2020-10-29 at 6 26 12 PM" src="https://user-images.githubusercontent.com/18255250/97731608-96a6e700-1a92-11eb-924a-8eca79426404.png">

**Comment by valentijnscholten** [comment]
can you provide the error/tracback from the log please?

**Comment by jayala-29** [comment]
logs from running `docker logs --since=2m --details django-defectdojo_celeryworker_1`

upload took place at the last two timestamps shown below:

[2020-11-02 16:52:00,964: INFO/MainProcess] Received task: dojo.tasks.async_dupe_delete[99045c38-b9a3-40ce-b8cc-52340aed3fc4]  
 [2020-11-02 16:52:00,971: INFO/MainProcess] Task dojo.tasks.async_dupe_delete[99045c38-b9a3-40ce-b8cc-52340aed3fc4] succeeded in 0.006090350914746523s: None
 [2020-11-02 16:53:01,014: INFO/MainProcess] Received task: dojo.tasks.async_dupe_delete[ae123cc4-ed07-4a1a-a9c9-802ca8963cdd]  
 [2020-11-02 16:53:01,021: INFO/MainProcess] Task dojo.tasks.async_dupe_delete[ae123cc4-ed07-4a1a-a9c9-802ca8963cdd] succeeded in 0.005998729029670358s: None

**Comment by valentijnscholten** [comment]
we need logs from uwsgi container

**Comment by jayala-29** [comment]
I ran `docker logs --since=2m django-defectdojo_uwsgi_1` but there was no output, any other suggestions?

**Comment by jayala-29** [comment]
I tried it again and got some output, here it is:

```
'title'
 Traceback (most recent call last):
   File "./dojo/engagement/views.py", line 624, in import_scan_results
     parser = import_parser_factory(file, t, active, verified)
   File "./dojo/tools/factory.py", line 195, in import_parser_factory
     parser = MobSFParser(file, test)
   File "./dojo/tools/mobsf/parser.py", line 124, in __init__
     "title": details["title"],
 KeyError: 'title'
 Error in parser: 'title'
```

**Comment by Ivanello** [comment]
the same issue: 
version 1.10.0
Deployment method (select with an X)
 Kubernetes
x Docker
 setup.bash / legacy-setup.bash
Operating System: Ubuntu 20
[report.json.zip](https://github.com/DefectDojo/django-DefectDojo/files/5604639/report.json.zip)

log:
```
uwsgi_1         | [26/Nov/2020 18:28:24] ERROR [dojo:635] 'title'
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "./dojo/engagement/views.py", line 628, in import_scan_results
uwsgi_1         |     parser = import_parser_factory(file, t, active, verified)
uwsgi_1         |   File "./dojo/tools/factory.py", line 198, in import_parser_factory
uwsgi_1         |     parser = MobSFParser(file, test)
uwsgi_1         |   File "./dojo/tools/mobsf/parser.py", line 124, in __init__
uwsgi_1         |     "title": details["title"],
uwsgi_1         | KeyError: 'title'
uwsgi_1         | [26/Nov/2020 18:28:24] ERROR [dojo:636] Error in parser: 'title'
```

**Comment by damiencarol** [comment]
Same pb here. I think the format of MobSF had changed a little bit.
It's the binary analysis part of the report that is broken.
I'm working on a patch to fix that. @Ivanello @jayala-29

**Comment by valentijnscholten** [comment]
@jayala-29 is this specific error now resolved for you?

**Comment by jayala-29** [comment]
@valentijnscholten no, the parsing error is still showing up

**Comment by Ivanello** [comment]
> @jayala-29 is this specific error now resolved for you (in `dev`)?

hello, sorry cant understand how to install **dev** version of Defectdojo?

**Comment by whitespots** [comment]
Still don't work in latest DefectDojo version with any MobSF version. Please, support at least one, maybe old version of MobSF.

**Comment by damiencarol** [comment]
@whitespots please help to describe and make issues more clear. if there is new bugs with new versions of MobSF just create a new issue with details. I will work on it but it's difficult to follow this kind of "don't work" feedback.
We have an opportunity. Next week we will release our new `0.14.0` release. So if you're able to point to the pb or share with us some reports that break the import, we can fix it for the next release and have it ready before next Tuesday.

**Comment by whitespots** [comment]
@damiencarol Thank you for your response! We will describe this issue as soon as possible.
