### ISSUE TITLE
add documentation for troubleshooting (enable DEBUG, command to get logs, etc)

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#3143]
Sometimes we get people who experience a bug, but are not fully equiped on how to debug/report it.
We should document maybe some extra stuff:
- How to enable DEBUG mode for Django
- How to get logs in docker-compose / k8s setup (and which container)
- How to enable DEBUG logging
- How to add extra logging statements

**Comment by herambchaudhari4121** [comment]
What should you include in a bug report? | Good (precise) example | Bad (imprecise)
-- | -- | --
Indicate whether you can reproduce the bug at will, occasionally, or not at all. | I can reproduce by following these steps: |  
Describe your method of interacting with Firefox in addition to the intent of each step. | 1. Start Firefox by clicking on the desktop icon2. Press Cmd+N (or Ctrl+N for Windows users) to open a new browser window3. Paste https://mail.google.com/ in the address bar and press Enter | Open Gmail in another window
After your steps, precisely describe the observed (actual) result and the expected result. Clearly separate facts (observations) from speculations. | Expected results: My Inbox displays correctly.Actual results: My inbox displays the message 'Your browser does not support cookies (error -91)'. | "It doesn't work""Page displays incorrectly"

**Comment by herambchaudhari4121** [comment]
HOPE YOU MAY GOT  IT🥰🥰😊😊🥰🥰🔥🔥💖💖🔥🔥🌟🌟🎉🎉👋
