### ISSUE TITLE
Missing or incomplete links in Slack notifications

### ISSUE THREAD

**Issue by marcosValle** [DefectDojo/django-DefectDojo#3144]
**Bug description**
Links to details in slack notifications are empty or incomplete.

**Steps to reproduce**
1. Set up Slack integration
2. Upload a new test, such as a Bandit output
3. When receiving the results in Slack, the url is incomplete

<img width="273" alt="Screen Shot 1399-08-12 at 19 11 46" src="https://user-images.githubusercontent.com/5929526/97903933-11e0f500-1d40-11eb-9352-32871a6f7f4c.png">

A similar issue happens when SLAs are due. In this case, no link at all is shown. I suspect the same goes with other reports too.

<img width="475" alt="Screen Shot 1399-08-12 at 19 12 00" src="https://user-images.githubusercontent.com/5929526/97903959-1c9b8a00-1d40-11eb-81e3-a037ed89413b.png">

**Expected behavior**
The URLs in Slack notifications should be complete, including the domain.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: MacOS Catalina 10.15.7

**Comment by madchap** [comment]
Seems `url` is used instead of `full_url` in templates.

**Comment by valentijnscholten** [comment]
@marcosValle the full_url is relatively new and not used everywhere yet. Are you able to take a stab at creating a PR?

**Comment by marcosValle** [comment]
Sure, let me give it a try.

**Comment by valentijnscholten** [comment]
fixed by #3538
