### ISSUE TITLE
Qualys XML import bug

### ISSUE THREAD

**Issue by jagusztinl** [DefectDojo/django-DefectDojo#3153]
**Bug description**
The attached file is a Qualys XML report. The import is successful, but the result does not shown in DD.

**Steps to reproduce**
1. Import the attached file to DD
2. Check the result in DD (missing)

**Expected behavior**
Vulnerability records/findings should shown in DD

**Deployment method** *(select with an `X`)*
- [x ] Docker

**Environment information**
 - Operating System: RHEL 7.8
 - DefectDojo Commit Message: 8.1

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.
Attached

[Scan_Report_kbc-lt_20201102 (1).zip](https://github.com/DefectDojo/django-DefectDojo/files/5479775/Scan_Report_kbc-lt_20201102.1.zip)

**Comment by iwalton3** [comment]
I can confirm that #3150 fixes this:
![image](https://user-images.githubusercontent.com/8078788/98415846-047f7f80-204c-11eb-9b73-5cc7c6bca614.png)

**Comment by jagusztinl** [comment]
We also confirm that after patching the current version with #3153, the Qualys report loading works.

In what version will be merged/released to production?

**Comment by ZsanettMagyar** [comment]
@jagusztinl  https://github.com/DefectDojo/django-DefectDojo/pull/3150#issuecomment-747395550

**Comment by damiencarol** [comment]
Part of `1.10.x` release
