### ISSUE TITLE
How to use URL prefix?

### ISSUE THREAD

**Issue by Seppl2202** [DefectDojo/django-DefectDojo#3159]
Hello,
we want to deploy DefectDojo using Docker and we want to access DefectDojo under www.domain.com/dojo.
We need to use a NGINX reverse proxy, thats why we need the URL prefix.

Is there a possibility to configure such an URL prefix?
We tried the parameters in dojo/fixtures/system_settings.json as well as settings/settings.dist.py, but we cant get it to work.

**Comment by valentijnscholten** [comment]
better post on slack, better chance to get replies: https://github.com/DefectDojo/django-DefectDojo#getting-involved

**Comment by Seppl2202** [comment]
> better post on slack, better chance to get replies: https://github.com/DefectDojo/django-DefectDojo#getting-involved

Thanks! We managed to get an own subdomain.
