### ISSUE TITLE
celery logging not working

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#3172]
Since upgrading to 1.9.0 my celery processes are no longer logging anything. It could be something weird in my setup, so I'm not saying it's a bug. But leaving it here for other people running into celery logging issues.

The only solution I have found is to comment out the celery logging bootstrap code in `dojo/celery.py`:

```
# @setup_logging.connect
# def config_loggers(*args, **kwags):
#     from logging.config import dictConfig
#     dictConfig(settings.LOGGING)
```

I tried all kinds of different things in `settings.dist.py` but none of the example online are working as long as this `@setup_logging.conntect` is present in the code.

**Comment by madchap** [comment]
@valentijnscholten did you try again after the latest changes made to settings.dist.py for celery logging? Let me know.

**Comment by valentijnscholten** [comment]
works now thanks
