### ISSUE TITLE
Different notification channels for each product

### ISSUE THREAD

**Issue by Seppl2202** [DefectDojo/django-DefectDojo#3174]
We noticed, that many of our users are using a different Teams/Slack channel for each software they develop. Currently, all notifications of DefectDojo are pushed to the same MS Teams channel (we do not use slack, but I think it is the same for Slack).
This is unfavorable, since there is a massive overload of information, because all products in DefectDojo are mixed up together in one channel.

**Describe the solution you'd like**
Each product in DefectDojo should get an own channel for MS Teams and Slack too, of course.
This channel can be configured in the products detail page (add/edit function).

**Describe alternatives you've considered**
I did not consider any alternatives, because I cannot imagine an alternative for this problem.

**Additional context**
As far as I watched the sourcecode, there is `createNotification()` in /dojo/notification/helper.py
This method is called from the UI pages, when actions are performed. My idea was: give each product an object (NotificationConfiguration, for example) which stores the different URLs and tokens for Teams/Slack notifications. This object is passed to `createNotification()` and will be used for the sending of the notification (and thus replacing the "system wide" setting of URLs/tokens for teams and slack).

However, before I start implementing and testing this in our appliance, I wanted to ask about your opinion on this topic and my approach.

**Comment by StefanFl** [comment]
I think this makes sense when you want to use notifications for a larger installation.
