### ISSUE TITLE
setup integration with Jira cloud fails

### ISSUE THREAD

**Issue by praveendvd** [DefectDojo/django-DefectDojo#3176]
Gets incorrect user name ,url or password error

**Steps to reproduce**
1) create a token from jira cloud account
2) provide url as https://<jiracloud>.net/jira
3) provide username as email address used in jira cloud
4) provide password as API token

**Expected behavior**

SHould create configuration successfully

**Deployment method** *(select with an `X`)*

- [x ] Docker

**Environment information**
 - Operating System:  CentOS Linux release 8.2.2004 (Core) 
 - DefectDojo Commit Message:[2020-10-29 16:05:41 +0100] 00cbddad: Update .travis.yml [ (HEAD -> master, origin/master, origin/HEAD)]

log:
[file.log](https://github.com/DefectDojo/django-DefectDojo/files/5494345/file.log)

Screenshots:

![image](https://user-images.githubusercontent.com/45095911/98167576-33c5ad80-1ee1-11eb-9a25-2121042531bb.png)

![image](https://user-images.githubusercontent.com/45095911/98241344-b8a4db80-1f62-11eb-9043-70c5bd34820e.png)

**Comment by valentijnscholten** [comment]
Missing information such as which version you are running, error from logs. Also check #3162. Reopen when needed (with more info).

**Comment by praveendvd** [comment]
> Missing information such as which version you are running, error from logs. Also check #3162. Reopen when needed (with more info).

how to get the log docker-compose logs ?

**Comment by valentijnscholten** [comment]
type `docker-compose logs`. If you are running 1.9.0 or 1.9.1 you're probably seeing this known issue: #3162

**Comment by praveendvd** [comment]
> type `docker-compose logs`. If you are running 1.9.0 or 1.9.1 you're probably seeing this known issue: #3162

i have added full log in the ticket , i tried docker-compose logs | grep "not defined" i didn't get anything

**Comment by valentijnscholten** [comment]
looks like a different issue then.

**Comment by valentijnscholten** [comment]
I think it might the same as I found out the code is swallowing exceptions. Could you try again with `release/1.9.2` branch?

**Comment by valentijnscholten** [comment]
sorry, I mean this branch https://github.com/valentijnscholten/django-DefectDojo/tree/jira-fixes-1.9.1

**Comment by praveendvd** [comment]
> sorry, I mean this branch https://github.com/valentijnscholten/django-DefectDojo/tree/jira-fixes-1.9.1

Sure i was trying with releas 1.9.2 , will try with this also

**Comment by valentijnscholten** [comment]
I just merged the fix into `release/1.9.2` and it works for me.

**Comment by praveendvd** [comment]
> I just merged the fix into `release/1.9.2` and it works for me.

It worked with 1.9.2

**Comment by praveendvd** [comment]
> I just merged the fix into `release/1.9.2` and it works for me.

I am not able to push any issues to Jira , it shows its success but nothing shows up in jira

**Comment by praveendvd** [comment]
[push.log](https://github.com/DefectDojo/django-DefectDojo/files/5496411/push.log)
THis is the log

**Comment by praveendvd** [comment]
I am getting bulk action success in UI but

**Comment by valentijnscholten** [comment]
click 'see all alerts'. better go to slack for support. https://github.com/DefectDojo/django-DefectDojo#getting-involved

**Comment by praveendvd** [comment]
> click 'see all alerts'. better go to slack for support. https://github.com/DefectDojo/django-DefectDojo#getting-involved

![image](https://user-images.githubusercontent.com/45095911/98286380-d17db300-1f9b-11eb-9002-4561db4d9de3.png)

**Comment by praveendvd** [comment]
Works fine with release/1.9.2 branch thanks for the help , have to configure jira in product> settings page also this is missing in documentation i guess
