### ISSUE TITLE
docs: update jira docs

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#3180]
Read the docs jira section only talks about enabling JIRA and creating a JIRA config. 
Missing step is setting up JIRA for a product.

Seems sometimes people forgot to add project key: https://github.com/DefectDojo/django-DefectDojo/issues/2747#issuecomment-702686216

**Comment by nbublikov** [comment]
and that the service account should be with global admin rights in JIRA
for example how in this case  https://github.com/DefectDojo/django-DefectDojo/issues/3130

**Comment by valentijnscholten** [comment]
@nbublikov what problem do you see when the account is not global admin?

**Comment by madchap** [comment]
The account definitely not need to be admin in jira to work properly, that's actually not recommended. It only need to proper project rights to create and update issues.
