### ISSUE TITLE
PR is failing as Helm stable repo has moved

### ISSUE THREAD

**Issue by namloc2001** [DefectDojo/django-DefectDojo#3186]
Please enter as much information as possible, otherwise we can't provide support. If possible upgrade to the latest release or dev version and try again.

**Bug description**
My PR #3184 is failing with the following:
```
Run helm repo add stable https://kubernetes-charts.storage.googleapis.com/
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/runner/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/runner/.kube/config
Error: repo "https://kubernetes-charts.storage.googleapis.com/" is no longer available; try "https://charts.helm.sh/stable" instead
Error: The operation was canceled.
```

This is because Helm stable and incubator repositories have moved: https://helm.sh/blog/new-location-stable-incubator-charts/

New locations:
 - https://charts.helm.sh/stable
 - https://charts.helm.sh/incubator

These should be updated with:
```
helm repo add stable https://charts.helm.sh/stable --force-update
helm repo add incubator https://charts.helm.sh/incubator --force-update
```

**Steps to reproduce**
1. Create a PR
2. See error

**Expected behavior**
PR to undergo tests without Helm issue.

**Deployment method** *(select with an `X`)*
1. Create a PR
2. See error

**Environment information**
N/A this is within the DefectDojo testing/pipeline environment, not mine.

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

**Comment by valentijnscholten** [comment]
just fixed by #3183 but we still see other errors.
