### ISSUE TITLE
set the mitigated field of a finding

### ISSUE THREAD

**Issue by saldam72** [DefectDojo/django-DefectDojo#3189]
I have to initialize DefectDojo by loading all vulnerabilities including the correct ones and I would need to be able to set the mitigation date but I don't think it's possible to do it via API, is it?

if so, Could you make the mitigation date setting available via API?

best regards,
Sal

**Comment by keenan-v1** [comment]
I have a local modification that sets the mitigation date if is_Mitigated was changed by the API, but I don't think that's the best path forward.

I think allowing the API to update the field would be the best path forward, and it should likely be a required field if is_Mitigated is true.

The reason this is a problem is that the API can set the is_Mitigated flag, but not the mitigation date. It seems that everywhere else in DefectDojo uses the presence of a mitigation date to indicate a mitigated finding, thus making it impossible (to my knowledge) to mitigate things via the API.

**Comment by valentijnscholten** [comment]
The field is not read only, but specified as not editable. This means it doesn't show up on forms in the UI so it can't be edited. The Django Rest Frame form seems to also use this flag to determine if it can be modified via the API.
Anyway, it looks like the original implementer of the `mitigated` field wanted to use it as a timestamp that was automatically set when the finding was set as having been mitigated. So setting it in the perform_update override you mentioned isn't too bad. Anotether way could be a pre or post save signal that compates values. But everything around Django signals quickly becomes a mess, so I'd like to avoid that if possible.
making the field updatable in the API but not in the UI is not possible out of the box. and making it mandatory if and only if is_Mitigated is true requires extra glue code and then would have to be reflected in the UI as well.
if you make a PR with the perform_update override we'll probably merge it.

**Comment by devGregA** [comment]
Addressed and fixed in today's release. thanks to @keenan-v1
