### ISSUE TITLE
Findings in DefectDojo are not creating Bugs automatically in Jira on creation.

### ISSUE THREAD

**Issue by childsc** [DefectDojo/django-DefectDojo#3191]
I am having problems when I am adding Findings to my Test for an Engagement. The Finding does not automatically create a Bug in Jira even though "Push to Jira"  is configured by default.

The work around is to perform the following after creating the new Finding; through the UI find the "Finding" and press the arrow for "Create a Jira instance for this Finding" under a box called "JIRA" . This will then create a new Bug in Jira.

I do not have this problem for Engagements. When I create an Engagement and I select the "Push to Jira" tick box then a new Epic is created in Jira. 

**Steps to reproduce**
1. Go to an Open Engagement
2. Select Test
3. Click to add a New Finding in the FINDINGS() box.
4. Fill in information about Finding. "Push to JIRA" is preselected and unable to unselect.
5. Check Jira

**Expected behavior**
I expect to see a new Bug created in Jira like an Epic.

**Deployment method** *(select with an `X`)*
- [x] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Version 1.8.0

**Console logs** (optional)
[pid: 1|app: 0|req: 52579/73958] 10.42.72.29 () {64 vars in 1332 bytes} [Fri Nov  6 14:39:35 2020] POST /engagement/24/add_tests => generated 0 bytes in 105 msecs (HTTP/1.1 302) 8 headers in 416 bytes (1 switches on core 0)
[pid: 1|app: 0|req: 52580/73959] 10.42.72.29 () {58 vars in 1296 bytes} [Fri Nov  6 14:39:35 2020] GET /test/27/add_findings => generated 63001 bytes in 153 msecs (HTTP/1.1 200) 8 headers in 475 bytes (1 switches on core 1)
[pid: 1|app: 0|req: 52581/73960] 10.42.72.29 () {58 vars in 1057 bytes} [Fri Nov  6 14:39:37 2020] GET /alerts/count => generated 12 bytes in 22 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 1|app: 0|req: 52582/73961] 10.42.72.29 () {58 vars in 1057 bytes} [Fri Nov  6 14:39:37 2020] GET /alerts/count => generated 12 bytes in 24 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 1)
[pid: 1|app: 0|req: 52583/73962] 10.13.18.43 () {34 vars in 391 bytes} [Fri Nov  6 14:39:39 2020] GET / => generated 0 bytes in 12 msecs (HTTP/1.1 302) 7 headers in 215 bytes (1 switches on core 0)
[pid: 1|app: 0|req: 52584/73963] 10.13.18.43 () {36 vars in 454 bytes} [Fri Nov  6 14:39:39 2020] GET /login?next=/ => generated 14736 bytes in 22 msecs (HTTP/1.1 200) 9 headers in 480 bytes (1 switches on core 1)
[pid: 1|app: 0|req: 52585/73964] 10.42.72.29 () {58 vars in 1061 bytes} [Fri Nov  6 14:39:42 2020] GET /alerts/count => generated 12 bytes in 22 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 1|app: 0|req: 52586/73965] 10.42.72.29 () {58 vars in 1082 bytes} [Fri Nov  6 14:39:42 2020] GET /alerts/count => generated 12 bytes in 26 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 1)
[pid: 16|app: 0|req: 21380/73966] 10.42.72.29 () {58 vars in 1060 bytes} [Fri Nov  6 14:39:44 2020] GET /alerts/count => generated 12 bytes in 23 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 1|app: 0|req: 52587/73967] 10.42.72.29 () {58 vars in 1070 bytes} [Fri Nov  6 14:39:46 2020] GET /alerts/count => generated 12 bytes in 26 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 1|app: 0|req: 52588/73968] 10.42.72.29 () {58 vars in 1057 bytes} [Fri Nov  6 14:39:47 2020] GET /alerts/count => generated 12 bytes in 23 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 1)
[pid: 16|app: 0|req: 21381/73969] 10.42.72.29 () {58 vars in 1057 bytes} [Fri Nov  6 14:39:47 2020] GET /alerts/count => generated 12 bytes in 23 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 1)
[pid: 1|app: 0|req: 52589/73970] 10.13.18.43 () {34 vars in 391 bytes} [Fri Nov  6 14:39:49 2020] GET / => generated 0 bytes in 12 msecs (HTTP/1.1 302) 7 headers in 215 bytes (1 switches on core 0)
[pid: 1|app: 0|req: 52590/73971] 10.13.18.43 () {36 vars in 454 bytes} [Fri Nov  6 14:39:49 2020] GET /login?next=/ => generated 14736 bytes in 24 msecs (HTTP/1.1 200) 9 headers in 480 bytes (1 switches on core 1)
[pid: 1|app: 0|req: 52592/73972] 10.42.72.29 () {58 vars in 1061 bytes} [Fri Nov  6 14:39:52 2020] GET /alerts/count => generated 12 bytes in 22 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 1|app: 0|req: 52592/73973] 10.42.72.29 () {58 vars in 1082 bytes} [Fri Nov  6 14:39:52 2020] GET /alerts/count => generated 12 bytes in 23 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 1)
[pid: 16|app: 0|req: 21382/73974] 10.42.72.29 () {58 vars in 1060 bytes} [Fri Nov  6 14:39:54 2020] GET /alerts/count => generated 12 bytes in 23 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 16|app: 0|req: 21383/73975] 10.42.72.29 () {58 vars in 1070 bytes} [Fri Nov  6 14:39:56 2020] GET /alerts/count => generated 12 bytes in 22 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 1)
[pid: 16|app: 0|req: 21384/73976] 10.42.72.29 () {58 vars in 1057 bytes} [Fri Nov  6 14:39:57 2020] GET /alerts/count => generated 12 bytes in 23 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 16|app: 0|req: 21385/73977] 10.42.72.29 () {58 vars in 1057 bytes} [Fri Nov  6 14:39:57 2020] GET /alerts/count => generated 12 bytes in 25 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 1)
[pid: 16|app: 0|req: 21386/73978] 10.13.18.43 () {34 vars in 391 bytes} [Fri Nov  6 14:39:59 2020] GET / => generated 0 bytes in 12 msecs (HTTP/1.1 302) 7 headers in 215 bytes (1 switches on core 0)
[pid: 16|app: 0|req: 21387/73979] 10.13.18.43 () {36 vars in 454 bytes} [Fri Nov  6 14:39:59 2020] GET /login?next=/ => generated 14736 bytes in 22 msecs (HTTP/1.1 200) 9 headers in 480 bytes (1 switches on core 1)
[pid: 1|app: 0|req: 52593/73980] 10.42.72.29 () {58 vars in 1061 bytes} [Fri Nov  6 14:40:02 2020] GET /alerts/count => generated 12 bytes in 21 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 1|app: 0|req: 52594/73981] 10.42.72.29 () {58 vars in 1082 bytes} [Fri Nov  6 14:40:02 2020] GET /alerts/count => generated 12 bytes in 24 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 1)
[pid: 1|app: 0|req: 52595/73982] 10.42.72.29 () {58 vars in 1060 bytes} [Fri Nov  6 14:40:04 2020] GET /alerts/count => generated 12 bytes in 22 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 16|app: 0|req: 21388/73983] 10.42.72.29 () {58 vars in 1070 bytes} [Fri Nov  6 14:40:06 2020] GET /alerts/count => generated 12 bytes in 25 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 1|app: 0|req: 52596/73984] 10.42.72.29 () {58 vars in 1057 bytes} [Fri Nov  6 14:40:07 2020] GET /alerts/count => generated 12 bytes in 31 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 1)
[pid: 16|app: 0|req: 21389/73985] 10.42.72.29 () {58 vars in 1057 bytes} [Fri Nov  6 14:40:07 2020] GET /alerts/count => generated 12 bytes in 23 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 1)
applying rules
No config file found at /home/defectdojo/.titlecase.txt
No config file found at /home/defectdojo/.titlecase.txt
Test
No config file found at /home/defectdojo/.titlecase.txt
Finding4
Test-Finding4
applying rules
No config file found at /home/defectdojo/.titlecase.txt
No config file found at /home/defectdojo/.titlecase.txt
Test
No config file found at /home/defectdojo/.titlecase.txt
Finding4
Test-Finding4
sending alert notification to None
sending alert notification to None
[pid: 1|app: 0|req: 52597/73986] 10.42.72.29 () {64 vars in 1323 bytes} [Fri Nov  6 14:40:08 2020] POST /test/27/add_findings => generated 0 bytes in 168 msecs (HTTP/1.1 302) 7 headers in 210 bytes (1 switches on core 0)
[pid: 1|app: 0|req: 52598/73987] 10.42.72.29 () {58 vars in 1127 bytes} [Fri Nov  6 14:40:08 2020] GET /test/27 => generated 102462 bytes in 316 msecs (HTTP/1.1 200) 7 headers in 378 bytes (1 switches on core 1)
[pid: 16|app: 0|req: 21390/73988] 10.13.18.43 () {34 vars in 391 bytes} [Fri Nov  6 14:40:09 2020] GET / => generated 0 bytes in 13 msecs (HTTP/1.1 302) 7 headers in 215 bytes (1 switches on core 0)
[pid: 16|app: 0|req: 21391/73989] 10.13.18.43 () {36 vars in 454 bytes} [Fri Nov  6 14:40:09 2020] GET /login?next=/ => generated 14736 bytes in 23 msecs (HTTP/1.1 200) 9 headers in 480 bytes (1 switches on core 1)
[pid: 1|app: 0|req: 52600/73990] 10.42.72.29 () {58 vars in 1061 bytes} [Fri Nov  6 14:40:12 2020] GET /alerts/count => generated 12 bytes in 30 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 1|app: 0|req: 52600/73991] 10.42.72.29 () {58 vars in 1082 bytes} [Fri Nov  6 14:40:12 2020] GET /alerts/count => generated 12 bytes in 28 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 1)
[pid: 1|app: 0|req: 52601/73992] 10.42.72.29 () {58 vars in 1060 bytes} [Fri Nov  6 14:40:14 2020] GET /alerts/count => generated 12 bytes in 22 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 1|app: 0|req: 52602/73993] 10.42.72.29 () {58 vars in 1057 bytes} [Fri Nov  6 14:40:17 2020] GET /alerts/count => generated 12 bytes in 22 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 1)
[pid: 1|app: 0|req: 52603/73994] 10.42.72.29 () {58 vars in 1057 bytes} [Fri Nov  6 14:40:17 2020] GET /alerts/count => generated 12 bytes in 26 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 1|app: 0|req: 52604/73995] 10.13.18.43 () {34 vars in 391 bytes} [Fri Nov  6 14:40:19 2020] GET / => generated 0 bytes in 14 msecs (HTTP/1.1 302) 7 headers in 215 bytes (1 switches on core 1)
[pid: 1|app: 0|req: 52605/73996] 10.13.18.43 () {36 vars in 454 bytes} [Fri Nov  6 14:40:19 2020] GET /login?next=/ => generated 14736 bytes in 22 msecs (HTTP/1.1 200) 9 headers in 480 bytes (1 switches on core 0)
[pid: 1|app: 0|req: 52606/73997] 10.42.72.29 () {58 vars in 1057 bytes} [Fri Nov  6 14:40:20 2020] GET /alerts/count => generated 12 bytes in 22 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 1)
[pid: 1|app: 0|req: 52607/73998] 10.42.72.29 () {58 vars in 1061 bytes} [Fri Nov  6 14:40:22 2020] GET /alerts/count => generated 12 bytes in 22 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 1|app: 0|req: 52608/73999] 10.42.72.29 () {58 vars in 1082 bytes} [Fri Nov  6 14:40:22 2020] GET /alerts/count => generated 12 bytes in 21 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 1)
[pid: 1|app: 0|req: 52609/74000] 10.42.72.29 () {58 vars in 1060 bytes} [Fri Nov  6 14:40:24 2020] GET /alerts/count => generated 12 bytes in 22 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 1|app: 0|req: 52610/74001] 10.42.72.29 () {58 vars in 1057 bytes} [Fri Nov  6 14:40:27 2020] GET /alerts/count => generated 12 bytes in 24 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 1)
[pid: 1|app: 0|req: 52611/74002] 10.42.72.29 () {58 vars in 1057 bytes} [Fri Nov  6 14:40:28 2020] GET /alerts/count => generated 12 bytes in 25 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 16|app: 0|req: 21392/74003] 10.13.18.43 () {34 vars in 391 bytes} [Fri Nov  6 14:40:29 2020] GET / => generated 0 bytes in 14 msecs (HTTP/1.1 302) 7 headers in 215 bytes (1 switches on core 0)
[pid: 1|app: 0|req: 52612/74004] 10.13.18.43 () {36 vars in 454 bytes} [Fri Nov  6 14:40:29 2020] GET /login?next=/ => generated 14736 bytes in 34 msecs (HTTP/1.1 200) 9 headers in 480 bytes (1 switches on core 1)
[pid: 16|app: 0|req: 21393/74005] 10.42.72.29 () {58 vars in 1057 bytes} [Fri Nov  6 14:40:30 2020] GET /alerts/count => generated 12 bytes in 29 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 1)
[pid: 1|app: 0|req: 52613/74006] 10.42.72.29 () {58 vars in 1061 bytes} [Fri Nov  6 14:40:32 2020] GET /alerts/count => generated 12 bytes in 23 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)
[pid: 1|app: 0|req: 52614/74007] 10.42.72.29 () {58 vars in 1082 bytes} [Fri Nov  6 14:40:32 2020] GET /alerts/count => generated 12 bytes in 23 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 1)
[pid: 1|app: 0|req: 52615/74008] 10.42.72.29 () {58 vars in 1060 bytes} [Fri Nov  6 14:40:34 2020] GET /alerts/count => generated 12 bytes in 24 msecs (HTTP/1.1 200) 6 headers in 180 bytes (1 switches on core 0)

**Comment by valentijnscholten** [comment]
What settings have you chosen in the JIRA config for the product

**Comment by childsc** [comment]
Hello,

I followed the instruction in the DefecDojo documentation, which is to say; I created a WebHook in our Jira istance with more options selected:

Events
Issue related events
JQL:
Issue
    created updated deleted worklog changed 
Worklog
    updated 
Issue link
    created 
Comment
    created updated 
User related events
User
    created deleted updated 
Jira configuration related events
Features status change (enabled/disabled)
    voting watching unassigned issues subtasks attachments issue links time tracking 
Exclude body
No
Transitions

**Comment by valentijnscholten** [comment]
I meant the settings for the product in Defect Dojo.

**Comment by childsc** [comment]
![image](https://user-images.githubusercontent.com/40882907/98506060-fb183200-225a-11eb-861b-a8219476de21.png)
![image](https://user-images.githubusercontent.com/40882907/98506112-1be08780-225b-11eb-8935-531c3defb467.png)

**Comment by valentijnscholten** [comment]
That's not the settings for product. Goto /product/1/edit. Replace 1 with the id of your product

**Comment by childsc** [comment]
![Edit Product  DefectDojo - Mozilla Firefox_2](https://user-images.githubusercontent.com/40882907/98516380-b8f7ec00-226c-11eb-9f94-f7442a5fb111.jpg)

**Comment by childsc** [comment]
Hi, Just leaving a message to see if there are any suggestions?

**Comment by valentijnscholten** [comment]
We did a big refactor in `dev`. Can you try that? Please also check logs. And check alerts on top right of the screen.
