### ISSUE TITLE
Cannot save system settings if jira webhook secret is disabled

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#3211]
![image](https://user-images.githubusercontent.com/5468769/98471727-9aeba680-21ee-11eb-8d00-2338a905c044.png)

When this is the case, you cannot save the form.

**Comment by valentijnscholten** [comment]
Hmmm thought I tested that, will check/fix

**Comment by madchap** [comment]
I haven't paid attention to which commit I was on, maybe something you fixed afterwards I didn't catch?

**Comment by valentijnscholten** [comment]
It's security through obscurity 😜

**Comment by valentijnscholten** [comment]
It's because the field is mandatory but empty. The django javascript tries to focus the field and display the error. Not sure how to fix it. Workaround is to put some value in there.

**Comment by madchap** [comment]
make it non-mandatory and catch the fact is empty more downstream maybe?

**Comment by valentijnscholten** [comment]
can't override django form validation easily on the client. this is what happens when you try to make the form look nice instead of the old school django form look ;-)
