### ISSUE TITLE
SAML-Integration: DefectDojo and ADFS

### ISSUE THREAD

**Issue by joreize** [DefectDojo/django-DefectDojo#3216]
Hello, 
I'm trying to integrate DefectDojo with SAML - ADFS Authentication.

**Bug description**
When i "click" the "Login with SAML" Button I can't be logged in because of an error with the ADFS.
 
**Steps to reproduce**

1.  I added the needed variables:

```
     DD_SAML2_ASSERTION_URL: https://defectdojo.xxx.com
     DD_SAML2_ENABLED: "true"
     DD_SAML2_ENTITY_ID: https://defectdojo.xxx.com/saml2_auth/acs/
    DD_SAML2_METADATA_AUTO_CONF_URL: https://xxx.xxx.com/FederationMetadata/2007-06/FederationMetadata.xml
```

2.  Added the system to ADFS
3. Restarted Pods

**Expected behavior**
Successful Login to DefectDojo

**Deployment method** *(select with an `X`)*
- [x] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Console logs** (optional)
From ADFS i receive the following Error-Message:
```
Encountered error during federation passive request. 
 Additional Data 

Protocol Name: 
Saml 

Relying Party: 
https://defectdojo.xxx.com/saml2_auth/acs/ 


Exception details: 
Microsoft.IdentityServer.Web.InvalidScopeException: MSIS7007: The requested relying party trust 'https://defectdojo.xxx.com/saml2_auth/acs/' is unspecified or unsupported. If a relying party trust was specified, it is possible that you do not have permission to access the trust relying party. Contact your administrator for details.
   at Microsoft.IdentityServer.Web.Protocols.Saml.SamlSignInContext.Validate()
   at Microsoft.IdentityServer.Web.Protocols.Saml.SamlProtocolHandler.GetRequiredPipelineBehaviors(ProtocolContext pContext)
   at Microsoft.IdentityServer.Web.PassiveProtocolListener.OnGetContext(WrappedHttpListenerContext context)

```

Thanks for your help and all the best

Johannes

**Comment by damiencarol** [comment]
@joreize hello, thank you for your report. This kind of support/question is better to ask directly on our Slack channel. You will have more answers/details here : https://owasp-slack.herokuapp.com/

**Comment by valentijnscholten** [comment]
Did you try everything you could find with google? Lots of posts which, same as the error, seem to indicate a configuration error on ADFS side. We use standard django social auth and django saml2 auth libraries.

**Comment by dsever** [comment]
Do you use self signed certs?

**Comment by joreize** [comment]
Thanks for comming back here - we've changed to AzureAD and everything is fine.

**Comment by saldam72** [comment]
Hi all,
we have resolved the problem by copying from the setting.dist.py file to the local_settings.py file the whole "if SAML2_ENABLED:" section as show below

SAML2_ENABLED=True
SAML2_CREATE_USER=True
SAML2_METADATA_LOCAL_FILE_PATH='/public/share/idp_metadata.xml'
if SAML2_ENABLED:
...

we think that the documentation needs to be a little more detailed for this.

best,
Sal

**Comment by valentijnscholten** [comment]
Please create a PR if you have suggestions to improve the docs. We need to help each other as we don't have every possible SSO solution in place to test and document.
