### ISSUE TITLE
Broken engagement metrics when editing the finding state

### ISSUE THREAD

**Issue by marcosValle** [DefectDojo/django-DefectDojo#3220]
**Bug description**
After bulk editing an active finding and selecting false-positive, the metrics dashboard show 0 findings. When clicking the "False-positives" gadget I can see the vulnerability there, even though the board shows 0 vulns.

**Steps to reproduce**
1. Create a new product and a new engagement
2. Create a new Critical severity finding
3. Go to `Findings` > `View Open Findings` and select the vulnerability
4. Click `Bulk Edit`, click `Status` and select `False Positive`
5. Click Submit
6. Go to `Metrics`
7. The panel shows 0 findings, even for "False-Positive Findings" chart
8. Click the "False-Positive Findings" chart
9. Confirm that the vulnerability is there

**Expected behavior**
When a vulnerability is set to a different state, the metrics panel should reflect it.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: MacOS Catalina

**Screenshots**
<img width="1791" alt="Screen Shot 1399-08-19 at 23 41 51" src="https://user-images.githubusercontent.com/5929526/98605071-28112700-22e5-11eb-8409-0697cf694ff5.png">

<img width="1671" alt="Screen Shot 1399-08-19 at 23 42 11" src="https://user-images.githubusercontent.com/5929526/98605108-33fce900-22e5-11eb-9b7c-488b419398be.png">

**Additional context**
I can see similar behavior happen with other states too, such as Active/Inactive vulnerabilities.

**Comment by valentijnscholten** [comment]
if you only select false_p it will set only the false_p flag and _unset_  the active and other flags. so check those as well when using bulk edit.

**Comment by marcosValle** [comment]
The same behavior persists when setting both Active and False-Positive flags in bulk edit.
What is the expected result for the "False-Positive Findings" chart? I suppose it should display the false positives regardless of any other flags.

**Comment by valentijnscholten** [comment]
What do you see when you open view all findings for this product

**Comment by marcosValle** [comment]
It seems to work as expected.

<img width="1685" alt="Screen Shot 1399-08-20 at 18 35 21" src="https://user-images.githubusercontent.com/5929526/98710081-80970180-2383-11eb-9f38-0bd3a1c456b0.png">

I don't see it on the product metrics board, though.
<img width="1675" alt="Screen Shot 1399-08-20 at 18 36 40" src="https://user-images.githubusercontent.com/5929526/98710242-afad7300-2383-11eb-912c-3e1d0ccdbe30.png">
