### ISSUE TITLE
error generating report (500, qs unknown)

### ISSUE THREAD

**Issue by undelete** [DefectDojo/django-DefectDojo#3221]
Problems generating report

**Bug description**

When I try to generate a report, it shows me the error 500. It only happens twice as an active user and as a superuser. Being a staff there is no problem.

**Steps to reproduce**
1. Go to 'Product report' and click
2. See error

**Expected behavior**
It should send to the screen to generate report

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x ] Docker
- [ ] setup.bash / legacy-setup.bash
- Version 1.9.2

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Commit Message: [use `git show -s --format="[%ci] %h: %s [%d]"`]

**Screenshots** (optional)

<img width="215" alt="Captura de Pantalla 2020-11-09 a la(s) 23 18 41" src="https://user-images.githubusercontent.com/25057634/98620127-6e658680-22e3-11eb-9fb7-20b824d099ad.png">

<img width="954" alt="Captura de Pantalla 2020-11-09 a la(s) 23 18 03" src="https://user-images.githubusercontent.com/25057634/98620141-74f3fe00-22e3-11eb-9425-ecdcb889567a.png">

<img width="954" alt="Captura de Pantalla 2020-11-09 a la(s) 23 17 43" src="https://user-images.githubusercontent.com/25057634/98620243-acfb4100-22e3-11eb-9589-0f586cb94530.png">

**Comment by valentijnscholten** [comment]
@Maffooch I think this is different from the missing Q import?

**Comment by Maffooch** [comment]
Yeah that's different. This looks like a missing qs import. No idea how all these issues are just now popping up now as all the things around the Q/qs changes came from 1.8.0

**Comment by valentijnscholten** [comment]
Report feature needs some automated tests

**Comment by undelete** [comment]
Hi the same error in 1.9.3 :( 

<img width="888" alt="Captura de Pantalla 2020-11-16 a la(s) 14 44 04" src="https://user-images.githubusercontent.com/25057634/99288992-22eb3500-281b-11eb-8b06-e26758c5c82d.png">

**Comment by Maffooch** [comment]
This fix is in `dev` but did not get added to `1.9.3`.. It will be in the next major version next tuesday.

**Comment by undelete** [comment]
> This fix is in `dev` but did not get added to `1.9.3`.. It will be in the next major version next tuesday.

Thanks a lot!
