### ISSUE TITLE
JS concurrent issue in "Simple Search" page

### ISSUE THREAD

**Issue by Wadeck** [DefectDojo/django-DefectDojo#3226]
After having search for an ID, I got the page with the "Findings", "Tests" and "Combined" tabs.
If I click on "Tests" too soon (~1sec after result shown), part of the JS (from "Findings") is not yet loaded for the tab body and so the tab "active" is changed but not the content. I have to click back to Findings and back to Tests to get the expected data.

I suspect a concurrent issue in JS, like the code is not waiting for the correct event before doing something else, like the common mistake with autocompletion.

<details>

<summary>Gif</summary>

![search_tests_tab_js_concur_issue](https://user-images.githubusercontent.com/2662497/98697970-ce0c7200-2375-11eb-83bd-49790d40970d.gif)

</details>

**Expected behavior**
The "Tests" tab to be loaded directly as it is if I wait enough time to see the filters from Findings being shown.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Commit Message: [use `git show -s --format="[%ci] %h: %s [%d]"`]

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

**Comment by valentijnscholten** [comment]
I can't reproduce this, maybe only happening on a slow server / slow client / slow connection / all of them combined :-)
