### ISSUE TITLE
Cannot submit comment after having used filter for "Similar Findings"

### ISSUE THREAD

**Issue by Wadeck** [DefectDojo/django-DefectDojo#3241]
Browse a finding with Similar Findings. Add a comment at the bottom of the page, it's working fine. Now, open the "Similar Findings" panel, change a bit the filters and click on "Apply Filters". You will see the URL changes with all the fields being inside (that could be the root cause).

Now, within that page with long URL, try adding a comment. I got a NGinx error.

**Expected behavior**
I do not expect any effect of the filters used on the ability to submit comments.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Commit Message: [use `git show -s --format="[%ci] %h: %s [%d]"`]

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

cc @valentijnscholten @madchap

**Comment by valentijnscholten** [comment]
fixed in dev, so 1.10.0. can you confirm?
