### ISSUE TITLE
View finding: images not found

### ISSUE THREAD

**Issue by Seppl2202** [DefectDojo/django-DefectDojo#3256]
**Bug description**
When viewing a finding with uploaded images, those images are not found

**Steps to reproduce**
1. Go to 'upload image through 'Manage images'
2. Click on 'save'
3. View this finding
4. Images are not loaded (HTTP 404)

**Expected behavior**
Uploaded images should be displayed.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Ubuntu 18.04
 - DefectDojo Commit Message: [use `git show -s --format="[%ci] %h: %s [%d]"`]

**Sample scan files** (optional)
This is the picture, that was uploaded:
![local_storage_zen](https://user-images.githubusercontent.com/38285208/98974789-99cfb780-2515-11eb-9226-c0da1bd232d7.png)

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)
DefectDojo then uses the following a element to load this image:

```
<a href="#" data-imageurl="https://defect-dojo.domain.com/media/CACHE/images/finding_images/39ead459-37cd-4dc7-86be-204b10db31c5/ee8036b0bc5670fe3bf1753d4ed6aff6.jpg" data-origurl="https://defect-dojo.domain.com/media/finding_images/39ead459-37cd-4dc7-86be-204b10db31c5.jpg" data-caption="" class="thumbnail" data-toggle="modal" data-target="#findingImageModal" id="finding_pic">
                                <img src="https://defect-dojo.domain.com/media/CACHE/images/finding_images/39ead459-37cd-4dc7-86be-204b10db31c5/5a3a5b319bbd7f3dde4c87015d2e1e10.jpg" alt="" title="">
                            </a>
```

This calls will fail with HTTP 404.

Maybe someone experienced this before?

**Comment by valentijnscholten** [comment]
known issue: https://github.com/DefectDojo/django-DefectDojo/blob/master/DOCKER.md#prerequisites
please come to slack for more support

**Comment by Seppl2202** [comment]
nvm, we had the volumes in our docker-compose, but we had a typo in it ...
