### ISSUE TITLE
jira: if no minimum severity configured, findings are never pushed

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#3261]
if no minimum severity is configured in system settings, findings are never pushed

**Comment by madchap** [comment]
hmm, I think I had opened something on that at some point. But indeed, probably still holds true.

**Comment by valentijnscholten** [comment]
I thought so to, but look at the code it still goes wrong. maybe because the fixtures for the unit tests are having null as value there

**Comment by madchap** [comment]
Maybe. I think the simple "fix" I had made was the have the default value set to `Low` instead of `null` back in the days.

**Comment by valentijnscholten** [comment]
fixed in dev, so 1.10.0
