### ISSUE TITLE
Error Looking up Findings with API

### ISSUE THREAD

**Issue by rkane-nm** [DefectDojo/django-DefectDojo#328]
Looking up products and engagements though the API works just fine, but for some reason trying to look up findings fails (and yes, we have about 5 or 6 test findings loaded). Been trying to look through it, and have found this info about django-tastypie and using ForeignKeys: https://stackoverflow.com/questions/11399342/reverse-relation-tomanyfield-tastypie (not sure that will help).

Here's the details:
> Request URL
> http://***.***.***.220:8000/api/v1/findings/
> Response Body
> {
>   "error_message": "'NoneType' object is not iterable",
>   "traceback": "Traceback (most recent call last):\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 221, in wrapper\n    response = callback(request, *args, **kwargs)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 461, in dispatch_list\n    return self.dispatch('list', request, **kwargs)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 493, in dispatch\n    response = method(request, **kwargs)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 1357, in get_list\n    for obj in to_be_serialized[self._meta.collection_name]\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 906, in full_dehydrate\n    data[field_name] = field_object.dehydrate(bundle, for_list=for_list)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/fields.py\", line 869, in dehydrate\n    for m2m in the_m2ms\n\nTypeError: 'NoneType' object is not iterable\n"
> }
> Response Code
> 500
> Response Headers
> {
>   "Date": "Tue, 18 Jul 2017 17:26:17 GMT",
>   "Vary": "Cookie",
>   "Server": "WSGIServer/0.1 Python/2.7.12+",
>   "Content-Length": "1058",
>   "X-Frame-Options": "SAMEORIGIN",
>   "Content-Type": "application/json"
> }

**Comment by vpulec** [comment]
This also occurs when looking up a specific finding, such as /api/v1/findings/200/

**Comment by devGregA** [comment]
@vpulec @rkane-nm I'm not able to reproduce this issue. Are you still having issues?
