### ISSUE TITLE
JIRA engagement level - JIRA URL not displayed when inherited

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#3283]
A jira configuration is enabled at product level, and not engagement level.

When editing a finding, the JIRA URL is None instead of being populated by the Product level JIRA config. I think that, since the engagement level is empty, it's looking at that.

Note that it all works as expected anyways, it's just a visual thing.

![image](https://user-images.githubusercontent.com/5468769/99415959-a3339800-28f8-11eb-81fa-8caebac17e63.png)

fyi @valentijnscholten

**Comment by valentijnscholten** [comment]
fixed by #3284
