### ISSUE TITLE
do not show sla notification option if sla notifications are disabled

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#3296]
When configuring JIRA for a product or engagement, currently you can always enable SLA notification even when those are disabled in setting.py or when SLA has been disabled in system_settings.

![image](https://user-images.githubusercontent.com/4426050/99453897-e821f380-2925-11eb-81e4-9b52c30625d3.png)

**Comment by madchap** [comment]
Right. This is to give freedom to users/product owners. A bug?

**Comment by madchap** [comment]
Anything you'd like to do for this?

**Comment by valentijnscholten** [comment]
Of you disable them globally in settings.py, why show this option which won't do anything but confuse the user?

**Comment by SoaAlex** [comment]
I agree with @valentijnscholten .
I would add that it's not only linked to JIRA. It should not display at all in the `/notifications` UI settings page if it's not enabled in settings.py (otherwise, enabling SLA Breach Alerts/Mails/MSTeams/Slack won't do anything).
