### ISSUE TITLE
DefectDojo Instance Stopped working

### ISSUE THREAD

**Issue by snipav1** [DefectDojo/django-DefectDojo#3298]
Today, our defectdojo instance stopped working. When I restarted and re-deployed, it seems like it gets stuck on in the following step:

![Screen Shot 2020-11-17 at 4 16 16 PM](https://user-images.githubusercontent.com/33110785/99457226-3f0cd600-28f0-11eb-987a-6a999fe7d12d.png)

When I looked at the logs, it looks like the password for 'dojo' user had expired and it stated 'source not found' as so:
![Screen Shot 2020-11-17 at 4 04 03 PM](https://user-images.githubusercontent.com/33110785/99456166-8f833400-28ee-11eb-9e95-8a6b17630c9a.png)

After changing the password for the dojo user I got rid of the password expiration error but the 'source: not found' issue still remains:
![Screen Shot 2020-11-17 at 4 04 46 PM](https://user-images.githubusercontent.com/33110785/99456215-a4f85e00-28ee-11eb-9b10-ebfec1ee9e42.png)

Has anyone seen this one before?

Thanks

**Comment by madchap** [comment]
We'd need more details about your environment, versions, etc.. but first time I am seeing this to be honest (but I only run docker and k8s). It seems more of an O/S related issue than defectdojo.

@mtesauro any clue?

**Comment by snipav1** [comment]
**OS version:**
Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1029-aws x86_64)

Docker Version:
19.03.13

**Docker-Compose Version:**
1.25.5, build 8a1c60f6

**Deployment:**
Docker Compose

**Commands run:**
docker-compose build
docker-compose up -d

**Comment by valentijnscholten** [comment]
better come to slack for support: https://github.com/DefectDojo/django-DefectDojo#getting-involved

**Comment by mtesauro** [comment]
Which container is throwing that error in the logs?

It's definitely not something I've seen before.

Did you pull a specific tagged/release version of DefectDojo, pull code from master branch, dev branch?
