### ISSUE TITLE
Changing host name to anything other than the default in helm chart causes 502 error.

### ISSUE THREAD

**Issue by g0pinath-metricon** [DefectDojo/django-DefectDojo#3299]
Please enter as much information as possible, otherwise we can't provide support. If possible upgrade to the latest release or dev version and try again.

**Bug description**
The default value for host is defectdojo.default.minikube.local, if I changed this to a custom domain name, DJANGO throws error as below.
Invalid HTTP_HOST header: 'defectdojo.cloudkube.xyz'. You may need to add 'defectdojo.cloudkube.xyz' to ALLOWED_HOSTS.
If I do a kubectl exec into that pod and set the env var as export ALLOWED_HOSTS="http://defectdojo.cloudkube.xyz/", the website loads.

Can this be added to the DJANGO deployment helm chart.

I can submit a PR if that helps.

**Steps to reproduce**

**Expected behavior**

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Commit Message: [use `git show -s --format="[%ci] %h: %s [%d]"`]

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

**Comment by madchap** [comment]
I had the same thing, simply overrode it in my helmfile. There is a `DD_ALLOWED_HOSTS` variable you can use for that purpose.
