### ISSUE TITLE
Link to "Total Findings" in engagement dashboard points to the wrong page

### ISSUE THREAD

**Issue by wturnes-flexion** [DefectDojo/django-DefectDojo#3303]
When viewing an engagement, the metrics dashboard link for Total Findings points to the /false_positive handler

**Steps to reproduce**
1. Open an Engagement from the "All Engagements" menu link
2. Click "Metrics" in the ribbon
3. Click the "Total Findings" link above the graph
4. Browser is directed to /false_positive view

**Expected behavior**
User should be directed to a view of all findings, not false positives.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - DefectDojo demo server (https://demo.defectdojo.org/)

**Comment by valentijnscholten** [comment]
confirmed

**Comment by valentijnscholten** [comment]
@wturnes-flexion can you confirm it is now solved?

**Comment by wturnes-flexion** [comment]
Looks fixed to me
