### ISSUE TITLE
Snyk Container scan import

### ISSUE THREAD

**Issue by ealkalai** [DefectDojo/django-DefectDojo#3310]
I would like to be able to import snyk container scan results.

**Comment by madchap** [comment]
Any help writing this parser welcome :-)

**Comment by damiencarol** [comment]
@ealkalai could you provide a report of this scanner?

**Comment by ealkalai** [comment]
@damiencarol, at the moment it is supported only the dependency scan feature of snyk.

Snyk offers, additionally, container scanning, which is not accepted by the `Snyk Scan` **Scan Type**. (defect dojo version 1.65)

I looked at your edited comments and here is a json report from snyk container test
[snyk-container.zip](https://github.com/DefectDojo/django-DefectDojo/files/5677960/snyk-container.zip)

**Comment by valentijnscholten** [comment]
so the container scans is different file, or are they both in the same report file?

**Comment by ealkalai** [comment]
Snyk exports these files via different processes. So I assume they are not compatible. If they were I could have uploaded via the existing functionality of defect dojo.
________________________________

**Comment by valentijnscholten** [comment]
It doesn't always work like that. There are scanners who put multiple sections in a report depending on chosen scan or export settings. For example twistlock and I believe qualys also does it.

**Comment by damiencarol** [comment]
I will compare both reports and try some unit tests. Thanks for providing the data @ealkalai it helps a lot!

**Comment by sguarin** [comment]
Just to note this seems to be still an issue on 2.8.0.

**Comment by manuel-sommer** [comment]
You can close this @mtesauro. I also advanced Snyk to support container scan:
https://github.com/DefectDojo/django-DefectDojo/pull/9289
