### ISSUE TITLE
ssl verification issue for DefectDojo and Jira integration

### ISSUE THREAD

**Issue by tahir59** [DefectDojo/django-DefectDojo#3319]
uwsgi_1         | Starting new HTTPS connection (3): jira.mydomain.local:443
uwsgi_1         | HTTPSConnectionPool(host='jira.mydomain.local', port=443): Max retries exceeded with url: /?verify=false/rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)) while doing GET https://jira.mydomain.local?verify=false/rest/api/2/serverInfo [{'params': None, 'headers': {'User-Agent': 'python-requests/2.25.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json,*.*;q=0.9', 'Connection': 'keep-alive', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json', 'X-Atlassian-Token': 'no-check'}}]

- is there any option in defectdojo to change verify=true to false.
- as an alternative is there any documentation on how to install root ca on defectdojo for Jira integration.
- if no option is present then whats the solution to address this issue.

**Comment by madchap** [comment]
in settings.dist.py there is a variable just for that.

`DD_JIRA_SSL_VERIFY=(bool, True)`

You can override it to `False` to achieve what you want.

**Comment by tahir59** [comment]
and whats the other work around i.e if I want to install my private ca for jira.

**Comment by dsever** [comment]
@tahir59  you can try with:

NOTE: In the case when IDP is configured to use self signed certificate, than CA needs to be specified by define environments variable REQUESTS_CA_BUNDLE that points to the path of public CA certificate.

In that case, in the same file include all certificates that are coming with certify and cert you want to add.  

But it depends if  JIRA is using request python module.

**Comment by tahir59** [comment]
will this solution work on version 1.6.1

**Comment by dsever** [comment]
You need to try it

**Comment by valentijnscholten** [comment]
> will this solution work on version 1.6.1

strongly advised to upgrade as jira integration has been reworked in 1.10.0
