### ISSUE TITLE
Upgrade to 1.9.3 is not working

### ISSUE THREAD

**Issue by BhaskiBuzz** [DefectDojo/django-DefectDojo#3320]
**Bug description**
We are trying to upgrade defectdojo to v1.9.3 from 1.7.1 (docker-compose installation) using the below commands as mentioned in the doc "https://defectdojo.readthedocs.io/en/latest/upgrading.html#upgrading-to-defectdojo-version-1-9-3" . But we are not able to see any real upgrade happening. The version in the dashboard still shows v1.7.1

**Steps to reproduce**
Step 1:
docker-compose exec uwsgi ./manage.py create_endpoint_status

Output:
enabling audit logging
patching TagDescriptor
Popen(['git', 'version'], cwd=/app, universal_newlines=False, shell=None, istream=None)
Popen(['git', 'version'], cwd=/app, universal_newlines=False, shell=None, istream=None)
/usr/local/lib/python3.7/site-packages/django/db/models/fields/__init__.py:1369: RuntimeWarning: DateTimeField Endpoint_Status.date received a naive datetime (2020-11-20 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.7/site-packages/django/db/models/fields/__init__.py:1369: RuntimeWarning: DateTimeField Endpoint_Status.date received a naive datetime (2020-10-29 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.7/site-packages/django/db/models/fields/__init__.py:1369: RuntimeWarning: DateTimeField Endpoint_Status.date received a naive datetime (2020-10-12 00:00:00) while time zone support is active.
  RuntimeWarning)

Step 2: 
docker-compose exec uwsgi ./manage.py buildwatson
Output:
enabling audit logging
patching TagDescriptor
Popen(['git', 'version'], cwd=/app, universal_newlines=False, shell=None, istream=None)
Popen(['git', 'version'], cwd=/app, universal_newlines=False, shell=None, istream=None)
Deleted 0 stale search entry(s) in 'default' search engine.
Deleted 0 stale search entry(s) in 'admin' search engine.
Refreshed 8941 search entry(s) in 'admin' search engine.

**Expected behavior**
Upgrade should happen to v1.9.3 and the version in the dashboard should show v1.9.3

**Deployment method** 
- [ ] Docker

**Environment information**
Linux

**Comment by madchap** [comment]
It sounds like you actually have not updated your container images? Running that command only updates endpoint statuses, but will not update defectdojo.

**Comment by BhaskiBuzz** [comment]
Hi @madchap 
It means, for updating container images, do I need to get the latest code from git and do docker-compose up? else could you please share me the complete steps for upgrade to v1.9.3.

**Comment by navzen2000** [comment]
@madchap Can you please help with standard procedure for upgrade? The documentation is not clear in terms of what all steps need to be followed when upgrading Defect Dojo docker installation.
https://defectdojo.readthedocs.io/en/latest/upgrading.html#upgrading-to-defectdojo-version-1-9-3

Thanks for your help in advance.

**Comment by valentijnscholten** [comment]
> It means, for updating container images, do I need to get the latest code from git and do docker-compose up? 

Yes

**Comment by navzen2000** [comment]
How will the mysql db get upgraded with the latest version info in this case?

**Comment by madchap** [comment]
Django takes care of it for you with the help of migration files you will find under `dojo/db_migrations`. As the image contain new migrations, the database schema will be brought up to date automatically.

You can read more about migrations at https://docs.djangoproject.com/en/2.2/topics/migrations/ and I encourage you to practice upgrading locally first.

**Comment by BhaskiBuzz** [comment]
Hi @madchap I tried upgrading the defectdojo from v1.7.1 to 1.12.0. But the database migration not happened. I could not see the old data anymore in the latest version. 

Steps performed:
1. downloaded the 1.12.0 zip code for git.
2. moved to docker-compose.yml file directory
3. did docker-compose build and docker-compose up -d.
4. logged into the site as admin

Observed that no old data is showing.

**Comment by valentijnscholten** [comment]
Sounds like you're not mounting the correct volume with existing data. You need to run from the same folder where you originally build/ran defect dojo 1.7.1 from.

**Comment by BhaskiBuzz** [comment]
Hi @valentijnscholten 
we have ran from the same folder where we originally ran defectdojo 1.7.1. Now the defectdojo version is showing as 1.12.0 and the old data is available. 
But it seems migration not happened properly. I could not see Burp REST API test type in the "Dashboard ->engagements -> test types" section. Even from API, /test_types/ is not listing the Burp Rest API test type. It was available when I ran/build v1.12.0 from new folder. 

$ docker-compose exec uwsgi /bin/bash -c 'python manage.py migrate'
[03/Feb/2021 05:22:44] INFO [dojo.models:3436] enabling audit logging
Operations to perform:
  Apply all migrations: admin, auditlog, auth, authtoken, contenttypes, django_celery_results, dojo, sessions, sites, social_django, tagging, tastypie, watson
Running migrations:
  No migrations to apply.

![scan types](https://user-images.githubusercontent.com/26956032/106704158-9f6b0400-6611-11eb-996a-6feb93b52443.PNG)
![testtypes_api](https://user-images.githubusercontent.com/26956032/106704165-a134c780-6611-11eb-853f-68c87b170c6c.PNG)
![version](https://user-images.githubusercontent.com/26956032/106704168-a42fb800-6611-11eb-9385-0a6b82250b7d.PNG)

mysql> select * from dojo_test_type where name like '%Burp%';
+-----+-----------------------+-------------+--------------+
| id  | name                  | static_tool | dynamic_tool |
+-----+-----------------------+-------------+--------------+
| 110 | Burp Scan             |           0 |            0 |
| 171 | Burp Suite Enterprise |           0 |            0 |
+-----+-----------------------+-------------+--------------+

**Comment by BhaskiBuzz** [comment]
Hi @valentijnscholten We are able to upgrade to v1.12.0 after build/ran defect dojo from the same folder where we ran 1.7.1
Now the old data also available. It seems its taking some time for database migration. 

Thanks.
