### ISSUE TITLE
Scanner type are not ordered in Swagger

### ISSUE THREAD

**Issue by Wadeck** [DefectDojo/django-DefectDojo#3328]
**Bug description**
The scan type dropdown is not ordered and thus reduce the speed of interaction.

**Steps to reproduce**
1. Go in /api/v2/doc/
1. Find /reimport-scan/
1. Open the select for the scan_type

**Expected behavior**
The list should be ordered, alphabetically ideally :)

**Screenshots** (optional)

<details>

<summary>📷 Screenshot 📷</summary>

![Screenshot_2020-11-23_111617_001](https://user-images.githubusercontent.com/2662497/99950991-ac4fb980-2d7d-11eb-8a7c-45c059ca1b27.png)

</details>

**Comment by damiencarol** [comment]
Hello @Wadeck , I'm refreshing this issue.
Made some tests on last dev and it seems that #3689 solved your pb.
![image](https://user-images.githubusercontent.com/1694940/106258471-26893800-621e-11eb-8f07-ee5a1ccd533f.png)

![image](https://user-images.githubusercontent.com/1694940/106257762-4704c280-621d-11eb-8248-8c6a592b5427.png)

**Comment by Wadeck** [comment]
@damiencarol thanks for the information, I will look at this soon-ish and close the issue :)

**Comment by Wadeck** [comment]
@damiencarol I checked the dev branch and it's 99% good. Even in your screenshot you can see the kube-bench listed at the bottom due to case-sensitive sorting.

From my use case it's perfectly fine 👍

**Comment by tonnyhideyori** [comment]
I would like to get the list of id of all scanners where i can use in found_by

**Comment by damiencarol** [comment]
@tonnyhideyori take a look at `/test_type/` endpoint
