### ISSUE TITLE
ERROR: Service 'uwsgi' failed to build : Error parsing reference: "python:3.6.12-slim-buster@sha256:e5259113df5a7c4dae16ad37c2ca53b1cf722e051cfd5f624e7b76aa72389e0c as build" is not a valid repository/tag: invalid reference format

### ISSUE THREAD

**Issue by gunda-sec** [DefectDojo/django-DefectDojo#3330]
django-DefectDojo]# docker-compose build
mysql uses an image, skipping
initializer uses an image, skipping
rabbitmq uses an image, skipping
celeryworker uses an image, skipping
celerybeat uses an image, skipping
Building uwsgi
Step 1/26 : FROM python:3.6.12-slim-buster@sha256:e5259113df5a7c4dae16ad37c2ca53b1cf722e051cfd5f624e7b76aa72389e0c as build
ERROR: Service 'uwsgi' failed to build : Error parsing reference: "python:3.6.12-slim-buster@sha256:e5259113df5a7c4dae16ad37c2ca53b1cf722e051cfd5f624e7b76aa72389e0c as build" is not a valid repository/tag: invalid reference format

I am using RHEL version 7.9

**Comment by valentijnscholten** [comment]
Sounds like an old docker/docker-compose version. Which versions of those are you running?

**Comment by gunda-sec** [comment]
docker --version
Docker version 1.13.1, build 64e9980/1.13.1
 docker-compose --version
docker-compose version 1.27.4, build 40524192

**Comment by madchap** [comment]
Multi-stage builds were introduced in a docker version more recent than yours. I expect this is the cause of your failure. You'd need to upgrade your docker version.

**Comment by gunda-sec** [comment]
Issue is resolved. Thanks @madchap
