### ISSUE TITLE
add/edit product: jira project config should be checked against JIRA

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#3336]
When adding/editing JIRA Project config for an engagement, a meta data check is done in JIRA to check if the url and project key are valid and Defect Dojo has permissions to access the JIRA project.
A similar check should be added to the add/edit product logic.

**Comment by Maffooch** [comment]
Validated with @XiChen-Tibco and it appears to be fixed

**Comment by sumanth11-ws** [comment]
How can we provide to Defect Dojo has permissions to access the JIRA project.
Getting below error:
Invalid project key or no permissions to this project?

My project key is correct, need to provide permission to this project.
Could you share the steps for the same.

Thanks and Regards
Sumanth
