### ISSUE TITLE
I am confused regarding the "/admin" page. Is this something which is used or not?

### ISSUE THREAD

**Issue by childsc** [DefectDojo/django-DefectDojo#3337]
Hi,

I am still learning defect dojo. 

I was interested in learning about setting up newly defined group access. To provide more fine tuned access rights.

However, after reading a number of issues here (#2536 , #1048 , #2944  etc) I keep coming across sentances like these when refering to /admin

- #2536 currently most of these don't work <-- when referring to the list of permissions
or

- #2944  The django permissions within Django's admin panel will not work in the UI (they could work through the API, because of the way dojo is written today). <-- when referring to the list of permissions

My questions are:

- what exactly is the /admin console used for?

- if this is not in use, why are we able to access it?

- why is there no documentation to say this is implemented or a site not mentioning this functionality has been deprecated?
https://defectdojo.readthedocs.io/en/latest/index.html

Thank you for your time.

**Comment by devGregA** [comment]
Hi @childsc you should not use the admin page. In the near future it's access will be disabled. It's part of the Django framework, which dojo is built off of. Django has changed a lot since 1.1 when dojo started.
