### ISSUE TITLE
APIv2 : Swagger Doc Test Results

### ISSUE THREAD

**Issue by RomainJufer** [DefectDojo/django-DefectDojo#3342]
I post here a first draft of the errors found by the test for the swagger schema. The test works by matching the swagger schema against the result of a query on a given endpoint. It tests the methods : list, read, create, update, partial_update provided that they are supported. Note that it does not check the request schema and currently does not check all the "sub-endpoints" (for example, `/findings/{id}/tags`).

**Results**
- **url :** /engagements/{id}/notes/
**method :** GET, POST,  PATCH
Result model is Engagement while it should be Note
- **url :** /engagements/{id}/accept_risks/
**method :** POST
According to schema it returns a response 201 but in reality it returns a response 200
- **url :** /findings/
**method :** GET
According to schema it returns a Finding but it should returned paginated Finding array
- **url :** /findings/{id}
**method :** GET, PUT, PATCH
request_response field is string according to schema but the value returned is a more complex structure
- **url :** /jira_configurations/
**method :** GET
password is still required but if endpoint queried without being superuser it will not be returned
- **url :** /jira_configurations/{id}
**method :** PATCH
configuration_name has default value blank according to model but does not allow blank value
info_mapping_severity is null but does not allow null value
- **url :** /jira_configurations/{id}
**method :** POST, PUT
same errors as PATCH and GET(above)
- **url :** /jira_configurations/{id}
**method :** GET
same errors as GET
- **url :** /products/
**method :** GET
findings_count is a string according to schema but is an integer
findings_list is a string according to schema but is a list of findings
- **url :** /products/{id}
**method :** GET
same errors as above

In addition, it seems that the endpoint for system settings expect an ID while not really expecting one as the description suggests to always use id=1 ? Furthermore, there is a lot of errors that I did not report here due to fields that are not nullable but for which the response contained a null value. However, upon inspection of the schema they are always for fields that are "read_only" as defined by the openapi standard. So I'm not sure if "read_only" means also nullable or not. According to `https://swagger.io/specification/`, "read_only" means that the property has no guarantee of being sent but it does not say anything about it being null. Does anyone know more about that ?

I will open a PR with the test later in the week as I did not find a way of getting the result of the test without it failing due to assertions.

**Comment by JorisVanEijden** [comment]
> findings_list is a string according to schema but is a list of findings
It's actually an array of integers (finding ids)
