### ISSUE TITLE
ERROR: unsatisfiable constraints

### ISSUE THREAD

**Issue by gunda-sec** [DefectDojo/django-DefectDojo#3351]
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz: BAD signature
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz: BAD signature
ERROR: unsatisfiable constraints:
  openssl (missing):
    required by: world[openssl]
ERROR: Service 'nginx' failed to build : The command '/bin/sh -c apk add --no-cache openssl &&   chmod -R g=u /var/cache/nginx &&   mkdir /var/run/defectdojo &&   chmod -R g=u /var/run/defectdojo &&   mkdir -p /etc/nginx/ssl &&   chmod -R g=u /etc/nginx &&   true' returned a non-zero code: 1

Appreciate your help with this. I am not able to install the tool.

**Comment by valentijnscholten** [comment]
> WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz: BAD signature
> WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz: BAD signature
Looks like your machine is unable to download these files. Could be just a glitch, so try again with --no-cache etc assuming you are using docker-compose. Which version/commit are you using?

**Comment by gunda-sec** [comment]
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

**Comment by valentijnscholten** [comment]
https://github.com/docker-library/golang/issues/286

**Comment by devGregA** [comment]
Closing as this seems to be outside the scope of Dojo. Please use the Slack channel for additional  community assistance or communication.
