### ISSUE TITLE
JIRA - no attribute default_issue_type

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#3354]
On my local test instance, I had no JIRA configured at first, but already 1 product, 4 engagements and some test data.

I then wanted to add JIRA configuration. Usual drill, enable JIRA in system settings, configuration, etc.... I only added the JIRA at the product level, but all engagement showed
![image](https://user-images.githubusercontent.com/5468769/100260176-66dfe780-2f49-11eb-81a6-a2183af02198.png)

I would expect not an error symbol, but just the regular icon maybe that it just inherits from the product level config? But then, maybe something to do with the below. 

When wanting to push to jira a finding within one of these engagements, the 500 error popped up:

```
eleryworker_1  | [25/Nov/2020 17:08:15] ERROR [celery.app.trace:257] Task dojo.jira_link.helper.add_jira_issue[0a1310e4-ba66-4722-a112-435f89398838] raised unexpected: AttributeError("'NoneType' object has no attribute 'default_issue_type'",)
celeryworker_1  | Traceback (most recent call last):
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task
celeryworker_1  |     R = retval = fun(*args, **kwargs)
celeryworker_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__
celeryworker_1  |     return self.run(*args, **kwargs)
celeryworker_1  |   File "/app/dojo/decorators.py", line 72, in __wrapper__
celeryworker_1  |     return func(*args, **kwargs)
celeryworker_1  |   File "/app/dojo/jira_link/helper.py", line 423, in add_jira_issue
celeryworker_1  |     'name': jira_instance.default_issue_type
celeryworker_1  | AttributeError: 'NoneType' object has no attribute 'default_issue_type'
```

I had to actually go in the engagement, and re-specify the JIRA configuration.

**Comment by valentijnscholten** [comment]
the error indicates that there is no default_issue_type specified in your jira_instance. Is that correct? that would be a bug in the pre-existing jira configuration form/wizard.

**Comment by valentijnscholten** [comment]
ok, I can see similar things here. Looks like one of the latest bugfixes broke lots of JIRA stuff.

**Comment by madchap** [comment]
Do you still need more logs from me?

**Comment by valentijnscholten** [comment]
No thanks

**Comment by madchap** [comment]
Tested PR, closing.
