### ISSUE TITLE
Upgrade doc for docker-composed based setup

### ISSUE THREAD

**Issue by cpandya2909** [DefectDojo/django-DefectDojo#3358]
Hi, 

I am using defect-dojo v. 1.6.0 ( release mode ) an want to upgrade to v 1.10.0. I have set it up with docker-compose on my VM with local mysql db.

But I am not sure how to upgrade version with docker-compose without breaking anything and also can not find clear instructions on Doc.

Can you please specify how to perform upgrade with docker-compose?

**Comment by madchap** [comment]
Hey @cpandya2909 

I created some basic steps in https://github.com/DefectDojo/Documentation/pull/158/files. This should help you out.

Of course, I'd advise you to backup first, just in case.

**Comment by devGregA** [comment]
Closing as this appears to be resolved. Please create a new ticket if needed.
