### ISSUE TITLE
no error message when trying to create JIRA on existing finding

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#3369]
**Bug description**
If you **edit** an existing finding, and attempt to **push to jira without having "active, verified" set**, then **you will have no error message,** despite the fact it is needed. Instead, you'd see a "successful" message.

This behavior _does not happen when it's a brand new finding_. If you create a new finding and try to submit it directly to JIRA (unchecking "active" for example), then the error messages are shown, both at the top and next to the missed checkbox at the bottom.
 
**Expected behavior**
The error messages appear whether it's a new or existing finding.

Errors expected to be shown

![image](https://user-images.githubusercontent.com/5468769/100521016-57f37200-31a1-11eb-89dd-713facb0ece6.png)

![image](https://user-images.githubusercontent.com/5468769/100521018-5aee6280-31a1-11eb-9ac5-d2426be0645d.png)

**Deployment method** *(select with an `X`)*
- [x] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
latest dev

**Comment by valentijnscholten** [comment]
Good find. I looked at the code and this is something that looks like it has been like this for a long time, not a blocker to release 1.10.1 I think. To be honest during the JIRA refactoring I have been thinking if it even makes sense to have this rule in place. Maybe in some cases yes as you don't want duplicates and false positives pushed to JIRA.

**Comment by madchap** [comment]
Right. Maybe it could be made less stringent, but something as a "warning" like "Are you sure you want to push a non-active finding?" but still leave the choice to the user. 

For instance, the security team could not be certain and want the product team to "verify" it, so in that case, it'd be good to be able to push an "active only" finding to JIRA (because product team backlog is in their issue tracker, and they won't go verify before having something there in the first place).

**Comment by valentijnscholten** [comment]
Looking at this I found another bug: https://github.com/DefectDojo/django-DefectDojo/issues/3879
