### ISSUE TITLE
Search inside findings tab does not find excerpted value

### ISSUE THREAD

**Issue by Wadeck** [DefectDojo/django-DefectDojo#3375]
**Bug description**
The Search box inside the Findings table (acting as a filter) does take into account only the visible values. It means that when you have a long "name", the value is excerpted to be displayed with some ... at the end. But the filter should take into account the real value, not the displayed one.

You can also check by looking just for "...", which does not appear in any of my data, but due to the excerpt, show lots of findings.

**Steps to reproduce**
1. Go to a test
1. Inside the Findings table
1. Look for a name that is excerpted (the "..." at the end)
1. Try filtering (using the Search box inside the table) with a part that is not displayed
1. It will not appear

**Expected behavior**
The filter should use the real data and not the visible ones.

**Screenshots** (optional)

### The desired finding
![Screenshot_2020-11-30_105501_001](https://user-images.githubusercontent.com/2662497/100595158-d6175c00-32fa-11eb-86d0-43679fe55d32.png)

### Regular filter with its name
![Screenshot_2020-11-30_104639_001](https://user-images.githubusercontent.com/2662497/100594537-1a562c80-32fa-11eb-989f-dc8b5743a89a.png)

### Filtering with "..." for the example
![Screenshot_2020-11-30_105309_001](https://user-images.githubusercontent.com/2662497/100595188-e0395a80-32fa-11eb-8e2d-d5e31ba8c3c7.png)

### Buggy filtering with its CVE due to excerpt
![Screenshot_2020-11-30_105511_001](https://user-images.githubusercontent.com/2662497/100595235-f1826700-32fa-11eb-8866-0bb280ce89af.png)

**Comment by valentijnscholten** [comment]
Please bear in mind this is just a client side filter, so it can only filter on data that is present there. Easiest fix for this particular usecase is to add the CVE column which is present everywhere else where we show lists of findings.

**Comment by valentijnscholten** [comment]
CVE field was added here as fix for the immediate issue at hand.
