### ISSUE TITLE
OWASP DC hash computation is hardcoded

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#3387]
Please enter as much information as possible, otherwise we can't provide support. If possible upgrade to the latest release or dev version and try again.

**Bug description**
The parser does not comply with the default hash computation and cannot be overriden.

https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/dependency_check/parser.py#L20-L23

**Comment by valentijnscholten** [comment]
this is not the hash_code computation but another computation to avoid duplicates inside the scanner itself. not saying it is correct, but it is not used for hash_code computation.

**Comment by damiencarol** [comment]
@valentijnscholten @madchap is it a good way to do it (detecting duplicate in the parser itself)?

**Comment by valentijnscholten** [comment]
Sometimes yes if you have a very noisy scanner with lots of 100% identical vulnerabilities. Sometimes not as it can be confusing :-) Maybe we should think about parametrizing parsers to let users tweak their behaviour, similar to the `detailed` mode we have for some of them

**Comment by damiencarol** [comment]
After analyzing a lot of scanner, I can say that there is no bug here. Just some de-duplication computation from the parser.
