### ISSUE TITLE
Typo in the documentation.

### ISSUE THREAD

**Issue by g0pinath** [DefectDojo/django-DefectDojo#3397]
Please enter as much information as possible, otherwise we can't provide support. If possible upgrade to the latest release or dev version and try again.

**Bug description**
In the document https://defectdojo.readthedocs.io/en/latest/social-authentication.html, under Azure AD section, AZUREAD_TENANT_OAUTH2_ENABLED = True should be DD_SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_ENABLED = True.

Its somewhat obvious but I following the doc as is and realized this by checking settings.dist.py file.

**Comment by valentijnscholten** [comment]
thanks, fixed https://github.com/DefectDojo/Documentation/commit/e5f5ebf621fb2cd186d1d10a49ba1f131cc4fb30#diff-9a4272f1c2c95ef4182f4458be472ec6339c7964d9c58553be365e0d84788ed0
