### ISSUE TITLE
Unable to find location for failed login attempts

### ISSUE THREAD

**Issue by DarkZatarra** [DefectDojo/django-DefectDojo#3398]
I looked all over the place but I was not able to find a location where failed login attempts are stored.

I found audit logs in DB, I found access logs in nginx, but not what I am looking for.

Any guidance?

Thanks

**Comment by valentijnscholten** [comment]
Seems like Django doesn't log those.

**Comment by DarkZatarra** [comment]
> Seems like Django doesn't log those.

As far as I understood they can be added. I can do that but it will take time - which I do don't have at the moment. That's why I was hoping somebody else has it already or can do it faster.
