### ISSUE TITLE
Defect Dojo link in jira ticket

### ISSUE THREAD

**Issue by Dungeon1** [DefectDojo/django-DefectDojo#3400]
How change url of description jira ticket?I want format http://ip:8080/finding/
![image](https://user-images.githubusercontent.com/36472686/100984500-88b71b00-3596-11eb-8de6-666ca39fffbf.png)

**Comment by rookies** [comment]
You can set this using the `DD_SITE_URL` environment variable.

**Comment by Gby56** [comment]
To help out people stuck maybe on Kubernetes, there was an issue related to this where the env variable was not set in containers https://github.com/DefectDojo/django-DefectDojo/issues/6422
