### ISSUE TITLE
Menu on "small" screens are not visible

### ISSUE THREAD

**Issue by ycrumeyrolle** [DefectDojo/django-DefectDojo#3401]
Defect Dojo has new features, it is great, but... 
On my laptop (screen resolution 1980x1080, scaling at 150%) the menu items on the bottom are not visible, as shown on the picture:
![image](https://user-images.githubusercontent.com/1958836/100990804-98ad0b80-3552-11eb-9aa0-8c511fa5193f.png)

Seen on version 1.10.2, but it was already true on version 1.5.

**Comment by valentijnscholten** [comment]
yeah, I've seen this too. Let's hope some front-end css / javascript savy dev is around to look at it.

**Comment by damiencarol** [comment]
Same pb here. I used "Zoom out" feature of my browser. not perfect but... I agree with @valentijnscholten ,  the UI could use some refresh 😅
