### ISSUE TITLE
Configurable log levels when deploying in a K8S cluster

### ISSUE THREAD

**Issue by bgoareguer** [DefectDojo/django-DefectDojo#3403]
**Is your feature request related to a problem? Please describe**
When deploying DefectDojo in a K8S cluster, there is no way to change the default log levels that are configured in files such as settings_dist.py, or the extra configuration files.

**Describe the solution you'd like**
At least I would like to be able to set log levels when deploying DefectDojo. I would then be able to just set the log levels in the values.yaml and these log levels would be applied.

**Describe alternatives you've considered**
It would be even better if the log levels could be changed while the containers are running, without restart.

**Comment by valentijnscholten** [comment]
I think this is now resolved with DD_LOG_LEVEL
