### ISSUE TITLE
Support Scoutsuite (Open source CSPM)

### ISSUE THREAD

**Issue by mrn42** [DefectDojo/django-DefectDojo#3409]
Hi team,

It would be great to support reports from cloud security auditing tools like Scoutsuite or Cloudsploit, so we can have a complete overview of the security to share with product/devops teams.

https://github.com/nccgroup/ScoutSuite 
https://github.com/aquasecurity/cloudsploit  

Best,

**Comment by damiencarol** [comment]
@mrn42 do you have some kind of report with this tool? JSON, CSV, XML format? an API to collect data?

**Comment by devGregA** [comment]
New tool requests need to have sample scans. Feel free to resubmit with sample scans.
