### ISSUE TITLE
Add Flag for Initializer Container Entrypoint to Not Exit Upon Completion

### ISSUE THREAD

**Issue by tohch4** [DefectDojo/django-DefectDojo#3421]
**Is your feature request related to a problem? Please describe**

When I use `docker-compose` or other AWS ECS Fargate deployments using supplied containers, it would be ideal to perform maintenance operations, scripted or manual, from the preexisting initializer container. Since this containers always exit upon completion, it must be restarted or (more applicable to cloud deployments) recreated.

**Describe the solution you'd like**

As a DevOps engineer that tests and deploys production workloads using docker, to better facilitate automated and manual maintenance work on the application or database, I would like a flag, using environmental variables, to default to exiting on completion of the initializer container, or optionally allow to leave it running for ongoing use.

**Describe alternatives you've considered**
Alternatives are manually working around container exits and restart or recreating containers, but for sustained development and production workloads, especially in the cloud, this is irritating.

**Additional context**
More context [in discussion with developers in OWASP #defectodojo-dev thread](https://owasp.slack.com/archives/C014H3ZV9U6/p1607054267297300).

**Comment by madchap** [comment]
This sounds like a bit of an anti-pattern. The initializer is made to initialize, not perform subsequent maintenance operations.

What operations are you thinking about?

**Comment by tohch4** [comment]
> This sounds like a bit of an anti-pattern. The initializer is made to initialize, not perform subsequent maintenance operations.

Hence I do not make it the default behavior? :-P
 
> What operations are you thinking about?

Jokes aside, we often run deployments in ECS, we can set up another task, but it is just more to do so with the existing change for this one minor difference. It just is a dead task because it completes, and keeping it warm would mean less hassle for me, maybe potentially others?

Whether local `docker-compose` or ECS as described, I then have to build another container with all the proper configuration and secrets in another place, and I'd rather not sprawl it elsewhere (especially the latter), and I'd rather not run administrative operations in the UWSGI app container itself, but maybe that is not worthwhile?

What kind of operations? Essentially anything I would need to do with `manage.py`. So,

- Account resets
- Data migrations
- Using `dbshell`
- AdHoc data load and data dumping (`dumpdata` and `loaddata`)

I could put it elsewhere, but in our cases sometimes it is convenient. How are you and others handling these things? Separate util container or just shelling in?
