### ISSUE TITLE
jira: Epic name field required error when pushing finding

### ISSUE THREAD

**Issue by Dungeon1** [DefectDojo/django-DefectDojo#3442]
When i pushing finging on Jira software he required epic name. I set up epic name id. Epic name it required field on Jira. How i can set up on Dojo this field?

**Comment by valentijnscholten** [comment]
What happens if you do the steps from the docs? https://defectdojo.readthedocs.io/en/latest/features.html?highlight=jira#jira-integration

**Comment by Dungeon1** [comment]
I complete all steps. Jira integration works. I can pushing all issue type(Task, story, bug, security etc), but cant epic. On Jira epic issue have required fields: theme and epic name. Theme is name of finding, but epic name i dont know and Dojo may be too. Epic name id(10102, default) on Jira settings on Dojo correctly set up, because he pushing finding but got error "Epic name required".

**Comment by valentijnscholten** [comment]
So are you trying to push a finding to JIRA as an epic? Or are you creating an epic from an engagement? The first one won't work because findings don't send epic name. The second one should work.

**Comment by valentijnscholten** [comment]
If there's an exception when pushing to JIRA, defect dojo prints the metadata from JIRA. Can you paste it here? Maybe we can easily set the epic name field if we see that it is present in the metadata.

**Comment by Dungeon1** [comment]
> So are you trying to push a finding to JIRA as an epic?
Yes

> Or are you creating an epic from an engagement?

How i can this do?

**Comment by Dungeon1** [comment]
I want create issue on Jira with subtask for each hosts. It's real with Dojo?

**Comment by Dungeon1** [comment]
> Can you paste it here?

fields from Jira is too much and i can't give information from pre-prod jira

**Comment by valentijnscholten** [comment]
epic name should be fixed by https://github.com/DefectDojo/django-DefectDojo/pull/3609

**Comment by valentijnscholten** [comment]
In #3782 we fixed the engagement to epic mapping which allows you to have all findings in an engagement be part of an Epic.
Please let us know if this solves your usecase.
