### ISSUE TITLE
Support SARIF (OASIS Static Analysis Results Interchange Format)

### ISSUE THREAD

**Issue by damiencarol** [DefectDojo/django-DefectDojo#3445]
**SARIF parser**
SARIF represents a leap forward in the usability of static analysis tools. Many organizations in the safety and security communities use several competing tools on their code. SARIF will allow them to combine and compare the results more easily to gain a sharper picture of the issues in their code that need to be addressed. Engineering teams will be able to easily access a broad range of potential defects and vulnerabilities in compliance with privacy and accessibility standards. SARIF will support the development of products whose code spans languages and operating systems.

[OASIS TC](https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=sarif)
[Official Spec](https://github.com/oasis-tcs/sarif-spec)

**Sample File**
From spec github:
[https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Documents/ScratchSamples/179-311.sarif](https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Documents/ScratchSamples/179-311.sarif)
[https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Documents/ScratchSamples/314-338.sarif](https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Documents/ScratchSamples/314-338.sarif)

**Comment by tohch4** [comment]
I'd be super excited to help with this @damiencarol. See DefectDojo/django-DefectDojo#2720 for previous discussion, but I thought there little or not interest. If there are two of us, I would like to move this forward!

**Comment by valentijnscholten** [comment]
it sounds interesting, don't think anybody noticed there was discussion around this in another PR.

**Comment by tohch4** [comment]
I am very interested in this space, I can look into on the weekend and revive previous draft efforts, unless @damiencarol wants to work it with us or for us, I will try and move ahead.

My main question: this is not tied to an import type anymore, and is more generalized. `semgrep` obviously supported, but a variety of static analysis tools have rapidly ramped up support after Github and Gitlab had announced integration in their APIs.

So how do we annotate the import correctly to allow SARIF to be used in abstract but concretely explain the tool that did the analysis and serialized it, @valentijnscholten?

**Comment by damiencarol** [comment]
@tohch4 @valentijnscholten Thanks a lot for your feedback. I'm pushing a branch with a minimum viable code and unit tests.
Take a look at the big SARIF report. It's a scan of DefectDojo itself... 😆 

⚠️  One thing that bothers me is that SARIF support multiple items which are "Test" in DefectDojo but the current code doesn't allow that (a parser that create data in more than one Test)

**Comment by damiencarol** [comment]
pushed some code to cover this issue #3464

**Comment by damiencarol** [comment]
@tohch4 if you can find me more SARIF exemple files, it could be very usefull.

**Comment by damiencarol** [comment]
@tohch4 @valentijnscholten pushed more code with more unit tests.
Waiting for feedback.

@tohch4 : if you want to contribute/improve you can fork my branch and/or copy/paste some code from my work. I'm open to any contribution.

**Comment by tohch4** [comment]
@damiencarol, I'll look later this afternoon, thanks! The last time I did this, I generated samples from `semgrep`. It seems [I added SARIF output after all](https://github.com/DefectDojo/sample-scan-files/commit/f1e1df958b67c25d8f3d12709c26b3b4e6d9e489#diff-649497b0b7549e8d0d54865051d2413e28e8321d2f93ea031f5c29991a7eb703). Let me think of other places to go with it!

**Comment by valentijnscholten** [comment]
@damiencarol can this be closed as the PR has been merged?

**Comment by damiencarol** [comment]
Yep @valentijnscholten
