### ISSUE TITLE
Burp suite json format

### ISSUE THREAD

**Issue by whitespots** [DefectDojo/django-DefectDojo#3447]
**Scanner Name**
Burp Suite **Pro**

**Sample File**
[example.json](https://github.com/DefectDojo/django-DefectDojo/files/5673899/example.txt)

**Where is a problem with existing reporters?**
They don't support json and burp can not export it's results in xml via REST API. 
It makes integration very difficult.

**Why is it important?**
It can be integrated in CI/CD in docker (will update this ticket with an example).
But it is required to import it in DefectDojo to make the process simple and support this tool as well as another tools.

PS. It is also required for building metrics
https://www.youtube.com/watch?v=6FGV4OcrIB8&t=2s

**Comment by whitespots** [comment]
https://github.com/whitespots/burp_docker

**Comment by damiencarol** [comment]
@whitespots is Burp able to export to SARIF format?

**Comment by httpnotonly** [comment]
I think it is not possible to return anything else in API :)

**Comment by damiencarol** [comment]
I can take a look but maybe a small script in Python that get data from API and push it to DefectDojo API is an easy solution (we do that with BlackDuck Hub at my company)

**Comment by damiencarol** [comment]
@whitespots I love your video :D .    the exemple rpeort in JSON is from the API of Burp Suite Pro?

**Comment by whitespots** [comment]
Thanks :)
Exactly, it is from REST API

**Comment by damiencarol** [comment]
@valentijnscholten you can assign it to me, I will work on an importer for this one.

**Comment by damiencarol** [comment]
@whitespots I will need more reports and/or documentation of the API. For now, the scan you provided only shows "info" severity findings.

**Comment by damiencarol** [comment]
@whitespots I made another shot this week-end. I enable to launch you Docker file and have an empty instance.
I'm adapting a new importer for these data.

**Comment by httpnotonly** [comment]
Sorry, have a new year weekend (all team)
Btw. Best wishes 🙂

**Comment by damiencarol** [comment]
@httpnotonly @whitespots PR is merged.

**Comment by whitespots** [comment]
So, it will be even in master now :)
Thanks, will test it.
BTW, it would be cool to have an article to see how can we deploy the, dev version.

**Comment by valentijnscholten** [comment]
no it's not in master. the readme links to the docker document which explains the different modes you can run in: https://github.com/DefectDojo/django-DefectDojo/blob/master/DOCKER.md

**Comment by whitespots** [comment]
@valentijnscholten got it
Just need to read carefuly
https://github.com/DefectDojo/django-DefectDojo/blob/master/DOCKER.md#run-with-docker-compose-in-development-mode-with-hot-reloading

**Comment by whitespots** [comment]
Rename to .json 
[sample.txt](https://github.com/DefectDojo/django-DefectDojo/files/5836475/sample.txt)

**Comment by damiencarol** [comment]
ok. thanks for the report, will work on a quick fix.

**Comment by damiencarol** [comment]
@whitespots fixed with https://github.com/DefectDojo/django-DefectDojo/pull/3657 if you can take a look at the Findings produced and make some feedback it could be good.

**Comment by whitespots** [comment]
![image](https://user-images.githubusercontent.com/65983771/105148549-f524b400-5b1b-11eb-8248-03a6fe80fe02.png)
Done!

**Comment by whitespots** [comment]
Issue description is ok as well. Maybe it will be good to have raw request details somewhere, but burp has quite good descriptions and we should take some time to live with existing functionality.
![image](https://user-images.githubusercontent.com/65983771/105156170-e7bff780-5b24-11eb-974d-5aaf624bfc4c.png)

**Comment by damiencarol** [comment]
@whitespots excellent! 
It will be better to rely on the next release IMO. we plan to release it next week.
For the `raw request details` feature, I'm working on it.
There are few things that we need to work on before adding more features for parser robustess.

**Comment by damiencarol** [comment]
Hello @whitespots long time no see..
Finally the #4025 was merged in `dev` branch. This PR implements de-duplication and add the feature you requested (request+response details in the findings)
This will be part of `0.14.0` (release at the end of march)

**Comment by whitespots** [comment]
Ah, it was just ok and we met no problems with current integration :)

**Comment by damiencarol** [comment]
awesome. Are you on release `1.13.0` ?

**Comment by whitespots** [comment]
Yes
There are another more critical problems with mobsf and some 500 in interface :)

**Comment by damiencarol** [comment]
do we have issues created that follow these problem with mobsf ?

**Comment by whitespots** [comment]
.. It is closed.
Need to reopen on the last version
https://github.com/DefectDojo/django-DefectDojo/issues/3134

Guys from mobsf changed the report in last version

**Comment by damiencarol** [comment]
arf. I asked them if they can use a standard like SARIF or whatever. It's hard to maintain when they are changing everything all the time.
