### ISSUE TITLE
Search using tag on Test/Engagement

### ISSUE THREAD

**Issue by Wadeck** [DefectDojo/django-DefectDojo#3451]
**Is your feature request related to a problem? Please describe**
In our instance, we are using tags. We are using them with external scripts to do various stuff from reporting to auto-managing the findings.

On the finding, we are using tags about the status inside our internal process.

On the test, we are using tags about specific part of the products impacted.

On an engagement, we are using tags to separate the source of the scan, between customer, our team, other team, etc.

**Describe the solution you'd like**
We would like to do a search for existing finding with any of the tags on the parent levels. 
E.g. finding about CVE-XXX, inside a test with given tag or equivalent for an engagement.
That will help us reduce the number of results of the search that are not directly useful for us.

**Describe alternatives you've considered**
The current workaround is to look at the full list of result and due to the size of the search results it's quickly annoying.

cc @valentijnscholten @madchap

**Comment by valentijnscholten** [comment]
@Wadeck I think the search improvements should help as you can search on `product-tags: xxx`, `engagement-tags:xxxx` etc now. Also the list of findings is now paged and the max results can be tweaked in `settings.py`.

**Comment by madchap** [comment]
Correct, also in the filters.

@Wadeck I'll let you close if that's satisfying enough for you.

**Comment by Wadeck** [comment]
Really nice, a tagged engagement will reveal also the parent product 🎉
