### ISSUE TITLE
encrypt connection to external/on premise MySQL

### ISSUE THREAD

**Issue by saldam72** [DefectDojo/django-DefectDojo#3472]
Hello Team,
I have deployed DefectDojo 1.10.4 on Kubernetes cluster with an external/on premise MySQL and I want to encrypt database connection. How can I do ?

Best
Sal

**Comment by saldam72** [comment]
> Hello Team,
> I have deployed DefectDojo 1.10.4 on Kubernetes cluster with an external/on premise MySQL and I want to encrypt database connection. How can I do ?
> 
> Best
> Sal

Hello Team,
in addition to encrypting the connection to the database I would like to know whether it is possible to encrypt the entire database to ensure data confidentiality (data at rest, data in transit ...)

Best
Sal

**Comment by saldam72** [comment]
Hello Team,
sorry but by mistake I closed it unintentionally.

best
Sal

**Comment by saldam72** [comment]
Hello Team,
we have deployed DefectDojo on a kubernetes cluster with ax external MySQL. How can we encript database connection ? How can we encrypt all database (data at rest) ?

Best,
Sal

**Comment by damiencarol** [comment]
@saldam72 the issues in github are not for support. use our Slack channel please.
