### ISSUE TITLE
UI artifact about number of columns for review message

### ISSUE THREAD

**Issue by Wadeck** [DefectDojo/django-DefectDojo#3475]
Reproduction:
- Request a review from a finding
- Come back to the finding view

Expectations:
- Number of columns match and there is no "hole"

![Screenshot_2020-12-15_182650_001](https://user-images.githubusercontent.com/2662497/102249971-3dd8c400-3f03-11eb-9cfa-5049b5bb9f9f.png)

**Comment by madchap** [comment]
you're such a nitpick :-D

**Comment by valentijnscholten** [comment]
No need to hide screenshots BTW
