### ISSUE TITLE
Large Test Data Set for Performance and Load Monitoring

### ISSUE THREAD

**Issue by tohch4** [DefectDojo/django-DefectDojo#3478]
**Is your feature request related to a problem? Please describe**
As discussed with @valentijnscholten and others in OWASP Slack and elsewhere, there is a need for larger size datasets that can be loaded into a testing environment to perform ad hoc load and performance testing.

**Describe the solution you'd like**
As a developer, in order to perform load test and performance test a DefectDojo instance and enhance its usability, I would like to be able to load a fixture in the database or load similar data through API into a DefectDojo instance to test use of the application with/without ongoing API load of data while users manipulate findings or look at metrics/reports.

**Describe alternatives you've considered**
There are a few approaches, I am not 100% sure which one is the most appropriate at this time. More to come given conversation with my colleagues and Valentijn today.

**Additional context**
[This Slack thread](https://owasp.slack.com/archives/C014H3ZV9U6/p1607017908290300?thread_ts=1607017384.289400&cid=C014H3ZV9U6) and ongoing conversation about defectdojo/django-DefectDojo#3207 and testability of performance enhancements in general.

**Comment by tohch4** [comment]
As discussed, I am willing to take on development work around this moving forward, to those devs that can assign! :-)

**Comment by valentijnscholten** [comment]
I think it would be usefule to have some kind of non-sensitive / anonymous larger data set which "people" can use to test their PRs against. We sometimes see PRs that are working fine, but can be (very) slow on medium to large instances.

**Comment by tohch4** [comment]
After discussing with @danielnaab and company, I realized I can try two two approaches, one more than I planned on.

1. A quick and dirty fixture script in JSON format to load a fun amount of data, easy but slow.
1. A [`bulk_create`](https://docs.djangoproject.com/en/3.1/ref/models/querysets/#bulk-create) utility script/class, potentially as a django-admin `manage.py` command to build a larger dataset on the fly with bulkier `dumpdata` `loaddata` fixtures generated in place that have-hard coded primary keys for `dojo.finding`/`Finding` objects and having to munge.
1. (Distant future): deidentification component unless people holler and see that is what they really looking for, beyond Valentijn of course! :-)

**Comment by madchap** [comment]
> After discussing with @danielnaab and company, I realized I can try two two approaches, one more than I planned on.
> 
> 1. A quick and dirty fixture script in JSON format to load a fun amount of data, easy but slow.

Will not work, I went down that path. Fixtures are only for smaller sets.

> 2. A [`bulk_create`](https://docs.djangoproject.com/en/3.1/ref/models/querysets/#bulk-create) utility script/class, potentially as a django-admin `manage.py` command to build a larger dataset on the fly with bulkier `dumpdata` `loaddata` fixtures generated in place that have-hard coded primary keys for `dojo.finding`/`Finding` objects and having to munge.

I think my comment for 1. will also apply here. Fixtures are no good for big load or perf tests.

> 3. (Distant future): deidentification component unless people holler and see that is what they really looking for, beyond Valentijn of course! :-)

I was successful in doing some fairly OK data anon placing myself in the middle of my prod database and some target database doing a mysqldump with over 500K findings, using proxysql and something like https://gist.github.com/madchap/1c0f19ae5a26849e8ae8c734d83975a3 to anon the data. It was a quick hack and worked OK for my use-case back then. It works only with MySQL though (I then since moved to PGSQL). I have not investigated it any further, but this worked well.

**Comment by damiencarol** [comment]
I'm wondering if it could be easier to generate with a script very big reports in a real format.
With a scale in size 5Mo, 10, 100, 250, 500, 1G.
We can even add it it integration tests by pushing them to the endpoint `/import-scan​/`

**Comment by valentijnscholten** [comment]
It's not about having 1 big report and upload it. It's about having Lots of products, lots of engagements, lots of tests, lots of findings. All of different types. So a real world like scenario / dataset.

**Comment by tohch4** [comment]
Sorry, I know I have been slow on fleshing out the intended behavior. I discussed the latter with @valentijnscholten. I got busy with other things and will do it later this week or early next week for the core ask: load the data into the database directly.

I will definitely want to discuss the approach you discussed, @damiencarol.

**Comment by damiencarol** [comment]
> It's not about having 1 big report and upload it. It's about having Lots of products, lots of engagements, lots of tests, lots of findings. All of different types. So a real world like scenario / dataset.
@valentijnscholten for this one I have another idea. I have a script that scans a Docker repository and creates automatically project+engagement CI/CD+test based on few tools like Dependancy Check .
You can see some output on the demo server => https://demo.defectdojo.org/product/5/engagements/cicd 
I can commit this script or we can launch it on a specific demo env dedicated to perf load

**Comment by tohch4** [comment]
Sorry, I have not forgotten, but I have some work priorities that kept me away. I will report back between now and later next week with working code or I shall be scolded! :-)
