### ISSUE TITLE
iOS MobSF report import to DefectDojo doesn't work

### ISSUE THREAD

**Issue by ZsanettMagyar** [DefectDojo/django-DefectDojo#3479]
**Bug description**

I have a MobSF iOS report in json format and we try to import it to DefectDojo, but it can't parse the json, so we can't se the results in DefectDojo.

DefectDojo version: v. 1.10.1 ( release mode ) 
    deployed with docker-compose
   commit:  [2020-11-29 15:50:10 +0100] a585f90f: Merge pull request #3370 from DefectDojo/release/1.10.1 [ (HEAD -> master, tag: 1.10.1, origin/master, origin/HEAD)]

MobSf version: Version v3.1.6 Beta

JSON file size: >2MB (2146019)

DefectDojo uwsgi log:

> [pid: 26|app: 0|req: 416/804] 172.19.0.11 () {44 vars in 685 bytes} [Wed Dec 16 08:24:34 2020] GET /api/v2/tests/?limit=10&offset=80 => generated 3993 bytes in 56 msecs (HTTP/1.0 200) 7 headers in 215 bytes (1 switches on core 1)
> [pid: 26|app: 0|req: 417/805] 172.19.0.11 () {44 vars in 685 bytes} [Wed Dec 16 08:24:34 2020] GET /api/v2/tests/?limit=10&offset=90 => generated 2028 bytes in 34 msecs (HTTP/1.0 200) 7 headers in 215 bytes (1 switches on core 0)
> ERROR:django.request:Internal Server Error: /api/v2/reimport-scan/
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
>     response = get_response(request)
>   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
>     return view_func(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/rest_framework/viewsets.py", line 125, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
>     response = self.handle_exception(exc)
>   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
>     self.raise_uncaught_exception(exc)
>   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
>     raise exc
>   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
>     response = handler(request, *args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/rest_framework/mixins.py", line 19, in create
>     self.perform_create(serializer)
>   File "./dojo/api_v2/views.py", line 1081, in perform_create
>     serializer.save(push_to_jira=push_to_jira)
>   File "./dojo/api_v2/serializers.py", line 1186, in save
>     data['scan_type'],)
>   File "./dojo/tools/factory.py", line 198, in import_parser_factory
>     parser = MobSFParser(file, test)
>   File "./dojo/tools/mobsf/parser.py", line 86, in __init__
>     "title": details[1],
> KeyError: 1

Our json is valid according to https://jsonformatter.curiousconcept.com/ (RFC 8259)
JSON MobSF generation:
curl -X POST --url http://localhost:8000/api/v1/report_json --data "hash=*****" -H "Authorization:*****" > iOS.json

**Comment by ZsanettMagyar** [comment]
Maybe it's related to https://github.com/DefectDojo/django-DefectDojo/issues/3134 
But in our case, DefectDojo can process an Android analysis JSON file, but not the iOS.

**Comment by valentijnscholten** [comment]
@ZsanettMagyar seems like the same issue and should (could) be fixed in dev. Are you able to try against the `dev` branch?

**Comment by ZsanettMagyar** [comment]
@valentijnscholten I tried, but it's not working:

> [pid: 20|app: 0|req: 21/31] 172.19.0.3 () {64 vars in 1558 bytes} [Wed Dec 16 16:08:31 2020] GET /test/2/re_import_scan_results => generated 52196 bytes in 76 msecs (HTTP/1.1 200) 7 headers in 369 bytes (1 switches on core 0)
> [16/Dec/2020 16:08:41] ERROR [dojo:673] 1
> Traceback (most recent call last):
>   File "./dojo/test/views.py", line 664, in re_import_scan_results
>     parser = import_parser_factory(file, test, active, verified)
>   File "./dojo/tools/factory.py", line 198, in import_parser_factory
>     parser = MobSFParser(file, test)
>   File "./dojo/tools/mobsf/parser.py", line 85, in __init__
>     "title": details[1],
> KeyError: 1
> [16/Dec/2020 16:08:41] ERROR [dojo:674] Error in parser: 1

DefectDojo version: v. 1.11.0-dev ( release mode )

**Comment by valentijnscholten** [comment]
@damiencarol or @ZsanettMagyar  are you able to check out the error and make a PR? might be something simple like a field not always being present.

**Comment by damiencarol** [comment]
@valentijnscholten I can take this one. It is similar to the #3134 bug that I fixed with #3429 (same kind but not the same attribute).
I will push a PR today.
@ZsanettMagyar could you provide a report? it helps a lot.

**Comment by ZsanettMagyar** [comment]
@damiencarol report is attached. Thanks!

[ios.zip](https://github.com/DefectDojo/django-DefectDojo/files/5707862/ios.zip)

**Comment by valentijnscholten** [comment]
Ideally we add a unit test, which would also make it easier for others to maintain this parser.

**Comment by damiencarol** [comment]
@valentijnscholten @ZsanettMagyar I will add the 2 reports and a specific unit test to check your high severity issues. If you can give me the IDs of the findings in the report that are not detected it will help me also.

**Comment by ZsanettMagyar** [comment]
@damiencarol  these are the IDs of the missing android findings:

- android_insecure_random
- android_md5
- android_webview_debug
- android_hardcoded
- android_temp_file
- android_aes_ecb
- android_read_write_external
- android_sql_raw_query
- android_sha1
- android_insecure_ssl

**Comment by damiencarol** [comment]
@ZsanettMagyar @valentijnscholten my analysis:
1) There is an error during import because @ZsanettMagyar uses version 3.1.6 of MobSF and there only have unit tests for 3.1.9 reports.
2) @ZsanettMagyar see that for imports that work, there are no security issues. It comes from another implementation limitation: in the current version all findings are imported as "Info" (hardcoded)

I'm preparing a pull request fixing these 2 errors

**Comment by ZsanettMagyar** [comment]
@damiencarol I would like to ask you to delete the test files (https://github.com/DefectDojo/django-DefectDojo/pull/3490#issuecomment-747505407). Our customer checked it, and wouldn't like to publish it.

Thank you for your help earlier and sorry for asking for the extra "fix".

**Comment by damiencarol** [comment]
@ZsanettMagyar it's ok. I will push another file. And by the way, I'm preparing a PR that will take into account some data specific to Android (like `code_analysis.android_*`)

**Comment by ZsanettMagyar** [comment]
@damiencarol I can't find any commit about the test file deletion. Could you please delete it?

**Comment by ZsanettMagyar** [comment]
MobSF import works in the new version of DefectDojo.
