### ISSUE TITLE
OSSIndex DevAudit SCA Scanner

### ISSUE THREAD

**Issue by bp4151** [DefectDojo/django-DefectDojo#3520]
**Scanner Name**

OSSIndex DevAudit Source Composition Analysis Scanner

- https://ossindex.sonatype.org/
- https://github.com/sonatype-nexus-community/DevAudit

**Sample File**
json format
[devaudit_results.zip](https://github.com/DefectDojo/django-DefectDojo/files/5725083/devaudit_results.zip)

**Comment by bp4151** [comment]
I've never worked on an open source project before. I am happy to code this myself if someone is willing to provide some guidance as to the process...

**Comment by valentijnscholten** [comment]
Thanks for the offer. If you look a [CONTRIBUTING.md](https://github.com/DefectDojo/django-DefectDojo/blob/master/CONTRIBUTING.md) and [DOCKER.md](https://github.com/DefectDojo/django-DefectDojo/blob/master/DOCKER.md) you'll see some instruction on starting the docker-compose setup in dev mode.

Adding a parser is not too hard, easiest is to look at these two examples to see what is needed:
https://github.com/DefectDojo/django-DefectDojo/pull/1115
https://github.com/DefectDojo/django-DefectDojo/pull/679

**Comment by damiencarol** [comment]
a pull request is in progress for this issue https://github.com/DefectDojo/django-DefectDojo/pull/3570
