### ISSUE TITLE
[APIv2] cvssv3 considered mandatory

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#3526]
When testing something random, with an empty string

```
{
  "cvssv3": [
    "This field may not be blank."
  ]
}
```

**Comment by damiencarol** [comment]
@madchap what's the issue here? That's the attribute is mandatory?

**Comment by madchap** [comment]
Actually, non blank. Got that whenever I was testing things with the apiv2 swagger and prepopulated json with all fields. It is actually probably warranted, just quickly created this before I forget, but it should be OK. Will go ahead and close.
