### ISSUE TITLE
Scan tags are not populated on reupload.

### ISSUE THREAD

**Issue by devGregA** [DefectDojo/django-DefectDojo#3563]
**Bug description**
Scan tags are not populated on reupload.

**Steps to reproduce**
1. Upload a scan and set a tag.
2. When reuploading, the tag is missing in the form and is deleted.

**Expected behavior**
Tags previously added should be populated in the re-upload form.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ X ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Dev

**Sample scan files** (optional)
Any Sample scan will work.

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

**Comment by valentijnscholten** [comment]
I saw and noted this behaviour during the tagulous migration, but didn't want to change behaviours then. I think it makes sense to display any existing tags so they are A) retained and B) can be editted

**Comment by valentijnscholten** [comment]
fixed in dev / 1.12.0, let me know if there's anything more to do here.
