### ISSUE TITLE
Custom Report Generation--Hostname Error

### ISSUE THREAD

**Issue by njfox** [DefectDojo/django-DefectDojo#357]
PR #353 was supposed to fix this issue but I've noticed with further testing it does not when the local Defect Dojo server does not resolve the hostname being parsed in the client Host HTTP header.

I've done some digging and I'm having trouble coming up with a robust way to solve this problem. The error below indicates that a request from 127.0.0.1 (wkhtmltopdf?) is attempting to resolve the external hostname dojo locally and failing:

```[2017-09-07 18:38:38,312: INFO/MainProcess] Received task: dojo.tasks.async_pdf_report[df5d7c95-ba39-4bea-9cd0-45b944dcb0b1]
[2017-09-07 18:38:41,147: ERROR/MainProcess] Task dojo.tasks.async_pdf_report[df5d7c95-ba39-4bea-9cd0-45b944dcb0b1] raised unexpected: IOError(u'wkhtmltopdf reported an error:\nError: Failed loading page http://dojo:80/reports/cover?info=Generated+By+%28admin%29+on+09%2F07%2F2017+11%3A38PM+UTC&subtitle=Engagement%3A+Test2+%28Sep+01%2C+2017%29&title=Engagement+Report (sometimes it will work just to ignore this error with --load-error-handling ignore)\nExit with code 1 due to network error: HostNotFoundError\n',)
Traceback (most recent call last):
  File "/home/nick/dojo/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/nick/dojo/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/nick/django-DefectDojo/dojo/tasks.py", line 102, in async_pdf_report
    raise e
IOError: wkhtmltopdf reported an error:
Error: Failed loading page http://dojo:80/reports/cover?info=Generated+By+%28admin%29+on+09%2F07%2F2017+11%3A38PM+UTC&subtitle=Engagement%3A+Test2+%28Sep+01%2C+2017%29&title=Engagement+Report (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1 due to network error: HostNotFoundError
```
I thought about modifying report_url_resolver in reports/views.py to always use 'localhost' as the hostname, but I'm afraid that might cause issues in a situation where multiple vhosts are listening on the same port. That would also require adding 'localhost' to ALLOWED_HOSTS in settings.py in addition to any external hostnames you want to use. It might be possible to modify report.sh to do this.

I've also tried setting the hostname to request.META['SERVER_NAME'], but that caused the request url to be http://:80/ in the request above.

Does anyone have any thoughts on how to efficiently deal with this?

edit: It turns out request.META['SERVER_NAME'] is correctly reading the server name when the `server_name` directive is set in the nginx configuration. The only issue is that the user will have to add an entry to /etc/hosts for wkhtmltopdf to successfully make the request. Perhaps we could make this change to reports/views.py and update the documentation to note that if the server is not the default vhost, you'll need to set the `server_name` directive in nginx and add a hosts entry to generate custom reports?

**Comment by devGregA** [comment]
@mtesauro will address this issue as part of the summit

**Comment by codedestructor** [comment]
@njfox , @devGregA 
Hi.. I found out same issues.
How to get fix?

**Comment by devGregA** [comment]
I beleive this is fixed from one of Aaron Weaver's recent PR's please reopen if this is still an issue.
