### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by breckwoldt** [DefectDojo/django-DefectDojo#3571]
Hello, can anybody explain the update process. I looked at the docu and have try it but the Version doesnt change. 

Kind regards

**Comment by valentijnscholten** [comment]
what happens when you follow https://defectdojo.readthedocs.io/en/latest/upgrading.html (and provide more details as requested in the template).

**Comment by madchap** [comment]
Please come chat on Slack for help. It's better for a possible lively conversation (unless you're Edgar on Slack, then it's done already).
