### ISSUE TITLE
jira: add support for personal access tokens

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#3599]
JIRA Server 8.14 and later can use personal access tokens to authenticate against the API instead of passwords.
Passwords via basic authentication will be deprecated, so we should support this new authentication method.

We are using the `jira` package for python, so filed an upstream feature request: https://github.com/pycontribs/jira/issues/993

Please note these personal access tokens are slightly different from the JIRA Cloud api tokens (thank you atlassian).

Cloud: `curl -H "Authorization: Basic <base64(<username>:<yourToken>>)" https://{jiraBaseUrl}/rest/api/`

Server: `curl -H "Authorization: Bearer <yourToken>" https://{jiraBaseUrl}/rest/api/`

**Comment by mattmedus** [comment]
Hi, I'm trying to integrate DD with Jira Server through personal access token. Is this possible?
