### ISSUE TITLE
Any user can retrieve all users data

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#3607]
Via the APIv2 `users/` endpoint it's possible to retrieve a list of all users, inluding details such as permission level, email address, last login:

```
    {
      "id": 5,
      "username": "valentijn",
      "first_name": "Valentijn",
      "last_name": "Scholten",
      "email": "valentijn.scholten@isaac.nl",
      "last_login": "2020-11-03T22:48:59.681817+01:00",
      "is_active": true,
      "is_staff": true,
      "is_superuser": true
    },
```

If you have a big instance with multiple teams or possibly even some of your clients with an account, this might be not ideal.

Should we considered either making the whole `/users` endpoint only for staff / superusers? Or, 
Should we consider returning the email + last_login + permission fields only to staff users (https://pypi.org/project/django-rest-serializer-field-permissions/)

What do you think?

**Comment by valentijnscholten** [comment]
I think APIv1 suffers from the same issue.

**Comment by madchap** [comment]
I think blanket access to staff and above is enough at first. Oneself should be able to query own login info if possible.

**Comment by valentijnscholten** [comment]
I think in the UI a user who is authorized for a product and staff flag has been enabled for authorized users, they can also see all users in the autocomplete for product settings user fields. I think that's OK, but we could mimic that in the API.

**Comment by mtesauro** [comment]
I agree that the API and UI should be in sync as mentioned ^

**Comment by valentijnscholten** [comment]
The requirement to be admin has been added recently: https://github.com/valentijnscholten/django-DefectDojo/commit/1709a583e8ffe8bc6ee4e2c8c4b8af376b530c7c#diff-c3e4e472bb522533ceae23de0978562b7370477002222332ac59b248be27d4edR1297

Side effect is that the defect dojo api wrapper we have now no longer works for non-admin users. The standard process is to retrieve the list of users to verify the user id / name before uploading a scan.

**Comment by kiblik** [comment]
Isn't this issue fixed?

**Comment by valentijnscholten** [comment]
Yes, and even better with the new authorization V2.
