### ISSUE TITLE
Deduplicate findings not working once enabled 

### ISSUE THREAD

**Issue by dania-abbas** [DefectDojo/django-DefectDojo#3611]
once i enabled the Deduplicate findings feature the celery worker not working probably, and the status of the celery becomes not processing and stuck. check the celery worker logs and it gives the following Worker exited prematurely: signal 9 (SIGKILL). Same as described here https://defectdojo.readthedocs.io/en/latest/running-in-production.html#celery-worker and i have changed the DD_CELERY_WORKER_POOL_TYPE to prefork but same error and same issue. please help on this so i could use the Deduplicate findings feature ?

**Comment by damiencarol** [comment]
@dania-abbas you should use our Slack channel for this kind of support questions : https://join.slack.com/t/owasp/shared_invite/zt-g398htpy-AZ40HOM1WUOZguJKbblqkw

**Comment by valentijnscholten** [comment]
Link to slack that won't expire: https://owasp-slack.herokuapp.com/

**Comment by thepatcher** [comment]
Hi, is there a solution for this problem?
I'm seeing the same error messages in my k8s cluster.

**Comment by valentijnscholten** [comment]
the solution is to discuss at slack
