### ISSUE TITLE
reimport: Error in parser: get() returned more than one Endpoint -- it returned 2!

### ISSUE THREAD

**Issue by BhaskiBuzz** [DefectDojo/django-DefectDojo#3612]
**Bug description**
While trying to upload webinspect xml report, I am getting error "Error in parser: get() returned more than one Endpoint -- it returned 2!"
**Steps to reproduce**
1. Create new test case with test type as Microfocus Webinspect Scan
2. upload the xml report. 

**Deployment method** *(select with an `X`)*
- [ ] Docker

**Environment information**
linux 64 bit
**Console logs** (optional)
Traceback (most recent call last):
  File "./dojo/test/views.py", line 587, in re_import_scan_results
    parser = import_parser_factory(file, test, active, verified)
  File "./dojo/tools/factory.py", line 232, in import_parser_factory
    parser = MicrofocusWebinspectXMLParser(file, test)
  File "./dojo/tools/microfocus_webinspect/parser.py", line 107, in __init__
    self.process_endpoints(finding, host)
  File "./dojo/tools/microfocus_webinspect/parser.py", line 136, in process_endpoints
    path=path
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 412, in get
    (self.model._meta.object_name, num)
dojo.models.Endpoint.MultipleObjectsReturned: get() returned more than one Endpoint -- it returned 2!
Error in parser: get() returned more than one Endpoint -- it returned 2!
[pid: 1|app: 0|req: 29/270] 127.0.0.1 () {58 vars in 1466 bytes} [Mon Jan 11 06:58:05 2021] POST /test/216/re_import_scan_results => generated 0 bytes in 7124 msecs (HTTP/1.1 302) 8 headers in 467 bytes (17 switches on core 0)

**Comment by damiencarol** [comment]
Hello @BhaskiBuzz , thanks for reporting this one. Are you able to provide the XML (or an anonymized version) that produced this is the error? it helps a lot to debug and/or understand what's going on.

**Comment by damiencarol** [comment]
@BhaskiBuzz do you have access to the DB? could you check that there is no 2 endpoint with the same protocol+host+query+fragment+path ? it could come from the code not managing well when we have 2 endpoints with the same protocol+host+query+fragment+path

**Comment by valentijnscholten** [comment]
please populate the template correctly. Which version are you running? This error was "quick-fixed" in 1.11.0 via https://github.com/DefectDojo/django-DefectDojo/pull/3531 for uploads via the UI. Can you confirm you version and if it's fixed in 1.11.0?

**Comment by BhaskiBuzz** [comment]
@damiencarol @valentijnscholten thanks for the response. I can't share the document as it is internal. we are using version 1.7.1. we will try to upgrade the version for having the fix provided. 

thanks.

**Comment by BhaskiBuzz** [comment]
@damiencarol could you please help me with the query to check the endpoints in the DB.

**Comment by damiencarol** [comment]
pushed this PR to improve the WebInspect parser https://github.com/DefectDojo/django-DefectDojo/pull/3621

**Comment by damiencarol** [comment]
@BhaskiBuzz have you be able to update to a more recent version? we merged a modification of this parser that could fix your pb.

**Comment by BhaskiBuzz** [comment]
@damiencarol I did query for endpoint with the same protocol+host+query+fragment+path and then deleted the duplicate row. Then the issue got resolved. I will try upgrading to the recent version.

**Comment by damiencarol** [comment]
@BhaskiBuzz a more recent version have a fix that avoid this kind of duplicate in the parser. But good to know that you fixed your data.

**Comment by damiencarol** [comment]
Part of `1.12.0` release
