### ISSUE TITLE
proper fix needed for duplicate endpoints / multipleobjects returned

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#3613]
As described in #3612 multiple endpoint objects can be returned during re_import. This was somewhat fixed in #3531 But only for UI reimports and not for the API. And it would be better to find out / fix the issue at the core, i.e. more db constraints at the EndPoint model and/or better create/insert logic.

**Comment by kiblik** [comment]
This was fixed in #4473. But please double-check.

**Comment by kiblik** [comment]
Can we close this issue?
