### ISSUE TITLE
1.12.0: add prs between 1.11.0 and 1.11.1 to release notes

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#3628]
All the PRs merged into dev between 1.11.0 and 1.11.1 are not listed by release drafter, so we have to add them manually when releasing.

https://github.com/release-drafter/release-drafter/issues/756

**Comment by valentijnscholten** [comment]
I created a fork of the release draftw with intention of fixing the behaviour, but it's not so easy because the release draft has lots of different scenario's it supports (except ours).
For now, I have added a second release drafter workflow that can be triggered manually and performs the behaviour we want: 
![image](https://user-images.githubusercontent.com/4426050/105577516-75485500-5d7a-11eb-8e28-45bf171cbe09.png)

Instructions:
- Do all the release stuff like creating release branch, merging to master, build/push/etc.
- Make sure the draft release has the correct next version number (i.e. 1.12.0 or 1.11.2)
- Run 'Release drafter Valentijn' (without any input parameters)

It should list the correct PRs on the release notes. For 1.12.0 everything since 1.11.0. For 1.11.2 everything since 1.11.1.

Pleaes note that there is a seperate bug in the release drafter: https://github.com/release-drafter/release-drafter/issues/766

**Comment by madchap** [comment]
So to not get that wrong, tomorrow, the first field would read `1.12.0` (or maybe remain empty?) and the previous release `1.11.0` ?

**Comment by valentijnscholten** [comment]
Yes, should list all prs front 29/12 onwards

**Comment by valentijnscholten** [comment]
updated the release instructions, so closing this.
