### ISSUE TITLE
[Question] Benchmark progress / repeat audit

### ISSUE THREAD

**Issue by eL-Prova** [DefectDojo/django-DefectDojo#3630]
Hi all,

We audit our applications (over 50) based on the ASVS. I was looking for the option to use DefectDojo benchmark to keep an eye on the progress. It is very nice to have a quick overview and see risks or checks which are not done yet.
But the benchmark seems to be for once, instead of report and do it again to see progression.
Is it possible to create a benchmark, freeze the report and start a new benchmark? This will also give a good idea for all applications where failed items are and how many in the full product/project suite.

Best regards

**Comment by valentijnscholten** [comment]
please discuss on slack.
