### ISSUE TITLE
User interface for Product Types is very different from other objects like Products

### ISSUE THREAD

**Issue by StefanFl** [DefectDojo/django-DefectDojo#3640]
**Is your feature request related to a problem? Please describe**
The user interface for Product Types looks and behaves very different compared to other areas of DefectDojo, eg.:

- Actions in the list of Product Types are buttons and not a drop down menu
- There is no view dialogue
- Delete is a button in the edit dialogue and deletes the Product Type without further warning

**Describe the solution you'd like**
Have Product Types behave like the other objects:

- Have 'Add Product Type' and 'All Product Types' in the main menu together with the existing 'Add Product' and 'All Products'
- Actions in the list of Product Types can be chosen with a drop down menu, that is accessible by clicking on an ellipsis at the front of the list
- Implement a view dialogue, showing the attributes and a list of products
- Add a description to the product type, similar to products
- Make delete an action on its own, with a delete dialogue showing the relationships, similar to products

If you agree to this idea, I would implement it soon.

**Comment by valentijnscholten** [comment]
Sounds good to me, thank you for contributing.

**Comment by damiencarol** [comment]
@StefanFl I'm interested to see this work. I saw that one thing that breaks the update to Django 3.x is linked to ProductType.
So if you need help to test/review/contribute I'm here.

**Comment by StefanFl** [comment]
@damiencarol I generated a draft PR, there you can see what I have done. Any remark is highly welcome

**Comment by valentijnscholten** [comment]
if you're ready, please add some screenshots to the PR :-)

**Comment by StefanFl** [comment]
### Extended main menu

![2021-01-19 21_49_40-DefectDojo](https://user-images.githubusercontent.com/2698502/105092259-50fe2700-5aa1-11eb-8230-cdfe6f34eb55.png)

### No buttons in product type list anymore but a drop down menu

![2021-01-19 21_51_05-Product Type List _ DefectDojo](https://user-images.githubusercontent.com/2698502/105092260-5196bd80-5aa1-11eb-842e-0f3c29283440.png)

### New product type view dialogue

![2021-01-19 21_53_56-View Product Type _ DefectDojo](https://user-images.githubusercontent.com/2698502/105092250-4fccfa00-5aa1-11eb-8be5-5aac689c866c.png)

### New attribut ``Description`` 

![2021-01-19 21_54_26-Edit Product Type _ DefectDojo](https://user-images.githubusercontent.com/2698502/105092255-50659080-5aa1-11eb-8c13-a5587b90e95c.png)

### New delete dialogue

![2021-01-19 22_06_08-Delete Product Type _ DefectDojo](https://user-images.githubusercontent.com/2698502/105093249-b56db600-5aa2-11eb-8c47-9e8cf450f5df.png)

**Comment by damiencarol** [comment]
@StefanFl awesome work. will take time to review.

**Comment by valentijnscholten** [comment]
Looks good!

**Comment by StefanFl** [comment]
The PR is ready for review and all current changes of the dev branch are incorporated.

**Comment by valentijnscholten** [comment]
fixed
