### ISSUE TITLE
Use seperate requirements file for unit/integration tests (non-prod)

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#3641]
Some dependencies we install with pip are only needed for unit tests, for example `PYYaml`. Which is vulnerable.
Would be good if our `release` mode docker images do not install these unneeded packages. 
Bonus is some space + buildtime is saved.

For inspiration: https://stackoverflow.com/questions/17803829/how-to-customize-a-requirements-txt-for-multiple-environments

**Comment by damiencarol** [comment]
In my previous projects, I used to see a `requirements.dev.txt` file or `dev_requirements.txt`
