### ISSUE TITLE
Creating a project without jira info show warning

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#3653]
**Bug description**
While creating a project on an instance that has system level JIRA enabled, creating the new product fails on the first try.

![image](https://user-images.githubusercontent.com/5468769/105006234-a94c0f00-5a36-11eb-92d9-618bd67c6987.png)

Something has to be specified for the project to be created.

However, as you're back on the edit product page, just saving it works.

Trying to reproduce it, subsequent attempts were not successful in reproducing this bug...

**Steps to reproduce**

This error is not always reproducible :man_shrugging: 

1. Enable JIRA system-wide
2. Go create a product
3. Do not enter anything for JIRA

**Expected behavior**
A product can be created without having to specify a JIRA setup.

**Deployment method** *(select with an `X`)*
- [x] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
Latest `dev`.

**Comment by madchap** [comment]
Actually, creating really a new project triggers the issue. No server side error, however.

**Comment by valentijnscholten** [comment]
I can't reproduce it. It's also covered by an integration tests, which succeeds.

**Comment by valentijnscholten** [comment]
what do the logs say?
![image](https://user-images.githubusercontent.com/4426050/105079702-1213a580-5a90-11eb-9d0a-e50fff2e08c1.png)

**Comment by madchap** [comment]
Not much yea

```
uwsgi_1         | [23/Jan/2021 09:22:59] DEBUG [dojo.forms:2113] validating jira project form
uwsgi_1         | [23/Jan/2021 09:22:59] DEBUG [dojo.jira_link.helper:1045] <ul class="errorlist"><li>__all__<ul class="errorlist nonfield"><li>Cannot save JIRA_Project without JIRA_Instance</li></ul></li></ul>
```

**Comment by madchap** [comment]
I rebuilt on latest dev, the first product to be added worked, then I tried again, and it failed with the above.

**Comment by valentijnscholten** [comment]
can you provide some more logs? and info on what you are putting in the fields on the form? this is really fragmented that doesn't provide a complete picture. It could be related to the "has_changed" function of the form, what do the logs say about this:
![image](https://user-images.githubusercontent.com/4426050/105575602-1b8d5e00-5d6d-11eb-9cdd-6d3190dcea71.png)

**Comment by valentijnscholten** [comment]
and maybe add `    logger.debug('jform changed_data: ' + str(jform.changed_data()))` in there

**Comment by valentijnscholten** [comment]
Updated the title because I think the product is created, but there's this incorrect warning about the JIRA config. Correct?

**Comment by madchap** [comment]
It seems you're right, seems only going through product_type to add triggers the error.

**Comment by valentijnscholten** [comment]
madchap told me he can no longer reproduce after 3692
