### ISSUE TITLE
Smart Upload

### ISSUE THREAD

**Issue by devGregA** [DefectDojo/django-DefectDojo#366]
This feature is to add a 'smart upload function' from the main menu that will take a scan and attempt to assign findings to the correct product. If there is an unrecognized endpoint, the user should be prompted to choose which product it should be assigned to. A new test / engagement should be created around 'smart upload' for each scan that is uploaded in this fashion.

**Comment by devGregA** [comment]
Concerns:
Private IP Conflicts

**Comment by devGregA** [comment]
AKA multi-product infrastructure scan

**Comment by devGregA** [comment]
Support subnets as endpoints?

**Comment by devGregA** [comment]
Should try to qualify by host and & IP for an endpoint

**Comment by devGregA** [comment]
Can we include an AWS tag?

**Comment by devGregA** [comment]
Front loading product selection vs at end review.

**Comment by bwu-tang** [comment]
This would probably solve the assignment of findings to multiple products. That seems like it would get to the end goal of breaking it up. How would it associate the actual engagement/assessment to the product itself? Would it duplicate the engagement as well in these cases?
