### ISSUE TITLE
replace API

### ISSUE THREAD

**Issue by devGregA** [DefectDojo/django-DefectDojo#368]
TastyPi's integration makes our API have crazy paths to submit data. Some of the docs are also being generated incorrectly. I suggest we replace our API with Django Rest: http://www.django-rest-framework.org/

**Comment by martinmarsicano** [comment]
In OWASP SKF backend that is written in Python, Restplus is used. It make really easy to define the URL were the API will respond to each function, what parameters to expect and what message to return if an error occurred.
