### ISSUE TITLE
search product by AND condition on multiple tags

### ISSUE THREAD

**Issue by saldam72** [DefectDojo/django-DefectDojo#3680]
Hello Team,
I have two products:
- product1 with tag1
- product2 with tag1 and tag2

If I search products by tag1 and tag2 I got both of them. Is it a bug ? Is it by design ?

best,
Sal

**Comment by madchap** [comment]
You mean that when you search like for `tag:tag1 tag:tag2` in the search box, you'd want to only see results for product2, correct?

**Comment by saldam72** [comment]
yes

**Comment by saldam72** [comment]
hello team,
is there any news?

best,
Sal
