### ISSUE TITLE
full risk acceptance via API

### ISSUE THREAD

**Issue by saldam72** [DefectDojo/django-DefectDojo#3681]
Hello Team,
how can I add full risk acceptance via API ? If it can't be done, can you implement such feature ?

Best,
Sal

**Comment by madchap** [comment]
You cannot at the moment, the feature is only present in the UI.

**Comment by saldam72** [comment]
Will you implement this feature ?

**Comment by saldam72** [comment]
News ?

**Comment by damiencarol** [comment]
@saldam72 don't know well this part, will relay your request to the mods
