### ISSUE TITLE
Allow enabling/disabling of parsers/scanners

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#3701]
Couple of people on Slack have asked me they would like to limit the set of scanners (parsers) users can use, i.e. the type of reports that can be uploaded. Reasons being that they feel some scanners are not good enough or generate too many false positives. Other reasons are they don't trust certain parsers afraid of XML injections etc.

**Comment by devGregA** [comment]
@damiencarol  are you working on this? If not I think I have some resources.

**Comment by damiencarol** [comment]
Fixed with #5084 
There is 2 ways to exclude a parser. With the settings or in DB (flag `active` of the Test_type)
