### ISSUE TITLE
Sonarqube import - "Error while parsing the report, did you specify the correct scan type?"

### ISSUE THREAD

**Issue by lucaverderame** [DefectDojo/django-DefectDojo#3725]
Dear all,
I'm experiencing a problem with the import of a **Sonarqube** report generate using [https://github.com/soprasteria/sonar-report.git](https://github.com/soprasteria/sonar-report.git). 

The report has been generated using the following command:

`sonar-report \
  			--sonarurl="http://172.17.0.1:9000" \
  			--sonarcomponent="DevSecOps" \
  			--project="DevSecOps Project" \
  			--sonartoken="<api_key>" \
  			--sinceleakperiod="false" \
  			--fixMissingRule="true" \
  			--noSecurityHotspot="true" \
  			--allbugs="true" > sonar.html
`
The corresponding sonar.html file has been successfully generated ![Screenshot_2021-01-27 SonarQube Vulnerability Report](https://user-images.githubusercontent.com/16080554/106012805-13f6ed80-60bc-11eb-855e-90745de26c29.png))

Now I'm stuck in the importing phase using the DefectDojo API. Using the command:

`curl -X POST "http://172.17.0.1:8081/api/v2/import-scan/" -H  "accept: application/json" -H "Authorization: Token 6fb3abcb97c8b970c840b9685ef2e41508008bc4" -H  "Content-Type: multipart/form-data" -H  "X-CSRFToken: B9oWt7gJxUNBA7H4y4UYnBeqQPs6ra5luEEDFxjpN6hlcxpDSgoe651sikKOCOnA" -F "scan_date=2021-01-27" -F "minimum_severity=Info" -F "active=true" -F "verified=true" -F "scan_type=SonarQube Scan detailed" -F "file=@sonar.html;type=text/html" -F "engagement=4" -F "close_old_findings=true" -F "push_to_jira=false"
`
I'm receiving the following error: `{"detail":"Error while parsing the report, did you specify the correct scan type ?"}`
I've also tried to 

1. change the scanner type (i.e., "SonarQube")
2. use the API gateway

Still I'm getting the same error. Can you please help me?

**Configurations**
SonarQube Version 8.6.0.39681
DefectDojo v. 1.11.1 ( release mode )

**Comment by valentijnscholten** [comment]
do you see any other exceptions in the logs? might be that they are swallowed as there are some problems with some recent changes to the error handling.

**Comment by valentijnscholten** [comment]
BTW I have no idea if the report you're generating is the right way to do it, but I created a PR to stop the swallowing of exceptions.
If you want you can build the branch from that PR and see if it provides a better error messsage this time.

**Comment by lucaverderame** [comment]
Hi thank you very much, I will give a try to see if I can catch something. 

At the moment the log does not seem to raise specific exceptions.

<img width="2059" alt="Schermata 2021-01-27 alle 18 02 28" src="https://user-images.githubusercontent.com/16080554/106026696-6f2fdc80-60ca-11eb-9490-28a6546a6cfa.png">

**Comment by damiencarol** [comment]
@lucaverderame for the sake of the test, is it possible to have your report file? Are you able to upload it in the UI, by hand ?

**Comment by lucaverderame** [comment]
> @lucaverderame for the sake of the test, is it possible to have your report file? Are you able to upload it in the UI, by hand ?

Dear @damiencarol yes, I've tried with the UI by hand selecting "Sonarqube Scan" and "Sonarqube Scan detailed" in two distinct attempts with "An error has occurred in the parser, please see error log for details". 

In the logs I can know spot the following exceptions.

With **"Sonarqube Scan detailed"**:

```
nginx_1         | 2021/01/28 15:25:54 [warn] 7#7: *15590 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000047, client: 172.18.0.1, server: , request: "POST /engagement/4/import_scan_results HTTP/1.1", host: "localhost:8081", referrer: "http://localhost:8081/engagement/4/import_scan_results"
uwsgi_1         | [28/Jan/2021 15:25:54] ERROR [dojo:600] must be str, not NoneType
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "./dojo/engagement/views.py", line 593, in import_scan_results
uwsgi_1         |     parser = import_parser_factory(file, t, active, verified)
uwsgi_1         |   File "./dojo/tools/factory.py", line 196, in import_parser_factory
uwsgi_1         |     parser = SonarQubeHtmlParser(file, test, 'detailed')
uwsgi_1         |   File "./dojo/tools/sonarqube/parser.py", line 29, in __init__
uwsgi_1         |     self.items = self.get_items(tree)
uwsgi_1         |   File "./dojo/tools/sonarqube/parser.py", line 64, in get_items
uwsgi_1         |     vuln_references = self.get_references(vuln_rule_name, vuln_details)
uwsgi_1         |   File "./dojo/tools/sonarqube/parser.py", line 170, in get_references
uwsgi_1         |     rule_references += "\n" + a.text
uwsgi_1         | TypeError: must be str, not NoneType
uwsgi_1         | [28/Jan/2021 15:25:54] ERROR [dojo:601] Error in parser: must be str, not NoneType
nginx_1         | 172.18.0.1 - - [28/Jan/2021:15:25:54 +0000] "POST /engagement/4/import_scan_results HTTP/1.1" 302 0 "http://localhost:8081/engagement/4/import_scan_results" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0" "-"
```

With **"Sonarqube Scan"**:

```
nginx_1         | 2021/01/28 15:27:04 [warn] 7#7: *15590 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000048, client: 172.18.0.1, server: , request: "POST /engagement/4/import_scan_results HTTP/1.1", host: "localhost:8081", referrer: "http://localhost:8081/engagement/4/import_scan_results"
uwsgi_1         | [28/Jan/2021 15:27:05] ERROR [dojo:600] must be str, not NoneType
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "./dojo/engagement/views.py", line 593, in import_scan_results
uwsgi_1         |     parser = import_parser_factory(file, t, active, verified)
uwsgi_1         |   File "./dojo/tools/factory.py", line 194, in import_parser_factory
uwsgi_1         |     parser = SonarQubeHtmlParser(file, test)
uwsgi_1         |   File "./dojo/tools/sonarqube/parser.py", line 29, in __init__
uwsgi_1         |     self.items = self.get_items(tree)
uwsgi_1         |   File "./dojo/tools/sonarqube/parser.py", line 64, in get_items
uwsgi_1         |     vuln_references = self.get_references(vuln_rule_name, vuln_details)
uwsgi_1         |   File "./dojo/tools/sonarqube/parser.py", line 170, in get_references
uwsgi_1         |     rule_references += "\n" + a.text
uwsgi_1         | TypeError: must be str, not NoneType
uwsgi_1         | [28/Jan/2021 15:27:05] ERROR [dojo:601] Error in parser: must be str, not NoneType
nginx_1         | 172.18.0.1 - - [28/Jan/2021:15:27:05 +0000] "POST /engagement/4/import_scan_results HTTP/1.1" 302 0 "http://localhost:8081/engagement/4/import_scan_results" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0" "-"
```

To perform the evaluation I'm using an insecure application [https://github.com/veracode/verademo](https://github.com/veracode/verademo). You can download the generated html export here: [https://filesender.garr.it/?s=download&token=e4b840f4-fcf9-4a63-bfed-495bdcc56cee](https://filesender.garr.it/?s=download&token=e4b840f4-fcf9-4a63-bfed-495bdcc56cee)

Later today I will try to use the PR created by valentijnscholten to see If I can catch something more also in the import through the API.

Thanks your your support

**Comment by damiencarol** [comment]
@lucaverderame it's possible that you catch a bug here. I will at least integrate this report to our unit tests.

**Comment by valentijnscholten** [comment]
I think testing my branch won't give anymore information as all it does is showing the exception instead of swallowing it. So good idea by @damiencarol to test in the UI. Looks like clear bug.

**Comment by damiencarol** [comment]
@lucaverderame @valentijnscholten tested on last branch dev . Saw a bug with this report. I was able to do a one line fix.
I'm preparing a PR to fix it.

**Comment by damiencarol** [comment]
@lucaverderame it's fixed in dev branch, you will have it in the next release.
