### ISSUE TITLE
finding: add fields for owasp top 10 qualifier (version & category)

### ISSUE THREAD

**Issue by saldam72** [DefectDojo/django-DefectDojo#3736]
Hello Team,
can you add owasp version & category to the finding information ?

Best,
Sal

**Comment by valentijnscholten** [comment]
What do you mean by "OWASP Version & Category"?

**Comment by saldam72** [comment]
We try to map a finding with OWASP TOP 10 (A1, A2 ...) but OWASP TOP 10 changes over the years (2013, 2017 ...) therefore we need a field to store the version and another to store category (at the moment we store this information in a finding tag)

**Comment by damiencarol** [comment]
I have some ideas to integrate that @valentijnscholten @saldam72  . Not by adding another column in Finding but as new tables.
Something like that:

![image](https://user-images.githubusercontent.com/1694940/106381945-7140b680-63bc-11eb-952d-54b8ab0c36a4.png)

**Comment by valentijnscholten** [comment]
I don't think we should complicate things and maybe focus on an easy to use 'meta data' solution so people can add their own key/value pairs to findings and other models. And query/report on them.
I think CVE and CWE are always needed to be readily available on the finding without having to join 2 extra tables.

@saldam72 did you consider using CWE to OWASP Top 10 mapping? Not sure if it is helpful as it would hide the original CWE, but wanted to make sure you saw it: 

![image](https://user-images.githubusercontent.com/4426050/106382078-66d2ec80-63bd-11eb-96c1-5136c0e4f6ec.png)

**Comment by saldam72** [comment]
Hello Team,
we have evaluated this solution but, for example, there are some CWE that should be mapped with A1 and they are not:

- File: 22, 23, 73, 501, 610, 99, 96, 97. 243, 863, 631, 98
- DoS - Threads: 400, 395, 476, 366, 705, 114, 404, 434, 730, 511, 821, 572, 185, 20, 372, 362
- Code: 94, 95, 170, 676, 470, 382, 246, 506, 662, 113, 705, 473, 695, 126, 499, 573, 594, 86
- Date: 200, 349, 612, 434 314, 471
- Overflow: 190, 823
- Log: 117 

We are currently using two finding tags to store this information but we would prefer to have ad-hoc fields.

best,
Sal

**Comment by damiencarol** [comment]
There is also another pb with CWE with the current model. Sometimes a finding could be liked to more than one CWE. But our data model only allow one.
