### ISSUE TITLE
Follow up for #3707  remove numerical_severity

### ISSUE THREAD

**Issue by manuel-sommer** [DefectDojo/django-DefectDojo#3758]
In #3707 , s_finding_severity_naming is removed:
`s_finding_severity_naming =
        models.BooleanField(default=False, blank=False,
                            help_text='With this setting turned on, Dojo '
                                      'will display S0, S1, S2, etc in most '
                                      'places, whereas if turned off '
                                      'Critical, High, Medium, etc will '
                                      'be displayed.')`

As a follow up, shouldn't then also "get_numerical_severity" and "numerical_severity" be removed?
`numerical_severity = models.CharField(max_length=4,
                                          verbose_name="Numerical Severity",
                                          help_text="The numerical representation of the severity (S0, S1, S2, S3, S4).")`

**Comment by valentijnscholten** [comment]
from what I remember it is used for some weird stuff and comparisons in some places, but if you can make a PR that passes all the tests in the test suite that would be good start :-D
