### ISSUE TITLE
Dropboxes should always have the values listed in consistent order

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#3765]
**Is your feature request related to a problem? Please describe**
Currently in full risk acceptance (might be elsewhere too, didn't pay attention), the "Owner" dropdown box lists users in whatever order. It's super hard to find the name you're looking for.

**Describe the solution you'd like**
The list should be ordered in alphabetical order to facilitate finding the value.

Also, it should not list users who no longer have any rights (e.g. basically disabled users).

**Comment by valentijnscholten** [comment]
The ordering part is fixed in #3812

**Comment by valentijnscholten** [comment]
see any other unordered dropdowns?
