### ISSUE TITLE
The Debug toolbar does not load when enabled and DefectDojo runs in Debug mode

### ISSUE THREAD

**Issue by nlandais** [DefectDojo/django-DefectDojo#3771]
If you add the debug_tools to the list of installed in your local settings, you'll notice that the login page does not load and the debug information provided points to the fact that the URL cannot be found.
Suggested fix, include the debug_toolbar urls to the list of url patterns

**Comment by valentijnscholten** [comment]
We don't want to include/enable the debug toolbar by default. To enable it locally is documented, for example here: https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/settings/template-local_settings
