### ISSUE TITLE
tag settings not working i.e. DD_FORCE_LOWERCASE_TAGS

### ISSUE THREAD

**Issue by saldam72** [DefectDojo/django-DefectDojo#3776]
Hello Team,
I have added to the extraConfigs section of the helm/values.yaml file the following two extra variables, but the DD_FORCE_LOWERCASE_TAGS variable seems to be ignored

- DD_MAX_TAG_LENGTH: '100'
- DD_FORCE_LOWERCASE_TAGS: 'false'

Best,
Sal

**Comment by valentijnscholten** [comment]
Those settings are no longer available with our new tag library (`tagulous`). Can you make a PR to remove them from the settings?

**Comment by saldam72** [comment]
OK, but DD_MAX_TAG_LENGTH works... I've been lucky ? :-)

**Comment by valentijnscholten** [comment]
These are the defaults (255 max length). If you change it you may need to do some stuff with migrations. https://radiac.net/projects/django-tagulous/documentation/installation/#settings
