### ISSUE TITLE
api should return not only active findings for product

### ISSUE THREAD

**Issue by saldam72** [DefectDojo/django-DefectDojo#3777]
Hello Team,
we want to integrate DefectDojo with an internal system via API. That system needs to know all the findings of a product: active, not active, false positive & so on. Can you change the behaviour of the Product API https://cr.rete.poste/api/v2/products/{product_id}/ so that it will be able to return all the findings's id ?

Best,
Sal

~~Hello Team,~~
~~if I send a request to https://cr.rete.poste/api/v2/products/{product_id}/, I get only active findings in findings_list, is it correct ?~~
~~Best,~~
~~Sal~~

**Comment by valentijnscholten** [comment]
Please come to slack to discuss these kinds of questions https://owasp-slack.herokuapp.com/ #defectdojo channel

**Comment by saldam72** [comment]
I have done another test (see image below)
![image](https://user-images.githubusercontent.com/72754155/106721391-e6063180-6604-11eb-806f-4752020b74ae.png)
If I invoke product API with product_id 245 I get this response (see abstract below)
{
  "id": 245,
  "findings_count": 1,
  "findings_list": [
    3897,
    3898,
    3900,
    3901
  ],
  "tags": [],
  "product_meta": [],
  "name": "TEST_PRODUCT_1",
  "description": "TEST_PRODUCT_1",

As you can see there is't finding set as a false positive which have 3899 id

**Comment by valentijnscholten** [comment]
Yes, that's what confirmed above. It only returns active findings.

**Comment by saldam72** [comment]
would it be possible to change this behavior returning all findings with their status?

**Comment by valentijnscholten** [comment]
I suggest to create a new github issue or update this one with a clear description of what you want to be implemented.

**Comment by saldam72** [comment]
Hello Team,
we want to integrate DefectDojo with an internal system via API that needs to know all the findings of a product (active, not active, false positive & so on). Can you chage the behavior of the API https://cr.rete.poste/api/v2/products/{product_id}/ so that IDs of all findings are returned ?

Best,
Sal

**Comment by valentijnscholten** [comment]
I updated the title and description for you

**Comment by nightshiba** [comment]
In case someone is wondering how to work around this issue:
```python3
class DefectDojoAPI:
    def __init__(self):
        self.url = os.getenv('DD_URL')
        self._headers = {'Authorization': 'Token ' + os.getenv('DD_API_KEY'),
                         'Content-type': 'application/json'}
        self._ssl_verification = os.getenv('DD_SSL_VERIFY', 'true').lower() == 'true'

        retries = requests.adapters.Retry(total=5, backoff_factor=0.1, status_forcelist=[500, 502, 503, 504])
        self._session.mount('http://', requests.adapters.HTTPAdapter(max_retries=retries))
        self._session.mount('https://', requests.adapters.HTTPAdapter(max_retries=retries))

        self._product_url = self.url + '/api/v2/products/'
        self._dojo_group_url = self.url + '/api/v2/dojo_groups/'
        self._test_url = self.url + '/api/v2/tests/'
        self._engagement_url = self.url + '/api/v2/engagements/'
        self._finding_url = self.url + '/api/v2/findings/'
        self._notes_url = self.url + '/api/v2/notes/'
        self._users_url = self.url + '/api/v2/users/'
        
        self._all_products = []

    def _get_paginated_items(self, url, url_params=None):
        items = []
        while url:
            # we explicitly pass the url_params only for the first page since next page url already contains them
            r = self._session.get(url, headers=self._headers, params=url_params if not items else None, verify=self._ssl_verification)
            r.raise_for_status()
            response = json.loads(r.text)
            items.extend(response['results'])
            url = response['next']
        return items

    def prefetch_products_in_scope(self):
        self._all_products = self._get_paginated_items(self._product_url, {
            'not_tags': ['divize-security'],
            'prefetch': ['authorization_groups', 'members', 'prod_type']
        })
        # workaround since findings_list only contains active findings
        for product in self._all_products:
            product['_findings'] = self._get_paginated_items(self._finding_url, {
                    'test__engagement__product': product['id'],
                    'prefetch': ['found_by', 'mitigated_by', 'notes', 'reporter', 'review_requested_by', 'reviewers', 'risk_acceptance_set'],
                    'related_fields': 'true',
                    'o': 'last_status_update'
                })
```
