### ISSUE TITLE
Publish the Helm chart tarball with each release

### ISSUE THREAD

**Issue by bgoareguer** [DefectDojo/django-DefectDojo#3778]
**Is your feature request related to a problem? Please describe**
Before using the Helm chart we need to clone the git repository.

**Describe the solution you'd like**
Instead, I would like Helm to download the Chart by itself.
This could be either from a chart repository or as a tarball published on the release page on Github.
Maybe using [chart-releaser](https://github.com/helm/chart-releaser)

**Comment by valentijnscholten** [comment]
Good idea. We use GitHub Actions for CI/CD. Are you able to try out / make a PR for https://github.com/helm/chart-releaser-action ?

**Comment by bgoareguer** [comment]
Sorry, I don't know Github Actions and I don't have time to learn it right now.
