### ISSUE TITLE
Remove dependency to pandas

### ISSUE THREAD

**Issue by damiencarol** [DefectDojo/django-DefectDojo#3779]
`pandas` is only used in one parser (`dsop`) since few maintenace PR.

As `pandas` is a big dependency, I plan to remove it completly from the web app.

**Comment by madchap** [comment]
We can tale the parser out at the same time. I think I was the only one using it and it's broken anyways.

**Comment by damiencarol** [comment]
You means the DSOP parser?
I already have a PR that fix that https://github.com/DefectDojo/django-DefectDojo/pull/3784
