### ISSUE TITLE
MySQL account password and "&" character

### ISSUE THREAD

**Issue by dp00** [DefectDojo/django-DefectDojo#379]
If MySQL account password contains "&" character, setup.bash script will fail to create tables
due to the fact that when will store the password to the "settings.py,", will replace the "&"
with "MYSQLPWD" and so the database authentication will fail.

For example a password like
  111&2222222222
will be stored on settings.py as 
  111**MYSQLPWD**2222222222

**Comment by mtesauro** [comment]
It looks like setup.bash doesn't have a quoted variable on this line:
https://github.com/OWASP/django-DefectDojo/blob/master/setup.bash#L65

And there's probably other instances.  Let me look through that and get them quoted so the special characters aren't treated as, well special characters.

**Comment by devGregA** [comment]
@mtesauro @dp00 I tried to correct this, but I think I'm making a fundamental mistake. @mtesauro can I assign this issue to you?

**Comment by mattvaldes** [comment]
@mtesauro @devGregA looking here:
https://github.com/DefectDojo/django-DefectDojo/blob/master/entrypoint_scripts/common/dojo-shared-resources.sh#L397
I think you may need to escape the special characters in the password, prior to the sed search and replace. I wasn't able to find a way to make this work using quotes (expansion, interpolation, etc.).

**Comment by dp00** [comment]
Thank you.

**Comment by devGregA** [comment]
I'm going to bug @mtesauro about this when he gets back from vacation 😉
