### ISSUE TITLE
Deleting a user will delete any linked objects

### ISSUE THREAD

**Issue by ycrumeyrolle** [DefectDojo/django-DefectDojo#3799]
When deleting users for respecting data purge involved by GDPR, all related objects will be deleted.
Disabling user is a short term option, but it is not possible at mid term.

There is now way to reassign to a default user or an active user.

**Comment by valentijnscholten** [comment]
what if you just change all the fields like firstname, lastname, email address?
having a feature that can globally reassign any findings / engagement / tests / products / reviews / notes / etc is non-trivial to implement,

**Comment by ycrumeyrolle** [comment]
GDPR is not trivial :)

Anonymization is a reasonable option.
Can you confirm we can update also the login without issue?

**Comment by valentijnscholten** [comment]
It should work as long as you don't edit the ìd` of the user.
