### ISSUE TITLE
Datatables have paging and search limitations

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#3800]
**Bug description**
On the product list page (with a bit less than 50 products):

`Showing 1 to 25 of 25 entries`

plus a link to page 2. Clicking it I go to /product?page=2 which says

`Showing 1 to 21 of 21 entries`

Beyond this, the filter also only works for the displayed findings only, and not the whole set.

**Expected behavior**
Showing 1 to 25 of 46 entries
Showing 26 to 46 of 46 entries

**Deployment method** *(select with an `X`)*
- [x] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
Latest `dev`

**Comment by madchap** [comment]
I have not looked at alternatives, but maybe there is better. Who's our best JS guy out there? ;-)

**Comment by valentijnscholten** [comment]
I saw the same, been like this for a long time I think. The numbers being wrong is not related to datatables. We are doing paging and outside database and searching/filtering both inside and outside. datatable can handle AJAX calls to retrieve data and let server side do the filtering/search. not sure if it can handle paging correctly in that case.

bit dramatic title, no? :-)

**Comment by valentijnscholten** [comment]
I have fixed the "showing entries X to Y of Z" in an upcoming PR.
