### ISSUE TITLE
Cleanup: Automatic nmap scans need to be fixed or should be removed

### ISSUE THREAD

**Issue by StefanFl** [DefectDojo/django-DefectDojo#3820]
**Bug description**
DefectDojo provides a functionality to run regular nmap scans and send the results via email. It is hidden in the UI, there are no menus pointing to it. It can be configured when a user knows the URL's or via the API. 

The scans don't run in a docker or kubernetes environment, because nmap must be installed.

**Steps to reproduce**
1. Add a scan with https://dd.example.com/product/1/scan/add
2. Open the scan with https://dd.example.com/product/1/scan/1/settings
3. Choose `Launch Scan Now` in the menu of the Scan Settings
4. Check logs, you will get the error message `('Nmap not found', <class 'nmap.nmap.PortScannerError'>)`
5. The UI doesn't report any failure but shows a completed scan

**Expected behavior**
I see 2 options:
- Fix the functionality by installing nmap in the docker image, add the management of scans to the UI and create findings instead of sending an email
- Remove the functionality, because it seems to have been added in 2015 and has only been touched for maintenance of other stuff

**Deployment method** 
- Kubernetes (impacted)
- Docker (impacted)

**Context**
This feature use a very old lib with last relase from 2016/07/29 (v0.6.1)

If the decision is to remove the functionality, I am happy to do it.

**Comment by StefanFl** [comment]
**Supplement:** The library `python-nmap`, which is used for the scan, has been updated the last time in 2016 and should be updated to the much more recent `python3-nmap`, in case the functionality shall be fixed.

**Comment by damiencarol** [comment]
@StefanFl I see this feature as out of scope for the project, we discussed to remove it in 2.0.0

**Comment by StefanFl** [comment]
Duplicate of #3974

**Comment by valentijnscholten** [comment]
We have decided to remove it during the team meeting last night. Feel free to go ahead and remove it.
