### ISSUE TITLE
Move up the "cvss" field when creating/editing finding

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#3823]
**Is your feature request related to a problem? Please describe**
The cvss3 field is way at the bottom. Too bad, it's got a nice JS to actually fill out the cvss right within dojo!

**Describe the solution you'd like**
Put it right under "severity" maybe?

**Comment by valentijnscholten** [comment]
I noticed it also lower on the page on the view finding page using a whole panel for itself. Might be more logical to put it at the top, maybe in the same row as location / component name+version?

**Comment by damiencarol** [comment]
It's a good idea
