### ISSUE TITLE
Display correct engagement count for staff users on home dashboard

### ISSUE THREAD

**Issue by michaelgibson** [DefectDojo/django-DefectDojo#3824]
Currently the total number of active engagements rendered on the home page dashboard is restricted to either superuser or engagement_lead.
My understanding is that "staff" level access should return the total count of engagements similar to superuser.
Something similar to this seems to correct the issue for me. May or may not be missing other updates.
Diff not rendering.
Submitting PR:
https://github.com/DefectDojo/django-DefectDojo/pull/3826

**Comment by valentijnscholten** [comment]
Can you make a PR?

**Comment by michaelgibson** [comment]
Closing. resolved'ish in #3826 :)
