### ISSUE TITLE
Error when try to upload scan result OpenScap - Atomic

### ISSUE THREAD

**Issue by damianmadeira** [DefectDojo/django-DefectDojo#3829]
When try upload scan result the openscap, defect dojo show this error: "An error has occurred in the parser, please see error log for more details".

Steps to get to the error:
![image](https://user-images.githubusercontent.com/56444256/107285488-03406300-6a3e-11eb-9814-d46aabb53faa.png)
![image](https://user-images.githubusercontent.com/56444256/107285505-09364400-6a3e-11eb-86ce-85f20a0c852f.png)
![image](https://user-images.githubusercontent.com/56444256/107285511-0f2c2500-6a3e-11eb-8cf3-cd8cb7f04a09.png)

Error:
docker logs django-defectdojo_uwsgi_1
![image](https://user-images.githubusercontent.com/56444256/107285541-1b17e700-6a3e-11eb-88cb-385223ffcc90.png)

Upload the file report the openscap - atomic
[cve.zip](https://github.com/DefectDojo/django-DefectDojo/files/5947070/cve.zip)

**Comment by damiencarol** [comment]
@damianmadeira testing your report.

**Comment by damiencarol** [comment]
@damianmadeira  It seems your report is in OVAL format and you are using a parser designed to support XCCDF reports generated by OpenSCAP (see https://csrc.nist.gov/Projects/Security-Content-Automation-Protocol/Specifications/xccdf)

I opened a feature request to support this format (https://github.com/DefectDojo/django-DefectDojo/issues/3840) but for now your pb is not a bug, maybe a missing feature.

**Comment by damianmadeira** [comment]
Thank you @damiencarol . I saw the same, hopefully this functionality can be added to defectdojo soon.
