### ISSUE TITLE
New importer: Open Vulnerability and Assessment Language

### ISSUE THREAD

**Issue by damiencarol** [DefectDojo/django-DefectDojo#3840]
**Scanner OVAL**

OVAL® International in scope and free for public use, OVAL is an information security community effort to standardize how to assess and report upon the machine state of computer systems. OVAL includes a language to encode system details, and an assortment of content repositories held throughout the community.

Tools and services that use OVAL for the three steps of system assessment — representing system information, expressing specific machine states, and reporting the results of an assessment — provide enterprises with accurate, consistent, and actionable information so they may improve their security. Use of OVAL also provides for reliable and reproducible information assurance metrics and enables interoperability and automation among security tools and services.
https://oval.mitre.org/

**Sample File**

[oval_report_zipped.zip](https://github.com/DefectDojo/django-DefectDojo/files/5960031/oval_report_zipped.zip)

**Comment by damianmadeira** [comment]
Hello how are you? Is there anything new with this topic?

**Comment by damiencarol** [comment]
Made some analysis. We have a parser that read reports close to this format.
I also have a prototype but nothing ready.
Writing a parser is fast. it's possible that I push it for `1.15.0` (end of April)

**Comment by damianmadeira** [comment]
good news !!! yes, off course @damiencarol  !!!

**Comment by damianmadeira** [comment]
hello @damiencarol, I can see available the version 1.15.0. Was issue incorporat in this version ?

**Comment by damiencarol** [comment]
@damianmadeira no sadly, I didn't had time for this new parser. we will have more time for the next release `2.0.0` (2 months)

**Comment by damianmadeira** [comment]
Hello @damiencarol, can you tell me how i can help. it really interests me.

**Comment by damiencarol** [comment]
@damianmadeira thanks for your interest. you can contribute by creating a new parser for OVAL.
Take a look at https://defectdojo.github.io/django-DefectDojo/contributing/how-to-write-a-parser/ and previous pull requests with tag `"import scans"` https://github.com/DefectDojo/django-DefectDojo/pulls?q=is%3Apr+is%3Aclosed+label%3A%22Import+Scans%22
