### ISSUE TITLE
Non-Staff (non-admin) users can't see findings

### ISSUE THREAD

**Issue by rkane-nm** [DefectDojo/django-DefectDojo#385]
Even with all permissions added to a group, and a non-staff users in that group, that user cannot see findings. It forwards them to the login screen (session isn't killed, but can't see findings). It appears that this happens with numerous menu options as well. And even with all the permissions added, there are no menu options for Engagements, Tests, Findings, etc.... only Products, Reports, Metrics and Configuration. The user is also added to the authorized users field of a product. Anything we are doing wrong on our end?

**Comment by devGregA** [comment]
@rkane-nm will have this fixed in my next pr (should be tomorrow).
