### ISSUE TITLE
How can I connect my postgresql to Defectdojo.?

### ISSUE THREAD

**Issue by rr1010** [DefectDojo/django-DefectDojo#3862]
**Is your feature request related to a problem? Please describe**
A clear and concise description of what the problem is.
Ex: I'm always frustrated when I kill defectdojo and run again. It will spawn another instance of mysql container and my data will be in the older container. So I thought to connecting to my external database. 

**Describe the solution you'd like**
Ex:  I am running a postgresql on digital ocean or locally, I want to connect that postgresql to defectdojo.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you have considered.

**Additional context**
I have tried changing the environment variable, and tried fixing the docker compose but was unsuccessful. It would be nice if you could provide a doc for connecting defectdojo to an external database.

**Comment by JoseRoman** [comment]
What environment variable(s) are you using? 

I think you need to set `DD_DATABASE_ENGINE` to django.db.backends.postgresql

```
DD_DATABASE_ENGINE:
DD_DATABASE_HOST:
DD_DATABASE_NAME
DD_DATABASE_PASSWORD:
DD_DATABASE_PORT:
DD_DATABASE_USER:
```

**Comment by rr1010** [comment]
Yup all changed.

**Comment by rr1010** [comment]
In docker-compose.yml file. I changed the DD_DATABASE_URL as well

**Comment by JoseRoman** [comment]
Can you try removing DD_DATABASE_URL and only using the other environment variables I mentioned above? 

I think that using DD_DATABASE_URL will default to the MySQL engine, but if you use the other environment variables and specifically set DD_DATABASE_ENGINE to "django.db.backends.postgresql", it should work.

**Comment by rr1010** [comment]
I tried with just changing the environment variables. But still it connects to the mysql and not the postgres.

**Comment by rr1010** [comment]
![image](https://user-images.githubusercontent.com/51348258/108003356-6beb9900-7057-11eb-95b2-c0df209c019d.png)

**Comment by JoseRoman** [comment]
The values you set in the setup.dist.py file will be overwritten by the environment variables. You have to use one or the other, not both, did you comment out the environment variables from your docker-compose file? 

Also I'm assuming that you are re-building the images after making the change?

**Comment by rr1010** [comment]
Yes I am building again if I change anything. Do I have to remove these Environment variables and the URL in the docker-compose.yml. If I run this like this it does give me errors saying no USER PASSWORD DATABASE OR ENGINE. Screenshot is below. 
![image](https://user-images.githubusercontent.com/51348258/108017246-45d6f080-7079-11eb-9257-58c16598872e.png)

![image](https://user-images.githubusercontent.com/51348258/108017863-dc57e180-707a-11eb-9d5d-7db97ef242c1.png)

**Comment by rr1010** [comment]
I feel it depends on the DD_DATABASE_URL to connect to postgres.

**Comment by valentijnscholten** [comment]
I think on slack some users solved the issue not too long ago: https://owasp-slack.herokuapp.com/
We are refactoring our documentation and this is for sure something we want to document.

**Comment by valentijnscholten** [comment]
The only thing needed is to set the DD_DATABASE_URL environment variable before running docker-compose up. So `export DD_DATABASE_URL=blablablabla`. Make sure there are no characters in the username or password that are not allow in urls (#, @, : etc) or urlencode those.

**Comment by Bala-ganesh** [comment]
> What environment variable(s) are you using?
> 
> I think you need to set `DD_DATABASE_ENGINE` to django.db.backends.postgresql
> 
> ```
> DD_DATABASE_ENGINE:
> DD_DATABASE_HOST:
> DD_DATABASE_NAME
> DD_DATABASE_PASSWORD:
> DD_DATABASE_PORT:
> DD_DATABASE_USER:
> ```

Hey [JoseRoman](https://github.com/JoseRoman) 
as you mentioned in the comment, I have added the envs.

I'm running defectdojo in EKS, I wanted to connect it to aws rds. but even-though I pass the correct password it says password authentication failed
```
[09/Jun/2022 10:52:24] INFO [dojo.models:3753] enabling audit logging
psql: error: FATAL:  password authentication failed for user "user"
FATAL:  password authentication failed for user "user"
CommandError: "psql -U user -h host -p 5432 dbname" returned non-zero exit status 2.
```

ps: haven't configured DD_DATABASE_URL and my db password is alphanumeric. 

can someone please help here?

**Comment by pr3l14t0r** [comment]
heyho @Bala-ganesh and the rest! :) 
Were you able to resolve the issue? I am planning to run DefectDojo in an AWS ECS cluster using Fargate, and i am still wondering if i have to set both all ENV variables (DB port, host, user...) **and** the `DD_DATABASE_URL` or if i can leave out the `DD_DATABASE_URL`.

**Comment by mtesauro** [comment]
@pr3l14t0r Generally speaking, DD_DATABASE_URL is the preferred way to pass DB credentials into DefectDojo - it simplifies things by requiring only a single ENV variable vs multiple variables.

**Comment by pr3l14t0r** [comment]
Okay, makes sense! Thank you for your response. :)
