### ISSUE TITLE
Nexpose miss some findings for authenticated scans

### ISSUE THREAD

**Issue by dsever** [DefectDojo/django-DefectDojo#3869]
When authenticated scan is in use against one of the IP addresses, nothing will be imported into DD. That type of scan do not contain endpoint and service tags.

Example of report is in attach. 

[report_auth.xml.txt](https://github.com/DefectDojo/django-DefectDojo/files/5988413/report_auth.xml.txt)

**Comment by damiencarol** [comment]
@dsever a patch has been merged to dev branch, it will be part of the `1.13.0` release.
