### ISSUE TITLE
cleanup 2.0: replace django-saml2-auth with django-saml2-pro-auth or djangosaml2 

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#3890]
[django-saml2-auth ](https://github.com/fangli/django-saml2-auth)is no longer maintained making it a security risk and incompatible with some newer libraries.
For example, it requires `PyJWT<2`, where other libraries have switched to `PyJWT>=2.0.0` ([issue](https://github.com/fangli/django-saml2-auth/issues/155))
This prevents us from:
A) doing a clean install from requirements needing the legacy resolver which will be removed later this year (Q1?)
B) locking out dependencies with pipenv
C) upgrading to django 3+ or even 2.2+ (already at risk using django 2.2)
D) using python 3.6 or higher (we are already at risk using 3.6)

The replacement seems to be [django-saml2-pro-auth](https://github.com/zibasec/django-saml2-pro-auth)

Or we could use [djangosaml2](https://pypi.org/project/djangosaml2/) which is mentioned in our [README.md](https://github.com/DefectDojo/django-DefectDojo/blob/master/README.md)

**Comment by peppelinux** [comment]
I suggest djangosaml2 :smile:

**Comment by quaffapint** [comment]
Could I ask whether this will still be part of 2.0.0 and what the rough planned release date is for that? We are unable to get our old ADFS system working with the current SAML plugin and we're hoping djangosaml2 will work for us.

**Comment by damiencarol** [comment]
@quaffapint we pinned this modification for `2.0.0`which will be release at the end of the month.
