### ISSUE TITLE
Typos on the DefectDojo

### ISSUE THREAD

**Issue by MFernstrom** [DefectDojo/django-DefectDojo#3910]
Found some typos on the website

commericial
avialable

and an odd period in the Commercial Support FAQ section.

**Comment by apilynx** [comment]
These are from defectdojo-web [https://github.com/DefectDojo/defectdojo-web/pull/5](url)

**Comment by sa-git123** [comment]
/system_settings has another as well: "Crital' instead of 'Critical' for SLA: **_"Crital Finding SLA Days* "_**

**Comment by damiencarol** [comment]
@MFernstrom as @apilynx said, you should check https://github.com/DefectDojo/defectdojo-web repo 😅

**Comment by damiencarol** [comment]
@sa-git123 for your comment I created another issue https://github.com/DefectDojo/django-DefectDojo/issues/4052
