### ISSUE TITLE
How to change the DB.

### ISSUE THREAD

**Issue by jis0324** [DefectDojo/django-DefectDojo#3911]
Hello, DefectDoJo Team.
At first, I appreciate you build a good repository, and project.
I am trying to change the DB.
Actually, I tried to combine DefectDojo and Local mysql db.
But it leaded me to hell, and I did not find why it does not work.
So then I decied to use aws online db.
For now, I followed your doc - https://defectdojo.readthedocs.io/en/latest/running-in-production.html
https://prnt.sc/1044tm3
It seems to go well, but it show errors when I check the logs.
https://prnt.sc/1044v0l

Which value did not I change?
How can I fix this problem.
Regards!

**Comment by valentijnscholten** [comment]
I believe this is solved on Slack and was caused by special characters in the password that violate the URL spec causing the database url being parsed incorrectly.

**Comment by jis0324** [comment]
Hello, @valentijnscholten
Thanks for your comment.
Yes, You and @madchap helped me, so I fixed this problem, 
The reason is that my password contains some special characters.
.......
Btw, did you fix this problem?
So can I contain special characters in my database password?

**Comment by valentijnscholten** [comment]
No, it's not a problem in defect dojo. It's a property URLs, certain characaters are forbidden. Did you try urlencoding them?

**Comment by jis0324** [comment]
No, I just created a new user(the password of the new user does not include any special char), then connected using this info.
