### ISSUE TITLE
MS teams and email webhook support question

### ISSUE THREAD

**Issue by rr1010** [DefectDojo/django-DefectDojo#3922]
**Is your feature request related to a problem? Please describe**
Your MS Teams integration using URL webhook not working. I have added the webhook and also enabled all the notifications for msteams in the product. But not receiving any notification on the teams. and Not receiving any errors from DD. 

For Email I gettting a error Cannot assign requested address. 

![image](https://user-images.githubusercontent.com/51348258/109072822-69c1c280-775a-11eb-8556-481ab98450e7.png)

**Comment by valentijnscholten** [comment]
Please populate all the info as requested in the template: https://github.com/DefectDojo/django-DefectDojo/issues/new?assignees=&labels=bug&template=bug_report.md&title=

**Comment by valentijnscholten** [comment]
#3930

**Comment by madchap** [comment]
You most likely have an issue with docker to send emails, and certainly has nothing to do with the app itself. I remember having that issue too, and it was purely a docker configuration problem (I can't recall how I solved it, but Google helped me).
