### ISSUE TITLE
jira tickets not reflecting in dojo console neither created in Jira board.

### ISSUE THREAD

**Issue by priyankaaggarwal20** [DefectDojo/django-DefectDojo#3924]
**Is your feature request related to a problem? 
Work done so far : Am doing jira integration with dojo , i could able to create webhook in jira and made connection to jira via dojo.
Problem>: when i am taking each vulnerability and editing , then checking "push issue to jira", so it is showing JIRA age and JIra change but , no jira were created at the JIRA board and neither jira number is displayed in front of that issue.
though i have put  product key and other parameters according to the Jira api document and dojo document.

please help me on this !

**Comment by valentijnscholten** [comment]
Please populate all the info as requested in the template: https://github.com/DefectDojo/django-DefectDojo/issues/new?assignees=&labels=bug&template=bug_report.md&title=
Or better, come to our slack channel for support.
