### ISSUE TITLE
Unable to upload trufflehog JSON output

### ISSUE THREAD

**Issue by haivipin4u** [DefectDojo/django-DefectDojo#3932]
Hi Team,

I have ran a scan using trufflehog3 for the vuln django.nv application and saved the results in json format.

But unable to import trufflehog3 json outout to defect-dojo. Giving some parse error.

I have attached the trufflehog json results and error which i am getting while uploading.

Also i validated the json format using an online json format checker. Screenshot attached.

<img width="952" alt="error_log" src="https://user-images.githubusercontent.com/79680902/109253111-106a9980-7815-11eb-8704-5a22ec2a9ac2.PNG">
[trufflehog3.zip](https://github.com/DefectDojo/django-DefectDojo/files/6047302/trufflehog3.zip)
<img width="829" alt="json_format" src="https://user-images.githubusercontent.com/79680902/109253325-8d960e80-7815-11eb-832a-ab06be207072.PNG">

**Comment by damiencarol** [comment]
@haivipin4u what version do you use ? which kind of deployment?

**Comment by damiencarol** [comment]
@haivipin4u  I took a look at your report and it seems that the format of TruffleHog report is not the same.
TruffleHog 3 seems to use JSON well formed now (it was JSON lines before)
As for now the parser only support JSON lines old one, you have this error.

**Comment by haivipin4u** [comment]
Thanks @damiencarol for the updates !

I have used trufflehog instead of trufflehog2. Getting 500 
 internal server error.

Attached screenshot and result output.

Any solutions or output sample format i can use and test it out.

<img width="949" alt="error_log_1" src="https://user-images.githubusercontent.com/79680902/109287610-d23b9d00-7849-11eb-88cc-a38d0c2fb18f.PNG">
[trufflehog.zip](https://github.com/DefectDojo/django-DefectDojo/files/6048912/trufflehog.zip)

**Comment by damiencarol** [comment]
@haivipin4u  I pushed a pull request to refresh the parser. it seems that trufflehog is broken since Dynamic infrastructure refactoring. There were no unit tests for this parser.

**Comment by damiencarol** [comment]
https://github.com/DefectDojo/django-DefectDojo/pull/3935

**Comment by valentijnscholten** [comment]
fixed in dev, so wille be part of 1.14.0
