### ISSUE TITLE
switch back to drf-yasg from drf-yasg2

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#3933]
drf-yasg2 is no longer supported
https://github.com/axnsan12/drf-yasg/issues/662
https://github.com/JoelLefkowitz/drf-yasg/commit/7316f13497065ffbe0e134e2a4bbd4ea76939d2c

**Comment by damiencarol** [comment]
@valentijnscholten  after some of our discussions on Slack, I was excepting to switch to a different framework that support OpenAPI 3.0 like maybe [drf-spectacular](https://github.com/tfranzel/drf-spectacular)
(see: https://github.com/axnsan12/drf-yasg#openapi-30-note )
Maybe for our API v3 ?!?

**Comment by valentijnscholten** [comment]
Good idea, when we have time :-)
