### ISSUE TITLE
Enhance cleanup job

### ISSUE THREAD

**Issue by michaelgibson** [DefectDojo/django-DefectDojo#3937]
We do daily imports of findings and rely on the de-duplication logic to delete any redundant findings.
This works great but ends up leaving a lot of empty tests lying around.

There was mention of enhancing the existing cleanup job:
https://github.com/DefectDojo/django-DefectDojo/pull/3279#issuecomment-735269844
To address this and other related issues.

I believe having an option to "Delete Empty" things would be good to have.
Opening feature request to continue discussion of enhancement.

**Comment by valentijnscholten** [comment]
Yes, a better cleanup would be nice. But also enhancements to the reimport might mean that could be interesting choice to avoid all the duplicates. Is there a reason why you are not using reimport?

**Comment by michaelgibson** [comment]
There are a few reasons we don't use import-scan/reimport-scan.
1. Supported parser is not available for the data so we create findings ourselves.
2. There are fields we want set at the finding level that we lose granular control for when using import-scan.
3. The supported parser does not work with the version of the tool we use.

**Comment by damiencarol** [comment]
@michaelgibson which parser? what is broken?

**Comment by michaelgibson** [comment]
> @michaelgibson which parser? what is broken?

The Veracode parser does not seem to mark mitigated findings as inactive but perhaps that has been fixed in newer DD version that I have not tested.
The Gitlab parser may not be actually "broken" for everyone. I think there are some compatibility issues with the version of GitLab we are using.
In either case I just chose to just import findings individually than try and dive too deep into the parsers.
I'm guessing I'm losing out on some performance gains? 
Didn't know reimport-scan did duplication pre-checks.

I believe we would still run into the empty tests issue at some point even if we used import-scan/reimport-scan for the initial import of findings. In addition to using the API and relying on the deduplication algorithms, we have a user-base that are manually flagging findings as duplicates.

**Comment by damiencarol** [comment]
> The Veracode parser does not seem to mark mitigated findings as inactive but perhaps that has been fixed in newer DD version that I have not tested.

Funny! I'm working on this specific parser on this specific part (mark as mitigated) but I have no data to test !
If you can provide me a Veracode report with some mitigated findings, I will be able to test/fix it!

Here is my current work: #3967 

For the Gitlab issues, same thing: if you can provide me a report that fail or provide some issue/stack trace I can fix/modify the parser.

**Comment by michaelgibson** [comment]
> > The Veracode parser does not seem to mark mitigated findings as inactive but perhaps that has been fixed in newer DD version that I have not tested.
> 
> Funny! I'm working on this specific parser on this specific part (mark as mitigated) but I have no data to test !
> If you can provide me a Veracode report with some mitigated findings, I will be able to test/fix it!
> 
> Here is my current work: #3967
> 
> For the Gitlab issues, same thing: if you can provide me a report that fail or provide some issue/stack trace I can fix/modify the parser.

Sorry, I don't think I will be able to provide you with reports from our scanners. I'd like to keep this ticket focused on the cleanup job so if I have more specific issues regarding the parsers, I'll open separate tickets for those.
