### ISSUE TITLE
Make the Django session duration configurable

### ISSUE THREAD

**Issue by bgoareguer** [DefectDojo/django-DefectDojo#3970]
**Is your feature request related to a problem? Please describe**
Currently the Django session cookie is valid for 14 days (this is the default value).
I would like to be able to lower this value.

**Describe the solution you'd like**
The Django session duration can be changed by setting the `SESSION_COOKIE_AGE` variable.
It would be nice if this value could be set as an environment variable.

An interesting discussion about this: https://stackoverflow.com/questions/14830669/how-to-expire-django-session-in-5minutes/14830874

**Comment by valentijnscholten** [comment]
Good idea, if wou want you can submit a PR.

**Comment by valentijnscholten** [comment]
fixed in dev/1.14.0
