### ISSUE TITLE
Remove nmap scans integrated feature

### ISSUE THREAD

**Issue by damiencarol** [DefectDojo/django-DefectDojo#3974]
https://defectdojo.readthedocs.io/en/latest/features.html#port-scans

**Comment by StefanFl** [comment]
Have you decided who will do it? I am happy to volunteer.

**Comment by valentijnscholten** [comment]
closing as duplicate of #3820

**Comment by damiencarol** [comment]
@valentijnscholten this one was for documentation :D but ok!
