### ISSUE TITLE
Integration with LDAP for authentication?

### ISSUE THREAD

**Issue by AliElKhatteb** [DefectDojo/django-DefectDojo#3981]
why defect-dojo do not come with ldap authentication out of the box and if i want to implement ldap what should i do

**Comment by manuel-sommer** [comment]
This should work:

in dojo/settings/settings.dist.py you have to 
a) Add this:
```
import ldap  
from django_auth_ldap.config import LDAPSearch 
```
b) Add in "AUTHENTICATION_BACKENDS:" the following:
```'django_auth_ldap.backend.LDAPBackend',```
c) Add the following and adjust this to your purposes:
```
AUTH_LDAP_SERVER_URI = 'ldap://URL'
AUTH_LDAP_BIND_DN = ""
AUTH_LDAP_BIND_PASSWORD = ""
AUTH_LDAP_USER_SEARCH = LDAPSearch(
    "ou=Groups,dc=example,dc=com", ldap.SCOPE_SUBTREE, "(uid=%(user)s)"
)

AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}
```
In file  requirements.txt you have to add: 
```
python-ldap==3.3.1
django-auth-ldap==2.3.0

```
In Dockerfile.django and Dockerfile.nginx add the following to the RUN section:
```
libldap2-dev \
    libsasl2-dev \
```

**Comment by valentijnscholten** [comment]
We use django as framework, which supplies authentication. So lots of options there and lots of blogs etc on how to configure them.

**Comment by AliElKhatteb** [comment]
i did exactly what u said and i got this error when i do docker-compose up

ERROR: for chs-defect-dojo_uwsgi_1  Cannot start service uwsgi: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/wait-for-it.sh\": permission denied": unknown

Creating chs-defect-dojo_celerybeat_1   ... error
tainer process caused "exec: \"/wait-for-it.sh\": permission denied": unknown
Creating chs-defect-dojo_initializer_1  ... error
ERROR: for chs-defect-dojo_celerybeat_1  Cannot start service celerybeat: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/wait-for-it.sh\": permission denied": unknown

ERROR: for chs-defect-dojo_initializer_1  Cannot start service initializer: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/wait-for-it.sh\": permission denied": unknown

ERROR: for uwsgi  Cannot start service uwsgi: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/wait-for-it.sh\": permission denied": unknown

ERROR: for celeryworker  Cannot start service celeryworker: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/wait-for-it.sh\": permission denied": unknown

ERROR: for celerybeat  Cannot start service celerybeat: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/wait-for-it.sh\": permission denied": unknown

ERROR: for initializer  Cannot start service initializer: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/wait-for-it.sh\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.

**Comment by valentijnscholten** [comment]
did you rebuild the containers? the error you are seeing indicates a local permission problem where docker is unable to create containers.

**Comment by AliElKhatteb** [comment]
this is my dockerfile.django`
# code: language=Dockerfile

# The code for the build image should be identical with the code in
# Dockerfile.nginx to use the caching mechanism of Docker.

# Ref: https://devguide.python.org/#branchstatus
FROM python:3.6.12-slim-buster@sha256:e5259113df5a7c4dae16ad37c2ca53b1cf722e051cfd5f624e7b76aa72389e0c as build
WORKDIR /app
RUN \
  apt-get -y update && \
  apt-get -y install \
    build-essential \
    dnsutils \
    libldap2-dev \
    libsasl2-dev \
    default-mysql-client \
    libmariadb-dev-compat \
    postgresql-client \
    xmlsec1 \
    git \
    uuid-runtime \
    && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists && \
  true
COPY requirements.txt ./
RUN pip3 wheel --wheel-dir=/tmp/wheels -r ./requirements.txt

FROM python:3.6.12-slim-buster@sha256:e5259113df5a7c4dae16ad37c2ca53b1cf722e051cfd5f624e7b76aa72389e0c
WORKDIR /app
ARG uid=1001
ARG appuser=defectdojo
ENV appuser ${appuser}
RUN \
  apt-get -y update && \
  # ugly fix to install postgresql-client without errors
  mkdir -p /usr/share/man/man1 /usr/share/man/man7 && \
  apt-get -y install --no-install-recommends \
    # libopenjp2-7 libjpeg62 libtiff5 are required by the pillow package
    libopenjp2-7 \
    libjpeg62 \
    libtiff5 \
    dnsutils \
    default-mysql-client \
    libmariadb3 \
    xmlsec1 \
    git \
    uuid-runtime \
    # only required for the dbshell (used by the initializer job)
    postgresql-client \
    curl \
    && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists && \
  true
COPY --from=build /tmp/wheels /tmp/wheels
COPY requirements.txt ./
RUN pip3 install \
	--no-cache-dir \
	--no-index \
  --find-links=/tmp/wheels \
  -r ./requirements.txt

COPY \
  docker/entrypoint-celery-beat.sh \
  docker/entrypoint-celery-worker.sh \
  docker/entrypoint-initializer.sh \
  docker/entrypoint-uwsgi.sh \
  docker/entrypoint-uwsgi-dev.sh \
  docker/entrypoint-uwsgi-ptvsd.sh \
  docker/entrypoint-unit-tests.sh \
  docker/entrypoint-unit-tests-devDocker.sh \
  docker/wait-for-it.sh \
  docker/certs/* \
  /
COPY wsgi.py manage.py docker/unit-tests.sh ./
COPY dojo/ ./dojo/

# Add extra fixtures to docker image which are loaded by the initializer
COPY docker/extra_fixtures/* /app/dojo/fixtures/

# Fallback for safety parser, if installation does't allow internet connectivity
RUN curl -sS -o dojo/tools/safety/insecure_full.json https://raw.githubusercontent.com/pyupio/safety-db/master/data/insecure_full.json

COPY tests/ ./tests/
RUN \
  # Remove placeholder copied from docker/certs
  rm -f /readme.txt && \
  # Remove placeholder copied from docker/extra_fixtures
  rm -f dojo/fixtures/readme.txt && \
  mkdir -p dojo/migrations && \
  chmod g=u dojo/migrations && \
  true
USER root
RUN \
    adduser --system --no-create-home --disabled-password --gecos '' \
        --uid ${uid} ${appuser} && \
    chown -R ${appuser} /app && \
    chmod 0700 /app && \
    chmod 0750 -R /app/* && \
	chmod g=u /app && \
	chmod -R g=u /app/* && \
    mkdir /var/run/${appuser} && \
    chown ${appuser} /var/run/${appuser} && \
	chmod g=u /var/run/${appuser}
USER ${uid}
ENV \
  DD_ADMIN_USER=admin \
  DD_ADMIN_MAIL=admin@defectdojo.local \
  DD_ADMIN_PASSWORD='' \
  DD_ADMIN_FIRST_NAME=Administrator \
  DD_ADMIN_LAST_NAME=User \
  DD_ALLOWED_HOSTS="*" \
  DD_CELERY_BEAT_SCHEDULE_FILENAME="/run/celery-beat-schedule" \
  DD_CELERY_BROKER_SCHEME="amqp" \
  DD_CELERY_BROKER_USER="defectdojo" \
  DD_CELERY_BROKER_PASSWORD="defectdojo" \
  DD_CELERY_BROKER_HOST="rabbitmq" \
  DD_CELERY_BROKER_PORT="5672" \
  DD_CELERY_BROKER_PATH="//" \
  DD_CELERY_LOG_LEVEL="INFO" \
  DD_CELERY_WORKER_POOL_TYPE="solo" \
  # Enable prefork and options below to ramp-up celeryworker performance. Presets should work fine for a machine with 8GB of RAM, while still leaving room.
  # See https://docs.celeryproject.org/en/stable/userguide/workers.html#id12 for more details
  # DD_CELERY_WORKER_POOL_TYPE="prefork" \
  # DD_CELERY_WORKER_AUTOSCALE_MIN="2" \
  # DD_CELERY_WORKER_AUTOSCALE_MAX="8" \
  # DD_CELERY_WORKER_CONCURRENCY="8" \
  # DD_CELERY_WORKER_PREFETCH_MULTIPLIER="128" \
  DD_DATABASE_ENGINE="django.db.backends.mysql" \
  DD_DATABASE_HOST="mysql" \
  DD_DATABASE_NAME="defectdojo" \
  DD_DATABASE_PASSWORD="defectdojo" \
  DD_DATABASE_PORT="3306" \
  DD_DATABASE_USER="defectdojo" \
  DD_INITIALIZE=true \
  DD_UWSGI_MODE="socket" \
  DD_UWSGI_ENDPOINT="0.0.0.0:3031" \
  DD_UWSGI_NUM_OF_PROCESSES="2" \
  DD_UWSGI_NUM_OF_THREADS="2" \
  DD_DJANGO_ADMIN_ENABLED="True" \
  DD_TRACK_MIGRATIONS="True" \
  DD_DJANGO_METRICS_ENABLED="False"
ENTRYPOINT ["/entrypoint-uwsgi.sh"]`

this is my dockerfile.nginx `# code: language=Dockerfile

# The code for the build image should be identical with the code in
# Dockerfile.django to use the caching mechanism of Docker.

FROM python:3.6.12-slim-buster@sha256:e5259113df5a7c4dae16ad37c2ca53b1cf722e051cfd5f624e7b76aa72389e0c as build
WORKDIR /app
RUN \
  apt-get -y update && \
  apt-get -y install \
    libldap2-dev \
    libsasl2-dev \
    build-essential \
    dnsutils \
    default-mysql-client \
    libmariadb-dev-compat \
    postgresql-client \
    xmlsec1 \
    git \
    uuid-runtime \
    && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists && \
  true
COPY requirements.txt ./
RUN pip3 wheel --wheel-dir=/tmp/wheels -r ./requirements.txt

FROM build AS collectstatic

USER root
ENV \
  # This will point yarn to whatever version of node you decide to use
  # due to the use of nodejs instead of node name in some distros
  node="nodejs"
RUN \
  apt-get -y update && \
  apt-get -y install apt-transport-https ca-certificates curl wget && \
  curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add --no-tty - && \
  echo 'deb https://deb.nodesource.com/node_14.x buster main' > /etc/apt/sources.list.d/nodesource.list && \
  echo 'deb-src https://deb.nodesource.com/node_14.x buster main' >> /etc/apt/sources.list.d/nodesource.list && \
  apt-get update -y -o Dir::Etc::sourcelist="sources.list.d/nodesource.list" \
  -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0" && \
  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
  wget https://github.com/yarnpkg/yarn/releases/download/v1.22.10/yarn_1.22.10_all.deb && \
  dpkg -i yarn_1.22.10_all.deb && \
  echo "$(yarn --version)" && \
  apt-get -y install nodejs && \
  echo "$(node --version)" && \
  apt-get clean && \
  rm yarn_1.22.10_all.deb && \
  rm -rf /var/lib/apt/lists && \
  true

RUN pip3 install \
	--no-cache-dir \
	--no-index \
  --find-links=/tmp/wheels \
	-r ./requirements.txt

COPY components/ ./components/
RUN \
  cd components && \
  yarn

COPY manage.py ./
COPY dojo/ ./dojo/

RUN env DD_SECRET_KEY='.' python3 manage.py collectstatic --noinput && true

FROM nginx:1.19.7-alpine@sha256:14536d83ca3128923ee7c2f7f4f285e023abd40f3ccdc8911f56cd4119558506
ARG uid=1001
ARG appuser=defectdojo
COPY --from=collectstatic /app/static/ /usr/share/nginx/html/static/
COPY wsgi_params nginx/nginx.conf nginx/nginx_TLS.conf /etc/nginx/
COPY docker/entrypoint-nginx.sh /
RUN \
  apk add --no-cache openssl && \
  chmod -R g=u /var/cache/nginx && \
  mkdir /var/run/defectdojo && \
  chmod -R g=u /var/run/defectdojo && \
  mkdir -p /etc/nginx/ssl && \
  chmod -R g=u /etc/nginx && \
  true
ENV \
  DD_UWSGI_PASS="uwsgi_server" \
  DD_UWSGI_HOST="uwsgi" \
  DD_UWSGI_PORT="3031" \
  GENERATE_TLS_CERTIFICATE="false" \
  USE_TLS="false" \
  NGINX_METRICS_ENABLED="false" \
  METRICS_HTTP_AUTH_USER="" \
  METRICS_HTTP_AUTH_PASSWORD=""
USER ${uid}
EXPOSE 8080
ENTRYPOINT ["/entrypoint-nginx.sh"]`

**Comment by AliElKhatteb** [comment]
the containers worked but i get this error everytime i try to login

uwsgi_1         | WARNING:django_auth_ldap:Caught LDAPError while authenticating example: INVALID_CREDENTIALS({'msgtype': 97, 'msgid': 1, 'result': 49, 'desc': 'Invalid credentials', 'ctrls': [], 'info': '80090308: LdapErr: DSID-0C090453, comment: AcceptSecurityContext error, data 52e, v3839'},)

**Comment by AliElKhatteb** [comment]
i think i did my conf right but when i login i get server error 500 and this is the log 

 | /usr/local/lib/python3.6/site-packages/jose/backends/cryptography_backend.py:18: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
uwsgi_1         |   from cryptography.utils import int_from_bytes, int_to_bytes
uwsgi_1         | WARNING:django_auth_ldap:'AccountName' while authenticating henry
uwsgi_1         | ERROR:django.request:Internal Server Error: /login
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
uwsgi_1         |     return self.dispatch(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
uwsgi_1         |     return bound_method(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
uwsgi_1         |     return view(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
uwsgi_1         |     return bound_method(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
uwsgi_1         |     response = view_func(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
uwsgi_1         |     return bound_method(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
uwsgi_1         |     response = view_func(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/views.py", line 61, in dispatch
uwsgi_1         |     return super().dispatch(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
uwsgi_1         |     return handler(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 141, in post
uwsgi_1         |     if form.is_valid():
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 185, in is_valid
uwsgi_1         |     return self.is_bound and not self.errors
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 180, in errors
uwsgi_1         |     self.full_clean()
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 382, in full_clean
uwsgi_1         |     self._clean_form()
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 409, in _clean_form
uwsgi_1         |     cleaned_data = self.clean()
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/forms.py", line 205, in clean
uwsgi_1         |     self.user_cache = authenticate(self.request, username=username, password=password)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
uwsgi_1         |     user = backend.authenticate(request, **credentials)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django_auth_ldap/backend.py", line 153, in authenticate
uwsgi_1         |     user = self.authenticate_ldap_user(ldap_user, password)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django_auth_ldap/backend.py", line 211, in authenticate_ldap_user
uwsgi_1         |     return ldap_user.authenticate(password)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django_auth_ldap/backend.py", line 353, in authenticate
uwsgi_1         |     self._authenticate_user_dn(password)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django_auth_ldap/backend.py", line 481, in _authenticate_user_dn
uwsgi_1         |     if self.dn is None:
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django_auth_ldap/backend.py", line 446, in dn
uwsgi_1         |     self._load_user_dn()
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django_auth_ldap/backend.py", line 521, in _load_user_dn
uwsgi_1         |     self._user_dn = self._search_for_user_dn()
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django_auth_ldap/backend.py", line 542, in _search_for_user_dn
uwsgi_1         |     results = search.execute(self.connection, {"user": self._username})
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django_auth_ldap/config.py", line 146, in execute
uwsgi_1         |     filterstr = self.filterstr % filterargs

**Comment by ABelhaj** [comment]
sorry guys, but i noticed that there is a lot of docker containers, 
Can you please help me with the Rebuilding process?
thank you in advance

**Comment by ravishel** [comment]
> 

HI, did you manage to authenticate with LDAP?

**Comment by de-adshot** [comment]
any idea where exactly we need to put the **C** section as per suggestion given by @manuel-sommer

**Comment by jake-cryptic** [comment]
For any future Defect Dojo users looking back at this thread to implement LDAP, please make sure to use the updated dependencies:

```
python-ldap==3.4.2
django-auth-ldap==4.1.0
```

And also include `ldap-utils` in your Dockerfile.nginx and Dockerfile.django files, like so:
```
libldap2-dev \
libsasl2-dev \
ldap-utils \
```

You can find additional docs here: https://django-auth-ldap.readthedocs.io/en/latest/
