### ISSUE TITLE
Close empty engagements

### ISSUE THREAD

**Issue by true-hero** [DefectDojo/django-DefectDojo#3989]
Hello. We have integrated DefectDojo in our CI pipeline. Every pipeline creates it's own engagement. I set up deleting duplicates, and now I have a tone of empty engagements and the amount growth every day. So, I really want to close empty engagements automatically. I think, as a quick solution, you can at least add additional field in /api/v2/engagements/ that indicates "is engagement has findings". Thanks for DefectDojo Project.

**Comment by damiencarol** [comment]
@true-hero hello and thanks for your comment.
You should use Slack for this kind of question.
A lot of users use the same engagement for all CI report and sometimes also use the reimport feature

**Comment by valentijnscholten** [comment]
Is there a reason why you're not using reimport?

**Comment by true-hero** [comment]
@valentijnscholten , to be honest, I have no idea how this endpoint works, but I read docs and swagger. I need to test it. As i understand, I can create a single engagement for project and do reimport of tests (one by one) every time my CI runs?

**Comment by damiencarol** [comment]
Yep. Also you can create a "CI/CD" engagement type.

**Comment by true-hero** [comment]
@damiencarol , can i ask you, is there any difference between engagement type (CI/CD or simple)? I see that CI/CD engagement has a little different fields, is there anything else?

**Comment by valentijnscholten** [comment]
not much, there is some logic that updates the 'end date' field based on the last scan that was uploaded. And I think it only becomes overdue after X days instead of immediately after the enddate.

**Comment by true-hero** [comment]
Thank you, Colleagues.

**Comment by SecurityEdge2** [comment]
@valentijnscholten where this X is configured. What's the default X value?

**Comment by valentijnscholten** [comment]
it's hardcoded 10 days, feel free to open a PR to make it configurable via settings for example.
