### ISSUE TITLE
Deleting a product exposes weird fields

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#3997]
**Bug description**
I don't think this information should be here. Am I deleting members?

![image](https://user-images.githubusercontent.com/5468769/109971507-a19aae00-7cf6-11eb-8ddf-e06c84aca0d3.png)

**Steps to reproduce**
1. Delete a product.

**Deployment method** *(select with an `X`)*
- [x] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
Latest `dev` as of this issue.

**Comment by StefanFl** [comment]
The members are coming from the new authorization, I can include a fix in PR #3926
