### ISSUE TITLE
No port present when importing an OpenVAS scan

### ISSUE THREAD

**Issue by MauJFernandez** [DefectDojo/django-DefectDojo#4000]
DefectDojo version: 1.12.0 (not using latest because is blocked by #3976).
Installation type: Docker.
OpenVAS version: 20.08.
Steps:
1- Add a product.
2- Add engagement.
3- Import CSV scan from OpenVAS (use this scan https://github.com/DefectDojo/django-DefectDojo/issues/3976#issuecomment-789287187).
4- Submit.
5- Review the newly created findings, no "Port" added alongside the Endpoint, which are essential to identify multiple equal vulnerabilities on the same IP but on different ports.

Expected behavior:
Port and other significant columns from the CSV scan added to the finding.

**Comment by MauJFernandez** [comment]
Hi, is there any timeline regarding this bug? Any way I can help testing?

**Comment by damiencarol** [comment]
@MauJFernandez I'm working on a fix on the parser *but* the upper layers *doesn't* take into account the port :sweat_smile:

**Comment by MauJFernandez** [comment]
Oh that's unfortunate. On the bright side, now it'll know what's a Port and can be expanded to other scanners I think.

**Comment by kiblik** [comment]
This was fixed in #4473. But please double-check.

**Comment by damiencarol** [comment]
I think @kiblik is right #4137 added lower level support and #4473 fixed the rest of the code (global support of port numbers).
This will be released with `2.0.0` at the end of the month (2021-06-29).
