### ISSUE TITLE
Maturity assessment module

### ISSUE THREAD

**Issue by alessandrosangalli** [DefectDojo/django-DefectDojo#4041]
hello, does it make sense to implement a UI for maturity assessment like OWASP SAMM v2 within the defect dojo?

I was thinking about implementing an independent project similar to https://concordusa.com/SAMM/ but open source, then I had the idea that maybe it would be useful to put it inside the defect dojo, I would like to hear opinions.

**Comment by damiencarol** [comment]
@alessandrosangalli yes it make sense. take a look at how ASVS frameworks where implemented.
![image](https://user-images.githubusercontent.com/1694940/111024513-76dbe400-83df-11eb-990b-739418e40910.png)
_-> Please keep in mind that this part is highly customizable._

**Comment by damiencarol** [comment]
@alessandrosangalli any news on your investigations? Have you been able to re-create SAMM framework with the benchmark feature?

**Comment by alessandrosangalli** [comment]
@damiencarol i need to stop this for now, but this year i want to evolve this

**Comment by damiencarol** [comment]
I honestly thing that the existing system could support well SAMM framework. One thing that could be improve is the link between benchmarks and questionnaires.
