### ISSUE TITLE
Time data parsing in Veracode SAST XML report import fails

### ISSUE THREAD

**Issue by Gby56** [DefectDojo/django-DefectDojo#4043]
`time data '' does not match format '%Y-%m-%d %H:%M:%S %Z'`

Seems like some reports I'm trying to import do not contain any `first_found_date` but I'm seeing `date_first_occurrence` elements though.

The report I'm using is version 1.5 `report_format_version="1.5"`

@damiencarol I saw you worked on dynamic parser infrastructure, is that fixed in a part 3 maybe ?
Thanks a lot !
https://github.com/DefectDojo/django-DefectDojo/blob/6a2b0e5939155554a284f90f58e6287632436ce8/dojo/tools/veracode/parser.py#L243

**Comment by Gby56** [comment]
Update: The issue comes from the builtin SCA analysis that comes with Veracode SAST reports (not their Agent-based SCA).
The findings don't have a `first_found_date` anymore, but we can see that SAST findings have a `date_first_occurrence` field.
I'd recommend handling a checkbox in the UI, or simpler, having a separate parser which specifies `Veracode + SCA`.
There is also a need for a Sourceclear parser possibly, which I may propose in a PR

**Comment by damiencarol** [comment]
@Gby56 hello and thanks a lot for your analysis!
1. Dynamic parser infrastructure was implemented to make maintenance/creation of parser easier. I tried to not change too much parsers when I'm doing work on the infra itself. But...
2. ... this work showed me that there are a lot of thing we can improve in our parsers. I have a [pull request](https://github.com/DefectDojo/django-DefectDojo/pull/3967) almost done for Veracode that improve the date management and a crash on... `first_found_date is` not existing. (speaking of the devil.. ) The work is done but I need report with finding mitigated to finish it. If you can provide me some data (anonymized or not, with a NDA or whatever) I can finish the PR that block you.
3.  For your comment:

> I'd recommend handling a checkbox in the UI, or simpler, having a separate parser which specifies Veracode + SCA.

I don't think it's a good idea. Best to follow the same design of other parsers, I mean stick to one parser that handle both cases. Take a look at nmap one or other that are able to act differently if some data are here or not.

4. For your comment:

> There is also a need for a Sourceclear parser possibly, which I may propose in a PR

It's awesome! I strongly encourage you to contribute with a PR. IF you take a look at other [PRs](https://github.com/DefectDojo/django-DefectDojo/pulls?q=is%3Apr+is%3Aopen+label%3A%22Import+Scans%22) (more [example](https://github.com/DefectDojo/django-DefectDojo/pull/4029/files)) that implements new parser and our new documentation you will see that the dynamic parser infra make things easier. I will support you in this initiative.

**Comment by Gby56** [comment]
Thanks a lot for answering ! I'm glad this is already fixed then, I had written a small ternary check to replace dates with a default empty value for example but I'll check your submission.

On the subject of splitting the parser in 2 pieces, I see what you mean yeah, is it possible to handle an option in the parser ? Think of it like a "don't parse SCA findings" checkbox in the UI.

I'm pushing on this because the Veracode offering is a bit annoying if you have a licence for both their SAST+SCA and their Agent-based SCA.
I naturally don't want to see duplicate issues on the SCA findings, also the slightly added workload of parsing SCA findings twice.

That's why eventually having the parser being able to ignore SCA, and writing the Sourceclear parser (which is Veracode Agent-based, they just acquired Sourceclear) would be the best solution IMO.

**Comment by damiencarol** [comment]
> I'll see what I can do to provide a report for testing :)

You made my day!
FYI you can send me the report on PM in Slack for privacy matters.

**Comment by damiencarol** [comment]
after some discussions on Slack with @Gby56 , I decided to finish the PR #3967 that fixes this issue.
