### ISSUE TITLE
DD - Jira integration: Jira custom priority field support 

### ISSUE THREAD

**Issue by sarosbacz** [DefectDojo/django-DefectDojo#4047]
**Is your feature request related to a problem? Please describe**
There is an option in Jira instance settings in DD to add Jira priority fields mapping. 
The issue is that the original issue field in Jira consists of 3 values (minor - high - critical) but there are 5 values (Info - critical) in DD. 
Some may consider that all I need to do is to add 2 more values to original issue field in Jira, but it is not an option since this field will be changed in every project in company and a lot of integrations will be broken.

**Describe the solution you'd like**
I'd like to have an option to add custom field ID and map id values from this field to Jira configuration. 
Custom field: 
Custom field name - "Priority" 
customfield - id 10022 
Low - 10319
Minor - 10320
Medium - 10321
High - 10322
Critical - 10323

**Describe alternatives you've considered**
There is an alternative to map 3 existing Jira priority field to 5 in Dojo, but it's not an option since it leads to misunderstanding. 

**Additional context**
Trying to map custom field names or IDs:
![image](https://user-images.githubusercontent.com/31366338/110930228-e8f9ed80-8339-11eb-85c5-8b93b0d22cb7.png)
Getting an error
![image](https://user-images.githubusercontent.com/31366338/110930356-0f1f8d80-833a-11eb-9c43-1d6d1bc7bc93.png)

**Comment by valentijnscholten** [comment]
Do you mean you do not want to use the system priority field in JIRA, but a custom field? Or am I misunderstanding?

**Comment by khubdm2** [comment]
We are using a custom field for security priority. All developers can change the bug priority in Jira according to their planning but "security priority" field is a custom field which is used only be the security team. Therefore, that would be great if we could map the DD Severity to a custom field in Jira

**Comment by zl-cruise** [comment]
This is a feature I would like to see, too. I don't know why this went stale.

**Comment by quine** [comment]
Seconding this - it would be helpful to be able to use a custom field instead of the Jira default of `Priority` (which is, unfortunately, hardcoded into DefectDojo).
