### ISSUE TITLE
AWS Sec Hub Parser sets every finding to Mitigated on import

### ISSUE THREAD

**Issue by sa-git123** [DefectDojo/django-DefectDojo#4050]
AWS Sec Hub Parser sets every finding to Mitigated on import

**Comment by sa-git123** [comment]
if finding.get('Compliance', {}).get('Status', "PASSED"): needs to be changed to if finding.get('Compliance',{}).get('Status') == "PASSED":

**Comment by damiencarol** [comment]
@sa-git123 are you able to do this 1 line pull request?
