### ISSUE TITLE
Fetching findings with staff or regular user does not yield the same results

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#4069]
**Bug description**
If I query the /findings endpoints for a `test`, I get different `count` depending on whether I am a staff/superuser or just a regular user authorized to the product. The actual responses are nearly identical, but even with http://www.jsondiff.com it's hard to tell. For sure, there is not 10380 findings count, there is only a few lines difference which I guess could be explained by potential issues in accessing certain data?

This issue does not arise in the UI. A regular user will see the proper count of findings.

Instance runs with

```
        DD_AUTHORIZED_USERS_ALLOW_CHANGE: "True"
        DD_AUTHORIZED_USERS_ALLOW_DELETE: "False"
        DD_AUTHORIZED_USERS_ALLOW_STAFF: "True"
```

As a regular user:
![image](https://user-images.githubusercontent.com/5468769/111310280-338ea900-865d-11eb-93d5-ca30b2e67fdf.png)

As an admin user:
![image](https://user-images.githubusercontent.com/5468769/111310467-68026500-865d-11eb-955d-cbbaf2204d96.png)

**Steps to reproduce**

**Expected behavior**

**Deployment method** *(select with an `X`)*
- [x] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
Latest `dev`.

**Comment by valentijnscholten** [comment]
So the findings returned are correct, but the count is wrong for non admin users.

**Comment by valentijnscholten** [comment]
@madchap what are the permissions of this user, i.e. authorized products / authorized product types. it looks like it might be occurring when a user is assigned permissions to a product type.

**Comment by madchap** [comment]
Yes, the user is assigned a product type and no product directly.
