### ISSUE TITLE
Expanding the similar findings, the filter always appear and act like the white arrow

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#4071]
**Bug description**

Expanding the similar findings, the filter always appear and act like the white arrow.

You cannot hide the filters. They should probably not be opened by default.

![image](https://user-images.githubusercontent.com/5468769/111315667-e57ca400-8662-11eb-8415-b26a451fa7dd.png)

**Steps to reproduce**

**Expected behavior**

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Commit Message: [use `git show -s --format="[%ci] %h: %s [%d]"`]

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

**Comment by valentijnscholten** [comment]
what commit are you on as I can't reproduce this on latest `dev`

**Comment by valentijnscholten** [comment]
ah, so you don't want the filters to open by default. I've seen that people don't understand the similar findings feature and are unaware which filters are applied. so I thought it would be better to open the filters by default. Open to alternatives.

**Comment by madchap** [comment]
I find it weird most likely because I guess there are so many filters.

Maybe some custom message in the blue bar or simple an interrogation point leading to text?
