### ISSUE TITLE
Defective Azure AD Tenant Integration - some users are logging in as the admin user

### ISSUE THREAD

**Issue by slicingmelon** [DefectDojo/django-DefectDojo#4073]
Hello guys, 

I have dojo 1.12.1 running with Azure Active Directory Tenant configured. A strange behavior is happening that I cannot debug. Assuming AD group **Group_One** was created with five members, two of us, when logging into dojo using azure integration, we are logged in straight as dojo admin with the email admin@defectdojo.local. 

![image](https://user-images.githubusercontent.com/57750222/111370240-a9683400-86a0-11eb-8219-f73334c95dde.png)

This is happening only to me and one other user of **Group_One**. This is very strange because the other users of the AD group are logging in as normal users. Me and the other user don't have any other special permissions. To sum up, it does not make us admin after login, but we are logging in as the admin user. Also to mention that I've never created normal dojo users, I've only set the Azure integration. 

I know it sounds unreal but this is what is happening. Please let me know what debug output you need and I will provide.

**Comment by valentijnscholten** [comment]
Can you share your config around azure ad integration?

**Comment by slicingmelon** [comment]
Hi @valentijnscholten 

Yes, here it is:
![image](https://user-images.githubusercontent.com/57750222/111428528-4c9c6600-8700-11eb-8229-4332bcc1b7c1.png)

Some other settings:
```
 DD_SITE_URL=(str, 'http://localhost:8080'),                          
 DD_DEBUG=(bool, False),                                              
 DD_TEMPLATE_DEBUG=(bool, False),                                     
 DD_LOG_LEVEL=(str, ''),                                              
 DD_DJANGO_METRICS_ENABLED=(bool, False),                             
 DD_LOGIN_REDIRECT_URL=(str, '/'),                                    
 DD_DJANGO_ADMIN_ENABLED=(bool, False),                               
 DD_SESSION_COOKIE_HTTPONLY=(bool, True),                             
 DD_CSRF_COOKIE_HTTPONLY=(bool, True),                                
 DD_SECURE_SSL_REDIRECT=(bool, False),                                
 DD_SECURE_HSTS_INCLUDE_SUBDOMAINS=(bool, False),                     
 DD_SECURE_HSTS_SECONDS=(int, 31536000),  # One year expiration       
 DD_SESSION_COOKIE_SECURE=(bool, False),                              
 DD_CSRF_COOKIE_SECURE=(bool, False),                                 
 DD_SECURE_BROWSER_XSS_FILTER=(bool, True),                           
 DD_SECURE_CONTENT_TYPE_NOSNIFF=(bool, True),                         
 DD_TIME_ZONE=(str, 'UTC'),                                           
 DD_LANG=(str, 'en-us'),                                              
 DD_WKHTMLTOPDF=(str, '/usr/local/bin/wkhtmltopdf'),                  
 DD_TEAM_NAME=(str, 'power rangers'),                                 
 DD_ADMINS=(str, 'DefectDojo:dojo@localhost,Admin:admin@localhost'),  
 DD_PORT_SCAN_CONTACT_EMAIL=(str, 'email@localhost'),                 
 DD_PORT_SCAN_RESULT_EMAIL_FROM=(str, 'email@localhost'),             
 DD_PORT_SCAN_EXTERNAL_UNIT_EMAIL_LIST=(str, ['email@localhost']),    
 DD_PORT_SCAN_SOURCE_IP=(str, '127.0.0.1'),                           
 DD_WHITENOISE=(bool, False),                                         
 DD_TRACK_MIGRATIONS=(bool, False),                                   
 DD_SECURE_PROXY_SSL_HEADER=(bool, False),                            
 DD_TEST_RUNNER=(str, 'django.test.runner.DiscoverRunner'),           
 DD_URL_PREFIX=(str, ''),                                             
 DD_ROOT=(str, root('dojo')),                                         
 DD_LANGUAGE_CODE=(str, 'en-us'),                                     
 DD_SITE_ID=(int, 1),                                                 
 DD_USE_I18N=(bool, True),                                            
 DD_USE_L10N=(bool, True),                                            
 DD_USE_TZ=(bool, True),
```

Please let me know what other settings would you like to see in particular.

**Comment by valentijnscholten** [comment]
I am not using Azure AD integration myself, but Defect Dojo is just using `social-auth-app-django`.
It seems poorly documented, but it seems that the config below triggers the module to get extra permissions from the MS graph:

```
SOCIAL_AUTH_AZUREAD_OAUTH2_RESOURCE = 'https://graph.microsoft.com/'
```

Not sure what that means or what that does, but maybe because of some properties of your user account it thinks you're the admin? or an admin? 

Better to ask at `social-auth-app-django` or `social-core` what is going on. Or join us on slack to see if anybody else is experiencing this.

**Comment by valentijnscholten** [comment]
Or maybe something is going on with retrieving the social id for users: https://github.com/DefectDojo/django-DefectDojo/blob/d2b94a52696dbf0b2696018b24a2407bb911a1e4/dojo/pipeline.py#L12

@Maffooch do you know how this works?

**Comment by Maffooch** [comment]
I wrote that function for an OKTA backend a couple years ago before is was officially supported by `social-core`, but it has grown since then to be used by the Google and Azure backends. My reasoning for it with OKTA was that user emails would be mapped correctly, but would also have a UUID appended. This forced a new account each time a person logged in.

Changes here were by @dougmorato in #1309

**Comment by dougmorato** [comment]
Users should be imported/created  as regular users ( after the change from @madchap  on https://github.com/DefectDojo/django-DefectDojo/commit/a0b1e669212b99b8f150315c7be37326b2be2ba6#diff-756c78208a4432d915ca32889680a6069043af0602d96b4afb9b3a40449b4dfc )

Check if you dojo/pipeline.py   user.is_staff = False like below

https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/pipeline.py#L61

**Comment by valentijnscholten** [comment]
Thanks. The symptom seen is that the user is logged in as 'admin'. So not logged in as itself, but as a completely different user (with username admin). Pretty sure it's not in our code.

**Comment by dougmorato** [comment]
alternatively, go to the dojo_app/admin , look for "social core" or something in that admin backend, you should be able to delete any UUID mappings associated with the admin account

**Comment by slicingmelon** [comment]
@dougmorato Thank you, I've found two azure UUID mapped to admin indeed. I deleted them and now we are able to log in as normal users. 

I think this is a legit bug and perhaps it should be addressed by a proper fix, not just a workaround.

**Comment by valentijnscholten** [comment]
Are you able to reproduce it? I'm sure the folks at `social-auth-app-django` are interested in a bug report so they can look at fixing it.
