### ISSUE TITLE
cleanup 2.0: Remove code to produce and store PDF reports

### ISSUE THREAD

**Issue by StefanFl** [DefectDojo/django-DefectDojo#4077]
PDF reports are not supported anymore for more than a year now, for a good reason. Users can print the HTML report via their browser. All the existing code that supports generating and storing PDF reports shall be removed.

**Comment by valentijnscholten** [comment]
@StefanFl feel free to make a PR, the next release is 2.0.0

**Comment by valentijnscholten** [comment]
done in dev/2.0.0
