### ISSUE TITLE
Support OIDC i.e. Keycloak authentication

### ISSUE THREAD

**Issue by dsolanki28** [DefectDojo/django-DefectDojo#4103]
**Is your feature request related to a problem? Please describe**

We are not able to configure keycloak open-id authentication with defectdojo using helm.

**Describe the solution you'd like**

In a similar fashion to that of Google, OKTA, Gitlab as a OAuth2 provider, we expect variables for keycloak open-id provider i.e. DD_SOCIAL_AUTH_KEYCLOAK_*, so that we can use these variables in helm values.yaml.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you have considered.

**Additional context**
Add any other context, screenshots, sketch, code snippet, etc. about the feature request here.

**Comment by dsever** [comment]
@dsolanki28 you can use extra vars in k8s 

https://github.com/DefectDojo/django-DefectDojo/blob/master/helm/defectdojo/values.yaml#L285

**Comment by dsolanki28** [comment]
@dsever thanks for the link. I had used these extra vars for configuring gitlab oauth2 provider. But since, patch for keycloak is missing in settings.dist.py, I believe, there would be no use to provide keycloak variables in extraConfigs. 

Refer this issue: https://github.com/DefectDojo/django-DefectDojo/issues/3129.

Let me know if I am missing something.

**Comment by dsever** [comment]
Honestly, this is new to me that oidc is supported at all. 

Yes env readers are missing

**Comment by dsolanki28** [comment]
Thanks for the information. Actually, our requirement is to have oauth2 rather than saml. Could you give some insight if oidc keycloak can be a part of future improvements ?

**Comment by cynthia-rempel** [comment]
Random notes to document how to enable keycloak auth...
https://python-social-auth.readthedocs.io/en/latest/backends/keycloak.html?highlight=keycloak

grep -n AUTHENTICATION_BACKENDS django-DefectDojo/dojo/settings/settings.dist.py
...
372:AUTHENTICATION_BACKENDS = (
vi +372 django-DefectDojo/dojo/settings/settings.dist.py
AUTHENTICATION_BACKENDS = (
    ...
    'social_core.backends.keycloak.KeycloakOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)
docker-compose up --build
... 
additional ENV settings to follow....

**Comment by cynthia-rempel** [comment]
grep -Rn SOCIAL_AUTH_ django-DefectDojo/ | grep KEY
django-DefectDojo/dojo/settings/settings.dist.py:434:SOCIAL_AUTH_AUTH0_KEY = env('DD_SOCIAL_AUTH_AUTH0_KEY')
vi +434 django-DefectDojo/dojo/settings/settings.dist.py
KEYCLOAK_OAUTH2_ENABLED = env('DD_SOCIAL_AUTH_KEYCLOAK_OAUTH2_ENABLED')
SOCIAL_AUTH_KEYCLOAK_KEY = env('DD_SOCIAL_AUTH_KEYCLOAK_KEY')
SOCIAL_AUTH_KEYCLOAK_SECRET = env('DD_SOCIAL_AUTH_KEYCLOAK_SECRET')
SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY = env('DD_SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY')
SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL = env('DD_SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL')
SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL = env('DD_SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL')

...
additional ENV settings to follow....

**Comment by cynthia-rempel** [comment]
Looks like some additions to
django-DefectDojo/dojo/context_processors.py
django-DefectDojo/dojo/templates/dojo/login.html
might be required...

**Comment by cynthia-rempel** [comment]
[defectdojo@nexus06 ~]$ grep -Rn -A5 -B1 KEYCLOAK_ENABLED django-DefectDojo/
django-DefectDojo/dojo/templates/dojo/login.html-39-
django-DefectDojo/dojo/templates/dojo/login.html:40:                {% if KEYCLOAK_ENABLED is True %}
django-DefectDojo/dojo/templates/dojo/login.html-41-                    <div class="col-sm-offset-1 col-sm-2">
django-DefectDojo/dojo/templates/dojo/login.html-42-                        <button class="btn btn-success" type="button">
django-DefectDojo/dojo/templates/dojo/login.html-43-                            <a href="{% url 'social:begin' 'keycloak' %}?next={{ request.GET.next }}" style="color: rgb(255,255,255)">Login with Keycloak</a>
django-DefectDojo/dojo/templates/dojo/login.html-44-                        </button>
django-DefectDojo/dojo/templates/dojo/login.html-45-                    </div>
--
django-DefectDojo/dojo/context_processors.py-10-            'GOOGLE_ENABLED': settings.GOOGLE_OAUTH_ENABLED,
django-DefectDojo/dojo/context_processors.py:11:            'KEYCLOAK_ENABLED': settings.KEYCLOAK_OAUTH2_ENABLED,
django-DefectDojo/dojo/context_processors.py-12-            'OKTA_ENABLED': 
....

**Comment by cynthia-rempel** [comment]
Pulled up the keycloak prompt, but I got an SSL error...

**Comment by cynthia-rempel** [comment]
Fixed the SSL error by adding the keycloak certs to docker/certs/ and adding the cert as a volume that overrides the certifi root certs.

**Comment by cynthia-rempel** [comment]
On keycloak disabled the full scope
![image](https://user-images.githubusercontent.com/24236064/121437830-bf9c2e00-c937-11eb-94e6-5e9d16a4f1d3.png)
And added an audience mapping
![image](https://user-images.githubusercontent.com/24236064/121437742-9bd8e800-c937-11eb-8019-debeac76f732.png)

**Comment by cynthia-rempel** [comment]
Logged into defectdojo successfully... 
![image](https://user-images.githubusercontent.com/24236064/121437965-05f18d00-c938-11eb-8612-74da076f7072.png)

**Comment by cynthia-rempel** [comment]
Of course, I'm a user, not a maintainer, so ...

**Comment by cynthia-rempel** [comment]
[keycloak.patch.txt](https://github.com/DefectDojo/django-DefectDojo/files/6627433/keycloak.patch.txt)
Redacted, and overly verbose patch that enables keycloak-oidc login for defectdojo... Thinking back, it probably would have made more sense to enable SAML social auth... Oh well :)

**Comment by cynthia-rempel** [comment]
Forgot to put in the patch, on the keycloak client, the BASE URL is: /complete/keycloak/
