### ISSUE TITLE
Allow call to external API as notification type

### ISSUE THREAD

**Issue by saldam72** [DefectDojo/django-DefectDojo#4104]
Hello Teams,
have you planned to develop a notification that invokes an API ?

Best,
Sal

**Comment by damiencarol** [comment]
You mean like a web-hook? We have a feature that is a web-hook.

**Comment by saldam72** [comment]
I've never used a web-hook but it might be fine ... where do I find the documentation?

**Comment by valentijnscholten** [comment]
Please try to make more meaningful summaries/descriptions of you github issues that make it clear what it is that you are requesting.

**Comment by saldam72** [comment]
Hello Teams,
I have seen here https://defectdojo.readthedocs.io/en/latest/features.html?highlight=notifications#notifications that DefectDojo can inform of different events in a variety of ways. We want to integrate DefectDojo with an internal system via API to notify them of different events such as added test or closed engagement.

@damiencarol told me about web-hooks which might be fine but I haven't found any documentation explaining how it works, can you help me ?

Best,
Sal
