### ISSUE TITLE
NodeJS Scan report

### ISSUE THREAD

**Issue by zakrush** [DefectDojo/django-DefectDojo#4105]
**Scanner Name**
NodeJsScan https://github.com/ajinabraham/njsscan

Hello. 
Into documents of DD you have that DD is support NodeJSScan result. https://defectdojo.readthedocs.io/en/latest/integrations.html#node-js-scan

Now I'm testing dd and don't see NodeJS Scan import. 
Did you delete nodejsscan integration?

I use 1.13.2 of DD

**Comment by damiencarol** [comment]
@zakrush working on a pull request that is able to import scans from njsscan with SARIF format (https://github.com/DefectDojo/django-DefectDojo/pull/4111).

**Comment by zakrush** [comment]
@damiencarol  ok/ Thank you. Wait merge.

**Comment by damiencarol** [comment]
@zakrush merged a pull request that support njsscan report in SARIF format. This will be part of `0.14.0`
