### ISSUE TITLE
Add "Created" Finding field to Findings Views (Open, Closed etc.)

### ISSUE THREAD

**Issue by pisces-period** [DefectDojo/django-DefectDojo#4112]
When I use `SonarQube API Import`  and `SonarQube` test types to import findings into DefectDojo, by default the `Findings` view displays `date` field as the date when the issue was imported to DefectDojo, but the date when the issue was created in the source tool is not displayed. 

It is possible to override the date to reflect the date when the issue was created in the source tool, but then you are unable to see the date when the issue was uploaded to DefectDojo.

As a DevSecOps Engineer, I would like to be able to see both the `DefectDojo creation date` and the `source issue creation date` (e.g., SonarQube issue creation date) side-by-side in the Findings views.

I have tried to create a `custom field` in DefectDojo for this purpose, but the custom field is added to the Product view, not finding.

Skimming through the code, I noticed that the `finding` model already has this data. 
- there is a field called [date](https://github.com/DefectDojo/django-DefectDojo/blob/77f241afd7773a95a73621fcc60971263885337a/dojo/models.py#L1466), which you can override, and which influences the calculation of SLA field
- and a field called [created](https://github.com/DefectDojo/django-DefectDojo/blob/77f241afd7773a95a73621fcc60971263885337a/dojo/models.py#L1693), which is automatically set by Django and not editable.

This second field is not visible in the `Findings` views. 

My proposition is to add the `created` field to the Findings views, so that both dates are displayed.

**Comment by damiencarol** [comment]
What you're describing is a bad implementation of the parser that doesn't set the date of the finding with the good value or don't set it at all (the current behavior is to set it to the current date)
To fix that, we must improve how the parser manage the attribute `date` of findings.

**Comment by pisces-period** [comment]
Hi @damiencarol, thanks for your swift response.

I don't quite see it as a bad implementation of the parser (I should mention that by using DefectDojo APIv2 `/findings/` endpoint I'm able to bypass parsers and send the payload directly, which gives me the opportunity to override the `date` value).

The default behavior is already correct in my assessment. If DefectDojo were to consider the issue creation as the `date` and I import a SonarQube issue that is 500 days old, my DefectDojo SLA would have been exceeded by over 470 days at the time of import. So it does make sense to use the current date instead.

I can set the `date` field to my choosing, but even then, I will only ever see one date. And this is where I would like to propose an enhancement.

Currently, DefectDojo records the current date twice  - in [created](https://github.com/DefectDojo/django-DefectDojo/blob/77f241afd7773a95a73621fcc60971263885337a/dojo/models.py#L1693) field and [date](https://github.com/DefectDojo/django-DefectDojo/blob/77f241afd7773a95a73621fcc60971263885337a/dojo/models.py#L1466) field (by default). I suppose the second field is reserved for use in the database, since it is not visible in the `Findings` view.

What I would like to suggest is the ability to use the second date field as well, to display both dates, side-by-side, in the `Findings` view (with DefectDojo `created` field used for SLA calculation).

**Comment by valentijnscholten** [comment]
There are so many fields on the findings that we can't show them all. I think we should look at maybe making it configurable which columns/fields to show. And possibly use the feature from the clientside Datatables() we're using where you can hide/unhide columns.

**Comment by pisces-period** [comment]
Hi @valentijnscholten, yes that would solve our problem!

**Comment by damiencarol** [comment]
@valentijnscholten there is this features discussed for the UI v2 SPA.
