### ISSUE TITLE
Swap ptvsd for debugpy, ptvsd deprecated

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#4115]
As mentioned by @ptrovatelli  at https://owasp.slack.com/archives/C014H3ZV9U6/p1616534386011200

> so it seems that ptvsd is deprecated, replaced by debugpy (see https://github.com/microsoft/ptvsd ). ptvsd is what we use for debugging with docker.

**Comment by yilmi** [comment]
Can't close this task myself.

**Comment by valentijnscholten** [comment]
fixed in dev/2.0.0
