### ISSUE TITLE
Jira Integration - Wrong issuetypes

### ISSUE THREAD

**Issue by xanhacks** [DefectDojo/django-DefectDojo#4116]
**DD version : 1.12.1**
**Jira version : 8.5.4**

Hello ! I have an issue when I want to add the Jira configuration to my product.

Here is the error :
```sh
[23/Mar/2021 12:14:38] WARNING [dojo.jira_link.helper:676] unable to retrieve metadata from JIRA JIRA PROJ | http://jira-url | user.name for issuetype Bug in project PROJ. Invalid default issue type configured in Defect Dojo?
[23/Mar/2021 12:14:38] WARNING [dojo.jira_link.helper:677] get_jira_meta: {
    "expand": "projects",
    "projects": [
        {
            "expand": "issuetypes",
            "self": "http://jira-url/rest/api/2/project/10000",
            "id": "10000",
            "key": "PROJ",
            "name": "Project name",
            "avatarUrls": {
                "48x48": "http://jira-url/secure/projectavatar?pid=10000&avatarId=10201",
                "24x24": "http://jira-url/secure/projectavatar?size=small&pid=10000&avatarId=10201",
                "16x16": "http://jira-url/secure/projectavatar?size=xsmall&pid=10000&avatarId=10201",
                "32x32": "http://jira-url/secure/projectavatar?size=medium&pid=10000&avatarId=10201"
            },
            "issuetypes": []
        }
    ]
}
```

But when I go to `http://jira-url/rest/api/2/project/10000` manually, I get plenty of issue types. So, I don't know why I can't connect Jira and DD.

Have a nice day !

**Comment by valentijnscholten** [comment]
This error indicates that with the credentials provided the issuetype `Bug` cannot be found in the meta data from JIRA. Is there such an issue type in that project?

**Comment by xanhacks** [comment]
No matter what issue type I put on DD, it always returns an empty issue type array.
`"issuetypes": []`

However I have many issuetypes created.
![Screenshot_2021-03-25 Screenshot](https://user-images.githubusercontent.com/23367144/112447175-4b4ae900-8d51-11eb-84c7-87fb71bd3acd.png)
