### ISSUE TITLE
Creating tags on findings require superuser rights

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#4125]
**Bug description**
Using a non-superuser user and wanting to tag findings through, it does not work. It fails with a 403.
`staff` is not needed, but `superuser` is.

A bit bothersome for service accounts :-/

**Comment by valentijnscholten** [comment]
Can you provide some info on how to reproduce this? I assume this is referring to the API as in the UI it seems to work fine.
Are you using a PATCH/POST on the finding itself? Or are you using the `/findings/tags` endpoint?

**Comment by damiencarol** [comment]
Is it something that will change/be modified with auth v2 system?

**Comment by valentijnscholten** [comment]
Yes, I was also thinking we should maybe just make sure that it works in the new system and not spent too much time on the old system. The "official" python API wrapper needs a superuser anyway to work, so easier to accept for now and fix everything when the new permissions are there.

**Comment by StefanFl** [comment]
With auth v2 you can add tags when you have the role Writer, Maintainer or Owner, just checked that.
