### ISSUE TITLE
WPScan parser does not parse all found vulnerabilities

### ISSUE THREAD

**Issue by manuel-sommer** [DefectDojo/django-DefectDojo#4129]
**Be informative**
I have scanned a vulnerable Wordpress Website with WPScan 3.8.15. It found a vulnerability in "contact-form-7". This vulnerability is not uploaded to Defectdojo as it is not processed by the parser.

**Steps to reproduce**
1. Run DefectDojo
2. Run a WP scan to output a JSON
3. Upload the JSON 

I have attached an output example of the JSON file. 

**Expected behavior**
The parser should parse all CVE 

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [Ubuntu 18.04]
 - DefectDojo Commit Message: [2021-03-25 21:38:57 +0100] 1fe8bb52: SARIF: support date of findings, add more tests (#4111) [ (HEAD -> dev, origin/dev)]

[wpscanjson.zip](https://github.com/DefectDojo/django-DefectDojo/files/6210218/wpscanjson.zip)

**Comment by damiencarol** [comment]
@manuel-sommer taking a look at it.

**Comment by damiencarol** [comment]
@manuel-sommer made some tests with recent version of WPScan and you're right, there is a pb.
Working on a pull request to solve this and improve the parser.
