### ISSUE TITLE
IPv6 not well supported in Finding view

### ISSUE THREAD

**Issue by damiencarol** [DefectDojo/django-DefectDojo#4138]
**Bug description**
When and endpoint as an IP v6 address in it, it is truncated.
Ex: `2001:8::1` become `8::1` in the UI

**Steps to reproduce**
1. Import a report with an endpoint that have an IP v6 address
2. Click on finding view
3. See IP v6 address truncated

**Expected behavior**
 I was expecting IP v6 address  `2001:8::1` in the UI

**Deployment method** *(select with an `X`)*
- [x] Docker

**Environment information**
 - Operating System: Arch
 - DefectDojo Commit Message: `91de047e: Bump sqlalchemy from 1.4.2 to 1.4.3 (#4126) [ (HEAD -> dev, upstream/dev, origin/dev)]`

**Sample scan files** (optional)
OpenSCAP report file
[ios-sample-v1.1.3.xccdf.xml.txt](https://github.com/DefectDojo/django-DefectDojo/files/6214710/ios-sample-v1.1.3.xccdf.xml.txt)

**Screenshots** (optional)
![image](https://user-images.githubusercontent.com/1694940/112702095-af28fb00-8e92-11eb-9db7-f8a9a5ed840b.png)

![image](https://user-images.githubusercontent.com/1694940/112701773-d03d1c00-8e91-11eb-99c5-93908218fe38.png)

**Comment by kiblik** [comment]
Is this still issue? I suppose it was fixed in #4473

**Comment by damiencarol** [comment]
@kiblik we have tests on IPv6 since #4473 ?

**Comment by kiblik** [comment]
https://github.com/DefectDojo/django-DefectDojo/blob/3817f3aa7914da306d6925000f0f6462c9a44325/dojo/unittests/tools/test_openscap_parser.py#L65

**Comment by damiencarol** [comment]
Ok. well done. I'm closing it.
