### ISSUE TITLE
Trying to import WebInspect files but get parser error

### ISSUE THREAD

**Issue by jamshaid120** [DefectDojo/django-DefectDojo#4155]
I am trying to import [webinspect](https://github.com/DefectDojo/sample-scan-files/tree/master/webinspect) files in **ScanType** IBM AppScan DAST but it throws the following error:
` An error has occurred in the parser, please see error log for details. `
the environment is set to default and **minimum security** is **info**. I have tried all the files given in repo but always get the above-mentioned error. I am on version  v. 1.13.2 ( release mode ) 

**Steps to reproduce**

1. Goto Products -> All Products
2. Select a product
3. Goto Engagements -> add new engagement 
4. Click on Import Scan results 
5. Select scan type as IBM AppScan DAST
6. select environment as Default
7. Upload [this](https://github.com/DefectDojo/sample-scan-files/blob/master/webinspect/Webinspect_V(18.20).xml) file
8. Click on import and you will see the above-mentioned error.

**Expected Behavior** 
It should have uploaded the scan result successfully

**Deployment Method**
I am using dojo in a docker container. 

**Environment information**
 - Operating System: [ Ubuntu 18.04]

**Comment by valentijnscholten** [comment]
Please complete the info as requested in https://github.com/DefectDojo/django-DefectDojo/issues/new?assignees=&labels=bug&template=bug_report.md&title=

**Comment by jamshaid120** [comment]
> Please complete the info as requested in https://github.com/DefectDojo/django-DefectDojo/issues/new?assignees=&labels=bug&template=bug_report.md&title=

@valentijnscholten  I just updated the question

**Comment by damiencarol** [comment]
taking a look

**Comment by jamshaid120** [comment]
> taking a look

Thanks. I will be waiting for your kind response

**Comment by damiencarol** [comment]
I was able to import it easily in our demo environment ( see the result here https://demo.defectdojo.org/test/55 )

**Comment by jamshaid120** [comment]
> I was able to import it easily in our demo environment ( see the result here https://demo.defectdojo.org/test/55 )

How do I log in to demo server?

**Comment by jamshaid120** [comment]
> I was able to import it in our demo environment ( see the result here https://demo.defectdojo.org/test/55 ) without error.
> I think you use the wrong type `IBM AppScan DAST` instead of `Microfocus Webinspect Scan`

I have to import for DAST. And DAST is only available in IBM Appscan DAST. Am I uploading the wrong file for DAST?

**Comment by damiencarol** [comment]
Take a look at our *Quick start* section of our README https://github.com/DefectDojo/django-DefectDojo#quick-start . don't hesitate to close the issue if it solve the pb for you.

**Comment by jamshaid120** [comment]
> Take a look at our _Quick start_ section of our README https://github.com/DefectDojo/django-DefectDojo#quick-start . don't hesitate to close the issue if it solve the pb for you.
> 
> > I have to import for DAST. And DAST is only available in IBM Appscan DAST. Am I uploading the wrong file for DAST?
> 
> it seems

Quickstart doesn't mention anything for this. Would you please guide me on which file should I try to upload for DAST? It would be a great help.

**Comment by jamshaid120** [comment]
@damiencarol I tested my steps on the demo server and It produces the error there too. Which files am I supposed to use for IBM AppScan DAST?

**Comment by jamshaid120** [comment]
Thanks, @damiencarol  for giving a hint about using the wrong file. I tried using [ibm_appscan_xml_file.xml](https://raw.githubusercontent.com/DefectDojo/sample-scan-files/master/appscan/ibm_appscan_xml_file.xml) file and it was uploaded successfully. Thanks a lot. I will update my docs for this.

**Comment by damiencarol** [comment]
good to know!
