### ISSUE TITLE
Django error is thrown when passing MobSF report into DefectDojo 

### ISSUE THREAD

**Issue by whitespots** [DefectDojo/django-DefectDojo#4158]
**Bug description**
MobSF v.  3.4.0 
Dojo is latest from master v. 1.13.2 ( release mode ) 
Error: Internal Server Error: /engagement/1/import_scan_results (500)

**Steps to reproduce**
1. Import scan results via API or UI. 
2. See error

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: any

**Screenshots** (optional)
<img width="1167" alt="Screenshot 2021-03-29 at 13 50 27" src="https://user-images.githubusercontent.com/65983771/112834957-51b6c900-90a1-11eb-8f88-3452a321c205.png">
<img width="1595" alt="Screenshot 2021-03-29 at 13 50 56" src="https://user-images.githubusercontent.com/65983771/112834961-52e7f600-90a1-11eb-9bb8-bfd5c1c38a13.png">
<img width="1790" alt="Screenshot 2021-03-29 at 13 51 09" src="https://user-images.githubusercontent.com/65983771/112834969-54b1b980-90a1-11eb-83df-af25038d518f.png">
<img width="1475" alt="Screenshot 2021-03-29 at 13 52 19" src="https://user-images.githubusercontent.com/65983771/112834973-55e2e680-90a1-11eb-9c55-c275c051b4ad.png">

**Comment by damiencarol** [comment]
@whitespots made some analysis, it's a bug. working on a PR to fix this

**Comment by Ivanello** [comment]
looks like updated issue  #3134

**Comment by damiencarol** [comment]
Fixed and will go in `0.14.0`
