### ISSUE TITLE
ORT parser error when importing oss-review-toolkit file

### ISSUE THREAD

**Issue by devsecopsale** [DefectDojo/django-DefectDojo#4161]
**Slack us first!**
I get an error when I try to upload an ORT report file that contains violation rules items with no 'license' or 'license_source' fields. I actually fixed this by checking the values do exist before handling the python keys. I'm submitting a pull request

**Be informative**
This bug prevents from uploading ORT scans files. This will typically occurs when a custom license is defined and it's unresolved but declared.

**Bug description**
This bug prevents from uploading ORT scans files.

**Steps to reproduce**
1. Go to a Test type 'import scan results' from ORT type
2. Click on 'choose file'
3. Select the file that contains violation rules with no license or license_source fields.
4. See error and see debugging errors in the logs. Those ones are caused by the ORT parser.py file

**Expected behavior**
an error will be seen.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [Redhat]
 - DefectDojo Commit Message: [use `git show -s --format="[%ci] %h: %s [%d]"`]

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

**Comment by damiencarol** [comment]
fixed in `dev` / `1.15.0`
