### ISSUE TITLE
How to remove Mitigated Endpoints / Systems or Vulnerable Endpoints / Systems section in the finding.

### ISSUE THREAD

**Issue by BhaskiBuzz** [DefectDojo/django-DefectDojo#4180]
Hi,

Is there any way to remove Mitigated Endpoints / Systems or Vulnerable Endpoints / Systems section displaying when we open the finding.

These endpoints looks not relevant to the finding so we are trying to remove that section in the finding view completely. 

Thanks.

**Comment by valentijnscholten** [comment]
@Maffooch

**Comment by damiencarol** [comment]
Maybe an update on the view to hide the part if the attribute is not set.
