### ISSUE TITLE
cannot load certificate "/etc/nginx/ssl/nginx.crt" BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:

### ISSUE THREAD

**Issue by jamshaid120** [DefectDojo/django-DefectDojo#4181]
I am trying to build dojo on a Linux environment in Docker but after I run docker-compose up, the container ends up with the following error:   
Basic auth is off (HTTP_AUTH_PASSWORD not provided)
2021/03/31 15:16:33 [emerg] 1#1: cannot load certificate "/etc/nginx/ssl/nginx.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/ssl/nginx.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: [emerg] cannot load certificate "/etc/nginx/ssl/nginx.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/ssl/nginx.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)

Previously it was working fine. I changed the certificate to a production certificate and the issue started appearing. I changed the certificate back to the self-signed certificate but not any luck on the successful run. 
Any comments on this? Thanks a lot

**Comment by valentijnscholten** [comment]
please provide the details requested in the bug report template.
