### ISSUE TITLE
Jira - Create EPIC field via API

### ISSUE THREAD

**Issue by xanhacks** [DefectDojo/django-DefectDojo#4187]
![Screenshot_2021-04-01 Edit Engagement DefectDojo](https://user-images.githubusercontent.com/23367144/113293080-9c308380-92f5-11eb-81c0-ede3babffc0d.png)

Hello,

I would like to **edit the field "Create EPIC"** in a engagement using the DefectDojo **APIv2** however I could not find where ?
Is this not implemented yet or I'm just blind ?

Regards,
xanhacks

**Comment by valentijnscholten** [comment]
I don't think it's implemented.
