### ISSUE TITLE
GVM report not adding hostnames on defectdojo with CSV report

### ISSUE THREAD

**Issue by maibold1** [DefectDojo/django-DefectDojo#4193]
Hi im a new to the community and im sorry if this has been addressed before but i cant find any info on this situation.

I installed the version 1.7.1 of DefectDojo

Then i import some vulnerability scan reports from GVM 28.1 without issue 

When i check the endpoints i can see the ip address but not the hostname 

The data related to the endpoint seems to be complete except for the missing hostname, Is maybe a compatibility issue or im missing something with the import.

Thanks

**Comment by valentijnscholten** [comment]
Please upgrade to 1.14.0 and try again. There's a lot of work being on endpoints in https://github.com/DefectDojo/django-DefectDojo/pull/4188

**Comment by maibold1** [comment]
> Please upgrade to 1.14.0 and try again. There's a lot of work being on endpoints in #4188

Hi @valentijnscholten thanks for the reply I actually upgrade as you recommended but still have the same behavior ... Should a start clean?.... I keep the volumes on the upgrade and all the reports previously added to test.

**Comment by valentijnscholten** [comment]
I think it just needs to be fixed, I don't know the details, but 4188 looks like it will fix a lot of peculiarities around endpoints.

**Comment by maibold1** [comment]
Thanks for the info I'll keep an 👀 for when merge the 4188 to dev branch and try again

**Comment by maibold1** [comment]
Hi i tray the latest version and it indeed bring the host names please close
