### ISSUE TITLE
Right evaluation of endpoint status

### ISSUE THREAD

**Issue by kiblik** [DefectDojo/django-DefectDojo#4198]
Endpoint evaluates status (if it is vulnerable and active and/or mitigated) based on [Finding fields](https://github.com/DefectDojo/django-DefectDojo/blob/b3393ecf09562da93b987e1eb598e823ff25e92a/dojo/models.py#L1163-L1199). However the real status depends (also) on the content of `Endpoint_Status`.

I suppose this should be redesigned when https://github.com/DefectDojo/django-DefectDojo/pull/4188 / https://github.com/DefectDojo/django-DefectDojo/pull/4473 will be finished. 

Another reason: https://owasp.slack.com/archives/C2P5BA8MN/p1621324919005200

**Comment by valentijnscholten** [comment]
Yeah, the endpoint_status thing wasn't 100% completed I think. There are also some performance issues around it which we need to tackle.

**Comment by kiblik** [comment]
Before implementation check https://owasp.slack.com/archives/C2P5BA8MN/p1645522693583909

**Comment by kiblik** [comment]
Fixed in https://github.com/DefectDojo/django-DefectDojo/pull/6193
