### ISSUE TITLE
Create endpoints via API?

### ISSUE THREAD

**Issue by xthk** [DefectDojo/django-DefectDojo#420]
### Issue Type 

- [ ] Bug
- [X] Enhancement

### Description

I'd like to be able to create endpoints via DefectDojo's API and link them to their associated products. To be a bit more precise, I'd love to see all CRUD (create, read, update, delete) operations for endpoints.

**Comment by aaronweaver** [comment]
@xthk Just curious, what's your use case for adding endpoints to the API?

**Comment by xthk** [comment]
Hi @aaronweaver,

we've just a large amount (1000+) of endpoints. We'd like to have them in DefectDojo, too. Due to the amount it is not an option to maintain the endpoint/project mapping by hand.

**Comment by devGregA** [comment]
Completed
