### ISSUE TITLE
Delete JIRA configurations?

### ISSUE THREAD

**Issue by xthk** [DefectDojo/django-DefectDojo#421]
### Issue Type 
- [X] Bug
- [ ] Enhancement

### Description

I'm not sure if this is a bug or an enhancement: It is possible to create multiple JIRA, but I don't see any option to delete a JIRA configuration on "/jira" or "/jira/<id>/edit ".

I'd assume that besides creating and editing it should be possible to delete a JIRA configuration.

### Operating System 

Ubuntu 16.04, Python 2.7.11, Django 1.11.2.

### Install

- [ ] setup.bash
- [ ] docker
- [X] custom

### Steps to Reproduce

- create JIRA configuration
- navigate to "/jira" or edit JIRA configuration

**Comment by devGregA** [comment]
Believe to be fixed via ee3e7ca

Please reopen this issue if you continue to have issues.
