### ISSUE TITLE
Push to JIRA: (pre)select JIRA configuration

### ISSUE THREAD

**Issue by xthk** [DefectDojo/django-DefectDojo#422]
### Issue Type 
- [ ] Bug
- [X] Enhancement

### Description

It is possible to select "Push to jira" upon creating or updating a finding, but it is not possible to select a JIRA configuration if more than one is available.

I'd expect to be able to select a JIRA configuration or even better to configure (pre-select) a JIRA configuration per project.

Screenshot:

![defectdojo_push2jira_2017-12-11](https://user-images.githubusercontent.com/5803044/33824701-88f430f8-de5f-11e7-9acf-a9586725663c.png)
 
### Steps to Reproduce

- Create a finding
- Select "Push to jira" prior to submitting with the "Finished" button.

**Comment by devGregA** [comment]
Hi @xthk This is controlled by Product creation/editing. Here is the menu:
![image](https://user-images.githubusercontent.com/4741312/33835311-a9a72436-de4b-11e7-8ad8-fc665d964d25.png)

**Comment by xthk** [comment]
Hi @devGregA,

if I create a new product using "/product/add" the dialog is shown. However, if I edit an existing product using e.g. "/product/1/edit" the dialog is not shown. Is this intentional or is it just a bug?

PS: I've created all products via the API, maybe this makes a difference somehow.

**Comment by xthk** [comment]
I've just tried it: If I create a product via the API the JIRA dialog does not show up. If I create it manually via the UI the JIRA dialog is shown.

That's how I create products (Ruby), it's a minimalistic example:

```
  payload = { 'name' => name.to_s,
              'description' => name.to_s,
              'prod_type' => product_type.to_s,
              'created' => timestamp.to_s }.to_json
  puts payload
  RestClient.post("#{dojo_api}/products/",
                  payload, headers = {
                    'Authorization' => "ApiKey #{dojo_user}:#{dojo_token}",
                    'content-type' => 'application/json'
                  })
```

**Comment by devGregA** [comment]
@xthk will investigate.

**Comment by xthk** [comment]
Another (sub-)issue is, that the checkbox "push to Jira" is shown even if there is no valid configuration for a given project.

**Comment by xthk** [comment]
To add the missing Jira config, I'm using a small Python script as a workaround. Please note, "project_key" and "component" are placeholders at the moment. You'll need additional code for that.

```python
#!/usr/bin/env python
import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "dojo.settings")
import django
django.setup()

# import DefectDojo's models
from dojo.models import JIRA_Conf
from dojo.models import JIRA_PKey
from dojo.models import Product

import pprint
pp = pprint.PrettyPrinter()

# get JIRA_Conf object
jira_conf = JIRA_Conf.objects.filter(pk=1)
pp.pprint(jira_conf.first)

products = Product.objects.all()
for product in products:
    print "-- %s --" % product
    print product.id
    jira_keys = JIRA_PKey.objects.filter(id=product.id)
    if not jira_keys:
        jira = JIRA_PKey(
            push_notes=True, project_key="FOO", push_all_issues=True,
            component="BAR", conf=jira_conf.first(), product=product
        )
        pp.pprint(jira)
        jira.save()
    else:
        print jira_keys
```
