### ISSUE TITLE
Apply new/updated rules to existing findings

### ISSUE THREAD

**Issue by whitespots** [DefectDojo/django-DefectDojo#4228]
**Bug description**
Dojo is unable to apply new rules to findings because it does not look through findings after rule was added.

**Steps to reproduce**
1. Create rule
2. Expecting it to be applied on all findings
3. Rule only applies when you click “Touch finding”
4. There are thousands of findings
It's impossible to click “Touch finding” on each of them.

![image](https://user-images.githubusercontent.com/65983771/114065811-bc3ae680-98a3-11eb-9afa-20da94e7b774.png)
![image](https://user-images.githubusercontent.com/65983771/114065877-c957d580-98a3-11eb-8eb5-3fba5b616fd4.png)

**Comment by vishnupriyaavp8** [comment]
### **Suggested Edit**

master/dojo/rules/views.py
![image](https://user-images.githubusercontent.com/54842012/141163217-9ba5470a-5a4f-4b66-a12d-e8452047658f.png)
