### ISSUE TITLE
Duplicate scanner name shown in notification banner

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#4275]
**Bug description**
![image](https://user-images.githubusercontent.com/5468769/114712863-dad03000-9d30-11eb-943d-aa5e00e706ad.png)

fyi @damiencarol 

**Steps to reproduce**
1. Import anything, and see the banner

**Comment by 37b** [comment]
You guys mind if I take this? It's just a couple of lines

` message = scan_type + '%s processed a total of %s findings' % (scan_type, finding_count)
`

**Comment by valentijnscholten** [comment]
fixed in dev / 1.15.0
