### ISSUE TITLE
Parsing error when importing Snyk results in 1.12.1

### ISSUE THREAD

**Issue by mperrotti-fdbl** [DefectDojo/django-DefectDojo#4277]
I am getting an error when attempting to import Snyk results in DefectDojo 1.12.1.

From the logs:

'references'
Traceback (most recent call last):
  File "./dojo/engagement/views.py", line 589, in import_scan_results
    parser = import_parser_factory(file, t, active, verified)
  File "./dojo/tools/factory.py", line 178, in import_parser_factory
    parser = SnykParser(file, test)
  File "./dojo/tools/snyk/parser.py", line 18, in __init__
    temp += self.process_tree(moduleTree, test)
  File "./dojo/tools/snyk/parser.py", line 25, in process_tree
    return [data for data in self.get_items(tree, test)]
  File "./dojo/tools/snyk/parser.py", line 48, in get_items
    item = get_item(node, test)
  File "./dojo/tools/snyk/parser.py", line 111, in get_item
    for item in vulnerability['references']:
KeyError: 'references'
Error in parser: 'references'

Steps to reproduce on my end:

1. Locate a Dot Net Core csproject and build it with dotnet build.
2. Run  snyk test --all-projects -json > snyk.json to generate the Snyk vulnerability JSON file.
3. Import the scan results into DefectDojo by going to the corresponding project, creating an engagement, and selecting import scan results > scan type = Snyk Scan > reference the snyk.json file generated in #2.

**Comment by damiencarol** [comment]
will take a look tomorrow

**Comment by damiencarol** [comment]
@mperrotti-fdbl seems that this attribute is not here some times.
Could you push your report in the description? I want to see what is blocking in the report.

**Comment by mperrotti-fdbl** [comment]
manually redacted some data via find/replace but otherwise this is my actual report.
[snyk.zip](https://github.com/DefectDojo/django-DefectDojo/files/6318650/snyk.zip)

**Comment by damiencarol** [comment]
@mperrotti-fdbl thanks a lot. I'm able to reproduce it. There is more than this anomaly. Working on a patch.

**Comment by damiencarol** [comment]
@mperrotti-fdbl it's merged in dev. will be included in `1.15.0`
