### ISSUE TITLE
Support for npm audit v7+

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#4285]
**Scanner Name**
npm7 audit is not supported because it is missing lots of data in the reports: https://github.com/npm/npm-audit-report/issues/45

**Comment by valentijnscholten** [comment]
Progress has been made, waiting for https://github.com/npm/metavuln-calculator/pull/34 to be merged.

**Comment by jake-cryptic** [comment]
Hi, any update on this? The PR was merged and a new release made: https://github.com/npm/metavuln-calculator/releases/tag/v3.1.0

**Comment by valentijnscholten** [comment]
They still don't include `cve`, but it seems it is hard for them to get that data and include it in the report. We could do a first implementation without `cve`.
They also don't include any other `id` we could easily use, except that we could parse the `url` field and hope for the best.

**Comment by valentijnscholten** [comment]
Some more info here: https://github.com/jeemok/better-npm-audit#npm-version-6-and-7-and-8

**Comment by manuel-sommer** [comment]
NPM Audit is already covered. I guess, this can be closed @mtesauro

**Comment by valentijnscholten** [comment]
I don't think npm 7 or higher is supported by the parser.

**Comment by manuel-sommer** [comment]
Do you have a sample file, then I will fix the parser ?

**Comment by manuel-sommer** [comment]
I guess this can be closed @mtesauro
