### ISSUE TITLE
Burp Enterprise Scan report importing failed,

### ISSUE THREAD

**Issue by rr1010** [DefectDojo/django-DefectDojo#4287]
**Be informative**
Importing Burp Enterprise Scan is not working in the latest version of DD,

**Bug description**
![image](https://user-images.githubusercontent.com/51348258/114957239-b8ffb600-9eb4-11eb-981b-08a7ff5850b8.png)

**Steps to reproduce**
* Go to a Test page.
* Import scan result
* Select Scan type as Burp Enterprise Scan
* Choose a report file .html file
* Click Import
* An error has occurred in the parser, please see error log for details.

**Expected behavior**
Import Burp Enterprise Scan 

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ * ] Docker
- [ ] setup.bash / legacy-setup.bash

**Comment by damiencarol** [comment]
taking a look.
@rr1010 do you have a report that fail? (even redacted)

**Comment by damiencarol** [comment]
I can reproduce the bug. I think it was introduced in #4082

**Comment by damiencarol** [comment]
@rr1010 fixed in `dev` / `1.15.0`
