### ISSUE TITLE
Maintain JIRA product specific configuration via API?

### ISSUE THREAD

**Issue by xthk** [DefectDojo/django-DefectDojo#429]
### Issue Type 

- [ ] Bug
- [X] Enhancement

### Description

I'd like to be able to maintain (create, read, update, delete) the product specific JIRA configuration via DefectDojo's API.

My use case is to maintain product specific JIRA configurations for 100+ projects. That's just infeasible via the UI. Issue #420 (create endpoints) is related to this.

**Comment by devGregA** [comment]
Completed.
