### ISSUE TITLE
Request Response pair fields in finding do not render images

### ISSUE THREAD

**Issue by Hijerboa** [DefectDojo/django-DefectDojo#4293]
Images are not rendered in the request/response pair fields of a finding, despite the editor allowing images to be added. All other fields in the finding screen allow for images to render.

I'm not sure if this is intentional or not, but if it is, is there a way to remove the option to add images in the editor for these fields?

**Steps to reproduce**
1. Create a finding
2. Add an image to a request/response field
3. Add an image to any other field
4. View finding, note that the image in the request/response field is not rendered, but is rendered in other fields

**Expected behavior**
Images to render in all fields of a finding

**Deployment method** *(select with an `X`)*
- [x] Kubernetes - Issue also present in Kubernetes deployment
- [X] Docker -pictures are from docker setup
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: WSL Ubuntu 20.04

**Screenshots** (optional)
![image](https://user-images.githubusercontent.com/25833688/115040191-2bfe3200-9e9f-11eb-8d76-aa68b918a9c8.png)
![image](https://user-images.githubusercontent.com/25833688/115040244-39b3b780-9e9f-11eb-86b1-204504989cf8.png)
Same picture used in both description field and request/response fields
![image](https://user-images.githubusercontent.com/25833688/115040303-489a6a00-9e9f-11eb-995b-ec07da6538d0.png)
![image](https://user-images.githubusercontent.com/25833688/115040369-5c45d080-9e9f-11eb-9fa4-ac8674dc177b.png)

**Comment by adayrodri** [comment]
I'd be very helpful if this issue is solved. Please, let me know if development help is needed.
