### ISSUE TITLE
Dependency Check: Invalid severity 'moderate'

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#4309]
OWASP Dependency check sometimes gives a 'Moderate' severity to findings, which doesn't map to our list of severities. It gets converted to 'Medium', but with a warning in the title. Suggestion: Just convert to Medium and only use the warning for sometimes we can't map.

**Comment by ansidorov** [comment]
@valentijnscholten I think we can close this issue.
