### ISSUE TITLE
Import of Qualys Scan throws unexpected keywork error

### ISSUE THREAD

**Issue by kareem-DA** [DefectDojo/django-DefectDojo#4317]
**Slack us first!**
The easiest and fastest way to help you is via Slack. There's a free and easy signup to join our #defectdojo channel in the OWASP Slack workspace: [Get Access.](https://owasp-slack.herokuapp.com/)
If you're confident you've found a bug, or are allergic to Slack, you can submit an issue anyway.

**Be informative**
Please enter as much information as possible, otherwise we can't provide support. If possible upgrade to the latest release or dev version and try again.

**Bug description**
I did an import of a "Qualys Scan" report and got an error return.  The logs on the server showed the error
uwsgi_1         | ERROR:django.request:Internal Server Error: /api/v2/import-scan/
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "./dojo/api_v2/serializers.py", line 1097, in save
uwsgi_1         |     parser_findings = parser.get_findings(data.get('file', None), test)
uwsgi_1         |   File "./dojo/tools/qualys/parser.py", line 233, in get_findings
uwsgi_1         |     return qualys_parser(file)
uwsgi_1         |   File "./dojo/tools/qualys/parser.py", line 210, in qualys_parser
uwsgi_1         |     parser = etree.XMLParser(resolve_entities=False, remove_blank_text=True, no_network=True, recover=True)
uwsgi_1         | TypeError: __init__() got an unexpected keyword argument 'resolve_entities'
uwsgi_1         | 

Looking at the code.  
https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/qualys/parser.py

The library is loaded on Line 6:
from defusedxml import ElementTree as etree

The library is called on Line 210:
parser = etree.XMLParser(resolve_entities=False, remove_blank_text=True, no_network=True, recover=True)

The parser used does not have the resolve_entrities option (or the others) . See below the help from the help.

GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from defusedxml import ElementTree as etree
>>> help(etree.XMLParser)
Help on class DefusedXMLParser in module defusedxml.ElementTree:

class DefusedXMLParser(xml.etree.ElementTree.XMLParser)
 |  Element structure builder for XML source data based on the expat parser.
 |  
 |  *html* are predefined HTML entities (deprecated and not supported),
 |  *target* is an optional target object which defaults to an instance of the
 |  standard TreeBuilder class, *encoding* is an optional encoding string
 |  which if given, overrides the encoding specified in the XML file:
 |  http://www.iana.org/assignments/character-sets
 |  
 |  Method resolution order:
 |      DefusedXMLParser
 |      xml.etree.ElementTree.XMLParser
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, html=<object object at 0x7f914b9e2100>, target=None, encoding=None, forbid_dtd=False, forbid_entities=True, forbid_external=True)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  defused_entity_decl(self, name, is_parameter_entity, value, base, sysid, pubid, notation_name)
 |  
 |  defused_external_entity_ref_handler(self, context, base, sysid, pubid)
 |  
 |  defused_start_doctype_decl(self, name, sysid, pubid, has_internal_subset)
 |  
 |  defused_unparsed_entity_decl(self, name, base, sysid, pubid, notation_name)
 |  
 |  ----------------------------------------------------------------------
 |  Methods inherited from xml.etree.ElementTree.XMLParser:
 |  
 |  close(self)
 |      Finish feeding data to parser and return element structure.
 |  
 |  doctype(self, name, pubid, system)
 |      (Deprecated)  Handle doctype declaration
 |      
 |      *name* is the Doctype name, *pubid* is the public identifier,
 |      and *system* is the system identifier.
 |  
 |  feed(self, data)
 |      Feed encoded data to parser.
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from xml.etree.ElementTree.XMLParser:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)

The LXML (https://lxml.de/api/lxml.etree.XMLParser-class.html) Does have the correct paramters.

**Steps to reproduce**
1. I use the API run this, but the WMI should work.  Import a qualys report from the WMI.  
2. It will return a 500 server error.
3. In the logs, will be the error above.

**Expected behavior**

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
DefectDojo version 1.14.1 installed with docker-compose.

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

**Comment by damiencarol** [comment]
@kareem-DA this issue is fixed in `dev` / `1.15.0` by https://github.com/DefectDojo/django-DefectDojo/pull/4121 .
Sorry that you still have this issue in your version :)
