### ISSUE TITLE
Error import GitLab SAST report

### ISSUE THREAD

**Issue by theoldscarana** [DefectDojo/django-DefectDojo#4344]
**Bug description**
Hi,
when i try to import a GitLab SAST report in DefectDojo through the UI, i get import error. 

I believe that problem are in the /dojo/tools/gitlab_sast/parser.py in the method get_item. The method does not verify if the field "severity" exists. In the [sast json schema](https://gitlab.com/gitlab-org/security-products/security-report-schemas/-/blob/v14.0.0/dist/sast-report-format.json) the field "severity" is optional.

**Steps to reproduce**
1. Go to "Import Scan Results"
2. Select Scan Type -> Gitlab SAST Report
3. Sets all required field
4. Choose report file
5. Click Import 

**Expected behavior**
A success import.

**Deployment method** *(select with an `X`)*
- [ X] Docker

**Sample scan files** (optional)
Attached the report sast that try to import.
[gl-sast-report.zip](https://github.com/DefectDojo/django-DefectDojo/files/6363578/gl-sast-report.zip)

**Console logs** (optional)
In the docker logs of the container django-defectdojo_uwsgi i found this error:
`[22/Apr/2021 14:00:03] ERROR [dojo:611] 'severity'
Traceback (most recent call last):
  File "./dojo/engagement/views.py", line 604, in import_scan_results
    parser_findings = parser.get_findings(file, t)
  File "./dojo/tools/gitlab_sast/parser.py", line 24, in get_findings
    return self.get_items(tree, test)
  File "./dojo/tools/gitlab_sast/parser.py", line 39, in get_items
    item = get_item(node, test)
  File "./dojo/tools/gitlab_sast/parser.py", line 93, in get_item
    severity = vuln['severity']
KeyError: 'severity'
[22/Apr/2021 14:00:03] ERROR [dojo:612] Error in parser: 'severity'`

**Comment by damiencarol** [comment]
@theoldscarana taking a look. do you have one report that generate this issue? (even redacted)

**Comment by damiencarol** [comment]
@theoldscarana a pull request that fixes this issue is in progress #4345 .

**Comment by valentijnscholten** [comment]
fixed in 1.15.0
