### ISSUE TITLE
AuthV2: Successful import but 403

### ISSUE THREAD

**Issue by kiblik** [DefectDojo/django-DefectDojo#4347]
**Bug description**

Scan_User has permission only to import test results. Even process is successful, DD returns HTTP 403. It is a bit confusing.

**Steps to reproduce**

- Log in as Scan_User
- Go to https://xxx/engagement/xx/import_scan_results
- Upload a valid scan

**Deployment method** *(select with an `X`)*
- [x] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - `DD_FEATURE_AUTHORIZATION_V2=True` 
 - DefectDojo Commit Message: `[2021-04-23 12:37:15 +0200] 952ebd0c: Bump easymde from 2.14.0 to 2.15.0 in /components (#4343) [ (HEAD, upstream/dev)]`

**Screenshots**
![image](https://user-images.githubusercontent.com/5609770/115873097-743ac880-a43a-11eb-8d8d-2365b9b1243d.png)

**Comment by valentijnscholten** [comment]
What is the url you're seeing this? I think after the import the user is redirect to the view test page of the test that was just imported.

**Comment by kiblik** [comment]
`http://localhost:8080/test/2`
I know that showing 403 for Test makes sense but it is still confusing

**Comment by valentijnscholten** [comment]
Yes. I think the scan user was more designed for the API, but even there it needs some more permissions.

**Comment by StefanFl** [comment]
The scan_user role was actually designed for the API only. Using it in the UI seems to be an edge case for me, because you can't navigate to the Import page, you have to know the URL.

It is not easy to design the role for a scan_user. I personally have a script that gets the names for product, engagement and test. If it can't find the objects, it creates them and then does a reimport.

**Comment by StefanFl** [comment]
Maybe it makes sense to give the scan_user role the permission to view the product and all objects underneath it (engagement, test, ...). Then the user can navigate to the product, import a scan result and view the result. But can't add or change anything manually.

**Comment by kiblik** [comment]
If Scan_User was designed to interact only from API, standard access can be totally denied.

**Comment by StefanFl** [comment]
Would it be clearer to change the name of the role to API_SCAN_USER?

**Comment by kiblik** [comment]
`API_IMPORTER`?
 "to import" is the only task for this user

**Comment by pisces-period** [comment]
> Maybe it makes sense to give the scan_user role the permission to view the product and all objects underneath it (engagement, test, ...). Then the user can navigate to the product, import a scan result and view the result. But can't add or change anything manually.

A little bit late I suppose, but IMHO this is the better approach. It doesn't make much sense to create a role that is capable of interacting with the tool so much so as to update resources and not be able to see what it just did (?).

`API_IMPORTER` suggests that you can do imports via API - but it still sounds vague, as one might think that you can bulk import users, products, engagements etc via the API, which doesn't seem to be the case.

**Comment by valentijnscholten** [comment]
renamed role in 1.15.0
