### ISSUE TITLE
Duplicate Cluster => Similar instead of "this"

### ISSUE THREAD

**Issue by Wadeck** [DefectDojo/django-DefectDojo#4372]
**Bug description**
In the duplicate cluster, from the original of the cluster, its own line is marked as "Similar" while it should be "Original(this)", if we want to be consistent with the "Duplicate(this)".

This is a bit confusing.

**Screenshots** (optional)
From original PoV
![from_original](https://user-images.githubusercontent.com/2662497/116213054-bd925d00-a745-11eb-9ba7-3e19cbe1e455.png)

From duplicate PoV
![from_duplicate](https://user-images.githubusercontent.com/2662497/116213057-bec38a00-a745-11eb-9836-7cc810c1a111.png)

FYI @madchap @valentijnscholten

**Comment by valentijnscholten** [comment]
fixed in dev/2.0.0
