### ISSUE TITLE
Separate endpoints per URL in the UI

### ISSUE THREAD

**Issue by dinvlad** [DefectDojo/django-DefectDojo#4377]
**Is your feature request related to a problem? Please describe**
APIv2 supports endpoints as separate entities for separate protocol+host+port+query+fragment combinations. However, when I add them in the UI, they are grouped on a per-host basis, and certain things (like tagging and deletion) only work on per-host instead of per-endpoint basis.

**Describe the solution you'd like**
I'd like all endpoints to be displayed as fully-qualified URLs in the UI, with ability to edit (e.g. set tags/attributes) and delete endpoints separately from each other.

**Describe alternatives you've considered**
The only alternative/workaround that works now is Endpoints APIv2 (either programmatic or via Swagger UI), but that's less convenient from the UI usability standpoint.

**Additional context**
We're using the latest `defectdojo/defectdojo-django` Docker image.

**Comment by damiencarol** [comment]
@dinvlad take a look at the big PR on endpoints. some features in it will cover your need I think https://github.com/DefectDojo/django-DefectDojo/pull/4188
