### ISSUE TITLE
Synopsys Coverity SAST

### ISSUE THREAD

**Issue by damiencarol** [DefectDojo/django-DefectDojo#4394]
New parser for Synopsys Coverity.

https://www.synopsys.com/software-integrity/security-testing/static-analysis-sast.html

**Comment by damiencarol** [comment]
Fixed in `dev` / `2.0.0`

**Comment by ngocnn97** [comment]
Hi Damien Carol
I am using Coverity and want to import report to defect dojo, i exported Coverity API view data in JSON format like this: But when I import defect dojo it shows 0 finding, tell me where is the error?
