### ISSUE TITLE
Burp XML Import Failed 

### ISSUE THREAD

**Issue by gh0st27** [DefectDojo/django-DefectDojo#4399]
**Bug description**
While uploading Burp Suite XML Scan report to defect dojo latest version (1.15.0) gives following error.
"ERROR [dojo.importers.utils:23] 'utf-8' codec can't decode byte 0x85 in position 249: invalid start byte"

**Steps to reproduce**
Steps to reproduce the behaviour:
1. Go to 'Engagement -> Active Engagement '
2. Click on 'Any Engagement'
3. Create a new test to upload burp scan XML report.
4. Upload XML report (See attachment for report) gives "Invalid Start byte" error.

**Expected behaviour**
The report should upload without any error.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Linux kali 5.10.0-kali3-amd64 #1 SMP Debian 5.10.13-1kali1 (2021-02-08) x86_64 GNU/Linux]
 - DefectDojo Commit Message: [use `git show -s --format="[%ci] %h: %s [%d]"`] : [2021-04-27 11:43:20 -0500] e1691cb9: Merge pull request #4374 from DefectDojo/release/1.15.0 [ (HEAD -> master, tag: 1.15.0, origin/master, [origin/HEAD)]]

**Sample scan files** (optional)
Change the extension to XML from burp.txt to burp.xml
[burp.txt](https://github.com/DefectDojo/django-DefectDojo/files/6403578/burp.txt)

**Screenshots** (optional)
<img width="960" alt="Error2" src="https://user-images.githubusercontent.com/35606874/116662412-609bde80-a9b3-11eb-927c-69b2224b1734.PNG">

**Console logs** (optional)
<img width="960" alt="Error1" src="https://user-images.githubusercontent.com/35606874/116662437-68f41980-a9b3-11eb-9c1c-347c4899284a.PNG">

**Comment by damiencarol** [comment]
Taking a look, thanks @gh0st27 for reporting.

**Comment by damiencarol** [comment]
I'm able to reproduce the bug, working on a PR
```
======================================================================
ERROR: test_burp_issue4399 (dojo.unittests.tools.test_burp_parser.TestBurpParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/damien/dd/dojo/unittests/tools/test_burp_parser.py", line 57, in test_burp_issue4399
    findings = parser.get_findings(test_file, Test())
  File "/home/damien/dd/dojo/tools/burp/parser.py", line 32, in get_findings
    return self.get_items(tree, test)
  File "/home/damien/dd/dojo/tools/burp/parser.py", line 38, in get_items
    item = get_item(node, test)
  File "/home/damien/dd/dojo/tools/burp/parser.py", line 131, in get_item
    response = get_clean_base64(request_response.findall('response')[0].text)
  File "/home/damien/dd/dojo/tools/burp/parser.py", line 102, in get_clean_base64
    return base64.b64decode(value).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 249: invalid start byte
```

**Comment by damiencarol** [comment]
@gh0st27 pushed a pull request that fixes this issue.
This issue happen when there is binary data in the base 64 encoded string.
