### ISSUE TITLE
Risk Recon importer does not include Unique Finding ID from tool

### ISSUE THREAD

**Issue by 37b** [DefectDojo/django-DefectDojo#4409]
@cody-m-tibco 

Hi Cody,

Could you add The Unique Finding ID from tool to the Finding object while doing Risk Recon import? I am trying to close the Finding on the Risk Recon side using automation, but I can't correlate the DD finding with the RR finding.

If you don't have time I can take a stab at adding it.

**Comment by damiencarol** [comment]
@37b @cody-m-tibco  hello Chris and cody , if you don't mind, I can take this one.

**Comment by damiencarol** [comment]
pushed a pull request to cover this one https://github.com/DefectDojo/django-DefectDojo/pull/4444

**Comment by damiencarol** [comment]
Closing it as it was merged long time ago.
