### ISSUE TITLE
Remove django-tagging dependency once #4419 is merged

### ISSUE THREAD

**Issue by damiencarol** [DefectDojo/django-DefectDojo#4420]
once #4419 is merged , we can remove `django-tagging`

**Comment by valentijnscholten** [comment]
that would break migration 0066

**Comment by damiencarol** [comment]
:thinking: Is ee, we must keep it in case users want to upgrade from version before migration 0066.
So we're stuck with a dependency that we don't use anymore in the rest of the application.

**Comment by damiencarol** [comment]
closing for now. maybe reopen if we want to get ride of `django-tagging` for future releases.
