### ISSUE TITLE
mozilla observatory scan report can not be imported

### ISSUE THREAD

**Issue by tonnyhideyori** [DefectDojo/django-DefectDojo#4436]
I tried to import mozilla observatory scan reports on findings. But keep raising error
>Traceback (most recent call last):
> uwsgi_1         |   File "./dojo/importers/utils.py", line 16, in parse_findings
> uwsgi_1         |     parsed_findings = parser.get_findings(scan, test)
> uwsgi_1         |   File "./dojo/tools/mozilla_observatory/parser.py", line 30, in get_findings
> uwsgi_1         |     if not node['pass']:
> uwsgi_1         | KeyError: 'pass'``
> uwsgi_1         |  WARNING [dojo.importers.utils:29] Error in parser: 'pass'``
> uwsgi_1         | ERROR [dojo.engagement.views:614] 'pass'``
> uwsgi_1         | Traceback (most recent call last):
> uwsgi_1         |   File "./dojo/engagement/views.py", line 602, in import_scan_results
> uwsgi_1         |     close_old_findings=close_old_findings)
> uwsgi_1         |   File "./dojo/importers/importer/importer.py", line 248, in import_scan
> uwsgi_1         |     parsed_findings = importer_utils.parse_findings(scan, test, active, verified, scan_type)
> uwsgi_1         |   File "./dojo/importers/utils.py", line 16, in parse_findings
> uwsgi_1         |     parsed_findings = parser.get_findings(scan, test)
> uwsgi_1         |   File "./dojo/tools/mozilla_observatory/parser.py", line 30, in get_findings
> uwsgi_1         |     if not node['pass']:
> uwsgi_1         | KeyError: 'pass'

hence, is there any solution for that error

**Comment by damiencarol** [comment]
@tonnyhideyori hello, could you provide more details? is it possible to push the report in the description? (even redacted)

**Comment by tonnyhideyori** [comment]
when I upload the file i get this warning
![import](https://user-images.githubusercontent.com/18649939/117010520-2bfa9080-aced-11eb-98a8-a9887ea4bfb6.png)
the report is generated locally mozilla observatory

{
  "scan": {
    "grade": "F",
    "likelihood_indicator": "MEDIUM",
    "response_headers": {
      "Accept-Ranges": "bytes",
      "Cache-Control": "public, max-age=0",
      "Connection": "keep-alive",
      "Content-Length": "1014",
      "Content-Type": "text/html; charset=UTF-8",
      "Date": "Tue, 04 May 2021 06:55:29 GMT",
      "Etag": "W/\"3f6-16be02422a8\"",
      "Last-Modified": "Thu, 11 Jul 2019 08:26:33 GMT",
      "Server": "Cowboy",
      "Via": "1.1 vegur",
      "X-Powered-By": "Express"
    },
    "score": 0,
    "tests_failed": 7,
    "tests_passed": 5,
    "tests_quantity": 12
  },
  "tests": {
    "content-security-policy": {
      "data": null,
      "expectation": "csp-implemented-with-no-unsafe",
      "http": false,
      "meta": false,
      "pass": false,
      "policy": null,
      "result": "csp-not-implemented",
      "score_description": "Content Security Policy (CSP) header not implemented",
      "score_modifier": -25
    },
    "contribute": {
      "data": null,
      "expectation": "contribute-json-only-required-on-mozilla-properties",
      "pass": true,
      "result": "contribute-json-only-required-on-mozilla-properties",
      "score_description": "Contribute.json isn't required on websites that don't belong to Mozilla",
      "score_modifier": 0
    }
}

part of the results generated by mozilla observatory http-probs

**Comment by damiencarol** [comment]
ok, I see. had the same format of report with the CLI.
I will work on it. I think I can modify the parser to accept the 2 format.

**Comment by tonnyhideyori** [comment]
Thank you

**Comment by damiencarol** [comment]
@tonnyhideyori could you tell me how you create the reports? which command line ?
do you use the JS version or the Python version?

**Comment by tonnyhideyori** [comment]
I have a python version. so i generated through httpobs-local-scan and the other one through python script in http-observatory directory clone from github

**Comment by damiencarol** [comment]
fixed in `dev` / `2.0.0`
