### ISSUE TITLE
Deploy to Docker cloud link gives 404 error

### ISSUE THREAD

**Issue by palash25** [DefectDojo/django-DefectDojo#444]
Please use the following template when submitting issues:

### Issue Type 
- [ ] Bug
- [ ] Enhancement

### Operating System 
Please include the version number (ex: Ubuntu 16.04)

### Install

- [ ] setup.bash
- [ ] docker

**Comment by devGregA** [comment]
Hi @palash25 are you signed into dockercloud before you click the button?

**Comment by devGregA** [comment]
Closing from lack of activity.
