### ISSUE TITLE
Parser issue while importing AWS_Prowler report

### ISSUE THREAD

**Issue by Parthasarathi7722** [DefectDojo/django-DefectDojo#4450]
**Bug description**
Getting parser issue while importing aws_prowler report
Import file type: csv
DefectDojo version: v. 1.15.0 ( release mode )

**Steps to reproduce**
1. Go to 'Product>>Findings>>Import scan result'
2. Upload the csv file obtained from prowler
3. see the error on screen "An exception error occurred during the report import:must be str, not NoneType"
4. 

**Expected behavior**
No error and successful import of report

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. macOS BigSur]
 

**Sample scan files** (optional)
Attached sample prowler report

**Console logs** (optional)

ginx_1         | 2021/05/05 07:02:21 [warn] 7#7: *759 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000003, client: 172.22.0.1, server: , request: "POST /product/1/import_scan_results HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/product/1/import_scan_results"
uwsgi_1         | [05/May/2021 07:02:21] ERROR [dojo.importers.utils:27] must be str, not NoneType
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "./dojo/importers/utils.py", line 16, in parse_findings
uwsgi_1         |     parsed_findings = parser.get_findings(scan, test)
uwsgi_1         |   File "./dojo/tools/aws_prowler/parser.py", line 49, in get_findings
uwsgi_1         |     description = "**Region:** " + region + "\n\n" + notes + "\n"
uwsgi_1         | TypeError: must be str, not NoneType
uwsgi_1         | [05/May/2021 07:02:21] WARNING [dojo.importers.utils:28] Error in parser: must be str, not NoneType
uwsgi_1         | [05/May/2021 07:02:21] ERROR [dojo.engagement.views:614] must be str, not NoneType
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "./dojo/engagement/views.py", line 602, in import_scan_results
uwsgi_1         |     close_old_findings=close_old_findings)
uwsgi_1         |   File "./dojo/importers/importer/importer.py", line 248, in import_scan
uwsgi_1         |     parsed_findings = importer_utils.parse_findings(scan, test, active, verified, scan_type)
uwsgi_1         |   File "./dojo/importers/utils.py", line 16, in parse_findings
uwsgi_1         |     parsed_findings = parser.get_findings(scan, test)
uwsgi_1         |   File "./dojo/tools/aws_prowler/parser.py", line 49, in get_findings
uwsgi_1         |     description = "**Region:** " + region + "\n\n" + notes + "\n"
uwsgi_1         | TypeError: must be str, not NoneType
uwsgi_1         | [pid: 19|app: 0|req: 645/1035] 172.22.0.1 () {62 vars in 1422 bytes} [Wed May  5 07:02:21 2021] POST /product/1/import_scan_results => generated 65169 bytes in 212 msecs (HTTP/1.1 200) 7 headers in 369 bytes (1 switches on core 0)
[Updated_prowler_ticket.csv](https://github.com/DefectDojo/django-DefectDojo/files/6425887/Updated_prowler_ticket.csv)

**Comment by damiencarol** [comment]
One column is missing and make the parser crash. I'm working on a patch.

**Comment by madchap** [comment]
Fixed in dev.
