### ISSUE TITLE
Problems with the UI

### ISSUE THREAD

**Issue by martinmarsicano** [DefectDojo/django-DefectDojo#447]
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description
When downloading repository and making the setup, there is a problem with the UI
Also due to Bootstrap upgrading there are some missing dependencies. When trying to open a dropdown in the browser console it appears: Uncaught TypeError: Bootstrap dropdown require Popper.js (https://popper.js.org)

### Operating System 
- Ubuntu 16.04 LTS
- MacOS 10.13.3

### Install
- [x] setup.bash
- [ ] docker

### Steps to Reproduce
- Clone the repo.
- Execute ./setup.bash
- Execute the server ('python manage.py runserver' || './run_dojo.bash')
- Open the webapp (here we can see the UI problems)
- Login with Dojo superuser
- In the Menu select Products -> All Products
- Try to open the dropdown menu on the right (here is where the error appears in the console)

### Screenshots
<img width="1916" alt="screen shot 2018-01-24 at 12 28 49 pm" src="https://user-images.githubusercontent.com/33671308/35345272-fa3ef0ba-010d-11e8-9963-36391645c2a8.png">

<img width="1918" alt="screen shot 2018-01-24 at 3 32 19 pm" src="https://user-images.githubusercontent.com/33671308/35350166-cd306730-011b-11e8-948e-8f3024e235fa.png">

**Comment by mymainmandeebo** [comment]
I am also getting this same issue.

**Comment by devGregA** [comment]
@cneill would you be able to look into this with your infinite JS wisdom? ;)

**Comment by aaronweaver** [comment]
@martinmarsicano @mymainmandeebo Issue is fixed in the latest commit.

**Comment by devGregA** [comment]
Please feel free to reopen if you continue to have issues.
