### ISSUE TITLE
"Add Product Tool Type Configuration"  produces error 500 on current dev branch

### ISSUE THREAD

**Issue by damiencarol** [DefectDojo/django-DefectDojo#4474]
**Bug description**
Add Product Tool Type Configuration produces error 500 when validating.

https://demo.defectdojo.org/product/1/tool_product/add

**Steps to reproduce**
1. Go to 'Product settings'
2. Click on 'Add Product Tool Type Configuration '
3. Validate

**Comment by valentijnscholten** [comment]
works fine for me locally, could be some flaky test / sample data in the demo instance?

**Comment by damiencarol** [comment]
don't know. will test more

**Comment by valentijnscholten** [comment]
I think Matt posted a url to view the logs from the demo site

**Comment by damiencarol** [comment]
I found the pb. one attribute is mandatory but the UI let you validate without it, don't which one without the logs... maybe the description.
