### ISSUE TITLE
docker image scanner (anchore, trivy ...)

### ISSUE THREAD

**Issue by saldam72** [DefectDojo/django-DefectDojo#4477]
When I import the results generated by an image scanner (anchor, trivy ...) I can't enter the name of the image repository in the endpoint field.

Allow to insert the name of the image repository in the endpoint field.

**Comment by saldam72** [comment]
If I insert into the system/endpoint field something like "goofy-disney" I got an error but if "goofy-disney-1.0.0-goofy" I got success.

Is this a bug ?

**Comment by damiencarol** [comment]
@saldam72 system/endpoint is not designed to handle image name but URLs.
Also the link between the interface and the import is not implemented for now, I think (I maybe wrong)

**Comment by saldam72** [comment]
@damiencarol I have successfully imported two files generated by scanning two diferent images with anchon (the only problem is that the unique_id_from_tool field has been populated with the CVE and I don't think that's correct) 

I think it is important to save also image name because the same vulnerability found on two different images is not one vulnerability but two

**Comment by damiencarol** [comment]
Maybe it's linked to your way to group the scans. can you have one project by image instead of grouping every scan on the same project ?

**Comment by saldam72** [comment]
No, we have one product, one engagement (of course we can have other engagements) and many test (manual, appscan, contrast, anchore/trivy for each image and so on).

**Comment by valentijnscholten** [comment]
We have seen this requirement before. Some applications exist of multiple smaller services, each in their own docker container. And sometimes people want to import these scans into the same product and same engagement to limit the amount of products/engagements needed. So at some point we may need to introduce an extra field to help with this. "servicename" or "application component name" or something like that. It's a shame we have already used `component_name` for something else...

**Comment by saldam72** [comment]
from my point of view system/endpoint is perfect ... you should just allow to insert something like "goofy-disney" and if string starts with http/https you can parse it otherwise you can save is without parsing in the host filed of the defectdojo.dojo_endpoint table
