### ISSUE TITLE
docker-compose build failed

### ISSUE THREAD

**Issue by Akilroyfen** [DefectDojo/django-DefectDojo#4485]
Bug description
Unable to run  docker-compose:
 docker-compose build
mysql uses an image, skipping
initializer uses an image, skipping
rabbitmq uses an image, skipping
celeryworker uses an image, skipping
celerybeat uses an image, skipping
Building uwsgi
Sending build context to Docker daemon   79.9MB
Step 1/27 : FROM python:3.6.12-slim-buster@sha256:e5259113df5a7c4dae16ad37c2ca53b1cf722e051cfd5f624e7b76aa72389e0c as build
 ---> c36a97a24d09
Step 2/27 : WORKDIR /app
 ---> Using cache
 ---> 6e670db66322
Step 3/27 : RUN   apt-get -y update &&   apt-get -y install     build-essential     dnsutils     default-mysql-client     libmariadb-dev-compat     postgresql-client     xmlsec1     git     uuid-runtime     &&   apt-get clean &&   rm -rf /var/lib/apt/lists &&   true
 ---> Running in a1a93eb8dd9f
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://deb.debian.org/debian buster InRelease [121 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [286 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
Reading package lists...
E: Release file for http://deb.debian.org/debian/dists/buster-updates/InRelease is not valid yet (invalid for another 1min 52s). Updates for this repository will not be applied.
The command '/bin/sh -c apt-get -y update &&   apt-get -y install     build-essential     dnsutils     default-mysql-client     libmariadb-dev-compat     postgresql-client     xmlsec1     git     uuid-runtime     &&   apt-get clean &&   rm -rf /var/lib/apt/lists &&   true' returned a non-zero code: 100
ERROR: Service 'uwsgi' failed to build : Build failed

Steps to reproduce:
1. Install latest versions of docker (https://docs.docker.com/install/linux/docker-ce/ubuntu/) and docker-compose (apt-get install docker-compose)
2. Clone django-DefectDojo repository
3. Go to django-DefectDojo directory
4. Run command docker-compose build

Environment:
centos-release-7-9.2009.1.el7.centos.x86_64

![2021-05-11_13h17_44](https://user-images.githubusercontent.com/17568724/117778506-530c1180-b25b-11eb-8b39-7927509a8a20.png)

Deployment method (select with an X)

 Kubernetes
X  Docker
 setup.bash / legacy-setup.bash

**Comment by valentijnscholten** [comment]
This is a local problem. Are you installing docker for ubuntu on centos? It's unclear what you're doing, but anyway this error message is something with timestamps not matching in apt repositories and not related to defect dojo.
We've seen this occasionally and it either resolved itself or people were using the wrong apt repositories.

**Comment by Akilroyfen** [comment]
Thank you so much, there was a mismatch in my timestamp. Fixed it and now it's working fine. Closing the defect
