### ISSUE TITLE
Set a configurable min_access_level for Gitlab projects import

### ISSUE THREAD

**Issue by christophe226** [DefectDojo/django-DefectDojo#4486]
**Is your feature request related to a problem? Please describe**
As a user, when I use "Login with Gitlab" button and GITLAB_PROJECT_AUTO_IMPORT is set to True, all the Gitlab projects I am member of are imported as products, regardless of my access level on the project (Guest, Reporter, Developer...)

**Describe the solution you'd like**
As DefectDojo admin, I want to set a global min_access_level for Gitlab projects import, so that my platform users do not see too many products. Only projects where the user has an access_level equal or higher than _the value of my choice_, defined in settings.

**Comment by valentijnscholten** [comment]
fixed in dev / 2.0.0
