### ISSUE TITLE
Gitlab projects tag_list and web_url reflected in products

### ISSUE THREAD

**Issue by christophe226** [DefectDojo/django-DefectDojo#4489]
**Is your feature request related to a problem? Please describe**
As a user, sometimes I want to filter DefectDojo products on specific tags which were in Gitlab projects, but it is not possible:  
when my Gitlab projects are imported as DefectDojo products, only the Gitlab project name is used to create the product, tag_list information is not used.
I also would like to retrieve Gitlab project URL in DefectDojo product, in order to access it easily. For now, I don't have this URL in DefectDojo product.

**Describe the solution you'd like**
As a user, I want that my DefectDojo products have automatically the same tag list as the corresponding Gitlab projects. The tag list would be synchronized when I use "Login with Gitlab" button. In the same step, I want to store Gitlab project URL in product description field.

**Screenshots**
Gitlab project:
![Gitlab project](https://user-images.githubusercontent.com/61734671/117834320-590feb80-b277-11eb-9284-e3deb98f7e3d.png)

DefectDojo product:
![DefectDojo product](https://user-images.githubusercontent.com/61734671/117834444-75138d00-b277-11eb-8a42-9597ebfb3c0c.png)

**Comment by bgoareguer** [comment]
Good idea! 

Would it be possible to also add the Gitlab project URL in the DefectDojo product description? This would allow users to easily go back to the Gitlab project from DefectDojo.

**Comment by christophe226** [comment]
> Good idea!
> 
> Would it be possible to also add the Gitlab project URL in the DefectDojo product description? This would allow users to easily go back to the Gitlab project from DefectDojo.

Thanks for the suggestion, I update the issue.
