### ISSUE TITLE
phpcs parser does not work

### ISSUE THREAD

**Issue by true-hero** [DefectDojo/django-DefectDojo#4492]
## Bug description
phpcs parser does not work properly. I am using fresh version 1.15.0 of dd. I can see error in logs:
```
uwsgi_1         | [12/May/2021 09:42:29] ERROR [dojo:611] name 'PhpSecurityAuditV2' is not defined
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "./dojo/engagement/views.py", line 604, in import_scan_results
uwsgi_1         |     parser_findings = parser.get_findings(file, t)
uwsgi_1         |   File "./dojo/tools/php_security_audit_v2/parser.py", line 39, in get_findings
uwsgi_1         |     sev = PhpSecurityAuditV2.get_severity_word(issue["severity"])
uwsgi_1         | NameError: name 'PhpSecurityAuditV2' is not defined
uwsgi_1         | [12/May/2021 09:42:29] ERROR [dojo:612] Error in parser: name 'PhpSecurityAuditV2' is not defined
```

## Steps to reproduce
1. Get phpcs report file
2. Try to import the report

##  Deployment method
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information
 - Ubuntu 20.04
 - DefectDojo 1.15.0
  
## Sample scan files*
[report.json.txt](https://github.com/DefectDojo/django-DefectDojo/files/6465379/report.json.txt)

## Linked issue
https://github.com/DefectDojo/django-DefectDojo/pull/4217

**Comment by damiencarol** [comment]
@true-hero taking a look.

**Comment by damiencarol** [comment]
@true-hero I checked the history and the fix for #4217 was merged since April 12th ( https://github.com/DefectDojo/django-DefectDojo/commit/b0bdc100a16c9298c3e5a3f34127ce4b927b6d99#diff-c535343e0809fd29dfa8c6b9a612dfeff7bab52225b47ed8581b18c69ee36825 ) so the fix was part of the `1.15.0` release that we released at the end of April.
So the big question is why do you have this issue? :thinking:

**Comment by damiencarol** [comment]
Last thing, the source code of `1.15.0` is different in your stack trace.
https://github.com/DefectDojo/django-DefectDojo/blob/e1691cb914d8c33169c491606aee45fee44806d8/dojo/tools/php_security_audit_v2/parser.py#L39

```
uwsgi_1         | [12/May/2021 09:42:29] ERROR [dojo:611] name 'PhpSecurityAuditV2' is not defined
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "./dojo/engagement/views.py", line 604, in import_scan_results
uwsgi_1         |     parser_findings = parser.get_findings(file, t)
uwsgi_1         |   File "./dojo/tools/php_security_audit_v2/parser.py", line 39, in get_findings
uwsgi_1         |     sev = PhpSecurityAuditV2.get_severity_word(issue["severity"])
uwsgi_1         | NameError: name 'PhpSecurityAuditV2' is not defined
uwsgi_1         | [12/May/2021 09:42:29] ERROR [dojo:612] Error in parser: name 'PhpSecurityAuditV2' is not defined
```

Something is fishy here. I'm not sure that you're using version `1.15.0`

**Comment by true-hero** [comment]
@damiencarol , you right. On test environment, I try the following code, and it is not update my image:
```bash
git pull
git checkout 1.15.0
sudo docker-compose run -d
```
After i update image, phpcs parser works correctly. Thank you.
