### ISSUE TITLE
Migrate to Bootstrap V4 from V3.

### ISSUE THREAD

**Issue by aaronweaver** [DefectDojo/django-DefectDojo#450]
### Issue Type 
- [ ] Bug
- [x] Enhancement

### Description
DefectDojo currently utilizes v3 of Bootstrap and needs to be migrated to v4. There are some changes that need to happen before that can take place. 

https://getbootstrap.com/docs/4.0/migration/

**Comment by dragos-sh** [comment]
@aaronweaver Hi, as a quick question instead of opening a whole new thread, how do you guys are loaded /apply the boostrap.min.css file? I'd like to do some tests related to the v4 version and I am yet able to figure out where I can find this file during a standard docker deployment. Thanks!
