### ISSUE TITLE
[phpcs] Rules error

### ISSUE THREAD

**Issue by true-hero** [DefectDojo/django-DefectDojo#4500]
## Bug description
Bug appears in production environment, when I try to upload phpcs report. Error log looks like this:
```
uwsgi_1         | [13/May/2021 08:57:08] ERROR [dojo.engagement.views:614] argument of type 'NoneType' is not iterable
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "./dojo/engagement/views.py", line 602, in import_scan_results
uwsgi_1         |     close_old_findings=close_old_findings)
uwsgi_1         |   File "./dojo/importers/importer/importer.py", line 254, in import_scan
uwsgi_1         |     now=now)
uwsgi_1         |   File "./dojo/importers/importer/importer.py", line 88, in process_parsed_findings
uwsgi_1         |     item.save(dedupe_option=False)
uwsgi_1         |   File "./dojo/models.py", line 2150, in save
uwsgi_1         |     do_apply_rules(self, *args, **kwargs)
uwsgi_1         |   File "./dojo/utils.py", line 390, in do_apply_rules
uwsgi_1         |     if rule.match_text in getattr(new_finding, rule.match_field):
uwsgi_1         | TypeError: argument of type 'NoneType' is not iterable
```

There is no such problem on testing environment with fresh database. 
UPD. It is problem with rules framework. When i delete my rules, problem was solved.

## Steps to reproduce
1. Get phpcs report file
2. Try to upload it

## Environment information
 - DefectDojo 1.15.0

**Comment by valentijnscholten** [comment]
what rules did you put in place?

**Comment by true-hero** [comment]
![Снимок экрана 2021-05-13 в 12 10 20](https://user-images.githubusercontent.com/32260664/118242781-5b0bc180-b4a6-11eb-89e6-9622de8263f5.png)
![Снимок экрана 2021-05-13 в 12 10 15](https://user-images.githubusercontent.com/32260664/118242785-5c3cee80-b4a6-11eb-913d-9e86a9afe52c.png)
![Снимок экрана 2021-05-13 в 12 10 08](https://user-images.githubusercontent.com/32260664/118242788-5c3cee80-b4a6-11eb-8651-410af8053e97.png)

**Comment by true-hero** [comment]
I completely remove them, to make phpcs parser works

**Comment by damiencarol** [comment]
thanks for the details @true-hero . Sadly, I don't know very well this part (rules). :/
