### ISSUE TITLE
Clair Scan file upload fails when parsing

### ISSUE THREAD

**Issue by devsecopsale** [DefectDojo/django-DefectDojo#4504]
**Be informative**
When I try to upload a Clair Scanner (json) file, it fails with server 500 code error.
when I look at the logs I can see: 
"TypeError: string indices must be integers"

**Bug description**
Clair Scan can't be imported due to an error.
This is cause by an improper json file parsing. I'll submit a pull request on this to fix it.

**Steps to reproduce**
1. Go to 'Clair Scan' test type
2. Try to upload or re-upload a Scan file
3. See error

**Expected behavior**
The upload will fail

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x ] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Debian (Docker)
 - DefectDojo Commit Message: [use `git show -s --format="[%ci] %h: %s [%d]"`]

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

**Comment by damiencarol** [comment]
@devsecopsale could you provide a stack trace? the report that fail ? (even redacted)

**Comment by devsecopsale** [comment]
web-ui error message: 

An error has occurred in the parser, please see error log for details.

nginx trace:

nginx_1         | 2021/05/14 08:36:10 [warn] 6#6: *103 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000001, client: x.x.x.x, server: , request: "POST /test/19/re_import_scan_results HTTP/1.1", host: "xxxxx:XXX", referrer: "http://xxxxx:XXX/test/19/re_import_scan_results"
uwsgi_1         | [14/May/2021 08:36:10] ERROR [dojo:701] string indices must be integers
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "./dojo/test/views.py", line 692, in re_import_scan_results
uwsgi_1         |     parser_findings = parser.get_findings(file, test)
uwsgi_1         |   File "./dojo/tools/clair/parser.py", line 19, in get_findings
uwsgi_1         |     return self.get_items(tree, test)
uwsgi_1         |   File "./dojo/tools/clair/parser.py", line 25, in get_items
uwsgi_1         |     item = get_item(node, test)
uwsgi_1         |   File "./dojo/tools/clair/parser.py", line 34, in get_item
uwsgi_1         |     if item_node['severity'] == 'Negligible' or item_node['severity'] == 'Unknown':
uwsgi_1         | TypeError: string indices must be integers
uwsgi_1         | [14/May/2021 08:36:10] ERROR [dojo:702] Error in parser: string indices must be integers
uwsgi_1         | [pid: 17|app: 0|req: 96/175] x.x.x.x () {52 vars in 1514 bytes} [Fri May 14 08:36:10 2021] POST /test/19/re_import_scan_results => generated 0 bytes in 88 msecs (HTTP/1.1 302) 8 headers in 466 bytes (1 switches on core 0)
nginx_1         | x.x.x.x - - [14/May/2021:08:36:10 +0000] "POST /test/19/re_import_scan_results HTTP/1.1" 302 0 "http://http://xxxxx:XXX/test/19/re_import_scan_results" "Mozilla/5.0 (Windows NT 10.0; Win64; x64)  "-"
uwsgi_1         | [pid: 17|app: 0|req: 97/176] x.x.x.x () {46 vars in 1447 bytes} [Fri May 14 08:36:10 2021] GET /test/19/re_import_scan_results => generated 51728 bytes in 88 msecs (HTTP/1.1 200) 8 headers in 467 bytes (1 switches on core 1)

**Comment by devsecopsale** [comment]
Pull request #4505  (that I submitted yesterday) should fix this

**Comment by damiencarol** [comment]
@devsecopsale it seems you are facing an already fixed bug (see https://github.com/DefectDojo/django-DefectDojo/pull/4120). 
Could you complete the description of the issue with your version? I have the feeling that you are using an old version that have an old bug.

**Comment by devsecopsale** [comment]
Hi @damiencarol  , it seems you are right. It was fixed like one month and a half ago in dev and then pulled to master.
