### ISSUE TITLE
Improve SonarQube integration with SonarCloud API

### ISSUE THREAD

**Issue by damiencarol** [DefectDojo/django-DefectDojo#4513]
**Is your feature request related to a problem?**
SonarQube API Import integration doesn't seem to work with sonarcloud.io (paid plan). This is due to api/components/search and api/rules/show requiring an organization field in SonarCloud, but not in SonarQube.
It is possible to make it work by hard-coding the org name in those two requests:
https://github.com/DefectDojo/django-DefectDojo/blob/38609f7316cf6bf6cb30736f644fe2c66cc71061/dojo/tools/sonarqube_api/api_client.py#L46
https://github.com/DefectDojo/django-DefectDojo/blob/38609f7316cf6bf6cb30736f644fe2c66cc71061/dojo/tools/sonarqube_api/api_client.py#L195

More details: https://github.com/DefectDojo/django-DefectDojo/pull/1444

**Describe the solution you'd like**
Something that work with every SonarQube API.

**Describe alternatives you've considered**
One way to fix that could be to rely on an external Python package that support the 3 implementations of the SonarQube API (SonarQube, sonarcloud free and paid):
https://pypi.org/project/python-sonarqube-api/

From:
https://python-sonarqube-api.readthedocs.io/en/latest/examples/setup.html

setup a sonarqube client:
```Python
from sonarqube import SonarQubeClient
url = 'http://localhost:9000'
username = "admin"
password = "admin"
sonar = SonarQubeClient(sonarqube_url=url, username=username, password=password)
```
setup sonarcloud client:
```Python
from sonarqube import SonarCloudClient
sonarcloud_url = "https://sonarcloud.io"
sonarcloud_token = "*********************"
sonar = SonarQubeClient(sonarcloud_url=sonarcloud_url, token=sonarcloud_token)
```

**Additional context**
Logs:
```
uwsgi_1         | [13/May/2021 11:15:49] ERROR [dojo.tools.sonarqube_api.importer:117] Unable to get the rule pythonsecurity:S5146 due to 400 - b'{"errors":[{"msg":"The \'organization\' parameter is missing"}]}'
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "./dojo/tools/sonarqube_api/importer.py", line 77, in import_issues
uwsgi_1         |     rule = client.get_rule(rule_id)
uwsgi_1         |   File "./dojo/tools/sonarqube_api/api_client.py", line 205, in get_rule
uwsgi_1         |     rule_id, response.status_code, response.content
uwsgi_1         | Exception: Unable to get the rule pythonsecurity:S5146 due to 400 - b'{"errors":[{"msg":"The \'organization\' parameter is missing"}]}
```

**Comment by MichaelGissingNC** [comment]
@damiencarol I am currently evaluating DefectDojo. I tried to patch the 2 requests with the organization field.
However, I don't get any error messages, also not wihtout the patch. Any hints on how to figure out if the tool was even triggered?

Thanks for your work!

**Comment by damiencarol** [comment]
@MichaelGissingNC you should be able to have more details by checking at the alert zone the upper right corner
![image](https://user-images.githubusercontent.com/1694940/119143836-5c119580-ba48-11eb-98d3-f4d0f0390b63.png)

**Comment by CharlieSears** [comment]
@MichaelGissingNC, is this something you're working on and have a branch that could be contributed to?

We've been loving Defect Dojo but SonarCloud missing is something I'd love to get functional and would hate to duplicate effort to get this in to 2.5.0.

**Comment by MichaelGissingNC** [comment]
@CharlieSears I only tried to incorporate the changes @damiencarol suggested in `django-DefectDojo/dojo/tools/sonarqube_api/api_client.py`, and I didn't even ship it to our production instance. I did no additonal work and no further investigation after it didn't work for me.

There was some discussion going on on OWASP Slack about it, I can offer to help testing a new implementation with our SonarCloud paid subscription.

https://owasp.slack.com/archives/C2P5BA8MN/p1633438882333800

**Comment by valentijnscholten** [comment]
I think there's some initial work in https://github.com/DefectDojo/django-DefectDojo/pull/5325

**Comment by fishhead108** [comment]
Any news here?

**Comment by onkardhane-oviva** [comment]
@fishhead108 I am not aware of the status of this enhancement, but I managed to import issues from SonarCloud by modifying the endpoints in`dojo/tools/sonarqube_api/api_client.py` 
Basically add organization  parameter at these places. e.g. 
`url='{}/components/search?organization=your_org_name'.format(self.sonar_api_url),`
[Here](https://github.com/DefectDojo/django-DefectDojo/blob/d75069724d45163c05f89976e209fa10a9cf76aa/dojo/tools/sonarqube_api/api_client.py#L45) and [Here](https://github.com/DefectDojo/django-DefectDojo/blob/d75069724d45163c05f89976e209fa10a9cf76aa/dojo/tools/sonarqube_api/api_client.py#L346)

**Comment by L3m0nb4tt3ry** [comment]
@fishhead108 I am not aware of the status of this enhancement, but I managed to import issues from SonarCloud by modifying the endpoints in`dojo/tools/sonarqube_api/api_client.py` 
Basically add organization  parameter at these places. e.g. 
`url='{}/components/search?organization=your_org_name'.format(self.sonar_api_url),`
[Here](https://github.com/DefectDojo/django-DefectDojo/blob/d75069724d45163c05f89976e209fa10a9cf76aa/dojo/tools/sonarqube_api/api_client.py#L45) and [Here](https://github.com/DefectDojo/django-DefectDojo/blob/d75069724d45163c05f89976e209fa10a9cf76aa/dojo/tools/sonarqube_api/api_client.py#L346)

**Comment by fishhead108** [comment]
Thx @L3m0nb4tt3ry !

**Comment by JonasDewit** [comment]
It looks like `api_client.py` has been updated. First of all, you'll have to look for it in `dojo/tools/api_sonarqube` instead of `sonarqube_api`. In addition, it will look for an `OrgID` parameter in the 'extras' field of the tool config in Defect Dojo. So just adding `OrgID=<SonarCloud organization key>` will suffice to connect to the SonarCloud API. Example:

![image](https://github.com/DefectDojo/django-DefectDojo/assets/12342163/bca5b79d-e51d-45de-958a-f509f37da5a1)

I couldn't find any reference to this in the documentation, so adding it here in case it might help someone.
