### ISSUE TITLE
Images on report when placed in files

### ISSUE THREAD

**Issue by VitorDominguesR** [DefectDojo/django-DefectDojo#4524]
Hi guys,

When we upload an image in a finding by using the "Manage Images" in the finding view, the app says that it will be no longer used and says to use the files instead.

However, when we generate a PDF report, there's no option to include this files or images in the report.

Another thing that i personally like more using the API is the image comes in base64 together with the finding and we can easyly access then rather then the files.

If you can maintain those information in API response, that would be great.

Thanks

**Comment by saldam72** [comment]
Hello teams,
we are interested to this feature (we are also interested to the "Manage Images" feature. Would you please tell us if this feature will be implemented ? Don't you agree that keeping both features is better ?

Best,
Sal
