### ISSUE TITLE
APIv1 leftover 

### ISSUE THREAD

**Issue by dsever** [DefectDojo/django-DefectDojo#4532]
**Bug description**

In dev  repo, (v.2.0) inside of user profile, user can ask for API key that still is pointing to the APIv1 endpoint, so error 500 is there.

![image (22)](https://user-images.githubusercontent.com/7211879/118936999-5b480900-b94d-11eb-9181-65aa6080b0ed.png)
![image (21)](https://user-images.githubusercontent.com/7211879/118937005-5c793600-b94d-11eb-8492-947289a88bc1.png)

**Expected behavior**
Replaced by APIv2 key request, or removed completely

**Comment by StefanFl** [comment]
Is anyone on it already? Otherwise I would volunteer.

**Comment by damiencarol** [comment]
@StefanFl assigning to you.

**Comment by valentijnscholten** [comment]
fixed in dev / 2.0.0
