### ISSUE TITLE
Error implementing devsecops in jenkins

### ISSUE THREAD

**Issue by cyclopsbarrack** [DefectDojo/django-DefectDojo#4540]
When we try to push results of trufflehog tool from jenkins to defect dojo using upload results.py (https://github.com/cyclopsbarrack/webapp/blob/master/upload-results.py) we are getting 403 issue.Any Possible solution to fix this?

![403](https://user-images.githubusercontent.com/78903969/119090876-ce26b200-ba29-11eb-9ecc-e30f36fe31f7.png)
![jenkins](https://user-images.githubusercontent.com/78903969/119091327-83596a00-ba2a-11eb-888d-ad74f7703f0e.png)

**Comment by damiencarol** [comment]
which version of Truffehog do you use? the situation around v2 and v3 is a mess. reports are incompatibles. It's why we have 2 different parsers.

**Comment by valentijnscholten** [comment]
please provide url, request, response etc. the upload-results.py is a black box to us.

**Comment by damiencarol** [comment]
@valentijnscholten made some checks, the script use API v1 and `importscan/` endpoint

**Comment by damiencarol** [comment]
@cyclopsbarrack there are not enough details here. Could you provide the message of the 403 error and the logs of the wusgi container of DefectDojo? the version of DefectDojo ? the deployment configuration (Docker/godojo) ?

**Comment by cyclopsbarrack** [comment]
> which version of Truffehog do you use? the situation around v2 and v3 is a mess. reports are incompatibles. It's why we have 2 different parsers.

we have used both versions of the truffle log but still facing the same issue we also tried to push zap report still the same issue.

**Comment by cyclopsbarrack** [comment]
> @cyclopsbarrack there are not enough details here. Could you provide the message of the 403 error and the logs of the wusgi container of DefectDojo? the version of DefectDojo ? the deployment configuration (Docker/godojo) ?

Here we are trying to setup a DevSecOps environment (https://owasp.org/www-project-devsecops-maturity-model/#) using this method (https://github.com/devopssecure/webapp) . We have automated everything using Jenkins. This is our project code (https://github.com/cyclopsbarrack/webapp/)  we are trying to push all the reports (truffle hog, owasp dependecy check, sonarqube, Zap, etc ) to defectdojo. Since API v1 has been stopped . we are using API v2. is there any other effective method to push the reports from jenkins to defectdojo?
[jenkins.log.1.txt](https://github.com/DefectDojo/django-DefectDojo/files/6568037/jenkins.log.1.txt)
[jenkins.log .txt](https://github.com/DefectDojo/django-DefectDojo/files/6568038/jenkins.log.txt)

**Comment by valentijnscholten** [comment]
Could you please provide the exact request / responses you are seeing? The earlier snippet seems to suggest you are using api v1. And provide info on which version of defect dojo, which install method, etc.

**Comment by StefanFl** [comment]
Closed due to inactivity
