### ISSUE TITLE
Acunetix Parser Bug

### ISSUE THREAD

**Issue by AliElKhatteb** [DefectDojo/django-DefectDojo#4552]
hello guys i hope you are doing great, i am facing an issue with Acunetix parser i tried to use the re-upload feature to upload my report and i got this error message
**Deployment method** *(select with an `X`)*
- [X] Kubernetes

**Console logs** (optional)
[pid: 1|app: 0|req: 262549/510967] 10.25.159.25 () {34 vars in 411 bytes} [Mon May 24 13:23:15 2021] GET /uwsgi_health => generated 13394 bytes in 24 msecs (HTTP/1.1 200) 9 headers in 472 bytes (1 switches on core 1)
[pid: 1|app: 0|req: 262550/510968] 10.25.159.25 () {30 vars in 392 bytes} [Mon May 24 13:23:22 2021] GET /login?next=/ => generated 13394 bytes in 26 msecs (HTTP/1.1 200) 9 headers in 472 bytes (1 switches on core 0)
[pid: 1|app: 0|req: 262551/510969] 10.25.159.25 () {34 vars in 411 bytes} [Mon May 24 13:23:25 2021] GET /uwsgi_health => generated 13394 bytes in 25 msecs (HTTP/1.1 200) 9 headers in 472 bytes (1 switches on core 1)
[24/May/2021 13:23:27] ERROR [dojo:701]
Traceback (most recent call last):
  File "./dojo/test/views.py", line 692, in re_import_scan_results
    parser_findings = parser.get_findings(file, test)
  File "./dojo/tools/acunetix/parser.py", line 33, in get_findings
    return self.set_defectdojo_findings(acunetix_defectdojo_findings, test)
  File "./dojo/tools/acunetix/parser.py", line 44, in set_defectdojo_findings
    date=get_defectdojo_date(acunetix_defectdojo_finding.date),
  File "./dojo/tools/acunetix/parser.py", line 70, in get_defectdojo_date
    match = next(enumerate(matches))
StopIteration
[24/May/2021 13:23:27] ERROR [dojo:702] Error in parser:
[pid: 1|app: 0|req: 262552/510970] 10.42.11.43 () {76 vars in 1982 bytes} [Mon May 24 13:23:27 2021] POST /test/46/re_import_scan_results => generated 0 bytes in 53 msecs (HTTP/1.1 302) 8 headers in 466 bytes (1 switches on core 0)
[uwsgi-http key: chs-defectdojo.cegedim.com client_addr: 10.25.159.25 client_port: 1212] hr_read(): Connection reset by peer [plugins/http/http.c line 917]

Thanks i hope to hear from you soon

**Comment by damiencarol** [comment]
@AliElKhatteb is it possible to have the report that failed? (even redacted)

**Comment by AliElKhatteb** [comment]
unfortunately i can't its a pentest report in my company

**Comment by AliElKhatteb** [comment]
[edited_report.zip](https://github.com/DefectDojo/django-DefectDojo/files/6537950/edited_report.zip)

**Comment by AliElKhatteb** [comment]
btw i used also json format and its not working also

**Comment by damiencarol** [comment]
taking a look at your report.

**Comment by damiencarol** [comment]
On release `2.0.0`:
![image](https://user-images.githubusercontent.com/1694940/119492881-e23b1e00-bd5f-11eb-8072-38736a076f10.png)

**Comment by AliElKhatteb** [comment]
so its fixed on release 1.15.0

**Comment by damiencarol** [comment]
it seems. It's why it's important to specify the release number when you open an issue. Most of the time, the bug is already fixed in further releases. :)
