### ISSUE TITLE
Aqua Scan findings not marked as duplicates after importing same report

### ISSUE THREAD

**Issue by vishalBajpai23** [DefectDojo/django-DefectDojo#4553]
**Bug description**
I am trying to import reports for Aqua Scan(JSON format). I have observed that even after importing same file across engagements or within same engagement, findings are not marked as duplicate automatically,rather present under similar findings - from there finding can be marked as duplicate manually. Where as this duplication works for Blackduck Component Risk, Checkmarx etc

**Steps to reproduce**
    
- Create an engagement under a product then import scan result for Aqua test type(JSON file)

-  Either create new engagement and import same scan file(attached json file) or import scan result in same engagement one more time, and all the findings are marked as Active for scan report uploaded later rather than marking findings as duplicate.

**Expected behavior**
If same report file is imported twice in same engagement or across engagement findings should be marked as duplicate for all the scan reports imported after first one

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ X] Docker
- [ ] setup.bash / legacy-setup.bash

**Sample scan files** (optional)
attached centos_7_aqua_report.zip - extract to get json file

**Screenshots** (optional)
In attached screenshot, both the tests(Aqua Scan) are of same report. 
<img width="1318" alt="aqua_scan_report" src="https://user-images.githubusercontent.com/84701263/119382285-731de500-bcdf-11eb-9d83-d786cbb98225.png">

[centos_7_aqua_report.json.zip](https://github.com/DefectDojo/django-DefectDojo/files/6533828/centos_7_aqua_report.json.zip)

**Comment by valentijnscholten** [comment]
@madchap Did you write the original Aqua parser? I think deduplication is not happening because some fields used by the legacy dedupe algorithm are not set: `cwe`, `file_path`, `line_number`, etc.

**Comment by ansidorov** [comment]
I want to try to fix this bug

**Comment by valentijnscholten** [comment]
fixed in dev / 2.0.0
