### ISSUE TITLE
Add "tags" to the API

### ISSUE THREAD

**Issue by xthk** [DefectDojo/django-DefectDojo#457]
### Issue Type

- [ ] Bug
- [X] Enhancement

### Add tags to the API

As an API user I'd like to be able to use DefectDojo's tagging system via the API. According to https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/models.py#L1231-L1237 tags could be applied to products, tests, findings, engagements, endpoints (currently missing in the API, #420), and finding templates.

An example use case would be to get a list of products or endpoints with a given tag, e.g. "Python" and then start a specialized tool for this products or endpoints. 

Another example use case would be to set set tags based on a discovery scan (e.g. for Typo3 instances) and use this information for the example above.

I'd love to see all CRUD (create, read, update, delete) operations for tags.

**Comment by Horst88** [comment]
Hi,
this would be great and also comply with, **Tools need to have an API so that the 'All the things' can be automated**, see https://www.owasp.org/index.php/OWASP_AppSec_Pipeline#tab=Pipeline_Tools

**Comment by devGregA** [comment]
Tags have been added to both v1 and v2 of the API
