### ISSUE TITLE
Dependabot only updates Dockerfile.django

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#4578]
It doesn't seem to recognize Dockerfile.nginx and Dockerfile.integration-tests: https://github.com/DefectDojo/django-DefectDojo/network/updates

**Comment by valentijnscholten** [comment]
submitted a support ticket. worst case we can adjust the renovate exclusion to start including the other dockerfiles.

**Comment by valentijnscholten** [comment]
actually the 2 other Dockerfiles are there, but slightly hidden:

![image](https://user-images.githubusercontent.com/4426050/120385250-79d3da00-c327-11eb-8aaa-915f54226612.png)


still 1.20 PR was never created and 1.21 was 1 week late.

**Comment by damiencarol** [comment]
weird

**Comment by valentijnscholten** [comment]
Seems to work fine
