### ISSUE TITLE
Show URIs in "All Endpoints" view?

### ISSUE THREAD

**Issue by xthk** [DefectDojo/django-DefectDojo#458]
### Issue Type 

- [ ] Bug
- [X] Enhancement

### Description

The current view of "All Endpoints" shows only the content of fiel "host". I think this view would benefit from showing the full URI of an endpoint. That'd really help in a scenario where multiple projects share a common hostname, e.g. www.example.com and their endpoints would be https://www.example.com/foo/ and https://www.example.com/bar/.

The current view looks like this:

<img width="800" alt="defectdojo_all_endpoints" src="https://user-images.githubusercontent.com/5803044/35668433-c314c5ae-0731-11e8-810b-7e2c9b2fba0e.png">

**Comment by devGregA** [comment]
@xthk https://github.com/DefectDojo/django-DefectDojo/commit/4be42a375f3a050b9c756470605a6c8abf6a9a8d adds a system setting to toggle this view. You'll need to pull the new code and the upgrade the DB by running:

`python manage.py makemigrations`

` python manage.py migrate`
