### ISSUE TITLE
Endpoint view shows false positive for "Vulnerable Services"

### ISSUE THREAD

**Issue by xthk** [DefectDojo/django-DefectDojo#460]
### Issue Type 
- [X] Bug
- [ ] Enhancement

### Description

The endpoint view indicates a vulnerable service, although there is no finding at all for the endpoint and the associated product.

### Operating System 

Ubuntu 16.04, Python 2.7.12, Django 1.11.2

### Install

- [ ] setup.bash
- [ ] docker

### Steps to Reproduce

- create new product
- create new endpoint for the new product (remember ID)
- open "/endpoint/<ID>"
- inspect list of "Vulnerable Services"

### Screenshots

<img width="800" alt="defectdojo_endpoint_vulnerable_services" src="https://user-images.githubusercontent.com/5803044/35669352-183f5b18-0735-11e8-8660-6f0b07d38f15.png">

**Comment by devGregA** [comment]
Believe to be fixed via https://github.com/DefectDojo/django-DefectDojo/commit/ee3e7cafc86a1c708af503d16459366c2926bd85

Please  reopen this issue if you continue to have issues.
