### ISSUE TITLE
Date format in findings API

### ISSUE THREAD

**Issue by tonnyhideyori** [DefectDojo/django-DefectDojo#4661]
**Bug description**
when using findings API /api/v2/findings/?date=2021-01-02, all date style results into an error 
{
  "date": [
    "Select a valid choice. 2021-01-02 is not one of the available choices."
  ]
}

**Steps to reproduce**
I have tried different date format, also i tried a timestamp still bring the same error. Hence, can you clarify what date format should be used on that field.
thank you

**Expected behavior**

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [ Ubuntu 18.04]

**Comment by valentijnscholten** [comment]
It's an integer similar to what's in the UI. In dev we have an OpenAPI v3 spec that describes it better.

```
                    {
                        "in": "query",
                        "name": "date",
                        "schema": {
                            "type": "string",
                            "format": "date",
                            "enum": [
                                "",
                                1,
                                2,
                                3,
                                4,
                                5,
                                6,
                                7
                            ]
                        },
                        "description": "The date the flaw was discovered.\n* \"\" - Any date\n* \"1\" - Today\n* \"2\" - Past 7 days\n* \"3\" - Past 30 days\n* \"4\" - Past 90 days\n* \"5\" - Current month\n* \"6\" - Current year\n* \"7\" - Past year\n"
                    },
```

**Comment by tonnyhideyori** [comment]
thank you
