### ISSUE TITLE
Re-import the same scan creates and closes findings

### ISSUE THREAD

**Issue by NicolasBi** [DefectDojo/django-DefectDojo#4663]
Hi,
I am trying to use the “re-import” feature for ScoutSuite scans however when I import the scan and then I re-import exactly the same scan (unchanged scoutsuite scan file) for some reasons DD creates and closes some findings and untouched others. 
Why did DD create and close finding even the scan file has not changed ? These deletions and creations break the lifecycle of the findings as the status and other fields are reset to default.

**Bug description**
DD closes and creates findings even if the scan file is the same (ScoutSuite report).

**Steps to reproduce**
1. Create an engagment
2. Import a scoutsuite scan -> Message "34 findings created" (for my example)
3. Reupload (reimport) the same scoutsuite scan -> Message "15 findings created, 15 findings closed , 19 findings" untouched.

**Expected behavior**
I expect that DD would untouch all findings as there is no difference between the first import and the reimport.

**Deployment method** *(select with an `X`)*
- [X] Kubernetes

**Environment information**
 - Operating System: [AL2]
 - DefectDojo version : 1.15.1
- deduplication activated, max duplicate = 0
- parser ScoutSuite

**Screenshots**
<img width="1251" alt="Capture d’écran 2021-06-14 à 17 35 10" src="https://user-images.githubusercontent.com/81238536/122083932-9c72f200-ce01-11eb-92a5-d12cf683495a.png">

**Comment by damiencarol** [comment]
@NicolasBi took some time to investigate. It seems that the de-duplication algorithm is not working well with ScoutSuite parser.

**Comment by damiencarol** [comment]
After some discussions, I confirm that there is no default configuration for ScoutSuite parser. this makes the de-duplication during re-import not work as @NicolasBi is expecting.
No really a bug but we can at least add a default configuration.

**Comment by damiencarol** [comment]
Pushed #4668 to fix this

**Comment by NicolasBi** [comment]
Thanks @damiencarol , since the Scout Suite parser aggregate some findings in the same description field, is it more appropriate to set the hash key to ['title', 'severity','description'] ?

**Comment by damiencarol** [comment]
@NicolasBi don't know. I checked the parser and it set the resource in the title. So I guess  ['title', 'severity'] should be ok.

**Comment by NicolasBi** [comment]
I tested with 2 different scans, with the ['title', 'severity','description'] and it suits best as it's detecting change inside the description field. For example: In a ScouSuite scan the title of the finding can be 'Single AZ RDS Instance' and the description contains all the faulty rds database. If a database change between 2 scans, the finding must be closed and recreated with updated description.

**Comment by damiencarol** [comment]
ok. will update the PR. thanks a lot for you tests and support 👍

**Comment by damiencarol** [comment]
https://github.com/DefectDojo/django-DefectDojo/pull/4668/commits/8e156c938d14e2b0ad3b49ef6a8968f11e3b1487

**Comment by valentijnscholten** [comment]
Known issue if the deduplication algorithm results in duplicates inside the same import: https://github.com/DefectDojo/django-DefectDojo/issues/3958
