### ISSUE TITLE
docker-compose break

### ISSUE THREAD

**Issue by tonnyhideyori** [DefectDojo/django-DefectDojo#4667]
**Bug description**
when i put my username, password ,host and port the docker-compose build breaks.
bringing this error :
ValueError: invalid literal for int() with base 10: 'B*\*\*\*\*\*3'
ERROR: Service 'nginx' failed to build: The command '/bin/sh -c env DD_SECRET_KEY='.' python3 manage.py collectstatic --noinput && true' returned a non-zero code: 1
I edited in settings.dist.py
EMAIL_CONFIG = env.email_url(
    'DD_EMAIL_URL', default='smtp://A*\*\*\*\*\*\*\*C@:B*\*\*\*\*\*\*\*\*3/x*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\+9*\*G@email-smtp.eu-central-1.amazonaws.com:25')
when i remove slas("/")h in the password it does not break , hence what could be the problem
**Deployment method** 
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Commit Message: [use `git show -s --format="[%ci] %h: %s [%d]"`]

**Comment by damiencarol** [comment]
your password must be URL encoded.
