### ISSUE TITLE
defectDojo failed after using latest docker image

### ISSUE THREAD

**Issue by Mason-Fan** [DefectDojo/django-DefectDojo#468]
Please use the following template when submitting issues:

### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description
use the defectdojo docker image from appsecpipeline/django-defectdojo docker hub for about 1month. yesterday update the image with latest and start a new container with the older mysql data volume mounted with command below
 docker run --name defectDojo -v defectDojo-mysql:/var/lib/mysql -it -p 8000:8000 appsecpipeline/django-defectdojo bash -c " bash /django-DefectDojo/docker/docker-startup.bash" 

get the error below after docker starts

Request Method: | GET
-- | --
OperationalError
(1054, "Unknown column 'dojo_finding.line' in 'field list'")
/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py in execute_sql, line 886
/usr/bin/python
2.7.12
['/opt/django-DefectDojo',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages',  '/opt/django-DefectDojo']
Fri, 9 Feb 2018 04:46:28 +0000

so hope we can have detailed document about upgrade or migration

### Operating System 
Ubuntu 16.04

### Install

- [ ] setup.bash
- [x] docker

### Screenshots (optional)
![image](https://user-images.githubusercontent.com/8722967/36012297-2e91c842-0d98-11e8-97e1-acabc91cbf73.png)

**Comment by devGregA** [comment]
@Mason-Fan on the docker system if you perform the following from the DD directory it should fix the issue: `python manage.py makemigrations` `python manage.py migrate` it should update the DB.
