### ISSUE TITLE
Severity not respected in "Similar Findings" tab

### ISSUE THREAD

**Issue by Wadeck** [DefectDojo/django-DefectDojo#4692]
**Bug description**
I have 2 findings, on the same CVE. Between the creation of the first one and the second one, the severity of the CVE seems to have changed. When I search the first one from "Similar Findings" from the second, the severity of the first one is not respected (from High to Critical).

**Expected behavior**
The severity to be the one from the found finding and not the current one.

**Deployment method** *(select with an `X`)*
- [x] Kubernetes
- [ ] Docker
- [ ] setup.bash / legacy-setup.bash

**Screenshots** (optional)

Similar findings

![Screenshot_2021-06-21_094821_001](https://user-images.githubusercontent.com/2662497/122726824-aae46200-d276-11eb-8798-a073ff14f6ad.png)

First finding

![Screenshot_2021-06-21_094830_001](https://user-images.githubusercontent.com/2662497/122726817-a9b33500-d276-11eb-9636-1a6fc5c1c736.png)

**Comment by valentijnscholten** [comment]
fixed in dev / 2.0.0
