### ISSUE TITLE
Timeout when calling findings API with large limit value

### ISSUE THREAD

**Issue by tonnyhideyori** [DefectDojo/django-DefectDojo#4694]
We have more than 3000 findings in defectdojo , when we want to list all findings with limit 4000 and setting **related_fields="true"**, we gate 504 error as time out. Hence, can you improve this situation or do you have any suggestion on how to tackle this situation.
recreate:
go to /api/v2/doc/
in /findings/
set limit=20000
set related_fields=true
when i check into to logs we get this error
`uwsgi_response_write_body_do():Broken pipe [core/writer.c line 341]during GET //api/v2/findings/?limit=20000&related_fields=true (xx.xx.xx.xx)
OSError: write error`
best regards

**Comment by devGregA** [comment]
@tonnyhideyori the broken pipe suggests a memory resource constraint. I don't believe you're hitting nginx or app constraints. The error suggests it's the hardware.
