### ISSUE TITLE
[URL broken] /metrics?view=dashboard&type=endpoint

### ISSUE THREAD

**Issue by damiencarol** [DefectDojo/django-DefectDojo#4701]
**Bug description**
One metric dashboard is broken at least on `1.15.1`, `dev`

```
uwsgi_1         | ERROR:django.request:Internal Server Error: /metrics
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
uwsgi_1         |     response = view_func(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/vary.py", line 38, in inner_func
uwsgi_1         |     response = func(*args, **kwargs)
uwsgi_1         |   File "/app/./dojo/metrics/views.py", line 459, in metrics
uwsgi_1         |     for obj in queryset_check(filters['all'])
uwsgi_1         | KeyError: 'all'
```

**Steps to reproduce**
1. Go to `/metrics?view=dashboard&type=endpoint`
2. See error 500

**Deployment method** *(select with an `X`)*
Docker

**Environment information**
 - DefectDojo  `1.15.1` & `dev`

**Comment by valentijnscholten** [comment]
@danielnaab I think this was "caused" by your metrics refactoring, do you have it still on top of mind and maybe know how to fix it?

**Comment by danielnaab** [comment]
> @danielnaab I think this was "caused" by your metrics refactoring, do you have it still on top of mind and maybe know how to fix it?

Hi @valentijnscholten - looking at the code, I'm guessing it's a case-sensitivity issue, not related to the perf changes - `type=Endpoint` vs `type=endpoint` - https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/metrics/views.py#L453

**Comment by valentijnscholten** [comment]
Weird, the view parameters contains `dashboard` but when I change the `type` parameter to `endpoint` the error dissappears.

**Comment by StefanFl** [comment]
@damiencarol How did you get this URL? When I switch to the endpoint metrics dashboard in the UI, the URL is `metrics?view=dashboard&type=Endpoint` and works fine.

**Comment by damiencarol** [comment]
@StefanFl an old chap of the project gave me it @Maffooch

**Comment by damiencarol** [comment]
but should we just return a 404 if the URL is not good?

**Comment by StefanFl** [comment]
I think 400 is the correct return code, as we find the ressource (`metrics`), but an HTTP parameter (`type=endpoint`) is invalid.

**Comment by valentijnscholten** [comment]
If it is not linked anywhere in the UI I don't think we need to do anything. If string comparison is case sensitive everywhere, probably every page in Defect Dojo will suffer from this.

**Comment by StefanFl** [comment]
Fine for me

**Comment by damiencarol** [comment]
ok. so I guess we can close it.
