### ISSUE TITLE
Add Asset view : Bind many endpoints to one asset. 

### ISSUE THREAD

**Issue by githule** [DefectDojo/django-DefectDojo#4712]
**Is your feature request related to a problem? Please describe**
Defect Dojo todays sees only assets as endpoints ( an IP OR an Url OR a domain...). 
However, it would be usefull to have an asset view based on a corporate cmdb import
Also different endpoints type can match to the same asset.
Then finding can be associated to assets via endpoint relation

**Describe the solution you'd like**
Add a new model that integrates CMDB assets that can be matched to endpoints.
Exemple an asset can be a container for multiple endpoints including url, ips, technical host fqdn, webservice fqdn...
As an extension an asset can be a parent of another asset.

**Describe alternatives you've considered**
I dont think this is possible in the nowadays Defect dojo model. Maybe I am wrong.

Do you have that kind of feature in your roadmap ?

**Comment by damiencarol** [comment]
@githule we had some discussions in the last maintainer meeting to introduce more generic code to handle assets linked to a finding (like file) but nothing concrete for now.
You're welcome if you want to contribute even if it's just for a design/ideas

**Comment by githule** [comment]
@damiencarol : as a design it can be assets objects that can be imported from a cmdb. Theses assets can represent for example : a public web site host seen as well from an internet view via a remote scanner or via a local agent on the host. 
The main goal is to associate different maner to address the same asset/app : URL, IP address, FQDN...
It can help to bind external "internet" view from the internal view of the same assets as well as when its having multiple ip address.
It can help when you scan large IP ranges to bind detected vuln not only with endpoints but also with apps/assets related to endpoints
It can help to add metadata like identified risks or comments associated to networks or assets...

**Comment by damiencarol** [comment]
ok. interesting.
