### ISSUE TITLE
Netsparker Parser - Using `url` in finding is deprecated. We are using endpoint now.

### ISSUE THREAD

**Issue by kiliczsh** [DefectDojo/django-DefectDojo#4719]
Hi. Using `url` in finding is [deprecated](https://github.com/DefectDojo/django-DefectDojo/blob/44ab2d979f5d97b330258b7fd0f30f18d9553e5a/dojo/models.py#L1590-L1594). We are using endpoint now.

I suppose:
- it should be removed from [here](https://github.com/DefectDojo/django-DefectDojo/pull/4711/files#diff-2eb8d9651a662bc2c796080d1b3e12a6c8b2891a33b2f3081417ae2343f54b91R61)
- also [here](https://github.com/DefectDojo/django-DefectDojo/pull/4711/files#diff-2eb8d9651a662bc2c796080d1b3e12a6c8b2891a33b2f3081417ae2343f54b91R72)
- add as endpoint, like [here](https://github.com/DefectDojo/django-DefectDojo/blob/44ab2d979f5d97b330258b7fd0f30f18d9553e5a/dojo/tools/generic/parser.py#L49-L59)
- cleaned like [here](https://github.com/DefectDojo/cookiecutter-scanner-parser/blob/fa13c1c23b82599b99a00d7c96a27fd2df5bf436/temp-%7B%7B%20cookiecutter.tool_directory_name%20%7D%7D/unittests/tools/test_%7B%7B%20cookiecutter.tool_directory_name%20%7D%7D_parser.py#L20-L22)
- and also some unittest

_Originally posted by @kiblik in https://github.com/DefectDojo/django-DefectDojo/issues/4711#issuecomment-868985636_

**Comment by kiblik** [comment]
Fixed in https://github.com/kiliczsh/django-DefectDojo/pull/1

**Comment by kiblik** [comment]
This is done - can be closed
