### ISSUE TITLE
Jira connection in one place

### ISSUE THREAD

**Issue by tulsluper** [DefectDojo/django-DefectDojo#472]
### Issue Type 
- [ ] Bug
- [x] Enhancement

### Description

Could you please implement jira connection in models.py. 
For example:

```
    def init(self):
        try:
            jira = JIRA(
                server = self.url,
                basic_auth = (self.username, self.password)
            )
            logging.info('connection established')
            return jira
        except JIRAError as exc:
            logging.error(exc)
            return None
```
It will allow to reduce dozen lines
`jira = JIRA(server=jira_conf.url, basic_auth=(jira_conf.username, jira_conf.password))`
to
`jira = jira_conf.init()`

and then add new authentication methods in one place.

**Comment by devGregA** [comment]
Hi @tulsluper, this isn't on our roadmap right now, but we're always happy to receive pull requests.
