### ISSUE TITLE
add_findings doesn't work for user with not touched profile

### ISSUE THREAD

**Issue by tulsluper** [DefectDojo/django-DefectDojo#473]
Please use the following template when submitting issues:

### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description

add_findings page returns error when  user with not touched profile (maybe not created automatically) tries to add a finding.
After go to User Profile and save empty form - adding findings works without errors.

### Operating System 
RHEL 7.3

### Install

- [x] setup.bash
- [ ] docker

### Steps to Reproduce
create new user in admin with staff permissions
log in as new user
add new findings - <defectdojo_url>/test/<test_id>/add_findings

Error:

```
   RelatedObjectDoesNotExist at /test/45/add_findings
   User has no usercontactinfo.

    /opt/dojo/defect-dojo/dojo/test/views.py in add_findings
    236.    new_finding.save() ...

    /opt/dojo/defect-dojo/dojo/models.py in save
    781.    if self.reporter.usercontactinfo.block_execution:
```

**Comment by devGregA** [comment]
@tulsluper I haven't been able to reproduce this. I've tried creating users via admin console, and the dojo create user function. I've also tried with an instance being migrated vs not being migrated. I'm not sure what else to try. The error you received definitely seems to lineup.
