### ISSUE TITLE
Incorrect False positives and Risk accepted metrics

### ISSUE THREAD

**Issue by zakrush** [DefectDojo/django-DefectDojo#4752]
**Slack us first!**
Hello. I write about problem here:
https://owasp.slack.com/archives/C2P5BA8MN/p1624892081234100

**Be informative**
As additional into slack I find the same behaviour with Risk Accepted findings. Into Metrics I see 0 **Risk Accepted** findings, but I have 1 Risk Accepted finding

**Bug description**
No error. Metrics into product, or metrics dushboard has incorrect info. 

**Steps to reproduce**
1. Create 2 two or more findings into product
2. SetUp **false Positive** for finding and **Risk Accepted** for other
1. Go to 'Metrics' of products see that here 0 'False Positives'
2. Go to Metrics - Simple Metrics
3. Click into _View Details_ of products
4. Scroll 
3. Scroll down to `Metric Counts` - `Accepted Findings` 
4. See here is 0

**Expected behavior**
I expected that I can see metrics with False Positives and RiskAccepted

**Deployment method** *(select with an `X`)*
- [X ] Docker
- [ ] Kubernetes
- [ ] GoDojo
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo is 1.15.0 from master

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)
![DD_Metrics_Bug](https://user-images.githubusercontent.com/33844164/123970372-bd227680-d9c1-11eb-83be-541aab74f976.gif)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

**Comment by zakrush** [comment]
I also foud the same behavior with Closed Findings into Metrics
Here is ZERO when I have Closed Findings
![image](https://user-images.githubusercontent.com/33844164/124109092-7428fb80-da6f-11eb-85fd-46ac2c12cbcf.png)

**Comment by devGregA** [comment]
@zakrush  can you please confirm that this persists after 10 minutes? Some metrics are cached but I don't know which off the top of my head.

**Comment by zakrush** [comment]
@devGregA It's persist more than 10 minutes. I am observing this problem so far. 
False Positives result are incorrect into product.

**Comment by XiChen-Tibco** [comment]
Inactive findings within the Product Metrics is incorrect as well.

**Comment by StefanFl** [comment]
@zakrush A fix for this problem has been released with version 2.2.0. Please check if the metrics are correct now.

**Comment by zakrush** [comment]
Hi.

**Comment by zakrush** [comment]
@StefanFl 
I checked 2.4.0-dev just now. 
I see that Accepted in Period is correct, but Dashboard view is 0. 
![image](https://user-images.githubusercontent.com/33844164/136355650-fd078d57-aa1a-4f83-8501-e987207fc767.png)

Other metrics is correct.
