### ISSUE TITLE
Bulk edit capabilities to "Similar Findings"

### ISSUE THREAD

**Issue by Wadeck** [DefectDojo/django-DefectDojo#4773]
**Is your feature request related to a problem? Please describe**
When the similar findings tab contains several findings it becomes annoying to apply some changes for each one, individually, with a forced refresh of the page

**Describe the solution you'd like**
It could be really nice to have bulk edit capabilities there as well.

**Describe alternatives you've considered**
Manual actions

**Comment by valentijnscholten** [comment]
Do you mean the normal bulk actions like setting status, adding a note, etc. Or the actions more geared towards similar findings, i.e. mark as duplicate.

**Comment by Wadeck** [comment]
Both actually :) if I can bulk add a tag or bulk mark as duplicate, that could really help
