### ISSUE TITLE
Issue comments not synced to DefectDojo with a webhook event

### ISSUE THREAD

**Issue by tulsluper** [DefectDojo/django-DefectDojo#478]
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description

Webhook support enabled.
If comment an issue in Jira - no new notes in finding.

It's because webhook json for comment also have 'issue' key.

jira_link/views.py
```
if 'issue' in parsed.keys():
    # issue actions
else:
    # comment actions
```
Maybe better below ?
```
if 'issue' in parsed.keys():
    # issue actions
if 'comment' in parsed.keys():
    # comment actions
```

### Operating System 
CentOS 7.3

### Install

- [x] setup.bash
- [ ] docker

### Steps to Reproduce

Comment issue in Jira
Check notes in related finding in DefectDojo

**Comment by cbdnyu** [comment]
Hi all, @tulsluper did you ever find a resolution for this? We are having a similar issue.
