### ISSUE TITLE
Findings of Deleted product or engagement

### ISSUE THREAD

**Issue by tonnyhideyori** [DefectDojo/django-DefectDojo#4781]
I would like to know if it is possible to get findings of deleted engagements or products. I have searched online I have not found a solution to this issue.
Thanks

**Comment by valentijnscholten** [comment]
When a product or engagement is deleted, all findings inside are also deleted.

**Comment by tonnyhideyori** [comment]
Also, When stale appears take the day of discovery. So when searching for finding through API and set date=1, the stale findings will not appear. I suggest you should also add stales in date=1. Or is there another way to get vuln. discovered with in day which include stales

**Comment by valentijnscholten** [comment]
I don't understand the question, please come to slack.
