### ISSUE TITLE
500 on upload Nessus scan results 

### ISSUE THREAD

**Issue by whitespots** [DefectDojo/django-DefectDojo#4816]
Getting 500 when trying to upload Nessus scan results to: 
/product/14/import_scan_results
/engagement/123/import_scan_results

**Deployment method** 
- [Х] Docker

**Sample scan files** (optional)
Unavailable. 

**Console logs** (optional)
![image](https://user-images.githubusercontent.com/65983771/125622507-48f98727-4a4b-46d1-ad41-00e1a4ec2283.png)

**Additional context** (optional)
Latest DD ver, reinstalled.

**Comment by valentijnscholten** [comment]
Please provide steps to reproduce as this works fine in the demo environment.

**Comment by whitespots** [comment]
It was caused by 200mb report. Will try to generate the same without showing production data
