### ISSUE TITLE
SonarQube test connection button

### ISSUE THREAD

**Issue by mccatrina** [DefectDojo/django-DefectDojo#4817]
After the sonarqube api configuration in Tool Configuration I'm expecting  an error  or  a confirmation regarding the connection status with sonarqube.

It will be a  great idea to have a test connection button for sonarqube or an error message if the sonarqube project has not been imported

Home ->  Tool Configuration List  -> Edit Tool Configuration _> Submit

Green or Red status after setting sonarqube api import

**Comment by kiblik** [comment]
Fix prepared: https://github.com/DefectDojo/django-DefectDojo/pull/4676#issuecomment-884878178

**Comment by valentijnscholten** [comment]
merged into dev / 2.2.0
