### ISSUE TITLE
unique_id_from_tool has disappeared from the findings search filter

### ISSUE THREAD

**Issue by saldam72** [DefectDojo/django-DefectDojo#4822]
Hello Team,
After the upgrade form 1.15.1 to 2.0.3 is not possible anymore to filter records on "unique_id_from_tool". Is this by design or do we need another fix ?

Best,
Sal

**Comment by valentijnscholten** [comment]
I think this has dissapeared in the refactoring of the search filters. If there's a valid usecase to filter by these fields, we can add it back in.

**Comment by saldam72** [comment]
A valid use case could be integration with other systems ? A valid use case could be the search for the vulnerability using a code present in the report of the tool used for the analysis ?
