### ISSUE TITLE
API way to manage notifications

### ISSUE THREAD

**Issue by dsever** [DefectDojo/django-DefectDojo#4827]
**Is your feature request related to a problem? Please describe**

In current application users and admins can change/manage their notifications using GUI only. But we want to have control over it using API, so we can setup predefined notifications for different user types (during the user provisioning)

**Describe the solution you'd like**

Add API endpoint that will allow admin/user to specify what kind of notification would like to receive.  It can be just translation from GUI approach to API way of controlling.

**Comment by valentijnscholten** [comment]
merged into dev / 2.2.0
