### ISSUE TITLE
Netsparker scan parsing failure

### ISSUE THREAD

**Issue by blizko** [DefectDojo/django-DefectDojo#4843]
**Bug description**
Netsparker vulnerability export can have multiple CWE values or "" defined in a single entry, causing the parser to fail

https://github.com/DefectDojo/django-DefectDojo/blob/13cdb6a0f3905c8db3bd73d86b376eacfa97d5d7/dojo/tools/netsparker/parser.py#L53

**Steps to reproduce**
Import a Netsparker scan with multiple CWE field values
`
        "Cwe": "937, 1035",
 `

**Expected behavior**
Single value for CWE used

**Deployment method** *(select with an `X`)*
- [X] Docker
- [ ] Kubernetes
- [ ] GoDojo
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: 20.04.2 LTS
 - DefectDojo Commit Message: [2021-07-09 16:41:23 -0500] 24477ef3: Add release cadence to README (#4796) [ (HEAD -> master, origin/master, origin/HEAD)]

**Sample scan files**
[scan-report-name-vulnerabilities-15_07_2021 11_26 AM.txt](https://github.com/DefectDojo/django-DefectDojo/files/6846992/scan-report-name-vulnerabilities-15_07_2021.11_26.AM.txt)

**Comment by StefanFl** [comment]
Fixed with #4826
