### ISSUE TITLE
SonarQube scan error on import

### ISSUE THREAD

**Issue by marcin33** [DefectDojo/django-DefectDojo#4855]
**Bug description**
Got error on SonarQube import scan
`An exception error occurred during the report import:can only concatenate str (not "NoneType") to str`

**Steps to reproduce**
1. Run defectDojo in docker (master or dev branch)
2. Create project & engagement
3. Import scan results
4. Pick SonarQube Scan or SonarQube Scan detailed
5. Pick Environment
6. Pick file
7. Got error notification

**Expected behavior**
Should import scan from SonarQube

**Deployment method** *(select with an `X`)*
- [X] Docker
- [ ] Kubernetes
- [ ] GoDojo
- [ ] setup.bash / legacy-setup.bash

**Sample scan files** (optional)
[sonar-report_sonar-report.zip](https://github.com/DefectDojo/django-DefectDojo/files/6867310/sonar-report_sonar-report.zip)

**Console logs** (optional)
`uwsgi_1         | [22/Jul/2021 09:41:20] WARNING [dojo.importers.utils:28] Error in parser: can only concatenate str (not "NoneType") to str
uwsgi_1         | [22/Jul/2021 09:41:20] ERROR [dojo.engagement.views:616] can only concatenate str (not "NoneType") to str
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/app/./dojo/engagement/views.py", line 601, in import_scan_results
uwsgi_1         |     test, finding_count, closed_finding_count = importer.import_scan(scan, scan_type, engagement, user, environment, active=active, verified=verified, tags=tags,
uwsgi_1         |   File "/app/./dojo/importers/importer/importer.py", line 290, in import_scan
uwsgi_1         |     parsed_findings = importer_utils.parse_findings(scan, test, active, verified, scan_type)
uwsgi_1         |   File "/app/./dojo/importers/utils.py", line 16, in parse_findings
uwsgi_1         |     parsed_findings = parser.get_findings(scan, test)
uwsgi_1         |   File "/app/./dojo/tools/sonarqube/parser.py", line 37, in get_findings
uwsgi_1         |     return self.get_items(tree, test, self.mode)
uwsgi_1         |   File "/app/./dojo/tools/sonarqube/parser.py", line 67, in get_items
uwsgi_1         |     raise Exception("Parser ValueError: can't find a title or a mitigation for vulnerability of name " + vuln_rule_name)
uwsgi_1         | TypeError: can only concatenate str (not "NoneType") to str
`

**Comment by slicingmelon** [comment]
Hello, 

I confirm that ZAP scans cannot be uploaded either, pretty much the same issue. 
`An exception error occurred during the report import:can only concatenate str`

The issue starts somewhere here:
https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/engagement/views.py#L599

And it raises that exception:
https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/engagement/views.py#L615

Running version 2.1.0 release.

**Comment by slicingmelon** [comment]
Update: I've noticed that this happens only when scanning with zap-daily. I was able to upload a scan generated by zap-stable without any problems. It looks like the report generated by zap-daily is totally different.

**Comment by iainrawson** [comment]
For ZAP import, I've traced this to an issue parsing the <params> element - specifically I get an error when the params element has no text - i.e. <params></params>.  

I'm not sure why ZAP is generating empty params elements, but it looks like DefectDojo errors when concatenating the node.text to the description_detail in the following code in dojo\tools\zap\parser.py

```
                if node.tag == "param":
                    if node.text != "":
                        description_detail += "Parameter: " + node.text
```

My temporary workaround is to manually remove instances of <param></param> from the XML prior to import.
