### ISSUE TITLE
SPONSORING.md broken link, links to deprecated policy

### ISSUE THREAD

**Issue by ed-wp** [DefectDojo/django-DefectDojo#4899]
SPONSORING.md links to [Project Sponsorship (broken)](https://owasp.org/www-policy/operational/project-sponsorship) but 404s. 
The working link is [Project Sponsorship](https://owasp.org/www-policy/operational-historical/project-sponsorship), however, that page is deprecated.

Is the correct policy now the [Donations Policy](https://owasp.org/www-policy/operational/donations)?

Anyways, the SPONSORING.md should be updated to state where and how external entities can contribute financially.

**Comment by devGregA** [comment]
Hi @ed-wp I've put in a PR to remove the info as you are correct, it is out of date. I believe the link you also provided is also likely out of date as OWASP no longer maintains specific project funds.
