### ISSUE TITLE
Unable to import from Github vulnerability scan

### ISSUE THREAD

**Issue by vyastj** [DefectDojo/django-DefectDojo#4911]
**Bug description**
When I am trying to import a Github vulnerability scan using the template given at [https://defectdojo.github.io/django-DefectDojo/integrations/import/#github-vulnerability]. I am receiving the error `An exception error occurred during the report import:Expecting value: line 1 column 1 (char 0)`.

I did some digging on the internet and found that in some Ubuntu systems, python2.7 can't identify json even if it's a built-in function. Hence, I used the shebang `#!/usr/local/bin python3` to prioritise python3. But I am still getting the error.

**Steps to reproduce**
Steps to reproduce the behaviour:
1. Go to 'Products'
2. Click on 'Product name'
3. Click on 'Findings' dropdown
4. Click on 'Import Scan Results'
5. Select scan type as 'Github Vulnerability Scan'
6. Choose a report file to import

**Expected behaviour**
Issues should populate in Finding. Because when I run the same python script locally on a terminal. It gives me expected results

**Deployment method** *(select with an `X`)*
- [X] Docker
- [ ] Kubernetes
- [ ] GoDojo
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04.1]
 - DefectDojo Commit Message: [[2021-07-09 16:41:23 -0500] 24477ef3: Add release cadence to README (#4796) [ (HEAD -> master, origin/master, origin/HEAD)]

**Sample scan files** (optional)

```
#!/usr/bin/python3

import json
import requests

query = """
query getVulnerabilitiesByRepoAndOwner($name: String!, $owner: String!) {
  repository(name: $name, owner: $owner) {
    vulnerabilityAlerts(first: 100) {
      nodes {
        id
        createdAt
        securityVulnerability {
          severity
          package {
            name
            ecosystem
          }
          advisory {
            description
            summary
            identifiers {
              type
              value
            }
            references {
              url
            }
            cvss {
              vectorString
            }
          }
        }
        vulnerableManifestPath
      }
    }
  }
}
"""

token = '...' # generated from GitHub settings
header = {"Authorization": "Bearer " + token}


request = requests.post(url='https://api.github.com/graphql',
                        json={
                          "operationName": "getVulnerabilitiesByRepoAndOwner",
                          'query': query,
                          'variables': {
                            'name': '...',
                            'owner': '...'
                          }
                        },
                        headers=header)

result = request.json()
print(json.dumps(result, indent=2))
```

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

**Comment by StefanFl** [comment]
Hi @vyastj, what you provided under **Sample scan files** is not the result of a scan but a example for a shell script to retrieve results from GitHub. Please attach an actual example of a vulnerabilities scan of GitLab, which must be a JSON file.

**Comment by vyastj** [comment]
Hello @StefanFl, I realised what I was doing wrong. Thanks

**Comment by vyastj** [comment]
@StefanFl Now, when I import the following JSON in a file
```
{
  "data": {
    "repository": {
      "vulnerabilityAlerts": {
        "nodes": [
          {
            "securityVulnerability": {
              "severity": "LOW",
              "package": {
                "name": "braces",
                "ecosystem": "NPM"
              },
              "advisory": {
                "description": "Versions of `braces` prior to 2.3.1 are vulnerable to Regular Expression Denial of Service (ReDoS). Untrusted input may cause catastrophic backtracking while matching regular expressions. This can cause the application to be unresponsive leading to Denial of Service.\n\n\n## Recommendation\n\nUpgrade to version 2.3.1 or higher.",
                "summary": "Regular Expression Denial of Service in braces",
                "identifiers": [
                  {
                    "type": "GHSA",
                    "value": "GHSA-g95f-p29q-9xw4"
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}
```

I am getting the error: `An exception error occurred during the report import:'NoneType' object is not iterable`. I don’t see an empty field or an object having value None

**Comment by akitibala** [comment]
hi @vyastj ,please provide _**id**_ for every object in **nodes** list like this:
`{
  "data": {
    "repository": {
      "vulnerabilityAlerts": {
        "nodes": [
          { "id":1,
            "securityVulnerability": {
              "severity": "LOW",
              "package": {
                "name": "braces",
                "ecosystem": "NPM"
              },
              "advisory": {
                "description": "Versions of `braces` prior to 2.3.1 are vulnerable to Regular Expression Denial of Service (ReDoS). Untrusted input may cause catastrophic backtracking while matching regular expressions. This can cause the application to be unresponsive leading to Denial of Service.\n\n\n## Recommendation\n\nUpgrade to version 2.3.1 or higher.",
                "summary": "Regular Expression Denial of Service in braces",
                "identifiers": [
                  {
                    "type": "GHSA",
                    "value": "GHSA-g95f-p29q-9xw4"
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}`

Explanation :  Since Github Vulnerability scan is looking for id field at [line 35](https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/github_vulnerability/parser.py)

**Comment by akitibala** [comment]
Explanation :  
Since Github Vulnerability scan is looking for id field at [line 35](https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/github_vulnerability/parser.py)

**Comment by akitibala** [comment]
hi @StefanFl , i think we can close this issue since  invalid schema is provided . i guess we should provide schema validator which can prevent users from uploading in-valid schema.

**Comment by StefanFl** [comment]
The documentation at https://defectdojo.github.io/django-DefectDojo/integrations/import/#github-vulnerability is clear about mandatory attributes. Not all mandatory attributes where provided in the scan results. Although error messages could be improved, I will close the issue.

**Comment by vyastj** [comment]
I did add the missing mandatory field (id), after referencing the documentation. However, the same error `An exception error occurred during the report import:'NoneType' object is not iterable` is thrown.

**Comment by StefanFl** [comment]
Please provide the complete stacktrace from the log and/or the file with the scan result

**Comment by vyastj** [comment]
@StefanFl The complete scan result is quite long, hence  I have attached the zipped version of the `json results`. 

[Github-Results.json.zip](https://github.com/DefectDojo/django-DefectDojo/files/6998662/Github-Results.json.zip)

**Comment by StefanFl** [comment]
This report works fine with my 2.1.0 version:
![2021-08-17 11_41_57-](https://user-images.githubusercontent.com/2698502/129703141-64c9db90-dd63-4562-9b5c-e564c4df02fe.png)

**Comment by vyastj** [comment]
@StefanFl, Can you validate at your end if I am following the right steps to import Results. Also, are there any pre-requisite to import the results?

**Comment by StefanFl** [comment]
I imported the findings via the UI using the Github Vulnerability Scanner. How do you do it?

**Comment by vyastj** [comment]
Okay, I believe i am also following the same procedure which is:

* Go to 'Products'
* Click on 'Product name'
*  Click on 'Findings' dropdown
* Click on 'Import Scan Results'
* Select scan type as 'Github Vulnerability Scan'
* Choose a report file to import

**Comment by StefanFl** [comment]
This is exactly what I did. When you are on version 2.1.0 it should work for you as well. Please make sure you are really using the same file that you uploaded here.

**Comment by vyastj** [comment]
Thanks for the help @StefanFl and @akitibala.
