### ISSUE TITLE
uwsgi error

### ISSUE THREAD

**Issue by xsseng** [DefectDojo/django-DefectDojo#492]
uwsgi error: django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty." 

because migrating the settings.py dict.
need to change /django-DefectDojo/wsgi.py 
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "**dojo.settings**")
to
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "**dojo.settings.settings**")

**Comment by devGregA** [comment]
Hi @xsseng that makes sense. Great catch! Would you like to do the PR so you get the credit?
