### ISSUE TITLE
Endpoint host report is not showing active findings

### ISSUE THREAD

**Issue by masty1982** [DefectDojo/django-DefectDojo#4936]
**Bug description**
I have not been able to get working endpoint host report in version DefectDojo 2.1.0. I go to /endpoint/host and then select the host. It shows me active findings, which I currently have four findings for one host. From the upper right corner I select Report and /endpoint/<host_id>/report?host_view page is opened. Instead of showing these four active findings this page shows all findings related to the host. When I use filter to show Active=Yes and Verified=Yes it filters everything out and the list is empty. Another host has 32 active findings and using the filter gives two findings. So, I am not able to generate html report with active findings. Am I doing something wrong or what is the best way to get an html report for a vulnerable host?

**Steps to reproduce**
See above and screenshots

**Expected behavior**
Endpoint host report with active findings

**Deployment method** *(select with an `X`)*
- [X] Docker
- [ ] Kubernetes
- [ ] GoDojo
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Ubuntu 20.04
 - DefectDojo 2.1.0

**Screenshots** (optional)
Here are vulnerable hosts and then I click Imaginary-10 host, which shows 4 active findings:
![image](https://user-images.githubusercontent.com/74306109/129185039-0d8e447b-31fd-4ce1-8195-0e0c4f3940c9.png)
![image](https://user-images.githubusercontent.com/74306109/129185000-70471249-14e4-4ae0-a4e1-8b504c610c31.png)

The report shows more than four findings when the report page opens (102 findings):
![image](https://user-images.githubusercontent.com/74306109/129185123-a40fb8ec-3454-45a7-936d-2d46aff00b37.png)
![image](https://user-images.githubusercontent.com/74306109/129185087-569efc27-66b1-4a9a-bd07-26d6c4ed50da.png)

If I use filter to set Active and Verified, it shows only one finding. I was expecting four findings:
![image](https://user-images.githubusercontent.com/74306109/129185311-f77f32b9-b76f-41f2-8d63-d1e2ace4c5d2.png)
![image](https://user-images.githubusercontent.com/74306109/129185353-25d2bfe0-b804-49a5-bc6c-10404ccb6485.png)

**Comment by kiblik** [comment]
I can work on it

**Comment by kiblik** [comment]
Fixed in #4942

**Comment by valentijnscholten** [comment]
merged into dev / 2.2.0
