### ISSUE TITLE
slack notification bug to find user profile

### ISSUE THREAD

**Issue by hackthesoul** [DefectDojo/django-DefectDojo#4937]
**Expected behavior**
In my case, our company workspace has a lot of employees. That means user list has limitation for showing.
so https://slack.com/api/users.list url, it does not work without cursor parameter.

![image](https://user-images.githubusercontent.com/59822000/129232826-fe31f309-1295-4b98-9a97-a4d5d0320235.png)

I suggest that it should be changed as below

```
res = requests.request(
        method='POST',
        url='https://slack.com/api/users.lookupByEmail',
        data={'token': get_system_setting('slack_token'), 'email': user_email})

users = json.loads(res.text)

    slack_user_is_found = False
    if users:
        if 'error' in users:
            logger.error("Slack is complaining. See error message below.")
            logger.error(users)
            raise RuntimeError('Error getting user list from Slack: ' + res.text)
        else:
            for member in users["user"]:
                if "email" in member["profile"]:
                    if user_email == member["profile"]["email"]:
                        if "id" in member:
                            user_id = member["id"]
                            logger.debug("Slack user ID is {}".format(user_id))
                            slack_user_is_found = True
                            break
                    else:
                        logger.warn("A user with email {} could not be found in this Slack workspace.".format(user_email))

            if not slack_user_is_found:
                logger.warn("The Slack user was not found.")

    return user_id        
```

**Deployment method** *(select with an `X`)*
- [X] Docker
- [ ] Kubernetes
- [ ] GoDojo
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Catalina 10.15.7
 - DefectDojo Commit Message: [use `git show -s --format="[%ci] %h: %s [%d]"`]

**Sample scan files** (optional)
If applicable, add sample scan files to help reproduce your problem.

**Screenshots** (optional)

**Console logs** (optional)
If applicable, add console logs to help explain your problem.

**Additional context** (optional)

**Comment by StefanFl** [comment]
@hackthesoul Please provide a bug description and more precise steps to reproduce the bug. Currently, I cannot see what the actual problem is.

**Comment by valentijnscholten** [comment]
If you have a fix, you can also create a PR which we can review/merge.

**Comment by whitespots** [comment]
![image](https://user-images.githubusercontent.com/65983771/133103053-c5a8b412-12d3-4259-ade8-713171370313.png)
Guys, our clients meet same problem with slack notifications.
Strange thing is that on fresh installation it did not appear, but exists after update. Maybe migrations went wrong in the init service

+all scopes on Slack side are set correctly
![image](https://user-images.githubusercontent.com/65983771/133103435-84f7be79-89fc-43a4-8fbf-5841caa4b74f.png)

**Comment by whitespots** [comment]
@StefanFl @valentijnscholten 
hope you will find such details helpful for solving this issue

**Comment by valentijnscholten** [comment]
A manual compare shows the suggestion is to replace

```
    res = requests.request(
        method='POST',
        url='https://slack.com/api/users.list',
        data={'token': get_system_setting('slack_token')})
```

with

```
res = requests.request(
        method='POST',
        url='https://slack.com/api/users.lookupByEmail',
        data={'token': get_system_setting('slack_token'), 'email': user_email})
```

The existing code retrieves the first page of the user list, which can result in users not being found if there are too many. The new code just tries to find the exact user needed.

**Comment by valentijnscholten** [comment]
Can someone test https://github.com/DefectDojo/django-DefectDojo/pull/5091 @hackthesoul @whitespots
