### ISSUE TITLE
High memory consumption in deletion view and long bulk delete duration (general scalability issues)

### ISSUE THREAD

**Issue by EndPositive** [DefectDojo/django-DefectDojo#4949]
**Bug description**
In internal testing, we encountered scalability issues in cases where there are a large number (> 4000) of findings and endpoints imported in a product.

Part of this issue was initially brought up in #964, however it was not followed through.

**Steps to reproduce**
Import a very large set of findings.

* Request the product deletion view, the `NestedObjects` collector loads all cascading objects into memory, resulting in the Kubernetes pod being evicted due to its resource limits being reached.
* Run bulk delete on a large subset of the findings in a product results in extremely long page loading times (often resulting in a nginx timeout).

**Discussion**
Increasing the pod limits and nginx timeouts is really not scalable (you might need to double memory limits again for > 10000 findings).

We use the Helm chart in combination with a HPA, which does not work good enough for sudden memory peaks in a single pod. VPA's don't work in this case as they require pod restarts.

**Expected behavior**
The user is not aware of any resource-heavy operations. The product deletion view is disabled for large sets (may be useless anyway for that much information). Bulk deletions are done asynchronously. Maybe it would even be possible to delay the deletion of objects and only mark them as deleted initially. Maybe we should schedule specific celery workers (with large memory requests/limits) for these operations.

In any case, I believe the project should add (functional) test cases for such large-scale operations.

**Deployment method**
- [ ] Docker
- [x] Kubernetes
- [ ] GoDojo
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Kubernetes version 1.21
 - DefectDojo version 2.1.0

**Comment by ed-wp** [comment]
+1. We have run into serious scaling issues related to deletion. We accidentally imported a bunch of duplicate findings and it took us a few hours to clear them out in small chunks since any larger deletion requests were causing 500s. I don't think every field of every dependency should be brought up in the deletion view, and it's also slow (5000+ items can take 30-60+ seconds to load). I think if you only pull the counts for the deletion overview instead it'll scale much better.
