### ISSUE TITLE
Unable to import TFSec Scans

### ISSUE THREAD

**Issue by nu-vi** [DefectDojo/django-DefectDojo#4951]
When importing TFSec Scans DefectDojo returns "An exception error occurred during the report import:'NoneType' object has no attribute 'get'"

**Comment by StefanFl** [comment]
@nu-vi Please provide a sample report that produces the bug.

**Comment by nu-vi** [comment]
Here you go.

[tf-error-output.json.zip](https://github.com/DefectDojo/django-DefectDojo/files/7013053/tf-error-output.json.zip)

**Comment by AshutoshBhardwaj2** [comment]
@nu-vi  May I know the process of importing tfsec report, As I'm working on Tekton pipeline.
