### ISSUE TITLE
docker-compose build failed

### ISSUE THREAD

**Issue by ganesh2183** [DefectDojo/django-DefectDojo#4956]
Trying to install DefectDojo in VM Virtual box Debian 10.10 (Guest OS)
Docker version: 20.10.8
Docker-compose version: 1.29.2

Getting the error when I run 'docker-compose build'

ERROR: Service 'uwsgi' failed to build : Build failed

How to fix this issue.

![1629371236796534177495551676958](https://user-images.githubusercontent.com/41476297/130058602-16daf307-091f-4bc0-9514-adff2aea3628.jpg)

**Comment by StefanFl** [comment]
Your machine seems to have no internet connection, which is needed to download packages.

**Comment by ganesh2183** [comment]
It downloaded other dependency packages, only this list of packages getting failed.

Also I m running behind corporate firewall, is there something it could be reason for this.

**Comment by StefanFl** [comment]
It is definitely a network issue. You have to find out, why the docker-compose process cannot get access to debian.org. Your corporate firewall might be a reason. There is nothing we can do to help you here.

**Comment by ganesh2183** [comment]
Thanks. It is working now after setting up proxy in docker file.
