### ISSUE TITLE
Forbidden 403 Error Page - CSRF Verification failed

### ISSUE THREAD

**Issue by ganesh2183** [DefectDojo/django-DefectDojo#4967]
Docker version: 20.10.8
Docker-compose version: 1.29.2

Running DefectDojo in VM Virtual box Debian 10.10 (Guest OS)

- Go to 'Products'
- Create a Product
- Go to 'Findings' tab and select 'Import Scan Results'
- Try importing any sort of scan - Ex: MobSF scan results using json file
- Click on Import and see this:

Getting 403 Forbidden - CSRF verification failed. Request aborted.

![130278379-a45701cd-1dd8-443e-b3cb-32ab19455ad2](https://user-images.githubusercontent.com/41476297/130342421-7020d8c0-9ebb-4dae-8df4-6e59d0ddb727.jpg)

Why? How to fix this error ??

**Comment by StefanFl** [comment]
@ganesh2183 I have never seen this behaviour. Seems to be a problem with your configuration.

**Comment by ganesh2183** [comment]
Ok. But I have not done any changes to configuration.

**Comment by ganesh2183** [comment]
I see same issue reported before, please refer https://github.com/DefectDojo/django-DefectDojo/issues/2760

Actually what is fix for this issue to resolve

**Comment by ganesh2183** [comment]
@StefanFl 

I see error message in log,

Warning [django.security.csrf:224] Forbidden (CSRF token missing or incorrect)

How to fix this error

**Comment by StefanFl** [comment]
Sorry @ganesh2183, there must be something wrong with your configuration. But since I have never seen this behaviour, I have no clue what causes the problem.

**Comment by ganesh2183** [comment]
@StefanFl Hi..When I try to import sample scan files (burp, checkmarx) from https://github.com/DefectDojo/sample-scan-files, it is working fine without any issues. But when I try to import my scan files it is giving CSRF Verification failed error page.

Why? Any reason for this.

**Comment by valentijnscholten** [comment]
As explained multiple times now we don't know what this issue is. We almost never see it. Maybe it's a bug in Django. Defect Dojo doesn't implement CSRF itself, but relies on Django.

**Comment by ganesh2183** [comment]
Finally, it worked. The issue was with linux file permission, after changing access permission to 'read and write'. Now I m able to import MobSF scan files without any issues.

Thanks for your response.

**Comment by valentijnscholten** [comment]
@ganesh2183 which file permissions? I assume of the whole /dojo or /app folder?

**Comment by ganesh2183** [comment]
I mean MobSF scan file permission, which I copied from another system.
