### ISSUE TITLE
SonarQube Imports Failing with Opaque Message

### ISSUE THREAD

**Issue by sempervictus** [DefectDojo/django-DefectDojo#4973]
**Steps to reproduce**
1. Configure http-based API to SQ using token auth (same token as used to scan the codebase)
2. Attempt to import data from the scanner 
3. Get error message in web UI stating:
```
Other | SonarQube API import issue | Expecting value: line 1 column 1 (char 0)
```
4. Experience confusion

**Expected behavior**
Imports work

**Deployment method** *(select with an `X`)*
- [X] Docker
- [ ] Kubernetes
- [ ] GoDojo
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Arch Linux
 - DefectDojo Commit Message: current containers as of 5m ago

**Comment by StefanFl** [comment]
Hello @sempervictus, please provide the logs with the error messages and stacktrace.
