### ISSUE TITLE
APIv2: Add feature of linking manually created JIRA tasks to finding

### ISSUE THREAD

**Issue by stateandprove** [DefectDojo/django-DefectDojo#5006]
**Is your feature request related to a problem? Please describe**
This feature is not related to any problem directly, however, it may add useful functionalities.

**Describe the solution you'd like**
Using put or patch requests to /api/v2/findings/{id}, I'd like to link manually created JIRA task to some finding, that is in "Active, Verified" state.  

**Describe alternatives you've considered**
I tried to do the following thing in present API, but no changes were applied.

**Additional context**
n/a

**Comment by sarosbacz** [comment]
+ Need the same functionality

**Comment by whitespots** [comment]
We need this for our clients

**Comment by devkekops** [comment]
+1

**Comment by BlancLoup** [comment]
+1

**Comment by valentijnscholten** [comment]
In theory it's possible via `api/v2/jira_finding_mappings` but I agree an easier way would be helpful. It can be done via the UI already, but not the API.

**Comment by W0uldYk1ndlY** [comment]
Nice feature

**Comment by sarosbacz** [comment]
@valentijnscholten 
Any suggestions on if this feature will be added?
