### ISSUE TITLE
navbar covering page

### ISSUE THREAD

**Issue by t3h2mas** [DefectDojo/django-DefectDojo#501]
Please use the following template when submitting issues:

### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description
The height of the navbar is covering part of the web application

### Operating System 
Mac 10.13.3

### Browser
Chrome v64
### Install

- [ ] setup.bash
- [x] docker

### Steps to Reproduce
Visit localhost:8000

### Screenshots (optional)
![defectdojo](https://user-images.githubusercontent.com/598146/37294559-a8aaba3e-25db-11e8-9737-c158c5ac4a02.png)

**Comment by devGregA** [comment]
Hi @t3h2mas I wasn't able to reproduce this, could you please share your ./setup.bash output?

**Comment by t3h2mas** [comment]
@devGregA Would you like me to run that inside the container?

**Comment by devGregA** [comment]
@t3h2mas didn't catch that this was docker. I have a meeting tomorrow to review PRs will discuss it with the team then.

**Comment by t3h2mas** [comment]
It looks like 

* dojo.css
* logo.png
* chop.png
* index.js

fail to load. After viewing previous issues, I tried testing the yarn install and it worked fine

**Comment by t3h2mas** [comment]
Ran into this again, with the docker one liner 

`docker run -it -p 8000:8000 appsecpipeline/django-defectdojo bash -c "export LOAD_SAMPLE_DATA=True && bash /django-DefectDojo/docker/docker-startup.bash"`

from https://defectdojo.readthedocs.io/en/latest/getting-started.html#docker-local-install

**Comment by t3h2mas** [comment]
In case anyone encounters this, I removed all of my docker images that had to deal with Defect Dojo, and did a `docker pull appsecpipeline/django-defectdojo` before running the one liner again.
