### ISSUE TITLE
Import of semgrep files never stop to add finding

### ISSUE THREAD

**Issue by Greenmouse94** [DefectDojo/django-DefectDojo#5012]
Hello !

Release : 2.1.0 DEV

**Bug description**
When I try to import semgrep files (with 169 findings), the import  function never stop and continue to add and add finding, at the end I have 2000 new findings.

**Steps to reproduce**
1. Go to Products > All products > "My Product" > Findings > Import scan results
2. Everything on default value except:
- Scan type : SEMGREP Json report
- Environment : Development
- Endpoints : https://myendpoint.com
- Choose report file : I select my file (257.9KB)
- Click on import

**Expected behavior**
Import successful.

**Deployment method** *(select with an `X`)*
- [ ] Docker
- [ ] Kubernetes
- [x] GoDojo
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 20.04]
 - DefectDojo Commit Message: [use `git show -s --format="[%ci] %h: %s [%d]"`]  ???

**Sample scan files** (optional)
/

**Screenshots** (optional)
/

**Console logs** (optional)
/

**Additional context** (optional)
/

Thank you.

**Comment by damiencarol** [comment]
@Greenmouse94 is it possible to have the report (even obfuscated)?

**Comment by Greenmouse94** [comment]
Hello, here is the file.

Ah yes maybe it is the problem.

[SEMGREP-typescript.txt](https://github.com/DefectDojo/django-DefectDojo/files/7084869/SEMGREP-typescript.txt)

**Comment by Greenmouse94** [comment]
And when I wait too much :
```
This page isn’t working
example.com didn’t send any data.
ERR_EMPTY_RESPONSE
```

I can also see that there is a lot of double, the same finding with the same file, with the same line number etc.

**Comment by damiencarol** [comment]
Working on it.

**Comment by damiencarol** [comment]
I'm able to import the file with 169 findings in version `2.1.0`
Also made some unit tests on my local branch to test the data but it seems ok

**Comment by damiencarol** [comment]
Closing this one as it seems configuration challenge :)
