### ISSUE TITLE
OAuth2/SAML2 Documentation tells you to hardcode credentials into settings.dist.py instead of recommending Environmental Variables

### ISSUE THREAD

**Issue by ed-wp** [DefectDojo/django-DefectDojo#5033]
[OAuth2/SAML2 Documentation](https://defectdojo.github.io/django-DefectDojo/integrations/social-authentication/)

`dojo/settings/settings.dist.py` is where Environmental variables and their defaults are stored. If the environmental variables is not set in the runtime environment of the application, then the default is used.

**Problem**
Hard-coding secret values can lead to embedded secrets if they build a docker image with them. Recommending users to `edit the dojo/settings/settings.dist.py file and edit/replace the following information` is poor security practice and can lead to users inadvertently exposing their secrets to others if they upload their docker image to a non-private repository.

**Reproduction**
1. Setup OAuth2/SAML2 per the [documentation](https://defectdojo.github.io/django-DefectDojo/integrations/social-authentication/)
1. Docker compose / build
1. Docker push to docker.io
1. Secrets are now accessible by all on docker.io

**Fix**
These values should be set within the runtime environment and using environmental variables. Instead of recommending to edit the defaults to a hard-coded secret, it should recommend to use environmental variables.

[kubernetes](https://kubernetes.io/docs/concepts/configuration/secret/), [AWS](https://docs.aws.amazon.com/AmazonECS/latest/userguide/specifying-sensitive-data-secrets.html), [GCP](https://cloud.google.com/run/docs/configuring/secrets), [Azure](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-environment-variables#secure-values), etc all allow you to inject secrets as environmental variables. This should be the default and recommend way of setting these secret values.

If just using docker, then recommend storing them in a safe place, like a secrets manager or password manager: 
Vault:
`docker run -e  DD_SOCIAL_AUTH_...="$(vault read ...)"`
LastPass:
`docker run -e  DD_SOCIAL_AUTH_...="$(lpass show ...)"`

**Comment by StefanFl** [comment]
Thank you @ed-wp for your observation, you are absolutely right. I will update this page and https://defectdojo.github.io/django-DefectDojo/getting_started/configuration/ as well.
