### ISSUE TITLE
Launch Scan Feature in defect dojo

### ISSUE THREAD

**Issue by MHarsh24** [DefectDojo/django-DefectDojo#5037]
Kindly add the launch scan feature in defect dojo, so that the supported tools can be used to assess the application for vulnerability by using the defect dojo application in one place instead of going to separate application and invoke the scan and then import the scan from each tool.

**Comment by StefanFl** [comment]
Every tool has it's own installation procedure, using different runtime dependencies like Python, NodeJS, Go, Docker and others. Installing and launching the scan tools would add a huge layer of complexity to DefectDojo. There are other projects like secureCodeBox (https://docs.securecodebox.io/) which address your needs and are integrated with DefectDojo.

**Comment by MHarsh24** [comment]
Can you possibly provide me the DefectDojo and Securecodebox API integration Document?

**Comment by StefanFl** [comment]
It's in the documentation of secureCodeBox: https://docs.securecodebox.io/docs/hooks/defectdojo
