### ISSUE TITLE
Notification option not visible in DD 1.15.0(release-mode)

### ISSUE THREAD

**Issue by sathish-ather** [DefectDojo/django-DefectDojo#5046]
Hello Folks,

We are not able to see the notification option to send out the alerts on slack,email,etc.

Is it known issue or not implemented in v1.15.0 ?

I referred this link https://defectdojo.github.io/django-DefectDojo/integrations/notifications/ but i am not able to find this option.

Please help us out.

**Comment by StefanFl** [comment]
Hello @sathish-ather, you find the option to manage notifications under **Configuration / Notifications** in the main menu on the left side. Superusers can manage notification on system and personal scope, other users can manage only their personal notifications.

**Comment by sathish-ather** [comment]
Hey,

Yes.. After the docker containers reboot, i am able to see the notification option under configuration.

Thanks u @StefanFl
