### ISSUE TITLE
Implement a Grafeas client

### ISSUE THREAD

**Issue by maennel** [DefectDojo/django-DefectDojo#505]
### Issue Type 
- [ ] Bug
- [x] Enhancement

### Description

Grafeas is a standard interface pushed by Google and JFrog which is used to transmit artifact metadata to annotate actual software artifacts. 

More information at:
https://github.com/grafeas/grafeas/blob/master/README.md

I suggest to implement a Grafeas client to be able to feed vulnerabilities managed in DefectDojo to a Grafeas server in order to enrich artifact metadata.

Grafeas page: https://grafeas.io/
Grafeas webinar: https://www.youtube.com/watch?v=03Ha6d_1Evk
Clair/Grafeas discussion: https://github.com/coreos/clair/issues/493
Grafeas sources: https://github.com/grafeas/grafeas
Grafeas sample client (in python): https://github.com/grafeas/client-python

**Comment by devGregA** [comment]
@maennel, archiving this one for now. In terms of integration for this year we are focused on improving JIRA integration and adding Rally support.
