### ISSUE TITLE
Google sheet Sync error 

### ISSUE THREAD

**Issue by MHarsh24** [DefectDojo/django-DefectDojo#5053]
Hello 

In Defect Dojo, I've done Google Sheets synchronization. When I create a file in my drive, everything works well, but when I try to sync that file, it gives me an error.

Error:   ["'' value has an invalid format. It must be in YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ] format."]

**Comment by valentijnscholten** [comment]
Where are you seeing this error, please provide details as requested in the bug report template.

**Comment by MHarsh24** [comment]
Hello, 

When I try to sync a document with my drive, I get the following error.

Kindly find the attached Snapshot of the error.

![image](https://user-images.githubusercontent.com/59463079/132485672-fa77261e-54b8-466a-b0e1-a0689a06d139.png)
 
Deployment method -- Docker

**Comment by StefanFl** [comment]
On which version are you? There has been a bug with empty values in Google sheets that have been fixed with 2.2.0. If you are on an older version, please upgrade to 2.2.1

**Comment by valentijnscholten** [comment]
@MHarsh24 what was the situation, upgrading?
