### ISSUE TITLE
Scan import error

### ISSUE THREAD

**Issue by Greenmouse94** [DefectDojo/django-DefectDojo#5058]
Hello,

I have an issue when I'm trying to import scan with `'api/v2/import-scan/'`

I tried a LOT of things, but I'm still not able to import a scan.

Here is my code : 
```
url = url + 'api/v2/import-scan/'
headers = {'Authorization': 'Token xxxxxxxxxxxxxxxxxxxxxxxxxx'}

now = datetime.datetime.now()
date = now.strftime("%Y-%m-%d")

dict_ = {
    "scan_type": scan_type,
    "file": file,
    "engagement": 19
}

multipart_form_data = {
    'scan_date': '2021-09-08',
    'file': (file, open(file, 'rb'), 'text/json'),
    "scan_type": "Semgrep JSON Report",
    "engagement": 19
}

print(dict_)
r = requests.post(url, headers=headers, files=multipart_form_data)
print(r.status_code)
```

I got the error : 500 Internal Server

Can you help me ?
Thank you in advance.

**Comment by valentijnscholten** [comment]
Can you provide more info as requested in the big report template?

**Comment by Greenmouse94** [comment]
Hello, 

Sorry completely forgot.

**Slack us first!**
The easiest and fastest way to help you is via Slack. There's a free and easy signup to join our #defectdojo channel in the OWASP Slack workspace: [Get Access.](https://owasp-slack.herokuapp.com/)
If you're confident you've found a bug, or are allergic to Slack, you can submit an issue anyway.

**Be informative**
I have an issue when I try to import scan with 'api/v2/import-scan/' via a Python script.
I tried a LOT of things, but I'm still not able to import a scan.

**Bug description**
I got the error : 500 Internal Server as a status code.
```
url = url + 'api/v2/import-scan/'
headers = {'Authorization': 'Token xxxxxxxxxxxxxxxxxxxxxxxxxx'}

now = datetime.datetime.now()
date = now.strftime("%Y-%m-%d")

dict_ = {
    "scan_type": scan_type,
    "file": file,
    "engagement": 19
}

multipart_form_data = {
    'scan_date': '2021-09-08',
    'file': (file, open(file, 'rb'), 'text/json'),
    "scan_type": "Semgrep JSON Report",
    "engagement": 19
}

print(dict_)
r = requests.post(url, headers=headers, files=multipart_form_data)
print(r.status_code)
```

**Steps to reproduce**
Steps to reproduce the behavior:


**Expected behavior**
Status code : 200

**Deployment method** *(select with an `X`)*
- [ ] Docker
- [ ] Kubernetes
- [X ] GoDojo
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Kali
 - DefectDojo Commit Message: /

**Sample scan files** (optional)
/

**Screenshots** (optional)
/

**Console logs** (optional)
/

**Additional context** (optional)
/

**Comment by valentijnscholten** [comment]
What's in the logs?

**Comment by Greenmouse94** [comment]
2.1.0 
In the log : 
x.x.x.x- - [08/Sep/2021:20:07:36 +0200] "POST /api/v2/import-scan/ HTTP/1.1" 500 216848 "-" "python-requests/2.25.1"

**Comment by valentijnscholten** [comment]
Can you try with 2.2.1? We fixed the logging of errors so there should be details in the logs.

**Comment by Greenmouse94** [comment]
Yes I can, but I'm not sure how to do to upgrade to 2.1.1.

**Comment by StefanFl** [comment]
I think you need to have the fields like `scan_type` and `engagement` in a separate dictionary which is given to the request as `data`. So something like: 

```
payload = {
    "scan_type": "Semgrep JSON Report",
    "engagement": 19
}

multipart_form_data = {
    'file': (file, open(file, 'rb'), 'application/json'),
}

r = requests.post(url, headers=headers, data=payload, files=multipart_form_data)
```

_Not having it tested in detail, more a sketch._

**Comment by Greenmouse94** [comment]
Hello @StefanFl ,

Thank you very much for your reply, it works now.

Best regards.
