### ISSUE TITLE
404 when attempting to 'promote' or 'delete' a 'potential finding'

### ISSUE THREAD

**Issue by t51** [DefectDojo/django-DefectDojo#5075]
Hi All,

Running the Release Mode 2.2.0 deployed with Docker-Compose.

Experiencing a 404 when trying to promote or delete a potential finding under a test.

1. Open an active Test (Product > Engagement > Test)
2. Add Potential Findings using the TextField 'Add a potential finding...' and click the button '+ Add Potential Finding'
3. Click the button 'Promote To Finding' or 'Delete' under actions for the Potential Finding created in step 2.
4. Page returns a 404 Not Found

Expecting the Promote to Findings form to be loaded.

Logs are showing:
[10/Sep/2021 03:21:52] WARNING [django.request:224] Not Found: /stub_finding/40/promote                                                         
WARNING:django.request:Not Found: /stub_finding/40/promote  

Reviewed the finding/urls.py and sighted a match however it doesn't seem to be matching. If I copied both Promote and Delete patterns above the Add, the request does work but with a delay. 

Screenshot of the modified finding/urls.py pattern. (copied promote and delete above the add pattern)
![image](https://user-images.githubusercontent.com/10723898/132794905-4f69cbd2-7346-4f6c-9e95-8dc4e432c73d.png)

**Comment by valentijnscholten** [comment]
In the latest dev I can't even add a potential finding, the `add` already gives a 404 for me.

**Comment by valentijnscholten** [comment]
Maybe we should add an integration test and also move to `path` based url routing.
https://stackoverflow.com/questions/47947673/is-it-better-to-use-path-or-url-in-urls-py-for-django-2-0

**Comment by StefanFl** [comment]
I take it

**Comment by valentijnscholten** [comment]
fixed in dev / 2.3.0

**Comment by t51** [comment]
Thank you
