### ISSUE TITLE
Calendar isn't working anymore since 2.2.0

### ISSUE THREAD

**Issue by StefanFl** [DefectDojo/django-DefectDojo#5079]
**Bug description**
The calendar isn't working anymore. You cannot choose the type (Engagement or Test) and so no calendar is shown

**Steps to reproduce**
1. Go to 'Calendar'
2. Click on 'Select an option' in the first box
3. No selection appears
4. Click on 'Apply'
5. No calendar is shown

**Expected behavior**
In the first box you should be able to select between Engagement and Test and a calender should be shown.

**Deployment method** *(select with an `X`)*
- [x] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - DefectDojo version: 2.2.0

**Screenshots**
![2021-09-10 17_27_20-Engagement Calendar _ DefectDojo](https://user-images.githubusercontent.com/2698502/132878983-34f489e9-2d2f-4fb1-9715-eac3d55270c1.png)

**Comment by StefanFl** [comment]
I have the feeling it is a side effect of #4766 and the JavaScript in that template. @kiblik can you have a look please?

**Comment by kiblik** [comment]
@valentijnscholten, I wanted to look at it but I see already did it.

**Comment by valentijnscholten** [comment]
fixed in dev / 2.3.0
