### ISSUE TITLE
Unable to deploy DefectDojo latest version

### ISSUE THREAD

**Issue by Akansha1804** [DefectDojo/django-DefectDojo#5080]
I am trying to use DefectDojo version 2.2.1 along with RabbitMQ 6.16.0. However, my rabbitmq pod never starts and the Readiness and Liveness probe keeps failing.

Also the django-deployment pod stucks at uwsgi container. The container does not come up.

**Comment by valentijnscholten** [comment]
please provide the required info as per the bug report template, i.e. logs.

**Comment by valentijnscholten** [comment]
closed as another ticket has been opened.
