### ISSUE TITLE
Unable to deploy DefectDojo version 2.0.0/2.2.x

### ISSUE THREAD

**Issue by Akansha1804** [DefectDojo/django-DefectDojo#5083]
I am trying to deploy DefectDojo latest version 2.2.1. 
I even tried versions like 2.2.0 and 2.0.0, but I always have the below error while deploying DefectDojo.

The logs of `defect-dojo-defectdojo-django` pod are something like this:

```
ERROR:django.request:Internal Server Error: /login
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "defectdojo"
```

**Comment by valentijnscholten** [comment]
Which of your two tickets do you want to progress?
Did you follow the steps fromhttps://github.com/DefectDojo/django-DefectDojo/blob/master/KUBERNETES.md to create the necessary secrets?

**Comment by Akansha1804** [comment]
> Which of your two tickets do you want to progress?
> Did you follow the steps fromhttps://github.com/DefectDojo/django-DefectDojo/blob/master/KUBERNETES.md to create the necessary secrets?

Hi, I want to keep this issue, the previous one is resolved for now.

And yeah, I have created all the necessary secrets except for Redis and MySQL as I am using RabbitMQ and PostgreSQL.

**Comment by Akansha1804** [comment]
I did few customizations in my helm chart, but then followed the official one. After doing that I was really wierd logs of nginx container in django pod.

<img width="949" alt="nginx_logs" src="https://user-images.githubusercontent.com/90467476/132953117-f6b7e1e0-3098-4018-9885-c5fb27f73500.PNG">

**Comment by Akansha1804** [comment]
The above nginx pod error is fine, but still I have 500 Server error while accessing Defect Dojo URL.

```
1 - [11/Sep/2021:16:34:38 +0000] "GET / HTTP/1.1" 302 0 "https://login.microsoftonline.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36" "122.161.53.213, 10.130.8.23"
127.0.0.1 - [11/Sep/2021:16:34:38 +0000] "GET /login?next=/ HTTP/1.1" 500 145 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36" "122.161.53.213, 10.130.8.23"
127.0.0.1 - [11/Sep/2021:16:34:39 +0000] "GET /favicon.ico HTTP/1.1" 302 0 "https://defect-dojo-url/login?next=/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36" "122.161.53.213, 10.130.8.23"
127.0.0.1 - [11/Sep/2021:16:34:39 +0000] "GET /login?next=/favicon.ico HTTP/1.1" 500 145 "https://defect-dojo-url/login?next=/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36" "122.161.53.213, 10.130.8.23"
```

**Comment by Akansha1804** [comment]
Here is the error message of `uwsgi` pod, same as before

`django.db.utils.OperationalError: FATAL:  password authentication failed for user "defectdojo"`

**Comment by parker3-peter3** [comment]
Any update on this ?
