### ISSUE TITLE
Re-Upload Scan error

### ISSUE THREAD

**Issue by viniciusnavarro** [DefectDojo/django-DefectDojo#5102]
**Slack us first!**
I spoke to Chris Fort on slack he told me to open an issue

**Bug description**
 When performing the reimport-scan of a Generic Findings Import, the error by the GUI is " An exception error occurred during the report import:name 'ValidationError' is not defined ".

Chris Fort pointed this out to me as the error:
>django.core.exceptions.ValidationError: ['Host must not be empty']

 Performing the Generic Findings import-scan using a .csv file works normally, with reimpot-scan it is not working, I am using the same .csv file as the import-scan.

Using the API the same exception happens.
**Steps to reproduce**
1. Import the file with Import-scan using Generic Findings Import
2. Re-import the same file using ReuploadScan.

**Expected behavior**
Run the Re-Upload Scan without errors

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Ubuntu 20.04
 - DefectDojo version (see footer) or commit message: 2.2.1

**Additional context** (optional)
 [2021-08-31 12:37:55 -0500] 00b4257: Merge pull request Release: Merge release into master from: release/2.2.0 #5014 from DefectDojo/release/2.2.0 [ (HEAD -> master, tag: 2.2.0, origin/master, origin/HEAD)]

***LOG***
[log.txt](https://github.com/DefectDojo/django-DefectDojo/files/7164843/log.txt)

https://pastebin.com/FH0GLHSc

**Comment by damiencarol** [comment]
I can take this one

**Comment by StefanFl** [comment]
The problem with the missing declaration of `ValidationError` has already solved with #4962

**Comment by damiencarol** [comment]
Ah! That's why I can't found it on dev :D

**Comment by damiencarol** [comment]
Fixed in dev by #4962
