### ISSUE TITLE
Plugin for Detectify 

### ISSUE THREAD

**Issue by nisarg0712** [DefectDojo/django-DefectDojo#5106]
Hello Everyone,

Just want to check if we have any plugin for Detectify to fetch report from Detectify to DefectDojo like Qualys or BurpeSuite.

Let me know if we have any.

**Comment by valentijnscholten** [comment]
If you just want to ask a question please come to our slack channel. Or in these case check the list of parsers in the docs: https://defectdojo.github.io/django-DefectDojo/integrations/import/ or the demo instance or in your own instance.

**Comment by damiencarol** [comment]
It seems that Detectify is an only service. So only API extract I think.
ref: https://developer.detectify.com/?_gl=1*8jxidj*_ga*NDAwMDU3NjA2LjE2MzE3MjQxNTQ.*_ga_F9HDKDJVKN*MTYzMTcyNDE1My4xLjEuMTYzMTcyNDE3NS4w*_fplc*NUpaV0lCNzFydXI5RW9NRW5BSmNkU1RHcG84QWxydzhpRzQ3VVQ1MFRjd2FZYk1PTnklMkJzRmFqVGYyZk5IeGUzZHRhb3dFYUpSUGR1aDlEYUdRdEtTTUFBaTNjMXZpNHBKYWklMkJnJTJGNGNyVVUxMEIzcTQwJTJGdmFMaTUyQyUyRllwdyUzRCUzRA..#operation/singleReport

**Comment by nisarg0712** [comment]
> If you just want to ask a question please come to our slack channel. Or in this case check the list of parsers in the docs: https://defectdojo.github.io/django-DefectDojo/integrations/import/ or the demo instance or in your own instance.
> 
> We can leave this open as feature request. Does detectify export xml/json reports or doesn it require import via detectify api? If you provide example we may be able to implement the import.

Detectify export the reports in PDF format.
