### ISSUE TITLE
OWASP ZAP and empty endpoints

### ISSUE THREAD

**Issue by zakrush** [DefectDojo/django-DefectDojo#5107]
**Be informative**
Hello. 
When OWASP ZAP report is uploaded, it added new endpoits to Findings. 
If I will go to endpoint tab and will click on endpoits, I see that endpoint didn't have active fingings. 
![image](https://user-images.githubusercontent.com/33844164/133485111-d67e0706-5e3e-4850-9bc5-ffc5ebef098e.png)

**Bug description**
No vulnerable endpoints after uploaded ZAP report

**Steps to reproduce**
1. Create engagement
2. Upload scan result of OWASP ZAP
3. Go to vulnerable Endpoints
4. See that "no vulnerable endpoints@

**Expected behavior**
I think here I should to see some endpoints with wulnerability

**Deployment method** *(select with an `X`)*
- [ `X`  ] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - DefectDojo version 2.1.0

**Sample scan files**
[tip_test.txt](https://github.com/DefectDojo/django-DefectDojo/files/7172330/tip_test.txt)
rename this to txt

**Additional context** (optional)

**Comment by damiencarol** [comment]
Taking this one, I'm already working on a ZAP maintenance PR.

**Comment by damiencarol** [comment]
You need to flag them as verified (attribute `verified` of the `Finding`) to have them in this screen.
