### ISSUE TITLE
Unclear Documentation in Findings

### ISSUE THREAD

**Issue by chanduaki** [DefectDojo/django-DefectDojo#5117]
Unable to understand the below things in the DefectDojo

ℹ️ Touch FIndings
ℹ️ Manage Files
ℹ️ Make Finding a Template
ℹ️ Create a CWE Remediation Template
ℹ️ Apply Template to Findings
ℹ️ Finding Templates
      ℹ️ ADD New Findings Template
      ℹ️ Download Finding Template
 ℹ️ Upload Threat model
ℹ️ Add Test Strategy

**Comment by StefanFl** [comment]
The best way to learn how these functionalities work is to try them with a test product, see what happens and if the functionality is useful to you. As DefectDojo being an open source project with limited resources, we try to produce good documentation too, but it is not always the highest priority on our to-do list to be honest.
