### ISSUE TITLE
Could update the Documentation in Few things in the Defectdojo Dashboard

### ISSUE THREAD

**Issue by chanduaki** [DefectDojo/django-DefectDojo#5118]
**Dashboard Overview**
ℹ️ Unassigned Answered Engagement Questionnaires 

**Endpoints**
ℹ️ List of Endpoints  
ℹ️ Vulnerable Endpoints 
ℹ️ Vulnerable Endpoint Hosts 
ℹ️ Migrate Endpoints

**Questionnaire**
ℹ️ All Questionnaires
ℹ️ All Questions

**Configurations**
ℹ️ Credential Manager
ℹ️Tool Configuration
ℹ️Tool Type Configuration
ℹ️ Rules Framework
ℹ️ Regulations - why it was Important & Advantage
ℹ️ Notifications - How can we configure our EMAIL, SLACK ID for sending ( similar doc like **Google Sheet Synchronization**)

**Comment by StefanFl** [comment]
@chanduaki Documentation is a great way to get involved and contribute to the project. Do you want to have a go?
