### ISSUE TITLE
Add more grouping options for findings (Title, vuln id, ...)

### ISSUE THREAD

**Issue by damiencarol** [DefectDojo/django-DefectDojo#5119]
One feature needed by few users is to be able to group by title or by vuln id.
It is very useful when you have the same vulnerability in a lot of different files.

Something like that for ex:
![image](https://user-images.githubusercontent.com/1694940/133830393-8c51abc4-7f5f-4e63-912a-e26f1d4aeffc.png)

![image](https://user-images.githubusercontent.com/1694940/133830542-b79e9285-dddc-4ff5-b4be-3e33822a0688.png)

**Comment by damiencarol** [comment]
FYI @valentijnscholten

**Comment by valentijnscholten** [comment]
Should we allow *all* fields and let users just find out what works best for them? We need to support combinations of fields as well.

**Comment by damiencarol** [comment]
Interesting. Yes, you're right there must be some users that would need arbitrary combination of more than 1 or 2 fields.
I'm wondering what UI could be useful. A big list of check-boxes :D ?

**Comment by BoBeR182** [comment]
I would be interested in seeing this feature added. Some scans create tons of findings and only being limited to component name / title is very challenging to manage in bulk.
