### ISSUE TITLE
Unable to import Harbor Vulnerability Scans

### ISSUE THREAD

**Issue by nu-vi** [DefectDojo/django-DefectDojo#5137]
This parser doesn't seem to be working with the current json format of Harbor Vulnerability Scans. 

A sample report that produces the bug is attached.
[harbor-report.json.zip](https://github.com/DefectDojo/django-DefectDojo/files/7210072/harbor-report.json.zip)

**Comment by StefanFl** [comment]
It's a problem with severities, should be easy to fix

**Comment by damiencarol** [comment]
Oh my... took a look at the harbor parser, lot of things to change. Please refactor it in the same time @StefanFl

**Comment by StefanFl** [comment]
Already done :smiley:

**Comment by valentijnscholten** [comment]
fixed in dev / 2.3.0.
