### ISSUE TITLE
Integration tests for finding lists are not executed

### ISSUE THREAD

**Issue by StefanFl** [DefectDojo/django-DefectDojo#5154]
The integration tests for Open Findings, Closed Findings and Accepted Findings are not executed, because the parameter `suffix` in `test_list_findings` is ignored, see https://github.com/DefectDojo/django-DefectDojo/blob/master/tests/finding_test.py#L17-L32.

If they would be executed, they would produce errors and need to be reworked.

**Comment by damiencarol** [comment]
Good catch. should be good to work also on test that have the `broken` tag

**Comment by StefanFl** [comment]
fixed in 2.3.0-dev
