### ISSUE TITLE
mysql_conf error when installing setup.bash with postgres

### ISSUE THREAD

**Issue by ekelson-bcove** [DefectDojo/django-DefectDojo#516]
Please use the following template when submitting issues:

### Issue Type 
- [x ] Bug
- [ ] Enhancement

### Description
When executing setup.bash on Centos 7 systems using postgres db type (without mysql installed), receive error that mysql_config is not found.  Then remainder of install fails
![image](https://user-images.githubusercontent.com/20729707/37680806-614b9358-2c5b-11e8-8424-94e1e00ca10f.png)

### Operating System 
Please include the version number (ex: Ubuntu 16.04)
centos 7.4

### Install

- [x ] setup.bash
- [ ] docker

### Steps to Reproduce
Follow for production directions, chose postgres db.

### Screenshots (optional)
attached

**Comment by maennel** [comment]
Hey Eric, according to this thread (
https://stackoverflow.com/questions/13922955/installing-mysql-python-without-mysql-server-on-centos),
can you try to install mysql-devel on OS level?

If this works, we should probably add it to "the yum part" of setup.bash...

Best, Manuel J.

**Comment by maennel** [comment]
Hm, a better solution would probably be to comment out the python mysql dependency (``mysqlclient``) in setup.py, so you don't install unnecssary software. This would mean we'd need to adapt the dependency installation in function of the target operating environment... food for thought, I guess.

**Comment by ekelson-bcove** [comment]
Will try. If I am not using MySQL should this be installed at all?

**Comment by ekelson-bcove** [comment]
Oh I like the second one. Agreed. The bash script should use the dB
selection to drive install.

**Comment by ekelson-bcove** [comment]
fyi, the install seems to try to do a yum install for yarn,  libpq-dev, libmysqlclient-dev

At least for libpq-dev, its postgresql-libs on centos.

**Comment by eik18** [comment]
https://github.com/DefectDojo/django-DefectDojo/pull/600
