### ISSUE TITLE
service attribute for Findings class

### ISSUE THREAD

**Issue by zakrush** [DefectDojo/django-DefectDojo#5171]
**Is your feature request related to a problem? Please describe**
Hello. I have monorepo. I have differents microservices into one repository. 
For ex: services/service1 services/service2
If I scanning it by DependencyCheck for example, I have deduplications for same findings. Now, I'm preventing it throught endpoins, but it incorrect as I think, becouse it functional for dynamic analyzers. Also, I have some trouble with using of endpoints into dedup for ex.: https://github.com/DefectDojo/django-DefectDojo/issues/5166

**Describe the solution you'd like**
I think it's good idea to add `service` field to findings. This field can be set in deduplication algorithm, import and reimport of scans. 

If service is not set, it is None for ex. I think it's should optional field.
**Describe alternatives you've considered**
Using endoints. Now I'm using it.

**Additional context**
Add any other context, screenshots, sketch, code snippet, etc. about the feature request here.

**Comment by StefanFl** [comment]
Another possibility to deal with services would be to have a separate Engagement per service and set **Deduplication within this engagement only** for every engagement. Then you would have deduplication per service and an easy way to view your findings per service.

**Comment by valentijnscholten** [comment]
I think @alles-klar had the same scenario. The downside of having an engagement for each service, it could explode the number of engagements. Especially if you have also "an engagement per branch".

**Comment by alles-klar** [comment]
I am using both, different engagements and endpoints.

**Comment by zakrush** [comment]
@alles-klar  As I say early, if you're using endpoints as dedup algo, you can't to do reimport with currectd deduplication. Also, I think that it's incorrect using endpoints for service-name. 

@StefanFl I already have some jobs with endpoints, sometimes I can't to do one engagement for every service. Yes, also I have engagements per branch. I'll get very much engagements. It is more convenient to use one engagement of branch job.

**Comment by damiencarol** [comment]
@valentijnscholten of course implementing the simpler solution can be better in the short term. Adding a `service` attribute is easy and I can support updating all the parsers that have this concept of "service".
*But* I really think that we should invest time in having a generic algorithm that handle this "linked" resources in the mid/long term.
The endpoints code for now is ok. It takes shortcuts to keep things simple. We can discuss in the next contributor meeting.

**Comment by StefanFl** [comment]
merged for release 2.4.0
