### ISSUE TITLE
Hardcoded password for MYSQL

### ISSUE THREAD

**Issue by joaquinrinaudo-olx** [DefectDojo/django-DefectDojo#518]
Hello,

When running docker now the password is hardcoded by setup.bash to "Cu3zehoh7eegoogohdoh1the" if running docker-compose .
Can we parametrize this MYSQL password via ENV MYSQL_PASSWORD as before?  Same for admin user default, before it was set by DOJO_ADMIN_PASSWORD.

### Sample Scan File (if applicable)
https://github.com/DefectDojo/django-DefectDojo/blob/master/setup.bash#L48

Regards,

**Comment by joaquinrinaudo-olx** [comment]
Duplicate of #504.

**Comment by t3h2mas** [comment]
@joaquinrinaudo-olx In that issue, I mentioned the hardcoded password, but my issue was specific to using a database outside of the defect dojo environment. I.E. in a cloud provider.

It's my opinion that the two issues are separate and this could be reopened as a non dup

**Comment by joaquinrinaudo-olx** [comment]
If they would support databases outside DefectDojo, probably this issue would be addressed (at least for us) since we could use RDS or similar technologies which probably mean a non-hardcoded password.
