### ISSUE TITLE
List of scanners id

### ISSUE THREAD

**Issue by tonnyhideyori** [DefectDojo/django-DefectDojo#5183]
To use API findings, there is option **_found_by_** this takes unique integer, but in documentation does not specify the unique id to the scanner. Can you provide the list os scanner corresponding to their unique number.
best regards

**Comment by valentijnscholten** [comment]
This differs per instance and the list can be retrieved via `GET /api/v2/test_types/`

**Comment by tonnyhideyori** [comment]
Thank you
