### ISSUE TITLE
Docker releases Tags

### ISSUE THREAD

**Issue by joaquinrinaudo-olx** [DefectDojo/django-DefectDojo#519]
### Issue Type 
- [ ] Bug
- [X] Enhancement

### Description

Please tag the proper release on [Dockerhub](https://hub.docker.com/r/appsecpipeline/django-defectdojo/) with the proper release version (1.2.2, 1.2.0) to avoid using beta releases and improve platform stability.

Regards,

**Comment by aaronweaver** [comment]
Added release tagging to Docker hub.
