### ISSUE TITLE
Toleration support for the initializer job

### ISSUE THREAD

**Issue by mikeanth-dev** [DefectDojo/django-DefectDojo#5202]
At the moment, in the `django-DefectDojo/helm/defectdojo/templates/initializer-job.yaml` file, there is specified support for `nodeSelector` and `affinity`, yet no mention of `tolerations`.

Support for tolerations would be nice, as it would allow more control of where each pod gets scheduled.

**Comment by valentijnscholten** [comment]
If you want you can make a PR with the desired changes

**Comment by mikeanth-dev** [comment]
Done. See #5208
