### ISSUE TITLE
decouple docker image from setup.bash

### ISSUE THREAD

**Issue by t3h2mas** [DefectDojo/django-DefectDojo#524]
### Issue Type 
- [X] Enhancement

### Description
The line https://github.com/DefectDojo/django-DefectDojo/blob/master/Dockerfile#L14
does a lot of OS bootstrapping. Taking this approach inside a Dockerfile fails to take advantage of docker cache layers.

While it's not a bad approach for end users, I believe that caching host package bootstrapping, etc, is in the best interest of both potential contributors and power users who want to tweak their configuration.

### Suggestion
Use a different bootstrap script for Docker, one that's more maintainable and doesn't care about the code paths for (mysql OR postgres) and (ubuntu, mac, or rpm*)

**Comment by maennel** [comment]
In the meantime, there were quite some activities going on. Nonetheless, I think we're not at a point where we can call it done.

I'd suggest to replace ``setup.bash`` by a Makefile including commands to install os requirements, application dependencies and, ultimately, the application itself.
Dockerfile would then be able to do calls to ``make install-os-requirements`` and similar. This would take most logic from Dockerfile and keep it centrally in the Makefile. 
Derivate- and Technology-specific stuff would also be handled by Makefile. 

The downside of this approach would be the specific syntax (e.g. tabs vs spaces) required by Make. 

Any thoughts on this?

**Comment by t3h2mas** [comment]
Having the provision commands ran as logical `CMD` groups in the Dockerfile would improve development time in the docker environment.

I'm not sure that the makefile would accomplish that specific goal, but I do see the need for grouping the different install options.

This is more important to me now, while there are certain app settings that can only be configured on `docker build`.

**Comment by devGregA** [comment]
@t3h2mas @maennel, I'm going to archive this issue for now. There isn't anything inherently broken, and we do not have the bandwith to take this on anytime in the near future. We review archived issues once a year to determine if they should be reopened. We as always are happy to review PRs 😉
