### ISSUE TITLE
Add Engagement ID to the All Engagements page as a selectable column.

### ISSUE THREAD

**Issue by jurschel** [DefectDojo/django-DefectDojo#5253]
Please add this ID to the All Engagements page so that when the list is exported it already contains the ID.  This is helpful when cleaning up a lot of engagements that might be getting created via automation.

**Comment by jurschel** [comment]
There is an export on that screen.  However it doesn't include that field as a selectable column.  Feels like it might be a really quick change to add that to the existing export fields?

**Comment by StefanFl** [comment]
I agree with @valentijnscholten, proper CSV/Excel export as with the Findings is the better way to go and not a lot of effort.

**Comment by StefanFl** [comment]
merged for release 2.4.0
