### ISSUE TITLE
Suspicious duplicate branch in a if in dojo.cred.view.delete_cred_controller()

### ISSUE THREAD

**Issue by damiencarol** [DefectDojo/django-DefectDojo#5256]
This branch duplicates the one on line 630.

https://github.com/DefectDojo/django-DefectDojo/blob/a2f75d4df79b770af8c02a07a324529e2aa958c3/dojo/cred/views.py#L630-L638

**Comment by manuel-sommer** [comment]
Thus, this issue can be closed.
