### ISSUE TITLE
Add test case for installing DefectDojo under a Mac OS X environment

### ISSUE THREAD

**Issue by maennel** [DefectDojo/django-DefectDojo#527]
Please use the following template when submitting issues:

### Issue Type 
- [ ] Bug
- [x] Enhancement

### Description

Currently, there is no test case to test ``setup.bash`` functionality in a Mac OS X environment. 
TravisCI, however, offers the possibility to run things in such an environment: https://docs.travis-ci.com/user/reference/osx/

This issue suggests to add a simple test case, testing for successful installation of DefectDojo under a Mac OS X environment.

If this is not done, errors as encountered in PR #486 may not be anticipated.

**Comment by devGregA** [comment]
I think this will be much easier once we split out the ansible and docker installs to separate repos

**Comment by devGregA** [comment]
@maennel closing this issue as it is duplicated of #143 copying your comments into the main issue.
