### ISSUE TITLE
Created Endpoint does not appear in the Findings

### ISSUE THREAD

**Issue by t51** [DefectDojo/django-DefectDojo#5278]
Hi Devs,

**Bug description**
Associating an endpoint to a finding no longer works. When attempting to add a system/endpoint to a finding, the endpoints are no longer displayed for that product.

**Steps to reproduce**
1. Go any Findings
2. Edit Finding
3. Click the drop-down under 'Systems / Endpoints' OR the add button for the popup creation.

**Expected behavior**
A list of endpoints associated with the Product should be displayed and selectable for the Finding when clicking the drop-down. 

**Deployment method** *(select with an `X`)*
- [x] Docker Compose

**Environment information**
 - DefectDojo version 2.3

** Attempted Troubleshooting**
- I have also tested it on the latest 2.3.1 demo instance and it's the same issue. 
- When creating the endpoint via the findings popup, no dojo_finding_endpoints record is created thus doesn't get associated with the findings.

Thank you,

**Comment by StefanFl** [comment]
merged for release 2.4.0
