### ISSUE TITLE
Endpoint Status returns all status records

### ISSUE THREAD

**Issue by t51** [DefectDojo/django-DefectDojo#5279]
**Bug description**
When editing an Endpoint, the Endpoint Status drop-down field returns all dojo_endpoint_status records. 

**Steps to reproduce**
1. Open any single Endpoint
2. Click Edit
3. Click the drop-down for Endpoint Status

**Expected behavior**
I'm actually unsure of the purpose of this field, however, I don't believe it should be returning all records. I'm expecting records to be at least associated with the specific endpoint/findings.

**Deployment method**
- Docker Compose

**Environment information**
 - DefectDojo version 2.3

![image](https://user-images.githubusercontent.com/10723898/137410254-919c604e-bfb9-4146-a02a-5aef2c143a53.png)

**Comment by StefanFl** [comment]
@Maffooch I am working on endpoints anyway and can include this issue as well.

**Comment by Maffooch** [comment]
Okay even better! Thanks @StefanFl

**Comment by StefanFl** [comment]
merged for release 2.4.0
