### ISSUE TITLE
"SonarQube API Import" parser mixes up severity and scanner confidence for security hotspots

### ISSUE THREAD

**Issue by StefanFl** [DefectDojo/django-DefectDojo#5282]
**Bug description**
SonarQube's security hotspots have a review priority defined like this:

> When SonarQube detects a Security Hotspot, it's added to the list of Security Hotspots according to its review priority from High to Low. Hotspots with a High Review Priority are the most likely to contain code that needs to be secured and require your attention first.

> Review Priority is determined by the security category of each security rule. Rules in categories that are ranked high on the OWASP Top 10 and CWE Top 25 standards are considered to have a High Review Priority. Rules in categories that aren't ranked high or aren't mentioned on the OWASP Top 10 or CWE Top 25 standards are rated as Medium or Low.

In the current implementation of the scanner this review priority is translated to scanner confidence (certain, firm, tentative) and the severity of the findings are always **Info**. 

A better interpretation would be to use the review priority to set the severity of the finding and set the scanner confidence always to **tentative**.

**Comment by StefanFl** [comment]
@jimtsikos You implemented the parsing of security hotspots initially. What do you think about it?

**Comment by damiencarol** [comment]
I can take this one.

**Comment by damiencarol** [comment]
@StefanFl we had the same discussion with @jimtsikos and I continue to think the same (https://github.com/DefectDojo/django-DefectDojo/pull/4107#discussion_r711770246).
Hotspots are just some info more or less likely to produce a finding.
According to the SQ documentation:

> Security Hotspots are not assigned severities as it is unknown whether there is truly an underlying vulnerability until they are reviewed.

Also as you said.

>  Hotspots with a High Review Priority are the most likely to contain code that needs to be secured and require your attention first.

Ths clearly state that it is ordered by the confidence of the tool (SonarQube) if this will produce a finding. But it's not linked to the severity.
