### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by kiblik** [DefectDojo/django-DefectDojo#5290]
In https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/CONTRIBUTING.md there are broken links to https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/tests.

**Comment by valentijnscholten** [comment]
We should probably remove the checklist there and point to the more complete checklist in the PR template: https://github.com/DefectDojo/django-DefectDojo/blob/master/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

That needs some updates then to incorporate the info/links from the checklist in the main readme.
