### ISSUE TITLE
Endpoints Created via Findings page are not getting associated back to the Finding

### ISSUE THREAD

**Issue by t51** [DefectDojo/django-DefectDojo#5291]
Bug description
When creating an Endpoint via the Finding page, the newly created Endpoint does not associate back to the Finding. 
When trying to select an Endpoint for the Finding, no Endpoints are listed.

Steps to reproduce

1. Open any single Finding click Edit
2. In the Endpoint section, attempt to select an Endpoint via the dropdown box. OR create a new Endpoint.

Expected behavior
Endpoints of that particular Product listed to be selected for the Finding;
Newly created Endpoints via the Findings page to be automatically associated with the current Finding.

Deployment method
Docker Compose

Environment information
DefectDojo version 2.3

Have also tested on the Demo 2.3.1 environment with the same issue.

**Comment by damiencarol** [comment]
@StefanFl this part broke in the past, and I find it not very user-friendly. It could be good to accept a list of URLs in a big text area and parse them when creating the Finding. What do you think?

**Comment by StefanFl** [comment]
merged for release 2.4.0
