### ISSUE TITLE
Add support for SCA json file import for Veracode

### ISSUE THREAD

**Issue by themenucha** [DefectDojo/django-DefectDojo#5292]
**Is your feature request related to a problem? Please describe**
Cannot import Veracode's SCA(srcclr) json scan results. File example: https://github.com/DefectDojo/sample-scan-files/blob/master/veracode/veracode-docker-scan-dojodjango.json
Ex: I'm always frustrated when [import scan results fails]

**Describe the solution you'd like**
It will be great to have the ability to upload srcclr scan results in json format
Ex: As a security engineer, I want to have the ability to upload srcclr scan results in json format so that could be imported to 'Findings'.

**Describe alternatives you've considered**
A new/modified parser for veracode
**Additional context**
Thank you!

**Comment by damiencarol** [comment]
I will take a look.
