### ISSUE TITLE
Trouble with pushing finding Files to Jira

### ISSUE THREAD

**Issue by zakrush** [DefectDojo/django-DefectDojo#5318]
**Slack us first!**
https://owasp.slack.com/archives/C2P5BA8MN/p1634721377444900

**Be informative**
If finding was pushed to Jira, and then user add/update files of finding, that it's not updated to Jira. 

**Bug description**
If Finding was created with files and than push to jira, attachment seem into issue. But not updated throught DD

**Steps to reproduce**
1.Create finding with File
2. Push to Jira
3. Check jira issue and see that it's have attach
3. Add second file to Finding
4. push to Jira
5. See that Jira issue doesn't have new file.

**Expected behavior**
New attachment added to Jira issue

**Deployment method** *(select with an `X`)*
- [ `X` ] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**

 - DefectDojo version 2.1.0 
 - 
**Logs** 
Into celery see this error:
```
RROR [celery.app.trace:265] Task dojo.jira_link.helper.update_jira_issue_for_finding[5edd8006-d5b3-4bae-b160-f30d0ed56b33] raised unexpected: NameError("name 'new_issue' is not defined")
celeryworker_1  | Traceback (most recent call last):
celeryworker_1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 450, in trace_task
celeryworker_1  |     R = retval = fun(*args, **kwargs)
celeryworker_1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 731, in __protected_call__
celeryworker_1  |     return self.run(*args, **kwargs)
celeryworker_1  |   File "/app/dojo/decorators.py", line 118, in __wrapper__
celeryworker_1  |     return func(*args, **kwargs)
celeryworker_1  |   File "/app/dojo/jira_link/helper.py", line 724, in update_jira_issue_for_finding
celeryworker_1  |     return update_jira_issue(finding, *args, **kwargs)
celeryworker_1  |   File "/app/dojo/jira_link/helper.py", line 805, in update_jira_issue
celeryworker_1  |     find, jira, new_issue,
celeryworker_1  | NameError: name 'new_issue' is not defined
```

**Comment by valentijnscholten** [comment]
fixed in dev / 2.4.0
