### ISSUE TITLE
History of finding page has improper formatting

### ISSUE THREAD

**Issue by pvasilevich** [DefectDojo/django-DefectDojo#5334]
**Bug description**
Bad formatting of the page (Finding History). Several lines combined into one, there are no line separators at all. Hard to read text.

**Steps to reproduce**
1. Go to 'Product->Open Findings->Finding'
2. Click on popup menu (toaster icon in upper-right corner)
3. Choose 'View History' in the menu
2. Page with history opened.

**Expected behavior**
If there are several changes appeared during one operation, they need to be formatted as separate lines

**Deployment method** *(select with an `X`)*
- [X] AWS ECS

**Environment information**
 - Operating System: Amazon Linux
 - DefectDojo version: 2.3.1

**Screenshots**
![image](https://user-images.githubusercontent.com/1565354/138691793-d3fafd08-7dd5-42f9-a2b0-05d2f9c21986.png)

**Comment by manuel-sommer** [comment]
This issue can be closed @valentijnscholten

**Comment by valentijnscholten** [comment]
fixed in dev/2.4.0
