### ISSUE TITLE
"title" input is missing from "import-scan" API method

### ISSUE THREAD

**Issue by kamranha** [DefectDojo/django-DefectDojo#5335]
![image](https://user-images.githubusercontent.com/93140960/138715790-b258c552-c26d-4eb5-9d8d-efb8612c5f46.png)

![image](https://user-images.githubusercontent.com/93140960/138720128-61071a77-6a5a-426f-b718-70299a35418b.png)

**Comment by manuel-sommer** [comment]
This can be closed @valentijnscholten

**Comment by valentijnscholten** [comment]
fixed in 2.5.0
