### ISSUE TITLE
Wrong Dedulication Algorithm for Mozilla Observatory Scan

### ISSUE THREAD

**Issue by manuel-sommer** [DefectDojo/django-DefectDojo#5339]
Bug description
Importing the same Mozilla Observatory Scan report multiple times makes the number of findings grow.

Steps to reproduce

Create an engagement
Import the same Mozilla Observatory Scan report multiple times.
Multiple findings are not deduplicated from DefectDojo. 

Expected behavior
The deduplication algorithm in DefectDojo deduplicates findings.

Deployment method
Docker Compose

Operating System: Ubuntu 21.04
DefectDojo version: 2.3.1

**Comment by StefanFl** [comment]
Closed due to inactivity
