### ISSUE TITLE
Docker dev version is not working

### ISSUE THREAD

**Issue by NMilicic** [DefectDojo/django-DefectDojo#534]
### Issue Type 
- [x] Bug
- [ ] Enhancement

Installing using 
`docker run -it -p 8000:8000 appsecpipeline/django-defectdojo bash -c "export LOAD_SAMPLE_DATA=True && bash /opt/django-DefectDojo/docker/docker-startup.bash"`

Stops on the 
` * Starting MySQL database server mysqld                                                                                                                           [ OK ] `

### Operating System 
macOs 10.13.3
Docker version: 18.03.0-ce-mac60 (23751)

### Install

- [ ] setup.bash
- [x] docker

**Comment by NMilicic** [comment]
@imohammedzen App starts, but in console there should be listed username and password so I can login to it, and it seems that code from docker-startup.bash isn't running.

**Comment by imohammedzen** [comment]
@NMilicic default username and password is admin and admin. Can you try logging in and check

**Comment by NMilicic** [comment]
@imohammedzen  I was able to login with default username and password.
It seems there is no demo data.

Screenshot:
<img width="1430" alt="screen shot 2018-04-06 at 13 35 26" src="https://user-images.githubusercontent.com/11042271/38419268-102b4138-39a0-11e8-9a79-b63e2f65d98a.png">

**Comment by imohammedzen** [comment]
Its not picking up your commands. If you drop into bash of running container, you will see that its using default entrypoint commands.

![image](https://user-images.githubusercontent.com/23624531/38419782-453cac02-39d4-11e8-84d9-3e47e5894fd3.png)

**Comment by NMilicic** [comment]
@imohammedzen Thanks for help.
Is there any solution to run these command on docker run and not run default entrypoint?

**Comment by imohammedzen** [comment]
@NMilicic You should probably create another docker container instead of overwriting entrypoint. If you do have to do it then following is the code but do remember it will split out some errors. 

`docker run -it --entrypoint /bin/bash -p 8000:8000 appsecpipeline/django-defectdojo -c "export LOAD_SAMPLE_DATA=True && bash /opt/django-DefectDojo/docker/docker-startup.bash"`

**Comment by imohammedzen** [comment]
Also i don't think its an issue but feature, I suggest you edit the Dockefile present in the project to create a new image.

**Comment by p3r1c0** [comment]
I have the same problem: 

Installing using
docker run -it -p 8000:8000 appsecpipeline/django-defectdojo bash -c "export LOAD_SAMPLE_DATA=True && bash /opt/django-DefectDojo/docker/docker-startup.bash"

Stops on the
* Starting MySQL database server mysqld [ OK ]

I want to attach to docker process and see some configuration and it fail:

C:\Users\pgalindo>docker ps -a
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                      PORTS                    NAMES
057540f78927        appsecpipeline/django-defectdojo   "/bin/sh -c 'chown -…"   34 minutes ago      Up 34 minutes               0.0.0.0:8000->8000/tcp   stupefied_cori
C:\Users\pgalindo>docker attach stupefied_cori
[fail]

Operating System
Windows 10 1607
Docker version: 18.03.0-ce-win59 (16762)

Thanks!

**Comment by p3r1c0** [comment]
Any solution to this problem?

**Comment by t3h2mas** [comment]
@imohammedzen @NMilicic You can run the prebuilt image with a different entry point using `docker run --entrypoint="[CODE HERE]" ...`

**Comment by secfigo** [comment]
@t3h2mas If you look at the previous comments, i did mention it ;)
