### ISSUE TITLE
Unable to upgrade DefectDojo from 1.15 to 2.0.0, migration errors

### ISSUE THREAD

**Issue by aishwaryakrish87** [DefectDojo/django-DefectDojo#5352]
Hi,

I have installed DefectDojo v1.15.0 using docker and restored database from another existing instance of same version. Works fine with v1.15.0 but it is required for us to upgrade to v2.2.1 with the database intact. During the upgrade process while bringing up the application with 'docker-compose up' the migration encounters a series of django migration errors. 

However, There's no issue upgrading a clean install as there's no migrations to apply.

_initializer_1   | Initializing.
initializer_1   | [27/Oct/2021 14:08:28] INFO [dojo.models:3613] enabling audit logging
initializer_1   | Waiting for database to be reachable
initializer_1   | Making migrations
initializer_1   | [27/Oct/2021 14:08:29] INFO [dojo.models:3613] enabling audit logging
initializer_1   | No changes detected in app 'dojo'
initializer_1   | Migrating
initializer_1   | [27/Oct/2021 14:08:33] INFO [dojo.models:3613] enabling audit logging
initializer_1   | Operations to perform:
initializer_1   |   Apply all migrations: admin, auditlog, auth, authtoken, contenttypes, django_celery_results, dojo, sessions, sites, social_django, tagging, watson
initializer_1   | Running migrations:
initializer_1   |   Applying auth.0012_alter_user_first_name_max_length... OK
initializer_1   | Traceback (most recent call last):
initializer_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
initializer_1   |     return self.cursor.execute(sql, params)
initializer_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
initializer_1   |     return self.cursor.execute(query, args)
initializer_1   |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
initializer_1   |     res = self._query(query)
initializer_1   |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
initializer_1   |     db.query(q)
initializer_1   |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
initializer_1   |     _mysql.connection.query(self, query)
initializer_1   | MySQLdb._exceptions.OperationalError: (1060, "Duplicate column name 'title'")_

**Comment by valentijnscholten** [comment]
timed out
