### ISSUE TITLE
Parse CycloneDX Recommendations to DefectDojo Mitigation

### ISSUE THREAD

**Issue by tsmithv11** [DefectDojo/django-DefectDojo#5376]
**Is your feature request related to a problem? Please describe**
CycloneDX has a category called "recommendations" and DefectDojo has a section called "mitigation that seems to match.

For example:
      <v:recommendations>
        <v:recommendation>Upgrade</v:recommendation>
      </v:recommendations>

Would translate to "Upgrade" in the mitigation section of DefectDojo.

**Describe alternatives you've considered**
For now, we include recommendations in the "references" section of DefectDojo ("advisory" in CycloneDX).

**Comment by StefanFl** [comment]
merged for release 2.7.0
