### ISSUE TITLE
Burp Pro file error when  imported a saved copy

### ISSUE THREAD

**Issue by SPoint42** [DefectDojo/django-DefectDojo#5386]
Just try with my Burp Pro V2021.9.1 and can't import the saved scan

Tested with Defectdojo 2.3.1 and fresh -dev from this 2021-11-04 day. 

Error is : 

uwsgi_1         | [pid: 35|app: 0|req: 7/10] 172.18.0.1 () {58 vars in 2183 bytes} [Thu Nov  4 07:24:46 2021] GET /alerts/count => generated 13 bytes in 28 msecs (HTTP/1.1 200) 6 headers in 171 bytes (1 switches on core 1)
uwsgi_1         | [04/Nov/2021 07:24:46] ERROR [dojo.engagement.views:633] not well-formed (invalid token): line 1, column 1
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 1693, in feed
uwsgi_1         |     self.parser.Parse(data, 0)
uwsgi_1         | xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 1
uwsgi_1         |
uwsgi_1         | During handling of the above exception, another exception occurred:
uwsgi_1         |
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/app/./dojo/engagement/views.py", line 618, in import_scan_results
uwsgi_1         |     test, finding_count, closed_finding_count = importer.import_scan(scan, scan_type, engagement, user, environment, active=active, verified=verified, tags=tags,
uwsgi_1         |   File "/app/./dojo/importers/importer/importer.py", line 350, in import_scan
uwsgi_1         |     parsed_findings = parser.get_findings(scan, test)
uwsgi_1         |   File "/app/./dojo/tools/burp/parser.py", line 29, in get_findings
uwsgi_1         |     tree = etree.parse(xml_output, etree.XMLParser())
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/defusedxml/common.py", line 100, in parse
uwsgi_1         |     return _parse(source, parser)
uwsgi_1         |   File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
uwsgi_1         |     tree.parse(source, parser)
uwsgi_1         |   File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 601, in parse
uwsgi_1         |     parser.feed(data)
uwsgi_1         |   File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 1695, in feed
uwsgi_1         |     self._raiseerror(v)
uwsgi_1         |   File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 1602, in _raiseerror
uwsgi_1         |     raise err
uwsgi_1         | xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 1

I can send the tested file (but seems not be upload in git :-( )

**Comment by valentijnscholten** [comment]
Line 1, column 1 is at the very start of the file. Is there some kind of invalid BOM character or something? (just guessing at the moment).

**Comment by SPoint42** [comment]
> Line 1, column 1 is at the very start of the file. Is there some kind of invalid BOM character or something? (just guessing at the moment).

Just done a save of a simple projet and try to upload. I don't be sure this is only the problem....

**Comment by SPoint42** [comment]
just having an issue on my repos, seems working well now
