### ISSUE TITLE
Integration Tests Missing Test File

### ISSUE THREAD

**Issue by CharlieSears** [DefectDojo/django-DefectDojo#5400]
**Bug description**
Integration tests do not succeed when running all tests or when run targeting `tests/user_standard_test.py`. This is because `tests/user_standard_test.py` does not exist.

**Steps to reproduce**
Run all integration tests as there is no way to currently run only `tests/user_standard_test.py`
1. `unset DD_INTEGRATION_TEST_FILENAME`
2. `docker/setEnv.sh integration_tests`
3. `docker-compose up --build` (--build does not change the outcome, but included since it's what I utilize)
4. See error `python3: can't open file 'tests/user_standard_test.py': [Errno 2] No such file or directory` in integration_test container logs

**Expected behavior**
Integration tests for `tests/user_standard_test.py` run and pass.

**Deployment method**
- Docker Compose

**Environment information**
 - Operating System: AlmaLinux 8.4 (Electric Cheetah) x86-64
 - DefectDojo version: 6a34d6ed4: main: improve documentation (#5390) [ (HEAD -> dev, origin/dev)]

**Logs** 
```
[*@* ~]$ docker logs django-defectdojo_integration-tests_1 2>&1
wait-for-it.sh: waiting max 30 seconds for mysql:3306
wait-for-it.sh: mysql:3306 is available after 0 seconds
Testing DefectDojo Service
Waiting max 60s for services to start
Succesfully displayed login page, starting integration tests
IT FILENAME: 
Preparing configuration: USER_PROFILE_EDITABLE=True
Running Read only user profile test
python3: can't open file 'tests/user_standard_test.py': [Errno 2] No such file or directory
Error: Read test failed\n
```

**Additional context**
- References to `tests/user_standard_test.py` were added with #5275
- #5401 should be resolved alongside this issue. I didn't want to muddy this single issue with multiple items/contexts.

**Comment by valentijnscholten** [comment]
@dsever Did you forget to commit a file in #5275 ?

**Comment by dsever** [comment]
I'm on it

**Comment by valentijnscholten** [comment]
@dsever can we close this?

**Comment by dsever** [comment]
Sure, close it
