### ISSUE TITLE
Integration Tests Setting Invalid Boolean

### ISSUE THREAD

**Issue by CharlieSears** [DefectDojo/django-DefectDojo#5401]
**Bug description**
`entrypoint-integration-tests.sh` sets a `local_settings.py` value to `Frue`.

**Steps to reproduce**
Run all integration tests as there is no way to currently run only `tests/user_standard_test.py`
1. `unset DD_INTEGRATION_TEST_FILENAME`
2. `docker/setEnv.sh integration_tests`
3. `docker-compose up --build` (--build is not required but it's what I run)
4. See error reported in # 
5. Re-run tests: `docker-compose up --build` (--build **is** required here)
6. See error `NameError: name 'Frue' is not defined`

**Expected behavior**
Running integration tests do not set values that cannot be interpreted and do not impact subsequent tests.

I _believe_ this should be `False` based on context but with #5400 I cannot say for sure. Happy to add a PR for this once #5400 is resolved.

**Deployment method**
- Docker Compose
- ~Kubernetes~
- ~GoDojo~

**Environment information**
 - Operating System: AlmaLinux 8.4 (Electric Cheetah) x86-64
 - DefectDojo version: 6a34d6ed4: main: improve documentation (#5390) [ (HEAD -> dev, origin/dev)]

**Logs** 
```
Traceback (most recent call last):
  File "/app/./dojo/wsgi.py", line 63, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/app/./dojo/settings/settings.py", line 6, in <module>
    include(
  File "/usr/local/lib/python3.8/site-packages/split_settings/tools.py", line 108, in include
    exec(compiled_code, scope)  # noqa: S102, WPS421
  File "/app/dojo/settings/local_settings.py", line 1, in <module>
    USER_PROFILE_EDITABLE=Frue
NameError: name 'Frue' is not defined
```

**Additional context**
I could make an argument to close this ticket as local_settings.py is the responsibility of the user, I just don't expect tests to impact what is set there negatively. My reproduction steps are a bit convoluted for the real world, this issue would be better represented by showing 'tests/user_standard_test.py' attempting to utilize this value. 

local_settings.py content:
```
[*@* django-DefectDojo]$ cat dojo/settings/local_settings.py 
USER_PROFILE_EDITABLE=Frue
```

**Comment by valentijnscholten** [comment]
@dsever Can you check this artifact from #5275 ?

**Comment by dsever** [comment]
Could be left overs, because first I went with this file to keep the tests, than @valentijnscholten recommended to have it in existing user file, so I made mistake than.  I will take a look

**Comment by valentijnscholten** [comment]
@dsever can we close this?

**Comment by dsever** [comment]
Sure close it
