### ISSUE TITLE
Better support for security logging 

### ISSUE THREAD

**Issue by dsever** [DefectDojo/django-DefectDojo#5404]
Story: As security auditor/forensic, we require that solution has capability to deliver logs remotely (to be compliant with regulatory requirements) and  would use audit logs as proofs of system events. I can use, already implemented `Audit logging` functionalities, but currently it can't be remotely delivered to LMS or SIEM for further analysis.  Additionally I as forensic I need logs about user activities (like when user login, password resets, API-a key was issues, etc.). 

What:  OWASP https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html#which-events-to-log guide.

Attributes: https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html#event-attributes

**Comment by mtcolman** [comment]
Is there any intention to do anything in this space?

**Comment by dsever** [comment]
There have been some improvements in last release, like now it reports failed, login/logout actions in standard logs. Together with option to change log formats and now is reporting in uwsgi logs what user invoked actions. 

https://github.com/DefectDojo/django-DefectDojo/pull/6041
