### ISSUE TITLE
Add Issue Type through Env Variables for JIRA config

### ISSUE THREAD

**Issue by pedroamaral27** [DefectDojo/django-DefectDojo#5411]
**Feature Request:**

We have multiple different custom JIRA Issue Types in our enterprise JIRA, which vary depending on the actual issue at hand.
I know there is a way to add different issue types within the settings.py file, but it would be great if we could do so through environment variables, making the process much easier for kubernetes prod environments.

**Comment by tarrinho** [comment]
Any news on this request?
