### ISSUE TITLE
[HELM] The metrics container in the Django pod cannot start

### ISSUE THREAD

**Issue by bgoareguer** [DefectDojo/django-DefectDojo#5414]
**Bug description**
Since #5260 has been merged, the metrics container in the Django pod cannot start anymore.

The entrypoint has been changed between version 0.8.0 and 0.9.0 of the [nginx-prometheus-exporter](https://github.com/nginxinc/nginx-prometheus-exporter/compare/v0.8.0...v0.9.0#diff-5aecd73bbcb9b7410938673269f0d4e676dd18509277b0ff2f2787c9d3e22604)

The new entrypoint should be used in [django-deployment.yaml](https://github.com/DefectDojo/django-DefectDojo/blob/master/helm/defectdojo/templates/django-deployment.yaml#L105)

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Ubuntu 18.04
 - DefectDojo version: 2.4.1

**Logs** 
Error: failed to start container "metrics": Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/usr/bin/exporter": stat /usr/bin/exporter: no such file or directory: unknown

**Comment by valentijnscholten** [comment]
Fixed in `dev` i.e. 2.5.0.
