### ISSUE TITLE
DefectDojo create findings apiv2 500 Error foreign key constraint fails

### ISSUE THREAD

**Issue by vishnupriyaavp8** [DefectDojo/django-DefectDojo#5416]
### **Bug description**
While creating a finding through DefectDojo API v2, I am getting 500 Internal Server Error.
The error shown in logs is 

> django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`defectdojo`.`dojo_finding`, CONSTRAINT `dojo_finding_reporter_id_dec2fe8c_fk_auth_user_id` FOREIGN KEY (`reporter_id`) REFERENCES `auth_user` (`id`))')

### **Steps to reproduce**
1. Create a Product P (from UI)
2. Create an Engagement E within Product P (from UI)
3. Create a Test T with Test type 'API Test' within engagement E (from UI)
4. Create a custom finding F1 inside Test T (from UI) -**This works**
5. Create a custom finding F2 inside T (from API) - **This does not work**

**Python Code used for API call:**
```
new_finding = {
   'request_response': {'req_resp': [{'request': '', 'response': ''}]},
   'push_to_jira': False,
   'age': 0,
   'display_status': 'Active',
   'title': 'Test finding 4',
   'date': '2021-11-09',
   'severity': 'Critical',
   'description': 'Test',
   'active': True,
   'verified': False,
   'false_p': False,
   'duplicate': False,
   'out_of_scope': False,
   'risk_accepted': False,
   'under_review': False,
   'last_status_update': '2021-11-09T11:14:50.385362Z',
   'under_defect_review': False,
   'is_mitigated': False,
   'thread_id': 0,
   'numerical_severity': 'S0',
   'static_finding': True,
   'dynamic_finding': False,
   'created': '2021-11-08T10:56:25.704222Z',
   'test': 29,
   'reporter': 8,
   'found_by': [1]
}

url = DD_URL + '/api/v2/findings/'

headers = {
    'content-type': 'application/json',
    'Authorization': 'Token ' + DD_API_KEY_PROD
}

r = requests.post(url, headers = headers, data = json.dumps(new_finding), verify = True)
r.json()
```

**Error :**
{'message': 'Internal server error, check logs for details'}

### **Logs** 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/app/./dojo/api_v2/serializers.py", line 1088, in create
    new_finding = super(TaggitSerializer, self).create(validated_data)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 939, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/tagulous/models/tagged.py", line 219, in create
    obj = super(TaggedQuerySet, self).create(**safe_fields)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/app/./dojo/models.py", line 2386, in save
    super(Finding, self).save(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 790, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 933, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`defectdojo`.`dojo_finding`, CONSTRAINT `dojo_finding_reporter_id_dec2fe8c_fk_auth_user_id` FOREIGN KEY (`reporter_id`) REFERENCES `auth_user` (`id`))')
[09/Nov/2021 12:01:27] ERROR [django.request:224] Internal Server Error: /api/v2/findings/
ERROR:django.request:Internal Server Error: /api/v2/findings/

```
**Screenshots**
![image](https://user-images.githubusercontent.com/54842012/140969111-d8897072-92c9-47b5-be80-bb9795c7e6e6.png)

### **Expected behavior**
Finding should be created successfully

### **Deployment method**
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

### **Environment information**
 - Operating System: Ubuntu 18.04
 - DefectDojo version : Git cloned on a random day

### **Additional context**
I am sure that the specified Test type (found_by), Test and User (reporter) exist

**Comment by valentijnscholten** [comment]
What happens if you browse in the UI to `https://<defectdojohostname>/user/8`?

**Comment by valentijnscholten** [comment]
And please provide the info as requested in the template.

**Comment by vishnupriyaavp8** [comment]
> https://<defectdojohostname>/user/8

This is what I get for /user/8
![image](https://user-images.githubusercontent.com/54842012/140966589-789f4eba-e177-4be0-b30e-7320c22c2d66.png)

I created a new Test type (called 'testing') and I am using it. Is that an issue?

**Comment by vishnupriyaavp8** [comment]
> And please provide the info as requested in the template.

Is it fine now?

**Comment by valentijnscholten** [comment]
Can you try to create your finding via the API docs / try out function? It's at `/api/v2/oa3/swagger-ui/?docExpansion=none#/findings/findings_create`. We have a test case creating findings and I can create findings manually without a problem via the API. I notice you are setting fields that are not available in the API to be set, but are calculated internally. Can you try via the api docs and stick to the fields available there? You might be able to play around with it to see which field or value triggers the problem.

**Comment by valentijnscholten** [comment]
Also please stick to the json standard with regards to booleans:
![image](https://user-images.githubusercontent.com/4426050/140979761-ee1e3e9d-63e5-4261-b3a7-8ae5c7f9ffe3.png)

**Comment by vishnupriyaavp8** [comment]
> Can you try to create your finding via the API docs / try out function? It's at `/api/v2/oa3/swagger-ui/?docExpansion=none#/findings/findings_create`. We have a test case creating findings and I can create findings manually without a problem via the API. I notice you are setting fields that are not available in the API to be set, but are calculated internally. Can you try via the api docs and stick to the fields available there? You might be able to play around with it to see which field or value triggers the problem.

I have tried from Swagger UI with only required fields. It leads to the same issue. Will share screenshots in some time.

**Comment by vishnupriyaavp8** [comment]
Issue solved by installing DefectDojo 2.4.1. (Previously, I had cloned the git repository). Thanks for the support.

**Comment by valentijnscholten** [comment]
On the same database or a fresh database?

**Comment by vishnupriyaavp8** [comment]
> On the same database or a fresh database?

Freshly installed in another system

**Comment by valentijnscholten** [comment]
ok, could be something in the database that was incorrect. I don't think many people are creating findings manually so there could be some bugs there as we don't test it a lot ourselves. If you find anything that can be reproduced let us know so we can try to improve it.

**Comment by vishnupriyaavp8** [comment]
> ok, could be something in the database that was incorrect. I don't think many people are creating findings manually so there could be some bugs there as we don't test it a lot ourselves. If you find anything that can be reproduced let us know so we can try to improve it.

Sure, thanks a lot. I want to rectify this issue in the first machine where I did git clone.

2 questions :
1. If I delete docker images and reinstall Defect Dojo 2.4.1, will my projects and findings be retained?
2. Will the issue persist? Will the same Database be used after my re-installation?

**Comment by valentijnscholten** [comment]
If you do not delete the volumes the data will be retained, but probably also the problem :-)

**Comment by valentijnscholten** [comment]
timed out
