### ISSUE TITLE
Some fields are ignored/changed in APIv2 when creating new finding

### ISSUE THREAD

**Issue by fuzzah** [DefectDojo/django-DefectDojo#5417]
**Bug description**
I've created my own test type with checkboxes Active and Dynamic tool.
I've created a separate user with user id 2 and product role Writer.
When I create new findings using APIv2:
1. field "reporter" gets changed from 2 to 1
2. field "static_finding" gets changed from false to true
3. field "dynamic_finding" gets changed from true to false

**Steps to reproduce**
1. Create new test type and get its id (**in my case the id is 141**). Test type settings should be: Active, Dynamic tool. Static tool checkbox shouldn't be set.
2. Create new user with the product role Writer, get user id (**in my case user id is 2**)
3. Create new engagement, in this engagement create new test and get test id (**in my case test id is 3016**).
4. Use "Try it out" option of APIv2 OpenAPI3 in POST method of "/api/v2/findings"
5. Specify JSON payload as follows:
```
{
  "test": 3016,
  "found_by": [
    141
  ],
  "title": "My API-testing issue title",
  "date": "2021-11-10",
  "cwe": 20,
  "severity": "Critical",
  "description": "My API-testing description",
  "impact": "Integrity",
  "references": "google.com",
  "active": true,
  "verified": true,
  "false_p": false,
  "is_mitigated": false,
  "duplicate": false,
  "numerical_severity": "S0",
  "line": 200,
  "file_path": "/path/to/source/file.cpp",
  "static_finding": false,
  "dynamic_finding": true,
  "unique_id_from_tool": "Segmentation fault in /path/to/source/file.cpp:200",
  "vuln_id_from_tool": "Segmentation fault",
  "publish_date": "2021-11-10",
  "reporter": 2
}
```

6. Click "Execute". Response has fields "static_finding", "dynamic_finding" and "reporter" changed:
```
{
  "id": 35178,
  "notes": [],
  "test": 3016,
  "thread_id": 0,
  "found_by": [
    141
  ],
  "url": null,
  "tags": [],
  "push_to_jira": false,
  "title": "My API-testing Issue Title",
  "date": "2021-11-10",
  "sla_start_date": null,
  "cwe": 20,
  "cve": null,
  "cvssv3": null,
  "cvssv3_score": null,
  "severity": "Critical",
  "description": "My API-testing description",
  "mitigation": null,
  "impact": "Integrity",
  "steps_to_reproduce": null,
  "severity_justification": null,
  "references": "google.com",
  "is_template": false,
  "active": true,
  "verified": true,
  "false_p": false,
  "duplicate": false,
  "out_of_scope": false,
  "risk_accepted": false,
  "under_review": false,
  "last_status_update": "2021-11-10T08:45:14.457609Z",
  "under_defect_review": false,
  "is_mitigated": false,
  "mitigated": null,
  "numerical_severity": "S0",
  "last_reviewed": null,
  "line_number": null,
  "sourcefilepath": null,
  "sourcefile": null,
  "param": null,
  "payload": null,
  "hash_code": "c87580583f0b3db992944219f610c4dba052b557498c46d20c842c44852b0c7b",
  "line": 200,
  "file_path": "/path/to/source/file.cpp",
  "component_name": null,
  "component_version": null,
  "static_finding": true,
  "dynamic_finding": false,
  "created": "2021-11-10T08:45:14.439492Z",
  "scanner_confidence": null,
  "unique_id_from_tool": "Segmentation fault in /path/to/source/file.cpp:200",
  "vuln_id_from_tool": "Segmentation fault",
  "sast_source_object": null,
  "sast_sink_object": null,
  "sast_source_line": null,
  "sast_source_file_path": null,
  "nb_occurences": null,
  "publish_date": "2021-11-10",
  "duplicate_finding": null,
  "review_requested_by": null,
  "defect_review_requested_by": null,
  "mitigated_by": null,
  "reporter": 1,
  "last_reviewed_by": null,
  "sonarqube_issue": null,
  "endpoints": [],
  "endpoint_status": [],
  "reviewers": [],
  "files": []
}
```

**Expected behavior**
Fields "static_finding", "dynamic_finding" and "reporter" should contain values that were passed in JSON payload of POST request.

**Deployment method**
- [x] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Arch Linux rolling, kernel 5.14.11-hardened1-1-hardened
 - DefectDojo version: v. 2.4.1 ( release mode )
 - Docker version 20.10.9, build c2ea9bc90b
 - Docker Compose version 2.0.1

**Additional context**
At first I've created same issue in defectdojo_api: https://github.com/DefectDojo/defectdojo_api/issues/61 , but the issue seems to be in DefectDojo itself, not in the api library.
I tried to change test type settings (Static, Dynamic, Active) with no impact on the issue described.

**Comment by StefanFl** [comment]
`reporter` is not an attribute of the Findings POST form. It will always be populated with the user who posts the data.

The values for `static_finding` and `dynamic_finding` are hardcoded as well, when saving the finding:

```python
        if self.pk is None:
            ...
            if (self.file_path is not None) and (len(self.unsaved_endpoints) == 0):
                self.static_finding = True
                self.dynamic_finding = False
            elif (self.file_path is not None):
                self.static_finding = True
```
