### ISSUE TITLE
Child rule not working and Rule applied thrice

### ISSUE THREAD

**Issue by vishnupriyaavp8** [DefectDojo/django-DefectDojo#5419]
### **Bug description**
1. Adding a child to a rule does not make any difference.
2. When Finding is created, Rule is applied thrice

### **Steps to reproduce**
1. Create a Rule with following specifications
![image](https://user-images.githubusercontent.com/54842012/141155739-85fb8c61-a8b2-43dc-977c-83c8caec4130.png)

2. Add Child as shown below
![image](https://user-images.githubusercontent.com/54842012/141155997-3950b173-6cfc-4397-bc08-3e70a9df1bd8.png)

3. Create Finding F4 with Verified=false 
![image](https://user-images.githubusercontent.com/54842012/141156483-f07a9cd1-d647-4f04-9567-da7932438c5b.png)

4. Create Finding F4 with Verified=true
![image](https://user-images.githubusercontent.com/54842012/141156589-b6c6a3c4-8e68-4291-9102-860cd0b9ead8.png)

5. Both Finding titles are updated
   _Dev appears thrice
![image](https://user-images.githubusercontent.com/54842012/141158721-649c1856-0b12-42c7-a2fe-ea3585aab5ce.png)

### **Expected behavior**
Only the Finding title with Verified=false should be updated
Only 1 _Dev should appear

### **Deployment method**
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

### **Environment information**
 - Operating System: Ubuntu 18.04
 - DefectDojo version: 2.4.1

### **Source Code Screenshot**
**master/dojo/rules/views.py**
![image](https://user-images.githubusercontent.com/54842012/141157692-fa0563cc-f1f5-45c2-bb83-9a4b9cdc5707.png)
child_rule.parent has been set
But, rule.child_rules has not been appended

**master/dojo/models.py**
![image](https://user-images.githubusercontent.com/54842012/141160395-f3cdd78e-6cca-473e-9228-1cb9abd72ba3.png)
This section of code runs 3 times when New Finding is created

**Comment by valentijnscholten** [comment]
The rules framework is no longer maintained and might be removed in the future unless someone steps up to take ownership. For now I'm closing this issue. 
![image](https://user-images.githubusercontent.com/4426050/141169398-28b3f98c-abc5-4404-97ef-09f5b20538e5.png)

**Comment by vishnupriyaavp8** [comment]
> The rules framework is no longer maintained and might be removed in the future unless someone steps up to take ownership. For now I'm closing this issue. ![image](https://user-images.githubusercontent.com/4426050/141169398-28b3f98c-abc5-4404-97ef-09f5b20538e5.png)

Rules is a wonderful feature when we want to accept risk in findings based on conditions in present and future. Requesting this enhancement.
