### ISSUE TITLE
Trufflehog3 import error

### ISSUE THREAD

**Issue by httpnotonly** [DefectDojo/django-DefectDojo#5422]
**Bug description**
Trying import a report from Trufflehog3:2.0.4, 3.0.1, 3.0.3 and see this 
`An exception error occurred during the report import:'reason'`

**Steps to reproduce**
1. Scan any project with trufflehog3 and get more that 10 findings
2. Import the report 
3. See error `An exception error occurred during the report import:'reason'`

**Expected behavior**
No error

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Screenshots**
![image](https://user-images.githubusercontent.com/38507289/141203430-0277b2a6-3e42-4c6b-98b4-e5dbf2fc7566.png)

**Comment by httpnotonly** [comment]
![image](https://user-images.githubusercontent.com/38507289/141276239-d2177e71-8545-4a79-bc4b-5c52e5258836.png)

**Comment by valentijnscholten** [comment]
Can you provide a (redacted) sample report to reproduce please?

**Comment by StefanFl** [comment]
merged in dev for release 2.5.0
