### ISSUE TITLE
Integration tests are not running anymore properly and override local_settings.py

### ISSUE THREAD

**Issue by StefanFl** [DefectDojo/django-DefectDojo#5424]
**Bug description**

At first the integration tests didn't run because they need write access to `dojo/settings/local_settings.py` and `dojo/settings/settings.py`. Because I didn't know which user I did `chmod ugo+w` for these files. We need a documentation what is the best way to deal with this.

Running the integration tests twice in a row doesn't work anymore, because `dojo/settings/local_settings.py` gets overriden with `USER_PROFILE_EDITABLE=Frue`. When you want to run the integration_tests again, the initializer complains with `NameError: name 'Frue' is not defined`

Third problem is overriding `dojo/settings/local_settings.py`. I had some local settings for my development environment in there, that are now gone. I don't want to copy that file all the time from another place when running different kinds of tests.

**Environment information**
 - Operating System: Ubuntu 20.04 with docker compose
 - DefectDojo version (see footer) or commit message: most recent dev branch

**Comment by StefanFl** [comment]
@dsever Please can you have a look at this? I think these issues have been introduced with #5275

**Comment by StefanFl** [comment]
Just seen #5401 which already addresses one of my three issues.

**Comment by dsever** [comment]
For your local test you can just promote `dojo/settings/` to be writable to anyone on your local disk, because in other hand as is in the docker compose, it uses your local permissions.

**Comment by dsever** [comment]
Sorry @StefanFl  I had impression that it is already fixed by: https://github.com/DefectDojo/django-DefectDojo/pull/5397/commits/7f1f2dc9da80a72c2ef70df12a1cf3f822858b16 

But looks like author decided to rollback this fix...So I can fix it right away

**Comment by valentijnscholten** [comment]
> At first the integration tests didn't run because they need write access to `dojo/settings/local_settings.py` and `dojo/settings/settings.py`. Because I didn't know which user I did `chmod ugo+w` for these files. We need a documentation what is the best way to deal with this.

It's hardcoded to user `1001`, but https://github.com/DefectDojo/django-DefectDojo/pull/5432 allows for a build arg to configure the desired uid (probably `1000` :-))

**Comment by valentijnscholten** [comment]
@dsever If you turn `USER_PROFILE_EDITABLE` into a `System_Setting` we can use a more normal testing approach.

**Comment by IUVSARINA2l1** [comment]
> **Bug description**
> 
> At first the integration tests didn't run because they need write access to `dojo/settings/local_settings.py` and `dojo/settings/settings.py`. Because I didn't know which user I did `chmod ugo+w` for these files. We need a documentation what is the best way to deal with this.
> 
> Running the integration tests twice in a row doesn't work anymore, because `dojo/settings/local_settings.py` gets overriden with `USER_PROFILE_EDITABLE=Frue`. When you want to run the integration_tests again, the initializer complains with `NameError: name 'Frue' is not defined`
> 
> Third problem is overriding `dojo/settings/local_settings.py`. I had some local settings for my development environment in there, that are now gone. I don't want to copy that file all the time from another place when running different kinds of tests.
> 
> **Environment information**
>  - Operating System: Ubuntu 20.04 with docker compose
>  - DefectDojo version (see footer) or commit message: most recent dev branch

Won't log I server

**Comment by dsever** [comment]
> @dsever If you turn `USER_PROFILE_EDITABLE` into a `System_Setting` we can use a more normal testing approach.

If tests are only criteria then we can use System_Settings(Selenium)/API to change the parameters. But there should be clear a logic/rule what is in the System_Settings and what will be preserved in file, for the sake of users.

To be honest I would like to see as much as possible within System_Settings, like SMTP, IDP setup,...to be able to change the most of things without  need to respin django/celery pods.

**Comment by valentijnscholten** [comment]
Yeah, we had some discussions about it and I think the conclusion was that the low level sysadmin / devops settings should be in `settings.dist.py` and the settings for defect dojo admins / staff users should be in `System_Settings`. But it's not a 100% clear definition. It's possible to write a unit test instead of an integration test. The unit test can work against the view method and check if it rejects the edit when disabled. And you could check the html response to see if the fields are disabled or if there is a text on screen. With unit tests you can override settings via the @override_settings decorator.

**Comment by dsever** [comment]
@valentijnscholten I'm aware of that, and I wanted to use it in same way how @StefanFl  is using patches for his work on authentication, but keep in mind integration test are executed remotely, and it is not possible to patch configuration remotely (only by API).

That means, Selenium part needs to be added to unit tests as well.

I would be really happy, if user interface can be testes as part of unit test :)

**Comment by valentijnscholten** [comment]
For now you could just call the backend views from the unit tests and check the response code and html. I do the same in `test_import_reimport.py`

**Comment by dsever** [comment]
Ok, I will try to find some time slot to try it out.

**Comment by StefanFl** [comment]
Will be solved with #5611

**Comment by prakashar11** [comment]
Not sure whether it is related; but I was trying to run DefectDojo in my local environment with some model changes. Migrations kept failing with permission error and I had to add this line in Dockerfile.django along with other chown & chmod statements. Adding this line also helped in running unit tests

`chown -R ${uid} /app/dojo/db_migrations && \`
