### ISSUE TITLE
New permission model doesn't allow to create multiple groups containing the same Product Type

### ISSUE THREAD

**Issue by psbelin** [DefectDojo/django-DefectDojo#5437]
**Bug description**
When using the new permission model, it's not possible to create multiple groups containing the same Product Type.

**Steps to reproduce**
1. Go to '/group'
2. Click on `New Group`
3. Set a name, assign no global role and click Submit
4. In Product Type groups (under /group/`group-number`) click `Add Product Types` 
5. Select a Product Type, assign it a Role and click Submit
6. Repeat the process from steps 1 to step 5 selecting the same Product type
7. See error (the product type is not added to the new group)

**Expected behavior**
A Product Type should be assigned to multiple groups in order to control the access within the Product Type using different profiles: pentester, administrator, auditor...

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/3503207/141459512-2b73023c-63cf-4f44-b869-67d8dc82987b.png)

**Additional context** (optional)
@StefanFl confirmed via Slack that the issue could be reproduced with his settings.

**Comment by StefanFl** [comment]
merged for release 2.5.0
