### ISSUE TITLE
JIRA: Support resolutions for False Positive, Risk Accepted, Out of Scope, etc.

### ISSUE THREAD

**Issue by zakrush** [DefectDojo/django-DefectDojo#5448]
**Is your feature request related to a problem? Please describe**
Discussion here
https://owasp.slack.com/archives/C2P5BA8MN/p1635238884057600 
third point

When I change finding to False Positive for ex., and push to jira, Into Jira finding have Done mitigated(not False Positives).  The DD send always "Done" mitigation.

**Describe the solution you'd like**
If finding is changed to False Positive or Risk Accepted, it should to be pushed Jira with the same resolutions.

**Comment by valentijnscholten** [comment]
Currently JIRA doesn't send any resolution to JIRA, so JIRA uses the default resolution which is 'Done' for default workflows, but can be something else in other workflows/instance. I think it could be helpful if we add resolution support to our JIRA integration.

**Comment by Ma1tobiose** [comment]
Same question, if a false positive issue is pushed from Dojo to Jira, will there be a field in the Jira task to distinguish between Done and False Positive?
