### ISSUE TITLE
package.json script part

### ISSUE THREAD

**Issue by maennel** [DefectDojo/django-DefectDojo#545]
Please use the following template when submitting issues:

### Issue Type 
- [ ] Bug
- [ ] Enhancement
- [x] Question

### Description

Is there a specific reason, the (following) script part in ``package.json`` is required? https://github.com/DefectDojo/django-DefectDojo/blob/5849604151c508854c2112a3b5e46957f1ea0468/components/package.json#L37

From what I can [find](https://github.com/DefectDojo/django-DefectDojo/search?utf8=%E2%9C%93&q=yarn_components&type=), it creates a symlink called ``yarn_components`` to the directory ``node_modules/@yarn_components``. This symlink is consumed in the ``settings.dist.py`` file (and an ansible template) for collecting static files. 

Problems can arise, if ``yarn install`` is run including the ``--ignore-scripts`` flag (https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-ignore-scripts). 
Another source of problems can be, if systems with different symlink behaviour are used (Windows, some PaaS platforms, depending on their API).

If we don't really need the symlink, I'd suggest to remove that part of the package.json file and to refer to yarn static files directly via ``node_modules/@yarn_components``.

Any thoughts on this? 

Thanks

**Comment by aaronweaver** [comment]
@maennel That file was automatically generated with a migration script from bower to yarn so most likely that can be removed.

**Comment by maennel** [comment]
@aaronweaver Thanks, good to hear. Will open a PR.
