### ISSUE TITLE
Detectsecretscan not showing the description field in the UI

### ISSUE THREAD

**Issue by BhaskiBuzz** [DefectDojo/django-DefectDojo#5453]
**Bug description**
After uploading the json report from detect-secrets scan tool, the description section of the findings shows empty in the defectdojo UI.
**Steps to reproduce**
1. Get the json report from detect-secret scan.
2. upload the report into defectdojo by selecting Detect-secret Scan type.
3. Open any issue and see the description section. It shows empty.
**Expected behavior**
The description field should be read from the json report and should be written in the description section of defectdojo.

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose

**Environment information**
Dojo-version using: v2.2.1

**Screenshots**
![image](https://user-images.githubusercontent.com/26956032/141922670-9d09f53a-914e-4c01-b6cd-2a472ef95384.png)

**Comment by valentijnscholten** [comment]
Can you provide a sample scan report

**Comment by valentijnscholten** [comment]
This is fixed in 2.3.0, please update.
https://github.com/DefectDojo/django-DefectDojo/pull/5092

**Comment by BhaskiBuzz** [comment]
Hi @valentijnscholten 
I can see the below code from the fix commits. It looks like the value for the description filed contains only the filename, line and type which are reading from the json report. But it's not reading the actual description field value from the json report.  

code:
                description = "Detected potential secret with the following related data:\n"
                description += "**Filename:** " + file + "\n"
                description += "**Line:** " + line + "\n"
                description += "**Type:** " + type + "\n"

Sample Report json file content is like below. I need the description field value from the below json file to be viewed in defectdojo description section.
sample report:
`{
  "version": "1.1.0",
  "plugins_used": [
    {
      "name": "ArtifactoryDetector"
    },
    {
      "name": "AWSKeyDetector"
    },
    {
      "name": "AzureStorageKeyDetector"
    },
    {
      "name": "Base64HighEntropyString",
      "limit": 4.5
    },
    {
      "name": "BasicAuthDetector"
    },
    {
      "name": "CloudantDetector"
    },
    {
      "name": "HexHighEntropyString",
      "limit": 3.0
    },
    {
      "name": "IbmCloudIamDetector"
    },
    {
      "name": "IbmCosHmacDetector"
    },
    {
      "name": "JwtTokenDetector"
    },
    {
      "name": "KeywordDetector",
      "keyword_exclude": ""
    },
    {
      "name": "MailchimpDetector"
    },
    {
      "name": "NpmDetector"
    },
    {
      "name": "PrivateKeyDetector"
    },
    {
      "name": "SlackDetector"
    },
    {
      "name": "SoftlayerDetector"
    },
    {
      "name": "SquareOAuthDetector"
    },
    {
      "name": "StripeDetector"
    },
    {
      "name": "TwilioKeyDetector"
    }
  ],
  "filters_used": [
    {
      "path": "detect_secrets.filters.allowlist.is_line_allowlisted"
    },
    {
      "path": "detect_secrets.filters.common.is_ignored_due_to_verification_policies",
      "min_level": 2
    },
    {
      "path": "detect_secrets.filters.heuristic.is_indirect_reference"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_likely_id_string"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_lock_file"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_not_alphanumeric_string"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_potential_uuid"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_prefixed_with_dollar_sign"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_sequential_string"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_swagger_file"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_templated_secret"
    }
  ],
  "results": {
    "secrets.txt": [
      {
        "type": "Secret Keyword",
        "filename": "secrets.txt",
        "hashed_secret": "91ae931c66910752ae180575854a7dbbf43ba047",
        "is_verified": false,
        "line_number": 1,
	"description":"abcdefghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh"
      }
    ]
  },
  "generated_at": "2021-11-15T11:21:05Z"
}`

Thanks.
Bhaskar.

**Comment by StefanFl** [comment]
I take it

**Comment by StefanFl** [comment]
@BhaskiBuzz How do you get a report with the `description` field? I have just tested `detect-secrets` with the most recent version 1.1.0 and I didn't get the field `description` in the report.

**Comment by BhaskiBuzz** [comment]
hi @StefanFl,

I too didn't get the field description in the report. Need to check if there is any way to configure the tool to get the description field as well. 
As per the json sample report in the link "https://defectdojo.github.io/django-DefectDojo/integrations/import/#detect-secrets", I thought that the defectdojo will support the description field as well along with other attributes. So I have manually added the description field to the report and tried uploading. 

For the time being, I am able to fix this issue like below.
code:
description = "Detected potential secret with the following related data:\n" + item.get('description') + "\n"
description += "Filename: " + file + "\n"
description += "Line: " + line + "\n"
description += "Type: " + type + "\n"

Thanks.

**Comment by StefanFl** [comment]
DefectDojo imports reports how they are generated of the scan tools, manual additions are not supported. As far as I can see all relevant information from the original report gets imported.
