### ISSUE TITLE
Add date preset for the last day for filtering findings

### ISSUE THREAD

**Issue by DImaste** [DefectDojo/django-DefectDojo#5465]
Hello, it would be great if defect dojo had the last day preset for filtering findings. We want to use the filter to calculate daily KPIs.

**Comment by valentijnscholten** [comment]
Where would you like to see it (search, api, ...) what is your definition of 'last day'? There is a 'today' filter, do you mean a 'yesterday' filter?

**Comment by DImaste** [comment]
@valentijnscholten  I mean the last 24hours filter. I'd like to see it both in API and metrics filtering. 
Thank you!

**Comment by valentijnscholten** [comment]
It could be added, but could you elaborate on the usecase? I think filtering by 'today' is more common compared to 'last 24 hours` which would result in some kind of running window for the date range.

**Comment by DImaste** [comment]
Today is also possible. We want to use it for daily triage/review stats by requesting this data via API with a scheduled script.
