### ISSUE TITLE
django-doctor findings

### ISSUE THREAD

**Issue by django-doctor** [DefectDojo/django-DefectDojo#5513]
`Product_Type` is referenced in the file, but not defined anywhere:

https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/db_migrations/0066_django_tagulous.py#L41

**Comment by valentijnscholten** [comment]
Good find. This case is hard to test as I think it's impossible to create products now with `prod_type_id==0`.
Can you try again with the changes in https://github.com/DefectDojo/django-DefectDojo/pull/5514 ?

**Comment by django-doctor** [comment]
good fix :)

FWIW I found this problem while testing new features we're writing at https://django.doctor/ (our test rig runs all our checkers against 666 codebases, your included).


Looking at https://django.doctor/DefectDojo/django-DefectDojo I see also see a few more issues (and some false positives which you can ignore). Example of something that probably wants attention is duplicate url name: https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/notifications/urls.py#L7

I'll leave that in your hands

**Comment by valentijnscholten** [comment]
https://django.doctor/rsumner31/django-DefectDojo

**Comment by django-doctor** [comment]
PRs solve the problem so closing this issue :)

FYI you can prevent similar issues by using Django Doctor on GitHub https://github.com/marketplace/django-doctor/
