### ISSUE TITLE
Authentication via OAuth2/SAML2

### ISSUE THREAD

**Issue by hkelley** [DefectDojo/django-DefectDojo#5516]
Okta setup notes that might improve the documentation:

- SOCIAL_AUTH_REDIRECT_IS_HTTPS = True was mandatory for me.  When I didn't use it,  a ":443" was appended to back of the parameters when returning the state code, and thus confusing DefectDojo.   I don't know if this was Okta or my nginx config, but simpler to use HTTPS and avoid any extra redirects.
- Sign-in redirect URI in Okta app setup should be the user's URL to the DefectDojo app,  not http://localhost:8000.   
- In some Okta tenants,  the trailing "/default" in `` DD_SOCIAL_AUTH_OKTA_OAUTH2_API_URL`` is invalid.   Try it without that if you get a 400 error about the endpoint/resource not being available on the server.   I think this a difference between "corporate" and "consumer" Okta tenants, but I forget the licensing specifics.

**Comment by valentijnscholten** [comment]
Thanks, could you do a PR with proposed changes? (see `/docs` folder)

**Comment by hkelley** [comment]
PR #5550
