### ISSUE TITLE
Fixtures are not found when migrating to 1.2.9 from 1.2.6.

### ISSUE THREAD

**Issue by maskimfr** [DefectDojo/django-DefectDojo#552]
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description

Fixtures are not found when migrating to 1.2.8 from 1.2.6.

### Operating System 
Ubuntu 16.04, fully patched

### Install

- [x] setup.bash
- [ ] docker

### Steps to Reproduce
The documentation for migration to 1.2.9 (https://defectdojo.readthedocs.io/en/latest/upgrading.html) states that the following commands should be launched: 
./manage.py loaddata dojo/fixtures/benchmark_type 
./manage.py loaddata dojo/fixtures/benchmark_category 
./manage.py loaddata dojo/fixtures/benchmark_requirement

An error message indicates that the fixtures are not found, for example:
CommandError: No fixture named 'benchmark_category' found.

### Solution
The resolv the issue, rename the fixtures files in dojo/fixtures/ to add .json at the end:
benchmark_category -> benchmark_category.json
benchmark_requirement -> benchmark_requirement.json
benchmark_type -> benchmark_type.json

**Comment by aaronweaver** [comment]
Fixed in dev
