### ISSUE TITLE
Multi-arch images

### ISSUE THREAD

**Issue by tiagoposse** [DefectDojo/django-DefectDojo#5525]
**Is your feature request related to a problem? Please describe**
I tried setting up an instance of defectdojo in my local k8s cluster on some arm SBC, only to realise current Docker images are only for amd64. 

**Describe the solution you'd like**
Release images as multi arch instead of just amd.

**Describe alternatives you've considered**
I have attempted to build the images myself. This should be possible, but would prefer not have to maintain. 

**Other context**
Unfortunately I couldn't find any reference as to what ci/cd is being used, so I can't attempt a PR

**Comment by valentijnscholten** [comment]
We're using GitHub actions, see `.github/workflows` folder. We may accept a PR if supporting multiple archs doesn't give us to many extra maintenance.

**Comment by rc-mattschwager** [comment]
Hi there, I'd like to purpose re-opening this issue. I'd also like to run DefectDojo on ARM architectures, specifically `arm64`. I initially noticed this issue when I was trying to run DefectDojo on AWS' new [M6g instances](https://aws.amazon.com/ec2/instance-types/m6g/). Also, as noted here: https://github.com/DefectDojo/django-DefectDojo/pull/6302#issuecomment-1133489343, this means DefectDojo will fail to run on Apple's new M1 and M2 processors, which are becoming more and more widespread. Running on ARM will become more and more common, it'd be great to support it in DefectDojo!

Thanks for the great OSS project!

**Comment by olfway** [comment]
Can we have this issue reopen, please, or should we create a new one?
