### ISSUE TITLE
Nessus: merge importers

### ISSUE THREAD

**Issue by kiblik** [DefectDojo/django-DefectDojo#5526]
**Is your feature request related to a problem? Please describe**
There are two Nessus importers: `nessus` and `nessus was`. Both are using almost the same parsing methods so there is redundancy which is harder to maintain.

**Describe the solution you'd like**
Merge two them

**Describe alternatives you've considered**
I don't know about the alternative.

**Additional context**
https://github.com/DefectDojo/django-DefectDojo/pull/5471#issuecomment-977904248

**Comment by damiencarol** [comment]
@kiblik our current parser model support having one parser that manage both. I think this could be done. I can take a look.
