### ISSUE TITLE
reimport with files is broken

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#5576]
No unit test coverage for reimport it seems.

![image](https://user-images.githubusercontent.com/4426050/145196456-ba764081-4aa9-478e-8842-b10bd435b3e1.png)

**Comment by damiencarol** [comment]
I should take this one as it's my fault 😓

**Comment by valentijnscholten** [comment]
fixed the bug, unit test still needed.

**Comment by damiencarol** [comment]
@valentijnscholten will add in https://github.com/DefectDojo/django-DefectDojo/pull/5632

**Comment by valentijnscholten** [comment]
fixed in dev / 2.6.0
