### ISSUE TITLE
POST findings: error suggests wrong values

### ISSUE THREAD

**Issue by t3h2mas** [DefectDojo/django-DefectDojo#558]
### Issue Type 
- [x] Bug

### Description
When POSTing to findings with the keys `title, description, engagement, product, test, reporter, impact, mitigation` but not `severity`, the error suggests choosing an option from the wrong list

the response:
`{"findings": {"severity": ["Select valid choice: In Progress, On Hold, Completed"]}}`

As far as I can tell, the 'valid choices' should be 'Low, Medium, High' etc.

### Steps to Reproduce
post to findings using the api playground or whatever method you'd like
example body:
```
{
"title": "testing the api",
"description": "foopy",
"engagement": "/api/v1/engagements/1/",
"product": "/api/v1/products/1/",
"test": "/api/v1/tests/1/",
"reporter": "/api/v1/users/1/",
"impact": "fdas",
"mitigation": "asdf"
}
```

**Comment by aaronweaver** [comment]
I'd recommend trying out the new v2 API as this is one of the reasons we are moving to the new version. V2 should be in shortly or you can try it out in the dev branch.

**Comment by t3h2mas** [comment]
Great, wasn't aware of v2.
