### ISSUE TITLE
Allow a Reader user to add Notes

### ISSUE THREAD

**Issue by Juu** [DefectDojo/django-DefectDojo#5581]
In our use case, we want to allow developers to see Findings on DefectDojo.
That's why we assigned them Role Reader, as we don't want them to edit or close the Findings by themselves.

However, we'd like to allow them to add Notes on the Findings (why not on Engagements/Tests), which they cannot do.
If we assign them Role Writer, they can add Notes but also edit/close the Findings.

We tried to assign User permission `dojo | notes | Can add notes` in `/admin`, but that doesn't seem to change anything.

Could you consider allowing a Reader adding Notes? Adding a new Role between Reader and Writer?
Is our use case too specific actually?

Thanks for your insights.

**Comment by StefanFl** [comment]
Hi @Juu, I understand your case, but I am not sure how to solve it. Adding a new role would technically be easy, but then we might get more and more roles. The ultimate solution would be to make roles configurable and let users define roles with the available permissions. But that's more work and definitely not be part of the next release. 

I will think about it a bit longer 😃

**Comment by valentijnscholten** [comment]
I was thinking the same as Stefan, making it configurable like JIRA would be cool, but also adds complexity. Personally I could also live with allowing a `Reader` to post notes. No harm in that, except for possible SPAM maybe?

**Comment by StefanFl** [comment]
You're right Valentijn, there is really no harm in allowing Readers to add notes.

**Comment by StefanFl** [comment]
merged for release 2.6.0
