### ISSUE TITLE
import_scan_results failing with 404 for certain VCG files

### ISSUE THREAD

**Issue by niprog** [DefectDojo/django-DefectDojo#560]
Please use the following template when submitting issues:

### Issue Type 
- [ X] Bug

### Description
Importing a VCG xml scan result is generating a 404. Only happens with a specific file and I've managed to track down that if I change one line in a <CodeLine> element from "and the amount - To be Esm" to "and the amount. To be Esm" the removal of the dash allows the import to progress to further in the file. I'm assuming something in vcg parser is unhappy but a single dash seems a strange thing to fall over on. Will work through parser code but appreciate any experience of the issue people may have. 

### Operating System 
Docker-Compose dojo from
https://github.com/aaronweaver/docker-DefectDojo
Master branch with no local changes

### Install

- [X ] docker

### Steps to Reproduce
Cannot share VCG file

### Sample Scan File (if applicable)
Cannot share VCG file

### Console Logs (optional)
No logs generated when viewed in docker-compose logs

**Comment by aaronweaver** [comment]
@niprog Do you have a file you can share?

**Comment by niprog** [comment]
@aaronweaver Hi. Its difficult as obviously it contains vulnerabilities of a production system. I'm worried that if I anonymize it then it masks or deflects from the actual issue. I'll try and sanitise it while still getting the same error and attach.

**Comment by aaronweaver** [comment]
@niprog Able to provide an example? Which element in the file is causing the issue?
