### ISSUE TITLE
`close_old_findings` only from findings with the same `service`

### ISSUE THREAD

**Issue by rucciva** [DefectDojo/django-DefectDojo#5618]
**Is your feature request related to a problem? Please describe**
I'm currently trying to import scans from a product which in reality consisted of multiple repository and multiple services. I modeled this product as a product in defect dojo, which will have many CI/CD engagements as many as CI/CI job that run triggered by changes in repositories or services of the product. I enabled deduplication on product level and in each scans upload enabled the `close_old_findings` flag.  I set the `service` attribute of scans upload to repositories url or service base url which the scans is targeted too. Deduplications across many engagements work great. The problem is in `close_old_findings`, which will close scans from older engagements which might not includes scan reports from the same repository or service.

**Describe the solution you'd like**
add filter by `service` in [here](https://github.com/DefectDojo/django-DefectDojo/blob/2796e2cbd532edc3c2d270fb215b422786d977d3/dojo/importers/importer/importer.py#L188-L200) so that product that has many repositories or services can still works with `close_old_findings`

**Describe alternatives you've considered**
the alternative would be to have one engagement only for each repository or service being scanned and enable engagement level deduplication. But that would seem weird since the engagement will never be closed.

another alternative is to have one product per repository or service. the downside will be losing real product level metrics in `product/{id}/metrics` page

**Additional context**
Add any other context, screenshots, sketch, code snippet, etc. about the feature request here.

**Comment by StefanFl** [comment]
Thank you @rucciva for bringing this to our attention. I will have a look at it.

**Comment by damiencarol** [comment]
@StefanFl @rucciva could it be better to and `service` attribute as a possible attribute for de-duplication?

**Comment by rucciva** [comment]
> @StefanFl @rucciva could it be better to add `service` attribute as a possible attribute for de-duplication?

From what i read [here](https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/settings/settings.dist.py#L1082),  `service` has been used in de-duplication, but only if dedup is done based on `hash_code` in .

But i personally think that there should be one more explicit abstraction under _engagement_ that denotes the component being scanned (repository, service, or any other kind of component) where de-duplication and close_old_findings should be limited to. De-duplication and close_old_findings across scans only make sense when the things being scanned is the same thing, while product and engagement it self is too broad for that.

**Comment by StefanFl** [comment]
Closing old findings have to acknowledge the `service` attribute like deduplication does already. This is why I think that's a bug instead of an enhancement.

**Comment by StefanFl** [comment]
merged for release 2.6.0
