### ISSUE TITLE
only the userid SAML attribute is mapped to the user

### ISSUE THREAD

**Issue by BhaskiBuzz** [DefectDojo/django-DefectDojo#5619]
With SAML SSO login, only the userid is getting mapped but not the other fields like firstname, lastname and email. 

I am using v. 2.4.1 ( release mode ).

SAML settings in the settings.dist.py
```
# Allow to create user that are not already in the Django database
    DD_SAML2_CREATE_USER=(bool, True),
    DD_SAML2_ATTRIBUTES_MAP=(dict, {
        # Change Email/UserName/FirstName/LastName to corresponding SAML2 userprofile attributes.
        # format: SAML attrib:django_user_model
        'Email': 'email',
        'UserName': 'userid',
        'Firstname': 'firstname',
        'Lastname': 'lastname'
    }),
```

We have enable sso login and auto create user. When the user logged in, in the SAML response, we can see all the valid values for email, userid, firstname and lastname. But when we checked the auto created user details using API/UI, only the username field got mapped. for other attibutes the values are null like below.

"first_name": "",
"last_name": "",
"email": "",

**Comment by dsever** [comment]
You have to map properly  your saml attribs to djsngo. There is section in doc that explains it

**Comment by renatosazup** [comment]
I have the same problem with SSO login

Defectdojo version:

![Screenshot_21](https://user-images.githubusercontent.com/88499872/146570071-ca07cdd3-46b3-4dc2-9faf-ee3a41fd7570.png)


Response SAML2: 

![Screenshot_19](https://user-images.githubusercontent.com/88499872/146569588-9d9d8e6b-252d-43d8-8a63-15437bf47842.png)

Environment DD_SAML2_ATTRIBUTES_MAP
![Screenshot_20](https://user-images.githubusercontent.com/88499872/146569840-97a09567-109d-4b90-a93f-de575be06b0f.png)

Mysql:

![Screenshot_22](https://user-images.githubusercontent.com/88499872/146570508-b2c58ad6-bfb9-4992-b84f-7ca7c2f31e62.png)

**Comment by dsever** [comment]
`DD_SAML2_ATTRIBUTES_MAP: Email=email,FirstName=first_name,LastName=last_name`

Can you try with this

**Comment by valentijnscholten** [comment]
Not sure the format of your environment variable is correct, check https://newbedev.com/how-to-store-a-python-dictionary-as-an-environment-variable

**Comment by mtesauro** [comment]
Another option is to put those SAML values in local_settings.py as the non-DD_ equivalents as this avoids strangeness when converting from Bash/environmental variables to Python (easy to get wrong)

If you're using local_settings.py, then drop them there as their Python equivalents. You can see an example of the ENV variable being set to an Python variable at https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/settings/settings.dist.py#L783 or:
`SAML_ATTRIBUTE_MAPPING = saml2_attrib_map_format(env('DD_SAML2_ATTRIBUTES_MAP'))`

So `SAML_ATTRIBUTE_MAPPING` can be set in local_settings.py directly as a native Python dict then you don't need to set `DD_SAML2_ATTRIBUTES_MAP` at all

**Comment by BhaskiBuzz** [comment]
Hi @dsever @valentijnscholten 

Below are the attributes from SAML and mapping to dojo user profile. It is not working. only the username filed value is there in the user details. And this value is populated because of the setting DD_SAML2_CREATE_USER=(bool, True). So, it seems the mapping of SAML attributes is not working. 

SAML Attributes
` <saml:Attribute Name="firstname"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                                     xsi:type="xs:string"
                                     >*******</saml:AttributeValue>
            </saml:Attribute>
<saml:Attribute Name="userid"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                                     xsi:type="xs:string"
                                     >********</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="email"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                                     xsi:type="xs:string"
                                     >********</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="lastname"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                                     xsi:type="xs:string"
                                     >********</saml:AttributeValue>
            </saml:Attribute>`

Mapping in the dojo settings.dist.py
` DD_SAML2_CREATE_USER=(bool, True),
    DD_SAML2_ATTRIBUTES_MAP=(dict, {
        # Change Email/UserName/FirstName/LastName to corresponding SAML2 userprofile attributes.
        # format: SAML attrib:django_user_model
        'email': 'email',
        'userid': 'username',
        'firstname': 'first_name',
        'lastname': 'last_name'
    }),`

**Comment by dsever** [comment]
You should not change things inside of settings.dist.py as @mtesauro  said, you can use  local_settings.py to rerwrite default values. 

Another thing I think  you are missing is: https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/settings/settings.dist.py#L133 -> True (https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/settings/settings.dist.py#L799)

In other case SAML SP will ignore attributes that are not defined by urn.  

Were do you run your DD, docker compose or k8s?

**Comment by BhaskiBuzz** [comment]
Hi @dsever 

I do run DD using docker-compose. 
Making the below attribute to true worked fine for me with the above mentioned SAML attribute mapping. 
https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/settings/settings.dist.py#L133 -> True

Thank you so much.
