### ISSUE TITLE
Assertion Consumer URL

### ISSUE THREAD

**Issue by pgabriel10** [DefectDojo/django-DefectDojo#5629]
What is the Assertion Consumer URL used to set up SAML for defect dojo ? 
Doc ( https://defectdojo.github.io/django-DefectDojo/integrations/social-authentication/ )  said :

DD_SAML2_ASSERTION_URL: not necessary any more - automatically generated

but i can´t find it.

**Comment by dsever** [comment]
Navigate to  `DD_FQDN/saml2/metadata/` there it is visible

**Comment by pgabriel10** [comment]
thanks !
