### ISSUE TITLE
Ubuntu 18.04 Server and ERROR: Version in "./docker-compose.yml" is unsupported ...

### ISSUE THREAD

**Issue by noloader** [DefectDojo/django-DefectDojo#5656]
**Bug description**
I have a Ubuntu 18.04 LTS Server, x86_64, fully patched. I am trying to follow [Running with Docker Compose](https://github.com/DefectDojo/django-DefectDojo/blob/dev/readme-docs/DOCKER.md) to test DefectDojo.

At the `docker-compose build` step, I am encountering an error:

```
$ docker-compose build
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

**Expected behavior**
I expect no problems at this point.

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System:
     ```
     $ lsb_release -a
     No LSB modules are available.
     Distributor ID:	Ubuntu
     Description:	Ubuntu 18.04.6 LTS
     Release:	18.04
     Codename:	bionic
     ```
 - DefectDojo version (see footer) or commit message: [use `git show -s --format="[%ci] %h: %s [%d]"`]
     ```
     $ git show -s --format="[%ci] %h: %s [%d]"
     [2021-12-08 11:55:43 +0100] ba1a41521: Fix typo (#5575) [ (HEAD -> master, origin/master, origin/HEAD)]
     ```
     And maybe:
     ```
     $ docker-compose --version
     docker-compose version 1.17.1, build unknown
     $ grep 'version:' docker-compose.yml 
     version: '3.7'
     ```
**Logs** 
Use `docker-compose logs` (or similar, depending on your deployment method) to get the logs and add the relevant sections here showing the error occurring (if applicable).

```
$ docker-compose logs
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

**Sample scan files**
N/A

**Screenshots**
N/A

**Additional context** (optional)
None that I can think of, but I have no experience with DefectDojo and nearly no experience with Docker.

**Comment by damiencarol** [comment]
It seems that your version of Docker compose is old. Are you able to update it?
https://www.digitalocean.com/community/tutorials/how-to-install-docker-compose-on-ubuntu-18-04

**Comment by valentijnscholten** [comment]
Please read the docker readme, especially the first line of the first paragraph: https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/DOCKER.md#prerequisites

**Comment by noloader** [comment]
Thanks @damiencarol and @ valentijnscholten.

We are using Ubuntu 18.04.6 LTS. Canoncial provides support for the release through 2023. It is an approved image for the organization.

Ubuntu 18.04 provides the following `docker-compose`. Ubuntu's governance does not allow them to jump to bleeding edge components. That means Ubuntu is fixed at 1.17 (plus hand-ported bug fixes).

```
$ apt show docker-compose
Package: docker-compose
Version: 1.17.1-2
Priority: optional
Section: universe/admin
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
```

**Comment by valentijnscholten** [comment]
If you cannot use our docker-compose based install, there is the `godojo` alternative install method as listed in the README: https://github.com/DefectDojo/django-DefectDojo#supported-installation-options

Alternatively you could try and make it work with an older docker compose format and docker compose version, but I doubt you'll be able to backport all features used.

Not sure what your corporate policies are, but I think upgrading docker by installing from the official Docker APT repositories is very common and is what I would suggest if you cannot upgrade to 20.04LTS: https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository

**Comment by damiencarol** [comment]
@noloader as a work-around could you just remove the `version` attribute to test if it's ok with an older version?
In the same time I'm checking what missing feature could be missing between this 2 versions.
