### ISSUE TITLE
dependency track: import project name and version from report

### ISSUE THREAD

**Issue by nibiwodong** [DefectDojo/django-DefectDojo#5666]
**Steps to reproduce**
1、config defectdojo apikey into dtrack platform
2、config a dtrack project  property, inorder to auto upload fpf to defectdojo
3、upload successed
4、but defectdojo only shows the vul name、pkgs、vul description, but no project name、project version
In this source code ,it shows that defectdojo only parse findings in fpf ,but not project info.
https://github.com/DefectDojo/django-DefectDojo/blob/2.4.1_hotfix/dojo/tools/dependency_track/parser.py

**Comment by valentijnscholten** [comment]
What do you mean by "Project Info". Are you referring to fields present in dependency track? Are these field present in the report? Can you provide a sample report that contains fields that are not imported? It sounds like you are pushing findings from within Dependency Track so it might be that dependency track itself is not setting the project name and version fields on the product?

**Comment by nibiwodong** [comment]
https://docs.dependencytrack.org/integrations/file-formats/
Here is dtrack fpf file format. It contains project name and version.
![image](https://user-images.githubusercontent.com/17465789/148072642-2a11f338-e76f-441d-9daf-c711b6ccb315.png)

Usually, dtrack project name is gitlab project name, dtrack version is git project branch or tag.

If defectdojo do not parse and store project name and version, maybe users have to config the project name and version into engagement name or engagement tag.

One product may have many gitlab project, so users may create many engagements.

**Comment by valentijnscholten** [comment]
Does dependency track use import or reimport? I assume import so creating a new Test inside the specified Engagment every time?
