### ISSUE TITLE
Missing comma resulting in unwanted string concatenation of filter

### ISSUE THREAD

**Issue by code-review-doctor** [DefectDojo/django-DefectDojo#5671]
**Bug description**

This tuple has a missing comma on line 1907 so `'sonarqube_issue'` gets concatenated with `'thread_id'`.

https://github.com/DefectDojo/django-DefectDojo/blob/ba1a415219ff20e8b4e909ef14f750de9b80297e/dojo/filters.py#L1906-L1910

The impact of this is Django tries to exclude a field called `'sonarqube_issuethread_id'` (which does not exist) and the `'sonarqube_issue'` `'thread_id'` fields are not excluded in the filter.

**Steps to reproduce**
NA

**Expected behavior**
Add a comma to the list like so `'sonarqube_issue',`

**Additional context** (optional)
I'm a [static analysis bot](http://codereview.doctor/) that detected this automatically

**Comment by valentijnscholten** [comment]
thanks @code-review-doctor

**Comment by StefanFl** [comment]
merged for release 2.6.0

**Comment by damiencarol** [comment]
this tool is really smart... and useful ^^

**Comment by code-review-doctor** [comment]
@damiencarol thanks!
