### ISSUE TITLE
Ms Teams Notification Shows Error Messsage When Closing From Jira

### ISSUE THREAD

**Issue by Roooodie** [DefectDojo/django-DefectDojo#5684]
Hello i having an issue with Defectdojo notification with Microsoft Teams.

**Bug description**
the notification message that appear in our microsoft channel is showing the error.
I've setting up and defectdojo integration with jira which can automatically close the finding in defectdojo when we're closing the ticket on jira.
the notification that had a problem is about Status changes from JIRA to defectdojo. when we close the finding in jira, the notification that got sent to our microsoft teams channel is showing this ex.
![image](https://user-images.githubusercontent.com/50097679/148177698-788dcc77-c6dc-4dff-bb5a-80b2a0ff3028.png)
"<class 'dojo.models.Finding'>: Testing High, Field 'environment' cannot be set. It is not on the appropriate screen, or unknown."
where Testing High is the finding name.

**Steps to reproduce**
1. Integrate Jira with Defectdojo
2. Create Webhook in Teams, and set it in Defectdojo
3. set system scope notification setting of finding status (Scan added) to on
2. Create finding and tick push to jira.
3. close the finding through Jira (if we close from defectdojo, the notification will be the correct one)
#update: on every pushing jira from defectdojo
4. Open the Microsoft Teams Channel.
5. See error

**Expected behavior**
i'm expecting that the notification will be correct as usual and shown that the the finding is closed by Jira.

**Deployment method** *(select with an `X`)*
- [ X ] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: CentOS 7
 - DefectDojo version 2.5.0

**Comment by valentijnscholten** [comment]
Looks like your JIRA project or instance doesn't have the environment field? But this error should only occur when creating issues not when closing issues, so I doubt this notification comes a finding/issue that was closed. It looks like an error from creating a JIRA issues. What do the logs say or the alerts in the DD UI?

**Comment by Roooodie** [comment]
looks like it's a miss from my side here ... you are right, it's from the Pushing a JIRA issues. cause of environment didn't exist in my project settings
![image](https://user-images.githubusercontent.com/50097679/148315264-abd9357d-d46a-4972-8758-8e0bc4e652d2.png)
i need to correct my steps to produce above on number 5. 
when i push to jira from Defectdojo it's showing the same error whether it's activate(open) or inactive(close) from defectdojo.

after i add the environment to my project, it's now shown another error
![image](https://user-images.githubusercontent.com/50097679/148322048-4eb5773d-937e-497d-950b-3d76e56d91a6.png)
do you have any clue on what's happening here?

**Comment by valentijnscholten** [comment]
Looks like an error on the JIRA side. JIRA is sometimes poor at error handling, sometimes it helps to inspect the JIRA server logs. I think that redacted url is a GET request so can be replayed by pasting into a browser address bar.
