### ISSUE TITLE
Rework sslyze 5 importer

### ISSUE THREAD

**Issue by kibernautas** [DefectDojo/django-DefectDojo#5686]
I have reworked the sslyze version 5 json importer and would like to commit it here.

**Comment by valentijnscholten** [comment]
Can you make a PR? https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/CONTRIBUTING.md

**Comment by kibernautas** [comment]
https://github.com/DefectDojo/django-DefectDojo/pull/5689
