### ISSUE TITLE
After the application is restarted, duplicate data in the queue cannot be judged

### ISSUE THREAD

**Issue by TriompheL** [DefectDojo/django-DefectDojo#5694]
**Slack us first!**
The easiest and fastest way to help you is via Slack. There's a free and easy signup to join our #defectdojo channel in the OWASP Slack workspace: [Get Access.](https://owasp-slack.herokuapp.com/)
If you're confident you've found a bug, or are allergic to Slack, you can submit an issue anyway.

**Be informative**
Please enter as much information as possible, otherwise we can't provide support. If possible upgrade to the latest release or dev version and try again.

**Bug description**
When I upload a bug that is very fast and causes the DefectDojo card owner, when I restart, the data that is queued up to determine whether it is duplicate will not be judged again.
![image](https://user-images.githubusercontent.com/27794837/148377395-d0be46ee-dcc2-4222-8e34-0bf7de6f6659.png)
I think the data in the queue that needs to be determined if it is repeated should be persisted, as with Kafka

**Steps to reproduce**
1、system setting enable the Delete duplicates 。
2. import many vul 
2、restart the defect dojo

**Expected behavior**

**Deployment method** *(select with an `X`)*
- [x] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo version (see footer) or commit message: [use `git show -s --format="[%ci] %h: %s [%d]"`]

**Logs** 
Use `docker-compose logs` (or similar, depending on your deployment method) to get the logs and add the relevant sections here showing the error occurring (if applicable).

**Sample scan files**
If applicable, add sample scan files to help reproduce your problem.

**Screenshots**

**Additional context** (optional)

**Comment by valentijnscholten** [comment]
Looks more like your restart didn't work correctly. What is in the logs? Please provide more details on the problem.
