### ISSUE TITLE
Useless code in the importer

### ISSUE THREAD

**Issue by damiencarol** [DefectDojo/django-DefectDojo#5714]
**Bug description**
Get ride of useless code

https://github.com/DefectDojo/django-DefectDojo/blob/d14696e576e31bc447645018d2d3aed558dd7ccd/dojo/importers/importer/importer.py#L54-L58

**Comment by damiencarol** [comment]
FYI @valentijnscholten

**Comment by valentijnscholten** [comment]
?

**Comment by damiencarol** [comment]
@valentijnscholten we already discussed about this piece of code. That's it

**Comment by StefanFl** [comment]
merged for release 2.7.0

**Comment by valentijnscholten** [comment]
I also changed the title of the PR, the titles are what ends up in the release note so I'd like to see us make an effort to make them clear and neutral.

**Comment by damiencarol** [comment]
yes, you're right
