### ISSUE TITLE
MariaDB/MySQL error with unique index

### ISSUE THREAD

**Issue by maennel** [DefectDojo/django-DefectDojo#575]
Please use the following template when submitting issues:

### Issue Type 
- [x] Bug
- [ ] Enhancement

### Operating System 

Please include the version number (ex: Ubuntu 16.04)
- OS not relevant
- MariaDB 10.1.22 (w/ InnoDB)

### Install

- [ ] setup.bash
- [ ] docker
- [x] PaaS (shared DB)

### Steps to Reproduce

The unique index at ``Object``:
https://github.com/DefectDojo/django-DefectDojo/blob/c042756a0106d5dbe119905e55a69a1ba360f608/dojo/models.py#L1435
making product and path unique causes the following error when applied to the DB:

```
Index column size too large. The maximum column size is 767 bytes.
```

Resolution suggestion:
Move path to a dedicated model and reference it from ``Object``. Create the unique index over the (existing) product ForeignKey and the (new) path ForeignKey. 

I am open for comments and will wait a couple of days for your feedback before starting work on the PR.

**Comment by aaronweaver** [comment]
Either solution sounds fine or we could remove the constraint and enforce it in the code.
