### ISSUE TITLE
Reimporting same Jfrog Xray report 2nd time mitigated some of the issue while others are untouched

### ISSUE THREAD

**Issue by techylinux** [DefectDojo/django-DefectDojo#5770]
Hello Team, I have one engagement under some product. I imported Jfrog Xray report 1st import and again I reimported the same report with option close old findings check marked. During this process it mitigated 3 findings.
Not Sure how those findings closed

**Repro steps:**

- Freshly import new report - created x findings
- Reimport same result with "close old findings check marked"
    Message- mitigated 3 findings

<img width="756" alt="image" src="https://user-images.githubusercontent.com/37924175/149905763-fc6c66e5-1424-4809-803c-838161696e44.png">

<img width="709" alt="image" src="https://user-images.githubusercontent.com/37924175/149905803-208fb57d-2575-4e73-a33c-7e7ca922c1df.png">

[Docker_docker.io-amazon-aws-alb-ingress-controller_version-v1.1.5_sumkumar_2022-01-17.zip](https://github.com/DefectDojo/django-DefectDojo/files/7887726/Docker_docker.io-amazon-aws-alb-ingress-controller_version-v1.1.5_sumkumar_2022-01-17.zip)

Attaching the sample Jfrog xray file

Please note I used JFROG-XRAY SCAN  scanner to import this report

**Comment by StefanFl** [comment]
There are no deduplication settings for the JFrog Xray Scan in the settings, that will be the reason. I will investigate more and write a PR.

**Comment by StefanFl** [comment]
merged for release 2.7.0
