### ISSUE TITLE
Adding a new tag(s) in product, with Markdown field, falls in a duplication of the existing first

### ISSUE THREAD

**Issue by rinaldistefano** [DefectDojo/django-DefectDojo#5776]
**General information about testbed**
We are running Defect Dojo v. 2.6.2 ( release mode ) with MariaDB ver. 10.5

**Bug description**
The bug is almost "cosmetic" but can drive user to a bad behavior loosing time trying to correct input data.
When editing tags, after the insert of a new tag, the first (already) present tag is duplicating when hitting return.
By the way, submitting the update, tags are correctly updated with no duplication.

More critical is the usage of the comma separated tags in the markdown window.
When trying to add more than one tag (comma or semicolon separated) the markdown field get "confused".
It insert partial pieces of tag and blocks the field editing.
See last image (adding multitag)

**Steps to reproduce**
1. Go to Product
2. Click on 'Edit'
3. Scroll down to 'tags'
4. Write a new tag and hit return
5. Look at the updated list of tags on the top (first tag duplicated)
6. Hit 'Submit'
7. Product updated with the correct number of tags

**Expected behavior**
when adding new tags, after the return key pressure, no duplication of the tags should be present.

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - Linux defectdojom01 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux
 - Defect Dojo v. 2.6.2 ( release mode )
 - MariaDB ver. 10.5

**Logs** 
N.A.

**Sample scan files**
N.A.

**Screenshots**

 Initial product status
![image](https://user-images.githubusercontent.com/71335929/150088386-8e9be5b1-565b-4daf-96f5-726692a1a15d.png)

Current product tags are debug:00001 and debug:00002 
![image](https://user-images.githubusercontent.com/71335929/150088364-22fcbb63-c520-4f37-8b3b-1d389e7d229e.png)

 
Adding the new tag debug:00003
![image](https://user-images.githubusercontent.com/71335929/150088341-5a7ce860-4a5a-4bb5-9650-3cd4955448c1.png)

 
When hitting return the tags are updated with the new added tag debug:00003 but duplicating the first debug:00001.
 
![image](https://user-images.githubusercontent.com/71335929/150088320-23161c55-a982-41e2-8db9-bf68935da71b.png)

 
By the way, after the submit button is clicked, the product is correctly updated with the 3 tags. The first tag (debug:00001) is not duplicated.
 
![image](https://user-images.githubusercontent.com/71335929/150088297-7b5c2a9a-1ff5-4edd-90e4-409cd90a8394.png)

**ADDING MULTITAG ERROR**
In this example I would like to add two tags: debug:MULTI01 and debug:MULTI02.
When adding the ";" and starting to write the second tag (debug:MULTI02) the markdown splits the first char of the second tag and add it on the top (duplicated). No way to add the rest of the second tag. 
![image](https://user-images.githubusercontent.com/71335929/150089911-0b5763c0-dbcd-4e65-a6c2-decbd0549202.png)

When adding "submit" all the partial tags are added with the exclusion of the first (that is duplicated one).
![image](https://user-images.githubusercontent.com/71335929/150091543-aa7d35b7-9c4d-4990-86ae-943839e5d133.png)

**Additional context** (optional)

**Comment by valentijnscholten** [comment]
Something is completely wrong with the tag field on the edit product page. There should be no markdown edit box. Possibly related to the changes made in https://github.com/DefectDojo/django-DefectDojo/pull/5207 and related PRs.
