### ISSUE TITLE
Products page going in time-out when called by Product Type list. Need of Pagination fetaure.

### ISSUE THREAD

**Issue by rinaldistefano** [DefectDojo/django-DefectDojo#5778]
**General information**
We are using a huge number of products in our DefectDojo production environment (about 160.000 and growing).
On DefectDojo we can access the Product list in two ways:
1. By clicking on the left menu "All products". Products list is generated with pagination and the possibility to filter records.
2. From the "Products Type" by clicking one of them (in our case SAST).

**Bug description**
In this second case it is possible (with a huge number of products) that the request falls in a "**504 gateway time-out**" error.
This because the list not only reports the Products but also look in the database other additional informations like: _Tags, Criticality, Metadata and Active (Verified) Findings_. 

**WORKAROUND**
The solution we found to avoid the "**504 gateway time-out**" error is uncomment and tune the following 3 parameters on the nginx ingress configuration:
proxy-read-timeout
proxy-send-timeout
proxy-connect-timeout
in the values.yaml files related to the kubernets elm chart 
Default values are 60 seconds and we tuned them for 1800 (=30 minutes)

This is the values.yaml part interested by the tuning:
```
django:
annotations: {}
affinity: {}
ingress:
enabled: true
activateTLS: true
secretName: defectdojo-tls
annotations: {}
# Restricts the type of ingress controller that can interact with our chart (nginx, traefik, ...)
# kubernetes.io/ingress.class: nginx
# Depending on the size and complexity of your scans, you might want to increase the default ingress timeouts if you see repeated 504 Gateway Timeouts
nginx.ingress.kubernetes.io/proxy-read-timeout: "**1800**"
nginx.ingress.kubernetes.io/proxy-send-timeout: "**1800**"
nginx.ingress.kubernetes.io/proxy-connect-timeout: "**1800**"

```

**Steps to reproduce**
See bug description section.

**Expected behavior**
Add  the Pagination (and Filtering would be appreciated) feature when accessing "Product list" from "Product Type" list.

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Linux defectdojom01 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux
 - DefectDojo version: Defect Dojo v. 2.6.2 ( release mode ) with MariaDB ver. 10.5

**Logs** 
DJANGO Pods on kubernetes logs reports the following:
[pid: 1|app: 0|req: 4/5] 10.44.0.2 () {72 vars in 1489 bytes} [Mon Jan 17 14:35:27 2022] GET /product/type => generated 52669 bytes in 194 msecs (HTTP/1.1 200) 7 headers in 335 bytes (1 switches on core 0)
Mon Jan 17 14:37:38 2022 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during GET /product/type/5 (10.44.0.2)

**Sample scan files**
N.A.

**Screenshots**

Accessing from "Product" list:
![image](https://user-images.githubusercontent.com/71335929/150101648-47c0ff40-a3f3-442d-8ec0-3edbaed4a6a5.png)

Accessing by clicking on "Product Type" list:
![image](https://user-images.githubusercontent.com/71335929/150101744-95f10c0e-98ca-42b5-9f5d-e90ea53e94c0.png)

![image](https://user-images.githubusercontent.com/71335929/150101767-d7c7689f-60fc-4890-9487-6df861d3ab09.png)

**Additional context** (optional)

**Comment by valentijnscholten** [comment]
fixed in dev / 2.7.0
