### ISSUE TITLE
500 error. Push to Jira

### ISSUE THREAD

**Issue by MIO1100** [DefectDojo/django-DefectDojo#5791]
**Steps to reproduce**

1. Go to adding finding in test
2. Set title and Description.
3. Scroll down to check button "push to JIRA" and click on this button.
4. Click button "Finished"
5. Catch a error 500.

DD version is 2.4.1
ubuntu1~18.04

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

I catch this is error.
logs:
`uwsgi_1         | [20/Jan/2022 08:59:00] ERROR [django.request:224] Internal Server Error: /test/3062/add_findings
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/app/./dojo/authorization/authorization_decorators.py", line 39, in _wrapped
uwsgi_1         |     return func(request, *args, **kwargs)
uwsgi_1         |   File "/app/./dojo/test/views.py", line 379, in add_findings
uwsgi_1         |     if form.is_valid() and (jform is None or jform.is_valid()):
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 177, in is_valid
uwsgi_1         |     return self.is_bound and not self.errors
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 172, in errors
uwsgi_1         |     self.full_clean()
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 375, in full_clean
uwsgi_1         |     self._clean_form()
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 402, in _clean_form
uwsgi_1         |     cleaned_data = self.clean()
uwsgi_1         |   File "/app/./dojo/forms.py", line 2669, in clean
uwsgi_1         |     if self.cleaned_data.get('push_to_jira', None) and finding.has_jira_group_issue:
uwsgi_1         | AttributeError: 'NoneType' object has no attribute 'has_jira_group_issue'
uwsgi_1         | ERROR:django.request:Internal Server Error: /test/3062/add_findings
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/app/./dojo/authorization/authorization_decorators.py", line 39, in _wrapped
uwsgi_1         |     return func(request, *args, **kwargs)
uwsgi_1         |   File "/app/./dojo/test/views.py", line 379, in add_findings
uwsgi_1         |     if form.is_valid() and (jform is None or jform.is_valid()):
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 177, in is_valid
uwsgi_1         |     return self.is_bound and not self.errors
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 172, in errors
uwsgi_1         |     self.full_clean()
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 375, in full_clean
uwsgi_1         |     self._clean_form()
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 402, in _clean_form
uwsgi_1         |     cleaned_data = self.clean()
uwsgi_1         |   File "/app/./dojo/forms.py", line 2669, in clean
uwsgi_1         |     if self.cleaned_data.get('push_to_jira', None) and finding.has_jira_group_issue:
uwsgi_1         | AttributeError: 'NoneType' object has no attribute 'has_jira_group_issue'`

**Comment by celonis-eg** [comment]
I have the same error in the same context as the reporter. I suspect there is a not obvious Jira integration configuration gap but have been unable to locate it.

**Comment by celonis-eg** [comment]
I ran into this issue although it was because #7035 was released but my local docker compose wasn't using an image version that had this fix (was using 2.15.0).

If you run into this again make sure you update Dojo >.>

**Comment by manuel-sommer** [comment]
This can be closed @mtesauro
