### ISSUE TITLE
language packs support

### ISSUE THREAD

**Issue by sergiomarotco** [DefectDojo/django-DefectDojo#5796]
**Describe the solution you'd like**
Need funcional to add language pack files for translating interface. I imagine as a folder in which there will be many files with different languages. Anyone will be able to create their own file and translate the default file with an English translation into their native language. Then select the language in the site menu, and the interface will be translated according to the translation in the file corresponding to the language.

**Comment by sergiomarotco** [comment]
news?

**Comment by damiencarol** [comment]
Since #5760 has been merged, it's possible to add new languages and change few translations in the UI.
Take a look at https://github.com/DefectDojo/django-DefectDojo/tree/dev/dojo/locale/en/LC_MESSAGES

**Comment by GoldraK** [comment]
You could integrate crowdin.com with the product to facilitate translation into different languages.

They have a version for opensource tools to facilitate the languages to other users.
