### ISSUE TITLE
Non UTF-8 characters break the burp report parser

### ISSUE THREAD

**Issue by adracea** [DefectDojo/django-DefectDojo#580]
### Issue Type 
- [ x] Bug
- [ ] Enhancement

### Description
When importing burp suite reports that contain an issue with a non-standard http request(Non UTF-8 characters in the METHOD area in my case) the BurpParser fails with an error 500 on importing .(I'll post the full stack trace and a sample scan file first thing tomorrow)
### Operating System 
Please include the version number (ex: Ubuntu 16.04)
Ubuntu 18.04 LTS

### Install

- [ x] setup.bash
- [ ] docker

### Steps to Reproduce
At this point it's really easy to replicate by importing/uploading a report that (at least in my case) contains non UTF-8 characters in the Method area (for example the kind of issue this : https://github.com/ilmila/J2EEScan/blob/be67a7c439fecb50a6498fd1550e5a76484a6631/src/main/java/burp/j2ee/issues/impl/AJPDetector.java would raise , where the request is a non-standard looking one)

**Comment by devGregA** [comment]
What version are you using? I believe the latest release solved all the issues related to Burp & UTF8

**Comment by adracea** [comment]
Hmm...I git cloned the master branch of the repo this morning

**Comment by devGregA** [comment]
Ah, could you provide a sample scan please?

**Comment by adracea** [comment]
![burpbrokenreport](https://user-images.githubusercontent.com/6214663/40043905-8b4dbe5c-582e-11e8-8ad5-f5c625a886d9.png)

[BuGXML.txt](https://github.com/DefectDojo/django-DefectDojo/files/2003927/BuGXML.txt)


Hmm...now that I think about it , it might be something to do with the generated XML itself although it does look well formatted notepad++ gives an xml validation error ?
