### ISSUE TITLE
Excel report bug - Findings' name ended with three dots (...)

### ISSUE THREAD

**Issue by Greenmouse94** [DefectDojo/django-DefectDojo#5812]
Hello,

**Bug description**
The names are not displayed correctly when I export the findings to excel. The name ended with three dots (...) once in the excel file, like it is showed in the findings web interface.

**Steps to reproduce**
1. Go to Product
2. Select a product
3. Go to Engagement
4. Select an engagement
5. You can see the findings
6. Click on Excel
7. The report is generated

**Expected behavior**
Full name displayed.

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [ ] Kubernetes
- [ X] GoDojo

**Environment information**
 - Operating System: Ubunut 20.04
 - DefectDojo version : 2.4.1

**Screenshots**

![defectdojo](https://user-images.githubusercontent.com/56369846/150760991-76a79ddc-5589-400c-b181-7717149601f0.PNG)

**Comment by StefanFl** [comment]
@Greenmouse94 Have you tried the new Excel export? You can find it with a button in the top right corner of the list:

![2022-02-17 20_39_15-Test _ DefectDojo](https://user-images.githubusercontent.com/2698502/154558079-ba74a255-5502-4b3d-a5a3-01d85bdc2c38.png)

This exports all the fields of the findings and nothing gets shortened.

**Comment by damiencarol** [comment]
@Greenmouse94 any news on this one?

**Comment by damiencarol** [comment]
Closing this one as it was fixed.
