### ISSUE TITLE
Deduplication algorithm does not work for SARIF and Rusty Hog

### ISSUE THREAD

**Issue by manuel-sommer** [DefectDojo/django-DefectDojo#5826]
Hi all,

I uploaded multiple RustyHog files (e.g. Essex Hog and Gottingen Hog), but the DefectDojo deduplication algorithm is wrong as no finding are deduplicated even though I uploaded one file multiple times. 

Tested on branch dev: v. 2.7.0-dev ( release mode )

**Comment by damiencarol** [comment]
@manuel-sommer we need to check the configuration and if the parser provide the data.

**Comment by manuel-sommer** [comment]
@damiencarol, that's exactly what I have already tried out. Didn't work out well yet. Still investigating.

**Comment by manuel-sommer** [comment]
It looks like this issue also applies for the SARIF scanner. 
Import this file multiple times:
https://github.com/DefectDojo/django-DefectDojo/blob/master/unittests/scans/sarif/dockle_0_3_15.sarif 
![SARIF Deduplication](https://user-images.githubusercontent.com/47991713/153305341-146884ea-c2d7-4d68-a49c-8135cc30f0a8.png)

**Comment by manuel-sommer** [comment]
It looks like the same issue applies for some SARIF scans. 
Use the following scanfile to reproduce the issue: 
https://github.com/DefectDojo/django-DefectDojo/blob/master/unittests/scans/sarif/dockle_0_3_15.sarif
![SARIF](https://user-images.githubusercontent.com/47991713/153359710-54e251fa-c6fa-4f72-9a0b-44bf34584686.png)
