### ISSUE TITLE
Generating report ignores selected filters for findings

### ISSUE THREAD

**Issue by EdoardoLunghi** [DefectDojo/django-DefectDojo#5827]
**Bug description**
Trying to produce product type report using filters in HTML format. Filters woks, vulnerabilities showed are correct in the table below. When you try to print HTML report, all vulnerabilities are inserted into without using setted filters. ASCII doc works well.

**Steps to reproduce**

1. Insert Product Type
2. Insert Product
3. Insert Engagement and vulnerabilities.
4. Open all products type.
5. Click on product report.
6. Apply filters (Active:yes , Duplicate: no)

**Expected behavior**
PDF should contains same vulnerabilities filtered in table list

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - DefectDojo version 2.6.2

**Logs** 
No logs

**Comment by valentijnscholten** [comment]
Can you explain the exact steps taken? When I try your steps, it already goes wrong when generating the report. Both HTML and ASCIIDOC do not apply the filters and show all findings.

**Comment by EdoardoLunghi** [comment]
1. Open all products type.
2. Select 1 product type and click on 3 dot
3. Click on product type report.
4. Apply filters (Active:yes , Duplicate: no)
5. Table below is filled correctly
6. Click on "Generate Report"
7. Report contains all vulnerabilities for these type of product

**Comment by StefanFl** [comment]
Thank you @EdoardoLunghi, good find.

merged for release 2.7.0
