### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement gitpython==3.1.24

### ISSUE THREAD

**Issue by devsecopsale** [DefectDojo/django-DefectDojo#5855]
**Slack us first!**
The easiest and fastest way to help you is via Slack. There's a free and easy signup to join our #defectdojo channel in the OWASP Slack workspace: [Get Access.](https://owasp-slack.herokuapp.com/)
If you're confident you've found a bug, or are allergic to Slack, you can submit an issue anyway.

**Be informative**
I'm having an error when building the docker image:

ERROR: Could not find a version that satisfies the requirement gitpython==3.1.24
ERROR: No matching distribution found for gitpython==3.1.24
WARNING: You are using pip version 21.0.1; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
ERROR: Service 'uwsgi' failed to build: The command '/bin/sh -c pip3 wheel --wheel-dir=/tmp/wheels -r ./requirements.txt' returned a non-zero code: 1

**Bug description**
A clear and concise description of what the bug is. For errors include at least the exact error message you are seeing (including traceback).

gitpython 3.1.24 can't be found.

ERROR: Could not find a version that satisfies the requirement gitpython==3.1.24
ERROR: No matching distribution found for gitpython==3.1.24
WARNING: You are using pip version 21.0.1; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
ERROR: Service 'uwsgi' failed to build: The command '/bin/sh -c pip3 wheel --wheel-dir=/tmp/wheels -r ./requirements.txt' returned a non-zero code: 1

**Steps to reproduce**
1.  run docker-compose -p defectDojo build 

**Expected behavior**
a success image built message.

**Deployment method** *(select with an `X`)*
- [X ] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: [Redhat 7.8]
 - DefectDojo version (see footer) or commit message: release-2.6.2

**Logs** 
Collecting social-auth-app-django==5.0.0
  Downloading social_auth_app_django-5.0.0-py3-none-any.whl (24 kB)
Collecting social-auth-core==4.1.0
  Downloading social_auth_core-4.1.0-py3-none-any.whl (333 kB)
Collecting Python-jose==3.3.0
  Downloading python_jose-3.3.0-py2.py3-none-any.whl (33 kB)
ERROR: Could not find a version that satisfies the requirement gitpython==3.1.24
ERROR: No matching distribution found for gitpython==3.1.24
WARNING: You are using pip version 21.0.1; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
ERROR: Service 'uwsgi' failed to build: The command '/bin/sh -c pip3 wheel --wheel-dir=/tmp/wheels -r ./requirements.txt' returned a non-zero code: 1

**Sample scan files**
If applicable, add sample scan files to help reproduce your problem.

**Screenshots**

**Additional context** (optional)

**Comment by valentijnscholten** [comment]
Are you doing something special or just building using plain docker-compose? I can't reproduce the error and our test suite is being built 10s of times per day without any errors. 
Although it shouldn't matter if you're building a docker container, I notice you're running RHEL 7.8 which is end of life.
What is your docker version? Can you try again to make sure it wasn't a PyPi hickup or something.

**Comment by devsecopsale** [comment]
It's working now. probably caused by my own infra issue
