### ISSUE TITLE
Consolidate user names in different views

### ISSUE THREAD

**Issue by kiblik** [DefectDojo/django-DefectDojo#5860]
**Is your feature request related to a problem? Please describe**

In `.../engagements`, `.../engagements/ID`, `.../test/ID`, user uses format "FirstName LastName", however in `.../finding/ID`, there is "LoginName".

**Describe the solution you'd like**

Showing names should be consolidated to the same format. 

**Describe alternatives you've considered**
Possible alternatives:
- `First Last (Login)`
- `Login (First Last)`
- `First Last` + `Login (email)` in tooltip
- `Login` + `First Last (email)` in tooltip
- ...

Maybe also `<a>` to the user profile could be there

_Notes_:
It is necessary to find also other places (not only these 4)

**Comment by dsever** [comment]
I detected the same problem in Test (Testing Lead), but is fixed with #5894

**Comment by manuel-sommer** [comment]
Can we close this @mtesauro ?
