### ISSUE TITLE
Rewrite of GitLab parsers

### ISSUE THREAD

**Issue by kiblik** [DefectDojo/django-DefectDojo#5863]
1. DD supports multiple GitLab formats (API fuzzing, container scan, DAST, Dep. Scan, SAST, Secret detection) but there is documentation only for SAST and Dep. scan
2. All GitLab scanners use the same common format (which is partially but nicely described [here](https://docs.gitlab.com/ee/development/integrations/secure.html#report) and full up-to-date examples are available [here](https://gitlab.com/gitlab-org/security-products/security-report-schemas/-/releases)) so it should be merged into the one. If there will be some change in format, it is easier to maintain one common code than multiple of them. Plus it will automatically support newly created scan categories (for example, "Cluster Image Scanning", "IaC Scanning" and "Coverage-guided fuzz testing" are missing right now)
3. (real bug) "GitLab DAST Report" uses IDs as names of findings even there is a meaningful title in the report (field name is "message").
![image](https://user-images.githubusercontent.com/5609770/152024745-a2323883-a996-445c-aec4-572c23faac7c.png)

**Comment by manuel-sommer** [comment]
Can you close this @mtesauro because of: https://github.com/DefectDojo/django-DefectDojo/discussions/9690
