### ISSUE TITLE
Support for Gitlab API

### ISSUE THREAD

**Issue by kiblik** [DefectDojo/django-DefectDojo#5864]
**Scanner Name**
GitLab API. There is already support for GitLab reports but direct support sounds better.

**Sample File**
https://docs.gitlab.com/ee/api/project_vulnerabilities.html
or
https://docs.gitlab.com/ee/api/graphql/reference/index.html#queryvulnerabilities

**Comment by manuel-sommer** [comment]
I guess this can be close @mtesauro as API imports are not extended anymore.
