### ISSUE TITLE
Add endpoint view to products

### ISSUE THREAD

**Issue by Horst88** [DefectDojo/django-DefectDojo#587]
Please use the following template when submitting issues:

### Issue Type 
- [ ] Bug
- [x] Enhancement

### Description
I would like to see all endponts associated with a product. I know that this is somehow possible over the endpoint-view but this does not fit my needs. I also do not see my product tags in the endpoint-view, ... My entry point is always the product. And therefore I would like to see all endpoints and not only the vulnerable ones, ... With this information I can doublecheck easily if all URLs are included that I would expect. At the end,  endpoints are what will be tested through zap, burp, ... and not the product, but one product has N endpoints, ...

### Operating System 
Please include the version number (ex: Ubuntu 16.04)

### Install

- [ ] setup.bash
- [ ] docker

**Comment by aaronweaver** [comment]
Added a link from product to the endpoint view --> From the Product, Menu on the far right, select 'View endpoints'
 
Also in system settings enable: **Display Endpoint Full URI** This will show you the full url for endpoints rather than consolidating the view.
