### ISSUE TITLE
Nessus report import to defect dojo fails with error 400

### ISSUE THREAD

**Issue by vaisakh007** [DefectDojo/django-DefectDojo#5879]
**Be informative**
While uploading nessus scan reports to  defect dojo (version v. 2.6.2) results in 400 bad request
Nessus scan report is a valid xml file with extension '.xml'

**Bug description**
when i issue curl as below

curl -v  -s -o $http_response -w "%{http_code}" -X POST  -H  "accept: */*"  -H  "Content-Type: multipart/form-data" -F "file=@scan-42244.xml;type=text/xml" http://api-defectdojo.defectdojo.svc.cluster.local/engagements/46/import-scan

Error getting logged at defectdojo

[03/Feb/2022:12:45:52 +0000] "POST /api/v2/import-scan/ HTTP/1.1" 400 165 "-" "python-requests/2.27.1" "-"

**Steps to reproduce**
Unable to reproduce on lower environment 

**Expected behavior**
Import should be completed successfully

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X ] Kubernetes
- [ ] GoDojo

**Environment information**
 - kubernetes v1.21
 - DefectDojo version version v. 2.6.2 

**Logs** 
[03/Feb/2022:12:45:52 +0000] "POST /api/v2/import-scan/ HTTP/1.1" 400 165 "-" "python-requests/2.27.1" "-"

**Comment by damiencarol** [comment]
Could you provide the report (even obfuscated) ? IT helps a lot

**Comment by valentijnscholten** [comment]
What is in the http response coming back from DD? And what is the actual request you're sending? The command given above seems to miss all the data needed to perform an import, i.e. engagement, scan_type, etc.

See https://defectdojo.github.io/django-DefectDojo/integrations/importing/

Also the url is incorrect, please check API spec at https://<host>/api/v2/oa3/swagger-ui/?docExpansion=none#/import-scan/import_scan_create
