### ISSUE TITLE
Helm Installation Problem

### ISSUE THREAD

**Issue by AliElKhatteb** [DefectDojo/django-DefectDojo#5897]
Hello i tried to install defect-dojo on my kubernetes cluster but i get this error
Error: secret "defectdojo-rabbitmq-specific" not found
this is the case for all pods

**Comment by John-Levi0909** [comment]
Is there any workaround for this? I'm also getting the same error together with "CreateContainerConfigError". The corresponding message states: Error: secret "defectdojo-rabbitmq-specific" not found.

**Comment by nullniverse** [comment]
check [dsever](https://github.com/dsever) answer above. It must be set to true and make sure:

`      existingPasswordSecret: defectdojo-rabbitmq-specific`
and
`      existingErlangSecret: defectdojo-rabbitmq-specific`

are also passed.

**Comment by manuel-sommer** [comment]
I guess this can be closed @mtesauro. This issue seems stale.

**Comment by mtesauro** [comment]
Closed as stale
