### ISSUE TITLE
trufflehog import scan report error 

### ISSUE THREAD

**Issue by samira-karimi-elfiman** [DefectDojo/django-DefectDojo#5912]
hi

**Bug description**
When importing the output of the Truffle Hog tool, I encounter the following error:

An exception error occurred during the report import:(1366, 'Incorrect string value: \'\\xF0\\x9F\\x91\\x8D")...\' for column \'description\' at row 1')

![image](https://user-images.githubusercontent.com/61731682/153872987-bdda09fc-ae1f-4a42-87b6-b526ab0b7dac.png)

I am not able to store any emoji in the database

**Deployment method** *(select with an `X`)*
- [X] Docker Compose

**Environment information**
 - Operating System: centos
 - DefectDojo version: v. 2.5.0 ( release mode )
 - mysql docker image version: 5.7.34  

I entered the MySQL docker image and examined the character set of defectdojo database and dojo_finding table:
![image](https://user-images.githubusercontent.com/61731682/153874543-1db5f4e6-5962-47ef-80da-efd5a611f99f.png)
![image](https://user-images.githubusercontent.com/61731682/153874883-0a442f03-5fa8-4963-9728-c35b7b3f953f.png)

Thank you for your help

**Comment by valentijnscholten** [comment]
Can you try the solution from #4336?

**Comment by samira-karimi-elfiman** [comment]
Thank you for your response
My problem was solved
