### ISSUE TITLE
Where are the logs ?

### ISSUE THREAD

**Issue by Greenmouse94** [DefectDojo/django-DefectDojo#5915]
Hello,

I was looking for the logs after a problem on my server, I looked in the documentation but I did not find anything.
So my question is "simple", where are the logs located ? Is it possible to configure them ?

**Deployment method**
- [ ] Docker Compose
- [ ] Kubernetes
- [ x] GoDojo

**Environment information**
 - Operating System: Ubuntu 20.04
 - DefectDojo version: V2.4.1

Thanks.

**Comment by mtesauro** [comment]
The logs of the install are written to the 'logs' directory in the same location/directory that godojo was run in.

So, if you run godojo in /opt/godojo, the logs would be located in /opt/godojo/logs:

```
# pwd
/opt/godojo
# tree
.
├── dojoConfig.yml
├── godojo
├── logs
│   ├── cmd-output_1644908712465994339.log
│   └── dojo-install_1644908712465994339.log
└── runtime-install-config.yml

1 directory, 5 files
```

If you mean the logs from DefectDojo, then that would depend on how you launched DefectDojo after doing the install.

If you used the example start and stop scripts at https://github.com/DefectDojo/godojo/tree/master/docs-and-scripts then the logs would be in the screen sessions for the various parts of DefectDojo (Django, celery worker, celery beat)

If you fronted the install with Apache or Nginx, the logs would be where they were configured for that services.  Same goes for the database used by DefectDojo - usually /var/logs in most Linuxes.

If you wrote a service file for systemd, then you'll use the systemctl and journalctl commands to get the logs.

The old documentation files have examples which _may_ work for systemd service files that might be useful examples.  I wrote those originally but that was years ago:
https://github.com/DefectDojo/Documentation/blob/master/docs/running-in-production.rst

HTH

**Comment by Greenmouse94** [comment]
Hello @mtesauro,

Thank you for your reply.

Yes I used this solution:
`If you used the example start and stop scripts at https://github.com/DefectDojo/godojo/tree/master/docs-and-scripts then the logs would be in the screen sessions for the various parts of DefectDojo (Django, celery worker, celery beat)`

But even with these information I have no idea where are the logs, I tried to add `-L -Logfile ...` to the scripts but even with that it does not work, I have no logs appearing.

After that I tried to add `-f celery-worker.log` to the celery script, but I still have no logs, is it possible to add a script or something else to have all logs in one folder ? (/var/log/dojo/ for example) ?
Or the place where I can find the logs.

Btw, I also tried the command `screen -S worker`, to go in the screen, but even with that I have no idea where the logs are.

Thank you.
Best regards.

**Comment by mtesauro** [comment]
So, in the case of those scripts, the "logs" are written to stdout (standard out) and that output is "written" to the screen session so there's not really a great way to look back at them.

 If you want them written to disk, you could either create a service file like I mentioned above (see [here](https://github.com/DefectDojo/Documentation/blob/master/docs/running-in-production.rst)) or a quick and dirty method would be to redirect the commands in the screen sessions to a file.  For example, you could change the command at https://github.com/DefectDojo/godojo/blob/master/docs-and-scripts/dojo-start#L16 to:

`screen -S worker -D -m /bin/bash -c 'source /opt/dojo/bin/activate && C_FORCE_ROOT="true" celery -A dojo worker -l info --concurrency 3 >> /opt/dojo/logs/celery-worker.log'`
Warning: The command ^ line wrapped - its a single line. The same as the link above with " >> /opt/dojo/logs/celery-worker.log" added.

You'll need to validate that works. I've not tried recently - before docker-compose, I used that 'hack' to get logs out of Defectdojo years ago.  You'll also need to make sure that the directory and file permissions allow the user running the dojo-start script to write to that directory - in my example /opt/dojo/logs.

If you add those 'append to a file' parts to the 3 screen commands in dojo-start (lines 16, 19, 26) you can get logs from celery-worker, celery-beat and DefectDojo/django for example:
line 16 add ` >> /opt/dojo/logs/celery-worker.log`
line 19 add ` >> /opt/dojo/logs/celery-beat.log`
line 26 add ` >> /opt/dojo/logs/django-DefectDojo.log`

**Comment by Greenmouse94** [comment]
Hello @mtesauro thank you very much !!

I will try this today.

Best regards.
