### ISSUE TITLE
Nessus CSV parser - 1048, Column 'description' cannot be null

### ISSUE THREAD

**Issue by dhenrygithub** [DefectDojo/django-DefectDojo#5924]
When importing a nessus scan result set in csv format,  I get an error (shown below) on the web page using the interactive engagement import page.  

I looked in the repo at the sample-scan-files, and the nessus folder only has .nessus and .xml samples.  If I try importing the sample xml file it works.

Using this page https://company[dot]com/product/1/new_engagement

**Error Message**
I get this error on the page:
```
An exception error occurred during the report import:(1048, "Column 'description' cannot be null")
```

**Logs**
This error appears in the logs
```
django.db.utils.IntegrityError: (1048, "Column 'description' cannot be null")
```

**Steps to reproduce**
1. Go to https://company[dot]com/product/1/new_engagement
2.  Click on Import Scan Results
3.  Select Scan Type - Nessus Scan
4.  Select Environment - Production
5.  Click on Choose File to select the csv scan result set file
6.  Click on Import
7.  See error

**Expected behavior**
When I attempted these steps using the sample xml file in the repo, I received a new page showing the results that were imported.  This is the expected result.

**Deployment method** *(select with an `X`)*
- [ x] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: RHEL 8
 - DefectDojo version 2.6.2

**Sample scan files**
Using this csv file

```
Plugin,description,Plugin Name,Family,Severity,VPR,IP Address,NetBIOS Name,DNS Name,MAC Address,Repository
153583,Apache < 2.4.49 Multiple Vulnerabilities,Apache < 2.4.49 Multiple Vulnerabilities,Web Servers,Medium,10,10.10.10.10,company.com\WINDOWS,windows.company.com,00:00:00:00:00:00,company.com.windows
```

**Comment by StefanFl** [comment]
@dhenrygithub The parser for Nessus CSV files expects a column called `Synopsis`, this will be used to fill the mandatory description. I don't know Nessus at all, do you have any idea why this column is not in your report?

**Comment by dhenrygithub** [comment]
This may be a difference between the CLI product and Security Center, which is their enterprise platform.  You can select fields to export from SC (the two samples I provided as pull requests to samples repo come from the All Vulnerabilities view, using the most commen exports for summarizing counts and summarizing all affected endpoints per vuln, and I have all fields enabled).  

I would select 'Plugin Name' if Synopsis isn't present, as in most cases users will need that ciolumn for their reporting to make sense.
