### ISSUE TITLE
Dojo docker settings edit

### ISSUE THREAD

**Issue by vulnz** [DefectDojo/django-DefectDojo#5937]
Good day. 
I'm using docker compose to deploy dojo.
I'm interested on how can i edit settings without destroying the container.
What is the password for docker enviroment, i basicaly want to change settings.dist.py file without doing redeployment.
thanks

**Comment by valentijnscholten** [comment]
What happens if you try the steps in the documentation: https://defectdojo.github.io/django-DefectDojo/getting_started/configuration/ ?

**Comment by manuel-sommer** [comment]
Can we close this as stale @mtesauro ?
