### ISSUE TITLE
Hidden packages name in snyk scan

### ISSUE THREAD

**Issue by rastorguevai** [DefectDojo/django-DefectDojo#5950]
Hi, our team use defectdojo v1.15 and snyk scans. When I get report packages name in "File Patch" is invisible (> >). 
![image](https://user-images.githubusercontent.com/99810902/155117415-667f9459-f3ad-4a73-ad4e-90899b7a5697.png)
But I see name in "Component Details"
![image](https://user-images.githubusercontent.com/99810902/155117718-ce5806c8-609b-4fbc-a60a-4e511523b5a1.png)
I think it's related to @ at the packages name begining 
<img width="774" alt="Снимок-экрана-2022-02-22-в-12 48 57" src="https://user-images.githubusercontent.com/99810902/155118138-6bc0114e-e210-49ba-98b3-3a34b7e4c9d5.png">
Are there any plans for a small fix?

**Comment by valentijnscholten** [comment]
Should be fixed by https://github.com/DefectDojo/django-DefectDojo/pull/5789 in 2.7.1.
Any plans to upgrade to the latest version? ;-P

**Comment by manuel-sommer** [comment]
Snyk had multiple improvements till now. I guess this can be closed @mtesauro .
