### ISSUE TITLE
Unable to add GHSA Findings due to validation rules for vulnerability identifier

### ISSUE THREAD

**Issue by fhoeborn-cb** [DefectDojo/django-DefectDojo#5958]
**Be informative**
If you have a GHSA vulnerability you are not able to save it, as it does not match the RegEx for Vulnerability identifier which prohibits characters after the first block.

**Bug description**
A clear and concise description of what the bug is. For errors include at least the exact error message you are seeing (including traceback).

**Steps to reproduce**
1. Go to a product of your choice in DefectDojo
2. Click on 'Findings' -> 'Add new Finding'
3. Enter any title, description and add for Cve 'GHSA-jfh8-c2jp-5v3q'
3. Scroll down to 'Finished'-Button, click that button
4. See validation error
<img width="949" alt="Bildschirmfoto 2022-02-24 um 10 57 09" src="https://user-images.githubusercontent.com/98820380/155501709-717b83f2-5c98-48c7-9607-ab825ae9835a.png">

**Expected behavior**
Expected behaviour would be to allow more flexibility with Vulnerability identifiers, maybe the text field also needs a renaming from "CVE" as there are some more identifier by now.

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Mac OS Monterey
 - DefectDojo version (see footer) or commit message: v. 2.7.1

**Comment by valentijnscholten** [comment]
This field is only designed to contain CVEs currently. There's work being done on supporting more ids: #5904
