### ISSUE TITLE
qualys xml report

### ISSUE THREAD

**Issue by vulnz** [DefectDojo/django-DefectDojo#5964]
Good day, qualys xml report is working fine during manual upload.
but it looks like they do not have xml report extraction from their api.
can you please add csv or json parser?

Idea is:
Qualys has api which allows to download only csv, or json however manually you can download xml, which is parsable by Defectdojo.
Please let me know how to process this issue in order to automate.

**Comment by vulnz** [comment]
![image](https://user-images.githubusercontent.com/20043135/155703178-464c2c89-5055-475b-aff1-9090e9c5bcb9.png)

**Comment by damiencarol** [comment]
Best solution is to create the loader part for the JSON formats.
You can take example on this PR which add a parser and the importer => https://github.com/DefectDojo/django-DefectDojo/pull/4962
If implementing the importer is too much, at least create the JSON loader part in the same parser.

**Comment by manuel-sommer** [comment]
@vulnz, if you add a JSON or CSV output file here, I can help you and make a PR for you.

**Comment by manuel-sommer** [comment]
Do you have an update here @vulnz ?

**Comment by manuel-sommer** [comment]
@vulnz do you have an output for qualys?

**Comment by manuel-sommer** [comment]
I guess this is deprecated as there was no response for over a month @mtesauro 
In case you still need support for this @vulnz feel free to open another issue, but then please add an output file.
