### ISSUE TITLE
fix/hide docker entrypoint warnings on copying of settings

### ISSUE THREAD

**Issue by techylinux** [DefectDojo/django-DefectDojo#5965]
As per Discussion with Valentin below error message can be ignored.
Better if we can hide this error if of no importance.

Got when started docker-compose .
![image](https://user-images.githubusercontent.com/37924175/155709843-682b6845-56e3-467d-9c19-d401d79cdbd5.png)

**Comment by StefanFl** [comment]
merged for release 2.9.0
