### ISSUE TITLE
Checkmarx import JSON support request

### ISSUE THREAD

**Issue by jayala-29** [DefectDojo/django-DefectDojo#5972]
**Scanner Name**
Checkmarx JSON file parsing to further enhance https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/checkmarx/parser.py 

**Sample File**
A json file is attached here: [example-Cx-scan.json.zip](https://github.com/DefectDojo/django-DefectDojo/files/8157044/example-Cx-scan.json.zip)

@damiencarol

**Comment by damiencarol** [comment]
Will work on it

**Comment by jayala-29** [comment]
Sure, this does come from the Checkmarx SAST UI but takes some digging to find.

Projects -> <project-name> (e.g. DIVA) -> Scan History -> expand three dots menu of scan -> Generate report -> Select Sections (click Scan Results) -> Export Method (click JSON) -> click Generate Report

@ptrovatelli Let me know if you're unable to find it, thanks! :)

**Comment by damiencarol** [comment]
@ptrovatelli I made some tests and the JSON and XML data have the same structure, like:

report -> query -> vuln -> node

I'm working on a basic JSON support to merge it fast but we can have a parser that manage both. The only challenge I'm facing is I don't have many report in JSON format.

**Comment by damiencarol** [comment]
Merge in `dev` and part of 2.12.0 release

**Comment by adamtimmins** [comment]
> @adamtimmins please add a new issue, best way to manage issues.

Created new issue here: https://github.com/DefectDojo/django-DefectDojo/issues/6956
