### ISSUE TITLE
Merge Findings

### ISSUE THREAD

**Issue by aaronweaver** [DefectDojo/django-DefectDojo#598]
### Issue Type 
- [ ] Bug
- [X] Enhancement

### Description
I'd like the ability to merge findings. The reasoning for this is sometimes scan results are similar and can be consolidated due to how the import occurs.

The merge finding screen would have a "parent finding" which would be the finding number the other findings would be merged into. There would be an option to concatenate the finding descriptions from the "child" findings into the parent finding. 

There should also be the ability to add the endpoints into the merged finding. The "child" finding merged should then be removed and deleted from the system. The redirect should take the user to the edit screen of the merged finding.

**Comment by aaronweaver** [comment]
Merge enhancement completed. Will be released in v1.4

**Comment by alekbc** [comment]
Hi. I couldn't find at last release. Was this included in 1.5 or 1.5.1? 
Thank you

**Comment by aaronweaver** [comment]
@alekbc Merge is in both releases. If you go to the findings tab, click two or more findings with the checkbox, then at the top left you will see a merge icon. Screenshots below.

![image](https://user-images.githubusercontent.com/220838/43459332-3265c0a6-949b-11e8-8ad3-5d0e21a65118.png)

![image](https://user-images.githubusercontent.com/220838/43459346-3d3266ec-949b-11e8-9924-3721f1d6e9b6.png)

**Comment by alekbc** [comment]
Hi, I can't see the function in version 1.5.1. I've tried with IE and Chrome.
Do I need to enable any setting?
Screenshot below. Thank you!

![merge](https://user-images.githubusercontent.com/34648262/43652044-f5902c5e-973b-11e8-9c67-38dccb2c540c.jpg)

**Comment by aaronweaver** [comment]
Check and see if there is a javascript error.

**Comment by alekbc** [comment]
Hi. I can only see the following error at jquery.js:3430.  However, it comes out when the page is loaded.
I've tried with Chrome and Firefox.

 [Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
jquery.js:3430 [Violation] 'DOMContentLoaded' handler took 168ms

Thanks

**Comment by aaronweaver** [comment]
@alekbc Can you go to the product and then click on the 'Findings tab' and try it there? I just remembered merge isn't an option at the moment in the all findings views.

**Comment by alekbc** [comment]
Hi @aaronweaver . It works from there. Thank you
