### ISSUE TITLE
Automatic assignment of users to corresponding Azure AD groups

### ISSUE THREAD

**Issue by stellastarssda** [DefectDojo/django-DefectDojo#5988]
**Is your feature request related to a problem? Please describe**

When using a corporate Azure Active Directory to authenticate users to Defect Dojo, they are not automatically assigned to the groups that exist in Azure AD.

**Describe the solution you'd like**

As an admin, I want users to be assigned to the groups they belong to. If the group does not yet exist in DefectDojo, it should be generated automatically. 

As a user, after signing in with Azure AD, I want to see all products and product types relevant for the groups I belong to.

**Additional context**

Preliminary work to this topic has been described in https://github.com/DefectDojo/django-DefectDojo/issues/2919
Concept of groups:  https://github.com/DefectDojo/django-DefectDojo/pull/4503

The creation of groups and the assignment of users to groups will be added by myself as a function to https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/pipeline.py#L71 which will be called in https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/settings/settings.dist.py#L437.

**Comment by kiblik** [comment]
This issue can be closed. It was implemented in #6128
