### ISSUE TITLE
Unrestricted Upload of File with Dangerous Type (CWE-434)

### ISSUE THREAD

**Issue by rinaldistefano** [DefectDojo/django-DefectDojo#5989]
**Be informative**
Our DefectDojo v. 2.6.2 ( release mode ) is running in a big organization. We currently updateDefectDojo upon relevant issues.

**Bug description**
Bug is related to file upload feature. In particular we are pointing findings risk acceptance informations set.
The "Proof" field scope is to add, uploading relevant files, documentation in the form of an Image or PDF.
Actually the "Proof" feature allows the upload of any file type.
As described in the Common Weakness Enumeration Database ([here](https://cwe.mitre.org/data/definitions/434.html)) this allows the attacker to upload or transfer files of dangerous types that can be automatically processed within the product's environment. 

**Steps to reproduce**
1) Open the "Findings" and choose one of the findings;
2) Add a "Risk Acceptance" by clicking on the three dots menù on the finding left;
3) Click on the "Proof" field;
4) Upload whatever you want other than images/PDF files.

**Expected behavior**
We expect at least to limit file upload to *.png, *.gif, *.jpg, *.pdf files.
Would be fine to add a check of the uploaded file to verify their real nature.
Using OWASP Weak Protections and Bypassing Methods described [here](https://owasp.org/www-community/vulnerabilities/Unrestricted_File_Up) will mitigate the issue. 

**Deployment method** *(select with an `X`)*
- [X] Deployment method independent
- [X] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
  Thi issue is environment independent

**Logs** 
  No specific log items are generated for this issue since it is an improper "physiological" behavior

**Sample scan files**
  Not applicable

**Screenshots**
Risk Acceptance interface:
![image](https://user-images.githubusercontent.com/71335929/156522489-05fdf610-bc6d-4959-8c4c-e1ccec9a1147.png)

![image](https://user-images.githubusercontent.com/71335929/156522087-a6013bb0-5a55-41c9-8b0c-19a474d79471.png)

Risk acceptance (in good faith) indicates to upload only images and documents:
![image](https://user-images.githubusercontent.com/71335929/156522123-217e16c9-0c1a-479b-ab4b-03fb1657e5af.png)

It is possible to load files with no restrictions (driver, executables. jar and so on):
![image](https://user-images.githubusercontent.com/71335929/156522141-cb0e45b2-7765-4479-8ce8-d100fe78e14f.png)

**Additional context** (optional)
  Nothing relevant

**Comment by damiencarol** [comment]
@rinaldistefano thanks for this detailled report.
It is not clear if it's pointing a lack of feature, a bug or a security issue.
If you consider it's a security issue, please report Security issues via our [disclosure policy](https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/SECURITY.md).

**Comment by rinaldistefano** [comment]
> @rinaldistefano thanks for this detailled report. It is not clear if it's pointing a lack of feature, a bug or a security issue. If you consider it's a security issue, please report Security issues via our [disclosure policy](https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/SECURITY.md).

Sorry but submitting this security issue (CWE-434) is quite tricky following your suggestion. I've created an account on "hackerone" but it is not clear what to do there. Sorry. Can you help ?

**Comment by rinaldistefano** [comment]
UIpdate:Finally opened 1498891 on hackerone.com.
