### ISSUE TITLE
Reimport should allow us to differentiate between new and old findings

### ISSUE THREAD

**Issue by techylinux** [DefectDojo/django-DefectDojo#6010]
As of now we are unable to figure out the newly created findings while reimport.
Let's say we reimport and that reimport show status as 8 created and 45 left untouched. But when I click on it, I am unable to figure out which 8 findings are created and it shows all findings 45+8.Also this I reimported one by one on  the same day.
It would be nice if we could see those newly created findings with some status.
![image](https://user-images.githubusercontent.com/37924175/157594435-26670ab9-f4ba-4307-8c14-fc267957abf7.png)

**Comment by manuel-sommer** [comment]
This can be closed, also with this fix https://github.com/DefectDojo/django-DefectDojo/pull/9410 
@mtesauro

**Comment by mtesauro** [comment]
Closing as approvals are rolling in for that PR
