### ISSUE TITLE
Mask fields in auditlog

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#6012]
`django-auditlog` now supports masking fields in the log output: https://github.com/jazzband/django-auditlog/pull/310

we should probably mask some fields like passwords/credentials, or at least check again if these are logged in the audit log.

**Comment by StefanFl** [comment]
We already exclude passwords of users and credentials from the auditlog. The other entities in the auditlog are:

* Endpoint
* Engagement
* Finding
* Product
* Test
* Risk_Acceptance
* Finding_Template

Can't think of information worth masking in these types of objects.

**Comment by mtesauro** [comment]
@StefanFl Agreed about not masking those objects - I can't see how they'd be considered sensitive in any 'normal' situation.

Thanks for taking the time to get the current state.

Looks like we were ahead of django-auditlog ;-)

**Comment by valentijnscholten** [comment]
The making feature request for django-auditlog came from me. But can't remember why. I think at some point we had a H1 report about password hashes being logged, but can't find it anymore. Maybe we already reduced the number of models being registered to the audit log.
