### ISSUE TITLE
Unable to upload Veracode Scan via API (importscan function)

### ISSUE THREAD

**Issue by jimminycrickett** [DefectDojo/django-DefectDojo#603]
Please use the following template when submitting issues:

### Issue Type 
- [X] Bug
- [ ] Enhancement

### Description
When attempting to import a scan via the API, through either the Swagger tester or python upload script, the API is unable to find the source file to be uploaded
### Operating System 
Please include the version number (ex: Ubuntu 16.04)
Ubuntu 16.04

### Install

- [ ] setup.bash
- [X] docker

### DefectDojo Version
1.3.0

### Steps to Reproduce
execute the 'importscan' function call within the API Swagger UI with the following inputs:
{ 'minimum_severity': 'Info',
   'scan_date': '2018-05-18',
   'verified': 'False',
   'file': 'http://localhost:8888/detailedreport_root_2018-05-18-17_37_31.xml',
   'lead': '/api/v1/users/1/',
   'tags': '',
   'active': 'True',
   'engagement': '/api/v1/engagements/3/',
   'scan_type': 'Veracode Scan'}
### Console Logs (optional)
[Python script output, same as Swagger UI output...

]

cookies
<RequestsCookieJar[]>
------------------
_content
{"error_message": "[Errno 2] No such file or directory: u'http://localhost:8888/detailedreport_root_2018-05-18-17_37_31.xml'", "traceback": "Traceback (most recent call last):\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 227, in wrapper\n    response = callback(request, *args, **kwargs)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 467, in dispatch_list\n    return self.dispatch('list', request, **kwargs)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 499, in dispatch\n    response = method(request, **kwargs)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 1408, in post_list\n    updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))\n\n  File \"/opt/django-DefectDojo/dojo/api.py\", line 1301, in obj_create\n    parser = import_parser_factory(bundle.data['file'], t)\n\n  File \"/opt/django-DefectDojo/dojo/tools/factory.py\", line 43, in import_parser_factory\n    parser = VeracodeXMLParser(file, test)\n\n  File \"/opt/django-DefectDojo/dojo/tools/veracode/parser.py\", line 12, in __init__\n    vscan = ElementTree.parse(filename)\n\n  File \"/usr/local/lib/python2.7/dist-packages/defusedxml/common.py\", line 100, in parse\n    return _parse(source, parser)\n\n  File \"/usr/lib/python2.7/xml/etree/ElementTree.py\", line 1182, in parse\n    tree.parse(source, parser)\n\n  File \"/usr/lib/python2.7/xml/etree/ElementTree.py\", line 647, in parse\n    source = open(source, \"rb\")\n\nIOError: [Errno 2] No such file or directory: u'http://localhost:8888/detailedreport_root_2018-05-18-17_37_31.xml'\n"}
------------------

headers
{'Content-Length': '1689', 'Vary': 'Cookie', 'Server': 'WSGIServer/0.1 Python/2.7.12', 'Date': 'Fri, 25 May 2018 19:45:11 GMT', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Type': 'application/json'}
------------------
url
http://127.0.0.1:8000/api/v1/importscan/
------------------
status_code
500
------------------
_content_consumed
True
------------------
encoding
None
------------------
request
<PreparedRequest [POST]>
------------------
connection
<requests.adapters.HTTPAdapter object at 0x7fef9eb358d0>
------------------
elapsed
0:00:00.025952
------------------
raw
<urllib3.response.HTTPResponse object at 0x7fef9e897ed0>
------------------
reason
Internal Server Error
------------------
_next
None
------------------
history
[]

[code won't attach, so I'm pasting it in here:]
`import requests
url = 'http://127.0.0.1:8000/api/v1/importscan/'
headers = {'content-type': 'application/json',
           'Authorization': 'ApiKey admin:anactuallyvalidapikeythisoneisbogus'}
params = { 'minimum_severity': 'Info',
           'scan_date': '2018-05-18',
           'verified': 'False',
           'file': 'http://10.1.1.39:8888/detailedreport_root_2018-05-18-17_37_31.xml',
           'lead': '/api/v1/users/1/',
           'tags': '',
           'active': 'True',
           'engagement': '/api/v1/engagements/3/',
           'scan_type': 'Veracode Scan'}
r = requests.post(url, headers=headers, json=params, verify=False) 
for key, value in r.__dict__.iteritems():
  print key
  print value
  print '\n'
  print '------------------'`

**Comment by aaronweaver** [comment]
The swagger doc isn't quite right. I'd use the Python API wrapper instead.

`Code: dd.upload_scan(engagement_id, scannerName, file, "true", dojoDate, build)`

https://github.com/aaronweaver/defectdojo_api/blob/master/examples/dojo_ci_cd.py

Soon we'll be out with a V2 that has better documentation. The raw request will look something like this:

`POST /api/v1/importscan/ HTTP/1.1
Host: localhost:8000
Connection: close
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.18.4
Authorization: ApiKey admin:*********
Content-Length: 1624
Content-Type: multipart/form-data; boundary=0ada9bafe72948a9a536e80876bf8f77
--0ada9bafe72948a9a536e80876bf8f77
Content-Disposition: form-data; name="scan_date"; filename=""
2018-05-15
--0ada9bafe72948a9a536e80876bf8f77
Content-Disposition: form-data; name="engagement"; filename=""
/api/v1/engagements/1/
--0ada9bafe72948a9a536e80876bf8f77
Content-Disposition: form-data; name="scan_type"; filename=""
Node Security Platform Scan
--0ada9bafe72948a9a536e80876bf8f77
Content-Disposition: form-data; name="minimum_severity"; filename=""
Low
--0ada9bafe72948a9a536e80876bf8f77
Content-Disposition: form-data; name="file"; filename="i.json"
[
   {
      "advisory": "https://nodesecurity.io/advisories/535", 
      "cvss_vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", 
      "vulnerable_versions": "< 1.4.1 || > 2.0.0 < 2.0.3", 
      "title": "Regular Expression Denial of Service", 
      "overview": "The mime module is vulnerable to regular expression denial of service when a mime lookup is performed on untrusted user input.", 
      "created_at": "2017-09-25T19:02:28.152Z", 
      "updated_at": "2017-09-27T18:25:14.673Z", 
      "module": "mime", 
      "version": "1.3.6", 
      "publish_date": "2017-09-27T18:25:14.672Z", 
      "recommendation": "Upgrade to version 2.0.3 or greater.", 
      "cvss_score": 7.5, 
      "path": [
         "delivero/cc-ui@undefined", 
         "url-loader@0.5.9", 
         "mime@1.3.6"
      ], 
      "id": 535, 
      "patched_versions": ">= 1.4.1 < 2.0.0 || >= 2.0.3"
   }
]
--0ada9bafe72948a9a536e80876bf8f77
Content-Disposition: form-data; name="active"; filename=""
true
--0ada9bafe72948a9a536e80876bf8f77--`

**Comment by jimminycrickett** [comment]
Just wanted to follow up: I've been using the python wrapper and it's working like a charm. Thanks so much for all your work on this!
