### ISSUE TITLE
Jira to Dojo Sync

### ISSUE THREAD

**Issue by secops-quotient** [DefectDojo/django-DefectDojo#6038]
Hi,

I have integrated jira in dojo. When i push the issues from dojo to jira it works fine. I know that status sync feature is there.
But if a developer or anyone changes the data directly in jira, I couldn't able to view the changed data in dojo. May i know that the bidirectional feature is only for status sync or the changed data in jira will be reflected in the dojo also.

Thanks

**Comment by valentijnscholten** [comment]
Only status and comments are synced.

**Comment by secops-quotient** [comment]
Thanks for confirming this
