### ISSUE TITLE
[feature][Findings] Bulk notes 

### ISSUE THREAD

**Issue by dsever** [DefectDojo/django-DefectDojo#6044]
Just to record FR.

While customer can mark multiple findings like false positive, out of scope, or something else, it would be useful to have option to add bulk notes as well. The intention is to write down note into multiple findings to leave trace why some status has been changed, without entering each finding separately.

**Comment by dsever** [comment]
https://github.com/DefectDojo/django-DefectDojo/pull/6094

**Comment by StefanFl** [comment]
merged for release 2.9.0
