### ISSUE TITLE
Error When Adding New Credentials

### ISSUE THREAD

**Issue by 8m4ck** [DefectDojo/django-DefectDojo#605]
Please use the following template when submitting issues:

### Issue Type 

- [x] Bug

### Description

DefectDojo reports an error when attempting to add a new credential.

### Operating System 

Ubuntu Version: 16.04.4 LTS

### Install

- [x] docker

### DefectDojo Version

v. 1.2.5

### Steps to Reproduce

Add a new credential via Configuration » Credential Manager » Add Credential at https://x.x.x.x/cred/add

### Console Logs (optional)

Request Method: | POST
Request URL: http://x.x.x.x/cred/add
Django Version: 1.11.11
Exception Type: TypeError
Exception Value: argument 1 must be string or read-only buffer, not None
Exception Location:/usr/local/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py in __init__, line 141
Python Executable: /usr/bin/python
Python Version: 2.7.12
Python Path: ['/opt/django-DefectDojo',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages',  '/opt/django-DefectDojo']

**Comment by aaronweaver** [comment]
Please configure a randomly generated key called DB_KEY and add to settings.py in dojo/settings/.

Added additional checks for this in 1.4
