### ISSUE TITLE
Images are not resizable

### ISSUE THREAD

**Issue by X0x1RG9f** [DefectDojo/django-DefectDojo#6068]
### Issue
When inserting a description (finding, product, etc.), `<img />` tag can be added. However, the tag does not allow to be used with `width`, `height` or `style=background-color:'#ffffff'`. Neither the image can be centered because the `<center>` tag is not allowed. 

### Solution
Pull Request #6064 added in order to fix this issue.

**Comment by StefanFl** [comment]
merged for release 2.9.0
