### ISSUE TITLE
Date erased when Finding created from Template

### ISSUE THREAD

**Issue by X0x1RG9f** [DefectDojo/django-DefectDojo#6069]
### Issue
When creating a Finding from a Template, the date given to the finding is not taken into account. Instead, date provided is erased by the date of the day. Date provided by the user should be taken into account if provided on the Form, as if normal Finding was created

### Solution
Pull request #6065 added in order to fix this issue.

**Comment by StefanFl** [comment]
merged for release 2.9.0
