### ISSUE TITLE
Issues on disconnection and connection using Social Auth

### ISSUE THREAD

**Issue by X0x1RG9f** [DefectDojo/django-DefectDojo#6070]
### Issue
Issue appear when SOCIAL_AUTH  "SHOW_LOGIN_FORM = False" are combined (no /login form) :
- When disconnecting, as return URL is not /login and does not contains next parameter, an error 500 is triggered.
- When connecting, message "You have logged out" is displayed after logging in.

### Solution
Pull Request #6066 added in order to fix this issue.

**Comment by manuel-sommer** [comment]
PR was merged. Could you close this @mtesauro ?
