### ISSUE TITLE
Edit Finding's mitigated time (EDITABLE_MITIGATED_DATA)

### ISSUE THREAD

**Issue by X0x1RG9f** [DefectDojo/django-DefectDojo#6071]
### Issue
When using "EDITABLE_MITIGATED_DATA = True", several issues are present within the DefectDojo application:
- Closing a finding with a mitigation date in the past close the finding badly:
  - The "active" parameter is not set to false and thus, Finding does not appear at ALL in the "Closed Finding" tab 👎.
  - The asset(s) linked to the finding is / are not affected and remain vulnerable, even if Finding is closed 👎.
- The form is added within the "Edit Finding" form, whereas there is a dedicated "Close Finding Form". Not very logical.
- Calendar Box used is not the standard DefectDojo one.

### Solution
A Pull Request #6067 added in order to fix the issues

The Fix contains:
- Close date is added within the "Close Finding" formulary and removed from "Edit Finding", which is much more logical.
- Calendar is set to the default one used in the whole app.
- Closing a finding with a date in the past sets also "active" to "False" and closes the linked asset. Nothing touched here, as we are now using functions of the "Close Finding" form !

**Comment by manuel-sommer** [comment]
@mtesauro , as the linked PR was merged, I don't know if this issue is still open.
