### ISSUE TITLE
Can not find the google sheet sync configuration in v2.8.0

### ISSUE THREAD

**Issue by anjai94** [DefectDojo/django-DefectDojo#6084]
As mentioned in the document [1], i can not find the any place to configure google sheet sync feature in Defectdojo v2.8.0. Please update the docs based on the new changes. 

[1] https://defectdojo.github.io/django-DefectDojo/integrations/google-sheets-sync/

**Comment by valentijnscholten** [comment]
What changes are you referring to? You can enable google sheets integration in System Settings.

**Comment by manuel-sommer** [comment]
I guess this can be closed @mtesauro
