### ISSUE TITLE
SAML2 force_authn environment variable

### ISSUE THREAD

**Issue by italvi** [DefectDojo/django-DefectDojo#6092]
**Is your feature request related to a problem? Please describe**
I want to make SSO with SAML2 possible.

**Describe the solution you'd like**
As an admin, I want to set an evironment variable to force_authn in SAML2, so that an user do not have to provide his credentials always.

**Additional context**
Provide a new Environment Variable, e.g., DD_SAML2_FORCE_AUTH and set force_authn to env('DD_SAML2_FORCE_AUTH') in the SAML_CONFIG dictionary

**Comment by italvi** [comment]
@dsever Done, but unfortunately the checker says it does not work. Seems like I did something wrong?

**Comment by StefanFl** [comment]
merged for release 2.9.0
