### ISSUE TITLE
Support HA PostgreSQL

### ISSUE THREAD

**Issue by bgoareguer** [DefectDojo/django-DefectDojo#6096]
**Is your feature request related to a problem? Please describe**
The DefectDojo Helm chart includes a dependency on the [postgresql](https://github.com/bitnami/charts/tree/master/bitnami/postgresql) Helm chart from Bitnami. This Helm chart does not support high availability (HA), it only supports master/slave replication.

But DefectDojo does not support configuring database writes to the PostgreSQL master and database reads to the PostgreSQL slaves, so the master/slave replication does not increase the global availability of the DefectDojo product.

In case the PostgreSQL master pod fails (e.g. because of a maintenance operation on the underlying node), the database is completely unavailable and DefectDojo is unusable (even with multiple PostgreSQL slaves).

**Describe the solution you'd like**
A solution would be to use the [postgresql-ha](https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha) Helm chart from Bitnami. This Helm chart supports high availability (HA) with database node failover.

**Comment by bgoareguer** [comment]
@valentijnscholten Do you have any feedback on this?

**Comment by dsever** [comment]
Resolved by: https://github.com/DefectDojo/django-DefectDojo/pull/6307
