### ISSUE TITLE
Potential Login Bug with product_owner credential

### ISSUE THREAD

**Issue by masofily** [DefectDojo/django-DefectDojo#610]
Please use the following template when submitting issues:

## Issue Template
Potential Login Bug with product_owner credential
### Issue Type 
- [ ] Bug
### Description
While trying to login with product_owner credential, I could found a potential bug on the login page. It seems the example site is not handling the error properly.

### DefectDojo Version
Bug found on https://defectdojo.pythonanywhere.com/login

### Steps to Reproduce
1. Launch https://defectdojo.pythonanywhere.com/login
2. Use correct credential for product_owner to login, you will get the below error:
KeyError at /metrics
u'Information'
Request Method:
GET 
Request URL:
https://defectdojo.pythonanywhere.com/metrics 
Django Version:
1.8.5 
Exception Type:
KeyError 
Exception Value:
u'Information'
 Exception Location:
/home/DefectDojo/django-DefectDojo/dojo/metrics/views.py in metrics, line 277 
Python Executable:
/usr/local/bin/uwsgi 
Python Version:
2.7.6 
Python Path:
['/var/www',

3. Return to https://defectdojo.pythonanywhere.com/login
4. You can see the page is asking for username/password. However, click on the top right corner image, it is showing you have logged in as product_owner.

**Comment by aaronweaver** [comment]
This will be addressed when pythonanywhere is updated.

**Comment by masofily** [comment]
Thanks @aaronweaver for your confirmation
