### ISSUE TITLE
how to solve this error "WARN[0000] The "DD_DATABASE_NAME" variable is not set. Defaulting to a blank string."

### ISSUE THREAD

**Issue by tx-abhay** [DefectDojo/django-DefectDojo#6108]
### Discussed in https://github.com/DefectDojo/django-DefectDojo/discussions/6107

<div type='discussions-op-text'>

<sup>Originally posted by **tx-abhay** April  1, 2022</sup>
![image](https://user-images.githubusercontent.com/100664313/161206213-e2fcac5f-bd33-40a6-9d3a-1e7a5cb3f7fb.png)
</div>

**Comment by valentijnscholten** [comment]
closing this as it is already being discussed in #6107
