### ISSUE TITLE
Cannot Import Nmap UDP Scan XML Results

### ISSUE THREAD

**Issue by ninp0** [DefectDojo/django-DefectDojo#611]
Please use the following template when submitting issues:

### Issue Type 
- [* ] Bug
- [ ] Enhancement

### Description
Nmap UDP XML Scan Results File is generated using the following nmap command:
```
nmap -iL targets.txt \
  -e $interface \
  --min-hostgroup 3 \
  --host-timeout 999m \
  -T4 \
  -Pn \
  -sU \
  -A \
  -oA "latest_udp_results"
```
Everything works fine when importing an Nmap TCP XML scan results file.  It Looks like the attrib method is being called on a None object class - please add a condition to check whether data is a None class prior to calling attrib.  This occurs when attempting to import latest_udp_results.xml:

AttributeError at /engagement/6/import_scan_results

'NoneType' object has no attribute 'attrib'

Request Method:              POST

Request URL:      https://defectdojo.DOMAIN/engagement/6/import_scan_results

Django Version: 1.11.11

Exception Type: AttributeError

Exception Value:              

'NoneType' object has no attribute 'attrib'

Exception Location:         /opt/django-DefectDojo/dojo/tools/nmap/parser.py in __init__, line 31

Python Executable:          /usr/bin/python

Python Version: 2.7.15

Python Path:      

['/opt/django-DefectDojo',

'/usr/lib/python2.7',

'/usr/lib/python2.7/plat-x86_64-linux-gnu',

'/usr/lib/python2.7/lib-tk',

'/usr/lib/python2.7/lib-old',

'/usr/lib/python2.7/lib-dynload',

'/usr/local/lib/python2.7/dist-packages',

'/usr/lib/python2.7/dist-packages',

'/usr/lib/python2.7/dist-packages/PILcompat',

'/usr/lib/python2.7/dist-packages/gtk-2.0',

'/usr/lib/python2.7/dist-packages/wx-3.0-gtk3',

'/opt/django-DefectDojo']

Server time:        Thu, 7 Jun 2018 15:19:32 +0000

 

 

 

Environment:

 

 

Request Method: POST

Request URL: http://defectdojo.whoami/engagement/6/import_scan_results

 

Django Version: 1.11.11

Python Version: 2.7.15

Installed Applications:

('django.contrib.auth',

'django.contrib.contenttypes',

'django.contrib.sessions',

'django.contrib.sites',

'django.contrib.messages',

'django.contrib.staticfiles',

'polymorphic',

'overextends',

'django.contrib.admin',

'django.contrib.humanize',

'gunicorn',

'tastypie',

'auditlog',

'dojo',

'tastypie_swagger',

'watson',

'tagging',

'custom_field',

'imagekit',

'multiselectfield')

Installed Middleware:

('django.middleware.common.CommonMiddleware',

'django.contrib.sessions.middleware.SessionMiddleware',

'django.middleware.csrf.CsrfViewMiddleware',

'django.contrib.auth.middleware.AuthenticationMiddleware',

'django.contrib.messages.middleware.MessageMiddleware',

'django.middleware.clickjacking.XFrameOptionsMiddleware',

'dojo.middleware.LoginRequiredMiddleware',

'dojo.middleware.TimezoneMiddleware')

 

 

 

Traceback:

 

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py" in inner

  41.             response = get_response(request)

 

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _legacy_get_response

  249.             response = self._get_response(request)

 

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _get_response

  187.                 response = self.process_exception_by_middleware(e, request)

 

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _get_response

  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

 

File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view

  23.                 return view_func(request, *args, **kwargs)

 

File "/opt/django-DefectDojo/dojo/engagement/views.py" in import_scan_results

  416.                 parser = import_parser_factory(file, t)

 

File "/opt/django-DefectDojo/dojo/tools/factory.py" in import_parser_factory

  42.         parser = NmapXMLParser(file, test)

 

File "/opt/django-DefectDojo/dojo/tools/nmap/parser.py" in __init__

  31.                 if 'name' in os.find('osmatch').attrib:

 

Exception Type: AttributeError at /engagement/6/import_scan_results

Exception Value: 'NoneType' object has no attribute 'attrib'

 

 

### Operating System 
Kali Rolling 2018.2

### Install

- [* ] setup.bash
- [ ] docker

### DefectDojo Version
v 1.3.0

### Steps to Reproduce
```
nmap -iL targets.txt \
  -e $interface \
  --min-hostgroup 3 \
  --host-timeout 999m \
  -T4 \
  -Pn \
  -sU \
  -A \
  -oA "latest_udp_results"
```
Import latest_udp_results.xml scan results into an engagement.

### Sample Scan File (if applicable)
Apologies, cannot provide scan results file.

**Comment by aaronweaver** [comment]
Fixed in dev branch. 

https://github.com/DefectDojo/django-DefectDojo/pull/613/commits/8a02105f6dee108e9849508774e1fc6fdbb730d5#diff-cd33e28b4ef579c12384b49d99f9a649

**Comment by ninp0** [comment]
How often is dev merged into master?

**Comment by aaronweaver** [comment]
Depends on the release. For this one it's probably going to be a week or more to ensure we've tested it. You can just pull this file down and swap it if you want. It's just one line that was added.
