### ISSUE TITLE
Checkmarx Integration with DefectDojo - DevSecOps

### ISSUE THREAD

**Issue by kramdass08** [DefectDojo/django-DefectDojo#6129]
Team - I'm able to manually upload Checkmarx XML Report to DefectDojo. Is there a plugin available for integrating Checkmarx with DefectDojo ? Are there any support/documentation available for Checkmarx Integration ? 

Thanks.

**Comment by ptrovatelli** [comment]
hello @kramdass08 ,
if by integration you mean a two-way link that updates defectdojo when things change in checkmarx and that updates checkmarx when things change in defectdojo, the answer is no. 

you can however automatically import checkmarx reports using the API

**Comment by celissac** [comment]
> hello @kramdass08 , if by integration you mean a two-way link that updates defectdojo when things change in checkmarx and that updates checkmarx when things change in defectdojo, the answer is no.
> 
> you can however automatically import checkmarx reports using the API

Is there any manual for this type of process?

**Comment by ptrovatelli** [comment]
One of our clients have opensourced their gitlab-ci pipeline template for defectdojo. This could help. Although you'll need to add checkmarx support (a couple of lines of code to fetch checkmarx reports and send them to defectdojo like the others)

- doc: https://to-be-continuous.gitlab.io/doc/ref/defectdojo/
- code: https://gitlab.com/to-be-continuous/defectdojo

**Comment by Akshay0570** [comment]
Is it only supported for Gitlab?
I am trying to push the report using jenkins, what to do to push the report from checkmarx to defectdojo

**Comment by mtesauro** [comment]
I've done that in the past by just using API calls from the Jenkins job (and yes, it was Checkmarx SAST scan output)

**Comment by manuel-sommer** [comment]
I guess this can be closed @mtesauro
