### ISSUE TITLE
JIRA_PKey matching query does not exist.

### ISSUE THREAD

**Issue by eik18** [DefectDojo/django-DefectDojo#614]
Please use the following template when submitting issues:

### Issue Type 
- [ x] Bug
- [ ] Enhancement

### Description
JIRA_PKey matching query does not exist. is occurring again  See 
This is occurring -> https://github.com/DefectDojo/django-DefectDojo/issues/276

### Operating System 
Please include the version number (ex: Ubuntu 16.04)
Centos 7.4

### Install

- [ x] setup.bash
- [ ] docker

### DefectDojo Version
Latest Pull from master (Plus addition of postfixcentos2 and (new) trustwave parser attempt.  Did not touch jira areas.

### Steps to Reproduce
Enable (but don't configure jira).  open issue.  Uncheck jira . Try to close via review workflow. 

### Console Logs (optional)
Environment:

Request Method: POST
Request URL: https://dojo.security.qa.ops.brightcove.com/finding/1415/defect_review

Django Version: 1.11.11
Python Version: 2.7.5
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'polymorphic',
 'overextends',
 'django.contrib.admin',
 'django.contrib.humanize',
 'gunicorn',
 'tastypie',
 'auditlog',
 'dojo',
 'tastypie_swagger',
 'watson',
 'tagging',
 'custom_field',
 'imagekit',
 'multiselectfield')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'dojo.middleware.LoginRequiredMiddleware',
 'dojo.middleware.TimezoneMiddleware')

Traceback:

File "/usr/local/brightcove/dojo/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/usr/local/brightcove/dojo/lib/python2.7/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/usr/local/brightcove/dojo/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/brightcove/dojo/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/brightcove/dojo/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "./dojo/finding/views.py" in defect_finding_review
  271.                 jira = get_jira_connection(finding)

File "./dojo/utils.py" in get_jira_connection
  681.     jpkey = JIRA_PKey.objects.get(product=prod)

File "/usr/local/brightcove/dojo/lib/python2.7/site-packages/django/db/models/manager.py" in manager_method
  85.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/usr/local/brightcove/dojo/lib/python2.7/site-packages/django/db/models/query.py" in get
  380.                 self.model._meta.object_name

Exception Type: DoesNotExist at /finding/1415/defect_review
Exception Value: JIRA_PKey matching query does not exist.

**Comment by aaronweaver** [comment]
Fixed in the upcoming 1.4 release. @eik18 will you be able to share the trustwave parser?

**Comment by eik18** [comment]
Yes. Just debugging a bit. Was also waiting to rebase against new master.

**Comment by eik18** [comment]
Hey Aaron. Just pushed it. Sorry for the two accounts. One is my work one,
one is my personal one.

**Comment by alekbc** [comment]
Hi @aaronweaver , I think this is a duplicated of "JIRA_Issue matching query does not exist." It's probably a misconfiguration issue.
