### ISSUE TITLE
Update Black Duck Hub importer

### ISSUE THREAD

**Issue by sjs6776** [DefectDojo/django-DefectDojo#6153]
**Issue**
The current Black Duck Hub version (2022.2.0) has more fields in the security.csv (Most importantly "CWE Ids"). We would like to have the CWEs imported alongside the rest of the information. 

https://testing.blackduck.synopsys.com/doc/reporting/projectversionreport.htm

**Sample File**
[security_YYYY-MM-DD_XXXXXX.csv](https://github.com/DefectDojo/django-DefectDojo/files/8476328/security_YYYY-MM-DD_XXXXXX.csv)

**Comment by damiencarol** [comment]
I can take this one.

**Comment by damiencarol** [comment]
@sjs6776 pushed a PR to add an importer in dojo. this should make the import easier https://github.com/DefectDojo/django-DefectDojo/pull/6679

**Comment by manuel-sommer** [comment]
I guess this can be close @mtesauro
