### ISSUE TITLE
New tools for kubernetes, terraform and keycloak config scans.

### ISSUE THREAD

**Issue by fproof** [DefectDojo/django-DefectDojo#6157]
Name: KubiScan
URL: https://github.com/cyberark/KubiScan
Desc: A tool for scanning Kubernetes cluster for risky permissions in Kubernetes's Role-based access control (RBAC) authorization model. The tool was published as part of the "Securing Kubernetes Clusters by Eliminating Risky Permissions" research https://www.cyberark.com/threat-research-blog/securing-kubernetes-clusters-by-eliminating-risky-permissions/.
Sample output:
[risky_roles.txt](https://github.com/DefectDojo/django-DefectDojo/files/8483420/risky_roles.txt)

Name: keycloak-scanner
URL: https://github.com/NeuronAddict/keycloak-scanner
Desc: This scanner scan keycloak for known vulnerabilities.
Sample output:
https://imgur.com/a/ssRVpVu

Name: tfsec
URL: https://github.com/aquasecurity/tfsec
Desc: tfsec uses static analysis of your terraform code to spot potential misconfigurations.
Sample output:
https://imgur.com/a/lHCOHkL

**Comment by manuel-sommer** [comment]
[tfsec](https://defectdojo.github.io/django-DefectDojo/integrations/parsers/file/tfsec/) is already covered

**Comment by manuel-sommer** [comment]
@fproof do you have sample data for tfsec? Also, I am not sure if the output from KubiScan you shared here is right as I did not see an output being provided.

**Comment by manuel-sommer** [comment]
@fproof do you have an Update here?

**Comment by manuel-sommer** [comment]
I don't know if we need to keep this issue open @mtesauro as there was no response for a month

**Comment by mtesauro** [comment]
Agreed.
