### ISSUE TITLE
Missing Black Duck Hub Deduplication

### ISSUE THREAD

**Issue by sjs6776** [DefectDojo/django-DefectDojo#6161]
**Slack us first!**

Archive of message:
https://owasp.slack.com/archives/C014H3ZV9U6/p1649801536535069

**Bug description**
Settings.dist.py does not include deduplication for Blackduck Hub Scans.

**Expected behavior**

The following code was added in our local DD instance, which resulted in successful deduplication of Black Duck Hub Scans:

cat -n settings.dist.py | grep duck
 1023 'Blackduck Hub Scan': ['title', 'cve', 'component_name'],
 1147 'Blackduck Hub Scan': DEDUPE_ALGO_HASH_CODE,

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Ubuntu 18.04
 - DefectDojo version: 2.8.0

**Comment by damiencarol** [comment]
fixed with #6623
