### ISSUE TITLE
CWE integer parsing problem on Acunetix

### ISSUE THREAD

**Issue by hasansimsekinvicti** [DefectDojo/django-DefectDojo#6168]
Hi there,

There is a parsing problem on Acunetix codes. There are PRs according to the issue like below. 
https://github.com/DefectDojo/django-DefectDojo/pull/6100
https://github.com/DefectDojo/django-DefectDojo/pull/5970

For Netsparker, this issue is fixed with this commit.
https://github.com/DefectDojo/django-DefectDojo/commit/63cdba42233d879b8c21b84e743cf17e3c0a8bc9

Could you implement the fix please?

**Comment by StefanFl** [comment]
merged for release 2.11
