### ISSUE TITLE
Celery add_issue_task UnboundLocalError

### ISSUE THREAD

**Issue by mattvaldes** [DefectDojo/django-DefectDojo#618]
Please use the following template when submitting issues:

### Issue Type 
**Bug**

### Description
Celery add_issue_task UnboundLocalError
`celeryworker[1366]: [2018-06-07 00:32:23,318: ERROR/ForkPoolWorker-3] Task add_issue_task[6439ddf4-bd65-4e4a-ae2b-be0e24280547] raised unexpected: UnboundLocalError("local variable 'labels' referenced before assignment",)
celeryworker[1366]: Traceback (most recent call last):
celeryworker[1366]:   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 374, in trace_task
celeryworker[1366]:     R = retval = fun(*args, **kwargs)
celeryworker[1366]:   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 629, in __protected_call__
celeryworker[1366]:     return self.run(*args, **kwargs)
celeryworker[1366]:   File "/data/prod_dojo/django-DefectDojo/dojo/tasks.py", line 206, in add_issue_task
celeryworker[1366]:     add_issue(find, push_to_jira)
celeryworker[1366]:   File "/data/prod_dojo/django-DefectDojo/dojo/utils.py", line 770, in add_issue
celeryworker[1366]:     add_labels(find, new_issue)
celeryworker[1366]:   File "/data/prod_dojo/django-DefectDojo/dojo/utils.py", line 723, in add_labels
celeryworker[1366]:     if labels is not None:
celeryworker[1366]: UnboundLocalError: local variable 'labels' referenced before assignment
`

### Operating System 
Please include the version number (ex: Ubuntu 16.04)
Ubuntu 16.04.4 LTS
### Install

 **setup.bash**

### DefectDojo Version
1.3.1

### Steps to Reproduce
Use Jira Push feature.
View syslog for celery errors.
### Screenshots (optional)
<img width="578" alt="screen shot 2018-06-12 at 1 45 58 pm" src="https://user-images.githubusercontent.com/6217829/41310413-0da9a70c-6e47-11e8-8090-c3fa0948480c.png">

### Console Logs (optional)

See above.

**Comment by aaronweaver** [comment]
Will be fixed in the upcoming 1.4 release:

`labels = system_settings.jira_labels.split()
    if len(labels) > 0:
        for label in labels:
            issue.fields.labels.append(label)`
