### ISSUE TITLE
wfuzz not importing

### ISSUE THREAD

**Issue by vulnz** [DefectDojo/django-DefectDojo#6182]
Good day, thanks for your contributions.
Wfuzz is not uploading

![image](https://user-images.githubusercontent.com/20043135/165205782-8ae9a9d9-fcea-462a-8b6f-e04545447a9e.png)

![image](https://user-images.githubusercontent.com/20043135/165205864-71531b17-168e-4a15-956a-ba1e7da6ee31.png)

Please check if you see some error, but as i see it is json.

thanks

**Comment by valentijnscholten** [comment]
Please provide all the info requested in the bug report template.

**Comment by manuel-sommer** [comment]
Do you have a sample file @vulnz ?

**Comment by manuel-sommer** [comment]
Could you please close this issue @mtesauro ?
