### ISSUE TITLE
500 error when editing or adding user and new FEATURE_CONFIGURATION_AUTHORIZATION configuration if not superuser

### ISSUE THREAD

**Issue by martinmarsicano** [DefectDojo/django-DefectDojo#6198]
**Bug description**
When the new FEATURE_CONFIGURATION_AUTHORIZATION configuration is used, if a user is not configured as superuser and tries to add a user via the UI, it gets a 500 error, even if it has the add_user permission.

**Steps to reproduce**
1. Go to Users
2. Create a User with no superuser role.
3. Give that User, User/Add permission
_User permission proof_
<img width="1935" alt="Screen Shot 2022-04-27 at 17 45 58" src="https://user-images.githubusercontent.com/33671308/165627939-9d8d15c0-723a-4feb-bb34-799da28bb2d3.png">
4. Login as the created User.
5. Go to Users
6. Click on Add User button
7. Get 500 error

**Expected behavior**
The user should be able to access and add a User.

**Deployment method** *(select with an `X`)*
- [ X ] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - DefectDojo version: tested on v.2.8.0 and v.2.9.0

**Logs** 
_Error received by email and on log_
![Screen Shot 2022-04-27 at 17 49 56](https://user-images.githubusercontent.com/33671308/165628510-8f333f4d-648a-4510-88e7-1d6ae446dcb0.png)

_Traceback_
![Screen Shot 2022-04-27 at 17 50 36](https://user-images.githubusercontent.com/33671308/165628610-44f3363a-e0fd-4cda-b729-e9a35891e09c.png)

**Comment by valentijnscholten** [comment]
fixed in `dev`/ 2.10.0
