### ISSUE TITLE
The execution command is unresponsive

### ISSUE THREAD

**Issue by Sharlong-Wen** [DefectDojo/django-DefectDojo#6213]
my execution command is unresponsive how can i resolve it？
![image](https://user-images.githubusercontent.com/86757800/165922418-a9d9f173-ac96-44ef-989e-b915b12e109e.png)

**Comment by valentijnscholten** [comment]
Follow this: https://github.com/DefectDojo/django-DefectDojo/blob/dev/readme-docs/DOCKER.md
You may have to update docker + compose to a recent version
