### ISSUE TITLE
SpotBugs JSON

### ISSUE THREAD

**Issue by httpnotonly** [DefectDojo/django-DefectDojo#6215]
**Scanner Name**
SpotBugs in docker form gitlab team
`registry.gitlab.com/gitlab-org/security-products/analyzers/spotbugs:2.15.2`

**Sample JSON**
[gl-sast-report.txt](https://github.com/DefectDojo/django-DefectDojo/files/8590647/gl-sast-report.txt)

So, it could make our security pipeline better for JAVA
https://gitlab.com/whitespots-public/vulnerable-java-app/-/jobs/2395182651

**Comment by damiencarol** [comment]
I don't understand, what is missing? it seems your pipeline is already able to push data to a DD instance.

**Comment by httpnotonly** [comment]
The problem is that I have 500 error. Just try it on your demo instance

**Comment by httpnotonly** [comment]
I think it expects xml, not json

**Comment by damiencarol** [comment]
I agree. I'm checking the code of the pipeline. What is the format of the report? it doesn't seems to be a SpotBugs report.

**Comment by damiencarol** [comment]
I see the pb now, the format is not good. the pipeline should use the GitLab SAST format
See:
```
curl -s -D - --insecure -X POST https://dd-demo.whitespots.io/api/v2/import-scan/ -H 'accept: application/json' -H 'Content-Type: multipart/form-data' -H 'Authorization: Token [MASKED]' -F file=@./gl-sast-report.json -F 'scan_type=SpotBugs Scan' -F engagement=34 -F active=true -F verified=false -F group_by=file_path -F close_old_findings=false -F scan_date=2022-04-29
```

**Comment by httpnotonly** [comment]
Nice!
So, let's close this 🙂
Maybe someone will find the answer for a the same question

**Comment by damiencarol** [comment]
if you use the 'Gitlab SAST' format DD is able to load it, see it on the demo:

![image](https://user-images.githubusercontent.com/1694940/166100113-d687d36c-8f03-4e05-83d8-312c3933b99f.png)

**Comment by damiencarol** [comment]
@httpnotonly your line here is wrong https://gitlab.com/whitespots-public/pipelines/-/blob/main/common/code-scan.yml#L164
you must change the value to this 
![image](https://user-images.githubusercontent.com/1694940/166100368-3301bfe7-2367-4d50-a682-73b4c828affe.png)

**Comment by httpnotonly** [comment]
Yes
Fixed, thanks

**Comment by httpnotonly** [comment]
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/38507289/166100526-1931c6e9-cdba-4e4a-ae02-e3cc639c94e7.png">

And finally
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/38507289/166100543-43f1dd7b-b434-44e6-9128-fcb76cddb2f5.png">

**Comment by damiencarol** [comment]
lovely :+1:  <3
