### ISSUE TITLE
Error when importing generic findings with UTF-8 chars (smart qutoes)

### ISSUE THREAD

**Issue by 37b** [DefectDojo/django-DefectDojo#623]
Please use the following template when submitting issues:

### Issue Type 
- [X ] Bug
- [ ] Enhancement

### Description
(Docker Image) Error when importing Generic Findings from CSV with UTF-8 bytes (smart quotes in this case)
### Operating System 
Ubuntu 16.04.4 LTS \n \l

### Install

- [ ] setup.bash
- [x ] docker

### DefectDojo Version
1.3.0

### Steps to Reproduce
Import generic findings from csv file

### Console Logs (optional)

Request Method: | POST
-- | --
http://localhost:8000/engagement/4/import_scan_results
1.11.11
UnicodeDecodeError
'ascii' codec can't decode byte 0xe2 in position 85: ordinal not in range(128)
/opt/django-DefectDojo/dojo/models.py in get_hash_code, line 758
/usr/bin/python
2.7.12
['/opt/django-DefectDojo',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages',  '/opt/django-DefectDojo']
Mon, 18 Jun 2018 20:37:36 +0000

[test_51445703.txt](https://github.com/DefectDojo/django-DefectDojo/files/2112909/test_51445703.txt)

**Comment by aaronweaver** [comment]
Will be fixed in the upcoming 1.4 release.
