### ISSUE TITLE
Snyk Scan parse: cvssScore null value causes exception for operator

### ISSUE THREAD

**Issue by P440Boyd** [DefectDojo/django-DefectDojo#6230]
**Description** 

cvssScore values of null cause an exception in the Snyk Scan parser, which permits only integer or float. 

**Expected behavior**
The vulnerability should be parsed without its cvssScore component, with field populated appropriately.

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04
 - DefectDojo version [2.9.1](https://hub.docker.com/layers/defectdojo-django/defectdojo/defectdojo-django/2.9.1/images/sha256-7f3d39336319ceb16fa8a7d740104822088aaa9f0d7f52cd0e38a868a159f95b?context=explore)
 - 
**Logs** 

**An exception error occurred during the report import:'<=' not supported between instances of 'NoneType' and 'float' **

**Sample scan files**

**Comment by P440Boyd** [comment]
This isn't too tricky a fix and I can crack on with it along with testcase from my scan result sample - However, I'm unsure how the null value should be handled and could do with advice on that.

**Comment by damiencarol** [comment]
@P440Boyd thanks for your feedback. Create a PR and we will gladly help you.
