### ISSUE TITLE
/product/add can be accessed by users with no authorization

### ISSUE THREAD

**Issue by elihu** [DefectDojo/django-DefectDojo#6247]
Hi, I was reviewing authorization policies in my test instance and founded some endpoints accessible from an user without authorization.

I've created a test user with read-only access in the demo instance of defectodojo (https://demo.defectdojo.org/) an it also happen there.
![image](https://user-images.githubusercontent.com/4126552/166648290-52760375-3db7-44f4-bef7-3067a4aa7879.png)

Product creation is not visible for this user in UI, but if I insert the /product/add endpoint in the URL I can access the product creation view.
![image](https://user-images.githubusercontent.com/4126552/166648328-5703a8b4-ab88-43f4-8efe-27ee843df839.png)

I cannot create the product in UI because the product_type listing is correctly protected and cannot associate the new product with any product_type. But It should return a HTTP 403 like the endpoint /product/type/add does.
![image](https://user-images.githubusercontent.com/4126552/166648363-0a2f858b-56be-49c9-aa75-d590e0aaf2b0.png)

It also happen when I try to access /endpoint/migrate with this test user.

Hope this helps, Regards

**Comment by damiencarol** [comment]
you mean you can access the page but not validate ?

**Comment by elihu** [comment]
I can access the page with an user with no permissions to access that page just typing the url.
But I cannot create a product though, because I can't select a valid product_type.
