### ISSUE TITLE
Suddenly Import Scan Results function not working

### ISSUE THREAD

**Issue by ishara** [DefectDojo/django-DefectDojo#625]
### Issue Type 
- [ ] Bug

### Operating System 
CenteOS 7

### Install

- [ ] setup.bash

### DefectDojo Version

current git master branch -date checkout  6-19-2018

### Steps to Reproduce

Suddenly Import Scan Results function not working, previously this is working fine. 

### Console Logs (optional)
Environment:

Request Method: POST
Request URL: http://192.168.2.157:8000/engagement/3/import_scan_results

Django Version: 1.11.11
Python Version: 2.7.5
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'polymorphic',
 'overextends',
 'django.contrib.admin',
 'django.contrib.humanize',
 'gunicorn',
 'tastypie',
 'auditlog',
 'dojo',
 'tastypie_swagger',
 'watson',
 'tagging',
 'custom_field',
 'imagekit',
 'multiselectfield')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'dojo.middleware.LoginRequiredMiddleware',
 'dojo.middleware.TimezoneMiddleware')

Traceback:

File "/opt/dojo/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/opt/dojo/lib/python2.7/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/opt/dojo/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/opt/dojo/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/opt/dojo/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/opt/dojo/django-DefectDojo/dojo/engagement/views.py" in import_scan_results
  468.                     item.save()

File "/opt/dojo/django-DefectDojo/dojo/models.py" in save
  894.                 if self.reporter.usercontactinfo.block_execution:

File "/opt/dojo/lib/python2.7/site-packages/django/utils/functional.py" in inner
  239.         return func(self._wrapped, *args)

File "/opt/dojo/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py" in __get__
  407.                     self.related.get_accessor_name()

Exception Type: RelatedObjectDoesNotExist at /engagement/3/import_scan_results
Exception Value: User has no usercontactinfo.

**Comment by ishara** [comment]
This is happening when enable  "False positive history".

**Comment by aaronweaver** [comment]
@ishara fix pushed to 1.4 dev branch shortly. If you want it to work now with no modifications disable false positive history or you can apply this patch in models.py.

if system_settings.false_positive_history:
                from dojo.tasks import async_false_history
                from dojo.utils import sync_false_history
                try:
                    if self.reporter.usercontactinfo.block_execution:
                        sync_false_history(self, *args, **kwargs)
                    else:
                        async_false_history.delay(self, *args, **kwargs)
                except:
                    async_false_history.delay(self, *args, **kwargs)
                    pass
