### ISSUE TITLE
Whether this product supports Chinese interface？

### ISSUE THREAD

**Issue by Sharlong-Wen** [DefectDojo/django-DefectDojo#6250]
Whether this product supports Chinese interface？

**Comment by damiencarol** [comment]
@Sharlong-Wen thanks for your interest. We have a couple of feature to support other languages.
Take a look at the https://github.com/DefectDojo/django-DefectDojo/tree/master/dojo/locale/en/LC_MESSAGES folder.
You can add another language like Chinese

**Comment by Sharlong-Wen** [comment]
I'm new to this industry and I don't quite understand how to add it. Do I need to write the translated "msgid" into "msgstr"?
![image](https://user-images.githubusercontent.com/86757800/167084591-4eeaa3f1-2cbb-4e32-853b-2d01a03ed064.png)

**Comment by damiencarol** [comment]
Yes. more details here: https://help.phrase.com/help/gettext-po-files

**Comment by wei777-cyber** [comment]
我是一个新手，我想学习这个项目但是不知道具体应该如何操作？
