### ISSUE TITLE
Veracode SCA Vulns with Same CVE Not Importing

### ISSUE THREAD

**Issue by cah-thomas-howard** [DefectDojo/django-DefectDojo#6252]
When parsing through SCA components, the 'dup_key' is set to the CVE ID. As a result, when two or more components have the same CVE, only the first one is imported.

Code in question:
![Screen Shot 2022-05-05 at 8 49 10 AM](https://user-images.githubusercontent.com/38532219/166932499-653acf6d-fc5a-4e1e-97fd-4c073f027144.png)

Veracode report showing two components with the same CVE:
![Screen Shot 2022-05-05 at 9 10 13 AM](https://user-images.githubusercontent.com/38532219/166932646-97d5e561-cbb7-4cf0-b80b-a720797c3255.png)

Only one component imported:
![Screen Shot 2022-05-05 at 9 07 11 AM](https://user-images.githubusercontent.com/38532219/166932966-f4645a9e-52b8-4e7a-a93e-894740a6f9e1.png)

Perhaps the dup_key could be a combination of the component_id and cve_id? That way each component will be imported but any dupe CVEs within the component vulns will be removed.

Code in question:
https://github.com/DefectDojo/django-DefectDojo/blob/612a0f682ae0a4e007196de4f438782464b3ae3d/dojo/tools/veracode/parser.py#L70

**Comment by coheigea** [comment]
@StefanFl It can be closed now I think

**Comment by damiencarol** [comment]
@coheigea I reviewed your PR and it's good as it fixes the bug but I really think that we should get ride of the internal aggregation and simplify the parser. we should not do the de-duplication in the parser.
It's ok for now but we can simplify code in later PRs
