### ISSUE TITLE
Product Dependencies

### ISSUE THREAD

**Issue by aaronweaver** [DefectDojo/django-DefectDojo#626]
Create the ability for products to be dependent on one another and allow inherited vulnerabilities from the dependent apps to show in the overall risk.

For example take Acme Product which consists of three main apps:

1. Web Application
2. API
3. Mobile App

The dependencies would be between the API and the web app and the mobile app and the api. If a vuln exists in the API this would "trickle" down to the mobile or web app.

**Comment by pb13** [comment]
Is there any solution to this?
In our situation, we are developing a software product that consists of multiple microservices. Each microservice is developed/maintained by a dedicated team and is built into a docker container. All containers use the same base image and some microservices include shared libraries.
We are currently evaluating ways to model this effectively within DefectDojo. Is it wise to create a product for each microservice, shared library and the base image? How can we then filter (or even deduplicate) findings across multiple products?
