### ISSUE TITLE
Import of XML report of fortify 20.1.1 failed

### ISSUE THREAD

**Issue by ludan-nin** [DefectDojo/django-DefectDojo#6260]
Scan the code with fortify version 20.1.1 and generate the XML report with the following command (provided that the FPR file has been successfully generated):

./path/to/ReportGenerator -format xml -f /path/to/output. xml -source /path/to/downloaded/artifact. fpr -template DefaultReportDefinitionAllIssues. xml

The generated XML file is uploaded through the defectdojo page,

Click: all product - > select a product - > engagements - > View engagements - > select the specified engagement - > type I to open the upload interface and fill in the parameters:

Minimum severity:Low

Scan type:Fortify Scan

Environment:Default

Choose report file: select the file to upload

The final filled interface is shown in the following screenshot:

![image](https://user-images.githubusercontent.com/84755351/167248723-b813c060-2d37-4c94-890f-622ed71ce731.png)

Click Import to display:

An exception error occurred during the report import:Unknown string format: 2022-5-6. a.source

The following screenshot:
![image](https://user-images.githubusercontent.com/84755351/167249056-b244adfe-4894-4561-b8a7-2a3ef4e0ba3e.png)

By analyzing the source code of defectdojo and the unit test file of fortify, it is found that there is an error in the date parsing of the text tag in the XML file of fortify. The date format generated by the fortify version I use is 2022-5-6, Screenshot:

![image](https://user-images.githubusercontent.com/84755351/167249424-28e22805-be05-45e7-8af3-276324bc73fa.png)

The format of defectdojo parsing is Dec 17, 2019, screenshot:

![0880c4c80710f1b09d02](https://user-images.githubusercontent.com/84755351/167249389-386e4942-2590-4a47-8a97-643d5785be46.png)

Therefore, there is an error in parsing. The parsing can be successfully uploaded by modifying the format

**Comment by damiencarol** [comment]
@ludan-nin can you provide a report that fail (even obfuscated) ? I can produce a patch quickly if you have one.

**Comment by ludan-nin** [comment]
[report.zip](https://github.com/DefectDojo/django-DefectDojo/files/8649730/report.zip)
This is a report generated by fortify@damiencarol
