### ISSUE TITLE
DrHeader JSON Importer Deduplication is not working right

### ISSUE THREAD

**Issue by manuel-sommer** [DefectDojo/django-DefectDojo#6280]
**Be informative**
DrHeader v1.7.0 supports severity adjustment for findings. I uploaded a file with findings, adjusted the severity as I wanted to update the DrHeader severities and reuploaded the findings with a new severity. The duplicates are not removed and the severities of existing findings are not adjusted.  

**Bug description**
Deduplication is not working for DrHeader

**Steps to reproduce**
1. Use DrHeader version 1.7.0 and upload the report to DefectDojo v. 2.11.0-dev 
2. Use DrHeader version 1.7.0 with custom severity (this is a new feature) and upload the report to DefectDojo v. 2.11.0-dev 
3. The severity of existing findings is not adjusted and findings are not deduplicated.

**Expected behavior**
A deduplication and severity adjustment should be achieved. 

**Deployment method** *(select with an `X`)*
- [x] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Ubuntu 18.04
 - DefectDojo version v. 2.11.0-dev ( 7e2caf59 )

**Sample scan files**
[scanresults.zip](https://github.com/DefectDojo/django-DefectDojo/files/8662928/scanresults.zip)

**Screenshots**
![Screenshot from 2022-05-10 17-30-28](https://user-images.githubusercontent.com/47991713/167666085-36fb840f-6739-471c-8503-b56709df722d.png)

**Comment by StefanFl** [comment]
merged for release 2.11
