### ISSUE TITLE
Duplicates not detected.

### ISSUE THREAD

**Issue by vulnz** [DefectDojo/django-DefectDojo#6290]
Duplicates do not work if upload zap report using api.

![image](https://user-images.githubusercontent.com/20043135/168044802-e4ca55fc-e32c-467b-ae78-ccbfde113795.png)

**Comment by manuel-sommer** [comment]
Hi @vulnz,
I retested this with the frontend and API. For me, this works fine, I used this scan result to retest it:
https://github.com/DefectDojo/django-DefectDojo/blob/master/unittests/scans/zap/zap-results-first-scan.xml 

**Frontend:**
![Screenshot from 2022-05-18 09-35-49](https://user-images.githubusercontent.com/47991713/168983629-7997a87f-9a4f-47ef-b080-1337a492f7c0.png)

**API:**
![Screenshot from 2022-05-18 09-32-44](https://user-images.githubusercontent.com/47991713/168983147-54224499-750a-4879-8995-0e0ba6b2687d.png)

Furthermore, in the settings.dist.py, there are the relevant settings for ZAP:
https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/settings/settings.dist.py

**Comment by elihu** [comment]
Is your celery running? and have you checked the deduplication option in system settings?
<img width="879" alt="image" src="https://user-images.githubusercontent.com/4126552/172428610-7c909371-e200-47e7-aea8-a3269542e98f.png">

**Comment by manuel-sommer** [comment]
I guess this can be closed @mtesauro
