### ISSUE TITLE
Incorrect links in engagement_added.tpl template

### ISSUE THREAD

**Issue by bgoareguer** [DefectDojo/django-DefectDojo#6296]
As a user, I activated email notifications for new engagements on a specific product.

**Bug description**
The email I receive contains links to the product and the engagement but they both point to the main DefectDojo URL.

**Expected behavior**
The links should point to the product page and the engagement page.

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [x] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Ubuntu 20.04
 - DefectDojo version: 2.10.0

**Comment by StefanFl** [comment]
merged for release 2.11
