### ISSUE TITLE
Attributes 'created' and 'updated' in Product and Contact models is missing a default/auto value

### ISSUE THREAD

**Issue by Nefast0** [DefectDojo/django-DefectDojo#6306]
I hope the title is self-explanatory.

**Product** model (_created_ and _updated_ attributes):
https://github.com/DefectDojo/django-DefectDojo/blob/612a0f682ae0a4e007196de4f438782464b3ae3d/dojo/models.py#L790

**Contact** model (_updated_ attribute):
https://github.com/DefectDojo/django-DefectDojo/blob/8667488e06c78dc6823102027569156a0375f98a/dojo/models.py#L530

Other models such as _Alert_ and _Finding_, use either `auto_now_add=True` or `default=now`

**Comment by StefanFl** [comment]
merged for release 2.12
