### ISSUE TITLE
Error Parsing Burp XML report 

### ISSUE THREAD

**Issue by s4bu** [DefectDojo/django-DefectDojo#631]
### Issue Type 
- [ ] Bug
While importing burp scan results application shows error in request method mentioned for AJP protocol in burp report xml. 

### Description
Issue occurs because of some gibberish value stored in request method specifically for AJP protocol in burp xml files. I temporarily fixed this issue by replacing all these value with 'GET'.
![defectdojobug](https://user-images.githubusercontent.com/10358578/41646713-2815ef96-7492-11e8-82c6-801cf8ca1226.PNG)

This specific request method is there for all AJP/8009 protocol reported issues. I guess this is binary representation of used method.

### Operating System 
Docker

### Install
- [ ] docker

### DefectDojo Version
v 1.3.0

**Comment by aaronweaver** [comment]
@s4bu any chance you could share the snippet in text?

**Comment by s4bu** [comment]
PFA.
[BurpReportDefectDojo.txt](https://github.com/DefectDojo/django-DefectDojo/files/2127410/BurpReportDefectDojo.txt)

**Comment by aaronweaver** [comment]
@s4bu Tested with your file and it loads. Fix in dev.

https://github.com/DefectDojo/django-DefectDojo/blob/dev/dojo/tools/burp/parser.py#L61
