### ISSUE TITLE
CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by isrc-team** [DefectDojo/django-DefectDojo#6329]
We have installed DefectDojo with the Docker option in Debian 11.

Reverse proxy has been configured to protect the machine with a public ip. 

After accessing with the proxy ip and login we get the following error:

![image](https://user-images.githubusercontent.com/106073386/169848082-83f740e0-f0b7-4b37-8b5e-24009381406c.png)

After reviewing previous problems in this platform, we have realized that we have to add the **CSRF_TRUSTED_ORIGINS** variable, but we do not know in which file to do it, since the installation has been done on top of the docker.

This is the structure of the DefectDojo folder: 
![image](https://user-images.githubusercontent.com/106073386/169855951-bf0c38af-3818-42c7-96aa-1fd253b933cb.png)

Thank you,

**Comment by dsever** [comment]
You can overwrite default settings using localsettings please follow https://defectdojo.github.io/django-DefectDojo/getting_started/configuration/#local_settingspy-not-with-kubernetes

**Comment by isrc-team** [comment]
Thank you!
We have been able to solve the problem, with the documentation provided.

**Comment by dsever** [comment]
Closing

**Comment by surajanuja** [comment]
> Thank you! We have been able to solve the problem, with the documentation provided.

@isrc-team Can you share how did you resolve this issue? Did you made any changes in settings.dist.py or any other settings file you have created and what is the settings that you have added?

**Comment by mtesauro** [comment]
As the linked PR above shows, you need CSRF_TRUSTED_ORIGINS

You can set that in local_settings.py or use an environmental variable like:
`DD_CSRF_TRUSTED_ORIGINS="https://my.domain.com"`

More details at https://docs.djangoproject.com/en/4.0/ref/settings/#csrf-trusted-origins
