### ISSUE TITLE
Make DefectDojo Publicly Accessible

### ISSUE THREAD

**Issue by ayush0033** [DefectDojo/django-DefectDojo#6349]
Hello,

We require our DefectDojo to be publicly accessible we have already modified Allowed hosts by changing it to 0.0.0.0 and DD_SITE_URL to our IP Address in dojo/settings/settings.dist.py but still, it isn't public. Requesting support over it.

Regards

**Comment by manuel-sommer** [comment]
I think this is rather something for the slack channel. Please close @mtesauro
