### ISSUE TITLE
Veracode Scan results do not include line, function, and sourcefile

### ISSUE THREAD

**Issue by jimminycrickett** [DefectDojo/django-DefectDojo#638]
Please use the following template when submitting issues:

### Issue Type 
- [X] Bug
- [ ] Enhancement

### Description
While the Veracode scan parser.py _does_ call out the sourcefile, function, and line number values, these aren't requested in  'django-DefectDojo/dojo/test/views.py' on lines 490-502 and are not associated with the completed finding. Loosing this information hampers the developers ability to identify where the vulnerability is. The information brought out of a veracode scan is essentially "there's an XSS bug in your code...somewhere...good luck". 
### Operating System 
Please include the version number (ex: Ubuntu 16.04)
N/A
### Install

- [ ] setup.bash
- [X] docker

### DefectDojo Version
1.3.0

### Steps to Reproduce
Import a Veracode "detailedreport.do" xml scan. Look at resultant finding for line number, source file, and vulnerable function name

**Comment by jimminycrickett** [comment]
after looking at the code, I think breaking out the 
"if 'Veracode' or 'Arachni'" test on line 490 and adding 
'line=item.line', sourcefilepath=item.sourcefilepath' to the inputs would resolve this. That said, I'm no developer and there's probably a much better way of doing it 😄

**Comment by aaronweaver** [comment]
@jimminycrickett Would you be able to provide me with a sample file or maybe scan the bodgeit app or something like that?

**Comment by jimminycrickett** [comment]
Absolutely, I've sanitized one of our scans and sent it to you via Slack

**Comment by aaronweaver** [comment]
@jimminycrickett I've pushed it to dev, you can pull in just this file. 

https://github.com/aaronweaver/django-DefectDojo/blob/3194e2e6fc6cb16c7ef6f99a41e9af80be7bb830/dojo/tools/veracode/parser.py#L97

Let me know how it goes.

**Comment by jimminycrickett** [comment]
That resolved it. Location and Line number are now showing up in a field immediately above the 'Affected Endpoints' box. Just FYI - the 'Location' title box isn't the same color as the others. Thanks for fixing this Aaron!
