### ISSUE TITLE
Support multiple SLA templates

### ISSUE THREAD

**Issue by timfoley66** [DefectDojo/django-DefectDojo#6389]
Provide a way to create and maintain multiple SLA templates.  Assign a template to a test.

Example:
    External Critical vulnerability - 7days
    Internal Critical vulnerability - 60 days
    Internal authenticated Critical vulnerability - 180 days
    Development Critical vulnerability - by next MVP (expect to create appropriate template)

**Comment by manuel-sommer** [comment]
As far as I know, this is possible now. Can be closed @mtesauro
