### ISSUE TITLE
Release problems with 2.11.0

### ISSUE THREAD

**Issue by bgoareguer** [DefectDojo/django-DefectDojo#6398]
**Bug description**
I tried to install version 2.11.0 with the Helm chart (version 1.6.33)
1- Helm cannot find version 1.6.33 of the chart (so I used version 1.6.32)
2- The DefectDojo version shown in the footer of every page indicates `v. 2.11.0-dev`

**Expected behavior**
1- Helm should be able to find version 1.6.33 of the chart
2- The DefectDojo version should be `v. 2.11.0` 

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [x] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Ubuntu 20.04
 - DefectDojo version (see footer) or commit message: 2.11.0

**Screenshots**
![image](https://user-images.githubusercontent.com/43874676/173313421-2d44d750-33d1-4e85-ac4d-a54da9eac3f3.png)

**Additional context** (optional)
The Docker image does not seem to contain the source code contained in the 2.11.0 git tag:
```bash
docker run --rm -it --entrypoint "" defectdojo/defectdojo-django:2.11.0 /bin/bash -c "cat dojo/__init__.py"


# This will make sure the app is always imported when
# Django starts so that shared_task will use this app.
from .celery import app as celery_app  # noqa

__version__ = '2.11.0-dev'
__url__ = 'https://github.com/DefectDojo/django-DefectDojo'
__docs__ = 'https://defectdojo.github.io/django-DefectDojo'

```

**Comment by dsever** [comment]
@bgoareguer  https://owasp.slack.com/archives/C2P5BA8MN/p1654643772993429 

You can fetch helm directly from the repo.

**Comment by Hashfyre** [comment]
Please publish the repo to the correct version if chart version is getting updated. Can help with the helm version release pipeline.

**Comment by Hashfyre** [comment]
@dsever right now only `1.6.32` is downloadable from helm repo, and this release is missing the following fix:
- https://github.com/DefectDojo/django-DefectDojo/pull/6149 by @KarstenSiemer 

Hence, when we are trying to connect to an external-redis (AWS Elasticache) we are hitting the said bug, as our values.yaml and the version are not matching up.

For now we are going to patch the generated YAMLs manually using `helm template` + some `jq` patch --> `kubectl apply`, but this won't last long.

**Comment by Gby56** [comment]
I don't understand what's going on with the current release, https://hub.docker.com/r/defectdojo/defectdojo-django/tags shows that latest and 2.11.0 have the same digest ?

**Comment by Maffooch** [comment]
@Hashfyre 

Your fix is on the [master branch](https://github.com/DefectDojo/django-DefectDojo/blob/master/helm/defectdojo/templates/django-deployment.yaml) and in the current release. The issue is that the current release (2.11.0) was not published as a helm chart. This was due to the bitnami issue as @dsever mentioned. The team is working through a solution here #6399

**Comment by Maffooch** [comment]
@Gby56 

Docker tags can either be static or dynamic. For example, the latest tag today points to 2.11.0 (the latest release) but last month it pointed to 2.10.0. On the next scheduled release for July, the latest tag will point to 2.12.0

If you wanted a specific version that is guaranteed not to change on you, use the 2.11.0 tag

**Comment by Gby56** [comment]
Right, I just saw that values.yaml in the chart was pointing to `latest` but got confused whether 2.11.0 was okay to use or not yet... My cluster still has the 2.10.0 (according to the hash, given that the tag says `latest`)

**Comment by dsever** [comment]
@Gby56  probably for the next release  version will be pinned

**Comment by TheocharisPetros** [comment]
@bgoareguer seems that the second issue relevant to the code base of the docker image of 2.11.0 has been resolved https://app.slack.com/client/T04T40NHX/C2P5BA8MN/thread/C2P5BA8MN-1655814088.154409 .

**Comment by italvi** [comment]
@bgoareguer did you solved the issue? I am still facing the problem that after helm repo update I can only find chart version 1.6.32

**Comment by bgoareguer** [comment]
> @bgoareguer did you solved the issue? I am still facing the problem that after helm repo update I can only find chart version 1.6.32

No, I can still only see version 1.6.32 version of the chart in the repo.

**Comment by Gby56** [comment]
Is 2.11.0 available for the helm deployment ? or are the fixes too complex so we'll wait for 2.12.0 ?

**Comment by bgoareguer** [comment]
Reading [this](https://github.com/bitnami/charts/issues/10833) issue on the Bitnami repo, it seems the chart versions we are using will not be included back in the official Bitnami chart repository (because they are more than 6 months old). So I think we should update the Bitnami repository in the chart dependencies: https://charts.bitnami.com/bitnami -> https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami. What do you think?

**Comment by StefanFl** [comment]
Helm upgrades work again with release 2.12.0, using newer versions of the Bitnami charts.
