### ISSUE TITLE
One vulnerability with multiple hosts 

### ISSUE THREAD

**Issue by adanalvarez** [DefectDojo/django-DefectDojo#641]
### Issue Type 
- [ ] Bug
- [x] Enhancement

### Description

Hello,

When uploading Qualys results, if a vulnerability exists on several hosts, the tool creates a finding for each host. We would like to have a finding and all affected hosts inside.

Do you know how we can do it?

If this is not possible now, but you can give us some tips on how to modify the code to implement this function, we will be more than happy to collaborate to create this function.

**Comment by aaronweaver** [comment]
@adanalvarez Take a look at the nessus parser:

https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/nessus/parser.py#L109

What you need to do is decide on what vulnerability you want to merge, for example nessus parser chooses: dat['severity'] + dat['title']. Then when you detect the duplicate you append an endpoint to the existing finding: find.unsaved_endpoints.append(endpoint).

https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/nessus/parser.py#L134

This will prevent a new finding from being created and just adds an endpoint to the existing finding.

Let me know if you have any more questions.

**Comment by aaronweaver** [comment]
@adanalvarez Let me know if you have any questions. Feel free to reopen if you do.
