### ISSUE TITLE
Cannot build new install

### ISSUE THREAD

**Issue by masterminerking** [DefectDojo/django-DefectDojo#6412]
When I try to run ./dc-build.sh I get error messages:

./docker/docker-compose-check.sh: line 3: docker-compose: command not found
./docker/docker-compose-check.sh: line 4: docker-compose: command not found
./docker/docker-compose-check.sh: line 5: docker-compose: command not found
Checking docker-compose version
is not supported docker-compose version, please upgrade to minimal supported version:1.28

If I do sudo docker version the Docker Engine Client is version 20.10.17 and the Docker Engine Server is 20.10.17. The Docker Compose version is v2.6.0. I am therefore way past the supported version.

The django and nginx images have also been pulled from dockerhub
https://hub.docker.com/r/defectdojo/defectdojo-django
https://hub.docker.com/r/defectdojo/defectdojo-nginx

I have tried other versions of Docker but seem to get the same issues.

Any help would be appreciated.

**Comment by dsever** [comment]
But it is reporting like docker-compose binary is not there.

**Comment by masterminerking** [comment]
Hi dsever

It says command not found. Is docker compose version not the newer version of docker-compose version? No docker-compose commands seem to work.

I basically did this to install Docker:
https://docs.docker.com/engine/install/debian/

Thanks

**Comment by dsever** [comment]
Yes, but you nees to install docker-compose as well. This instructions are installing docker only.

**Comment by masterminerking** [comment]
The instructions do say Docker Compose is installed with this command and as I said it displays Compose version is v2.6.0.
 
I have come across the solution and its on a completely different page and a different issue but it fixed the trouble I was having:
 _If the command docker-compose fails after installation, check your path. You can also create a symbolic link to /usr/bin or any other directory in your path. For example:
sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose_

I hope it can help anyone else having the same issue.

**Comment by StefanFl** [comment]
This issue seems to be fixed.
