### ISSUE TITLE
DD_SITE_URL not set by helm chart

### ISSUE THREAD

**Issue by Gby56** [DefectDojo/django-DefectDojo#6422]
**Be informative**
There was an issue when I tried to push issues to Jira, the link stayed localhost, the helm chart was broken.

**Bug description**
Simply missing an env setting

**Steps to reproduce**

**Expected behavior**

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
DDojo version 2.10.0

**Logs** 
Use `docker-compose logs` (or similar, depending on your deployment method) to get the logs and add the relevant sections here showing the error occurring (if applicable).

**Sample scan files**
If applicable, add sample scan files to help reproduce your problem.

**Screenshots**

**Additional context** (optional)

**Comment by dsever** [comment]
Merged into dev
