### ISSUE TITLE
UI on small screens: weird horizontal scrolling

### ISSUE THREAD

**Issue by AndreyMZ** [DefectDojo/django-DefectDojo#6458]
**Bug description**
See the screenshot.

**Steps to reproduce**
See the screenshot.

**Expected behavior**
1. No issue on the left.
2. No empty space on the right.
3. No horizontal scrolling.

**Environment information**
 - Operating System: ?
 - DefectDojo version: `v. 2.11.0-dev ( release mode )`

**Screenshots**
<img width="966" alt="Screenshot 2022-06-23 172439" src="https://user-images.githubusercontent.com/9609370/175324470-544372c7-4b8e-400b-822e-eecfce518183.png">

**Comment by manuel-sommer** [comment]
This was not reproducable @mtesauro with v2.31.0-dev
