### ISSUE TITLE
Finding Reporter id always equal to 1 when finding created in API 

### ISSUE THREAD

**Issue by testsecrbw** [DefectDojo/django-DefectDojo#6484]
**Slack us first!**
I did and was told to report a bug on slack

**Be informative**
I am using: v. 2.10.0 ( release mode ) 
I am creating products, engagements and findings through the API.

**Bug description**
When creating a finding I would like the reporter to correspond to the id of the pentester in defectdojo so I tried in 2 ways:

First while using the API with admin APIKEY I created a finding and sent  a reporter field with the id of the pentester (3). The reporter id for the finding ends up being 1 (admin) anyhow.

Second  while using the API with the pentester APIKEY I created a finding. The reporter id for the finding is 1 when the pentester id is 3.

**Steps to reproduce**
One can use the  /api/v2/oa3/swagger-ui/#/findings/findings_create to reproduce
One need a product and an engagement to create the finding

**Expected behavior**
I would like the "reporter" field value to be taken into account.

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose

**Environment information**
 - DefectDojo version v. 2.10.0 ( release mode )

**Comment by StefanFl** [comment]
Merged for release 2.12
