### ISSUE TITLE
Error 500 when deleting tests (v 2.9.1)

### ISSUE THREAD

**Issue by devsecopspaylouser** [DefectDojo/django-DefectDojo#6485]
Hello, please see also

    https://owasp.slack.com/archives/C2P5BA8MN/p1656088958681279

When I choose to delete a test within any of our engagements, I am met w/ "Error 500". I found this in the logs:

django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`defectdojo`.`dojo_endpoint_status`, CONSTRAINT `dojo_endpoint_status_finding_id_394d34c7_fk_dojo_finding_id` FOREIGN KEY (`finding_id`) REFERENCES `dojo_finding` (`id`))')

1. Go to Engagements
2. Choose an Engagement
3. In the Tests section, choose the kebab (row context actions) menu for the test you want to delete
4. Choose Delete, and then Delete Test at the bottom of the following page

I expected the test to be removed after I selected Delete.

We are currently running v. 2.9.1 ( release mode )

Please let me know what I may be missing here.  Thank you,  -Daniel

**Comment by StefanFl** [comment]
Hi @devsecopspaylouser, I can't reproduce that behaviour, deleting Tests works fine for me. I tried it with tests including findings with and without connections to endpoints. Please check if all migrations ran properly with your last upgrade.

**Comment by dkemper01** [comment]
Thank you for looking into this, @StefanFl. I will verify migrations today or tomorrow and post back with the result.

**Comment by devsecopspaylouser** [comment]
I was able to access the docker host and execute the following command:

```
$ docker exec <container_id> /bin/bash -c 'python manage.py migrate'
[06/Jul/2022 19:04:44] INFO [dojo.models:3753] enabling audit logging
[06/Jul/2022 19:04:44] DEBUG [dojo.forms:2083] templates: [('', '---'), ('issue-trackers/jira_full', 'jira_full'), ('issue-trackers/jira_limited', 'jira_limited')]
Operations to perform:
  Apply all migrations: admin, auditlog, auth, authtoken, contenttypes, django_celery_results, dojo, sessions, sites, social_django, tagging, watson
Running migrations:
  No migrations to apply.
```

Would anyone happen to know how to execute the migrations again?

**Comment by devsecopspaylouser** [comment]
Adding debug log info ...

Environment:


> Request Method: POST
> Request URL: http://54.146.221.129:8080/test/95/delete
> 
> Django Version: 3.2.12
> Python Version: 3.8.12
> Installed Applications:
> ('django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.sites',
>  'django.contrib.messages',
>  'django.contrib.staticfiles',
>  'polymorphic',
>  'django.contrib.admin',
>  'django.contrib.humanize',
>  'gunicorn',
>  'auditlog',
>  'dojo',
>  'watson',
>  'tagging',
>  'imagekit',
>  'multiselectfield',
>  'rest_framework',
>  'rest_framework.authtoken',
>  'dbbackup',
>  'django_celery_results',
>  'social_django',
>  'drf_yasg',
>  'drf_spectacular',
>  'tagulous')
> Installed Middleware:
> ['django.middleware.common.CommonMiddleware',
>  'dojo.middleware.DojoSytemSettingsMiddleware',
>  'django.contrib.sessions.middleware.SessionMiddleware',
>  'django.middleware.csrf.CsrfViewMiddleware',
>  'django.middleware.security.SecurityMiddleware',
>  'django.contrib.auth.middleware.AuthenticationMiddleware',
>  'django.contrib.messages.middleware.MessageMiddleware',
>  'django.middleware.clickjacking.XFrameOptionsMiddleware',
>  'dojo.middleware.LoginRequiredMiddleware',
>  'social_django.middleware.SocialAuthExceptionMiddleware',
>  'watson.middleware.SearchContextMiddleware',
>  'auditlog.middleware.AuditlogMiddleware',
>  'crum.CurrentRequestUserMiddleware',
>  'dojo.request_cache.middleware.RequestCacheMiddleware']
> 
> 
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
>     return self.cursor.execute(query, args)
>   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
>     res = self._query(query)
>   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
>     db.query(q)
>   File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
>     _mysql.connection.query(self, query)
> 
> The above exception ((1452, 'Cannot add or update a child row: a foreign key constraint fails (`defectdojo`.`dojo_endpoint_status`, CONSTRAINT `dojo_endpoint_status_finding_id_394d34c7_fk_dojo_finding_id` FOREIGN KEY (`finding_id`) REFERENCES `dojo_finding` (`id`))')) was the direct cause of the following exception:
>   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
>     response = get_response(request)
>   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/app/./dojo/authorization/authorization_decorators.py", line 30, in _wrapped
>     return func(request, *args, **kwargs)
>   File "/app/./dojo/test/views.py", line 275, in delete_test
>     test.delete()
>   File "/app/./dojo/models.py", line 1680, in delete
>     super().delete(*args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 967, in delete
>     return collector.delete()
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/deletion.py", line 404, in delete
>     signals.pre_delete.send(
>   File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 180, in send
>     return [
>   File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
>     (receiver, receiver(signal=self, sender=sender, **named))
>   File "/app/./dojo/finding/helper.py", line 320, in finding_pre_delete
>     instance.status_finding.clear()
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 715, in clear
>     self._clear(self, bulk)
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 724, in _clear
>     queryset.update(**{self.field.name: None})
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 783, in update
>     rows = query.get_compiler(self.db).execute_sql(CURSOR)
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
>     cursor = super().execute_sql(result_type)
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
>     cursor.execute(sql, params)
>   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
>     return super().execute(sql, params)
>   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
>     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
>   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
>     return executor(sql, params, many, context)
>   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
>     raise dj_exc_value.with_traceback(traceback) from exc_value
>   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
>     return self.cursor.execute(query, args)
>   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
>     res = self._query(query)
>   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
>     db.query(q)
>   File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
>     _mysql.connection.query(self, query)
> 
> Exception Type: IntegrityError at /test/95/delete
> Exception Value: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`defectdojo`.`dojo_endpoint_status`, CONSTRAINT `dojo_endpoint_status_finding_id_394d34c7_fk_dojo_finding_id` FOREIGN KEY (`finding_id`) REFERENCES `dojo_finding` (`id`))')

**Comment by StefanFl** [comment]
The line `instance.status_finding.clear()` was removed with PR #6192, which was released with 2.10.0. Please update your instance and try again.

**Comment by devsecopspaylouser** [comment]
Hi @StefanFl, 

I upgraded to 2.10.0 as you recommended. I am now experiencing a different error when attempting to delete a test:

AttributeError at /test/95/delete

'Settings' object has no attribute 'DELETE_PREVIEW'

> Environment:
> 
> 
> Request Method: GET
> Request URL: http://35.175.188.200:8080/test/95/delete
> 
> Django Version: 3.2.13
> Python Version: 3.8.12
> Installed Applications:
> ('django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.sites',
>  'django.contrib.messages',
>  'django.contrib.staticfiles',
>  'polymorphic',
>  'django.contrib.admin',
>  'django.contrib.humanize',
>  'gunicorn',
>  'auditlog',
>  'dojo',
>  'watson',
>  'tagging',
>  'imagekit',
>  'multiselectfield',
>  'rest_framework',
>  'rest_framework.authtoken',
>  'dbbackup',
>  'django_celery_results',
>  'social_django',
>  'drf_yasg',
>  'drf_spectacular',
>  'tagulous')
> Installed Middleware:
> ['django.middleware.common.CommonMiddleware',
>  'dojo.middleware.DojoSytemSettingsMiddleware',
>  'django.contrib.sessions.middleware.SessionMiddleware',
>  'django.middleware.csrf.CsrfViewMiddleware',
>  'django.middleware.security.SecurityMiddleware',
>  'django.contrib.auth.middleware.AuthenticationMiddleware',
>  'django.contrib.messages.middleware.MessageMiddleware',
>  'django.middleware.clickjacking.XFrameOptionsMiddleware',
>  'dojo.middleware.LoginRequiredMiddleware',
>  'social_django.middleware.SocialAuthExceptionMiddleware',
>  'watson.middleware.SearchContextMiddleware',
>  'auditlog.middleware.AuditlogMiddleware',
>  'crum.CurrentRequestUserMiddleware',
>  'dojo.request_cache.middleware.RequestCacheMiddleware']
> 
> 
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
>     response = get_response(request)
>   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/app/./dojo/authorization/authorization_decorators.py", line 30, in _wrapped
>     return func(request, *args, **kwargs)
>   File "/app/./dojo/test/views.py", line 297, in delete_test
>     display_preview = get_setting('DELETE_PREVIEW')
>   File "/app/./dojo/utils.py", line 1443, in get_setting
>     return getattr(settings, setting)
>   File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 83, in __getattr__
>     val = getattr(self._wrapped, name)
> 
> Exception Type: AttributeError at /test/95/delete
> Exception Value: 'Settings' object has no attribute 'DELETE_PREVIEW'
>

**Comment by StefanFl** [comment]
This attribute has been introduced with release 2.10.0 in the file `dojo/settings/settings.dist.py`. Do you have your own set of settings?

**Comment by devsecopspaylouser** [comment]
Yes, thank you that was my mistake. I have the proper settings now and all is well!! Thank you again for your help here.
