### ISSUE TITLE
sonarqube integration

### ISSUE THREAD

**Issue by mydailypuff** [DefectDojo/django-DefectDojo#6490]
I am facing the below issue while integrating defectdojo with sonarqube
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/83843152/176912895-0cf4fd32-33ea-4d82-aab3-e240308c7187.png">

After hitting submit, I am getting the below error in ui
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/83843152/176913138-48b9d42a-4ff9-4caa-bd73-5eadbf9e9e3f.png">

I have added the project in product and added defectdojo webhook in sonarqube project as well

**Comment by StefanFl** [comment]
Please have a look at https://defectdojo.github.io/django-DefectDojo/integrations/parsers/#sonarqube-api-import, I think you have to set the URL differently.
