### ISSUE TITLE
Edit Engagement Fails to Save

### ISSUE THREAD

**Issue by jpbowie** [DefectDojo/django-DefectDojo#650]
Please use the following template when submitting issues:

### Issue Type 
- [X] Bug
- [ ] Enhancement

### Description
When an engagement is created with the API and a later attempt is made to edit details about the engagement using the web interface, the edit engagement screen simply refreshes and the changes are not saved.  Strangely, I don't think the same issue occurs if the engagement is created with the web interface.  Note, I'm not currently using Jira integration.

### Operating System 
Please include the version number (ex: Ubuntu 16.04)
Windows 2012 R2 Data Center

### Install
I performed a manual installation on Windows based on the setup.bash script

- [ ] setup.bash
- [ ] docker

### DefectDojo Version
1.3.0

### Steps to Reproduce
1.  Create an engagement using the API (Without a name)
2.  View the engagement in the Defect Dojo web interface
3.  From the menu, select Edit Engagement
4.  Enter a name for the engagement
5.  Click Done

### Screenshots (optional)
When troubleshooting the issue, I found that the condition for the form to save wasn't being met (because jform is None) and there isn't an else block to handle alternatives.   

![image](https://user-images.githubusercontent.com/23224163/42854988-77f1c276-8a0c-11e8-8012-7ccd45540273.png)
 

### Possible Patch
I added some logic above line 142 similar to the code below to resolve my issue.  Ideally, this would be refactored to remove the duplication, but I just needed a quick patch for now.

`        elif form.is_valid() and jform is None:
            form.save()
            tags = request.POST.getlist('tags')
            t = ", ".join(tags)
            eng.tags = t
            messages.add_message(request,
                                 messages.SUCCESS,
                                 'Engagement updated successfully.',
                                 extra_tags='alert-success')
            if '_Add Tests' in request.POST:
                return HttpResponseRedirect(reverse('add_tests', args=(eng.id,)))
            else:
            return HttpResponseRedirect(reverse('view_engagement', args=(eng.id,)))
        else:
            messages.add_message(request,
                                 messages.ERROR,
                                 'Something went very wrong!')`

**Comment by aaronweaver** [comment]
This should be fixed in 1.5
