### ISSUE TITLE
talisman integration with defectdojo

### ISSUE THREAD

**Issue by mydailypuff** [DefectDojo/django-DefectDojo#6512]
Hi Team,
We are trying to integrate talisman findings report with defectdojo. Is there any integration supported by defectdojo? or talisman is generating json report; Is there any option to upload this report ?

If so, please share the link.

**Comment by damiencarol** [comment]
@mydailypuff best solution would be that the tool support one standard format like SARIF.
Took a look at the repo of talisman and it doesn't seems that you can generate something else than HTML.
opened an issue for that https://github.com/thoughtworks/talisman/issues/384

**Comment by iamnihal** [comment]
@damiencarol - Can we close this issue?

**Comment by manuel-sommer** [comment]
@mtesauro can you close this issue please?
