### ISSUE TITLE
Microsoft Teams Notification - How to change URL Notification ?

### ISSUE THREAD

**Issue by rjhaikal** [DefectDojo/django-DefectDojo#6547]
Hello,

I created a Teams Webhook to send notification.

It's running now. So when i created a new test, i will received the notification

For Example :
![tanya](https://user-images.githubusercontent.com/72386335/178401379-f276b87b-aea9-4feb-975d-6312dafdecae.png)

But when i click on the `View Engangement`, it will take me to localhost:8080
![tanya2](https://user-images.githubusercontent.com/72386335/178401701-0abea64a-923f-4f19-a1db-a57558106433.png)

how can i change that to my domain?
Your support will help me a lot

**Deployment method** *(select with an `X`)*
- [ X ] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Ubuntu 18.04
 - DefectDojo version : v2.11.0

**Comment by StefanFl** [comment]
I think you have to set the parameter DD_SITE_URL to the URL of your DefectDojo installation.

**Comment by AndreVirtimo** [comment]
I have the same problem. Also links in Jira tickets are now pointing to localhost. The Jira links where working until my update from 2.10.0 to 2.14.3. An update to version 2.15.1 didn't changed this issue.

I have DD_SITE_URL in an env file and set this via the parameter "--env-file". I also use docker-compose.
