### ISSUE TITLE
Auto_create_context in reimport scan changes the engagement deduplication

### ISSUE THREAD

**Issue by Gby56** [DefectDojo/django-DefectDojo#6558]
When trying to create engagements dynamically with different deduplication modes, I realized that the setting would be switched back to "disabled" for the deduplicate only in engagement, which is not ideal

**Expected behavior**
Either let the user input that param in the reimport-scan API or don't change it

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - DefectDojo version 2.12.0

**Logs** 
Use `docker-compose logs` (or similar, depending on your deployment method) to get the logs and add the relevant sections here showing the error occurring (if applicable).

**Sample scan files**
If applicable, add sample scan files to help reproduce your problem.

**Screenshots**

**Additional context** (optional)

**Comment by manuel-sommer** [comment]
This can be closed @mtesauro
