### ISSUE TITLE
Bugcrowd parser breaks on submission titles that contain special characters

### ISSUE THREAD

**Issue by Gby56** [DefectDojo/django-DefectDojo#6580]
https://github.com/DefectDojo/django-DefectDojo/blob/fbd6cc78e6880ae7312193a31c6a4a0f1eb62420/dojo/tools/bugcrowd/parser.py#L55

I had an occurrence today when trying to import a CSV that had a title containing : `xxxxxx http://xxx.domain.example.com`

The defectdojo I get is:
`An exception error occurred during the report import:invalid scheme: 'xxxxxx http'. Only alphanumeric, "+", "-", and "." allowed. Did you meant to call URL.from_text()?`

I think `:` is not allowed and breaks a lot of things

**Comment by manuel-sommer** [comment]
The PR was merged, could you close this @mtesauro ?
