### ISSUE TITLE
Reassign an engagement to another product

### ISSUE THREAD

**Issue by gzot** [DefectDojo/django-DefectDojo#6588]
Hello,

Using the web interface, I can edit an engagement (https://demo.defectdojo.org/engagement/[ID]/edit).
Last option is to change the associated product but when I submit the form ("Done" button), the new product is not saved.

Can we move an engagement to another product using the web interface ?

Note : It is possible to do the same thing using the PATCH verb on the following API endpoint : https://demo.defectdojo.org/api/v2/engagements/[ID]/

**Comment by X0x1RG9f** [comment]
@gzot, this should be fixing the issue: https://github.com/DefectDojo/django-DefectDojo/pull/6617

**Comment by manuel-sommer** [comment]
PR was merged. can we close this @mtesauro ?
