### ISSUE TITLE
Specific filter not exposed on ApiFindingFilter but on FindingFilter (test__engagement__product__prod_type)

### ISSUE THREAD

**Issue by fw-work** [DefectDojo/django-DefectDojo#6589]
The field `test__engagement__product__prod_type` is exposed as a filter on the `FindingFilter` class:
https://github.com/DefectDojo/django-DefectDojo/blob/fbd6cc78e6880ae7312193a31c6a4a0f1eb62420/dojo/filters.py#L1165-L1167

That's great, because it allows people to filter findings by a product type in the UI, via `/finding/open?test__engagement__product__prod_type=<id>`.

Unfortunately, this field is not exposed as a filter on `ApiFindingFilter` though.
Only `test__engagement__product` is exposed, see:
https://github.com/DefectDojo/django-DefectDojo/blob/fbd6cc78e6880ae7312193a31c6a4a0f1eb62420/dojo/filters.py#L1072

**Expected behaviour**
I would expect the behaviour between the UI filters and API filters to be similar, in the sense that the `test__engagement__product__prod_type` field is also exposed on the API, and not just in the UI.

**Deployment method**
- [x] Docker Compose
- [x] Kubernetes
- [x] GoDojo

**Environment information**
 - Operating System: MacOS 12.04
 - DefectDojo version: 2.12.0

**Comment by StefanFl** [comment]
merged for release 2.13.0
