### ISSUE TITLE
Create an API import for Bugcrowd

### ISSUE THREAD

**Issue by Gby56** [DefectDojo/django-DefectDojo#6620]
**Scanner Name**
Bugcrowd, for bug bounty and vulnerability disclosure programs.
The current import is for a CSV that can only be downloaded in the UI, not really automatable.

**Sample File**
See the api docs https://docs.bugcrowd.com/api/2021-10-28/#tag/submission_resource/operation/listSubmissions

**Comment by Gby56** [comment]
I'm working on this

**Comment by manuel-sommer** [comment]
The PR was merged, could you close this @mtesauro ?
