### ISSUE TITLE
NoReverseMatch at test...

### ISSUE THREAD

**Issue by MaroonBeret** [DefectDojo/django-DefectDojo#664]
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description
I've imported a Retire report with several findings via the API. After marking and saving one of them as a false positive, the test of the finding became unreachable. It shows me the stacktrace in the screenshots section. 
Any help would be greatly appreciated!
If there is any more info necessary I'll be happy to supply.

### Operating System 
Please include the version number (ex: Ubuntu 16.04)
Ubuntu 16.04.4 LTS

### Install

- [ ] setup.bash
- [x] docker

### DefectDojo Version
1.3.0

### Steps to Reproduce
See description

### Sample Scan File (if applicable)
Cannot retrieve the specific scan report because of this problem.

### Screenshots
<img width="989" alt="screen shot 2018-07-26 at 10 44 42" src="https://user-images.githubusercontent.com/10127839/43253429-3c66a19e-90c5-11e8-84a3-d96aa95adc0b.png">

### Console Logs
Will retrieve if necessary.

**Comment by aaronweaver** [comment]
Can you upgrade? I'd recommend that.

**Comment by MaroonBeret** [comment]
@aaronweaver Hi Aaron. I can't find a way to upgrade dojo in a Docker setup. Running the latest image from _appsecpipeline/django-defectdojo:latest_ seems to run V1.3.0.

**Comment by aaronweaver** [comment]
Possibly have something cached? Pull down the explicit version. appsecpipeline/django-defectdojo:1.5.2

https://hub.docker.com/r/appsecpipeline/django-defectdojo/tags/
