### ISSUE TITLE
Issue with Critical Product Metric stats

### ISSUE THREAD

**Issue by w3synack** [DefectDojo/django-DefectDojo#665]
Please use the following template when submitting issues:

### Issue Type 
- [ ] Bug

### Description
Wen we add critical tag and key feature, the product is visible in Critical Product Metric menu, but alway shoing 5...in fact no one as 5, someone as 3 or other has more...

### Operating System 
Please include the version number (ex: Ubuntu 16.04)
Ubuntu 18.04
### Install

- [ ] setup.bash

### DefectDojo Version
1.51

### Steps to Reproduce
See pics
### Screenshots (optional)
https://imgur.com/a/pxUbjMl

The first product:
https://imgur.com/a/bU5Z6Y1

**Comment by devGregA** [comment]
Hi @w3synack the number is a calculation based on a health formula. This probably should be reconciled with the new grading system, but the code specific to that view is here: https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/models.py#L297 if you want to alter the formula.

**Comment by w3synack** [comment]
Ok thanks for information, I'm new user with this project... ;)
