### ISSUE TITLE
Issue for regulation - didn't show in menu after upgrade

### ISSUE THREAD

**Issue by w3synack** [DefectDojo/django-DefectDojo#666]
Please use the following template when submitting issues:

### Issue Type 
- [ ] Bug

### Description
After upding to 1.51, Regulation , like GDRP or PCI DSS as not showing for existing product, or new one.

### Operating System 
Please include the version number (ex: Ubuntu 16.04)
Ubuntu 18.04
### Install

- [ ] setup.bash

### DefectDojo Version
1.51

### Steps to Reproduce
See pics
### Screenshots (optional)
https://imgur.com/a/hCjfdi7

**Comment by devGregA** [comment]
@w3synack which version did you upgrade from?

**Comment by w3synack** [comment]
From 1.31

**Comment by aaronweaver** [comment]
Hi @w3synack, I'll update the docs but here is how you can load that data:

./manage.py loaddata dojo/fixtures/regulation.json

Also you can view the regulation data in django admin - http://localhost:8000/admin

**Comment by w3synack** [comment]
Ok  good!

Thanks for your help!
