### ISSUE TITLE
Configuration Docs Vagueness

### ISSUE THREAD

**Issue by bitdeft** [DefectDojo/django-DefectDojo#6680]
https://defectdojo.github.io/django-DefectDojo/getting_started/configuration/

It has been a bit hard to decipher what exactly needs to be done to configure the system. Those who aren't familiar with docker-compose, docker files, django, and python...etc will have a hard time configuring the service. It is unclear where certain variables need to be placed. 

For instance, this paragraph:

> When you deploy DefectDojo via Docker Compose, you can set environment variables in [docker-compose.yml](https://github.com/DefectDojo/django-DefectDojo/blob/master/docker-compose.yml). Be aware you have to set the variables for three services: uwsgi, celerybeat and celeryworker.

It should specific that you will want to edit `ENVIRONMENT` section of the yml file (even though it may seem obvious). Also, is it asking to add the environment variable to three of the containers' environment sections, or just uwsgi? Also, it is hard to tell if it is implying that if you set _any_ customizations in one of the containers, you now need to create custom settings for all of them as a result of deviating from "default"?

Without pouring over code it's hard to tell what is actually using X variable.

 On top of that, what about the overrides? When is it appropriate to use them, why would you make a symbolic link..etc. 

It would be great to update this page for System Admins or IT Teams who are implementing DefectDojo, but who are not developers themselves.

**Comment by manuel-sommer** [comment]
Hi @bitdeft ,
Do you think you can make a PR and contribute? I guess you will get help with reviews. This also helps you to learn and the maintainers understand where the docs lack information?

**Comment by mtesauro** [comment]
@bitdeft @fuzzah 
Though a bit dated (you'd have to update the image references in the docker-compose.yml for example), I think this lays out a rather straight forward way to deploy DefectDojo on a Linux system. No `docker build` required.

It's RHEL specific but most of those commands will also work on the .deb side of the house or it's not hard to search for what the equivalent of `yum install` is for Debian systems.

It's certainly an 90% solution including a suggested directory structure, ability to modify things like the nginx.conf without building a new container, etc.
