### ISSUE TITLE
Internal server error 500 after updating to 2.13.1

### ISSUE THREAD

**Issue by ruedaja11** [DefectDojo/django-DefectDojo#6689]
After upgrading to version 2.13.1, I experienced an error 500. All containers are running fine and have initialised correctly. 

Here you can find the docker-compose logs of uwsgi_1

uwsgi_1         | [11/Aug/2022 11:18:30] ERROR [django.request:224] Internal Server Error: /login
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
uwsgi_1         |     response = response.render()
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 105, in render
uwsgi_1         |     self.content = self.rendered_content
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
uwsgi_1         |     return template.render(context, self._request)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
uwsgi_1         |     return self.template.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 168, in render
uwsgi_1         |     with context.bind_template(self):
uwsgi_1         |   File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
uwsgi_1         |     return next(self.gen)
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/template/context.py", line 244, in bind_template
uwsgi_1         |     updates.update(processor(self.request))
uwsgi_1         |   File "/app/./dojo/context_processors.py", line 15, in globalize_vars
uwsgi_1         |     'AZUREAD_TENANT_OAUTH2_GET_GROUPS': settings.AZUREAD_TENANT_OAUTH2_GET_GROUPS,
uwsgi_1         |   File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 83, in __getattr__
uwsgi_1         |     val = getattr(self._wrapped, name)
uwsgi_1         | AttributeError: 'Settings' object has no attribute 'AZUREAD_TENANT_OAUTH2_GET_GROUPS'
uwsgi_1         | [pid: 1|app: -|req: -/-] 172.31.35.16 (admin) {44 vars in 1255 bytes} [Thu Aug 11 11:18:30 2022] GET /login?next=/ => generated 145 bytes in 36 msecs (HTTP/1.1 500) 7 headers in 362 bytes (1 switches on core 1)
uwsgi_1         | [11/Aug/2022 11:18:30] ERROR [django.request:224] Internal Server Error: /favicon.ico
uwsgi_1         | [pid: 31|app: -|req: -/-] 172.31.35.16 (admin) {42 vars in 1189 bytes} [Thu Aug 11 11:18:30 2022] GET /favicon.ico => generated 145 bytes in 36 msecs (HTTP/1.1 500) 6 headers in 184 bytes (1 switches on core 0)

docker ps -a exit command

![image](https://user-images.githubusercontent.com/99332552/184123991-027c9eba-6e74-481d-b658-14e576ef3d8e.png)

**Comment by manuel-sommer** [comment]
I guess this issue is user specific, not a general DefectDojo problem. Also, it is quite old. Thus, I would close it @mtesauro . 
If you still face this issue, ask in the slack channel @ruedaja11
