### ISSUE TITLE
KeyError at /api/v1/doc/schema/engagements

### ISSUE THREAD

**Issue by jpbowie** [DefectDojo/django-DefectDojo#669]
Please use the following template when submitting issues:

### Issue Type 
- [X ] Bug
- [ ] Enhancement

### Description
Using the API v1 documentation for engagements results in a KeyError

### Operating System 
Please include the version number (ex: Ubuntu 16.04)
OSX 10.12.6 and Windows Server 2016 Data Center

### Install

- [ X] setup.bash
- [ ] docker

### DefectDojo Version
1.5.1

### Steps to Reproduce
1. From the user icon menu, choose API v1 Docs
2. Click raw on engagements

### Screenshots (optional)
![image](https://user-images.githubusercontent.com/23224163/43352879-0e52fe8a-91f9-11e8-9634-591a72741bf1.png)

### Possible fix
In the dojo/api.py file in the EngagementResource class line 506 has a reference to tools_configuration in the filtering variable, but there doesn't appear to be a corresponding tools_configuration field for the engagement.  I found that commenting this line out resolves the error.

![screen shot 2018-07-28 at 12 00 14 am](https://user-images.githubusercontent.com/23224163/43352916-d92661ba-91f9-11e8-8327-4d1ac22d2886.png)

**Comment by aaronweaver** [comment]
Fixed in 1.5.2
