### ISSUE TITLE
Error Retrieving Engagements with API v1

### ISSUE THREAD

**Issue by jpbowie** [DefectDojo/django-DefectDojo#670]
Please use the following template when submitting issues:

### Issue Type 
- [ X] Bug
- [ ] Enhancement

### Description
When attempting to retrieve engagements using v1 of the API an error is returned regarding a null value for the orchestration_engine.

### Operating System 
Please include the version number (ex: Ubuntu 16.04)
OSX 10.12.6, Windows 2016 Data Center

### Install

- [X ] setup.bash
- [ ] docker

### DefectDojo Version
1.5.1

### Steps to Reproduce
1. Navigate to the API V1 Docs page
2. Click Engagements
3. Click Try it out!

### Screenshots (optional)
![screen shot 2018-07-28 at 12 11 51 am](https://user-images.githubusercontent.com/23224163/43352977-f08190f4-91fa-11e8-9d95-5d3ac2071190.png)

### Possible Fix
In the dojo/api.py file in the EngagementResource class the source_code_management_server, build_server, and orchestration_engine all have null=False.  Data upgraded from previous versions of Defect Dojo may not have values for these so they could be null.  Changing the null=False to null=True appears to resolve the problem.

![screen shot 2018-07-28 at 12 13 23 am](https://user-images.githubusercontent.com/23224163/43353023-c8a6f7ee-91fb-11e8-8d71-e1d135cc9a5a.png)

**Comment by aaronweaver** [comment]
@jpbowie Thanks for the great report write ups. Just pushed a fix that should address the issue in .1.5.2.
