### ISSUE TITLE
[Helm] Initializer pod remains and becomes OutOfSync in Argo CD

### ISSUE THREAD

**Issue by ryok-0319** [DefectDojo/django-DefectDojo#6727]
Hi.

I'm using DefectDojo Helm chart and deploy it via Argo CD

Whenever it’s synchronized on Argo CD, initializer pod starts up
The pod remains after the job completion, so when it gets synchronized again, it generates another job pod and that makes the old job pod `OutOfSync`

I tried adding [Argo CD resource hook annotations](https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/), but the chart doesn’t allow me to change `metadata.annotations` of the initializer job
(Although `spec.template. metadata.annotations` are customizable)

There are a few solutions I can think of
- Add Helm chart hooks to the job
- Enable to customize `metadata.annotations` of the job

Thanks in advance!

**Comment by lme-nca** [comment]
Hi @ryok-0319 I have a the same problem with our deployment, can you see if my change would fix it ?

**Comment by ryok-0319** [comment]
Thank you for your PR!
I think something like that would work, but I'm wondering if it's ok to add something like this

```
"helm.sh/hook": post-install,post-upgrade
```

ref: https://helm.sh/docs/topics/charts_hooks/#the-available-hooks

**Comment by lme-nca** [comment]
And would we want to add this as well:

"helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
?

Or would we leave the default “before-hook-creation” behavior and add the “optional” argoCD hooks for those that use it.

From: ryok-0319 ***@***.***>
Date: Wednesday, 17 August 2022 at 10:32
To: DefectDojo/django-DefectDojo ***@***.***>
Cc: Lars Meijers ***@***.***>, Comment ***@***.***>
Subject: Re: [DefectDojo/django-DefectDojo] [Helm] Initializer pod remains and becomes OutOfSync in Argo CD (Issue #6727)

Thank you for your PR!
I think something like that would work, but I'm wondering if it's ok to add something like this

"helm.sh/hook": post-install,post-upgrade

ref: https://helm.sh/docs/topics/charts_hooks/#the-available-hooks

**Comment by ryok-0319** [comment]
Thank you!
Having `jobAnnotations` should be enough, let me close this issue
