### ISSUE TITLE
SonarCloud Integration with DefectDojo

### ISSUE THREAD

**Issue by yasreebsaad** [DefectDojo/django-DefectDojo#6728]
Hi There,

I was looking for documentation to integrate SonarCloud with DefectDojo. I see we have something for SonarQueb but not for SonarCloud.

https://defectdojo.github.io/django-DefectDojo/integrations/parsers

SonarCloud is not supported as of now?

**Comment by L3m0nb4tt3ry** [comment]
SonarCloud is essentially a SaaS version of SonarQube with some additional features, the `sonarqube_api` integration works well with SonarCloud as well, needs a bit of tweaking though.

**Comment by moxli** [comment]
@L3m0nb4tt3ry Did you try using it with SonarCloud?

**Comment by manuel-sommer** [comment]
Yeah, it works with sonarcloud, I have used it as well. 

@mtesauro could you close this ticket?
