### ISSUE TITLE
Aqua Integration with DefectDojo

### ISSUE THREAD

**Issue by yasreebsaad** [DefectDojo/django-DefectDojo#6729]
Hi Team,

I was looking for a documentation for Aqua Integration with DefectDojo. I see integration is possible in below article, but I do not find integration steps anywhere. Can someone help please?

https://defectdojo.github.io/django-DefectDojo/integrations/parsers

**Comment by tonnyhideyori** [comment]
you can use API

**Comment by manuel-sommer** [comment]
@mtesauro could you close this ticket?
