### ISSUE TITLE
API for generating a report

### ISSUE THREAD

**Issue by dploeger** [DefectDojo/django-DefectDojo#673]
Please use the following template when submitting issues:

### Issue Type 
- [ ] Bug
- [X] Enhancement

### Description

Perhaps this is a DOCS issue, but I didn't find an API endpoint for triggering the creation of a report or fetching a report.

I would like to notify project managers with the current project report after each new engagement. Would this be possible?

**Comment by aaronweaver** [comment]
Hi @dploeger, at the moment we don't have that in the API. Are you looking to generate a PDF report, an HTML report or both?

**Comment by dploeger** [comment]
@aaronweaver I'm mostly thinking about a PDF report. I guess, that would be the user friendliest report to mail.
