### ISSUE TITLE
support for yaml in generic parser

### ISSUE THREAD

**Issue by jozseftiborcz** [DefectDojo/django-DefectDojo#6749]
Background:  we are planning to import manual penetration testing results to defectdojo as well. We would standardize on a simple format to describe findings. I found the generic parser is the closest to what we could use. However, that parser currently support only csv and json formats. 

Proposal: Add yaml format to generic parser as it is more natural and easy to edit by hand.

**Comment by italvi** [comment]
You can do this adjustment: https://defectdojo.github.io/django-DefectDojo/contributing/how-to-write-a-parser/
Take a look at dojo/tools/generic/parser.py
CVS and JSON are already supported, so adding YAML should not be that hard.

**Comment by jozseftiborcz** [comment]
Ok, I'll extend.

**Comment by italvi** [comment]
Please take a look at https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/CONTRIBUTING.md where it is also documented and what to consider when making a PR

**Comment by manuel-sommer** [comment]
@jozseftiborcz, is this still an open topic or can you close this issue?

**Comment by mtesauro** [comment]
@manuel-sommer I think this is old enough that we can close - they are welcome re-open or create a new issue if there's something left to cover.
