### ISSUE TITLE
Add "Found By" to the filters of the Findings page

### ISSUE THREAD

**Issue by emresaglam-dremio** [DefectDojo/django-DefectDojo#6758]
**Is your feature request related to a problem? Please describe**
When I'm reviewing findings it would be great to be able to filter by the source of the scan that the finding is coming from. 

**Describe the solution you'd like**
Add "Found by" filter in the main filter for the Findings page. 

**Describe alternatives you've considered**
Alternative is to go per engagement. But it is way more clicks and it doesn't contain a holistic view.

**Additional context**
None.

**Comment by Elwood-Blues** [comment]
@emresaglam-dremio if you're trying to filter by the originating tool type that exists in already with the 'Test Type' dropdown box

**Comment by emresaglam-dremio** [comment]
I think name inconsistencies between "Found By" and "Test Type" threw me off. This is exactly what I was looking for. Thank you @PyterBd. I'll close this ticket.
