### ISSUE TITLE
Docker: Backup solutions

### ISSUE THREAD

**Issue by dploeger** [DefectDojo/django-DefectDojo#676]
Please use the following template when submitting issues:

### Issue Type 
- [ ] Bug
- [X] Enhancement

### Description

When users run DefectDojo using Docker, they need some way of backing up their database. Currently, the DefectDojo image starts a database of its own, but also prepulates it in the build phase. That way, bind-mounting /var/lib/mysql to the host, which is the usual way of persisting important container storage, will crash the container (because of missing databases).

My idea would be:

* Make the used database settings configurable through environment variables and default to SQLite (resulting in very few dependencies)
* Move the default population of the database to the entrypoint script

That way, we could use the defaults in a dev environment and configure a, say, MySQL database connection in a second container or in a hosted environment for prod.

Another possibility would be to define and document a default workflow for backing up and restoring the DefectDojo data.

**Comment by aaronweaver** [comment]
The original intent was only a dev/demo version of docker. Some in the community have done what you have suggested, here: https://github.com/kulinacs/django-DefectDojo/tree/docker and https://github.com/abelmokadem/docker-defect-dojo. Always happy to accept a pull request.

**Comment by dploeger** [comment]
@aaronweaver Great. I will check kulinacs fork for that. @kulinacs, if you need help with that, give me a hint.
