### ISSUE TITLE
Failed during build 'nginx' service

### ISSUE THREAD

**Issue by wssnetwork** [DefectDojo/django-DefectDojo#6763]
During following step in https://github.com/DefectDojo/django-DefectDojo/tree/master#quick-start, I got stuck at run the dc-build.sh script. It happen few times during building the nginx service as step below:

![image](https://user-images.githubusercontent.com/6211900/187025427-0ef2f49b-56dd-42db-8824-5e0d7379525c.png)

**Deployment method** *(select with an `X`)*
- [ X ] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Ubuntu 22.04.1 LTS
 - DefectDojo version (see footer) or commit message: [2022-08-19 09:37:27 -0500] d75069724: Correct branch checking for workflow launching [ (HEAD -> master, origin/master, origin/HEAD)]
 - Virtual Box Version 6.1.36 r152435 (Qt5.6.2) - enable 2 network adapters NAT and Host-only

**Fix works for me**
- Add code as image below (line no. 81 and 82) in ./Dockerfile.nginx

![image](https://user-images.githubusercontent.com/6211900/187025715-2087d79e-42e9-441c-ba4e-951a9f262c15.png)

Hope this helps

**Comment by manuel-sommer** [comment]
Can you generate a PR for this improvement, if this is still needed @wssnetwork ?

**Comment by manuel-sommer** [comment]
@Maffooch and @mtesauro do you think we need to implement this? If yes, I can make a PR, if not, please close this issue.

**Comment by mtesauro** [comment]
FWIW, I'm not seeing these errors and actually built on Ubuntu 22.04 yesterday - I'm a Linux user so only do dev work in Linux.
Yesterday's build was in a VM but my day to day work is in a Debian-based distro.

All that to say, I don't think this is an issue anymore. At least one I'm not experiencing  with that same version of Linux this week.

I'm going to go ahead and close this as stale.
