### ISSUE TITLE
Accepted Risk from Netsparker is Still showing Active and not Inactive

### ISSUE THREAD

**Issue by tonnyhideyori** [DefectDojo/django-DefectDojo#6776]
**Slack us first!**
I have already Done

**Be informative**

**Bug description**
Netsparker reports with risk acceptance still remains Active though it is marked as accepted risk.
<img width="1169" alt="Screenshot 2022-08-31 at 13 38 44" src="https://user-images.githubusercontent.com/18649939/187694911-4b74a0fe-a2c0-427b-898a-49daf2ac67cf.png">

**Steps to reproduce**
1. Upload a netsparker report json format or receive report direct from netsparker Web-app
2. Check the findings. i.e Accepted risk, still active

**Expected behavior**
The Accepted Risk  should be Inactivee

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - DefectDojo version: v. 2.13.1 ( release mode )

**Comment by coheigea** [comment]
This can be closed
