### ISSUE TITLE
Integration with Kube-hunter

### ISSUE THREAD

**Issue by alexr3** [DefectDojo/django-DefectDojo#6778]
Hi!

Unable to get report from kube-hunter. There is no such Test Type in the Defect Dojo.
Tried to use other Test Types, but no reports come in.

Is it possible to integrate with a kube-hunter or use another Test Type?

**Comment by alexr3** [comment]
Is it possible to add Test Type "kube-hunter" to DefectDojo?

**Comment by italvi** [comment]
Hi, please see https://defectdojo.github.io/django-DefectDojo/integrations/parsers/. There you can find the supported scan-types. It is possible to add your own parser, please refer to https://defectdojo.github.io/django-DefectDojo/contributing/how-to-write-a-parser/ and if you do so please see https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/CONTRIBUTING.md

**Comment by manuel-sommer** [comment]
@alexr3 Do you have an example output file from kube-hunter which you can share? You can anonymize the example output file before uploading, to rewrite real data in it. The stucture of the example output file has to stay as it is.

**Comment by manuel-sommer** [comment]
@mtesauro kubehunter is already supported https://defectdojo.github.io/django-DefectDojo/integrations/parsers/file/kubehunter/
