### ISSUE TITLE
[Helm] Mistake in the "upgrading" documentation regarding the postgresql breaking change

### ISSUE THREAD

**Issue by maximemf** [DefectDojo/django-DefectDojo#6793]
Hello,

I wanted to upgrade DefectDojo from the version 2.5.0 to 2.12.0 through the Helm chart, but I faced an issue:

```
Failed to upgrade helm release: cannot patch "defectdojo-postgresql" with kind StatefulSet: StatefulSet.apps "defectdojo-postgresql" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy' and 'minReadySeconds' are forbidden
```

The [upgrading documentation](https://defectdojo.github.io/django-DefectDojo/getting_started/upgrading) mentions this breaking change about the postgresql dependency, but in the 2.13 section, so I thought I wouldn't have to worry when upgrading to the 2.12.

But after checking, it seems that this breaking change was really introduced in the version 2.12 and not 2.13 as it is currently specified in the documentation.

It"s ok for me now, but it would be great to fix this for other users 🙂

**Comment by dsever** [comment]
Looks like you are right, is would address upgrading to 2.12 and above (so 2.13 should be included there).

**Comment by manuel-sommer** [comment]
This can be closed @mtesauro. It would be nice if you can add in your workflow to fix linked issues in PRs as soon as they get merged.
