### ISSUE TITLE
Deployment Error in Docker setup 

### ISSUE THREAD

**Issue by suru71** [DefectDojo/django-DefectDojo#6808]
**Problem description**
Please help in resolving the issue while Running "./dc-up-d.sh mysql-redis" -- The setup stops with below error -

#0 15.01 Setting up gnupg (2.2.27-2+deb11u2) ...
#0 15.04 Processing triggers for libc-bin (2.31-13+deb11u3) ...
#0 15.27 Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
#0 15.28 curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to deb.nodesource.com:443
#0 15.38 gpg: no valid OpenPGP data found.
------
failed to solve: executor failed running [/bin/sh -c apt-get -y update &&   apt-get -y install --no-install-recommends apt-transport-https ca-certificates curl wget gnupg &&   curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add --no-tty - &&   echo 'deb https://deb.nodesource.com/node_14.x bullseye main' > /etc/apt/sources.list.d/nodesource.list &&   echo 'deb-src https://deb.nodesource.com/node_14.x bullseye main' >> /etc/apt/sources.list.d/nodesource.list &&   apt-get update -y -o Dir::Etc::sourcelist="sources.list.d/nodesource.list"   -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0" &&   curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - &&   wget https://github.com/yarnpkg/yarn/releases/download/v1.22.10/yarn_1.22.10_all.deb &&   dpkg -i yarn_1.22.10_all.deb &&   echo "$(yarn --version)" &&   apt-get -y install --no-install-recommends nodejs &&   echo "$(node --version)" &&   apt-get clean &&   rm yarn_1.22.10_all.deb &&   rm -rf /var/lib/apt/lists &&   true]: exit code: 2

**Deployment method** 
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: [CentOS 7]
 - DefectDojo version - DefectDojo/release/2.14.0

**Screenshots**
![image](https://user-images.githubusercontent.com/103187866/188830089-fdb9f796-8723-4854-a806-ba59f1ef7a09.png)

**Comment by manuel-sommer** [comment]
A lot has changed since 2.14.0. Could you try again with the current version and otherwise ask in the slack channel for help? You can close this @mtesauro
