### ISSUE TITLE
Adding a "component" / "service" data structure below products

### ISSUE THREAD

**Issue by fhoeborn** [DefectDojo/django-DefectDojo#6810]
**Is your feature request related to a problem? Please describe**
We have Products with multiple components / services. Each component / service will be built into its own docker container image. We are scanning our docker container images with a vulnerability scanner.
Per container we create an engagement for the scan and add tests per done scan. We use the “close old findings” feature to keep track, what is still an active vulnerability and what not.

As a lot of vulnerability findings are coming from common issues in the base image, so for multiple components / services we will see similar vulnerabilities. If we would deduplicate on product level, we would run into the problem that those similar vulnerabilities across components / services get deduplicated. And when they get solved in that one container image, it gets closed off, even though it might not be solved in the other docker images.

Now to solve that problem we could create one Product per component / service, but that would blow up our product count pretty much.
With our current solution to bundle those components / services into an engagement we are misusing that engagement data type a bit and it’s not blending into the metrics.

**Describe the solution you'd like**
An idea to solve that could be to create a structure below the product called something like “component”. It would be good to be able to deduplicate inside the "component"

**Describe alternatives you've considered**
We also thought about using "product type" as the full bundle of all services inside a "product" and then make a "product" for each service.
From our understanding the “product type” is more suited for something like a “business unit” that might span multiple products (e.g. you have a business unit doing "Tax software" and one doing "accounting software - I totally made those examples up).

**Comment by jaskaransinghdr6j** [comment]
+1, we face the same issue and currently have to flatten our application/service hierarchy for this and use Custom Fields and tags to point them to actual repositories. If implemented, this would be massively helpful.

**Comment by StefanFl** [comment]
Have you tried the `service` field when importing the findings? It should do what you need, by adding an additional layer to deduplication. Findings in a product are not deduplicated, when they belong to different services.

**Comment by fhoeborn-cb** [comment]
I tried out the `service` field in a test setup.
My test setup was the following:
Two identical scans uploaded to different engagements (deduplication set to product level) with two different service names per upload. It didn't seem to care about the service name and deduplicated anyway.

Broken or did I miss something? (we are on v. 2.14.0, but I didn't see a fix in that part in a quick changelog check...)

**Comment by damiencarol** [comment]
As @StefanFl mentioned, `service` attribute was designed for that. if it doesn't works it's a bug. we should focus on understanding why `service` attribute doesn't works.

**Comment by Alestrix** [comment]
Sorry to hijack this issue, but I think my topic is related.

In the [OpenAPI spec](https://demo.defectdojo.org/api/v2/oa3/swagger-ui/) of the image-scan API call it looks like I can segment my scan results by using a `service` (a freeform (?) string), an `endpoint` (by ID, so I need to create it beforehand), but there is also mentioning of a `component_name`, which I can only find in the API spec in conjunction with findings, but not in the import-scan call. When and what is stored into that `component_name`? Would it, e.g. in case of some container scan like Trivy, be the name of the scanned image? Or the affected library?

Could the "segmentation" of results (to confine deduplication to that segment) as mentioned by OP also be possible by `endpoint` or by `component_name`?

And where is all that documented?

**Comment by mtesauro** [comment]
@Alestrix To be blunt, service is a somewhat 1/2 baked feature which was contributed a while back. The idea was you could associate a service with a specific finding to distinguish the same finding that exists between two services. IMHO, you'd do yourself a favor to have different products or at least engagements if you want to make distinctions between findings. That's a much more reliable path then using service.

The 'documentation' on service is [here](https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/models.py#L2571)

I believe you can still use it as part of a [dedup](https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/models.py#L2571) hash calculation

As far as `component_name`, that's what DefectDojo calls a 3rd party library/module/software component like SCA scanners find. If a tool provides this info, it will be stored. Obviously, SCA tools do this as well as some others. If it's provided really depends on the tools output your adding to DefectDojo.

You can see the definition [here](https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/models.py#L2494).

So, for either of those items you list, you can potentially use them via the UI or API to restrict what's returned when you list/request findings.

**Comment by Alestrix** [comment]
Thanks @mtesauro for the links! (though I believe you wanted to link to another line for the dedup hash link)

Our issue is very similar to OP's: We scan our containers and if a vulnerability is fixed in one container image, that doesn't mean that it's also fixed in all other container images. Multiple containers (-> microservices) work together to provide a function, multiple functions are clustered into various domains (like management domain, service domain, ...) and sometimes different domains run on the same Kubernetes cluster. If for "close old findings" to work properly we would be required to put each container into its own product, then that would make it impossible to model the complex structure of our deployment.

Let's hope your statement

> I believe you can still use it as part of a [dedup](https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/models.py#L2571) hash calculation

holds true :) as `service` can be used far enough "down" in the hierarchy I believe.

**Comment by mtesauro** [comment]
@Alestrix Best of luck.

I'm going to go ahead and close this - I didn't realize it's been hanging around open as long as it has been until your update. Looks like our stale PR bot is busted. Guess, I'll look into that too :shrug:
