### ISSUE TITLE
APIv2: Inconsistent identifiers for objects

### ISSUE THREAD

**Issue by Nilix007** [DefectDojo/django-DefectDojo#682]
### Issue Type 
- [ ] Bug
- [x] Enhancement

### Description

Most of the objects are identified by their URL in the APIv2, f.e. the `Product` object with the `id=1` is identified by`http://myserver/api/v2/products/1/`.  However, there are also some objects which are identified by their ID or a name field, like `Report_Type` and `Notes`.

This inconsistency makes the APIv2 harder to use and should be resolved -- probably by adding the missing endpoints so that all objects can be identified by URLs.

(Also, I am not really sold on the URLs as identifier because I don't see any benefit compared to directly using the object IDs.)

**Comment by Nilix007** [comment]
Alright, I opened a PR at #694 with proposed changes 👍

**Comment by aaronweaver** [comment]
I believe this is addressed now. Please re-open if it's still an issue.
