### ISSUE TITLE
An exception error occurred during the report import:field larger than field limit (131072)

### ISSUE THREAD

**Issue by timsonner** [DefectDojo/django-DefectDojo#6827]
Description:
Importing an OpenVas CSV report, I encountered the error: 

An exception error occurred during the report import:field larger than field limit (131072)

Steps:
1. Do an OpenVAS scan and export the report as a CSV
2. In DefectDojo, create a new product
3. In the navigation bar of the product page, select the engements tab
4. Select add new interactive engagement
5. Near the bottom of the new engament page, select "Import scan results"
6. In the Scan type dropdown, select OpenVAS CSV
7. At the Choose report file section, choose the CSV from the OpenVAS scan
8. Click the import button

Expected result:
CSV is imported

Actual result:
Import fails with error

Environment:
Greenbone Security Assistant Version 21.4.3
Debian 11/Kali hybrid kernel 5.18.0-kali7-amd64
Firefox 91.13.0esr (64-bit) 

Notes:
This has to do with one of the fields in the CSV being absurdly large, OpenVAS was doing some DoS testing and it logged out hundreds of lines.

My solution to get the file to import was to open the CSV in Visual Studio Code and trim out the offending wall of text.

Once I did this and saved the file, DefectDojo imported the CSV file perfectly.

Possible fix:  
https://stackoverflow.com/questions/15063936/csv-error-field-larger-than-field-limit-131072  

Screenshots:  
Add a new engagement
![Screenshot from 2022-09-11 19-05-52](https://user-images.githubusercontent.com/66705347/189558773-e063ce90-0ade-4db1-bb7d-b431f4fe34dd.png)  
Select import scan results
![Screenshot from 2022-09-11 19-06-57](https://user-images.githubusercontent.com/66705347/189558774-9119026d-280d-425b-b8d2-a927f2bb4fab.png)
Choose report file, then select import
![Screenshot from 2022-09-11 19-15-52](https://user-images.githubusercontent.com/66705347/189558775-b448f70c-bd4a-4eee-a1c3-3b6ed0b58c9a.png)
The error message
![Screenshot from 2022-09-11 19-18-04](https://user-images.githubusercontent.com/66705347/189558776-6b87533e-a43a-41b0-b4df-ddcf3e438e03.png)

**Comment by iman4000** [comment]
did you resolve this issue?

**Comment by timsonner** [comment]
My solution to get the file to import was to open the CSV in Visual Studio Code and trim out some of the text from the CSV.

I actually forgot about this.

Might be worth looking into, replicating the results may be difficult though.

**Comment by manuel-sommer** [comment]
If someone has a sample file, I could take a look at this.

**Comment by manuel-sommer** [comment]
I guess this can be closed @mtesauro as there was no response for almost a month.
