### ISSUE TITLE
Interperter used for product grade is sensitive to denial of service

### ISSUE THREAD

**Issue by ycrumeyrolle** [DefectDojo/django-DefectDojo#6833]
https://github.com/DefectDojo/django-DefectDojo/blob/d54ea52791d7ee33ea0f83a8869b8e8764824e58/dojo/utils.py#L1545

The asteval Interpreter is used for computing the product grade. 
This interpreter is currently vulnerable to denial of service / bogus, either by infinite loop, or by infinite recursion. 

The Interpreter should be hardened with the follwoing parameters:  
- max_time, in order to introduce a timeout (but ... https://github.com/newville/asteval/issues/110)
- set no_* to True https://newville.github.io/asteval/api.html#asteval-api. For example no_for and no_while will avoid infinite loop.

**Comment by manuel-sommer** [comment]
As we always update the dependencies, I assume this can be closed @mtesauro
