### ISSUE TITLE
DefectDojo's Documentation

### ISSUE THREAD

**Issue by devhops** [DefectDojo/django-DefectDojo#6835]
On this page
https://defectdojo.github.io/django-DefectDojo/#where-to-find-defectdojo

The username and password for the demo site does not work.

![image](https://user-images.githubusercontent.com/539676/189909152-a31ce4c4-0a0c-4c68-b8a0-f1b828d6509a.png)

**Comment by mtesauro** [comment]
@devhops 
Sometimes "clever" people go and change the admin's password on the demo site.

We have automation in place to reset the password regularly for when this happens. 

So try again and you should be good to go. (FWIW, I just did and the provided username/password worked as expected),
