### ISSUE TITLE
Credentials encryption weaker than it should be

### ISSUE THREAD

**Issue by Nilix007** [DefectDojo/django-DefectDojo#684]
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description

The credentials encryption uses a 32byte hexadecimal key [0] for AES256 [1]. 

A hexadecimal string has only 16 values per byte so that the total entropy of the key is 128bit.  Therefore, the cryptographic strength of the credentials encryption is not 256bit but only 128bit which is still enough but much less than one would assume.

[0] https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/utils.py#L1340
[1] https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/utils.py#L1283

**Comment by aaronweaver** [comment]
I'd actually like to swap out the library behind that so will take care of that when that is done.
