### ISSUE TITLE
Metrics page graphs

### ISSUE THREAD

**Issue by DominykasLT** [DefectDojo/django-DefectDojo#6844]
**Problem description**
Hello, I just setup DefectDojo via Docker Compose, uploaded some issues and tried to check metrics (http://localhost:8080/metrics?date=5&view=dashboard), but it seems that I did something wrong, because the graph shows just 08/22 date (code haven't been changed). 

What could be wrong or what I did wrong, how can I check it or fix it? 

Thank you

**Steps to reproduce**
1. Instruction to setup is here https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/DOCKER.md

**Expected behavior**
Graph dates should be ascending or descending, but not the same.

**Deployment method** *(select with an `X`)*
- [X] Docker Compose

**Environment information**
 - Operating System: Windows 11
 - DefectDojo version (see footer) or commit message: 2.13.1

**Screenshots**
![image](https://user-images.githubusercontent.com/55694581/190417928-cf64526a-910a-41a1-9d68-a89b315c8fb7.png)

**Comment by saheredelgadom** [comment]
something similar happens with the individual metrics of the products, as you will see in the following images in that product I have 59 vulns registered but in the metrics only 14 are shown, I attach another screenshot to certify that all the findings are as active and verified
![Product-DefectDojo-metrics](https://user-images.githubusercontent.com/26166135/190708936-d2384905-4742-43d4-9c68-7cc3dfbf5b1f.png)
![Findings-DefectDojo-findings](https://user-images.githubusercontent.com/26166135/190708961-3cd90a25-287d-4e6c-80ab-4a341f6c6a0c.png)

**Comment by saheredelgadom** [comment]
So I just discovered that only the individual metrics accept current data values, it means that I add a report from any tool and put a 2021 data, it does not recognize it.

I did the test of changing the data of a vulnerability from 2021 to September 13 and it was recognized by the metrics.

Could you please help me correct this?

**Comment by saheredelgadom** [comment]
@DominykasLT 

It was resolved in the latest updates.

so you don't miss updates you can make a bash script to update the system before starting defectdojo run this before starting:

Pull the latest version

docker pull defaultdojo/defaultdojo-django:latest
docker pull defectdojo/defectdojo-nginx:latest

I also recommend that if you use defectdojo in production with mysql and you use the default database created by docker, I recommend that every time you close defectdojo you make a backup of the database.

You can also include that line in the script and automate all those processes.

**Comment by manuel-sommer** [comment]
I guess this can be closed @mtesauro, see last comment.
