### ISSUE TITLE
Error building the application

### ISSUE THREAD

**Issue by ArthurSouza37** [DefectDojo/django-DefectDojo#6857]
We are trying to install Defect-Dojo by following the steps below:

git clone https://github.com/DefectDojo/django-DefectDojo
cd django-DefectDojo
./dc-build.sh
./dc-up.sh mysql-rabbitmq
docker-compose logs initializer | grep "Admin password:"

Note > Machine using: Debian 10
<br /><br />

We are having **problems** when executing the line **./dc-build.sh**, where when trying to execute it shows the error message below:    

<br /><br />

**Error message**:

Err:3 http://security.debian.org/debian-security bullseye-security InRelease                                                                                                                 

  Could not connect to debian.map.fastlydns.net:80 (199.232.114.132), connection timed out Could not connect to security.debian.org:80 (151.101.194.132), connection timed out Could not conn

ect to security.debian.org:80 (151.101.2.132), connection timed out Could not connect to security.debian.org:80 (151.101.66.132), connection timed out Could not connect to security.debian.o

rg:80 (151.101.130.132), connection timed out                                                                                                                                                

Reading package lists...                                                                                                                                                                     

W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Could not connect to debian.map.fastlydns.net:80 (199.232.114.132), connection timed out Unable to connect to deb.d

ebian.org:http:                                                                                                                                                                              

W: Failed to fetch http://security.debian.org/debian-security/dists/bullseye-security/InRelease  Could not connect to debian.map.fastlydns.net:80 (199.232.114.132), connection timed out Cou

ld not connect to security.debian.org:80 (151.101.194.132), connection timed out Could not connect to security.debian.org:80 (151.101.2.132), connection timed out Could not connect to secur

ity.debian.org:80 (151.101.66.132), connection timed out Could not connect to security.debian.org:80 (151.101.130.132), connection timed out                                                 

W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Unable to connect to deb.debian.org:http:                                                                  

W: Some index files failed to download. They have been ignored, or old ones used instead.   

<br /><br /><br /><br /><br />

From the error message, we see that the machine is unable to access **debian.map.fastlydns.net:80**, and when accessing it through the browser, we see the following message:

Fastly error: unknown domain: debian.map.fastlydns.net. Please check that this domain has been added to a service.

Details: cache-cgh11139-CGH

**Comment by mtesauro** [comment]
Based on the error messages in your issue, it's a network error on your end/computer.  I'd check local connectivity and try the dc-build.sh script again.

HTH
