### ISSUE TITLE
MySQLdb.OperationalError: (1054, "Unknown column 'dojo_test_type.active' in 'field list'")

### ISSUE THREAD

**Issue by raziqk26** [DefectDojo/django-DefectDojo#6859]
Hey,

**Problem description**
I am facing the issue where initializer is getting failed due to MySQL Errors with exit code 0, I havent done any modifications to code besides a Logo change and resize in templates/base.html after that I am getting Server Error (500). To mitigate I have also tried to 

> export DD_INITIALIZE=true
and also purged Docker and re-built multiple times and I am still facing the same issue.

**Expected behavior**

**Deployment method** *(select with an `X`)*
- [X ] Docker Compose
- [] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: [Ubuntu 20.04]
 - DefectDojo version [2.14.1]

**Logs** 
[DefectDojo Logs.txt](https://github.com/DefectDojo/django-DefectDojo/files/9596947/DefectDojo.Logs.txt)

Regards

**Comment by manuel-sommer** [comment]
I guess this is maybe stale @mtesauro ?

**Comment by manuel-sommer** [comment]
Maybe such questions are better within the OWASP slack channel @raziqk26
