### ISSUE TITLE
Add database migrations

### ISSUE THREAD

**Issue by Nilix007** [DefectDojo/django-DefectDojo#686]
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description

DefectDojo does not include database migrations for the main app `dojo` and the documentation says that the end user has to create the migrations by themselves. This is against the common practice for Django (see [here](https://docs.djangoproject.com/en/1.11/topics/migrations/)) and has already been discussed before in #495 and #511.

This is very error prone for end users which have to track the migrations by themselves. If a user forgets to generate new migrations for each version or deletes migrations by accident, the database might get out of sync so that the inconsistencies have to be cleaned up by hand. Also in case of issues with a new release, a user might not be able to rollback the database to the old version.

Likewise, this approach is incompatible with containers: At XING, we have a containerized environment and we build stateless containers from DefectDojo's source. To keep track of migrations, I (basically) have to fork the DefejctDojo repository and manually generate migrations for each version we want to roll out.

Considering the issues mentioned in #511, I propose that the DefectDojo team generates one migration for each (new) stable release.

**Comment by aaronweaver** [comment]
As noted we've debated this in prior issues, I don't find it problematic but do understand the use case for containers.

That said, If we could do this in a way that makes it optional that's something we might consider. Perhaps we could tag it in a branch or another repo and auto-generate at release time from travis.

**Comment by Nilix007** [comment]
With proper DB migrations, we can also easily get rid of deprecated fields in the `Product` model [0] by providing a custom data migration. [1]

[0] https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/models.py#L424-L435
[1] https://docs.djangoproject.com/en/1.11/topics/migrations/#data-migrations

**Comment by aaronweaver** [comment]
@Nilix007 Would like your thoughts on this approach:

- Add in settings.py MIGRATION_MODULES = `{'defectdojo': 'defectdojo.db_migrations'}` The reason for not using the default migrations folder is to support legacy installations that have possibly added their own migrations and wish to continue managing them. For new installs this would be the default and existing installations if they want to can switch to this.
- I think there should be a short guide on committing migrations. I want to make sure, should there be a migration conflict in git, we have a procedure for rectifying this issue: For example:
  - branch1, developer A added a “text” field to the Finding model, generating a migration 0002_finding_text.py
  - branch2 developer B added a “cve” field to the Finding model, generating a migration 0002_finding_cve.py
 Most likely, use –merge can take care of this.

- Should we consider squashing migrations as well for optimization?

**Comment by Nilix007** [comment]
@aaronweaver Looks really good to me.  We could provide a squashed migration for every release, but I don't think this is necessary performance-wise.

**Comment by Nilix007** [comment]
@aaronweaver Another idea that just came to my mind:
- We should include a CI test that checks every PR for uncommitted or conflicting migrations

**Comment by devGregA** [comment]
@maennel had previously submitted a PR with a CI check

**Comment by aaronweaver** [comment]
Thanks for the reminder @devGregA I'll have the PR read shortly and will review what @maennel had previously submitted.
