### ISSUE TITLE
import-scan/reimport-scan

### ISSUE THREAD

**Issue by Wongt8** [DefectDojo/django-DefectDojo#6862]
### Discussed in https://github.com/DefectDojo/django-DefectDojo/discussions/6008

<div type='discussions-op-text'>

<sup>Originally posted by **RKCP** March  9, 2022</sup>
Hi,

I may be using the API wrong, but no matter what payload I send to the two endpoints in the title, I always get `"product_name parameter missing"` as a response, along with `400 Bad Request`.

If I execute these endpoints through the swagger docs, there is no issue, but in Postman I keep getting this response. I even duplicated the swagger doc payload and still get the issue.

This happens whether I run defectdojo locally, or use the demo tool.

I have attached an image of a request I am sending. Any one have ideas on what is going wrong?

<img width="859" alt="image" src="https://user-images.githubusercontent.com/43743193/157442477-e0f2c4f2-9e69-4e86-b531-2914ee3f7cb0.png">
</div>

**Comment by italvi** [comment]
I am not sure whether this solves your problem but you have a typo, it should be auto_create_context, not auto_create_contex. 
Furthermore, the API Doku says, that your Data should not be raw but form-data, using this works for me:
![image](https://user-images.githubusercontent.com/58322186/191255434-4b663ea7-3d8f-472b-af98-fa020e789699.png)

**Comment by Wongt8** [comment]
Thank for the answear,
I haven't seen the typo error *it is not my screenshot, it is originally posted by RKCP* but even by fixing the typo this is not working
I gonna give more exemple down below with Python.

```py
import json
import requests

url = 'http://10.0.2.7:8080/api/v2/import-scan/'

headers = { "content-Type": "multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW",
            'Authorization': 'Token fa2. . .f'}

file = {"file": open("./OS_Detection.csv","rb").read()}

data_to_import = {
        "scan_date": "2022-03-12",
        "minimum_severity":"Info",
        "acitive": True,
        "verified": True,
        "scan_type": "Nessus Scan",
        "file": file,
        "product_type_name":"Manufacturing Site",
        "product_name":"Banking Site 1",
        "engagement_name":"Banking Site 1 - Annual Pentest",
        "close_old_findings": False,
        "push_to_jira": False,
        "auto_create_context": True
}

r = requests.post(url, files=file, json=data_to_import, headers=headers)
print(r, r.text)
```
I still got 
```
<400 Bad Request>, "product_name parameter missing" 
```
I also tried using the `engagement ID `, so I don't even need to provid `product_name`
*the code is the same, only `data_to_import` is changing*
**New data_to_import** : 
```py
data_to_import = {
        "scan_date": "2022-03-12",
        "minimum_severity":"Info",
        "acitive": True,
        "verified": True,
        "scan_type": "Nessus Scan",
        "file": file,
        "engagement": 7,
        "close_old_findings": False,
        "push_to_jira": False
}
```
I still got 
```
<400 Bad Request>, "product_name parameter missing" 
```
Even if it is not supposed to check the `product_name` because I'm using the `engagement ID`.

So I'm a bit lost. Don't know if I'm doing wrong or this is a issue with the API.

Maybe I should have explained that immediately

**Comment by alt3kx** [comment]
Guys FYI , API seems to be working OK
```ruby
Demo page 
https://demo.defectdojo.org

user: admin 
pass: 1Defectdojo@demo#appsec
```  

1. Get the token using the user/credentials
```ruby
$ curl -X POST -H 'content-type: application/json' https://demo.defectdojo.org/api/v2/api-token-auth/ -d '{"username": "admin", "password":  "1Defectdojo@demo#appsec"}' 
{"token":"548afd6fab3bea9794a41b31da0e9404f733e222"}%  
```  

2. Now consume the API endpoints using the Autorhization token header as intructions posted , my simple test below 
```ruby
$ curl -X GET  -H 'content-type: application/json' https://demo.defectdojo.org/api/v2/ -H "Authorization: Token 548afd6fab3bea9794a41b31da0e9404f733e222" 
```
3. Or using curl command and parsing the response with jq command
```ruby
$ curl -X GET  -H 'content-type: application/json' https://demo.defectdojo.org/api/v2/ -H "Authorization: Token 548afd6fab3bea9794a41b31da0e9404f733e222" | jq . 
[../snip]
```
![image](https://user-images.githubusercontent.com/3140111/191547712-d3d40a47-e7db-49d1-b889-ed1988be4123.png)
4. Just following the sample provide into API documentation and  extract users available , source here: https://demo.defectdojo.org/api/key-v2 , my test  below 
```ruby
$ curl -X GET  -H 'content-type: application/json' https://demo.defectdojo.org/api/v2/users/ -H "Authorization: Token 548afd6fab3bea9794a41b31da0e9404f733e222" | jq . 
```
![image](https://user-images.githubusercontent.com/3140111/191548307-dcde09d6-8390-49dd-8402-9a9eae5429e2.png)
5. Now lest's create something quickly  based on APIs  documentation 
source1: https://demo.defectdojo.org/api/v2/oa3/swagger-ui/ and based on data available on demo portal
source2: https://demo.defectdojo.org/engagement/8 
```ruby
$ curl -XPOST https://demo.defectdojo.org/api/v2/import-scan/ -H 'accept: application/json' -H 'Content-Type: multipart/form-data' -H 'X-CSRFTOKEN: vLnVqtviVF6TXE40uy0XmnfuYoWWahLyZwfNV0RX2VN48vYyiQKeXmtHDKDvfnxq' -F 'product_type_name=Billing' -F 'active=true' -F 'endpoint_to_add=' -F 'verified=true' -F 'close_old_findings=false' -F 'test_title=' -F 'engagement_name=alex666_engagement' -F 'build_id=' -F 'deduplication_on_engagement=' -F 'push_to_jira=false' -F 'minimum_severity=Critical' -F 'scan_date=2022-09-21' -F 'environment=' -F 'service=' -F 'commit_hash=' -F 'group_by=' -F 'version=' -F 'tags=api test alex 2' -F 'api_scan_configuration=' -F 'product_name= Apple Accounting Software' -F 'file=' -F 'auto_create_context=' -F 'lead=' -F 'scan_type=Nessus Scan' -F 'branch_tag=' -F 'engagement=8' -H "Authorization: Token 548afd6fab3bea9794a41b31da0e9404f733e222"
```

6. Even with Internal error my API tests were  created :-)  , please just ready becareful the API documentation and play with swagger file the same building  your python code... 
![image](https://user-images.githubusercontent.com/3140111/191546530-3cfe5bec-ab12-4b22-8860-c4622cbd84b3.png)

![image](https://user-images.githubusercontent.com/3140111/191547063-91aabc07-6445-4bd0-bfd8-2b6679681694.png)

**Comment by Wongt8** [comment]
Ok I finally manage to make it work.
The problem was in my headers `X-CSRF Token` was missing and something that I was totally not aware on my `data_to_import`
I need to write it like this `"field_name": (None, data)`
Exemple : 
```py

headers = { 'accept': 'application/json',
            'X-CSRFToken': CSRFToken,
            'Authorization': f'Token {TOKEN}'}

data_to_import = {
        "scan_date": (None, "2022-03-12"),
        "minimum_severity":(None, "Info"),
        "acitive": (None, True),
        "verified": (None, True),
        "scan_type": (None, "Nessus Scan"),
        "file": file,
        "product_type_name":(None, "Web Site"),
        "product_name":(None, "TEST PROD"),
        "engagement_name":(None, "TEST"),
        "close_old_findings": (None, False),
        "push_to_jira": (None, False)
}
```
So I will close the issue thank for the help 😄
