### ISSUE TITLE
Brup parser vulnerable to XXE attacks

### ISSUE THREAD

**Issue by Nilix007** [DefectDojo/django-DefectDojo#689]
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description

The Burp parser does not use `defusedxml` like most of the parsers but `lxml` as you can see [here](https://github.com/DefectDojo/django-DefectDojo/blob/dev/dojo/tools/burp/parser.py#L11).  This make it vulnerable to XXE attacks and can be used by an attacker to access local files.

**Comment by aaronweaver** [comment]
Updated to use defusedxml.
