### ISSUE TITLE
Deduplication of Dependency Track import disables active vulnerabilities

### ISSUE THREAD

**Issue by IchGehSteil** [DefectDojo/django-DefectDojo#6899]
**Slack us first!**
Done

**Problem description**
I have a Dependency Track instance that sends daily updates to DefectDojo. After working with the vulnerabilities, like manually deduplicating what was not recognized or adding mitigations, requests and so on, the next day the import from Dependency Track sets the vulnerability I worked on to duplicate and inactive. Actually I want it the other way around, to recognize what I have worked on and set the new imported vulnerability to duplicate.
Any way to achieve this with the current version 2.14.2?

**Steps to reproduce**
1. Set up one product
2. Add multiple endpoints. Endpoints are representing each a module of the product.
3. Setup an engagement for each endpoint
4. Make use of the Dependency Track import for each engagement (deduplication not limited to the engagement)
5. Wait for import of findings from DT. 
6. Edit any Vulnerability (Change severity, add mitigation, add resources, merge similar or linked vulnerabilities, etc...)
7. Wait for next import from DT
8. Edited Vulnerability is set to inactive (sometimes mitigated)
9. The same imported Vulnerability is set to active and contains none of the information that was previously added.

**Expected behavior**
Recognize the vulnerability that was edited and set the new import to duplicate and inactive.

**Deployment method**
- Docker Compose

**Environment information**
 - Operating System: Debian 11
 - DefectDojo version 2.14.2

**Logs** 
Let me know what could be usefull for this.

**Comment by bakalor** [comment]
Same issue with latest 2.16.1 version and Trivy scans, it put validated finding with Jira ticket assigned to duplicates and eventually findings is wiped out by dedup clean up mechanism. Thus we completely lose finding attached to created Jira ticket...

**Comment by B310M0R** [comment]
+1

**Comment by manuel-sommer** [comment]
I guess this is a stale issue @mtesauro as we have put work into DependencyTrack and Trivy in the last releases. 
It would rather help to open up new issues with the latest releases.

**Comment by mtesauro** [comment]
@manuel-sommer I agree.
