### ISSUE TITLE
Forbidden (CSRF cookie not set.): /login

### ISSUE THREAD

**Issue by nicoleoakley** [DefectDojo/django-DefectDojo#691]
### Issue Type 
- [X] Bug
- [ ] Enhancement

### Description
When anything is created or updated in JIRA and the webhook fires, I get the following POST error on my dojo server

"POST /webhook?user_id=nicole.krantz&user_key=nicole.krantz HTTP/1.1" 302 0
Forbidden (CSRF cookie not set.): /login
Forbidden (CSRF cookie not set.): /login
[08/Aug/2018 07:54:19] "POST /login?next=/webhook%3Fuser_id%3Dnicole.krantz%26user_key%3Dnicole.krantz HTTP/1.1" 403 2857

Is this a problem within settings.py? 

### Operating System 
Ubuntu 16.04

### Install

- [X] setup.bash
- [ ] docker

### DefectDojo Version
1.5.2

### Steps to Reproduce
update anything in JIRA instance after setting up configuration in DefectDojo

**Comment by nicoleoakley** [comment]
Do you think it is related to the webhook function in /dojo/jira_link/views.py not passing a request to the template's render method?

**Comment by bars1001** [comment]
I am having the same issue
