### ISSUE TITLE
migration from version 2.9.0 doesn't work

### ISSUE THREAD

**Issue by sergeymeleschenko** [DefectDojo/django-DefectDojo#6922]
I want to update Defectdojo from v 2.9.0 to the latest.
1. I'm backup MySQL DB.
2. ./dc-stop.sh
3. docker pull defectdojo/defectdojo-django:latest
4. ./dc-up-d mysql-rabbitmq
Got the latest version, but I can't enter to system_settings - Server Error (500)

django-defectdojo-initializer-1  | Initializing.
django-defectdojo-initializer-1  | [30/Sep/2022 11:49:59] INFO [dojo.models:4056] enabling audit logging
django-defectdojo-initializer-1  | Waiting for database to be reachable
django-defectdojo-initializer-1  | Making migrations
django-defectdojo-initializer-1  | [30/Sep/2022 11:50:02] INFO [dojo.models:4056] enabling audit logging
django-defectdojo-initializer-1  | No changes detected in app 'dojo'
django-defectdojo-initializer-1  | Migrating
django-defectdojo-initializer-1  | [30/Sep/2022 11:50:09] INFO [dojo.models:4056] enabling audit logging
django-defectdojo-initializer-1  | Operations to perform:
django-defectdojo-initializer-1  |   Apply all migrations: admin, auditlog, auth, authtoken, contenttypes, django_celery_results, dojo, sessions, sites, social_django, tagging, watson
django-defectdojo-initializer-1  | Running migrations:
django-defectdojo-initializer-1  |   Applying auditlog.0010_alter_logentry_timestamp... OK
django-defectdojo-initializer-1  | Traceback (most recent call last):
django-defectdojo-initializer-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
django-defectdojo-initializer-1  |     return self.cursor.execute(sql, params)
django-defectdojo-initializer-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
django-defectdojo-initializer-1  |     return self.cursor.execute(query, args)
django-defectdojo-initializer-1  |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
django-defectdojo-initializer-1  |     res = self._query(query)
django-defectdojo-initializer-1  |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
django-defectdojo-initializer-1  |     db.query(q)
django-defectdojo-initializer-1  |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
django-defectdojo-initializer-1  |     _mysql.connection.query(self, query)
django-defectdojo-initializer-1  | MySQLdb.OperationalError: (1022, "Can't write; duplicate key in table '#sql-1_14'")
django-defectdojo-initializer-1  |
django-defectdojo-initializer-1  | The above exception was the direct cause of the following exception:
django-defectdojo-initializer-1  |
django-defectdojo-initializer-1  | Traceback (most recent call last):
django-defectdojo-initializer-1  |   File "manage.py", line 11, in <module>
django-defectdojo-initializer-1  |     execute_from_command_line(sys.argv)
django-defectdojo-initializer-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
django-defectdojo-initializer-1  |     utility.execute()
django-defectdojo-initializer-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
django-defectdojo-initializer-1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
django-defectdojo-initializer-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
django-defectdojo-initializer-1  |     self.execute(*args, **cmd_options)
django-defectdojo-initializer-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
django-defectdojo-initializer-1  |     output = self.handle(*args, **options)
django-defectdojo-initializer-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
django-defectdojo-initializer-1  |     res = handle_func(*args, **kwargs)
django-defectdojo-initializer-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
django-defectdojo-initializer-1  |     post_migrate_state = executor.migrate(
django-defectdojo-initializer-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
django-defectdojo-initializer-1  |     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
django-defectdojo-initializer-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
django-defectdojo-initializer-1  |     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
django-defectdojo-initializer-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 230, in apply_migration
django-defectdojo-initializer-1  |     migration_recorded = True
django-defectdojo-initializer-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 118, in __exit__
django-defectdojo-initializer-1  |     self.execute(sql)
django-defectdojo-initializer-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 145, in execute
django-defectdojo-initializer-1  |     cursor.execute(sql, params)
django-defectdojo-initializer-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
django-defectdojo-initializer-1  |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
django-defectdojo-initializer-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
django-defectdojo-initializer-1  |     return executor(sql, params, many, context)
django-defectdojo-initializer-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
django-defectdojo-initializer-1  |     return self.cursor.execute(sql, params)
django-defectdojo-initializer-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
django-defectdojo-initializer-1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
django-defectdojo-initializer-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
django-defectdojo-initializer-1  |     return self.cursor.execute(sql, params)
django-defectdojo-initializer-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
django-defectdojo-initializer-1  |     return self.cursor.execute(query, args)
django-defectdojo-initializer-1  |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
django-defectdojo-initializer-1  |     res = self._query(query)
django-defectdojo-initializer-1  |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
django-defectdojo-initializer-1  |     db.query(q)
django-defectdojo-initializer-1  |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
django-defectdojo-initializer-1  |     _mysql.connection.query(self, query)
django-defectdojo-initializer-1  | django.db.utils.OperationalError: (1022, "Can't write; duplicate key in table '#sql-1_14'")
django-defectdojo-initializer-1  |   Applying dojo.0157_vulnerability_reference...Admin user: admin
django-defectdojo-initializer-1  | [30/Sep/2022 11:50:13] INFO [dojo.models:4056] enabling audit logging
django-defectdojo-initializer-1  | Admin password: Initialization detected that the admin user admin already exists in your database.
django-defectdojo-initializer-1  | If you don't remember the admin password, you can create a new superuser with:
django-defectdojo-initializer-1  | $ docker-compose exec uwsgi /bin/bash -c 'python manage.py createsuperuser'
django-defectdojo-initializer-1  | Initialization of test_types
django-defectdojo-initializer-1  | [30/Sep/2022 11:50:14] INFO [dojo.models:4056] enabling audit logging
django-defectdojo-initializer-1  | Creation of non-standard permissions
django-defectdojo-initializer-1  | [30/Sep/2022 11:50:17] INFO [dojo.models:4056] enabling audit logging
django-defectdojo-initializer-1  | [30/Sep/2022 11:50:18] INFO [dojo.management.commands.initialize_permissions:28] Non-standard permissions have been created

**Comment by jplopezy2** [comment]
I have the same problem... I migrated from version 2.6 to 2.13 without problem... but when I go from 2.13 to 2.14 it generates this error 500 when I want to see the findings... it is strange it is as if something had changed in that part of the database...

**Comment by jplopezy** [comment]
I have the same problem... I migrated from version 2.6 to 2.13 without problem... but when I go from 2.13 to 2.14 it generates this error 500 when I want to see the findings... it is strange it is as if something had changed in that part of the database...

**Comment by manuel-sommer** [comment]
I guess this release so so old that this issue is deprecated @mtesauro

**Comment by mtesauro** [comment]
Closed as stale
