### ISSUE TITLE
Qualys Monthly PCI Scan

### ISSUE THREAD

**Issue by ravishel** [DefectDojo/django-DefectDojo#6932]
Qualys Monthly PCI Scan
Name of the scanner, brief description of the scanner and link.

Currently I have tried using the Qualys Scan, and it imports with zero findings

[Book1.csv](https://github.com/DefectDojo/django-DefectDojo/files/9694710/Book1.csv)

**Comment by damiencarol** [comment]
please @ravishel follow our guidelines to open issues. The description lack some mandatory details.

**Comment by manuel-sommer** [comment]
This issue can be closed @mtesauro
