### ISSUE TITLE
Add a Sysdig importer

### ISSUE THREAD

**Issue by e-minguez** [DefectDojo/django-DefectDojo#6939]
**Scanner Name**

Sysdig vulnerability reports

https://docs.sysdig.com/en/docs/sysdig-secure/vulnerabilities/reporting/

Sysdig Secure can schedule asynchronous reports about detected runtime vulnerabilities along with package and image data.

**Sample File**

https://github.com/e-minguez/sysdig-to-defectdojo/blob/main/examples/20220926-090023-2Bw41vBq8qfnCThYiYDhr6EoMKQ-2FIbycpRUupe7syyasV3bBSV0kV.json

** Notes **

I tried the other way around, converting the Sysdig report to a generic one https://github.com/e-minguez/sysdig-to-defectdojo but I guess it should be better to do it the opposite way.

**Comment by coheigea** [comment]
Are you planning to contribute a pull request for this feature @e-minguez ?

**Comment by damiencarol** [comment]
I took a look at the report format and it's configurable, it will be hard as most of the data could be optional.

**Comment by manuel-sommer** [comment]
Can you close this @mtesauro ?

**Comment by miles3719** [comment]
Since this shows up in google when you search for Sysdig and Defect Dojo, just pointing anyone who gets here, a parser was created

https://github.com/DefectDojo/django-DefectDojo/pull/8868

and by the time you read this, is in the main branch already

**Comment by e-minguez** [comment]
cc @manuelbcd
