### ISSUE TITLE
Checkmarx JSON Report Not Parsing

### ISSUE THREAD

**Issue by adamtimmins** [DefectDojo/django-DefectDojo#6956]
From looking at the parser script for Checkmarx it can't successfully parse the latest JSON reports from Checkmarsx One. 

When adding the standard vulnerability report from Checkmarx One it has difficulty parsing which vulnerabilities to import. There's three scanning modules that we have access to; SAST, SCA and KICS. Currently the script seems to only support SAST. Can we get support for SCA and KICS as well? 

Within the report for SAST there is an error to retrieve these these results in `_get_findings_json` function. It cannot parse the report because the SAST field of the report is not specifically specified. 

Also within the SAST report the field for  `date` has changed from:
`"firstFoundDate": "2022-02-25T21:55:06Z"`
to:
`"firstFoundDate": { "seconds": 1651835167 }`

**Deployment method** *(select with an `X`)*
- [ X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: AWS Linux 2 
 - DefectDojo version: v. 2.14.3 
 
**Logs** 
Returns generic parser error

**Sample scan files**

**Screenshots**

**Additional context** (optional)

**Comment by damiencarol** [comment]
@adamtimmins is it possible to have a report (even obfuscated)?

**Comment by adamtimmins** [comment]
@damiencarol hi I emailed you a sample report.

**Comment by damiencarol** [comment]
taking a look

**Comment by damiencarol** [comment]
@adamtimmins it's more deep than what I through :D  
1) what you ask is support for 2 diferent data type (SCA and KICS), the parser currently only support SAST
2) I saw hidden bugs in the current code XD

**Comment by damiencarol** [comment]
Fixed by #7552
