### ISSUE TITLE
Support for Chef InSpec

### ISSUE THREAD

**Issue by LOLCATATONIA** [DefectDojo/django-DefectDojo#6990]
Please support integration with [Chef InSpec](https://github.com/inspec/inspec). I thought it was already supported, but I can't find it listed on https://github.com/DefectDojo/django-DefectDojo/tree/master/dojo/tools ?

**Comment by mtesauro** [comment]
@LOLCATATONIA Do you have an example output file from Chef InSpec you can share?  If so adding it to this repo - https://github.com/DefectDojo/sample-scan-files is a great way to assist getting a new parser added to DefectDojo.

The example file doesn't have to have 'real' data in it - just have reasonable data and keeps the structure of the tools output.  For example, I added a [BugCrowd file to that repo](https://github.com/DefectDojo/sample-scan-files/blob/master/bugcrowd/BugCrowd-export.csv) but have never worked for 'BigCorp'.  I simply took legit output from a tool and removed/re-wrote anything that might identify the actual source. Some contributors have scanned open source / known vulnerable apps (OWASP JuiceShop) to produce output files as well.

HTH

**Comment by LOLCATATONIA** [comment]
[inspec_audit.log](https://github.com/DefectDojo/django-DefectDojo/files/9798419/inspec_audit.log)

Here's a sample file. I had trouble pulling that repo.

**Comment by manuel-sommer** [comment]
This issue can be closed @mtesauro
