### ISSUE TITLE
Nessus Import Incorrect Severity

### ISSUE THREAD

**Issue by AmenoBars** [DefectDojo/django-DefectDojo#6992]
Hello,

We've been testing DefectDojo for managing Nessus imports. I've noticed that the Severity seems to be acting weird. It seems to take the values from the Nessus scan correctly, but not display them correctly. If I then go to edit the finding, it will have the right settings and then saving it without making changes it displays as it does according to the Nessus report. As an example, this finding is marked in Nessus as a 9.8 - Critical, but is showing in DefectDojo findings as a 9.8 High:

![image](https://user-images.githubusercontent.com/61434742/195872720-d973fb9a-e1e4-4192-a0a3-6b14585e2df0.png)

If I then go and edit it, it has critical as the severity rating:
![image](https://user-images.githubusercontent.com/61434742/195872797-4a641e7b-73ed-4580-952b-18001eaa4595.png)

And then saving that without making any changes to what was already there changes it to a critical:
![image](https://user-images.githubusercontent.com/61434742/195872875-172977cf-eea2-4ba4-a0b3-ecc8d49d5da3.png)

Is this expected behaviour? It seems odd.

**Comment by Retrospected** [comment]
We seem to have the exact same issue: A finding marked in Nessus as HIGH was imported in DefectDojo as MEDIUM. Changing the finding in DefectDojo showed the right severity (HIGH). Re-saving the finding without modifying any fields would update the severity back to the correct one.

**Comment by Retrospected** [comment]
it has been a while, for me this is not relevant anymore and I don't have access to a sample file either, sorry. Hopefully @AmenoBars can help out

**Comment by manuel-sommer** [comment]
I managed to reproduce this with existing unittests, but thank you anyway. :-)

**Comment by manuel-sommer** [comment]
could you close this issue please @mtesauro ?
