### ISSUE TITLE
An exception error occurred during the report import:A string literal cannot contain NUL (0x00) characters.

### ISSUE THREAD

**Issue by 2013kaa** [DefectDojo/django-DefectDojo#6999]
hi, I'm getting the error "An exception error occurred during the report import:A string literal cannot contain NUL (0x00) characters." when downloading the TruffleHog3 scanner report. I found a defect repays for the appearance of an error, it is in the application.
Version DD v. 2.15.0 (release mode)
[error.txt](https://github.com/DefectDojo/django-DefectDojo/files/9801634/error.txt)

**Comment by 2013kaa** [comment]
Forgot to write that the error is in the field "context"
There is an idea that somehow the escaping of special characters does not work correctly

**Comment by manuel-sommer** [comment]
Please close this issue @mtesauro
