### ISSUE TITLE
Server error when Accessing System Settings

### ISSUE THREAD

**Issue by guilhermepaulozup** [DefectDojo/django-DefectDojo#7001]
Deployed version 2.15.0 to AWS EC2 with a RDS using docker-compose.

**Bug description**

The application works almost just fine but when accessing System Settings we get a Server Error (500).

Reading the logs from uwsgi container, this exception is raised when the error occurs:

```
file "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 551, in create_connect_args
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Invalid SQLite URL: sqlite://defectdojo:***@/dojo.celerydb.sqlite
Valid SQLite URL forms are:
 sqlite:///:memory: (or, sqlite://)
 sqlite:///relative/path/to/file.db
 sqlite:////absolute/path/to/file.db
 ```

**Steps to reproduce**
1. Deploy DefectDojo to EC2 using docker-compose.
2. Access the login page and login
3. Click on Settings > System Settings

**Expected behavior**
The System Settings menu to appear

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Amazon Linux 2
 - DefectDojo version (see footer) or commit message: 2.15.0

**Logs** 
Use `docker-compose logs` (or similar, depending on your deployment method) to get the logs and add the relevant sections here showing the error occurring (if applicable).

**Screenshots**

![error_dd_1](https://user-images.githubusercontent.com/90329628/196248842-f5c3b8a3-1800-40e6-9959-c45d28e8e994.png)

![error_dd_2](https://user-images.githubusercontent.com/90329628/196246837-78a371ec-bfbf-48d0-be28-78d9852845a5.png)

![error_dd_3](https://user-images.githubusercontent.com/90329628/196247623-3861d80b-7758-4603-b9a4-90309f91c057.png)

**Comment by badal-hd** [comment]
use `defectdojo/defectdojo-django:2.24.3` version it worked for me. I was facing same issue in 2.24.4.

**Comment by guilhermepaulozup** [comment]
This issue is kinda old already, we updated to another version earlier after and the issue was gone. Closing.
