### ISSUE TITLE
Jira Templates being ignored

### ISSUE THREAD

**Issue by devsecopsale** [DefectDojo/django-DefectDojo#7029]
**Bug description**
When Jira templates (jira_full or jira_limited) are modified, it doesn't impact on new tickets creation. Docker images must be rebuilt in order for the changes to have effect, which is not the desired behaviour.

**Steps to reproduce**
1. Edit any template file such as templates/issue-trackers/jira_limited/jira_description.tpl
2. restart docker containers
3. Create new jira instance using webUI (with jira_limited as template)
4. Configure the new created jira instance (with jira_limited as template from the drop down menu)
5. create new finding and push it
6. check ticket description

**Expected behavior**
Ticket description should match jira template

**Deployment method** *(select with an `X`)*
- [ x] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - DefectDojo version 2.15.1

**Comment by mtesauro** [comment]
In some respects, that's kinda how Docker works - the images are meant to be ephemeral and not to persist changes.

You've got a couple of choices if you want to keep data around after a docker 'restart'

(1) Re-build the container as you mention above with your changes and use that container.  I generally build all the containers I use in prod locally just so I know what goes into them and can replicate the process in case the upstream images disappear. So, this is what I'd do FWIW.

(2) Use a volume to place your customizations into the container (could be a Docker volume or a bind-mount from the host)

(3) Launch the 'normal' DefectDojo container, use `docker cp` to move in your customized template into the container then save that running container as a new image.  Update docker-compose to use your new image and your changes should be there. Its sort of another way to build a custom image.  See https://www.howtogeek.com/devops/how-to-create-a-docker-image-from-a-running-container/

Its possible that in future releases the entrypoint script for DefectDojo may take updated jira templates and make them available without rebuilding the containers but that PR hasn't been written by someone yet.

HTH

**Comment by devsecopsale** [comment]
Hi. I actually bind mounted the /app/templates (dojo/templates) DIR to a docker host's dir. When I change the template it's not reflected. I can see that the files in the docker container are actually changed (by running docker exec...).
It doesn't happen the same if I edit, for example, a report template, where after I restart uwsgi container, it takes the changes immediately.

**Comment by mtesauro** [comment]
Oh, very interesting.  I've not experimented with the Jira templates myself so haven't tried to to the bind mount you described.

That is an odd behavior that you experienced. I can try to find time to try out the Jira templates of hopefully someone else will chime in on the Jira templates.  Maybe @Maffooch has used them.

**Comment by devsecopsale** [comment]
I believe this is just a behaviour. When Jira templates are modified, the docker container must be rebuilt.
