### ISSUE TITLE
Swagger not showing complete documentation for API v2 docs

### ISSUE THREAD

**Issue by Horst88** [DefectDojo/django-DefectDojo#703]
Please use the following template when submitting issues:

### Issue Type 
- [x ] Bug
- [ ] Enhancement

### Description
Hi,
I am using v.1.5.2 in Docker and accessing the API V2 Docs I am missing the documentation for the whole API. I only see one entry for api-token-auth and not all methods like documented on swagger-hub, see screenshot.

### Operating System 
Please include the version number (ex: Ubuntu 16.04)

### Install

- [ ] setup.bash
- [x ] docker

### DefectDojo Version
1.5.2

### Steps to Reproduce
- login
- open API v2 Docs
- check swagger

### Screenshots (optional)
![defectdojo-api2-swagger](https://user-images.githubusercontent.com/32541498/44035109-5b1bddd8-9f17-11e8-9589-826925703422.png)

**Comment by aaronweaver** [comment]
I believe you have to authorize it before you can view the rest of it.

**Comment by Horst88** [comment]
Can you elaborate? So I login to to Defect-Dojo and then have to authorize to see the swagger documentation? How?
So trying the authorize button with the API key does not result in showing the whole API docu, see screenshot. The user has all necessary rights, ...
![rundeck-apiv2-swagger](https://user-images.githubusercontent.com/32541498/44073993-82090dde-9f9f-11e8-8dbc-d1d5d4044263.png)

**Comment by aaronweaver** [comment]
Not sure, when I click on authorize this is what I see. Also, I'm working on a process to push the swagger file here as well: https://app.swaggerhub.com/apis/DefectDojo/defect-dojo_api_v_2/1.0.0

![image](https://user-images.githubusercontent.com/220838/44090374-f5164966-9f97-11e8-956a-ac86aebce60e.png)

**Comment by aaronweaver** [comment]
Can't reproduce this issue.

**Comment by Horst88** [comment]
Here a screencast, ....
[defectdojo-api.zip](https://github.com/DefectDojo/django-DefectDojo/files/2293668/defectdojo-api.zip)

**Comment by Horst88** [comment]
@aaronweaver  So this does also not work on the demo in heroku, see https://defectdojo.herokuapp.com

**Comment by aaronweaver** [comment]
Please follow these steps:

1.  Navigate to: https://defectdojo.herokuapp.com/api/key-v2
2. Copy the full Token <api-key>
3. Navigate to: https://defectdojo.herokuapp.com/api/v2/doc/
4. Click Authorize and then paste in the full Token <api-key> 

![image](https://user-images.githubusercontent.com/220838/44527482-ea4c6780-a6b4-11e8-9509-ce2448113250.png)

**Comment by Horst88** [comment]
So finally I figured it out, ... you have to insert the hole "API Authorization Header value" including the "Token" text, ... and not only the API-Key, ... this is somehow misleading, ....

**Comment by wheelq** [comment]
> @aaronweaver
> So finally I figured it out, ... you have to insert the hole "API Authorization Header value" including the "Token" text, ... and not only the API-Key, ... this is somehow misleading, ....

wow
