### ISSUE TITLE
K8s (minikube) INSTALLATION FAILED: failed post-install: timed out waiting for the condition

### ISSUE THREAD

**Issue by sprathod369** [DefectDojo/django-DefectDojo#7037]
Installed Helm version - 3.9.4
Installed Minikube version - 1.26.1

1) Follow KUBERNETES.md instructions - [kubernetes-local-quickstart](https://github.com/DefectDojo/django-DefectDojo/blob/dev/readme-docs/KUBERNETES.md#kubernetes-local-quickstart)
2) Perform helm install
3) See error

~/django-DefectDojo$ helm install defectdojo ./helm/defectdojo --set django.ingress.enabled=true --set django.ingress.activateTLS=false --set createSecret=true --set createRabbitMqSecret=true --set createMysqlSecret=true

**Error: INSTALLATION FAILED: failed post-install: timed out waiting for the condition**

**Debug mode**
~/django-DefectDojo$ helm install defectdojo ./helm/defectdojo --set django.ingress.enabled=true --set django.ingress.activateTLS=false --set createSecret=true --set createRabbitMqSecret=true --set createMysqlSecret=true --debug

install.go:192: [debug] Original chart version: ""
install.go:209: [debug] CHART PATH: ~/django-DefectDojo/helm/defectdojo

client.go:310: [debug] Starting delete for "defectdojo" ServiceAccount
client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "defectdojo" Secret
client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "defectdojo-mysql-specific" Secret
client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "defectdojo-rabbitmq-specific" Secret
client.go:128: [debug] creating 1 resource(s)
client.go:128: [debug] creating 16 resource(s)
client.go:310: [debug] Starting delete for "defectdojo-initializer-2022-10-21-17-52" Job
client.go:339: [debug] jobs.batch "defectdojo-initializer-2022-10-21-17-52" not found
client.go:128: [debug] creating 1 resource(s)
client.go:540: [debug] Watching for changes to Job defectdojo-initializer-2022-10-21-17-52 with timeout of 5m0s
client.go:568: [debug] Add/Modify event for defectdojo-initializer-2022-10-21-17-52: ADDED
client.go:607: [debug] defectdojo-initializer-2022-10-21-17-52: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:568: [debug] Add/Modify event for defectdojo-initializer-2022-10-21-17-52: MODIFIED
client.go:607: [debug] defectdojo-initializer-2022-10-21-17-52: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
Error: INSTALLATION FAILED: failed post-install: timed out waiting for the condition
helm.go:84: [debug] failed post-install: timed out waiting for the condition
INSTALLATION FAILED
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:141
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.5.0/command.go:872
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.5.0/command.go:990
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.5.0/command.go:918
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:250
runtime.goexit
        runtime/asm_amd64.s:1571

**Comment by dsever** [comment]
Do you have enough resources on the k8s?

**Comment by sprathod369** [comment]
I believe so - minikube setup is running on an Ubuntu VM with a 4 CPU / 16 GB Memory configuration. I'm able to successfully install DefectDojo using the docker-compose approach (postgresql & rabbitmq config) so image pullback etc is not an issue. Still troubleshooting to figure out is anything is blocked by the firewall as part of K8s setup of the pods. Thanks!!

**Comment by dhodyrahmad** [comment]
Hi, I'm facing the same problem and I'm sure the resource enough. There is any workaround about this?

**Comment by dsever** [comment]
Hi sorry, finally I have some time to debug it. But in your configuration I don't see that you specified `database: mysql` , while pgsql is default

**Comment by eatasaur** [comment]
Hi,

I'm also facing this issue.
When this happens, pods are being created on the cluster, but when I issue `helm uninstall defectdojo`, the initializer pod won't terminate.

I would really appreciate if the issue can be addressed. @dsever, you have mentioned that `database: mysql` wasn't specified. Can you please expand on what does this mean? I'm very new to DefectDojo as a whole.

Thanks!

**Comment by dsever** [comment]
Can you describe scenario you want to have (redis, mysql, pg, rabbit or what), then I will provide you proper  command?

**Comment by meytrix183** [comment]
@sprathod369 is it your first installation? Asking because I had issues when re-installing without running 

`kubectl delete secrets defectdojo defectdojo-redis-specific defectdojo-rabbitmq-specific defectdojo-postgresql-specific defectdojo-mysql-specific 
kubectl delete serviceAccount defectdojo
kubectl delete pvc data-defectdojo-rabbitmq-0 data-defectdojo-postgresql-0 data-defectdojo-mysql-0
`
I use k3d instead of minikube and it worked alright, also in a vm (way less powerful than yours).

**Comment by sprathod369** [comment]
Thanks @meytrix183 for the inputs.  I've been using the docker-compose setup for a while which is working fine. I've not retested this on minikube since I opened this issue. Closing this for now as I've now moved to Kind (from minikube) so will explore this further on this setup.
