### ISSUE TITLE
WPScan deduplication does not work

### ISSUE THREAD

**Issue by manuel-sommer** [DefectDojo/django-DefectDojo#7039]
**Summary:**
WpScan duplicates are not removed eventhough deduplication is active.

**Bug description**
Deduplication is not working for WPScan

**Steps to reproduce**
1. Activate deduplication on DefectDojo
2. Use WPScan to scan a vulnerable Wordpress page and upload the results multiple times to the same engagement. 
3. Findings are not deduplicated.

**Expected behavior**
Findings are deduplicated.

**Deployment method (select with an X)**
 Docker Compose

**Environment information**
Operating System: Ubuntu 18.04
DefectDojo version v. 2.13.1

**Comment by quirinziessler** [comment]
Bug also exists at v2.15.1

**Comment by quirinziessler** [comment]
Solution:
https://github.com/DefectDojo/django-DefectDojo/pull/7042

**Comment by quirinziessler** [comment]
Fix: https://github.com/DefectDojo/django-DefectDojo/pull/7043
