### ISSUE TITLE
Burp Dastardly scan

### ISSUE THREAD

**Issue by iman4000** [DefectDojo/django-DefectDojo#7045]
**Burp Dastardly scan**

Dastardly is a free, lightweight [web application security](https://portswigger.net/burp/application-security-testing) scanner for your CI/CD pipeline. It is designed specifically for web developers, and checks your application for seven security issues that are likely to interest you during software development. Dastardly is based on the same scanner as Burp Suite (Burp Scanner).  

**Sample File**
Dastardly scan results are available as a JUnit XML file when a scan is complete.

**Comment by Stamka** [comment]
wait too:)

**Comment by damiencarol** [comment]
I took a look, it produce JUnit XML files. This choice is weird. They could have choose a more security oriented format like SARIF.

**Comment by iman4000** [comment]
I don't think they changed it because burp suit had XML format before. I think I saw some JUnit parsers in defectdojo for other scans. can you reuse it for a burp suit?

**Comment by manuel-sommer** [comment]
Hi @iman4000 ,

if you provide an output sample file, I can help you with a PR.

**Comment by manuel-sommer** [comment]
Reminder @Stamka and @iman4000,
could you provide a sample out?

**Comment by mikesindieiev** [comment]
Hello @manuel-sommer 
Here is the output of the scan that was run against "https://ginandjuice.shop"

[dastardly.xml.zip](https://github.com/DefectDojo/django-DefectDojo/files/14210998/dastardly.xml.zip)

**Comment by manuel-sommer** [comment]
Could you please close this issue @mtesauro ?
