### ISSUE TITLE
Setup New Demo on Heroku

### ISSUE THREAD

**Issue by devGregA** [DefectDojo/django-DefectDojo#705]
Please use the following template when submitting issues:

### Issue Type 
- [ ] Bug
- [ X ] Enhancement

### Operating System 
Please include the version number (ex: Ubuntu 16.04)

### Install

- [ ] setup.bash
- [ ] docker

**Comment by aaronweaver** [comment]
Complete: https://defectdojo.herokuapp.com/

**Comment by micksmix** [comment]
@aaronweaver  - Could you share your Heroku `Procfile` or the steps you used to deploy this on Heroku, so other users can spin up their own Heroku instances of DefectDojo?

**Comment by aaronweaver** [comment]
@micksmix I'm using the docker container to run on Heroku. I'm close to completing the PR and can update once it's pushed out.

**Comment by arkwrn** [comment]
> @aaronweaver - Could you share your Heroku `Procfile` or the steps you used to deploy this on Heroku, so other users can spin up their own Heroku instances of DefectDojo?

is there any update how can we do dojo deployment on our own heroku @aaronweaver ?
thank you.
