### ISSUE TITLE
Embedded error 404 for "tests" pages and "login banner" configuration

### ISSUE THREAD

**Issue by jimmy31120** [DefectDojo/django-DefectDojo#7069]
Hello,

I encounter an issue with my defectdojo instance (2.14.1) running with Helm chart and Gitlab SSO enabled.

When I am trying to go on my the detail of a test page. I have a 404 error page displayed inside my DefectDojo UI.
Also, **the same error** is happening when trying to configure the login page (https://urldefectdojo/configure_banner) ??

1. Go to DD URL
2. Click on 'Engagement'
3. Select any engagement displayed
4. In the "tests" part, clic on the title
5. Error occurs (see screenshot below)

**Expected behavior**
Expected a report/details about the test ?

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [ X] Kubernetes (Helm Chart)
- [ ] GoDojo

**Screenshots**

![image](https://user-images.githubusercontent.com/46381751/199509626-ce518265-fa37-4106-b75b-4dc7f836e45e.png)

Logs on my pods do not seems to have any visible issue and I am able to navigate freely in the rest of Defectdojo app.

Thank you for your help !

**Comment by Maffooch** [comment]
Hi @jimmy31120 
I have seen this issue on the demo site, but have not been able to reproduce on any other instance. The issue with the demo site was the lack of the login banner object in the database. The demo site loads the sample data (which does not have a sample data object) and then we load this file on top of that.

I believe loading that fixture will help in your case as well 
https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/fixtures/initial_banner_conf.json

**Comment by jimmy31120** [comment]
Hello Maffooch,
Many thanks for your reply and sorry for delay.

After loading the fixture, banner configuration page works now.

However the issue still persist for all "tests" pages.
After enabling uWSGI debug mode and go again on the faulty page, my browser display now this error.

![image](https://user-images.githubusercontent.com/46381751/201893391-aec4820b-03a8-4a9c-b0c7-280e922ef66d.png)

![image](https://user-images.githubusercontent.com/46381751/201893446-00668c69-513d-4ff4-8be9-ca70fdf38835.png)

For information, I use DefectDojo in version 2.14.1

Is a known bug ? Should I upgrade ?

Thank you again for your help

**Comment by kembox** [comment]
I got the same thing. 2.16.2 Kubernetes setup ( mysql db - redis celery ). 
Can reproduce by importing new scan results. The import process itself finished successfully but tests was never found. 

```
[17/Nov/2022 23:35:36] DEBUG [dojo.notifications.helper:138] Rendering from the template notifications/scan_added.tpl
[17/Nov/2022 23:35:36] DEBUG [dojo.importers.importer.importer:358] IMPORT_SCAN: Updating Test progress
[17/Nov/2022 23:35:36] DEBUG [dojo.decorators:32] dojo_async_task <@task: dojo.importers.utils.update_test_progress of dojo at 0x7fef44811970>: no current user, running task in the background
[17/Nov/2022 23:35:36] DEBUG [dojo.importers.importer.importer:361] IMPORT_SCAN: Done
[Thu Nov 17 23:35:35 2022] POST /engagement/33/import_scan_results => generated 0 bytes in 529 msecs (HTTP/1.1 302) 8 headers in 426 bytes (1 switches on core 0)
[17/Nov/2022 23:35:36] WARNING [django.request:224] Not Found: /test/39
```
Please help to check

**Comment by kembox** [comment]
I've just learned that "django-watson search engine require one or more MyISAM tables", thus my mysql setup was wrong. Switching to an instance that support MyISAM solved my issue with 404 test pages. Sorry for wrong alarm.

**Comment by Ersharma1** [comment]
@jimmy31120 is this issue solved 
I am also seeing 404 for test pages and I am using postgresql for database

**Comment by manuel-sommer** [comment]
I guess this can be closed @mtesauro

**Comment by mtesauro** [comment]
Closed as stale
