### ISSUE TITLE
sslabs-cli import not working

### ISSUE THREAD

**Issue by Horst88** [DefectDojo/django-DefectDojo#708]
Please use the following template when submitting issues:

### Issue Type 
- [ x] Bug
- [ ] Enhancement

### Description
Import of ssllabs-cli json file issues error and does not work

### Operating System 
Please include the version number (ex: Ubuntu 16.04)
Ubuntu 18.04 LTS
### Install

- [x ] setup.bash
- [ ] docker

### DefectDojo Version
1.5.2

### Steps to Reproduce
Create DefectDojo product
Click Findings/Import scan/result
Select Scan Type SSL Labs Scan
Select File
Click upload
-> Error - See screenshot

### Sample Scan File (if applicable)
created with: ./ssllabs-scan-v3 https://www.defectdojo.org/ >www-defectdojo-org.json
[www-defectdojo-org.json.txt](https://github.com/DefectDojo/django-DefectDojo/files/2293644/www-defectdojo-org.json.txt)

### Screenshots (optional)
![defect-dojo-import-ssl-error](https://user-images.githubusercontent.com/32541498/44207856-4ff59c80-a167-11e8-876f-cea588b73088.png)

### Console Logs (optional)
[defect-dojo-import-ssl-error.txt](https://github.com/DefectDojo/django-DefectDojo/files/2293638/defect-dojo-import-ssl-error.txt)

**Comment by Thetides** [comment]
Working on a PR for this. Seems the parser was set to handle a response from version 2 of ssllabs API and doesn't handle missing fields very well.

**Comment by devGregA** [comment]
Awesome! Thanks Luke!

Greg Anderson
Member of the Board
DefectDojo Project Leader
greg.anderson@owasp.org


*Consider giving back, and supporting the open source community by becoming
a member <https://www.owasp.org/index.php/Membership> or making a donation
<https://www.owasp.org/index.php/Donate> today! *

*Join us at AppSec USA 2018 <https://2018.appsecusa.org/> 8-12 October in
San Jose, CA!*

**Comment by aaronweaver** [comment]
I actually had a fix for this in my repo, which I just pushed to dev. Feel free to review.
