### ISSUE TITLE
Import report whispers Error

### ISSUE THREAD

**Issue by rafaelsilvaaa10** [DefectDojo/django-DefectDojo#7097]
Hello there, 

I saw that now whispers is compatible with defectDojo.

I'm trying to import a report to it and I'm getting an error.

I took the example [unitTest](https://raw.githubusercontent.com/DefectDojo/django-DefectDojo/master/unittests/scans/whispers/whispers_many_vul.json) report: 

`[{"key": "01_static_password", "value": "hardcoded0", "file": "src/config.yml", "line": 12, "rule_id": "password", "message": "Password ", "severity": "CRITICAL"}, {"key": "02_static_passwords", "value": "Hardcoded1", "file": "src/config.yml", "line": 14, "rule_id": "password", "message": "Password", "severity": "CRITICAL"}, {"key": "02_static_passwords", "value": "hardCoded2", "file": "src/config.yml", "line": 15, "rule_id": "password", "message": "Password", "severity": "CRITICAL"}, {"key": "02_static_passwords", "value": "haRdcOded3", "file ": "src/config.yml", "line": 16, "rule_id": "password", "message": "Password", "severity": "CRITICAL"}, {"key": "password", "value": "hardcodEd", "file": "src/config.yml", "line": 19, "rule_id": "password", "message": "Password", "severity": "CRITICAL"} ]`.  

The error I get is:

```
ERROR [dojo.engagement.views:683] Tried to update field dojo.Finding.references with a model instance, <Endpoint: https://cwe.mitre.org/data/definitions/798.html>. Use a value compatible with TextField.
Traceback (most recent call last):
```

Need to do something additional to resolve it?

**Comment by CarlosElicabe** [comment]
I have the same issue. This is solved?

**Comment by manuel-sommer** [comment]
PR was merged, please close this issue @mtesauro
