### ISSUE TITLE
 Error: failed to download "helm-charts/defectdojo"

### ISSUE THREAD

**Issue by John-Levi0909** [DefectDojo/django-DefectDojo#7111]
Hello, I've encountered a problem with my helm deployment of the defect dojo in an Azure cluster. Defect dojo had been running in the cluster for months already and it is only until today that I encountered this problem. Aside from the logs below, I have no starting point for debugging the problem. It looks like the same issue also arises when deploying in AWS.

<img width="703" alt="image" src="https://user-images.githubusercontent.com/117496581/201074349-e983f0ad-6029-4544-a643-b620912d650f.png">

<img width="704" alt="image" src="https://user-images.githubusercontent.com/117496581/201074281-3def830c-26e3-45f5-88eb-470ba7dfe1b1.png">

Is there an existing workaround on this problem? I've been browsing for hours and I might have reached an impasse.

**Comment by dsever** [comment]
What error do you have when executing `helm pull  helm-charts/defectdojo` ?

**Comment by dsever** [comment]
Issue is still there?

**Comment by mtesauro** [comment]
As far as I know, it's no longer an issue based on things being generally quiet here and Slack
