### ISSUE TITLE
Cannot import Prisma JSON scan result file

### ISSUE THREAD

**Issue by gun082544** [DefectDojo/django-DefectDojo#7146]
Hello, I have a question. 
I cannot import Prisma JSON scan result file because it return an error as images. 
I guess, it cannot read “link” key in JSON file. 
How can I do? 

I use latest version DefectDojo and have deployed on Kubernetes Cluster.

Thank you. 

![Screenshot 2565-11-16 at 14 53 23](https://user-images.githubusercontent.com/56395331/202130751-7892e6e6-850e-4e94-b456-8c8fba9ce2dc.png)
![Screenshot 2565-11-16 at 15 00 43](https://user-images.githubusercontent.com/56395331/202130760-8339626d-75fd-4365-8a0d-c7f40a79d09e.png)

**Comment by coheigea** [comment]
Can you attach a sample file that is causing the problem?

**Comment by gun082544** [comment]
[https://github.com/gun082544/prisma-sample-result/blob/main/prisma-result.json](prisma-result.json)

Here it is.

**Comment by coheigea** [comment]
What scan type are you using to parse this file @gun082544  ?

**Comment by gun082544** [comment]
@coheigea I use Twistlock Image Scan type.

**Comment by coheigea** [comment]
Pr submitted: https://github.com/DefectDojo/django-DefectDojo/pull/7159

**Comment by gun082544** [comment]
@coheigea Thank you. 🙏🏻
