### ISSUE TITLE
Deduplication does not work well with edited findings

### ISSUE THREAD

**Issue by Nilix007** [DefectDojo/django-DefectDojo#715]
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description

Currently, findings are deduplicated if they have the same hash code which depends on the title, among other values. [0] This hash code is updated each time the finding is saved to the database. [1]

If a finding's title is edited, the next re-upload of this findings will not be deduplicated anymore. (And the following re-uploads will have the previous re-upload as original)

I had a chat yesterday with @xthk, and we believe that the hash code should be immutable so that re-uploads of findings will be correctly deduplicated even if the original finding has been edited.

@aaronweaver: What are your thoughts about this?

[0] https://github.com/DefectDojo/django-DefectDojo/blob/dev/dojo/models.py#L1044
[1] https://github.com/DefectDojo/django-DefectDojo/blob/dev/dojo/models.py#L1185

**Comment by aaronweaver** [comment]
Hi @Nilix007 - Yes, I agree it should be that way, I think the rules PR changed the save override as it was working in the way you have outlined it.

**Comment by Nilix007** [comment]
Has been fixed by #722
