### ISSUE TITLE
Adding Location and Line Number using CSV Imports

### ISSUE THREAD

**Issue by JohnWickAppSec** [DefectDojo/django-DefectDojo#718]
### Issue Type 
- [X] Enhancement

### Description
When uploading findings using CSV files I cannot get DefectDojo to import Location or Line Number. I tried different column headers in an attempt to get it to automatically populate. Some of the column headers I tried were: URL, Location, Files, File, and Line Number. I can edit the finding after I import findings to manually add the Location and Line Number but I would prefer to be able to import that information automatically from a CSV file. The scan type I am using is Generic Findings Import. 

### Install

- [X] setup.bash
### DefectDojo Version
1.5.2

**Comment by aaronweaver** [comment]
@JohnWickAppSec that won't be a problem to add. Just curious, what scanner findings are you importing?

**Comment by JohnWickAppSec** [comment]
Thank you for responded so quickly! It would be great if you could add that functionality. It would save us a lot of time from manually adding the location and Line Number to each finding. Can you give me any estimate on when it would be added? Since the scanning tool we use is not supported by DefectDojo I was just trying to upload the scan findings in a CSV file using the column headers that are listed in the documentation. 

Another thing I have noticed is that the column header Url does not seem to populate any field in DefectDojo. Url is listed as a supported header in the documentation but I have been unable to see where the information listed in that column header goes in DefectDojo.
