### ISSUE TITLE
Connection Reset by peer (curl http://localhost:8080) : DejectDojo Docker not working

### ISSUE THREAD

**Issue by cicode225** [DefectDojo/django-DefectDojo#7182]
Hello,

I followed the installation step on the documentation
Everything was ok till I tried to access the GUI web application.
It doest not work when I try to access Defectdojo web app
Even when I'm on the server, it does not. I tried with curl http://localhost:8080 and I get Connection Reset by peer

I don't know what to say about the steps to reproduce since I juste followed everything ont the documentation

The host is RHEL 8.3 and firewalld is disabled

Below is the log file
[defectdojo logs.txt](https://github.com/DefectDojo/django-DefectDojo/files/10085458/defectdojo.logs.txt)

**Comment by mtesauro** [comment]
What type of install did you do?  godojo/docker-compose/k8s?

Also, there's a decent guide to installing on CentOS/RHEL at https://github.com/DefectDojo/Community-Contribs/tree/master/CentOS-7-deploy

**Comment by cicode225** [comment]
> What type of install did you do? godojo/docker-compose/k8s?
> 
> Also, there's a decent guide to installing on CentOS/RHEL at https://github.com/DefectDojo/Community-Contribs/tree/master/CentOS-7-deploy

@mtesauro Thank you for you reply
After reading the link you posted, I realized I took somewhat a shortcut.
The computer I installed DejectDojo on is an Air Gapped virtual machine ; so no internet
So here's how I installed it : 
    1. Download all docker required packages (ex : docker-ce )  
    2. Install Docker and Docker Compose for airgapped environment as per docker documentation
    3. Reconfigure docker to run as Rootless (as per docker documentation)
    4. On a separate system, I ran the dc-up.sh and  dc.build.sh so that it can get me all necessary docker images
    5. Moved, using a USB, all images from steps 4 into the airgapped environment
    6. Load all docker images using docker load command
    7. Finally, I simply ran dc-up.sh on the airgapped system

As a result, it worked perfectly the first time. I was able to access DefectDojo web UI. But after a couple of days, the issue started and I could not fix it ; nothing changed in my initial settings though

Here's the guide I followed
https://github.com/DefectDojo/django-DefectDojo/blob/dev/readme-docs/DOCKER.md

**Comment by mtesauro** [comment]
I've talked to people that had restricted environments - not airgapped but no public Internet access.  From my recollection, they had some issues with the docker images - I think they did `docker save` and piped it to gz then used `docker load` with the resulting  file after piping through gunzip. Something like that.

Anyway, as I recall they had issues with the tagging of the containers getting lost in that process though this doesn't sound like your case.

If you can get docker compose up - I'd suggest looking at the output of `docker logs` for the various running containers.  Dojo is pretty good about printing decent logs when there are problems.

**Comment by cicode225** [comment]
> I've talked to people that had restricted environments - not airgapped but no public Internet access. From my recollection, they had some issues with the docker images - I think they did `docker save` and piped it to gz then used `docker load` with the resulting file after piping through gunzip. Something like that.
> 
> Anyway, as I recall they had issues with the tagging of the containers getting lost in that process though this doesn't sound like your case.
> 
> If you can get docker compose up - I'd suggest looking at the output of `docker logs` for the various running containers. Dojo is pretty good about printing decent logs when there are problems.

@mtesauro The logs for each container are for the most exactly that I posted in my first post (see attached file)
Nonetheless, I saw this error : 
   -  in the mysql container the following error : "Got an error reading communication packets"

**Comment by mtesauro** [comment]
Sorry, missed the log file.

Unfortunately, I'm a Posgres user so can't offer much help with MySQL.  Have you asked on #DefectDojo on the OWASP Slack instance?  Details to join are [here](https://github.com/DefectDojo/django-DefectDojo/issues/7182#issuecomment-1329190040) if you're not joined yet.

**Comment by manuel-sommer** [comment]
Hi @mtesauro can we close this issue as stale?
I guess you should ask in the slack channel @cicode225
