### ISSUE TITLE
Languages / Lines of Code Graphic Overflow

### ISSUE THREAD

**Issue by Maffooch** [DefectDojo/django-DefectDojo#7183]
When adding many languages to a given product, the table that pie chart is in does not accommodate the size of the legend very well

![image](https://user-images.githubusercontent.com/46459665/203847448-0695a867-0d79-42e4-8c9f-89f40a7fbc40.png)

**Comment by blakeaowens** [comment]
@Maffooch Introduced a fix here: https://github.com/DefectDojo/django-DefectDojo/pull/7185

**Comment by mtesauro** [comment]
Closed by #7185
