### ISSUE TITLE
Wrong list append when CVE and vulnerability_ids list exists on finding

### ISSUE THREAD

**Issue by appsec-igm-sbf** [DefectDojo/django-DefectDojo#7187]
https://github.com/DefectDojo/django-DefectDojo/blob/2e129c3538f95bb457e8397618de8ea21a7edc00/dojo/tools/generic/parser.py#L78

As vulnerability_ids field is a list(array), the "extend" function must be used instead "append".

**Comment by manuel-sommer** [comment]
To me this looks fine. Also tested [this](https://github.com/DefectDojo/django-DefectDojo/blob/master/unittests/scans/generic/generic_report4.json) report and it was parsed right in DefectDojo.

You can probably close this @mtesauro
