### ISSUE TITLE
DefectDojo social-authentication with Gitlab

### ISSUE THREAD

**Issue by Yuan-Yubin** [DefectDojo/django-DefectDojo#7216]
I want to use Gitlab as a OAuth2 provider and I followed documention but it didn't work.

In the documention I need to edit the settings with the following information:
DD_SOCIAL_AUTH_GITLAB_KEY=(str, 'xxxxxxxxxxxx'),
DD_SOCIAL_AUTH_GITLAB_SECRET=(str, 'xxxxxxxxxxxx'),
DD_SOCIAL_AUTH_GITLAB_API_URL=(str, 'https://xx.xxx.xxx.xx'),
DD_SOCIAL_AUTH_GITLAB_OAUTH2_ENABLED = True
*https://documentation.defectdojo.com/integrations/social-authentication/#gitlab

I also read the documention of configuration, environment variables in my local_settings.py must have no DD_ prefix. So I edit the settings like this but it didn't work:
SOCIAL_AUTH_GITLAB_KEY = 'xxxxxxxxxxxx'
SOCIAL_AUTH_GITLAB_SECRET = 'xxxxxxxxxxxx'
SOCIAL_AUTH_GITLAB_API_URL= 'https://xx.xxx.xxx.xx'
SOCIAL_AUTH_GITLAB_OAUTH2_ENABLED = True
*https://documentation.defectdojo.com/getting_started/configuration/

When I read the code of DefectDojo, I found that in the /dojo/settings/settings.dist.py , the variable is GITLAB_OAUTH2_ENABLED, not SOCIAL_AUTH_GITLAB_OAUTH2_ENABLED.

So I edit the settings like this and restart DefectDojo, I finally see a Login with Gitlab button on the login page:
SOCIAL_AUTH_GITLAB_KEY = 'xxxxxxxxxxxx'
SOCIAL_AUTH_GITLAB_SECRET = 'xxxxxxxxxxxx'
SOCIAL_AUTH_GITLAB_API_URL = 'https://xx.xxx.xxx.xx'
GITLAB_OAUTH2_ENABLED = True

I think it is necessary to write the documention more clearly or name variables uniformly :)

**Comment by manuel-sommer** [comment]
Hi @Yuan-Yubin,

were you successful? And if yes, could you please make a PR to update the docs?

**Comment by manuel-sommer** [comment]
Do you also have an answer on this: https://github.com/DefectDojo/django-DefectDojo/issues/9084 ?

**Comment by wywerne** [comment]
> Do you also have an answer on this: #9084 ?

No...

**Comment by wywerne** [comment]
You can add this values in docker-compose.yml 

    uwsgi:
      image: defectdojo/defectdojo-django
      environment:
        DD_DEBUG: "true"
        ***
        DD_SOCIAL_AUTH_GITLAB_KEY: "****"
        DD_SOCIAL_AUTH_GITLAB_SECRET: "****"
        DD_SOCIAL_AUTH_GITLAB_API_URL: "https://gitlib.domain.ext"
        DD_SOCIAL_AUTH_GITLAB_OAUTH2_ENABLED: "true"

**Comment by manuel-sommer** [comment]
@Yuan-Yubin , did this information from @wywerne help you to fix the issue?
You can also take a look here https://defectdojo.github.io/django-DefectDojo/integrations/social-authentication/#gitlab

I guess this can be closed @mtesauro
