### ISSUE TITLE
Grype's Report Upload Issue (v. 2.16.2)

### ISSUE THREAD

**Issue by mohammadkamrani** [DefectDojo/django-DefectDojo#7229]
Once I want to upload Grype report on DefectDojo, I get an error the same as below:
"An exception error occurred during the report import:local variable 'file_path' referenced before assignment"

![2022-12-04_11-01-16](https://user-images.githubusercontent.com/53512886/205479519-2d3ddd17-4b82-4ac2-af40-c17ece754258.jpg)

I don't get the error on v. 2.7.1

**Comment by coheigea** [comment]
Can you attach a sample scan file (with anything sensitive removed)?

**Comment by damiencarol** [comment]
As @coheigea asked, it's hard to understand what's going on without a report that fail (even obfuscated) or a stack trace.
We are using template for issue for this reason.

**Comment by mohammadkamrani** [comment]
Yes, here you are
I had to change JSON to txt due to upload limitations here.
[dojo.txt](https://github.com/DefectDojo/django-DefectDojo/files/10148449/dojo.txt)

**Comment by damiencarol** [comment]
Taking a look tomorrow.

**Comment by coheigea** [comment]
The issue can be closed as the PR is merged
