### ISSUE TITLE
Login and authenticate Dojo through Gitlab

### ISSUE THREAD

**Issue by Yuan-Yubin** [DefectDojo/django-DefectDojo#7246]
I want to use Gitlab as a OAuth2 provider, and I followed the documention. 
But when I click Login with Gitlab, my page displays error message:
![0880c4c80710d9bfbb09](https://user-images.githubusercontent.com/74064038/206079010-bf97e667-8cbe-4deb-9c1e-ac51e6e8214f.png)

Error is :
Authentication failed: HTTPSConnectionPool(host='xx.xxx.xxx.xx', port=443): Max retries exceeded with url: /oauth/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')))

*The host here is my gitlab host.

I refer to the configuration here: https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/DOCKER.md#run-with-docker-using-https, however, the problem has not been solved.

How can I solve this problem?

**Deployment method** 
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Centos 7
 - DefectDojo version (see footer) or commit message: 2.16.2

**Comment by mtesauro** [comment]
FWIW, I read the error message you provided to suggest that the Gitlab instances didn't have a valid TLS cert.

Does the Gitlab host have a valid TLS cert?  Is it signed by an internal CA?  Is that internal CA trusted by DefectDojo's nginx and uwsgi container?

As far as setting up TLS for DefectDojo, you can always bind mount in a valid TLS cert for Nginx to use a 'real' certificate.  Here's [an example](https://github.com/DefectDojo/Community-Contribs/blob/master/CentOS-7-deploy/dojo/docker-compose.yml#L18) of that way of solving the DefectDojo TLS issue though there's [other methods](https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/DOCKER.md#run-with-docker-compose-using-https) that also work.

**Comment by Yuan-Yubin** [comment]
The Gitlab host have a selfsigned certificate.
I am trying to import a set of certificates into dojo.
I have some doubts when reading this documention. (https://github.com/DefectDojo/Community-Contribs/blob/master/CentOS-7-deploy/dojo/docker-compose.yml)

Do I need to add volumes settings  to my docker-compose.yml?
volumes:
      - /opt/dojo/certs:/etc/nginx/certs
      - /opt/dojo/nginx/nginx.conf:/etc/nginx/nginx.conf

Like this?
version: '3.8'
services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    image: "defectdojo/defectdojo-nginx:${NGINX_VERSION:-latest}"
    profiles:
      - mysql-rabbitmq
      - mysql-redis
      - postgres-rabbitmq
      - postgres-redis
    depends_on:
      - uwsgi
    environment:
      NGINX_METRICS_ENABLED: "${NGINX_METRICS_ENABLED:-false}"
    volumes:
      - defectdojo_media:/usr/share/nginx/html/media
      - /opt/dojo/certs:/etc/nginx/certs
      - /opt/dojo/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - target: 8080
        published: ${DD_PORT:-8080}
        protocol: tcp
        mode: host
      - target: 8443
        published: ${DD_TLS_PORT:-8443}
        protocol: tcp
        mode: host

The Dockerfile.nginx is this:

# code: language=Dockerfile

# The code for the build image should be identical with the code in
# Dockerfile.django to use the caching mechanism of Docker.

# Ref: https://devguide.python.org/#branchstatus
FROM python:3.8.15-slim-bullseye@sha256:16c6f3c044b248c69bd1e20d4c0b04af6b3f16ef8a7e0fb5ff9f527f30180289 as base
FROM base as build
WORKDIR /app
RUN \
  apt-get -y update && \
  apt-get -y install --no-install-recommends \
    gcc \
    build-essential \
    dnsutils \
    default-mysql-client \
    libmariadb-dev-compat \
    postgresql-client \
    xmlsec1 \
    git \
    uuid-runtime \
    # libcurl4-openssl-dev is required for installing pycurl python package
    libcurl4-openssl-dev \
    && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists && \
  true
COPY requirements.txt ./
# CPUCOUNT=1 is needed, otherwise the wheel for uwsgi won't always be build succesfully
# https://github.com/unbit/uwsgi/issues/1318#issuecomment-542238096
RUN CPUCOUNT=1 pip3 wheel --wheel-dir=/tmp/wheels -r ./requirements.txt


FROM build AS collectstatic

USER root
ENV \
  # This will point yarn to whatever version of node you decide to use
  # due to the use of nodejs instead of node name in some distros
  node="nodejs"
RUN \
  apt-get -y update && \
  apt-get -y install --no-install-recommends apt-transport-https ca-certificates curl wget gnupg && \
  curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add --no-tty - && \
  echo 'deb https://deb.nodesource.com/node_14.x bullseye main' > /etc/apt/sources.list.d/nodesource.list && \
  echo 'deb-src https://deb.nodesource.com/node_14.x bullseye main' >> /etc/apt/sources.list.d/nodesource.list && \
  apt-get update -y -o Dir::Etc::sourcelist="sources.list.d/nodesource.list" \
  -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0" && \
  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
  wget https://github.com/yarnpkg/yarn/releases/download/v1.22.10/yarn_1.22.10_all.deb && \
  dpkg -i yarn_1.22.10_all.deb && \
  echo "$(yarn --version)" && \
  apt-get -y install --no-install-recommends nodejs && \
  echo "$(node --version)" && \
  apt-get clean && \
  rm yarn_1.22.10_all.deb && \
  rm -rf /var/lib/apt/lists && \
  true

RUN pip3 install \
	--no-cache-dir \
	--no-index \
  --find-links=/tmp/wheels \
	-r ./requirements.txt

COPY components/ ./components/
RUN \
  cd components && \
  yarn

COPY manage.py ./
COPY dojo/ ./dojo/

RUN env DD_SECRET_KEY='.' python3 manage.py collectstatic --noinput && true

FROM nginx:1.23.2-alpine@sha256:2452715dd322b3273419652b7721b64aa60305f606ef7a674ae28b6f12d155a3
ARG uid=1001
ARG appuser=defectdojo
COPY --from=collectstatic /app/static/ /usr/share/nginx/html/static/
COPY wsgi_params nginx/nginx.conf nginx/nginx_TLS.conf /etc/nginx/
COPY docker/entrypoint-nginx.sh /
RUN \
  apk add --no-cache openssl && \
  chmod -R g=u /var/cache/nginx && \
  mkdir /var/run/defectdojo && \
  chmod -R g=u /var/run/defectdojo && \
  mkdir -p /etc/nginx/ssl && \
  chmod -R g=u /etc/nginx && \
  true
ENV \
  DD_UWSGI_PASS="uwsgi_server" \
  DD_UWSGI_HOST="uwsgi" \
  DD_UWSGI_PORT="3031" \
  GENERATE_TLS_CERTIFICATE="false" \
  USE_TLS="false" \
  NGINX_METRICS_ENABLED="false" \
  METRICS_HTTP_AUTH_USER="" \
  METRICS_HTTP_AUTH_PASSWORD=""
USER ${uid}
EXPOSE 8080
ENTRYPOINT ["/entrypoint-nginx.sh"]

**Comment by Yuan-Yubin** [comment]
I also have some doubts when reading this documention. (https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/DOCKER.md#run-with-docker-compose-using-https)
![0880c4c80710db8a8909](https://user-images.githubusercontent.com/74064038/206432082-50c818aa-d78f-41c1-a769-527e7c6b6b67.png)
Where do I need to copy my secrets into? The DefectDojo's nginx or uwsgi container? 
I just try to copy my secrets into the corresponding path in the DefectDojo's nginx container.
But after I set the GENERATE_TLS_CERTIFICATE != True in the docker-compose.override.https.yml, and I run defectDojo with the command line, the DefectDojo's nginx container cannot be started.

Looking forward to your reply~!!!

**Comment by Yuan-Yubin** [comment]
![0880c4c80710dce7e70f](https://user-images.githubusercontent.com/74064038/207221654-85b994bf-0dca-471e-a1a3-80154749790f.png)
I changed docker-compose.override.yml to the above form, but the problem still exists.
PLEASE!

**Comment by Yuan-Yubin** [comment]
By the way, the nginx.cert and nginx.key in the nginx container are imported by me now, but the error problem has not been solved.
HELP! Please HELP!

**Comment by Yuan-Yubin** [comment]
Set VERIFY_SSL = False in the local_settings.py
