### ISSUE TITLE
No metrics after installation 

### ISSUE THREAD

**Issue by AdrienGuillerme** [DefectDojo/django-DefectDojo#725]
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description

I tried to install Defect-dojo and i had many troubles doing it. I had to install some python packages by myself in order to complete the installation.
I finally managed to run the server, create a product, an engagement, a test and added some scans from Checkmarx and Nessus.
I have many open findings but nothing appears in the metrics. Do I miss something?

### Operating System 

Ubuntu 18.04

### Install

- [x] setup.bash
- [ ] docker

### DefectDojo Version

1.5.2

### Steps to Reproduce

I tried [Getting Started Instructions](https://defectdojo.readthedocs.io/en/latest/getting-started.html#install-script)
and [Installation Guide](https://github.com/DefectDojo/django-DefectDojo/wiki/DefectDojo-Installation-Guide-Ubuntu-Desktop-16.04.2)

Running `./setup.bash` I have the error : `Could not find a version that satisfies the requirement Django==1.11.11 (from DefectDojo==1.5.2)`
and then this kind of errors : `ImportError : No module named celery`
This is why I imported packages by myself.

**Comment by aaronweaver** [comment]
@AdrienGuillerme check to make sure you are using Celery 4 or greater. For metrics, make sure you have set the findings to active and verified.
