### ISSUE TITLE
Jira v9 integration issue on v2.17.0

### ISSUE THREAD

**Issue by frost9i** [DefectDojo/django-DefectDojo#7253]
🐞 **Related:**
[Jira 9.0+ is not supported #6963](https://github.com/DefectDojo/django-DefectDojo/issues/6963)

👀 **Description:**
Jira v9 integration issue happens at step of performing Product configuration.
Jira v9.2.0 in use.

🦶 **Steps to reproduce:**
1) Enable Jira in settings
2) Add Jira configuration
3) Configure product to use this Jira instance and press apply

💉 **Stacktrace:**
```
[08/Dec/2022 10:26:10]
ERROR [dojo.jira_link.helper:1399] 'JIRA' object has no attribute 'createmeta_issuetypes'
Traceback (most recent call last):
  File "/app/dojo/jira_link/helper.py", line 1380, in process_jira_project_form
    if not is_jira_project_valid(jira_project):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/jira_link/helper.py", line 1049, in is_jira_project_valid
    get_issuetype_fields(jira, jira_project.project_key, jira_project.jira_instance.default_issue_type)
  File "/app/dojo/jira_link/helper.py", line 1011, in get_issuetype_fields
    issuetypes = jira.createmeta_issuetypes(project_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'JIRA' object has no attribute 'createmeta_issuetypes'
```

🎈**Assumption:**
Jira library wasn't updated.

**Comment by valentijnscholten** [comment]
What is the purpose of this ticket? Is there anything not covered already by #6963?

**Comment by frost9i** [comment]
Yes, it didn't get covered. Integration is still broken.

**Comment by valentijnscholten** [comment]
That's what #6963 is for.

**Comment by frost9i** [comment]
You're right, additional context in #6963 describes it.
Sorry for adding noise. This issue can be discarded.
