### ISSUE TITLE
Issues with Duplicates 

### ISSUE THREAD

**Issue by JohnWickAppSec** [DefectDojo/django-DefectDojo#728]
### Issue Type 
- [X] Bug

### Description
When importing findings from CSV I am trying to mark findings as duplicates. According to the documentation Duplicate is a field that can be imported. However when I set the field to True in the CSV it is not pushing that value to the uploaded finding in DefectDojo. Is this working as intended or a bug?

Also, I have been testing and I cannot seem to get DefectDojo to Deduplicate findings. According to the System Settings when the Deduplicate findings box is checked it should automatically deduplicate findings that share a URL and have the same CWE or title. I have set these fields to be the same and DefectDojo has still not marked any of the findings as duplicates.   

### Install

- [X] setup.bash

### DefectDojo Version
1.5.2

**Comment by aaronweaver** [comment]
Hi @JohnWickAppSec for dedupe, ensure that you have Celery running as well and/or you can dedupe in "realtime" by setting the user in the user settings to "blocking" mode. I don't believe the field duplicate in CSV does anything. I'll check the docs and update to reflect the behavior.

**Comment by JohnWickAppSec** [comment]
We are using Fortify as our scanning tool.

**Comment by JohnWickAppSec** [comment]
Changing the user setting to blocking mode fixed the issue. Thank you for your response.
