### ISSUE TITLE
Upgrade to 2.17 fails because of django-auditlog new column

### ISSUE THREAD

**Issue by rwanauo** [DefectDojo/django-DefectDojo#7283]
(Tried getting to slack, but the links were all dead.)

Short version - 
The lastest version of django-auditlog adds a new column to the logentry.

https://github.com/jazzband/django-auditlog/blob/master/auditlog/migrations/0011_logentry_serialized_data.py

```
        migrations.AddField(
            model_name="logentry",
            name="serialized_data",
            field=models.JSONField(null=True),
        ),
```

Which runs 
`ALTER TABLE `auditlog_logentry` ADD COLUMN `serialized_data` JSON NULL`

On databases with significant logs, this takes a long long time, and a ton of space. In our case, our 400 gig db with 200 gig free run this migration for about 3 hours, ate the 200 gig free, then died and rolled back.

At this point, I think the only path to upgrading is to remove all the audit logs, or a ton of old ones at leats, and try again. 

DB is MySQL 5.7.38.  

I know in MSSQL, adding a null column without a default would take a second and not really have tried changing every row. Maybe there is some MySQL setting we have messed up (I expect not.)

**Comment by manuel-sommer** [comment]
Is this issue still open? Then, please try again in the slack channel. (OWASP Slack --> DefectDojo)
You can close this @mtesauro
