### ISSUE TITLE
need support for sesu linux

### ISSUE THREAD

**Issue by dkommi** [DefectDojo/django-DefectDojo#729]
Please use the following template when submitting issues:

## Unable to install/deploy DefectDojo in Sesu linux 12. we are seeing below error.

(dojo) *********************:/opt/dojo/django-DefectDojo # ./setup.bash

Welcome to DefectDojo! This is a quick script to get you up and running.

Select database type: 0.) SQLite, 1.) MySQL or 2.) Postgres: 1
Setting up database

NEED SUDO PRIVILEGES FOR NEXT STEPS!

Attempting to install required packages...

which: no yum in (/opt/dojo/bin:/usr/local/rvm/gems/ruby-2.3.0/bin:/usr/local/rvm/gems/ruby-2.3.0@global/bin:/usr/local/rvm/rubies/ruby-2.3.0/bin:/sbin:/usr/sbin:/usr/local/sbin:/root/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/usr/local/rvm/bin)
which: no apt-get in (/opt/dojo/bin:/usr/local/rvm/gems/ruby-2.3.0/bin:/usr/local/rvm/gems/ruby-2.3.0@global/bin:/usr/local/rvm/rubies/ruby-2.3.0/bin:/sbin:/usr/sbin:/usr/local/sbin:/root/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/usr/local/rvm/bin)
which: no brew in (/opt/dojo/bin:/usr/local/rvm/gems/ruby-2.3.0/bin:/usr/local/rvm/gems/ruby-2.3.0@global/bin:/usr/local/rvm/rubies/ruby-2.3.0/bin:/sbin:/usr/sbin:/usr/local/sbin:/root/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/usr/local/rvm/bin)
ERROR! OS not supported. Try the Vagrant option.

### Issue Type 
- [X ] Enhancement

### Description
Is it possible to provide the file dojo-shared-resources.sh for sesu linux. 

### Operating System 
(dojo) OHCINXDEFECTDOJOP1:/opt/dojo/django-DefectDojo/entrypoint_scripts/common # uname -a
Linux OHCINXDEFECTDOJOP1 3.12.28-4-default #1 SMP Thu Sep 25 17:02:34 UTC 2014 (9879bd4) x86_64 x86_64 x86_64 GNU/Linux

### Install

- [ X] setup.bash

**Comment by dkommi** [comment]
Thank you aaronweaver , we did some modifications in script and installed the required packages. now we am unable to connect to the mysql server. 

MySQL host:***************************
MySQL port: XXXXXX
MySQL user (should already exist): mysql
Password for user:
Database name (should NOT exist): db_information_schema
Enter password:
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
mysqladmin: connect to server at '*************************' failed
error: 'Host '************************.****.***' is not allowed to connect to this MariaDB server'
Error! Failed to create database db_information_schema. Check your credentials.

**Comment by aaronweaver** [comment]
Hi @dkommi - I'd it sounds like either the database server isn't up or that the root password wasn't entered correctly. Also, for the database name I'd recommend using defectdojo or dojodb, not db_information_schema.
