### ISSUE TITLE
Upload fails due to missing profile information

### ISSUE THREAD

**Issue by wurstbrot** [DefectDojo/django-DefectDojo#732]
Please use the following template when submitting issues:

### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description
Uploading of reports via API fails due to missing contact information.

Recommendation: Allow missing values in the users profile

### Operating System 
docker-DefectDojo

### Install
- [x] docker

### DefectDojo Version
1.5.2

### Steps to Reproduce
Start docker.
export API_KEY
Create a product and call:
~/git/defectdojo_api/examples$ python dojo_ci_cd.py --product=1 --file "$(pwd)/scan-results/arachni/172.17.0.1-2018-08-24-15_34_36.2.json" --scanner="Arachni Scan"  --host=http://localhost:8000 --api_key=$DOJO_API_KEY --user=admin --critical=0 --high=0

Uploading Arachni Scan scan: /home/tpagel/git/defectdojo_api/examples/scan-results/arachni/172.17.0.1-2018-08-24-15_34_36.2.json

Upload failed: Detailed error message: {"error_message": "User has no usercontactinfo.", "traceback": "Traceback (most recent call last):\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 227, in wrapper\n    response = callback(request, *args, **kwargs)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 467, in dispatch_list\n    return self.dispatch('list', request, **kwargs)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 499, in dispatch\n    response = method(request, **kwargs)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 1408, in post_list\n    updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))\n\n  File \"/opt/django-DefectDojo/dojo/api.py\", line 1378, in obj_create\n    item.save(dedupe_option=False)\n\n  File \"/opt/django-DefectDojo/dojo/models.py\", line 1191, in save\n    if self.reporter.usercontactinfo.block_execution:\n\n  File \"/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related_descriptors.py\", line 407, in __get__\n    self.related.get_accessor_name()\n\nRelatedObjectDoesNotExist: User has no usercontactinfo.\n"}

**Comment by devGregA** [comment]
This specific bug only occurs when using the root user.
