### ISSUE TITLE
Deduplication tooltip probably misleading

### ISSUE THREAD

**Issue by anantshri** [DefectDojo/django-DefectDojo#7337]
Hi Team,

The System Level setting for Deduplication has a message which suggests that the older findings will be marked as duplicate and not the recent one.
<img width="710" alt="Screenshot 2022-12-30 at 4 46 22 AM" src="https://user-images.githubusercontent.com/236843/210020250-f2f6a778-57c9-4340-afe1-1c909f88d89d.png">

"Dojo marks the less recent finding as a duplicate." <- this is the message

however from my experience its the recent entries that are marked duplicate and not the initial occurrences. 

Can you confirm whats the expected behaviour and if the tooltip is reflecting correct behaviour.

**Comment by manuel-sommer** [comment]
This can be closed @mtesauro
