### ISSUE TITLE
Adding Betterscan.io to "Scan type" on "import scan results" screen

### ISSUE THREAD

**Issue by marcinguy** [DefectDojo/django-DefectDojo#7354]
**Is your feature request related to a problem? Please describe**
Is it possible to add Betterscan.io to "Scan type" on "import scan results" screen. Betterscan produces SARIF, so it can be mapped to it directly I hope. I think users can also find it useful to see Betterscan.io scan type vs generic SARIF type. Can improve usability. Was asked by users about it at Betterscan project, hence write here.

**Describe the solution you'd like**
As a user I would like to see "Scan type" being also Betterscan.io on "import scan results" screen

I can also make a PR for this (if I figure it out)

**Describe alternatives you've considered**
Not having Betterscan.io name there. But not everyone will know that SARIF will also work for Betterscan.

**Additional context**

I mean "Scan type" field on this screen

![image](https://user-images.githubusercontent.com/20355405/210394447-9aa0af1d-86d8-4caf-9b4a-b361eab49e18.png)

With guidance I can open PR for this.

Thanks,

**Comment by marcinguy** [comment]
Made a PR for it. Hope it is fine. Thanks,

**Comment by mtesauro** [comment]
#7398  for reference

**Comment by manuel-sommer** [comment]
@mtesauro I guess we can close this issue.
