### ISSUE TITLE
markdown code-block is not rendering as expected

### ISSUE THREAD

**Issue by df-dev** [DefectDojo/django-DefectDojo#736]
Please use the following template when submitting issues:

### Issue Type 
- [x] Bug

### Description
when using triple-tick or `</>` menu option; code blocks do not render as expected in edit mode and lose all formatting once a save is executed. Tested in both my instance and in the demo app and behaves the same. 

### Operating System 
OS: Ubuntu 18.04 LTS

### Install
- [ ] setup.bash

### DefectDojo Version
v1.5.2

### Steps to Reproduce
Add a code block to any input field when entering a finding. click save and all formatting will be removed; showing only: 

<triple-ticks>
code
<triple-ticks>
```

### Screenshots (optional)
From demo site: 
![dd_md_issues](https://user-images.githubusercontent.com/22565691/45378979-1f651f00-b5bc-11e8-9f0e-c8379882ab50.png)
![dd_md_2](https://user-images.githubusercontent.com/22565691/45378986-2429d300-b5bc-11e8-9430-bd878d612b51.png)

**Comment by aaronweaver** [comment]
It's an inconsistency between the javascript viewer renderer and python markdown display. May need to switch to markdown2 as it looks to be a more "accurate" markdown renderer. https://github.com/trentm/python-markdown2

**Comment by df-dev** [comment]
thank you @aaronweaver; I will give that a try.
