### ISSUE TITLE
Test tags are not updated when using reimport_scan

### ISSUE THREAD

**Issue by gietschess** [DefectDojo/django-DefectDojo#7367]
**Bug description**
When using the reimport_scan api call and updating a test tag value for a existing test its value will not be updated.

**Steps to reproduce**
1. Use reimport_scan to add a test containing any test tag
2. Use reimport_scan again with the same scan and change the test tag value

**Expected behavior**
Test tag value is updated to the new value.

**Deployment method**
- [ ] Docker Compose
- [x] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: [Amazon Linux 2, k8s 1.21]
 - DefectDojo version 2.18.0

**Sample api calls**
```bash
curl -X 'POST' \
  'https://defectdojo.local/api/v2/reimport-scan/' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'minimum_severity=Info' \
  -F 'active=true' \
  -F 'verified=true' \
  -F 'do_not_reactivate=false' \
  -F 'scan_type=Trivy Scan' \
  -F 'file=@alpine312.txt;type=application/json' \
  -F 'product_type_name=container' \
  -F 'product_name=os' \
  -F 'engagement_name=alpine' \
  -F 'test_title=alpine' \
  -F 'auto_create_context=true' \
  -F 'deduplication_on_engagement=true' \
  -F 'push_to_jira=false' \
  -F 'close_old_findings=true' \
  -F 'close_old_findings_product_scope=false' \
  -F 'version=3.12' \
  -F 'service=alpine' \
  -F 'tags=image_tag=3.12' \
  -F 'create_finding_groups_for_all_findings=true'
```
```bash
curl -X 'POST' \
  'https://defectdojo.local/api/v2/reimport-scan/' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'minimum_severity=Info' \
  -F 'active=true' \
  -F 'verified=true' \
  -F 'do_not_reactivate=false' \
  -F 'scan_type=Trivy Scan' \
  -F 'file=@alpine317.txt;type=application/json' \
  -F 'product_type_name=container' \
  -F 'product_name=os' \
  -F 'engagement_name=alpine' \
  -F 'test_title=alpine' \
  -F 'auto_create_context=true' \
  -F 'deduplication_on_engagement=true' \
  -F 'push_to_jira=false' \
  -F 'close_old_findings=true' \
  -F 'close_old_findings_product_scope=false' \
  -F 'version=3.17' \
  -F 'service=alpine' \
  -F 'tags=image_tag=3.17' \
  -F 'create_finding_groups_for_all_findings=true'
```

**Sample scan files**
[alpine312.txt](https://github.com/DefectDojo/django-DefectDojo/files/10350959/alpine312.txt)
[alpine317.txt](https://github.com/DefectDojo/django-DefectDojo/files/10350960/alpine317.txt)

**Screenshots**
![1](https://user-images.githubusercontent.com/49275246/210747080-152a9c97-4644-4e95-ad44-87908de2d1b2.PNG)
![2](https://user-images.githubusercontent.com/49275246/210747082-2ab4831e-fefe-4500-a742-0132dca3efa1.PNG)

**Comment by gietschess** [comment]
why aren't the commited tags used when the test already exists?

reimported existing test: https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/api_v2/serializers.py#L1764
new reimported test (with auto_create_context): https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/api_v2/serializers.py#L1782

**Comment by coheigea** [comment]
PR submitted: https://github.com/DefectDojo/django-DefectDojo/pull/7472
