### ISSUE TITLE
Pulling the image from docker hub fails

### ISSUE THREAD

**Issue by alexppg** [DefectDojo/django-DefectDojo#737]
Please use the following template when submitting issues:

### Issue Type 
- [ X ] Bug
- [ ] Enhancement

### Description
The order shown in the documentation, `docker run -it -p 8000:8000 appsecpipeline/django-defectdojo bash -c "export LOAD_SAMPLE_DATA=True && bash /opt/django-DefectDojo/docker/docker-startup.bash"`, doesn't work.

## If the issue is a bug, please also include the following:
It should work.

### Operating System 
Please include the version number (ex: Ubuntu 16.04)

### Install

- [ ] setup.bash
- [ X] docker

### DefectDojo Version
None

### Steps to Reproduce
Just try to pull the image without a tag. The default tag when doing that is use `latest`, and since there's none, it fails. I guess it can be resolved by just  pushing the `latest` tag.

**Comment by aaronweaver** [comment]
Correct, just pull the version you need. I'll add latest in the next release.

**Comment by devGregA** [comment]
@aaronweaver stop looking at dojo stuff. Enjoy your vacation. Don't make me suspend your access 😉

**Comment by wileycybrotie** [comment]
Can you please give a more verbose response on how you solved this?

**Comment by aaronweaver** [comment]
Latest tag has been added back so you can do latest or pull the particular version you are looking for.
