### ISSUE TITLE
DefectDojo Automatic scan upload with Nessus API

### ISSUE THREAD

**Issue by Anillaerdal** [DefectDojo/django-DefectDojo#7371]
Hi All, 

Iam looking for DefectDojo Automatic scan upload with Nessus API.
Please share me how to get this details

**Comment by manuel-sommer** [comment]
Are you searching for this: https://defectdojo.github.io/django-DefectDojo/integrations/parsers/file/tenable/ ?

This request is not very clear to me. ALso, could you please ask such questions in the slack channel?

Could you close this please @mtesauro ?
