### ISSUE TITLE
Translate for PT_BR

### ISSUE THREAD

**Issue by meetgyn** [DefectDojo/django-DefectDojo#7397]
**Is your feature request related to a problem? Please describe**
A clear and concise description of what the problem is.
Ex: I'm always frustrated when [...]

**Describe the solution you'd like**
Ex: As a < role >, I want < some goal > so that < some reason >.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you have considered.

**Additional context**
Add any other context, screenshots, sketch, code snippet, etc. about the feature request here.

**Comment by fsbano** [comment]
Great ! very good

**Comment by appsec-igm-sbf** [comment]
[pt_BR.po.gz](https://github.com/DefectDojo/django-DefectDojo/files/11012209/pt_BR.po.gz)

**Comment by manuel-sommer** [comment]
Can you close this @mtesauro ?
