### ISSUE TITLE
Nessus reimport mitigating endpoint that still vunerable

### ISSUE THREAD

**Issue by aflima** [DefectDojo/django-DefectDojo#7403]
Nessus reimport mitigating endpoint that still vunerable
When a scan made via nessus is reimported, defectdojo is mitigating an endpoint that is not effectively mitigated and make finding open with all endpoints wrongly mitigated.

**Steps to reproduce**
1. Create an engagment and import .nessus scan result in some test;
2. After import, reupload scan results
[Machine.zip](https://github.com/DefectDojo/django-DefectDojo/files/10392960/Machine.zip)
 the same .nessus file;
3. You will see that for some reason Dojo mitigate some endpoints even using the same file.

**Expected behavior**
Dojo needs to correctly validate which endpoints were mitigated at reimport time.

**Deployment method** *(select with an `X`)*
- [x] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: 
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
 - DefectDojo version v. 2.18.1 ( release mode )

**Sample scan files**
[Machine.zip](https://github.com/DefectDojo/django-DefectDojo/files/10392970/Machine.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/2230195/211824133-3748000d-5d3e-4f11-9cd7-7eaee00bf5c5.png)
![image](https://user-images.githubusercontent.com/2230195/211824347-070b75d5-28e7-4f95-9b52-ae1117604bf4.png)
![image](https://user-images.githubusercontent.com/2230195/211824465-5d0a8ecb-c8f6-4c24-82bd-e317d014e9d0.png)
![image](https://user-images.githubusercontent.com/2230195/211824569-d1b364f8-ac39-4b2f-8f27-f746449d17e4.png)
![image](https://user-images.githubusercontent.com/2230195/211824684-dcc091f1-cbb5-4a36-bdfa-a8fabb2db196.png)
![image](https://user-images.githubusercontent.com/2230195/211824801-1ce82698-cef1-4985-8276-ff0f56056277.png)

**Comment by coheigea** [comment]
I found the bug here: https://github.com/DefectDojo/django-DefectDojo/pull/7416

**Comment by coheigea** [comment]
This can be closed as it's fixed in 2.18.2.

**Comment by sixpacksecurity** [comment]
Doesn't look like it's fixed. Did a fresh clone and ran the steps mentioned above.

Imported Nessus scan (csv)
Re-imported the same nessus scan (csv) within the same engagement and test
Somehow a lot of the findings have been moved to mitigated but ideally there should be no change, right ?

**Comment by aflima** [comment]
> Doesn't look like it's fixed. Did a fresh clone and ran the steps mentioned above.
> 
> Imported Nessus scan (csv) Re-imported the same nessus scan (csv) within the same engagement and test Somehow a lot of the findings have been moved to mitigated but ideally there should be no change, right ?

In my case this fix work, i don't really test csv format because i only use .nessus format.

**Comment by aflima** [comment]
Good morning, @coheigea how are you?
I believe that the mitigation made did not resolve the issue 100%.
Validating with files containing different endpoint numbers, it is possible to validate that by importing the files alternately, the endpoint remains mitigated, even with a vulnerability present.
[MachineAB.zip](https://github.com/DefectDojo/django-DefectDojo/files/10519720/MachineAB.zip)

**Comment by coheigea** [comment]
@aflima Can you detail exactly the steps to follow to reproduce the issue?

**Comment by aflima** [comment]
> @aflima Can you detail exactly the steps to follow to reproduce the issue?

Yes, sorry for the delay
1) Import scan result MachineA.nessus
![image](https://user-images.githubusercontent.com/2230195/216362184-419015c8-5ab2-4d87-bd6f-52d65b63df54.png)
![image](https://user-images.githubusercontent.com/2230195/216362515-529d93f3-d8d9-4efe-a23b-d8dcb54189db.png)
You will see that all vulns have only 1 endpoint active
![image](https://user-images.githubusercontent.com/2230195/216362799-314db330-12d5-4a49-bd86-116b557a59b7.png)

2) reimport using the file MachineB.nessus
![image](https://user-images.githubusercontent.com/2230195/216363020-bbf1b367-3892-4e1f-8a3c-9e667c484ec3.png)
![image](https://user-images.githubusercontent.com/2230195/216363150-c9f93934-2cee-4708-9820-1f5500b3bf7a.png)
You will see that now have 3 endpoints vulnerable in each finding
![image](https://user-images.githubusercontent.com/2230195/216363412-2051068d-2b50-4190-bfd7-f10eb959b348.png)

If you reimport MachineA.nessus and before reimport MachineB.nessus you will see that the endpoints that have to reactive as vulnerable will be present as mitigated:
3) Reupload MachineA.nessus
![image](https://user-images.githubusercontent.com/2230195/216363875-44725063-1bab-427c-ab60-cf30089e77cc.png)
4) Reupload MachineB.nessus
![image](https://user-images.githubusercontent.com/2230195/216364063-49477bf4-6be7-464f-b9de-35ff38ca0a8a.png)

This is wrong because the last uploaded .nessus file show all de endpoints vulnerable. In case of continuous reimport results this will show the view of endpoints mitigated, but this is not true.

**Comment by C0mebreathe** [comment]
Same thing with re-imported csv reports in last dd version, there are plenty of mitigated endpoints that should be active.

**Comment by gulsezim11** [comment]
I also have this issue, in my case I import sonar scan, and then reimport the same results. And all findings are being mitigated, even though they are not closed in the imported results. Did someone solve it?
