### ISSUE TITLE
Blind XSS in Admin Log Overview

### ISSUE THREAD

**Issue by droptableuser** [DefectDojo/django-DefectDojo#742]
### Issue Type 
- [x ] Bug
- [ ] Enhancement

### Description
On a fresh installation of 1.5.2 it is possible to create a blind XSS by setting a users name to an XSS payload e.g.:
```
<script>alert(1);</script>
```
as shown in one of the two screenshots.
The resulting log entry in 
http://localhost:8000/admin/auditlog/logentry/ results in the XSS. shown in the second screenshot
### Operating System 
macOS X 

### Install

- [ ] setup.bash
- [x] docker

### DefectDojo Version
1.5.2

### Steps to Reproduce
1. Create a new user. 
2. New user logs in 
3. User changes (both first and last name fields are effected) name to payload
4. User logs out
5. Admin user logs in, goes to http://localhost:8000/admin/auditlog/logentry/ 
6. XSS

### Screenshots (optional)
![image](https://user-images.githubusercontent.com/924849/45835391-4634fb00-bd0a-11e8-95ee-154193cdf4b8.png)
![image](https://user-images.githubusercontent.com/924849/45835562-bb083500-bd0a-11e8-8789-e52497a2d42a.png)

**Comment by aaronweaver** [comment]
Hi @droptableuser. Thanks for reporting the vulnerability. I've tracked down the issue to a third party component that had updated the code but hadn't cut a new release with the fix. 

I've [requested](https://github.com/jjkester/django-auditlog/issues/189) a new release to be put out but if I don't get a speedy response then I'll fork the code and update the setup to point to this forked repo.

**Comment by aaronweaver** [comment]
@droptableuser This issue has been fixed by removing the feature entirely from admin. We will be re-evaluating the use of this module. The release is 1.5.3.0 and the docker has also been updated. Thanks again for reporting.
