### ISSUE TITLE
Wrong endpoint finding description aggregation in reimport Nessus report if new or mitigated endpoint

### ISSUE THREAD

**Issue by aflima** [DefectDojo/django-DefectDojo#7430]
The description given at the time of a nessus vulnerability reimport.
When the vulnerability title and endpoint are maintained, but there was an update in the output presented by the tool, this new vulnerable version is not presented in the defectdojo description. Even if the endpoints changes when mitigated ou new to the finding de description still the same.

Example images follow
![image](https://user-images.githubusercontent.com/2230195/212754349-d525bfdb-3483-4ed5-ad5b-bb1dadb97f9a.png)
![image](https://user-images.githubusercontent.com/2230195/212754574-a16bc31e-c9e8-448a-952a-e35330a92253.png)

**Steps to reproduce**
1. Create an engagment and import .nessus scan result in some test;
2. Change de version of vulnerable version showing in .nessus
3. You will see that for some reason Dojo still show the old version in description.

**Expected behavior**
Update de description information in Dojo when the version, or endpoints changed in the finding.

**Deployment method** *(select with an `X`)*
- [x] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
Operating System:
Distributor ID: Ubuntu
Description: Ubuntu 22.04.1 LTS
Release: 22.04
Codename: jammy
DefectDojo version v. 2.18.1 ( release mode )

**Comment by coheigea** [comment]
This is because the Nessus parser uses these settings for deduplication:

'Nessus Scan': ['title', 'severity', 'vulnerability_ids', 'cwe'],

As it doesn't use the description then it sees that the reimport is the same as the old one and doesn't update it. Most of the parsers don't use description, so I'm not sure TBH if it should be changed or not.
