### ISSUE TITLE
Missconfiguration in the API endpoint "/dojo_groups" due to "configuration_permissions"

### ISSUE THREAD

**Issue by adrianasantex** [DefectDojo/django-DefectDojo#7445]
## Bug description
I have made a very big upgrade since 2.3.1 to 2.18.1 and some configuration permission has been implemented. In 2.3.1 I had some groups of users defined and now this error happens:
Internal server error occurs when calling API endpoint “dojo_groups”. I supposed this error happens because configuration permissions from “dojo_groups” have not been loaded yet when I call endpoint “/dojo_groups” or “/dojo_groups/{id}”. 

**Example**: If I call a group through API that I have never visited before with “GET /dojo_groups/1” I receive a 500 Internal server error.
When I load this group from the DefectDojo UI I can see this group correctly and then, when calling again the API endpoint the information appears and 200 OK is received.

This must be a not completed performance of the function that process the request and doesn’t preload the configuration permission if this haven’t been created before. 
Same error occurs when I try to get information of all “dojo_groups”. 
I **followed all the instructions in the UPGRADING.md notes** to update version to version. 

### Steps to reproduce
To reproduce exactly my issue:
1. Deploy DefectDojo 2.3.1 and create some groups with users. 
2. Then deploy with the same data DefectDojo 2.18.1 and don’t visit through DefectDojo UI the groups which you created before.
3. Call the API endpoint “/dojo_groups” and then you will receive a 500 Internal Server Error
4. If then you visit all those groups and call again the API endpoint, will receive the information correctly.

### Expected behavior
The expected behavior is when I call through the API a group that has not set the configuration permissions by default, the function that receive the request must set it as happens while trying to access to this group in the UI. 

### Deployment method
- [X] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

### Environment information
 - Operating System: Not relevant
 - DefectDojo version (see footer) or commit message: Since DefectDojo version 2.12.0 (when configuration permission API endpoint was implemented) to latest version.

### Screenshots

1. Get all groups: 

![imagen](https://user-images.githubusercontent.com/115696190/213132704-be63f0aa-80c8-496c-8d83-aee932ed309d.png)

2. Get group 39: 

![imagen](https://user-images.githubusercontent.com/115696190/213132799-1d85888c-6ec8-4d32-a0ae-7cdb043374b0.png)

3. Error log: 

![imagen](https://user-images.githubusercontent.com/115696190/213133973-2b7efe83-30ba-463e-bb86-a2466c43a837.png)

4. Get group 39 in the UI: 

![imagen](https://user-images.githubusercontent.com/115696190/213132931-15ab761e-966b-4c57-9b0b-acfa59d55960.png)

5. Now get the group 39 through API again:
![imagen](https://user-images.githubusercontent.com/115696190/213133037-03847e91-9088-4f45-9a6e-f533338eaca4.png)

**Comment by manuel-sommer** [comment]
This can be closed as fix was merged @mtesauro
