### ISSUE TITLE
Reimport Generic Findings Import error "An exception error occurred during the report import:['Host XXX has invalid format']

### ISSUE THREAD

**Issue by aflima** [DefectDojo/django-DefectDojo#7451]
When execute an reimport having the same host defined in the import a receive an error. This bug happens only in the version 2.18.2 of Dojo

**Steps to reproduce**
1. Create a engagement and import this file [test.zip](https://github.com/DefectDojo/django-DefectDojo/files/10449352/test.zip) as a Generic Finding Import test.
2. Try to reimport the same file in the test and you will see the error " An exception error occurred during the report import:['Host "arn:aws:ecr:us-east-1:1:teste/teste/sha256:111111111111111111111111111111111111111111" has invalid format']"

**Expected behavior**
Still work as the older versions of Dojo

**Deployment method** *(select with an `X`)*
- [x] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
Operating System:
Distributor ID: Ubuntu
Description: Ubuntu 22.04.1 LTS
Release: 22.04
Codename: jammy
DefectDojo version v. 2.18.2 ( release mode )

**Screenshots**
![image](https://user-images.githubusercontent.com/2230195/213261803-87d5988e-84a6-4e52-8184-3448d1d0f171.png)
![image](https://user-images.githubusercontent.com/2230195/213261879-487bd186-dddc-467f-9587-e97dc922f782.png)

**Comment by coheigea** [comment]
PR submitted: https://github.com/DefectDojo/django-DefectDojo/pull/7461

**Comment by mtesauro** [comment]
PR merged.  Thanks :+1:
