### ISSUE TITLE
Port before URI in nginx_TLS

### ISSUE THREAD

**Issue by awakenine** [DefectDojo/django-DefectDojo#7466]
**Bug description**
https://github.com/DefectDojo/django-DefectDojo/blob/1bc9f67ee8470ac1bbbad9aadc8a837979e81c12/nginx/nginx_TLS.conf#L24

URI should be after port

**Comment by manuel-sommer** [comment]
@mtesauro , this issue sounds for me like a false positive. You can probably close it

**Comment by manuel-sommer** [comment]
This issue is already fixed @mtesauro
