### ISSUE TITLE
Jira webhook integration for "all issues" scope causes 404 errors in logs

### ISSUE THREAD

**Issue by awakenine** [DefectDojo/django-DefectDojo#7467]
**Bug description**
Jira webhook creation according to the Docs https://defectdojo.github.io/django-DefectDojo/integrations/jira/#enabling-the-webhook forses Jira to push webhook for default scope "all issues", which causes ton of 404 errors in DefectDojo logs for issues are not connected with Dojo.

**Expected behavior**
The documentation can be updated mentioning that we should configure the scope of the webhook instead of using default "all issues" (e.g with labels=defectdojo).

Webhook Scope and Events should be defined for configuration on Jira side. I'm not sure which events DefectDojo currently handle, but it would be great to have a list for configuring.

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Logs** 
```
[20/Jan/2023 10:51:32] WARNING [dojo.jira_link.views:205] 404 error processing JIRA webhook
[20/Jan/2023 10:51:32] WARNING [django.request:224] Not Found: /jira/webhook/[token]
[pid: 33|app: -|req: -/-] ***.**.**.*** (-) {60 vars in 1020 bytes} [Fri Jan 20 10:51:32 2023] POST /jira/webhook/[token] => generated 15948 bytes in 12 msecs (HTTP/1.0 404) 6 headers in 189 bytes (1 switches on core 0)
```

**Comment by kokhanevych-macpaw** [comment]
Faced the same bug for K8s based deployment. Could you take a look, please?

**Comment by kokhanevych-macpaw** [comment]
Hi @awakenine,

Have you mitigated it somehow? Could you provide an example of a JQL query?

**Comment by lolziac** [comment]
I encountered the same issue ! documentations should point that out.
Thanks @awakenine for bringing this up, saved me troubleshooting time - I'll use the same path as you with labels=defectdojo

**Comment by mtesauro** [comment]
Closed as stale
