### ISSUE TITLE
Sysdig Scan Report Import Parser

### ISSUE THREAD

**Issue by ronkara** [DefectDojo/django-DefectDojo#7468]
**Is your feature request related to a problem? Please describe**
Hello,
I would like to know how I can go about requesting a feature update to this project that would create an importation parser that can read Sysdig container scanner report CSV files. The Sysdig report contains the following attributes and they are not tailorable or modifiable within the Sysdig application (you get what you see).

VulnerabilityID,Severity,Packagename,ImageID,Imagename,Imagetag,Vulnerabilitytype,CVSSv2vector,CVSSv2basescore,CVSSv3vector,CVSSv3basescore,Vulnlink,Fixversion,Vulnexception,Packageversion,Imageadded,Pod,Namespace,ContainerName,ContainerID,ClusterName,Deployment,Hostname

I was capable of modifying my report file to match the Generic Findings attribute fields as displayed below and though this succeeded in importing it is a cludgy solution at best and requires manually modifying the file each and every time or developing some external manual process to convert the data.

Date,Title,CweId,Url,Severity,Description,Mitigation,Impact,References,Active,Verified,CVE

**Describe the solution you'd like**
As an ISSO, I want to be able to utilize DefectDojo to import all three scan source types (Tenable and Burp are ok) into a single consolidate view so that reporting may be done to FedRAMP PMO and Federal agency security personnel on a monthly basis as required.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you have considered.
The only alternative I have at this time is to take the aforementioned scanning attributes and manually modify them into the Generic Findings parser importation format which defeats the required automated nature of creating our monthly POAM (Plan of Action and Milestone) reports (different formats for FedRAMP and Federal agencies).

**Additional context**
Add any other context, screenshots, sketch, code snippet, etc. about the feature request here.

Sysdig report attributes (spaces have been removed)
"VulnerabilityID,Severity,Packagename,ImageID,Imagename,Imagetag,Vulnerabilitytype,CVSSv2vector,CVSSv2basescore,CVSSv3vector,CVSSv3basescore,Vulnlink,Fixversion,Vulnexception,Packageversion,Imageadded,Pod,Namespace,ContainerName,ContainerID,ClusterName,Deployment,Hostname"

**Comment by ronkara** [comment]
That appears to be the case but curious if the other one is being worked on and if there is any time line for making it available.  Also curious if my report in its details gives a better definition of the issue and the output format fields.

**Comment by manuel-sommer** [comment]
Can you close this @mtesauro ?
