### ISSUE TITLE
Access Level Support

### ISSUE THREAD

**Issue by xtrcamel** [DefectDojo/django-DefectDojo#7473]
I'm trying to confirm on how to separate access for varying levels of users on Defect Dojo.

My company can have many teams. Each team can have many projects. I have users on team level and project level. team level users will require access to multiple projects, while project level users can only access one project.

I've tried to summarize the rough ERD of DefectDojo in order to solve my problem. Here's what ive got:
![image](https://user-images.githubusercontent.com/123347707/213992474-a958c7e6-04f2-4c8a-bf47-0fb143012d6b.png)

From here, I inferred that I can do the following:
1. create a `product_type`, 
1. create `product` from the `product_type`
1. create `dojo_group` for that team users
1. create `dojo_group` for that project users

and then for my team users to be able to access multiple projects (in DefectDojo terms: `product`), I can just create a `product_type_group` of the team level users `dojo_group`.

while for my project users to be able to access only one project, I can just create a `product_group` of the project level users `dojo_group`.

is this correct?
any assistance would be helpful

thank you

**Comment by manuel-sommer** [comment]
You can create user groups and add personst to user groups. Those user groups will get access to projects.
Please ask such questions rather in the slack channel.

I guess you can close this @mtesauro

**Comment by mtesauro** [comment]
@xtrcamel 
See the documentation at https://documentation.defectdojo.com/usage/permissions/
