### ISSUE TITLE
How to configure https nginx

### ISSUE THREAD

**Issue by sergeymeleschenko** [DefectDojo/django-DefectDojo#7476]
django-DefectDojo/nginx

  server {
    server_tokens off;
    listen 8443 ssl;
    server_name dojotest.mydomain.com;
    ssl_certificate /etc/nginx/ssl/mycert.crt;
    ssl_certificate_key /etc/nginx/ssl/private.key;
    ssl_session_cache builtin:1000 shared:SSL:10m;
    # ciphers from https://ssl-config.mozilla.org/#server=nginx&version=1.17.7&config=intermediate&openssl=1.1.1d&guideline=5.4
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA25>
    ssl_prefer_server_ciphers off;

    location = /50x.html {
        root                    /usr/share/nginx/html;
    }
    location /static/ {
      alias /usr/share/nginx/html/static/;
    }
    location / {
      include /run/defectdojo/uwsgi_pass;
      include /etc/nginx/wsgi_params;
      uwsgi_read_timeout 1800;

The port 8443 doesn't respond. How can I configure SSL connection with nginx ?

**Comment by devhops** [comment]
Is your firewall open on 8443?

If you run `sudo lsof -i :8443` does that show nginx listening on that port?

Can you reach 8443 from localhost? (where you installed DD)

**Comment by sergeymeleschenko** [comment]
The firewall is clear. There are no rules. Port 8080 respond and I can open web DD by http
lsof -i :8080
COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
docker-pr 42074 root    4u  IPv4 152497      0t0  TCP *:http-alt (LISTEN)
docker-pr 42082 root    4u  IPv6 152503      0t0  TCP *:http-alt (LISTEN)

 lsof -i :8443
COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
docker-pr 42046 root    4u  IPv4 152666      0t0  TCP *:8443 (LISTEN)
docker-pr 42053 root    4u  IPv6 152433      0t0  TCP *:8443 (LISTEN)

**curl -i 127.0.0.1:8443
curl: (56) Recv failure: Connection reset by peer**

root@cybersecops-test:/defectdojo-2.9.0/django-DefectDojo# curl -i 127.0.0.1:8080
HTTP/1.1 302 Found
Server: nginx/1.23.1
Date: Tue, 24 Jan 2023 08:44:33 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 0
Connection: keep-alive
Location: /login?next=/
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
Vary: Cookie

**Comment by sergeymeleschenko** [comment]
How to use my own SSL certificate ?

**Comment by sergeymeleschenko** [comment]
I don't see any answers, please let me know about this.

**Comment by sergeymeleschenko** [comment]
Is there any info on how to use this on Ubuntu 20.04? I'm using docker-compose with docker-compose.yaml.

**Comment by sergeymeleschenko** [comment]
version: '3.8'
services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    image: "defectdojo/defectdojo-nginx:${NGINX_VERSION:-latest}"
    profiles:
      - mysql-rabbitmq
      - mysql-redis
      - postgres-rabbitmq
      - postgres-redis
    depends_on:
      - uwsgi
    environment:
     **USE_TLS: 'true'
     GENERATE_TLS_CERTIFICATE: 'true'**
     NGINX_METRICS_ENABLED: "${NGINX_METRICS_ENABLED:-false}"
    volumes:
      - defectdojo_media:/usr/share/nginx/html/media
    ports:
      - target: 8080
        published: ${DD_PORT:-8080}
        protocol: tcp
        mode: host
      **- target: 8443
        published: ${DD_PORT:-8443}
        protocol: tcp
        mode: host**

https works, but I need to use my own wilcard certificate.

**Comment by sergeymeleschenko** [comment]
any updates ?

**Comment by sergeymeleschenko** [comment]
How can I change 8443 port to 443 ?

**Comment by sergeymeleschenko** [comment]
no answer. no reaction

**Comment by 0xCVEer** [comment]
> version: '3.8' services: nginx: build: context: ./ dockerfile: Dockerfile.nginx image: "defectdojo/defectdojo-nginx:${NGINX_VERSION:-latest}" profiles: - mysql-rabbitmq - mysql-redis - postgres-rabbitmq - postgres-redis depends_on: - uwsgi environment: **USE_TLS: 'true' GENERATE_TLS_CERTIFICATE: 'true'** NGINX_METRICS_ENABLED: "${NGINX_METRICS_ENABLED:-false}" volumes: - defectdojo_media:/usr/share/nginx/html/media ports: - target: 8080 published: ${DD_PORT:-8080} protocol: tcp mode: host **- target: 8443 published: ${DD_PORT:-8443} protocol: tcp mode: host**
> 
> https works, but I need to use my own wilcard certificate.

Thankyou so much.
