### ISSUE TITLE
CVSS import error while importing vulnerabilities from Nessus

### ISSUE THREAD

**Issue by sixpacksecurity** [DefectDojo/django-DefectDojo#7477]
**Be informative**
While trying to import vulnerability scan data from Nessus, seeing an error for CVSS import field

**Bug description**
An exception error occurred during the report import:Malformed CVSS3 vector "AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N" is missing mandatory prefix or uses unsupported CVSS version

**Steps to reproduce**
1. Export scan data from Nessus
2. Create a new Engagment and Test
3. Import scan data
4. An error is received on the UI

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: [e.g. Ubuntu 20.04]
 - DefectDojo version 2.18.2

**Logs** 
[23/Jan/2023 14:23:22] ERROR [dojo.test.views:754] Malformed CVSS3 vector "AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N" is missing mandatory prefix or uses unsupported CVSS version
Traceback (most recent call last):
  File "/app/dojo/test/views.py", line 745, in re_import_scan_results
    reimporter.reimport_scan(scan, scan_type, test, active=active, verified=verified,
  File "/app/dojo/importers/reimporter/reimporter.py", line 383, in reimport_scan
    parsed_findings = parser.get_findings(scan, test)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/tools/nessus/parser.py", line 264, in get_findings
    return NessusXMLParser().get_findings(filename, test)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/tools/nessus/parser.py", line 197, in get_findings
    cvssv3 = CVSS3(item.findtext("cvss3_vector")).clean_vector()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cvss/cvss3.py", line 96, in __init__
    self.parse_vector()
  File "/usr/local/lib/python3.11/site-packages/cvss/cvss3.py", line 123, in parse_vector
    raise CVSS3MalformedError('Malformed CVSS3 vector "{0}" is missing mandatory prefix '
cvss.exceptions.CVSS3MalformedError: Malformed CVSS3 vector "AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N" is missing mandatory prefix or uses unsupported CVSS version

**Screenshots**
![image](https://user-images.githubusercontent.com/91971692/214063512-3d1034af-f1c2-48b0-8f50-be9fe35f3437.png)

**Comment by coheigea** [comment]
Can you give an example?

**Comment by damiencarol** [comment]
we have the same challenge for few other parsers. it needs some logic in the parser.

**Comment by WojTecH94** [comment]
Same for me, no cvss imported either via api or UI. Sample Tenable (Nessus) report to test attached
[nessus_report.csv](https://github.com/DefectDojo/django-DefectDojo/files/11296043/nessus_report.csv)

**Comment by mtesauro** [comment]
Please check this again in 2.23.0 which will be out the first week of May - #8072 updates the parser.
