### ISSUE TITLE
Automatically add users to groups based on SSO groups

### ISSUE THREAD

**Issue by KramNamez** [DefectDojo/django-DefectDojo#7495]
When users first login to DefectDojo, they have no permissions on anything and an admin has to go and manually give them the correct permissions / add them to groups. Since the user is created on login, this also can't be done in advance.

Ideally, DefectDojo can match groups / roles that the users have in a "groups" claim in their authentication token to groups in DefectDojo and auto-add them if there are one or more matches. This is the behavior that for example Dependency-Track has and would be very useful here.

**Comment by kiblik** [comment]
This behaviour is available for
- Azure: https://documentation.defectdojo.com/integrations/social-authentication/#automatic-import-of-user-groups
  - Implemented in https://github.com/DefectDojo/django-DefectDojo/blob/a8bd8f5a8ec0d79ef57b8bbee5364f640bc08ce7/dojo/pipeline.py#L70
- RemoveUser: https://documentation.defectdojo.com/integrations/social-authentication/#remoteuser
  - Implemented in https://github.com/DefectDojo/django-DefectDojo/blob/e6a88af6109c8d9fdeee9dddc87a319d74292e88/dojo/remote_user.py#L59

Both providers use https://github.com/DefectDojo/django-DefectDojo/blob/a8bd8f5a8ec0d79ef57b8bbee5364f640bc08ce7/dojo/pipeline.py#L112  
We will be more than happy if somebody will add it also to other identity providers.

And there is also the `default group`: https://documentation.defectdojo.com/integrations/social-authentication/#default-group

**Comment by KramNamez** [comment]
I see - thank you for your information! 

For my use, _maybe_ the default group is enough, but I'll look at the code and see if I can make it useable for Keycloak, too.

**Comment by manuel-sommer** [comment]
@KramNamez, were you able to do that for Keycloak?
If yes, could you update the documentation accordingly?

**Comment by KramNamez** [comment]
No, sorry. Ultimately, my experience with DefectDojo was that it matched my usecases so poorly that I didn't pursue it any longer.
