### ISSUE TITLE
RABBITMQ DEPENDENCIES NOT FOUND IN BITNAMI

### ISSUE THREAD

**Issue by spantacms** [DefectDojo/django-DefectDojo#7500]
We are using Defectdojo chart ( 2.15.1 or main). The Rabbitmq dependencies chart is not found since Bitnami already deprecated or removed it. Please update the Rabbitmq chart version

Let me know if you can help us with this
lock file config
- name: rabbitmq
  repository: https://charts.bitnami.com/bitnami
  version: 9.1.4
This version not found in bitnami

**Comment by dsever** [comment]
Please remove lock file and pull dependencies, for some reason locked is old version

**Comment by bushong1** [comment]
Any updates @Maffooch ?

**Comment by manuel-sommer** [comment]
Can we close this because of https://github.com/DefectDojo/django-DefectDojo/pull/10661 @mtesauro and @Maffooch ?

**Comment by mtesauro** [comment]
FYI: DefectDojo deprecated MySQL and RabbitMQ as supported tech as of the July release (2.36.0) and is removing both from our compose, helm and Github actions in August's release (Monday, Aug 5th 2.37.0).

Because of those deprecations, this issue no longer applies.
