### ISSUE TITLE
DataTables Warning Popup on Open Findings page

### ISSUE THREAD

**Issue by alles-klar** [DefectDojo/django-DefectDojo#7523]
**Bug description**
When a user has read only permission on a product level, he gets a popup with a DataTables warning when opening the finding page from the product: /product/1/finding/open

![](https://user-images.githubusercontent.com/16321214/215859068-04ad9aa4-5939-490a-b581-2506cc4dd058.png)

**Steps to reproduce**
1. Create a user with read only permissions on a product with open findings.
2. Switch to the new user
3. Open the page with open findings from the product (/product/1/finding/open)

**Environment information**
 - DefectDojo version: 2.18.0

**Comment by alles-klar** [comment]
FYI: @damiencarol and @Maffooch

**Comment by Maffooch** [comment]
Wow! The pop up was not being displayed on the screenshare. That is gnarly.

**Comment by Maffooch** [comment]
Still seeing this on the view test page.. Looking into It
![image](https://user-images.githubusercontent.com/46459665/233461751-d4db68ae-ed5a-48e1-bdaf-d4d42658ebb4.png)
