### ISSUE TITLE
Dependency Check findings always have CWE 1035

### ISSUE THREAD

**Issue by Nilix007** [DefectDojo/django-DefectDojo#753]
### Issue Type 
- [ ] Bug
- [x] Enhancement

### Description

Dependency Check findings always have the CWE 1035 in DefectDojo (See [here](https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/dependencycheck/parser.py#L44))

This is technically correct (the best kind of correct), however I have the feeling that setting this CWE for all DC findings does not add any value because DC only scans for vulnerable dependencies.

I'd prefer it when the actual CWE of the finding is used if present and 1035 is only used as a fallback. What do you think, @aaronweaver?

**Comment by aaronweaver** [comment]
Does DC expose CWE? I think at the time it wasn't available but if it is I agree with your suggestion.

**Comment by Nilix007** [comment]
Yes, roughly a quarter of our DC findings have a specific CWE set.

I'll make a patch.
