### ISSUE TITLE
Direct Import of Scans

### ISSUE THREAD

**Issue by giveen** [DefectDojo/django-DefectDojo#7538]
Without using multiple API's, it would be nice to have a direct import feature for Nessus.

Right now, I have to run a script to download scans from Nessus and then import them into DefectDojo. It sometimes screws up or missing things, would be nice to just have it be an option to point it to my Nessus server.

**Comment by damiencarol** [comment]
@giveen this could be possible but will require a new importer+parser. Can you contribute on this one?

**Comment by giveen** [comment]
> @giveen this could be possible but will require a new importer+parser. Can you contribute on this one?

I wish I could, but I'm not really a programmer, I can write some scripts in powershell, python, bash but thats about all I can do.

**Comment by gso-trifork-security** [comment]
@damiencarol - I may be able to build an API integration to Nessus. But I am missing some information on how "API Pull" works in DefectDojo, and in particular how to get started building a new integration. What code is required to create a new API pull integration?

**Comment by damiencarol** [comment]
> @damiencarol - I may be able to build an API integration to Nessus. But I am missing some information on how "API Pull" works in DefectDojo, and in particular how to get started building a new integration. What code is required to create a new API pull integration?

You could take a look at the other "api" parsers, to be open source project is sometimes useful ;)

**Comment by gso-trifork-security** [comment]
@damiencarol I think it's bad practice for an open-source project, when you need to reverse engineer the code for building a extended implementation, instead of just having a technical documentation on how components work.

**Comment by manuel-sommer** [comment]
@mtesauro I guess this can be closed as you probably don't want to extend API integrations further.
