### ISSUE TITLE
Report Generation not working

### ISSUE THREAD

**Issue by pierre-ernst** [DefectDojo/django-DefectDojo#754]
### Issue Type 
- Bug

### Description
PDF custom report generation keeps running, no error message

### Operating System 
Ubuntu 16.04

### Install
$ sudo ./setup.bash
$ sudo ./entrypoint_scripts/misc/reports.sh
$ sed -i 's/\\/usr\\/local\\/bin\\/wkhtmltopdf/\\/usr\\/bin\\/wkhtmltopdf/'  ./dojo/settings/settings.py
$ sudo ./entrypoint_scripts/run/run-local-dojo.bash

### DefectDojo Version
1.5.2.1

### Steps to Reproduce
Try to create any PDF report

**Comment by aaronweaver** [comment]
@pierre-ernst Do you have celery running?

```
celery -A dojo worker -l info --concurrency 3 &

celery beat -A dojo -l info &
```

**Comment by pierre-ernst** [comment]
yes, as per my original comment, I'm running this script:

https://github.com/DefectDojo/django-DefectDojo/blob/1.5.2.1/entrypoint_scripts/run/run-local-dojo.bash#L12

**Comment by pierre-ernst** [comment]
I found the root-cause of the issue:
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3001

Maybe you should update your install script to upgrade to wkhtmltopdf 0.12.5

After I've re-installed wkhtmltopdf 0.12.5, everything works as intended
