### ISSUE TITLE
Problem with V1 docs

### ISSUE THREAD

**Issue by MaroonBeret** [DefectDojo/django-DefectDojo#756]
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description
There is a bug in both your test environment and my deployment of Defect Dojo.
It isn't possible to interact with the V1 API docs. When I click on one of the endpoints, it doesn't fold out. Developer tools show some errors.

### Operating System 
Not relevant

### Install

- [x] setup.bash
- [x] docker

### DefectDojo Version
1.5.3 & 1.5.2

### Steps to Reproduce
1. Get testing environment credentials from: https://github.com/DefectDojo/django-DefectDojo
2. Go to the official testing environment and log in: https://defectdojo.herokuapp.com/
3. Get an api v1 key
4. Fill it in the v1 docs inputfield
5. Try to fold out one of the endpoints

### Screenshots (optional)
Chrome Developer Console logs
<img width="570" alt="screen shot 2018-09-26 at 17 32 20" src="https://user-images.githubusercontent.com/10127839/46090998-2aba6c00-c1b2-11e8-9cec-bd361583bbe4.png">

**Comment by MaroonBeret** [comment]
@aaronweaver Hey Aaron, got anything?

**Comment by aaronweaver** [comment]
I just tried it in the dev branch and it works.
