### ISSUE TITLE
Deduplication should only check on engagement level

### ISSUE THREAD

**Issue by wurstbrot** [DefectDojo/django-DefectDojo#757]
### Issue Type 
- [ ] Bug
- [x] Enhancement

### Description
By using deduplication with the dependency check, I want to deduplicate findings on engagement level.
I do not want to deduplicate on product level. Each engagement belongs to one branch.
It might happen that a vulnerability occours only in one branch and not in an other or that a vulnerability is mitigated by patching a lib. in one branch and not in an other.
Specially the second example is important as the close_finding-Option will close a no showing up finding. By using de-duplication on product level, also other branches would be effected.

I would like to add a setting to the "System Settings" to switch de-duplication between product and engagement level.
As an alternativ, we can add the feature to the engagement itself. By doing that, you have the option to choose within a product.

What do you say @aaronweaver?

As an alternative I can de-reference findings according to the idea presented on [slack](https://owasp.slack.com/archives/C2P5BA8MN/p1537857169000100?thread_ts=1536415373.000100&cid=C2P5BA8MN).

Please assign this task to me.

**Comment by aaronweaver** [comment]
I think it should be on the engagement itself and we should create some test cases as the duplication code has several different use cases. 
We also need to make sure we document the functionality intended so that it's clear how to use it.
