### ISSUE TITLE
can't update DD from 2.9v to the latest

### ISSUE THREAD

**Issue by sergeymeleschenko** [DefectDojo/django-DefectDojo#7574]
Update commands:
[logs.txt](https://github.com/DefectDojo/django-DefectDojo/files/10684663/logs.txt)

./dc-stop.sh

Go to the directory where your docker-compose.yml file lives

Stop DefectDojo: ./dc-stop.sh

Re-start DefectDojo, allowing for container recreation: ./dc-up-d.sh

Database migrations will be run automatically by the initializer. Check the output via docker-compose logs initializer

docker-compose logs initializer see in attachment 

How can I fixed this ?

**Comment by manuel-sommer** [comment]
Hi @sergeymeleschenko ,

could you ask such questions in the slack channel please?

This can be closed @mtesauro
