### ISSUE TITLE
View History on a User throws a  Server Error (500)

### ISSUE THREAD

**Issue by sirferl** [DefectDojo/django-DefectDojo#759]
### Issue Type 
- [x ] Bug
- [ ] Enhancement

### Description
When selecting View History on a User, a  Server Error (500) is thrown.
I could "fix" it by inserting " object_value = None" at line 25 to /opt/dojo/django-DefectDojo/dojo/views.py
I am not very fluent in python, so I am not sure, if this is a vlid fix.
Great Tool, please keep up the work.
regards ferdinand

### Operating System 
Ubuntu 18.04.1
### Install

- [ x] setup.bash
- [ ] docker

### DefectDojo Version
1.5.3

### Steps to Reproduce
Click view History on the All Users panel for a User.

### Console Logs (optional)
Sep 28 09:37:38 defectdojo-test dojo[30918]: Internal Server Error: /history/3/1
Sep 28 09:37:38 defectdojo-test dojo[30918]: Traceback (most recent call last):
Sep 28 09:37:38 defectdojo-test dojo[30918]:   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
Sep 28 09:37:38 defectdojo-test dojo[30918]:     response = get_response(request)
Sep 28 09:37:38 defectdojo-test dojo[30918]:   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
Sep 28 09:37:38 defectdojo-test dojo[30918]:     response = self._get_response(request)
Sep 28 09:37:38 defectdojo-test dojo[30918]:   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
Sep 28 09:37:38 defectdojo-test dojo[30918]:     response = self.process_exception_by_middleware(e, request)
Sep 28 09:37:38 defectdojo-test dojo[30918]:   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
Sep 28 09:37:38 defectdojo-test dojo[30918]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Sep 28 09:37:38 defectdojo-test dojo[30918]:   File "./dojo/views.py", line 68, in action_history
Sep 28 09:37:38 defectdojo-test dojo[30918]:     "object_value": object_value,
Sep 28 09:37:38 defectdojo-test dojo[30918]: UnboundLocalError: local variable 'object_value' referenced before assignment

**Comment by sirferl** [comment]
Hmm, how can I contribute so that it is not closed unpatched ?

**Comment by ktreptow** [comment]
I've encountered this problem too and implemented your workaround. It's working now, thank you! Did you think about opening a pull request?

**Comment by sirferl** [comment]
I will eventually. But at the moment I do not have time.

**Comment by ktreptow** [comment]
If you want me to, I could open the pull request. But you found the solution first, so maybe you'd like to do this yourself?

**Comment by sirferl** [comment]
It's an open project, so if you could put that solution in the main code, great !
