### ISSUE TITLE
Github integration not available for products created before enabling the feature

### ISSUE THREAD

**Issue by joeppeeters** [DefectDojo/django-DefectDojo#7590]
**Bug description**
While setting up the Github integration in our Dojo I could only enable it for new products; existing product didn't show the github config form.

After setting `SystemSettings.enable_github` and configuring a github access token, I could not select it for existing product, but the option shows when creating a new product.

**Steps to reproduce**
1. Add new product
2. Go to `Configuration > System Settings` and check "Enable GITHUB integration"
3. Go to `Configuration > Github` and add Github token
4. Either 
  a. Open a new Product form, scroll down, notice the github config (see screenshot)
  b. Edit the product from the first step, scroll down in the form, notice the github config missing.

**Expected behavior**
Show the github config form for existing products too.

**Screenshots**
This form is not showing while editing existing products:
<img width="1018" alt="Screenshot 2023-02-09 at 08 43 04" src="https://user-images.githubusercontent.com/3350917/217748607-26ebf4bb-7cf4-4693-9cb8-f6e72e781c79.png">

**Additional context** (optional)
Suspicious code:
https://github.com/DefectDojo/django-DefectDojo/blob/4dfb3a43651846696823e2d3d7bd5ec485b54276/dojo/product/views.py#L899-L905

`github_inst` is always empty for existing products after enabling the feature, so it will never render the form for those given the condition in `L899`

-----
slack [thread](https://owasp.slack.com/archives/C2P5BA8MN/p1675855241318589)

**Comment by coheigea** [comment]
PR submitted: https://github.com/DefectDojo/django-DefectDojo/pull/7614
