### ISSUE TITLE
Synchronizing DefectDojo groups with IDP

### ISSUE THREAD

**Issue by dvelardez** [DefectDojo/django-DefectDojo#7598]
According to the [documentation](https://documentation.defectdojo.com/integrations/social-authentication/#user-permissions) when a new user is created via social-auth only the default permissions are active. I would like to be able to retrieve the list of groups from the userinfo claim (such as lists of user group names). Is this possible?
I'm trying to integrate DD with Keycloak via SAML.
Thanks in advance.

**Comment by kiblik** [comment]
https://documentation.defectdojo.com/dev/integrations/social-authentication/#groups-from-identity-providers

**Comment by manuel-sommer** [comment]
This can be closed @mtesauro. PR was merged.
