### ISSUE TITLE
Missing Password Change Confirmation

### ISSUE THREAD

**Issue by pierre-ernst** [DefectDojo/django-DefectDojo#760]
### Issue Type 
- [ ] Bug
- [ X] Enhancement

### Description
When changing password (either with the UI or API), the user is prompted for the current password (for security reason) as well as for the new password. It would be better (for usability) to ask users to enter the new password a second time

**Comment by shaunakshah** [comment]
@aaronweaver @mikethebro and myself will be working on this. You can assign it to us!

**Comment by mikethebro** [comment]
@aaronweaver, the fix for this is in pull request #811. What is the process for adding reviewers?
