### ISSUE TITLE
API to download files

### ISSUE THREAD

**Issue by tandhy** [DefectDojo/django-DefectDojo#7608]
**Is your feature request related to a problem? Please describe**
It appears the new API of DefectDojo is not able to download files. This API localhost:8080/api/v2/findings/1234/files does list the path but appears to be in an incorrect format.
        {
            "id": 111,
            "file": "http://localhost:8080/access_url/987/1234/Finding",
            "title": "file_title"
        }

The actual path to the file is actually http://localhost:8080/access_file/987/1234/Finding. But there is no API to download the files. A valid sessionID is required to download the files.

**Describe the solution you'd like**
An API to access a specific file based on the file ID should be available. A valid token is required to get the expected token.
e.g. api/v2/files/{ID}

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by glhl86** [comment]
self-assigned

**Comment by manuel-sommer** [comment]
Hi @mtesauro ,

this can be closed due to the merged PR.
