### ISSUE TITLE
Parsing nessus scan results with important errors 

### ISSUE THREAD

**Issue by php-lover-boy** [DefectDojo/django-DefectDojo#7609]
After importing the Nessus scan output file in to DefectDojo, There are important differences in the scan results (Nessus Csv file) and finding page (DefectDojo).

below is the finding page that is different with Nessus CSV file. 

![pastedImage](https://user-images.githubusercontent.com/111951701/218461389-ecbca92b-6613-4a3a-afb9-a98d271a3656.png)
 
in Nessus Csv file there is not any Wireshark signature except in 172.23.143.2 and 172.23.143.1 
and other results (172.23.140.2, 172.23.140.1 , ....) in finding page in DefectDojo it seems that error and should not be listed here.

**Comment by coheigea** [comment]
I think you will have to provide a sample scan result to help us reproduce the problem.

**Comment by php-lover-boy** [comment]
here is my nessus csv export.
I think this is very important bug.
[172.23.140-142-143.csv](https://github.com/DefectDojo/django-DefectDojo/files/10776866/172.23.140-142-143.csv)

**Comment by coheigea** [comment]
Can you state exactly what the error is?

**Comment by php-lover-boy** [comment]
After importing Nessus csv file in DefectDojo, As you can see below, there are  6 endpoint with this vulnerability (Wireshark 3.6.x <3.6.9 ) but in Nessus csv file there are just 2 endpoint with this vulnerability.

![218461389-ecbca92b-6613-4a3a-afb9-a98d271a3656](https://user-images.githubusercontent.com/111951701/221348963-7d7fb6f1-9882-4fbd-9b0f-9bccbdfbec5d.png)

you can search "Wireshark" in the csv file and then you will find there are just 2 endpoint (172.23.143.1 , 172.23.143.2 ) with this vulnerability.

Defect dojo show wrong vulnerable endpoint.

**Comment by mtesauro** [comment]
You might want to re-check this when 2.23.0 comes out the first week of May - the parser has had a somewhat significant update in #8072

**Comment by manuel-sommer** [comment]
I have uploaded the sample report which was uploaded here and it works fine. version: 2.31.0-dev
You can close this @mtesauro
