### ISSUE TITLE
ZAP scan results upload to dojo resulting in server error (500)

### ISSUE THREAD

**Issue by V1Reddy** [DefectDojo/django-DefectDojo#762]
Please use the following template when submitting issues: (If this is a security issue, then review the [disclosure policy](https://github.com/DefectDojo/django-DefectDojo/blob/master/SECURITY.md) and submit via our security reporting program.

### Issue Type 
- [X] Bug
- [ ] Enhancement

### Description
Receiving a Server Error (500) when I am trying to upload the scan results from the ZAP tool under 'ZAP Scan' scan type.

### Operating System 
Oracle Linux 7.5

### Install

- [X] setup.bash
- [ ] docker

### DefectDojo Version
1.5.2

### Steps to Reproduce

1. Go to Product -> Engagement -> Import Scan Results
2. Provide the required fields data and click 'Choose File' (select a ZAP results xml)
3. Click 'Upload File' button

### Console Logs (optional)
/dojo/django-DefectDojo/dojo/tools/zap/parser.py:227: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
  item = {'uri': n.text, 'param': n2.text if n2 else "", 'host': host, 'protocol': protocol, 'port': port}
**Internal Server Error: /engagement/5/import_scan_results**
Traceback (most recent call last):
  File "/dojo/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/dojo/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/dojo/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/dojo/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/dojo/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/dojo/django-DefectDojo/dojo/engagement/views.py", line 543, in import_scan_results
    item.save(dedupe_option=False)
  File "/dojo/django-DefectDojo/dojo/models.py", line 1191, in save
    if self.reporter.usercontactinfo.block_execution:
  File "/dojo/lib/python2.7/site-packages/django/utils/functional.py", line 239, in inner
    return func(self._wrapped, *args)
  File "/dojo/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py", line 407, in __get__
    self.related.get_accessor_name()
RelatedObjectDoesNotExist: User has no usercontactinfo.
[02/Oct/2018 15:49:14] **"POST /engagement/5/import_scan_results HTTP/1.0" 500 27**

**Comment by V1Reddy** [comment]
Actually, this bug got resolved when I added phone numbers in the User's Profile and the scan results were imported fine.

**Comment by AlexanderTyutin** [comment]
The same error while importing ZAP scan result.
Docker-compose version of django-DefectDojo.

Nginx container output:
```
172.18.0.1 - - [17/Feb/2020:08:23:03 +0000] "GET /alerts/count HTTP/1.1" 200 12 "http://127.0.0.1:8080/engagement/1/import_scan_results" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" "-"
172.18.0.1 - - [17/Feb/2020:08:23:13 +0000] "GET /alerts/count HTTP/1.1" 200 12 "http://127.0.0.1:8080/engagement/1/import_scan_results" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" "-"
172.18.0.1 - - [17/Feb/2020:08:23:23 +0000] "GET /alerts/count HTTP/1.1" 200 12 "http://127.0.0.1:8080/engagement/1/import_scan_results" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" "-"
172.18.0.1 - - [17/Feb/2020:08:23:33 +0000] "GET /alerts/count HTTP/1.1" 200 12 "http://127.0.0.1:8080/engagement/1/import_scan_results" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" "-"
2020/02/17 08:23:34 [warn] 6#6: *376 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000001, client: 172.18.0.1, server: , request: "POST /engagement/1/import_scan_results HTTP/1.1", host: "127.0.0.1:8080", referrer: "http://127.0.0.1:8080/engagement/1/import_scan_results"
172.18.0.1 - - [17/Feb/2020:08:23:34 +0000] "POST /engagement/1/import_scan_results HTTP/1.1" 500 27 "http://127.0.0.1:8080/engagement/1/import_scan_results" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" "-"
172.18.0.1 - - [17/Feb/2020:08:23:34 +0000] "GET /favicon.ico HTTP/1.1" 404 23090 "http://127.0.0.1:8080/engagement/1/import_scan_results" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" "-"

```
