### ISSUE TITLE
Error Notification for Slack and Msteams templates

### ISSUE THREAD

**Issue by hptho** [DefectDojo/django-DefectDojo#7628]
Please add more line code for Slack and Msteams. If it doestn't add. it will error full_url.

`{% load display_tags %}`

![bugfix](https://user-images.githubusercontent.com/80236481/218933108-45fd0a0d-0c16-4a34-892d-b836a7b219d6.png)

Path: dojo\templates\notifications\slack\  <== all files tpl
  dojo\templates\notifications\msteams\  <== all files tpl

Thank you

**Comment by hptho** [comment]
@Maffooch

**Comment by Maffooch** [comment]
Fixed today in #7623 

Will be in the release this upcoming Monday

**Comment by adamtimmins** [comment]
I'm still seeing this issue on v2.19.2 for teams.

**Comment by edwardtyson** [comment]
> I'm still seeing this issue on v2.19.2 for teams.

Me too.

**Comment by kan0n1r** [comment]
I'm still seeing this issue on v2.20.3 for teams.

**Comment by Dejavu610** [comment]
Incoming Webhooks is deprecated in teams. Can we still use the URL in workflow？
