### ISSUE TITLE
[mobsfscan] an exception error occurred during the report import:'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by ghost** [DefectDojo/django-DefectDojo#7630]
Hello dear developers!

When import [Mobsfscan 0.2](https://github.com/MobSF/mobsfscan/releases/tag/0.2.0) JSON results to DefectDojo 2.19.0 following error occured:

```An exception error occurred during the report import:'NoneType' object has no attribute 'group'```

Looks like the Mobsfscan developers changed their JSON structure so it doesn't work correctly now.

Thanks in advance!

**Comment by hvechtomov** [comment]
@ansidorov @damiencarol could you help please?

**Comment by hvechtomov** [comment]
This error appeared due to the fact that in the new report, mobsfscan `CWE` was written in lower case.

**Comment by damiencarol** [comment]
@hvechtomov thanks for this analysis! reviewing your PR

**Comment by manuel-sommer** [comment]
The PR was merged. Please close this @mtesauro
