### ISSUE TITLE
How can I change 8443 port to 443 ?

### ISSUE THREAD

**Issue by sergeymeleschenko** [DefectDojo/django-DefectDojo#7634]
Please provide info on where and what I should change in DD config file to use 443 port instead 9443. 
Please provide config or screenshot. After changing any config with 443 port nginx container didn't start.

**Comment by manuel-sommer** [comment]
Hi @sergeymeleschenko ,

could you please ask such things in the owasp slack channel? 

This can be closed @mtesauro
