### ISSUE TITLE
Switch from `docker-compose` (v1) to `docker compose` (v2)

### ISSUE THREAD

**Issue by ericcornelissen** [DefectDojo/django-DefectDojo#7641]
Following the [deprecation of `docker-compose` (or Compose v1)](https://www.docker.com/blog/new-docker-compose-v2-and-v1-deprecation/) I want to suggest for the DefectDojo to start moving to `docker compose` (or Compose v2).

From my preliminary testing (previous contributions, running [all `./dc-*.sh` scripts](https://github.com/DefectDojo/django-DefectDojo/blob/ede53ab8aa387785e5235dc3c84cd883190a9356/readme-docs/DOCKER.md#scripts) as well as [unit tests](https://github.com/DefectDojo/django-DefectDojo/blob/ede53ab8aa387785e5235dc3c84cd883190a9356/readme-docs/DOCKER.md#running-the-unit-tests)) it seems this should be a pretty smooth transition, at least in terms of development. However, I'm not sure if and how this upgrade would affect end-users of DefectDojo. Also, I don't know a (efficient) way to determine the minimum version of `docker compose` that works, I tested with `v2.15.1`.

**Comment by tannerjones4075** [comment]
I would like to help with this issue.

**Comment by manuel-sommer** [comment]
I guess this can be closed @mtesauro because of https://github.com/DefectDojo/django-DefectDojo/pull/8817
