### ISSUE TITLE
Can't add new users 

### ISSUE THREAD

**Issue by YuToutCourt** [DefectDojo/django-DefectDojo#7673]
Hello, so I don't think it is a bug maybe just a miss config from my side. But I can't add new users.

When I click **+New User** on the users page I got this error :
![image](https://user-images.githubusercontent.com/63105226/220651994-89dfacea-9065-4504-958c-e0ca19e79847.png)

I'm using **v. 2.19.1 ( release mode )**

**Comment by kiblik** [comment]
Can you share the error log, please?

**Comment by YuToutCourt** [comment]
Well I was looking for the logs but I really can'y find them.
I found this but was not working for me 
https://github.com/DefectDojo/django-DefectDojo/issues/5915

Deployment method

    Docker Compose
    nginx


Environment information

    Operating System: Kali 6.0.0
    DefectDojo version: V2.19.1

**Comment by kiblik** [comment]
Not sure, which stack you are running but this can be useful for `docker-compose` method
```shell
docker-compose --profile mysql-rabbitmq --env-file ./docker/environments/mysql-rabbitmq.env logs uwsgi
```

**Comment by YuToutCourt** [comment]
Ok thank you 

So I have this : 

uwsgi_1         |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |                ^^^^^^^^^^^^^^^^^^^^^
uwsgi_1         |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi_1         |   File "/app/dojo/authorization/authorization_decorators.py", line 63, in _wrapped
uwsgi_1         |     return func(request, *args, **kwargs)
uwsgi_1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi_1         |   File "/app/dojo/user/views.py", line 314, in add_user
uwsgi_1         |     form = AddDojoUserForm()
uwsgi_1         |            ^^^^^^^^^^^^^^^^^
uwsgi_1         |   File "/app/dojo/forms.py", line 1966, in __init__
uwsgi_1         |     self.fields['password'].help_text = get_password_requirements_string()
uwsgi_1         |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi_1         |   File "/app/dojo/utils.py", line 2294, in get_password_requirements_string
uwsgi_1         |     return password_requirements_string + '.'
uwsgi_1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi_1         | UnboundLocalError: cannot access local variable 'password_requirements_string' where it is not associated with a value

I think I know now what is the problem 😅
I gonna go change the code to see if I can solve it

**Comment by YuToutCourt** [comment]
Okay, I understand the problem now. While testing some things with DefectDojo in my sandbox environment, I removed the option for new users to create difficult passwords.
![image](https://user-images.githubusercontent.com/63105226/221141852-84f910f1-dbf6-4734-a970-f7fe86f65ae8.png)


 As a result, in the get_password_requirements_string() function in utils.py, there is a mistake in the code that was not accounted for.

The current implementation of the function is missing a case where someone may have removed all password requirements, leading to an unexpected behavior. Here's the current implementation of the function:

```py
    if s.count(', ') == 1:
        password_requirements_string = s.rsplit(', ', 1)[0] + ' and ' + s.rsplit(', ', 1)[1]
    elif s.count(', ') > 1:
        password_requirements_string = s.rsplit(', ', 1)[0] + ', and ' + s.rsplit(', ', 1)[1]

    return password_requirements_string + '.'
```

 The updated function could look something like this:

```py
    if s.count(', ') == 1:
        password_requirements_string = s.rsplit(', ', 1)[0] + ' and ' + s.rsplit(', ', 1)[1]
    elif s.count(', ') > 1:
        password_requirements_string = s.rsplit(', ', 1)[0] + ', and ' + s.rsplit(', ', 1)[1]
    else :
        password_requirements_string = s

    return password_requirements_string + '.'
```
This worked for me. I think I can put this issue as bug

**Comment by kiblik** [comment]
I suppose you are right.
If you already know, how to fix it and open a PR
https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/CONTRIBUTING.md
