### ISSUE TITLE
500 Error due to recursive copying

### ISSUE THREAD

**Issue by sjs6776** [DefectDojo/django-DefectDojo#7677]
**Bug description**
A 500 error will appear during an attempt to copy information that includes uploaded files, the copy will partially complete but is blocked once the error is reached. Uploaded files that are copied will have " - clone-xxxxxxxx" appended to the filename during the copy. The filename has a 100 character limit, which causes a 500 error if exceeded. Recursive copying will exceed this limit within 5 copies

**Steps to reproduce**
1. Upload a file to a finding
2. Click on 'copy' for the finding, test, or engagement
3. Repeat step 2 until a 500 error is achieved
4. Error Logs indicate the 100 character limit on the filename 

**Expected behavior**
Copying anything that includes an uploaded file will overwrite the final characters of a filename if appending will exceed 100 character limit (prevent breaking).

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Standard DockerHub image
 - DefectDojo version 2.19.0

**Screenshots**
![Filenames](https://user-images.githubusercontent.com/103534016/220819709-a1f56995-e276-4b10-a5c8-2d740dd74fc9.png)

**Comment by manuel-sommer** [comment]
Hi @sjs6776 , I wanted to reproduce this error, but I can't find a way to upload a file to a finding. I am testing on v. 2.32.0-dev ( release mode )

**Comment by mtesauro** [comment]
@manuel-sommer I suspect they mean adding a file to a finding like when you add a screenshot to a finding - here's a silly example from the public demo:

Using this finding: https://demo.defectdojo.org/finding/406

![image](https://github.com/DefectDojo/django-DefectDojo/assets/3422419/ce7ae0ec-83a7-4280-b755-9fbc8d03ebb8)

![image](https://github.com/DefectDojo/django-DefectDojo/assets/3422419/b8edceae-f6d7-4534-b494-fa419ec68284)

![image](https://github.com/DefectDojo/django-DefectDojo/assets/3422419/0ad5c5da-0a11-43b5-9cd9-11d3be6aab77)

Once this is in place, then doing the option to Copy the File, Test or Engagement should cause the 500.

**Comment by mtesauro** [comment]
Just got a chance to try copying the fining above -it worked fine in the public demo. I'm going to close this.

Feel free to reopen this and add enough details for the issue to be replicated.
