### ISSUE TITLE
Scout2 support

### ISSUE THREAD

**Issue by spartantri** [DefectDojo/django-DefectDojo#771]
### Issue Type 
- [ ] Bug
- [X] Enhancement

### Description
Is there a roadmap of future integrations, scout2 in particular?

**Comment by aaronweaver** [comment]
It's been on my wishlist to get to. We've recently added to the dev branch about 4 new parsers and an AWS parser would be a nice addition.

**Comment by aaronweaver** [comment]
@spartantri Merged in dev.

**Comment by spartantri** [comment]
Thanks! let me take a look
