### ISSUE TITLE
BlackDuck API - get_asset issue

### ISSUE THREAD

**Issue by juanrafaelvillen** [DefectDojo/django-DefectDojo#7717]
Hi I am facing the below issue when trying to connect to my BlackDuck repository.

I did create the API Tool conection, with the API Key, but the error is showed when configuring a new API Scan configuration.

**Deployment method** *(select with an `X`)*
- [ x] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo version v. 2.19.2 ( release mode )

![image](https://user-images.githubusercontent.com/38559203/221889278-1feb3ff2-24f0-454d-981f-e87e5304d7a1.png)

**Comment by kiblik** [comment]
Fixed in #7665, released in [2.19.3](https://github.com/DefectDojo/django-DefectDojo/releases/tag/2.19.3).
