### ISSUE TITLE
Deduplication not working

### ISSUE THREAD

**Issue by Vulcainreo** [DefectDojo/django-DefectDojo#772]
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description
During scan import (burp XML report, retrieved by API), DefectDojo don't operate deduplication about findings. I try to import the same report two times in the same testID and in two different testID. I havealready activated the option deduplicating findings, the option delete duplicate and set the max duplicate to 1.

### Operating System 
Linux Ubuntu 18?04 LTS - 4.15.0-20 x64.

### Install
- [x] setup.bash
- [ ] docker

### DefectDojo Version
I'm running the last version (fresh git pull)

### Steps to Reproduce
Try to import  this burp report twice and see that the deduplication process do nothing (all findings are store twice)

[reportBurpLight.zip](https://github.com/DefectDojo/django-DefectDojo/files/2465450/reportBurpLight.zip)

**Comment by aaronweaver** [comment]
Make sure that you either have celery running and/or set your user preferences to blocking. If that still doesn't work for you we've made a few patches in dev for certain edge cases.

**Comment by Vulcainreo** [comment]
Everythings works ! Thank you so much.
