### ISSUE TITLE
Demo creds for user2

### ISSUE THREAD

**Issue by wadebee** [DefectDojo/django-DefectDojo#7720]
What is the login password for user2? 

I would like to login as user2 so I can evaluate the RBAC filtering capabilities of DD. We need to ensure that users are only able to see scanning results of their own workloads.

**Comment by mtesauro** [comment]
If you're talking about the public demo (https://demo.defectdojo.org/) then the only "real" user is the Admin user that's auto-created when the demo is refreshed regularly.  Feel free to create a user, set the password and explore the RBAC.

Just be aware that what you do is public and will be refreshed every 24 hours.
