### ISSUE TITLE
JIRA integration - inaccurate documentation

### ISSUE THREAD

**Issue by Kedlix** [DefectDojo/django-DefectDojo#7733]
I've been trying to set up an integration with Jira for weeks, but the documentation isn't clear as to what we need to integrate.

What kind of Jira project? ID names in jira are not compatible with DefectDojo.

**Comment by damiencarol** [comment]
it seems you have questions more than describing an issue, please check our https://github.com/DefectDojo/django-DefectDojo#community-getting-involved-and-updates resources.
Closing it.
