### ISSUE TITLE
I'm looking forward to the DojoPRO version

### ISSUE THREAD

**Issue by renatosazup** [DefectDojo/django-DefectDojo#7736]
I would like to know more about this new version, will it be paid? I saw that there are two new features in the menu heheheh

could you give more details?

![Screenshot_24](https://user-images.githubusercontent.com/113721433/222282278-802f6c43-38b1-4c31-a382-e59af7665c90.png)

**Comment by mtesauro** [comment]
What @Gby56 said is correct.  The features in those menu items are in the doc link he provided.

The goal is to have sustainable funding for the project so it can maintain quality going forward while still providing a solid open source project.
