### ISSUE TITLE
GITLAB dependency scan json importer error

### ISSUE THREAD

**Issue by polter05** [DefectDojo/django-DefectDojo#7747]
**Slack us first!**
The easiest and fastest way to help you is via Slack. There's a free and easy signup to join our #defectdojo channel in the OWASP Slack workspace: [Get Access.](https://owasp-slack.herokuapp.com/)
If you're confident you've found a bug, or are allergic to Slack, you can submit an issue anyway.

**Be informative**
Please enter as much information as possible, otherwise we can't provide support. If possible upgrade to the latest release or dev version and try again.

**Bug description**
Error in import json file form GitLab Dependency Scanning Report since version 15.0.0. The filed category is deleted, remplaced by scanner field.
https://gitlab.com/gitlab-org/security-products/security-report-schemas/-/blob/master/CHANGELOG.md

**Steps to reproduce**
import_report with type GitLab Dependency Scanning Report 

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [x] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Helm chart
 - DefectDojo version : 2.19.4

**Logs** 
│ uwsgi [03/Mar/2023 10:18:26] ERROR [dojo.api_v2.exception_handler:32] 'category'                                                                                                                  │
│ uwsgi Traceback (most recent call last):                                                                                                                                                          │
│ uwsgi   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch                                                                                             │
│ uwsgi     response = handler(request, *args, **kwargs)                                                                                                                                            │
│ uwsgi                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                            │
│ uwsgi   File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create                                                                                               │
│ uwsgi     self.perform_create(serializer)                                                                                                                                                         │
│ uwsgi   File "/app/dojo/api_v2/views.py", line 2054, in perform_create                                                                                                                            │
│ uwsgi     serializer.save(push_to_jira=push_to_jira)                                                                                                                                              │
│ uwsgi   File "/app/dojo/api_v2/serializers.py", line 1600, in save                                                                                                                                │
│ uwsgi     test, finding_count, closed_finding_count, test_import = importer.import_scan(scan, scan_type, engagement, lead, environment,                                                           │
│ uwsgi                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                           │
│ uwsgi   File "/app/dojo/importers/importer/importer.py", line 300, in import_scan                                                                                                                 │
│ uwsgi     parsed_findings = parser.get_findings(scan, test)                                                                                                                                       │
│ uwsgi                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                       │
│ uwsgi   File "/app/dojo/tools/gitlab_dep_scan/parser.py", line 23, in get_findings                                                                                                                │
│ uwsgi     return self.get_items(tree, test)                                                                                                                                                       │
│ uwsgi            ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                       │
│ uwsgi   File "/app/dojo/tools/gitlab_dep_scan/parser.py", line 41, in get_items                                                                                                                   │
│ uwsgi     item = get_item(node, test)                                                                                                                                                             │
│ uwsgi            ^^^^^^^^^^^^^^^^^^^^                                                                                                                                                             │
│ uwsgi   File "/app/dojo/tools/gitlab_dep_scan/parser.py", line 49, in get_item                                                                                                                    │
│ uwsgi     if vuln['category'] != 'dependency_scanning':                                                                                                                                           │
│ uwsgi        ~~~~^^^^^^^^^^^^                                                                                                                                                                     │
│ uwsgi KeyError: 'category'

**Sample scan files**
[gemnasium-dependency_scanning-report-simplify.txt](https://github.com/DefectDojo/django-DefectDojo/files/10880933/gemnasium-dependency_scanning-report-simplify.txt)

**Screenshots**

**Additional context** (optional)

**Comment by damiencarol** [comment]
thank you for providing a report, I will work on a fix for this.

**Comment by manuel-sommer** [comment]
I tested this, it works fine. Please close this @mtesauro
