### ISSUE TITLE
Empty is not a valid openapi 3.0 schema enum value for date-time and date fields

### ISSUE THREAD

**Issue by jozseftiborcz** [DefectDojo/django-DefectDojo#7760]
**Bug description**
OpenApi specification from (https://demo.defectdojo.org/api/v2/oa3/schema/?format=yaml) contains the following schema definition:  
[...]
/api/v2/findings/:
    get:
      operationId: findings_list
      parameters:
[...]
      - in: query
        name: created
        schema:
          type: string
          format: date-time
          nullable: true
          enum:
          - ''
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
Here the empty enum value is not allowed...
Or at least openapi-generator-cli validate -i api.yaml  complains that 
[...]
	- attribute paths.'/api/v2/findings/'(get).parameters.[created].schemas.enum=`` is not of
	  type `date-time`
After removing the empty enum value (- '') the validation succeeded and I was able to generate a client.

**Expected behavior**
I expect without further manual modification of the download yaml openapi schema to generate an api client, 
Note: swagger 2.0 api endpoints works as expected, only oa3 has this bug.

**Environment information**
 - Tested with defectdojo demo site (api version: 2.9.2)

**Some hints**
- The problematic part is with DateRangeFilter in Filters.py:364. As '' valus refers to any date it can be the default value for date/date-time filters. However, for MetricsDateRangeFilter the '' value refers to 'Past 30 days'.
- A quick solution would be to remove format specifier from date/date-time fields with empty enum value.
- Or just make such fields are all nullable (that is already true for date-time but not for date fields) and remove empty enum anyway. In this case the missing field can be rendered as given with empty enum.

**Comment by damiencarol** [comment]
@Maffooch check the "hints", it seams there is easy fix here.

**Comment by kiblik** [comment]
I suppose this issue can be closed. Fixed in [2.25.0](https://github.com/DefectDojo/django-DefectDojo/releases/tag/2.25.0)
