### ISSUE TITLE
Error calculating hash-value for findings

### ISSUE THREAD

**Issue by sirferl** [DefectDojo/django-DefectDojo#780]
Please use the following template when submitting issues: (If this is a security issue, then review the [disclosure policy](https://github.com/DefectDojo/django-DefectDojo/blob/master/SECURITY.md) and submit via our security reporting program.

### Issue Type 
- [ x] Bug
- [ ] Enhancement

### Description
The code for calculating the hashvalue has an error in dojo/models.py.
If it is a dynamic finding and there are no endpoints,  the hashvalue is always the same.
Here is the code. hash_string is always set to the last endpoint.

 _def get_hash_code(self):
        hash_string = self.title + str(self.cwe) + str(self.line) + str(self.file_path)

        if self.dynamic_finding:
            endpoint_str = ""
            for e in self.endpoints.all():
                endpoint_str += str(e)
             hash_string = endpoint_str
        hash_string = hash_string.decode('utf-8').strip()
        return hashlib.sha256(hash_string.encode('utf-8')).hexdigest()_

I replaced the line after the for statement and then it calculated correct hashvalues:
hash_string = hash_string + endpoint_str

### Operating System 
Please include the version number (ex: Ubuntu 16.04)
Ubuntu 18.04.1
### Install

- [ x] setup.bash
- [ ] docker

### DefectDojo Version
1.5.3

### Steps to Reproduce
Upload findings with different titles, that are dynamic and have no endpoints.

**Comment by aaronweaver** [comment]
Fixed in dev.

**Comment by sirferl** [comment]
Thank you.
