### ISSUE TITLE
Add feature to Detect Secrets Scan parser

### ISSUE THREAD

**Issue by adrianasantex** [DefectDojo/django-DefectDojo#7818]
Hi, I would like to implement a feature in the "Detect Secrets Scan" parser. It consist on the following: 

- Detect Secrets have a field in the report that match "is_secret". This field is for marking false positives when detecting a secret in the code. 
- I would like to upload those secrets which are marked as FPs in DefectDojo. It will be very useful for analyze the patterns and obtain metrics. 

The question is, could I develop this feature on the "Detect Secrets Scan" parser and open a PR?

**Comment by mtesauro** [comment]
@damiencarol Thoughts on ^

Just pinged our most expert contributor on parsers.  Generally speaking, we like it when parsers get more accurate but will defer to Damien about your specific suggestion.

If you do end up creating a PR, please look at this first:  https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/CONTRIBUTING.md

**Comment by manuel-sommer** [comment]
I guess you can generate a PR @adrianasantex and extend the test coverage with the PR.

**Comment by manuel-sommer** [comment]
If you provide a sample file, I can also help you

**Comment by mtesauro** [comment]
@adrianasantex @manuel-sommer 
We have a detect-secrets parser already? Isn't this the same thing?
https://documentation.defectdojo.com/integrations/parsers/file/detect_secrets/
