### ISSUE TITLE
Change import size

### ISSUE THREAD

**Issue by giveen** [DefectDojo/django-DefectDojo#7831]
![image](https://user-images.githubusercontent.com/1180939/225650914-2d949dcb-d6b1-4a05-9a78-c6b6dd1c8924.png)

How do I change this to allow a greater than 100MB size?

**Comment by mtesauro** [comment]
It's in the settings - best way is to 'override' this in local_settings.py or use an environmental variable.

The setting is: DD_SCAN_FILE_MAX_SIZE at https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/settings/settings.dist.py#L256

Specifics on configuring DefectDojo (depending on how you've deployed which wasn't provided in your issue) is at https://documentation.defectdojo.com/getting_started/configuration/

Note: If you have a service fronting DefectDojo (Nginx,  load balancer) settings of those may also need to be adjusted.  Without deploy details, it's impossible to give more specific details.

**Comment by giveen** [comment]
> DD_SCAN_FILE_MAX_SIZE

I set to 150 in my local_settings, my report is 128, gives same error.
