### ISSUE TITLE
Limited API

### ISSUE THREAD

**Issue by feeltheajf** [DefectDojo/django-DefectDojo#785]
### Issue Type 
- [ ] Bug
- [x] Enhancement

### Description

There was a similar problem with API v1, where API was limited in methods in comparison to DefectDojo - [API Parity with DefectDojo](https://github.com/DefectDojo/django-DefectDojo/issues/171). Currently, API v2 is limited as well, for instance, methods for deleting scan/engagement/product are not available. Is it planned to add support of these methods as well?

**Comment by feeltheajf** [comment]
As a temprorary workaround I added mixins.DestroyModelMixin to dojo/api_v2/views.py to make DELETE API method available for engagements. All related findings are removed as well. However, I am waiting for proper solution as well

```
class EngagementViewSet(mixins.ListModelMixin,
                        mixins.RetrieveModelMixin,
                        mixins.UpdateModelMixin,
                        mixins.DestroyModelMixin,
                        mixins.CreateModelMixin,
                        viewsets.GenericViewSet):
```

**Comment by aaronweaver** [comment]
API methods are added as the community needs them. If there is a missing API feel free to submit a PR.

**Comment by feeltheajf** [comment]
Ok, thanks, I will check everything one more time and make a PR
