### ISSUE TITLE
Deduplication not working

### ISSUE THREAD

**Issue by domcar** [DefectDojo/django-DefectDojo#7867]
**Problem description**
I added some ENV VARs to the dojo deployment to make use of deduplications, unfortunately is not appearing to be working

**Steps to reproduce**
I added the following env vars via chart:
```yaml
extraConfigs:
  DD_DEDUPLICATION_ALGORITHM_PER_PARSER: |
    {
    "gitleaks":"DEDUPE_ALGO_HASH_CODE",
    "trivy-image":"DEDUPE_ALGO_HASH_CODE",
    "kube-hunter":"DEDUPE_ALGO_HASH_CODE",
    "kubeaudit":"DEDUPE_ALGO_HASH_CODE",
    "semgrep":"DEDUPE_ALGO_HASH_CODE",
    "zap-api-scan":"DEDUPE_ALGO_HASH_CODE"
    }
  DD_HASHCODE_FIELDS_PER_SCANNER: |
    {
    "gitleaks": ["title", "severity"],
    "trivy-image": ["title", "severity"],
    "kube-hunter": ["title", "severity"],
    "kubeaudit": ["title", "severity"],
    "semgrep": ["title", "severity"],
    "zap-api-scan": ["title", "severity"]
    }
```
But still also the Endpoint is being used for duplicates.

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X ] Kubernetes
- [ ] GoDojo

**Comment by alexandrelimait** [comment]
did you fix it somehow? I have the same issue

**Comment by domcar** [comment]
Nope, still nothing

**Comment by Gby56** [comment]
Hey ! I'm pretty familiar with these features, I wrote the one for the fields. For the algorithm, definitely you're not using the right value, that's the variable name, you should use `unique_id_from_tool` or `legacy` or `hash_code` or `unique_id_from_tool_or_hash_code`

**Comment by alexeykond** [comment]
Hi. Did anyone manage to override hashcode fields for gitleaks? 
HASHCODE_FIELDS_PER_SCANNER map doesn't contain 'Gitleaks Scan' item for some reasons and DD_HASHCODE_FIELDS_PER_SCANNER env variable cannot override the map.
settings.dist.py:
`if len(env('DD_HASHCODE_FIELDS_PER_SCANNER')) > 0:
    env_hashcode_fields_per_scanner = json.loads(env('DD_HASHCODE_FIELDS_PER_SCANNER'))
    for key, value in env_hashcode_fields_per_scanner.items():
        if key in HASHCODE_FIELDS_PER_SCANNER:
            print("Replacing {} with value {} from env var DD_HASHCODE_FIELDS_PER_SCANNER".format(key, value))
            HASHCODE_FIELDS_PER_SCANNER[key] = value`

**Comment by Gby56** [comment]
I might want to make a PR to change that environment variable behavior so that it just injects the key value without checking for the key presence

**Comment by manuel-sommer** [comment]
The PR was merged, could you please close this issue @mtesauro ?
