### ISSUE TITLE
Scan import tagging does not work in API v2

### ISSUE THREAD

**Issue by feeltheajf** [DefectDojo/django-DefectDojo#787]
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description
Tags are not shown in DefectDojo after scan import using API v2. It seems that they are not saved in DefectDojo backend. Solution described below worked fine for me

### Operating System 
CentOS 7.5

### Install

- [x] setup.bash
- [ ] docker

### DefectDojo Version
1.5.3.0

### Steps to Reproduce
- Upload any scan using API v2 (set "tags" field as well)

### Possible solution
Add missing tags field

**dojo/api_v2/serializers.py**
_ImportScanSerializer.save_

```
test.save()
test.tags = ','.join(data['tags'])
```

**Comment by aaronweaver** [comment]
I'm pretty sure this is fixed in dev.

**Comment by feeltheajf** [comment]
Ok, thanks, I will check it
