### ISSUE TITLE
Feature / Helper Tool - defect_dojo_docker_wrapper.sh

### ISSUE THREAD

**Issue by ninp0** [DefectDojo/django-DefectDojo#7878]
I wrote a wrapper for administering DefectDojo in a Docker environment - it's helpful for me, perhaps others as well...would there be interest in having it available in the official repo or is there some utility I should be using that behaves similarly?

https://gist.github.com/ninp0/c96910d9f790da51fbd8ad7559763a5f

**Comment by manuel-sommer** [comment]
Hi @ninp0 , I am interested. Maybe you can make a PR in the official repo, but I don't know if it will be merged. What is it doing exactly?

**Comment by mtesauro** [comment]
@ninp0 I'd love to see a PR into the community contrib repo at https://github.com/DefectDojo/Community-Contribs

This looks cool but probably not right for the DefectDojo repo.

**Comment by ninp0** [comment]
All set PR submitted via DefectDojo/Community-Contribs/pull/44

**Comment by ninp0** [comment]
@manuel-sommer - It effectively allows for various tasks, tailing logs, upgrading, backing up, dropping into a container's shell, etc.  My brain holds too much stuff so it's easier to use the wrapper script.

```
$ defect_dojo_docker_wrapper.sh 
USAGE: /usr/local/bin/defect_dojo_docker_wrapper.sh <
        list_containers || 
        start postgres-redis*|postgres-rabbitmq|mysql-redis|mysql-rabbitmq || 
        stop || 
        restart postgres-redis*|postgres-rabbitmq|mysql-redis|mysql-rabbitmq || 
        deploy <docker hub username> || 
        container_logs celerybeat|celeryworker|nginx|uwsgi|mysql|rabbitmq|mailhog || 
        backup_db || 
        upgrade || 
        destroy || 
        reset_password USERNAME || 
        shell celerybeat|celeryworker|nginx|uwsgi|mysql|rabbitmq|mailhog
```

**Comment by manuel-sommer** [comment]
I gotta take a look, thank you.

**Comment by manuel-sommer** [comment]
Can we close this then @mtesauro ?

**Comment by mtesauro** [comment]
Sure thing. Thanks for the PR in community contribs
