### ISSUE TITLE
Error in calling bubblechart code on dashboard

### ISSUE THREAD

**Issue by sirferl** [DefectDojo/django-DefectDojo#789]
### Issue Type 
- [ x] Bug
- [ ] Enhancement

### Description
By chance I detected the errors in the nginx errorfile and than realized that the weekly activity chart on the dashboard is empty.
Dashboard tries to call the following files:
/static/JUMFlot/JUMFlot.min.js
/static/JUMFlot/jquery.flot.mouse.js
/static/JUMFlot/jquery.flot.bubbles.js

These files have a different location on my system:
/static/JUMFlot/javascripts/JUMFlot.min.js
/static/JUMFlot/javascripts/jquery.flot.mouse.js
/static/JUMFlot/javascripts/jquery.flot.bubbles.js

I changed the respective lines in dojo/templates/dojo/dashboard.html and the error disappears and the chart is filled with bubbles ( oh, how I love bubbles...)

### Operating System 
Ubuntu 18.04.1

### Install

- [x] setup.bash
- [ ] docker

### DefectDojo Version
1.5.3

### Steps to Reproduce
Access the Dashbaord
### Console Logs (optional)
2018/10/19 10:53:37 [error] 11255#11255: *24 open() "/opt/dojo/django-DefectDojo/static/JUMFlot/JUMFlot.min.js" failed (2: No such file or directory), client: 10.239.132.52, server: defectdojo, request: "GET /static/JUMFlot/JUMFlot.min.js HTTP/1.1", host: "10.237.239.38", referrer: "http://10.237.239.38/dashboard"
2018/10/19 10:53:37 [error] 11255#11255: *24 open() "/opt/dojo/django-DefectDojo/static/JUMFlot/jquery.flot.mouse.js" failed (2: No such file or directory), client: 10.239.132.52, server: defectdojo, request: "GET /static/JUMFlot/jquery.flot.mouse.js HTTP/1.1", host: "10.237.239.38", referrer: "http://10.237.239.38/dashboard"
2018/10/19 10:53:37 [error] 11255#11255: *24 open() "/opt/dojo/django-DefectDojo/static/JUMFlot/jquery.flot.bubbles.js" failed (2: No such file or directory), client: 10.239.132.52, server: defectdojo, request: "GET /static/JUMFlot/jquery.flot.bubbles.js HTTP/1.1", host: "10.237.239.38", referrer: "http://10.237.239.38/dashboard"

**Comment by aaronweaver** [comment]
Thanks, will fix it. Your comment made me laugh, "oh, how I love bubbles."

**Comment by sirferl** [comment]
You're welcome. We all need a laugh from time to time, don't we?
