### ISSUE TITLE
AWS Inspector findings via AWS Security Hub

### ISSUE THREAD

**Issue by daniel-laszlo** [DefectDojo/django-DefectDojo#7914]
**Scanner Name**
AWS Inspector findings via AWS Security Hub. https://docs.aws.amazon.com/inspector/latest/user/securityhub-integration.html

DefectDojo is treating all scans coming from Security Hub the same way - but there are multiple types coming from different products (defined in the ProductName/ProductArn field) field. For us the most important would be Inspector.

**Sample File**

[securityhub_inspector.json.txt](https://github.com/DefectDojo/django-DefectDojo/files/11112493/securityhub_inspector.json.txt)

**Comment by manuel-sommer** [comment]
@daniel-laszlo 
So what is your expected result? Do you want the findings to list the result of ProductName and ProductArn?

**Comment by daniel-laszlo** [comment]
Hey @manuel-sommer ,

Thank you so much for your response. The ideal result is that if ProductName = "Inspector", then we parse more data from the JSON specific to Inspector findings. For us the most important would be to have the following fields:

```
cve = Finding.Vulnerability.Id
mitigation = Finding.Vulnerability.VulnerablePackages.Remediation
tags = Finding.Resources.Tags
```

**Comment by manuel-sommer** [comment]
Hi @daniel-laszlo,

I am preparting a PR. I have two questions:

- Could you provide an example json which includes tags?
- If you retrieve the findings from AWS Security Hub, how does it work: Do you then retrieve either the findings of an enabled AWS Security Hub Standard or Inspector or a summary of all enabled (AWS Security Hub Standard and Inspector)?  If the output is a summary of everything, could you provide such a json file?

**Comment by daniel-laszlo** [comment]
Hey @manuel-sommer ,

thank you for the PR!

- there is an example on AWS official documentation, do you think you can use it? If not, let me know. https://docs.aws.amazon.com/inspector/latest/user/securityhub-integration.html
- The only vulnerability related data that we have in Security Hub is Inspector findings. The rest we don't want to ingest into DefectDojo.

**Comment by manuel-sommer** [comment]
You can close the Issue @daniel-laszlo
