### ISSUE TITLE
ssl: certificate_verify_failed when trying to configure SonarQube tool configuration

### ISSUE THREAD

**Issue by gtaboadela** [DefectDojo/django-DefectDojo#7917]
**Problem description**
When I'm setting up SonarQube tool configuration to run an API import scan, I'm getting the following error:

sslerror(sslcertverificationerror(1, '[ssl: certificate_verify_failed] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

Based in the [documentation](https://documentation.defectdojo.com/integrations/parsers/api/sonarqube/) 

"Note:: If https is used for the SonarQube, the certificate must be trusted by the DefectDojo instance."

The SSL Certificate of SonarQube is signed by LetsEncrypt (Chain: ssl cert > R3 > ISRG Root X1)  Can you provide some guidance on how to make this certificate/CA trusted by the DefectDojo instance?

Already tried upgrading ca-certs in ubuntu and python3-certifi packages with no luck. 

**Steps to reproduce**
1. Go to 'Configuration', Tool Configuration, Add tool configuration
2. Set up Tool Configurtion for Sonarqube 
3. Click Submit

"HTTPSConnectionPool(host='sonar.emerios.com', port=443): Max retries exceeded with url: /api/components/search?qualifiers=TRK (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))) "

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [ ] Kubernetes
- [X] GoDojo

**Environment information**
 - Operating System: Ubuntu 22.04
 - DefectDojo version 2.8.14

**Comment by guerreroag12** [comment]
im having this same issue

**Comment by manuel-sommer** [comment]
You could try to disable session with verify = False here: https://github.com/DefectDojo/django-DefectDojo/blob/d698a7a1ff2a914754a541140b236dd3092d7e8e/dojo/tools/api_sonarqube/api_client.py#L45
https://www.geeksforgeeks.org/how-to-disable-security-certificate-checks-for-requests-in-python/

You can close this @mtesauro
