### ISSUE TITLE
MobSF Scan reports are not deduplicated - Missing deduplication algorithm

### ISSUE THREAD

**Issue by ghost** [DefectDojo/django-DefectDojo#7936]
Hello dear developers!

Seems like that something went wrong with deduplication of MobSF Scanner.

DefectDojo version is `2.21.0`.

Celery is working and green.

I have enabled deduplication and max duplicates is set to `0`.

When I run in uwsgi: `python3 manage.py dedupe` MobSF Scanner reports is not deduplicated, and I have a lot of duplicates:

![test](https://user-images.githubusercontent.com/125442562/229735894-e6674128-2aea-438c-9013-da62f7eef02e.png)

Thanks in advance!

**Comment by MukulG27** [comment]
I am facing the same issue. When this did not work, I tried to use the system defined deduplication but it works inconsistently as some findings have filepath and line number fields as null.

**Comment by mtesauro** [comment]
Ghost user has been deleted so I'll reply to @MukulG27 

I've never changed the default of 2 max duplicates, but that will have no effect on how duplicates are determined.

Dedup is run whenever findings are imported so I'm not sure why the original issue submitter was using the `python3 manage.py dedupe` - I've never had to use this to do deduplication.

You (MukulG27)  don't say which version you're using so I'll assume you're using the latest release. The fields from the MobSF scan file that are used for dedup purposes by default are `'Mobsfscan Scan': ['title', 'severity', 'cwe'],` see [here](https://github.com/DefectDojo/django-DefectDojo/blob/e7d9f715fa5c6405cf0d4c7465883d002a48a338/dojo/settings/settings.dist.py#L1192).

If you adjust those in settings.py, you can change the fields that are used to dedup to match the situation you are facing.

The ability to alter the dedup fields allows you to make the deduplication match your needs.

**Comment by MukulG27** [comment]
@mtesauro I don't quite understand what you mean by 2 max duplicates please elaborate a bit.
Firstly, I would like to point out that I am using MobSF which is a separate tool from Mobsfscan and both have different scan types. There is deduplication present for Mobsfscan but not for MobSF. This is also the case with another tool by the name of Trufflehog. There might be other scan types missing as well.
Secondly, I am importing the scans using an API Call and accoridng to this comment by @Maffooch https://github.com/DefectDojo/django-DefectDojo/issues/1478#issuecomment-521350280, I should not have to enable the deduplication in system settings and just pass skip_duplicates=true in the api call. But this is not working

**Comment by Maffooch** [comment]
@MukulG27 if there is not a deduplication configuration for MobSF, then it will be using the defaults
```
 ['title', 'cwe', 'line', 'file_path', 'description']
```
as you mentioned, that has been inconsistent with null file paths and line numbers. Solution here is to create a deduplication algorithm for MobSF. Unfortunately, there are many scanners that do not have deduplication algorithms as the functionality is newer than many of the parsers we have. 

> Secondly, I am importing the scans using an API Call and accoridng to this comment by @Maffooch https://github.com/DefectDojo/django-DefectDojo/issues/1478#issuecomment-521350280, I should not have to enable the deduplication in system settings and just pass skip_duplicates=true in the api call. But this is not working

This is four years old now and is likely not applicable

**Comment by manuel-sommer** [comment]
Can we close this @mtesauro ?
