### ISSUE TITLE
KICS partial import

### ISSUE THREAD

**Issue by Acsigen** [DefectDojo/django-DefectDojo#7966]
**Bug description**
When importing a KICS json report, not all vulnerabilities are displayed in DefectDojo when compared to html version of KICS.

**Steps to reproduce**
1. Perform KICS scan with output as JSON and HTML
2. Import the report to a DefectDojo project
3. Compare the number of findings between DefectDojo and KICS HTML

**Expected behavior**
The number of vulnerabilities should be the same

**Deployment method** *(select with an `X`)*
- [x] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Ubuntu 22.04
 - DefectDojo version: 2.21.0

**Screenshots**
KICS HTML report:
![image](https://user-images.githubusercontent.com/13287878/231697013-da624512-fab8-4f26-9281-4e1d87701db7.png)

DefectDojo Vulnerabilities count after importing the KICS report:
![image](https://user-images.githubusercontent.com/13287878/231697274-06a94e94-921c-42ca-a2c2-3606a4fa3046.png)

**Workaround**:
Set the output format of KICS to Gitlab SAST and then import it in DefectDojo as Gitlab SAST.

**Comment by security101** [comment]
Yes, I have the same observation. 22 distinct findings within the json file but only 7 imported / presented running DD v2.24.1 (docker-compose)

**Comment by manuel-sommer** [comment]
Hey @security101 and @Acsigen ,

could you please provide a sample report?

**Comment by Acsigen** [comment]
> Hey @security101 and @Acsigen ,
> 
> could you please provide a sample report?

Sadly I don't have a report now. I will upload one as soon as I have a new project comming my way.

**Comment by manuel-sommer** [comment]
Is this the right link @Acsigen ?
https://github.com/Checkmarx/kics

**Comment by manuel-sommer** [comment]
@quirinziessler maybe kics is interesting for you?

**Comment by manuel-sommer** [comment]
could you close this PR please @mtesauro
