### ISSUE TITLE
Integration with AAD doesn't work. Got message when login with AAD Your credentials aren't allowed.

### ISSUE THREAD

**Issue by sergeymeleschenko** [DefectDojo/django-DefectDojo#7967]
![image](https://user-images.githubusercontent.com/34446179/231703812-ea1cd39c-8123-412d-803d-984ec52e6cad.png)

Integration with AAD doesn't work. Got message when login with AAD Your credentials aren't allowed.

DD v. 2.18.4 ( release mode )

Deployment method Docker Compose. OS Ubuntu 20.04

Steps to reproduce:

Open DD
Click Login with AAD
Enter credentials
Got message Your credentials aren't allowed

**Comment by Jon-the-2nd** [comment]
Got the same problem. Were you able to fix this?

**Comment by manuel-sommer** [comment]
Did you folllow this documentation: https://defectdojo.github.io/django-DefectDojo/integrations/social-authentication/#azure-ad-configuration ?

**Comment by Jon-the-2nd** [comment]
We followed the steps and restarted DefectDojo. However, at some point we had to generate a new secret for the app registration in Azure, add the new secret to the `local_settings.py` file, build (`dc-build.sh`) and then restart. Now it works.

**Comment by manuel-sommer** [comment]
Then, I guess we can close this @mtesauro.

**Comment by yunusmrcoban** [comment]
@Jon-the-2nd hey, can you tell me step by step how he solved it?

**Comment by Jon-the-2nd** [comment]
@yunusmrcoban, follow the steps in the documentation. At some point, if you feel like you're sure you've got the right client secret but it still doesn't work, go to the app registration in Azure and create a new secret (https://learn.microsoft.com/en-us/entra/identity-platform/quickstart-register-app?tabs=certificate#add-credentials). Add the new secret in `local_settings.py`, then build using `dc-build.sh`. I'm afraid that's all I can tell you. Hope it helps.

**Comment by yunusmrcoban** [comment]
@Jon-the-2nd Hey,

I solved the problem, thank you.
