### ISSUE TITLE
Check unittest

### ISSUE THREAD

**Issue by aaronweaver** [DefectDojo/django-DefectDojo#797]
@Nilix007 would you mind checking to see why [these](https://travis-ci.org/aaronweaver/django-DefectDojo/jobs/447837496) are failing? I'm not that familiar with the new feature set and unsure why it's failing.

FAIL: test_duplicates_skipped (dojo.unittests.test_apiv2_scan_import_options.ScanImportOptionsTest)

FAIL: test_only_closed_iff_not_duplicate (dojo.unittests.test_apiv2_scan_import_options.ScanImportOptionsTest)

FAIL: test_originals_of_skipped_duplicates_are_not_closed (dojo.unittests.test_apiv2_scan_import_options.ScanImportOptionsTest)

**Comment by Nilix007** [comment]
I found the issue.  PR is up :)
