### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by vlados31999** [DefectDojo/django-DefectDojo#7970]
Good afternoon 
Tell me how to change the ip address from localhost to another

**Comment by oluapG** [comment]
Why do you need change ? what you want to do ? 

You can edit settings.dist.py in django-DefectDojo/dojo/settings... change DD_SITE_URL.

**Comment by vlados31999** [comment]
> Зачем вам нужны перемены? что ты хочешь делать ?
> 
> Вы можете отредактировать settings.dist.py в django-DefectDojo/dojo/settings... изменить DD_SITE_URL.

Hi
After the change, it still runs on ip 127.0.0.1 
![image](https://user-images.githubusercontent.com/104201717/234365165-e28de0e9-8eda-4794-8d50-282542886d12.png)

**Comment by oluapG** [comment]
Are version you deploy ? 

If you deploy a Docker ? 

You can edit settings.dist.py in django-DefectDojo/dojo/settings... change DD_SITE_URL.

If you deploy a Godojo ? 

In this link below, you have scripts:

https://github.com/DefectDojo/godojo/tree/master/docs-and-scripts 

and inside the script dojo-start you can see this information:

# Startup DefectDojo with 'runserver' on port 8000
screen -S dojo -D -m /bin/bash -c 'source /opt/dojo/bin/activate && python manage.py runserver 0.0.0.0:8000' &

echo "DefectDojo should now be available on port 8000 e.g. http://127.0.0.1:8000 or http://[your IP or hostname]:8000"

**Comment by manuel-sommer** [comment]
Hi @vlados31999 ,
could you please ask this in the owasp channel?
You can close this @mtesauro
