### ISSUE TITLE
Findings sorting is giving incorrect order 

### ISSUE THREAD

**Issue by sahil3112** [DefectDojo/django-DefectDojo#7988]
**Bug description**

When I sort the findings in the test engagement by severity, then the order of the vulnerability is Medium->Low->High->Critical (
Incorrect order), and when I again sort by severity then the order of vulnerability is Critical->High->Low->Medium

**Steps to reproduce**

1. Create an Engagement in DD
2. Upload any tool report in DD
3. Go to the test findings 
4. Change the page size to all(We can see the findings in the correct order Critical->High->Medium->Low->Info)
![image](https://user-images.githubusercontent.com/43255158/233024866-f0dd8312-9b2c-40d1-b9c9-10cdcdb80d2b.png)
I am not sure what is the use of the 2 sort button that is highlighted in the blue box

5. Sort the findings by severity

![image](https://user-images.githubusercontent.com/43255158/233025406-183a0070-c24c-4ced-9482-574c27a25af5.png)

![image](https://user-images.githubusercontent.com/43255158/233025487-ea575549-ab25-4f9b-9089-c8488d4b492f.png)

**Expected behavior**

When we sort the findings by severity then They will sort in the correct order
Critical->High->Medium->Low->Info
Info->Low->Medium->high->Critical

**Deployment method** *(select with an `X`)*
- [ X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Comment by manuel-sommer** [comment]
Hi @mtesauro,
this fix was merged, could you please close this?
