### ISSUE TITLE
Import Scan using Black Duck Api results in error

### ISSUE THREAD

**Issue by rsudhad** [DefectDojo/django-DefectDojo#7989]
Hi,

Import scan using Black Duck api results in following error.

**An exception error occurred during the report import:"resource name 'versions' not found in available resources"**

![image](https://user-images.githubusercontent.com/131010169/233027044-5cd49a8c-b14c-4ca9-af81-3bb8589fd99b.png)

Installation: Docker compose
Version : latest(v. 2.21.1)

Black duck configuration added under tools config .
Api scan configuration added under project settings.

Authentication to blackduck works well but api/projects results in the above issue.

**Comment by manuel-sommer** [comment]
Hi @rsudhad could you pleaes add a sample file to reproduce this issue?

**Comment by manuel-sommer** [comment]
I guess this can be closed @mtesauro as it seems like a stale isssue. There was no response.
