### ISSUE TITLE
An exception error occurred during the report import:'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by pshitnalli** [DefectDojo/django-DefectDojo#7992]
Hello DefectDojo Team, 

I was using this DefectDojo for the firt time. From their official site of DefectDojo Github , I could successfully install, build and open the defectdojo from the browser with "http://localhost:8080" and with generated admin password, I could successfully login. 

After creating a product and active engagement, I wanted to import generated Nessus Scan (.nessus) report file into DefectDojo for specific created product. But when I try to import I'm facing an issue of **"An exception error occurred during the report import:'NoneType' object has no attribute 'split'"** 

Could you please help me in understading where is this issue coming from and what's the possible solution.? 

Version of DefectDojo being used: v. 2.21.1 ( release mode )

![DefectDojo FIle Import 'NoSplit' Error](https://user-images.githubusercontent.com/116246347/233321829-262a447f-8fb3-4a9a-aa93-9d3c3764fead.jpg)

**Comment by mtesauro** [comment]
If memory serves, you need to use the .csv output from Nessus not the .nessus output.  I believe the parser expects the .csv format - at least that's what I've been using for quite some time.

A quick look at the parser code shows it supports only .csv and .xml formats - see https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/nessus/parser.py#L258

` return "Reports can be imported as CSV or .nessus (XML) report formats."`

**Comment by mtesauro** [comment]
@pshitnalli 
For this one:
> What do you mean by "If memory serves ..." ? Do I need to allocate any enough memory to my system ? I'm currently using Ubuntu 22.04 LTS VM with enough memory (4 CPUs, 100 GB disk allocated).

I basically meant if I'm remembering correctly aka recalling facts from my brain.

> Well, when scan report is being imported, ".nessus" is one of supported format . Hence, I was using .nessus files of Nessus Scanned system. (Pls find attached screenshot)

Sorry, I've been using Nessus long enough that I got the changing file formats mixed up in my head. A while back .nessus was it's own format (early 2005 or so) and that's what I was getting confused. There used to be an option to download a file with .xml.  But you're correct, looks like the new .nessus file is XML based (if you scroll down the import file page, you'll eventually see this:
![image](https://user-images.githubusercontent.com/3422419/233465441-382f4dff-26d9-47c4-84dd-5b090b72525c.png)

> How to resolve this ? Resolving this issue is very much highly appreciated.

Well, it appears my initial thought that you were using the wrong file type was incorrect.  This looks like it's probably a bug in the Nessus parser.

I'd suggest you open up a new issue (or edit #7995 ) and include the error message plus if you can provide an anonymized version of the file you're uploading, that will greatly help us figure out what's going on. Please don't send real data - and you can remove all but 1 or 2 findings to keep the example simple.  I've done that in the past - removed all but 2 issues in a tools output and then changed any sensitive data to bogus stuff like this [one](https://github.com/DefectDojo/sample-scan-files/tree/master/bugcrowd).

**Comment by pshitnalli** [comment]
@mtesauro Thanks for all your detailed response. I do understand from your response, there seems to be probably Nessus parser bug. 

Ok, since you've reopened this #7992, what I think, It's really good to update and share all piece of info here as we can trace back also. #7995 doesn't have much details, I request you to CLOSE it. 

Pls give me a day or two. I'll send anonymized data of Nessus, CSV file. I'll try to run Nessus on some dummy machines and share data. I'll get back to you and share all the files here. 

Please keep this #7992 Open until that time 🙂. 
Thank you.

**Comment by pshitnalli** [comment]
@mtesauro Matt, my another main concern was, if I wasn't able to import Nessus Scanned .nessus file in to defect Dojo that's fine. Basically, I'm unable to import possibly supported formats. 

I'm downloading Nessus Scanned file from our Enterprised Tenable site which provides report to Export in .html, .CSV and .pdf (leave .pdf as it doesn't support here). But at least with .CSV and .html ? And even I converted .CSV to .xlsx as well. No luck at all . One or other parsing issue 🙂.

**Comment by pshitnalli** [comment]
@mtesauro I was looking for some sample ".nessus" formatted file to send it to you. Actually, I wanted to scan really on a metaspoitable 2 intentionally vuln machine from Kali system and wanted to share generated .nessus file from Tenable site. But unfortunately I couldn't do that because of technical challenges. 

Meanwhile when I was searching, I came across this. Surprisingly and coincidently  , this sample ".nessus" file is updated by you only somewhere in year 2018. Could you please try parsing this sample .nessus file to DefectDojo and check ? 

[https://github.com/DefectDojo/sample-scan-files/blob/master/nessus/nessus_v_unknown.nessus](url)

**Comment by Fotkurz** [comment]
> https://github.com/DefectDojo/sample-scan-files/blob/master/nessus/nessus_v_unknown.nessus

Just pointing out, the link referenced is pointing toward the wrong url. (The issues page).

[https://github.com/DefectDojo/sample-scan-files/blob/master/nessus/nessus_v_unknown.nessus](https://github.com/DefectDojo/sample-scan-files/blob/master/nessus/nessus_v_unknown.nessus)

**Comment by pshitnalli** [comment]
Well, thanks for pointing to correct URL @Fotkurz . 

BTW, did this issue resolved in latest v2.22.0 by any chance ? Does parsing .nessus files work as expected in DefectDojo now ? 
Or, is it still in plan to fix this issue ? (somewhere in major release v3.0 ?

**Comment by mtesauro** [comment]
@pshitnalli  Do me a favor and try either of your files using the "Nessus WAS" test type. I had someone report that a .nessus file wasn't parsed by the current "Nessus" test type *but* was parsed by Nessus WAS.

We're wondering if Nessus has started to consolidate their output formats. At one point in time Nessus's output != Nessus WAS but that may have changed. We considering just making a single parser called "Tenable" or "Nessus" that can determine what type from Tenable is uploaded and parse according to try to make things simpler for DefectDojo users.

If you happen to have  an example file - one that you sanitize / anonymize / remove any sensitive info, that would really help us with the parser update. I don't currently have a license for Nessus/Tenable anything so we're relying on the community providing example files. 

Adding one to this issue would really help us get this sorted out.

**Comment by pshitnalli** [comment]
@mtesauro Thank you very much for the quick updates. 

I'll try with "Nessus WAS" as you suggested. As well, I completely agree with you specially on `Nessus's output != Nessus WAS`.
Nessus WAS is specifically for only if the Web Applications are being scanned using that WAS option. 
Our product is being mainly scanned using Gold Scan template of Nessus and output is only expected as Nessus (but not really as Nessus WAS). 

We much appreciate on part of DD team is planning to consider _"making a single parser called "Tenable" or "Nessus" that can determine what type from Tenable is uploaded and parse according to try to make things simpler for DefectDojo users."_

I'll try once more time to provide you anonymized version of Nessus report.

**Comment by pshitnalli** [comment]
@mtesauro Well, this time somehow I could successfully scan a Metaspoitable (damn vulnerable) machine from Tenable Nessus Community edition scanner and could get a proper ".nessus" report file for your assessment and debugging purpose. 
[MetaSploitable2_Scan_oet9kb.txt](https://github.com/DefectDojo/django-DefectDojo/files/11372342/MetaSploitable2_Scan_oet9kb.txt)

Please find attached file `MetaSploitable2_Scan_oet9kb.txt`. Change the extension of file from `.txt` to `.nessus` as ".nessus" files can't be attached here and not supported. Even that attached nessus report has good vulnerabilities count. May helpful good for assessment and debuggin
[MetaSploitable2_Scan_oet9kb.txt](https://github.com/DefectDojo/django-DefectDojo/files/11372357/MetaSploitable2_Scan_oet9kb.txt)
g.

**Comment by Fotkurz** [comment]
Could be something related to [line 181](https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/nessus/parser.py#L181) of the parser? It seems to be trying to .split() a None so the refs.text property is missing in the report, a simple conditional could fix the issue maybe.

**Comment by mtesauro** [comment]
FYI: This is nearly merged so keep an eye on #8072

**Comment by mtesauro** [comment]
Going to go ahead and close this - the merge is into the dev branch so it will be in 2.23.0 - first week of May.
