### ISSUE TITLE
Your credentials aren't after login with AAD

### ISSUE THREAD

**Issue by sergeymeleschenko** [DefectDojo/django-DefectDojo#7994]
image
Integration with AAD doesn't work. Got message when login with AAD Your credentials aren't allowed.

DD v. 2.18.4 ( release mode )

Deployment method Docker Compose. OS Ubuntu 20.04

Steps to reproduce:

Open DD
Click Login with AAD
Enter credentials
Got message Your credentials aren't allowed

**Comment by Jon-the-2nd** [comment]
Got the same problem. Were you able to fix this?

**Comment by sergeymeleschenko** [comment]
This issue is still present :( Can't find decision :(

пт, 10 лист. 2023, 12:59 користувач Jon ***@***.***> пише:

**Comment by manuel-sommer** [comment]
Could you please ask such things in the owasp slack channel?
please close this @mtesauro
