### ISSUE TITLE
An exception error occurred during the report import:'NoneType' object has no attribute 'split' #7992

### ISSUE THREAD

**Issue by pshitnalli** [DefectDojo/django-DefectDojo#7995]
@mtesauro - I'm just raising new request in follow up for the #7992. (An exception error occurred during the report import:'NoneType' object has no attribute 'split')

Actually you had closed the ticket. I'm not sure, once it's Closed, whether you guys get any notification or not. Since, I'm raising thee kind of tickets in Github for very first time. 

Please see my comments and various screenshots after your comment and closing it, Matt.

**Comment by mtesauro** [comment]
Closed per request of @pshitnalli
