### ISSUE TITLE
Azure SSO - HTTP/HTTPS 

### ISSUE THREAD

**Issue by oluapG** [DefectDojo/django-DefectDojo#8010]
I have provided Azure SSO but when I clicked in "Login with Azure" I received the error bellow:

ADSTS50011: The redirect URI 'http://xxxxx/azuread-tenant-oauth2/' specified in the request does not match the redirect URIs configured for the application '422****dd'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal.

The problem is redirect URI **'http://*** because Azure SSO is set to ***https://xxxxx/azuread-tenant-oauth2/***. ( It's not possible to put http in Azure SSO) 

Where I set this URI to send ***HTTPS*** instead of ***HTTP*** in defect dojo ? 

Deployment method (select with an X)

 Kubernetes
[X ] Docker
 setup.bash / legacy-setup.bash
Environment information
Deployment method (select with an X)

 Kubernetes
[X ] Docker

Operating System: Ubuntu 20.04

**Comment by oluapG** [comment]
I resolved put this variable inside the settings.py.

SOCIAL_AUTH_REDIRECT_IS_HTTPS = True

**Comment by hembhardwaj6** [comment]
I have installed opensource 2.55.4 version through helm chart and trying to enable login with azure AD, but after settings extraSecrets or extraConfigs or extraEnv, the button does not appear at all.
How to enble this as documentations is also not clear.
If it does not working with Helm installation then as least they should mention it.
