### ISSUE TITLE
Vulnerability Priority Score

### ISSUE THREAD

**Issue by ghost** [DefectDojo/django-DefectDojo#8015]
Some scanners have the ability to calculate a "Vulnerability Priority Score" - this score is typically a combination of the criticality of the vulnerability and the current threats. For example, Nessus/Tenable has a "Vulnerability Priority Rating" (VPR) that goes from 0.0 to 10.0, with 10 being the most critical. It could be very valuable to implement this in "Findings" and the individual "Parsers". There is probably a need to standardize this value, for example
- A value between 0.0-10.0.
- A value between 0-100
- Categorize with: Informational, Low, Medium, High, Critical

**Comment by mtesauro** [comment]
I'd look at #8072 as the Nessus parser is getting an update.

**Comment by manuel-sommer** [comment]
We standardize this in general in the parsers. Please close this @mtesauro
