### ISSUE TITLE
Error! Failed to create database

### ISSUE THREAD

**Issue by poobaisle** [DefectDojo/django-DefectDojo#802]
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description
When I try to install DefectDojo on the latest version of Kali (2018.4), I reach the point where the setup.bash script tries to install mysql-server and libmysqlclient-dev packages on top of the existing MariaDB. 
To ensure DB is present, I need to enter manually MySQL host, port, user, password but I cannot create the database name. Hereafter is what I get... I read other posts on MariaDB issues but it didn't help me.
Thank you

E: Package 'libmysqlclient-dev' has no installation candidate
E: Package 'mysql-server' has no installation candidate
Ensure application DB is present
MySQL host: localhost
MySQL port: 3306 
MySQL user (should already exist): root
Password for user: 
Database name (should NOT exist): Dojo_DB       
Enter password: 
mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'root'@'localhost''
Error! Failed to create database Dojo_DB. Check your credentials.

### Operating System 
VMWare version of Kali-Linux 2018.4

### Install

- [x] setup.bash
- [ ] docker

### DefectDojo Version
Latest version that I got on github

**Comment by poobaisle** [comment]
I would really appreciate if someone can spend 1 or 2 minutes to tell me if I am missing something here ? Thank you guys.

**Comment by heepspray** [comment]
@poobaisle I seem to remember overcoming the same problem, don't think this is a problem with DefectDojo. Try to google and solve the isolated error you are getting 'Access denied for user 'root'@'localhost''  - and run again. There are many potential solutions for this

https://stackoverflow.com/questions/41645309/mysql-error-access-denied-for-user-rootlocalhost

**Comment by tonnyhideyori** [comment]
I am facing this issue today

**Comment by jonan-dsouza** [comment]
I am facing the same issue.. Please assist with the Solution

**Comment by mtesauro** [comment]
Just wanted to raise 2 points on this issue from the perspective of the DefectDojo maintainers:

1. This project (DefectDojo) didn't create the Kali Linux package so can't really comment on how that works, what choices where made when packaging, etc.

2. I'm unsure what version of DefectDojo was packaged for Kali Linux but as of 2.36.0 we no longer support MySQL so it would be a good idea to file a bug against the Kali package so they are aware that MySQL isn't guaranteed to work going forward. We're not going to intentionally break support but we're also no longer going to test MySQL as part of our GH Actions/CICD testing.

I do agree with the previous commenters, this seems like permissions weren't setup correctly and any general documentation of fixing access to MySQL would likely help in this case.

**Comment by mtesauro** [comment]
@tonnyhideyori @jonan-dsouza :point_up:
