### ISSUE TITLE
Unable to upload CycloneDX vulnerability analysis detail without a recommendation

### ISSUE THREAD

**Issue by Driste** [DefectDojo/django-DefectDojo#8022]
**Bug description**
If I have a CycloneDx v1.4 SBOM with Vulnerabilities, and an analysis (example pulled from tests):
```yml
{
  "bomFormat": "CycloneDX",
  "specVersion": "1.4",
  ...
  "vulnerabilities": [
    ...
    {
      ...
      "analysis": {
        "state": "not_affected",
        "justification": "code_not_reachable",
        "response": ["will_not_fix", "update"],
        "detail": "An optional explanation of why the application is not affected by the vulnerable component."
      },
    }
  ]
}
```
This will not work unless the `.vulnerabilities[].recommendation` field exists or `.vulnerabilities[].analysis.detail` is removed.

**Steps to reproduce**
1. Grab the [test cyclonedx json sbom](https://github.com/DefectDojo/django-DefectDojo/blob/b2197f1cae1cfeaa1c87e0266d5d14374dd3c36e/unittests/scans/cyclonedx/valid-vulnerability-1.4.json)
2. Remove the `recommendation` key and value from the vulnerability.
3. Import or test the scan
4. Additional: You can also remove `advisory.detail` to get it to work again. 

**Expected behavior**
An `analysis` should be allowed without a `recommendation`.

There are probably a lot of other bugs in this parser as the cyclonedx schema is quite large and half the fields are optional.

**Comment by Driste** [comment]
I've had other issues with different uploads also:
  - Create a cyclonedx sbom+vulnerabilities from grype scanning `docker.io/library/ubuntu:latest` 
  ```bash
  grype docker:docker.io/library/ubuntu:latest -o cyclonedx-json > test/cyclonedx-sbom.json
  ```
  - The upload won't work (file validated using cyclonedx-cli).

**Comment by manuel-sommer** [comment]
Can you close this @mtesauro ?
