### ISSUE TITLE
Support of ThreatModeler Tool

### ISSUE THREAD

**Issue by gh0st27** [DefectDojo/django-DefectDojo#8054]
**Scanner Name**
ThreatModeler 
https://threatmodeler.com/threatmodeler/#threatmodeler

Threat Modeler is a automated threat modeling solution which automatically identify the security requirements and threats based on DFD diagram.

**Sample File**
[Security_Requirements_security_requirements.xlsx](https://github.com/DefectDojo/django-DefectDojo/files/11394044/Security_Requirements_security_requirements.xlsx)

**Comment by manuel-sommer** [comment]
Hi @gh0st27,

is there a way to configure the outputs of ThreatModeler?
e.g. Severity would be nice.

**Comment by manuel-sommer** [comment]
Any update on this @gh0st27 ?

**Comment by manuel-sommer** [comment]
I don't know if we still need this parser as there was only one request and no response within a whole month. Should we close this @mtesauro ?

**Comment by mtesauro** [comment]
Yes, XLSX is not a great file format to have to parse and this has gone quiet so closing for now.
