### ISSUE TITLE
Scan import through API returns a 'not valid JSON' error

### ISSUE THREAD

**Issue by bewell** [DefectDojo/django-DefectDojo#809]
### Issue Type 
- [X] Bug

### Description
I am having the python script which uploads the scan results to the Dojo server using API. From the documentation example I formed my request. The request looks like this:

```
print 'Importing the scan'
import_scan_url = 'https://defectdojo.company.net:443/api/v1/importscan/'

import_data_json = """
{
  "minimum_severity": "Info",
  "scan_date": """ + todays_date + """,
  "verified": false,
  "file": """ + file_for_importing + """",
  "lead": "",
  "tags": "",
  "active": false,
  "engagement": "/api/v1/engagements/5/",
  "resource_uri": "",
  "scan_type": ""
}
"""

post = requests.post(import_scan_url, headers=headers, data=import_data_json )
```

Unfortunately, the server returns this error:
`{"error": "Request is not valid JSON."}`

I'm not entirely sure what am I missing.

**Comment by aaronweaver** [comment]
Take a look at the slack channel or use the defectdojo api.
