### ISSUE TITLE
Custom CA 

### ISSUE THREAD

**Issue by downright-ux** [DefectDojo/django-DefectDojo#8095]
Hi we are using our own self made certs and wondering if there is a environment variable I can call to add in the CA certificate.
I'm able to mount the cert but unable to run update-ca-certificates in the container. I really didn't want to rebuild docker image with CA copied in. Is there anyway around this.
```
defectdojo@f95abdab0c66:/etc/ssl/certs$ update-ca-certificates
Updating certificates in /etc/ssl/certs...
rm: cannot remove 'ca-certificates.crt': Permission denied
```

**Comment by downright-ux** [comment]
I went ahead and ran the container as root, and update-ca-certificates , which work from within django-defectdojo-uwsgi-1.
Double checked this by install curl and hitting my Keycloak instance.
When trying in the browser I get the sign-in then the following message after filling out my Keycloak creds.

```
Authentication failed: HTTPSConnectionPool(host='keycloak.sdm', port=443): Max retries exceeded with url: /auth/realms/sdm/protocol/openid-connect/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')))

```

**Comment by dsever** [comment]
Take a look at the NOTE section  of the https://defectdojo.github.io/django-DefectDojo/integrations/social-authentication/#saml-20

**Comment by dsever** [comment]
@downright-ux does it help?

**Comment by downright-ux** [comment]
Yes sorry that worked

**Comment by downright-ux** [comment]
Yes this works fine thank you

**Comment by Stamka** [comment]
> Yes this works fine thank you

Hi! Can you explain me, what I need to do to fix this issue?
