### ISSUE TITLE
Findings Closed as "Mitigated / Inactive" after Reimport of identical results.json

### ISSUE THREAD

**Issue by danileau** [DefectDojo/django-DefectDojo#8100]
** Creating Issue, since Slack https://owasp-slack.herokuapp.com is down

**Bug-Description:**
I am currently using DefectDojo v.2.22.1 for my vulnerability management, running on Docker-compose and RHOS Openshift. 
I have noticed an issue when importing the trivy-findings-JSON file as a product using "/api/v2/reimport-scan/". 
Initially, all findings are imported correctly, and their status is set as "active." 
However, when I reimport the same file still using /api/v2/reimport-scan/, I observed that out of the 78 findings, 46 of them are being closed with the status "mitigated."
Since i've created scripts which scan in a weekly basis all of my repos and upload every result-files to DD, this is very problematic, since this behaviour implies that vulnerabilities have been fixed, but they are then being ignored but still putting the systems at risk.

**Details of the Requests:**
headers = {'accept': 'application/json', 'Authorization': f'Token {token}'}
data = {'scan_type': 'Trivy Scan', 'scan_date':f'{today}', 'minimum_severity': 'Low', 'product_type_name':'GIT Repository','product_name':f'{product_name}', 'engagement_name':f'{today}','auto_create_context':'true','tags':f'{project}', 'version':f'{today}', 'close_old_findings':'true', 'close_old_findings_product_scope':'true'}

I would expect this behaviour when i've successfully patched those 46 findings and would import now a new scanresult, where those now are missing compared to the first import - but not with the identical file.

**Questions:**
1. Why are findings being closed as "mitigated" on reimport instead of creating duplicates or being ignored after checking if the vulnerabilities are still present?
2. Shouldn't the reimport process verify the presence of vulnerabilities on the system and display them accordingly?
Please help me understand this behavior and suggest any possible solutions or workarounds to address this issue. Thank you.

**Steps to reproduce**
1. Scan a example Git-Repository for getting the findings with trivy: `trivy repository https://github.com/cloudfoundry/cf-java-client --format json --scanners vuln -q > trivy-cf-example.json`
2. Import this findings to DD: `curl -X 'POST'  'https://<Your-DD-Instance>/api/v2/reimport-scan/'  -H 'accept: application/json'  -H 'Authorization: Token <Your-Token>*  -H 'Content-Type: multipart/form-data'  -F 'scan_date=2023-05-12'  -F 'minimum_severity=Low'  -F 'scan_type=Trivy Scan'  -F 'file=@trivy-cf-example.json;type=application/json'  -F 'product_type_name=application'  -F 'product_name=CF-Example'  -F 'engagement_name=2023-05-12'  -F 'auto_create_context=true'  -F 'tags=CF'  -F 'close_old_findings=true'  -F 'close_old_findings_product_scope=true'  -F 'push_to_jira=false'  -F 'version=latest'` 
3. Check DD-Dashboard and the created Engagement on the new product: 
```
Name: 2023-05-12
Type: CI/CD
Lead: Admin User (admin)
Date: 12th May - 11th May
Lengt 11 month 29 days
Tests: 1
Active (Verified): 78 (0)
Mitigated: 0
Accepted: 0
All: 78 
Duplicated: 0
```

4. Repeat Step 2 with the exact same curl command
5. Check DD-Dashboard and the created Engagement on the new product - The Amount of the Active and Mitigated Findings changed
```
Name: 2023-05-12
Type: CI/CD
Lead: Admin User (admin)
Date: 12th May - 11th May
Lengt 11 month 29 days
Tests: 1
Active (Verified): **32(0)**
Mitigated: **46**
Accepted: 0
All: 78 
Duplicated: 0
```

**Expected behavior**
I would expect, that after a reimport of the identical results-file, nothing would be set to mitigated / inactive.

**Deployment method** *(select with an `X`)*
Reproduced with:
- [ X ] Docker Compose
- [ X ] Kubernetes / Redhat Openshift

**Environment information**
 - Operating System: Ubuntu 22.04.2 LTS
 - DefectDojo version: v 2.22.1

**Logs** 
No errors found in the Logs - May the 301 indicate an issue?

docker logs nginx container:
```
OST /api/v2/reimport-scan HTTP/1.1", host: "192.168.178.35:8080"
192.168.178.35 - - [12/May/2023:11:17:15 +0000] "POST /api/v2/reimport-scan HTTP/1.1" 301 0 "-" "curl/7.81.0" "-"
2023/05/12 11:17:27 [warn] 6#6: *2336 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000670, client: 192.168.178.35, server: , request: "POST /api/v2/reimport-scan HTTP/1.1", host: "192.168.178.35:8080"
192.168.178.35 - - [12/May/2023:11:17:24 +0000] "POST /api/v2/reimport-scan HTTP/1.1" 301 0 "-" "curl/7.81.0" "-"
192.168.178.35 - - [12/May/2023:11:17:27 +0000] "POST /api/v2/reimport-scan HTTP/1.1" 301 0 "-" "curl/7.81.0" "-"
2023/05/12 11:17:57 [warn] 6#6: *2341 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000671, client: 192.168.178.35, server: , request: "POST /api/v2/reimport-scan/ HTTP/1.1", host: "192.168.178.35:8080"
192.168.178.35 - - [12/May/2023:11:18:00 +0000] "POST /api/v2/reimport-scan/ HTTP/1.1" 201 1380 "-" "curl/7.81.0" "-"
2023/05/12 11:21:24 [warn] 6#6: *2367 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000672, client: 192.168.178.35, server: , request: "POST /api/v2/reimport-scan/ HTTP/1.1", host: "192.168.178.35:8080"
192.168.178.35 - - [12/May/2023:11:21:26 +0000] "POST /api/v2/reimport-scan/ HTTP/1.1" 201 5138 "-" "curl/7.81.0" "-"
2023/05/12 11:24:40 [warn] 6#6: *2393 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000673, client: 192.168.178.35, server: , request: "POST /api/v2/reimport-scan/ HTTP/1.1", host: "192.168.178.35:8080"
192.168.178.35 - - [12/May/2023:11:24:42 +0000] "POST /api/v2/reimport-scan/ HTTP/1.1" 201 1380 "-" "curl/7.81.0" "-"

```
docker logs uwsgi container
```
[pid: 27|app: -|req: -/-] 192.168.178.35 (-) {38 vars in 666 bytes} [Fri May 12 11:17:15 2023] POST /api/v2/reimport-scan => generated 0 bytes in 2 msecs (HTTP/1.1 301) 3 headers in 127 bytes (1 switches on core 1)
[pid: 27|app: -|req: -/-] 192.168.178.69 (admin) {44 vars in 828 bytes} [Fri May 12 11:17:20 2023] GET /alerts/count => generated 15 bytes in 24 msecs (HTTP/1.1 200) 7 headers in 212 bytes (1 switches on core 0)
[pid: 27|app: -|req: -/-] 192.168.178.35 (-) {38 vars in 663 bytes} [Fri May 12 11:17:24 2023] POST /api/v2/reimport-scan => generated 0 bytes in 2 msecs (HTTP/1.1 301) 3 headers in 127 bytes (1 switches on core 1)
[pid: 27|app: -|req: -/-] 192.168.178.35 (-) {38 vars in 663 bytes} [Fri May 12 11:17:27 2023] POST /api/v2/reimport-scan => generated 0 bytes in 2 msecs (HTTP/1.1 301) 3 headers in 127 bytes (1 switches on core 0)
[pid: 27|app: -|req: -/-] 192.168.178.69 (admin) {44 vars in 828 bytes} [Fri May 12 11:17:30 2023] GET /alerts/count => generated 15 bytes in 25 msecs (HTTP/1.1 200) 7 headers in 212 bytes (1 switches on core 1)
```

**Sample scan files**
Scanresults - rename to trivy-cf-example.json:
[trivy-cf-example.json.txt](https://github.com/DefectDojo/django-DefectDojo/files/11463364/trivy-cf-example.json.txt)

**Screenshots**
First Import:
![image](https://github.com/DefectDojo/django-DefectDojo/assets/3265170/a0ed0772-5a20-4998-b74b-bbdc2d622340)

Second Import
![image](https://github.com/DefectDojo/django-DefectDojo/assets/3265170/3ac028a0-657d-4ecb-aee2-46d9327f0ea4)

**Comment by mtesauro** [comment]
@danileau Just FYI: The new place to get Slack invites for OWASP is https://owasp.org/slack/invite

**Comment by danileau** [comment]
Thank you. I'll post it there too

**Comment by danileau** [comment]
Update: the Issue only occurs when you reimport a resultsfile with the same engagement-name. When reimporting with a different engagement-name, the existing engagements get closed and the findings get mitigated, while the same findings reopened.

**Comment by QuaiGoner** [comment]
I have simillar issue with nessus scans uploaded via /import-scan in the same engagement.
Newer test gets duplicates (rightfully), but those duplicates gets mitigated in the previous test

**Comment by danileau** [comment]
Are you using the same engagement-name when importing? What happens when you use /reimport?

**Comment by htarnacki** [comment]
I have the same or very similar issue as described here when reimporting. But this issue happens only when new test is created during reimport API call. Look at these steps:

1.
```
curl -X 'POST' \
  -k \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -H 'Authorization: Token abcdefghijk' \
  -F 'product_type_name= test/product/type' \
  -F 'product_name=test-product' \
  -F 'engagement_name=7.8.6.0' \
  -F 'engagement_end_date=2023-07-01' \
  -F 'test_title=Quality Gate 1 - Trivy' \
  -F 'active=true' \
  -F 'verified=true' \
  -F 'do_not_reactivate=false' \
  -F 'close_old_findings=true' \
  -F 'close_old_findings_product_scope=false' \
  -F 'deduplication_on_engagement=true' \
  -F 'push_to_jira=false' \
  -F 'minimum_severity=Info' \
  -F 'create_finding_groups_for_all_findings=true' \
  -F 'group_by=component_name' \
  -F 'file=@/home/abc/dojo/OWASP/build/trivy/someReport.json;type=application/json' \
  -F 'auto_create_context=true' \
  -F 'scan_type=Trivy Scan' \
  'https://abcd:8443/api/v2/reimport-scan/'
  ```
  as a result:
  product type is created: test/product/type
  product is created: test-product
  engagement is created: 7.8.6.0
  test is created: Quality Gate 1 - Trivy
  2 findigs are loaded and are in active state
  
  2.
  ```
  curl -X 'POST' \
  -k \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -H 'Authorization: Token abcdefghijk' \
  -F 'product_type_name= test/product/type' \
  -F 'product_name=test-product' \
  -F 'engagement_name=7.8.6.0' \
  -F 'engagement_end_date=2023-07-01' \
  -F 'test_title=Quality Gate 2 - Trivy' \
  -F 'active=true' \
  -F 'verified=true' \
  -F 'do_not_reactivate=false' \
  -F 'close_old_findings=true' \
  -F 'close_old_findings_product_scope=false' \
  -F 'deduplication_on_engagement=true' \
  -F 'push_to_jira=false' \
  -F 'minimum_severity=Info' \
  -F 'create_finding_groups_for_all_findings=true' \
  -F 'group_by=component_name' \
  -F 'file=@/home/abc/dojo/OWASP/build/trivy/someReport.json;type=application/json' \
  -F 'auto_create_context=true' \
  -F 'scan_type=Trivy Scan' \
  'https://abcd:8443/api/v2/reimport-scan/'
  ```
  
  as a result:
  new test is created: Quality Gate 2 - Trivy
  we have loaded the same report so 2 findings are loaded to test 'Quality Gate 2 - Trivy' and are marked as: 'duplicates'  of original findings from test 'Quality Gate 1 - Trivy'  (and that is ok)
  but at the same time at test  'Quality Gate 1 - Trivy' the original findings have changed their status to: Mitigated (and this looks like a bug? Why these 2 were mitigated? Because of 'close_old_findings=true'? but why? these 2 findings are still in report though. They did not vanished from report.
  
  3.
  ok so let's reload once again report for test 'Quality Gate 1 - Trivy' 
  
  ```
  curl -X 'POST' \
  -k \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -H 'Authorization: Token abcdefghijk' \
  -F 'product_type_name= test/product/type' \
  -F 'product_name=test-product' \
  -F 'engagement_name=7.8.6.0' \
  -F 'engagement_end_date=2023-07-01' \
  -F 'test_title=Quality Gate 1 - Trivy' \
  -F 'active=true' \
  -F 'verified=true' \
  -F 'do_not_reactivate=false' \
  -F 'close_old_findings=true' \
  -F 'close_old_findings_product_scope=false' \
  -F 'deduplication_on_engagement=true' \
  -F 'push_to_jira=false' \
  -F 'minimum_severity=Info' \
  -F 'create_finding_groups_for_all_findings=true' \
  -F 'group_by=component_name' \
  -F 'file=@/home/abc/dojo/OWASP/build/trivy/someReport.json;type=application/json' \
  -F 'auto_create_context=true' \
  -F 'scan_type=Trivy Scan' \
  'https://abcd:8443/api/v2/reimport-scan/'
  ```
  
  as a result the desired state of our findings is ok:
  we have 2 findings in 'Quality Gate 1 - Trivy' in active state
  and 2 duplicated findings in 'Quality Gate 2 - Trivy'
  
  4.
  and finally let's reload report for 'Quality Gate 2 - Trivy'. Here the only difference against '2.' is fact that new test will not be created as it already exists
  
  ```
  curl -X 'POST' \
  -k \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -H 'Authorization: Token abcdefghijk' \
  -F 'product_type_name= test/product/type' \
  -F 'product_name=test-product' \
  -F 'engagement_name=7.8.6.0' \
  -F 'engagement_end_date=2023-07-01' \
  -F 'test_title=Quality Gate 2 - Trivy' \
  -F 'active=true' \
  -F 'verified=true' \
  -F 'do_not_reactivate=false' \
  -F 'close_old_findings=true' \
  -F 'close_old_findings_product_scope=false' \
  -F 'deduplication_on_engagement=true' \
  -F 'push_to_jira=false' \
  -F 'minimum_severity=Info' \
  -F 'create_finding_groups_for_all_findings=true' \
  -F 'group_by=component_name' \
  -F 'file=@/home/abc/dojo/OWASP/build/trivy/someReport.json;type=application/json' \
  -F 'auto_create_context=true' \
  -F 'scan_type=Trivy Scan' \
  'https://abcd:8443/api/v2/reimport-scan/'
  ```
  
  after reimporting the states of our findings are still ok: at ' Quality Gate 1 - Trivy' 2 active findings and at 'Quality Gate 2 - Trivy' 2 duplicated.
  So our problem occurs only when reimport api call creates at the same time new test. When the test is reused problem do not exists

**Comment by testaccount90009** [comment]
Hello, I hope to share some of my experiences in what I did to solve the issue mentioned.  

Our team had this same issue and we tried several combinations of Engagements, Tests, deduplication settings, etc. and experienced varying behaviors (rightfully so).  In DefectDojo System Settings, this gives a good description:
![image](https://github.com/DefectDojo/django-DefectDojo/assets/122134756/e0d9b117-6ba0-48cd-b176-2b7717040f62)

"Dojo deduplicates findings by comparing endpoints, cwe fields, and titles.  If two findings share a URL and have the same CWE or title, Dojo marks the less recent finding as a duplicate..."  

If you are using CI jobs to run automated scans in a pipeline, make sure the nesting/name of engagements, tests, etc. are appropriately configured.  If you have a finding in engagement > test A and you run another scan and the finding appears in engagement B > test A, it's _technically_ a new finding from a different engagement, though it could be the same scan_type / test / tool data.  

@htarnacki above explanation of  "So our problem occurs only when reimport api call creates at the same time **new** test.  When the test is **reused** problem does not exist"  is exactly the case.

Pay special attention to 'test_title' and 'engagement_name' for appropriate nesting and referencing.  A new test/engagement means a new set of findings and will exhibit duplicate/mitigated/inactive behaviors based on the quote from the screenshot/documentation above.  In addition to those two, 'deduplication_on_engagement', 'do_not_reactivate', 'close_old_findings', and 'close_old_findings_product_scope' will each have an impact on the results and the logical interpretation / dojo representation based on above.

Hope this helps, happy Dojoing!

**Comment by manuel-sommer** [comment]
Hi all,
we face the same issue with 2.23.0 and docker-compose deployment.

**Comment by valentijnscholten** [comment]
Most of this sounds as a duplicate of #3958 a known issue caused by the hashcode matching algorithm.

**Comment by danileau** [comment]
I was able to finish my scripts with a small change in the reimport API-Call, by setting the engagementname to the current Timestamp - in my case i'll open a new engagement with every new Scan.
`curl -X 'POST' -s -o /dev/null '<ENDPOINT>/api/v2/reimport-scan/' -H 'accept: application/json'  -H 'Authorization: Token <TOKEN>'  -H 'Content-Type: multipart/form-data'  -F 'scan_date=<TODAY YYYY-MM-DD>'  -F 'minimum_severity=Low'  -F 'scan_type=Trivy Scan' -F 'file=@<FILETOUPLOAD>;type=application/json' -F 'product_type_name=application' -F 'product_name=<PRODUCTNAME>' -F 'engagement_name=<NOW YYYY-MM-DD-HH-MM>' -F 'auto_create_context=true'  -F 'tags=<TAGS>'  -F 'close_old_findings=true'  -F 'close_old_findings_product_scope=true'  -F 'push_to_jira=false'  -F 'version=<NOW YYYY-MM-DD>'`
