### ISSUE TITLE
Error in SAML Integration 

### ISSUE THREAD

**Issue by surajanuja** [DefectDojo/django-DefectDojo#8128]
**Problem description**
After entering the username and password through SAML login. I am getting authentication error as Access Denied. Below is the screenshot for reference -
![image](https://github.com/DefectDojo/django-DefectDojo/assets/112088960/9a00a982-c022-469a-9d8e-7ec91f080929)

Below is the SAML settings added in settings.dist.py

DD_SAML2_ENABLED=(bool, True),
DD_SAML2_FORCE_AUTH=(bool, True),
DD_SAML2_LOGIN_BUTTON_TEXT=(str, 'Login with SAML'),
DD_SAML2_LOGOUT_URL=(str, ''),
DD_SAML2_METADATA_AUTO_CONF_URL=(str, 'https://sts.xyz.com/federationmetadata/2007-06/federationmetadata.xml'),
DD_SAML2_METADATA_LOCAL_FILE_PATH=(str, ''), 
DD_SAML2_ENTITY_ID=(str, 'https://defectdojocompanyname.com/saml2/metadata/'),
DD_SAML2_CREATE_USER=(bool, True),
DD_SAML2_ATTRIBUTES_MAP=(dict, {
 'Email': 'email',
 'UserName': 'userid',
 'Firstname': 'firstname',
 'Lastname': 'lastname',
 }),

# Even I tried changing the above mentioned attribute name to email, username, first_name, last_name etc.

**Deployment method** *
Docker Compose
MySQL Database

**Environment information**
 - Operating System: [CentOS 7]
 - DefectDojo version (2.22.1) 

**Logs** 
Below is the Error Logs -
![image](https://github.com/DefectDojo/django-DefectDojo/assets/112088960/07386178-311c-45cf-9207-c8f9a4ae77f7)

Can anyone help me to resolve this issue ?

**Comment by surajanuja** [comment]
@dsever can you help me here?

**Comment by surajanuja** [comment]
> I can try, first this is inappropriate way of configuring, you should not it in this way, so please follow https://defectdojo.github.io/django-DefectDojo/getting_started/configuration/
> 
> From your logs, looks like your clock is drifting so assertion is not valid. Be sure that you have same time on your IDP and Service Provider (DD)

I am still trying it on test environment just to check if the saml is getting integrated. Later during Production movement.
Also I just checked, my IDP and DD servers both are in same timezone EST/EDT

**Comment by dsever** [comment]
It is not about time zone, looks like your clocks are not in sync . Even your SAML indicates that your SP has lower time, try to check your time service configurations on both of systems, even 15 seconds can make a huge difference.

**Comment by surajanuja** [comment]
> It is not about time zone, looks like your clocks are not in sync . Even your SAML indicates that your SP has lower time, try to check your time service configurations on both of systems, even 15 seconds can make a huge difference.

Thanks for the support. You were right, it was NTP sync issue.
