### ISSUE TITLE
Nessus imported scan findings are not pushed to Jira

### ISSUE THREAD

**Issue by alekbc** [DefectDojo/django-DefectDojo#813]
Please use the following template when submitting issues: (If this is a security issue, then review the [disclosure policy](https://github.com/DefectDojo/django-DefectDojo/blob/master/SECURITY.md) and submit via our security reporting program.

### Issue Type 
- [X] Bug
- [ ] Enhancement

### Description
Nessus imported Findings are not pushed to Jira. Manual findings are pushed successfully.

Celery Error: "Exception: JIRA_Issue matching query does not exist."

### Operating System 
Please include the version number (ex: Ubuntu 16.04)
Debian buster/sid
### Install

- [X] setup.bash
- [ ] docker

### DefectDojo Version
1.5.2

### Steps to Reproduce
Configure Jira and import a nessus scan.

### Console Logs (optional)
Nov 21 14:56:27 XXXXXXX celeryworker[26065]: [2018-11-21 14:56:27,921: ERROR/ForkPoolWorker-1] Task update_issue_task[c76396b1-f7ea-4946-bb5d-2e7cb66e8476] raised unexpected: DoesNotExist('JIRA_Issue matching query does not exist.',)
Nov 21 14:56:27 XXXXXXX celeryworker[26065]: Traceback (most recent call last):
Nov 21 14:56:27 XXXXXXX celeryworker[26065]:   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 382, in trace_task
Nov 21 14:56:27 XXXXXXX celeryworker[26065]:     R = retval = fun(*args, **kwargs)
Nov 21 14:56:27 XXXXXXX celeryworker[26065]:   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 641, in __protected_call__
Nov 21 14:56:27 XXXXXXX celeryworker[26065]:     return self.run(*args, **kwargs)
Nov 21 14:56:27 XXXXXXX celeryworker[26065]:   File "/opt/dojo/django-DefectDojo/dojo/tasks.py", line 235, in update_issue_task
Nov 21 14:56:27 XXXXXXX celeryworker[26065]:     update_issue(find, old_status, push_to_jira)
Nov 21 14:56:27 XXXXXXX celeryworker[26065]:   File "/opt/dojo/django-DefectDojo/dojo/utils.py", line 1066, in update_issue
Nov 21 14:56:27 XXXXXXX celeryworker[26065]:     j_issue = JIRA_Issue.objects.get(finding=find)
Nov 21 14:56:27 XXXXXXX celeryworker[26065]:   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
Nov 21 14:56:27 XXXXXXX celeryworker[26065]:     return getattr(self.get_queryset(), name)(*args, **kwargs)
Nov 21 14:56:27 XXXXXXX celeryworker[26065]:   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 380, in get
Nov 21 14:56:27 XXXXXXX celeryworker[26065]:     self.model._meta.object_name
Nov 21 14:56:27 XXXXXXX celeryworker[26065]: Exception: JIRA_Issue matching query does not exist.

**Comment by alekbc** [comment]
To make it work, I had to edit "dojo/views.py" file as follows:

$ diff  views.py views.py.ORI
34,37d33
< from dojo.utils import add_comment, add_epic, add_issue, update_epic, update_issue, \
<                        close_epic, create_notification, sync_rules
<
<
583,584c579
<                       # HERE: I have to add the jira creation
<                   add_issue(item, True)
---
>

**Comment by aaronweaver** [comment]
@alekbc Can you verify which file you edited? Was it finding/views.py? Also, are you running celery?

**Comment by alekbc** [comment]
Hi @aaronweaver , I edited "django-DefectDojo/dojo/engagement/views.py" file.
Yes, celery was/is running. 
I belive I should use the push_to_jira flag  from the engagement object instead of "True" but I couldn't find an easy way

**Comment by alekbc** [comment]
PR #833 fixes it
