### ISSUE TITLE
Snyk Code / IaC / Container

### ISSUE THREAD

**Issue by alexander-p2p** [DefectDojo/django-DefectDojo#8133]
Please add new parsers for Snyk Code / IaC / Container. Currently, a parser is implemented only for dependency analysis.

**Comment by jplobianco** [comment]
I think as a temporary solution you can use the SARIF parser.

`snyk iac test --sarif-file-output=snyk-iac.sarif`

And then, use the SARIF parser when uploading the scan or (re)importing via api.

**Comment by damiencarol** [comment]
@jplobianco is right. If a tool support a generic format, we prefer to use it instead of increasing the code size of dojo

**Comment by manuel-sommer** [comment]
This can be closed @mtesauro.
Duplicate to https://github.com/DefectDojo/django-DefectDojo/issues/9270 and also fixed already https://github.com/DefectDojo/django-DefectDojo/pull/9289
