### ISSUE TITLE
support “docker compose” command

### ISSUE THREAD

**Issue by cnsino** [DefectDojo/django-DefectDojo#8144]
**Is your feature request related to the issue? Please describe**
Currently, when installing a new version of docker, the docker-compose command installed through the plug-in is generally called "docker compose", and of course some are "docker-compose". Can these two forms of docker compose be supported?

**Describe your desired solution**
For example, adding a global variable allows the user to choose whether to use "docker compose" or "docker-compose"

**Comment by ericcornelissen** [comment]
Looks related to #7641. While supporting both command names would be an option, given that `docker-compose` is deprecated I personally think it'd make more sense to just switch to `docker compose`. Of course, that decision is up to the maintainers and broader community.

**Comment by manuel-sommer** [comment]
I guess this can be closed @mtesauro because of https://github.com/DefectDojo/django-DefectDojo/pull/8817
