### ISSUE TITLE
No module named django.core.management

### ISSUE THREAD

**Issue by poobaisle** [DefectDojo/django-DefectDojo#815]
### Issue Type 
- [ ] Bug
- [ ] Enhancement

I don't think this is a bug... It is more an installation problem I guess.

### Description

During the installation, after choosing 1.) Mysql database type, I get several ERROR : 

ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

Which is strange because I did set a password for root user with these commands : 
S
ET PASSWORD FOR 'root'@'localhost' = PASSWORD('MyNewPass');
UPDATE mysql.user SET plugin = '' WHERE user = 'root' AND host = 'localhost';
FLUSH PRIVILEGES;

Anyway the database Dojo2DB was created and the script continued running until I saw this line is RED : 

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-sNYYIO/mysqlclient/

Then, the script will throw several times : 

Create Dojo superuser:
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line

At the end of the script I have the message to edit the settings.py file. 

Then, if I want to run the command : 

root@kali:~/django-DefectDojo# python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management

### Operating System 
Kali-Linux-2018.4-vm-amd64

### Install
- [x ] setup.bash
- [ ] docker

### DefectDojo Version
Latest stable

Did someone already face this issue ? Thank you guys for your help. You're doing great job !

**Comment by aaronweaver** [comment]
Sounds like the required modules didn't get installed. You may want to create a virtual environment first or try it on ubuntu.

**Comment by devGregA** [comment]
Part of the script isn't being run due to the SQL error. It isn't happy with the DB setup for some reason or another. To me it looks like you're skipping over the password in the setup script.
