### ISSUE TITLE
SonarQube API Hotspot Import - Hardcoded Severity Info

### ISSUE THREAD

**Issue by manuel-sommer** [DefectDojo/django-DefectDojo#8150]
If you use SonarQube API Import and import SonarQube Hotspots of projects, the findings in DefectDojo always have severity "info".
https://github.com/DefectDojo/django-DefectDojo/blob/386d2e69a4ada567e6b849e48b2978e22dcd19d1/dojo/tools/api_sonarqube/importer.py#L194 

**Expected behavior**
Take the severity from "vulnerabilityProbability" and set it accordingly. 

**Deployment method** *(select with an `X`)*
- [x] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - DefectDojo version 2.22.3

**Comment by quirinziessler** [comment]
The sonarqube API used at the findings import (api/hotspots/search) returns something called "vulnerabilityProbability" which should be used as severity in DD as well. Maybe give it a tag "under review" or just don't add the status "verified" (as it is right now). Furthermore sonarqube "issues" maybe should get the status "verified" as they indeed are.

Documentation reference:
https://next.sonarqube.com/sonarqube/web_api/api/hotspots?query=hotspots
