### ISSUE TITLE
Option for products with the same name, but different product types

### ISSUE THREAD

**Issue by feeltheajf** [DefectDojo/django-DefectDojo#816]
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description
It is no longer possible to create products with the same name, but different type in latest DefectDojo version. It was a useful feature to distinguish products from different areas. Moreover, it breaks backward compatibility of the upcoming update

### Operating System 
CentOS 7.5

### Install

- [x] setup.bash
- [ ] docker

### DefectDojo Version
latest dev

### Steps to Reproduce
Try to create two products with identical names, but with different product types -> error: product already exists

**Comment by aaronweaver** [comment]
I can see your use case, it's an intentional feature though not a bug. I can see that we should make it an optional feature on allowing duplicate product names. In the mean time you can always remove unique in models.py - 

```
name = models.CharField(max_length=255, unique=True)
```
