### ISSUE TITLE
Metrics dashboard dates

### ISSUE THREAD

**Issue by andresghelarducci** [DefectDojo/django-DefectDojo#8169]
**Bug description**
The metric dashboard page presents incorrect reference dates

**Steps to reproduce**
1. Go to 'Metrics->Metrics dashboard'

**Expected behavior**
issues :
1)It is not clear why title for dashboard is Metrics for Feb. 3, 2023 - Feb. 4, 2023 , why it generates a metrics specifically for these 2 days?How can I select dashboard reference period?
2)As depicted in the attached image in the first 2 charts there's always printed 01/23, is that correct?
3) If I selected "measured findings" in the top right menu all charts are empty, am I missing something?

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Centos 7.9
 - DefectDojo version 2.22.3

**Logs** 
Not needed
**Sample scan files**
Not needed

**Screenshots**
![immagine](https://github.com/DefectDojo/django-DefectDojo/assets/44871257/72d5f242-6994-4c6e-a9e4-d6a295eec662)

**Additional context** (optional)

**Comment by italvi** [comment]
I think this is similar to my problem mentioned in #6216
