### ISSUE TITLE
docker-compose up error

### ISSUE THREAD

**Issue by ryuuk1** [DefectDojo/django-DefectDojo#8178]
docker-compose up    
 
WARNING: The DD_DATABASE_HOST variable is not set. Defaulting to a blank string.
WARNING: The DD_DATABASE_PORT variable is not set. Defaulting to a blank string.
WARNING: The DD_DATABASE_URL variable is not set. Defaulting to a blank string.
WARNING: The DD_CELERY_BROKER_URL variable is not set. Defaulting to a blank string.
WARNING: The DD_DATABASE_NAME variable is not set. Defaulting to a blank string.
WARNING: The DD_DATABASE_USER variable is not set. Defaulting to a blank string.
WARNING: The DD_DATABASE_PASSWORD variable is not set. Defaulting to a blank string.

**Comment by dsever** [comment]
Please take a look at https://github.com/DefectDojo/django-DefectDojo/blob/dev/readme-docs/DOCKER.md

**Comment by manuel-sommer** [comment]
I guess this can be closed @mtesauro ?
Please ask such things in the owasp channel @ryuuk1
