### ISSUE TITLE
Findings Severity is reset to `High` upon manual edit

### ISSUE THREAD

**Issue by Hydragyrum** [DefectDojo/django-DefectDojo#8188]
**Bug description**
When viewing a finding, I can edit using the `e` key. The severity on the edit screen does not take into account the current setting and will reset to `High`.

**Steps to reproduce**
1. Create or click on an engagement
![image](https://github.com/DefectDojo/django-DefectDojo/assets/4928181/9098bfb9-6829-4d3d-b993-ae10dfd357c7)
2. Create or click on a test
![image](https://github.com/DefectDojo/django-DefectDojo/assets/4928181/ac094934-d3e4-4ffe-95df-5531f67be1ba)
3. Create a new finding with a severity level of `Low`
![image](https://github.com/DefectDojo/django-DefectDojo/assets/4928181/9b37049e-6906-45fc-b22a-5a1107ff3d39)
4. Edit the finding, modifying nothing and clicking on `Finished`
![image](https://github.com/DefectDojo/django-DefectDojo/assets/4928181/29216533-6696-481b-8d59-e1013af817f0)
6. The Finding severity has updated to `High` 

**Expected behavior**
The finding severity should remain at `Low`.

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Unknown
 - DefectDojo version (see footer) or commit message: v. 2.22.0

**Logs** 
Use `docker-compose logs` (or similar, depending on your deployment method) to get the logs and add the relevant sections here showing the error occurring (if applicable).

No logs available

**Sample scan files**
If applicable, add sample scan files to help reproduce your problem.

Reproducible via manual actions

**Screenshots**
See above

**Additional context** (optional)

**Comment by mtesauro** [comment]
@Hydragyrum 
I am unable to reproduce on the demo site: https://demo.defectdojo.org/finding/1524

Login details for the demo site are at https://github.com/DefectDojo/django-DefectDojo#demo

I reproduced your steps and every time I hit 'e' and make no edits and save the file, it remains low severity.

**Comment by Hydragyrum** [comment]
@mtesauro  Ok I confirm it's not reproducible on the demo version. Was likely fixed some time in between or I missed the issue in question. Closing now
