### ISSUE TITLE
Nessus API import scan failed - unicode has no attribute name

### ISSUE THREAD

**Issue by alekbc** [DefectDojo/django-DefectDojo#819]
Please use the following template when submitting issues: (If this is a security issue, then review the [disclosure policy](https://github.com/DefectDojo/django-DefectDojo/blob/master/SECURITY.md) and submit via our security reporting program.

### Issue Type 
- [ x] Bug
- [ ] Enhancement

### Description
When a scan is imported via APIv1, it fails.

### Operating System 
Please include the version number (ex: Ubuntu 16.04)
Debian buster/sid
### Install

- [ x] setup.bash
- [ ] docker

### DefectDojo Version

1.5.2 
### Steps to Reproduce
\"minimum_severity\": \"Low\",
  \"scan_date\": \"2018-10-01\",
  \"verified\": false,
  \"file\": \"/tmp/1542837614.xml\",
  \"lead\": \"/api/v1/users/2/\",
  \"tags\": \"complete\",
  \"active\": false,
  \"resource_uri\": \"/api/v1/engagements/14/\",
  \"engagement\": \"/api/v1/engagements/14/\",
  \"scan_type\": \"Nessus Scan\"

**Comment by alekbc** [comment]
Here's how I patched "dojo/factory.py file to make it work (just for Nessus, but it can be used for any other scan type). 
NOTE: Celery status: runing.

django-DefectDojo/dojo/tools# diff factory.py factory.py.ORI
39,40c39
<       #filename = file.name.lower()
<       filename = file.lower()
---
>         filename = file.name.lower()

**Comment by aaronweaver** [comment]
So the filename contained unicode?

**Comment by alekbc** [comment]
Actually, the problem was that "file" variable was the name of the file. "file.name" didn't exist.

**Comment by alekbc** [comment]
I improved it a little , as it was failing when I was reimporting a scan  manually:
 
        if hasattr(file,'name'):
            filename = file.name.lower()
        if hasattr(file,'lower'):
            filename = file.lower()

**Comment by devGregA** [comment]
@alekbc would you like to submit the PR so you get credit for the fix?

**Comment by alekbc** [comment]
Hi @devGregA  , I've just did
https://github.com/DefectDojo/django-DefectDojo/compare/master...alekbc:patch-1
Thanks
