### ISSUE TITLE
Defectdojo integration with SonarQube through web hook

### ISSUE THREAD

**Issue by gulsezim11** [DefectDojo/django-DefectDojo#8217]
Hello!

I am using SonarQube and would like to integrate with Defectdojo. We already have some projects in sonar, and I would like to set a web hook in sonarqube, so that any results at each run of pipeline will be sent to defectdojo. 

I could not find any detailed information on webhooks. I don’t want to integrate sending to defectdojo through script in ci/cd, and I don’t want to create a third party between SonarQube and defectdojo. (third party catches the sonar webhook, parses it and sends to defectdojo). 

Are there any ways that sonar web hook directly connects to defectdojo?
Any help would be appreciated, thanks :)

**Comment by kiblik** [comment]
Have you checked the official documentation? https://documentation.defectdojo.com/integrations/parsers/api/sonarqube/

**Comment by gulsezim11** [comment]
hello, yes, but I understand it as a manual work, where I have to import the result every time by my hand, I would like to automate it

**Comment by kiblik** [comment]
Onboarding (set up connection), might be manual but you can use API endpoints for it
- `POST /api/v2/tool_types/`
- `POST /api/v2/tool_configurations/`
- `POST /api/v2/product_api_scan_configurations/`

Uploading of data can be done via API as well (if you need it on a regular basis, you can set up CronJob)
- `POST /api/v2/import-scan/` or `POST /api/v2/reimport-scan/` with `api_scan_configuration=XX`

**Comment by kiblik** [comment]
Are you asking to send this kind of webhook https://docs.sonarqube.org/latest/project-administration/webhooks/ directly to DD? No, it is not possible right now. 3rd party is necessary for that scenatio.
