### ISSUE TITLE
manage.py migrate not working with external database

### ISSUE THREAD

**Issue by mirasifali** [DefectDojo/django-DefectDojo#8227]
I have deployed defectdojo using godojo on EC2 and hooked up to external RDS. While doing version upgrade when I run manage.py migrate it shows no changes to apply. It doesn't look like its comparing the schema with RDS database

**Comment by mtesauro** [comment]
Did you activate the virtual environment that godojo creates before you ran that command? An example of making that a 'one-liner' is at https://github.com/DefectDojo/godojo/blob/master/docs-and-scripts/dojo-start#L26 or

```
source /opt/dojo/bin/activate && python manage.py [manage.py sub-command here]
```

If you did activate the virtual environment, it's still not migrating maybe try these commands:

```
source ../bin/activate && python3 manage.py makemigrations dojo
source ../bin/activate && python3 manage.py migrate
```

This is one of the many reasons why the docker-compose install is significantly better that a godojo install - the initializer container handles upgrades for you. You might get some clues from looking at it's entrypoint script as well - https://github.com/DefectDojo/django-DefectDojo/blob/master/docker/entrypoint-initializer.sh

godojo was really written to replace an old 1200+ line Bash script called setup.bash and will be deprecated for DefectDojo v3 or sooner. It assume a high level of familiarity with how DefectDojo and Django works that ends up causing users problems that could easily be avoided by using the docker-compose install path.

HTH

**Comment by manuel-sommer** [comment]
Can we close this issue @mtesauro ?
