### ISSUE TITLE
"Semgrep Cloud Platform" and support for webhook integration

### ISSUE THREAD

**Issue by tomaszn** [DefectDojo/django-DefectDojo#8232]
**Scanner Name**
Semgrep, with their SaaS offering: https://semgrep.dev/docs/semgrep-cloud-platform/webhooks/

So another webhook configuration would be needed.

**Sample File**
There are two JSON formats:
* for scans (can be mapped to engagements)?
* for findings

Up-to-date versions are available in under the link above.

**Comment by manuel-sommer** [comment]
Hi @tomaszn, 
if you provide sample output, the semgrep parser can be extended. But there will most likely be no API importer implemented. https://defectdojo.github.io/django-DefectDojo/contributing/how-to-write-a-parser/#api-parsers

**Comment by manuel-sommer** [comment]
I guess this can be closed as there was no update for over a month @mtesauro .
If you still need help here, feel free to open a new issue with sample files.
