### ISSUE TITLE
Auto-close Findings Doesn't Work (2.16.2)

### ISSUE THREAD

**Issue by mohammadkamrani** [DefectDojo/django-DefectDojo#8284]
**Problem:**
I upload reports through CI/CD into DefectDojo. In the first step, create an engagement and then import a scan report. During uploading, I'd used "`close_old_findings`", but, it couldn't close all mitigated findings. Now, I've used "`close_old_findings_product_scope`" but, it doesn't work too.

**Import curl:**
`curl --fail --location --request POST "${DEFECTDOJO_URL}/api/v2/import-scan/" --header "Authorization: Token ${NEW_DEFECTDOJO_TOKEN}" --form "scan_date=\"${TODAY}\"" --form "minimum_severity=\"${DEFECTDOJO_SCAN_MINIMUM_SEVERITY}\"" --form "active=\"${DEFECTDOJO_SCAN_ACTIVE}\"" --form "verified=\"${DEFECTDOJO_SCAN_VERIFIED}\"" --form "scan_type=\"${DEFECTDOJO_SCAN_TYPE}\"" --form "engagement=\"${ENGAGEMENTID}\"" --form "file=@${DEFECTDOJO_SCAN_FILE}" --form "close_old_findings_product_scope=\"${DEFECTDOJO_SCAN_CLOSE_OLD_FINDINGS}\"" --form "push_to_jira=\"${DEFECTDOJO_SCAN_PUSH_TO_JIRA}\"" --form "test_type=\"${DEFECTDOJO_SCAN_TEST_TYPE}\"" --form "environment=\"${DEFECTDOJO_SCAN_ENVIRONMENT}\""`

DEFECTDOJO_SCAN_CLOSE_OLD_FINDINGS = "true"

**My configuration:**

![2023-06-20_15-13-41](https://github.com/DefectDojo/django-DefectDojo/assets/53512886/4fc8b69f-8835-4d44-bde6-6e43de6e4c4a)

Version: 
`2.16.2`

**Comment by elihu** [comment]
Hi! I had the same issue. But when I set both "close_old_findings" and "close_old_findings_product_scope" to true it works like before 2.16. I hope it helps

**Comment by mohammadkamrani** [comment]
Hi
I've added both "`close_old_findings`" and "`close_old_findings_product_scope`". It didn't work!.

**Comment by mohammadkamrani** [comment]
Hi @elihu 

I'll try a new version. and then I will let you know what I found out.

Thanks

**Comment by mohammadkamrani** [comment]
Hi @elihu 
I have updated it to version `2.24.0`, but it is still not functioning. I attempted to use both "`close_old_findings`" and "`close_old_findings_product_scope`", but neither of them worked. I also tried using just "`close_old_findings`", but that did not work either.

**Comment by VasilyevaAn** [comment]
Hi, I use release 2.26.4 and close_old_findings_product_scope=True still not working.
both close_old_findings=True and close_old_findings_product_scope=True didnt work.

**Comment by mtesauro** [comment]
We did a bunch of cleanup in #8728 which will land in 2.27.0 - I'd wait till that release and test again.

**Comment by manuel-sommer** [comment]
What is the Status here? Can we close this?

**Comment by mtesauro** [comment]
Closing as stale.
