### ISSUE TITLE
Can't start DefectDojo

### ISSUE THREAD

**Issue by zhukovmisha** [DefectDojo/django-DefectDojo#8303]
I do everything according to the instruction
When I run ./dc-up.sh postgres-redis
It says
"service rabbitmq is required by celeryworker but is disabled. Can be enabled by profiles [mysql-rabbitmq postgres-rabbitmq]"
if I run ./dc-up.sh mysql-redis
It says the opposite
service postgres is required by initializer but is disabled. Can be enabled by profiles [postgres-rabbitmq postgres-redis]

**Comment by lolboo11** [comment]
i have the same problem. Help plz

**Comment by lolboo11** [comment]
> I do everything according to the instruction When I run ./dc-up.sh postgres-redis It says "service rabbitmq is required by celeryworker but is disabled. Can be enabled by profiles [mysql-rabbitmq postgres-rabbitmq]" if I run ./dc-up.sh mysql-redis It says the opposite service postgres is required by initializer but is disabled. Can be enabled by profiles [postgres-rabbitmq postgres-redis]


what version docker-compose do you have? In my case, it helped to install an older version 2.17 for example

**Comment by zhukovmisha** [comment]
> > I do everything according to the instruction When I run ./dc-up.sh postgres-redis It says "service rabbitmq is required by celeryworker but is disabled. Can be enabled by profiles [mysql-rabbitmq postgres-rabbitmq]" if I run ./dc-up.sh mysql-redis It says the opposite service postgres is required by initializer but is disabled. Can be enabled by profiles [postgres-rabbitmq postgres-redis]
> 
> what version docker-compose do you have? In my case, it helped to install an older version 2.17 for example

Thank you! I downgraded docker-compose to v2.18.1 and it works.

**Comment by D3vil0p3r** [comment]
I had the same issue and solved by downgrading docker-compose to v2.18.1. I hope they will adapt DefectDojo to the latest docker-compose version.

**Comment by dlarubia** [comment]
I had the same issue. Downgrading to v2.18 worked for me.

**Comment by gnustavo** [comment]
I had the same issue after upgrading Docker Compose to v2.19.1. I think it's related to this issue: https://github.com/docker/compose/issues/10751

**Comment by kiblik** [comment]
Same problem here. My testing scenario `./dc-up.sh postgres-redis`
Results (for different `docker-compose` versions):
- `2.18.1` - works
- `2.19.0` - `service rabbitmq is required by celerybeat but is disabled. Can be enabled by profiles [mysql-rabbitmq postgres-rabbitmq]`
- `2.19.1` - `service mysql is required by celerybeat but is disabled. Can be enabled by profiles [mysql-rabbitmq mysql-redis]`
- `2.20.0` - `no such service: rabbitmq`
- `2.20.1` - `no such service: mysql`
- `2.20.2` - `no such service: mysql`

So there was some change (between `2.19.1` and `2.20.0`) but it didn't fix the issue.

**Comment by kiblik** [comment]
> I had the same issue after upgrading Docker Compose to v2.19.1. I think it's related to this issue: [docker/compose#10751](https://github.com/docker/compose/issues/10751)
> ...

@gnustavo, I suppose, you are right.
It looks like it is related to https://github.com/docker/compose/pull/10602 (which fixes https://github.com/docker/compose/issues/10751)

**Comment by mtesauro** [comment]
I would be great to get  a PR from someone who has experienced this issue. I've not experienced it personally so not  in a great place to describe how to avoid this problem.

PRs are always welcome: https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/CONTRIBUTING.md

**Comment by valentijnscholten** [comment]
> So there was some change (between `2.19.1` and `2.20.0`) but it didn't fix the issue.

For me it buils/runs fine with docker compose v2.20.0.

**Comment by kiblik** [comment]
Small follow-up.

I just upgraded my `docker-compose` to `2.21.0` mainly I noticed this note in [the release notes](https://github.com/docker/compose/releases/tag/v2.21.0):
> Fix for "no such service" errors when using include and profiles (https://github.com/compose-spec/compose-go/pull/448)

However, I'm still facing an error: `service mysql is required by celerybeat but is disabled. Can be enabled by profiles [mysql-rabbitmq mysql-redis]` (my test command is `./dc-up.sh postgres-redis`).

I suppose there are 2 possible ways:
- `docker-compose` would start to support a "softer" evaluation of `depends_on` (I will try to open an issue on their GH repo)
- Implementation of `docker-compose.yml` in the DD repo would need to be changed (Remove all `depends_on`? Or supports only one profile = only one "database-message broker" pair? Or create `docker-compose.yml` for each profile?)

**Comment by kiblik** [comment]
> Small follow-up.
> 
> I just upgraded my `docker-compose` to `2.21.0` mainly I noticed this note in [the release notes](https://github.com/docker/compose/releases/tag/v2.21.0):
> 
> > Fix for "no such service" errors when using include and profiles ([compose-spec/compose-go#448](https://github.com/compose-spec/compose-go/pull/448))
> 
> However, I'm still facing an error: `service mysql is required by celerybeat but is disabled. Can be enabled by profiles [mysql-rabbitmq mysql-redis]` (my test command is `./dc-up.sh postgres-redis`).
> 
> I suppose there are 2 possible ways:
> 
> * `docker-compose` would start to support a "softer" evaluation of `depends_on` (I will try to open an issue on their GH repo)
> * Implementation of `docker-compose.yml` in the DD repo would need to be changed (Remove all `depends_on`? Or supports only one profile = only one "database-message broker" pair? Or create `docker-compose.yml` for each profile?)

Or this might be a way in the future? https://github.com/docker/compose/issues/10855 (https://github.com/compose-spec/compose-spec/pull/404)

**Comment by kiblik** [comment]
https://github.com/docker/compose/issues/10855 inspired me solution which is already available.
I might find an elegant way to solve our issue.
I'm looking for testers: https://github.com/DefectDojo/django-DefectDojo/pull/8598

**Comment by kiblik** [comment]
This issue has been fixed and released in [2.26.1](https://github.com/DefectDojo/django-DefectDojo/releases/tag/2.26.1).
The issue can be closed.

**Comment by zhukovmisha** [comment]
I'm closing the issue then
