### ISSUE TITLE
[Feature Request:] Apply for listing in ArtifactHub 

### ISSUE THREAD

**Issue by GeiserX** [DefectDojo/django-DefectDojo#8315]
### Is your feature request related to a problem? Please describe.

[ArtifactHub](https://artifacthub.io/) contains a list of all installable Helm charts supercharged with functionalities, which makes DevOps work easier. 

I have searched for DefectDojo project there but it's not listed. Currently I'm blind to changes in the Helm chart when in need of upgrading it.
You will need to apply for `Official status request` and request your Helm repository to be included [here](https://github.com/artifacthub/hub/issues/new/choose)

**Comment by manuel-sommer** [comment]
This is a duplicate to #9556  @mtesauro
