### ISSUE TITLE
Add vulnerability type to Qualys scan import (PR created)

### ISSUE THREAD

**Issue by nv-pipo** [DefectDojo/django-DefectDojo#8333]
**Qualys Scan**
Type of vulnerability information is missing from the current XML parsing script. I have created a PR to include the type during the import of Qualys scans. Following the following post:
https://success.qualys.com/discussions/s/question/0D52L00004TnzgISAR/explanation-of-ig-vuln-practice

Could you please approve the PR?
https://github.com/DefectDojo/django-DefectDojo/pull/8330

**Comment by manuel-sommer** [comment]
This can be closed @mtesauro
