### ISSUE TITLE
Change fields in findings

### ISSUE THREAD

**Issue by sakyra01** [DefectDojo/django-DefectDojo#8345]
Good day!

How could I change field "references" in findings by requests to API in DefectDojo?
Didn't find any possibilities how could I did it.

**Comment by kiblik** [comment]
`PATCH /api/v2/findings/{id}/` with JSON
```json
{
    "references": "new references"
}
```

**Comment by sakyra01** [comment]
Thank u! It helped

**Comment by kiblik** [comment]
> Thank u! It helped

Happy to hear that. Please, close the issue.

**Comment by sakyra01** [comment]
GG
