### ISSUE TITLE
email notifications are not working

### ISSUE THREAD

**Issue by alekbc** [DefectDojo/django-DefectDojo#835]
Please use the following template when submitting issues: (If this is a security issue, then review the [disclosure policy](https://github.com/DefectDojo/django-DefectDojo/blob/master/SECURITY.md) and submit via our security reporting program.

### Issue Type 
- [x ] Bug
- [ ] Enhancement

### Description
email notifications are not working.
host can relay to the smtp server. Other applications are sending emails from the same OS.
I added following lines at settings/settings.py and restarted services

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'XXXX my smtp hostname XXXX'
EMAIL_PORT = '25'

### Operating System 
Debian  buster/sid
### Install

- [ x] setup.bash
- [ ] docker

### DefectDojo Version
1.5.2

### Steps to Reproduce

Set to notify by email when peer review is requested
Mark a finding as "peer review requested".
No information can be found in the logs.

### Console Logs (optional)

no logs related to this issue were found.

**Comment by PreenaPrakash** [comment]
Hi.
Emails notifications are not working.
Please help on this .

Thanks in Advance

**Comment by madchap** [comment]
If you host email works, you can simply use it.

Example for your settings.py (or else)
```
DD_EMAIL_URL=smtp://<LOCALHOST_OR_IP_ADDR_OF_SPECIFC_IF>:25
```

This is the only thing you'd need. The variables that you mention in the initial post are not necessary, as they will be derived from the one I just mentioned.

**Comment by PreenaPrakash** [comment]
@madchap : Thank you for your help. But it is still not working. Should I do any other steps? 

TIA

**Comment by PreenaPrakash** [comment]
(530, '5.7.0 Must issue a STARTTLS command first. w6sm7296816lfq.95 - gsmtp', u'mailid')

-getting this error now. It is showing in the notifications of application. 
Any idea guys?

**Comment by madchap** [comment]
Well, you probably have the wrong configuration then. You need to pass the proper ports and such. Nothing to do with DD or Django at this point.

**Comment by PreenaPrakash** [comment]
@madchap : Thank you so much..

**Comment by iman4000** [comment]
how can I enable TLS? I should use it on port 587.... but I cannot find any variable related to it
