### ISSUE TITLE
Improve trivy json reports PARSER to produce actionable findings

### ISSUE THREAD

**Issue by denisovval** [DefectDojo/django-DefectDojo#8375]
Aquasec Trivy scanner can scan for vulnerabilities, misconfigurations and etc.

The current Aquasec trivy JSON parser doesn't parse at all the "CauseMetadata" keys in their json report. This leads to useless findings like this:

![image](https://github.com/DefectDojo/django-DefectDojo/assets/129956250/8e291aef-598a-43f9-ab13-8822974f1ed0)

There is absolutely no information on:
1. what was scanned? This information is in "ArtifactName" 
2. Where exactly is this problem? This information is a list of keys under "CauseMetadata" 

**Describe the solution you'd like**
Improve trivy JSON parser for misconfigurations and include in "message" details on where this issue has been found in visual form the same as trivy does.

<img width="940" alt="image" src="https://github.com/DefectDojo/django-DefectDojo/assets/129956250/6a610c4e-5ae0-4a71-92cb-4d2056a7dc6c">

**Describe alternatives you've considered**
Tried to use TFSec scan, it's a bit better but still doesn't allow quickly understand where is the problem due to doesn't generate a text table as trivy does. Only generates a summary table with findings.

**Additional context**
TFSec generates:
![image](https://github.com/DefectDojo/django-DefectDojo/assets/129956250/0eba5837-d948-43da-ac2a-81b8cbb13b44)

**Comment by manuel-sommer** [comment]
Hi @denisovval , could you add json examples here that we can improve the parser?

**Comment by manuel-sommer** [comment]
Can we close this issue with this PR @mtesauro ?

https://github.com/DefectDojo/django-DefectDojo/pull/8607
