### ISSUE TITLE
Sonarqube test re-upload not working

### ISSUE THREAD

**Issue by quirinziessler** [DefectDojo/django-DefectDojo#8379]
**Bug description**
When re-importing a Sonarcloud scan, the import seems to run smooth but an alert is created that there is an issue with a missing organization key. As well, no changes are showing up on the findings page. Probably the key is not part of the sonarqube api calls happening within the re-import.

**Steps to reproduce**
1. setup Sonarcloud API integration
2. import Sonarcloud findings via the API
3. trigger a re-upload of the scan

**Expected behavior**
no error coming up and findings synced correctly

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - DefectDojo version (see footer) or commit message: 2.23.0 & 2.24.0

**Logs** 

uwsgi_1         | [14/Jul/2023 07:52:19] ERROR [dojo.tools.sonarqube_api.importer:157] Unable to get the rule java:S2039 due to 400 - {"errors":[{"msg":"The \u0027organization\u0027 parameter is missing"}]}
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/app/dojo/tools/sonarqube_api/importer.py", line 110, in import_issues
uwsgi_1         |     rule = client.get_rule(rule_id)
uwsgi_1         |            ^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi_1         |   File "/app/dojo/tools/sonarqube_api/api_client.py", line 268, in get_rule
uwsgi_1         |     raise Exception(f'Unable to get the rule {rule_id} due to {response.status_code} - {response.content.decode("utf-8")}')
uwsgi_1         | Exception: Unable to get the rule java:S2039 due to 400 - {"errors":[{"msg":"The \u0027organization\u0027 parameter is missing"}]}

**Screenshots**
![image](https://github.com/DefectDojo/django-DefectDojo/assets/19915467/9538db78-f5ad-41c9-9c05-20bd40dbfa09)

**Comment by kiblik** [comment]
@Maffooch, I would like to check and test it but I'm running only local SQ instances. Can you check it, please?

Not sure if there is a change in API but it looks like not only `get_project`, `find_project` and `find_issues` need organisation but `get_rule` as well.

**Comment by kiblik** [comment]
But based on https://sonarcloud.io/web_api/api/rules, `organization` is required

**Comment by quirinziessler** [comment]
actually `get_issue` & `get_rule` do need the organization param. I am currently looking into it and preparing a fix.

**Comment by quirinziessler** [comment]
It seems like there is another problem with  `get_issue`. Independent of the organization param, I always receive an empty list of issues.

`django-defectdojo-celeryworker-1               | [14/Jul/2023 10:07:07] ERROR [celery.app.trace:270] Task dojo.tools.tool_issue_updater.tool_issue_updater[b33a8148-8686-4106-907b-51188d5c5048] raised unexpected: Exception('Expected Issue "XXXXXXXXXXXX", but it returned \n            "[]."\n            full response: "\n            "{\'total\': 0, \'p\': 1, \'ps\': 100, \'paging\': {\'pageIndex\': 1, \'pageSize\': 100, \'total\': 0}, \'effortTotal\': 0, \'debtTotal\': 0, \'issues\': [], \'components\': [], \'organizations\': [], \'facets\': []}')
django-defectdojo-celeryworker-1               | Traceback (most recent call last):
django-defectdojo-celeryworker-1               |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
django-defectdojo-celeryworker-1               |     R = retval = fun(*args, **kwargs)
django-defectdojo-celeryworker-1               |                  ^^^^^^^^^^^^^^^^^^^^
django-defectdojo-celeryworker-1               |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
django-defectdojo-celeryworker-1               |     return self.run(*args, **kwargs)
django-defectdojo-celeryworker-1               |            ^^^^^^^^^^^^^^^^^^^^^^^^^
django-defectdojo-celeryworker-1               |   File "/app/dojo/decorators.py", line 120, in __wrapper__
django-defectdojo-celeryworker-1               |     return func(*args, **kwargs)
django-defectdojo-celeryworker-1               |            ^^^^^^^^^^^^^^^^^^^^^
django-defectdojo-celeryworker-1               |   File "/app/dojo/tools/tool_issue_updater.py", line 28, in tool_issue_updater
django-defectdojo-celeryworker-1               |     SonarQubeApiUpdater().update_sonarqube_finding(finding)
django-defectdojo-celeryworker-1               |   File "/app/dojo/tools/api_sonarqube/updater.py", line 131, in update_sonarqube_finding
django-defectdojo-celeryworker-1               |     issue = client.get_issue(issue_key=sonarqube_issue.key)
django-defectdojo-celeryworker-1               |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-defectdojo-celeryworker-1               |   File "/app/dojo/tools/api_sonarqube/api_client.py", line 262, in get_issue
django-defectdojo-celeryworker-1               |     raise Exception(
django-defectdojo-celeryworker-1               | Exception: Expected Issue "XXXXXXXXXXXX", but it returned 
django-defectdojo-celeryworker-1               |             "[]."
django-defectdojo-celeryworker-1               |             full response: "
django-defectdojo-celeryworker-1               |             "{'total': 0, 'p': 1, 'ps': 100, 'paging': {'pageIndex': 1, 'pageSize': 100, 'total': 0}, 'effortTotal': 0, 'debtTotal': 0, 'issues': [], 'components': [], 'organizations': [], 'facets': []}
`
