### ISSUE TITLE
Defectdojo MySql Configuration

### ISSUE THREAD

**Issue by azoumed** [DefectDojo/django-DefectDojo#838]
Hello every one ,

I try to deploy Defectdojo in production environnement that turn in kubernetes , in "setting.py" , i modidy Data Base space and launching installation .

This is how the DataBase is configured , but she didn't work in container environnement

 DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        # 'django.db.backends.mysql','django.db.backends.sqlite3' or 'django.db.backends.oracle'.
        'NAME': 'DB_Defect',  # Or path to database file if using sqlite3.
        # The following settings are not used with sqlite3:
        'USER': 'root',
        'PASSWORD': 'Amine2018',
        'HOST': 'accforgev2portaldbpr.mysql.database.azure.com',  # Empty for localhost through domain sockets
        # or '127.0.0.1' for localhost through TCP.
        'PORT': '3306',  # Set to empty string for default.
    }

Can some one Help Me !!
Thank you

**Comment by aaronweaver** [comment]
I'd check networking and ensure the port is open, without any error messages it's difficult to know what this issue is.
