### ISSUE TITLE
Credentials for external tools are stored unhashed in database

### ISSUE THREAD

**Issue by Arebjel** [DefectDojo/django-DefectDojo#839]
Please use the following template when submitting issues: (If this is a security issue, then review the [disclosure policy](https://github.com/DefectDojo/django-DefectDojo/blob/master/SECURITY.md) and submit via our security reporting program.

### Issue Type 
- [ ] Bug
- [ x ] Enhancement

### Description
When adding a configuration for an external tool, e.g. JIRA, you can store sensitive information such as password, SSH private key, API key in DefectDojo. However, when you take a look in the database afterwards (e.g. via SELECT * FROM dojo_tool_configuration;) you can see that these credentials are stored in clear text, without hashing. 
These credentials should instead be hashed with a salt, as is done for the application user's passwords in the table auth_user.

### Operating System 
Please include the version number (ex: Ubuntu 16.04)

### Install

- [ ] setup.bash
- [ ] docker

**Comment by aaronweaver** [comment]
Not hashed but encrypted. Some of the fields are encrypted with AES and we'll put in a ticket to encrypt the rest of the fields.

**Comment by devGregA** [comment]
@aaronweaver do you know what fields need to be encrypted / have more info so I can give this to the interns?

**Comment by devGregA** [comment]
pycrypto has been replaced.
