### ISSUE TITLE
dependency track integrate with defectdojo

### ISSUE THREAD

**Issue by naveen2131-hue** [DefectDojo/django-DefectDojo#8398]
As per the given official document https://documentation.defectdojo.com/integrations/parsers/file/dependency_track/
applied all the steps but still the dependency report is not generated. I have one doubt should we do any scan to import the report or just integrating the depedency track with defectdojo is enough? kindly guide me to solve this.

@dougmorato @Juu @olafz @hasantayyar @0x4d4e @

**Comment by hasantayyar** [comment]
I am tagged here. My last contribution to this project was years ago and it was very tiny. I am afraid I am not useful here.

**Comment by manuel-sommer** [comment]
@naveen2131-hue,
The integration works fine.  Just follow the steps in the documentation, I took a look at it. You have to upload a bom file to the dependencytrack project which is linked with defectdojo and the bom file has to include a vulnerable dependency. Then, the vulnerability is linked from dependencytrack to defectdojo.

This can be closed @mtesauro
