### ISSUE TITLE
Import Nessus (Tenable) plugin output

### ISSUE THREAD

**Issue by WojTecH94** [DefectDojo/django-DefectDojo#8407]
**Is your feature request related to a problem? Please describe**
Importing results from Nessus or Tenable Plugin Output field is not included. The field most of the times provides some important information about the vulnerability like how it was triggered or what was its indicator.

**Describe the solution you'd like**
There is no exact "Plugin output" field in Defect Dojo so problably the easiest way to include the data from Nessus would be import it to some unused (by Tenable importer) fields like: Request, Response or Steps to reproduce 

You might say none of the fields would always be suitable according to Nessus Plugin Output which sometimes contains both request AND response sometimes only response or other data generated in some specific way by Nessus plugin. In this case the other way to not loosing information could be adding data from Plugin Output at the end of the Description field in Defect Dojo.

**Comment by Maffooch** [comment]
Hi @WojTecH94 

Would you mind making a PR to correct this issue as you see fit? The `Plugin Output` field is used in both formats:
-  CSV
   - https://github.com/DefectDojo/django-DefectDojo/blob/dff45eaa8ed2e0d9b9483e7966e0ae5f92a94862/dojo/tools/tenable/csv_format.py#L136-L138
- XML
  - https://github.com/DefectDojo/django-DefectDojo/blob/dff45eaa8ed2e0d9b9483e7966e0ae5f92a94862/dojo/tools/tenable/xml_format.py#L87-L91

**Comment by WojTecH94** [comment]
Hello @Maffooch 
It seems that recent changes have fixed that issue. Plugin output is added to description indeed. I had the problem on version 2.23.0 but when upgraded to v. 2.24.3 it is on place. Sorry for my carelessness.
