### ISSUE TITLE
HPE Fortify Integration Steps with DefectDojo. Urgent Help required..!!

### ISSUE THREAD

**Issue by PavitraRaj** [DefectDojo/django-DefectDojo#842]
Please use the following template when submitting issues: (If this is a security issue, then review the [disclosure policy](https://github.com/DefectDojo/django-DefectDojo/blob/master/SECURITY.md) and submit via our security reporting program.

### Issue Type 
- [ ] Bug
- [x] Enhancement

### Description
Please provide the steps for integrating HPE Fortify Results with DefectDojo tool.
This issue does not provide complete steps in performing the above said action.
https://github.com/DefectDojo/django-DefectDojo/issues/647

### Operating System 
Please include the version number (ex: Ubuntu 16.04)

### Install

- [ ] setup.bash
- [x] docker

**Comment by PavitraRaj** [comment]
Hi,

Can you please provide the steps for integrating HPE Fortify results with Defect Dojo.

Thanks,
Pavitra

**Comment by PavitraRaj** [comment]
Do we need to convert Fortify report from xml to csv for it to import to DefectDOJO.
If so, which tool do you suggest for converting xml report to csv format.
Please elaborate on the procedure as it is little urgent.

**Comment by aaronweaver** [comment]
It requires XML. You can review the import code [here](https://github.com/DefectDojo/django-DefectDojo/blob/dev/dojo/tools/fortify/parser.py).
