### ISSUE TITLE
view Vulnerable Hosts / view Vulnerable Endpoints empty despite existing vulnerable endpoints and hosts

### ISSUE THREAD

**Issue by furrnace** [DefectDojo/django-DefectDojo#8450]
**Bug description**

view Vulnerable Hosts / view Vulnerable Endpoints shows an empty list although view Hosts and view Endpoints do have hosts/endpoints in the list that are marked as vulnerable

**Steps to reproduce**
1. Go to view Endpoints, browse to see if there are vulnerable Endpoints (analoguously for Hosts/vulnerable hosts)
2. Go to view Vulnerable Endpoints, see that the list is empty (analoguously for Vulnerable Hosts)

**Expected behavior**
Vulnerable Endpoints should contain the endpoints marked as vulnerable in view Endpoints
Vulnerable Hosts should contain the hosts marked as vulnerable in view Hosts

**Deployment method** *(select with an `X`)*
- [ X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Debian 11
 - DefectDojo version (see footer) or commit message: 2.24.3

**Comment by WojTecH94** [comment]
Similar situation in version v. 2.28.1
My suspection is that endpoints are cleared from vulnerabilities once mitigated, but then when the same vulnerability is reported again endpoint status is not updated and it stays mitigated.

**Comment by manuel-sommer** [comment]
Can we close this issue @mtesauro ?

**Comment by mtesauro** [comment]
Yes,
