### ISSUE TITLE
Defectdojo can import the report in automate?

### ISSUE THREAD

**Issue by naveen2131-hue** [DefectDojo/django-DefectDojo#8452]
Can Defectdojo import the tool automatically - means it will generate the report in automated basis. still now from my end importing the report in manual basis. it can be automated?

@dougmorato @Juu @olafz @hasantayyar @0x4d4e

**Comment by manuel-sommer** [comment]
Yes, you can use the REST API. This is rather something for the slack channel.
This can be closed @mtesauro
