### ISSUE TITLE
Bug - Parser for AWS Security Hub Scan (ASFF) does not import mitigation correctly

### ISSUE THREAD

**Issue by testaccount90009** [DefectDojo/django-DefectDojo#8462]
**Slack us first!**
The easiest and fastest way to help you is via Slack. There's a free and easy signup to join our #defectdojo channel in the OWASP Slack workspace: [Get Access.](https://owasp-slack.herokuapp.com/)
If you're confident you've found a bug, or are allergic to Slack, you can submit an issue anyway.

I am confident in this bug - I have mentioned it in Slack here (https://owasp.slack.com/archives/C2P5BA8MN/p1690992114411319).

**Be informative**
Please enter as much information as possible, otherwise we can't provide support. If possible upgrade to the latest release or dev version and try again.

**Bug description**
A clear and concise description of what the bug is. For errors include at least the exact error message you are seeing (including traceback).

Import an ASFF Scan and no 'Mitigation' is associated with the Finding, although there is a field for this to be pulled in by the parser.  In the Finding metadata there is:

"Title": ....
"Description": ....
"Remediation": {
  "Recommendation": {
    "Text": "This is the field that should go to Mitigation in DefectDojo",
    "URL": "Don't really care about this, but References would be a good fit for this metadata component as well, I think"
    }
  }

**Steps to reproduce**
1. Import ASFF Scan
2. See in Finding metadata there is a "Remediation" "Recommendation" set of fields.
3. This data doesn't go into DefectDojo - which is probably not expected behavior.
4. 
**Expected behavior**

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo version (see footer) or commit message: [use `git show -s --format="[%ci] %h: %s [%d]"`]
 v2.24.3

**Logs** 
Use `docker-compose logs` (or similar, depending on your deployment method) to get the logs and add the relevant sections here showing the error occurring (if applicable).

**Sample scan files**
If applicable, add sample scan files to help reproduce your problem.

**Screenshots**

**Additional context** (optional)

**Comment by manuel-sommer** [comment]
@blakeaowens or @testaccount90009 please close this issue.
