### ISSUE TITLE
DefectDojo docker deployment not work

### ISSUE THREAD

**Issue by BlauerPulli** [DefectDojo/django-DefectDojo#847]
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description
I struggle with the DefectDojo Docker setup, so this problems relates as well to the https://github.com/aaronweaver/docker-DefectDojo project.

1. The entry-command of the appsecpipeline/django-defectdojo container executes docker-startup.bash with the wrong path(see docker-compose.yml). --> set the path to "/opt/django-DefectDojo/docker/docker-startup.bash"
2. docker-startup.bash needs the argument "setup" at first execution for creating the setup-functions(via dojo-shared-resources) that are later called. --> bash /opt/django-DefectDojo/docker/docker-startup.bash setup
3. Creating a venv is not possible because the needed command is not found. --> added "apt-get install -y virtualenv"
4. I got the message: "Error loading MySQLdb module: No module named MySQLdb.Did you install mysqlclient or MySQL-python?" So, the Python venv is created successfully and the script is sourcing the venv. But the following "pip install ." seems still to refer to the default /usr/bin path. --> Going with docker exec into the container and manually install the requirements in the created venv fixed this (at least temporarly for testing..)
5. From there going to the next Issue: "/dojo-data.bash: No such file or directory". The script calls "DOCKER_DIR/dojo-data.bash". i dont know where DOCKER_DIR is defined.. it is just empty..

And this are still not all of the problems i got while trying to deploy DefectDojo.. the whole process feels buggy..
Am I the only one who have to fight extremely with this setup?! Or am i doing something completely wrong?

### Operating System 
Ubuntu 16.04

### Install

- [ ] setup.bash
- [x] docker

### DefectDojo Version
latest

### Steps to Reproduce
git clone https://github.com/aaronweaver/docker-DefectDojo
bash setup.bash
docker-compose up

### Console Logs (optional)
Traceback (most recent call last):
File "manage.py", line 10, in <module>
execute_from_command_line(sys.argv)
File "/opt/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
utility.execute()
File "/opt/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
django.setup()
File "/opt/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
apps.populate(settings.INSTALLED_APPS)
File "/opt/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
app_config.import_models()
File "/opt/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
self.models_module = import_module(models_module_name)
File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
__import__(name)
File "/opt/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 4, in <module>
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
File "/opt/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/contrib/auth/base_user.py", line 52, in <module>
class AbstractBaseUser(models.Model):
File "/opt/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 124, in __new__
new_class.add_to_class('_meta', Options(meta, app_label))
File "/opt/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 325, in add_to_class
value.contribute_to_class(cls, name)
File "/opt/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/db/models/options.py", line 214, in contribute_to_class
self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
File "/opt/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/db/__init__.py", line 33, in __getattr__
return getattr(connections[DEFAULT_DB_ALIAS], item)
File "/opt/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 211, in __getitem__
backend = load_backend(db['ENGINE'])
File "/opt/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 115, in load_backend
return import_module('%s.base' % backend_name)
File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
__import__(name)
File "/opt/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 30, in <module>
'Did you install mysqlclient or MySQL-python?' % e
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module: No module named MySQLdb.
Did you install mysqlclient or MySQL-python?

**Comment by petrabrunner** [comment]
hi :) 
**no you are not the only one struggling with the process.** 

I have not had exactly the same problem you have unfortunately... BUT.
I can tell  you what I am doing and maybe it helps you with finding something that you are currently not doing.

**preparations (workarounds before the first startup)**
1. checkout the two repos: django-defectdojo, docker-defectdojo (in my case I cloned them in same parent directory) 
2. rename the docker-compose-dev.yaml inside docker-defectdojo to docker-compose.yaml (I have been using this so I can trigger the docker-compose build command)
3. I moved the django-defectdojo/docker/docker-startup.bash to django-defectdojo/docker-startup.bash
4. after the first startup the dojo-ui was screwed up. the css-files could not be found. (I suspect that there is still some funky business because the api-viewer does not work for me) so as a workaround I copied:
{{ echo "=============================================================================="}}
{{ echo "copying static stylesheets to /django-DefectDojo/static/"}}
{{ echo "=============================================================================="}}
{{ cp ./static/* -r /django-DefectDojo/static/}}
{{ fi}}
inside the docker-startup.bash
5. adapted the line containing "ALLOWED_HOSTS" to contain the current hostname of the maschine docker is running on (otherwise django will prevent you from connecting to the dojo...)
------ 
**and in daily business I simply run:** 
1. docker-compose down 
2. docker-compose build (if something has changed!!) - that process will take a while
3. and finally docker-compose up -d 

hope this helps you

**Comment by orval** [comment]
I am seeing a similar issue. When I use the docker run command shown [here](https://defectdojo.readthedocs.io/en/latest/getting-started.html#docker-local-install) I get the following error:
```
==============================================================================
Starting DefectDojo
==============================================================================

/opt/django-DefectDojo/docker/docker-startup.bash: line 34: venv/bin/activate: No such file or directory
```
The only place within the container there is an `activate` script is at `/usr/lib/python3.5/venv/scripts/posix/activate`.

**Comment by orval** [comment]
@BlauerPulli Do you have instructions we could follow?

**Comment by BlauerPulli** [comment]
i am currently work on that and will make a pull request if it works

**Comment by BlauerPulli** [comment]
@aaronweaver there are several changes in the setup.bash and the dojo-shared-resources.sh necessary. Shall I create new versions of them(at least of setup.bash and a new entrypoint script)  especially for a docker setup? If I integrate my changes the whole setup process is quite more confusing and i dont know if the other installations are affected..

**Comment by BlauerPulli** [comment]
Or rechecking of that very nice pull request would be a goot idea: https://github.com/DefectDojo/django-DefectDojo/pull/824
@devGregA @aaronweaver @mtesauro

**Comment by irawanhd** [comment]
> I am seeing a similar issue. When I use the docker run command shown [here](https://defectdojo.readthedocs.io/en/latest/getting-started.html#docker-local-install) I get the following error:
> 
> ```
> ==============================================================================
> Starting DefectDojo
> ==============================================================================
> 
> /opt/django-DefectDojo/docker/docker-startup.bash: line 34: venv/bin/activate: No such file or directory
> ```
> The only place within the container there is an `activate` script is at `/usr/lib/python3.5/venv/scripts/posix/activate`.

I'm having the same issue. did you resolved it?

**Comment by orval** [comment]
> I'm having the same issue. did you resolved it?

No. I switched to this fork: https://github.com/JonathanWilbur/django-DefectDojo

**Comment by DshSec** [comment]
Hello, MySQL error occurred when I built this environment with docker. What should I do?

Is there any effective way to shoot wrong ideas or solutions to tell me?

Thank you.

The following are commands and errors:

Docker run-it-p 8000:8000 appsecpipeline/django-defectdojo bash-c "export LOAD_SAMPLE_DATA=True & bash/opt/django-DefectDojo/docker/docker-startup.bash"

* Starting MySQL database server mysqld No directory, logging in with HOME=/

**Comment by DshSec** [comment]
Hello, MySQL error occurred when I built this environment with docker. What should I do?

Do you have any effective ideas or solutions to troubleshooting?

Thank you.

The following are commands and errors:

Docker run-it-p 8000:8000 appsecpipeline/django-defectdojo bash-c "export LOAD_SAMPLE_DATA=True & bash/opt/django-DefectDojo/docker/docker-startup.bash"

* Starting MySQL database server mysqld No directory, logging in with HOME=/

**Comment by aaronweaver** [comment]
Fixed in dev and push soon to master. Thanks to Hendrik Mallow's assistance.
