### ISSUE TITLE
Deploy Defectdojo Kuberbetes environement 

### ISSUE THREAD

**Issue by azoumed** [DefectDojo/django-DefectDojo#849]
Hi 
i try to deploy defectdojo in Kubernetes environement , but i'm blocked in important step when  i deploy through pod .

i share with you error message : 

Error: failed to start container "defect-dojo": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/opt/django-DefectDojo/dojo\": permission denied": unknown
_____________________________________________________________________________________
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: defectdojo
  #namespace: @@KUBE_NameSpace@@

spec:
  replicas: 1  
  template:
    metadata:
      labels:
        app: defectdojo 
        name: defectdojo 
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: defect-dojo 
          image: appsecpipeline/django-defectdojo
          imagePullPolicy: Always
          command: ["/opt/django-DefectDojo/dojo"]
          args: ["run"]
          resources:
            requests:
             cpu: 250m
             memory: 256Mi
            limits:
             cpu: 2000m                             
             memory: 4096Mi
          ports:
          - containerPort: 8000 
          volumeMounts:
          - name: defectdojo-config
            mountPath: /opt/django-DefectDojo/dojo/settings/settings.dist.py
            subPath: settings.dist.py
          - name: defectdojo-data
            mountPath: /opt/django-DefectDojo/dojo

      volumes:
      - name: defectdojo-data
        persistentVolumeClaim:
          claimName: defectdojo-data-pvc
      - name: defectdojo-config
        configMap:
          name: defectdojo-configmap 
  
      nodeSelector:
        beta.kubernetes.io/os: linux

**Comment by aaronweaver** [comment]
Hi @azoumed, did you get this working then in Kubernetes? If so, maybe you would like to submit it to our community [repo](https://github.com/DefectDojo/community) under Kubernetes?

Thanks

**Comment by hendrikhalkow** [comment]
@azoumed have a look here: https://github.com/DefectDojo/django-DefectDojo/tree/k8s
