### ISSUE TITLE
During Qualys scan import, add finding "type" to the title. For easier filtering

### ISSUE THREAD

**Issue by nv-pipo** [DefectDojo/django-DefectDojo#8492]
**Qualys Scan**
While importing Qualys scans: The type defines if a finding is "Confirmed", "Potential" or "Information", adding this information to the title would allow ITSec analysts to focus on findings depending on the type (via filters).

Could you please approve the PR?
https://github.com/DefectDojo/django-DefectDojo/pull/8491

**Comment by tannerjones4075** [comment]
I believe that this issue should be closed.
