### ISSUE TITLE
cannot bulk verify findings

### ISSUE THREAD

**Issue by petrabrunner** [DefectDojo/django-DefectDojo#850]
Please use the following template when submitting issues: (If this is a security issue, then review the [disclosure policy](https://github.com/DefectDojo/django-DefectDojo/blob/master/SECURITY.md) and submit via our security reporting program.

### Issue Type 
- [x ] Bug
- [ ] Enhancement

### Description
I cannot bulk edit findings. Their initial import state is active and verified. (though I have tried with various different original import states) I can only bulk edit them to active or inactive. ... 
Did anyone else experience the same problem? 

### Operating System 
Ubuntu 18.04 LTS

### Install

- [ ] setup.bash
- [ x] docker

### DefectDojo Version
latest master (latest commit: f4dd2aa)

### Steps to Reproduce
-- see screenshot

### Screenshots (optional)
![image](https://user-images.githubusercontent.com/45869415/51373972-de4cc080-1b01-11e9-98be-00e5575a97e1.png)

**Comment by aaronweaver** [comment]
@petrabrunner What error do you see in the console? Right click, inspect, console?

**Comment by petrabrunner** [comment]
@aaronweaver I dont see an error. I cannot execute the click in the first place.
I do see a violation: 
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive.

![image](https://user-images.githubusercontent.com/45869415/52618809-24e2d000-2ea0-11e9-90bf-76b039ed87f5.png)
