### ISSUE TITLE
Unable to submit DefectDojo security issue via HackerOne

### ISSUE THREAD

**Issue by ratherbeonline** [DefectDojo/django-DefectDojo#852]
### Issue Type 
Bug

### Description
I have a security issue I would like to disclose. The documentation at https://github.com/DefectDojo/django-DefectDojo/blob/master/SECURITY.md suggests submitting security issues at https://hackerone.com/defectdojo/reports/new. However, the HackerOne program is currently private. Maybe you can send an invite to hackerone.com/johnny

**Comment by ratherbeonline** [comment]
<img width="444" alt="issue" src="https://user-images.githubusercontent.com/26527435/57522731-d34bb500-72d7-11e9-9736-95cbc262b1ba.png">

There is a systemic OWASP Top 10 vulnerability that exists across the DefectDojo application. The disclosure policy requests submission via HackerOne. This issue is now closed as stale. Unfortunately, I still have no method of disclosing within policy.

**Comment by ppiotr3k** [comment]
@devGregA, @aaronweaver, can you help on this one?

**Comment by aaronweaver** [comment]
It's hung up on the vetting process in hackerone. I'm going to switch back to bugcrowd and once that's up  I'll update this issue.

**Comment by reedloden** [comment]
@aaronweaver I believe you were talking to me. I'll reach out via e-mail again to get you unblocked.

**Comment by reedloden** [comment]
@aaronweaver Sent you an e-mail. Let me know if you're not getting them for some reason. You should be good to go on the HackerOne side now. Happy to help out further in any way!

**Comment by reedloden** [comment]
@ratherbeonline I moved your disclosure assistance report to the new program at https://hackerone.com/defectdojo. @aaronweaver should be able to see and respond to it now (if he hasn't already).

I believe this issue can be closed now.

**Comment by ratherbeonline** [comment]
Thanks everyone! 🙂
