### ISSUE TITLE
Docker setup (dev)

### ISSUE THREAD

**Issue by wurstbrot** [DefectDojo/django-DefectDojo#854]
### Issue Type 
- [x] Bug

### Description
Docker build runs.
docker run is not working afterwards.

### Install
- [x] docker

### DefectDojo Version
Current develop

### Steps to Reproduce
docker checkout dev
docker build test .
docker run test

Error:
´Error: '' is not a valid port number.´

I recommend to merge the WORKING solution from https://github.com/DefectDojo/django-DefectDojo/pull/824

**Comment by aaronweaver** [comment]
Fixed in dev and push soon to master. Thanks to Hendrik Mallow's assistance.
