### ISSUE TITLE
File upload size error "Report file is too large"

### ISSUE THREAD

**Issue by BrotherOfJhonny** [DefectDojo/django-DefectDojo#8543]
**Bug Description**
File upload size error on default docker installation of defectdojo in VM with Kali linux

**Steps to reproduce**
1. Go to 'http://0.0.0.0:8080/product/1/import_scan_results'
2. Click 'import data'

Imported file size error is displayed.

#### Report file is too large. Maximum supported size is 100 MB 

**Nginx Config**

/etc/nginx $ cat nginx.conf 
worker_processes 1;
error_log /var/log/nginx/error.log warn;
pid /var/run/defectdojo/nginx.pid;
events {
  worker_connections  1024;
}
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';
  access_log /var/log/nginx/access.log main;
  client_max_body_size 1G;
  sendfile on;
  keepalive_timeout 65;
  upstream uwsgi_server {
    include /run/defectdojo/uwsgi_server;
  }
  # Disable metrics auth for localhost (for nginx prometheus exporter)
  geo $metrics_auth_bypass {
    127.0.0.1/32 "off";
    default "Metrics";
  }
  server {
    server_tokens off;
    listen 8080;

    gzip on;
    gzip_types      application/atom+xml  application/geo+json  application/javascript  application/x-javascript  application/json  application/ld+json  application/manifest+json  application/rdf+xml  application/rss+xml  application/xhtml+xml  application/xml  font/eot  font/otf  font/ttf  image/svg+xml  text/css  text/javascript text/plain  text/xml;
    gzip_proxied    any;
    gzip_min_length 1000;

    location = /50x.html {
      root /usr/share/nginx/html;
    }
    location /static/ {
      alias /usr/share/nginx/html/static/;
    }
    location / {
      include /run/defectdojo/uwsgi_pass;
      include /etc/nginx/wsgi_params;
      uwsgi_read_timeout 1800;
    }
    location /django_metrics {
      # do no edit the following lines, instead set the environment  
      # variables METRICS_HTTP_AUTH_USER and METRICS_HTTP_AUTH_PASSWORD
      #auth_basic $metrics_auth_bypass;
      #auth_basic_user_file /etc/nginx/.htpasswd;
      include /run/defectdojo/uwsgi_pass;
      include /etc/nginx/wsgi_params;
      uwsgi_read_timeout 1800;
    }
    location /nginx_status {
      # do no edit the following lines, instead set the environment  
      # variables METRICS_HTTP_AUTH_USER and METRICS_HTTP_AUTH_PASSWORD
      #auth_basic $metrics_auth_bypass;
      #auth_basic_user_file /etc/nginx/.htpasswd;
      #stub_status  on;
      access_log   off;
    }
    # Used by Kubernetes liveness checks
    location = /nginx_health {
      return 200 "Born to be alive!\n";
      access_log off;
    }
    # Used by Kubernetes readiness checks
    location = /uwsgi_health {
      limit_except GET { deny all; }
      rewrite /.+ /login?force_login_form&next=/ break;
      include /run/defectdojo/uwsgi_pass;
      include /etc/nginx/wsgi_params;
      access_log off;
    }

    error_page 500 502 503 504 /50x.html;
  }
}
/etc/nginx $ 

**Deployment method** *(select with an `X`)*
- [X] Docker composition
- [ ] Kubernetes
- [ ] GoDojo

**Environmental Information**

https://github.com/DefectDojo/django-DefectDojo

**Comment by testaccount90009** [comment]
@BrotherOfJhonny actually you can set this to a different size / value in many different ways... 
1) dojo/settings/settings.dist.py
2) ENV variable

DD_SCAN_FILE_MAX_SIZE defaults to 100MB, but I have increased it to 1000MB and it is fine.

This is not a bug, but this is just a simple setting tweak to fix your error.  

Please update your pull request.

**Comment by manuel-sommer** [comment]
This can be closed @mtesauro
