### ISSUE TITLE
Contrast Security not available for import

### ISSUE THREAD

**Issue by hujarl** [DefectDojo/django-DefectDojo#855]
The documents state that Contrast CSVs can be imported, but within the import console Contrast is not an available choice from the scan type drop down.

**Comment by aaronweaver** [comment]
Check in the dev branch. We'll be pushing a new release soon.

**Comment by hujarl** [comment]
Still not seeing the Contrast Scanner import option under the Scan Type dropdown while importing Contrast CSVs
