### ISSUE TITLE
Dependency-track reimport fails to close findings if new import is empty

### ISSUE THREAD

**Issue by VM-Beebly** [DefectDojo/django-DefectDojo#8553]
Hello,

**Bug description**

I push findings from dependency-track to defectdojo using the builtin defectdojo integration in dependency-track. I also use the reimport option. If a developer fixes all findings in a dependency-track project, the next reimport will contain 0 findings. The expected behavior in defectdojo would be for existing findings to be closed. Instead, it throws an error.
DD_ASYNC_FINDING_IMPORT is set to true.

The following error is thrown while reimporting:

> ERROR [celery.app.trace:270] Task dojo.importers.reimporter.reimporter.process_parsed_findings[4c09c285-a141-49d4-befa-78d4e95f8586] raised unexpected: IndexError('list index out of range')
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
>     R = retval = fun(*args, **kwargs)
>                  ^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
>     return self.run(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/app/dojo/importers/reimporter/reimporter.py", line 240, in process_parsed_findings
>     reimporter_utils.chunk_endpoints_and_reactivate(endpoint_statuses)
>   File "/app/dojo/importers/reimporter/utils.py", line 118, in chunk_endpoints_and_reactivate
>     logger.debug('IMPORT_SCAN: Split endpoints into ' + str(len(chunk_list)) + ' chunks of ' + str(chunk_list[0]))
>                                                                                                                                                ~~~~~~~~~~^^^
> IndexError: list index out of range

I guess that in the case where no findings are in the report, chunk_list[0] isn't defined. 

It comes from this line in [dojo/importers/reimporter/utils.py](https://github.com/DefectDojo/django-DefectDojo/blob/54dd3a5904871ca60b480f0054e2afbbe824c967/dojo/importers/reimporter/utils.py#L118)

**Steps to reproduce**
1. Follow the dependency-track documentation about defectdojo integration
2. Set DD_ASYNC_FINDING_IMPORT to True in defectdojo
3. Enable the reimport feature in dependency-track
4. Have a project with findings in dependency-track, and push them in defectdojo a first time
5. Fix the findings in dependency-track and wait for the next reimport in defectdojo

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - DefectDojo version 2.24.4

Thanks for your help,

**Comment by pna-nca** [comment]
Just wanted to add that this bug is not Dependency Track-specific. I observe it with other types of scans in the mentioned configuration (asynchronous scan import).

**Comment by manuel-sommer** [comment]
Hi @quirinziessler .
Is this Bug still existing or do you also observe it?

**Comment by mtesauro** [comment]
@VM-Beebly 

I think the key thing to note about Async imports is in the docs:
> DefectDojo offers an experimental feature to aynschronously import security reports.

https://documentation.defectdojo.com/usage/performance/#asynchronous-import

"experimental" being the important word.
