### ISSUE TITLE
Azure AD Integration disappeared after Upgrade2.19.4 to 2.25.4

### ISSUE THREAD

**Issue by oluapG** [DefectDojo/django-DefectDojo#8579]
**Be informative**
I Tried upgrade the defect dojo from version 2.19.4 to 2.25.3 but after upgrade the Azure AD Integration disappeared. 

**Problem description**

I updated defect dojo version 2.19.4 to 2.25.3, when I tried access the botton of Azure AD Integration disappeared.  So I need build the image again and the image return to version 2.19.4. 

In this case, I need to clone new image v.2.25  and replace the file settings  ? 

**Steps to reproduce**

1. Upgrade
2.  docker pull defectdojo/defectdojo-django:latest
3.  docker pull defectdojo/defectdojo-nginx:latest
4. ./dc-stop.sh
5. ./dc-up-d.sh
6. Acesss console but the botton of Azure AD Integration disappeared

**Deployment method** *(select with an `X`)*
**- [X] Docker Compose**
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Ubuntu 20.04
 - DefectDojo version 2.19.4

**Comment by manuel-sommer** [comment]
Did you fix the issue? I guess you should rather ask in the owasp slack channel. Should we close this @mtesauro ?

**Comment by mtesauro** [comment]
Closed as stale
