### ISSUE TITLE
Finding Bulk Edit menu closes when Severity value selected

### ISSUE THREAD

**Issue by ddraillantclark** [DefectDojo/django-DefectDojo#8582]
**Bug description**
The Bulk Edit menu closes when you select a value in the Severity drop down. To apply the changes you have to open the Bulk Edit menu again and click Submit.

**Steps to reproduce**
1. Open https://demo.defectdojo.org/finding
2. Check some findings to make Bulk Edit appear
3. Choose any item in the Severity drop down menu

**Expected behavior**
As for the other fields in the Bulk Edit menu, setting a value in the Severity field should leave the menu open. The menu should not disappear unless you click Submit, click somewhere else in the page, or press Escape.

**Screenshots**
<img width="602" alt="image" src="https://github.com/DefectDojo/django-DefectDojo/assets/34193231/e4b0bed0-1c20-4fb2-b1b8-7f3be951aef9">

**Comment by mtesauro** [comment]
This issue is addressed in #8594 - it just needs to be merged and should be in the next release.
