### ISSUE TITLE
DefectDojo API v2

### ISSUE THREAD

**Issue by sakyra01** [DefectDojo/django-DefectDojo#8592]
Good day. Notice problem when I make request to DD API findings with params fields, I get full information about fields

Python
url = "https://defectdojo.<->/api/v2/findings/"
    params = {
        "fields": "date,severity,title"
    }
    headers = {
        "Authorization": "Token  <token>"
    }
    response = requests.get(url, params=params, headers=headers)
    findings = response.json()
    print(findings)

How to get only the fields I need from DD without additional processing of all fields?

**Comment by kiblik** [comment]
As I know, it is the default behaviour of `django-rest-framework` (which is used to provide DD API) so I suppose it is not possible right now.

But I just found lib which is able to limit in a way as you described: https://github.com/wimglenn/djangorestframework-queryfields
DD is open-source and I suppose the community might be willing to accept adding this functionality to API. It would be nice if somebody would be able to add it and test it.
