### ISSUE TITLE
Image upload not working

### ISSUE THREAD

**Issue by brunomcuesta** [DefectDojo/django-DefectDojo#8597]
**Problem description**
When I click on the WYSIWYG HTML editor icon to upload an image, no window appears to select an image for upload. Instead, the editor places a Markdown line.
DefectDojo is running in a container so it couldn't edit the Markdown line since the image is on the Ubuntu host.
This problem occurs in all **Findings** fields that use the WYSIWYG HTML editor.
How do I upload an image?

**Steps to reproduce**
1. Go to All Products.
2. Select a Product.
3. Click in Findings > View active findings.
4. On the three dots on the left select "edit".
5. Scroll down to Steps to Reproduce field (can be any other),
6. Click on the add image icon, 

![image](https://github.com/DefectDojo/django-DefectDojo/assets/816237/8dc10cdd-12bb-4670-87e4-475d44bd8b0d)

**Expected behavior**
Open a window that allows the user to select the image on the host for upload.

**Deployment method**
- [X ] Docker Compose

**Environment information**
 - Operating System: Ubuntu 22.04
 - DefectDojo version 2.25.4

Thanks!

**Comment by manuel-sommer** [comment]
https://github.com/DefectDojo/django-DefectDojo/issues/9120

**Comment by manuel-sommer** [comment]
Hi @mtesauro ,

can we either close #9120 or #8597 as they are duplicates?

**Comment by mtesauro** [comment]
@manuel-sommer #9120 was just closed as duplicate.

**Comment by manuel-sommer** [comment]
I guess this can be closed @mtesauro as image upload is working, see here: https://github.com/DefectDojo/django-DefectDojo/issues/7677#issuecomment-1946687506

I just tried it myself. The reporter is mixing up a linked image vs. an uploaded image.

**Comment by Dejavu610** [comment]
If these were a rich text editor, wouldn't it be better? Because we want to directly paste images under the text instead of uploading a bunch of files.

**Comment by chumperz** [comment]
Can we actually upload an image here? I know this is Markdown you can link an image... but if we are using this to manage our pentest findings, we can't actually upload an image?
