### ISSUE TITLE
API V2: Finding does not contain product / cannot filter on product

### ISSUE THREAD

**Issue by ISAF87** [DefectDojo/django-DefectDojo#860]
Please use the following template when submitting issues: (If this is a security issue, then review the [disclosure policy](https://github.com/DefectDojo/django-DefectDojo/blob/master/SECURITY.md) and submit via our security reporting program.

### Issue Type 
- [ ] Bug
- [ X ] Enhancement

### Description
API V1 lists the product url/id in each finding. 
API V2 doesn't do this. 

Neither API versions allow the filtering based on product

### Operating System 
Please include the version number (ex: Ubuntu 16.04)
Postman for Windows
Version 6.7.2
win32 10.0.16299 / x64

### Install

- [ ] setup.bash
- [ ] docker

### DefectDojo Version
v1.5.2

### Screenshots (optional)
Plain retrieval of findings (API V2):
![image](https://user-images.githubusercontent.com/24564971/51978444-7fd0fc00-248a-11e9-94fe-72b18a2881ff.png)

Filtered on date (API V2) (working):
![image](https://user-images.githubusercontent.com/24564971/51978476-9b3c0700-248a-11e9-9eb5-6b2ebb91ba87.png)

Result (API V1)
![image](https://user-images.githubusercontent.com/24564971/51978574-cde5ff80-248a-11e9-83c5-21ba724995bd.png)

**Comment by valentijnscholten** [comment]
I agree this would be a good addition to the API. Sometimes I want to query DD for the findings for a specific product and make some decisions based on that data.

**Comment by valentijnscholten** [comment]
Looking at this some more:
1) Filtering on product in APIv2 should be possible using the test__engagement__product parameter (I can see it working on dev branch at least). Could you test this?
2) The Finding result contains the id of the test, which can be used to retrieve the test which contains the id of the engagement. From engagement you can get the id of the product.
