### ISSUE TITLE
Microfocus webinspect csv or xml report 

### ISSUE THREAD

**Issue by irawanhd** [DefectDojo/django-DefectDojo#862]
Please use the following template when submitting issues: (If this is a security issue, then review the [disclosure policy](https://github.com/DefectDojo/django-DefectDojo/blob/master/SECURITY.md) and submit via our security reporting program.

### Issue Type 
- [ ] Bug
- [x ] Enhancement

### Description
Do you have any plan to support MicroFocus (previously own by HP) Webinspect report in upload finding format. tried generic csv import but its throw an error

### Operating System 
Please include the version number (ex: Ubuntu 16.04)

### Install

- [ ] setup.bash
- [ x] docker

**Comment by irawanhd** [comment]
> 
> 
> If you upload a couple scan files to https://github.com/DefectDojo/sample-scan-files we can add it to the list.

can you guide me to upload the scan file? Thanks

**Comment by aaronweaver** [comment]
Hi @irawanhd - You would need to do a pull request from your repo to this one and then I can merge it in.
Thanks!

**Comment by irawanhd** [comment]
Hi @aaronweaver 

I have created pull request. with two file export from Webinspect XML. Thanks..

**Comment by aaronweaver** [comment]
https://github.com/DefectDojo/sample-scan-files/tree/master/webinspect

**Comment by dr3dd589** [comment]
hello, @Maffooch you can assign this to me. working on it.

**Comment by dr3dd589** [comment]
@Maffooch you can close this one now.
