### ISSUE TITLE
How to configure Azure SSO for Raw Kubernetes (Not using Helm chart)

### ISSUE THREAD

**Issue by vanye-wadawasina-alida** [DefectDojo/django-DefectDojo#8626]
Problem description
Please how can I configure SSO for raw kubernetes? We are currently deploying DD in kubernetes by just pulling each of the manifest file, setting environment variables; we are not using helm chart. 

i.e the documentation mentions how to set the variables using helm chart  (https://defectdojo.github.io/django-DefectDojo/getting_started/configuration/#environment-variables) but not raw kubernetes file.

Steps to reproduce
I placed the environment variables in each of the manifest file (Uswgi, nginx) and it did not work; 
```


    DD_SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_KEY=(str, 'YOUR_APPLICATION_ID_FROM_STEP_ABOVE'),
    DD_SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_SECRET=(str, 'YOUR_CLIENT_SECRET_FROM_STEP_ABOVE'),
    DD_SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_TENANT_ID=(str, 'YOUR_DIRECTORY_ID_FROM_STEP_ABOVE'),
    DD_SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_ENABLED = True
    
```
    

Expected behavior
Login with azure SSO

Deployment method
Kubernetes individual manifest files 

Environment information
AWS EKS
DefectDojo latest version

**Comment by manuel-sommer** [comment]
I guess this is rather a question for the slack channel. Could you closed this @mtesauro ?
