### ISSUE TITLE
Defectdojo API v2 OpenAPI3 Docs not able to load in offline environment

### ISSUE THREAD

**Issue by weeshieh** [DefectDojo/django-DefectDojo#8627]
Cannot load API v2 OpenAPI3 Docs (blank page)

**Bug description**
The swagger-ui resources (css and js) have sources https://cdn.jsdeliver.net/npm/swagger-ui-dist@latest/
My environment for running defectdojo is offline (on-prem)

**Steps to reproduce**
1. Go to 'homepage'
2. Click on 'user icon at top right > API v2 OpenAPI3 Docs'
3. Right click the page > Inspect 
4. Select Console

**Expected behavior**
Able to provide API v2 OpenAPI3 Docs in offline environment?

**Deployment method** *(select with an `X`)*
- [X ] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Centos Linux 7
 - DefectDojo version (see footer) : 2.19.0

**Screenshots**
![Capture_unable-load-dd-api-docs](https://github.com/DefectDojo/django-DefectDojo/assets/74439415/f3642367-7ef6-48aa-8a06-d53184792c25)

**Comment by kiblik** [comment]
Can you try to set `DD_DEFAULT_SWAGGER_UI=False`?

https://github.com/DefectDojo/django-DefectDojo/blob/9742d9ff21b36ef7daf6b927ed5ac822c8227c49/dojo/settings/settings.dist.py#L203-L204

**Comment by weeshieh** [comment]
Yes thanks for point out. I am in the midst of doing an upgrade. Will update again when ready :)

**Comment by weeshieh** [comment]
Yes I upgraded to `2.21.0` and set the `DD_DEFAULT_SWAGGER_UI` to false in [django-DefectDojo/dojo/settings/settings.dist.py](https://github.com/DefectDojo/django-DefectDojo/blob/9742d9ff21b36ef7daf6b927ed5ac822c8227c49/dojo/settings/settings.dist.py#L203-L204) then managed to load the docs. Thank you
