### ISSUE TITLE
Harbor Parser: Reuploaded file does not touch finding to add mitigation

### ISSUE THREAD

**Issue by manuel-sommer** [DefectDojo/django-DefectDojo#8633]
**Bug description**
Upload a Harbor file via the Harbor parser to DefectDojo and upload it a second time, but then with a "fix_version". The "mitigation" field should be updated within the finding. Or we should only upload CVEs that can actually be fixed. 

**Steps to reproduce**
1. Upload a Harbor file
2. Adapt the Harbor file that a finding includes a "fixed_version".
3. Reupload this Harbor file to the same engagement
4. View the result (finding)

**Expected behavior**
The finding should be updated in a way that it now shows the mitigation. 

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - DefectDojo version: 2.27.0 (dev)

**Comment by manuel-sommer** [comment]
I guess this problem affects multiple parsers. Is there something planned in V3, @mtesauro ?

**Comment by manuel-sommer** [comment]
What if we add mitigation field to the HASHCODE_FIELDS_PER_SCANNER in https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/settings/settings.dist.py ? Would that work?

**Comment by C0mebreathe** [comment]
> What if we add mitigation field to the HASHCODE_FIELDS_PER_SCANNER in https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/settings/settings.dist.py ? Would that work?

seems to like it should solve your problem

**Comment by mtesauro** [comment]
Addressed in #8701
