### ISSUE TITLE
Start to use Pylint

### ISSUE THREAD

**Issue by kiblik** [DefectDojo/django-DefectDojo#8665]
Issues as https://github.com/DefectDojo/django-DefectDojo/issues/8636#issuecomment-1719081247 (fixed in https://github.com/DefectDojo/django-DefectDojo/pull/8663) would not happen if we would have a track of unused variables.

I suggest using Pylint to keep the code clean. Flake8 does a lot but it is not enough.

**Comment by mtesauro** [comment]
@kiblik Looks like well get that and more with #8704 - lets go with that and see how that work for now.
