### ISSUE TITLE
Add file_path field when parsing trivy results

### ISSUE THREAD

**Issue by Yuan-Yubin** [DefectDojo/django-DefectDojo#8669]
When I was using dojo to parse trivy scan results and re-upload them, I found that there were some different vuls that were marked as duplicates.

I have read the code and I think the problem lies in the configuration of HASHCODE_FIELDS_PER_SCANNER.

The original code is in the dojo\settings\settings.dist.py

HASHCODE_FIELDS_PER_SCANNER = {

    'Trivy Scan': ['title', 'severity', 'vulnerability_ids', 'cwe'],
    
}

I think a field `file_path` needs to be added to distinguish between the two vulnerabilities when parsing trivy results.

**Comment by mtesauro** [comment]
@Yuan-Yubin Thanks for the suggestion - would love to [see a PR](https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/CONTRIBUTING.md) to that effect as I don't have Trivy handy to validate this.

Worst case, you can always adjust that setting by overriding the value in local_settings.py to make that change local to your DefectDojo installation.
