### ISSUE TITLE
Deduplication problem

### ISSUE THREAD

**Issue by sakyra01** [DefectDojo/django-DefectDojo#8688]
Good day! Here is some problem.

When deduplication is enabled globally for all products and the option to remove duplicates is enabled, duplicates are not removed if they are within the same engagement but in different tests.

Real example:
When scanning images from harbor, a test is created for each new image, if the tests are repeated, i.e. the image does not change and the vulnerabilities are preserved, they are simply marked as duplicate and are not deleted.

**Comment by mtesauro** [comment]
Thanks for reporting this issue.

Looks like Harbor uses the deduplication algorithm specified [here](https://github.com/DefectDojo/django-DefectDojo/blob/358dde8faa1a5c009f8b227223a60f80d8531faa/dojo/settings/settings.dist.py#L1436).

I'd look at the docs for DEDUPE_ALGO_HASH_CODE in [this page.](https://documentation.defectdojo.com/usage/features/#deduplication)

Adjusting the [fields used to dedupe](https://github.com/DefectDojo/django-DefectDojo/blob/358dde8faa1a5c009f8b227223a60f80d8531faa/dojo/settings/settings.dist.py#L1240) for Harbor would likely correct the issue your seeing.

There's also been a [couple of recent PRs](https://github.com/DefectDojo/django-DefectDojo/pulls?q=is%3Apr+is%3Aopen+harbor) around the Harbor scanner as well. #8633 directly addresses this.

This is a configuration issue, not  a bug so removing that label.
