### ISSUE TITLE
Benchmarks controls API 

### ISSUE THREAD

**Issue by juanrafaelvillen** [DefectDojo/django-DefectDojo#8697]
## :warning: Note on feature completeness :warning:

We are narrowing the scope of acceptable enhancements to DefectDojo in preparation for v3. Learn more here:
https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/CONTRIBUTING.md

**Describe the solution you'd like**
It would be great to have an endpoint to modify benchmark's controls status or adding notes trough the API as we do for other objects such as Products, engagements or findings.

**Comment by mtesauro** [comment]
Thanks for the feature suggestion :+1: 

This is an interesting idea - it's just not something we can take up right now.

I've labeled this "consider-for-3.0" so it won't get lost when we get to the point we can consider that change.
