### ISSUE TITLE
Main page does not display properly

### ISSUE THREAD

**Issue by TmmmmmR** [DefectDojo/django-DefectDojo#870]
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Operating System 
Please include the version number (ex: Ubuntu 16.04)

### Install

- [x] setup.bash
- [ ] docker

### DefectDojo Version
 1.5.2

### Steps to Reproduce
installation using setup.bash script and access to the login page.

### Screenshots

![image](https://user-images.githubusercontent.com/5222862/52248411-3c411c80-28e6-11e9-9e90-43e163fa7de9.png)

### Console Logs

![image](https://user-images.githubusercontent.com/5222862/52248394-26335c00-28e6-11e9-9288-a2b2310ffc03.png)

**Comment by aaronweaver** [comment]
There was a change in a version of a static asset. Copy this [file](https://github.com/DefectDojo/django-DefectDojo/blob/dev/components/package.json) into components/package.json and then re-run yarn by executing the following commands.

1. In the root of your dojo directory 
2. cd components && yarn && cd ..
3. python manage.py collectstatic --noinput

**Comment by TmmmmmR** [comment]
Thanks, it solved the issue !
