### ISSUE TITLE
Keycloak Auth InvalidAudienceError: Audience doesn't match

### ISSUE THREAD

**Issue by scott86** [DefectDojo/django-DefectDojo#8705]
I'm trying to deploy a keycloak-enabled DefectDojo instance in a kubernetes environment.

We followed these instructions: https://defectdojo.github.io/django-DefectDojo/integrations/social-authentication/#keycloak

We've double-checked all the environment variables and we believe everything is correct, but we always get the "Audience doesn't match" error from the JWT library when we click the "Login with keycloak" button.

Is there a way to disable audience validation entirely?

**Comment by mtesauro** [comment]
I don't believe any of the active contributors have keycloak available to test the SSO integration.
 
You might be able to find something in the upstream Python module docs - https://python-social-auth.readthedocs.io/en/latest/configuration/django.html

Other than that, I'm not sure what to tell you.  Perhaps someone in the community who uses keycloak can chime into this issue.

**Comment by scott86** [comment]
We were able to get the login to work. It was something specific to our environment where the audience name was not being stored in the proper variable.

We can log in to the dashboard with the keycloak button now. However, our service scripts have been unable to make calls to the v2 API ever since we configured the keycloak environment variables.  We double-checked the API key we are using and according to the dashboard it is still valid.  Is there anything we need to do differently when sending API requests to a keycloak-enabled DD instance?

**Comment by mtesauro** [comment]
I've never used keycloak but have had several other SSO providers (Google Auth, Okta, AzureAD) and all of them were fine with API calls.

I'd try using curl to make API calls with headers and verbosity on to see if you can see any errors. At the same time, I'd look at the DefectDojo/Django container and watch the logs for errors.  I suspect there's an issue with nginx or however you're handling ingress to your DefectDojo container.
