### ISSUE TITLE
Site https://defectdojo.pythonanywhere.com/ down

### ISSUE THREAD

**Issue by barbich** [DefectDojo/django-DefectDojo#873]
### Issue Type 
- [X] Bug
- [ ] Enhancement

### Description

Demo site on https://defectdojo.pythonanywhere.com/ is down.

### Operating System 
N/A

### Install

- [ ] setup.bash
- [ ] docker

**Comment by aaronweaver** [comment]
@barbich We don't use that site anymore, where did you find the link to it? The demo site is [here](https://defectdojo.herokuapp.com). Thanks

**Comment by barbich** [comment]
@aaronweaver link is on the defectdojo site https://www.defectdojo.org/ text in the page says "If you'd like to check out a demo of DefectDojo before installing it, you can check out our demo." with demo pointing to the wrong page.

**Comment by aaronweaver** [comment]
Ah ok thx will update that one.
