### ISSUE TITLE
Documenting Trivy-DefectDojo-Report Operator

### ISSUE THREAD

**Issue by rndmh3ro** [DefectDojo/django-DefectDojo#8732]
**Is your feature request related to a problem? Please describe**

I built a custom Kubernetes operator (https://github.com/telekom-mms/trivy-dojo-report-operator) that listens for vulnerability reports generated by the Trivy Operator and forwards them to DefectDojo for further analysis and tracking.
It uses DefectDojo's `import-scan` API-endpoint for this.
I'd like to document this.

**Describe the solution you'd like**
Should the docs live here? https://documentation.defectdojo.com/integrations/parsers/file/trivy_operator/

What should I document? A one-liner and link to the project?

**Comment by manuel-sommer** [comment]
Done, this can be closed @mtesauro
