### ISSUE TITLE
Disable SSL verification for import scan using Black Duck Api 

### ISSUE THREAD

**Issue by saldam72** [DefectDojo/django-DefectDojo#8745]
Hello Team,
can you give a setting like DD_JIRA_SSL_VERIFY for import scan using Black Duck Api ?

ref. https://github.com/blackducksoftware/hub-rest-api-python/wiki/Client-API-Reference

Best,
Sal

**Comment by manuel-sommer** [comment]
I don't know if it makes sense to disable ssl verification. 
You can make a custom setting in the code: https://github.com/DefectDojo/django-DefectDojo/blob/738dca4534382049ca7587a60fb6b33715213943/dojo/tools/api_blackduck/api_client.py#L13
Just add: `verify=False`

I guess this can be closed @mtesauro ?

**Comment by mtesauro** [comment]
I agree that DefectDojo won't ship with ignoring TLS errors on by default. It's open source and anyone is free to remove those checks in their own installation.
