### ISSUE TITLE
Import Report Greenbone (Openvas) XML

### ISSUE THREAD

**Issue by c0dr123** [DefectDojo/django-DefectDojo#8761]
### Discussed in https://github.com/DefectDojo/django-DefectDojo/discussions/8750

<div type='discussions-op-text'>

<sup>Originally posted by **c0dr123** September 28, 2023</sup>
Dear Sir or Madam,

we use the vendor Greenbone, the company distributes the paid version of Openvas. The paid version allows only export to XML 
 / json format of a report. Could you enable an import from Greenbone (Openvas) to XML / json file?</div>

**Comment by c0dr123** [comment]
[26.09.2023_openvas_metasploitable2-scan.xml.zip](https://github.com/DefectDojo/django-DefectDojo/files/12764764/26.09.2023_openvas_metasploitable2-scan.xml.zip)

**Comment by manuel-sommer** [comment]
Hi @c0dr123, 

could you please do the following:

- mark my comment in https://github.com/DefectDojo/django-DefectDojo/discussions/8750 as "answer"
- provide a scan result with 0 findings for the unittest
- provide a scan result with 1 finding for the unittest

**Comment by c0dr123** [comment]
Hi @manuel-sommer ,

could you explain that in more detail?
Do you need a scan without vulnerabilities and a scan with vulnerabilities or does it have to be exactly one vulnerability.

**Comment by manuel-sommer** [comment]
Hi @c0dr123,
for each new parser unittests are needed. The unittests cover 3 scenarios for each parser: 0 findings, one finding, multiple findings. Thus, I need two more scan results which cover the scenarios 0 findings and exactly one finding. An example can be found here: https://github.com/DefectDojo/django-DefectDojo/tree/master/unittests/scans/cobalt 

Regarding "_mark my comment in https://github.com/DefectDojo/django-DefectDojo/discussions/8750 as answer_ ":
You just wrote an additional comment, but I don't know if you have the rights to mark my comment as the answer, see here: https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/participating-in-a-discussion#marking-a-comment-as-an-answer

**Comment by c0dr123** [comment]
Hi @manuel-sommer ,

as requested, the Findings are attached. Unfortunately, I do not have permission to mark the comment as " answer ".
[Archiv.zip](https://github.com/DefectDojo/django-DefectDojo/files/12812936/Archiv.zip)

**Comment by manuel-sommer** [comment]
You can close the issue @c0dr123
