### ISSUE TITLE
Please update the docker compose CLI V2

### ISSUE THREAD

**Issue by trnayan** [DefectDojo/django-DefectDojo#8787]
From July 2023 Compose V1 stopped receiving updates. It's also no longer available in new releases of Docker Desktop. The new Compose V2, which supports the compose command as part of the Docker CLI, is now available.

 Ref: https://docs.docker.com/compose/reference/

Compose V2 integrates compose functions into the Docker platform, continuing to support most of the previous docker-compose features and flags. You can run Compose V2 by replacing the hyphen (-) with a space, using docker compose, instead of docker-compose.

**Comment by manuel-sommer** [comment]
I guess ghis can be closed @mtesauro
