### ISSUE TITLE
 the "save" button on the "edit risk acceptance" field is invisible.

### ISSUE THREAD

**Issue by lme-nca** [DefectDojo/django-DefectDojo#8801]
**Bug description**
 the "save" button on the "edit risk acceptance" field is invisible.

**Steps to reproduce**

- Create a Risk acceptance
- go to engagements and edit risk acceptance
- scroll down to under "Restart SLA on expiration"
- There should be a save button (it is there if you hover) but not visible 

**Expected behavior**
- the save button is visible

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [ x] Kubernetes
- [ ] GoDojo

**Environment information**
 - DefectDojo version: 2.26.4

**Screenshots**
![image](https://github.com/DefectDojo/django-DefectDojo/assets/79927042/88f241cb-5bff-4a87-8e3c-971365b8a612)

**Additional context** (optional)
- Tested on Firefox, Chrome and Safari: none can see the button

**Comment by lme-nca** [comment]
It seems background color is set to transparent somehow

The following CSS line is causing this:
""
.panel-default .btn-primary {
    /* background-color: transparent!important;

""

![image](https://github.com/DefectDojo/django-DefectDojo/assets/79927042/b6709834-deeb-4b35-883f-541c65fa93a8)

**Comment by lme-nca** [comment]
okay, its actually caused by the button being inside a DIV with "panel default". see:
https://github.com/netceteragroup/django-DefectDojo/blame/0217ed77ccd5ac0ada19148f34e669a13ef41b77/dojo/templates/dojo/view_risk_acceptance.html#L30

**Comment by lme-nca** [comment]
The UI is different for the "edit" mode here as compared to "findings" because of this as well... as the "panel default" seems to keep the blue boxes around all the fields. I guess an easy fix would be to move the button underneath all the panels ? (maybe rename them to be consistent with "edit finding" i.e. "Finished") but i do not know how the Defectdojo team keeps the style consistent ?

**Comment by manuel-sommer** [comment]
The PR closed this issue. Could you close this issue @mtesauro ?
