### ISSUE TITLE
Read-only access, e.g. for reviews/audits

### ISSUE THREAD

**Issue by xthk** [DefectDojo/django-DefectDojo#882]
### Issue Type

- [ ] Bug
- [X] Enhancement

### Description

As a DefectDojo superuser I'd like to grant read-only access to users, e.g. for reviews or audits.

I can think of three options here:

- global read-only role, like "superuser", but read-only
- ~per product, like "Authorized users", but "Read-only users"~
- per product, add permissions (read-write or read-only) to "Authorized users"

As mentioned by @valentijnscholten, there is already the option to use the "Authorized users" available for a single product. Therefore I struck through the above item in the list.

### DefectDojo Version

1.5.1

**Comment by valentijnscholten** [comment]
For me it already works like this. Authorized users can only view engagements/findings and cannot modify anything. But it sounds like that might be a bug? I'm all for better permission/role management, even if it's only documenting how it currently works or is supposed to work.

**Comment by xthk** [comment]
Hi @valentijnscholten,
you are right. I'll remove the per product items from the above list.
