### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by zhukovmisha** [DefectDojo/django-DefectDojo#8820]
**How to set up a timezone in DefectDojo**
I live in Moscow, Russia and I'd like to set up the correct timezone

I tried a bunch of staff:

1. Changing dojo/setting/setting.dist.py
2. Creating dojo/setting/.env.prod
DD_TIME_ZONE="Europe/Moscow"
4. Changed all timezones in containers TZ="Europe/Moscow"
5. Adding the right timezone here docker/environments
6. Changed it in GUI to Europe/Moscow

and yet when importing a scan I get UTC

**Comment by shipko** [comment]
Hi, Misha! 
What type of scan you was using?

**Comment by zhukovmisha** [comment]
Eventually, rebuilding the containers worked out for me
