### ISSUE TITLE
HCL appscan on cloud integration 

### ISSUE THREAD

**Issue by ausmanki** [DefectDojo/django-DefectDojo#8829]
Hi team I am a active user of defect dojo where I have been using it for a long time I could see defect dojo supports IBM appscan and not hcl appscan on cloud as you know IBM appscan was acquired by hcl appscan try to build a functionality that accepts hcl appscan XML report the current parser is not accepting hcl appscan on cloud XML report

**Comment by mtesauro** [comment]
@ausmanki Is it possible for you to provide a sanitized example of the output of HCL AppScan? That will needed if a new or update parser is to be written.

If you can, please add it to this issue.  Thanks!

**Comment by ausmanki** [comment]
[demo_1.txt](https://github.com/DefectDojo/django-DefectDojo/files/12925174/demo_1.txt)
Thanks @mtesauro  please find a sample xml

**Comment by ausmanki** [comment]
one issue and no issue reports
[one issue.txt](https://github.com
[no issue.txt](https://github.com/DefectDojo/django-DefectDojo/files/13038005/no.issue.txt)
/DefectDojo/django-DefectDojo/files/13038004/one.issue.txt)

**Comment by ausmanki** [comment]
i have attached the sample files

**Comment by manuel-sommer** [comment]
@ausmanki I guess something went wrong with your upload. Maybe it is easier to just zip all three files and upload them all at once in a zip.

**Comment by manuel-sommer** [comment]
Hi @ausmanki , I made a PR for that scanner, but right now the unittests fail because "one findings" from your supported reports is an invalid xml file. It can't be parsed. 
You can validate it with: https://www.xmlvalidation.com

_The element type "issue-type-group" must be terminated by the matching end-tag "</issue-type-group>"._

**Comment by ausmanki** [comment]
can you attach the file so that i can look it out through

**Comment by manuel-sommer** [comment]
https://github.com/DefectDojo/django-DefectDojo/blob/a3c33284279762edbee2a2889778d1d98bd2817a/unittests/scans/hcl_appscan/one_finding.xml

**Comment by ausmanki** [comment]
[one issue.txt](https://github.com/DefectDojo/django-DefectDojo/files/13042660/one.issue.txt)
updated

**Comment by manuel-sommer** [comment]
This fail is has 0 issues in it. Nevermind, I will just remove the one finding unittest and we will see what the maintainers say.

**Comment by manuel-sommer** [comment]
@ausmanki could you give me input about the comment from cneil in https://github.com/DefectDojo/django-DefectDojo/pull/8858:
"_Can you add a little more detail here about how to generate a report in the proper format for the parser? Doesn't have to be super detailed (see [Snyk](https://documentation.defectdojo.com/integrations/parsers/file/snyk/) and [Bandit](https://documentation.defectdojo.com/integrations/parsers/file/bandit/) examples)_"

**Comment by manuel-sommer** [comment]
https://github.com/DefectDojo/django-DefectDojo/pull/8858

**Comment by manuel-sommer** [comment]
This can be closed as it was merged.
