### ISSUE TITLE
sonarqube plugin input file

### ISSUE THREAD

**Issue by barbich** [DefectDojo/django-DefectDojo#883]
Hi
can someone clarify what is the import file for the newer sonarqube plugin?

tx

**Comment by aaronweaver** [comment]
It was generated by a contributor and the export was created with an intermediate file that couldn't get released. We probably won't include it in the next release, unless there is a format we can get directly from Sonar without having to run an intermediate app. Would you be able to provide me with some sample files?

**Comment by barbich** [comment]
hi
in fact I do. Sonarqube has a nice API to allow extracting various informations such as (in our case) issues which would correspond to vulnerabilities. I currently generate a XLSX file with some statistics but it can be tweaked for more. I will do this in the upcoming days and share the script + sample outcome.

tx

**Comment by barbich** [comment]
hi
wrote a python wrapper to sonar api to extract a csv of the issue of a given project.
Script is at [https://gitlab.com/barbereau/sonar-issue-extract] with a sample csv generated on a scan of defectdojo (see [https://sonarcloud.io/dashboard?id=barbich_django-DefectDojo])

**Comment by aaronweaver** [comment]
Nice, I like it. Can you submit a sample file to: https://github.com/DefectDojo/sample-scan-files and if you want you can submit the parser to: https://github.com/DefectDojo/community or we can link to it in the notes.

Also, for sonarcloud interesting that it was picking up these php files. django-DefectDojo/static/jquery/test/.

**Comment by barbich** [comment]
Will submit the files in a couple of days.
For sonar: the results are strange. If I run a local docker instance of the community version I get very different results (towards python code), I will post as sample the run from a local scan and from sonarcloud.
I also realised it could be as simple to change my code a bit to generate a csv that can be parsed by the defectdojo csv parser ...

**Comment by aaronweaver** [comment]
I agree adding language would be very interesting, thanks for the update!

**Comment by barbich** [comment]
created pull request as suggested.
Also too opportunity to relaunch the sonarcloud scan (with more representative results):
https://sonarcloud.io/dashboard?id=barbich_django-DefectDojo
