### ISSUE TITLE
MobSF scan for ipa file couldn't be processed

### ISSUE THREAD

**Issue by dmytro-tkachenko2** [DefectDojo/django-DefectDojo#8860]
**Bug description**
Hello, colleagues
some time ago, for me, it's since MobSF version 3.6.0, import scans of ipa files stopped working, regardless DefectDojo version.
Now, for DefectDojo version v. 2.27.2 ( release mode ) and MobSF version 3.7.6, when report generated with MobSF is being imported to DefectDojo, we're getting error in defectdojo-django pod:

```
ERROR [dojo.api_v2.exception_handler:36] 'detailed_desc'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/app/dojo/api_v2/views.py", line 3472, in perform_create
    serializer.save(push_to_jira=push_to_jira)
  File "/app/dojo/api_v2/serializers.py", line 2502, in save
    ) = reimporter.reimport_scan(
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/importers/reimporter/reimporter.py", line 609, in reimport_scan
    parsed_findings = parser.get_findings(scan, test)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/tools/mobsf/parser.py", line 154, in get_findings
    "title": details["detailed_desc"],
             ~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'detailed_desc'
```

After a quick review differences in report json files generated with MobSF, I found a light difference in JSON path of this field from error above - 'detailed_desc':

MobSF 3.6.0: 

_.binary_analysis.Binary makes use of malloc function.detailed_desc
.binary_analysis.Binary makes use of insecure API(s).detailed_desc
.binary_analysis.Binary makes use of the insecure Random function(s).detailed_desc
.binary_analysis.Binary makes use of Logging function.detailed_desc_

MobSF 3.7.6:

_.binary_analysis.findings.Binary makes use of insecure API(s).detailed_desc
.binary_analysis.findings.Binary makes use of the insecure Random function(s).detailed_desc
.binary_analysis.findings.Binary makes use of Logging function.detailed_desc
.binary_analysis.findings.Binary makes use of malloc function.detailed_desc_

^^^ you can see odd '.finding' part for newr version of MobSF

**Steps to reproduce**
1. Grab MobSF scan as a JSON file
2. Go to an Engagement and click Import Scan Results
3. Scroll down to Choose report file and upload MobSF scan

**Expected behavior**
A successful scan import, DefectDojo parses the scan and properly displays findings.

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Linux 5.10.186-179.751.amzn2.x86_64
 - DefectDojo version (see footer) or commit message: 2.27.2 ( release mode )

**Logs** 
```
ERROR [dojo.api_v2.exception_handler:36] 'detailed_desc'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/app/dojo/api_v2/views.py", line 3472, in perform_create
    serializer.save(push_to_jira=push_to_jira)
  File "/app/dojo/api_v2/serializers.py", line 2502, in save
    ) = reimporter.reimport_scan(
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/importers/reimporter/reimporter.py", line 609, in reimport_scan
    parsed_findings = parser.get_findings(scan, test)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/tools/mobsf/parser.py", line 154, in get_findings
    "title": details["detailed_desc"],
             ~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'detailed_desc'
```

**Sample scan files**
If applicable, add sample scan files to help reproduce your problem.

**Screenshots**

**Additional context** (optional)

**Comment by manuel-sommer** [comment]
Hi @dmytro-tkachenko2 , could you put scan file here, then I can submit a fix in a PR?

**Comment by dmytro-tkachenko2** [comment]
hello, @manuel-sommer!
sure, here is a MobSF scan report, generated even with more recent version of MobSF - 3.7.9. I checked JSONpaths I mentioned above -- problem persists. 

Thank you in advance! 
[mobsf_3.7.9.json](https://github.com/DefectDojo/django-DefectDojo/files/13051101/mobsf_3.7.9.json)

**Comment by manuel-sommer** [comment]
Hi @dmytro-tkachenko2 could you check the PR please if the results are right?

**Comment by dmytro-tkachenko2** [comment]
@manuel-sommer, looks good for me :)
Thanks a lot!

**Comment by manuel-sommer** [comment]
@dmytro-tkachenko2 I pushed another fix. The number of findings is correct for your reported file?

**Comment by dmytro-tkachenko2** [comment]
@manuel-sommer looks like all works as expected
I've built DD from your branch and tested real MobSF ipa scan reports import. All were successful. And number of findings is correct.
Thank you!

**Comment by mtesauro** [comment]
The approvals are rolling in for #8865 so I'm going to go ahead and close this one.

Feel free to reopen if needed.

**Comment by aposhliakov** [comment]
Hi there,
I would like to ask which version fix will be released in?
Thanks

**Comment by mtesauro** [comment]
@aposhliakov The DEV branch will become 2.28.0 on the first Monday of November (2023-11-06)
