### ISSUE TITLE
Veracode combined static and dynamic not imported

### ISSUE THREAD

**Issue by barbich** [DefectDojo/django-DefectDojo#887]
Please use the following template when submitting issues: (If this is a security issue, then review the [disclosure policy](https://github.com/DefectDojo/django-DefectDojo/blob/master/SECURITY.md) and submit via our security reporting program.

### Issue Type 
- [X] Bug
- [ ] Enhancement

### Description
Veracode detailed report containing dynamic and static scan are not imported.
"simple" static reports are imported without problems.

### Operating System 
Please include the version number (ex: Ubuntu 16.04)
Ubuntu 18.1

### Install

- [ ] setup.bash
- [X] docker

### DefectDojo Version
latest-dev
but issue could be reproduced with older versions too

### Steps to Reproduce
try to import attached sample static&dynamic report

### Sample Scan File (if applicable)

[Sample_Static_and_Dynamic.detailed.xml.gz](https://github.com/DefectDojo/django-DefectDojo/files/2852294/Sample_Static_and_Dynamic.detailed.xml.gz)

### Console Logs (optional)
Environment:

Request Method: POST
Request URL: http://dojo.test/product/19/import_scan_results

Django Version: 1.11.18
Python Version: 2.7.15
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'polymorphic',
 'overextends',
 'django.contrib.admin',
 'django.contrib.humanize',
 'gunicorn',
 'tastypie',
 'auditlog',
 'dojo',
 'tastypie_swagger',
 'watson',
 'tagging',
 'custom_field',
 'imagekit',
 'multiselectfield',
 'rest_framework',
 'rest_framework.authtoken',
 'rest_framework_swagger',
 'dbbackup',
 'taggit_serializer')
Installed Middleware:
['django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'dojo.middleware.LoginRequiredMiddleware',
 'dojo.middleware.TimezoneMiddleware']

Traceback:

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/opt/django-DefectDojo/dojo/product/views.py" in import_scan_results_prod
  380.     return import_scan_results(request, pid=pid)

File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/opt/django-DefectDojo/dojo/engagement/views.py" in import_scan_results
  516.             parser = import_parser_factory(file, t)

File "/opt/django-DefectDojo/dojo/tools/factory.py" in import_parser_factory
  64.         parser = VeracodeXMLParser(file, test)

File "/opt/django-DefectDojo/dojo/tools/veracode/parser.py" in __init__
  59.                     dupe_key = sev + flaw.attrib['cweid'] + flaw.attrib['module'] + flaw.attrib['type'] + flaw.attrib['line'] + flaw.attrib['issueid']

Exception Type: KeyError at /product/19/import_scan_results
Exception Value: 'line'

**Comment by aaronweaver** [comment]
@barbich Can you provide a sample combined report to the samples repo?

Thx!

**Comment by barbich** [comment]
A scan is attached in the issue:

[Sample_Static_and_Dynamic.detailed.xml.gz](https://github.com/DefectDojo/django-DefectDojo/files/2852294/Sample_Static_and_Dynamic.detailed.xml.gz)

**Comment by barbich** [comment]
created pull request as suggested.

**Comment by wheelq** [comment]
where can I find this PR?

**Comment by wheelq** [comment]
using dev brach, importing this file fails with:

```
uwsgi_1         | Internal Server Error: /test/6/re_import_scan_results
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 538, in get_or_create
uwsgi_1         |     return self.get(**kwargs), False
uwsgi_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 408, in get
uwsgi_1         |     self.model._meta.object_name
uwsgi_1         | tagging.models.Tag.DoesNotExist: Tag matching query does not exist.
uwsgi_1         |
uwsgi_1         | During handling of the above exception, another exception occurred:
uwsgi_1         |
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
uwsgi_1         |     return self.cursor.execute(sql, params)
uwsgi_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
uwsgi_1         |     return self.cursor.execute(query, args)
uwsgi_1         |   File "/usr/local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
uwsgi_1         |     res = self._query(query)
uwsgi_1         |   File "/usr/local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 312, in _query
uwsgi_1         |     db.query(q)
uwsgi_1         |   File "/usr/local/lib/python3.7/site-packages/MySQLdb/connections.py", line 224, in query
uwsgi_1         |     _mysql.connection.query(self, query)
uwsgi_1         | MySQLdb._exceptions.DataError: (1406, "Data too long for column 'name' at row 1")
uwsgi_1         |
uwsgi_1         | The above exception was the direct cause of the following exception:

```
