### ISSUE TITLE
Unable to configure SonarQube API integration using API key

### ISSUE THREAD

**Issue by brampat** [DefectDojo/django-DefectDojo#8883]
**Problem description**
I'm trying to set up integration between SonarQube and Defect Dojo. However, when I try to access SonarQube's API through Defect Dojo's Tool integration, I get an error.

**Steps to reproduce**
1. Start SonarQube
2. Create a user DefectDojo with an API access key in SonarQube
3. Start DefectDojo
4. Go to Tools configurator
5. Add Tool Type SonarQube, with the following info:
6. Url: "http://localhost:9000/api" (without double quotes)
7. Authentication type: API Key
8. Username "DefectDojo" (as username in SonarQube from step 2)
9. Password: as entered in SonarQube, used to try out for Auth type username/password
10. Title for SSH / API Key: DefectDojo (same as in step 8)
11. SSH kEy <empty>
12. API Key: as copied from SonarQube in step 2
13. Click on 'Submit'

I get the following error in Defect Dojo:
`HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /api/components/search?qualifiers=TRK (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffa2ada4d0>: Failed to establish a new connection: [Errno 111] Connection refused'))`

**Test Using CURL**
In a terminal, I perform the following:
$curl -u <token, same as step 12>: http://localhost:9000/api/user_tokens/search

I receive:
`{"login":"DefectDojo","userTokens":[{"name":"DefectDojo","createdAt":"2023-10-23T12:00:21+0000","lastConnectionDate":"2023-10-23T12:44:40+0000","type":"USER_TOKEN"}]}`

This tells me that both the user and the API token work on SonarQube's side.

**Expected behavior**
Defect Dojo can successfully connect to SonarQube

**Deployment method** *(select with an `X`)*
- Docker Compose
- SonarQube in Docker as well Community Edition Version 10.2.1 (build 78527)

**Environment information**
 - Operating System: Docker / Alpine (?)
 - DefectDojo version v. 2.27.0 ( release mode )

**Logs** 
No corresponding logs are written in SonarQube

**Sample scan files**
NA

**Screenshots**
NA

**Additional context** (optional)
NA

**Comment by valentijnscholten** [comment]
Looks like defect dojo can't access SonarQube. Remember that inside the container `localhost` refers to the running container, not to the host machine. You can bash into the uwsgi container and try some curling to find out how to reach SQ, something like `docker-compose exec uwsgi -it /bin/sh`

**Comment by manuel-sommer** [comment]
To me this sounds like a configuration issue. 
This can be closed @mtesauro
