### ISSUE TITLE
body overflow 

### ISSUE THREAD

**Issue by bilalmirza74** [DefectDojo/django-DefectDojo#8889]
**Slack us first!**
The easiest and fastest way to help you is via Slack. There's a free and easy signup to join our #defectdojo channel in the OWASP Slack workspace: [Get Access.](https://owasp-slack.herokuapp.com/)
If you're confident you've found a bug, or are allergic to Slack, you can submit an issue anyway.

body of the website is getting overflow because of banner image

**Be informative**
Please enter as much information as possible, otherwise we can't provide support. If possible upgrade to the latest release or dev version and try again.

**Bug description**
A clear and concise description of what the bug is. For errors include at least the exact error message you are seeing (including traceback).

**Steps to reproduce**
1. Go to https://www.defectdojo.com/
2. see on banner image
3. resize the tab for more info

**Expected behavior**

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [ ] Kubernetes
- [x] GoDojo

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo version (see footer) or commit message: [use `git show -s --format="[%ci] %h: %s [%d]"`]

**Logs** 
Use `docker-compose logs` (or similar, depending on your deployment method) to get the logs and add the relevant sections here showing the error occurring (if applicable).

**Sample scan files**
If applicable, add sample scan files to help reproduce your problem.

**Screenshots**

![image](https://github.com/DefectDojo/django-DefectDojo/assets/84387676/4472d65f-22ae-4b3b-b091-a5f7a798ee63)

**Additional context** (optional)

**Comment by manuel-sommer** [comment]
@bilalmirza74 do you want to do a PR here?
