### ISSUE TITLE
Finding: Add CVE field

### ISSUE THREAD

**Issue by Sec-Team-XING** [DefectDojo/django-DefectDojo#889]
### Issue Type 
- [ ] Bug
- [x] Enhancement

### Description

As most of our findings are vulnerabilities with a dedicated CVE, we'd like to have a separate, optional field for that on the Finding model.  Also, this needs some work on the Dependency Check parser to extract the CVE.

**Comment by dr3dd589** [comment]
@aaronweaver Can I take this issue to start working on it.

**Comment by HSR-4** [comment]
pyscraping from www.cvedetails.com and simplifying to short report,
Is this a good method?

**Comment by Nilix007** [comment]
> pyscraping from [www.cvedetails.com](http://www.cvedetails.com) and simplifying to short report,
> Is this a good method?

I'm not sure what do you want to achieve with this.

The Dependency Check reports CVEs for most vulnerabilities.

**Comment by devGregA** [comment]
Added.
