### ISSUE TITLE
API support for custom Fields

### ISSUE THREAD

**Issue by jbryanmiller** [DefectDojo/django-DefectDojo#891]
### Issue Type 
- [x ] Question

### Description

Does the API support custom fields ? Retrieving, Updating , Adding , etc

### Operating System 
Windows 10

### Install
- [x ] docker

### DefectDojo Version
v2

**Comment by shizzgar** [comment]
Yo, @jbryanmiller, man, if you still need this functionality, 
You can use metadata API.
![image](https://github.com/DefectDojo/django-DefectDojo/assets/39241841/00e11818-4189-4fc0-aaa9-c73af8483898)
You can add metadata to project and it will be displayed in product page. 
![image](https://github.com/DefectDojo/django-DefectDojo/assets/39241841/4782c674-5663-48c0-bf0d-a3805ada9a8f)
So, you can use such custom field later.
![image](https://github.com/DefectDojo/django-DefectDojo/assets/39241841/a01a53a3-3050-42ad-a9b1-ccc810fb3a46)
