### ISSUE TITLE
Issue with github actions

### ISSUE THREAD

**Issue by Vijaygawate** [DefectDojo/django-DefectDojo#8913]
I am using below github actions to send trvy report to detectdojo but report is not sending to defectdojo 
Github action is running fine, but when I check the UI, it show nothing

Docker-image-scan:
    runs-on: ubuntu-latest
    needs: ['build', 'depchecktest', 'build-and-push-docker-image', 'test-stage']
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/Hklsdksdk/bluegreen'
          format: 'json'
          output: 'trivy-results.json'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Upload results to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: trivy-results
          path: trivy-results.json
      - name: Publish report
        id: import-scan
        uses: ivanamat/defectdojo-import-scan@v1
        with:
          token: c651bb5dc6209fb0cf8c9527dae5cbe784129ec0
          defectdojo_url: 'https://detectdojo.com'
          file: trivy-results.json
          scan_type: Trivy Scan
          engagement: 1

**Comment by manuel-sommer** [comment]
I guess this rather should be asked in  the slack channel. Maybe closed this @mtesauro ?
