### ISSUE TITLE
Issue with importing nuclei.json report from nuclei scan into DefectDojo

### ISSUE THREAD

**Issue by Trincazul** [DefectDojo/django-DefectDojo#8920]
**informative**
When attempting to import the report from the nuclei.json file in DefectDojo through the frontend, I am confronted with the error message mentioned above. This prevents the viewing of results and hinders the intended functionality of DefectDojo.

**Bug description**
Problem Summary: When attempting to import the report from the nuclei.json file in DefectDojo through the frontend, I am encountering an error that prevents a successful import.

**Steps to reproduce**
1. Logged into my account.
2. Navigated to the report import section.
3. Selected the nuclei.json file for import.
4. Provided the necessary information for the import.
5. Clicked the button to initiate the import.
6. Encountered the aforementioned error during the import of the nuclei.json file.

**Expected behavior**
I expected the report to import successfully without errors, allowing me to view the results in DefectDojo.

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Debian GNU/Linux 12 (bookworm)
 - DefectDojo version: Merge pull request #8875 from DefectDojo/release/2.27.3 [ (HEAD -> master, tag: 2.27.3, origin/master, origin/HEAD)]

**Screenshots**
![Captura de tela em 2023-11-01 09-46-34](https://github.com/DefectDojo/django-DefectDojo/assets/49641058/7520fe7b-725a-4c6d-bde1-6ede99edc6c4)

**Additional context** 
I appreciate your assistance in resolving this issue within DefectDojo. I look forward to a solution that allows for the successful import of the nuclei.json report through the frontend.

**Comment by manuel-sommer** [comment]
Hi @Trincazul, could you please add a sample output to reproduce this issue?

**Comment by noskiddie** [comment]
> Hi @Trincazul, could you please add a sample output to reproduce this issue?

Any json report from nuclei version 3+ have the error.

In logs you can find this:

`[06/Nov/2023 12:27:04] ERROR [dojo.engagement.views:704] 'list' object has no attribute 'get'
Traceback (most recent call last):
  File "/app/dojo/engagement/views.py", line 688, in import_scan_results
    test, finding_count, closed_finding_count, _ = importer.import_scan(scan, scan_type, engagement, user, environment, active=active, verified=verified, tags=tags,
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/importers/importer/importer.py", line 315, in import_scan
    parsed_findings = parser.get_findings(scan, test)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/tools/nuclei/parser.py", line 36, in get_findings
    template_id = item.get("templateID", item.get("template-id", ""))
                  ^^^^^^^^
AttributeError: 'list' object has no attribute 'get'`

**Comment by Trincazul** [comment]
@noskiddie I have the same error, I updated the nuclei and it didn't help

**Comment by manuel-sommer** [comment]
See linked issue

**Comment by noskiddie** [comment]
> @noskiddie I have the same error, I updated the nuclei and it didn't help

@manuel-sommer You done! fixed this error. Now the nuclei reports is uploading to Dojo.

**Comment by manuel-sommer** [comment]
You can close this at @Trincazul. The fix was merged.

**Comment by Trincazul** [comment]
Issue fixed, thanks @manuel-sommer
