### ISSUE TITLE
Launch scans for supported tools like zap, burp pro, arachni through rest api

### ISSUE THREAD

**Issue by itsgauravjain22** [DefectDojo/django-DefectDojo#895]
### Issue Type 
- [ ] Bug
- [x] Enhancement

### Description
Kindly add the launch scan feature in defect dojo, so that the supported tools can be used to assess the application for vulnerability by using the defect dojo application in one place instead of going to separate application and invoke the scan and then import the scan from each tool.

### Operating System 
Linux Mint 19 Cinnamon

### DefectDojo Version
1.5.3.1

**Comment by aaronweaver** [comment]
I agree, it's been on our backlog and I know how it can be done. Stay tuned!

**Comment by itsgauravjain22** [comment]
Thanks for the update. Kindly have a look at this [tool](https://github.com/archerysec/archerysec) which support invoking web scans assesment tools.

**Comment by ninp0** [comment]
Here's one as well: https://github.com/0dayinc/csi
