### ISSUE TITLE
Clair json importer

### ISSUE THREAD

**Issue by kempy007** [DefectDojo/django-DefectDojo#896]
### Issue Type 
- [ ] Bug
- [X] Enhancement

### Description
I thought there was support for importing clair scan results in json format. I can only see on Dev branch under dojo/tools, a folder for clair.  

Tried to copy dojo/tools onto appsecpipeline/django-defectdojo 
But the tool still won't show up, What does one have to do to create a custom parser?

I'm using arminc/* and objectiflibre/clair-scanner to generate the scan data.

Should I just parse externally and submit each finding over the API

### Install

- [ ] setup.bash
- [X] docker

### DefectDojo Version
latest

**Comment by aaronweaver** [comment]
@kempy007 this will be in master shortly. Working on a release candidate. Thx!
