### ISSUE TITLE
Missing Accunetix report on upload section

### ISSUE THREAD

**Issue by itsgauravjain22** [DefectDojo/django-DefectDojo#899]
### Issue Type 
- [ ] Bug
- [x] Enhancement

### Description
The dfectdojo currently not supporting accunetix scanners report, which are highly used in market. It would be great to have the support of accunetix tool in defectdojo.

**Comment by aaronweaver** [comment]
@itsgauravjain22 I believe this has been added in dev. If you would like to confirm it works.
