### ISSUE TITLE
Excel Export of the Findings broke after updating from 2.17.0 to 2.27.3

### ISSUE THREAD

**Issue by Wincioor11** [DefectDojo/django-DefectDojo#8996]
When exporting the findings (Open or ALL) in EXCEL format using this option in Findings view, the data is corrupted. Multiple columns are mismatched with their values. 

This doesn't affect the CSV export option, which can be used as a workaround. 
![image](https://github.com/DefectDojo/django-DefectDojo/assets/38164733/4b75cd84-b850-482a-9781-d15ed31b8708)

**Comment by mtesauro** [comment]
@Wincioor11 
There was an issue with CSV/Excel export fixed in 2.28.0 - [details here](https://github.com/DefectDojo/django-DefectDojo/releases/tag/2.28.0) which could lead to the issue you're experiencing.

I'd suggest you update to latest.
