### ISSUE TITLE
pip install fails with AttributeError

### ISSUE THREAD

**Issue by shreyansh23** [DefectDojo/django-DefectDojo#902]
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description
pip install fails with AttributeError: 'NoneType' object has no attribute 'splitlines'

### Operating System 
Ubuntu 18.04

### Install

- [x] setup.bash
- [ ] docker

### DefectDojo Version
(latest)

### Steps to Reproduce
install using ./setup.bash

### Screenshots
![screenshot from 2019-02-27 05-14-37](https://user-images.githubusercontent.com/32803230/53454866-a2850f00-3a4e-11e9-8377-8d0184c5e808.png)

**Comment by aaronweaver** [comment]
@sdesapriya I'd suggest trying out the docker-compose in dev. Thx!
