### ISSUE TITLE
how to   Migrate data from2.16 to2.28

### ISSUE THREAD

**Issue by summerainX** [DefectDojo/django-DefectDojo#9037]
i try upgrade from from2.16 to2.28
but i dont know how to migrate my data
i find my data seem in dojo.celerydb.sqlite ,so I copy this file in my new dir and run with docker 
but there is no data in my new 2.28 project
how can I migrate my data,is there any document? 
need help~QAQ

**Comment by manuel-sommer** [comment]
Hi @summerainX ,
regarding upgrading take a look here https://defectdojo.github.io/django-DefectDojo/getting_started/upgrading/

and if you have trouble, rather ask in the slack channel. 

I guess ww can closed this @mtesauro
