### ISSUE TITLE
deduplication bug: nessus issues with low severity replace high severity issues

### ISSUE THREAD

**Issue by petrabrunner** [DefectDojo/django-DefectDojo#904]
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description
when deduplicating findings of an engagement (in this case a nessus report and a ci/cd engagement) the high findings "disappeared" and became low or medium findings because they were deduplicated and the findings marked as "original", were the findings with the lower severity.... 

if duplicates exist I would expect the system to deduplicate the lower-prio issue into the higher-prio issue. not the other way around. aka. I dont want to loose visibility of the high-prio issues, because of deduplication in the "open findings" view. (also in reports etc. the duplicates would be "excluded" because the originals are reported anyway)

### Operating System 
Ubuntu 18.04 LTS 

### Install

- [ ] setup.bash
- [x] docker

### DefectDojo Version
https://github.com/DefectDojo/django-DefectDojo/commit/cce053272650283adf1a0c34ac0d61f15eb565cf

### Screenshots (optional)
![image](https://user-images.githubusercontent.com/45869415/53480838-4638e400-3a7c-11e9-9db3-eab9ea56c3dc.png) high issues as duplicates, no issues with severity "critical" exist, meaning that all of these high issues were deduplicated into lower prio issues...

**Comment by adracea** [comment]
Could you please check if this is still happening with the latest dev/master ? Also , could you give a few more details on which deduplication options were used ? Using deduplication on engagement can still currently cause this I believe but normal deduplication should be fixed .

**Comment by valentijnscholten** [comment]
Also could you tell which finding was considered as the original for the high ones that were marked dupllicate? Are they the same title/filepath/cwe?

**Comment by petrabrunner** [comment]
Hi guys, sry this takes so long. unfortunately I am having big trouble getting defectdojo up and running again after the update. I am running dojo in docker and the docker-compose seems to have changed quite a bit, and I have not been able to get it to run for now.
@adracea I will keep you posted after I get the system back up. But this could take a few days, as I have zero ideas why the system is not working. 
@valentijnscholten  I will check after I get the system back up (having problems with my old version as well unfortunately)


for the curious: the problems seems to be this (new version): 

> uwsgi_1         | wait-for-it.sh: waiting 30 seconds for mysql:3306
> uwsgi_1         | wait-for-it.sh: mysql:3306 is available after 0 seconds
> uwsgi_1         | *** Starting uWSGI 2.0.18 (64bit) on [Mon Apr 15 06:52:57 2019] ***
> uwsgi_1         | compiled with version: 6.3.0 20170516 on 15 April 2019 06:51:20
> uwsgi_1         | os: Linux-4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018
> uwsgi_1         | nodename: a500f9870db5
> uwsgi_1         | machine: x86_64
> uwsgi_1         | clock source: unix
> uwsgi_1         | pcre jit disabled
> uwsgi_1         | detected number of CPU cores: 2
> uwsgi_1         | current working directory: /app
> uwsgi_1         | detected binary path: /usr/local/bin/uwsgi
> uwsgi_1         | *** WARNING: you are running uWSGI without its master process manager ***
> uwsgi_1         | your memory page size is 4096 bytes
> uwsgi_1         | detected max file descriptor number: 1048576
> uwsgi_1         | lock engine: pthread robust mutexes
> uwsgi_1         | thunder lock: disabled (you can enable it with --thunder-lock)
> uwsgi_1         | uwsgi socket 0 bound to TCP address 0.0.0.0:3031 fd 3
> uwsgi_1         | Python version: 2.7.16 (default, Mar 27 2019, 09:43:28)  [GCC 6.3.0 20170516]
> uwsgi_1         | *** Python threads support is disabled. You can enable it with --enable-threads ***
> uwsgi_1         | Python main interpreter initialized at 0x564d67bf0bb0
> uwsgi_1         | your server socket listen backlog is limited to 100 connections
> uwsgi_1         | your mercy for graceful operations on workers is 60 seconds
> uwsgi_1         | mapped 72920 bytes (71 KB) for 1 cores
> uwsgi_1         | *** Operational MODE: single process ***
> uwsgi_1         | Traceback (most recent call last):
> uwsgi_1         |   File "./dojo/wsgi.py", line 29, in <module>
> uwsgi_1         |     application = get_wsgi_application()
> uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
> uwsgi_1         |     django.setup(set_prefix=False)
> uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 22, in setup
> uwsgi_1         |     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
> uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
> uwsgi_1         |     self._setup(name)
> uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
> uwsgi_1         |     self._wrapped = Settings(settings_module)
> uwsgi_1         |   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
> uwsgi_1         |     mod = importlib.import_module(self.SETTINGS_MODULE)
> uwsgi_1         |   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
> uwsgi_1         |     __import__(name)
> uwsgi_1         | ImportError: No module named settings
> uwsgi_1         | unable to load app 0 (mountpoint='') (callable not found or import error)
> uwsgi_1         | *** no app loaded. going in full dynamic mode ***
> uwsgi_1         | *** uWSGI is running in multiple interpreter mode ***
> uwsgi_1         | spawned uWSGI worker 1 (and the only) (pid: 1, cores: 1)

**Comment by adracea** [comment]
Yeah , this is related with one of the docker issues , namely #1036 , you should also check out #1045 for more info :)

**Comment by petrabrunner** [comment]
@adracea thx for the hint!!! the workaround provided in issue #1036 worked. :)
