### ISSUE TITLE
Missing notification templates

### ISSUE THREAD

**Issue by tomaszn** [DefectDojo/django-DefectDojo#9049]
Some notification templates are missing. For example, there is no "scan_added.tpl" for the built-in web UI alerts:
https://github.com/DefectDojo/django-DefectDojo/tree/release/2.28.2/dojo/templates/notifications/alert

Such issues are reported at the `DEBUG` level:
https://github.com/DefectDojo/django-DefectDojo/blob/release/2.28.2/dojo/notifications/helper.py#L139

I see three issues here:
1. The missing templates need to be created.
2. There are no CI tests that would ensure that all notification channels have the complete set of templates.
3. Missing templates should be logged as `WARNING`s when it breaks sending the expected notification. Optionally, there could be a runtime check on start, logging such issues as `DEBUG`.

**Comment by valentijnscholten** [comment]
If there is no notification specific template, the default `other.tpl` is used.

**Comment by tomaszn** [comment]
Thanks, closing then.
