### ISSUE TITLE
 Error: Well this was unexpected.

### ISSUE THREAD

**Issue by rayanepimentel** [DefectDojo/django-DefectDojo#9051]
**Slack us first!**
The easiest and fastest way to help you is via Slack. There's a free and easy signup to join our #defectdojo channel in the OWASP Slack workspace: [Get Access.](https://owasp-slack.herokuapp.com/)
If you're confident you've found a bug, or are allergic to Slack, you can submit an issue anyway.

**Be informative**
Please enter as much information as possible, otherwise we can't provide support. If possible upgrade to the latest release or dev branch and try again.

**Problem description**
A clear and concise description of what the problem is. For errors include at least the exact error message you are seeing (including traceback).

**Steps to reproduce**

**Expected behavior**

**Deployment method** *(select with an `X`)*
- [x] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Ubuntu 22.04.3 LTS
 - DefectDojo version (see footer) or commit message: v2.28.2

I followed the script:

```

git clone https://github.com/DefectDojo/django-DefectDojo
cd django-DefectDojo
# building
./dc-build.sh
# running (for other profiles besides postgres-redis look at https://github.com/DefectDojo/django-DefectDojo/blob/dev/readme-docs/DOCKER.md)
./dc-up.sh postgres-redis
# obtain admin credentials. the initializer can take up to 3 minutes to run
# use docker-compose logs -f initializer to track progress
docker compose logs initializer | grep "Admin password:"
```

However, when executing the command ./dc-up.sh postgres-redis, logs continue to appear for several minutes (as shown in the image), and upon trying to access the URL, the following error appears:

```
Well...
...this was unexpected.
```

<img width="819" alt="image" src="https://github.com/DefectDojo/django-DefectDojo/assets/37915359/21f04ad3-171a-4608-897b-c64edfea90bf">

<img width="830" alt="image" src="https://github.com/DefectDojo/django-DefectDojo/assets/37915359/e31a38fb-0b51-4d01-b993-07c1ca0a0a32">

**Comment by superbvgv** [comment]
Can cofirm got the same error yesterday.

**Comment by manuel-sommer** [comment]
Can't confirm, it just works fine. @mtesauro please close this. 
If you still have questions on how to run it locally, please ask in the slack channel.
