### ISSUE TITLE
Trufflehog report don't importing with "import scan result"

### ISSUE THREAD

**Issue by Slytherin-Master** [DefectDojo/django-DefectDojo#9062]
DD version - 2.26.4 
Trufflehog version - 3.63.1

My scan result in JSON format 
I scanning my local gitlab repository 

[](url)
[cs _ Security utilities _ trufflehog-multi.json](https://github.com/DefectDojo/django-DefectDojo/files/13484491/cs._.Security.utilities._.trufflehog-multi.json)

Problem:
When I upload my report to DD, I only get 1 finding, although there are 3 in the file.
When I load your example I get 3 findings.
<img width="1478" alt="Снимок экрана 2023-11-28 в 09 52 37" src="https://github.com/DefectDojo/django-DefectDojo/assets/78446946/a33f607c-41d1-451d-88bc-c0540db60c5c">

And this 1 finding description collect all 3 desciption:
<img width="1488" alt="Снимок экрана 2023-11-28 в 09 58 04" src="https://github.com/DefectDojo/django-DefectDojo/assets/78446946/29e01860-bd04-447a-85ed-20f56a4e8c05">

I do not understand what the problem is.
Because my file looks similar to your files in unittests.

The only difference is that I scan Gitlab

Can someone help me ?

**Comment by manuel-sommer** [comment]
I guess this can be fixed @mtesauro as this was not reproducable
