### ISSUE TITLE
Authentication via Gitlab

### ISSUE THREAD

**Issue by wywerne** [DefectDojo/django-DefectDojo#9084]
Hello,

When we use gitlab to authenticate users, the first and last names are reversed in the user list.

![image](https://github.com/DefectDojo/django-DefectDojo/assets/2127966/8c121e98-cde5-49b9-94bd-98e6fcce7355)

Regard,

**Comment by manuel-sommer** [comment]
Hi @wywerne ,
did you solve the issue? And if yes, could you advance the docs that others will not face the issue again?

**Comment by wywerne** [comment]
In version 2.30.4 : 

![image](https://github.com/DefectDojo/django-DefectDojo/assets/2127966/96abcab3-add6-4e97-a205-030dade3b0e0)

My first name is : Philippe
My last name is PETIT

Regard

**Comment by manuel-sommer** [comment]
Could you ask in the owasp slack channel?

**Comment by mtesauro** [comment]
Closed as stale
