### ISSUE TITLE
Trivy Parser Resulting Discrepancy in Severity and CVSS

### ISSUE THREAD

**Issue by farhanardiya** [DefectDojo/django-DefectDojo#9092]
**Bug description**
When trivy parses the CVSS vector, it only considers the nvd CVSS score, meanwhile trivy may use other sources that is defined in the SeveritySource parameter
Below is the problematic code (dojo/tools/trivy/parser.py)
<img width="554" alt="image" src="https://github.com/DefectDojo/django-DefectDojo/assets/79713416/2e145dfb-c7ed-4069-87f4-0ba839565e74">
Below is the proposed code (please correct this if it is not right, it has not been tested)
```
                cvss = vuln.get("CVSS", None)
                cvssv3 = None
                if cvss is not None:
                    nvd = cvss.get("nvd", None)
                    severity_source = vuln.get("SeveritySource", None)
                    if severity_source != "nvd" and severity_source != None:
                        custom_vendor = cvss.get(severity_source, None)
                        if custom_vendor is not None:
                            cvssv3 = custom_vendor.get("V3Vector", None)
                    else:
                        if nvd is not None:
                            cvssv3 = nvd.get("V3Vector", None)
```

**Steps to reproduce**
1. Import a trivy scan result (with dependency vulnerabilities which does not use nvd as its SeveritySource)
2. Check on defectdojo web, it either uses the nvd cvss score or not show any score at all if nvd score is not available, even though there is another cvss data source

**Expected behavior**
The cvss score is synced with the severity, meaning taking the SeveritySource into account when obtaining the cvss score

**Deployment method** *(select with an `X`)*
- [ x] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System:  Ubuntu 20.04
 - DefectDojo version (see footer) or commit message: v. 2.24.4 ( release mode )

**Comment by manuel-sommer** [comment]
This can be closed.
