### ISSUE TITLE
DefectDojo throwing error when Burp Rest API Json File contain binary

### ISSUE THREAD

**Issue by slimism** [DefectDojo/django-DefectDojo#9128]
Bug description
DefectDojo is having issues parsing a Burp Rest API scan when trying to import its JSON file into an Engagement. This is occurring when Json file contains binary 

Steps to reproduce

1. Grab Burp Rest API scan as a JSON file
2. Go to an Engagement and click Import Scan Results
3. Scroll down to Choose report file and upload Burp Rest API

Expected behavior
A successful scan import, DefectDojo parses the scan and properly displays findings.

Deployment method:
[X] Docker

Release: 
[X] v. 2.28.2
  
Operating System: 
[X] Ubuntu Jammy 22.04

![Screenshot 2023-12-06 at 16 33 24](https://github.com/DefectDojo/django-DefectDojo/assets/16501217/3cf17703-4662-44d6-afd4-25d966dbbb26)

Example of Response in Json causing error: 

[output.json](https://github.com/DefectDojo/django-DefectDojo/files/13598368/output.json)

If I remove the part below causing the error in the Json File (Which is binary) it will work normally: 

![Screenshot 2023-12-07 at 10 48 32](https://github.com/DefectDojo/django-DefectDojo/assets/16501217/d8b7c943-aa78-4971-927b-9037c076c556)

Sample of File without the part causing the error: 

[output_noerror.json](https://github.com/DefectDojo/django-DefectDojo/files/13598452/output_noerror.json)

![Screenshot 2023-12-07 at 10 55 03](https://github.com/DefectDojo/django-DefectDojo/assets/16501217/9fe9e98c-f590-4985-a3a4-f2d4b1d64f23)

**Comment by manuel-sommer** [comment]
I tried it out, but at the moment, I don't really know how to fix it. This is the problematic snippet after base64.b64decode(segment["data"]) 

\x00\x01\x00\x00\x00\x00\xffh\x00\x0b\x00\x00\x00\x01\xcf\x1c\x00\x00\xff\x14\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1cT\x06V\x00\xb30\n\x86\xaad\x84\xebx\x016\x02$\x03\x8bx\x0b\x85~\x00\x04 \x05\x86*\x07\xa3\x7f[\xeckq\xa7\xf0`\x7f\xb34(uW\x95\xdfs\xben\x07gE\x07t\xd88\x806\x90\x8d\x16\x1d\x88=\x0e\x94\xa2\xd6d\xff\xff\xff\xff\x1b\x92\x89\x8cYr\xc0%i\xdb\x02\xa0\x00\xe26\xe7\xcf\x17\x9a\xb9\n\x13\xd7Ir\x01UL5e\xe2\x88\xc2\x11\x98\x97\xa9\xce\xcb\x9a$\x83\x9b\xf0\x0e\t9\x84\xad\xed\xc7\xf9x\xa0K\xb5\xed\x08\xb9TPv\xa1\x8e\xa4\x9eQ\xbe\xaet\xbfZ9\x1e\xa5\x9c\xde

**Comment by manuel-sommer** [comment]
![grafik](https://github.com/DefectDojo/django-DefectDojo/assets/47991713/7284ce18-cd5a-4920-9edc-59c2a708992f)

**Comment by mtesauro** [comment]
Looks like this was fixed in #8244 so closing

**Comment by slimism** [comment]
If this was already resolved back in June then why isn't working in the most recent update on DefectDojo -.- Or am I missing something?

**Comment by manuel-sommer** [comment]
Hi @slimism,
I guess @mtesauro mixed something up here. 

@mtesauro, could you please help to get https://github.com/DefectDojo/django-DefectDojo/pull/9131 merged , then this issue is resolved.

**Comment by mtesauro** [comment]
@manuel-sommer Sure thing - I'll see if we can get the necessary approvals on that one.
