### ISSUE TITLE
MobSF scan results aren't fully processed

### ISSUE THREAD

**Issue by ahammoudeh96** [DefectDojo/django-DefectDojo#9132]
MobSF binary static scan results in json format aren't fully processed.DefectDojo skips lots of findings made by MobSF, e.g. malware analysis and code analysis

Steps to reproduce:

- Download json report via MobSF REST API
- Upload MobSF json report to DefectDojo either via REST API or WEB UI
- lots of findings are skipped!

**Comment by manuel-sommer** [comment]
Could you provide a sampleoutput? I can help you to fix this.

**Comment by ahammoudeh96** [comment]
Thank you for replaying back @manuel-sommer,

I have attached the following file:

- Mobsf scan result json file
- Mobsf scan result pdf file
- Defectdojo pdf file from the uploaded Mobsf scan result json file.

As you can see in mobsf json and pdf files the total numbers of findings are 36. defectdojo on the other hand only reports 21.

[defectdojo_scan_result.xlsx](https://github.com/DefectDojo/django-DefectDojo/files/13627018/defectdojo_scan_result.xlsx)
[download.pdf](https://github.com/DefectDojo/django-DefectDojo/files/13627019/download.pdf)
[mobsf_scan_result.json](https://github.com/DefectDojo/django-DefectDojo/files/13627021/mobsf_scan_result.json)

**Comment by manuel-sommer** [comment]
@ahammoudeh96 I started to fix the parser, could you provide more output files from different scans or test my fix?

**Comment by ahammoudeh96** [comment]
@manuel-sommer I have findings for two apps.

-------
**Allsafe - 1.4**
[allsafe.pdf](https://github.com/DefectDojo/django-DefectDojo/files/13635630/allsafe.pdf)
[allsafe.json](https://github.com/DefectDojo/django-DefectDojo/files/13635631/allsafe.json)
-------
**damnvulenrablebank**
[damnvulnerablebank.pdf](https://github.com/DefectDojo/django-DefectDojo/files/13635699/damnvulnerablebank.pdf)
[damnvulnrablebank.json](https://github.com/DefectDojo/django-DefectDojo/files/13635705/damnvulnrablebank.json)


I will create a dev defectdojo machine to test your fix. might takes a bit of time. you know management approval

**Comment by manuel-sommer** [comment]
You can also test on localhost. ;-) 

Tested both your json and added them to the unittests, they are processed fine.

**Comment by manuel-sommer** [comment]
This can be closed.
