### ISSUE TITLE
Contacts not updating through API

### ISSUE THREAD

**Issue by tpat13** [DefectDojo/django-DefectDojo#9164]
Hello! I've been having issues while trying to update the contacts within a product using the Defect Dojo API. This is the method: `/api/v2/products/{id}/ `Updating the contacts for a product will return a 200 status but doesn't actually update the contacts in the response body (even using the Swagger UI). I am on the latest Defect Dojo version. 

For example, just updating the technical contact:

My request body is just: `{"technical_ contact": 1}`
![image](https://github.com/DefectDojo/django-DefectDojo/assets/32806320/62df2688-af66-4e2a-a594-19e60cfab7bb)

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Comment by manuel-sommer** [comment]
Hi @tpat13,
I tested it at the demo.defectdojo.org and it worked fine.

![grafik](https://github.com/DefectDojo/django-DefectDojo/assets/47991713/102b2050-1883-42cb-80b7-9a4e4c0aa962)
![grafik](https://github.com/DefectDojo/django-DefectDojo/assets/47991713/c319997c-c6f6-4d9c-8b3c-977020822ad8)

**Comment by kiblik** [comment]
I'm quite surprised that you have received 200 because you have a typo there. The space after `_` should not be there.

**Comment by manuel-sommer** [comment]
Good catch @kiblik , I didn't see the spacing. :-D

**Comment by mtesauro** [comment]
Closing as this seems complete.  Feel free to reopen if needed.

**Comment by tpat13** [comment]
Thanks for catching that @kiblik! I am actually getting a 200 though even there's a space in `"technical_ contact"`. 

I tried the same request in the demo site to be sure: 
![image](https://github.com/DefectDojo/django-DefectDojo/assets/32806320/597c1411-c5f2-4cbc-bc8f-308ebade7c47)

**Comment by kiblik** [comment]
Hi @tpat13. Well yes. The API endpoint is simply ignoring everything that does not know. So your request is equal to `{}` which just says to make an empty update. Which is correct so it responds `HTTP 200`.
It is a good question whether this might be improved in general (for all endpoints) to implementation where endpoints will complain about unknown parameters.
