### ISSUE TITLE
Trivy parser for k8s cluster scan needs fix

### ISSUE THREAD

**Issue by veneber** [DefectDojo/django-DefectDojo#9170]
Trivy parser for kubernetes scans needs a fix since reports has changed it's structure. In the current implemetation of dojo, Trivy parser expects a json file and inspects it's ["Vulnerabilities"] and ["Misconfigurations"] objects/list. But now in the new structure, there is a ["Resources"] object/list that needs to be looped where each of them has it's own ["Vulnerabilities"] and ["Misconfigurations"] objects/lists to get the findings.
Currently if the reports are imported they are created empty. I've attached a example report.
[trivy-report-github.json](https://github.com/DefectDojo/django-DefectDojo/files/13676879/trivy-report-github.json)

**Comment by dsever** [comment]
k9s cluster? ;)

**Comment by dsever** [comment]
Looks like parser if version is not specified is using old schema, while k8s uses new schema but trivy not exposing the schema version :/

https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/trivy/parser.py#L78C16-L78C16

**Comment by manuel-sommer** [comment]
@veneber could you take a look at the fix #9215 if this works fine now?

**Comment by manuel-sommer** [comment]
This can be closed

**Comment by veneber** [comment]
@manuel-sommer I have tested it and It's working fine. Thank you so much !
