### ISSUE TITLE
flot-axis 0.0.0 malicious package?

### ISSUE THREAD

**Issue by Fl3xappeal** [DefectDojo/django-DefectDojo#9187]
# hackerone is saying you guys aren't accepting issues there? ...

SCA scanner has reported flot-axis within components/yarn.lock as a malicious package. I scanned locally and the github project directly and have found hits both times for this. 

Is this a true positive?

[www.npmjs.com/advisories?search=flot-axis](https://www.npmjs.com/advisories?search=flot-axis)
https://my.diffend.io/npm/flot-axis/0.0.1-security/1.0.0
https://www.mend.io/vulnerability-database/MSC-2023-15220
https://security.snyk.io/vuln/SNYK-JS-FLOTAXIS-5851108

**Comment by kiblik** [comment]
Based on my observation, DD contains
https://github.com/DefectDojo/django-DefectDojo/blob/ae5ff9d0677be1db39daa2a6db4811bb2a3fc4da/components/yarn.lock#L530-L532

https://github.com/markrcote/flot-axislabels/tree/a181e09d04d120d05e5bc2baaa8738b5b3670428

This version of the package does not contain malicious parts of the code.
It is just a coincidence of the similar/same name of the package.

But maybe I'm wrong.

**Comment by Fl3xappeal** [comment]
Do we know for sure that we are pulling flot-axislabels and not flot-axis? I like to think we are but I don't know etierh and can only rely on tools/what "building the depencies" outputs. In my case my scanner "builds the dependencies" for resolution rather than reg-ex and it is saying that this is building flot-axis 0.0.0. Unfortunately package managers and dependencies isn't my speciality but I would rather be safe than sorry on this project.

**Comment by kiblik** [comment]
If we are still talking about `flot-axis` within `components/yarn.lock`, these are files collected by `yarn`:
https://github.com/DefectDojo/django-DefectDojo/blob/ae5ff9d0677be1db39daa2a6db4811bb2a3fc4da/Dockerfile.nginx-alpine#L135-L138
https://github.com/DefectDojo/django-DefectDojo/blob/ae5ff9d0677be1db39daa2a6db4811bb2a3fc4da/Dockerfile.nginx-alpine#L146
```bash
$ docker exec -it django-defectdojo-nginx-1 /bin/sh
~ $ /usr/bin/sha256sum /usr/share/nginx/html/static/flot-axis/*
8eccd4bf8aed6caec3dd5ee1ec90d35c57e4604fb07675cfd202c4252128c6f9  /usr/share/nginx/html/static/flot-axis/README.md
002fd1985afe180e48a8551e18d2689826be3dda3009a1ce1cf006706a9726f6  /usr/share/nginx/html/static/flot-axis/jquery.flot.axislabels.js
```

They are the same as the mentioned malicious-free repo:
```bash
$ git clone git@github.com:markrcote/flot-axislabels.git
...
$ cd flot-axislabels
$ git checkout a181e09d04d120d05e5bc2baaa8738b5b3670428
...
$ sha256sum *
8eccd4bf8aed6caec3dd5ee1ec90d35c57e4604fb07675cfd202c4252128c6f9  README.md
002fd1985afe180e48a8551e18d2689826be3dda3009a1ce1cf006706a9726f6  jquery.flot.axislabels.js
```
Do you have an idea, where else a might be malicious package installed?

From my perspective, the scanner saw `flot-axis` and `0.0.0` and ignored `markrcote/flot-axislabels`, so it is False positive.

**Comment by Fl3xappeal** [comment]
thanks for digging into this. I learned something new to triage this and will take this in my back pocket. I am going to raise this issue with vendor so they can tune their solution. 

That was the only malicious package my tools detected. 

I'll try to close this out as false positive

**Comment by Fl3xappeal** [comment]
Closing, seems to be a false positive on scanner. Apologies, but I wanted to be extra sure given the potential severity here.

**Comment by mtesauro** [comment]
@Fl3xappeal Thanks for bringing this up - I was unaware that HackerOne paused new report submission on us. I'll get that sorted out as we prefer security issues be submitted there.
