### ISSUE TITLE
Some dependecies are deprecated

### ISSUE THREAD

**Issue by juanrafaelvillen** [DefectDojo/django-DefectDojo#9189]
Hi team,
Our SCA scanner has identify that several libraries are deprecated and also contains security vulnerabilities. Libraries affected:

- pyca/cryptography 3.4.8: This vulnerability has been patched on the new versions.
- PyJWT 2.3.0 : Users should upgrade to v2.4.0 to receive a patch for this issue.
- urllib3 1.26.5: This issue has been patched in urllib3 version 1.26.17 or 2.0.5

Could you please let us know when this dependencies will be updated to newest versions?

Thanks

**Comment by kiblik** [comment]
Hi @juanrafaelvillen,

can you please be more specific about your version and location of libraries, please?
When I check the latest release `2.29.3`: 
- I'm not able to find `pyca/cryptography`, only `cryptography` and it is in version `41.0.7` https://github.com/DefectDojo/django-DefectDojo/blob/ae5ff9d0677be1db39daa2a6db4811bb2a3fc4da/requirements.txt#L41
- `PyJWT` is in version `2.8.0` https://github.com/DefectDojo/django-DefectDojo/blob/ae5ff9d0677be1db39daa2a6db4811bb2a3fc4da/requirements.txt#L70
- and `urllib3` is in version `1.26.18` https://github.com/DefectDojo/django-DefectDojo/blob/ae5ff9d0677be1db39daa2a6db4811bb2a3fc4da/requirements.txt#L48

So it looks safe for me.

**Comment by manuel-sommer** [comment]
I guess this can be closed @mtesauro
