### ISSUE TITLE
Add ldap modules to docker image

### ISSUE THREAD

**Issue by olfway** [DefectDojo/django-DefectDojo#9199]
According to #3981 everyone who wants ldap auth have to patch and rebuild defectdojo images and then rebuild new versions too

dependencies:
```
python-ldap==3.4.2
django-auth-ldap==4.1.0
```

And also include ldap-utils in your Dockerfile.nginx and Dockerfile.django files, like so:
```
libldap2-dev \
libsasl2-dev \
ldap-utils \
```

Could you add it to default image instead?

**Comment by mtesauro** [comment]
Unfortunately, LDAP is not a supported integration with DefectDojo so it won't be part of the default images created by the project.

However, we do provide dockerfiles for all the images so there's not a great deal of work for you to create LDAP-ified version of the containers used by DefectDojo.  The dockerfiles are in the root of the repo so fee free to fork the project and adjust as needed. That's one of the big advantages of Open Source projects - you're free to modify them to fit your specific needs.

Best of luck!
