### ISSUE TITLE
Reduction of supported OS

### ISSUE THREAD

**Issue by wurstbrot** [DefectDojo/django-DefectDojo#921]
@hendrikhalkow and I restructure the setup for docker-compose and kubernetes.

We recognized that it is hard to support container and manual setup together.
We recommend to remove support for everything other than docker-compose and helm for setup. We will be happy to create a PR. A forecast is available at https://github.com/hendrikhalkow/django-DefectDojo/tree/k8s.
It uses the docker one process pattern. Due to that, we need to create multiple image for celery, database, django, message broker, ...
Therefore, we state that the best way is to support docker-compose and helm only. Specially the change from python2 to python3 might be challenging for some administrators.
@devGregA @mtesauro @aaronweaver do you agree?

**Comment by aaronweaver** [comment]
@wurstbrot nice timing. Last month I was looking at a few other popular opensource projects and saw that a few of them are doing exactly as you stated. What I'm thinking is that we move to docker-compose as the officially supported install but perhaps keep the legacy install for a few months and then officially remove it from the repo. Let me chat with the others and get their thoughts.
Thanks!

**Comment by rseedorff** [comment]
I agree @wurstbrot . It would be great if you support docker in the first place instead of a manual setup.

**Comment by hendrikhalkow** [comment]
That would be awesome. I recommend supporting both a Kubernetes installation via Helm and a Docker Compose installation.

I just added the Helm charts to the branch mentioned above, Docker Compose will be updated next.

**Comment by hendrikhalkow** [comment]
There is now the [k8s branch](https://github.com/DefectDojo/django-DefectDojo/tree/k8s) where we work on that topic.

**Comment by wurstbrot** [comment]
I recommend to use owasp/defectdojo-* on hub.docker.com and not defectdojo. I guess only the _projectleader_, e.g. @aaronweaver  has the right to do that.

**Comment by hendrikhalkow** [comment]
We can also use the owasp prefix, whichever you prefer. I chose defectdojo so that it is the same as on GitHub.

As we introduced these new images, should we remove the old docker image stuff from the source code? Or would you like to keep that for a while and remove it later?

**Comment by hendrikhalkow** [comment]
https://github.com/DefectDojo/django-DefectDojo/pull/927/files

**Comment by hendrikhalkow** [comment]
The changes to make DefectDojo run on Kubernetes and Docker Compose have been integrated into the dev branch. Now we can discuss how long the non-container setup should be supported. What do you think?
