### ISSUE TITLE
Importing duplicates in same product under different engagement

### ISSUE THREAD

**Issue by mrupnikm** [DefectDojo/django-DefectDojo#9211]
**Problem description**
I am not sure if I am using DD as intended but the issue I am having is that duplicate issues are imported under the same produc(API1)s but different engagement(Sprint1 and Sprint2). If I close issues in Sprint1 and try to upload the same results in Sprint2 I get the same issues highlighted.

I am using trivy and grype scans uploaded via the API(between them I have no duplication as deduplication_on_engagement=True for /api/v2/import-scan/ is working). I have Deduplicate findings and  Delete duplicates set to true and Max Duplicates set to 0. 

Please provide guidance  for this issue or how to approach this use case correctly 

**Deployment method**
- [ ] Docker Compose
- [x] Kubernetes
- [ ] GoDojo

**Environment information**
-  version 2.29.2 
- Mysql and Reddis

**Comment by manuel-sommer** [comment]
Hi @mrupnikm,
take a look here: https://defectdojo.github.io/django-DefectDojo/usage/features/#deduplication

If you have issues with deduplication, you should be more specific, e.g. name the parser and also add a sample scan file. 

Also, you can ask in the slack channel.

This can be closed @mtesauro
