### ISSUE TITLE
Character length exceeded at column 'component_name' while Importing Prowler V3 scan results

### ISSUE THREAD

**Issue by thesk7828** [DefectDojo/django-DefectDojo#9221]
**Bug description**
I found an error: "**_An exception error occurred during the report import:(1406, "Data too long for column 'component_name' at row 1")_**", while importing the Prowler V3 scan results. Later, I realize that there is a column name '_component_name_' at table '_dojo_finding_' under the db '_defectjdojo_' which is responsible to store AWS ARN location, that do-not accepts the value if character length exceeds, which is currently set as varchar(200) for both MySQL and PostgreSQL databases.

Hence, it led us down to import the Prowler V3 scan results half-way or less.

**Steps to reproduce**
1. Go to All Products -> select your desired product
2. Click on Findings -> Import Scan Results
3. Fill out the required details and upload the Prowler V3 output file in json format (FYI, my json file was 30 MB long 🥲) and hit the Submit button.
4. Finally after some spins of your cursor, a red pop-up will appear mentioning the error: "_An exception error occurred during the report import:(1406, "Data too long for column 'component_name' at row 1")_"

![image 1](https://github.com/DefectDojo/django-DefectDojo/assets/49841461/54fe0540-24de-4d69-9e62-b4153cf63a10)

**Expected behavior**
This is how the result to be expected after the fix.

![expected](https://github.com/DefectDojo/django-DefectDojo/assets/49841461/1789044e-261a-4aa3-b9bc-4915bea82d9a)

**Deployment method**
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Amazon Machine Image (Ubuntu Server 22.04 LTS (HVM), SSD Volume Type, x86_64, t2.Medium, 20 GB Storage)
 
![os](https://github.com/DefectDojo/django-DefectDojo/assets/49841461/6b57e3a9-208d-4f28-853e-3cdce74fe0b1)

 - DefectDojo version 2.29.3 (release mode)

**Sample scan files**
Not in the position to share the sample scan file, as per my client's instruction.

**Mitigation** 
Below are the steps/commands to fix the problem -

1.  **MySQL**
- Once, the container is running, take container shell with cmd: _docker exec -u 0 -it <container_ID> /bin/sh_
- Then, follow these command:
- _mysql -u defectdojo -p_ (to access MySQL server)
- _use defectdojo;_ (to select the DB)
- _select * from information_schema.columns where table_name='dojo_finding' and column_name like 'component_name';_ (to view the current configuration)
![image 2](https://github.com/DefectDojo/django-DefectDojo/assets/49841461/5df5fe72-2f40-4447-b4ad-89214f8d3e73)

- _ALTER TABLE dojo_finding MODIFY component_name VARCHAR(500);ALTER TABLE dojo_finding MODIFY component_name VARCHAR(500);_ (To modify the data type)

![image 3](https://github.com/DefectDojo/django-DefectDojo/assets/49841461/dce5835e-7dc0-466b-9e69-9d807a634989)

2. **PosgreSQL**
- Once, the container is running, take container shell with cmd: _docker exec -u 0 -it <container_ID> /bin/sh_
- Then, follow these command:
- _psql -U defectdojo -d defectdojo_ (to access PostgreSQL server)
- _SELECT column_name, data_type, character_maximum_length, is_nullable, column_default FROM information_schema.columns WHERE table_name = 'dojo_finding' AND column_name = 'component_name';SELECT column_name, data_type, character_maximum_length, is_nullable, column_default FROM information_schema.columns WHERE table_name = 'dojo_finding' AND column_name = 'component_name';_ (to view the current configuration)
![psql 1](https://github.com/DefectDojo/django-DefectDojo/assets/49841461/0cfdf91a-886e-48b0-9560-c5eecfd6b62e)

- ALTER TABLE dojo_finding ALTER COLUMN component_name TYPE VARCHAR(500); (To modify the data type)
![psql 2](https://github.com/DefectDojo/django-DefectDojo/assets/49841461/4f5896f6-1ac9-480c-b4bc-25c7460201ce)

**Conclusion**
And, this is how it will fix the Import Scan bug.
Help me out to contribute and fix this issue for the latest release to make DefectDojo more stronger, hope this do-not affect DefectDojo V3.

**Comment by manuel-sommer** [comment]
This can be closed.
