### ISSUE TITLE
Adding CVSS to the list of findings

### ISSUE THREAD

**Issue by uyless** [DefectDojo/django-DefectDojo#9278]
Hey,

starting with a vulnerability management in a quite big environment can be challenging. Specially when tools are used which are scanning everything and creating big lists of different, yet unknown, vulnerabilities for an import in defectdojo. Depending on the size of the environment, patch management and vulnerability management before using such tools, you could be overwhelmed by a big list of vulnerabilities found in your environment.

To have an easier mechanism for prioritizing each finding, it would be very helpful to have the CVSS score also listed in the list of findings. Thus making it more easy to filter and prioritize the fix of each finding, specially when you think that some of them might have an other score depending on the situation.

Kind regards

**Comment by manuel-sommer** [comment]
In order to prioritize findings, we added EPSS score recently (look at release 2.32). To me it can be closed. What is your opinion @mtesauro ?

**Comment by mtesauro** [comment]
@manuel-sommer Yes, I agree. We also have vunerability ID which can hold any vulnerability identifier you want so I think we're good here.

Additionally, you can provide CVSS (including environmental, etc) scores and DefectDojo will adjust the Severity of a finding accordingly so you can still utilize CVSS as long as you're OK with it being 'translated' into DefectDojo's severity levels.
