### ISSUE TITLE
HCL AppScan Support

### ISSUE THREAD

**Issue by 253153** [DefectDojo/django-DefectDojo#9279]
I'm evaluating DefectDojo to see if it is suitable to use as our primary vulnerability management tool in my organization. But when I try to import HCL AppScan results (into DefectDojo version 2.30.0) that I generated from HCL AppScan (version 10.4.0) I get some errors such as:

`An exception error occurred during the report import:'NoneType' object has no attribute 'text'`

`An exception error occurred during the report import:cannot access local variable 'issuetypename' where it is not associated with a value`

The [example file AppScan file provided by DefectDojo ](https://raw.githubusercontent.com/DefectDojo/sample-scan-files/master/appscan/ibm_appscan_xml_file.xml) though I am able to success.

The documentation only mentions DefectDojo support for HCL AppScan Cloud. There is also support for IBM AppScan which is HCL AppScan's old name. I have tried importing results as both. Does Defect Dojo at all support HCL AppScan results scanned locally? If so is there any AppScan version export/import was tested to be working with? Or is there any special configuration that needs to be done? 

Any help would be highly appreciated.

**Comment by manuel-sommer** [comment]
Hi @253153 ,
could you provide a sample scan result for the HCL AppScan, I can help you with a PR.

**Comment by 253153** [comment]
@manuel-sommer  please find the sample scan result here: 

[demo.testfire.net.zip](https://github.com/DefectDojo/django-DefectDojo/files/13835258/demo.testfire.net.zip)

**Comment by manuel-sommer** [comment]
@253153 could you take a look at the PR? It is not yet finished but should go in the right direction.

**Comment by 253153** [comment]
Wow thank you so much for the prompt changes. I will take a look tomorrow.

**Comment by 253153** [comment]
@manuel-sommer  Wow I am able to pull successful with that PR! Wow, thank you so much for patching this so quickly. That is really really great, props to you. I will continue my evaluation.

**Comment by manuel-sommer** [comment]
Don't hesitate to report other Bugs.

**Comment by fabio-gu** [comment]
Hi,
same issue here trying to import manually HCL AppScan demo.test file.
`An exception error occurred during the report import:cannot access local variable 'issuetypename' where it is not associated with a value.` 
I am evaluating defectDojo (docker installation, DefectDojo ver. 2.30.3. 
What I can do to fix the issue on docker installation?
thanks so much.
f

**Comment by manuel-sommer** [comment]
You can also just wait for next release next week Monday if I have it right and then test the next Release.

**Comment by fabio-gu** [comment]
Thank you so much. It will be the dockerized 2.30.4?

**Comment by manuel-sommer** [comment]
It will we Release 2.31.0

**Comment by manuel-sommer** [comment]
I don't know the exact Release cycle. Look it up or ask a maintainer

**Comment by mtesauro** [comment]
@fabio-gu 

Merges into dev get added to minor releases 2.X.0 - so this will be in February's 2.31.0 - minor releases happen on the first Monday of the month, unless it's a holiday, then it happens the next business day - basically Tuesday. So 2.31.0 should be out mid-day to afternoon (US timezone) on Feb 5th.

Merges into the bugfix branch get added to the patch 2.31.X release which happen every week there isn't a minor release.

@manuel-sommer ^ so now you know :wink:

**Comment by fabio-gu** [comment]
Thank you so much!
I will back to you after tested on my side the import. I'm sure it will go smooth

**Comment by fabio-gu** [comment]
> You can also just wait for next release next week Monday if I have it right and then test the next Release.

I built the (new) docker image (2.31) and I tested the appScan XML import. It works like a charm!! 
**Thank you so much!**
