### ISSUE TITLE
pip update error (Django>=1.11.18)

### ISSUE THREAD

**Issue by no-sec-marko** [DefectDojo/django-DefectDojo#928]
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description
In 9f82fed3086e7169c7952a2c5670f094713b7059, the latest django was introduced in the requirements.txt:
`Django>=1.11.18`

This runs in an error during the update process because Django in version 2 will be fetched. Instead, the update string should be somthing like this: `Django==1.11.*`

### Operating System 
CentOS

### Install

- [x] setup.bash
- [ ] docker

### DefectDojo Version
1.5.1

### Steps to Reproduce
Update the latest pip requirements
` pip install -r requirements.txt --upgrade`

### Log
>   Downloading https://files.pythonhosted.org/packages/7e/ae/29c28f6afddae0e305326078f31372f03d7f2e6d6210c9963843196ce67e/Django-2.1.7.tar.gz (8.6MB)
>     100% |################################| 8.6MB 121kB/s
>     Complete output from command python setup.py egg_info:
> 
>     ==========================
>     Unsupported Python version
>     ==========================
> 
>     This version of Django requires Python 3.5, but you're trying to
>     install it on Python 2.7.
>

**Comment by aaronweaver** [comment]
Thx correct!
