### ISSUE TITLE
Trivy import closing wrong findings

### ISSUE THREAD

**Issue by FuzzyGophers** [DefectDojo/django-DefectDojo#9290]
**Bug description**

I have a Trivy Scan with 75 findings and a second scan with 74 total findings as one vulnerability was fixed.

When re-uploading a new scan with the 74 findings (subsequent scan) and "Close Old Findings" set to true there are numerous vulnerabilities set to "Inactive, Mitigated" that should not be. There is only 1 vulnerability fixed.

A `diff -u` of the files confirms this from a schema perspective. There is one vulnerability remediated.

Am I missing something fundamental here?

**Steps to reproduce**
1. Import trivy_scan-tf.json (produces 75 findings as expected)
2. Reupload the scan with trivy_scan-tf-remediated.json with "Close Old Findings" set to true (should set relevant finding to "Inactive, Mitigated")
3. Approximately 8 findings will be set to "Inactive, Mitigated" which is not expected behavior.

**Expected behavior**
Only the relevant finding is set to "Inactive, Mitigated"

**Deployment method** *(select with an `X`)*
- [X] Docker Compose

**Environment information**
 - MacOs
 - DefectDojo version: 2.30

**Sample scan files**

These files were generated with `trivy config <dir>` against a Git repo.

[trivy_scan-tf-remediated.json](https://github.com/DefectDojo/django-DefectDojo/files/13850380/trivy_scan-tf-remediated.json)
[trivy_scan-tf.json](https://github.com/DefectDojo/django-DefectDojo/files/13850381/trivy_scan-tf.json)

**Comment by FuzzyGophers** [comment]
@manuel-sommer hoping you may have some insight here :)

**Comment by manuel-sommer** [comment]
@FuzzyGophers see PR

**Comment by manuel-sommer** [comment]
Take also a look at this if you use this fix. It might help if you run into inconsitencies https://defectdojo.github.io/django-DefectDojo/usage/features/#hashcode-generation--regeneration

**Comment by FuzzyGophers** [comment]
> @FuzzyGophers see PR

Thank you, @manuel-sommer!

I have tested your fix here locally and it works as expected :)

**Comment by manuel-sommer** [comment]
This can be closed @mtesauro

**Comment by danilolicitra** [comment]
Thank you @manuel-sommer & @mtesauro ! It is finally working!

Maybe the following examples can help a few people not wasting all to much time like me with not working implementation-approaches:
How i've setup my workflow:
1. scan your entity (git repo inside git project)
2. create DD Project (named like the git project)
3. create DD Engagement (name like the git repo)
4. import the scanresults via the reimport api 
5. (The curl command handles Step 2-4)
`curl -X POST https://<DD-Instance>/api/v2/reimport-scan/ -H 'accept: application/json' -H 'Content-Type: multipart/form-data' -H 'Authorization: Token <api-token>' -F 'minimum_severity=Low' -F 'scan_date=2024-02-06' -F 'scan_type=Trivy Scan' -F 'product_type_name=application' -F 'engagement_name=<git-repo-name>' -F 'product_name=<git-project-name>' -F 'auto_create_context=true' -F 'deduplication_on_engagement=true' -F 'close_old_findings=true' -F 'close_old_findings_product_scope=false' -F 'tags=["<tags-you-like>"]' -F 'push_to_jira=false' -F 'version=2024-02-02-17-16' -F 'service=<git-project-name>' -F 'group_by=component_name' -F 'file=@<your-scan-resultfile.json>;type=application/json'`

Have a great day
