### ISSUE TITLE
Celery stops with "AttributeError: async" error

### ISSUE THREAD

**Issue by no-sec-marko** [DefectDojo/django-DefectDojo#930]
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description
After updating the latest master brunch 7eacd53, the celery task `celery -A dojo worker -l info --concurrency 3 --loglevel=INFO -n worker.%%h` stops with following error:
>   File "/usr/lib/python2.7/site-packages/celery/worker/worker.py", line 241, in should_use_eventloop
>     self._conninfo.transport.implements.async and
>   File "/usr/lib/python2.7/site-packages/kombu/transport/base.py", line 127, in __getattr__
>     raise AttributeError(key)
> AttributeError: async

A short research shows, that celery has some trouble with kombu:
https://github.com/celery/celery/issues/4753
https://github.com/celery/kombu/issues/870

After a celery upgrade to 4.1.1, the celery worker runs without any errors.
`pip install celery==4.1.1`

The pip requirements should be updated.

### Operating System 
CentOS 7

### Install
- [x] setup.bash
- [ ] docker

### DefectDojo Version
1.5.1
Commit: 7eacd53
### Steps to Reproduce
- Install on CentOS
- Update to the latest DD 1.5.1, commit 7eacd53
- Try to run celery using following command: `celery -A dojo worker -l info --concurrency 3 `

**Comment by aaronweaver** [comment]
Thanks, done!
