### ISSUE TITLE
Kiuwan CSV Import silently drops some findings

### ISSUE THREAD

**Issue by flmarkus** [DefectDojo/django-DefectDojo#9308]
**Bug description**
When importing a kiuwan CSV report file. Some findings are dropped silently.

The parser in https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/kiuwan/parser.py does not contain the file column in the description. Therefore findings that have the same description and line content have the same hash even if they are found in different files. This will skip the last found file.

**Steps to reproduce**
1. Create a new project
2. Create a new engagement
3. Import the testfile `kiuwan-testscenario-missing-imports.csv` which containes two findings
4. Only the first finding is imported. The second one is dropped silently

**Expected behavior**
Both findings from the test file are imported and displayed.

**Deployment method**
- [ ] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo
- [X] DefectDojo Saas (Pro Account)

**Environment information**
 - DefectDojo Version 2.30.1 - Pro

**Sample scan files**
[kiuwan-testscenario-missing-imports.csv](https://github.com/DefectDojo/django-DefectDojo/files/13886789/kiuwan-testscenario-missing-imports.csv)
[kiuwan-testscenario-missing-imports-working.csv](https://github.com/DefectDojo/django-DefectDojo/files/13886791/kiuwan-testscenario-missing-imports-working.csv)

The second file contains the same import line from the first file to proof that the line itself does not contain any issues. It can imported successfully if the first line does not exist.

**Comment by manuel-sommer** [comment]
This can be closed @mtesauro

**Comment by flmarkus** [comment]
Thanks for the fast response @manuel-sommer.

Unfortunately this does not solve our issue.
I tested you changes from the lasted dev branch.

In the attached test file I manually edited the CVE number to be able to better distinguish the results in the UI.
In the real export from kiuwan the CVE is the same in both lines.

This file better refelcts this:
[kiuwan-testscenario-missing-imports.csv](https://github.com/DefectDojo/django-DefectDojo/files/13903019/kiuwan-testscenario-missing-imports.csv)

The only difference is the file name. I created a pull request highlighting this change.

**Comment by flmarkus** [comment]
@mtesauro Is it possible to open this issue again? Or should I file a new one?

**Comment by mtesauro** [comment]
@flmarkus Yes. Re-opened

**Comment by manuel-sommer** [comment]
This can be closed again @mtesauro 
https://github.com/DefectDojo/django-DefectDojo/pull/9316

**Comment by flmarkus** [comment]
Thanks for accepting and merging my PR!
