### ISSUE TITLE
JFrog Xray API Summary Artifact Scan

### ISSUE THREAD

**Issue by ricktep** [DefectDojo/django-DefectDojo#9315]
This link on this page is outdated. Please update to the following:
 https://jfrog.com/help/r/jfrog-rest-apis/artifact-summary

**Comment by manuel-sommer** [comment]
Where is the link outdated? Here https://defectdojo.github.io/django-DefectDojo/integrations/parsers/file/jfrog_xray_api_summary_artifact/?

**Comment by manuel-sommer** [comment]
This can be closed @mtesauro
