### ISSUE TITLE
DEDUPLICATION_ALGORITHM_PER_PARSER with Burp 

### ISSUE THREAD

**Issue by slimism** [DefectDojo/django-DefectDojo#9321]
Scenario: 
Currently I'm using Burp Scanner and importing finding to DD via API. However, I noticed that duplication is occurring possibly altho findings are having the Same Title, Same CVE, Same Endpoint but slightly different in description. They are having the same Vuln ID from tool. I would like the deduplication algorithm to be used based on this ID. 

I read in the documentation that the default is the legacy that depends on the title, CVE, Line and description. However, I would like to change that deduplication algorithm to depend on this ID assigned by Burp. 

Deployment method:
[X] Docker

Release:
[X] v. 2.29.4

Operating System:
[X] Ubuntu Jammy 22.04

![Screenshot 2024-01-11 at 15 56 26](https://github.com/DefectDojo/django-DefectDojo/assets/16501217/f9a948a2-347e-41f7-81c7-6232df24a09c)

![Screenshot 2024-01-11 at 15 56 33](https://github.com/DefectDojo/django-DefectDojo/assets/16501217/7dd7486e-2f0b-4fe6-91e1-4a476e80c842)

How can I choose DEDUPLICATION_ALGORITHM_PER_PARSER  to be the deduplication algorithm instead of the legacy one?

**Comment by mtesauro** [comment]
You can make a change to settings.py - see https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/settings/settings.dist.py#L1339 for the deduplication settings.

Using local_settings.py is the way to customize for your install of DefectDojo. You can see an example template to create a local settings.py file at https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/settings/template-local_settings

The settings in local_settings.py override what's in settings.dist.py as shown in https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/settings/settings.py#L8

HTH

**Comment by slimism** [comment]
Correct me if Im mistaken, initially DD will recognize what Test Type Im using and adjust the Deduplication algorithm accordingly. 
For instance, I'm uploading my findings via Burp Rest API, the deduplication method will automatically be assigned to "DEDUPE_ALGO_UNIQUE_ID_FROM_TOOL" as per the DEDUPLICATION_ALGORITHM_PER_PARSER? 

Or I should Specify in the Local_settings that I want to use this Deduplication Algorithm because initially its set to legacy?

**Comment by mtesauro** [comment]
You should use local_settings to replace or modify the default algorithm used for a specific tool.  The idea is if your use case requires modifying how a dedup algorithm works - either by adding/removing fields used or changing from legacy to something else.

HTH
