### ISSUE TITLE
TypeError during Trivy report upload from Node.js Image

### ISSUE THREAD

**Issue by Noppakn** [DefectDojo/django-DefectDojo#9333]
I am experiencing an issue when uploading Trivy reports to DefectDojo. The issue is related to the way I am building the image.

If I build the image like this:
```
FROM node:20.11.0

WORKDIR /usr/src/app/

COPY src/ /usr/src/app/

RUN npm install

EXPOSE 3000

CMD ["node", "index.js"]
```
and then scan the image with Trivy and upload the report to DefectDojo, with the Scan Type set to Trivy Scan, the upload will fail with the following error:

TypeError: float() argument must be a string or a real number, not 'NoneType'
However, if I build the image like this:
```
FROM node:20.11.0-alpine

WORKDIR /usr/src/app/

COPY src/ /usr/src/app/

RUN npm install

EXPOSE 3000

CMD ["node", "index.js"]
```
the upload will succeed.

I have tried different versions of Trivy and I have tried different versions of DefectDojo, none of these have resolved the issue.

**Steps to reproduce**
1. Build image
2. Scan image
```
./trivy image --exit-code 0 --cache-dir .trivycache/ --no-progress --format json -o reports/trivy/trivy-report.json $IMAGE_NAME:$IMAGE_TAG
```
3. Create DefectDojo engagement

```
curl -k -X 'POST' "${DEFECTDOJO_URL}/api/v2/engagements/" \
              --header "Authorization: Token ${DEFECTDOJO_API_KEY}" \
              --header 'Content-Type: application/json' \
                --data-raw "{
                  \"tags\": [\"GITLAB-CI\"],
                  \"name\": \"${CI_COMMIT_BRANCH}-${CI_PIPELINE_ID}\",
                  \"first_contacted\": \"${TODAY}\",
                  \"target_start\": \"${TODAY}\",
                  \"target_end\": \"${ENDDAY}\",
                  \"version\": \"${CI_COMMIT_REF_NAME}\",
                  \"engagement_type\": \"CI/CD\",
                  \"build_id\": \"${CI_PIPELINE_ID}\",
                  \"commit_hash\": \"${CI_COMMIT_SHORT_SHA}\",
                  \"branch_tag\": \"${CI_COMMIT_REF_NAME}\",
                  \"product\": \"${DEFECTDOJO_PRODUCTID}\" }"
```
4. Upload report
```
        curl -k -X 'POST' "${DEFECTDOJO_URL}/api/v2/import-scan/" \
            --header "Authorization: Token ${DEFECTDOJO_API_KEY}" \
            --header "accept: application/json" \
            --header "Content-Type: multipart/form-data" \
            --form "scan_date=\"${TODAY}\"" \
            --form "minimum_severity=\"${DEFECTDOJO_SCAN_MINIMUM_SEVERITY}\"" \
            --form "active=\"${DEFECTDOJO_SCAN_ACTIVE}\"" \
            --form "verified=\"${DEFECTDOJO_SCAN_VERIFIED}\"" \
            --form "scan_type=Trivy Scan" \
            --form "engagement=\"${DEFECTDOJO_ENGAGEMENTID}\"" \
            --form "file=@${DEFECTDOJO_SCAN_FILE}" \
            --form "close_old_findings=true" \
            --form "test_type=API Test" 
```
5. See error
```
Internal Server Error: /api/v2/import-scan/
```
**Expected behavior**
The Trivy report should be uploaded to DefectDojo successfully without any errors.

**Deployment method** *(select with an `X`)*
- [x] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
- Trivy version: 0.48.2
- DefectDojo version: 2.30.1

**Logs** 
```
ERROR [dojo.api_v2.exception_handler:36] float() argument must be a string or a real number, not 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/app/dojo/api_v2/views.py", line 3047, in perform_create
    serializer.save(push_to_jira=push_to_jira)
  File "/app/dojo/api_v2/serializers.py", line 2219, in save
    ) = importer.import_scan(
        ^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/importers/importer/importer.py", line 315, in import_scan
    parsed_findings = parser.get_findings(scan, test)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/tools/trivy/parser.py", line 90, in get_findings
    return self.get_result_items(test, results, artifact_name=artifact_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/tools/trivy/parser.py", line 176, in get_result_items
    severity = self.convert_cvss_score(cvssclass.get("V3Score", None))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/tools/trivy/parser.py", line 58, in convert_cvss_score
    val = float(raw_value)
          ^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'

```

**Sample scan files**
Report that can upload:
```

{
  "SchemaVersion": 2,
  "CreatedAt": "2024-01-10T12:25:24.145071401Z",
  "ArtifactName": "noppaknopsta/example-app:main-114",
  "ArtifactType": "container_image",
  "Metadata": {
    "OS": {
      "Family": "alpine",
      "Name": "3.12.3",
      "EOSL": true
    },
    "ImageID": "sha256:5bf34d95bce8de6a4db53139e7b7551bc92fc68bb06bdb12a41de2972bc1406c",
    "DiffIDs": [
      "sha256:777b2c648970480f50f5b4d0af8f9a8ea798eea43dbcf40ce4a8c7118736bdcf",
      "sha256:264dfe42a385c7bd749fd8208bfd617c2cecea6df60636174cf1c32f5fd19152",
      "sha256:7c7455e7f503120c3d097896e622968849b1260cdfd9f31a1a5dbc026f15fd3f",
      "sha256:69fbee19464e6eedfe3f58f82048dc720bae8ebe257bee3e4e6297e9fcf217cb",
      "sha256:7eb2d4f8f15517cfa05e2976a7dcb15899654e66137740c0957771aa490c1d35",
      "sha256:3eae1af7177c982ea46b3eef575b232530b60bbe575d17534524ffed690be02c",
      "sha256:5beb2afcd044fccb03422db5201f00638b728d89eea2f4c4b2e22730d42f9016"
    ], ...
}
```
Report that can't upload:
```
{
    "SchemaVersion": 2,
    "CreatedAt": "2024-01-15T08:58:29.82753744Z",
    "ArtifactName": "noppaknopsta/example-app:main-159",
    "ArtifactType": "container_image",
    "Metadata": {
        "OS": {
            "Family": "debian",
            "Name": "10.13"
        },
        "ImageID": "sha256:22ae3921bdaac434bb4cb92dbbc209e46b1f3f70e9fa0b5fbbb43ce7d452c72d",
        "DiffIDs": [
            "sha256:b2dba74777543b60e1a5be6da44e67659f51b8df1e96922205a5dde6b92dda3c",
            "sha256:f1186e5061f20658954f6bfdfaead0abc5ed2371d70f707da05206e868a226ab",
            "sha256:fe0fb3ab4a0f7be72784fcab5ef9c8fda65ea9b1067e8f7cdf293c12bcd25c13",
            "sha256:c45660adde371317a1eafb102ee1d33b059328ec73a01b5c2461c4d04a40ecec",
            "sha256:e01a454893a9a11115c598e5dec158ded8bd41326046c993c81b76b6a963590b",
            "sha256:cb81227abde588a006a8b7ceac6034a303813efadc2c711fabf7b224649d183f",
            "sha256:f8a91dd5fc84e4e5a1f261cf306ba1de28894524326d86eec0d74e9c0d22baec",
            "sha256:3c777d951de2c488f73618f92b2adee8bd5de6f77e36bab51d57583bc487b99b",
            "sha256:0d5f5a015e5d65973cce1dbab5aa60ce0836dbf2b3c9eabcb6efc89db1db3221",
            "sha256:baa0956fea600c916f370870566aca1edf9a5ffc7facf51cfb1286e774f6e0e2",
            "sha256:2f08eba9a3eddbb1e9dc2b70a25a1a3860807dac0d42c1e40fd890bbafbfba29",
            "sha256:bf7d7d997f27e713b44ac0e763a38c46f9698e71e2243b0ffa80405d62d8c5e0"
        ], ...
}
```

**Comment by manuel-sommer** [comment]
Hi @Noppakn, could you please upload a complete and anonymized file to reproduce the error? Then, I can help you to fix this issue.

**Comment by manuel-sommer** [comment]
I tried to reproduce it, but was not successful. Also, it seems like the only difference between your above examples is the "EOSL" field in Metadata. Please produce a complete file.

**Comment by Noppakn** [comment]
Sorry for replying late Yes, the difference between the two files is "EOSL". This is the complete report file

[Unable-to-upload-report.json](https://github.com/DefectDojo/django-DefectDojo/files/13945055/Unable-to-upload-report.json)
[Uploadable-report.json](https://github.com/DefectDojo/django-DefectDojo/files/13945057/Uploadable-report.json)

**Comment by manuel-sommer** [comment]
I guess you reported the wrong reportfile to reproduce this. "EOSL" has nothing to do with "convert_cvss_score". I made a PR with your sample file which proofs this. 

Could you please provide the right scan report to reproduce the issue or close this issue?

**Comment by Noppakn** [comment]
[Unable-to-upload-report.json](https://github.com/DefectDojo/django-DefectDojo/files/13946180/Unable-to-upload-report.json)
[Uploadable-report.json](https://github.com/DefectDojo/django-DefectDojo/files/13946181/Uploadable-report.json)

**Comment by manuel-sommer** [comment]
The unable to upload-report works fine out of the box:
![grafik](https://github.com/DefectDojo/django-DefectDojo/assets/47991713/21c96ceb-c1c5-4f11-b57f-0b4493daee12)

**Comment by Noppakn** [comment]
I try manual import scan results with unable-to-upload-report.json but it still get error.

![Screenshot 2024-01-16 000647](https://github.com/DefectDojo/django-DefectDojo/assets/94559598/642ff3cb-f502-4dd9-ab43-1a0a152b13bc)

logs : 
[16/Jan/2024 08:06:37] ERROR [dojo.engagement.views:751] float() argument must be a string or a real number, not 'NoneType'
Traceback (most recent call last):
  File "/app/dojo/engagement/views.py", line 735, in post
    test, finding_count, closed_finding_count, _ = importer.import_scan(scan, scan_type, engagement, user, environment, active=active, verified=verified, tags=tags,
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/importers/importer/importer.py", line 315, in import_scan
    parsed_findings = parser.get_findings(scan, test)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/tools/trivy/parser.py", line 90, in get_findings
    return self.get_result_items(test, results, artifact_name=artifact_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/tools/trivy/parser.py", line 176, in get_result_items
    severity = self.convert_cvss_score(cvssclass.get("V3Score", None))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/tools/trivy/parser.py", line 58, in convert_cvss_score
    val = float(raw_value)
          ^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
[16/Jan/2024 08:06:37] INFO [django.request:241] OK: /engagement/37/import_scan_results
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/engagement/views.py", line 772, in post
    return HttpResponseRedirect(reverse('view_test', args=(test.id, )))
                                                           ^^^^
UnboundLocalError: cannot access local variable 'test' where it is not associated with a value

**Comment by deigott** [comment]
I had the same issue while trying to upload an Aqua Trivy scan report:

<img width="1490" alt="Screenshot 2024-01-16 at 10 11 50 AM" src="https://github.com/DefectDojo/django-DefectDojo/assets/143202415/ab594de7-a1bf-4bcf-ad75-7b23c39d446f">

After checking the logs here's the error, it got something `float() argument must be a string or a real number, not 'NoneType'`

```bash
[pid: 27|app: -|req: -/-] 192.168.65.1 (admin) {50 vars in 1016 bytes} [Tue Jan 16 09:51:43 2024] GET /alerts/count => generated 13 bytes in 959 msecs (HTTP/1.1 200) 7 headers in 212 bytes (1 switches on core 0)
[16/Jan/2024 09:51:51] ERROR [dojo.api_v2.exception_handler:36] float() argument must be a string or a real number, not 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/app/dojo/api_v2/views.py", line 3047, in perform_create
    serializer.save(push_to_jira=push_to_jira)
  File "/app/dojo/api_v2/serializers.py", line 2219, in save
    ) = importer.import_scan(
        ^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/importers/importer/importer.py", line 315, in import_scan
    parsed_findings = parser.get_findings(scan, test)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/tools/trivy/parser.py", line 90, in get_findings
    return self.get_result_items(test, results, artifact_name=artifact_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/tools/trivy/parser.py", line 176, in get_result_items
    severity = self.convert_cvss_score(cvssclass.get("V3Score", None))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/tools/trivy/parser.py", line 58, in convert_cvss_score
    val = float(raw_value)
          ^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
```

**Comment by manuel-sommer** [comment]
Processing container-image-scan-results.json with v. 2.31.0-dev:

![grafik](https://github.com/DefectDojo/django-DefectDojo/assets/47991713/f66d866b-6f23-42da-a7df-8327fe64c0b5)

**Comment by manuel-sommer** [comment]
Lol, I guess this is the problem: https://github.com/DefectDojo/django-DefectDojo/pull/9268

**Comment by manuel-sommer** [comment]
See issue https://github.com/DefectDojo/django-DefectDojo/issues/9263 

Please retest with current dev build.
