### ISSUE TITLE
Not able to create products with the same name but different product types

### ISSUE THREAD

**Issue by st1ckyf1ng4z** [DefectDojo/django-DefectDojo#9362]
**Problem description**
I have an error when i try to create product with the same name as other product in another product type
Why is it designed this way?

**Steps to reproduce**
1. Create product type "Processing"
2. Create product "auth_service" for product type "Processing"
3. Create product type "Acquiring"
4. Create product "auth_service" for product type "Acquiring"
5. Got an error: `{"name":["product with this name already exists."],"message":"{'name': [ErrorDetail(string='product with this name already exists.', code='unique')]}"}`

**Expected behavior**
Ability to create products with the same names for different product types. It maybe usefull for many teams, especially for common names like "auth", "backend", "frontend" etc.

**Deployment method**
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - DefectDojo version 2.30.2

**Comment by mtesauro** [comment]
@st1ckyf1ng4z 
The unique constraint on product names allows you to move a product from one product-type to another.

Most users prefix or append a string on the conflicting product name to allow two 'same' names while being unique.

**For example**
Product Type Processing
* Auth: Processing
* Backend: Processing
* Frontend: Processing

Product Type Acquiring
* Acquiring - Auth
* Acquiring - Backend
* Acquiring - Frontend

Obviously, it's better to have a consistent scheme for prefix/appending the product type to the product name - the example shows both. I've also seen many abbreviate the product-type as well.

It also makes things like alerts (to Slack for example) better so things like "New scan of Acquiring - Auth" mean more then "New Scan of Auth" which could be Processing or Acquiring.

HTH
