### ISSUE TITLE
Add kubeadit importer

### ISSUE THREAD

**Issue by veneber** [DefectDojo/django-DefectDojo#9384]
**kubeaudit** is a command line tool and a Go package to audit Kubernetes clusters for various different security concerns, such as:
    run as non-root
    use a read-only root filesystem
    drop scary capabilities, don't add new ones
    don't run privileged
    and more!

[Link](https://github.com/Shopify/kubeaudit) to the tool repo. 

Example report:
[kubeaudit_report.json](https://github.com/DefectDojo/django-DefectDojo/files/14010849/kubeaudit_report.json)

**Comment by manuel-sommer** [comment]
Can you close this @mtesauro ?
