### ISSUE TITLE
Missing docker-compose yaml

### ISSUE THREAD

**Issue by hujarl** [DefectDojo/django-DefectDojo#940]
Unable to "docker-compose up" as there is no associated docker-compose yaml file available from the git clone.

Instructions:

Clone the `DefectDojo Repo`_
git clone https://github.com/DefectDojo/django-DefectDojo.git

Change directories into the newly created folder.
cd django-DefectDojo

.......

To run docker-DefectDojo and see the Dojo logs in the terminal, use: docker-compose up

To run docker-DefectDojo and get your terminal prompt back, use: docker-compose up -d

**Comment by aaronweaver** [comment]
Try the dev branch, we are also currently working on upgrading that in the k8 branch.

**Comment by hujarl** [comment]
Has been moved to master, closing.

Cheers!
