### ISSUE TITLE
Product List shows wrong number of Vulnerable Hosts / Endpoints

### ISSUE THREAD

**Issue by manuel-sommer** [DefectDojo/django-DefectDojo#9413]
v. 2.31.0-dev ( release mode )

1. Upload a report with endpoints and make sure they are not vulnerable.
2. Take a look at "Product List"
![grafik](https://github.com/DefectDojo/django-DefectDojo/assets/47991713/f7132d2e-e0a1-497b-945e-801504ba9c7c)

3.  Click on the Vulnerable Hosts / Endpoints
4.  No vulnerable Host or Endpoint is listed
![grafik](https://github.com/DefectDojo/django-DefectDojo/assets/47991713/3f9accdb-31e6-407b-9038-4b76b0ec1e3f)
![grafik](https://github.com/DefectDojo/django-DefectDojo/assets/47991713/b7121e5d-0c8c-4599-b1b1-5021d71870b5)

Solution:
Either correct the wording "Vulnerable Hosts / Endpoints" to "Hosts / Endpoints" and forward to the other pages (Hosts / Endpoints) or correct the summary of "Vulnerable Hosts / Endpoints" which would be 0/0 in this case.

**Comment by manuel-sommer** [comment]
@mtesauro which of the two solutions should be prefered here?

**Comment by manuel-sommer** [comment]
Similar: https://github.com/DefectDojo/django-DefectDojo/issues/8450

**Comment by mtesauro** [comment]
@manuel-sommer Thanks for discovering this and asking :smiley: 

We should go with 'option 2'

> correct the summary of "Vulnerable Hosts / Endpoints" which would be 0/0 in this case.

Since I think most uses will want to know what's vulnerable over just a count of hosts or endpoints.

**Comment by manuel-sommer** [comment]
@FelixHernandez may I ask you to help to close this? I thought it might be easy for you because of this PR https://github.com/DefectDojo/django-DefectDojo/pull/9419

**Comment by FelixHernandez** [comment]
@manuel-sommer Let me take a look to fix it in a new PR
