### ISSUE TITLE
Duplicate "Risk Accepted" field to filter. 

### ISSUE THREAD

**Issue by manuel-sommer** [DefectDojo/django-DefectDojo#9414]
v. 2.31.0-dev ( release mode )

1.  Go to http://defectdojo/test/$any
2. Click on button to open menu for sorting options
3. There are two "Risk Accepted" fields to be selected.

--> Please specify which in a better way, which "Risk Accepted" does what

![grafik](https://github.com/DefectDojo/django-DefectDojo/assets/47991713/98d23413-6544-40e4-a9ec-74065ed39065)

**Comment by mtesauro** [comment]
Addressing this in #9419

**Comment by mtesauro** [comment]
Closing since approvals are coming in on that PR

**Comment by mtesauro** [comment]
Addressing this in #9419
