### ISSUE TITLE
Cannot authenticate by using LDAP on version 2.30.x

### ISSUE THREAD

**Issue by wonhee0410** [DefectDojo/django-DefectDojo#9416]
**Bug description**
On the version 2.29.x, I still can login using LDAP. 
But after upgrading to version 2.30.x, I cannot login anymore.
I've tried uninstall the current system and reinstall with the latest 2.30.3, the issue is the same.

**Steps to reproduce**
![image](https://github.com/DefectDojo/django-DefectDojo/assets/60768442/329cf7ce-54b1-4928-b592-4f7e200138f8)

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Redhat
 - DefectDojo version (see footer) or commit message: 2.30.3

**Logs** 
The log is just 1 line for this behaviour:
django-defectdojo-uwsgi-1         | [26/Jan/2024 07:38:30] WARNING [dojo.utils:2345] login failed for: testldap via ip: x.x.x.x

**Comment by manuel-sommer** [comment]
Hi @wonhee0410 ,
I don't know if you will get an answer here. Ask rather in the owasp slack channel.

**Comment by manuel-sommer** [comment]
I guess this can be closed @mtesauro

**Comment by R00G3R** [comment]
@mtcolman you found a solutions for this issue?
I just upgrade my instance and have the same problem.
