### ISSUE TITLE
openscap support

### ISSUE THREAD

**Issue by barbich** [DefectDojo/django-DefectDojo#942]
Please use the following template when submitting issues: (If this is a security issue, then review the [disclosure policy](https://github.com/DefectDojo/django-DefectDojo/blob/master/SECURITY.md) and submit via our security reporting program.

### Issue Type 
- [ ] Bug
- [X] Enhancement

### Description
Hi
support for openscap xccdf results file would be interresting.
Reference: https://www.open-scap.org/
Oscap results can be of 2 forms, either vulnerability scan or baseline assessment.
Attached are 2 sample xml output files:

[sample-rhsa.xml.zip](https://github.com/DefectDojo/django-DefectDojo/files/2980844/sample-rhsa.xml.zip)
[sample-stig.xml.zip](https://github.com/DefectDojo/django-DefectDojo/files/2980845/sample-stig.xml.zip)

**Comment by dr3dd589** [comment]
hello, @aaronweaver Can you put this in GSoC project and assign it to me?

**Comment by aaronweaver** [comment]
@dr3dd589 sure

**Comment by dr3dd589** [comment]
@Maffooch working on it now.
