### ISSUE TITLE
Find Kubernetes hosting provider to replace heroku

### ISSUE THREAD

**Issue by aaronweaver** [DefectDojo/django-DefectDojo#947]
Please use the following template when submitting issues: (If this is a security issue, then review the [disclosure policy](https://github.com/DefectDojo/django-DefectDojo/blob/master/SECURITY.md) and submit via our security reporting program.

### Issue Type 
- [ ] Bug
- [ ] Enhancement

### Operating System 
Please include the version number (ex: Ubuntu 16.04)

### Install

- [ ] setup.bash
- [ ] docker

**Comment by hendrikhalkow** [comment]
The most known are:

http://openshift.com/
https://cloud.google.com/kubernetes-engine/
https://azure.microsoft.com/services/kubernetes-service/
https://aws.amazon.com/eks/
https://www.ibm.com/cloud/container-service/
https://www.rackspace.com/managed-kubernetes/

Even more here:
https://kubernetes.io/docs/setup/pick-right-solution/#hosted-solutions
