### ISSUE TITLE
Inititing for GS0C 2019

### ISSUE THREAD

**Issue by HSR-4** [DefectDojo/django-DefectDojo#948]
Hi, I would Like to contribute this project under **GSoC 2019**
Can You please direct some Instructions for commencing contributions to this project?

**Comment by aaronweaver** [comment]
@HSR-4 Take a look at the [suggestions](https://www.owasp.org/index.php/GSoC2019_Ideas#OWASP_DefectDojo) and then follow through the GSOC process of submission. Thx for you interest!!
