### ISSUE TITLE
Kiuwan Importer For DefectDojo

### ISSUE THREAD

**Issue by aaronweaver** [DefectDojo/django-DefectDojo#952]
Please use the following template when submitting issues: (If this is a security issue, then review the [disclosure policy](https://github.com/DefectDojo/django-DefectDojo/blob/master/SECURITY.md) and submit via our security reporting program.

### Issue Type 
- [ ] Bug
- [X] Enhancement

### Description
Work with Kiuwan to create an importer.

**Comment by jsalado** [comment]
Hello there,

find attached a CSV file example with some vulnerabilities found by Kiuwan in the WebGoat application. Let me know if you need any clarification or more examples.

Open to explore more possibilities of integration.

[Kiuwan_VulnerabilitiesTable_rfc_4180.zip](https://github.com/DefectDojo/django-DefectDojo/files/2993221/Kiuwan_VulnerabilitiesTable_rfc_4180.zip)

**Comment by aaronweaver** [comment]
Thanks @jsalado. I'll start with this one and then can explore API options.

**Comment by dr3dd589** [comment]
hello, @jsalado here is steps for the testing. 
 - Clone the repo checkout to the dev branch.
 - Install via docker describe here [doc](https://github.com/DefectDojo/django-DefectDojo/blob/dev/DOCKER.md)
 - Create a Product.
 - Go to findings and click import scan option.
 - choose kiuwan scan.
 - import your kiuwan sample.

**Comment by jsalado** [comment]
Hello @dr3dd589, @aaronweaver 

I successfully installed and run DefectDojo via docker. However, the Kiuwan Scan option does not appear in the Scan type combo when importing findings.

My guess is that the version supporting has not been committed to DockerHub. Do you know when this will be available?

In the meantime I'll build the containers locally from the latest varsion in the repo and try again. 

Highly appreciate the effort. Best,
J.

**Comment by jsalado** [comment]
I've built the images locally after cloning the repo following the instruction [here](https://github.com/DefectDojo/django-DefectDojo/blob/dev/DOCKER.md) and then run `docker-compose up` again but stil I don't see the Kiuwan scan option in the Scan type combo.

Is there anything that I'm missing?

Thanks

**Comment by jsalado** [comment]
Sorry, I just noticed the 'checkout to the dev branch' bit.

I did and now it is there ;-) I tried it and found a couple of issues. I'll open a new issue for them
