### ISSUE TITLE
Report Generation Error

### ISSUE THREAD

**Issue by LeonardoNve** [DefectDojo/django-DefectDojo#955]
### Issue Type 
- [ X] Bug

### Description

After some work with the config of DD, now the report tool create an error each time I try to create a PDF report

### Operating System 
Centos 7

### Install

- [X ] setup.bash

### DefectDojo Version
Defect Dojo v. 1.5.2
wkhtmltopdf 0.12.5

### Console Logs (optional)
manage.py runserver logs:

> [20/Mar/2019 12:01:42] "GET /product/1/endpoint/report?include_finding_notes=0&include_finding_images=0&include_executive_summary=0&include> _table_of_contents=0&report_type=PDF&_generate= HTTP/1.0" 302 0
> [20/Mar/2019 12:01:43] "GET /alerts/count HTTP/1.0" 200 13
> [20/Mar/2019 12:01:44] "GET /reports HTTP/1.0" 200 32759

Celery logs:

> [2019-03-20 12:00:42,213: INFO/MainProcess] Received task: dojo.tasks.async_pdf_report[77e6fb42-d0a2-4dc4-bdb5-4b4cfc8ade1a]  
> [2019-03-20 12:00:43,024: INFO/ForkPoolWorker-3] Task dojo.tasks.async_pdf_report[77e6fb42-d0a2-4dc4-bdb5-4b4cfc8ade1a] succeeded in 0.789048105013s: True
> [2019-03-20 12:01:43,108: INFO/MainProcess] Received task: dojo.tasks.async_pdf_report[54d25e06-f58a-4f82-9e25-f266dd156463]  
> [2019-03-20 12:01:46,304: INFO/ForkPoolWorker-2] Task dojo.tasks.async_pdf_report[54d25e06-f58a-4f82-9e25-f266dd156463] succeeded in 3.17504298803s: True

Web Request:

> GET /reports/11/status

Web Response: 
> {"status": "error", "id": 11}

**Comment by aaronweaver** [comment]
@LeonardoNve We have dropped support for PDF reports as the generator was problematic. We now suggest using the html report and printing to PDF.
