### ISSUE TITLE
The Uwsgi pod is restarted occasionally, with exit code 30 or exit code 137

### ISSUE THREAD

**Issue by comicrr** [DefectDojo/django-DefectDojo#9579]
**Overview**
Hello,
For the last few days, I have been experiencing frequent restarts of the Django pod. After checking the pod's status description, it appears that the issue stems from Uwsgi. The exit code indicates a memory problem. However, upon checking the usage trends, they were not even close to the request limit.
<img width="725" alt="usage_trend" src="https://github.com/DefectDojo/django-DefectDojo/assets/33969768/92fd6b10-7835-498f-b1f2-586802291e6c">

Also, I have tried checking the pod's logs and found only "connection refused" errors at Nginx, while Uwsgi doesn't show any errors.
**Nginx Log**
<img width="958" alt="nginx_log" src="https://github.com/DefectDojo/django-DefectDojo/assets/33969768/53ebf624-0da0-4968-98b0-c6f8552ba3ed">
**Uwsgi Log**
<img width="958" alt="uwsgi_log" src="https://github.com/DefectDojo/django-DefectDojo/assets/33969768/37c5c4ad-aaf3-47d8-ad33-f8d3125679f6">

**Expected behavior**
- The pod is restarted only when it is utilizing memory equal to the memory request limit or when an error is displayed in the pod log prior to the restart.

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - Deployed on AWS EKS
 - Django Version 2.27.0
 - CPU: No Limit
 - Memory: 4GB Limit

**Comment by vivekkontham** [comment]
@comicrr, Have you resolved the error? I'm encountering the same issue. If you've fixed it, could you please share the solution?

**Comment by comicrr** [comment]
@vivekkontham , unfortunately, it is still happening and there is still no solution for this problem.

**Comment by sebglon** [comment]
We have the same when we try to show reports and metrics dashboard

**Comment by comicrr** [comment]
Hi, 
After upgrade our Memory limit, seems no problem shows anymore. it was seems to be a monitoring problem that can't caught the metric right before pod was error OOMKilled

**Comment by stchstepan** [comment]
Hello!
Can you tell me what limit you set? We're having the same issue

**Comment by stchstepan** [comment]
Hello!

@comicrr 
Can you tell me what limit you set? We're having the same issue

**Comment by comicrr** [comment]
Hi @stchstepan , I had increase the limit from 4GB into 16GB.
Thanks
