### ISSUE TITLE
Github Advanced Security Code Scanning Alerts/Secret Scanning Alerts

### ISSUE THREAD

**Issue by CarpFlop** [DefectDojo/django-DefectDojo#9582]
**Scanner**
Name: GitHub Advanced Security
Description:A GitHub Advanced Security license provides the following additional features:

Code scanning - Search for potential security vulnerabilities and coding errors in your code.

Secret scanning - Detect secrets, for example keys and tokens, that have been checked into private repositories. Secret scanning alerts for users and secret scanning alerts for partners are available and free of charge for public repositories on GitHub.com. If push protection is enabled, also detects secrets when they are pushed to your repository.

Dependency review - Show the full impact of changes to dependencies and see details of any vulnerable versions before you merge a pull request.

Link:(https://docs.github.com/en/get-started/learning-about-github/about-github-advanced-security)

**Sample File**
Attached is an example file when querying code-scanning alerts. To my knowledge each scan type must be queried by itself using GitHub REST API, you cannot unify all three
[example.json](https://github.com/DefectDojo/django-DefectDojo/files/14336063/example.json)

**Comment by CarpFlop** [comment]
The provided parser by DefectDojo for GitHub Vulnerability Alerts only pulls Dependabot alert but not code and secret scanning
https://documentation.defectdojo.com/integrations/parsers/file/github_vulnerability/

**Comment by manuel-sommer** [comment]
@CarpFlop can you please take a look at the PR, test it and review?

**Comment by manuel-sommer** [comment]
Also, another unittest file would be nice. 

- What values can `security_severity_level` have?
- Multiple values are None, are they always None, or relevant? `fixed_at`, `dismissed_by` etc.

**Comment by CarpFlop** [comment]
I will look to provide more examples for varied values as well as a secret scanning example. 

I did however want to specify that the original post I made was inquiring in regards to the GraphQL parser found here: https://documentation.defectdojo.com/integrations/parsers/file/github_vulnerability/
Is that un-needed once the appropriate changes to the parser is made to directly ingest code-scanning and secret-scanning alerts?

**Comment by manuel-sommer** [comment]
I guess this can be closed, the fix was released yesterday.
