### ISSUE TITLE
Migrate DefectDojo to another host

### ISSUE THREAD

**Issue by tvnnn** [DefectDojo/django-DefectDojo#9585]
Hi everyone,
I am currently running DefectDojo (with some custom code) using docker-compose on my personal computer. How can I migrate everything to another host?

**Comment by manuel-sommer** [comment]
Can you please ask such questions on slack?

Can we close this @mtesauro ?

**Comment by mtesauro** [comment]
@tvnnn I agree with @manuel-sommer  that his is a question best asked in Slack.

There was a Github discussion on a related topic [here](https://github.com/DefectDojo/django-DefectDojo/discussions/9480) which may help. If not, please ask on Slack.
