### ISSUE TITLE
Wiz tool support (https://www.wiz.io/)

### ISSUE THREAD

**Issue by barucijah** [DefectDojo/django-DefectDojo#9602]
**Is your feature request related to a problem? Please describe**
I would like to import my report from WIZ to the DefectDojo
https://www.wiz.io/

**Describe the solution you'd like**
Create a new feature that will support the WIZ tool.
https://www.wiz.io/

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you have considered.
An alternative for the support of the new tools could be creating a feature that will enable users to define their template, something like a generic template which will match their tool report.

**Comment by barucijah** [comment]
Hi @manuel-sommer, I was waiting for the report example. I have 2 types of reports standard format and one which uses OCSF format. Please feel free to use one of those one of those 2.
[Payment_Issues__OCSF_2024_03_01T14_40_51Z.csv](https://github.com/DefectDojo/django-DefectDojo/files/14479815/Payment_Issues__OCSF_2024_03_01T14_40_51Z.csv)
[Payment_Issues_2024_03_01T14_36_46Z.csv](https://github.com/DefectDojo/django-DefectDojo/files/14479817/Payment_Issues_2024_03_01T14_36_46Z.csv)

**Comment by manuel-sommer** [comment]
@barucijah ,
you can review the PR

**Comment by barucijah** [comment]
> Hi @barucijah, just a question: Regarding the ocsf output. Does the parser save the output file format, or can you choose the file format? Then, it would be easier to distinguish between both file types.

I can choose the file format.
![image](https://github.com/DefectDojo/django-DefectDojo/assets/22957660/64dd33ed-08b2-44e8-b086-35a6862e137c)

**Comment by manuel-sommer** [comment]
If you choose OCSF, then the file type is .ocsf or .csv (how you uploaded it)?
Furthermore: It is a dynamic scanner, right?

**Comment by manuel-sommer** [comment]
Ok, so you chose "Standard"

**Comment by barucijah** [comment]
It is up to you, which one you consider easier to parse. I am fine with both file formats, as the reports are giving similar results.

**Comment by manuel-sommer** [comment]
Please close this issue as PR has been merged.

**Comment by barucijah** [comment]
Hi @manuel-sommer, thanks for implementing this feature. It's working fine, but I have one question. Does it support importing CWE, Vulnerability ID, Image ID, and other details? Currently, I don't see them in imported vulnerabilities.
if not, could this also be implemented?
