### ISSUE TITLE
SonarQube is Longer then 30 characters

### ISSUE THREAD

**Issue by g-sahil22** [DefectDojo/django-DefectDojo#9611]
When I try to import the SonarQube Scan results using the SonarQube API Import scan type then I get the below error

`postgres-1      | 2024-02-22 10:36:21.480 UTC [954] ERROR:  value too long for type character varying(30)
postgres-1      | 2024-02-22 10:36:21.480 UTC [954] STATEMENT:  INSERT INTO "dojo_sonarqube_issue" ("key", "status", "type") VALUES ('9270f3d9-891f-40f5-a5dc-2c47dafbf549', 'OPEN', 'BUG') RETURNING "dojo_sonarqube_issue"."id"
uwsgi-1         | [22/Feb/2024 10:36:21] ERROR [dojo.tools.api_sonarqube.importer:204] value too long for type character varying(30)
uwsgi-1         | Traceback (most recent call last):
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 929, in get_or_create
uwsgi-1         |     return self.get(**kwargs), False
uwsgi-1         |            ^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
uwsgi-1         |     raise self.model.DoesNotExist(
uwsgi-1         | dojo.models.Sonarqube_Issue.DoesNotExist: Sonarqube_Issue matching query does not exist.
uwsgi-1         |
uwsgi-1         | During handling of the above exception, another exception occurred:
uwsgi-1         |
uwsgi-1         | Traceback (most recent call last):
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
uwsgi-1         |     return self.cursor.execute(sql, params)
uwsgi-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         | psycopg2.errors.StringDataRightTruncation: value too long for type character varying(30)
uwsgi-1         |
uwsgi-1         |
uwsgi-1         | The above exception was the direct cause of the following exception:
uwsgi-1         |
uwsgi-1         | Traceback (most recent call last):
uwsgi-1         |   File "/app/dojo/tools/api_sonarqube/importer.py", line 166, in import_issues
uwsgi-1         |     sonarqube_issue, _ = Sonarqube_Issue.objects.update_or_create(
uwsgi-1         |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
uwsgi-1         |     return getattr(self.get_queryset(), name)(*args, **kwargs)
uwsgi-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 962, in update_or_create
uwsgi-1         |     obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
uwsgi-1         |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 936, in get_or_create
uwsgi-1         |     return self.create(**params), True
uwsgi-1         |            ^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 671, in create
uwsgi-1         |     obj.save(force_insert=True, using=self.db)
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 812, in save
uwsgi-1         |     self.save_base(
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 863, in save_base
uwsgi-1         |     updated = self._save_table(
uwsgi-1         |               ^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1006, in _save_table
uwsgi-1         |     results = self._do_insert(
uwsgi-1         |               ^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1047, in _do_insert
uwsgi-1         |     return manager._insert(
uwsgi-1         |            ^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
uwsgi-1         |     return getattr(self.get_queryset(), name)(*args, **kwargs)
uwsgi-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1791, in _insert
uwsgi-1         |     return query.get_compiler(using=using).execute_sql(returning_fields)
uwsgi-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql
uwsgi-1         |     cursor.execute(sql, params)
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
uwsgi-1         |     return self._execute_with_wrappers(
uwsgi-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
uwsgi-1         |     return executor(sql, params, many, context)
uwsgi-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
uwsgi-1         |     with self.db.wrap_database_errors:
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
uwsgi-1         |     raise dj_exc_value.with_traceback(traceback) from exc_value
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
uwsgi-1         |     return self.cursor.execute(sql, params)
uwsgi-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         | django.db.utils.DataError: value too long for type character varying(30)
postgres-1      | 2024-02-22 10:36:21.624 UTC [954] ERROR:  value too long for type character varying(30)
postgres-1      | 2024-02-22 10:36:21.624 UTC [954] STATEMENT:  INSERT INTO "dojo_sonarqube_issue" ("key", "status", "type") VALUES ('de57db69-ac25-4b7a-b3a2-92ff11a41805', 'TO_REVIEW', 'SECURITY_HOTSPOT') RETURNING "dojo_sonarqube_issue"."id"
uwsgi-1         | [22/Feb/2024 10:36:21] ERROR [dojo.tools.api_sonarqube.importer:327] value too long for type character varying(30)
uwsgi-1         | Traceback (most recent call last):
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 929, in get_or_create
uwsgi-1         |     return self.get(**kwargs), False
uwsgi-1         |            ^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
uwsgi-1         |     raise self.model.DoesNotExist(
uwsgi-1         | dojo.models.Sonarqube_Issue.DoesNotExist: Sonarqube_Issue matching query does not exist.
uwsgi-1         |
uwsgi-1         | During handling of the above exception, another exception occurred:
uwsgi-1         |
uwsgi-1         | Traceback (most recent call last):
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
uwsgi-1         |     return self.cursor.execute(sql, params)
uwsgi-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         | psycopg2.errors.StringDataRightTruncation: value too long for type character varying(30)
uwsgi-1         |
uwsgi-1         |
uwsgi-1         | The above exception was the direct cause of the following exception:
uwsgi-1         |
uwsgi-1         | Traceback (most recent call last):
uwsgi-1         |   File "/app/dojo/tools/api_sonarqube/importer.py", line 291, in import_hotspots
uwsgi-1         |     sonarqube_issue, _ = Sonarqube_Issue.objects.update_or_create(
uwsgi-1         |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
uwsgi-1         |     return getattr(self.get_queryset(), name)(*args, **kwargs)
uwsgi-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 962, in update_or_create
uwsgi-1         |     obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
uwsgi-1         |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 936, in get_or_create
uwsgi-1         |     return self.create(**params), True
uwsgi-1         |            ^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 671, in create
uwsgi-1         |     obj.save(force_insert=True, using=self.db)
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 812, in save
uwsgi-1         |     self.save_base(
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 863, in save_base
uwsgi-1         |     updated = self._save_table(
uwsgi-1         |               ^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1006, in _save_table
uwsgi-1         |     results = self._do_insert(
uwsgi-1         |               ^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1047, in _do_insert
uwsgi-1         |     return manager._insert(
uwsgi-1         |            ^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
uwsgi-1         |     return getattr(self.get_queryset(), name)(*args, **kwargs)
uwsgi-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1791, in _insert
uwsgi-1         |     return query.get_compiler(using=using).execute_sql(returning_fields)
uwsgi-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql
uwsgi-1         |     cursor.execute(sql, params)
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
uwsgi-1         |     return self._execute_with_wrappers(
uwsgi-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
uwsgi-1         |     return executor(sql, params, many, context)
uwsgi-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
uwsgi-1         |     with self.db.wrap_database_errors:
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
uwsgi-1         |     raise dj_exc_value.with_traceback(traceback) from exc_value
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
uwsgi-1         |     return self.cursor.execute(sql, params)
uwsgi-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         | django.db.utils.DataError: value too long for type character varying(30)
uwsgi-1         |
uwsgi-1         | [22/Feb/2024 10:36:21] ERROR [dojo.api_v2.exception_handler:36] 'NoneType' object is not iterable
uwsgi-1         | Traceback (most recent call last):
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
uwsgi-1         |     response = handler(request, *args, **kwargs)
uwsgi-1         |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
uwsgi-1         |     self.perform_create(serializer)
uwsgi-1         |   File "/app/dojo/api_v2/views.py", line 3229, in perform_create
uwsgi-1         |     serializer.save(push_to_jira=push_to_jira)
uwsgi-1         |   File "/app/dojo/api_v2/serializers.py", line 2534, in save
uwsgi-1         |     ) = reimporter.reimport_scan(
uwsgi-1         |         ^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/app/dojo/importers/reimporter/reimporter.py", line 682, in reimport_scan
uwsgi-1         |     ) = self.process_parsed_findings(
uwsgi-1         |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/app/dojo/decorators.py", line 48, in __wrapper__
uwsgi-1         |     return func(*args, **kwargs)
uwsgi-1         |            ^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/celery/local.py", line 182, in __call__
uwsgi-1         |     return self._get_current_object()(*a, **kw)
uwsgi-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/usr/local/lib/python3.11/site-packages/celery/app/task.py", line 411, in __call__
uwsgi-1         |     return self.run(*args, **kwargs)
uwsgi-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^
uwsgi-1         |   File "/app/dojo/importers/reimporter/reimporter.py", line 71, in process_parsed_findings
uwsgi-1         |     for item in items:
uwsgi-1         | TypeError: 'NoneType' object is not iterable
uwsgi-1         | [22/Feb/2024 10:36:21] ERROR [django.request:241] Internal Server Error: /api/v2/reimport-scan/`

API Call That I use to import the scan

`curl -X 'POST'   'http://localhost:8080/api/v2/reimport-scan/'   -H 'accept: application/json'   -H 'Content-Type: multipart/form-data'   -H 'Authorization: Token TOKEN'   -F 'api_scan_configuration=1'   -F 'scan_type=SonarQube API Import'   -F 'product_name=demo'   -F 'engagement_name=demo'   -F 'auto_create_context=true'`

**Comment by kiblik** [comment]
Full context and more readable log: https://owasp.slack.com/archives/C2P5BA8MN/p1708598229852049?thread_ts=1708528719.634919&cid=C2P5BA8MN

**Comment by manuel-sommer** [comment]
I guess this can be closed @mtesauro. Could you please update the PR review process to always close linked issues once the PR is merged / released?
