### ISSUE TITLE
Importing Grype result not handling missing severity key

### ISSUE THREAD

**Issue by mfindra** [DefectDojo/django-DefectDojo#9618]
**Bug description**
When importing Anchore Grype output in JSON format (using API), not all fields are handled correctly. Based on https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/anchore_grype/parser.py#L34

if the key severity is missing, the import will fail with 500 internal error.  If other key eg. namespace is missing `.get` will return `None` and import can continue.

**Steps to reproduce**
1. Generate Grype scan output.
2. Remove `severity` from any of the matches inside `vulnerability`.
3. Import file.
4. Internal Error 500.

**Expected behavior**
Either Assign `None` or `Info`.

**Deployment method** 
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: Fedora Linux 39  
 - DefectDojo version (see footer) or commit message: DefectDojo/release/2.30.1

**Logs** 
```
[22/Feb/2024 19:06:05] ERROR [dojo.api_v2.exception_handler:36] 'severity'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/app/dojo/api_v2/views.py", line 3047, in perform_create
    serializer.save(push_to_jira=push_to_jira)
  File "/app/dojo/api_v2/serializers.py", line 2219, in save
    ) = importer.import_scan(
        ^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/importers/importer/importer.py", line 315, in import_scan
    parsed_findings = parser.get_findings(scan, test)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/tools/anchore_grype/parser.py", line 34, in get_findings
    vuln_severity = self._convert_severity(vulnerability["severity"])
                                           ~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'severity'
[22/Feb/2024 19:06:05] ERROR [django.request:241] Internal Server Error: /api/v2/import-scan/
```

**Sample scan files**
If applicable, add sample scan files to help reproduce your problem.

**Screenshots**

**Additional context** (optional)

**Comment by mfindra** [comment]
the severity is missing on line 5394.

[xjoin-kafka-connect-strimzi:latest_grype_2024-02-22_19:46:26.json](https://github.com/DefectDojo/django-DefectDojo/files/14383607/xjoin-kafka-connect-strimzi.latest_grype_2024-02-22_19.46.26.json)

**Comment by manuel-sommer** [comment]
See PR
