### ISSUE TITLE
High memory consumption when deleting engagements, tests...

### ISSUE THREAD

**Issue by Ravenons** [DefectDojo/django-DefectDojo#964]
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description

The view generated when asking for confirmation to delete an engagement or similar consumes too much memory. This view is the one containing related objects that will be deleted too (by cascading).

Actually, it happens too when the deletion itself is requested (when you confirm). This is because both requests use the same endpoint (e.g. _engagements/1/delete_) with different HTTP methods and the data for the view asking for confirmation is precomputed before checking which HTTP method is handling. The view asking for confirmation is obtained using GET and the deletion itself happens when using POST to the same endpoint.

Two things must be corrected here:
1) For the deletion itself (POST), the data for the view asking for confirmation (the one obtained with GET) should not be precomputed.
2) Generating the data for the view asking for confirmation (GET) should be lighter.

The code affected is present in several views for different objects, like products, users... Just search for _NestedObjects_, which is the one causing the high memory consumption.

### Operating System 

Debian 9.8 (stretch)

### Install

- [x] setup.bash
- [ ] docker

### DefectDojo Version

master 7eacd539baa5a2af3aaaad0d8d46880e7ef87102

### Steps to Reproduce

1) Try to delete an existing high-level object with a lot of related objects (e.g. deleting an engagement after importing scan results).
2) Observe how both the preview "are you sure?" view and the deletion itself increases significantly the memory usage (4 GB's each in my case).

**Comment by Ravenons** [comment]
I will write a PR tomorrow for the first issue (avoid precomputation for POST view), and I will investigate how to deal with the second issue.

**Comment by aaronweaver** [comment]
@Ravenons Thanks for digging into this, your plans sounds good to address.

**Comment by Ravenons** [comment]
@aaronweaver The second issue can be solved by programming a custom function that gets the related objects to be deleted, but does not load all these objects into memory, like NestedObjects is doing (so just getting the string version of the object).

Actually the view itself does not use the whole object at all, so we are optimising. Is this approach OK for you?

**Comment by Ravenons** [comment]
Hey, there's a question still there, and an issue to resolve. Should I open a new issue for that?

**Comment by Ravenons** [comment]
and another thing to correct*

**Comment by aaronweaver** [comment]
This one, right? 

> The second issue can be solved by programming a custom function that gets the related objects to be deleted, but does not load all these objects into memory, like NestedObjects is doing (so just getting the string version of the object).

Yes, another issue for tracking is fine. Thx

**Comment by Ravenons** [comment]
New issue for the second problem here: https://github.com/DefectDojo/django-DefectDojo/issues/979
