### ISSUE TITLE
Additional safeguards needed for "null" values in SCA result type. 

### ISSUE THREAD

**Issue by KK7NZY** [DefectDojo/django-DefectDojo#9641]
Attempted to import a Checkmarx Detailed file with the "sca" result type, but it threw an error when it reached line 447 of the Checkmarx parser. [Here is the link to the file.](https://github.com/DefectDojo/django-DefectDojo/blob/c5d896b2a606985f41669388962e47409f4866ba/dojo/tools/checkmarx/parser.py#L447)

I was able to get around the issue by adding `results[result_type].get("packages", []) or []`. I also added the same correction to other areas of the code that were attempting to loop over a list.

Posting example of the SCA result type below. 

```json
"sca": {
   "packagesCount": 0,
   "packages": null,
   "containersCount": 0,
   "containers": null,
   "vulnerabilities": {
    "total": 0,
    "critical": 0,
    "high": 0,
    "medium": 0,
    "low": 0,
    "info": 0
   }
```

**Steps to reproduce**
1. Upload file with example SCA result type posted above. 
2. See error

**Comment by manuel-sommer** [comment]
@KK7NZY  I was not able to reproduce this. Could you please add an output file to reproduce this? This will also serve as a unittest scan file to stabalize the parser.

**Comment by manuel-sommer** [comment]
@KK7NZY ,

could you please post a valid sample file to reproduce this. Yours is not valid, it is a deformed JSON file. I would help you with a PR if you can post a sample file here.

**Comment by manuel-sommer** [comment]
No feedback for multiple weeks. can we close this @mtesauro ?
