### ISSUE TITLE
DefectDojo should support Idle Session Timeout

### ISSUE THREAD

**Issue by tech-surajrk** [DefectDojo/django-DefectDojo#9662]
Currently I dont see a feature in DefectDojo where the session is IDLE then defectdojo logout automatically.

This is good to have feature when it comes to security standpoint if the tool is handling the finding data for each product.

**Comment by WojTecH94** [comment]
Did you try to configure DefectDojo browser session timeout by setting DD_SESSION_EXPIRE_AT_BROWSER_CLOSE to TRUE & DD_SESSION_COOKIE_AGE to 86400 (i.e., 24 hours) in dojo/settings/settings.dist.py ?

**Comment by tech-surajrk** [comment]
> Did you try to configure DefectDojo browser session timeout by setting DD_SESSION_EXPIRE_AT_BROWSER_CLOSE to TRUE & DD_SESSION_COOKIE_AGE to 86400 (i.e., 24 hours) in dojo/settings/settings.dist.py ?

Yes. But this is not solving the expectation.

Like if suppose a User is logged in Defectdojo and the browser is kept open and we are not browsing the application for more then 30 minutes and after 30 mins if we go and browse the application the session is still active even after the session was kept idle for more then 30 mins.

So there should be a feature to monitor the idle session and logout the user if the session is idle for specific period of time defined in the settings. (Like example logout the user after 30 mins of idle session)

**Comment by WojTecH94** [comment]
I think COOKIE SESSION AGE which I mentioned does exactly that...

**Comment by tech-surajrk** [comment]
> I think COOKIE SESSION AGE which I mentioned does exactly that...

@WojTecH94 - Cookie session age is just defining the age of a cookie. If i define cookie session age to 30 mins then in this case Even if my session is active then too it will end my session in 30 mins.

Active session should not end the cookie in 30 mins. The expectation is to end the cookie session if it is inactive for 30 mins

**Comment by mtesauro** [comment]
@tech-surajrk Please see Django session documentation for details: https://docs.djangoproject.com/en/4.2/topics/http/sessions/
