### ISSUE TITLE
Date of test (scan) in UI off by 1

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#970]
### Issue Type 
- [X] Bug

### Description
When importing a scan via UI or APIv2, the date that is displayed afterwards in the DD UI is off by one (1 day earlier)

### Operating System 
Debian 9

### Install

- [X] setup.bash

### DefectDojo Version
dev branch 22/3/2019 (46692a0f7bf568f5739d093ab0e4d2ef6733faf6)

### Steps to Reproduce
import a npm audit scan into an engagement using UI or APIv2. Select today as import date.
For example attached report.json. 
Observe after import the date column for the scan displays yesterdays date

**Comment by valentijnscholten** [comment]
[report.json.txt](https://github.com/DefectDojo/django-DefectDojo/files/2996684/report.json.txt)

**Comment by valentijnscholten** [comment]
Did some testing with scans uploaded just now, scan_date = '2019-04-25' provided in api v2 upload.
Results in 2019-04-24 in database as target_start and target_end. The created and updated columns look alright (2019-04-25):

```
MariaDB [DojoDB]> select * from dojo_test order by id desc limit 5;
+-----+-------------+----------------------------+----------------------------+----------------+-------------+------------------+----------------------------+----------------------------+---------------+----------------+---------+--------------+
| id  | description | target_start               | target_end                 | estimated_time | actual_time | percent_complete | updated                    | created                    | engagement_id | environment_id | lead_id | test_type_id |
+-----+-------------+----------------------------+----------------------------+----------------+-------------+------------------+----------------------------+----------------------------+---------------+----------------+---------+--------------+
| 747 | NULL        | 2019-04-24 22:00:00.000000 | 2019-04-24 22:00:00.000000 | NULL           | NULL        |              100 | 2019-04-25 13:31:55.208353 | 2019-04-25 13:31:55.208380 |           421 |              1 |    NULL |            2 |
| 746 | NULL        | 2019-04-24 22:00:00.000000 | 2019-04-24 22:00:00.000000 | NULL           | NULL        |              100 | 2019-04-25 13:27:39.102271 | 2019-04-25 13:27:39.102296 |           412 |              1 |    NULL |            2 |
| 745 | NULL        | 2019-04-24 22:00:00.000000 | 2019-04-24 22:00:00.000000 | NULL           | NULL        |              100 | 2019-04-25 13:27:07.356461 | 2019-04-25 13:27:07.356498 |           412 |              1 |    NULL |            2 |
| 744 | NULL        | 2019-04-24 22:00:00.000000 | 2019-04-24 22:00:00.000000 | NULL           | NULL        |              100 | 2019-04-25 13:26:34.959157 | 2019-04-25 13:26:34.959187 |           412 |              1 |    NULL |            2 |
| 743 | NULL        | 2019-04-24 22:00:00.000000 | 2019-04-24 22:00:00.000000 | NULL           | NULL        |              100 | 2019-04-25 13:23:53.050969 | 2019-04-25 13:23:53.050996 |           421 |              1 |    NULL |            2 |
+-----+-------------+----------------------------+----------------------------+----------------+-------------+------------------+----------------------------+----------------------------+---------------+----------------+---------+--------------+
```

**Comment by valentijnscholten** [comment]
BTW created and updates are 2 hours off, which could be because the timestamps are in UTC and I am living in CEST which is UTC+2. target_start looks to have the same 2 hour difference, so maybe the display logic is not respecting the timezone.

**Comment by valentijnscholten** [comment]
OK, so I have found the timezone setting in settings.py and changed it to `DD_TIME_ZONE=(str, 'Europe/Amsterdam')` but it doesn't make any difference. Anybody familiar with timezones in django and/or DefectDojo to know what to do? It's pretty confusing to have (some of) your dates off by one.

**Comment by valentijnscholten** [comment]
Just observed these warnings in the logs:

```
/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:1393: RuntimeWarning: DateTimeField Test.target_start received a naive datetime (2019-04-25 00:00:00) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:1393: RuntimeWarning: DateTimeField Test.target_end received a naive datetime (2019-04-25 00:00:00) while time zone support is active.
  RuntimeWarning)
```

**Comment by ppiotr3k** [comment]
As discussed on Slack with @valentijnscholten  I'm having a look and going to propose something for these timezone issues. @aaronweaver could you please check my right on GitHub? My reviews of PR still don't count for merging, neither can I assign an issue to myself, thanks!

**Comment by aaronweaver** [comment]
@ppiotr3k You should be set I confirmed your access earlier this afternoon. Regarding timezones I know there was some work done on this awhile back. I remember Patrik Nordlen did some work on that. Might want to review those PR's.
