### ISSUE TITLE
Flot-axis still in Yarn.lock file under Components folder

### ISSUE THREAD

**Issue by CarpFlop** [DefectDojo/django-DefectDojo#9700]
Flot-axis was removed from everywhere except yarn.lock.

It's a malicious package with a Synk rating of 9.8/10 Criticality.
Please hotfix for part of latest release that was meant to address this issue!

Thank you guys for your hard work

**Comment by CarpFlop** [comment]
https://github.com/DefectDojo/django-DefectDojo/issues/9187 Potentially false positive:

But since all references and usage of flot-axislabels was removed in latest update, potentially still worth cleaning up lingering reference in lockfile

**Comment by mtesauro** [comment]
@CarpFlop  Agree that this appears to be lingering cruft vs a real issue as this library was removed in  #9540 

I do agree we should remove that reference if for no other reason to remove confusion.

**Comment by manuel-sommer** [comment]
This can be close @mtesauro ;-) was already released.
