### ISSUE TITLE
Import nmap scans to defecetdojo

### ISSUE THREAD

**Issue by gitingua** [DefectDojo/django-DefectDojo#9726]
Hello, please tell me if there is a ready-made python script, examples, for sending nmap scan results via api

I can't find anything useful. It’s not adding correctly via api, maybe I’m doing something wrong somewhere.

Help!)

**Comment by manuel-sommer** [comment]
@gitingua, yes you are doing something wrong. Maybe this helps: https://github.com/MaibornWolff/dd-import

Please close the issue or rather ask int the owasp slack channel.

**Comment by manuel-sommer** [comment]
@gitingua, please ask questions in the slack channel and not in an issue.
