### ISSUE TITLE
Trivy Operator Parser: add ClusterComplianceReport

### ISSUE THREAD

**Issue by Pionerd** [DefectDojo/django-DefectDojo#9733]
**Is your feature request related to a problem? Please describe**
Currently it is not possible to report on CIS or NSA compliance. These reports are generated by the Trivy Operator but cannot be imported in DefectDojo.

**Describe the solution you'd like**
I would like the ClusterComplianceReport resources to be supported by the Trivy Operator Parser. 

**Describe alternatives you've considered**
I do not mind writing a PR, but my Python is more on a scripting level. Adding the ClusterComplianceReports requires a bit of additional logic, since it is of a different structure than e.g. the VulnerabilityReport

**Additional context**
Discussion originated here: https://github.com/telekom-mms/trivy-dojo-report-operator/issues/60#issuecomment-1994171501

**Comment by manuel-sommer** [comment]
Hi @Pionerd , if you have a sample file I could help you with advancing the parser.

**Comment by Pionerd** [comment]
[cis_example.json](https://github.com/DefectDojo/django-DefectDojo/files/14590607/cis_example.json)

**Comment by manuel-sommer** [comment]
Hi @Pionerd see PR.

Could you also provide a File with 0 findings?

**Comment by manuel-sommer** [comment]
This can be closed @Pionerd
