### ISSUE TITLE
High memory consumption in the confirmation view for deletion

### ISSUE THREAD

**Issue by Ravenons** [DefectDojo/django-DefectDojo#979]
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description

The view generated when asking for confirmation to delete an engagement or similar consumes too much memory. This view is the one containing related objects that will be deleted too (by cascading).

Generating the data for the view asking for confirmation should be lighter. The code affected is present in several views for different objects, like products, users... Just search for _NestedObjects_, which is the one causing the high memory consumption.

### Operating System 

Debian 9.8 (stretch)

### Install

- [ ] Kubernetes
- [ ] Docker
- [x] setup.bash / legacy-setup.bash

### DefectDojo Version

master 7eacd539baa5a2af3aaaad0d8d46880e7ef87102

### Steps to Reproduce

1. Try to delete an existing high-level object with a lot of related objects (e.g. deleting an engagement after importing scan results).
2. Observe how the preview "are you sure?" for the deletion increases significantly the memory usage (4 GB's in my case).

**Comment by Ravenons** [comment]
I will make a PR for this, btw.

**Comment by aaronweaver** [comment]
Thanks for working on this @Ravenons

**Comment by devGregA** [comment]
PR was merged I believe.

**Comment by Ravenons** [comment]
> PR was merged I believe.

I think you mean the PR for #964, I'm still checking this issue here.

**Comment by ppiotr3k** [comment]
@Ravenons, I'm a bit confused if this issue should still be open, or if it has been resolved. Please advise, thanks!

**Comment by Ravenons** [comment]
> @Ravenons, I'm a bit confused if this issue should still be open, or if it has been resolved. Please advise, thanks!

I did not solve it, and I doubt somebody did in the meanwhile, so the issue should still be there. I have a solution which is almost working, but I don't know if I'm going to be able to fix it soon. I would leave it closed, and if I finally fix it, I will inform here.
