### ISSUE TITLE
Upgrade to 1.5.4 from 1.5.1 breaks Dojo

### ISSUE THREAD

**Issue by bhowmik** [DefectDojo/django-DefectDojo#980]
### Issue Type 
- [ ] Bug

### Description
Upgrading a standalone DefectDojo v1.5.1 to v1.5.4 via the steps on the upgrade page (https://defectdojo.readthedocs.io/en/latest/upgrading.html) throws errors while accessing the following areas.
- /product
- /engagement
- /finding
- /finding/open
- /calendar/engagements
- /metrics
- /metrics/research
- /metrics/product/type

The error that shows up is 

(1054, "Unknown column 'dojo_engagement.preset_id' in 'field list'")

### Operating System 
Ubuntu 16.04.6 LTS

### Install
- [ ] setup.bash / legacy-setup.bash

### DefectDojo Version
1.5.1 upgraded to 1.5.4

### Steps to Reproduce
Follow steps on https://defectdojo.readthedocs.io/en/latest/upgrading.html

### Screenshots 
<img width="1165" alt="DefectDojo - Error" src="https://user-images.githubusercontent.com/10627098/55002417-91530200-4ffc-11e9-85ba-4498c355feb2.png">

**Comment by aaronweaver** [comment]
To confirm, you did a make migrations and then migrate?

**Comment by bhowmik** [comment]
Yep, i did the make migrations and then migrate. If it helps I can only see 109 tables in the defectdojo DB as compared to a 112 tables in a fresh docker install of v1.5.4.
