### ISSUE TITLE
Wfuzz parser: accept more status codes

### ISSUE THREAD

**Issue by GilFernandes2000** [DefectDojo/django-DefectDojo#9824]
Hello,

I'm using wfuzz to perform dictionary attacks to try to find possible missed directories from spider scans.
When trying to import the results to the DefectDojo I ran into problems. It doesn't accept some status codes present in the results.
Also, is there a possibility to discard the severity based on the status code? From the results I only wanted to upload the endpoints.

Here's a sample output
[wfuzz_results.json](https://github.com/DefectDojo/django-DefectDojo/files/14757500/wfuzz_results.json)

Have a nice day.

**Comment by manuel-sommer** [comment]
Hi @GilFernandes2000 , I uploaded your sample output and it was fine, all three results were shown. 
Could you please be more specific about which DefectDojo version you used and also which status codes were not covered. In https://github.com/DefectDojo/django-DefectDojo/releases/tag/2.32.0 there were fixes regarding Wfuzz.
Regarding the severity, this could be implemented as soon as https://github.com/DefectDojo/django-DefectDojo/issues/9250 would be implemented. 

I guess this can be closed @mtesauro and ias a false positive.

**Comment by GilFernandes2000** [comment]
Hi @manuel-sommer, sorry for the inconvenience. I wasn't running the latest version of DefectDojo. I was having problems with the status code 301 but I saw that it was already fixed.
In case of the severity, I just wanted to have the option to skip it because there are endpoints that are supposed to be visible and accessible to the public so a High severity doesn't apply.
I'll close this issue.

Thanks for the prompt answer.

**Comment by manuel-sommer** [comment]
Within the linked issue, finetuneing could be implemented.
