### ISSUE TITLE
apply_tags_to_findings not working as intended 

### ISSUE THREAD

**Issue by enidevops** [DefectDojo/django-DefectDojo#9841]
**Bug description**
It appears there's an issue with the apply_tags_to_findings API functionality. During the process of importing results with the following command:

curl --location --request POST 'https://defectdojo.internal/api/v2/import-scan/' \
--header 'Authorization: Token 123456' \
--form 'engagement=434' \
--form 'verified="true"' \
--form 'active="true"' \
--form 'scan_date=2024-03-13' \
--form 'scan_type=MobSF Scan' \
--form 'minimum_severity="Info"' \
--form 'skip_duplicates="true"' \
--form 'close_old_findings="false"' \
--form 'environment=GITLAB' \
--form 'apply_tags_to_findings="true"' \
--form 'tags="test1"' \
--form 'file=@mobsf_scan.json;type=application/json'

I get the following result:

![image](https://github.com/DefectDojo/django-DefectDojo/assets/44378292/56aea6c7-e6d2-453f-a69c-ea81cbbcd556)
The tag gets applied correctly to the test itself, but the findings tags are messed up:

![image](https://github.com/DefectDojo/django-DefectDojo/assets/44378292/59820a77-003b-429a-97a3-3bde51af8f06)

**Sample File
[mobsf_scan.txt](https://github.com/DefectDojo/django-DefectDojo/files/14786484/mobsf_scan.txt)

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**

- DefectDojo version 2.32.2

**Comment by mtesauro** [comment]
@enidevops 
There's a couple of PRs that were merged after 2.32.2 that involve tags - I'd look a those and potentially upgrade. See https://github.com/DefectDojo/django-DefectDojo/releases/tag/2.32.3

There have been a couple of tag-related PRs against the dev branch which will be part of the 2.33.0 release next week (assuming the are approved and merged). So there's a decent chance 2.33.0 will resolve this as well.

**Comment by mtesauro** [comment]
@enidevops 
Just checked and this isn't happening with #9830 which will be in 2.33.0 (Monday, April 1st)

**Comment by enidevops** [comment]
@mtesauro ok great, thank you! then I will wait for the 2.33.0 release

**Comment by mtesauro** [comment]
@enidevops Feel free to reopen this if needed but I don't expect it to be needed so I'm closing this now.

**Comment by enidevops** [comment]
@mtesauro I just tried the same command with 2.33.0 and now the tags are only applied to the test and not the findings:

![image](https://github.com/DefectDojo/django-DefectDojo/assets/44378292/340409af-d6cf-4617-a7b8-28e896495c00)

**Comment by enidevops** [comment]
This seems to be happening only with the scan type 'MobSF Scan'. I tested this with the SARIF format and there it is working

**Comment by mtesauro** [comment]
@enidevops 
Perhaps compare the structure of your MobSF Scan file output to what's in the [unit tests](https://github.com/DefectDojo/django-DefectDojo/tree/master/unittests/scans/mobsfscan) because I'm not seeing that behavior with those files.
