### ISSUE TITLE
uWSGI OOMKilled after certain interactions (Kubernetes)

### ISSUE THREAD

**Issue by jackson-van-hyning** [DefectDojo/django-DefectDojo#9849]
**Bug description**
uWSGI container in Django pod crashes and restarts with reason "OOMKilled" after certain actions/interactions. While I have noticed several different actions that cause this behavior, the most consistent of these is clicking on "Metrics Dashboard" on the web interface. Frequent and/or large requests made through the DefectDojo API also seem to cause this behavior, although less consistently.

I should note that the issue being experienced is different from the one described in [DefectDojo/django-DefectDojo#9562](https://github.com/DefectDojo/django-DefectDojo/issues/9562) in a couple of ways:
- The problem discussed in that issue was related to the max file descriptor number, however the one shown in my case is consistent with what is expected.
- Unlike in this issue, the uWSGI container does not crash upon starting up, but instead upon being interacted with in certain ways.

**Steps to reproduce**
1. Deploy helm chart to a kubernetes cluster.
2. Navigate to DefectDojo web interface, and click on the "Metrics Dashboard" option from the "Metrics" panel.
3. Web interface displays "An error occured", and defectdojo-django pod displays "OOMKilled" status. Web interface then displays "503 Temporarily Unavailable".
4. Pod is restarted and interface is made re-available.
_This is not the only course of action that I have observed to cause the behavior, but it is the most consistent and most quick to test_

**Expected behavior**
Expect "Metrics Dashboard" to be displayed after clicked on from the web interface, with no issue.

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - *NOTE*: _Embarrassingly, as of writing this I am not 100% sure about specific environment information about the Kubernetes nodes (OS Image, Kernel Version, etc.) and I do not have permission on the cluster to describe these nodes. I will update this issue with that information as soon as I can find it._
 - DefectDojo version - 2.32.3

**Logs** 
The below logs are taken from a uWSGI container that was started and then immediately crashed after "Metrics Dashboard" was selected in the web interface. Note that the request "GET /dashboard" is not from the aforementioned Metrics Dashboard, but from the homepage dashboard.

```
 kl dojo-defectdojo-django-6b9f99cd6-n4nvk -c uwsgi --previous
/usr/local/lib/python3.11/site-packages/coreapi/codecs/download.py:5: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
  import cgi
System check identified no issues (0 silenced).
*** Starting uWSGI 2.0.23 (64bit) on [Mon Apr  1 08:16:23 2024] ***
compiled with version: 10.2.1 20210110 on 27 November 2023 18:58:16
os: Linux-5.15.0-1031-azure #38~20.04.1-Ubuntu SMP Mon Jan 9 18:23:48 UTC 2023
nodename: dojo-defectdojo-django-6b9f99cd6-n4nvk
machine: x86_64
clock source: unix
detected number of CPU cores: 16
current working directory: /app
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI without its master process manager ***
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8081 fd 3
spawned uWSGI http 1 (pid: 14)
uwsgi socket 0 bound to UNIX address /run/defectdojo/uwsgi.sock fd 6
Python version: 3.11.4 (main, Aug 16 2023, 05:31:52) [GCC 10.2.1 20210110]
Python main interpreter initialized at 0x7fca33a16558
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 183136 bytes (178 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7fca33a16558 pid: 1 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 1, cores: 2)
spawned uWSGI worker 2 (pid: 15, cores: 2)
[pid: 1|app: -|req: -/-] 198.18.218.1 (-) {34 vars in 421 bytes} [Mon Apr  1 08:16:24 2024] GET /uwsgi_health => generated 16003 bytes in 2594 msecs (HTTP/1.1 200) 10 headers in 489 bytes (1 switches on core 0)
[pid: 1|app: -|req: -/-] 198.18.180.80 (e078436) {74 vars in 1552 bytes} [Mon Apr  1 08:16:28 2024] GET /dashboard => generated 59560 bytes in 253 msecs (HTTP/1.1 200) 8 headers in 373 bytes (1 switches on core 1)
```

As you might be able to tell, these logs do not show anything out of the ordinary, which is part of what's making this issue so hard to track down.

Finally, I should note that I am somewhat inexperienced not only in DefectDojo deployment but also in using GitHub issues in this manner in general, so please forgive my lack of knowledge and inform me of any information I can provide that could help in analyzing this problem. Thanks in advance

**Comment by pb-let-me-search-code-thx** [comment]
+1, I'm getting the same issue on a Helm deployment of v2.32.3.

**Comment by mtesauro** [comment]
@jackson-van-hyning @pb-let-me-search-code-thx 
FWIW, you're much more likely to get better answers on OWASP's Slack in the DefectDojo channel. There's more traffic and interaction there then on Github issues.

Details on joining that Slack instance are at https://github.com/DefectDojo/django-DefectDojo?tab=readme-ov-file#community-getting-involved-and-updates

**Comment by jackson-van-hyning** [comment]
Still facing this issue after updating to 2.33.1. Let me know if I can provide any configuration values or anything that could help solve the problem

**Comment by sebglon** [comment]
same issue for me with version 2.31.4

**Comment by jackson-van-hyning** [comment]
Update: This was resolved, though it was mostly handled by someone else so the details I can provide are limited. We substantially increased the memory limits and also discovered that the celery worker was a zombie, so that was addressed. Following this, the uWSGI container has not shown the same OOM issues.
