### ISSUE TITLE
ORCA Scan (New Importer / Enhancement Pre-approval Request)

### ISSUE THREAD

**Issue by jackson-van-hyning** [DefectDojo/django-DefectDojo#9851]
I would like scans from the ORCA cloud vulnerability management platform to be supported. However, due to the nature of the reason I need this feature implemented, I have chosen to open this issue for the purposes of both requesting this enhancement, and requesting pre-approval to begin working on it myself.

**Scanner Name**: ORCA 
**Scanner Description** _(From [ORCA website](https://orca.security/platform/vulnerability-management/#:~:text=Orca%20collects%20data%20directly%20from,and%20sensitive%20data%20at%20risk.))_: 
- Orca collects data directly from your cloud configuration and the workload’s runtime block storage out-of-band.
- Within minutes, Orca finds and prioritizes your most critical cloud risks, including vulnerabilities, malware, misconfigurations, lateral movement risks, IAM risks, and sensitive data at risk.

**Scanner Link**: https://github.com/orcasecurity

**Sample File**
_I currently do not have access to an example scan file that is small enough for it to be reasonably attached to this issue. As soon as I do, I will update this issue accordingly. Until then, this issue can be regarded purely as an enhancement approval request, and not as a New Importer request_

**Comment by manuel-sommer** [comment]
I guess you can just start working and making a PR. I don't think you need an enhancement approval, I built several parsers in the past and they were all merged once all review requests are done. Note that you should not built an api parser, but rather a normal file upload parser. https://defectdojo.github.io/django-DefectDojo/contributing/how-to-write-a-parser/#api-parsers

**Comment by mtesauro** [comment]
@jackson-van-hyning We have no problem with PRs for new parsers.  Please read the docs manual-sommer linked on writing a parser and best of luck with the PR :+1:

**Comment by jackson-van-hyning** [comment]
Thank you!

**Comment by Camille-Arsac** [comment]
Hello,
Is anyone working on the ORCA parser?

**Comment by manuel-sommer** [comment]
Haven't seen anything. But this is also only possible if an example output file is provided. If you can provide that @Camille-Arsac , please in a new issue.
