### ISSUE TITLE
Endpoints by POST /api/v2/findings/

### ISSUE THREAD

**Issue by Stepashka20** [DefectDojo/django-DefectDojo#9884]
In user API i can add endpoints in form:
![image](https://github.com/DefectDojo/django-DefectDojo/assets/40739871/5caae2e8-c80b-400e-9adf-53da5cfc4c41)
![image](https://github.com/DefectDojo/django-DefectDojo/assets/40739871/8cdf6029-9461-405f-8b2b-4505e4d25e40)

However, how to add endpoint in `POST /api/v2/findings/` ? I have tried:
```javascript
    const findings = await axios.post('/api/v2/findings/',{
        test: TEST_ID,
        title: "title",
        description: "Test desc",
        severity: "Low",
        url: 'https://google.com',
        active: true,
        verified: false,
        numerical_severity: 1,
        found_by: [1],
        endpoints: 5
    })
```

But response endpoints are empty:
![image](https://github.com/DefectDojo/django-DefectDojo/assets/40739871/9c125364-05fb-4ee3-a8a0-6d10813191a1)

**Comment by kiblik** [comment]
It is not possible to create `endpoint-finding` mapping via `/api/v2/findings/` endpoint. It is read-only.
You need to create the finding first and use `/api/v2/endpoint_status/` to connect your endpoint with the new finding.

**Comment by Stepashka20** [comment]
@kiblik thanks!
