### ISSUE TITLE
User persmission on views product

### ISSUE THREAD

**Issue by YuToutCourt** [DefectDojo/django-DefectDojo#9887]
Hello,

I want to ensure that not all users can see all products. For example, if I have a product with the product type AAA, I would like only the users in the group AAA to be able to see all the products for AAA. 
Do it is possible, and if yes can someone explain me.

**Comment by mtesauro** [comment]
@YuToutCourt Yes, this is very possible. I've done that and similar things many times with DefectDojo.

Please read the documentation on Permissions especially the section on Groups at https://documentation.defectdojo.com/usage/permissions/
