### ISSUE TITLE
Checkmarx import doesn't support all valid utf-8 characters

### ISSUE THREAD

**Issue by ptrovatelli** [DefectDojo/django-DefectDojo#989]
### Issue Type 
- [ ] Bug

### Operating System 
Windows 10 build 1803

### Install

- [x ] Docker

### DefectDojo Version
master on march 28 11pm UTC+1
*** MINGW64 /d/product/django-DefectDojo (master)
$ git pull
Already up to date.

*** MINGW64 /d/product/django-DefectDojo (master)
$ date
jeu. 28 mars 2019 22:47:04

### Steps to Reproduce
This is similar to https://github.com/DefectDojo/django-DefectDojo/issues/875 
When uploading checkmarx scans results, we're getting various errors although we're always uploading valid utf-8 byte sequences. 
You'll find attached different test files and an export of the debugging information from defectDojo.
Webgoat_reference.xml is the reference file and imports correcly. other files have been forged based on this file, after adding characters that cause the issue (those characters come from real checkmarx exports that I can't share)

The issues are found with: 
- utf-8 "REPLACEMENT CHARACTER". see https://www.utf8-chartable.de/unicode-utf8-table.pl?start=65280 this is a valid character. Hexa is: ef bf bd, unicode: U+FFFD
See test Webgoat_replacement_char.xml
error is: 
`(1366, "Incorrect string value: '\\xEF\\xBF\\xBD\\x0A--...' for column 'description' at row 1") `
when inserting into dojo_finding table

- **(THIS IS FIXED NOW IN DEV BRANCH)** characters badly converted by checkmarx probably from latin encoding to utf-8. Still they are valid utf-8 i believe. 
See tests 
  - Webgoat_badly_converted_by_checkmarx_1.xml **(THIS IS FIXED NOW IN DEV BRANCH) :**
    includes 2 2-byte characters: C3 83, C2 A9 (see https://www.utf8-chartable.de/unicode-utf8-table.pl, or http://en.wikipedia.org/wiki/UTF-8)
error is: 

`'ascii' codec can't decode byte 0xc3 in position 772: ordinal not in range(128)` 
in self.compute_hash_code() 

  - Webgoat_badly_converted_by_checkmarx_2.xml **(THIS IS FIXED NOW IN DEV BRANCH)** 
    includes 4 2-bytes characters c3 83, c6 92, c3 82, c2 a9 (see https://www.utf8-chartable.de/unicode-utf8-table.pl, https://www.utf8-chartable.de/unicode-utf8-table.pl?start=256 or http://en.wikipedia.org/wiki/UTF-8)

error is: 
`'ascii' codec can't decode byte 0xc3 in position 772: ordinal not in range(128)`
in  self.hash_code = self.compute_hash_code() 

Other than checking hexa values, I have checked the utf-8 validity with various methods taken from this thread : https://stackoverflow.com/questions/29465612/how-to-detect-invalid-utf8-unicode-binary-in-a-text-file (DBA answer in C, Blaf answer with grep) : 

(in ubuntu subsystem)
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

$ grep -axv '.*' Webgoat_badly_converted_by_checkmarx_1.xml
$ grep -axv '.*' Webgoat_badly_converted_by_checkmarx_2.xml
$ grep -axv '.*' Webgoat_replacement_char.xml
$

$ ./bad_utf8 issue_github/Webgoat_badly_converted_by_checkmarx_1.xml
$ ./bad_utf8 issue_github/Webgoat_badly_converted_by_checkmarx_2.xml
$ ./bad_utf8 issue_github/Webgoat_replacement_char.xml
$

Thanks

### Sample Scan File (if applicable)
[checkmarx_reports_and_debugging_information.zip](https://github.com/DefectDojo/django-DefectDojo/files/3020353/checkmarx_reports_and_debugging_information.zip)

**Comment by aaronweaver** [comment]
Recently addressed this on the burp importer and should handle it the same way.

**Comment by dr3dd589** [comment]
hey, @aaronweaver  are you able to reproduce this one in checkmarx import scan because in my case it is working fine all above sample scan is passed.

**Comment by ptrovatelli** [comment]
> hey, @aaronweaver are you able to reproduce this one in checkmarx import scan because in my case it is working fine all above sample scan is passed.

Hi dr3dd589, 
Thanks for checking on this. I have just rebuilt the docker images based on dev branch; now 
- Webgoat_badly_converted_by_checkmarx_1.xml and Webgoat_badly_converted_by_checkmarx_2.xml are OK
- Webgoat_replacement_char.xml is still KO

Are you using docker? from windows?
(I didn't rebuild the images before opening the issue so it's possible it was already in that situation 6 days ago sorry about that; or maybe the 2 other files were fixed since - i've seen a couple of commits changing the encoding management)

Thanks!

**Comment by dr3dd589** [comment]
I'm using both Docker as well as local on Linux. I have tested it on docker and only third one gives an error but locally it is working fine. and also error is different I think it is due to MySQL version used in docker. I google it and found this solution that is related to this error.
[link to solution](https://stackoverflow.com/a/10959780)

**Comment by aaronweaver** [comment]
Ah correct, @dr3dd589, utf8mb4 is what should be used. We should change the docker compose to initialize as utf8mb4.

**Comment by ptrovatelli** [comment]
Hi,
Following the stackoverflow instructions, I was able to make "Webgoat_replacement_char.xml" work with: 
- changing mysql configuration in the django-defectdojo_mysql_1 container
```
/etc/mysql/conf.d/mysql.cnf :
[mysql]
default-character-set=utf8mb4
```

```
/etc/mysql/mysql.conf.d/mysqld.cnf:
[mysqld]
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
```

- changing charset and collation in tables and columns (previously was latin1/latin1_swedish_ci)
```
use defectdojo
alter table  defectdojo.dojo_finding CHARACTER SET = utf8mb4 , COLLATE  utf8mb4_general_ci

use defectdojo;
ALTER TABLE dojo_finding 
  MODIFY description 
  longtext
  CHARACTER SET utf8mb4 
  COLLATE utf8mb4_general_ci;  

ALTER TABLE watson_searchentry 
  MODIFY content   longtext  CHARACTER SET utf8mb4   COLLATE utf8mb4_general_ci,
  MODIFY title   longtext  CHARACTER SET utf8mb4   COLLATE utf8mb4_general_ci,
  MODIFY description   longtext  CHARACTER SET utf8mb4   COLLATE utf8mb4_general_ci;

```
It might be a good idea to generalize to all the tables.

**Comment by ptrovatelli** [comment]
Not sure how to change mysql configuration files from docker-compose config but this works in docker-compose.yml: 
```
  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET CHARACTER SET utf8mb4;'
```

All tables and columns are then created with the correct collation: 

```
SELECT CHARACTER_SET_NAME, COLLATION_NAME FROM INFORMATION_SCHEMA.COLUMNS
where table_name = 'dojo_finding' and column_name = 'description'
CHARACTER_SET_NAME               COLLATION_NAME                   
-------------------------------- -------------------------------- 
utf8mb4                          utf8mb4_unicode_ci               

 SELECT TABLE_SCHEMA
    , TABLE_NAME
    , TABLE_COLLATION 
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME ='dojo_finding';
TABLE_SCHEMA                                                     TABLE_NAME                                                       TABLE_COLLATION                  
---------------------------------------------------------------- ---------------------------------------------------------------- -------------------------------- 
defectdojo                                                       dojo_finding                                                     utf8mb4_unicode_ci               

```

Doing a PR today

**Comment by adracea** [comment]
Wait , can you try pulling the fix from #1010  and trying with that to see if it fixes the UTF-8 issue ?

**Comment by adracea** [comment]
The MySQL issue may still happen though

**Comment by ptrovatelli** [comment]
@adracea the mysql issue is the only one remaining. the other 2 reports Webgoat_badly_converted_by_checkmarx_1.xml and Webgoat_badly_converted_by_checkmarx_2.xml regarding the hash function are already ok in dev branch by now; i'll edit my initial post to make this easier to follow
In your PR, can you attach test reports that fail processing without your PR and that the PR fixes? are they valid or invalid utf-8 sequences? 
Regards

**Comment by adracea** [comment]
I'll post it in a few minutes

**Comment by ptrovatelli** [comment]
The mysql issue should be fixed by @aaronweaver 's commit yesterday evening 6d4cc0f4c244675e9e8a6cadf240b29990d35741 . 
However I can't test it, the changes on docker-compose seem to have broken the docker-compose for windows (version 2.0.0.3 - engine 18.09.2) ; am I the only one? should I open another issue? 
It seeems that using the volume mount in the entrypoint is not working : at the time of trying to access it by  python, the "manage.py" file it's not there: 
`    entrypoint: ['/wait-for-it.sh', 'mysql:3306', '-t', '30', '--', 'python', 'manage.py', 'runserver 0.0.0.0:8000']`

i've tried also
`    entrypoint: ['/wait-for-it.sh', 'mysql:3306', '-t', '30', '--', 'python', '/app/manage.py', 'runserver 0.0.0.0:8000']`

```
D:\product\django-DefectDojo>docker start -ai django-defectdojo_uwsgi_1
wait-for-it.sh: waiting 30 seconds for mysql:3306
wait-for-it.sh: mysql:3306 is available after 0 seconds
python: can't open file 'manage.py': [Errno 2] No such file or directory
```

however if I commit the django-defectdojo_uwsgi_1 container id and run bash in it to have a look, the manage.py is there! 
```
D:\product\django-DefectDojo>docker commit  5ece100f7502  ptrovatelli/test
sha256:4c8979bb413f45060147c7982f22693b605f92f18f7bbef4a18013f009979acd

D:\product\django-DefectDojo>docker run -ti --entrypoint=sh  ptrovatelli/test
$ ls
dojo  manage.py  requirements.txt  tests  unit-tests.sh  wsgi.py
$ pwd
/app
$
```

**Comment by adracea** [comment]
Docker for windows seems to be rather weird , I use a hyper-v ubuntu vm for hosting dockers , I've had issues with actually building the container on linux .

**Comment by ptrovatelli** [comment]
I think we can close this

- the mysql issue is fixed on dev branch by https://github.com/DefectDojo/django-DefectDojo/commit/6d4cc0f4c244675e9e8a6cadf240b29990d35741 . 

- The hash issues were probably already fixed on dev branch when opening the issue or were fixed couple of days after opening this issue. 

- The docker-compose issues are tracked there https://github.com/DefectDojo/django-DefectDojo/issues/1026 

Thanks :)
