### ISSUE TITLE
Dedupe algo fields change - release information

### ISSUE THREAD

**Issue by WojTecH94** [DefectDojo/django-DefectDojo#9895]
**Is your feature request related to a problem? Please describe**
After https://github.com/DefectDojo/django-DefectDojo/pull/9619 changed Tenable's default fields (added description) used for deduplication there is a problem when reimporting scans:
Old findings have some hashes generated but new scans will be imported and different hashes (including added description field) will be generated which means that all the old findings will be closed and pretty the same new ones will be created.

**Describe the solution you'd like**
I am not sure if some generic solution (for example recalculate all hashes during DD upgrade) is possible, but there should be at least some kind of information in release notes that before importing new scans you should do manual recalculation of hashes.

**Describe alternatives you've considered**
I see that historically there were some "migrations" that changed types of findings so maybe it is possible to do it automatically during update.

**Comment by valentijnscholten** [comment]
The docs provide info on how to recalculate all hashes:
![image](https://github.com/DefectDojo/django-DefectDojo/assets/4426050/1ca5c925-aa68-40f3-ae84-316f32dbaa4f)
https://defectdojo.github.io/django-DefectDojo/usage/features/

**Comment by WojTecH94** [comment]
Yes I know and eventually I used this tool, but first you need to know that it is adviced to use manual deduplication after upgrading to this particular version of defect dojo (which changed hash code fields). Ideally deduplication could be trigerred automatically in such cases.
