### ISSUE TITLE
Yarn Audit v2 and later version

### ISSUE THREAD

**Issue by egorbeliy** [DefectDojo/django-DefectDojo#9911]
**Scanner Name**
Yarn audit v2+
yarn npm audit --json -R -A
https://yarnpkg.com/cli/npm/audit

**Comment by kiblik** [comment]
Can you provide an example report file, please?

**Comment by egorbeliy** [comment]
Sample of logs:

{"value":"@babel/plugin-proposal-class-properties","children":{"ID":"@babel/plugin-proposal-class-properties (deprecation)","Issue":"This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.","Severity":"moderate","Vulnerable Versions":"7.18.6","Tree Versions":["7.18.6"],"Dependents":["jscodeshift@virtual:95986a29f66ea5c154da709639e46d9f25ab769cdc542a6076b371e193f79e407bbee37bc9d3845bfa503bd700408966c85b5a74356facf4da9a113fd4ce89d9#npm:0.14.0"]}}
{"value":"@babel/plugin-proposal-nullish-coalescing-operator","children":{"ID":"@babel/plugin-proposal-nullish-coalescing-operator (deprecation)","Issue":"This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.","Severity":"moderate","Vulnerable Versions":"7.18.6","Tree Versions":["7.18.6"],"Dependents":["jscodeshift@virtual:95986a29f66ea5c154da709639e46d9f25ab769cdc542a6076b371e193f79e407bbee37bc9d3845bfa503bd700408966c85b5a74356facf4da9a113fd4ce89d9#npm:0.14.0"]}}
{"value":"@babel/plugin-proposal-optional-chaining","children":{"ID":"@babel/plugin-proposal-optional-chaining (deprecation)","Issue":"This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.","Severity":"moderate","Vulnerable Versions":"7.21.0","Tree Versions":["7.21.0"],"Dependents":["jscodeshift@virtual:95986a29f66ea5c154da709639e46d9f25ab769cdc542a6076b371e193f79e407bbee37bc9d3845bfa503bd700408966c85b5a74356facf4da9a113fd4ce89d9#npm:0.14.0"]}}

**Comment by egorbeliy** [comment]
hi @manuel-sommer @kiblik , what do you think about it?

**Comment by kiblik** [comment]
Hi @egorbeliy. Yes, the report file is usable (contains many useful parameters).
If you need to ASAP, please check
- https://github.com/DefectDojo/django-DefectDojo/blob/master/readme-docs/CONTRIBUTING.md
- https://documentation.defectdojo.com/contributing/how-to-write-a-parser/

and feel free to implement it. Unfortunately, I do not have the capacity to work on it now.

**Comment by manuel-sommer** [comment]
Hi @egorbeliy, if you wait maybe around a week, I might have the capacity to work on it

**Comment by manuel-sommer** [comment]
Done @egorbeliy , take a look at the PR

**Comment by manuel-sommer** [comment]
Can we close this @mtesauro as this was merged in the last release?
