### ISSUE TITLE
Forbidden (403) CSRF verification failed. Request aborted. (Deploying Defect Dojo using Helm Chart In AKS Cluster) 

### ISSUE THREAD

**Issue by vivekkontham** [DefectDojo/django-DefectDojo#9964]

**Comment by vivekkontham** [comment]
Hi @kiblik , 

I would like to thank for the quick response , 

I have Also Tried adding  prefix DD_ to both the variables but still we are facing the same issue While accessing the application. 

Yes the page is Not secure as we haven't attached any Certificate for secure connection as of now .


![image](https://github.com/DefectDojo/django-DefectDojo/assets/145244132/cd4ef71c-615b-4a6c-bc6c-3a7939e07457)

**Comment by kiblik** [comment]
Not secure connection might not be compatible with secure cookie. So until you will not enable HTTPS, set `DD_CSRF_COOKIE_SECURE` to false.

**Comment by vivekkontham** [comment]
Hi @kiblik , 

I have tried changing it but after changing we are not able to login , I have made another one change by adding below variable to false and it started working .
**- name: DD_SESSION_COOKIE_SECURE
value: "False"**

But now we are facing another issue were pod is currently getting restarted below is the error we tried to find from the logs

>  nginx 2024/04/22 07:37:12 [error] 10#10: *5029 connect() to unix:///run/defectdojo/uwsgi.sock failed (111: Connection refused) while connecting to upstrea │
> │ m, client: 10.224.0.6, server: , request: "GET /alerts/count HTTP/1.1", upstream: "uwsgi://unix:///run/defectdojo/uwsgi.sock:", host: "XX.XX.XX", r │
> │ eferrer: "http://XX.XX.XX/user/add"                                                                                                                 │
> │ nginx 10.224.0.6 - - [22/Apr/2024:07:37:12 +0000] "GET /alerts/count HTTP/1.1" 502 497 "http://XX.XX.XX/user/add" "Mozilla/5.0 (Windows NT 10.0; Wi │
> │ n64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"                                                                       │
> │ nginx 2024/04/22 07:37:12 [error] 10#10: *5031 connect() to unix:///run/defectdojo/uwsgi.sock

**Comment by kiblik** [comment]
Nginx is not able to contact uwsgi but from your logs is not possible to identify why.
